### ISSUE TITLE
We want donate and hope keep updating

### ISSUE THREAD

**Issue by johnwatsondev** [v2ray/v2ray-core#10]
I'm a general programmer in China Mainland. 
I used both [lantern](https://github.com/getlantern/lantern) (instable after 2.0.2) and [云梯](https://www.ttincloud.com) (responsive and responsible) .
<img width="290" alt="qq20150914-2" src="https://cloud.githubusercontent.com/assets/12760754/9846675/40505b3a-5b06-11e5-8d49-08720c59b367.png">
In fact i also used [红杏](http://www.hongxingchajian.com) (really suck).
<img width="430" alt="qq20150914-1" src="https://cloud.githubusercontent.com/assets/12760754/9846491/03e639d6-5b05-11e5-9a3d-56832959e13e.png">
I'm not care about the money but the attitude! What a fu*king company?

I believe a lot of person need stable ladder like v2ray. So i appeal to donate v2ray and hope keep updating as far as possible.

What about this advice ?@v2ray

**Comment by hdstar2009** [comment]
楼上红杏等东西是免费用吗?如果不免费的话，何必呢，自己买个vps建个ss server，自用绰绰有余了。

2015-09-14 17:32 GMT+08:00 JohnWatsonDev <notifications@github.com>:

**Comment by v2ray** [comment]
Donation is definitely a good way to keep me motivated. However, this project is still at its early state. Donation is not a high priority issue compared with other usability ones. I will consider it once Version 1.0 is released.

**Comment by johnwatsondev** [comment]
Yea! I hope v2ray will enough stable.

**Comment by v2ray** [comment]
Well. Found an easier way than using Bitcoin. You may send Amazon Gift Card to donate@v2ray.com, although I don't think the project is good enough at the moment for donation.
