### ISSUE TITLE
Only listen ipv6 port

### ISSUE THREAD

**Issue by Benyjuice** [v2ray/v2ray-core#100]
I have a digitalocean vps with ipv6 enabled. V2ray only listen the ipv6 port.

**Comment by v2ray** [comment]
What OS/version are you running on the VPS?

Could you run the following command to see the detail of ports that V2Ray is listening on?
> netstat -anp

**Comment by btstream** [comment]
I met this problem too. 

Linode VPS on archlinux with latest Arch's kernel

**Comment by btstream** [comment]
here is my config.json fle
```json
{
  "port": 32767,
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "info"
  },
  "inbound": {
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "xxx", // hidden :)
          "level": 1,
          "alterId": 64
        }
      ]
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}
```

**Comment by Benyjuice** [comment]
Both debian 7 and ubuntu 14.04 test. Here is my netstat -anp results:
`
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:27676           0.0.0.0:*               LISTEN      370/sshd        
tcp6       0      0 :::27676                :::*                    LISTEN      370/sshd        
tcp6       0      0 :::10721                :::*                    LISTEN      402/v2ray       
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path
unix  2      [ ACC ]     STREAM     LISTENING     827047557 1/init              @/com/ubuntu/upstart
unix  2      [ ACC ]     SEQPACKET  LISTENING     827048039 139/systemd-udevd   /run/udev/control
unix  3      [ ]         STREAM     CONNECTED     827048401 1/init              @/com/ubuntu/upstart
unix  3      [ ]         STREAM     CONNECTED     827048356 241/upstart-file-br 
unix  3      [ ]         STREAM     CONNECTED     827048350 1/init              @/com/ubuntu/upstart
unix  3      [ ]         STREAM     CONNECTED     827048267 240/upstart-socket- 
unix  3      [ ]         DGRAM                    827048073 139/systemd-udevd   
unix  3      [ ]         DGRAM                    827048072 139/systemd-udevd   
`

**Comment by btstream** [comment]
I tried debian 8.1, still problem

**Comment by v2ray** [comment]
@Benyjuice @btstream It seems that if the server has only one network interface with both IPv4 and IPv6 addresses, netstat shows only IPv6 port being listened.

However, V2Ray **does** listen on both stacks. You can confirm this by connecting to the IPv4 address through V2Ray client.

If it doesn't work, could you please share your SSH account to the server, so that I do more test on it?

**Comment by v2ray** [comment]
Please also check the following settings on your server:
> net.ipv6.bindv6only

by
> sysctl -a | grep bindv6only

The value should be zero, otherwise Golang will prefer system default to listen on IPv6 only.

**Comment by Benyjuice** [comment]
It does listen both ipv4 and ipv6 address. I successed to connect via ipv4 address. Many thanks!

**Comment by muziling** [comment]
openwrt也不监听IPV4了。
