### ISSUE TITLE
go get -u 命令下载ext的源码，提示太多错误了

### ISSUE THREAD

**Issue by 523860169** [v2ray/v2ray-core#1002]
![default](https://user-images.githubusercontent.com/6436073/38086235-2a2d20a8-3386-11e8-9750-f05aaaf8cddf.PNG)
对编译是否有影响?

**Comment by Yaspee** [comment]
你需要 golang 1.10。

**Comment by wongsyrone** [comment]
我用golang 1.10 windows amd64版本编译也是这个

**Comment by 523860169** [comment]
@Yaspee 
![default](https://user-images.githubusercontent.com/6436073/38087210-e1e9f862-3389-11e8-9855-45aed8730615.PNG)

**Comment by Yaspee** [comment]
![img_20180329_200044_899](https://user-images.githubusercontent.com/34875338/38087764-ee6eea00-338b-11e8-9532-937553de231e.jpg)

我在自己的 Linux amd64 机器上测试并没有问题。

有可能是平台不同的原因？

**Comment by DarienRaymond** [comment]
已修。这个目录暂时没什么用，你可以只 `go get` 你需要的目录，比如 `"v2ray.com/ext/tools/conf"`。

另外这个issue可以在ext下面提。
