### ISSUE TITLE
几个小建议！

### ISSUE THREAD

**Issue by Steve789** [v2ray/v2ray-core#1004]
1.更新日志指向官网，而官网没更新！希望及时更新或者github更新。
2."www.v2ray.com"内容过于繁琐，配置指南的内容和https://toutyrater.github.io/重复了，而且似乎后者的做得更好。
3.希望官网重点显示工作机制，版本日志，授权，捐赠，开发等一些内容。

**Comment by caonimac** [comment]
没有好好读字，哈哈哈。

**Comment by Steve789** [comment]
@caonimac 你说的字是指日常bug修复吗？包括“修复一些问题”我觉得还是写清楚问题为好。另外官网确实太长，不太好用。
