### ISSUE TITLE
看来国内还没有一个可以支持ws的CDN啊

### ISSUE THREAD

**Issue by SnorlaxYum** [v2ray/v2ray-core#1007]
用同样CF能奏效的配置尝试了又拍、腾讯，
腾讯的会导致Secure Connection Failed，客户端服务端无任何错误
又拍云的话，客户端错误
```
[Warning] failed to handler mux client connection > Proxy|VMess|Outbound: failed to find an available destination > Retry: [Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://网址/path): 400 Bad Request > websocket: bad handshake] > Retry: all retry attempts failed
```
直接访问反代路径也是正常显示“Bad Request”，不过好像访问起来还是CF快些
看来目前WS套CDN还是CF了～

**Comment by gbmeco** [comment]
除了Cloudflare国外还有什么CDN是 支持WS套的吗？

**Comment by caonimac** [comment]
中国电信，cf可以秒开youtube1080p

**Comment by SnorlaxYum** [comment]
今天测试用了一下百度云加速，表示其实和CF套速度差别不大（速度有折扣），有时还会400错误，大概就是因为ws本身性能没那么好～换回了TLS+H2

**Comment by SnorlaxYum** [comment]
@gbmeco CF算相当实惠了～在实惠的范围内，它算是不错～

**Comment by SnorlaxYum** [comment]
@caonimac 通过youtube的Stats for nerds，TLS+H2在手机热点上看YOUTUBE的8K峰值是3G左右的速度，CDN套峰值1.8G左右= =够用是够用，说明WS还是会打折扣

**Comment by caonimac** [comment]
@SnorlaxYum cdn是不是不能h2啊？想没有成功。

**Comment by SnorlaxYum** [comment]
@caonimac Nginx反代可以设置吧，不过还是不如原生TLS+H2来的快

**Comment by VictoriaRaymond** [comment]
不属于V2Ray的问题

**Comment by Jay54520** [comment]
@SnorlaxYum 
![image](https://user-images.githubusercontent.com/13315364/58702568-b0915580-83d8-11e9-9036-e3cc28d22b94.png)
https://common-buy.aliyun.com/

**Comment by SnorlaxYum** [comment]
> @SnorlaxYum
> ![image](https://user-images.githubusercontent.com/13315364/58702568-b0915580-83d8-11e9-9036-e3cc28d22b94.png)
> https://common-buy.aliyun.com/

土豪

**Comment by wysnxzm** [comment]
2019年7月10日 14:42:45 CF不支持h2,ws太慢,还是tls+http2快

**Comment by joveqiao** [comment]
@wysnxzm 怎么开http2?

**Comment by adamgonglj** [comment]
> 中国电信，cf可以秒开youtube1080p

4K都可以秒开。

**Comment by ttsunboy** [comment]
又拍上线了WS，按使用流量计费，价格不错，但似乎没有那么稳定，偶尔会没反应

**Comment by socalledPF** [comment]
> @caonimac 通过youtube的Stats for nerds，TLS+H2在手机热点上看YOUTUBE的8K峰值是3G左右的速度，CDN套峰值1.8G左右= =够用是够用，说明WS还是会打折扣

大佬 tls+h2 如何用cdn中转呢

**Comment by frank-pian** [comment]
> 
> 
> > @caonimac 通过youtube的Stats for nerds，TLS+H2在手机热点上看YOUTUBE的8K峰值是3G左右的速度，CDN套峰值1.8G左右= =够用是够用，说明WS还是会打折扣
> 
> 大佬 tls+h2 如何用cdn中转呢

同问，HTTP2+tls都搞通了，上了nodecache的CDN，就不行了，证书也配置了，https也强制打开了
