### ISSUE TITLE
请教大神：不知大神可否加入UDP伪装成TCP的功能？

### ISSUE THREAD

**Issue by mzxwt** [v2ray/v2ray-core#1009]
万恶的校园网！UDP被封，mKCP被废了！看到GitHub上有这个项目udp2raw-tunnel。突发奇想，问一个十分弱智的问题：mKCP是否可以利用这种方法绕过UDP封锁达到双边加速的目的？
期待大神指教！

**Comment by VictoriaRaymond** [comment]
暂时没有这个计划。V2Ray不会考虑在TCP上的重新造轮子。

**Comment by Cwek** [comment]
输出用Socks5？Socks5有UDP报文支持。

**Comment by Justsoos** [comment]
既然你是学生党，……  天赋没点加钱其他能力自然提升…… 自己装个 udp2raw 也不难，那个作者也非常 nice 的，有问题都肯帮忙。
