### ISSUE TITLE
关于ip限速

### ISSUE THREAD

**Issue by pjomvndy** [v2ray/v2ray-core#1022]
我搭建的v2ray账号想分享给朋友使用，但考虑到流量问题，想对连接v2ray服务器的ip进行限速，比如单个ip限速300kb/s，请问能做到吗？

**Comment by DarienRaymond** [comment]
https://www.google.ch/search?q=ip%E9%99%90%E9%80%9F+iptables&oq=ip%E9%99%90%E9%80%9F+iptables&aqs=chrome..69i57j0.4292j0j7&sourceid=chrome&ie=UTF-8
