### ISSUE TITLE
https://install.direct/go.sh有发现一个BUG

### ISSUE THREAD

**Issue by hiboyhiboy** [v2ray/v2ray-core#1023]
```
    if [ -n `command -v apt-get` ];then
        CMD_INSTALL="apt-get -y -qq install"
        CMD_UPDATE="apt-get -qq update"
    elif [[ -n `command -v yum` ]]; then
        CMD_INSTALL="yum -y -q install"
        CMD_UPDATE="yum -q makecache"
    else
        return 1
    fi
    return 0
```
少了个括号，修复：if [[ -n `command -v apt-get` ]];then

**Comment by DarienRaymond** [comment]
在上述情况下，`[` 和 `[[` 的效果是一样的。https://stackoverflow.com/questions/669452/is-double-square-brackets-preferable-over-single-square-brackets-in-ba

**Comment by hiboyhiboy** [comment]
a=""
if [ -n $a ];then
echo 111
fi
if [ -n "$a" ]; then
echo 222
fi
if [[ -n $a ]];then
echo 333
fi
if [[ -n "$a" ]]; then
echo 444
fi
但是这里的参数`command -v apt-get`漏了双引号，所以要[[

**Comment by sunshineplan** [comment]
今天也碰到一个类似的问题，用"["命令的-n参数，如果后面一个变量是空的话，这个变量一定要加上双引号，否则会测试通过。
不加双引号测试空字符的命令相当于
root@test:~#  [ -n ] && echo 1
1
加双引号测试空字符的命令相当于
root@test:~#  [ -n "" ] && echo 1
root@test:~#
所以这里如果使用"["的话，在命令外面套个双引号也是可以的
https://unix.stackexchange.com/questions/65624/why-do-i-need-to-quote-variable-for-if-but-not-for-echo
