### ISSUE TITLE
Docker image未同步更新，why?

### ISSUE THREAD

**Issue by LYU-Daliang** [v2ray/v2ray-core#1027]
如题。

**Comment by nicholascw** [comment]
https://github.com/v2ray/v2ray-core/blob/master/LICENSE

**Comment by DarienRaymond** [comment]
Docker hub shows the build is 'queued' for 5 days. Basically we can do nothing but wait.

**Comment by LYU-Daliang** [comment]
I am sorry to hear that. Hope it get through soon. I have been used to running v2ray in a multi-container manner.
