### ISSUE TITLE
UDP转发存在漏洞

### ISSUE THREAD

**Issue by FH0** [v2ray/v2ray-core#1029]
@korzonek 
部分UDP流量不转发，或者说游戏的UDP流量不转发

我做了对比实验，使用dokodemo-door和socks

结果是dokodemo-door只能转发部分udp流量，而我用redsocks2把udp流量转换成socks之后再发往socks端口，完美转发

如果需要日志的话我在下面粘贴出来

**Comment by Cwek** [comment]
先按提交标准上配置和日志吧

**Comment by FH0** [comment]
先暂时用着redsocks2吧，我看v2rayng也是用的tun2socks
