### ISSUE TITLE
公司内网问题

### ISSUE THREAD

**Issue by zhaxg** [v2ray/v2ray-core#1030]
一模一样的配置，服务器和客户端，在家里一切正常；
在公司里面就不行，公司有网康的防火墙吧，但公司并没有封外网线路，只是各种屏蔽。
但是shadowsocks工具（非v2ray的ss协议）在家和在公司都可以。
底层有什么差异？不应该能监测到v2ray而监测不出ss啊？

**Comment by nicholascw** [comment]
Invalid Issue

**Comment by notomatoes** [comment]
解决了吗请教下
