### ISSUE TITLE
关于手动安装--local

### ISSUE THREAD

**Issue by dnvcupid** [v2ray/v2ray-core#1031]
go.sh 参数
go.sh 支持如下参数，可在手动安装时根据实际情况调整：

-p 或 --proxy: 使用代理服务器来下载 V2Ray 的文件，格式与 curl 接受的参数一致，比如 "socks5://127.0.0.1:1080" 或 "http://127.0.0.1:3128"。
-f 或 --force: 强制安装。在默认情况下，如果当前系统中已有最新版本的 V2Ray，go.sh 会在检测之后就退出。如果需要强制重装一遍，则需要指定该参数。
--version: 指定需要安装的版本，比如 "v1.13"。默认值为最新版本。
--local: 使用一个本地文件进行安装。如果你已经下载了某个版本的 V2Ray，则可通过这个参数指定一个文件路径来进行安装。
示例：

使用地址为 127.0.0.1:1080 的 SOCKS 代理下载并安装最新版本：./go.sh -p socks5://127.0.0.1:1080
安装本地的 v1.13 版本：./go.sh --version v1.13 --local /path/to/v2ray.zip

梅林路由器，sh ./go.sh --local v2ray.zip 卡住不动，手动安装前需要什么组件？

**Comment by ToutyRater** [comment]
https://v2ray.com/chapter_00/install.html#linuxscript
你这梅林能满足带 Systemd 或是 Debian/Ubuntu 系列这两个条件之一吗

**Comment by dnvcupid** [comment]
@ToutyRater 都不满足需要怎么装吗

**Comment by InoriHeart** [comment]
解压

readme.md 里面写着怎么用

### Linux

压缩包中包含多个配置文件，按需使用。

可执行程序为 v2ray，启动命令：

```bash
v2ray --config=<full path>
```
