### ISSUE TITLE
多实例的 systemd 文件

### ISSUE THREAD

**Issue by InoriHeart** [v2ray/v2ray-core#1032]
标题不知道应该叫什么了

https://git.archlinux.org/svntogit/community.git/tree/trunk/v2ray.service?h=packages/v2ray

官方有没有意向考虑加上

**Comment by InoriHeart** [comment]
嗯，就是如果有人需要运行多个客户端的话
应该会用上这个文件

**Comment by DarienRaymond** [comment]
官方的就不改了，有需求的同学自己写配置文件吧。

参考： https://fedoramagazine.org/systemd-template-unit-files/
