### ISSUE TITLE
[建议]能否增加对非客户端的请求做反向代理？

### ISSUE THREAD

**Issue by lanybass** [v2ray/v2ray-core#1033]
即 区分普通http请求和客户端代理请求，普通请求走反向代理，客户端请求正常代理。
SSR和goflyway中有这项功能，当其他人使用浏览器直接访问我的代理端口时，给他返回一个指定页面来迷惑他，让他以为这是个普通WEB端口。

**Comment by DarienRaymond** [comment]
请使用 nginx 或其它工具做分流，然后将比如特定 websocket 的流量分发给 v2ray。v2ray 中不会支持类似功能。
