### ISSUE TITLE
公司、企业该如何设计翻墙方案？

### ISSUE THREAD

**Issue by benhon2008** [v2ray/v2ray-core#104]
公司由于业务涉外，需常用Google及一些墙外服务。安全起见，不让终端用户直连墙外服务器，都是通过墙内的服务器来中转。墙内服务器位于青岛机房，出境线路为C2C和TPE，墙外服务器位于加州、日本、新加坡。员工大多没有计算机操作基础知识，为了简化终端的设置，并且照顾移动设备，都是使用在线pac脚本，脚本内置自定义白黑名单，来实现按需分流，简易拓扑结构如图示：

![net](https://cloud.githubusercontent.com/assets/12547424/13554785/1147bf80-e3ec-11e5-97ac-a6154c7253d0.png)

现在有两个问题，望指教：
1. vmess协议动态端口接入功能，会有额外的开销（性能、带宽）吗？现象比如带宽利用率低，经常不满载；
2. 按现在的使用场景，在保证墙外服务器地址安全的前提下，有没有更科学的拓扑结构或者配置方案来提升带宽利用率；

**Comment by benhon2008** [comment]
有没有一种可能，例如，墙内中转服务器A(或是正常的运营商出口)，墙外实际代理服务器B。体制内的软件像BAT数字娱乐之流（公司虽命令禁止，但大多数员工会私自安装），会同时监控你墙内与墙外出口公网地址，一旦发现不一样（知道用户在翻墙）就(ISP、GFW)收录下。虽说拿vmess没办法，但只要是对B的流量就干扰、限速甚至断流。

如果真有这样的模式的话，在服务器B的“后端”再桥接一台服务器C（带公网出口），把B、C放到私有云里互联，减少网络性能销，这样可以防范吗？

**Comment by v2ray** [comment]
1. 理论上动态端口不会比固定端口性能差，服务器端会有额外的内存开销，但在内存足够的情况下，不会有性能问题；
2. 你可以在中转服务器 A 上使用 V2Ray 的[路由功能](https://www.v2ray.com/zh_cn/chapter_02/03_routing.html)，把墙内流量从服务器 A 直接发出，不经过服务器 B。V2Ray 已经内置了一些常见国内的网站，可以作为路由使用。

**Comment by nxtreaming** [comment]
根据我的经验， 提高带宽利用率是个伪命题，除非你们公司的业务是视频类非常耗带宽的类型，否则完全不需要关心带宽的利用率，因为绝大部分情况下你连10%的带宽/流量配额都用不掉。

**Comment by benhon2008** [comment]
谢谢作者你的回复，非常感谢作者提供了一款这么“便捷、安全”的工具给大家，我是名运维（并不是开发/Coder），V2Ray给了我想要的功能，再也不用装好几款程序组合、配置调调调了……各种进出流量一个工具全搞定。

还有几个问题：
1. dokodemo-door 适合做反向代理吗？
2. 终端到中转服务器间，http还是socks5合适？
3. 路由功能里内置的chinaip与chinasites，是初次安装V2Ray时生成，还是每次启动时都会重新生成？
4. 路由功能里内置的chinasites未来会考虑支持gfwlist吗?

**Comment by v2ray** [comment]
@benhon2008 
1. 不适合，反向代理通常需要修改 HTTP 头，而 dokodemo-door 不具备这个能力。相应的功能之后会做在 HTTP 里面。
2. 目前 SOCKS5 比 HTTP 性能好，HTTP 暂时不支持连接复用，而 SOCKS 可由浏览器选择性支持；
3. [chinaip](https://github.com/v2ray/v2ray-core/blob/master/app/router/rules/chinaip.go) 和 [chinasites](https://github.com/v2ray/v2ray-core/blob/master/app/router/rules/chinasites.go) 都是固定的列表，编译时就生成。如果你有需求可以提交 PR。Chinasites 的代码应该很好理解。
4. 我个人对 gfwlist 兴趣不高，因为这不是一个有据可循的列表，维护成本略高，不过欢迎 PR。如果你公司有特殊的需要，可以在 V2Ray 的配置文件中指定需要中转的网站列表。

**Comment by benhon2008** [comment]
@v2ray 了解。再次感谢！
