### ISSUE TITLE
做了一个V2RAY的Laucnher很方便，图标非常美观哦。

### ISSUE THREAD

**Issue by becapital** [v2ray/v2ray-core#1042]
做了一个V2RAY的Laucnher....放在你下载的客户端文件夹内，就直接启动V2RAY.EXE....很方便，图标非常美观哦。

链接: https://pan.baidu.com/s/1s73-Ydvv2X-uNDHzI6BUjQ 密码: sj5k

**Comment by DarienRaymond** [comment]
No ads please.
