### ISSUE TITLE
路由器安装v2ray后ddns服务器访问规则

### ISSUE THREAD

**Issue by dnvcupid** [v2ray/v2ray-core#1044]
有没有人在路由安装了v2ray同时又有使用ddns服务的，想问一下规则要怎么写，家里有个群晖之前是用`http://www.xxx.com:5000`这样外网访问的，路由上装了v2ray后，这样就无法访问了

**Comment by gsh199449** [comment]
我也遇到了这个问题，我猜原因是群辉的ddns走了v2ray的代理，导致群辉的域名解析到了v2ray的ip。所以只要把群辉的ddns的域名写进直连列表就行。但是怎么知道群辉ddns的域名是什么呢？请问你是怎么解决的？

**Comment by 1989car** [comment]
"checkip.synology.com",
"checkipv6.synology.com",
"checkport.synology.com",
"ddns.synology.com",
"account.synology.com",
"quickconnect.to",
"dyndns.org",
