### ISSUE TITLE
Caddy无法转发来自v2ray-core的HTTP/2请求

### ISSUE THREAD

**Issue by chnliupu** [v2ray/v2ray-core#1048]
**客户端配置**

> "outbound": {
    "tag": "agentout",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "******",  **NOT www.example.com**
          "port": 443,
          "users": [
            {
              "id": "******",
              "alterId": 64,
              "security": "aes-128-gcm"
            }
          ]
        }
      ],
      "servers": null
    },
    "streamSettings": {
      "network": "h2",
      "security": "tls",
      "httpSettings": {
        "path": "/victoria/"
      }
    },

**Caddy报错**
`[INFO] www.example.com - No such site at :443`

**服务端日志无连接记录，证明caddy无法转发该请求**

**Comment by DarienRaymond** [comment]
请在配置中添加 `host` 项，参见：https://www.v2ray.com/chapter_02/transport/h2.html

另外请按模板提交issue

**Comment by chnliupu** [comment]
添加host项后，status出现如下输出
![photo_2018-04-13_21-53-35](https://user-images.githubusercontent.com/17331680/38738865-d22a4dcc-3f65-11e8-9866-fe2d9815094c.jpg)

**Comment by DarienRaymond** [comment]
如果你的caddy配置中转发地址是IP，如127.0.0.1，则需要添加`insecure_skip_verify`选项，详见：https://github.com/mholt/caddy/issues/1657

**Comment by chnliupu** [comment]
原有的参数是
`header_upstream Host "HOST.domain" 
    header_upstream X-Forwarded-Proto "https"`
实现服务端、客户端、caddy无任何报错，access和error的日志均无连接记录，无法代理上网
------------
添加`insecure_skip_verify`后
caddy status输出` -0400 [ERROR 502 /victoria/] client disconnected`和`-0400 [ERROR 502 /victoria/] context canceled`
其余一致，均无报错，仍无法代理上网
--------------
同一服务器下的caddy+ws+web+tls无问题，可排除Caddyfile、证书、config存在错误的可能。

**Comment by 523860169** [comment]
caddy配置不能加gzip
