### ISSUE TITLE
[help wanted]路由中转功能未开启[附config.json]

### ISSUE THREAD

**Issue by benhon2008** [v2ray/v2ray-core#105]
按照官方文档说明，准备启用中转功能。
http/socks5进来，按需以vmess、或者直连出去，但是设置改了好几遍，流量出来还是全局到代理服务器，大家帮忙看下是不是配置文件内容写得不对。

另外，在使用固定端口时，看油管视频加载都是一撸到底；
配置动态端口时，则会偶尔会缓冲，所以决定把配置都换成了固定端口。

官方文档提到动态端口功能是为了防止ISP针对用户大流量应用作限速设置，如果使用一些常见的端口号，如443、1433、1521、3306，可以减免这种情况的发生吗？还是说只要保持固定端口通讯，被“干扰”都是迟早的问题？

[config.txt](https://github.com/v2ray/v2ray-core/files/163708/config.txt)

**Comment by v2ray** [comment]
你的配置没错，目前 V2Ray 还不支持 DNS 解析，如果客户端发来的是域名，比如连接 10086.cn，chinaip 是不启作用的。于是 10086.cn 还是会被发到代理服务器去。

DNS 解析的功能正在制作中……

干扰的问题视 ISP 不同而不同，没有定论。据说当一个端口的流量过大时，部分 ISP 会进行限速。至于那些常用端口，80 和 443 之类，并没有详细评测。如果你的 ISP 不进行任何的限速，那么用一个固定端口也是可以的。

**Comment by benhon2008** [comment]
@v2ray 意思是中转服务器的v2ray分流功能暂时还没上线是吗？（不分http/socks5）
