### ISSUE TITLE
Suspicion man in the middle-attack when browse google

### ISSUE THREAD

**Issue by 10people** [v2ray/v2ray-core#1058]
English:
Please read the [instruction](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md) and answer the following questions before submitting your issue. Thank you.
Please answer all the questions with enough information. All issues not following this template will be closed immediately.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
client v2ray-v3.14-windows-64
server 3.14 on ubuntu
2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
Browse google, twitter, youtube, etc via VMess in Beijing
3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)
Chrome display connection not secure warning, which shows CERT　NAME　ERROR,
**normal website not blocked by GFW is secure even browsed via v2ray, example: microsoft.com,
It seems they know which website I browsed**
4) What's your expectation?
Secure internet connection
5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Server configuration:
{
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 
    "protocol": 
    "settings": {
      "clients": [
        {
          "id":
          "level": 
          "alterId": 
        }
      ]
    },
    "streamSettings":{"network":"tcp","security":"none","tlsSettings":{"serverName":"v2ray.com","allowInsecure":false},"tcpSettings":{"connectionReuse":true,"header":{"type":"http"}},"kcpSettings":{"mtu":1350,"tti":20,"uplinkCapacity":5,"downlinkCapacity":100,"readBufferSize":1,"writeBufferSize":1,"congestion":false,"header":{"type":"none"}},"wsSettings":{"connectionReuse":false,"path":""}}
  },
  "inboundDetour": [
    {
"port":
    "protocol": 
    "settings": {
      "clients": [
        {
          "id": 
          "alterId":
        }
      ]
    },
    "streamSettings":{"network":"kcp","security":"none","tlsSettings":{"serverName":"v2ray.com","allowInsecure":false},"tcpSettings":{"connectionReuse":true,"header":{"type":"http"}},"kcpSettings":{"mtu":1350,"tti":20,"uplinkCapacity":5,"downlinkCapacity":100,"readBufferSize":1,"writeBufferSize":1,"congestion":false,"header":{"type":"none"}},"wsSettings":{"connectionReuse":false,"path":""}}
    },
    {
      "port": 
    "protocol": 
    "settings": {
      "clients": [
        {
          "id": 
          "alterId":
        }
      ]
    },
    "streamSettings":{"network":"ws","security":"none","tlsSettings":{"serverName":"v2ray.com","allowInsecure":false},"tcpSettings":{"connectionReuse":true,"header":{"type":"http"}},"kcpSettings":{"mtu":1350,"tti":20,"uplinkCapacity":5,"downlinkCapacity":100,"readBufferSize":1,"writeBufferSize":1,"congestion":false,"header":{"type":"none"}},"wsSettings":{"connectionReuse":false,"path":""}}
    }
  ],
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}

    Client configuration:
{
  "log": {
    "loglevel": "warning"
  },
  "inbound": {
    "port": 
    "protocol":
    "settings": {
      "auth": "noauth"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": 
          "port": 
          "users": [
            {
              "id": 
              "alterId": 
            }
          ]
        }
      ]
    },
    "streamSettings":{"network":"tcp","security":"none","tlsSettings":{"serverName":"v2ray.com","allowInsecure":false},"tcpSettings":{"connectionReuse":true,"header":{"type":"http"}},"kcpSettings":{"mtu":1350,"tti":20,"uplinkCapacity":5,"downlinkCapacity":100,"readBufferSize":1,"writeBufferSize":1,"congestion":false,"header":{"type":"none"}},"wsSettings":{"connectionReuse":false,"path":""}}
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        }
      ]
    }
  }
}

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.

No errors

7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.
```
    // Please attach your server access log here.
```

Please review your issue before submitting.

8) Other configurations (such as Nginx) and logs.

9) If V2Ray doesn't run, please attach output from `--test`.

The command is usually `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`, but may vary according to your scenario.

10) If V2Ray service doesn't run, please attach journal log.

Usual command is `journalctl -u v2ray`.

How do they make MITM for connection via v2ray

**Comment by DarienRaymond** [comment]
Usually this is caused by DNS pollution. Please use a secure DNS server, or use `domainOverride` in V2Ray's inbound. See https://www.v2ray.com/chapter_02/01_overview.html

**Comment by 10people** [comment]
Dns server is 8.8.8.8,8.8.4.4

**Comment by Bethannfrum** [comment]
Fix and restore to original format and release old documents
