### ISSUE TITLE
启动成功后无法访问youtube或者Facebook

### ISSUE THREAD

**Issue by jellybean4** [v2ray/v2ray-core#106]
配置之后不能访问youtube或者facebook，但是可以访问google。而且配置文件里没有对youtube和facebook进行限制，请问是怎么回事。

**Comment by Randy000** [comment]
dns污染太严重。

**Comment by cool5** [comment]
@Randy000 V2Ray的DNS好像是在本地完成的，而不是发送到远端

**Comment by v2ray** [comment]
猜测是 DNS 的问题，如果你用 SOCKS 协议，请确保浏览器把域名发给 V2Ray 而不是 IP。如下图， Remote DNS **要打勾**。

![image](https://cloud.githubusercontent.com/assets/14110142/13741634/984d8a78-e9d7-11e5-868d-1ec39fdb896c.png)

**Comment by Randy000** [comment]
@v2ray,你給的設置是firefox的。其他瀏覽器似乎沒有遠程dns這個設定。不過，今天chrome版本 49.0.2623.87 m (64-bit)+SwitchyOmega用v2ray竟然正常了。問題沒有再現。

**Comment by Jeffwhen** [comment]
有相似问题。
VPS：Ubuntu 14.04 x64；
Client：Windows 10 x64。
Google、Youtube工作正常。Facebook、Twitter无法打开。

**Comment by wenjinlibug** [comment]
试试dnscrypt，设置了dns为8.8.8.8也是没用的，因为dns请求无加密无验证。

**Comment by Misaka19090go** [comment]
google搜索正常油管无法完全打开

**Comment by jiqing112** [comment]
> Google搜索、Twitter正常，油管无法完全打开



> Google搜索、Twitter正常，油管无法完全打开

你好，请问问题有解决思路吗，我也遇到了类似的问题。socks5正常，就是YouTube经常断流。

**Comment by Misaka19090go** [comment]
> > Google搜索、Twitter正常，油管无法完全打开
> 
> 
> 
> > Google搜索、Twitter正常，油管无法完全打开
> 
> 你好，请问问题有解决思路吗，我也遇到了类似的问题。socks5正常，就是YouTube经常断流。
> 

还不知道解决方法，手机是这样，换电脑就没问题

**Comment by jiqing112** [comment]
> > > Google搜索、Twitter正常，油管无法完全打开
> > 
> > 
> > > Google搜索、Twitter正常，油管无法完全打开
> > 
> > 
> > 你好，请问问题有解决思路吗，我也遇到了类似的问题。socks5正常，就是YouTube经常断流。
> 
> 还不知道解决方法，手机是这样，换电脑就没问题

我是反过来，我电脑无法访问油管。我大概猜到是宽带的问题了。过几个月宽带到期换电信看看

**Comment by zyf-ncepu** [comment]
> Google搜索、Twitter正常，油管无法完全打开

我遇到了同样的问题，请问现在解决了吗？

**Comment by Rhantolk-Ytri** [comment]
解决了，但不知其所以然
