### ISSUE TITLE
v2ray配置多用户失败，只有第一个好用，不知道为什么？如图

### ISSUE THREAD

**Issue by ugvf2009** [v2ray/v2ray-core#1060]
v2ray 服务器和客户端版本都是3.18

客户端用的是v2rayN

配置图片如下，只有alterId:222的可以用。
![muser](https://user-images.githubusercontent.com/2819436/38906730-e87b337e-42ea-11e8-91a5-39a055682afd.png)

**Comment by cnperi** [comment]
明显少了个逗号。

**Comment by DarienRaymond** [comment]
如上。
