### ISSUE TITLE
升级到3.19后，配置文件里有两个邮箱相同的用户会导致Linux服务端无法启动。

### ISSUE THREAD

**Issue by hehongbo** [v2ray/v2ray-core#1067]
Please skip to the English section below if you don't write Chinese.

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
服务端：3.19（Linux amd64）
客户端：3.19（macOS，v2rayX手动更新了core）

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
在macOS上使用Chrome通过Socks/VMess/Websocket

3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
服务端Linux版本无法启动，--test提示User already exists，但是我用同一版本的二进制却没有问题。

4)  你期待看到的正确表现是怎样的？
服务端正常运行啊....😂

5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
（说明，两个clients字段各有6个UUID，其中有两个对应同一个邮箱，一个是我自己在家使用的，一个是我在公司使用的。其他4个都是朋友的。UUID和邮箱马赛克。）
```javascript
{
  "inbound": {
    "port": 6666,
    "listen": "127.0.0.1",
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "00000000-0000-0000-0000-000000000000",
          "email": "myemail@example.com"
        },
        {
          "id": "11111111-1111-1111-1111-111111111111",
          "email": "myemail@example.com"
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "wsSettings": {
        "path": "/my_websocket_path"
      }
    }
  },
  "inboundDetour": [
    {
      "protocol": "vmess",
      "port": 6669,
      "listen": "0.0.0.0",
      "tag": "kcp",
      "allocate": {
        "strategy": "always",
        "refresh": 5,
        "concurrency": 3
      },
      "settings": {
        "clients": [
          {
            "id": "00000000-0000-0000-0000-000000000000",
            "email": "myemail@example.com"
          },
          {
            "id": "11111111-1111-1111-1111-111111111111",
            "email": "myemail@example.com"
          }
        ]
      },
      "streamSettings": {
        "network": "kcp",
        "kcpSettings": {
          "mtu": 1200,
          "tti": 12,
          "uplinkCapacity": 24,
          "downlinkCapacity": 8,
          "congestion": true,
          "header": {
            "type": "none"
          }
        }
      }
    }
  ],
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  }
}
```

    客户端配置:
    用v2rayX，没管过客户端的配置文件。这个issue应该也与客户端无关。

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
    （真的没有任何输出啊，我调成debug都没有...我有哪点搞错了么？）

    客户端错误日志:
（这个issue应该跟客户端无关）

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
（也没有输出。）

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。
```
sudo /usr/bin/v2ray/v2ray ./config.json
V2Ray v3.19 (die Commanderin) 20180419
A unified platform for anti-censorship.
Main: failed to create server > Proxy|VMess|Inbound: failed to initiate user > Proxy|VMess|Inbound: User myemail@example.com already exists.
```
（此配置文件在linux上--test会报错，在macos上--test就通过，都是3.19）

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

**简要概括一下：3.18的时候正常，升级3.19后服务端原地无法启动，报错如上。我配置了两个UUID不一样，email一样的用户，用于分别在自己的设备和公司的设备上使用，3.19 Linux报错，而同一个配置文件3.19 macos通过，因此考虑是bug。改掉其中的一个email就顺利启动了。**

关于日志，我不知道是不是我操作有问题，配置文件里的日志路径无任何日志文件生成，我手动创建了日志文件并确认权限，亦无任何输出。还请指教。
![photo_2018-04-21_03-49-21](https://user-images.githubusercontent.com/665472/39070711-ff80fa30-4516-11e8-9aaa-ecb37159204a.jpg)

**Comment by TanNang** [comment]
> 配置文件里有两个邮箱相同的用户会导致Linux服务端无法启动
> myemail@example.com already exists. 


这是软件预期的行为，请参考 https://github.com/v2ray/v2ray-core/blob/9a8488074ea36561e72af010d85a704796723e24/proxy/vmess/inbound/inbound.go#L155

**Comment by VictoriaRaymond** [comment]
如上，同一个inbound内不支持重复email。
