### ISSUE TITLE
能否将动态端口的刷新间隔按秒设置

### ISSUE THREAD

**Issue by fengyuwujian** [v2ray/v2ray-core#107]
学校使用深信服进行网络限制，深信服会在TCP连接成功建立并开始数据传输的几秒钟内对连接进行阻断。如果重新建立TCP连接，即使在相同端口，也会重复上述过程。具体表现为使用Shadowsocks能够打开http协议传输的网页，但页面不完整，刷新亦是如此。故想请教能否将动态端口的刷新间隔设置为几秒，或能否以其他方式不断地建立新的TCP连接以达到能够正常传输数据包的目的。

**Comment by Sherman-Liu** [comment]
If you do that, there might be too much pressure for your servers.

**Comment by v2ray** [comment]
对于 TCP 来说没什么好的解决方案。现在有 [mKCP](https://www.v2ray.com/chapter_03/kcp.html) 了，是一个基于 UDP 的协议，能否试试看会不会被限制？
