### ISSUE TITLE
请问v2ray服务器端能降级回滚吗？

### ISSUE THREAD

**Issue by moonwater** [v2ray/v2ray-core#1071]

**Comment by moonwater** [comment]
自己找到答案了： 
`~/v2ray-core/release$ sudo  ./install-release.sh -c
Checking for update.
No new version. Current version is v3.21.

~/v2ray-core/release$ sudo  ./install-release.sh --version v3.20
Installing V2Ray v3.20 on x86_64
Downloading V2Ray.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   608    0   608    0     0    608      0 --:--:-- --:--:-- --:--:--   738
100 8690k  100 8690k    0     0  1086k      0  0:00:08  0:00:08 --:--:-- 1962k
Extracting V2Ray package to /tmp/v2ray.
Archive:  /tmp/v2ray/v2ray.zip
   creating: /tmp/v2ray/v2ray-v3.20-linux-64/
  inflating: /tmp/v2ray/v2ray-v3.20-linux-64/geoip.dat  
  inflating: /tmp/v2ray/v2ray-v3.20-linux-64/geosite.dat  
  inflating: /tmp/v2ray/v2ray-v3.20-linux-64/readme.md  
   creating: /tmp/v2ray/v2ray-v3.20-linux-64/systemd/
  inflating: /tmp/v2ray/v2ray-v3.20-linux-64/systemd/v2ray.service  
   creating: /tmp/v2ray/v2ray-v3.20-linux-64/systemv/
  inflating: /tmp/v2ray/v2ray-v3.20-linux-64/systemv/v2ray  
  inflating: /tmp/v2ray/v2ray-v3.20-linux-64/v2ctl  
 extracting: /tmp/v2ray/v2ray-v3.20-linux-64/v2ctl.sig  
  inflating: /tmp/v2ray/v2ray-v3.20-linux-64/v2ray  
 extracting: /tmp/v2ray/v2ray-v3.20-linux-64/v2ray.sig  
  inflating: /tmp/v2ray/v2ray-v3.20-linux-64/vpoint_socks_vmess.json  
  inflating: /tmp/v2ray/v2ray-v3.20-linux-64/vpoint_vmess_freedom.json  
Shutting down V2Ray service.
Restarting V2Ray service.
V2Ray v3.20 is installed.`

可是大部分的客户端还是不能连上回滚后的服务器了。
猜想V3.21有钓鱼的脏东西在里面。
想想办法去证明

**Comment by DarienRaymond** [comment]
请问你的配置和出错信息？
