### ISSUE TITLE
default里面写了alterId，是否还有必要在clients中写？

### ISSUE THREAD

**Issue by wanzhiyu** [v2ray/v2ray-core#1072]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
3.21
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
配置vmess协议时，我在default里面写了level和alterId，发现如果在clients中不写alterID，将无法正常使用。
4)  你期待看到的正确表现是怎样的？
只要在default里面写了level和alterId，就算在clients中不写alterID，也能使用我在default中设置的alterID。
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置（关键部分）:
"clients": [
    {
      "id": "27848739-7e62-4138-9fd3-098a63964b6b",
    //"level": 0,
    //"alterId": 32
      "email": "whatever"
    }
  ],
  "default": {
    "level": 0,
    "alterId": 32
  },

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
1、error.log
2018/04/24 07:58:06 [Warning] Core: V2Ray v3.21 started
2018/04/24 07:58:10 [Warning] Transport|Internet|WebSocket: failed to serve http for WebSocket > accept tcp [::]:10086: use of closed network connection
2、access.log
2018/04/24 07:58:07 127.0.0.1:35226 rejected  Proxy|VMess|Encoding: invalid user

**Comment by Chandler-Lu** [comment]
为啥要添一个default
![wx20180425-164318](https://user-images.githubusercontent.com/18322610/39235184-ce89ba22-48a7-11e8-94a4-d68851ac34bc.png)

**Comment by 523860169** [comment]
为了不用每个用户都要写那两行吧

**Comment by DarienRaymond** [comment]
Kamino closed and cloned this issue to v2ray/discussion
