### ISSUE TITLE
WebSocket模式下，数据传输异常

### ISSUE THREAD

**Issue by emengweb** [v2ray/v2ray-core#1077]
在下载或浏览大视频或文件的时候，如果关闭网页，或中断下载，虽然客户端app显示流量为0，单手机自身监控流量显示后台仍然在继续下载，且vps监控也显示数据依然在传输。会直至整个大文件传输完毕才会中断，这个bug导致手机在4g下偷跑了2个多G的流量啊，心在滴血。。。

目前手上的vps只在Adman.com的主机上可以重复必现此bug，其他主机皆无此问题。配置就是最简单的websocket标准配置，客户端使用安卓BifrostV，希望可以解决这个问题，辛苦了！

**Comment by 523860169** [comment]
不只ws，其实其他模式也是这样的

**Comment by ironpike** [comment]
好像大流量请求还会持续占用Mux链接，比如说我打算打开一个有好多巨大图片的网页，然后我后悔了把这个页面关掉。之后会有一段时间无法打开新网页，推测是不是后台仍然在下载这些图片，同时由于图片较多导致连接总数到达上限无法打开新网页？

**Comment by diocat** [comment]
那是因为你开了Mux，关了就没事了

**Comment by VictoriaRaymond** [comment]
Mux的问题会在4.4修复

**Comment by William96911** [comment]
现在还没修复

**Comment by xesax45410** [comment]
2020.06.18 v4.24.2版本问题复现，开启mux一直跑流量，不开启的话每个网页打开非常慢
