### ISSUE TITLE
可以国内路由走国内的代理而不是直连吗？

### ISSUE THREAD

**Issue by ljm000** [v2ray/v2ray-core#108]
我看了一下客户端里的config.json路由表，国内的路由是本地直连的。

我现在是想把国内路由走国内代理加速国内的访问，而不是直连。国外走国外代理。

请问该如何设置？:)

谢谢！

**Comment by v2ray** [comment]
如果你的国内代理用的也是 V2Ray 的话，把 config.json 中的 freedom 配置改成 vmess 即可。大概是这个样子：

```javascript
"outboundDetour": [
  {
    "protocol": "vmess", // 本来这里是 freedom
    "settings": {  // vmess 的配置，具体内容可参考文档，这里略过
    },
    "tag": "domestic"  // 标签，内容随意，和路由对应起来即可
  }
],
"routing": {
  "strategy": "rules",
  "settings": {
    "rules": [
      {
        "type": "chinasites",
        "outboundTag": "domestic" // 和上面的 tag 对应
      }
    ]
  }
}
```

**Comment by ljm000** [comment]
谢谢~

**Comment by sg7ye** [comment]
{            
  "inbounds": [
    {
      "port": 1080,
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
    },
      "settings": {
        "auth": "noauth"
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom", // 本来这里是 vmess因为在墙外使用回国模式要做到墙外直连墙内代理这个效果
      "settings": {},
  "outboundDetour": [
    {
      "protocol": "vmess", // 本来这里是 freedom
      "settings": 
        "vnext": [
          {
            "address": "XXX.XXX.XXX.XXX",
            "port": 5201,
            "users": [
              {
                "id": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
                "alterId": 64,
				"security": "auto"
              }
            ]
          },
          {
            "address": "XXX.XXX.XXX.XXX",
            "port": 5202,
            "users": [
              {
                "id": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
                "alterId": 64,
				"security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "mkcp",  //需要kcp模式降低延时
        "kcpSettings": {
          "uplinkCapacity": 100,    //我墙外宽带千兆，墙内有30兆，不知道这个数值对不对！
          "downlinkCapacity": 100,
          "congestion": true,
          "header": {
            "type": "none"
                }
            }
        },
        "mux": {
            "enabled": true
        },
      "tag": "Proxy" //如果要使用路由，这个 tag 是一定要有的，在这里 Proxy 就是 freedom 的一个标号，在路由中说 Proxy V2Ray 就知道是这里的 freedom 了
    }    
  ],
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "outboundTag": "Proxy",
        "domain": ["geosite:cn"] // 中国大陆主流网站的域名
      },
      {
        "type": "field",
        "outboundTag": "Proxy",
        "ip": [
          "geoip:cn", // 中国大陆的 IP
          "geoip:private" // 私有地址 IP，如路由器等
        ]
      }
    ]
  }
}                        //DNS配置不知道要不要写
