### ISSUE TITLE
[Help Request] Config file is a valid json but cannot run

### ISSUE THREAD

**Issue by kmahyyg** [v2ray/v2ray-core#1080]
Please skip to the English section below if you don't write Chinese.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

V3.21

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

正在配置服务端

3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

```
root@host:~/v2ray# ./v2ray --config ./v2rayserver.json --test
V2Ray v3.21 (die Commanderin) 20180423
A unified platform for anti-censorship.
Main: failed to read config file: ./v2rayserver.json > proto: can't skip unknown wire type 6 for core.Config
```

4)  你期待看到的正确表现是怎样的？

正常运行

5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:

请看 Comments 5

客户端配置:

暂未配置

请问配置文件哪里有问题？json is Valid.

**Comment by kmahyyg** [comment]
![image](https://user-images.githubusercontent.com/16604643/39420163-e3ec9a64-4c95-11e8-9e77-83454e2daf7c.png)

**Comment by rufengsuixing** [comment]
请检查一下你提交的issue配置
请好好读文档

**Comment by kmahyyg** [comment]
抱歉，剪贴板上的数据出了一点点问题，已更新

**Comment by peter-tank** [comment]
https://codebeautify.org/jsonviewer

层级都错了，inbound应该在outbound前结束。
