### ISSUE TITLE
流量统计信息在哪里看？

### ISSUE THREAD

**Issue by jjlizz** [v2ray/v2ray-core#1083]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
3.21

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
通过chrome看u2b，pixiv等

3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
按照手册设置发现无法找到流量统计有关信息

4)  你期待看到的正确表现是怎样的？
找到流量统计信息

5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
```javascript
{
    "log": {
        "access": "/var/log/v2ray/access.log",
        "error": "/var/log/v2ray/error.log",
        "loglevel": "warning"
    },
    "policy": {
        "levels": {
            "1": {
                "statsUserUplink": true,
                "statsUserDownlink": true
            }
        },
        "system": {
            "statsInboundUplink": true,
            "statsInboundDownlink": true
        }
    },
    "stats": {
    },
    "inbound": {
        "port": 1995,
        "listen": "127.0.0.1",
        "protocol": "vmess",
        "settings": {
            "udp": true,
            "clients": [
                {
                    "id": "xxxxxxxxxxxxxxx",
                    "level": 1,
                    "alterId": 233,
                    "email": "PC@163.com"
                }, 
                {
                    "id": "xxxxxxxxxxxxxxx",
                    "level": 1,
                    "alterId": 233,
                    "email": "phone@163.com"
                }
            ]
        },
        "streamSettings": {
            "network": "ws",
            "security": "auto",
            "wsSettings": {
                "connectionReuse": true,
                "path": "/ray"
            }
        },
        "tag": "Lee"
    },
    "outbound": {
        "protocol": "freedom",
        "settings": {}
    },
    "inboundDetour": [
    ],
    "outboundDetour": [
        {
            "protocol": "blackhole",
            "settings": {},
            "tag": "blocked"
        }
    ],
    "routing": {
        "strategy": "rules",
        "settings": {
            "rules": [
                {
                    "type": "field",
                    "ip": [
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "203.0.113.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10"
                    ],
                    "outboundTag": "blocked"
                }
            ]
        }
    }
}
```

    客户端配置:
```javascript
{
    "log": {
        "loglevel": "warning"
    },
    "inbound": {
        "listen": "127.0.0.1",
        "port": 1080,
        "protocol": "socks",
        "settings": {
            "auth": "noauth",
            "udp": true,
            "ip": "127.0.0.1"
        }
    },
    "outbound": {
        "protocol": "vmess",
        "settings": {
            "vnext": [
                {
                    "address": "xxxxxxxxx.com",
                    "port": 443,
                    "users": [
                        {
                            "id": "xxxxxxxxxxx",
                            "level": 1,
                            "alterId": 233
                        }
                    ]
                }
            ]
        },
        "mux": {
            "enabled": true,
            "concurrency": 8
        },
        "streamSettings": {
            "network": "ws",
            "security": "tls",
            "tlsSettings": {
                "serverName": "xxxxxxxx.com"
            },
            "wsSettings": {
                "path": "/ray"
            }
        }
    },
    "outboundDetour": [
        {
            "protocol": "freedom",
            "settings": {},
            "tag": "direct"
        }
    ],
    "routing": {
        "strategy": "rules",
        "settings": {
            "rules": [
                {
                    "type": "field",
                    "port": "54-79",
                    "outboundTag": "direct"
                },
                {
                    "type": "field",
                    "port": "81-442",
                    "outboundTag": "direct"
                },
                {
                    "type": "field",
                    "port": "444-65535",
                    "outboundTag": "direct"
                },
                {
                    "type": "field",
                    "domain": [
                        "gc.kis.scr.kaspersky-labs.com"
                    ],
                    "outboundTag": "direct"
                },
                {
                    "type": "field",
                    "ip": [
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "203.0.113.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10"
                    ],
                    "outboundTag": "direct"
                }
            ]
        }
    }
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
无

    客户端错误日志:
无

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
2018/05/01 07:34:32 tcp:127.0.0.1:59598 accepted tcp:yt3.ggpht.com:443 
2018/05/01 07:34:32 tcp:127.0.0.1:59598 accepted tcp:yt3.ggpht.com:443 
2018/05/01 07:34:32 tcp:127.0.0.1:59598 accepted tcp:yt3.ggpht.com:443 
2018/05/01 07:34:32 tcp:127.0.0.1:59598 accepted tcp:clients1.google.com:443 
2018/05/01 07:34:32 tcp:127.0.0.1:59598 accepted tcp:clients1.google.com:443 
2018/05/01 07:34:34 tcp:127.0.0.1:59612 accepted tcp:i.ytimg.com:443 
2018/05/01 07:34:34 tcp:127.0.0.1:59612 accepted tcp:i.ytimg.com:443 
2018/05/01 07:34:34 tcp:127.0.0.1:59612 accepted tcp:i.ytimg.com:443 
2018/05/01 07:34:34 tcp:127.0.0.1:59612 accepted tcp:s.ytimg.com:443 
2018/05/01 07:34:34 tcp:127.0.0.1:59612 accepted tcp:s.ytimg.com:443 
2018/05/01 07:34:34 tcp:127.0.0.1:59612 accepted tcp:i.ytimg.com:443 
2018/05/01 07:34:34 tcp:127.0.0.1:59612 accepted tcp:i.ytimg.com:443 
2018/05/01 07:34:34 tcp:127.0.0.1:59612 accepted tcp:i.ytimg.com:443 
2018/05/01 07:34:34 tcp:127.0.0.1:59600 accepted tcp:s.ytimg.com:443 
2018/05/01 07:34:34 tcp:127.0.0.1:59600 accepted tcp:www.youtube.com:443 
2018/05/01 07:34:34 tcp:127.0.0.1:59600 accepted tcp:s.ytimg.com:443 
2018/05/01 07:34:34 tcp:127.0.0.1:59600 accepted tcp:s.ytimg.com:443 
2018/05/01 07:34:34 tcp:127.0.0.1:59600 accepted tcp:yt3.ggpht.com:443 
2018/05/01 07:34:34 tcp:127.0.0.1:59600 accepted tcp:www.youtube.com:443 
2018/05/01 07:34:34 tcp:127.0.0.1:59600 accepted tcp:yt3.ggpht.com:443 
2018/05/01 07:34:34 tcp:127.0.0.1:59600 accepted tcp:yt3.ggpht.com:443 
2018/05/01 07:34:36 tcp:127.0.0.1:59646 accepted tcp:www.google.com:443 
2018/05/01 07:34:36 tcp:127.0.0.1:59646 accepted tcp:www.google.com:443 
2018/05/01 07:34:36 tcp:127.0.0.1:59646 accepted tcp:www.google.com:443 
2018/05/01 07:34:36 tcp:127.0.0.1:59646 accepted tcp:www.google.com:443 
2018/05/01 07:34:36 tcp:127.0.0.1:59646 accepted tcp:www.google.com:443 
2018/05/01 07:34:36 tcp:127.0.0.1:59646 accepted tcp:clients1.google.com:443 
2018/05/01 07:34:36 tcp:127.0.0.1:59646 accepted tcp:s.ytimg.com:443 
2018/05/01 07:34:36 tcp:127.0.0.1:59646 accepted tcp:www.youtube.com:443 
2018/05/01 07:34:39 tcp:127.0.0.1:59646 accepted tcp:s.ytimg.com:443 
2018/05/01 07:35:04 tcp:127.0.0.1:59646 accepted tcp:i.ytimg.com:443 
2018/05/01 07:35:04 tcp:127.0.0.1:59646 accepted tcp:clients5.google.com:443 
2018/05/01 07:35:04 tcp:127.0.0.1:59646 accepted tcp:ogs.google.com:443 
2018/05/01 07:35:04 tcp:127.0.0.1:59646 accepted tcp:mtalk.google.com:443 
2018/05/01 07:35:04 tcp:127.0.0.1:59646 accepted tcp:clients4.google.com:443 
2018/05/01 07:35:04 tcp:127.0.0.1:59646 accepted tcp:www.google.com:443 
2018/05/01 07:35:04 tcp:127.0.0.1:59646 accepted tcp:www.gstatic.com:443 
2018/05/01 07:35:05 tcp:127.0.0.1:59612 accepted tcp:i.ytimg.com:443 
2018/05/01 07:35:06 tcp:127.0.0.1:59612 accepted tcp:i.ytimg.com:443 
2018/05/01 07:35:06 tcp:127.0.0.1:59612 accepted tcp:i.ytimg.com:443 
2018/05/01 07:35:06 tcp:127.0.0.1:59612 accepted tcp:i.ytimg.com:443 
2018/05/01 07:35:06 tcp:127.0.0.1:59612 accepted tcp:clients4.google.com:443 
2018/05/01 07:35:06 tcp:127.0.0.1:59612 accepted tcp:www.google.com:443 
2018/05/01 07:35:06 tcp:127.0.0.1:59612 accepted tcp:www.google.com:443 
2018/05/01 07:35:10 tcp:127.0.0.1:59646 accepted tcp:www.google.com:443 
2018/05/01 07:35:10 tcp:127.0.0.1:59646 accepted tcp:clients4.google.com:443 
2018/05/01 07:35:11 tcp:127.0.0.1:59646 accepted tcp:clients5.google.com:443 
2018/05/01 07:35:11 tcp:127.0.0.1:59646 accepted tcp:www.google.com:443 
2018/05/01 07:35:11 tcp:127.0.0.1:59646 accepted tcp:www.google.com:443 
2018/05/01 07:35:11 tcp:127.0.0.1:59612 accepted tcp:www.google.com:443 
2018/05/01 07:35:11 tcp:127.0.0.1:59694 accepted tcp:www.youtube.com:443 
2018/05/01 07:35:11 tcp:127.0.0.1:59694 accepted tcp:www.google.com:443 
2018/05/01 07:35:11 tcp:127.0.0.1:59694 accepted tcp:notifications.google.com:443 
2018/05/01 07:35:11 tcp:127.0.0.1:59694 accepted tcp:play.google.com:443 
2018/05/01 07:35:12 tcp:127.0.0.1:59612 accepted tcp:scholar.google.com.hk:443 
2018/05/01 07:35:12 tcp:127.0.0.1:59612 accepted tcp:ogs.google.com:443 
2018/05/01 07:35:17 tcp:127.0.0.1:59612 accepted tcp:beacons5.gvt3.com:443 

8) 其它相关的配置文件（如 Nginx）和相关日志。
```javascript
##
# You should look at the following URL's in order to grasp a solid understanding
# of Nginx configuration files in order to fully unleash the power of Nginx.
# https://www.nginx.com/resources/wiki/start/
# https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/
# https://wiki.debian.org/Nginx/DirectoryStructure
#
# In most cases, administrators will remove this file from sites-enabled/ and
# leave it as reference inside of sites-available where it will continue to be
# updated by the nginx packaging team.
#
# This file will automatically load configuration files provided by other
# applications, such as Drupal or Wordpress. These applications will be made
# available underneath a path with that package name, such as /drupal8.
#
# Please see /usr/share/doc/nginx-doc/examples/ for more detailed examples.
##

# Default server configuration
#
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	# SSL configuration
	#
	# listen 443 ssl default_server;
	# listen [::]:443 ssl default_server;
	#
	# Note: You should disable gzip for SSL traffic.
	# See: https://bugs.debian.org/773332
	#
	# Read up on ssl_ciphers to ensure a secure configuration.
	# See: https://bugs.debian.org/765782
	#
	# Self signed certs generated by the ssl-cert package
	# Don't use them in a production server!
	#
	# include snippets/snakeoil.conf;

	root /var/www/html;

	# Add index.php to the list if you are using PHP
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
	}

	# pass PHP scripts to FastCGI server
	#
	#location ~ \.php$ {
	#	include snippets/fastcgi-php.conf;
	#
	#	# With php-fpm (or other unix sockets):
	#	fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
	#	# With php-cgi (or other tcp sockets):
	#	fastcgi_pass 127.0.0.1:9000;
	#}

	# deny access to .htaccess files, if Apache's document root
	# concurs with nginx's one
	#
	#location ~ /\.ht {
	#	deny all;
	#}
}


# Virtual Host configuration for example.com
#
# You can move that to a different file under sites-available/ and symlink that
# to sites-enabled/ to enable it.
#
#server {
#	listen 80;
#	listen [::]:80;
#
#	server_name example.com;
#
#	root /var/www/example.com;
#	index index.html;
#
#	location / {
#		try_files $uri $uri/ =404;
#	}
#}
server {
  listen  443 ssl;
  ssl on;
  ssl_certificate       /etc/v2ray/v2ray.crt;
  ssl_certificate_key   /etc/v2ray/v2ray.key;
  ssl_protocols         TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers           HIGH:!aNULL:!MD5;
  server_name           xxxxxxx.com;
        location / {
        proxy_redirect off;
        proxy_pass http://127.0.0.1:1995;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        }
}
```

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。
无

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。
无

**Comment by nicholascw** [comment]
暂无相关功能, 请考虑通过端口监控等方式统计流量.

**Comment by DarienRaymond** [comment]
参考： https://twitter.com/TachyonDevel/status/982113032888176645
