### ISSUE TITLE
如何设置全局代理？

### ISSUE THREAD

**Issue by zhezhe168** [v2ray/v2ray-core#1084]
目前的模式默认为国内外自动分流，国外走代理，国内直连，但是想国内国外一起走代理，该如何进行设置？

**Comment by rufengsuixing** [comment]
请说明你使用的客户端

**Comment by zhezhe168** [comment]
客户端是windows 64位github release的原版

**Comment by rufengsuixing** [comment]
你只是用了核心的话，在config.json配置文件的routing里面改，把rules 删空

**Comment by nicholascw** [comment]
v2ray.com

**Comment by zhezhe168** [comment]
还是不行，取消了其他设置后运行报错，能不能劳烦大佬贴一下绕过本地局域网，代理全部网络连接的配置文件？
