### ISSUE TITLE
请问日志提示“2018/05/06 23:58:47 [Error] App|Proxyman|Mux: failed to read metadata > App|Proxyman|Mux: invalid metalen 19082” 是什么意思

### ISSUE THREAD

**Issue by ntgeralt** [v2ray/v2ray-core#1093]
请问一下，2018/05/06 23:58:47 [Error] App|Proxyman|Mux: failed to read metadata > App|Proxyman|Mux: invalid metalen 19082是什么意思。客户端工作正常，感觉不到异样，只是偶尔一句这个提示，不知道什么意思，望指教

**Comment by VictoriaRaymond** [comment]
这个错误通常表示mux的bug，或者连接数据受到第三方干扰。如果不影响使用可以不用管。
