### ISSUE TITLE
为什么privoxy转发ss的socks的端口可以连上Google而v2ray却不行呢？

### ISSUE THREAD

**Issue by loremwalker** [v2ray/v2ray-core#1094]
v2ray与ss的privoxy配置如图
![](https://s1.ax2x.com/2018/05/07/SkAFJ.png)
测试效果
![](https://s1.ax2x.com/2018/05/07/Sk6A6.png)

v2ray
![](https://s1.ax2x.com/2018/05/07/SkIwp.png)

**Comment by rufengsuixing** [comment]
请使用1081和1187端口，这样你的privoxy才生效
v2ray的socks5不支持http代理，虽然ss做了兼容

**Comment by loremwalker** [comment]
ss兼容的相关原理是什么？

**Comment by Yaspee** [comment]
@loremwalker 
https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Controller/ShadowsocksController.cs#L547

https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Controller/Service/Listener.cs#L123

https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Controller/Service/Listener.cs#L205

**Comment by Justsoos** [comment]
你一楼截图开的1081端口http代理，ie用的却是1080的socks5
你叫马小虎还是吧吧呜？
