### ISSUE TITLE
求助。V2ray 无法使用。选哪个节点都一样。

### ISSUE THREAD

**Issue by marswow** [v2ray/v2ray-core#1098]
【2018年05月08日 08:42:49】: ======================= 梅林固件 - 【科学上网】 ========================
【2018年05月08日 08:42:49】:
【2018年05月08日 08:42:49】: ------------------------- 启动【科学上网】 -----------------------------
【2018年05月08日 08:42:49】: 删除ss相关的名单配置文件.
【2018年05月08日 08:42:49】: 重启dnsmasq服务...
【2018年05月08日 08:42:49】: 清除iptables规则和ipset...
【2018年05月08日 08:42:49】: 你选择了v2ray节点，当前系统已经启用虚拟内存！！符合启动条件！
【2018年05月08日 08:42:49】: 检测到你的SS服务器已经是IP格式：10.10.40.41,跳过解析...
【2018年05月08日 08:42:49】: 创建ipset名单
【2018年05月08日 08:42:49】: 自动判断使用国内优先模式，不加载cdn.txt
【2018年05月08日 08:42:49】: 应用域名黑名单
【2018年05月08日 08:42:50】: 创建gfwlist的软连接到/jffs/etc/dnsmasq.d/文件夹.
【2018年05月08日 08:42:50】: 生成V2Ray配置文件...
【2018年05月08日 08:42:50】: 解析V2Ray配置文件...
【2018年05月08日 08:42:50】: V2Ray配置文件写入成功到/koolshare/ss/v2ray.json
【2018年05月08日 08:42:50】: 测试V2Ray配置文件.....
【2018年05月08日 08:42:50】: V2Ray配置文件没有通过测试，请检查设置!!!
【2018年05月08日 08:42:50】: 插件将在5秒后自动关闭！！
【2018年05月08日 08:42:51】: 5
【2018年05月08日 08:42:52】: 4
【2018年05月08日 08:42:53】: 3
【2018年05月08日 08:42:54】: 2
【2018年05月08日 08:42:55】: 1
【2018年05月08日 08:42:56】: 0
【2018年05月08日 08:42:56】: 插件已关闭！！

**Comment by marswow** [comment]
一直提示配置文件没有通过测试，请检查设置。

**Comment by Chandler-Lu** [comment]
那你倒是把配置贴上来啊

**Comment by markowen10** [comment]
> 已经解决啦~~~@Chandler-Lu
> 我之前出现过BUG，必须格式化U盘后才能用U盘，然后还要把缓存卸载掉，重新加载缓存就解决V2ray的问题

能在说的具体一点吗兄弟

**Comment by ptmicky** [comment]
配置中的内容不能留空，例如额外ID无，则填写0，否则会提示：“V2Ray配置文件没有通过测试，请检查设置!!!”
