### ISSUE TITLE
有没有大佬能教我如何删除routing里面的rules

### ISSUE THREAD

**Issue by zhezhe168** [v2ray/v2ray-core#1099]
想设置全局代理，不分流，按照教程改了不行，无法运行，以下是原配置文件，使用的是release的win64版

{
 "outbound": {
  "streamSettings": {
   "network": "ws", 
   "kcpSettings": null, 
   "wsSettings": {
    "headers": {
     "host": "**********"
    }, 
    "path": "", 
    "connectionReuse": true
   }, 
   "tcpSettings": null, 
   "tlsSettings": {}, 
   "security": ""
  }, 
  "tag": "agentout", 
  "protocol": "vmess", 
  "mux": {
   "enabled": true
  }, 
  "settings": {
   "vnext": [
    {
     "users": [
      {
       "alterId": 100, 
       "security": "none", 
       "id": "*************************"
      }
     ], 
     "port": 80, 
     "address": "**************"
    }
   ]
  }
 }, 
 "log": {
  "access": "", 
  "loglevel": "info", 
  "error": ""
 }, 
 "outboundDetour": [
  {
   "tag": "direct", 
   "protocol": "freedom", 
   "settings": {
    "response": null
   }
  }, 
  {
   "tag": "blockout", 
   "protocol": "blackhole", 
   "settings": {
    "response": {
     "type": "http"
    }
   }
  }
 ], 
 "inbound": {
  "streamSettings": null, 
  "settings": {
   "ip": "127.0.0.1", 
   "udp": true, 
   "clients": null, 
   "auth": "noauth"
  }, 
  "protocol": "socks", 
  "port": 1080, 
  "listen": "0.0.0.0"
 }, 
 "inboundDetour": null, 
 "routing": {
  "settings": {
   "rules": [
    {
     "ip": [
      "0.0.0.0/8", 
      "10.0.0.0/8", 
      "100.64.0.0/10", 
      "127.0.0.0/8", 
      "169.254.0.0/16", 
      "172.16.0.0/12", 
      "192.0.0.0/24", 
      "192.0.2.0/24", 
      "192.168.0.0/16", 
      "198.18.0.0/15", 
      "198.51.100.0/24", 
      "203.0.113.0/24", 
      "::1/128", 
      "fc00::/7", 
      "fe80::/10"
     ], 
     "domain": null, 
     "type": "field", 
     "port": null, 
     "outboundTag": "direct"
    }, 
    {
     "type": "chinaip", 
     "outboundTag": "direct"
    }, 
    {
     "type": "chinasites", 
     "outboundTag": "direct"
    }
   ], 
   "domainStrategy": "IPIfNonMatch"
  }, 
  "strategy": "rules"
 }, 
 "dns": {
  "servers": [
   "8.8.8.8", 
   "8.8.4.4", 
   "localhost"
  ]
 }
}

**Comment by rufengsuixing** [comment]
https://www.v2ray.com/chapter_02/03_routing.html
删除
```json
{
"type": "chinaip",
"outboundTag": "direct"
},
{
"type": "chinasites",
"outboundTag": "direct"
}
],
```
