### ISSUE TITLE
UDP QoS

### ISSUE THREAD

**Issue by david9991** [v2ray/v2ray-core#1101]
V2ray Version: 3.21
Systems: Linux, MacOS
由于 UDP QoS，导致使用 mKCP 加速时断时续，因此我使用了 https://github.com/iceonsun/rsock 和 udp2raw 项目，在 UDP 头部加入 FakeTCP。虽然工作非常良好，但感觉配置起来还是有些麻烦。我想可否考虑将 FakeTCP 加入 V2ray 原生支持中，配合 mKCP 一同使用？比如：
```
"kcpSettings": {
  "header": {
    "type": "faketcp"
  }
}
```

**Comment by TanNang** [comment]
https://github.com/v2ray/Planning/issues/16

**Comment by DarienRaymond** [comment]
V2Ray不会考虑重写（或伪造）TCP栈。

**Comment by pinatsu** [comment]
> V2ray Version: 3.21
> Systems: Linux, MacOS
> 由于 UDP QoS，导致使用 mKCP 加速时断时续，因此我使用了 https://github.com/iceonsun/rsock 和 udp2raw 项目，在 UDP 头部加入 FakeTCP。虽然工作非常良好，但感觉配置起来还是有些麻烦。我想可否考虑将 FakeTCP 加入 V2ray 原生支持中，配合 mKCP 一同使用？比如：
> 
> ```
> "kcpSettings": {
>   "header": {
>     "type": "faketcp"
>   }
> }
> ```

请问v2ray+udp2raw是怎么配置的？
