### ISSUE TITLE
路由器的v2ray连接谷歌学术提示we are sorry，PC/Android客户端完全正常

### ISSUE THREAD

**Issue by google9002** [v2ray/v2ray-core#1105]
中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
PC端：latest，3.21
路由端：科学上网插件自带，作者已更新至v2ray-core 3.21
手机端：v2rayNG，最新版，内核应同样为3.21
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
在不同的场景下（手机、路由、PC）通过同一个配置文件启动v2ray，然后通过Chrome登录scholar.google.com
需要说明：我的vps（弗里蒙特）的ipv4网段应该确实是被谷歌封了，因此我通过修改服务器hosts文件，强制使用ipv6登录scholar。另外，一个月以前我用shadowsocks时，无论ipv6还是ipv4连接scholar均显示“we are sorry”页面
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
手机端开启v2rayNG使用Chrome登录scholar，时而正常时而不正常；
PC端开启v2ray使用Chrome登录scholar，正常；
路由器端开启科学上网插件使用v2ray节点，PC使用Chrome登录scholar，显示“we are sorry，but your computer seems to be sending automated quires”；
路由器和PC端同时开启v2ray，其中PC端使用v2rayN并关闭系统代理（此时如果路由器不开科学上网插件，则Micro Edge浏览器无法翻墙。即，Chrome流量走PC端v2ray，Edge走路由器端），使用Chrome+switchyomega登录scholar，正常；Microsoft Edge登录scholar，“we are sorry...”
4)  你期待看到的正确表现是怎样的？
按之前shadowsocks的测试，在我使用这个服务器的情况下应该无论如何都无法登录google scholar才对；
如果google解封了这个服务器的ipv6访问，那应该无论如何都能正常访问scholar才对；
总而言之，不应该出现不同的现象——除非我的路由器在自己重复访问？
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
配置暂略，因为除了谷歌学术之外一切正常，仅仅是同一个配置文件放在改版梅林384.4固件上的最新版ss/v2ray/ssr/koolgame四合一插件上的话，登录谷歌学术就会出现“we are sorry”界面。我认为这理应不是我的配置问题，但是无法理解出现问题的原因。
另外，我的v2ray设置为http/2+tls
以上为主要问题，以下是一个附加问题：
能不能不用proxifier之类的软件，让v2ray能直接代理Outlook同步Gmail邮件？

**Comment by rufengsuixing** [comment]
请提交路由器端的配置文件，路由器是用iptables和传送门进行重定向，一般不会使用ip6tables进行ipv6流量的重定向，另外默认的dns一般不会有ipv6
避免这个问题最简单的方式就是在路由器上留下代理端口，然后进行浏览器代理设置

**Comment by google9002** [comment]
@rufengsuixing 明白了，多谢！

**Comment by IPNUISTlegal** [comment]
![image](https://user-images.githubusercontent.com/35527568/80269877-28015f00-86e6-11ea-825b-1ba1ad837efb.png)
请问现在如何使用v2ray上谷歌学术？
感谢

**Comment by adoer1115** [comment]
和楼上有一样的问题，求解答
