### ISSUE TITLE
纯ipv6服务器配置了v2ray，发现所有访问被指向ipv4地址，有办法解决吗？

### ISSUE THREAD

**Issue by xiaoxiaoxiao2018** [v2ray/v2ray-core#1109]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
最新版的V2ray，和0.3.13的V2rayNG客户端，因为更新版的客户端在我的手机上 无法运行。
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
      android通过v2rayNG使用。我的服务器只有IPv6地址，配置了nat64，可以在服务器上访问v4域名，但是不能访问v4ip，连接方式是v4only客户端==>cloudflare==>v6only v2ray 服务器==>目标服务器。
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
     查看log发现大量的指向IPV4地址的连接，而没有访问ipv6地址的连接，即使访问的是youtube和Google这种ipv6优先的服务，导致无法访问任何网站。
4)  你期待看到的正确表现是怎样的？
    ipv4 only的android手机通过cloudflare访问到ipv6 only的v2ray服务器(传送给V2ray服务器url)，v2ray通过ipv6 only网络请求目标服务器（v2ray在服务器上将url解析为ipv6地址访问目标服务器），再传回客户端数据。
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
```javascript
    // 在这里附上服务器端配置文件
``` {
"log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "info" },
  "inbound": {
    "port": 80,
    "listen":"::",
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "*******************",
          "alterId": 64
        }
      ]
    },
  "dns": {
    "servers": [
      "2001:4860:4860::8888",
      "2001:4860:4860::8844",
      "localhost"
    ]
  },
    "streamSettings": {
      "network": "ws",
      "wsSettings": {
      "path": "/php"
      }
    }
  },
  "outbound": {
    "sendThrough": ‘服务器ipv6地址’，
    "protocol": "freedom",
    "settings": {}
  }
}

 


    客户端配置:
```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
```
    // 在这里附上服务器端日志
（因为服务器没有ipv4地址，所以全部无法连接，其中未看到ipv6的地址，在netstat -a下也未曾看到）
```2018/05/13 08:01:47 [Info] [66025416] Proxy|VMess|Inbound: received request for udp:8.8.4.4:53
2018/05/13 08:01:47 [Info] [66025416] App|Dispatcher: default route for udp:8.8.4.4:53
2018/05/13 08:01:47 [Info] [66025416] Proxy|Freedom: opening connection to udp:8.8.4.4:53
2018/05/13 08:01:47 [Info] [2298703093] Proxy|VMess|Inbound: received request for udp:8.8.4.4:53
2018/05/13 08:01:47 [Info] [2298703093] App|Dispatcher: default route for udp:8.8.4.4:53
2018/05/13 08:01:47 [Info] [2298703093] Proxy|Freedom: opening connection to udp:8.8.4.4:53
2018/05/13 08:01:47 [Info] [3662262621] Proxy|VMess|Inbound: received request for udp:8.8.4.4:53
2018/05/13 08:01:47 [Info] [3662262621] App|Dispatcher: default route for udp:8.8.4.4:53
2018/05/13 08:01:47 [Info] [3662262621] Proxy|Freedom: opening connection to udp:8.8.4.4:53
2018/05/13 08:01:47 [Info] [1474248173] Proxy|VMess|Inbound: received request for udp:8.8.4.4:53
2018/05/13 08:01:47 [Info] [1474248173] App|Dispatcher: default route for udp:8.8.4.4:53
2018/05/13 08:01:47 [Info] [1474248173] Proxy|Freedom: opening connection to udp:8.8.4.4:53
2018/05/13 08:01:47 [Info] [1113209949] Proxy|VMess|Inbound: received request for tcp:13.32.16.94:443
2018/05/13 08:01:47 [Info] [1113209949] App|Dispatcher: default route for tcp:13.32.16.94:443
2018/05/13 08:01:47 [Info] [1113209949] Proxy|Freedom: opening connection to tcp:13.32.16.94:443
2018/05/13 08:01:47 [Info] [1113209949] Transport|Internet|TCP: dialing TCP to tcp:13.32.16.94:443
2018/05/13 08:01:47 [Info] [1113209949] Transport|Internet|TCP: dialing TCP to tcp:13.32.16.94:443
2018/05/13 08:01:47 [Info] [1113209949] Transport|Internet|TCP: dialing TCP to tcp:13.32.16.94:443
2018/05/13 08:01:47 [Info] [1113209949] Transport|Internet|TCP: dialing TCP to tcp:13.32.16.94:443
2018/05/13 08:01:47 [Info] [508616678] Proxy|VMess|Inbound: received request for tcp:13.35.3.146:443
2018/05/13 08:01:47 [Info] [508616678] App|Dispatcher: default route for tcp:13.35.3.146:443
2018/05/13 08:01:47 [Info] [508616678] Proxy|Freedom: opening connection to tcp:13.35.3.146:443
2018/05/13 08:01:47 [Info] [508616678] Transport|Internet|TCP: dialing TCP to tcp:13.35.3.146:443
2018/05/13 08:01:47 [Info] [508616678] Transport|Internet|TCP: dialing TCP to tcp:13.35.3.146:443
2018/05/13 08:01:48 [Info] [508616678] Transport|Internet|TCP: dialing TCP to tcp:13.35.3.146:443
2018/05/13 08:01:48 [Info] [1113209949] Transport|Internet|TCP: dialing TCP to tcp:13.32.16.94:443
2018/05/13 08:01:48 [Info] [508616678] Transport|Internet|TCP: dialing TCP to tcp:13.35.3.146:443


    客户端错误日志:
```
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
```
    // 在这里附上服务器端日志
（只有IPV4地址，但是v4地址应该是无法访问我的服务器的）
2018/05/13 08:42:09 106.118.179.255:17257 accepted udp:8.8.4.4:53 
2018/05/13 08:42:10 106.118.179.255:34751 accepted tcp:13.32.8.212:443 
2018/05/13 08:42:10 106.118.179.255:32671 accepted tcp:13.32.16.196:443 
2018/05/13 08:42:13 106.118.179.255:18073 accepted tcp:52.84.10.163:443 
2018/05/13 08:42:13 106.118.179.255:17273 accepted udp:8.8.8.8:53 
2018/05/13 08:42:13 106.118.179.255:19293 accepted tcp:13.35.19.205:443 
2018/05/13 08:42:14 106.118.179.255:24989 accepted udp:8.8.8.8:53 
2018/05/13 08:42:15 106.118.179.255:27529 accepted tcp:54.230.0.209:443 
2018/05/13 08:42:15 106.118.179.255:20411 accepted tcp:13.35.2.165:443 
2018/05/13 08:42:17 106.118.179.255:24083 accepted udp:8.8.4.4:53 
2018/05/13 08:42:18 106.118.179.255:15457 accepted tcp:54.192.20.90:443 
2018/05/13 08:42:18 106.118.179.255:33573 accepted tcp:13.35.3.103:443 
2018/05/13 08:42:19 106.118.179.255:36657 accepted udp:8.8.4.4:53 
2018/05/13 08:42:21 106.118.179.255:34243 accepted tcp:54.230.7.73:443 
2018/05/13 08:42:21 106.118.179.255:9415 accepted tcp:13.35.4.189:443 
2018/05/13 08:42:23 106.118.179.255:22843 accepted udp:8.8.8.8:53 
2018/05/13 08:42:24 106.118.179.255:13665 accepted tcp:13.35.5.229:443 
2018/05/13 08:42:24 106.118.179.255:12673 accepted tcp:54.230.20.113:443 
2018/05/13 08:42:26 106.118.179.255:19905 accepted tcp:52.84.10.97:443 
2018/05/13 08:42:26 106.118.179.255:9321 accepted tcp:13.32.20.189:443 
2018/05/13 08:42:28 106.118.179.255:16077 accepted udp:8.8.4.4:53 
2018/05/13 08:42:29 106.118.179.255:13365 accepted tcp:13.35.7.60:443 
2018/05/13 08:42:29 106.118.179.255:15089 accepted tcp:54.230.11.178:443 
2018/05/13 08:42:32 106.118.179.255:28709 accepted tcp:52.84.7.8:443 
2018/05/13 08:42:32 106.118.179.255:21703 accepted tcp:54.230.15.43:443 
2018/05/13 08:42:33 106.118.179.255:32917 accepted udp:8.8.8.8:53 
2018/05/13 08:42:34 106.118.179.255:27913 accepted tcp:52.84.7.154:443 
2018/05/13 08:42:34 106.118.179.255:19217 accepted tcp:54.182.2.148:443 
2018/05/13 08:42:37 106.118.179.255:37197 accepted tcp:54.230.7.214:443 
2018/05/13 08:42:37 106.118.179.255:21749 accepted tcp:52.84.10.173:443 
2018/05/13 08:42:38 106.118.179.255:12229 accepted udp:8.8.4.4:53 
2018/05/13 08:42:40 106.118.179.255:11681 accepted tcp:54.239.192.30:443 
2018/05/13 08:42:40 106.118.179.255:11933 accepted tcp:54.230.0.230:443 
2018/05/13 08:42:42 106.118.179.255:27005 accepted udp:8.8.8.8:53 
2018/05/13 08:42:43 106.118.179.255:22733 accepted udp:8.8.8.8:53 
2018/05/13 08:42:43 106.118.179.255:29047 accepted tcp:13.32.8.27:443 
2018/05/13 08:42:43 106.118.179.255:25569 accepted tcp:13.35.5.222:443 
2018/05/13 08:42:46 106.118.179.255:11337 accepted tcp:13.35.20.165:443 
2018/05/13 08:42:46 106.118.179.255:37119 accepted tcp:13.35.3.55:443 
2018/05/13 08:42:47 106.118.179.255:25923 accepted udp:8.8.4.4:53 
2018/05/13 08:42:48 106.118.179.255:33509 accepted udp:8.8.4.4:53 
2018/05/13 08:42:48 106.118.179.255:34395 accepted tcp:13.32.8.113:443 
2018/05/13 08:42:48 106.118.179.255:35115 accepted tcp:13.35.18.29:443 
2018/05/13 08:42:51 106.118.179.255:30755 accepted tcp:205.251.207.234:443 
2018/05/13 08:42:51 106.118.179.255:18221 accepted tcp:54.192.20.108:443 
2018/05/13 08:42:52 106.118.179.255:33119 accepted udp:8.8.8.8:53 
2018/05/13 08:42:53 106.118.179.255:16949 accepted udp:8.8.8.8:53 
2018/05/13 08:42:54 106.118.179.255:22295 accepted tcp:54.230.15.223:443 
2018/05/13 08:42:54 106.118.179.255:11871 accepted tcp:54.192.20.174:443 
2018/05/13 08:42:56 106.118.179.255:27355 accepted tcp:13.35.14.140:443 
2018/05/13 08:42:56 106.118.179.255:12585 accepted tcp:54.182.2.164:443 
2018/05/13 08:42:57 106.118.179.255:12457 accepted udp:8.8.4.4:53 
```




8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

如果你已经填完上面的问卷，请把下面的英文部份删除，再提交 Issue。
Please remove the Chinese section above.

English:
Please read the [instruction](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md) and answer the following questions before submitting your issue. Thank you.
Please answer all the questions with enough information. All issues not following this template will be closed immediately.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)

4) What's your expectation?

5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Server configuration:
```javascript
    // Please attach your server configuration here.
```

    Client configuration:
```javascript
    // Please attach your client configuration here.
```

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.

    Server error log:
```
    // Please attach your server error log here.
```
    Client error log:
```
    // Please attach your client error log here.
```

7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.
```
    // Please attach your server access log here.
```

Please review your issue before submitting.

8) Other configurations (such as Nginx) and logs.

9) If V2Ray doesn't run, please attach output from `--test`.

The command is usually `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`, but may vary according to your scenario.

10) If V2Ray service doesn't run, please attach journal log.

Usual command is `journalctl -u v2ray`.

**Comment by rufengsuixing** [comment]
https://www.v2ray.com/chapter_02/01_overview.html
domainoverride

**Comment by kslr** [comment]
目前没有标准：https://github.com/v2ray/v2ray-core/issues/1487
不支持
