### ISSUE TITLE
同一个inbound 端口 支持多个协议

### ISSUE THREAD

**Issue by kuyagic** [v2ray/v2ray-core#111]
是否能 在一个端口实现 socks5 和 http 的协议. 或者一个v2ray 支持多个inbound的不同协议的端口监听

**Comment by zxcso** [comment]
同问，现在是跑多个客户端来支持不同端口

**Comment by v2ray** [comment]
你可以添加多个 InboundDetour 也支持多个端口，不需要启动多个客户端。

参考这个配置文件： https://www.v2ray.com/zh_cn/chapter_05/00_config/06_shadowsocks.html

V2Ray 暂时不考虑在同一端口支持多种协议。
