### ISSUE TITLE
请问有什么办法能够在客户端获取服务端V2Ray版本

### ISSUE THREAD

**Issue by Shinlor** [v2ray/v2ray-core#1115]
请问有什么办法能够在客户端获取服务端V2Ray版本
一些情况下，需在本地判断服务器版本。

**Comment by longercui** [comment]
V2Ray -v，好像是这个命令

**Comment by Shinlor** [comment]
V2Ray -v这个是获取本地的版本
我是想问有没有办法从客户端，获取服务器端的版本，或者能否增加此项功能

**Comment by DarienRaymond** [comment]
没有，不支持。你为什么有这样的需求？

**Comment by Shinlor** [comment]
至少运行时可以提示”版本不匹配“之类的

**Comment by DarienRaymond** [comment]
没有必要，兼容性是保证的。
