### ISSUE TITLE
关于Dispatcher和Routing的疑问

### ISSUE THREAD

**Issue by bitching** [v2ray/v2ray-core#1118]
Please skip to the English section below if you don't write Chinese.

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
　3.17

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
　公司内网，需要 http 代理方可上网，已使用 h2s 组成代理链（https://github.com/Equim-chan/h2s/issues/1 ），已可正常穿越公司内网的 http 代理服务器访问 google 等网站。
　h2s 监听 127.0.0.1:5 。

3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
　路由似乎工作不正常，所有请求都发往 VPS 中转了。

4)  你期待看到的正确表现是怎样的？
　geosite:cn / geoip:cn 请求通过内网 http 代理服务器直接访问，仅特殊网站通过内网 http 代理服务器发往 VPS 中转。

5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

　客户端配置:
```javascript
{
  "inbound": {
    "port": 1080,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "mux":{"enabled": true, "concurrency": 8},
    "tag": "breakthewall",
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "wsSettings": {"path": "/v2ray", "headers": {"Host": "my.vps" }},
      "tlsSettings": {"serverName": "my.vps"}
    },
    "settings": {
      "vnext": [
        {
          "address": "127.0.0.1",
          "port": 8,
          "users": [{xxxxxx}]
        }
      ]
    }
  },
  "inboundDetour": [{
      "listen": "127.0.0.1",
      "port": 8,
      "protocol": "dokodemo-door",
      "settings": {
        "network": "tcp",
        "address": "my.vps",
        "port": 443
      },
      "tag": "bridged"
    }],
  "outboundDetour": [
    {
      "protocol": "socks",
      "settings": {
        "servers": [{
          "address": "127.0.0.1",
          "port": 5
        }]
      },
      "tag": "h2s"
    },
    {
      "protocol": "socks",
      "settings": {
        "servers": [{
          "address": "127.0.0.1",
          "port": 5
        }]
      },
      "tag": "proxying"
    },
    {
      "protocol": "blackhole",
      "settings": {"response": {"type": "http"}},
      "tag": "block"
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "dns": {"servers": ["10.1.1.10"]},
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "inboundTag": ["bridged"],
          "outboundTag": "h2s"
        },
        {
          "type": "field",
          "outboundTag": "block",
          "domain": ["adserv"]
        },
        {
          "type": "field",
          "outboundTag": "breakthewall",
          "domain": ["google.com"]
        },
        {
          "type": "field",
          "outboundTag": "proxying",
          "domain": ["geosite:cn"],
          "ip": ["geoip:cn"]
        },
        {
          "type": "field",
          "outboundTag": "direct",
          "domain": ["my.domain"],
          "ip": ["10.0.0.0/7"]
        }
      ]
    }
  }
}

```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
　无

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
```
　//客户端日志
V2Ray v3.17 (die Commanderin) 20180412
A unified platform for anti-censorship.
2018/05/25 08:15:27 [Warning] Core: V2Ray v3.17 started
2018/05/25 08:16:01 [Info] [1234697310] Proxy|Socks: TCP Connect request to tcp:www.baidu.com:443
2018/05/25 08:16:01 [Info] App|Router: looking for IP for domain: www.baidu.com
2018/05/25 08:16:01 [Info] Transport|Internet|UDP: establishing new connection for udp:10.1.1.10:53
2018/05/25 08:16:01 [Info] App|Dispatcher: default route for udp:10.1.1.10:53
2018/05/25 08:16:01 [Info] App|Proxyman|Mux: dispatching request to udp:10.1.1.10:53
2018/05/25 08:16:01 [Info] Transport|Internet|WebSocket: creating connection to tcp:127.0.0.1:8
2018/05/25 08:16:01 [Info] Transport|Internet|TLS: failed to get system cert pool. > crypto/x509: system root pool is not available on Windows
2018/05/25 08:16:01 tcp:127.0.0.1:11353 accepted tcp:www.baidu.com:443 
2018/05/25 08:16:01 [Info] [2795070134] App|Dispatcher: taking detour [h2s] for [tcp:my.vps:443]
2018/05/25 08:16:01 [Info] [2795070134] Transport|Internet|TCP: dialing TCP to tcp:127.0.0.1:5
2018/05/25 08:16:02 [Info] Proxy|VMess|Outbound: tunneling request to tcp:v1.mux.cool:9527 via tcp:127.0.0.1:8
2018/05/25 08:16:05 [Info] Transport|Internet|UDP: failed to handle UDP input > context canceled
2018/05/25 08:16:09 [Info] App|Router: failed to get IP address > App|DNS: returning nil for domain www.baidu.com.
2018/05/25 08:16:09 [Info] [1234697310] App|Dispatcher: default route for tcp:www.baidu.com:443
2018/05/25 08:16:09 [Info] [1234697310] App|Proxyman|Mux: dispatching request to tcp:www.baidu.com:443

```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

如果你已经填完上面的问卷，请把下面的英文部份删除，再提交 Issue。

**Comment by bitching** [comment]
Thanks，解决了我的问题，居然是因为这个。。。

**Comment by mysteryboy2000** [comment]
公司有HTTP PROXY，我在瓦工上架了V2ray，用的朴素TCP
全都配好了，出现了如下错误。。。


 
Handshake failed
The SSL handshake could not be performed.
Host: pan.baidu.com
Reason: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request:state 23:Application response 500 handshakefailed
Company Acceptable Use Policy
This is an optional acceptable use disclaimer that appears on every page. You may change the wording or remove this section entirely in index.html.
For assistance, please contact your system administrator.
generated 2018-06-26 16:49:47 by McAfee Web Gateway 

这个是没救了？
感觉是证书的问题？

**Comment by mysteryboy2000** [comment]
h2s config
{
  "bind": "127.0.0.1:8088",
  "upstreams": [ {
    "address": "192.168.170.5:8080"
  }, {
    "address": "192.168.170.5:443",
    "tls": {
      "serverName": "192.168.170.5",
      "insecureSkipVerify": false,
      "rootCA": "",
      "certFile": "",
      "keyFile": ""
    }
  }],
  "timeout": "20s",
  "retries": 3
}

V2ray config
{
    "log": {
        "access": "access.log",
        "error": "error.log",
        "loglevel": "warning"
    },
    "inbound": {
        "port": 1080,
        "listen": "127.0.0.1",
        "protocol": "socks",
        "settings": {
            "auth": "noauth",
            "udp": false
        }
    },
    "outbound": {
        "protocol": "vmess",
        "settings": {
            "vnext": [
                {
                    "address": "127.0.0.1",
                    "port": 50001,
                    "users": [
                        {
                            "id": "my-id-from-vmess-config",
                            "alterId": 233,
                            "security": "auto"
                        }
                    ]
                }
            ]
        },
        "mux": {
            "enabled": true
        }
    },
    "inboundDetour": [
        {
            "listen": "127.0.0.1",
            "port": 50001,
            "protocol": "dokodemo-door",
            "settings": {
                "network": "tcp",
                "address": "my vmess server id",
                "port": 3366
            },
            "tag": "inner"
        }
    ],
    "outboundDetour": [
        {
            "protocol": "socks",
            "settings": {
                "servers": [{
                    "address": "127.0.0.1",
                    "port": 8088,
                    "username": "",
                    "password": ""
                }]
            },
            "tag": "h2s"
        }
    ],
    "dns": {
        "servers": [
            "8.8.8.8",
            "8.8.4.4",
            "localhost"
        ]
    },
    "routing": {
        "strategy": "rules",
        "settings": {
            "domainStrategy": "IPIfNonMatch",
            "rules": [
                {
                    "type": "field",
                    "ip": [
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "203.0.113.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10",
                        "geoip:cn"
                    ],
                    "domain": [
                        "geosite:cn"
                    ],
                    "outboundTag": "direct"
                },
                {
                    "type": "chinasites",
                    "outboundTag": "h2s"
                },
                {
                    "type": "chinaip",
                    "outboundTag": "h2s"
                },
                {
                    "type": "field",
                    "inboundTag": ["inner"],
                    "outboundTag": "h2s"
                }
            ]
        }
    }
}

**Comment by mysteryboy2000** [comment]
2018/06/26 17:13:59 [Warning] App|DNS: failed to lookup IPs for domain www.google.com. > lookup www.google.com.: no such host
2018/06/26 17:13:59 [Warning] App|DNS: failed to lookup IPs for domain www.google.com. > lookup www.google.com.: no such host
