### ISSUE TITLE
使用mkcp方式时上层socket不稳？

### ISSUE THREAD

**Issue by bitching** [v2ray/v2ray-core#1119]
Please skip to the English section below if you don't write Chinese.

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
3.23

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
如上

3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
speedtest.net测到一半时提示“A socket error occurred”，firefox下载github上的release时中断，但使用tcp或者ws方式则无此问题（但是比mkcp慢多了。。）。
而且复现不稳定，有时能跑完speedtest，能正常下载，有时候连续几分钟出问题。。
<img width="442" alt="111" src="https://user-images.githubusercontent.com/12702029/40527260-fdf87fea-601d-11e8-8511-041eeaaa84ed.png">
<img width="458" alt="222" src="https://user-images.githubusercontent.com/12702029/40527265-0267696a-601e-11e8-8d7a-18cdfc2c3892.png">

4)  你期待看到的正确表现是怎样的？
mkcp方式的底层传输不该导致上层socket reset

5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
```javascript
    {
      "port":6113,
      "protocol":"vmess",
      "streamSettings":{"network":"kcp"},
      "settings":{
        "clients":[
          {
            "id":"xxxxx",
            "level":0,
            "alterId":2
          }
        ],
        "detour":{"to":"dynamic"}
      }
    },
    {
      "protocol":"vmess",
      "port":"16000-20000",
      "streamSettings":{"network":"kcp"},
      "tag":"dynamic",
      "settings":{},
      "allocate":{
        "strategy":"random",
        "concurrency":4,
        "refresh":10
      }
    },
  "transport":{
    "kcpSettings":{
      "mtu":1200,
      "tti":50,
      "uplinkCapacity":3,
      "downlinkCapacity":100,
      "congestion":true,
      "readBufferSize":2,
      "writeBufferSize":2,
      "header":{"type":"wechat-video"}
    }
  }

```

    客户端配置:
```javascript
  "transport": {
    "kcpSettings": {
      "mtu": 1200,
      "tti": 50,
      "uplinkCapacity": 3,
      "downlinkCapacity": 100,
      "congestion": true,
      "readBufferSize": 2,
      "writeBufferSize": 2,
      "header": {"type": "wechat-video"}
    }
  },
  "outbound": {
    "protocol": "vmess",
    "mux": {"enabled": false},
    "tag": "breakthewall",
    "streamSettings": {"network": "kcp"},
    "settings": {
      "vnext": [
        {
          "address": "my.vps",
          "port": 6113,
          "users": [
            {
              "id": "xxxxx",
              "alterId": 2,
              "security": "aes-128-gcm"
            }
          ]
        }
      ]
    }

```

**Comment by cdtsuipo** [comment]
我也用mkcp，FF配合swithyomega，网络不好的时候，FF容易死，断流，超高CPU占用，chrome没遇到过问题

**Comment by bitching** [comment]
最神奇的是原版kcptun+ss不会出问题，就mkcp会出问题。
我现在已经基本不用mkcp了。。

**Comment by VictoriaRaymond** [comment]
请升级到最新版本。
