### ISSUE TITLE
[咨询]大家都用什么"配置"玩PUBG？

### ISSUE THREAD

**Issue by ghost** [v2ray/v2ray-core#1121]
1)  你正在使用哪个版本的 V2Ray？
v2.46

2)  你的使用场景是什么？
proxifier > socks5 > CLIENT > TCP > SERVER
proxifier > socks5 > CLIENT > mKCP > SERVER
proxifier > socks5 > CLIENT > WS+TLS > SERVER[nginx]
proxifier > socks5 > CLIENT > WS+TLS+CDN > SERVER[nginx]

3)  你看到的不正常的现象是什么？
a.) 使用TCP时，延时120ms+，偶尔卡顿（几分钟来一次），进大厅、返回大厅都比较慢；
b.) 使用mKCP时，延时60ms左右，频繁轻微卡顿（不影响游戏），偶尔大卡一下（回档），进大厅、开匹、返回大厅都很迅速。但是国际出口网络不好时会爆卡；
c.) 使用WS+TLS时，延时80~120ms波动，偶尔轻微卡顿（不影响游戏），但是每次连续玩2～3张地图后就开始各种卡顿（而且越来越卡，最后直至爆卡没法玩），必须退出游戏进程后，等一会儿再重新启动游戏才能正常。但是又只能持续玩个2张地图，然后又开始爆卡；
d.) WS+TLS 偶尔会延时会抽风，CDN套上就好了，但是延时会增加。

4)  你期待看到的正确表现是怎样的？
a.) 准备再试下 TLS 不要 webserver 中转；
b.) 想问下用 V2Ray 流畅吃鸡的朋友，你们用的什么配置？（ 比如mux设置、缓存设置什么的）

**Comment by lushengwen** [comment]
proxifier不支持udp，pubg进大厅和匹配是tcp，进游戏后是udp，所以你上面写的这些都等于没加速pubg。正确的姿势上hostloc搜索下，去年就有帖子有详细姿势了。

**Comment by leepoi** [comment]
试试微林中转

**Comment by MatcherAny** [comment]
我是玩枫之谷国际私服 服务器ip 185.125.230.177 
直连200 - 300ms 玩起来略卡
proxifier 代理游戏，起来玩起来无延迟 很稳定

只用了mKCP、其他都没有
服务端的完整配置
```json
{
  "inbound": {
    "protocol": "shadowsocks",
    "port": 1111,
    "settings": {
      "method": "aes-256-gcm",
      "password": "xxxxxxxx",
      "udp": true,
      "level": 1
    }
  },
  "inboundDetour": [
    {
      "port": 20000,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "xxx",
            "level": 1,
            "alterId": 64
          },{
            "id": "xxx",
            "level": 1,
            "alterId": 40
          }
        ]
      },
      "streamSettings": {
        "network": "mkcp",
        "kcpSettings": {
          "mtu": 1350,
          "tti": 20,
          "uplinkCapacity": 12,
          "downlinkCapacity": 100,
          "congestion": false,
          "readBufferSize": 2,
          "writeBufferSize": 2,
          "header": {
            "type": "utp"
          }
        }
      }
    }
  ],
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  }
}
```

**Comment by dragonzhi** [comment]
@MatcherAny 玩游戏有掉线断流的现象吗？

**Comment by MatcherAny** [comment]
@dragonzhi 没什么感觉 不过我玩的不是FPS 对网速不是这么敏感

**Comment by yobabyshark** [comment]
用openvpn+udp2raw+udpspeeder，防Qos和降低丢包。
https://github.com/yobabyshark/onekeyopenvpn

**Comment by DarienRaymond** [comment]
Kamino closed and cloned this issue to v2ray/discussion
