### ISSUE TITLE
设置中的"outboundTag": "direct"，除direct，还有什么参数，用来设黑名单

### ISSUE THREAD

**Issue by flukaxkx** [v2ray/v2ray-core#1122]
**1)  你正在使用哪个版本的 V2Ray？**
3.23
**2)  你的使用场景是什么？**
透明代理，代理浏览，BT，等
**3)  你看到的不正常的现象是什么？**
无
**4)  你期待看到的正确表现是怎样的？**
我想用v2ray的设置文件来控制只有gfwlist上的网站走VPS，其他直接连接，所以有如下代码。若采用"direct"参数，这相当于一个白名单，这样第一不能保证BT、电驴的流量不走VPS，第二白名单也太大了。因此，我想问的是"outboundTag"有没有别的参数选项，比方“proxy”、“block”什么的，可以让我把黑名单放在设置里。

```
 {
          "type": "field",
          "outboundTag": "direct",
          "domain": [
            "taobao.com",
          ......
          ]
}
```

**Comment by Yaspee** [comment]
参考资料：https://v2ray.com/chapter_02/03_routing.html 

tag 是自己设定的，outboundDetour 的 tag 和路由中的 outboundTag 对应即可，具体设置请见手册

**Comment by flukaxkx** [comment]
噢，明白了，明白了。
多谢多谢。

**Comment by flukaxkx** [comment]
补充一下，我现在就是把白名单改成黑名单了，其他地方没有改，但是依然能顺利科学上网。
这就产生个问题，v2ray怎么知道 原来是名单外的自动翻墙，现在是名单外的不翻墙？
v2ray的怎么设置默认是科学线路还是普通线路呢？
测试了一下，比如iplocation.net这个网站，不在黑名单里，但是却走了科学线路，
而ip138.com，也不在黑名单里，确实走了正常线路。

**Comment by DarienRaymond** [comment]
请贴上完整配置，否则没有办法分析。

另外不同的问题请提交一个新的issue。
