### ISSUE TITLE
3.23.1 CPU 100%

### ISSUE THREAD

**Issue by moetakaoruko** [v2ray/v2ray-core#1124]
Please skip to the English section below if you don't write Chinese.

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
3.23.1

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
NAS上做客户端代理

3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
CPU100%

4)  你期待看到的正确表现是怎样的？
CPU 正常使用（换回旧版正常）

5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
  
```
{
  "inbound": {
    "port": xxxxx,
    "listen": "xxxx",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "xxxxx",
          "port": 443,
          "users": [
            {
              "id": "xxxxxx",
              "security": "none",
              "alterId": 0
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "tlsSettings": {
        "allowInsecure": false
      },
      "wsSettings": {
        "path": "xxxxxx"
      }
    },
     "mux": {
        "enabled": true
    }
  },
  "policy": {
    "levels": {
        "0": {
            "uplinkOnly": 0,
            "downlinkOnly": 0,
            "bufferSize": 0,
            "connIdle": 30
        }
    }
  }
}
```

**Comment by DarienRaymond** [comment]
能不能试一下把 bufferSize 删掉之后能不能重现

**Comment by moetakaoruko** [comment]
bufferSize 删掉。过了半小时还是CPU 100%了
![5f1i esos n zgkfwqa b](https://user-images.githubusercontent.com/36332677/40614878-1de02ba0-62b7-11e8-961a-9372256294aa.png)

**Comment by hutozh** [comment]
@DarienRaymond 请问levels必须在policy下吗？我直接写的levels没报错，另外不要这个字段，默认是什么？

**Comment by DarienRaymond** [comment]
@moetakaoruko 可以再试一下 3.23.2 吗？谢谢

**Comment by moetakaoruko** [comment]
3.23.2 暂时没有出现这个问题了
