### ISSUE TITLE
[纯讨论]v2ray+websocket+tls/v2ray+http2+tls和普通的http2代理有区别吗

### ISSUE THREAD

**Issue by pingma** [v2ray/v2ray-core#1128]
v2ray+websocket+tls/v2ray+http2+tls在底层都是采用http+tls来传输的，那么在流量特征上，采用v2ray+websocket+tls/v2ray+http2+tls和直接用http2+tls代理有区别吗？

如果没有区别的话，直接采用caddy+forwardproxy似乎更简单……

**Comment by Hardrain980** [comment]
我认为有区别。

caddy的forwardproxy或nghttpx+squid(也可以换3proxy等后端)是一般的HTTP代理，用GET(对HTTP/FTP等明文资源)或CONNECT(建立隧道，用于SSL或任何TCP)方式进行请求。这类代理不支持UDP(DNS解析是在服务器端完成)

v2ray的http2仅作为传输方式，协议仍是上层所使用的(Vmess/ss/socks5...)

**Comment by billryan** [comment]
使用 v2ray h2, 未经反代，树莓派 v3 上有一定速度提升。几个百分点吧

**Comment by fqx** [comment]
v2ray+websocket+tls 为什么不能支持http2，我看了服务器的accesslog是用http1.1连接的。

**Comment by Leo-Mu** [comment]
> v2ray+websocket+tls 为什么不能支持http2，我看了服务器的accesslog是用http1.1连接的。

对呀！我也想知道。
因为客户端设置的是 ws ，那还能够通过 http2 访问吗？那么 http2 岂不是白配置了？！为什么不能 ws 外面套 http2 呢？
感觉绕晕了。。。

**Comment by Kylejustknows** [comment]
大哥们，区别太大了。
如果你稍微读一些关于墙的探测手段，其中就包括网站握手数据量嗅探，比如说你访问youtube.com，你的电脑和youtube之间连接、握手、加密、数据传输等等，来回的每段数据的大小都是固定的，墙根据往返的数据大小，就能准确判断你在通过代理访问youtube，并封锁你的代理IP。
V2ray的加密，和SSR的混淆算法中，很重要的一部分是“数据量混淆”，在往返的握手数据中随机添加一些无用数据来改变数据包大小，来迷惑墙。

另外楼上的，能不能用http2，不是v2ray来决定的，而是你的网页服务器软件（伪装你是正常网站）是否支持http2代理决定的。 幕后工作的v2ray可以接收websocket代理转来的数据，也可以接收http2代理转来的数据，非常强大怎样都行。但如果你的网页服务器软件不支持http2代理（比如说nginx），那http2就没戏。
另，websocket就是http1.1，一旦成为http2了就没有websocket了（因为http2协议包含了websocket的功能了，你可以理解为融为一体了，也可以理解为http2就是websocket的升级版）
