### ISSUE TITLE
Add option to force shadowsocks server to use OTA

### ISSUE THREAD

**Issue by htfy96** [v2ray/v2ray-core#113]
just like `-A` option of shadowsocks-libev

**Comment by v2ray** [comment]
In what scenarios do you need this feature?

**Comment by v2ray** [comment]
For now V2Ray detects whether the client uses OTA or not, and then act accordingly. I don't think it is reasonable to force client to use OTA. If you have strong requirement on this feature, please reopen this issue and clarify further.

**Comment by htfy96** [comment]
According to https://github.com/breakwa11/shadowsocks-rss/issues/475, SS server without forced OTA is vulnerable to active detection.
```
➜  /tmp python2 ss_att3.py 
scan iv size is 16
2%
15%
28%
41%
54%
67%
80%
93%
Waiting response
attack size 60
{Ip}:{Port} seems a Shadowsocks-go/qt server. Double check now
{Ip}:{Port} is a Shadowsocks-go/qt server with rc4-md5/aes encryptor
```

Server configuration:
```
	{
		"protocol": "shadowsocks",   
		"port": {Port}, 
		"settings": {
			"method": "aes-256-cfb",
			"password": "________",   
			"udp": true,
			"ota": true
		}
	},
```

**Comment by v2ray** [comment]
会在下一版本修复。
