### ISSUE TITLE
软件是好软件，但真的很难用，也复杂，希望改一下

### ISSUE THREAD

**Issue by Linqing0808** [v2ray/v2ray-core#1130]
我们这些是不懂技术的人，能够翻墙是很感谢一众技术员努力的，但是请技术员们站在我们这些普通用户的角度想一下，我们只是想简单的翻个墙，看个代码对我们来说真的很难，请你们优化一下这个软件，至少也要有个图型界面什么的，如果像SS那样设置好IP、Port、Password就能上网就好了

**Comment by bash99** [comment]
据说有基于v2ray的付费服务了，估计你希望的那些都有。

**Comment by maryjeck** [comment]
倒是希望能提供各参数的说明，这样也好部署。

现在的gitbook参数说明比较零散

**Comment by alinuxsa** [comment]
恕我直言，嫌麻烦可以买付费服务。。

**Comment by thenextsupersun** [comment]
有用户门槛可以一定程度防止泛滥被墙

**Comment by Linqing0808** [comment]
我现用的就是付费v2ray，商家将SSR全部换成了v2ray，我能怎么办？

**Comment by bash99** [comment]
@Linqing0808 找商家抱怨啊

**Comment by tonychanczm** [comment]
客户端有图形界面啊

**Comment by Chandler-Lu** [comment]
1. 客户端是有图形界面的
2. 软件提供了大量的中文说明手册，要是还不会，不是能力低，而是懒

**Comment by BoneAsh** [comment]
网上那么多教程，官方文档写的也非常详细，还是弄不明白只能说明你懒

**Comment by Cwek** [comment]
RTFM。除非api部分（虽然有代码demo）外，其他我认为已经足够配置。

**Comment by a1033894877** [comment]
我在此只能说一句你弱你有理 emmmm

**Comment by Hardrain980** [comment]
[https://www.v2ray.com/](https://www.v2ray.com/)
[https://toutyrater.github.io/](https://toutyrater.github.io/)

我不认为你如果认真读了这两套**用中文写的**manual，你还是不会配置客户端。
此外我印象中V2Ray也有配置文件生成器，似乎在Github上就有。请**善用搜索引擎**

**Comment by JMaxime** [comment]
https://github.com/Jrohy/v2rayN/releases
可以试试这个图形界面的客户端

**Comment by i258559** [comment]
@Linqing0808 文科路过，看教程（https://www.v2ray.com/）以及不断实践已经会使用，如果这点耐性和时间投入都没，换一个灰机场吧，没什么可说的。不客气说一句：给一点门槛正好区分“低端”用户，毕竟滥用后总会遇到各种关照。参考各种使用一键搭建梯子被封然后骂娘的=.=

**Comment by BitbeyHub** [comment]
希望那些自我的低端用户不要用Github来给伟大的作者们添堵。
