### ISSUE TITLE
v2ray无法正常启动

### ISSUE THREAD

**Issue by saigyouji-chief** [v2ray/v2ray-core#1133]
核心版本是3.23
![f ppsvq a 1 id9 e o3k](https://user-images.githubusercontent.com/39905675/40911702-20cf43f8-6822-11e8-8753-83e307087168.png)
日志如图
cmd窗口闪了一下就消失了配置文件为默认未修改，已尝试使用管理员权限运行

**Comment by njjpx** [comment]
可能是你的config有错误，可以尝试检查一下

**Comment by saigyouji-chief** [comment]
直接解压出来没动过config

**Comment by njjpx** [comment]
需要自己修改config的，方法详见https://toutyrater.github.io/

**Comment by Chandler-Lu** [comment]
没动过config你怎么用？什么都没配置

**Comment by Hardrain980** [comment]
1. `config.json`需要按自己情况设置
2. 请附上`error.log`的内容(敏感内容，如IP等请查找替换掉)。

如不记录日志，在`config.json`的最下一层加入:
```
"log": {
    "loglevel": "info",
    "access": "C:\\v2ray\\access.log",
    "error": "C:\\v2ray\\error.log"
  }
```
如果这一行不是最后一项，按照json格式，要把`}`换成`},`
