### ISSUE TITLE
idm如何设置V2Ray代理下载youtube视频

### ISSUE THREAD

**Issue by shuouzuidiao** [v2ray/v2ray-core#1134]
![55511](https://user-images.githubusercontent.com/39938475/40955857-5a700eec-68bf-11e8-99b7-11711d5544e8.jpg)

这个帖子看了还是不懂如何设置
https://github.com/v2ray/v2ray-core/issues/806

**Comment by JMaxime** [comment]
使用系统默认设置即可

**Comment by JMaxime** [comment]
https://github.com/Jrohy/v2rayN/releases
配合这个客户端

**Comment by shuouzuidiao** [comment]
这样设置吗，还是不行，我1楼那图那idm设置 脸书和推特视频都能下 就只有油管不能下
![552211](https://user-images.githubusercontent.com/39938475/41044781-96cb51f6-69d9-11e8-8d73-1afb0cac1842.jpg)

谷歌浏览器的插件 都能下的
![144111](https://user-images.githubusercontent.com/39938475/41045190-6f3dfb7e-69da-11e8-99b2-0d952875ba3c.jpg)

**Comment by JMaxime** [comment]
pac模式

**Comment by shuouzuidiao** [comment]
pac模式也没用 我一小白连服务器都不会搭研究这个真是搞不懂问题出在哪，用IDM下载速度可以快2M还能断点下载 用浏览器插件下才几百K的速度

**Comment by Chandler-Lu** [comment]
你v2rayN真的配置好了么

**Comment by shuouzuidiao** [comment]
问题已解决，v2rayN.exe 这个文件我没把它放在V2Ray里就点击运行 所以不能下
![2211](https://user-images.githubusercontent.com/39938475/41099926-8620bd32-6a92-11e8-8206-87a1bdcc3472.jpg)

**Comment by shuouzuidiao** [comment]
@JMaxime
vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogInJ1c3NpYW4tY2xvdWQiLA0KICAiYWRkIjogIjE4NS4xNzcuMjE2LjEzNCIsDQogICJwb3J0IjogIjIyNTM1IiwNCiAgImlkIjogIjUyMDUwMDU3LWY1ZTEtNGI5ZS1iNzhiLTVmNDliNTQ5ZmQyMSIsDQogICJhaWQiOiAiNjQiLA0KICAibmV0IjogImtjcCIsDQogICJ0eXBlIjogInNydHAiLA0KICAiaG9zdCI6ICIiLA0KICAicGF0aCI6ICIiLA0KICAidGxzIjogIiINCn0=

**Comment by JMaxime** [comment]
@shuouzuidiao 谢谢

**Comment by DarienRaymond** [comment]
请不要提交于 V2Ray 无关的issue.

**Comment by getwhatyouwant** [comment]
> @JMaxime
> vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogInJ1c3NpYW4tY2xvdWQiLA0KICAiYWRkIjogIjE4NS4xNzcuMjE2LjEzNCIsDQogICJwb3J0IjogIjIyNTM1IiwNCiAgImlkIjogIjUyMDUwMDU3LWY1ZTEtNGI5ZS1iNzhiLTVmNDliNTQ5ZmQyMSIsDQogICJhaWQiOiAiNjQiLA0KICAibmV0IjogImtjcCIsDQogICJ0eXBlIjogInNydHAiLA0KICAiaG9zdCI6ICIiLA0KICAicGF0aCI6ICIiLA0KICAidGxzIjogIiINCn0=

请问下，
您这个是什么链接？？

**Comment by Chandler-Lu** [comment]
> 请问下，
> 您这个是什么链接？？


v2rayN的链接，base64编码，只是早就失效了
