### ISSUE TITLE
Shadowsocks 增加none加密，节省资源

### ISSUE THREAD

**Issue by ylwxb** [v2ray/v2ray-core#1135]
我是这么用的。
VPS上装了服务端，用vmess协议。
路由器运行arm版客户端，其中inbound用Shadowsocks协议，目前用的加密方法是aes-128-cfb，listen地址是127.0.0.1 。
路由器是K3刷的LEDE，设置路由器的koolss 服务器地址为127.0.0.1.  这样就通过路由器的koolss实现了透明代理，经测试，用起来效果也不错，就和原来路由器直接连Shadowsocks服务器是一样的。

我想如果Shadowsocks不加密，这样占用资源是不是会更少些。

**Comment by noeruh** [comment]
直接用 socks5 不行吗？

**Comment by Cwek** [comment]
至少原生ss还没有吧。

**Comment by ylwxb** [comment]
@Cwek koolss里面倒是有none的选项。

**Comment by DarienRaymond** [comment]
你可以用VMess的None加密。SS是按官方文档实现的，除非SS官方定义了None加密方式，V2Ray是不会加入额外的加密方式的。

**Comment by TanNang** [comment]
@ylwxb 

https://github.com/v2ray/v2ray-core/commit/cb68575444124c81556eb1b2353ccfa26c6805bc

参考上述 commit，开发者已经加入了 none 加密方式。

**Comment by tufu9441** [comment]
@TanNang 但是我试了一下，如果将shadowsocks的method设置为none的话，v2ray-server会无法启动。
