### ISSUE TITLE
TLS协议无法正常运行

### ISSUE THREAD

**Issue by lcpp1123** [v2ray/v2ray-core#1136]
中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
 v2ray-v3.25-windows-64
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
 Chrome使用VMess，使用的v2rayN 为了纯洁性，使用了自定义服务器，制定配置文件。端口配置正常。
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
服务器配置是不变的。本地配置了TLS后，无法连接，不配置TLS连接正常。TLS连接验证不知道错误在哪里。
4)  你期待看到的正确表现是怎样的？
可以成功实现TLS
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
```javascript
    // 在这里附上服务器端配置文件
{
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 1074,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "abc",
          "alterId": 64
        }
      ]
    }
  },
    "streamSettings": {
      "network": "tcp",
            "security": "tls", 
      "tlsSettings": {
        "certificates": [
          {
            "certificateFile": "/etc/v2ray/v2ray.crt", // 证书文件
            "keyFile": "/etc/v2ray/v2ray.key" // 密钥文件
          }
        ]
      }

      
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}

```

    客户端配置:
```javascript
    // 在这里附上客户端配置
可以使用的配置：
{
  "inbound": {
    "port": 6688,
    "protocol": "socks",
    "domainOverride": ["tls","http"],
    "settings": {
      "auth": "noauth"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "abc", // tls 需要域名，所以这里应该填自己的域名
          "port": 1074,
          "users": [
            {
              "id": "abc",
              "alterId": 64
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "tcp",
      "security": "" // 客户端的 security 也要设置为 tls
    }
  }
}
无法正常使用的配置：
{
  "inbound": {
    "port": 6688,
    "protocol": "socks",
    "domainOverride": ["tls","http"],
    "settings": {
      "auth": "noauth"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "abc.com", // tls 需要域名，所以这里应该填自己的域名
          "port": 1074,
          "users": [
            {
              "id": "abc",
              "alterId": 64
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "tcp",
      "security": "tls" // 客户端的 security 也要设置为 tls
    }
  }
}

```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
```
    // 在这里附上服务器端日志
2018/06/06 17:27:00 [Warning] Core: V2Ray v3.25 started
2018/06/07 09:01:00 [Warning] Core: V2Ray v3.25 started
2018/06/07 09:01:03 [Warning] Core: V2Ray v3.25 started
2018/06/07 09:01:04 [Warning] Core: V2Ray v3.25 started

```

    客户端错误日志:
```
    // 在这里附上客户端日志
--------------------------------CurrentDomain_UnhandledException[09:02:34]--------------------------------
System.ComponentModel.Win32Exception (0x80004005): 拒绝访问。
   在 System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   在 System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   在 System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   在 System.Diagnostics.Process.get_MainModule()
   在 v2rayN.Program.RunningInstance()
   在 v2rayN.Program.Main()

 
--------------------------------info[09:02:50]--------------------------------
System.Exception: Webserver Stop ws

 
--------------------------------info[09:03:16]--------------------------------
System.Exception: Webserver Stop ws

 
--------------------------------info[09:03:16]--------------------------------
System.Exception: Webserver prefixes http://127.0.0.1:1082/pac/

 
--------------------------------info[09:03:16]--------------------------------
System.Exception: Webserver running...

 
--------------------------------info[09:03:42]--------------------------------
System.Exception: Webserver Stop ws
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
```
    // 在这里附上服务器端日志


```
服务器端都是开启了TLS的TCP连接。客户端使用TLS时异常，不使用TLS时正常，使用443为默认接口时，测试网站也检测不到我的TLS，根据白皮书使用的acme.sh，生成了文件并放在了文件夹下。
生成时已经改了域名为我的域名。

**Comment by Chandler-Lu** [comment]
```
        "certificates": [
          {
            "certificateFile": "/etc/v2ray/v2ray.crt", // 证书文件
            "keyFile": "/etc/v2ray/v2ray.key" // 密钥文件
          }
        ]
```
你确定你的证书文件的文件名及路径正确？

**Comment by lcpp1123** [comment]
~/.acme.sh/acme.sh --installcert -d abc.com --fullchainpath /etc/v2ray/v2ray.crt --keypath /etc/v2ray/v2ray.key --ecc

使用该命令安装的证书

我还试过了使用Nginx
 listen  443 ssl;
  ssl on;
  ssl_certificate       /etc/v2ray/v2ray.crt;
  ssl_certificate_key   /etc/v2ray/v2ray.key;
使用了同样的密钥文件
想使用/RAY 导流； / 正常访问web1  web页使用https://abc.com可以打开我的web1  但是/ray 就是提示invalid user
这是否说明TLS没有问题？
费解

**Comment by lcpp1123** [comment]
debian 9 系统

**Comment by lcpp1123** [comment]
vultr NJ

**Comment by Chandler-Lu** [comment]
晕死，你检查一下inbound的配置，括号配对有问题
![wx20180607-144542](https://user-images.githubusercontent.com/18322610/41082625-89644c6a-6a61-11e8-9736-98117b73ad4d.png)
![wx20180607-144607](https://user-images.githubusercontent.com/18322610/41082626-89a6c932-6a61-11e8-8f6f-e51b0f1c19c3.png)

**Comment by lcpp1123** [comment]
这么尴尬....

**Comment by lcpp1123** [comment]
streamSettings是inbound里面的项目吗？

**Comment by lcpp1123** [comment]
尴尬.....成了！3Q

**Comment by Chandler-Lu** [comment]
你能不能找一个支持json语法的软件。。
![wx20180607-153039](https://user-images.githubusercontent.com/18322610/41084861-db5ac3cc-6a67-11e8-8681-7a3776c0c5aa.png)

**Comment by Chandler-Lu** [comment]
好～

**Comment by lcpp1123** [comment]
请问一下 下载了sunblime  要安装哪个？来检查语法?有链接吗......

**Comment by Chandler-Lu** [comment]
另外你问题正文里面的`无法正常使用的配置：`下面的配置暴露了你的服务器ip和uuid，赶紧删掉吧。
sub以前用过现在忘了，我现在用的vscode

**Comment by lcpp1123** [comment]
谢谢

**Comment by lcpp1123** [comment]
额...真的倒霉....又用了Nginx
2018/06/07 08:26:00 127.0.0.1:22194 rejected  Proxy|VMess|Encoding: failed to read request header > read tcp 127.0.0.1:10000->127.0.0.1:22194: i/o timeout
2018/06/07 08:26:00 127.0.0.1:22196 rejected  Proxy|VMess|Encoding: failed to read request header > read tcp 127.0.0.1:10000->127.0.0.1:22196: i/o timeout
2018/06/07 08:26:00 127.0.0.1:22198 rejected  Proxy|VMess|Encoding: failed to read request header > read tcp 127.0.0.1:10000->127.0.0.1:22198: i/o timeout
2018/06/07 08:26:00 127.0.0.1:22200 rejected  Proxy|VMess|Encoding: failed to read request header > read tcp 127.0.0.1:10000->127.0.0.1:22200: i/o timeout
2018/06/07 08:26:00 127.0.0.1:22202 rejected  Proxy|VMess|Encoding: failed to read request header > read tcp 127.0.0.1:10000->127.0.0.1:22202: i/o timeout
2018/06/07 08:26:05 127.0.0.1:22204 rejected  Proxy|VMess|Encoding: failed to read request header > read tcp 127.0.0.1:10000->127.0.0.1:22204: i/o timeout
这个错误....可以麻烦解答一下吗......

**Comment by lcpp1123** [comment]
116.*194 - - [07/Jun/2018:08:30:29 +0000] "GET /saywhy HTTP/1.1" 101 14 "-" "Go-http-client/1.1"
116.*194 - - [07/Jun/2018:08:30:34 +0000] "GET /saywhy HTTP/1.1" 101 14 "-" "Go-http-client/1.1"
116.*.194 - - [07/Jun/2018:08:30:42 +0000] "GET /saywhy HTTP/1.1" 101 14 "-" "Go-http-client/1.1"
116.*.194 - - [07/Jun/2018:08:30:49 +0000] "GET /saywhy HTTP/1.1" 101 14 "-" "Go-http-client/1.1"
116.*194 - - [07/Jun/2018:08:30:55 +0000] "GET /saywhy HTTP/1.1" 101 14 "-" "Go-http-client/1.1"
这是Nginx的日志

**Comment by Chandler-Lu** [comment]
恕我没有用nginx配过v2。。我只用caddy干过。。要不你把现在的nginx和v2ray配置贴上来？

**Comment by Hardrain980** [comment]
vmess(也可以换成socks5) + websocket + nginx 模板:

v2ray server(仅inbound部分，`$`后面的内容换成自己的):
```
  "inbound": {
    "tag": "vmess",
    "port": $your_port,
    "listen": "127.0.0.1",
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "$your_uuid",
          "level": 1,
          "alterId": 64,
          "security": "aes-128-gcm"
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "security": "none",
      "wsSettings": {
        "path": "/"
      }
    }
  }
```

nginx(添加到`server {}`之间，`%`后面的部分换成自己的):
```
location /%websocket_path/ {
	proxy_redirect off;
	proxy_pass http://127.0.0.1:%websocket_port/;
	proxy_http_version 1.1;
	proxy_set_header Connection "Upgrade";
	proxy_set_header Upgrade "WebSocket";
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	access_log off;
}
```

v2ray client(仅outbound部分，`$`后面的换成自己的):
```
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "$your_domain",
          "port": 443,
          "users": [
            {
              "id": "$your_uuid",
              "level": 1,
              "alterId": 64,
              "security": "aes-128-gcm"
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "wsSettings": {
        "path": "/$websocket_path/",
        "headers": {
        }
      },
      "tlsSettings":{
        "serverName": "$your_domain",
        "allowInsecure": false
      }
    }
  }
```

**Comment by lcpp1123** [comment]
2018/06/07 09:15:35 [Warning] Transport|Internet|WebSocket: failed to serve http for WebSocket > accept tcp 127.0.0.1:10000: use of closed network connection
2018/06/07 09:15:35 [Warning] Core: V2Ray v3.25 started
想问下这个报错是正常还是异常？
