### ISSUE TITLE
v2ray能否增加QUIC协议?

### ISSUE THREAD

**Issue by lgcde** [v2ray/v2ray-core#1137]
Quic 全称 quick udp internet connection，“快速 UDP 互联网连接”，（和英文 quick 谐音，简称“快”）是由 google 提出的使用 udp 进行多路并发传输的协议。

QUIC（`UDP+QUIC Crypto`）在功能层面等价于`TCP+TLS`, 并且其加密协议(`QUIC Crypto`)未来会被`TLS1.3`代替。

![HTTP2_over_QUIC](https://i.loli.net/2018/06/07/5b189f4b3c9fb.gif)

Quic 相比现在广泛应用的 http2+tcp+tls 协议有如下优势：

1. 减少了 TCP 三次握手及 TLS 握手时间。
2. 改进的拥塞控制。
3. 避免队头阻塞的多路复用。
4. 连接迁移。
5. 前向冗余纠错。

HTTP/2 over QUIC相比HTTP/2 over TLS 1.3最大的优势是首次连接是的RTT开销降低了1-RTT(25%)。在连接复用的情况，QUIC的RTT开销与TLS1.3相等。

当然，QUIC也是有缺点的。比如很多运营商对UDP的QoS级别是比TCP低的，甚至只允许DNS 53端口的UDP包，其他UDP包都是被封掉的。在IDC中，UDP的优先级一般也比TCP低。

参考线索:

[100行代码实现基于 QUIC 的 http 代理 | 行思錄 | Travel Coder](https://liudanking.com/beautiful-life/100%E8%A1%8C%E4%BB%A3%E7%A0%81%E5%AE%9E%E7%8E%B0%E5%9F%BA%E4%BA%8E-quic-%E7%9A%84-http-%E4%BB%A3%E7%90%86/ )
[GitHub - lucas-clemente/quic-go: A QUIC implementation in pure go](https://github.com/lucas-clemente/quic-go)
[TLS1.3/QUIC 是怎样做到 0-RTT 的 | 行思錄 | Travel Coder](https://liudanking.com/network/tls1-3-quic-%E6%98%AF%E6%80%8E%E6%A0%B7%E5%81%9A%E5%88%B0-0-rtt-%E7%9A%84/)
[科普：QUIC协议原理分析](https://zhuanlan.zhihu.com/p/32553477)

**Comment by njjpx** [comment]
这个缺点有点致命。。。

**Comment by Justsoos** [comment]
QUIC工作在应用层，直接决定或改造软件协议栈的算法是有意义的，放在代理上是几乎没意义的--改变不了上层软件协议栈算法。

**Comment by Justsoos** [comment]
有理由怀疑某国内游戏巨头，已经抄袭了QUIC算法应用在生产环境了，此事并未公开。
kcp 也有这个可能性去模拟一个quic算法，也就是说，用不着 v2ray 来实现

**Comment by tsanie** [comment]
题外话，UDP 的 QoS 问题倒是可以通过串联 [udp2raw](https://github.com/wangyu-/udp2raw-tunnel) 来解决。

**Comment by DarienRaymond** [comment]
Kamino closed and cloned this issue to v2ray/Planning
