### ISSUE TITLE
建议：官方推行统一的配置二维码标准

### ISSUE THREAD

**Issue by pipilupipixia** [v2ray/v2ray-core#1139]
如题。现在不同的客户端使用不同的标准（已经至少有两套），因此售卖面板就需要给不用的客户端适配多种标准，这对于v2ray的整个生态链无疑是不利的。
建议官方推行统一的二维码配置标准，并尽可能简单（如base64整个outbound的json配置部分）。

**Comment by pipilupipixia** [comment]
提供目前的两套标准以供参考：
1、
> vmess://base64(security:uuid@host:port)?[urlencode(parameters)]
> 其中 base64、urlencode 为函数，security 为加密方式，parameters 是以 & 为分隔符的参数列表，例如：network=kcp&aid=32&remark=服务器1 经过 urlencode 后为 network=kcp&aid=32&remark=%E6%9C%8D%E5%8A%A1%E5%99%A81
> 可选参数（参数名称不区分大小写）：
> network - 可选的值为 "tcp"、 "kcp"、"ws"、"h2" 等
> wsPath - WebSocket 的协议路径
> wsHost - WebSocket HTTP 头里面的 Host 字段值
> kcpHeader - kcp 的伪装类型
uplinkCapacity - kcp 的上行容量
downlinkCapacity - kcp 的下行容量
h2Path - h2 的路径
h2Host - h2 的域名
aid - AlterId
tls - 是否启用 TLS，为 0 或 1
allowInsecure - TLS 的 AllowInsecure，为 0 或 1
tlsServer - TLS 的服务器端证书的域名
mux - 是否启用 mux，为 0 或 1
muxConcurrency - mux 的 最大并发连接数
remark - 备注名称
导入配置时，不在列表中的参数一般会按照 Core 的默认值处理。

2、
>分享的链接（二维码）格式：vmess://(Base64编码的json格式服务器数据
json数据如下
{
"v": "2",
"ps": "备注别名",
"add": "111.111.111.111",
"port": "32000",
"id": "1386f85e-657b-4d6e-9d56-78badb75e1fd",
"aid": "100",
"net": "tcp",
"type": "none",
"host": "www.bbb.com",
"path": "/",
"tls": "tls"
}
v:配置文件版本号,主要用来识别当前配置
net ：传输协议（tcp\kcp\ws\h2)
type:伪装类型（none\http\srtp\utp\wechat-video）
host：伪装的域名
1)http host中间逗号(,)隔开
2)ws host
3)h2 host
path:path(ws/h2)
tls：底层传输安全（tls)

**Comment by deepbwork** [comment]
这个完全可以根据市场定夺，kitsunebi，v2rayNG, v2rayN都是采用一样的标准

**Comment by pipilupipixia** [comment]
@deepbwork 我发的两个里 第一个是kitsunebi的 第二个是v2rayn的

**Comment by pipilupipixia** [comment]
@deepbwork 可以参考：
[v2rayn](https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2))
[kit](https://eycorsican.github.io/kits-faq/)

**Comment by Nobitasean** [comment]
@pipilupipixia 不知道你有没有试过kit是可以扫描v2rayN的二维码的

**Comment by deepbwork** [comment]
@pipilupipixia kit是可以扫v2rayN的二维码的

**Comment by DarienRaymond** [comment]
Kamino closed and cloned this issue to v2ray/Planning

**Comment by zhuxiaoxi** [comment]
@pipilupipixia 我最近写一个脚本遇见了Quantumult这种订阅规则，不同于这两个，不过没找到定义文档。而且kitsunebi是支持v2rayn的规则的。
