### ISSUE TITLE
1.如何在ubuntu上卸载删除v2ray？2.如何更新ubuntu服务器端？

### ISSUE THREAD

**Issue by azgh** [v2ray/v2ray-core#114]

**Comment by aflyhorse** [comment]
1. 把所有安装进的软件删除即可，通常在 ```/usr/bin/v2ray``` 和 ```/etc/v2ray``` 内，如果你用的版本的ubuntu是用systemd，则在```/usr/lib/systemd/system/v2ray.service```，upstart不清楚
2. 重新运行一遍[安装脚本](https://github.com/v2ray/v2ray-core/blob/master/release/install-release.sh)即可
