### ISSUE TITLE
[Aliyun]违规信息整改通知

### ISSUE THREAD

**Issue by BenhoNNNN** [v2ray/v2ray-core#1145]
1)  你正在使用哪个版本的 V2Ray？
v2.46

2)  你的使用场景是什么？
PC/Phone >socks5> [AliyunVPS(Client)] >WebSocket+TLS> GFW >WebSocket+TLS> [Server]

3)  你看到的不正常的现象是什么？
这两天突然接到RT通知。
Aliyun自带的服务组件全部都禁用、删除过。V2Ray的进程也重命名过，日志也都禁用了。用了大半年，一直正常。只是 socks5 没有设置验证密码。

4)  你期待看到的正确表现是怎样的？
正常使用；
另外，墙内这段路有什么好的接入建议？

![aliyun](https://user-images.githubusercontent.com/12547424/41334754-42055870-6f19-11e8-8b72-a62a8c20c130.png)

**Comment by marswow** [comment]
非得用阿里云？？？？？？

**Comment by tonychanczm** [comment]
你的被举报了？

**Comment by tonychanczm** [comment]
请问你的是阿里云国内版吗？

**Comment by nxtreaming** [comment]
楼主犯了两个错误：
1）使用阿里云翻墙
2）使用搜狗输入法

这两个东西都会监控你。

-----------------------------------------
Productive. Reliable. Fast.

**Comment by likfe** [comment]
自己打包，修改进程名

**Comment by nobody3u** [comment]
服务提供商想查代理是很简单的。
只要进出的网络流量相近（线性相关），
通常是在运行代理软件。
然后查下ip进出记录就可以确定了。
再怎么加密、混淆都只是自我安慰。

所以，还是换一家吧。

**Comment by jasonliul** [comment]
@nobody3u 
请勿惊扰他人中国梦, 大大~~ :)

**Comment by nxtreaming** [comment]
@nobody3u 实际阿里云不需要这么搞，他本身就能做到墙的功能，他能监控你所有流量，而一般发现某修流量他不识别，就假定你在翻墙了，这个GFW的工作原理一样，人家才不会浪费算力去破解所谓的加密流量呢，只需要怀疑就行了。

**Comment by Justsoos** [comment]
阿里云，腾讯云，其实早就知道你在干什么，想躲猫猫只是自欺欺人，只不过看腾讯、阿里背后靠山能不能撑得住它们赚这份快钱。
实在撑不住的时候，就拿你开一下刀。

**Comment by picorotab** [comment]
首先你应该卸载阿里云的"云盾"，这是一个帮助共党监控你的VPS的程序。

但我要说明，即便你删除了云盾的所有二进制并重启，甚至自行安装作业系统而不用阿里云提供之镜像，阿里云仍能够监控你——只要你的VPS出站与入站之流量相差无几，便可大致判断为用作充当代理服务器——这种情形在一般的各类应用服务器中很少见。

此外，在互联网路上使用socks5并不明智——这是一个被定义于1996年的**明文**协议，当时互联网路上并无对窃听有太多顾虑，很多协议(包括socks5)都未采用任何加密。这意味着你的ISP(以及阿里云)能直接看到你与国内中转服务器的通讯内容。这或是阿里云判定你违规的另一依据。

建议:

1. 使用国内小众的VPS充当中转服务器，它们受到的、来自IDC的监控力度或小一些。
2. 用haproxy或nginx的stream{}完成TCP中转，不要令你的IDC发现你的主机上运行v2ray。

如采用建议2，则拓扑可表示为:

浏览器==socks5==>v2ray客户端==WS-TLS==>中转服务器==WS-TLS==>(墙外)V2ray服务器===>目标地址

这样一来中转服务器便无法得知TLS中传输的是什么，国内中转服务器亦无需运行v2ray服务。

------

###这个账号是怎么回事?为何在此issue前无任何commit?

这是一个小号。出于对微软过去作为的不放心，建立此号以作身份隔离。

**Comment by nicholascw** [comment]
Not a issue.

**Comment by swang2019** [comment]
实测：忽略该邮件即可，至今收到xx封，服务从未暂停

**Comment by Justsoos** [comment]
都用不着监测进程和流量。
只要你阿里云出口经常访问的都是Google  Twitter的ip，就很显然知道你在做什麽了，而且不会误伤。
国内Vps最好是用来作中转加速，到海外vps落地,，海外只直连一到两个不敏感vps的IP。

**Comment by hangox** [comment]
楼主勇士啊，socket是没有加密的，你都敢用来裸奔

**Comment by Heisenberg0391** [comment]
> 首先你应该卸载阿里云的"云盾"，这是一个帮助共党监控你的VPS的程序。
> 
> 但我要说明，即便你删除了云盾的所有二进制并重启，甚至自行安装作业系统而不用阿里云提供之镜像，阿里云仍能够监控你——只要你的VPS出站与入站之流量相差无几，便可大致判断为用作充当代理服务器——这种情形在一般的各类应用服务器中很少见。
> 
> 此外，在互联网路上使用socks5并不明智——这是一个被定义于1996年的**明文**协议，当时互联网路上并无对窃听有太多顾虑，很多协议(包括socks5)都未采用任何加密。这意味着你的ISP(以及阿里云)能直接看到你与国内中转服务器的通讯内容。这或是阿里云判定你违规的另一依据。
> 
> 建议:
> 
> 1. 使用国内小众的VPS充当中转服务器，它们受到的、来自IDC的监控力度或小一些。
> 2. 用haproxy或nginx的stream{}完成TCP中转，不要令你的IDC发现你的主机上运行v2ray。
> 
> 如采用建议2，则拓扑可表示为:
> 
> 浏览器==socks5==>v2ray客户端==WS-TLS==>中转服务器==WS-TLS==>(墙外)V2ray服务器===>目标地址
> 
> 这样一来中转服务器便无法得知TLS中传输的是什么，国内中转服务器亦无需运行v2ray服务。
> 
> ### 这个账号是怎么回事?为何在此issue前无任何commit?
> 这是一个小号。出于对微软过去作为的不放心，建立此号以作身份隔离。

tls似乎不支持tcp中转？
