### ISSUE TITLE
geoip:cn geoip:jp无效

### ISSUE THREAD

**Issue by ilikecola** [v2ray/v2ray-core#1146]
Please skip to the English section below if you don't write Chinese.

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
3.25.1
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
根据geoip分流
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
无法正常分流
4)  你期待看到的正确表现是怎样的？
根据geoip分流
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
```javascript
   "routing":{  
      "domainStrategy":"IPOnDemand",
      "strategy":"rules",
      "settings":{  
         "rules":[  
            {  
               "type":"field",
               "ip":[  
                  "0.0.0.0/8",
                  "10.0.0.0/8",
                  "100.64.0.0/10",
                  "127.0.0.0/8",
                  "169.254.0.0/16",
                  "172.16.0.0/12",
                  "192.0.0.0/24",
                  "192.0.2.0/24",
                  "192.168.0.0/16",
                  "198.18.0.0/15",
                  "198.51.100.0/24",
                  "203.0.113.0/24",
                  "::1/128",
                  "fc00::/7",
                  "fe80::/10"
               ],
               "inboundTag": [
                "L_vmess_inbound_kcp",
                "L_vmess_inbound_tcp",
                "L_in_detour_kcp",
                "L_in_detour_tcp",
                "C_in_vmess_inbound_kcp",
                "C_in_vmess_inbound_tcp",
                "C_in_detour_kcp",
                "C_in_detour_tcp"
                ],
               "outboundTag":"blocked"
            },
 {
               "type":"field",
               "inboundTag": [
                "L_vmess_inbound_kcp",
                "L_vmess_inbound_tcp",
                "L_in_detour_kcp",
                "L_in_detour_tcp"
                ],
                "outboundTag": "K2L",
                "ip":[
                  "geoip:cn"
               ]
            },
            {
               "type":"field",
               "inboundTag": [
                "L_vmess_inbound_kcp",
                "L_vmess_inbound_tcp",
                "L_in_detour_kcp",
                "L_in_detour_tcp"
                ],
                "outboundTag": "K2L",
                "ip":[
                  "geoip:jp"
               ]
            },
            {
               "type":"field",
               "inboundTag": [
                "C_in_vmess_inbound_kcp",
                "C_in_vmess_inbound_tcp",
                "C_in_detour_kcp",
                "C_in_detour_tcp"
                ],
                "outboundTag": "K2C",
                "ip":[
                  "geoip:jp"
               ]
                
            },
            {
               "inboundTag": [
                   "api"
                ],
                "outboundTag": "api",
                "type": "field"
            }
         ]
      }
   }
```
其中detour为动态端口的detour

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
2018/06/14 04:37:24 [Info] [1047851256] App|Proxyman|Mux: received request for tcp:sp0.baidu.com:443
2018/06/14 04:37:24 [Info] [1047851256] App|Dispatcher: default route for tcp:sp0.baidu.com:443

sp0.baidu.com 显然是geoip:cn范围 应该走K2L

感谢!!

**Comment by DarienRaymond** [comment]
sp0.baidu.com 这个域名会被解析多个 IP（见 https://www.whatsmydns.net/#A/sp0.baidu.com ）。取决于你的 DNS 配置，有可能没有解析到国内的 IP。

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!

**Comment by emacsnt** [comment]
should change domain policy from asis to other policy tfirst
