### ISSUE TITLE
无法将Shadowsocks作为inboundDetour

### ISSUE THREAD

**Issue by Ninzero** [v2ray/v2ray-core#1147]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

v3.25

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

测试使用Vmess和Shandowsocks 同时使用。

3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

当shaodwsocks作为inbound时可以正常使用shadowsocks连接,但作为inboundDetour则无法连接,确认过并非密码和端口等的问题。不能确定我对于inboundDetour的理解是否有误。检查过json文件符合语法。

4)  你期待看到的正确表现是怎样的？

可以同时使用shadowsocks和Vmess连接

5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
```javascript
    {
  "log":{
      "access": "~/v2rayLog/_access.log",
      "error": "~/v2rayLog/_error.log",
      "loglevel": "warning"
    }, 
  "inbound": {
      "port": ****,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "*************************",
            "alterId": 45,
            "level": 0
          }
        ],
        "disableInsecureEncryption": true,
        "streamSettings":{
          "network": "mkcp",
          "kcpSettings":{
            "mtu": 1350,
            "tti": 20,
            "uplinkCapacity": 10,
            "downlinkCapacity": 100,
            "congestion": false,
            "readBufferSize": 1,
            "writeBufferSize": 1,
            "header": {
              "type": "wechat-video"
            }
          }
        }
      }
    },
    "inboundDetour":{
        "protocol": "shadowsocks",
        "port": ****,
        "tag": "Shadowsocks",
        "listen": "127.0.0.1",
        "allocate": {
          "strategy": "always",
          "refresh": 5,
          "concurrency": 3
        },
        "settings": {
          "method": "chacha20-ietf-poly1305",
          "ota": false,
          "password": "************"
        }
    },
    "outbound": {
      "protocol": "freedom",  
      "settings": {}
    }
  }
```
客户端为ShadowsocksX-NG,版本 1.6.1(1)

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

未生成任何日志。

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

未生成任何日志。

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

V2Ray v3.25 (die Commanderin) 20180605
A unified platform for anti-censorship.
Main: failed to read config file: /etc/v2ray/config.json > Main|Json: failed to execute v2ctl to convert config file. > Command|Platform|CtlCmd: failed to execute v2ctl: Ext|Tools|Conf|Command: failed to parse json config > Ext|Tools|Conf|Serial: failed to read config file > json: cannot unmarshal object into Go struct field Config.inboundDetour of type []conf.InboundDetourConfig

 > exit status 255

**Comment by DarienRaymond** [comment]
InboundDetour是个数组，请仔细阅读配置文件的说明。 https://www.v2ray.com/chapter_02/01_overview.html

**Comment by Ninzero** [comment]
不好意思,才发现 @DarienRaymond
