### ISSUE TITLE
cross-compiling for openwrt

### ISSUE THREAD

**Issue by debiansid** [v2ray/v2ray-core#115]
Is it possible to compile v2ray for openwrt?

**Comment by lixingcong** [comment]
golang要用c重写吧，，openwrt这玩意跑py都力不从心。。

**Comment by debiansid** [comment]
I have openwrt on X86 which it powerful enough to run it

**Comment by v2ray** [comment]
ARM 和 i386 系列的 CPU 都可以运行，MIPS 由于 Golang 不支持我也没什么办法。 openwrt 本质上也是 Linux，有 SSH 权限就可以配置 V2Ray。至于 openwrt 的安装包，暂时没有时间做。

**Comment by debiansid** [comment]
root@openwrt-x86:/mnt/backup# ./v2ray -version
V2Ray 1.20 (New Order) Custom
An unified platform for anti-censorship.

ok, finally I made it work on x86 openwrt. thanks
