### ISSUE TITLE
请问游戏加速用什么配置最好？游戏延迟极大

### ISSUE THREAD

**Issue by GenjiWu** [v2ray/v2ray-core#1150]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
客户端3.25.1 服务端3.26
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
查看网页、DOTA2亚服游戏加速
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
DOTA2游戏延迟过高，直连200ms，开v2ray后500ms。
我到韩国vps的延迟为47ms，下载速度和上传速度都是200M满速，应该不是vps的问题
4)  你期待看到的正确表现是怎样的？
80ms左右的延迟
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
```javascript
    // 在这里附上服务器端配置文件
```

    客户端配置:
```javascript
{
  "log": {
      "loglevel": "warning"
  },
  "inbound": {
      "listen": "127.0.0.1",
      "port": 1080,
      "protocol": "socks",
      "settings": {
          "auth": "noauth",
          "udp": true,
          "ip": "127.0.0.1"
      }
  },
  "outbound": {
      "protocol": "vmess",
      "settings": {
          "vnext": [
              {
                  "address": "IP",
                  "port": 35279,
                  "users": [
                      {
                          "id": "ID",
                          "level": 1,
                          "alterId": 100
                      }
                  ]
              }
          ]
      }
  },
  "outboundDetour": [
      {
          "protocol": "freedom",
          "settings": {},
          "tag": "direct"
      }
  ],
  "routing": {
      "strategy": "rules",
      "settings": {
          "rules": [
              {
                  "type": "field",
                  "port": "54-79",
                  "outboundTag": "direct"
              },
              {
                  "type": "field",
                  "port": "81-442",
                  "outboundTag": "direct"
              },
              {
                  "type": "field",
                  "port": "444-65535",
                  "outboundTag": "direct"
              },
              {
                  "type": "field",
                  "domain": [
                      "gc.kis.scr.kaspersky-labs.com"
                  ],
                  "outboundTag": "direct"
              },
              {
                  "type": "chinasites",
                  "outboundTag": "direct"
              },
              {
                  "type": "field",
                  "ip": [
                      "0.0.0.0/8",
                      "10.0.0.0/8",
                      "100.64.0.0/10",
                      "127.0.0.0/8",
                      "169.254.0.0/16",
                      "172.16.0.0/12",
                      "192.0.0.0/24",
                      "192.0.2.0/24",
                      "192.168.0.0/16",
                      "198.18.0.0/15",
                      "198.51.100.0/24",
                      "203.0.113.0/24",
                      "::1/128",
                      "fc00::/7",
                      "fe80::/10"
                  ],
                  "outboundTag": "direct"
              },
              {
                  "type": "chinaip",
                  "outboundTag": "direct"
              }
          ]
      }
  }
}

    // 在这里附上客户端配置
```
{
    "log": {
        "access": "/var/log/v2ray/access.log",
        "error": "/var/log/v2ray/error.log",
        "loglevel": "warning"
    },
    "inbound": {
        "port": 35279,
        "protocol": "vmess",
        "settings": {
            "clients": [
                {
                    "id": "ID",
                    "level": 1,
                    "alterId": 100
                }
            ]
        }
    },
    "outbound": {
        "protocol": "freedom",
        "settings": {}
    },
    "inboundDetour": [],
    "outboundDetour": [
        {
            "protocol": "blackhole",
            "settings": {},
            "tag": "blocked"
        }
    ],
    "routing": {
        "strategy": "rules",
        "settings": {
            "rules": [
                {
                    "type": "field",
                    "ip": [
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "203.0.113.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10"
                    ],
                    "outboundTag": "blocked"
                }
            ]
        }
    }
}

**Comment by aaaxiaoganaaa** [comment]
先恶补一下網絡知識再來提問。

**Comment by TanNang** [comment]
建议使用低延时的主机作为 v2ray 服务端。

**Comment by GenjiWu** [comment]
是这样的啊，我到服务器的延迟只有47ms

**Comment by AAAxiaoxin** [comment]
你到服務器的MS不等於你的服務器到遊戲服務器的MS。

**Comment by Justsoos** [comment]
你至少还要测试，vps到dota2的延迟，才能下判断

**Comment by jackwangshanghai** [comment]
Try remove Routing Rules

**Comment by DarienRaymond** [comment]
Kamino closed and cloned this issue to v2ray/discussion
