### ISSUE TITLE
[功能建议] 在流量统计 API 中增加“清空统计信息”功能

### ISSUE THREAD

**Issue by t123yh** [v2ray/v2ray-core#1153]
服务端每次统计流量后，将流量数据清空，可以更准确地进行流量统计，不会漏计。如果没有清空功能，则必须记忆上次的查询结果并计算差值，不是很方便。

**Comment by alinuxsa** [comment]
`v2ctl api --server=127.0.0.1:10010 StatsService.GetStats 'name: "user>>>pc@gmail.com>>>traffic>>>downlink" reset: true'`

**Comment by DarienRaymond** [comment]
如上，reset设为true即清空，原子操作。
