### ISSUE TITLE
V2Ray 无法正常运行

### ISSUE THREAD

**Issue by SpaceWalkerMan** [v2ray/v2ray-core#1154]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

服务器客户端均为 V2Ray v3.26

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

同比如。

3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

无法访问此网站
facebook.com 意外终止了连接。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
运行 Windows 网络诊断
ERR_CONNECTION_CLOSED

4)  你期待看到的正确表现是怎样的？

正常访问。

5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:

```javascript

{
	"log": {
		"access": "/var/log/v2ray/access.log",
		"error": "/var/log/v2ray/error.log",
		"loglevel": "debug"
	},
	"inbound": {
		"port": 80,
		"protocol": "vmess",
		"settings": {
			"clients": [
				{
					"id": "xxxxxxxxxxxx",
					"level": 1,
					"alterId": 64
				}
			]
		},
		"streamSettings": {
			"network": "tcp",
			"tcpSettings": {
				"connectionReuse": true,
				"header": {
					"type": "http",
					"request": {
						"version": "1.1",
						"method": "GET",
						"path": [
							"/"
						],
						"headers": {
							"Host": [
								"www.baidu.com",
								"www.taobao.com",
								"www.tmall.com",
								"www.jd.com",
								"www.qq.com",
								"www.youku.com"
							],
							"User-Agent": [
								"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36",
								"Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
							],
							"Accept-Encoding": [
								"gzip, deflate"
							],
							"Connection": [
								"keep-alive"
							],
							"Pragma": "no-cache"
						}
					},
					"response": {
						"version": "1.1",
						"status": "200",
						"reason": "OK",
						"headers": {
							"Content-Type": [
								"application/octet-stream",
								"application/x-msdownload",
								"text/html",
								"application/x-shockwave-flash"
							],
							"Transfer-Encoding": [
								"chunked"
							],
							"Connection": [
								"keep-alive"
							],
							"Pragma": "no-cache"
						}
					}
				}
			}
		}
	},
	"outbound": {
		"protocol": "freedom",
		"settings": {
		}
	},
	"inboundDetour": [
		{
			"protocol": "shadowsocks",
			"port": 99,
			"settings": {
				"method": "aes-256-cfb",
				"password": "password",
				"udp": true,
				"level": 1
			}
		}
	],
	"outboundDetour": [
		{
			"protocol": "blackhole",
			"settings": {
			},
			"tag": "blocked"
		}
	],
	"routing": {
		"strategy": "rules",
		"settings": {
			"rules": [
				{
					"type": "field",
					"ip": [
						"0.0.0.0/8",
						"10.0.0.0/8",
						"100.64.0.0/10",
						"127.0.0.0/8",
						"169.254.0.0/16",
						"172.16.0.0/12",
						"192.0.0.0/24",
						"192.0.2.0/24",
						"192.168.0.0/16",
						"198.18.0.0/15",
						"198.51.100.0/24",
						"203.0.113.0/24",
						"::1/128",
						"fc00::/7",
						"fe80::/10"
					],
					"outboundTag": "blocked"
				}
			]
		}
	}
}

```

    客户端配置:

```javascript
{
	"log": {
		"loglevel": "debug"
	},
	"inbound": {
		"listen": "127.0.0.1",
		"port": 1080,
		"protocol": "socks",
		"settings": {
			"auth": "noauth",
			"udp": true,
			"ip": "127.0.0.1"
		}
	},
	"outbound": {
		"protocol": "vmess",
		"settings": {
			"vnext": [
				{
					"address": "xxxxxxxxxx",
					"port": 80,
					"users": [
						{
							"id": "xxxxxxxxxxxx",
							"level": 1,
							"alterId": 64
						}
					]
				}
			]
		},
		"streamSettings": {
			"network": "tcp",
			"tcpSettings": {
				"connectionReuse": true,
				"header": {
					"type": "http",
					"request": {
						"version": "1.1",
						"method": "GET",
						"path": [
							"/"
						],
						"headers": {
							"Host": [
								"www.baidu.com",
								"www.taobao.com",
								"www.tmall.com",
								"www.jd.com",
								"www.qq.com",
								"www.youku.com"
							],
							"User-Agent": [
								"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36",
								"Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
							],
							"Accept-Encoding": [
								"gzip, deflate"
							],
							"Connection": [
								"keep-alive"
							],
							"Pragma": "no-cache"
						}
					},
					"response": {
						"version": "1.1",
						"status": "200",
						"reason": "OK",
						"headers": {
							"Content-Type": [
								"application/octet-stream",
								"application/x-msdownload",
								"text/html",
								"application/x-shockwave-flash"
							],
							"Transfer-Encoding": [
								"chunked"
							],
							"Connection": [
								"keep-alive"
							],
							"Pragma": "no-cache"
						}
					}
				}
			}
		},
		"mux": {
			"enabled": false
		}
	},
	"outboundDetour": [
		{
			"protocol": "freedom",
			"settings": {
			},
			"tag": "direct"
		}
	],
	"dns": {
		"servers": [
			"8.8.8.8",
			"8.8.4.4",
			"localhost"
		]
	},
	"routing": {
		"strategy": "rules",
		"settings": {
			"rules": [
				{
					"type": "chinasites",
					"outboundTag": "direct"
				},
				{
					"type": "chinaip",
					"outboundTag": "direct"
				},
				{
					"type": "field",
					"ip": [
						"0.0.0.0/8",
						"10.0.0.0/8",
						"100.64.0.0/10",
						"127.0.0.0/8",
						"169.254.0.0/16",
						"172.16.0.0/12",
						"192.0.0.0/24",
						"192.0.2.0/24",
						"192.168.0.0/16",
						"198.18.0.0/15",
						"198.51.100.0/24",
						"203.0.113.0/24",
						"::1/128",
						"fc00::/7",
						"fe80::/10"
					],
					"outboundTag": "direct"
				}
			]
		}
	}
}

```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:

access.log

2018/06/21 18:20:59 xxxxx:49040 rejected  Proxy|VMess|Encoding: failed to read request header > read tcp IPAddress:Port->xxxxx:49040: i/o timeout
2018/06/21 18:25:15 xxxxx:62235 rejected  Proxy|VMess|Encoding: failed to read request header > read tcp IPAddress:Port->xxxxx:62235: i/o timeout

error.log

2018/06/21 18:23:05 [Debug] App|Log: Logger started
2018/06/21 18:23:05 [Warning] Core: V2Ray v3.26 started
2018/06/21 18:24:53 [Debug] App|Log: Logger started
2018/06/21 18:24:53 [Warning] Core: V2Ray v3.26 started
2018/06/21 18:25:15 [Info] [2552770636] App|Proxyman|Inbound: connection ends > Proxy|VMess|Inbound: invalid request from xxxxx:62235 > Proxy|VMess|Encoding: failed to read request header > read tcp IPAddress:Port->xxxxx:62235: i/o timeout

    客户端错误日志:

V2Ray v3.26 (die Commanderin) 20180614
A unified platform for anti-censorship.
2018/06/20 18:25:06 [Debug] App|Log: Logger started
2018/06/20 18:25:06 [Warning] Core: V2Ray v3.26 started
2018/06/20 18:25:11 [Info] [201449661] Proxy|Socks: TCP Connect request to tcp:facebook.com:443
2018/06/20 18:25:11 [Info] [201449661] App|Dispatcher: default route for tcp:facebook.com:443
2018/06/20 18:25:11 [Info] [201449661] Transport|Internet|TCP: dialing TCP to tcp:IPAddress:Port
2018/06/20 18:25:11 tcp:127.0.0.1:62232 accepted tcp:facebook.com:443
2018/06/20 18:25:11 [Info] [201449661] Proxy|VMess|Outbound: tunneling request to tcp:facebook.com:443 via tcp:IPAddress:Port
2018/06/20 18:25:11 [Info] [201449661] App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > Proxy|VMess|Outbound: failed to read header > Proxy|VMess|Encoding: failed to read response header > EOF
2018/06/20 18:25:11 [Info] [201449661] App|Proxyman|Inbound: connection ends > Proxy|Socks: connection ends > Proxy|Socks: failed to transport all TCP response > io: read/write on closed pipe
2018/06/20 18:25:11 [Info] [2419378399] Proxy|Socks: TCP Connect request to tcp:facebook.com:443
2018/06/20 18:25:11 [Info] [2419378399] App|Dispatcher: default route for tcp:facebook.com:443
2018/06/20 18:25:11 [Info] [2419378399] Transport|Internet|TCP: dialing TCP to tcp:IPAddress:Port
2018/06/20 18:25:11 tcp:127.0.0.1:62234 accepted tcp:facebook.com:443
2018/06/20 18:25:11 [Info] [2419378399] Proxy|VMess|Outbound: tunneling request to tcp:facebook.com:443 via tcp:IPAddress:Port
2018/06/20 18:25:16 [Info] [2419378399] App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > Proxy|VMess|Outbound: failed to read header > Proxy|VMess|Encoding: failed to read response header > EOF
2018/06/20 18:25:16 [Info] [2419378399] App|Proxyman|Inbound: connection ends > Proxy|Socks: connection ends > Proxy|Socks: failed to transport all TCP response > io: read/write on closed pipe

**Comment by DarienRaymond** [comment]
Kamino closed and cloned this issue to v2ray/discussion

**Comment by willerhehehe** [comment]
I fixed it  by  synchronised  the client time and server time

**Comment by CJuNing** [comment]
同步本机时间和Internet时间一致

**Comment by Bohan-Song** [comment]
> 同步本机时间和Internet时间一致

Windows用哪个同步服务器 我遇到相同的问题了 总是断联
