### ISSUE TITLE
[solved] thunderbird/evolution邮件客户端无法使用v2ray，但浏览器可以使用

### ISSUE THREAD

**Issue by imapproxy** [v2ray/v2ray-core#1157]
中文：
已解決：客戶端routing中添加端口993,465,587即可。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
服务器端和客户端都是v3.26
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
thunderbird/evolution 使用gmail app password通过socks代理接收和发送gmail邮件
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
evolution客户端tls握手失败；thunderbird客户端无法验证用户名和密码，但是状态栏显示已经连接到imap.gmail.com
4)  你期待看到的正确表现是怎样的？
至少可以使用gmail app password通过socks代理使用gmail；如果两步验证oauth2也能使用是最好
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
```javascript
    
```
    客户端配置:

```javascript
    
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
/var/log/v2ray/error.log中未发现v3.26的错误日志
```
    // 在这里附上服务器端日志
```
    客户端错误日志:
/var/log/v2ray/error.log 该v2ray文件夹为空文件夹，无error.log文件
```
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
无最近的日志，只有4月份的访问日志

```
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。
可以启动
通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。
运行正常
通常的命令为 `journalctl -u v2ray`。

**Comment by homanw104** [comment]
中文：
请问有无问题解决后的配置样例？谢谢。

**Comment by imapproxy** [comment]
很久没用了v2ray了, 当时没保存

> 
> 
> 中文：
> 请问有无问题解决后的配置样例？谢谢。

**Comment by YijunYuan** [comment]
> 中文：
> 已解決：客戶端配置的routing中添加端口993,465,587即可。
> 
> 1. 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
>    服务器端和客户端都是v3.26
> 2. 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
>    thunderbird/evolution 使用gmail app password通过socks代理接收和发送gmail邮件
> 3. 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
>    evolution客户端tls握手失败；thunderbird客户端无法验证用户名和密码，但是状态栏显示已经连接到imap.gmail.com
> 4. 你期待看到的正确表现是怎样的？
>    至少可以使用gmail app password通过socks代理使用gmail；如果两步验证oauth2也能使用是最好
> 5. 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
>    服务器端配置:
> 
> ```js
>     
> ```
> 
> ```
> 客户端配置:
> ```
> 
> ```js
>     
> ```
> 
> 1. 请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
>    服务器端错误日志:
>    /var/log/v2ray/error.log中未发现v3.26的错误日志
> 
> ```
>     // 在这里附上服务器端日志
> ```
> 
> ```
> 客户端错误日志:
> ```
> 
> /var/log/v2ray/error.log 该v2ray文件夹为空文件夹，无error.log文件
> 
> ```
>     // 在这里附上客户端日志
> ```
> 
> 1. 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
>    无最近的日志，只有4月份的访问日志
> 
> ```
>     // 在这里附上服务器端日志
> ```
> 
> 1. 其它相关的配置文件（如 Nginx）和相关日志。
> 2. 如果 V2Ray 无法启动，请附上 `--test` 输出。
>    可以启动
>    通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。
> 3. 如果 V2Ray 服务运行不正常，请附上 journal 日志。
>    运行正常
>    通常的命令为 `journalctl -u v2ray`。

请问具体应该如何修改？是否能提供样例？谢谢。
