### ISSUE TITLE
raw:failed to read response header:EOF这个是怎么回事。。。

### ISSUE THREAD

**Issue by ToyoDAdoubi** [v2ray/v2ray-core#116]
raw:failed to read response header:EOF
VMessOut:Failed to read response:EOF
使用v2ray时提示这个，翻不出去...

**Comment by gakiyuibo** [comment]
同样问题

**Comment by v2ray** [comment]
看一下服务器的日志，多数情况是认证失败了。

**Comment by monsterjack** [comment]
@ghost 大佬问一下,升级到3.14还是有这个问题怎么办？

**Comment by monsterjack** [comment]
认证失败是什么意思呢？

**Comment by decemer** [comment]
同样问题

**Comment by tcstory** [comment]
@mrdulin 好像确实通过这个办法解决了....... 之所以用"好像"是因为我在服务器A上设置了头部为 `utp`后, 就能连接上了, 但是服务器B没有设置头部,默认为`none`, 在没有设置服务器A之前, 是有问题的, 但是在服务器A设置好后, 服务器B也能连接上了.....太玄学了.

**Comment by ntgeralt** [comment]
检查时钟校时

**Comment by michaeledi** [comment]
> 检查时钟校时

完美解决~感谢！

**Comment by chazhongbao** [comment]
> 检查时钟校时

排查了2个小时，终于搞定了，之前测试修改了电脑时间

**Comment by initialneil** [comment]
同样的问题，Windows。我手动把时间改错，重启 v2ray，再改回成网络授时，终于好了。

**Comment by WuYufeng233** [comment]
系统时间不对，更新系统时间同步好了
