### ISSUE TITLE
pybitmessage raise 'Command not supported' Socks5Error:7 on DNS resolving

### ISSUE THREAD

**Issue by peter-tank** [v2ray/v2ray-core#1160]
Please read the [instruction](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md) and answer the following questions before submitting your issue. Thank you.
Please answer all the questions with enough information. All issues not following this template will be closed immediately.
 
1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

`V2Ray 3.27 (die Commanderin) Custom`
 
2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

`pybitmessage > V2Ray.inbound: socks5://127.0.0.1:1080 >> V2Ray.mkcp`

 
3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)

>- ERROR - SOCKS DNS resolving failed
>Traceback(most recent call last):
>  File "/media/Downloads/BitMessage/src/helper_bootstrap.py", line 73, in dns
>ip = sock.resolve("bootstrap" + str(port) + ".bitmessage.org")
>File "/media/Downloads/BitMessage/src/socks/__init__.py", line 460, in resolve
>return self.__resolvesocks5(host)
>File "/media/Downloads/BitMessage/src/socks/__init__.py", line 275, in __resolvesocks5
>raise Socks5Error((ord(resp[1: 2]), _socks5errors[ord(resp[1: 2])]))
>Socks5Error: (7, 'Command not supported')

4) What's your expectation?
 
5) Please attach your configuration file (**Mask IP addresses before submit this issue**).
 
    pybitmessage error raised on:
```python
def __resolvesocks5(self, host): #Now we can request the actual connection
req = struct.pack('BBB', 0x05, 0xF0, 0x00)
req += chr(0x03).encode() + chr(len(host)).encode() + host
req = req + struct.pack(">H", 8444)
self.sendall(req)# Get the response
ip = ""
resp = self.__recvall(4)
if resp[0: 1] != chr(0x05).encode():
  self.close()
raise GeneralProxyError((1, _generalerrors[1]))
elif resp[1: 2] != chr(0x00).encode(): #Connection failed
self.close()
if ord(resp[1: 2]) <= 8:
  raise Socks5Error((ord(resp[1: 2]), _socks5errors[ord(resp[1: 2])]))
else :
  raise Socks5Error((9, _socks5errors[9]))
```
 
    Client configuration:
```javascript
    // Please attach your client configuration here.
```
 
6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.
 
    Server error log:
```
    // Please attach your server error log here.
```
    Client error log:
```
    // Please attach your client error log here.
```
 
7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.
```
    // Please attach your server access log here.
```
 
Please review your issue before submitting.
 
8) Other configurations (such as Nginx) and logs.
 
9) If V2Ray doesn't run, please attach output from `--test`.
 
The command is usually `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`, but may vary according to your scenario.
 
10) If V2Ray service doesn't run, please attach journal log.
 
Usual command is `journalctl -u v2ray`.

**Comment by DarienRaymond** [comment]
Please attach your V2Ray config which opens Socks5 inbound, and make sure that the socks inbound accepts UDP payload.

**Comment by peter-tank** [comment]
Thanks,
Then, I did more test to minimize the config file
inbound:

```javascript
 "inbound": {
  "port": 1080, 
  "tag": "inbound", 
  "protocol": "socks", 
  "listen": "127.0.0.1", 
  "settings": {
   "auth": "noauth", 
   "udp": true, 
   "ip": "127.0.0.1", 
   "timeout": 300
  }
 }
```
routing.settings.domainStrategy = "AsIs"
dns.servers = []
transport.kcpSettings.congestion = true
outbound.streamSettings.network = "kcp"

* full version of client.json
```javascript
{
 "log": {
  "access": "/mnt/sdcard/v2ray/access.log", 
  "error": "/mnt/sdcard/v2ray/error.log", 
  "loglevel": "debug"
 }, 
 "inbound": {
  "port": 1080, 
  "protocol": "socks", 
  "listen": "127.0.0.1", 
  "settings": {
   "auth": "noauth", 
   "udp": true, 
   "ip": "127.0.0.1", 
   "timeout": 300
  }
 }, 
 "outbound": {
  "protocol": "vmess", 
  "settings": {
   "vnext": [
    {
     "address": "{VPS_IP}", 
     "port": 10900, 
     "users": [
      {
       "id": "{VMESS_USER_ID}", 
       "alterId": 100, 
       "security": "chacha20-poly1305"
      }
     ]
    }
   ]
  }, 
  "streamSettings": {
   "network": "kcp"
  }
 }, 
 "outboundDetour": [
  {
   "protocol": "blackhole", 
   "tag": "block_request", 
   "settings": {
    "response": {
     "type": "http"
    }
   }
  }, 
  {
   "protocol": "freedom", 
   "settings": {
    "domainStrategy": "AsIs", 
    "timeout": 0
   }, 
   "tag": "direct"
  }
 ], 
 "dns": {
 "servers": ["8.8.8.8"]
 },
 "routing": {
  "strategy": "rules", 
  "settings": {
   "domainStrategy": "AsIs", 
   "rules": [
    {
     "type": "field", 
     "ip": [
      "geoip:private"
     ], 
     "outboundTag": "direct"
    }
   ]
  }
 }
}

```
* on `dns.servers = []`
** error.log
```
[Info] [3450331400] App|Proxyman|Inbound: connection ends > Proxy|Socks: failed to read request > Proxy|Socks: unknown command 240
[Info] [2340882369] App|Proxyman|Inbound: connection ends > Proxy|Socks: failed to read request > Proxy|Socks: unknown command 240
[Info] [4123624537] App|Proxyman|Inbound: connection ends > Proxy|Socks: failed to read request > Proxy|Socks: failed to read request > EOF
```
** access.log
```
tcp:127.0.0.1:39196 rejected  Proxy|Socks: unknown command 240
tcp:127.0.0.1:39198 rejected  Proxy|Socks: unknown command 240
tcp:127.0.0.1:39204 rejected  Proxy|Socks: failed to read request > EOF
```

* on `dns.servers = ["8.8.8.8"]` , just the same `unknown command 240` error
** error.log
```
[Info] [720784354] App|Proxyman|Inbound: connection ends > Proxy|Socks: failed to read request > Proxy|Socks: unknown command 240
[Info] [2098878254] App|Proxyman|Inbound: connection ends > Proxy|Socks: failed to read request > Proxy|Socks: unknown command 240
[Info] [1902820848] Proxy|Socks: TCP Connect request to tcp:166.175.191.127:8444
[Info] [1902820848] App|Dispatcher: default route for tcp:166.175.191.127:8444
[Info] [1902820848] Proxy|VMess|Outbound: tunneling request to tcp:166.175.191.127:8444 via tcp:{VPS_IP}:10900
[Info] [1902820848] App|Proxyman|Inbound: connection ends > Proxy|Socks: connection ends > Proxy|Socks: failed to transport all TCP request > read tcp 127.0.0.1:1080->127.0.0.1:39246: read: connection reset by peer
[Info] [1902820848] App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > context canceled
```
** access.log
```
tcp:127.0.0.1:39238 rejected  Proxy|Socks: unknown command 240
tcp:127.0.0.1:39240 rejected  Proxy|Socks: unknown command 240
tcp:127.0.0.1:39246 accepted tcp:166.175.191.127:8444
```
* traces:

> `sock.setproxy(2, localhost, 1080, True)`
> `sock.resolve("bootstrap8444.bitmessage.org")`

* `ping bootstrap8444.bitmessage.org` returns very diffrent ips every time.
* `curl -x socks5://127.0.0.1:1080 http://bootstrap8444.bitmessage.org` returns OK once on (li439-12.members.linode.com, 50.116.53.12)
* curl 7.37.0 (x86_64-suse-linux-gnu)

**Comment by DarienRaymond** [comment]
The command 240 (0xF0) is a Tor specific usage in socks5. It is not a standard socks5 command and V2Ray currently doesn't understand it. There is few description on how the command works. It will take a while for V2Ray to support it (properly).

**Comment by VictoriaRaymond** [comment]
0xF0 and 0xF0 are supports in latest V2Ray release. Although they may not behave as Tor expected, this is the best we can do for now.
