### ISSUE TITLE
V2ray only use IP addr when both Domain name and IP addr are provided in sock5. 

### ISSUE THREAD

**Issue by suicuneyuheng** [v2ray/v2ray-core#1163]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
3.26
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
Using Proxifier proxy chrome via Sock5
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
When Proxifier passes both domain name and IP via sock5 to v2ray but unfortunately this IP was poisoned. V2ray used poisoned domain's IP addr directly, passing it to remote server without it's domain name. And remote server used a wrong IP to open a proxy connection. And we got a proxy connection timeout.
4)  你期待看到的正确表现是怎样的？
Indeed, we got a wrong IP addr because of GFW. But if v2ray can use domain name instead of IP addr which they all provided by Proxifier via sock5, passing to the remote server. Remote server can use this domain name and resolve it and get the IP addr currently. The proxy will work as expected.
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
```javascript
    "inbound": {
		"port": 443,
		"protocol": "vmess",
		"settings": {
			"clients": [
				{
					"id": "*************************",
					"level": 0,
					"alterId": 0,
					"email": "**************"
				}
			]
		}
	},
    // 在这里附上服务器端配置文件
```

    客户端配置:
```javascript
	"inbound": {
        "listen": "127.0.0.1",
        "port": 20003,
        "protocol": "socks",
        "settings": {
            "auth": "noauth",
            "udp": true,
            "ip": "127.0.0.1"
        }
    },
	"outbound":{
			"tag": "proxy",
			"protocol": "vmess",
			"settings": {
				"vnext": [
					{
						"address": "**************",
						"port": 443,
						"users": [
							{
								"id": "***************",
								"level": 0,
								"alterId": 0,
								"security": "none"
							}
						]
					}
				]
			}
		},

    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
```
null
    // 在这里附上服务器端日志
```

    客户端错误日志:
```
null
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
```
client's log:
sock5 when domain name (www.google.com) and ip (poisoned) are provided.
2018/06/27 08:47:01 tcp:127.0.0.1:59887 accepted tcp:208.43.170.231:443

sock5 when only domain name (www.google.com) is provided.
2018/06/27 08:49:19 tcp:127.0.0.1:59932 accepted tcp:www.google.com:443

remote server's log :   
sock5 when domain name (www.google.com) and ip (poisoned) are provided.
2018/06/27 08:47:02 tcp:*******:25566 accepted tcp:208.43.170.231:443

sock5 when only domain name (www.google.com) is provided.
2018/06/27 08:49:21 tcp:*********:45340 accepted tcp:www.google.com:443
```

Have a nice day, sir.

**Comment by DarienRaymond** [comment]
Enable `domainOverride` on your socks inbound. 

https://www.v2ray.com/chapter_02/01_overview.html#%E4%B8%BB%E4%BC%A0%E5%85%A5%E8%BF%9E%E6%8E%A5%E9%85%8D%E7%BD%AE%EF%BC%88inbound%EF%BC%89

**Comment by suicuneyuheng** [comment]
@DarienRaymond 
I enable `domainOverride` .  And this issue solved.
Why not use domain name first by default if both domain name and ip are provided. After all it do not need to be sniffed. And if connection is not either TLS or HTTP, V2ray can still proxy it even if its DNS result is poisoned. 😀
Thank you for your reply and your time.

**Comment by DarienRaymond** [comment]
AFAIK, socks protocol can't provide both domain and IP at the same time. It should be either IP (in your case) or domain in the socks handshake.
