### ISSUE TITLE
V2Ray配置文件没有通过测试，请检查设置!!!

### ISSUE THREAD

**Issue by Suidge** [v2ray/v2ray-core#1169]
我用的配置文件完全是以前刷机前用的版本。新刷机后就出现了这个问题。重刷了好几遍机也没有变化。log如下：

【2018年06月27日 20:16:14】: ---------------------- LEDE 固件 v2ray -----------------------
【2018年06月27日 20:16:14】: v2ray符合启动条件！~
【2018年06月27日 20:16:14】: 重启dnsmasq服务...
【2018年06月27日 20:16:17】: 尝试先清除已存在的iptables规则，防止重复添加
【2018年06月27日 20:16:18】: 先清空已存在的ipset名单，防止重复添加
【2018年06月27日 20:16:18】: 清除重复的ip rule规则.
【2018年06月27日 20:16:18】: 删除ip route规则.
【2018年06月27日 20:16:18】: 清除firewall中相关的 v2ray 启动命令...
【2018年06月27日 20:16:18】: 创建国内CDN解析优化配置文件
【2018年06月27日 20:16:18】: 创建国外GFW解析优化配置文件
【2018年06月27日 20:16:18】: 创建状态检测解析优化配置文件
【2018年06月27日 20:16:18】: 应用域名黑名单
【2018年06月27日 20:16:18】: DNS解析方案国外优先，优先解析国外DNS.
【2018年06月27日 20:16:18】: 添加nat-start触发事件...
【2018年06月27日 20:16:18】: 使用自定义 v2ray 配置文件...
【2018年06月27日 20:16:18】: 解析V2Ray配置文件...
【2018年06月27日 20:16:18】: V2Ray配置文件写入成功到/koolshare/v2ray/v2ray.json
【2018年06月27日 20:16:18】: 检测到你的json配置的v2ray服务器是：
【2018年06月27日 20:16:18】: 测试V2Ray配置文件.....
【2018年06月27日 20:16:18】: V2Ray配置文件没有通过测试，请检查设置!!!
【2018年06月27日 20:16:18】: 插件将在5秒后自动关闭！！
【2018年06月27日 20:16:19】: 5
【2018年06月27日 20:16:20】: 4
【2018年06月27日 20:16:21】: 3
【2018年06月27日 20:16:22】: 2
【2018年06月27日 20:16:23】: 1
【2018年06月27日 20:16:24】: 0
【2018年06月27日 20:16:29】: 插件已关闭！！
【2018年06月27日 20:16:29】: ------------------------- v2ray 成功关闭 -------------------------

**Comment by choicky** [comment]
ref： https://itlaws.cn/post/openwrt-guide/
