### ISSUE TITLE
从网上和教程看到两种DNS配置方法，请教他们有什么区别？

### ISSUE THREAD

**Issue by princelai** [v2ray/v2ray-core#1170]
Please skip to the English section below if you don't write Chinese.

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
```
v2ray -version                                                                                                                                                 
V2Ray 3.27 (die Commanderin) Custom
```
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
用chromium通过switchyomega代理上国外网站

3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
DNS解析很慢，电脑上偶尔断流

4)  你期待看到的正确表现是怎样的？
不用国内被污染的DNS的同时加快DNS解析，如果可以的话，最好是国内网址和IP走国内DNS，国外的走8.8.8.8

5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
不涉及服务端

    客户端配置:
自己用的方案是h2+tls，上网正常，只是想配置下DNS，请教如下两种DNS配置的区别
```javascript
{
  "inbound": {},
  "outbound": {},
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {}
}

```

第二种
```javascript
{
  "inboundDetour": [
    {
      "protocol": "http",
      "port": 80,
      "settings": {
        "timeout": 8
      }
    },
    {
      "protocol": "dokodemo-door",
      "port": 53,
      "settings": {
        "address": "8.8.8.8",
        "port": 53,
        "network": "udp",
        "timeout": 0
      }
    }
  ]
}
```
第一种是不是意味着全局DNS都走8.8.8.8，而且还要在routing-->rules里加一个field，让53端口走udp。
第二种通常用在什么地方？

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
没有错误

    客户端错误日志:
没有错误

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
访问正常

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

**Comment by nicholascw** [comment]
第一种即所有通过 V2Ray 的流量使用您列出的 DNS 服务器, 而第二种是在您本机53端口转发远程 DNS 服务器的流量,即本机所有试用本机53端口的流量将使用来自 8.8.8.8 的结果. RTFM.
