### ISSUE TITLE
An established connection was aborted by the software in your host machine.

### ISSUE THREAD

**Issue by niguolaiya** [v2ray/v2ray-core#1177]
Please skip to the English section below if you don't write Chinese.

中文：

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
  3.27版

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
firefox浏览器 用socks/vmess 上youtube

3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
上网正常，，能用youtube就是log里老是会有报错，有的时候确实感觉延迟高点，打开慢点

4)  你期待看到的正确表现是怎样的？
期待log不报错
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
```javascript
    // 在这里附上服务器端配置文件
```

    客户端配置:
```javascript
    {
  "log": {
  "loglevel": "warning", // 日志级别
  "access": "C:\\v2ray\\access.log",  // 这是 Windows 系统的路径
  "error": "C:\\v2ray\\error.log"
},
  "inbound": {
    "port": 1080,  // SOCKS 代理端口，在浏览器中需配置代理并指向这个端口
    "listen": "127.0.0.1",
    "protocol": "socks",
    "domainOverride": ["http", "tls"],
    "settings": {
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [{
        "address": "", // 服务器地址，请修改为你自己的服务器 ip 或域名
        "port": 10086,  // 服务器端口
        "users": [
          {
             "id": "160e1c18-a3f5-46ce-8366-342db808ad2a",
             "alterId": 32,
             "security": "auto",
             "level": 0
             }
           ]
      }]
    }
  },
  "mux": {
    "enabled": true,
    "concurrency": 8
  },
  "outboundDetour": [{
    "protocol": "freedom",
    "tag": "direct",
    "settings": {}
  }],
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPOnDemand",
      "rules": [{
        "type": "field",
        "ip": [
          "0.0.0.0/8",
          "10.0.0.0/8",
          "100.64.0.0/10",
          "127.0.0.0/8",
          "169.254.0.0/16",
          "172.16.0.0/12",
          "192.0.0.0/24",
          "192.0.2.0/24",
          "192.168.0.0/16",
          "198.18.0.0/15",
          "198.51.100.0/24",
          "203.0.113.0/24",
          "::1/128",
          "fc00::/7",
          "fe80::/10"
        ],
        "outboundTag": "direct"
      }
    ],
    "domainStrategy": "IPIfNonMatch",
    "rules": [{
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
      }]
    }
  }
}
// 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
```
2018/06/30 18:29:10 [Warning] Core: V2Ray v3.27 started
2018/06/30 18:41:50 [Warning] Core: V2Ray v3.27 started
2018/07/01 12:38:36 [Warning] Core: V2Ray v3.27 started
    


    客户端错误日志（有两种）:
```2018/07/01 14:48:06 tcp:127.0.0.1:13915 rejected  Proxy|Socks: failed to read request > read tcp 127.0.0.1:1080->127.0.0.1:13915: wsarecv: An established connection was aborted by the software in your host machine.
2018/07/01 14:36:56 [Warning] [3418110] App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: failed to find an available destination > Retry: [dial tcp 68.168.142.198:10086: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. dial tcp 68.168.142.198:10086: operation was canceled] > Retry: all retry attempts failed

  在这里附客户端访问日志（异常的只有这一种）
```2018/07/01 14:48:06 tcp:127.0.0.1:13914 rejected  Proxy|Socks: failed to read request > read tcp 127.0.0.1:1080->127.0.0.1:13914: wsarecv: An established connection was aborted by the software in your host machine.
2018/07/01 14:48:06 tcp:127.0.0.1:13915 rejected  Proxy|Socks: failed to read request > read tcp 127.0.0.1:1080->127.0.0.1:13915: wsarecv: An established connection was aborted by the software in your host machine.

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
```
2018/07/01 12:38:41 134.129.18.114:49151 accepted udp:8.8.8.8:53
2018/07/01 12:38:43 134.129.18.114:49153 accepted udp:8.8.8.8:53
2018/07/01 12:38:43 134.129.18.114:49156 accepted udp:8.8.8.8:53
2018/07/01 12:38:43 134.129.18.114:49157 accepted tcp:alt1-mtalk.google.com:443
2018/07/01 12:38:47 134.129.18.114:49159 accepted udp:8.8.8.8:53
2018/07/01 12:38:55 134.129.18.114:49165 accepted udp:8.8.8.8:53
2018/07/01 12:39:00 134.129.18.114:49170 accepted udp:8.8.8.8:53
2018/07/01 12:39:00 134.129.18.114:49171 accepted tcp:49.51.229.169:80
2018/07/01 12:39:00 134.129.18.114:49174 accepted udp:8.8.8.8:53
2018/07/01 12:39:00 134.129.18.114:49175 accepted tcp:push.airdroid.com:443
2018/07/01 12:41:37 134.129.18.114:49187 accepted udp:8.8.8.8:53
2018/07/01 12:41:37 134.129.18.114:49188 accepted udp:8.8.8.8:53
2018/07/01 12:41:37 134.129.18.114:49189 accepted tcp:mtalk.google.com:5228
2018/07/01 12:41:48 134.129.18.114:49193 accepted udp:8.8.8.8:53
2018/07/01 12:42:01 134.129.18.114:49199 accepted udp:139.198.120.194:19000
2018/07/01 12:42:02 134.129.18.114:49202 accepted tcp:103.229.215.11:7007
2018/07/01 12:42:27 134.129.18.114:49209 accepted udp:8.8.8.8:53
2018/07/01 12:42:37 134.129.18.114:49214 accepted tcp:47.74.170.157:5222
2018/07/01 12:43:38 134.129.18.114:49228 accepted udp:8.8.8.8:53

    // 在这里附上服务器端日志
```

其他都正常只是会报错，谢谢大家，看看怎么弄好，感觉应该哪里被挡了所以有点延迟

**Comment by 517030910405** [comment]
所以是怎么弄好的呢？

**Comment by jw-star** [comment]
已建立的连接已被主机中的软件中止。 说明有其他软件中断了连接，一般是杀毒软件，关闭杀毒软件，重新解压v2rayn,重新连接即可。
