### ISSUE TITLE
CentOS 6.5启动服务提示缺少vars.sh文件

### ISSUE THREAD

**Issue by supersonic600** [v2ray/v2ray-core#118]
具体情况如下：
按照新手入门－下载安装步骤，将v2ray下载到自己的vps中，启动服务时出现以下情况
[root@xxxx]# service v2ray start
/etc/init.d/v2ray: line 29: /lib/init/vars.sh: No such file or directory

目前，自己也在google寻找解决方案，post上来请遇到同样问题的人帮忙一下

many thanks

**Comment by v2ray** [comment]
自动运行脚本不支持 CentOS 6.x，请升级到 CentOS 7，或使用 Debian / Ubuntu。

**Comment by supersonic600** [comment]
谢谢！

**Comment by gwc0721** [comment]
@supersonic600 #101
[init.d script tested on CentOS 6.6](https://github.com/v2ray/v2ray-core/issues/101#issuecomment-214670792])
