### ISSUE TITLE
执行 ./v2ray 或 sudo ./v2ray皆报错 ./v2ray: ./v2ray: cannot execute binary file

### ISSUE THREAD

**Issue by XWolcen** [v2ray/v2ray-core#1180]
用docker 执行 手动部署V3.28  v2ray-linux-arm64.zip ，执行 ./v2ray 或 sudo ./v2ray皆报错 ./v2ray: ./v2ray: cannot execute binary file，我怀疑是不是缺少运行库啥的？因为我在宿主机上同样的也不能执行，因为压根不能执行，所以我也看不到错误日志。。。求帮助，谢谢！

**Comment by DarienRaymond** [comment]
你的CPU和下载的文件没有对应
