### ISSUE TITLE
Socks inbound doesn't work with ipv6 address

### ISSUE THREAD

**Issue by GarrisonBaird** [v2ray/v2ray-core#1181]
1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
- Client: `V2Ray v3.21 (die Commanderin) 20180423`
- Server: `V2Ray v3.24.1 (die Commanderin) 20180604`
2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
_Visit an IPv6 site using an IPv6 address directly, firefox/curl, via socks5 inbound and vmess outbound_
3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)
```
> `curl -x "socks5h://127.0.0.1:1080" "https://[2a00:1450:4007:816::200e]"`
< App|Proxyman|Inbound: connection ends > Proxy|Socks: failed to read request > Proxy|Socks: failed to read address > Protocol: invalid domain name: 2a00:1450:4007:816::200e
> `curl -x "http://127.0.0.1:8080" "https://[2a00:1450:4007:816::200e]"`
< tcp:127.0.0.1:39810 accepted tcp:[2a00:1450:4007:816::200e]:443
< App|Dispatcher: taking detour [vmess] for [tcp:[2a00:1450:4007:816::200e]:443]
```

5) Please attach your configuration file
    Client configuration:
```javascript
{
	"routing": {
		"strategy": "rules",
		"settings": {
			"domainStrategy": "AsIs",
			"rules": [
				{
					"type": "field",
					"inboundTag": ["socks", "http"],
					"outboundTag": "vmess"
				}
				// ...
			]
		}
	},
	"inboundDetour": [
		{
			"tag": "socks",
			"port": 1080,
			"protocol": "socks",
			"settings": {
				"auth": "noauth",
				"udp": true,
				"ip": "127.0.0.1"
			}
		},
		{
			"tag": "http",
			"port": 8080,
			"protocol": "http",
			"settings": {
				"timeout": 30,
				"allowTransparent": false
			}
		}
		// ...
	],
	"outboundDetour": [
		{
			"tag": "vmess",
			"protocol": "vmess",
			"settings": {
				"vnext": [
					{
						"address": "[server-ip]",
						"port": 443,
						"users": [
							{
								"id": "[uuid]",
								"alterId": 16,
								"security": "aes-128-gcm"
							}
						]
					}
				]
			},
			"proxySettings": {
				"tag": "out"
			},
			"mux": {"enabled": false, "concurrency": 8}
		},
		{
			"tag": "out",
			"protocol": "freedom",
			"settings": {
			}
		}
		// ...
	],
	"dns": {
		"hosts": {},
		"servers": [
			"localhost"
		]
	}
	// ...
}
```

**Comment by GarrisonBaird** [comment]
```
> curl -x "socks5://127.0.0.1:1080" "https://[2a00:1450:4007:816::200e]"
< curl: (51) SSL: no alternative certificate subject name matches target host name '2a00:1450:4007:816::200e'
> curl -x "socks5h://127.0.0.1:1080" "https://[2a00:1450:4007:816::200e]"
< curl: (7) Failed to receive SOCKS5 connect request ack.
> curl --version
< curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2l zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
```
:thinking:

**Comment by VictoriaRaymond** [comment]
V2Ray is supposed to support 'socks5h' with IP address, but you should use 'socks5' instead of 'socks5h', as 'socks5h' treats the address as domain.

And you should not use 'https://' as the server ([2a00:1450:4007:816::200e]) seems doesn't support https anyway.

**Comment by GarrisonBaird** [comment]
Please don't simply close an issue without any investigation
- `[2a00:1450:4007:816::200e]` is an IPv6 address of google.com with HTTPS support
- SSL error is expected, which shows IPv6 is working. Otherwise you can make a request with http, or use `https://[2606:4700:4700::1111]/` which has a valid SSL cert. But that doesn't matter anyway.
- Using Firefox doesn't work either, but both Firefox and cURL work fine with other proxy programs like Shadowsocks Python version
- The difference between `socks5`, `socks5h` and `http` shows that v2ray may have a problem handling the socks5 protocol

**Comment by GarrisonBaird** [comment]
Oh never mind, I didn't see you've fiexed this issue, sorry
