### ISSUE TITLE
mkcp协议配置问题

### ISSUE THREAD

**Issue by cjwddtc** [v2ray/v2ray-core#1185]
我对kcp不是非常了解，配置选项中的tti的含义让我十分困惑，我记得原版kcp协议是有控制多倍发包的选项的。我是用的线路是cn2 gia，几乎不存在丢包的问题，带宽固定（100mbps），如何配置kcp能够在这种情况下跑满带宽。

**Comment by dragonzhi** [comment]
tti就是控制flush时间间隔的，感觉就是每隔tti时间就发一次包，想跑满带宽应该uplinkCapacity/downlinkCapacity,并且相应的调大readBufferSize/writeBufferSize.
但是v2ray有个巨坑就是断流，自己玩玩可以，商用的话慎重。

**Comment by Kurobac** [comment]
@dragonzhi 请问这个断流的含义具体是什么？是突然延迟增大速度变慢还是完全无法连接？

**Comment by DarienRaymond** [comment]
Kamino closed and cloned this issue to v2ray/discussion
