### ISSUE TITLE
outbound部分Socks报错exit status 4294967295

### ISSUE THREAD

**Issue by OneWizard** [v2ray/v2ray-core#1186]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
3.29
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
想要v2ray 本地替代privoxy，因有部分服务由其他软件提供，需要连接本地socks5，报错后进行排查，目前看是socks5部分问题（是格式改了吗？）
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
按https://www.v2ray.com/chapter_02/protocols/socks.html#outbound 配置socks5，报错，不能运行
4)  你期待看到的正确表现是怎样的？

5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
无
    客户端配置:
```javascript
{
	"log": {
		"access": "",
		"error": "",
		"loglevel": ""
	},
	"inbound": {
		"port": 1086,
		"listen": "127.0.0.1",
		"protocol": "socks",
		"settings": {
			"auth": "noauth",
			"udp": true,
			"ip": "127.0.0.1",
			"clients": null
		},
		"streamSettings": null
	},
	"inboundDetour": null,
	"outbound": {
		"servers": [{
				"address": "127.0.0.1",
				"port": 1234,
				"users": [{
						"user": "test user",
						"pass": "test pass",
						"level": 0
					}
				]
			}
		]
	}
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
     客户端错误日志:
无
7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
无
8) 其它相关的配置文件（如 Nginx）和相关日志。
无
9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

Main: failed to read config file: D:\Program Files\ProxyTool\V2Ray\Core\config.json > Main|Json: failed to execute v2ctl to convert config file. > Command|Platform|CtlCmd: failed to execute v2ctl: Ext|Tools|Conf|Command: failed to parse json config > Ext|Tools|Conf|Serial: failed to parse json config > Ext|Tools|Conf: failed to parse outbound config > Ext|Tools|Conf: unknown config id:

 > exit status 4294967295

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

**Comment by DarienRaymond** [comment]
你的 outbound 少了一部分，正确的是这样的：

```javascript
"outbound": {
  "protocol": "socks",
  "settings": { /* 这里写 socks 的配置 */},
}
```

详见： https://www.v2ray.com/chapter_02/01_overview.html#outbound
