### ISSUE TITLE
linux_arm_32bit client only listen tcp6 port

### ISSUE THREAD

**Issue by trepwq** [v2ray/v2ray-core#119]
树莓派3 raspbian jessie 使用默认配置，客户端只监听ipv6端口，确定没有其他程序占用。

 V2Ray v1.10 (New Order) 20160306
An unified platform for anti-censorship.
2016/04/18 22:20:44 [Warning]Point server started on port 6666

netstat -nat |grep LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN     
tcp6       0      0 :::6666                 :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN

**Comment by zxcso** [comment]
v2ray默认监听端口的所有地址，::::是包括了IPv4转译地址的，所以ipv4是可以访问的，如果不能访问，应该看下防火墙设置是否正确

**Comment by trepwq** [comment]
确实如楼上所说，防火墙的问题。
ps：移动端发布有时间表了吗？

**Comment by v2ray** [comment]
@trepwq  没有时间表
