### ISSUE TITLE
无法代理git

### ISSUE THREAD

**Issue by Youlor** [v2ray/v2ray-core#1190]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
3.29
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
系统代理代理git client
1.为git设置代理
2.命令
git config --global https.proxy http://127.0.0.1:1080
git config --global https.proxy https://127.0.0.1:1080
git config --global http.proxy 'socks5://127.0.0.1:1080' 
git config --global https.proxy 'socks5://127.0.0.1:1080'
3.git clone项目

3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
无法代理 返回错误日志 使用ss ssr可以正常代理
2018/07/10 20:52:29 tcp:127.0.0.1:60854 rejected  Proxy|Socks: unknown Socks version: 67
2018/07/10 20:53:09 tcp:127.0.0.1:60858 rejected  Proxy|Socks: unknown Socks version: 67
2018/07/10 20:53:10 tcp:127.0.0.1:60859 rejected  Proxy|Socks: unknown Socks version: 67
4)  你期待看到的正确表现是怎样的？
正常代理git下载请求

**Comment by nobody3u** [comment]
> git config --global http.proxy 'socks5://127.0.0.1:1080'

git需要的是http代理，然而你给他个socks代理。。。
[v2ray.com/http](https://www.v2ray.com/chapter_02/protocols/http.html)

**Comment by VictoriaRaymond** [comment]
同上。

**Comment by MioYvo** [comment]
设置代理为
```
git config --global http.proxy http://127.0.0.1:8001
git config --global https.proxy https://127.0.0.1:8001
```
注意端口修改为自己v2ray的http传入配置

然后git clone 仓库时选择https方式 [Clone with HTTPS](https://help.github.com/articles/which-remote-url-should-i-use/)
比如`git clone https://github.com:v2ray/v2ray-core.git`
而不是`git clone git@github.com:v2ray/v2ray-core.git`
这样就会生效

**Comment by txdywy** [comment]
试试这个如何？ export ALL_PROXY=socks5://127.0.0.1:1080

**Comment by elliott-yang** [comment]
为什么我用http代理提示无法连接 改成socks代理下载速度可以达到3M  
git config -l 显示如下：
http.postbuffer=1048576000
http.proxy=socks5://127.0.0.1:2333
https.proxy=socks5://127.0.0.1:2333
