### ISSUE TITLE
docker自动打包失败

### ISSUE THREAD

**Issue by zgc** [v2ray/v2ray-core#1191]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
docker
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
docker自动打包失败
Build failed: The command '/bin/sh -c go get -u v2ray.com/core/...' returned a non-zero code: 1
4)  你期待看到的正确表现是怎样的？
docker自动打包成功
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
https://hub.docker.com/r/v2ray/dev/builds/bdpjjk4ianicunl4kmhvepk/

**Comment by VictoriaRaymond** [comment]
已修复。
