### ISSUE TITLE
路由器arm版本用mKCP被限速，youtube测试3000kbps，MacOS版本V2RayX却能跑30000kbps。

### ISSUE THREAD

**Issue by seven76six** [v2ray/v2ray-core#1192]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
服务器，客户端都升级到v3.30

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

macos下使用V2RayX观看YouTube或者NETFLIX，路由器梅林arm插件版本观看YouTube或者NETFLIX。
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

1号VPS服务器配置和2号VPS服务器配置完全一样，都设置成使用mKCP的任一种伪装协议。

1号VPS服务器在macos下使用V2RayX跑YouTube为30000kbps，路由器梅林arm插件版本同样也能跑30000kbps。

2号VPS服务器在macos下使用V2RayX跑YouTube为30000kbps，路由器梅林插件版本却只能跑到2000~3000kbps左右。偶尔达到6000。

2号VPS服务器尝试更改TCP或者H2后，路由器插件版本可以恢复正常速度。

4)  你期待看到的正确表现是怎样的？

路由器梅林arm插件版本使用mKCP协议可以正常跑满路由器应该有的速度，不被限速（暂且排除路由器性能问题，路由器肯定性能受限，但是好像被QOS限制到了3000kbps一样，而且发生在个别服务器身上）

5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
```javascript
    // 在这里附上服务器端配置文件
暂无
```

    客户端配置:
```javascript
    // 路由器客户端配置
{
	"log": {
		"access": "/dev/null",
		"error": "/tmp/v2ray_log.log",
		"loglevel": "error"
	},
	"inbound": {
		"protocol": "dokodemo-door",
		"port": 7913,
		"settings": {
			"address": "8.8.8.8",
			"port": 53,
			"network": "udp",
			"timeout": 0,
			"followRedirect": false
		}
	},
	"inboundDetour": [
		{
			"listen": "0.0.0.0",
			"port": 3333,
			"protocol": "dokodemo-door",
			"settings": {
				"network": "tcp,udp",
				"followRedirect": true
			}
		}
	],
	"outbound": {
		"tag": "agentout",
		"protocol": "vmess",
		"settings": {
			"vnext": [
				{
					"address": "IP",
					"port": 123456,
					"users": [
						{
							"id": "111111111111111111",
							"alterId": 64,
							"security": "chacha20-poly1305"
						}
					]
				}
			],
			"servers": null
		},
		"streamSettings": {
			"network": "kcp",
			"security": "",
			"tlsSettings": null,
			"tcpSettings": null,
			"kcpSettings": {
				"mtu": 1350,
				"tti": 50,
				"uplinkCapacity": 12,
				"downlinkCapacity": 100,
				"congestion": false,
				"readBufferSize": 2,
				"writeBufferSize": 2,
				"header": {
					"type": "srtp",
					"request": null,
					"response": null
				}
			},
			"wsSettings": null,
			"httpSettings": null
		},
		"mux": {
			"enabled": true,
			"concurrency": 8
		}
	}
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
```
   无
```

    客户端错误日志:
```
   无
```

**Comment by VictoriaRaymond** [comment]
和软件无关，应该是你的网络问题。另外按实际情况来看，你的uplink值有些高了。

**Comment by seven76six** [comment]
实验证明，换回SS，速度就可以恢复了，说明还是ARM版本对路由的支持问题。而且不会出现NATFLIX断流停播。

**Comment by changyp6** [comment]
我遇到了一模一样的问题。用mKCP，就会出现有的机器可以到几十mbps，有的只是几十kbps
然而，相同的网络环境，kcptun就是OK的，可以达到几十mbps

公司的网络环境的确是有防火墙的，但是不知道为什么kcptun的UDP包可以畅通无阻，V2ray的mKcp的UDP包，就会被防火墙拦。

**Comment by i258559** [comment]
同样有一样的疑问，下午折腾了kcptun和mkcp，貌似mkcp效果真是惨不忍睹，各种参数也试过了
