### ISSUE TITLE
同一个ID分别由3个以上的人从不同地方连接是否有影响？

### ISSUE THREAD

**Issue by Jetranger** [v2ray/v2ray-core#1196]
如题。
是否推荐这样做，如果这样做是否需要把AlertID设置到60以上？

**Comment by VictoriaRaymond** [comment]
请举例说明哪方面的影响。性能方面肯定是没有的，安全性肯定是有的，比如一个人可以解密另一个人的流量。AlterID 同理。

另外请按模板提交issue。
