### ISSUE TITLE
中南海政變

### ISSUE THREAD

**Issue by sogenstant** [v2ray/v2ray-core#1197]
今晨，老编辑收到北京城根的一位读者转来的一篇老领导谈话录，读后发人深思。现将此录全文转发，以飨读者

今晚闲聊简单说几句哈，就是把这一两年来的大事件给大家串联一下，让我们明白很多事情的前因后果，免得盲目猜测。

当然我也不敢保证我的推测就准确，毕竟是大道消息+小道消息+个人推理的结论，请独立思考。

这几天各种蹊跷的事情接二连三，看起来主旋律还是中美贸易战，实际上这并不是最危险的。

我还是那句话，贸易战只是手段，其根本目的不言而喻。

从三月份贸易战开打以来，我们会发现似乎朝廷的各种对策非常愚蠢，各种策略朝令夕改，根本没有一个完全的统一的策略。

一会儿战斗到底，一会儿需要合作，一会儿不惜一切代价，一会儿我们配合开放……根本让人们看不懂他们究竟想干什么。

各种办法相互矛盾，各种宣传自打自脸，看起来愚蠢至极。他们真的很蠢吗？答案是否定的。

我们总以为这些愚蠢的对策好像是习近平至高无上，一拍大腿就是个决定一样，实际上不是，习近平也没那么蠢。这些矛盾政策出现的根本原因，就是朝廷内部的分化结果。

现在针对中美贸易战问题，朝廷对立的两面各不相让，各有各的办法，结果弄到现在，已经不可收拾了，不但中美贸易战一败涂地，而且更为严峻的是国内经济的频临崩溃，
目前能用的办法都用了。

以前是一手悬空，还有可能拉上来，现在是坠落时间，无法挽回了。

现在不要谈保什么，汇率保不住，储备保不住，股市保不住，甚至房市也保不住了。

那么出现今天的结果，必然需要承担责任的人，习近平首当其冲。但是他却不认为责任在自己，因为他知道很多人在搅局，甚至很多人在背叛。

举个例子，所谓的对策，前脚刚研究出来，后脚对方就完全知道了，你的心思，你的策略，你的底线，美国完全掌控，这种贸易战怎么打？

习近平认为反动派出卖国家，但你要有证据。没证据只能是习近平承担，因为反动派一切都听你的，谈判的人是习近平找的，策略是习近平定的，讲理吧。

那么我们今天研究第一个问题就是，为什么会造成崇祯模式（垂帘亡国）？

所谓崇祯模式很简单，就是习近平一个人想努力，大伙都不配合，要点钱都不给，这个大家都知道是吧。这种矛盾的产生主要来自于各自的诉求。

习近平是个有大理想大抱负的初中生，他总觉得我行，给我二十年，我还大家一个强盛的大清帝国。

于是我要说了算，我只有说了算才能把我的理想实现，我都是为大家好，灭霸的角色。于是习近平开始垄断权力。

第一步，废总理，习近平认为李克强总理无能，不是那块料，实际上李克强总理也的确不行。

李克强总理的经济政策有很多失误，当然这不是他自己的原因，现在习近平让他背锅，他不能拥权，于是这是第一步争吵。

接着习近平来了个釜底抽薪。翻出辽宁贿选案，翻出辽宁GDP水分案。那么这些案子真与假呢？都是事实。

我以前讲过，老领导要把李克强总理拉上位，但是呢，朝廷有规定，你做李克强总理需要业绩，于是辽宁为了李克强总理一个人做假。

本来这事朝廷都心知肚明，因为这种事也不是他一个人干过，谁也没当回事。

但是后来辽宁经济几乎崩溃，再加上习近平别有用心，于是这两个案子一翻出来，小题大做，国内经济问题你不背锅，至少辽宁的问题你的背锅，辽宁问题证明你不行。

据说李克强拂袖离去，跑到了德国。老子不干了。不干正好，于是各种小组成立，完全取代原来的朝廷运作模式。

李克强总理彻底靠边，成为傀儡，当然你还得干，你不能走，走了轩然大波，朝廷没法交代。

如果说李克强总理被架空算大事，但这大事并没有引起什么不满。

原因很简单，第一李克强总理没啥盟友，说白了实力不行。第二个原因，给李克强总理弄上来的那个老领导信守承诺，不再参政，换句话说不管这事。

第一步习近平成功了，于是不管是御书房还是军机处，各种官员的任命完全习近平一个人说了算了。

后来的事大家知道了，习近平主义思想确定，修宪连任成功。到这时候就引起很多人不满了，特别是邓家一派，他们认为这违背了邓家当年的遗嘱。

反对声开始了，于是邓朴方就被好一顿诽谤，2013年网上一片疯传，邓朴方拿了1000亿美元跑路了。

邓朴方呢，可不管病，坚决反击，弄了些习近平的花边新闻到处转。到这时候，习近平和邓家就势同水火了。

但是这两派怎么斗，其他人都看热闹，因为其他人巴不得两虎相争。到这时候还算太平。

什么时候不太平了呢？

一年以前。北戴河会开了三次，三次吵翻，就为了一个人。习近平力主王岐山在位，所有人除了江泽民几乎全部反对。

反对的原因很简单，第一都不喜欢这个人，贪婪跋扈。第二这个人干掉了自己不少人，哪个派系都涉及到了。

但是习近平不知道是什么原因，联手了还是被王岐山拿到把柄了，我不详细，但前者很有可能，反正就是坚决要王岐山上位。

最后达成妥斜，王岐山副主席，有参与军机处会议的权利。到这时候，基本上就都有意见了。只是没有彻底爆发。

十九大会前，忽然习近平搞了一个国家监察局，这个国家监察委员会就是王岐山垂帘，完全垂帘。

这样一来不但王岐山的权力没有被削减，反而比以前更大了，连金融系统的首脑任命都是王岐山说了算，可以说王岐山控制了所有的金融系统。

这是朝廷的命脉啊，因为在这样的位置上，一个好招不一定把经济弄好，但是一个坏招，大清经济就崩溃了。所以这时候人人自危了。

国家监察局成立以后，开始低调了，但实际上却比以前更加下狠手了。我们不知道是因为以前国安局干掉谁马上通报，现在国家监察局抓人根本不通报，民间根本不知道什么人又被怎么样了。

细心你会发现，失踪的、跳楼的、割腕的、照相的、车祸的高官死亡很多很多。王岐山的绝对权力加上心狠手辣，终于引起连锁效应了。

特别是对江泽民派系的清洗上更是斩草除根，不留后患。鸡死了，猴也害怕。这时候各个集团开始不自觉的抱团取暖了，毕竟人人自危。

如果说这时候或者在此之前他们的策略不过是懒政、过度执行、看习近平笑话、找习近平背锅、私分了习近平的标杆政策——精准赖政这些小伎俩，那么另外一件事的发生则让高官们开始造反了。

习近平上台四五年了，按照他的意思要解放全人类，就得让全世界认可。后来一带一路撒了一圈钱。发现，不但一个朋友没交到而且外汇见底了。

大清这种制度离开钱是万万不能的，因为他需要养活庞大的独裁暴力机器，没钱肯定不行。

钱从哪里来？民间没了，对老百姓的征收赋税已经到了极限，再征收就出事了。

一年半前老领导就说过，习近平将来一定会拿有钱的富二代们开刀，因为只有他们有钱。

更可恶的是，习近平在这面要创建强盛大国，保汇率，你们这些人却在外面打着收购美国的旗号，大肆洗钱，把国内资产往外倒腾，不杀你们杀谁？

这不用预言，熟读历史就不难发现。但是杀谁呢？谁能让杀。后来找到了邓家，这家不但肥，而且习近平还恨他们家。

于是去年六月，吴晓辉被抓了，这一下上万亿到手了。

正是这件事，引起了高官们的惶恐，每个人都知道不一定下一个就是自己。于是纷纷站起来，保邓家，其实就是保护自己。

这件事历时11个月还没有尘埃落定，可见其中的争论有多激烈。

据说邓家吴晓辉洗钱、跑路的证据太多太多，都是王岐山弄出来的，触目惊心，其他人也不好说话，最终还是被拿下。

但是这件事彻底激起了高官们的反抗，他们决定齐心协力，掀翻习近平，不然自己哪天死都不知道。

可是这些集团不像我们民间，随便坐个飞机打个电话都能说点啥，他们近在咫尺，但却很难见面，通电话等于站在楼顶喊。

这个时候一个联络员陈小鲁主动挺身而出了，这个联络员陈小鲁是五四运动的小闯将，但这个闯将后来认识了很多东西，于是开始反思大运动。

又是找老领导道歉，又是开大运动反思会。更是喊话，大清绝不能回到过去，走大运动的路子死路一条。

习近平本来要往回走，你喊话往回走死路一条，而后你还串联这些高官，是不是想害朕？

于是习近平生气了，王岐山出手了，联络员陈小鲁没有看到今年三月第一天的太阳。

这件事算是把同志们弄到一起了。而我认为，美国正是瞅准了这个机会开始打贸易战等等一系列行动。

于是这些人开始分裂了，纷纷拆习近平的台，习近平的每个政策都是透明的。

更有甚者，对南海和南沙群岛的政策也被人知道了底牌，所以你看南沙群岛按部就班玩的很嗨，根本不在意你什么，因为人家知道你不敢怎么样，即使习近平非要打，人家也知道中国军队不堪一击。

仅仅如此还不够，过去虽有矛盾，但是大家见面笑呵呵，现在不行了。邓家的事证据确凿高官们都承认，但是你海航的事情更严重，想依法治理可以啊，大家一碗水端平呗，你不能只安邦不海航对吧？

你国家监察局到处抓人，个个证据确凿，可以啊，但是你不能只抓他不抓他吧？你弄我的人，那我也会调查你的人。

于是首当其冲的栗战书被人家拿到了把柄，数额巨大。后来习近平竭力保护，拿下了栗战书贴身秘书，一切事都推在了秘书身上。

虽然栗战书人身没咋地，但是栗战书彻底失去了话语权，举手资格都没有了。

不但如此，据说西南那个习近平的小弟陈敏尔也被参了好几本，把柄不少。没啥证据，只能看出陈敏尔很久了都很低调，没啥新闻，更没啥立场表态。

总之你会发现一件事，过去誓死效忠习近平、每每最先表态的现在都不说话了，比如某强、某笔、某车、某希，某奇更是灰头土脸。

这些人虽然不会反习近平，但是从沉默中能感觉到，他们对习近平放任宦官专权，也颇有微词。

我觉得更说明一件事，他们都已经心灰意冷，可能都在为自己考虑，而心灰意冷的根本原因就是他们比我们会更先感知到大清国要完。

不但在拿人上，在针对企业上也是，你不能只动邦不动航吧？所以其实从很早开始，就有人调查海航，而后供料给海外郭文贵，可是后来都被习近平压下了。

但是某邦被拿下，大家不干了，坚决要求彻查海航，否则休想配合。这些人不但在国内查海航，而且也在国外找人查，大家都有朋友的。

于是德意志、瑞士、美利坚、英格兰甚至西班牙等都开始对海航进行调查。这个海航究竟有没有习近平的资产目前的确没证据，但是是王岐山控制这个不用再找证据了。

自从大家翻出海航，海航也知道混不下去了，早晚的事。于是海航就开始秘密破产行动，就是能变卖的统统变卖，而后钱弄进自己腰包再说。

可是海航越是这样，越是给了人把柄。为了弄清楚海航变卖资产的转移情况，也是下了不手段多。

那么其中了解内幕的人便首当其冲，匹夫无罪、怀璧其罪。高官们经过很多手段，让怀璧的人开始犹豫不决。

而一旦此人其璧被人弄走，那么王岐山可就真的死无葬身之地了，就连习近平恐怕也不好收场了。在这种情况下，唯有死人是最安全的，于是海航王建顺理成章的意外身亡了。

这里有两个问题我们可以轻而易举的推断出来。

第一海航王建的死亡现场太搞笑了，可能你就想死狠命跳下去都未必有多大事。换句话说，造假的太明显。

那么为什么会留下这么大的漏洞？很简单事情紧急，顾不了那么多了，也许此次海航王建就是去交接璧的也不一定。

第二个问题也好推断，海航王建本来不是要死的，是前一天。但是第二天就公布了。

以往这样的事情，就算没有隐情也不可能这么早就弄的全世界都知道。

很显然王岐山的对手们爆料了，就是要把这件事端到桌面上，人人皆知，而且还选了个特殊的暗示什么的日子发布，王健死于7月3日。

顺便我们还可以看出来，反对派对舆论的控制能力显然很强。如果你细心，你可以挨个新闻门户看，看那些媒体转载了这件事，那些媒体没有说这件事，从中能看出很多东西，也是很有意思的。

更让人惊愕的一件事是昨天的小姑娘泼墨举动，其实这是一件非常非常大的事情，她就好比是齐奥塞斯库在广场上演讲，十万人中第一个喊口号的那个人。

这件事开启了一个先例，把社会矛盾大大的升级了一个台阶。

这个举动在往常，超过任何其他政治事件，因为这件事矛头指向特别明确。但是这个事件你若细细观察，你会发现很多匪夷所思的问题。

第一个问题我绝不是不相信这个小姑娘泼墨的勇敢，虽然我做不到，但是我还是非常钦佩。只是这个勇敢的背后存在着许多问题。

很多人可能被墨汁吸引，但我却被小姑娘的一句话吸引，我认为那才是重点，小姑娘说我身后就是海航的大厦，就是习近平资产。

这一句看似没什么必要，前面那些我认为就足够了，但恰恰这句我认为才是小姑娘的目的，不然她不会选择这个位置。

第二就在小姑娘事件发生以后，很多的时间内国外各大有影响的媒体纷纷报道跟进，就像提前排版好了一样，而且各大人权组织马上照会大清，寻找此人。

看架势要把这件事做成一个大新闻，超过当年的盲人。也正因为此我反而不太为小姑娘担心了，我似乎也能理解小姑娘的勇敢了。

第三令人匪夷所思的是，这件事的视频会同步流出，而且所谓屏蔽只是象征性的，当局被没有如临大敌的架势，说白了，就是这个视频的传播并没有收到任何实质性的影响，这在以往是不可能发生的。

这说明了很多东西，我就不说了，大家都聪明。

大致就是这么个脉络，那么我们不妨往下推断一下，事情发展的可能性有多少？

第一可能性，所有人齐心合力，把习近平赶下台或者习近平傀儡，只有10%可能性，这取决于习近平对军队的掌控。我只能说习近平差不多可以号令全军。

第二个可能性，就是习近平大开杀戒，坚决剿灭一切反对者，杀人拿钱。这个可能性目前只有40%，因为习近平的根基还没那么深，他也不敢那自己的身家性命开玩笑。除非有绝对把握，而这个绝对把握暂时没有。

第三个可能性，君臣议和。但这种议和一定会削弱习近平的权力而不是相反，最重要的是一定会剥夺王岐山的权力。这种可能性大概50%，但如果一旦是这样，大清的经济会加速下坠，具体不解释了。

现在我就是瞎猜，所以具体走到哪一步还需要看。但有一点是肯定的，那就是我原来预计的混沌期提前来临了，比我预想的提前了两年，这个可以肯定。

所以我今天讲这个归根结底的目的很简单，就是让大家别抱幻想，赶紧自己想的办法，在第二次文化大革命前移民出国为第一位。特别是有钱人。（京城老领导言）

老领导所言转毕，最后老编辑只想说八个字：仁者见仁 智者见智！

**Comment by XiLingHost** [comment]
无关内容请不要发issue
