### ISSUE TITLE
panic: interface conversion: crypto.PlainChunkSizeParser is not crypto.PaddingLengthGenerator: missing method MaxPaddingLen

### ISSUE THREAD

**Issue by peter-tank** [v2ray/v2ray-core#1213]
Please read the [instruction](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md) and answer the following questions before submitting your issue. Thank you.
Please answer all the questions with enough information. All issues not following this template will be closed immediately.
 
1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
 `V2Ray 3.33 (die Commanderin) Custom`
2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
 ```
android(arm64) termux, kcp, mux: false, export V2RAY_VMESS_PADDING=1
```
3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)
 `client crash on first connection`
4) What's your expectation?

5) Please attach your configuration file (**Mask IP addresses before submit this issue**).
 
    Server configuration:
```javascript
    // Please attach your server configuration here.
```
 
    Client configuration:
```javascript
    // Please attach your client configuration here.
```
 
6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.
 
    Server error log:
```
    // Please attach your server error log here.
```
    Client error log:
```panic: interface conversion: crypto.PlainChunkSizeParser is not crypto.PaddingLengthGenerator: missing method MaxPaddingLen

goroutine 126 [running]:
v2ray.com/core/proxy/vmess/encoding.(*ClientSession).EncodeRequestBody(0x442904eea0, 0x4420607710, 0x6fc940, 0x4429071f00, 0x0, 0x0)
	/data/data/com.termux/files/home/golang/src/v2ray.com/core/proxy/vmess/encoding/client.go:115 +0x1050
v2ray.com/core/proxy/vmess/outbound.(*Handler).Process.func2(0x0, 0x0)
	/data/data/com.termux/files/home/golang/src/v2ray.com/core/proxy/vmess/outbound/outbound.go:122 +0x234
v2ray.com/core/common/task.executeParallel.func1(0x442904ef60, 0x442900e158, 0x442904ef00)
	/data/data/com.termux/files/home/golang/src/v2ray.com/core/common/task/task.go:124 +0x20
created by v2ray.com/core/common/task.executeParallel
	/data/data/com.termux/files/home/golang/src/v2ray.com/core/common/task/task.go:123 +0xb0
```
 
7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.
```
    // Please attach your server access log here.
```
 
Please review your issue before submitting.
 
8) Other configurations (such as Nginx) and logs.
 
9) If V2Ray doesn't run, please attach output from `--test`.
 
The command is usually `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`, but may vary according to your scenario.
 
10) If V2Ray service doesn't run, please attach journal log.
 
Usual command is `journalctl -u v2ray`.

**Comment by DarienRaymond** [comment]
Fixed in bf2d3890de0211d65cce1b532b7c6ee43c0e4a5d
