### ISSUE TITLE
请教关于openwrt透明代理的问题(not an issue)

### ISSUE THREAD

**Issue by sjz123321** [v2ray/v2ray-core#1219]
尝试在openwrt下使用v2ray core 修改了/etc/profile 增加了 
export http_proxy=http://127.0.0.1:1080
export https_proxy=$http_proxy

使用./v2ray -config /etc/v2ray/config.json &开启了v2ray v2ray代理配置为http方式 日志等级为info

当使用opkg update opkg install xxx 时 根据error.log发现这部分流量可以正常经过代理

执行curl google.com能收到正常的数据包

但连接到路由的设备流量并没有经过代理且无法翻墙 根据v2ray白话文教程透明代理章节配置iptables没有得到解决。
求教

**Comment by nicholascw** [comment]
not an issue.
RTFM regarding environment variables.
