### ISSUE TITLE
1.11.1 异常退出

### ISSUE THREAD

**Issue by kxjhlele** [v2ray/v2ray-core#122]
V2Ray v1.11.1 (New Order) 20160419
An unified platform for anti-censorship.
panic: send on closed channel                                                goroutine 3701 [running]:                                                    panic(0x73cc80, 0xc8205879c0)                                                        /usr/local/go/src/runtime/panic.go:464 +0x3e6                        github.com/v2ray/v2ray-core/transport/ray.(*Stream).Write(0xc82061b7a0, 0xc8$        /root/go/src/github.com/v2ray/v2ray-core/transport/ray/direct.go:86 $github.com/v2ray/v2ray-core/common/io.Pipe(0x7fd4457aa440, 0xc82060e460, 0x7$        /root/go/src/github.com/v2ray/v2ray-core/common/io/transport.go:7 +0$github.com/v2ray/v2ray-core/proxy/freedom.(*FreedomConnection).Dispatch.func$        /root/go/src/github.com/v2ray/v2ray-core/proxy/freedom/freedom.go:75$created by github.com/v2ray/v2ray-core/proxy/freedom.(*FreedomConnection).Di$        /root/go/src/github.com/v2ray/v2ray-core/proxy/freedom/freedom.go:76$
^G Get Help ^O WriteOut ^R Read File^Y Prev Page^K Cut Text ^C Cur Pos
^X Exit     ^J Justify  ^W Where Is ^V Next Page^U UnCut Tex^T To Spell

**Comment by kxjhlele** [comment]
我先升级 .2 试试

**Comment by v2ray** [comment]
1.11.2 应该可以修复这个问题

**Comment by kxjhlele** [comment]
目前没有异常退出，关了
