### ISSUE TITLE
关于vmess时间验证的问题。。。

### ISSUE THREAD

**Issue by wutongskype** [v2ray/v2ray-core#1221]
情况是这样的，我光猫调成了桥接模式，然后软路由连接光猫进行拨号，软路由是lede，在然后我在路由上开启v2，结果v2插件显示国内通国外不通。

经过一番排查发现服务器那边查看日志显示用户无效被拒绝。Google了相关issues说这个情况是用户id或者时间不对导致的，经排查配置文件正常，因为这个配置文件是我从v2rayN里面导出的，在win系统上跑没问题，而且在lede作为2级路由时使用也正常，在经过一番苦逼排查发现光猫的系统时间是1970年，由于删除了TR069这个光猫管理链接，在光猫是桥接模式的时候它无法自动同步时间，而作为路由模式的光猫它可以通过拨上号的ppoe自动同步时间。。。。。。。

最后我通过telnet手动设置了光猫的系统时间以后路由器上的v2回复了正常，可是每次光猫一重启之后时间又变回了1970年。。。v2又上不去了。不知道这个问题出在哪里，软路由的本地时间都是正常，所有设备的时间唯独光猫不对。

我目前想到两种解决办法，1.修改v2提取时间戳的一些东西。2.想办法让光猫能在桥接模式下联网同步时间。有大佬能指导一下吗？俺的光猫是贝尔G-120W-B，昨天刚拿到手，超密已有，已经能telnet链接，好像里面还有个busybox但是俺不会用，本身也没有ntp服务。最主要它没网！或者有什么办法给桥接模式下的光猫设置个类似win系统下全局代理什么的吗？我光猫本地lanip是192.168.1.6，网口1用来桥接软路由负责软路由的拨号，网口2接的交换机，让其他设备能链接192.168.1.6进行管理，软路由的lanip是192.196.1.11，经过测试软路由ping光猫能通，光猫ping软路由的.11也能通。
本人linux小白一个，只会照着输命令，网上找了一些设置网关或者本地ip什么的教程，照着搞了以后光猫直接歇菜。。。。

**Comment by nicholascw** [comment]
Not a V2Ray issue. Closed.

请自行脚本解决时间重设问题.

**Comment by wutongskype** [comment]
大佬，能给点指点吗？😂😂😂😂

**Comment by wordlesswind** [comment]
@wutongskype 
Lede 带有本地 NTP 服务器功能的吧，你看看？
然后光猫那设置 NTP 服务器为软路由地址就好啦
