### ISSUE TITLE
KCP无法正常工作 

### ISSUE THREAD

**Issue by cdtsuipo** [v2ray/v2ray-core#1229]
Please skip to the English section below if you don't write Chinese.

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V3.35

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
通过firefox Socks/VMess KCP 代理观看YouTube 视频

3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
无法连接，页面显示 Secure Connection Failed ,同服务器上搭载的SS可以正常运行。
4)  你期待看到的正确表现是怎样的？
正常使用
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
```javascript
{
    "log": {
        "access": "/var/log/v2ray/access.log",
        "error": "/var/log/v2ray/error.log",
        "loglevel": "info"
    },
    "inbound": {
        "port": 4430,
        "protocol": "vmess",
        "settings": {
            "udp": true,
            "clients": [
                {
                    "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                    "level": 1,
                    "alterId": 233
                }
            ],
            "detour": {
                "to": "dynamic"
            }
        },
        "streamSettings": {
            "network": "kcp"
        }
    },
    "outbound": {
        "protocol": "freedom",
        "settings": {
	"domainStrategy": "AsIs"
		}
    },
    "inboundDetour": [
        {
            "protocol": "shadowsocks",
            "port": 58530,
            "settings": {
                "method": "chacha20",
                "password": "xxxxx",
                "udp": true,
                "level": 1,
                "ota": false
            }
        },
        {
            "protocol": "vmess",
            "port": "11111-33333",
            "tag": "dynamic",
            "settings": {
                "udp": true,
                "default": {
                    "level": 1,
                    "alterId": 32
                }
            },
            "allocate": {
                "strategy": "random",
                "concurrency": 2,
                "refresh": 5
            },
            "streamSettings": {
                "network": "kcp"
            }
        }
    ],
    "transport": {
        "kcpSettings": {
            "mtu": 1300,
            "tti": 30,
            "uplinkCapacity": 100,
            "downlinkCapacity": 100,
            "congestion": true,
            "readBufferSize": 4,
            "writeBufferSize": 4,
            "header": {
                "type": "srtp"
            }
        }
    }  
}
```

    客户端配置:
```javascript
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": ""
  },
  "inbound": {
    "port": 1080,
    "listen": "0.0.0.0",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "127.0.0.1",
      "clients": null
    }
  },
  "outbound": {
    "tag": "agentout",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "xxx.xxx.xxx.xxx",
          "port": 4430,
          "users": [
            {
              "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
              "alterId": 233,
              "security": "aes-128-gcm"
            }			
          ]
		}
      ]
	  },
	  "streamSettings": {
			"network": "kcp"
					}
    },
        "kcpSettings": {
            "mtu": 1300,
            "tti": 30,
            "uplinkCapacity": 100,
            "downlinkCapacity": 100,
            "congestion": true,
            "readBufferSize": 4,
            "writeBufferSize": 4,
            "header": {
                "type": "srtp"
            }
        },  
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {
        "response": null
      },
      "tag": "direct"
    }
  ]  
 
}
```
6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
```
    // 在这里附上服务器端日志
```
2018/08/10 15:56:47 [Info] Transport|Internet|mKCP: discarding invalid payload from udp:171.223.186.103:51457
2018/08/10 15:56:47 [Info] Transport|Internet|mKCP: discarding invalid payload from udp:171.223.186.103:51521
2018/08/10 15:56:48 [Info] Transport|Internet|mKCP: discarding invalid payload from udp:171.223.186.103:51521
2018/08/10 15:56:48 [Info] Transport|Internet|mKCP: discarding invalid payload from udp:171.223.186.103:51457
2018/08/10 15:56:48 [Info] Transport|Internet|mKCP: discarding invalid payload from udp:171.223.186.103:51521
2018/08/10 15:56:48 [Info] Transport|Internet|mKCP: discarding invalid payload from udp:171.223.186.103:51457
2018/08/10 15:56:48 [Info] Transport|Internet|mKCP: discarding invalid payload from udp:171.223.186.103:51457
2018/08/10 15:56:48 [Info] Transport|Internet|mKCP: discarding invalid payload from udp:171.223.186.103:51521
2018/08/10 15:56:48 [Info] Transport|Internet|mKCP: discarding invalid payload from udp:171.223.186.103:51521
2018/08/10 15:56:48 [Info] Transport|Internet|mKCP: discarding invalid payload from udp:171.223.186.103:51457
2018/08/10 15:56:48 [Info] Transport|Internet|mKCP: discarding invalid payload from udp:171.223.186.103:51457
2018/08/10 15:56:48 [Info] Transport|Internet|mKCP: discarding invalid payload from udp:171.223.186.103:51521
2018/08/10 15:56:48 [Info] Transport|Internet|mKCP: discarding invalid payload from udp:171.223.186.103:51521
2018/08/10 15:56:48 [Info] Transport|Internet|mKCP: discarding invalid payload from udp:171.223.186.103:51457
2018/08/10 15:56:48 [Info] Transport|Internet|mKCP: discarding invalid payload from udp:171.223.186.103:51457
2018/08/10 15:56:48 [Info] Transport|Internet|mKCP: discarding invalid payload from udp:171.223.186.103:51521
2018/08/10 15:56:48 [Info] Transport|Internet|mKCP: discarding invalid payload from udp:171.223.186.103:51521
2018/08/10 15:56:48 [Info] Transport|Internet|mKCP: discarding invalid payload from udp:171.223.186.103:51521
2018/08/10 15:56:49 [Info] Transport|Internet|mKCP: discarding invalid payload from udp:171.223.186.103:51521
2018/08/10 15:56:49 [Info] Transport|Internet|mKCP: discarding invalid payload from udp:171.223.186.103:51521
2018/08/10 15:56:49 [Info] Transport|Internet|mKCP: discarding invalid payload from udp:171.223.186.103:51521
2018/08/10 15:56:49 [Info] Transport|Internet|mKCP: discarding invalid payload from udp:171.223.186.103:51521
2018/08/10 15:56:49 [Info] Transport|Internet|mKCP: discarding invalid payload from udp:171.223.186.103:51521
2018/08/10 15:56:49 [Info] Transport|Internet|mKCP: discarding invalid payload from udp:171.223.186.103:51521
2018/08/10 15:56:49 [Info] Transport|Internet|mKCP: discarding invalid payload from udp:171.223.186.103:51521

    客户端错误日志:
```
    // 在这里附上客户端日志
```
2018/08/10 15:18:25 tcp:127.0.0.1:7904 accepted tcp:www.youtube.com:443
2018/08/10 15:18:26 tcp:127.0.0.1:7905 accepted tcp:www.youtube.com:443
2018/08/10 15:18:55 tcp:127.0.0.1:7916 accepted tcp:www.youtube.com:443
2018/08/10 15:18:56 tcp:127.0.0.1:7917 accepted tcp:www.youtube.com:443
2018/08/10 15:20:44 tcp:127.0.0.1:7950 accepted tcp:www.youtube.com:443
2018/08/10 15:20:45 tcp:127.0.0.1:7951 accepted tcp:www.youtube.com:443
2018/08/10 15:20:53 tcp:127.0.0.1:7955 accepted tcp:www.youtube.com:443
2018/08/10 15:21:15 tcp:127.0.0.1:7972 accepted tcp:www.youtube.com:443
2018/08/10 15:21:21 tcp:127.0.0.1:7975 accepted tcp:github.com:443
2018/08/10 15:21:23 tcp:127.0.0.1:7977 accepted tcp:www.youtube.com:443
2018/08/10 15:21:29 tcp:127.0.0.1:7978 accepted tcp:github.com:443
2018/08/10 15:21:29 tcp:127.0.0.1:7979 accepted tcp:github.com:443
2018/08/10 15:21:33 tcp:127.0.0.1:7981 accepted tcp:github.com:443
2018/08/10 15:21:51 tcp:127.0.0.1:7987 accepted tcp:github.com:443
2018/08/10 15:21:52 tcp:127.0.0.1:7990 accepted tcp:www.google-analytics.com:443
2018/08/10 15:21:53 tcp:127.0.0.1:7992 accepted tcp:www.youtube.com:443
2018/08/10 15:22:23 tcp:127.0.0.1:8001 accepted tcp:www.youtube.com:443
2018/08/10 15:22:28 tcp:127.0.0.1:8003 accepted tcp:github.com:443
2018/08/10 15:32:47 tcp:127.0.0.1:8277 accepted tcp:github.com:443
2018/08/10 15:54:08 tcp:127.0.0.1:8686 accepted tcp:raw.githubusercontent.com:443
2018/08/10 15:54:10 tcp:127.0.0.1:8687 accepted tcp:www.youtube.com:443
2018/08/10 15:54:11 tcp:127.0.0.1:8688 accepted tcp:www.youtube.com:443
2018/08/10 15:54:40 tcp:127.0.0.1:8739 accepted tcp:www.youtube.com:443
2018/08/10 15:54:41 tcp:127.0.0.1:8745 accepted tcp:www.youtube.com:443
2018/08/10 15:54:45 tcp:127.0.0.1:8757 accepted tcp:safebrowsing.googleapis.com:443
2018/08/10 15:55:32 tcp:127.0.0.1:8772 accepted tcp:www.youtube.com:443
2018/08/10 15:55:33 tcp:127.0.0.1:8774 accepted tcp:www.youtube.com:443
2018/08/10 15:56:02 tcp:127.0.0.1:8778 accepted tcp:www.youtube.com:443
2018/08/10 15:56:03 tcp:127.0.0.1:8780 accepted tcp:www.youtube.com:443

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
```
    // 在这里附上服务器端日志
```
2018/08/10 09:16:26 101.206.167.100:46185 accepted tcp:r3---sn-a5mlrnel.googlevideo.com:443 
2018/08/10 09:16:26 101.206.167.100:46187 accepted tcp:i.ytimg.com:443 
2018/08/10 09:16:26 101.206.167.100:46186 accepted tcp:i.ytimg.com:443 
2018/08/10 09:16:26 101.206.167.100:46188 accepted tcp:i.ytimg.com:443 
2018/08/10 09:16:26 101.206.167.100:46189 accepted tcp:i.ytimg.com:443 
2018/08/10 09:16:26 101.206.167.100:46190 accepted tcp:i.ytimg.com:443 
2018/08/10 09:16:26 101.206.167.100:46191 accepted tcp:s.ytimg.com:443 
2018/08/10 09:16:31 101.206.167.100:47525 accepted tcp:www.google.com:443 
2018/08/10 09:16:32 101.206.167.100:47526 accepted tcp:www.google.com:443 
2018/08/10 09:16:38 101.206.167.100:47527 accepted tcp:r3---sn-a5mlrnel.googlevideo.com:443 
2018/08/10 09:17:49 101.206.167.100:47528 accepted tcp:data.flurry.com:443 
2018/08/10 15:56:07 171.223.186.103:49666 accepted tcp:connected.dy103.com:3389 
2018/08/10 15:56:08 171.223.186.103:51456 accepted tcp:data.flurry.com:443 

8) 其它相关的配置文件（如 Nginx）和相关日志。
无
9) 如果 V2Ray 无法启动，请附上 `--test` 输出。
正常启动
通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

服务运行正常

**Comment by VictoriaRaymond** [comment]
目测你的客户端kcpSettings写错位置了
