### ISSUE TITLE
有没有方法用 apache2 的 .htaccess 转发 v2ray 的 websocket？

### ISSUE THREAD

**Issue by 1046329594** [v2ray/v2ray-core#1235]
Please skip to the English section below if you don't write Chinese.

### 问题：有没有方法用 apache2 的 .htaccess 转发 v2ray 的 websocket？

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
latest
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
windows下的v2rayN
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
无
4)  你期待看到的正确表现是怎样的？
无
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    无需
    服务器端配置:
```javascript
    // 在这里附上服务器端配置文件
```

    客户端配置:
```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
无
    服务器端错误日志:
```
    // 在这里附上服务器端日志
```

    客户端错误日志:
```
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
```无
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。
无
9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by DarienRaymond** [comment]
Kamino closed and cloned this issue to [v2ray/discussion](https://github.com/v2ray/discussion/issues/20)
