### ISSUE TITLE
安卓客戶端上傳數據巨大

### ISSUE THREAD

**Issue by Handsome1080P** [v2ray/v2ray-core#1241]
一連上服務器，就使勁上傳數據，甚至速度遠遠大於下載速度？！

**Comment by 523860169** [comment]
应该不会吧？你是看系统自带的统计还是v2ray的安卓app自带的？

**Comment by Handsome1080P** [comment]
不, bifrost自帶顯示的網速。上傳始終500-600KB/S，不管有沒有程序在用，比我下載速度還快！

**Comment by 523860169** [comment]
不开 bifrost时，有没有检测到流量上传

**Comment by Handsome1080P** [comment]
沒有，回復平靜

**Comment by updater1234** [comment]
会不会是Bv有后门？

**Comment by chenxijun** [comment]
试一下连接电脑测流量？

**Comment by Handsome1080P** [comment]
安卓端的v2ray软件都同样，连接后上传数据飞升，后门应该不会都有。电脑流量只是http代理，没有上传异常流量产生

**Comment by updater1234** [comment]
那应该是你手机的问题吧

**Comment by Handsome1080P** [comment]
系统是Lineage OS，ovpn或者ssr anyconnect都不会出现这种问题

**Comment by nicholascw** [comment]
Not a v2ray-core issue, please use https://github.com/v2ray/discussion/issues instead.
