### ISSUE TITLE
HTTP/2 host设为任何值客户端都无法连接

### ISSUE THREAD

**Issue by yuanl** [v2ray/v2ray-core#1242]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
server: v3.36
client: v2ray-core v3.36
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
HTTP/2 访问google
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
v2ray outbound direct 的国内网站都可以访问。outbound freedom的网站都无法访问。

5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    客户端配置:
```javascript
    "streamSettings" : {
      "tlsSettings" : {
        "serverName" : "...",
        "allowInsecure" : true
      },
      "httpSettings" : {
        "path" : "\/some_radon_path",
        "host" : [
          ""
        ]
      },
      "network" : "http",
      "security" : "tls"
    }
```

6)  服务端一切正常

    客户端错误日志:
```
[Warning] [3529074508] App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: failed to find an available destination > Retry: [Transport|Internet|HTTP: unexpected status404] > Retry: all retry attempts failed
```

服务器端的配置是没问题的，我使用Kitsunebi在两台iOS设备上正常使用。
Kitsunebi生成的配置只有path没有host的部分
```
      "httpSettings" : {
        "path" : "\/some_radon_path"
      },
```
macOS下使用v2ray-core只要在配置里加上
```
        "host" : [
          ""
        ]
```
就可以重现这个bug.

**Comment by yuanl** [comment]
又试了一下，只要写了host这个设置，都无法连接。只有删除才能正确连接。

**Comment by veekxt** [comment]
所以说...    
你为什么要加`host`?    
你并没有贴服务器配置, 但是从你的表述看你应该没有在服务器端配置`host`, 所以自然是无法通过`host`验证的.    
你大概是误解了`host`的作用?

**Comment by yuanl** [comment]
两边设置了相同的`host`就没问题了。
看来是v2rayX 生成了不适合的默认设置。
