### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by ticonci** [v2ray/v2ray-core#1245]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

v3.36

2)  你的使用场景是什么？
树莓派3B, 系统fedora，做透明网关，使用的任意门协议

3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
journalctl -u vray, 有很多panic: runtime error: slice bounds out of range的报错, v2ray崩溃然后自动重启

4)  你期待看到的正确表现是怎样的？
当然是没有报错了

5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
服务端为nginx+tls+websocket

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
日志里面会出现i/o error on closed pipe错误，应该是panic: runtime error: slice bounds out of range这个报错造成v2ray重启，之前的socket不可用造成的

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

panic: runtime error: slice bounds out of range

**Comment by ticonci** [comment]
Aug 26 21:33:17 FedoraPi systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 26 21:33:17 FedoraPi systemd[1]: v2ray.service: Failed with result 'exit-code'.
Aug 26 21:33:18 FedoraPi systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
Aug 26 21:33:18 FedoraPi systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 6.
Aug 26 21:33:18 FedoraPi systemd[1]: Stopped V2Ray Service.
Aug 26 21:33:18 FedoraPi systemd[1]: Started V2Ray Service.
Aug 26 21:33:18 FedoraPi v2ray[17582]: V2Ray v3.36 (die Commanderin) 20180823
Aug 26 21:33:18 FedoraPi v2ray[17582]: A unified platform for anti-censorship.
Aug 26 21:33:25 FedoraPi v2ray[17582]: panic: runtime error: slice bounds out of range
Aug 26 21:33:25 FedoraPi v2ray[17582]: goroutine 179 [running]:
Aug 26 21:33:25 FedoraPi v2ray[17582]: v2ray.com/core/common/buf.(*Buffer).Read(...)
Aug 26 21:33:25 FedoraPi v2ray[17582]:         /v2ray/src/v2ray.com/core/common/buf/buffer.go:158
Aug 26 21:33:25 FedoraPi v2ray[17582]: v2ray.com/core/common/buf.(*MultiBuffer).Read(0x12e7e160, 0x12daed41, 0x2bf, 0x2bf, 0x0, 0x1892a0, 0x10)
Aug 26 21:33:25 FedoraPi v2ray[17582]:         /v2ray/src/v2ray.com/core/common/buf/multi_buffer.go:106 +0x310
Aug 26 21:33:25 FedoraPi v2ray[17582]: v2ray.com/core/common/buf.ReadFrom.func1(0x12dae848, 0x7b8, 0x7b8, 0x55ab60, 0x12e7e180, 0x12e7e160)
Aug 26 21:33:25 FedoraPi v2ray[17582]:         /v2ray/src/v2ray.com/core/common/buf/io.go:32 +0x3c
Aug 26 21:33:25 FedoraPi v2ray[17582]: v2ray.com/core/common/buf.(*Buffer).AppendSupplier(0x12a23e80, 0x12e7e180, 0x12e7e180, 0x800)
Aug 26 21:33:25 FedoraPi v2ray[17582]:         /v2ray/src/v2ray.com/core/common/buf/buffer.go:45 +0x58
Aug 26 21:33:25 FedoraPi v2ray[17582]: v2ray.com/core/common/buf.(*BufferedWriter).WriteMultiBuffer(0x12e7e030, 0x12e7e0f0, 0x2, 0x3, 0x0, 0x0)
Aug 26 21:33:25 FedoraPi v2ray[17582]:         /v2ray/src/v2ray.com/core/common/buf/writer.go:120 +0xf4
Aug 26 21:33:25 FedoraPi v2ray[17582]: v2ray.com/core/common/crypto.(*AuthenticationWriter).writePacket(0x12de6090, 0x0, 0x0, 0x0, 0x0, 0x0)
Aug 26 21:33:25 FedoraPi v2ray[17582]:         /v2ray/src/v2ray.com/core/common/crypto/auth.go:318 +0x264
Aug 26 21:33:25 FedoraPi v2ray[17582]: v2ray.com/core/common/crypto.(*AuthenticationWriter).WriteMultiBuffer(0x12de6090, 0x12d9ff70, 0x2, 0x2, 0x0, 0x0)
Aug 26 21:33:25 FedoraPi v2ray[17582]:         /v2ray/src/v2ray.com/core/common/crypto/auth.go:335 +0xb0
Aug 26 21:33:25 FedoraPi v2ray[17582]: v2ray.com/core/common/buf.CopyOnceTimeout(0x65ff10, 0x12e59288, 0x65faf0, 0x12de6090, 0x5f5e100, 0x0, 0x65c980, 0x0)
Aug 26 21:33:25 FedoraPi v2ray[17582]:         /v2ray/src/v2ray.com/core/common/buf/copy.go:128 +0xa4
Aug 26 21:33:25 FedoraPi v2ray[17582]: v2ray.com/core/proxy/vmess/outbound.(*Handler).Process.func2(0x0, 0x0)
Aug 26 21:33:25 FedoraPi v2ray[17582]:         /v2ray/src/v2ray.com/core/proxy/vmess/outbound/outbound.go:123 +0x248
Aug 26 21:33:25 FedoraPi v2ray[17582]: v2ray.com/core/common/task.executeParallel.func1(0x12e7a570, 0x12db85c0, 0x12aa5810)
Aug 26 21:33:25 FedoraPi v2ray[17582]:         /v2ray/src/v2ray.com/core/common/task/task.go:124 +0x1c
Aug 26 21:33:25 FedoraPi v2ray[17582]: created by v2ray.com/core/common/task.executeParallel
Aug 26 21:33:25 FedoraPi v2ray[17582]:         /v2ray/src/v2ray.com/core/common/task/task.go:123 +0xa0
Aug 26 21:33:25 FedoraPi systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

**Comment by ticonci** [comment]
callstack 的日志 怎么调出来？

**Comment by VictoriaRaymond** [comment]
上面的这段就可以了。

你有使用Mux或DNS吗？

**Comment by ticonci** [comment]
DNS有，
"inboundDetour": [
    {
      "listen": "0.0.0.0",
      "port": 5353,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "1.1.1.1",
        "port": 53,
        "network": "udp",
        "timeout": 0,
        "followRedirect": false,
        "userLevel": 0
      },
      "tag": "dns"
    }
  ],

MUX情况也有这个报错，就给disable了

**Comment by VictoriaRaymond** [comment]
尝试修了一下，但并没有确定问题的原因。一会会和 3.37 一起发布。

**Comment by ticonci** [comment]
好，谢谢了。发布了我更新一把再试一遍，到时候我再反馈。

**Comment by ticonci** [comment]
看来还是有这个报错
==============================
Aug 31 19:51:56 FedoraPi systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 31 19:51:56 FedoraPi systemd[1]: v2ray.service: Failed with result 'exit-code'.
Aug 31 19:51:56 FedoraPi systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
Aug 31 19:51:56 FedoraPi systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 36.
Aug 31 19:51:56 FedoraPi systemd[1]: Stopped V2Ray Service.
Aug 31 19:51:56 FedoraPi systemd[1]: Started V2Ray Service.
Aug 31 19:51:56 FedoraPi v2ray[20365]: V2Ray v3.37 (die Commanderin) 20180830
Aug 31 19:51:56 FedoraPi v2ray[20365]: A unified platform for anti-censorship.
Aug 31 19:52:00 FedoraPi v2ray[20365]: panic: runtime error: slice bounds out of range
Aug 31 19:52:00 FedoraPi v2ray[20365]: goroutine 8 [running]:
Aug 31 19:52:00 FedoraPi v2ray[20365]: v2ray.com/core/common/buf.(*Buffer).Read(...)
Aug 31 19:52:00 FedoraPi v2ray[20365]:         /v2ray/src/v2ray.com/core/common/buf/buffer.go:158
Aug 31 19:52:00 FedoraPi v2ray[20365]: v2ray.com/core/common/buf.(*MultiBuffer).Read(0x206dc40, 0x1fd653a, 0x2c6, 0x2c6, 0x14ded8, 0x10, 0x197550)
Aug 31 19:52:00 FedoraPi v2ray[20365]:         /v2ray/src/v2ray.com/core/common/buf/multi_buffer.go:106 +0x330
Aug 31 19:52:00 FedoraPi v2ray[20365]: v2ray.com/core/common/buf.ReadFrom.func1(0x1fd6041, 0x7bf, 0x7bf, 0x19b3c4, 0x5872e0, 0x206dc50)
Aug 31 19:52:00 FedoraPi v2ray[20365]:         /v2ray/src/v2ray.com/core/common/buf/io.go:32 +0x3c
Aug 31 19:52:00 FedoraPi v2ray[20365]: v2ray.com/core/common/buf.(*Buffer).AppendSupplier(0x1d26000, 0x206dc50, 0x206dc50, 0x2f6100)
Aug 31 19:52:00 FedoraPi v2ray[20365]:         /v2ray/src/v2ray.com/core/common/buf/buffer.go:45 +0x58
Aug 31 19:52:00 FedoraPi v2ray[20365]: v2ray.com/core/common/buf.(*BufferedWriter).WriteMultiBuffer(0x206db10, 0x206dbc0, 0x2, 0x3, 0x0, 0x0)
Aug 31 19:52:00 FedoraPi v2ray[20365]:         /v2ray/src/v2ray.com/core/common/buf/writer.go:120 +0xf4
Aug 31 19:52:00 FedoraPi v2ray[20365]: v2ray.com/core/common/crypto.(*AuthenticationWriter).writePacket(0x1f2b320, 0x0, 0x0, 0x0, 0x0, 0x0)
Aug 31 19:52:00 FedoraPi v2ray[20365]:         /v2ray/src/v2ray.com/core/common/crypto/auth.go:318 +0x268
Aug 31 19:52:00 FedoraPi v2ray[20365]: v2ray.com/core/common/crypto.(*AuthenticationWriter).WriteMultiBuffer(0x1f2b320, 0x1f2e010, 0x2, 0x2, 0x0, 0x0)
Aug 31 19:52:00 FedoraPi v2ray[20365]:         /v2ray/src/v2ray.com/core/common/crypto/auth.go:335 +0xb4
Aug 31 19:52:00 FedoraPi v2ray[20365]: v2ray.com/core/common/buf.CopyOnceTimeout(0x6b9f98, 0x1c72b78, 0x6b9b90, 0x1f2b320, 0x5f5e100, 0x0, 0x190980, 0x1d6c301)
Aug 31 19:52:00 FedoraPi v2ray[20365]:         /v2ray/src/v2ray.com/core/common/buf/copy.go:127 +0xa4
Aug 31 19:52:00 FedoraPi v2ray[20365]: v2ray.com/core/proxy/vmess/outbound.(*Handler).Process.func2(0x0, 0x0)
Aug 31 19:52:00 FedoraPi v2ray[20365]:         /v2ray/src/v2ray.com/core/proxy/vmess/outbound/outbound.go:123 +0x348
Aug 31 19:52:00 FedoraPi v2ray[20365]: v2ray.com/core/common/task.executeParallel.func1(0x2028e10, 0x1c80ac0, 0x206e820)
Aug 31 19:52:00 FedoraPi v2ray[20365]:         /v2ray/src/v2ray.com/core/common/task/task.go:162 +0x1c
Aug 31 19:52:00 FedoraPi v2ray[20365]: created by v2ray.com/core/common/task.executeParallel
Aug 31 19:52:00 FedoraPi v2ray[20365]:         /v2ray/src/v2ray.com/core/common/task/task.go:161 +0xa0
Aug 31 19:52:00 FedoraPi systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 31 19:52:00 FedoraPi systemd[1]: v2ray.service: Failed with result 'exit-code'.
Aug 31 19:52:01 FedoraPi systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
Aug 31 19:52:01 FedoraPi systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 37.

**Comment by VictoriaRaymond** [comment]
请试一下 3.37.5，修了一个可能会造成这个错误的问题。

**Comment by ticonci** [comment]
好像一直在重启了
========================================
Sep 01 20:08:49 FedoraPi systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
Sep 01 20:08:49 FedoraPi systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 11.
Sep 01 20:08:49 FedoraPi systemd[1]: Stopped V2Ray Service.
Sep 01 20:08:49 FedoraPi systemd[1]: Started V2Ray Service.
Sep 01 20:08:49 FedoraPi v2ray[21837]: V2Ray v3.37.5 (die Commanderin) 20180831
Sep 01 20:08:49 FedoraPi v2ray[21837]: A unified platform for anti-censorship.
Sep 01 20:08:53 FedoraPi v2ray[21837]: panic: runtime error: slice bounds out of range
Sep 01 20:08:53 FedoraPi v2ray[21837]: goroutine 24 [running]:
Sep 01 20:08:53 FedoraPi v2ray[21837]: v2ray.com/core/common/buf.(*Buffer).Read(...)
Sep 01 20:08:53 FedoraPi v2ray[21837]:         /v2ray/src/v2ray.com/core/common/buf/buffer.go:158
Sep 01 20:08:53 FedoraPi v2ray[21837]: v2ray.com/core/common/buf.(*MultiBuffer).Read(0x1114230, 0x14da541, 0x2bf, 0x2bf, 0xd4, 0x5872f0, 0x5)
Sep 01 20:08:53 FedoraPi v2ray[21837]:         /v2ray/src/v2ray.com/core/common/buf/multi_buffer.go:106 +0x330
Sep 01 20:08:53 FedoraPi v2ray[21837]: v2ray.com/core/common/buf.ReadFrom.func1(0x14da048, 0x7b8, 0x7b8, 0x19b49c, 0x5872f0, 0x1114240)
Sep 01 20:08:53 FedoraPi v2ray[21837]:         /v2ray/src/v2ray.com/core/common/buf/io.go:32 +0x3c
Sep 01 20:08:53 FedoraPi v2ray[21837]: v2ray.com/core/common/buf.(*Buffer).AppendSupplier(0x14dc000, 0x1114240, 0x1114240, 0x0)
Sep 01 20:08:53 FedoraPi v2ray[21837]:         /v2ray/src/v2ray.com/core/common/buf/buffer.go:45 +0x58
Sep 01 20:08:53 FedoraPi v2ray[21837]: v2ray.com/core/common/buf.(*BufferedWriter).WriteMultiBuffer(0x14dc020, 0x11141c0, 0x2, 0x3, 0x0, 0x0)
Sep 01 20:08:53 FedoraPi v2ray[21837]:         /v2ray/src/v2ray.com/core/common/buf/writer.go:135 +0x12c
Sep 01 20:08:53 FedoraPi v2ray[21837]: v2ray.com/core/common/crypto.(*AuthenticationWriter).writePacket(0x14d2090, 0x0, 0x0, 0x0, 0x0, 0x0)
Sep 01 20:08:53 FedoraPi v2ray[21837]:         /v2ray/src/v2ray.com/core/common/crypto/auth.go:318 +0x268
Sep 01 20:08:53 FedoraPi v2ray[21837]: v2ray.com/core/common/crypto.(*AuthenticationWriter).WriteMultiBuffer(0x14d2090, 0x1116120, 0x2, 0x2, 0x0, 0x0)
Sep 01 20:08:53 FedoraPi v2ray[21837]:         /v2ray/src/v2ray.com/core/common/crypto/auth.go:335 +0xb4
Sep 01 20:08:53 FedoraPi v2ray[21837]: v2ray.com/core/common/buf.CopyOnceTimeout(0x6ba040, 0x1116080, 0x6b9c38, 0x14d2090, 0x5f5e100, 0x0, 0x190980, 0x1075601)
Sep 01 20:08:53 FedoraPi v2ray[21837]:         /v2ray/src/v2ray.com/core/common/buf/copy.go:127 +0xa4
Sep 01 20:08:53 FedoraPi v2ray[21837]: v2ray.com/core/proxy/vmess/outbound.(*Handler).Process.func2(0x0, 0x0)
Sep 01 20:08:53 FedoraPi v2ray[21837]:         /v2ray/src/v2ray.com/core/proxy/vmess/outbound/outbound.go:123 +0x348
Sep 01 20:08:53 FedoraPi v2ray[21837]: v2ray.com/core/common/task.executeParallel.func1(0x1087c30, 0x1075900, 0x13078b0)
Sep 01 20:08:53 FedoraPi v2ray[21837]:         /v2ray/src/v2ray.com/core/common/task/task.go:162 +0x1c
Sep 01 20:08:53 FedoraPi v2ray[21837]: created by v2ray.com/core/common/task.executeParallel
Sep 01 20:08:53 FedoraPi v2ray[21837]:         /v2ray/src/v2ray.com/core/common/task/task.go:161 +0xa0
Sep 01 20:08:53 FedoraPi systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 01 20:08:53 FedoraPi systemd[1]: v2ray.service: Failed with result 'exit-code'.
Sep 01 20:08:54 FedoraPi systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
Sep 01 20:08:54 FedoraPi systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 12.

**Comment by ticonci** [comment]
hi，有的，不知道是不是DNS的问题，麻烦再看看（这是新运行的日志，时间点journal的输出和上面一样）
===========
2018/09/01 22:26:00 [Warning] Core: V2Ray v3.37.5 started
2018/09/01 22:26:00 [Debug] [2998047986] Proxy|Dokodemo: processing connection from: 192.168.1.222:5353
2018/09/01 22:26:00 [Info] [2998047986] App|Dispatcher: taking detour [dns_server] for [udp:1.1.1.1:53]
2018/09/01 22:26:00 [Info] [2998047986] Transport|Internet|WebSocket: creating connection to tcp:mydomain.com:443
2018/09/01 22:26:01 [Debug] [2115958683] Proxy|Dokodemo: processing connection from: 192.168.1.18:53990
2018/09/01 22:26:01 [Info] [2115958683] App|Dispatcher: sniffed domain: www.google.com
2018/09/01 22:26:01 [Info] [2115958683] App|Dispatcher: taking detour [to-default-tls] for [tcp:www.google.com:80]
2018/09/01 22:26:01 [Info] [2115958683] Transport|Internet|WebSocket: creating connection to tcp:mydomain.com:443
2018/09/01 22:26:01 [Info] [2115958683] Proxy|VMess|Outbound: tunneling request to tcp:www.google.com:80 via tcp:mydomain.com:443
2018/09/01 22:26:01 [Info] [2998047986] Proxy|VMess|Outbound: tunneling request to udp:1.1.1.1:53 via tcp:mydomain.com:443
2018/09/01 22:26:05 [Debug] App|Log: Logger started
2018/09/01 22:26:05 [Warning] Core: V2Ray v3.37.5 started
2018/09/01 22:26:07 [Debug] [3265577977] Proxy|Dokodemo: processing connection from: 192.168.1.18:53994
2018/09/01 22:26:07 [Debug] [1846282772] Proxy|Dokodemo: processing connection from: 192.168.1.18:53995
2018/09/01 22:26:07 [Info] [1846282772] App|Dispatcher: sniffed domain: connectivitycheck.gstatic.com
2018/09/01 22:26:07 [Info] [3265577977] App|Dispatcher: sniffed domain: www.google.com
2018/09/01 22:26:07 [Info] [1846282772] App|Dispatcher: taking detour [to-default-tls] for [tcp:connectivitycheck.gstatic.com:80]
2018/09/01 22:26:07 [Info] [3265577977] App|Dispatcher: taking detour [to-default-tls] for [tcp:www.google.com:443]
2018/09/01 22:26:07 [Info] [1846282772] Transport|Internet|WebSocket: creating connection to tcp:mydomain.com:443
2018/09/01 22:26:07 [Info] [3265577977] Transport|Internet|WebSocket: creating connection to tcp:mydomain.com:443
2018/09/01 22:26:07 [Info] [1846282772] Proxy|VMess|Outbound: tunneling request to tcp:connectivitycheck.gstatic.com:80 via tcp:mydomain.com:443
2018/09/01 22:26:07 [Info] [3265577977] Proxy|VMess|Outbound: tunneling request to tcp:www.google.com:443 via tcp:mydomain.com:443
2018/09/01 22:26:11 [Debug] [1608711521] Proxy|Dokodemo: processing connection from: 192.168.1.222:5353
2018/09/01 22:26:11 [Info] [1608711521] App|Dispatcher: taking detour [dns_server] for [udp:1.1.1.1:53]
2018/09/01 22:26:11 [Info] [1608711521] Transport|Internet|WebSocket: creating connection to tcp:mydomain.com:443
2018/09/01 22:26:11 [Info] [1608711521] Proxy|VMess|Outbound: tunneling request to udp:1.1.1.1:53 via tcp:mydomain.com:443
2018/09/01 22:26:14 [Debug] App|Log: Logger started
2018/09/01 22:26:14 [Warning] Core: V2Ray v3.37.5 started
2018/09/01 22:26:15 [Debug] [1070019211] Proxy|Dokodemo: processing connection from: 192.168.1.222:5353
2018/09/01 22:26:15 [Info] [1070019211] App|Dispatcher: taking detour [dns_server] for [udp:1.1.1.1:53]
2018/09/01 22:26:15 [Info] [1070019211] Transport|Internet|WebSocket: creating connection to tcp:mydomain.com:443
2018/09/01 22:26:15 [Debug] [3913947353] Proxy|Dokodemo: processing connection from: 192.168.1.18:53996
2018/09/01 22:26:15 [Info] [3913947353] App|Dispatcher: sniffed domain: client.wns.windows.com
2018/09/01 22:26:15 [Info] [3913947353] App|Dispatcher: taking detour [to-default-tls] for [tcp:client.wns.windows.com:443]
2018/09/01 22:26:15 [Info] [3913947353] Transport|Internet|WebSocket: creating connection to tcp:mydomain.com:443
2018/09/01 22:26:15 [Info] [1070019211] Proxy|VMess|Outbound: tunneling request to udp:1.1.1.1:53 via tcp:mydomain.com:443
2018/09/01 22:26:19 [Debug] App|Log: Logger started
2018/09/01 22:26:19 [Warning] Core: V2Ray v3.37.5 started

**Comment by VictoriaRaymond** [comment]
请试一下 3.37.6

**Comment by ticonci** [comment]
这下可以了，不报错了，非常感谢!!

**Comment by ticonci** [comment]
error logl里面一直出现这类closed pipe的log，这个能帮忙看看么？
===================================
2018/09/02 13:06:29 [Debug] [1139912285] Proxy|Dokodemo: processing connection from: 192.168.1.18:49908
2018/09/02 13:06:29 [Info] [1139912285] App|Dispatcher: sniffed domain: ctldl.windowsupdate.com
2018/09/02 13:06:29 [Info] [1139912285] App|Dispatcher: taking detour [to-default-tls] for [tcp:ctldl.windowsupdate.com:80]
2018/09/02 13:06:29 [Info] [1139912285] Transport|Internet|WebSocket: creating connection to tcp:mydomain.com:443
2018/09/02 13:06:29 [Info] App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > context canceled
2018/09/02 13:06:29 [Info] [2053743124] App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > context canceled
2018/09/02 13:06:30 [Info] [1139912285] Proxy|VMess|Outbound: tunneling request to tcp:ctldl.windowsupdate.com:80 via tcp:mydomain.com:443
2018/09/02 13:06:30 [Info] [1346923533] App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > websocket: close 1006 (abnormal closure): unexpected EOF
2018/09/02 13:06:30 [Info] [1346923533] App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport response > io: read/write on closed pipe
2018/09/02 13:06:30 [Info] [1906831846] App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > websocket: close 1006 (abnormal closure): unexpected EOF
2018/09/02 13:06:30 [Info] [1906831846] App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport response > io: read/write on closed pipe
2018/09/02 13:06:31 [Info] [4277338403] App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > websocket: close 1006 (abnormal closure): unexpected EOF
2018/09/02 13:06:31 [Info] [4277338403] App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport response > io: read/write on closed pipe
2018/09/02 13:06:32 [Info] [3952676309] App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > websocket: close 1006 (abnormal closure): unexpected EOF
2018/09/02 13:06:32 [Info] [3952676309] App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport response > io: read/write on closed pipe
2018/09/02 13:06:33 [Info] [2269985784] App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > websocket: close 1006 (abnormal closure): unexpected EOF
2018/09/02 13:06:33 [Info] [2269985784] App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport response > io: read/write on closed pipe
2018/09/02 13:06:33 [Info] [2098337714] App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > websocket: close 1006 (abnormal closure): unexpected EOF
2018/09/02 13:06:33 [Info] [2098337714] App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport response > io: read/write on closed pipe
2018/09/02 13:06:35 [Info] [3208488586] App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > websocket: close 1006 (abnormal closure): unexpected EOF
2018/09/02 13:06:35 [Info] [3208488586] App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport response > io: read/write on closed pipe

**Comment by VictoriaRaymond** [comment]
不是Warning或者Error的错误都是正常的
