### ISSUE TITLE
请问v2ray中的uplinkonly和downlink是什么意思？看文档说明还是看不懂

### ISSUE THREAD

**Issue by mrzenwell** [v2ray/v2ray-core#1246]
麻烦作者具体解释下uplinkonly和downlinkonly，谢谢

**Comment by Chandler-Lu** [comment]
```
"downlinkOnly": 5,
```
客服：您好先生，还有什么需要帮助的吗？
（动作：关闭浏览器）
客服：您好先生，还在吗？（1s）
客服：您好先生，还在吗？（2s）
客服：您好先生，还在吗？（3s）
客服：您好先生，还在吗？（4s）
客服：您好先生，还在吗？（5s）
客服：MD不玩了！感谢使用本公司在线客服，本次会话已结束，请在会话结束后给予我们评价

**Comment by mrzenwell** [comment]
哈哈哈生动形象
