### ISSUE TITLE
路由器科学上网插件里面的V2ray,速度比在手机和电脑上慢了很多。

### ISSUE THREAD

**Issue by asp250** [v2ray/v2ray-core#1248]
插件配置文件如下
路由器连接的是猫，
VPS是bbr加速的。插件说利用配置文件只抽取outbound的内容，支持所有协议，但是我用配置文件和不使用配置文件速度都没有变化，应该是没有支持SOCK的原因。配置文件除了outbound之外的肯定都没有用上。但是路由器开三个终端看YouTube，速度基本都一样。我用SS+KCP加速，速度能提升一倍，我就很是不解了，本来SS+KCP是没有v2ray+bbr速度快的。
{
  "log": {
    "error": "error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 23456,
    "listen": "0.0.0.0",
    "protocol": "socks",
    "domainOverride": ["tls", "http"],
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "0.0.0.0"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [{
        "address": "101.0.0.1",
        "port": 12456,
        "users": [{
          "id": "11111-1111-1111-111-111111",
          "alterId": 111,
          "security": "auto"
        }]
      }]
    },
    "mux": {
      "enabled": true
    }
  },
  "inboundDetour": [{
    "domainOverride": ["tls", "http"],
    "port": 23456,
    "listen": "0.0.0.0",
    "protocol": "http",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "0.0.0.0"
    }
  }],
  "outboundDetour": [{
    "protocol": "freedom",
    "settings": {},
    "tag": "direct"
  }],
  "dns": {
    "servers": ["8.8.8.8", "8.8.4.4", "localhost"]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [{
        "type": "field",
        "ip": ["0.0.0.0/8", "10.0.0.0/8", "100.64.0.0/10", "127.0.0.0/8", "169.254.0.0/16", "172.16.0.0/12", "192.0.0.0/24", "192.0.2.0/24", "192.168.0.0/16", "198.18.0.0/15", "198.51.100.0/24", "203.0.113.0/24", "::1/128", "fc00::/7", "fe80::/10", "geoip:cn"],
        "domain": ["geosite:cn"],
        "outboundTag": "direct"
      },
      {
        "type": "chinasites",
        "outboundTag": "direct"
      },
      {
        "type": "chinaip",
        "outboundTag": "direct"
      }]
    }
  }
}

**Comment by DarienRaymond** [comment]
Kamino closed and cloned this issue to [v2ray/discussion](https://github.com/v2ray/discussion/issues/23)
