### ISSUE TITLE
V2Ray大流量经常死掉！

### ISSUE THREAD

**Issue by d808b** [v2ray/v2ray-core#125]
软件环境：
OpenVZ
localhost.localdomain   [WAGONV2-10G]
Physical Location:	US, California    Node ID: v426    VPS ID: 149167
IP address:
SSH Port:	28187
Status:	Running (19 processes; LA: 0.00/0.00/0.00)
Actions:	
RAM:	15.77/256 MB
SWAP:	1.37/128 MB
Disk usage (/):	0.49/12 GB
Bandwidth usage:6.5/550 GB
Resets: 2016-05-09	
Operating system:	Ubuntu 14.04 x86_64 minimal   

root@localhost:~# ps ax
  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:00 init
    2 ?        S      0:00 [kthreadd/149167]
    3 ?        S      0:00 [khelper/149167]
  182 ?        Ss     0:00 /lib/systemd/systemd-udevd --daemon
  283 ?        S      0:00 upstart-file-bridge --daemon
  284 ?        S      0:00 upstart-socket-bridge --daemon
  424 ?        Ss     0:00 /usr/sbin/sshd -D
  456 ?        Sl     0:08 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
  479 tty1     Ss+    0:00 /sbin/getty 38400 console
  481 tty2     Ss+    0:00 /sbin/getty 38400 tty2
  513 ?        Ss     0:00 sshd: root@pts/0    
  524 pts/0    Ss     0:00 -bash
  530 pts/0    R+     0:00 ps ax
root@localhost:~# uname -msr
Linux 2.6.32-042stab113.21 x86_64
root@localhost:~# dpkg -l | grep golang
root@localhost:~# free -m
             total       used       free     shared    buffers     cached
Mem:           256         30        225          2          0         20
-/+ buffers/cache:          9        246
Swap:          128          1        126
root@localhost:~# netstat -an | grep LISTEN
tcp        0      0 0.0.0.0:28187           0.0.0.0:*               LISTEN     
tcp6       0      0 :::1873                 :::*                    LISTEN     
tcp6       0      0 :::28187                :::*                    LISTEN     
unix  2      [ ACC ]     SEQPACKET  LISTENING     711098173 /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     711097713 @/com/ubuntu/upstart

**Comment by bhzhu203** [comment]
内存超过openvz的限制了吧？ 建议把其它占用内存的程序关掉。因为本身v2ray也挺占用内存的

**Comment by v2ray** [comment]
这是一个已知问题，还在研究中，V2Ray 在某种情况下会瞬间消耗大量内存而导致内存不足。具体原因还不清楚。

**Comment by Talent30** [comment]
服务器启用一段时间之后内存会瞬间占满CPU占有率100%

**Comment by wtlusvm** [comment]
一看就知道是搬瓦工的VPS

作者已经在修复了，个人无责任猜测是多线程状态下缓存过大引起的

**Comment by d808b** [comment]
升级v1.12.6后，已经解决！谢谢大家！
