### ISSUE TITLE
服务器端设置如何采用黑名单或者白名单访问机制

### ISSUE THREAD

**Issue by yifan513** [v2ray/v2ray-core#1251]
如题：
Ubuntu18的VPS，采用最新版本和确实的配置，工作正常。现在想共享给朋友，但是担心流量超标，想禁止访问youtube和黄色站点，请问如何设置黑名单或者实现白名单机制？
谢谢！

**Comment by Chandler-Lu** [comment]
把手册看一遍吧。。利用路由的block就可以做
https://www.v2ray.com/chapter_02/03_routing.html

**Comment by yifan513** [comment]
谢谢，使用 "outboundTag": "blocked"的确可以实现黑名单，之前是因为IP和Domain同时使用造成不工作，去掉IP就好了。
请问有没有可能实现白名单，就是只能上指定的系列网站呢？

**Comment by Chandler-Lu** [comment]
domain和ip不应在在同一组内，否则将同时匹配domain和ip是否在规则之内。大概类似这样
```
"rules": [
      {
        "type": "field",
        "domain": [
          "baidu.com",
          "qq.com"
        ],
        "outboundTag": "direct"
      },
     {
        "type": "field",
        "ip": [
          "192.168.1.1"
        ],
        "outboundTag": "direct"
      }
    ]
```

**Comment by yifan513** [comment]
恩，知道了，谢谢。
对于白名单机制，现在是否只能自行修改code，否则还是不能实现，对吗？

**Comment by Chandler-Lu** [comment]
这个我不清楚，但是实话说作为一个梯子，白名单真的是没有必要。。

**Comment by nicholascw** [comment]
Read the manual.
