### ISSUE TITLE
关于多IP方面的疑问

### ISSUE THREAD

**Issue by i258559** [v2ray/v2ray-core#1252]
Please skip to the English section below if you don't write Chinese.

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
     3.38

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
     VMess/TCP看网页，玩游戏

3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
     服务器有多个IP，但无论用哪个IP接入，被访网页那边都是显示使用主IP进行访问（早起SSR也有该问题，后面修复了）

4)  你期待看到的正确表现是怎样的？
     用哪个IP访问，被访网页那边显示对应的IP而不是主IP

5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
{
    "log": {
        "access": "/var/log/v2ray/access.log",
        "error": "/var/log/v2ray/error.log",
        "loglevel": "warning"
    },
    "inbound":{
        "port":3389,
        "protocol":"vmess",
        "settings":{
            "udp": true,
            "clients":[
                {
                    "id":"隐藏的码",
                    "levels": {
                        "1": {
                            "handshake": 8,
                            "connIdle": 300,
                            "uplinkOnly": 5,
                            "downlinkOnly": 10,
                            "bufferSize": 20480
                            }
                    },
                    "alterId":128
                }
            ],
			"disableInsecureEncryption":true
        },
        "streamSettings":{
            "network":"tcp"
        },
        "detour":{
            "to":"dynport"
        }
    },
    "outbound":{
        "protocol":"freedom",
        "settings":{

        }
    },
    "inboundDetour":[
        {
            "protocol":"vmess",
            "port":"16380-36490",
            "tag":"dynport",
            "settings":{

            },
            "allocate":{
                "strategy":"random",
                "concurrency":3,
                "refresh":8
            },
            "streamSettings":{
                "network":"tcp"
            }
        }
    ],
    "outboundDetour":[
        {
            "protocol":"blackhole",
            "settings":{

            },
            "tag":"blocked"
        }
    ],
    "routing":{
        "strategy":"rules",
        "settings":{
            "rules":[
                {
                    "type":"field",
                    "ip":[
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "203.0.113.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10"
                    ],
                    "outboundTag":"blocked"
                }
            ]
        }
    }
}

    客户端配置:
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 1080,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "127.0.0.1",
      "clients": null
    },
    "streamSettings": null
  },
  "outbound": {
    "tag": "agentout",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "100.100.100.1",
          "port": 3389,
          "users": [
            {
              "id": "隐藏的码",
              "alterId": 128,
              "security": "aes-128-gcm"
            }
          ]
        }
      ],
      "servers": null
    },
    "streamSettings": {
      "network": "tcp",
      "security": "",
      "tlsSettings": null,
      "tcpSettings": null,
      "kcpSettings": null,
      "wsSettings": null,
      "httpSettings": null
    },
    "mux": {
      "enabled": true
    }
  },
  "inboundDetour": null,
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {
        "response": null
      },
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "blockout"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": null,
          "outboundTag": "direct",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "domain": null
        }
      ]
    }
  }
}

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
     其实没有错误，都是可用的

**Comment by TanNang** [comment]
你可能需要配置 sendThrough
请参考：https://www.v2ray.com/chapter_02/01_overview.html

**Comment by i258559** [comment]
"outboundDetour": [
{
"sendThrough": "100.100.100.2",
"protocol": "blackhole",
"settings": {},
"tag": "blocked"
}
新的疑问：
在outbound的“sendThrough”指定副IP，可生效，
而在在outboundDetour的“sendThrough”指定副IP貌似不起作用（outbound为缺省主IP）0.0

====== 服务器配置文件如下 ======

{
    "inbound": {
        "port": 80,
        "protocol": "vmess",
        "settings": {
            "clients": [
                {
                    "id": "f9258dae-1d07-ac03-de0f-ad1944af5c3c",
                    "level": 1,
                    "alterId": 96
                }
            ]
        },
        "detour": {
            "to": "vmess-detour-640328"
        }
    },
    "outbound": {
        "protocol": "freedom",
        "settings": {}
    },
    "inboundDetour": [
        {
            "protocol": "vmess",
            "port": "12000-16000",
            "tag": "vmess-detour-640328",
            "settings": {},
            "allocate": {
                "strategy": "random",
                "concurrency": 4,
                "refresh": 10
            }
        },
        {
            "port": 3389,
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "f2e02c12-49cd-4145-7c93-242ad7d8c3a5",
                        "level": 1,
                        "alterId": 128
                    }
                ]
            },
            "detour": {
                "to": "vmess-detour-68873"
            }
        },
        {
            "protocol": "vmess",
            "port": "40000-44000",
            "tag": "vmess-detour-68873",
            "settings": {},
            "allocate": {
                "strategy": "random",
                "concurrency": 4,
                "refresh": 10
            }
        }
    ],
    "outboundDetour": [
        {
            "sendThrough": "100.100.100.2",
            "protocol": "blackhole",
            "settings": {},
            "tag": "blocked"
        }
    ],
    "routing": {
        "strategy": "rules",
        "settings": {
            "rules": [
                {
                    "type": "field",
                    "ip": [
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "203.0.113.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10"
                    ],
                    "outboundTag": "blocked"
                }
            ]
        }
    }
}
