### ISSUE TITLE
功能请求：路由规则可以增加url匹配吗

### ISSUE THREAD

**Issue by 523860169** [v2ray/v2ray-core#1256]
目前，路由只能对域名、端口、ip等进行代理，针对的也是GFW的屏蔽策略，但是像网站主动屏蔽中国ip，或者网站内部分内容对中国IP不可见，就有点缺乏灵活，只能对整个域名进行代理。
比如Apple Store的国际版就屏蔽了中国ip，返回404，而访问中国版就正常
https://itunes.apple.com/us/app/qq/id444934666?mt=8
https://itunes.apple.com/cn/app/qq/id444934666?mt=8
以上两个链接在代理后都能打开，但是不代理的情况下，上面404，下面正常
所以只要代理itunes.apple.com/us/就可以了

**Comment by TanNang** [comment]
如要对 https url 进行判断，可能需要 MITM 才能获取 url 信息。

**Comment by DarienRaymond** [comment]
Kamino closed and cloned this issue to [v2ray/Planning](https://github.com/v2ray/Planning/issues/69)
