### ISSUE TITLE
性能测试 校验问题

### ISSUE THREAD

**Issue by yinliangc** [v2ray/v2ray-core#1257]
https://steemit.com/cn/@v2ray/3cjiux

> 很有趣的一点是 None 居然比 GCM 慢。不加密反而比加密慢，有一点违反常识。原因是这样的：VMess 不管加不加密，都会进行数据校验，None 中使用的校验算法是 FNV，而 GCM 是一个 AEAD 算法，自带校验。于是带 CPU 加成的校验比软件实现的校验快了不小。这一点也超出了开发人员的预期，之后会考虑提升校验的性能。

请问这个问题解决了吗，目前 tls 参与的配置，似乎并不需要 GCM 加密，如果 none 的话，应该会提升性能，前提是校验的性能， 请问，现在 none 的问题解决了吗

**Comment by VictoriaRaymond** [comment]
解决了。
