### ISSUE TITLE
cpu负载高

### ISSUE THREAD

**Issue by cnperi** [v2ray/v2ray-core#126]
我在两台vps上架设了v2ray，1.11.2版的，同时开了vmess和shadowsocks。
平时主要用shadowsocks连接，运行一段时间后（2～6小时后）出现cpu负载高，导致无法连接。
在没有开shadowsocks的时候，没有这种问题。

**Comment by cnperi** [comment]
ps H -e -o pid,tid,pcpu,cmd --sort=pcpu |grep 7303
 8352  8352  0.0 grep --color=auto 7303
 7303  7305  0.1 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
 7303  7303 13.1 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
 7303  7308 14.0 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
 7303  7306 14.1 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
 7303  7774 22.2 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json

**Comment by v2ray** [comment]
为什么要同时开启多个进程？一个配置文件搞不定？

**Comment by cnperi** [comment]
没有多开进程啊，就是一个配置文件。

**Comment by cnperi** [comment]
配置文件就这样，是我配置有问题？
{
  "port": ×××××,
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "error"
  },
  "inbound": {
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "XXXXXXX",
          "level": 1,
          "alterId": 100
        }
      ]
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "inboundDetour": [
    {
      "protocol": "shadowsocks",
      "port": XXXX,
      "settings": {
        "method": "aes-256-cfb",
        "password": "mypassword",
        "udp": true,  
        "level": 1
      }
    }
  ],
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}

**Comment by v2ray** [comment]
哦，我之前看错了。配置文件看上去没有问题，Shadowsocks 的问题我要再研究一下。

**Comment by v2ray** [comment]
错误日志里有什么关于 Shadowsocks 的内容么？

**Comment by cnperi** [comment]
都是这类的错误：
[Error]Shadowsocks: Failed to read IV: read tcp x.x.x.x:ports ->112.224.21.157:28521: i/o timeout

**Comment by Talent30** [comment]
如果只用SS的话可以试试看我这个配置文件
{
  "port": 1080,
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",  
    "loglevel": "warning"
  },
  "inbound": {
      "protocol": "shadowsocks",  
      "port": 443, 
      "settings": {
        "method": "chacha20-ietf", 
        "password": "Zd2C$P",     
        "udp": true             
      }
    },
  "outbound": {    
    "protocol": "freedom",
    "settings": {}
    
  }
}
昨天精简了一下用到现在都没有发现问题，以前用官方WIKI上的也是跟你一样爆内存CPU 100%

**Comment by Talent30** [comment]
> {
>   "port": 1080,
>   "log": {
>     "access": "/var/log/v2ray/access.log",
>     "error": "/var/log/v2ray/error.log",  
>     "loglevel": "warning"
>   },
>   "inbound": {
>       "protocol": "shadowsocks",  
>       "port": 443, 
>       "settings": {
>         "method": "chacha20-ietf", 
>         "password": "Zd2C$P",     
>         "udp": true             
>       }
>     },
>   "outbound": {    
>     "protocol": "freedom",
>     "settings": {}
>     
>   }
> }
>

**Comment by Talent30** [comment]
```
{
  "port": 1080,
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",  
    "loglevel": "warning"
  },
  "inbound": {
      "protocol": "shadowsocks",  
      "port": 443, 
      "settings": {
        "method": "chacha20-ietf", 
        "password": "Zd2C$P",     
        "udp": true             
      }
    },
  "outbound": {    
    "protocol": "freedom",
    "settings": {}
    
  }
}

```

**Comment by Talent30** [comment]
为什么你SS这里会有个用户Level？

```
"inboundDetour": [
    {
      "protocol": "shadowsocks",
      "port": XXXX,
      "settings": {
        "method": "aes-256-cfb",
        "password": "mypassword",
        "udp": true,  
        "level": 1
      }
    }
  ],
```

**Comment by tlze** [comment]
lever 1 表示信任用户，比较少限制。同Vmesg协议的解释，文档有写。

**Comment by Talent30** [comment]
```
{
  "port": 443,
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",  
    "loglevel": "warning"
  },
  "inbound": {
      "protocol": "shadowsocks",  
      "port": 443, 
      "settings": {
        "method": "chacha20-ietf", 
        "password": "XXXXX",     
        "udp": true 
        "level": 1         
      }
    },
  "outbound": {    
    "protocol": "freedom",
    "settings": {}

  }
}
```
加入以后在服务器上启动失败

**Comment by Talent30** [comment]
```
{
  "port": 37192, // 主端口
  "log" : {
    "access": "/var/log/v2ray/access.log", // 访问日志文件
    "error": "/var/log/v2ray/error.log",   // 错误日志文件
    "loglevel": "warning"                  // 错误日志等级，可选 debug / info / warning / error
  },
  "inbound": {
    "protocol": "vmess",    // 主传入协议，参见协议列表
    "settings": {
      "clients": [
        {
          "id": "3b129dec-72a3-4d28-aeee-028a0fe86e22",  // 用户 ID，客户端须使用相同的 ID 才可以中转流量
          "level": 1  // 用户等级，自用 VPS 可设为 1；共享 VPS 请设为 0。
        }
      ]
    }
  },
  "outbound": {
    "protocol": "freedom",  // 主传出协议，参见协议列表
    "settings": {}
  },
  "inboundDetour": [
    {
      "protocol": "shadowsocks",   // 开启 Shadowsocks
      "port": 30001, // 监听 30001 端口
      "settings": {
        "method": "aes-256-cfb", // 加密方式，支持 aes-256-cfb 和 aes-128-cfb
        "password": "v2ray",     // 密码，必须和客户端相同
        "udp": false             // 是否开启 UDP 转发
      }
    },
    {
      "protocol": "shadowsocks",   // 开启 Shadowsocks
      "port": 30002, // 监听 30002 端口，由于 Shadowsocks 的限制，多用户的时候只能开多个端口
      "settings": {  // 配置和上述类似
        "method": "aes-256-cfb",
        "password": "v2ray-2",
        "udp": false
      }
    }
  ],
  "outboundDetour": [
    {
      "protocol": "blackhole",  // 额外的传出协议，参见协议列表
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",  // 路由设置，默认将屏蔽所有局域网流量，以提升安全性。
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}
```
官方配置这里也没有Level

**Comment by tlze** [comment]
"udp": true,      这里少了个",".
 "level": 1

**Comment by Talent30** [comment]
谢谢！

**Comment by tlze** [comment]
https://www.v2ray.com/zh_cn/chapter_02/protocols/shadowsocks.html

协议描述：
    名称：shadowsocks
    版本：V2Ray 1.6+
    类型：Inbound
    配置：
    {
    "method": "加密方式",
    "password": "密码",
    "udp": false,
    "level": 0
    }
其中：
    method: 加密方式，没有默认值。可选的值有：
        aes-256-cfb
        aes-128-cfb
        chacha20
        chacha20-ietf
    password: 密码，任意字符串。Shadowsocks 协议并不限制密码长度，但短密码会更可能被破解，建议使用 16 字符或更长的密码。
    udp: true / false，是否开启 UDP 转发，默认值为 false。
    level (V2Ray 1.7+): 用户等级，默认值为 0。如果是自用的 VPS，可以设成 1。详见 VMess 中的 level 选项。

**Comment by Talent30** [comment]
看到了，谢谢！

**Comment by Talent30** [comment]
即使是正确的语法也不行。。。。
```
{
  "port": 443,
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",  
    "loglevel": "warning"
  },
  "inbound": [
    {
      "protocol": "shadowsocks",  
      "port": 443, 
      "settings": {
        "method": "chacha20-ietf", 
        "password": XXX",     
        "udp": true,
        "level": 0
      }
    }
  ],
  "outbound": {    
    "protocol": "freedom",
    "settings": {}

  }
}
```
```
● v2ray.service - V2Ray Service
   Loaded: loaded (/lib/systemd/system/v2ray.service; enabled)
   Active: inactive (dead) since Sat 2016-04-30 00:03:52 EDT; 2s ago
  Process: 490 ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json (code=exited, status=0/SUCCESS)
 Main PID: 490 (code=exited, status=0/SUCCESS)

Apr 30 00:03:52 JonSun systemd[1]: Starting V2Ray Service...
Apr 30 00:03:52 JonSun systemd[1]: Started V2Ray Service.
Apr 30 00:03:52 JonSun v2ray[490]: V2Ray v1.11.2 (New Order) 20160419
Apr 30 00:03:52 JonSun v2ray[490]: An unified platform for anti-censorship.
Apr 30 00:03:52 JonSun v2ray[490]: 2016/04/30 00:03:52 [Error]Failed to load server config: json: cannot unmarshal array into...onConfig
Apr 30 00:03:52 JonSun v2ray[490]: 2016/04/30 00:03:52 [Error]Failed to read config file (/etc/v2ray/config.json): /etc/v2ray...onConfig

```

**Comment by cnperi** [comment]
升级至1.12.3后，已经稳定运行了10个小时了，貌似没有问题了。

**Comment by v2ray** [comment]
Consider this is fixed.

**Comment by cnperi** [comment]
还是有cpu爆表的情况。两台服务器，一台6-10小时左右出现一次，一台运行了40多少小时出现了一次。

**Comment by v2ray** [comment]
@cnperi Shadowsocks 开 UDP 了么？

**Comment by cnperi** [comment]
@v2ray 都开了

**Comment by v2ray** [comment]
可以尝试关闭 shadowsocks 的 UDP 看看，目前 shadowsocks 的 UDP 部分没有良好的测试。其它的应该没问题。

**Comment by cnperi** [comment]
那样不就没法测试udp部分了吗？我现在的办法是用crontab，每6小时restart一次:(
