### ISSUE TITLE
Add an API to clear stats

### ISSUE THREAD

**Issue by t123yh** [v2ray/v2ray-core#1261]
It would be nice if an API could be added to clear the traffic statistics for every or each user. (Or it would be better if there's an API that returns stat data while resetting them at the same time.) This way it will be easier to implement accurate traffic accounting.

**Comment by nobody3u** [comment]
那么问题来了，你现目前是用什么参数来调用他的流量统计API的？

**Comment by t123yh** [comment]
Sorry, I didn't read the code carefully.
