### ISSUE TITLE
PAC模式无法上BBC中文和SSRShare;全局模式绕过大陆地址和IP看国内网站卡顿

### ISSUE THREAD

**Issue by willaytoun** [v2ray/v2ray-core#1267]
PAC模式无法上BBC和SSRShare，平时浏览的网站不多暂时只知道这两个。
全局模式参数设置里点击绕过大陆地址和IP，国外网站没有发现不可以上的，但是看国内网站明显卡顿。看虎牙、斗鱼直播有时一直加载不出画面，其它的不经常用。

PS：PAC模式选择第二项自动配置PAC；全局模式设置上传文件中
![image](https://user-images.githubusercontent.com/43229736/45612178-cd793900-ba94-11e8-8273-166bdfaf4b2a.png)

**Comment by Chandler-Lu** [comment]
这里是core的issue，不是v2rayng的issue。。看清楚发。。
你自己把你要代理的网站域名丢进列表不就完了
