### ISSUE TITLE
一键安装脚本未能成功识别树莓派(Raspberry Pi B)

### ISSUE THREAD

**Issue by wtlusvm** [v2ray/v2ray-core#127]
树莓派型号为Raspberry Pi B.
安装输出信息如下:

> root@raspberrypi:/home/pi# bash <(curl -L -s https://raw.githubusercontent.com/v2ray/v2ray-core/master/release/install-release.sh)
> Updating software repo via apt-get.
> Installing curl via apt-get.
> Installing unzip via apt-get.
> Downloading https://github.com/v2ray/v2ray-core/releases/download/v1.11.2/v2ray-linux-64.zip directly.
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   595    0   595    0     0    219      0 --:--:--  0:00:02 --:--:--   219
> 100 2129k  100 2129k    0     0  46324      0  0:00:47  0:00:47 --:--:-- 80590
> Archive:  /tmp/v2ray/v2ray.zip
>   inflating: /tmp/v2ray/v2ray-v1.11.2-linux-64/systemd/v2ray.service  
>   inflating: /tmp/v2ray/v2ray-v1.11.2-linux-64/systemv/v2ray  
>   inflating: /tmp/v2ray/v2ray-v1.11.2-linux-64/v2ray  
>   inflating: /tmp/v2ray/v2ray-v1.11.2-linux-64/vpoint_socks_vmess.json  
>   inflating: /tmp/v2ray/v2ray-v1.11.2-linux-64/vpoint_vmess_freedom.json  

可以看到脚本自动识别为AMD64型CPU而不是ARM64.导致安装完成后无法成功启动
查看脚本，发现第67行：

> ARCH=$(uname -m)

紧接着67行为条件判断语句：

> VDIS="64"
> 
> if [[ "$ARCH" == "i686" ]] || [[ "$ARCH" == "i386" ]]; then
>   VDIS="32"
> elif [[ "$ARCH" == *"armv7"* ]]; then
>   VDIS="arm"
> elif [[ "$ARCH" == *"armv8"* ]]; then
>   VDIS="arm64"
> fi

然而我手动在bash中运行uname -m，输出为：

> pi@raspberrypi:~ $ uname -m
> armv6l

呃，这是个脚本编写失误还是当时就没想考虑Raspberry Pi B+以下所有型号的兼容性呢（手动滑稽）？还是说指令集太老了不再兼容了呢？

**Comment by zxcso** [comment]
Raspberry Pi 2 Model B可以正常识别，只有Pi 3才是arm64架构的，其他的Pi都是32位架构，所以只要把安装脚本里的armv7改为uname的输出结果应该就可了

**Comment by wtlusvm** [comment]
@zxcso 因为Raspberry Pi 2 Model B的CPU是ARMv7系列，条件判断语句里有，当然可以正常识别。问题是Raspberry Pi B的CPU是ARM11系列，直接改可能装不上。

**Comment by v2ray** [comment]
理论上 armv6 是支持的，不过我手头没有足够的测试机器（只有 arm64 测试过，32 位 arm 没机器）。你可以试试改一下安装脚本，如果安装完 V2Ray 可以正常运行的话，欢迎提交一个 PR。
