### ISSUE TITLE
使用kcp协议，安全防护软件symantec endpoint protection提示: 端口扫描攻击，并且封掉IP。

### ISSUE THREAD

**Issue by MrBenWang** [v2ray/v2ray-core#1271]
1. 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v3.41

2. 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
- vmess，shadowsocks。 都可以正常连接。使用 tcp，ws，http 协议都不会出现被拦截[已禁止]的情况。
- 使用 kcp 协议后，并且在有丢包的情况下，会触发安全防护，封掉IP。推测可能是重发导致的。
- 使用 kcp 协议后，一段时间内可以正常的连接。
- 不知道是kcp本身的原因，还是因为改进kcp导致的。
 
![20号](https://user-images.githubusercontent.com/9692054/45794422-377a2400-bcc9-11e8-9784-ce38bc09e881.jpg)
![githubbug](https://user-images.githubusercontent.com/9692054/45744846-0e5a8480-bc32-11e8-8d42-c67d19ea1d29.jpg)

**Comment by VictoriaRaymond** [comment]
Symantec的问题
