### ISSUE TITLE
能加入屏蔽广告模块吗??

### ISSUE THREAD

**Issue by agzfan** [v2ray/v2ray-core#1272]
用这里的数据,Unified hosts = (adware + malware)就够用了
https://github.com/StevenBlack/hosts

集成类似geosite和geoip功能

服务器上用hosts延迟太慢,如果开了http还会直接打开服务器网站
直接集成到v2ray会快很多

**Comment by VictoriaRaymond** [comment]
可以使用路由功能实现此效果。

**Comment by condy0919** [comment]
使用路由功能，把 host 放在 config 里太庞大了，会使得配置没法看

**Comment by beckball** [comment]
> 使用路由功能，把 host 放在 config 里太庞大了，会使得配置没法看

服务端路由功能可以做到吗？我尝试用客户端的写法添加配置 但是似乎没有效果
