### ISSUE TITLE
最近几个版本出现一个问题，能否解决

### ISSUE THREAD

**Issue by lxitdn** [v2ray/v2ray-core#1278]
最近几个版本总是出现一个问题，软件自动运行，更换节点以后无论如何都不能代理，打不开谷歌以及所有外网，唯一的解决办法就是吧软件退出，重新打开软件，重启服务也不行，我的电脑是win10系统

**Comment by VictoriaRaymond** [comment]
> 除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
