### ISSUE TITLE
关于AES-256-CFB解密问题

### ISSUE THREAD

**Issue by whisper-bye** [v2ray/v2ray-core#128]
@v2ray 
我在开发一个v2ray的客户端，基本已经完成，但是在解密AES-256-CFB流量的时候时常会出现乱码的问题，有的部分正确有的部分错误，在服务器返回大量数据的时候会分多次将数据返回，比如使用http协议，如何知道应该解密多少长度呢？如果解密一个不完整的块就会出现乱码的情况。

请赐教！

**Comment by v2ray** [comment]
对于 HTTP 代理，现在暂不支持连接复用，没办法用一个 TCP 连接发送多个 HTTP 请求。也就是说，要解密服务器的响应，从头解到尾就可以了，没有分段的。

**Comment by whisper-bye** [comment]
谢谢，我已经解决了
