### ISSUE TITLE
建议增加多服务器切换功能

### ISSUE THREAD

**Issue by StrollStars** [v2ray/v2ray-core#1280]
如题，如今虽然服务器列表可能有很多服务器，但是只能一个个手动切换。
建议增加类似SS的负载均衡功能，每次随机挑选一个服务器，并且最好与最近一次所用的不同。
或者可以像Proxifier那样可以服务器轮换。

**Comment by ilouiss** [comment]
白话文中写到了怎么用负载均衡[https://toutyrater.github.io/app/balance.html](url)，你可以看看

**Comment by StrollStars** [comment]
@ilouiss 感谢分享，感觉上手不太容易，而且如果是同一时间只有一个连接的话，似乎一直都只用第一个。
希望开发者还是能够原生支持负载均衡。

**Comment by nobody3u** [comment]
但是如果一个链接也定时切换的话，就会造成一些需要一直链接的任务断线了。

**Comment by beyondkmp** [comment]
目前websockets支持不了多条线路

**Comment by StrollStars** [comment]
@nobody3u 当然不能切断连接中的任务，我是这么想的，如果当前没有代理连接，那么从所有的服务器中挑一个，并且和最后一次使用的服务器不同；如果当前已有代理连接，从剩下的服务器中随机挑选。

**Comment by fax001** [comment]
负载均衡策略据说在4.0版本中会有

**Comment by StrollStars** [comment]
@fax001 感谢告知^_^

**Comment by VictoriaRaymond** [comment]
https://github.com/v2ray/Planning/issues/64
