### ISSUE TITLE
没有路由器系统openwrt/lede客户端吗

### ISSUE THREAD

**Issue by channingbox** [v2ray/v2ray-core#1281]
如题

**Comment by wongsyrone** [comment]
得益于golang的静态编译，搞了个简易版：https://github.com/wongsyrone/openwrt-v2ray

**Comment by VictoriaRaymond** [comment]
> 如果你遇到的问题不是 V2Ray 的 bug，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

**Comment by qiang-yu** [comment]
我做了一个 openwrt 版本的，带设置界面  https://github.com/qiang-yu/V2rayVPN-openwrt
