### ISSUE TITLE
Api 调用的bug：无流量时，StatsServiceClient.GetStats() 不正确返回错误。应该是返回Stat.Value 值为0

### ISSUE THREAD

**Issue by JMVoid** [v2ray/v2ray-core#1284]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V2Ray v3.43 (die Commanderin) 20180921
A unified platform for anti-censorship

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
Chomre 通过 vmess上网

3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
在调用StatsServiceClient.GetStats()时.如果获取某email 的流量时，如果该email 地址没有产生过流量。会产生如下错误
 rpc error: code = Unknown desc = App|Stats|Command

4)  你期待看到的正确表现是怎样的？
正确的表现应该是返回的流量值应该是0.而不是一个错误

**Comment by 5high** [comment]
人家返回的是no found，如果返回为0，我猜对性能来讲可能会有影响。

**Comment by JMVoid** [comment]
如果有不少email在v2ray实例中， 会导致很多报错。而且没有这个email  也是返回同一错误。用户(email)没有使用是这种正常的状态，不应该由于没有数据流量，返回就是一个报错的

**Comment by VictoriaRaymond** [comment]
就是这样设计的，在没有流量的时候，Stats并不知道这个用户存不存在
