### ISSUE TITLE
关于子域名匹配的一些疑问及路由优先级问题？

### ISSUE THREAD

**Issue by ZeronoFreya** [v2ray/v2ray-core#1287]
* 子域名
```
domain:github.com
```
不能够匹配 `github.com.cn` (假设有这个域名)，对吗？

* 路由
```
[
    {
        "domain": [
            "www.google.com"
        ], 
        "type": "field", 
        "outboundTag": "direct"
    }, 
    {
        "domain": [
            "www.google.com"
        ], 
        "type": "field", 
        "outboundTag": "proxy"
    }
]
```
会优先执行哪一个呢（我不太清楚如何查看某一个域名是代理还是直连）

* 关于type的问题
看到《白话文教程》中有
```
{
    "type": "chinaip", 
    "outboundTag": "direct", 
    "ip": [
        "geoip:cn"
    ]
}
```
不是说type只有field的吗？笔误还是文档未更新？

谢谢！

**Comment by ToutyRater** [comment]
1.  github.com.cn 不属于 github.com 的子域名，故不能匹配。如果不理解，请 google 学习一下子域名的概念
2. 路由优先级自上而下递减，优先匹配前面的
3. chinaip 是曾经支持的，现在由 geoip 替代。白话文教程已经更新了一段时间，你怕不是看的是缓存的教程吧

**Comment by nobody3u** [comment]
可以开2个v2ray-core然后，浏览器-> v2ray1 -> v2ray2  
routing等要测试的配置写在v2ray1中  
观察v2ray2的log就可以知道流量是从v2ray1出去还是转到v2ray2

**Comment by ZeronoFreya** [comment]
> 
> 
>     1. github.com.cn 不属于 github.com 的子域名，故不能匹配。如果不理解，请 google 学习一下子域名的概念
> 
>     2. 路由优先级自上而下递减，优先匹配前面的
> 
>     3. chinaip 是曾经支持的，现在由 geoip 替代。白话文教程已经更新了一段时间，你怕不是看的是缓存的教程吧

感谢回复，关于第二点，即使是属于不同的连接方式也是按顺序的吗？比如上述的google，先写在了 **直连** 的路由里，后又写在了 **代理** 的路由中，那么按顺序来，google就是直连了？
这只是一个疑问，或许现实中没太大用处
