### ISSUE TITLE
一个进程可以同时开socks与http吗？

### ISSUE THREAD

**Issue by benhon2008** [v2ray/v2ray-core#129]
RT，inbound 与 inboundDetour。

**Comment by v2ray** [comment]
可以的

**Comment by benhon2008** [comment]
@v2ray (http)inbound 与 (socks)inboundDetour 还是(socks)inbound 与 (http)inboundDetour？

**Comment by v2ray** [comment]
没有区别。inbound 有且只能有一个，inboundDetour 可以有多个，怎么写方便就怎么写。

**Comment by benhon2008** [comment]
@v2ray http 与 socks 的端口怎么写？这么调试都不通过……求助。

**Comment by benhon2008** [comment]
{
    "port": 80,
    "log": {
        "access": ""
    },
    "inbound": {
        "protocol": "socks",
        "settings": {
            "auth": "noauth",
            "udp": false,
            "ip": "0.0.0.0",
            "port": 1080
        }
    },
    "inboundDetour": {
        "protocol": "http",
        "settings": {}
    },

... ... ... ...

**Comment by v2ray** [comment]
Socks 的 settings 中没有 port 选项，猜测你把 http 的 port 搞混了。另外部份操作系统不允许监听1000以下的端口。

大概应该是这样：

```javascript
{
    "port": 1080,
    "log": {
        "access": ""
    },
    "inbound": {
        "protocol": "socks",
        "settings": {
            "auth": "noauth",
            "udp": false,
            "ip": "0.0.0.0"
        }
    },
    "inboundDetour": {
        "protocol": "http",
        "port": 8080,
        "settings": {}
    },
```

**Comment by benhon2008** [comment]
还是不行……
===================================
D:\v2ray>v2ray.exe
V2Ray v1.11.2 (New Order) 20160419
An unified platform for anti-censorship.
2016/05/01 23:30:03 [Error]Failed to load server config: json: cannot unmarshal
object into Go value of type []*point.InboundDetourConfig
2016/05/01 23:30:03 [Error]Failed to read config file (D:\v2ray\config.json): D:
\v2ray\config.jsonjson: cannot unmarshal object into Go value of type []*point.I
nboundDetourConfig
===================================
{
    "port": 8888,
    "log": {
        "access": ""
    },
    "inbound": {
        "protocol": "socks",
        "settings": {
            "auth": "noauth",
            "udp": false,
            "ip": "0.0.0.0"
        }
    },
    "inboundDetour": {
        "protocol": "http",
        "port": 8080,
        "settings": {}
    },
    "outbound": {
        "protocol": "vmess",
        "settings": {
            "vnext": [
                {
                    "address": "104.238.154.21",
                    "port": 443,
                    "users": [
                        {
                            "id": "174213a6-6802-4bdf-b1bc-e44cd015af53",
                            "alterId": 100
                        }
                    ]
                }
            ]
        }
    },
    "outboundDetour": [
        {
            "protocol": "freedom",
            "settings": {},
            "tag": "direct"
        }
    ],
    "routing": {
        "strategy": "rules",
        "settings": {
            "rules": [
                {
                    "type": "field",
                    "ip": [
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "203.0.113.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10"
                    ],
                    "outboundTag": "direct"
                }
            ]
        }
    }
}

**Comment by v2ray** [comment]
```javascript
{
    "port": 3786,
    "log": {
        "access": ""
    },
    "inbound": {
        "protocol": "socks",
        "settings": {
            "auth": "noauth",
            "udp": false,
            "ip": "0.0.0.0"
        }
    },
    "inboundDetour": [{
        "protocol": "http",
        "port": 8080,
        "settings": {}
    }],
    "outbound": {
        "protocol": "vmess",
        "settings": {
            "vnext": [
                {
                    "address": "1.2.3.4",
                    "port": 443,
                    "users": [
                        {
                            "id": "xxxxxxx-xxxx-xxxx-xxxxxxxx",
                            "alterId": 100
                        }
                    ]
                }
            ]
        }
    },
    "outboundDetour": [
        {
            "protocol": "freedom",
            "settings": {},
            "tag": "direct"
        }
    ],
    "routing": {
        "strategy": "rules",
        "settings": {
            "rules": [
                {
                    "type": "field",
                    "ip": [
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "203.0.113.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10"
                    ],
                    "outboundTag": "direct"
                }
            ]
        }
    }
}
```

**Comment by benhon2008** [comment]
@v2ray 明白了。感谢！
