### ISSUE TITLE
google验证码显示不了

### ISSUE THREAD

**Issue by moozc** [v2ray/v2ray-core#1295]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v3.45
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
google搜索
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
验证码显示不了
![11](https://user-images.githubusercontent.com/8488695/46369510-ce75b180-c6b5-11e8-9910-93c34dbbda51.png)
4) 你期待看到的正确表现是怎样的？
正常显示
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    {
	"inbound": {
		"protocol": "vmess",
		"port": 29377,
		"streamSettings": {
			"network": "h2",
			"httpSettings": {
				"host": [
					"a.com"
				],
				"path": "/v2"
			},
			"tlsSettings": {
				"certificates": [
					{
						"keyFile": "a.com.key",
						"certificateFile": "a.com.crt"
					}
				]
			},
			"security": "tls"
		},
		"settings": {
			"udp": false,
			"clients": [
				{
					"alterId": 64,
					"id": "9cafbf8b-763e-4e2e-8998-ef6a71a359fe"
				}
			]
		}
	},
	"outbound": {
	"protocol": "freedom",
	"settings": {}
	}
}

```

客户端配置:

```javascript
    {
	"log": {
		"loglevel": "info",
		"access": "",
		"error": ""
	},
	"dns": {
		"servers": [
			"8.8.8.8",
			"1.1.1.1",
			"119.29.29.29",
			"114.114.114.114"
		]
	},
	"inbound": {
		"port": 1080,
		"listen": "127.0.0.1",
		"protocol": "http",
		"settings": {
			"timeout": 360
		}
	},
	"inboundDetour": [
		{
			"port": 1088,
			"listen": "127.0.0.1",
			"protocol": "socks",
			"settings": {
				"auth": "noauth",
				"timeout": 360,
				"udp": true
			}
		}
	],
	"outbound": {
		"tag": "agentout",
		"protocol": "vmess",
		"streamSettings": {
			"network": "h2",
			"httpSettings": {
				"host": [
					"a.com"
				],
				"path": "/v2"
			},
			"tlsSettings": {},
			"security": "tls"
		},
		"settings": {
			"vnext": [
				{
					"users": [
						{
							"alterId": 64,
							"id": "9cafbf8b-763e-4e2e-8998-ef6a71a359fe"
						}
					],
					"port": 443,
					"address": "a.com"
				}
			]
		}
	},
	"outboundDetour": [
		{
			"tag": "direct",
			"protocol": "freedom",
			"settings": {
				"response": null
			}
		},
		{
			"tag": "blockout",
			"protocol": "blackhole",
			"settings": {
				"response": {
					"type": "http"
				}
			}
		}
	],
	"routing": {
		"strategy": "rules",
		"settings": {
			"domainStrategy": "IPIfNonMatch",
			"rules": [
				{
					"type": "field",
					"outboundTag": "direct",
					"ip": [
						"geoip:private"
					]
				},
				{
					"type": "field",
					"outboundTag": "direct",
					"domain": [
						"geosite:cn"
					]
				},
				{
					"type": "field",
					"outboundTag": "direct",
					"ip": [
						"geoip:cn"
					]
				}
			]
		}
	}
}

```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    2018/10/03 02:36:50 [Warning] Core: V2Ray v3.45 started
2018/10/03 02:36:52 [Info] [4114068218] Proxy|HTTP: request to Method [CONNECT] Host [clients1.google.com:443] with URL [//clients1.google.com:443]
2018/10/03 02:36:52 [Info] App|Router: looking for IP for domain: clients1.google.com
2018/10/03 02:36:52 [Info] Transport|Internet|UDP: establishing new connection for udp:8.8.8.8:53
2018/10/03 02:36:52 [Info] App|Dispatcher: default route for udp:8.8.8.8:53
2018/10/03 02:36:52 [Info] [2457429987] Proxy|HTTP: request to Method [CONNECT] Host [clients1.google.com:443] with URL [//clients1.google.com:443]
2018/10/03 02:36:52 [Info] App|Router: looking for IP for domain: clients1.google.com
2018/10/03 02:36:53 [Info] Proxy|VMess|Outbound: tunneling request to udp:8.8.8.8:53 via tcp:a.com:443
2018/10/03 02:36:54 [Info] [2557829959] Proxy|HTTP: request to Method [CONNECT] Host [www.google.com:443] with URL [//www.google.com:443]
2018/10/03 02:36:54 [Info] App|Router: looking for IP for domain: www.google.com
2018/10/03 02:36:54 [Info] [1083097916] Proxy|HTTP: request to Method [CONNECT] Host [clients1.google.com:443] with URL [//clients1.google.com:443]
2018/10/03 02:36:54 [Info] App|Router: looking for IP for domain: clients1.google.com
2018/10/03 02:36:54 [Info] [2557829959] App|Dispatcher: default route for tcp:www.google.com:443
2018/10/03 02:36:54 [Info] [1083097916] App|Dispatcher: default route for tcp:clients1.google.com:443
2018/10/03 02:36:54 [Info] [4114068218] App|Dispatcher: default route for tcp:clients1.google.com:443
2018/10/03 02:36:54 [Info] [2457429987] App|Dispatcher: default route for tcp:clients1.google.com:443
2018/10/03 02:36:55 [Info] [1083097916] Proxy|VMess|Outbound: tunneling request to tcp:clients1.google.com:443 via tcp:a.com:443
2018/10/03 02:36:55 [Info] [2457429987] Proxy|VMess|Outbound: tunneling request to tcp:clients1.google.com:443 via tcp:a.com:443
2018/10/03 02:36:55 [Info] [2557829959] Proxy|VMess|Outbound: tunneling request to tcp:www.google.com:443 via tcp:a.com:443
2018/10/03 02:36:55 [Info] [4114068218] Proxy|VMess|Outbound: tunneling request to tcp:clients1.google.com:443 via tcp:a.com:443
2018/10/03 02:36:58 [Info] [4045343246] Proxy|HTTP: request to Method [CONNECT] Host [adservice.google.com:443] with URL [//adservice.google.com:443]
2018/10/03 02:36:58 [Info] App|Router: looking for IP for domain: adservice.google.com
2018/10/03 02:37:00 [Info] App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > context canceled
2018/10/03 02:37:00 [Info] Transport|Internet|UDP: failed to handle UDP input > io: read/write on closed pipe
2018/10/03 02:37:02 [Info] Transport|Internet|UDP: establishing new connection for udp:1.1.1.1:53
2018/10/03 02:37:02 [Info] App|Dispatcher: default route for udp:1.1.1.1:53
2018/10/03 02:37:03 [Info] Proxy|VMess|Outbound: tunneling request to udp:1.1.1.1:53 via tcp:a.com:443
2018/10/03 02:37:03 [Info] [4045343246] App|Dispatcher: default route for tcp:adservice.google.com:443
2018/10/03 02:37:04 [Info] [4045343246] Proxy|VMess|Outbound: tunneling request to tcp:adservice.google.com:443 via tcp:a.com:443
2018/10/03 02:37:10 [Info] App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > context canceled
2018/10/03 02:37:10 [Info] Transport|Internet|UDP: failed to handle UDP input > io: read/write on closed pipe
2018/10/03 02:40:59 [Info] [1083097916] App|Proxyman|Inbound: connection ends > Proxy|HTTP: connection ends > context canceled
2018/10/03 02:40:59 [Info] [1083097916] App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > context canceled
2018/10/03 02:41:19 [Info] [1147172607] Proxy|HTTP: request to Method [CONNECT] Host [github-production-user-asset-6210df.s3.amazonaws.com:443] with URL [//github-production-user-asset-6210df.s3.amazonaws.com:443]
2018/10/03 02:41:19 [Info] App|Router: looking for IP for domain: github-production-user-asset-6210df.s3.amazonaws.com
2018/10/03 02:41:19 [Info] Transport|Internet|UDP: establishing new connection for udp:8.8.8.8:53
2018/10/03 02:41:19 [Info] App|Dispatcher: default route for udp:8.8.8.8:53
2018/10/03 02:41:19 [Info] Proxy|VMess|Outbound: tunneling request to udp:8.8.8.8:53 via tcp:a.com:443
2018/10/03 02:41:20 [Info] [1147172607] App|Dispatcher: default route for tcp:github-production-user-asset-6210df.s3.amazonaws.com:443
2018/10/03 02:41:20 [Info] [1147172607] Proxy|VMess|Outbound: tunneling request to tcp:github-production-user-asset-6210df.s3.amazonaws.com:443 via tcp:a.com:443
2018/10/03 02:41:33 [Info] App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > context canceled
2018/10/03 02:41:33 [Info] Transport|Internet|UDP: failed to handle UDP input > io: read/write on closed pipe
2018/10/03 02:41:55 [Info] [1147172607] App|Proxyman|Inbound: connection ends > Proxy|HTTP: connection ends > context canceled
2018/10/03 02:41:55 [Info] [1147172607] App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > context canceled

```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
2018/10/03 02:36:52 127.0.0.1:49185 accepted //clients1.google.com:443  
2018/10/03 02:36:52 127.0.0.1:49189 accepted //clients1.google.com:443  
2018/10/03 02:36:54 127.0.0.1:49191 accepted //www.google.com:443  
2018/10/03 02:36:54 127.0.0.1:49195 accepted //clients1.google.com:443  
2018/10/03 02:36:58 127.0.0.1:49204 accepted //adservice.google.com:443  
2018/10/03 02:41:19 127.0.0.1:49634 accepted //github-production-user-asset-6210df.s3.amazonaws.com:443  

```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by Chandler-Lu** [comment]
默认dns试试？

**Comment by ZhouZiY** [comment]
我也遇到了一样的问题  
`2019/01/14 12:59:10 [Debug] v2ray.com/core/app/log: Logger started
2019/01/14 12:59:10 [Warning] v2ray.com/core: V2Ray 4.10.0 started
2019/01/14 12:59:10 [Info] [1857637865] v2ray.com/core/proxy/socks: TCP Connect request to tcp:108.177.97.188:5228
2019/01/14 12:59:10 [Info] [1857637865] v2ray.com/core/app/dispatcher: default route for tcp:108.177.97.188:5228
2019/01/14 12:59:10 [Info] [1857637865] v2ray.com/core/transport/internet/websocket: creating connection to tcp:mywebsite.com:443
2019/01/14 12:59:10 [Info] [4117253549] v2ray.com/core/proxy/socks: TCP Connect request to tcp:216.58.221.106:443
2019/01/14 12:59:10 [Info] [4117253549] v2ray.com/core/app/dispatcher: default route for tcp:216.58.221.106:443
2019/01/14 12:59:10 [Info] [4117253549] v2ray.com/core/transport/internet/websocket: creating connection to tcp:mywebsite.com:443
2019/01/14 12:59:10 [Info] [1721052256] v2ray.com/core/proxy/socks: TCP Connect request to tcp:172.217.161.173:443
2019/01/14 12:59:10 [Info] [1721052256] v2ray.com/core/app/dispatcher: default route for tcp:172.217.161.173:443
2019/01/14 12:59:10 [Info] [1721052256] v2ray.com/core/transport/internet/websocket: creating connection to tcp:mywebsite.com:443
2019/01/14 12:59:10 [Info] [199398460] v2ray.com/core/proxy/socks: TCP Connect request to tcp:172.217.24.206:443
2019/01/14 12:59:10 [Info] [199398460] v2ray.com/core/app/dispatcher: default route for tcp:172.217.24.206:443
2019/01/14 12:59:10 [Info] [199398460] v2ray.com/core/transport/internet/websocket: creating connection to tcp:mywebsite.com:443
2019/01/14 12:59:10 [Info] [3312158138] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: failed to read request > v2ray.com/core/proxy/socks: insufficient header > EOF
2019/01/14 12:59:10 [Info] [1310932997] v2ray.com/core/proxy/socks: TCP Connect request to tcp:216.58.221.106:443
2019/01/14 12:59:10 [Info] [1310932997] v2ray.com/core/app/dispatcher: default route for tcp:216.58.221.106:443
2019/01/14 12:59:10 [Info] [1310932997] v2ray.com/core/transport/internet/websocket: creating connection to tcp:mywebsite.com:443
2019/01/14 12:59:10 [Info] [321478725] v2ray.com/core/proxy/socks: TCP Connect request to tcp:216.58.221.106:443
2019/01/14 12:59:10 [Info] [321478725] v2ray.com/core/app/dispatcher: default route for tcp:216.58.221.106:443
2019/01/14 12:59:10 [Info] [321478725] v2ray.com/core/transport/internet/websocket: creating connection to tcp:mywebsite.com:443
2019/01/14 12:59:10 [Info] [4117253549] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:216.58.221.106:443 via tcp:mywebsite.com:443
2019/01/14 12:59:10 [Info] [1721052256] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:172.217.161.173:443 via tcp:mywebsite.com:443
2019/01/14 12:59:10 [Info] [1857637865] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:108.177.97.188:5228 via tcp:mywebsite.com:443
2019/01/14 12:59:10 [Info] [199398460] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:172.217.24.206:443 via tcp:mywebsite.com:443
2019/01/14 12:59:10 [Info] [508382990] v2ray.com/core/proxy/socks: TCP Connect request to tcp:151.101.0.133:443
2019/01/14 12:59:10 [Info] [508382990] v2ray.com/core/app/dispatcher: default route for tcp:151.101.0.133:443
2019/01/14 12:59:10 [Info] [508382990] v2ray.com/core/transport/internet/websocket: creating connection to tcp:mywebsite.com:443
2019/01/14 12:59:10 [Info] [1310932997] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:216.58.221.106:443 via tcp:mywebsite.com:443
2019/01/14 12:59:10 [Info] [321478725] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:216.58.221.106:443 via tcp:mywebsite.com:443
2019/01/14 12:59:10 [Info] [508382990] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:151.101.0.133:443 via tcp:mywebsite.com:443
2019/01/14 12:59:10 [Info] [2650317994] v2ray.com/core/proxy/socks: TCP Connect request to tcp:172.217.24.46:443
2019/01/14 12:59:10 [Info] [2650317994] v2ray.com/core/app/dispatcher: default route for tcp:172.217.24.46:443
2019/01/14 12:59:10 [Info] [2650317994] v2ray.com/core/transport/internet/websocket: creating connection to tcp:mywebsite.com:443
2019/01/14 12:59:11 [Info] [179075319] v2ray.com/core/proxy/socks: TCP Connect request to tcp:172.217.24.46:443
2019/01/14 12:59:11 [Info] [179075319] v2ray.com/core/app/dispatcher: default route for tcp:172.217.24.46:443
2019/01/14 12:59:11 [Info] [179075319] v2ray.com/core/transport/internet/websocket: creating connection to tcp:mywebsite.com:443
2019/01/14 12:59:11 [Info] [2650317994] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:172.217.24.46:443 via tcp:mywebsite.com:443
2019/01/14 12:59:11 [Info] [179075319] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:172.217.24.46:443 via tcp:mywebsite.com:443
2019/01/14 12:59:11 [Info] [3036019081] v2ray.com/core/proxy/socks: TCP Connect request to tcp:64.233.189.138:443
2019/01/14 12:59:11 [Info] [3036019081] v2ray.com/core/app/dispatcher: default route for tcp:64.233.189.138:443
2019/01/14 12:59:11 [Info] [3036019081] v2ray.com/core/transport/internet/websocket: creating connection to tcp:mywebsite.com:443
2019/01/14 12:59:11 [Info] [3037788189] v2ray.com/core/proxy/socks: TCP Connect request to tcp:64.233.189.138:443
2019/01/14 12:59:11 [Info] [3037788189] v2ray.com/core/app/dispatcher: default route for tcp:64.233.189.138:443
2019/01/14 12:59:11 [Info] [3037788189] v2ray.com/core/transport/internet/websocket: creating connection to tcp:mywebsite.com:443
2019/01/14 12:59:12 [Info] [3036019081] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:64.233.189.138:443 via tcp:mywebsite.com:443
2019/01/14 12:59:12 [Info] [3037788189] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:64.233.189.138:443 via tcp:mywebsite.com:443
2019/01/14 12:59:14 [Info] [1962456490] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: failed to read request > v2ray.com/core/proxy/socks: insufficient header > read tcp 127.0.0.1:1080->127.0.0.1:60810: i/o timeout
2019/01/14 12:59:14 [Info] [839772951] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: failed to read request > v2ray.com/core/proxy/socks: insufficient header > read tcp 127.0.0.1:1080->127.0.0.1:60809: i/o timeout
2019/01/14 12:59:14 [Info] [1711941061] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: failed to read request > v2ray.com/core/proxy/socks: insufficient header > read tcp 127.0.0.1:1080->127.0.0.1:60811: i/o timeout
2019/01/14 12:59:14 [Info] [519673656] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: failed to read request > v2ray.com/core/proxy/socks: insufficient header > read tcp 127.0.0.1:1080->127.0.0.1:60812: i/o timeout
2019/01/14 12:59:14 [Info] [547398255] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: failed to read request > v2ray.com/core/proxy/socks: insufficient header > read tcp 127.0.0.1:1080->127.0.0.1:60813: i/o timeout
2019/01/14 12:59:14 [Info] v2ray.com/core/transport/internet/udp: failed to read UDP msg > read udp 127.0.0.1:1080: use of closed network connection
2019/01/14 12:59:29 [Debug] v2ray.com/core/app/log: Logger started
2019/01/14 12:59:29 [Warning] v2ray.com/core: V2Ray 4.10.0 started
2019/01/14 12:59:29 [Info] [3934453786] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.google.com:443
2019/01/14 12:59:29 [Info] [3934453786] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:443
2019/01/14 12:59:29 [Info] [3934453786] v2ray.com/core/transport/internet/websocket: creating connection to tcp:mywebsite.com:443
2019/01/14 12:59:30 [Info] [1444232284] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.google.com:443
2019/01/14 12:59:30 [Info] [1444232284] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:443
2019/01/14 12:59:30 [Info] [1444232284] v2ray.com/core/transport/internet/websocket: creating connection to tcp:mywebsite.com:443
2019/01/14 12:59:30 [Info] [3934453786] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via tcp:mywebsite.com:443
2019/01/14 12:59:30 [Info] [1444232284] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via tcp:mywebsite.com:443
2019/01/14 12:59:31 [Info] [760782379] v2ray.com/core/proxy/socks: TCP Connect request to tcp:ogs.google.com:443
2019/01/14 12:59:31 [Info] [760782379] v2ray.com/core/app/dispatcher: default route for tcp:ogs.google.com:443
2019/01/14 12:59:31 [Info] [760782379] v2ray.com/core/transport/internet/websocket: creating connection to tcp:mywebsite.com:443
2019/01/14 12:59:31 [Info] [760782379] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:ogs.google.com:443 via tcp:mywebsite.com:443
2019/01/14 12:59:33 [Info] [847884137] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.gstatic.com:443
2019/01/14 12:59:33 [Info] [847884137] v2ray.com/core/app/dispatcher: default route for tcp:www.gstatic.com:443
2019/01/14 12:59:33 [Info] [847884137] v2ray.com/core/transport/internet/websocket: creating connection to tcp:mywebsite.com:443
2019/01/14 12:59:33 [Info] [847884137] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.gstatic.com:443 via tcp:mywebsite.com:443
2019/01/14 12:59:34 [Info] [2146821938] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: failed to read request > v2ray.com/core/proxy/socks: insufficient header > read tcp 127.0.0.1:1080->127.0.0.1:60842: i/o timeout
2019/01/14 12:59:34 [Info] [3722359777] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: failed to read request > v2ray.com/core/proxy/socks: insufficient header > read tcp 127.0.0.1:1080->127.0.0.1:60843: i/o timeout
2019/01/14 12:59:37 [Info] v2ray.com/core/transport/internet/udp: failed to read UDP msg > read udp 127.0.0.1:1080: use of closed network connection
2019/01/14 13:05:25 [Debug] v2ray.com/core/app/log: Logger started
2019/01/14 13:05:25 [Warning] v2ray.com/core: V2Ray 4.10.0 started
2019/01/14 13:05:26 [Info] [289572687] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.google.com:443
2019/01/14 13:05:26 [Info] [289572687] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:443
2019/01/14 13:05:26 [Info] [289572687] v2ray.com/core/transport/internet/websocket: creating connection to tcp:mywebsite.com:443
2019/01/14 13:05:26 [Info] [2012266353] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.google.com:443
2019/01/14 13:05:26 [Info] [2012266353] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:443
2019/01/14 13:05:26 [Info] [2012266353] v2ray.com/core/transport/internet/websocket: creating connection to tcp:mywebsite.com:443
2019/01/14 13:05:26 [Info] [2012266353] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via tcp:mywebsite.com:443
2019/01/14 13:05:27 [Info] [289572687] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via tcp:mywebsite.com:443
2019/01/14 13:05:28 [Info] [1900073886] v2ray.com/core/proxy/socks: TCP Connect request to tcp:mtalk.google.com:443
2019/01/14 13:05:28 [Info] [1900073886] v2ray.com/core/app/dispatcher: default route for tcp:mtalk.google.com:443
2019/01/14 13:05:28 [Info] [1900073886] v2ray.com/core/transport/internet/websocket: creating connection to tcp:mywebsite.com:443
2019/01/14 13:05:28 [Info] [1900073886] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:mtalk.google.com:443 via tcp:mywebsite.com:443
2019/01/14 13:05:29 [Info] [1213397246] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.gstatic.com:443
2019/01/14 13:05:29 [Info] [1213397246] v2ray.com/core/app/dispatcher: default route for tcp:www.gstatic.com:443
2019/01/14 13:05:29 [Info] [1213397246] v2ray.com/core/transport/internet/websocket: creating connection to tcp:mywebsite.com:443
2019/01/14 13:05:29 [Info] [1213397246] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.gstatic.com:443 via tcp:mywebsite.com:443
`

**Comment by ZhouZiY** [comment]
`2019/01/14 12:59:10 tcp:127.0.0.1:60803 accepted tcp:108.177.97.188:5228 
2019/01/14 12:59:10 tcp:127.0.0.1:60804 accepted tcp:216.58.221.106:443 
2019/01/14 12:59:10 tcp:127.0.0.1:60805 accepted tcp:172.217.161.173:443 
2019/01/14 12:59:10 tcp:127.0.0.1:60807 accepted tcp:172.217.24.206:443 
2019/01/14 12:59:10 tcp:127.0.0.1:60808 rejected  v2ray.com/core/proxy/socks: insufficient header > EOF
2019/01/14 12:59:10 tcp:127.0.0.1:60814 accepted tcp:216.58.221.106:443 
2019/01/14 12:59:10 tcp:127.0.0.1:60815 accepted tcp:216.58.221.106:443 
2019/01/14 12:59:10 tcp:127.0.0.1:60816 accepted tcp:151.101.0.133:443 
2019/01/14 12:59:10 tcp:127.0.0.1:60825 accepted tcp:172.217.24.46:443 
2019/01/14 12:59:11 tcp:127.0.0.1:60827 accepted tcp:172.217.24.46:443 
2019/01/14 12:59:11 tcp:127.0.0.1:60829 accepted tcp:64.233.189.138:443 
2019/01/14 12:59:11 tcp:127.0.0.1:60830 accepted tcp:64.233.189.138:443 
2019/01/14 12:59:14 tcp:127.0.0.1:60809 rejected  v2ray.com/core/proxy/socks: insufficient header > read tcp 127.0.0.1:1080->127.0.0.1:60809: i/o timeout
2019/01/14 12:59:14 tcp:127.0.0.1:60810 rejected  v2ray.com/core/proxy/socks: insufficient header > read tcp 127.0.0.1:1080->127.0.0.1:60810: i/o timeout
2019/01/14 12:59:14 tcp:127.0.0.1:60811 rejected  v2ray.com/core/proxy/socks: insufficient header > read tcp 127.0.0.1:1080->127.0.0.1:60811: i/o timeout
2019/01/14 12:59:14 tcp:127.0.0.1:60812 rejected  v2ray.com/core/proxy/socks: insufficient header > read tcp 127.0.0.1:1080->127.0.0.1:60812: i/o timeout
2019/01/14 12:59:14 tcp:127.0.0.1:60813 rejected  v2ray.com/core/proxy/socks: insufficient header > read tcp 127.0.0.1:1080->127.0.0.1:60813: i/o timeout
2019/01/14 12:59:29 tcp:127.0.0.1:60844 accepted tcp:www.google.com:443 
2019/01/14 12:59:30 tcp:127.0.0.1:60845 accepted tcp:www.google.com:443 
2019/01/14 12:59:31 tcp:127.0.0.1:60848 accepted tcp:ogs.google.com:443 
2019/01/14 12:59:33 tcp:127.0.0.1:60853 accepted tcp:www.gstatic.com:443 
2019/01/14 12:59:34 tcp:127.0.0.1:60842 rejected  v2ray.com/core/proxy/socks: insufficient header > read tcp 127.0.0.1:1080->127.0.0.1:60842: i/o timeout
2019/01/14 12:59:34 tcp:127.0.0.1:60843 rejected  v2ray.com/core/proxy/socks: insufficient header > read tcp 127.0.0.1:1080->127.0.0.1:60843: i/o timeout
2019/01/14 13:05:26 tcp:127.0.0.1:61445 accepted tcp:www.google.com:443 
2019/01/14 13:05:26 tcp:127.0.0.1:61447 accepted tcp:www.google.com:443 
2019/01/14 13:05:28 tcp:127.0.0.1:61453 accepted tcp:mtalk.google.com:443 
2019/01/14 13:05:29 tcp:127.0.0.1:61455 accepted tcp:www.gstatic.com:443 
`

**Comment by kslr** [comment]
Http 503

**Comment by moozc** [comment]
我换成官方安装。ws+tls+nginx就没有再出现过这个问题了。

**Comment by ZhouZiY** [comment]
> 我换成官方安装。ws+tls+nginx就没有再出现过这个问题了。

官方安装是什么意思？

**Comment by Chandler-Lu** [comment]
@ZhouZiY 用官方安装脚本。。不要用网上乱七八糟的一件脚本

**Comment by ZhouZiY** [comment]
@Chandler-Lu 我就是用官方脚本安装的  apache+ws+tls

**Comment by Chandler-Lu** [comment]
@ZhouZiY 你好歹提供客户端&服务端配置吧。。
