### ISSUE TITLE
Patch to support MTProto on Telegram X

### ISSUE THREAD

**Issue by nicholascw** [v2ray/v2ray-core#1297]
The long-lasting knwon issue that V2Ray cannot work with Telegram X 's MTProxy could probably have the same issue like this issue mentioned. Maybe it's possible to fix it?

https://github.com/tdlib/td/issues/292

**Comment by zbttl** [comment]
I also encountered this problem.The MTProxy of V2Ray support
32 numbers key.It can't work.I use a script to get a 34 numbers key,it's OK.

**Comment by meokey** [comment]
I have the same error:

2018/10/10 13:57:53 [Info] [2795172921] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/mtproto: invalid connection type: [ee,ee,ee,ee]
