### ISSUE TITLE
挂代理没法访问路由器管理页面http://192.168.1.1/ 怀疑是路由实现有问题

### ISSUE THREAD

**Issue by daiaji** [v2ray/v2ray-core#1304]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V2Ray v3.46
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
firefox里设置代理为127.0.0.1:1080访问路由器管理页面http://192.168.1.1/
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
无法访问
4) 你期待看到的正确表现是怎样的？
可以访问
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
```

客户端配置:

```
{
	"inbound": {
		"port": 1080,
		"protocol": "http",
		"settings": {
			"auth": "noauth"
		}
	},
	"outbound": {
		"protocol": "vmess",
		"settings": {
			"vnext": [{
				"address": "*.*.*",
				"port": 443,
				"users": [{
					"id": "***********************************",
					"alterId": 64
				}]
			}]
		},
		"streamSettings": {
			"network": "ws",
			"security": "tls"
		}
	},
	"outboundDetour": [{
		"protocol": "freedom",
		"settings": {

		},
		"tag": "direct"
	}],
	"routing": {
		"strategy": "rules",
		"settings": {
			"domainStrategy": "IPOnDemand",
			"rules": [{
				"type": "field",
				"domain": [
					"mob.com",
					"jpush.cn",
					"mincdn.com",
					"bilibili.cn",
					"umeng.com",
					"xiaomi.net",
					"geosite:cn"
				],
				"ip": [
					"0.0.0.0/8",
					"10.0.0.0/8",
					"100.64.0.0/10",
					"127.0.0.0/8",
					"169.254.0.0/16",
					"172.16.0.0/12",
					"192.0.0.0/24",
					"192.0.2.0/24",
					"192.168.0.0/16",
					"198.18.0.0/15",
					"198.51.100.0/24",
					"203.0.113.0/24",
					"::1/128",
					"fc00::/7",
					"fe80::/10",
					"geoip:cn"
				],
				"outboundTag": "direct"
			}]
		}
	}
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

浏览器F12貌似是请求503
怀疑是被丢到vmess代理去了
直接访问

**Comment by DarienRaymond** [comment]
https://www.v2ray.com/chapter_02/03_routing.html#tips
