### ISSUE TITLE
在配置开发环境的时候发现一个问题

### ISSUE THREAD

**Issue by Mondaydream** [v2ray/v2ray-core#1306]
If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2ray/discussion/issues) first.
在配置开发环境的时候,出现 undefined: net.ListenConfig 的error 如下
go get -u v2ray.com/core/...
# v2ray.com/core/common/net
../../../../../../../v2ray.com/core/common/net/system.go:11:21: undefined: net.ListenConfig

然后利用gomobile尝试编译v2ray-core出现同样的error
是否是版本代码的问题?使用的是最新的版本
This issue will be closed immediately.

**Comment by VictoriaRaymond** [comment]
请升级到 Go 1.11。这个类是 1.11 新加的。
