### ISSUE TITLE
如何自行修改geoip和geosite文件

### ISSUE THREAD

**Issue by mikusjelly** [v2ray/v2ray-core#1307]
想了解一下，项目中的geoip和site的dat文件是从哪里更新的？
刚才配置了国内直连，发现某个国内域名不在里面，所以，想自行添加。

请问如何操作比较好？

**Comment by mikusjelly** [comment]
https://github.com/gslsoft/v2ray-custom-geo

使用了这个数据，替换了默认的。

**Comment by avatasia** [comment]
> https://github.com/gslsoft/v2ray-custom-geo
> 
> 使用了这个数据，替换了默认的。

不行 只有CN, github什么的全没有.

**Comment by mikusjelly** [comment]
肯定只有CN的，默认cn ip不使用代理。
