### ISSUE TITLE
导入config string的问题

### ISSUE THREAD

**Issue by Mondaydream** [v2ray/v2ray-core#1312]
If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2ray/discussion/issues) first.
最近的commit中增加了 一个函数 
// StartInstance starts a new V2Ray instance with given serialized config.
func StartInstance(configFormat string, configBytes []byte) (*Instance, error) {
	var mb buf.MultiBuffer
	common.Must2(mb.Write(configBytes))
	config, err := LoadConfig(configFormat, "", &mb)
	if err != nil {
		return nil, err
	}
	instance, err := New(config)
	if err != nil {
		return nil, err
	}
	if err := instance.Start(); err != nil {
		return nil, err
	}
	return instance, nil
}
用来更方便地接入config ,实践中发现 configFormat 字符串不知应给什么格式 才能获取到 正确的config
在内部的函数中 

	if f, found := configLoaderByName[formatName]; found {
		return f.Loader(input)
	}
这个map 的 found 始终都处于 false的状态 导致一直会出现 Unable to load config in  configFormat 的error 
This issue will be closed immediately.

**Comment by VictoriaRaymond** [comment]
默认只支持 protobuf 格式，见：https://github.com/v2ray/v2ray-core/blob/master/v2ray_test.go#L70

或者引用这个包才可以支持 json 格式：https://github.com/v2ray/v2ray-core/blob/master/main/jsonem/jsonem.go
