### ISSUE TITLE
关于设置多个传输参数的疑问

### ISSUE THREAD

**Issue by i258559** [v2ray/v2ray-core#1317]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
3.47

2) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
在主传出、额外传出配置中定义“sendThrough”，并指向服务器的2个IP，但在使用中发现，如果在主传出配置存在的前提下，额外的传出配置不生效（使用v2配置文件中2中连接方式，实际传出都是“100.100.101.1”）

3) 你期待看到的正确表现是怎样的？
期待额外的传出配置也可生效。

4) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:
### {
    "inbound": {
        "port": 123,
        "protocol": "vmess",
        "settings": {
            "udp": true,
            "clients": [
                {
                    "id": "8fa4666-6a67-70c0-4e55-dbc2356f70ce",
                    "levels": 1，
                    "alterId": 32
                }
            ]
        }
    },
    "outbound": {
        "sendThrough": "100.100.101.1",
        "protocol": "freedom",
        "settings": {}
    },
    "inboundDetour": [
        {
            "protocol": "shadowsocks",
            "port": 456,
            "settings": {
                "method": "chacha20-ietf-poly1305",
                "password": "UJ2fnz0Bm",
                "udp": true,
                    "levels": 1,
                "ota": false
            }
        }
    ],
    "outboundDetour": [
        {
            "protocol": "blackhole",
            "sendThrough": "100.100.101.2",
            "settings": {},
            "tag": "blocked"
        }
    ],
    "routing": {
        "strategy": "rules",
        "settings": {
            "rules": [
                {
                    "type": "field",
                    "ip": [
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "203.0.113.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10"
                    ],
                    "outboundTag": "blocked"
                }
            ]
        }
    }
}

**Comment by TanNang** [comment]
![image](https://user-images.githubusercontent.com/38479770/47012796-aa45b600-d134-11e8-83ab-0f142d9aaf4b.png)

**Comment by i258559** [comment]
多谢大佬回复，我再根据上面的研究下
