### ISSUE TITLE
服务器安装问题：使用go.sh在服务器安装v3.47的最后一步的时候，系统提示找不到/tmp/v2ray/v2ray-v3.47-linux-32/v2ray文件，安装失败。

### ISSUE THREAD

**Issue by c4fun** [v2ray/v2ray-core#1320]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

仅与服务器相关：v3.41

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

使用go.sh在服务器升级v3.47的最后一步的时候，系统提示找不到/tmp/v2ray/v2ray-v3.47-linux-32/v2ray文件。安装失败。

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

安装脚本提示**拷贝v2ray二进制文件失败**；
并且v2ray安装不成功

4) 你期待看到的正确表现是怎样的？

v2ray可以正确安装

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:
不涉及

客户端配置:
不涉及

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
root@host:~# ./go.sh 
Installing V2Ray v3.47 on i686
Downloading V2Ray.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   608    0   608    0     0    583      0 --:--:--  0:00:01 --:--:--   583
100 10.5M  100 10.5M    0     0  2550k      0  0:00:04  0:00:04 --:--:-- 4383k
Extracting V2Ray package to /tmp/v2ray.
Archive:  /tmp/v2ray/v2ray.zip
   creating: /tmp/v2ray/doc/
  inflating: /tmp/v2ray/doc/readme.md  
  inflating: /tmp/v2ray/geoip.dat    
  inflating: /tmp/v2ray/geosite.dat  
   creating: /tmp/v2ray/systemd/
  inflating: /tmp/v2ray/systemd/v2ray.service  
   creating: /tmp/v2ray/systemv/
  inflating: /tmp/v2ray/systemv/v2ray  
  inflating: /tmp/v2ray/v2ctl        
 extracting: /tmp/v2ray/v2ctl.sig    
  inflating: /tmp/v2ray/v2ray        
 extracting: /tmp/v2ray/v2ray.sig    
  inflating: /tmp/v2ray/vpoint_socks_vmess.json  
  inflating: /tmp/v2ray/vpoint_vmess_freedom.json  
Shutting down V2Ray service.
cp: cannot stat '/tmp/v2ray/v2ray-v3.47-linux-32/v2ray': No such file or directory
Copy V2Ray binary failed.

```

客户端错误日志:  不涉及

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

不涉及

8) 其它相关的配置文件（如 Nginx）和相关日志。

不涉及

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

不涉及。安装问题

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

不涉及。安装问题

**Comment by veekxt** [comment]
应该是你的go.sh太老了，更新它

**Comment by c4fun** [comment]
好的，多谢。确实是go.sh太老了，更新了就可以
