### ISSUE TITLE
如何禁止tls1.0 tls1.1

### ISSUE THREAD

**Issue by ZhouZiY** [v2ray/v2ray-core#1323]
服务器上使用vmess h2，tlsSettings添加
"allowInsecure": false,
"allowInsecureCiphers":false
在www.ssllabs.com测试
![image](https://user-images.githubusercontent.com/16163586/47199481-6527bb00-d3a4-11e8-9486-87b11ef66f8e.png)
TLS 1.0、TLS 1.1仍然在使用

**Comment by TanNang** [comment]
https://github.com/golang/go/issues/21144

**Comment by hzlmy2002** [comment]
通过nginx转发，在nginx里禁用

**Comment by veekxt** [comment]
这两个配置的含义参考官方文档，不过看起来你已经看了，但误解了他们的含义，前者会验证证书是否被信任，后者限制了加密算法的使用，但他们和`TLS版本`没有直接关系。

**Comment by ZhouZiY** [comment]
> 这两个配置的含义参考官方文档，不过看起来你已经看了，但误解了他们的含义，前者会验证证书是否被信任，后者限制了加密算法的使用，但他们和`TLS版本`没有直接关系。

好的，谢谢
