### ISSUE TITLE
BT流量不走代理能配置在客户端吗？

### ISSUE THREAD

**Issue by lededev** [v2ray/v2ray-core#1325]
手册里的例子是在服务器端抛弃Bittorrent协议流量的，而不是在客户端。
如果有这个功能的话，能否给个配置文件例子，在v2ray客户端直接分析协议，将redir到透明代理端口的Bittorrent不走v2ray server而走直通。
毕竟很多用户的v2ray server账号只是买服务，用户并没有配置权，而在客户端直接避免bittorrent的流量走代理服务器则相对要方便控制一些。

**Comment by Chandler-Lu** [comment]
手册里的routing大部分内容在客户端和服务端都是通用的啊

**Comment by VictoriaRaymond** [comment]
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。
