### ISSUE TITLE
用最基本的json配置都无法使用v2ray，求救！

### ISSUE THREAD

**Issue by douruixin** [v2ray/v2ray-core#1328]
vps是vultr，用官方的新手配置好服务器端和客户端的config.json，并做了如下修改，仍然无法使用v2ray：
1、已将服务端和客户端的时间调成一样；
2、已将两个版本都升级到了3.48；
3、服务端的tcp端口已经是ipv4；
4、远程可以ping通，telnet也可以建立连接；

但就是无法使用v2ray，在梅林路由器中不行，在chrome的proxy中不行，真是郁闷死了，请大神们指点我还需要注意啥？

**Comment by nicholascw** [comment]
当然是需要注意这里**不是**你发这种求救的内容的地方啊

**Comment by wswaw** [comment]
请将问题填入issue模板后提交
