### ISSUE TITLE
是否支持限制单个用户的流量

### ISSUE THREAD

**Issue by b1gw00d** [v2ray/v2ray-core#1329]
官网已经支持流量统计但是不知道是否支持限制单个用户流量，或者有什么接口吗，感谢

**Comment by VictoriaRaymond** [comment]
不支持 

如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。
