### ISSUE TITLE
请教一下服务器按域名自动分流转发的配置问题

### ISSUE THREAD

**Issue by kennysoul** [v2ray/v2ray-core#1330]
资源：
拥有VPS1和VPS2两台服务器，VPS1（主力）搭载v2ray 版本3.48，VPS2（工作用）搭载Shadowsocks；

现状：
1、本地客户端连接VPS1或VPS2均可正常使用，服务器本身配置没有问题；
2、客户端连接VPS2的速度不理想，但客户端连接VPS1，以及VPS1连接VPS2的速度都相当理想；
 3、VPS2只能提供SS服务，不能安装v2ray等其它服务

需求：
因某些场景（本文以google.com为例）需要VPS2的IP，所以希望在VPS1上配置，实现自动转发的功能，不需要更改客户端的设置；

求助：
参考了网上的资料后自行配置了一下，但不成功，因为本身只是个新手，找不到问题所在，现将我的配置文件（VPS1的配置文件）发上来，请各位高手帮忙指正一下，谢谢！

`{
  "inbound": {
    "port": 9394,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "27568e45-xxxx-xxxx-xxxx-170559eae1aa",
          "level": 1,
          "alterId": 64
        }
      ]
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  }
},
  "outboundDetour": [
    {
      "protocol": "shadowsocks",
      "settings": {
           "servers": [
          {
            "address": "2.2.2.2", //my vps2的IP
            "method": "rc4-md5",
            "ota": false,
            "password": "mypassword",
            "port": 1997
          }
         ]  
        },
      "tag": "work"
 }
],

  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "domain": [
            "www.goole.com"  // 匹配"www.goole.com"的域名
          ],
          "outboundTag": "work"
        }
      ]
    }
  }

`

**Comment by qgtxqj** [comment]
www.goole.com 这儿仅仅是笔误吗？

**Comment by hasayakey** [comment]
这个应该是IP的问题，就是到达vps1的请求是IP了，不再是google.com，路由无法识别

**Comment by kennysoul** [comment]
> [www.goole.com](http://www.goole.com) 这儿仅仅是笔误吗？

不好意思，是笔误

**Comment by kennysoul** [comment]
> 这个应该是IP的问题，就是到达vps1的请求是IP了，不再是google.com，路由无法识别

可能配置语法也有问题，我重新在json editor online校正后，在vps上的v2ray校验的结果是不通过的，不知道哪里出错了...
错误信息：
V2Ray 3.48 (die Commanderin) 20181021
A unified platform for anti-censorship.
main: failed to read config file: /etc/v2ray/c3.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/ext/tools/conf/command: failed to parse json config > v2ray.com/ext/tools/conf/serial: failed to parse json config > v2ray.com/ext/tools/conf: unknown router rule type: 

 > exit status 255

**Comment by kennysoul** [comment]
以下是JSON EDITOR在线校验后的json代码：
`{
"inbound": {
"port": 9394,
"protocol": "vmess",
"settings": {
"clients": [
{
"id": "27568e45-xxxx-xxxx-xxxx-170559eae1aa",
"level": 1,
"alterId": 64
}
]
}
},
"outbound": {
"protocol": "freedom",
"settings": {}
},
"outboundDetour": [
{
"protocol": "shadowsocks",
"settings": {
"servers": [
{
"address": "2.2.2.2", 
"method": "aes-256-gcm",
"ota": false,
"password": "mypassword",
"port": 1997
}
]
},
"tag": "work"
}
],

"routing": {
"strategy": "rules",
"settings": {
"rules": [
{
"domain": [
"www.google.com" 
],
"outboundTag": "work"
}
]
}
}
}
`

**Comment by kennysoul** [comment]
此json通过v2ray的校验，但是无法分流，所有流量都是走v2ray服务器：
`{
  "inbound": {
    "port":9394,
    "listen":"127.0.0.1",
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
	  "id":"91625b5f-xxxx-xxxx-xxxx-660f026f3a4f",
	  "alterId":64
	}
    ]
    },
    "streamSettings":{
      "network":"ws",
      "wsSettings": {
	  "path":"/vv/"
    }
	}
   },
  "outbound": {
"protocol": "freedom",
"settings": {}
},
   "outboundDetour ":{  
        "protocol":"shadowsocks",
        "settings":{  
            "servers":[  
                {  
                    "address":"2.2.2.2",
                    "method":"aes-256-cfb",
                    "password":"mypassword",
                    "port":1997,
                    "ota":false
                }
            ]
        },
        "tag": "work"
},
     "dns": {
  
  "servers": [
      "1.1.1.1",
      "8.8.8.8",
      "localhost"
     ]
     },
     "routing": {
  "strategy": "rules",
  "settings": {
  "domainStrategy":"AsIs",
    "rules": [
      {
        "type": "field",
        "domain": [
          "ipaddress.com",
          "google.com"
        ],
        "outboundTag": "work"
      },
      {
        "type": "field",
        "ip": "0.0.0.0/8",
        "outboundTag": "direct"
      }
  ]
  }
}
}`

**Comment by kennysoul** [comment]
此json通过v2ray校验，并且所有流量都会走ss服务器
`{
  "inbound": {
    "port":9394,
    "listen":"127.0.0.1",
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
	  "id":"91625b5f-xxxx-xxxx-xxxx-660f026f3a4f",
	  "alterId":64
	}
    ]
    },
    "streamSettings":{
      "network":"ws",
      "wsSettings": {
	  "path":"/vv/"
    }
	}
   },
  
   "outbound":{  
        "protocol":"shadowsocks",
        "settings":{  
            "servers":[  
                {  
                    "address":"2.2.2.2",
                    "method":"aes-256-cfb",
                    "password":"mypassword",
                    "port":1997,
                    "ota":false
                }
            ]
        }
    }
}`

**Comment by kennysoul** [comment]
始终都是无法指定域名（如google.com）走SS服务器

**Comment by nobody3u** [comment]
你在下面引用的那份配置里面的outboundDetour后面多了个空格
同时outboundDetour应该写在一个`[ ]`（列表）里面，而不是直接用`{ }`（字典）
大概这样：
```bash
"outboundDetour": [
    {
      "protocol": "socks",
      "tag": "work",
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 1234,
            "users": []
          }
        ]
      }
    }
  ],
```
测试配置的时候注意仔细看日志，很多问题可以从日志里发现
比如刚才我是看到这么一行，然后逐步查到问题：
```bash
[Warning] [2511306159] v2ray.com/core/app/dispatcher: non existing tag: work
```

> 此json通过v2ray的校验，但是无法分流，所有流量都是走v2ray服务器：
> `{
> "inbound": {
> "port":9394,
> "listen":"127.0.0.1",
> "protocol": "vmess",
> "settings": {
> "clients": [
> {
> "id":"91625b5f-xxxx-xxxx-xxxx-660f026f3a4f",
> "alterId":64
> }
> ]
> },
> "streamSettings":{
> "network":"ws",
> "wsSettings": {
> "path":"/vv/"
> }
> }
> },
> "outbound": {
> "protocol": "freedom",
> "settings": {}
> },
> "outboundDetour ":{
> "protocol":"shadowsocks",
> "settings":{
> "servers":[
> {
> "address":"2.2.2.2",
> "method":"aes-256-cfb",
> "password":"mypassword",
> "port":1997,
> "ota":false
> }
> ]
> },
> "tag": "work"
> },
> "dns": {
> 
> "servers": [
> "1.1.1.1",
> "8.8.8.8",
> "localhost"
> ]
> },
> "routing": {
> "strategy": "rules",
> "settings": {
> "domainStrategy":"AsIs",
> "rules": [
> {
> "type": "field",
> "domain": [
> "ipaddress.com",
> "google.com"
> ],
> "outboundTag": "work"
> },
> {
> "type": "field",
> "ip": "0.0.0.0/8",
> "outboundTag": "direct"
> }
> ]
> }
> }
> }`

**Comment by kennysoul** [comment]
> 你在下面引用的那份配置里面的outboundDetour后面多了个空格
> 同时outboundDetour应该写在一个`[ ]`（列表）里面，而不是直接用`{ }`（字典）
> 大概这样：
> 
> ```shell
> "outboundDetour": [
>     {
>       "protocol": "socks",
>       "tag": "work",
>       "settings": {
>         "servers": [
>           {
>             "address": "127.0.0.1",
>             "port": 1234,
>             "users": []
>           }
>         ]
>       }
>     }
>   ],
> ```
> 
> 测试配置的时候注意仔细看日志，很多问题可以从日志里发现
> 比如刚才我是看到这么一行，然后逐步查到问题：
> 
> ```shell
> [Warning] [2511306159] v2ray.com/core/app/dispatcher: non existing tag: work
> ```
> 
> > 此json通过v2ray的校验，但是无法分流，所有流量都是走v2ray服务器：
> > `{
> > "inbound": {
> > "port":9394,
> > "listen":"127.0.0.1",
> > "protocol": "vmess",
> > "settings": {
> > "clients": [
> > {
> > "id":"91625b5f-xxxx-xxxx-xxxx-660f026f3a4f",
> > "alterId":64
> > }
> > ]
> > },
> > "streamSettings":{
> > "network":"ws",
> > "wsSettings": {
> > "path":"/vv/"
> > }
> > }
> > },
> > "outbound": {
> > "protocol": "freedom",
> > "settings": {}
> > },
> > "outboundDetour ":{
> > "protocol":"shadowsocks",
> > "settings":{
> > "servers":[
> > {
> > "address":"2.2.2.2",
> > "method":"aes-256-cfb",
> > "password":"mypassword",
> > "port":1997,
> > "ota":false
> > }
> > ]
> > },
> > "tag": "work"
> > },
> > "dns": {
> > "servers": [
> > "1.1.1.1",
> > "8.8.8.8",
> > "localhost"
> > ]
> > },
> > "routing": {
> > "strategy": "rules",
> > "settings": {
> > "domainStrategy":"AsIs",
> > "rules": [
> > {
> > "type": "field",
> > "domain": [
> > "ipaddress.com",
> > "google.com"
> > ],
> > "outboundTag": "work"
> > },
> > {
> > "type": "field",
> > "ip": "0.0.0.0/8",
> > "outboundTag": "direct"
> > }
> > ]
> > }
> > }
> > }`

问题已解决，非常感谢

**Comment by kennysoul** [comment]
最终配置文件如下，感谢大家帮忙。
`{
  "inbound": {
    "port":9527,
    "listen":"127.0.0.1",
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
	  "id":"965cd0bf-xxxx-xxxx-xxxx-ec451abaxxxx",
	  "alterId":64
        }
      ]
    },
    "streamSettings":{
      "network":"ws",
      "wsSettings": {
	  "path":"/vv"
      }
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
        {   "protocol": "shadowsocks",
            "settings": {
                "servers": [
                    {
                    "address": "1.1.1.1",
                    "method": "aes-256-gcm",
                    "password": "mypassword",
                    "port": 1997,
                    "ota": false
                    }
                ]
            },
            "tag": "work"
        },
        {   "protocol": "shadowsocks",
            "settings": {
                "servers": [
                    {
                    "address": "2.2.2.2",
                    "method": "aes-256-cfb",
                    "password": "mypassword",
                    "port": 1997,
                    "ota": false
                    }
                ]
            },
            "tag": "home"
        }
  ],
  "routing": {
        "strategy": "rules",
        "settings": {
            "domainStrategy": "AsIs",
            "rules": [
				{
                "type": "field",
                "domain": [
					"domain:google.com",
					"domain:apple.net",
					"android",
					"ios"
					],
                "outboundTag": "work"
                },
				{
				"type": "field",
				"domain": [
					"myip.cn",
					"iqiyi",
					"qqlive",
					"qq.com"
					],
				"outboundTag": "Home"
				}
			]
        }
  }
}
`

**Comment by kennysoul** [comment]
'{
  "inbound": {
    "port":24860,
    "listen":"127.0.0.1",
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
	  "id":"",
	  "alterId":64
        }
      ]
    },
    "streamSettings":{
      "network":"ws",
      "wsSettings": {
	  "path":"/ray"
      }
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
        {   "protocol": "shadowsocks",
            "settings": {
                "servers": [
                    {
                    "address": "",
                    "method": "aes-256-gcm",
                    "password": "",
                    "port": 990,
                    "ota": false
                    }
                ]
            },
            "tag": "LA"
        },
        {   "protocol": "shadowsocks",
            "settings": {
                "servers": [
                    {
                    "address": "",
                    "method": "",
                    "password": "",
                    "port": 990,
                    "ota": false
                    }
                ]
            },
            "tag": "GZ"
        }
  ],
  "routing": {
        "strategy": "rules",
        "settings": {
            "domainStrategy": "AsIs",
            "rules": [
				{
                "type": "field",
                "domain": [
					"domain:ipaddress.com",
					"domain:cloudfront.net",
					"netflix",
					"nflx",
					"aws",
					"amazon",
					"aiv"
					],
                "outboundTag": "LA"
                },
				{
				"type": "field",
				"domain": [
					"myip.cn",
					"ssports",
					"qqmusic",
					"youku",
					"ykimg.com",
					"irs01.com",
					"qy.net",
					"iqiyi",
					"qqlive",
					"qq.com"
					],
				"outboundTag": "GZ"
				}
			]
        }
  }
}
`

**Comment by kennysoul** [comment]
最终配置如下，感谢大家的帮忙！

```
{
  "inbound": {
    "port":9527,
    "listen":"127.0.0.1",
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
	  "id":"965cd0bf-xxxx-xxxx-xxxx-ec451abxxxx",
	  "alterId":64
        }
      ]
    },
    "streamSettings":{
      "network":"ws",
      "wsSettings": {
	  "path":"/vv"
      }
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
        {   "protocol": "shadowsocks",
            "settings": {
                "servers": [
                    {
                    "address": "1.1.1.1",
                    "method": "aes-256-gcm",
                    "password": "mypassword",
                    "port": 1997,
                    "ota": false
                    }
                ]
            },
            "tag": "work"
        },
        {   "protocol": "shadowsocks",
            "settings": {
                "servers": [
                    {
                    "address": "2.2.2.2",
                    "method": "aes-256-gcm",
                    "password": "mypassword",
                    "port": 1997,
                    "ota": false
                    }
                ]
            },
            "tag": "home"
        }
  ],
  "routing": {
        "strategy": "rules",
        "settings": {
            "domainStrategy": "AsIs",
            "rules": [
				{
                "type": "field",
                "domain": [
					"domain:google.com",
					"domain:icloud.com",
					"apple"
					],
                "outboundTag": "work"
                },
				{
				"type": "field",
				"domain": [
					"myip.cn",
					"iqiyi",
					"qq.com"
					],
				"outboundTag": "home"
				}
			]
        }
  }
}
```

**Comment by VictoriaRaymond** [comment]
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。
