### ISSUE TITLE
添加chinasites后无法正常访问google play市场

### ISSUE THREAD

**Issue by coffilk** [v2ray/v2ray-core#1332]
1.  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
    服务器v2ray v3.48 客户端为android 8.0 Bifrostv v4.6

2. 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
   google play为手机内置（国行）。打开市场无法加载，客户端配置去掉chinasites可以正常使用

3. 你看到的不正常的现象是什么？
    What did you see?
    无法加载

4. 你期待看到的正确表现是怎样的？
    What's your expectation?
    国内网站直连，谷歌市场正常使用

5. 请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (Mask IP addresses before submit this issue).

    Server Configuration File（服务器端配置文件）:

    // 在这里附上服务器端配置文件
    // Please attach your server configuration file here.
{
    "log": {
        "access": "/var/log/v2ray/access.log",
        "error": "/var/log/v2ray/error.log",
        "loglevel": "warning"
    },
    "inbound": {
        "port": 12345,
        "protocol": "vmess",
        "settings": {
            "clients": [
                {
                    "id": "uuid",
                    "level": 1,
                    "alterId": 64
                }
            ]
        },
        "streamSettings": {
            "network": "kcp"
        }
    },
    "outbound": {
        "protocol": "freedom",
        "settings": {}
    },
    "inboundDetour": [],
    "outboundDetour": [
        {
            "protocol": "blackhole",
            "settings": {},
            "tag": "blocked"
        }
    ],
    "routing": {
        "strategy": "rules",
        "settings": {
            "rules": [
                {
                    "type": "field",
                    "ip": [
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "203.0.113.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10"
                    ],
                    "outboundTag": "blocked"
                }
            ]
        }
    }
}

    Client Configuration File（客户端配置文件）:

    // 在这里附上客户端配置文件
    // Please attach your client configuration file here.
{
    "log": {
        "loglevel": "warning"
    },
    "inbound": {
        "listen": "127.0.0.1",
        "port": 1080,
        "protocol": "socks",
        "settings": {
            "auth": "noauth",
            "udp": true,
            "ip": "127.0.0.1"
        }
    },
    "outbound": {
        "protocol": "vmess",
        "settings": {
            "vnext": [
                {
                    "address": "ip",
                    "port": 12345,
                    "users": [
                        {
                            "id": "uuid",
                            "level": 1,
                            "alterId": 64
                        }
                    ]
                }
            ]
        },
        "streamSettings": {
            "network": "kcp"
        },
        "mux": {
            "enabled": true,
            "concurrency": 8
        }
    },
    "outboundDetour": [
        {
            "protocol": "freedom",
            "settings": {},
            "tag": "direct"
        }
    ],
    "routing": {
        "strategy": "rules",
        "settings": {
            "rules": [
                {
                    "type": "chinasites",
                    "outboundTag": "direct"
                },
                {
                    "type": "field",
                    "ip": [
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "203.0.113.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10"
                    ],
                    "outboundTag": "direct"
                },
                {
                    "type": "chinaip",
                    "outboundTag": "direct"
                }
            ]
        }
    }
}

6. 请附上出错时软件输出的日志。在 Linux 中，日志通常在 /var/log/v2ray/error.log 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually /var/log/v2ray/error.log on Linux.

    Server Log File（服务器端日志）:

    // 在这里附上服务器端日志
    // Please attach your server log here.

Client Log File（客户端日志）:

    // 在这里附上客户端日志
    // Please attach your client log here.

**Comment by qgtxqj** [comment]
可能是services.googleapis.cn这个网站的被错误归类到chinasites里了

**Comment by coffilk** [comment]
> 
> 
> 可能是services.googleapis.cn这个网站的被错误归类到chinasites里了

感谢，客户端配置里加了
       {
          "type": "field",
          "domain": [
            "googleapis.cn",
            "google.cn"
          ],
          "outboundTag": "proxy"
        },
可以正常使用了
