### ISSUE TITLE
mkcp的速度慢（不如KCPTUN+SOCKS5快）

### ISSUE THREAD

**Issue by becapital** [v2ray/v2ray-core#1333]
1. mkcp的速度慢（不如KCPSERVER=KCPTUN+SOCKS5快）
2. 我电信200MB宽带，跑V2RAY KCP才1-5MB/S.
服务器端，客户端，设置过了，速度还是没有KCPSERVER快.KCPSERVER有5-15MB/S)
请教老师大佬，这个需要怎么配置参数才够快

**Comment by VictoriaRaymond** [comment]
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。
