### ISSUE TITLE
Ubuntu 18.04.1中V2Ray显示command not found 

### ISSUE THREAD

**Issue by sherkwast** [v2ray/v2ray-core#1335]
版本：3.48
场景：将v2ray-linux-64压缩包解压后命令行直接使用
`~/v2ray-linux-64/v2ray`
显示  `-bash: ～/v2ray-linux-64/v2ray: Permission denied`
使用sudo提高权限
显示 `sudo: ～/v2ray-linux-64/v2ray: command not found`

使用v3.41时命令`~/v2ray-linux-64/v2ray`能正常运行
请问解决方式？

**Comment by veekxt** [comment]
文件需要“可执行权限”才能运行，即使root也是如此。请自行搜索相关知识。

**Comment by sherkwast** [comment]
以前的版本没有需要额外授权，现在不能即开即用，不考虑之后的版本恢复一下么

**Comment by hzlmy2002** [comment]
这个与v2ray无关
想省事考虑umask 000
