### ISSUE TITLE
v2ray 源码获取报错

### ISSUE THREAD

**Issue by lanjianchun** [v2ray/v2ray-core#1336]
`root@hwsrv-312409:~#` go get -u v2ray.com/core/...
`#` v2ray.com/core/common/net
`go/src/v2ray.com/core/common/net/system.go:11:21:` undefined: net.ListenConfig
`root@hwsrv-312409:~#` go get -u v2ray.com/ext/...
`#` v2ray.com/core/common/net
`go/src/v2ray.com/core/common/net/system.go:11:21: undefined: net.ListenConfig
`root@hwsrv-312409:~# 

undefined: net.ListenConfig

**Comment by VictoriaRaymond** [comment]
升级Go 1.11
