### ISSUE TITLE
Windows10 1809出现过多HTTP Auto Proxy Detection Worker Process进程

### ISSUE THREAD

**Issue by luojianxhlxt** [v2ray/v2ray-core#1337]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
服务器和客户端都是3.48
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
win10 1803,Chromium 67，通过VMess kcp-udp，代理任何网站
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
windows任务管理器出现许多HTTP Auto Proxy Detection Worker Process进程，查询发现是C:\Windows\System32\pacjsworker.exe程序导致。
能够正常连接代理数据，服务器和客户端占用正常，仅仅出现HTTP Auto Proxy Detection Worker Process进程数量太多的问题。
[示例图链接](https://ws1.sinaimg.cn/large/0076Qr4mgy1fwlu3lpd8xj317w0mrgpq.jpg)
4) 你期待看到的正确表现是怎样的？
进程数量不应该会这么多，索然我不清楚正常会是多少

**Comment by nobody3u** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1979

**Comment by VictoriaRaymond** [comment]
和V2Ray没有关系，V2Ray压根不涉及 proxy auto config
