### ISSUE TITLE
Centos 7 安装最新版的r2ray v1.12.4 ,客户端异常退出

### ISSUE THREAD

**Issue by helpit** [v2ray/v2ray-core#134]

**Comment by helpit** [comment]
vps centos 7 升级到最新版,V2ray v1.12.4,
本地 centos 7 客户端 也使用最新V2ray v1.12.4, 当有流量通过本地centos客户端v2ray时, v2ray 进程自动终止,现centos 7 v2ray 版本切换成V2ray v1.12.2, 暂时没自动退出.

**Comment by helpit** [comment]
Win10 x64最新V2ray v1.12.4客户端,用一会也莫名退出.

**Comment by v2ray** [comment]
主要问题出在 VMess Outbound，临时的解决方案是把客户端降回 1.11.x，服务器可以继续使用1.12.x。

**Comment by helpit** [comment]
thanks

**Comment by wtlusvm** [comment]
今天同样情况，将客户端和服务端升到最新版本后解决

**Comment by sutun2008** [comment]
博主能不能写个centos下的一键安装脚本，适合俺这样的老菜用

**Comment by wtlusvm** [comment]
@sutun2008 

> V2Ray 提供了一个[安装脚本](https://www.v2ray.com/zh_cn/chapter_01/install.html)用于在 Linux 环境的安装和配置。这个脚本会自动检测有没有安装过 V2Ray，如果没有，则进行完整的配置；如果之前安装过 V2Ray，则只更新 V2Ray 二进制程序而不更新配置。

**Comment by v2ray** [comment]
Fixed
