### ISSUE TITLE
YouTube iOS客户端无法播放视频及内存泄漏的问题

### ISSUE THREAD

**Issue by ShuoHuang** [v2ray/v2ray-core#1341]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
   3.50.1

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

     用v2ray core编译了一个Frameworks，供给iOS的network extension调用，实现科学上网。

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

1. inbound采用socks协议，打开YouTube iOS客户端，视频列表，个人信息等都能加载成功，但是点击播放后，无法播放视频，一直在缓冲，包括视频前的广告也无法播放，但是用浏览器打开同样的视频是没有任何问题的，流畅播放，另外inbound采用http协议，就没有这样的问题；

2. 连接成功后，刷网页时，内存会缓慢增长，而在观看视频时，会出现内存飙升的情况，由于iOS对network extension的内存有15MB的限制，导致这个扩展进程被系统杀死，关于这个问题，经过我们自己的各种测试，例如修改本地策略的bufferSize为0或者其他一些尝试，都无法解决；

4) 你期待看到的正确表现是怎样的？

1. inbound采用socks协议时，YouTube iOS客户端能正常播放视频；

2. 内存能正常释放

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

使用的共享的服务器，没有配置

客户端配置:
```json
{
  "log": {
    "loglevel": "warning"
  },
  "inbound": {
    "port": 1089,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "127.0.0.1"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
        "vnext": [
            {
                "address": "xx.xx.xx.xx",
                "port": 20066,
                "users": [
                    {
                        "id": "xxxxxxxxxxxxxxxxxxxxxxxx",
                        "level": 0,
                        "alterId": 32
                    }
                ]
            }
        ]
    },
    "tag": "direct"
  },
  "policy": {
    "levels": {
      "0": {
          "uplinkOnly": 0,
          "bufferSize": 0
      }
    }
  }
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:
    无

客户端错误日志:
    无

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
    无

8) 其它相关的配置文件（如 Nginx）和相关日志。
   无

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。
  无

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。
无

**Comment by uimeet** [comment]
遇到同样的问题，我这边包括调整了arm64下默认的buffersize到1k（默认是16k），仍然无法解决这个问题。

**Comment by FatChou** [comment]
你好，我现在编译出了core.framework，但还不知道怎么在packetTunnel里面怎么使用，读取配置，启动服务，能否指点一二？

**Comment by uimeet** [comment]
@FatChou 在PacketTunnel启动服务器就行了。

**Comment by VictoriaRaymond** [comment]
Golang 的问题。https://github.com/golang/go/issues/21489

**Comment by FatChou** [comment]
> > Golang 的问题。[golang/go#21489](https://github.com/golang/go/issues/21489)
> 
> 第1个问题，inbound采用socks时，YouTube iOS客户端 无法播放视频的问题，你知道是怎么回事吗？
请问，怎么在PacketTunnel启动服务啊？

**Comment by ShuoHuang** [comment]
> > > Golang 的问题。[golang/go#21489](https://github.com/golang/go/issues/21489)
> > 
> > 
> > 第1个问题，inbound采用socks时，YouTube iOS客户端 无法播放视频的问题，你知道是怎么回事吗？
> > 请问，怎么在PacketTunnel启动服务啊？

你编译的Frameworks需要抛出启动接口，
然后配置好NEPacketTunnelNetworkSettings，调用setTunnelNetworkSettings()方法就可以启动了，
另外用非http的inbound协议的话，NEProxySettings中设置autoProxyConfigurationEnabled为true，设置好pac就可以了

**Comment by FatChou** [comment]
> autoProxyConfigurationEnabled

嗯，谢谢你的回答。我是这样做的：
NEPacketTunnelNetworkSettings *networkSettings = [[NEPacketTunnelNetworkSettings alloc] initWithTunnelRemoteAddress:@"8.8.8.8"];
    networkSettings.MTU = [NSNumber numberWithInteger:1500];
    
    NEIPv4Settings *IPv4Settings = [[NEIPv4Settings alloc] initWithAddresses:@[@"10.0.0.1"] subnetMasks:@[@"255.255.255.0"]];
    networkSettings.IPv4Settings = IPv4Settings;
    
    NSInteger proxyPort = 1080;
    NEProxySettings *proxySettings = [[NEProxySettings alloc] init];
    proxySettings.HTTPEnabled = YES;
    proxySettings.HTTPServer = [[NEProxyServer alloc] initWithAddress:@"127.0.0.1" port:proxyPort];
    proxySettings.HTTPSEnabled = YES;
    proxySettings.HTTPSServer = [[NEProxyServer alloc] initWithAddress:@"127.0.0.1" port:proxyPort];
    proxySettings.excludeSimpleHostnames = YES;
    proxySettings.matchDomains = @[@""];
    proxySettings.exceptionList = @[@"api.smoot.apple.com",@"configuration.apple.com",@"xp.apple.com",@"smp-device-content.apple.com",@"guzzoni.apple.com",@"captive.apple.com",@"*.ess.apple.com",@"*.push.apple.com",@"*.push-apple.com.akadns.net"];
    networkSettings.proxySettings = proxySettings;//代理配置
    
    NSError *coreError;
    NSString *configPath = [[NSBundle mainBundle] pathForResource:@"config3" ofType:@"json"];//配置文件路径

    //读取配置文件
    NSString *configString = [NSString stringWithContentsOfFile:configPath encoding:NSUTF8StringEncoding error:nil];
    configString = [configString stringByReplacingOccurrencesOfString:@"log_access" withString:self.logAccessPath];
    configString = [configString stringByReplacingOccurrencesOfString:@"log_error" withString:self.logErrorPath];
    
    NSData *configData = [configString dataUsingEncoding:NSUTF8StringEncoding];
    
    BOOL re = CoreLoadPlugins(&coreError);
    
    CoreConfig *coreConfig = [[CoreConfig alloc] init];
   
  BOOL result = [coreConfig xxX_Unmarshal:configData error:&coreError];//从这一步开始出错,解析配置，这里报错 result = NO。如果不做这一步，能启动服务，但好像没有转发数据。(我的设想是读出配置文件，传递给framework解析，加载。)

    //NSData *coreData = [coreConfig xxX_Marshal:data deterministic:YES error:&coreError];
    CoreInstance *coreInstance = CoreNew(coreConfig, &coreError);
    [coreInstance start:&coreError];
    
    [self setTunnelNetworkSettings:networkSettings completionHandler:^(NSError * _Nullable error) {
        if (error) {
            NSLog(@"error:%@", error);
            return;
        }
        NSLog(@"");
        completionHandler(coreError);
    }];

你再帮我看看哪里不对呢？谢谢啦

**Comment by FatChou** [comment]
> > > > Golang 的问题。[golang/go#21489](https://github.com/golang/go/issues/21489)
> > > 
> > > 
> > > 第1个问题，inbound采用socks时，YouTube iOS客户端 无法播放视频的问题，你知道是怎么回事吗？
> > > 请问，怎么在PacketTunnel启动服务啊？
> 
> 你编译的Frameworks需要抛出启动接口，
> 然后配置好NEPacketTunnelNetworkSettings，调用setTunnelNetworkSettings()方法就可以启动了，
> 另外用非http的inbound协议的话，NEProxySettings中设置autoProxyConfigurationEnabled为true，设置好pac就可以了

@ShuoHuang 谢谢你的解答。autoProxyConfigurationEnabled为false. inbound为http。
    CoreConfig *coreConfig = [[CoreConfig alloc] init];
    [coreConfig setXXX_unrecognized:configData];
    CoreInstance *coreInstance = CoreNew(coreConfig, &coreError);
    [coreInstance start:&coreError];
这样启动服务，感觉无法转发所有请求，设置pac后，国内可以访问，YouTube等国外的不能访问呢。config.json如下：
{
  "inbound": {
      "port": 1080,
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
          
      }
  },
  "outbound": {
        "protocol": "shadowsocks",
        "settings": {
            "servers": [{
                "method": "chacha20",
                "port": port,
                "password": "123",
                "address": "ip"
            }]
        },
        "mux": {
            "concurrency": 8,
            "enabled": false
        },
        "tag": "proxy"
    },
  "policy": {
      "levels": {
          "0": {"uplinkOnly": 0}
      }
  }
}

**Comment by VictoriaRaymond** [comment]
@ShuoHuang 有可能是 DNS 的问题，你可以开启 sniffing 试试看

**Comment by FatChou** [comment]
@ShuoHuang inbound用http，autoProxyConfigurationEnabled为false，这样的全局模式可以。如果换成true，pac配置好，inbound用socks不行，会是什么原因？

**Comment by ShuoHuang** [comment]
> @ShuoHuang inbound用http，autoProxyConfigurationEnabled为false，这样的全局模式可以。如果换成true，pac配置好，inbound用socks不行，会是什么原因？

应该是可以的，只是我们测试发现YouTube没法播放视频的问题，改为用tun2socks的方式了，你可以试试

**Comment by FatChou** [comment]
NEProxySettings只能设置HTTP代理，那么config.json中inbound用socks能使用socks协议代理隧道数据么？如何设置tun2socks呢？packetFlow read出来后，自己转吗？

**Comment by imfaker** [comment]
> @ShuoHuang inbound用http，autoProxyConfigurationEnabled为false，这样的全局模式可以。如果换成true，pac配置好，inbound用socks不行，会是什么原因？

请问这个 问题你解决了么 ？ 还有启动方法是暴露哪个么

**Comment by ameue** [comment]
> > @ShuoHuang inbound用http，autoProxyConfigurationEnabled为false，这样的全局模式可以。如果换成true，pac配置好，inbound用socks不行，会是什么原因？
> 
> 请问这个 问题你解决了么 ？ 还有启动方法是暴露哪个么

放弃了

**Comment by imfaker** [comment]
> > > @ShuoHuang inbound用http，autoProxyConfigurationEnabled为false，这样的全局模式可以。如果换成true，pac配置好，inbound用socks不行，会是什么原因？
> > 
> > 
> > 请问这个 问题你解决了么 ？ 还有启动方法是暴露哪个么
> 
> 放弃了


能求教下你  http下时如何配置的么 ？  调了天了 还没调通 ，要崩溃了 。    能帮忙 给下 packettunnel里你是怎么配置的么

**Comment by ameue** [comment]
> > > > @ShuoHuang inbound用http，autoProxyConfigurationEnabled为false，这样的全局模式可以。如果换成true，pac配置好，inbound用socks不行，会是什么原因？
> > > 
> > > 
> > > 请问这个 问题你解决了么 ？ 还有启动方法是暴露哪个么
> > 
> > 
> > 放弃了
> 
> 能求教下你 http下时如何配置的么 ？ 调了天了 还没调通 ，要崩溃了 。 能帮忙 给下 packettunnel里你是怎么配置的么

如果你会go，可以尝试优化下运行内存，Kitsunebi这个APP优化的很好，据说这个APP就是用的v2ray来支持的PacektTunnel，如果不会，最后还是放弃吧，15M的运行内存限制是被系统卡死了的。

**Comment by imfaker** [comment]
> > > > > @ShuoHuang inbound用http，autoProxyConfigurationEnabled为false，这样的全局模式可以。如果换成true，pac配置好，inbound用socks不行，会是什么原因？
> > > > 
> > > > 
> > > > 请问这个 问题你解决了么 ？ 还有启动方法是暴露哪个么
> > > 
> > > 
> > > 放弃了
> > 
> > 
> > 能求教下你 http下时如何配置的么 ？ 调了天了 还没调通 ，要崩溃了 。 能帮忙 给下 packettunnel里你是怎么配置的么
> 
> 如果你会go，可以尝试优化下运行内存，Kitsunebi这个APP优化的很好，据说这个APP就是用的v2ray来支持的PacektTunnel，如果不会，最后还是放弃吧，15M的运行内存限制是被系统卡死了的。

我们现在正在做的就是 去 优化go的内存 ，在弄。但是 ，现在就卡在 packet tunnel 这端，无法继续下去，而且也找不到原因，packet tunnel里 总共也没多少行代码 ，但就是调试不通，好几天找不出问题所在，然后之前别人是可以的，然后我真的就很无语，extension 里和 v2ray-core 又很难调试。  所以就想请教下 ，您之前http的inbounds是如何调通的， 如果能有packettunnel的 代码 ，真的不胜感激。570499253@qq.com 。 这是我的邮箱和 qq，如果能够  帮忙的话，真的非常感激 。

**Comment by wfkbyni** [comment]
使用Tun2socks.framework、vmess协议，youtube没有问题，能正常播放，只是在看某些网页的时候，vpn会很不稳定，会断掉链接，这个怎么处理呢？

**Comment by ednew2018** [comment]
> > > > > > @ShuoHuang inbound用http，autoProxyConfigurationEnabled为false，这样的全局模式可以。如果换成true，pac配置好，inbound用socks不行，会是什么原因？
> > > > > 
> > > > > 
> > > > > 请问这个 问题你解决了么 ？ 还有启动方法是暴露哪个么
> > > > 
> > > > 
> > > > 放弃了
> > > 
> > > 
> > > 能求教下你 http下时如何配置的么 ？ 调了天了 还没调通 ，要崩溃了 。 能帮忙 给下 packettunnel里你是怎么配置的么
> > 
> > 
> > 如果你会go，可以尝试优化下运行内存，Kitsunebi这个APP优化的很好，据说这个APP就是用的v2ray来支持的PacektTunnel，如果不会，最后还是放弃吧，15M的运行内存限制是被系统卡死了的。
> 
> 我们现在正在做的就是 去 优化go的内存 ，在弄。但是 ，现在就卡在 packet tunnel 这端，无法继续下去，而且也找不到原因，packet tunnel里 总共也没多少行代码 ，但就是调试不通，好几天找不出问题所在，然后之前别人是可以的，然后我真的就很无语，extension 里和 v2ray-core 又很难调试。 所以就想请教下 ，您之前http的inbounds是如何调通的， 如果能有packettunnel的 代码 ，真的不胜感激。[570499253@qq.com](mailto:570499253@qq.com) 。 这是我的邮箱和 qq，如果能够 帮忙的话，真的非常感激 。

https://github.com/xxf098/go-tun2socks-build
https://github.com/duanhai/Tun2socks-PacketTunnelDemo

**Comment by lil-hope** [comment]
> > > > > > > @ShuoHuang inbound用http，autoProxyConfigurationEnabled为false，这样的全局模式可以。如果换成true，pac配置好，inbound用socks不行，会是什么原因？
> > > > > > 
> > > > > > 
> > > > > > 请问这个 问题你解决了么 ？ 还有启动方法是暴露哪个么
> > > > > 
> > > > > 
> > > > > 放弃了
> > > > 
> > > > 
> > > > 能求教下你 http下时如何配置的么 ？ 调了天了 还没调通 ，要崩溃了 。 能帮忙 给下 packettunnel里你是怎么配置的么
> > > 
> > > 
> > > 如果你会go，可以尝试优化下运行内存，Kitsunebi这个APP优化的很好，据说这个APP就是用的v2ray来支持的PacektTunnel，如果不会，最后还是放弃吧，15M的运行内存限制是被系统卡死了的。
> > 
> > 
> > 我们现在正在做的就是 去 优化go的内存 ，在弄。但是 ，现在就卡在 packet tunnel 这端，无法继续下去，而且也找不到原因，packet tunnel里 总共也没多少行代码 ，但就是调试不通，好几天找不出问题所在，然后之前别人是可以的，然后我真的就很无语，extension 里和 v2ray-core 又很难调试。 所以就想请教下 ，您之前http的inbounds是如何调通的， 如果能有packettunnel的 代码 ，真的不胜感激。[570499253@qq.com](mailto:570499253@qq.com) 。 这是我的邮箱和 qq，如果能够 帮忙的话，真的非常感激 。
> 
> https://github.com/xxf098/go-tun2socks-build
> https://github.com/duanhai/Tun2socks-PacketTunnelDemo

服务器的协议是ws+tsl  试了很多方法还是连不上是怎么回事  可以邮箱联系吗  luckytyga@163.com

**Comment by elsadeny** [comment]
> > > > > > > > @ShuoHuang inbound uses http and autoProxyConfigurationEnabled is false. This global mode is fine. If it is changed to true, pac is configured properly, socks cannot be used for inbound, what is the reason?
> > > > > > > 
> > > > > > > 
> > > > > > > Have you solved this problem? Which startup method is exposed?
> > > > > > 
> > > > > > 
> > > > > > give up
> > > > > 
> > > > > 
> > > > > Can you ask me how to configure it under http? It has been adjusted for a long time and it is about to collapse. Can you help me with how you configure it in packettunnel?
> > > > 
> > > > 
> > > > If you can go, you can try to optimize the running memory. Kitsunebi is a very well optimized app. It is said that this app is PacektTunnel supported by v2ray. If not, give up at the end. The 15M running memory limit is caused by the system card. Dead.
> > > 
> > > 
> > > What we are doing now is to optimize the memory of go. However, I am stuck at the end of the packet tunnel and cannot continue, and I can’t find the reason. There are not many lines of code in the packet tunnel, but I can’t find the problem for several days. Yes, then I am really speechless, and it is difficult to debug with v2ray-core in extension. So I would like to ask you how to adjust the http inbounds before. If you can have the code for packettunnel, I would really appreciate it. [570499253@qq.com](mailto:570499253@qq.com) . This is my mailbox and qq. I would really appreciate any help.
> > 
> > 
> > [https://github.com/xxf098/go-tun2socks-build ](https://github.com/xxf098/go-tun2socks-build)
> > https://github.com/duanhai/Tun2socks-PacketTunnelDemo
> 
> The server's protocol is ws+tsl. I tried many methods and still can't connect. What's the matter, can I contact you by [email luckytyga@163.com](mailto:luckytyga@163.com)

Did you managed to make the app work with ws+tsl please let me know

**Comment by imfaker** [comment]
sorry, I have not slove this problem. &nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "v2ray/v2ray-core"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月30日(星期一) 中午11:28
收件人:&nbsp;"v2ray/v2ray-core"<v2ray-core@noreply.github.com&gt;;
抄送:&nbsp;"饕餮"<570499253@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [v2ray/v2ray-core] YouTube iOS客户端无法播放视频及内存泄漏的问题 (#1341)





         
@ShuoHuang inbound uses http and autoProxyConfigurationEnabled is false. This global mode is fine. If it is changed to true, pac is configured properly, socks cannot be used for inbound, what is the reason?
  
Have you solved this problem? Which startup method is exposed?
  
give up
  
Can you ask me how to configure it under http? It has been adjusted for a long time and it is about to collapse. Can you help me with how you configure it in packettunnel?
  
If you can go, you can try to optimize the running memory. Kitsunebi is a very well optimized app. It is said that this app is PacektTunnel supported by v2ray. If not, give up at the end. The 15M running memory limit is caused by the system card. Dead.
  
What we are doing now is to optimize the memory of go. However, I am stuck at the end of the packet tunnel and cannot continue, and I can’t find the reason. There are not many lines of code in the packet tunnel, but I can’t find the problem for several days. Yes, then I am really speechless, and it is difficult to debug with v2ray-core in extension. So I would like to ask you how to adjust the http inbounds before. If you can have the code for packettunnel, I would really appreciate it. 570499253@qq.com . This is my mailbox and qq. I would really appreciate any help.
  
https://github.com/xxf098/go-tun2socks-build 
 https://github.com/duanhai/Tun2socks-PacketTunnelDemo
  
The server's protocol is ws+tsl. I tried many methods and still can't connect. What's the matter, can I contact you by email luckytyga@163.com
  
Did you managed to make the app work with ws+tsl please let me know
