### ISSUE TITLE
只要一上https://blog.csdn.net/ 就accept4: too many open files

### ISSUE THREAD

**Issue by tarkky** [v2ray/v2ray-core#1344]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v2ray 3.50
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
x64 vmware 虚机运行 Lede 17路由器+透明代理+chinadns自动分流，服务器vps是debian 9.3 
采用vmess websocket + TLS方式。

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
通过lede路由器的机器只要上https://blog.csdn.net/，v2rayerror.log生成大量的
2018/10/29 11:21:22 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12345: accept4: too many open files
网站不能访问。
目前看，没发现其他网站有同样情况。
移动设备通过bifrostV通过4G网络可以访问
4) 你期待看到的正确表现是怎样的？

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:
{
    "log": {
        "access": "/var/log/v2ray/access.log",
        "error": "/var/log/v2ray/error.log",
        "loglevel": "warning"
    },
    "inbound": {
        "port": #########,
        "listen": "127.0.0.1",
        "protocol": "vmess",
        "settings": {
            "udp": true,
            "clients": [
        {
          "id": "#########",
          "level": 1,
          "alterId": 64,
          "email": "LEDE"
        },
        {
          "id": "#########",
          "level": 1,
          "alterId": 64,
          "email": "#########"
        },
        {
          "id": "#########",
          "level": 1,
          "alterId": 64,
          "email": "#########"
        },
        {
          "id": "c#########",
          "level": 1,
          "alterId": 64,
          "email": "#########"
        },
        {
          "id": "#########",
          "level": 1,
          "alterId": 64,
          "email": "#########"
        },
        {
          "id": "#########",
          "level": 1,
          "alterId": 64,
          "email": "#########"
        },
        {
          "id": "#########",
          "level": 1,
          "alterId": 64,
          "email": "#########"
        },
        {
          "id": "#########",
          "level": 1,
          "alterId": 64,
          "email": "#########"
        },
        {
          "id": "#########",
          "level": 1,
          "alterId": 64,
          "email": "#########"
        },
        {
          "id": "#########",
          "level": 1,
          "alterId": 64,
          "email": "#########"
        },
        {
          "id": "#########",
          "level": 1,
          "alterId": 64,
          "email": "no1"
        },
        {
          "id": "#########",
          "level": 1,
          "alterId": 64,
          "email": "no2"
        },
        {
          "id": "#########",
          "level": 1,
          "alterId": 64,
          "email": "no3"
        },
        {
          "id": "#########",
          "level": 1,
          "alterId": 64,
          "email": "no4"
        },
        {
          "id": "#########",
          "level": 1,
          "alterId": 64,
          "email": "no5"
        },
        {
          "id": "#########",
          "level": 1,
          "alterId": 64,
          "email": "no6"
        },
        {
          "id": "#########",
          "level": 1,
          "alterId": 64,
          "email": "no7"
        },
        {
          "id": "#########",
          "level": 1,
          "alterId": 64,
          "email": "no8"
        },
        {
          "id": "#########",
          "level": 1,
          "alterId": 64,
          "email": "no9"
        },
        {
          "id": "#########",
          "level": 1,
          "alterId": 64,
          "email": "no10"
        }
        ]
        },
        "streamSettings": {
            "network": "ws"
        }
    },
    "outbound": {
        "protocol": "freedom",
        "settings": {}
    },
    "outboundDetour": [
        {
            "protocol": "blackhole",
            "settings": {},
            "tag": "blocked"
        }
    ],
    "routing": {
        "strategy": "rules",
        "settings": {
            "rules": [
                {
                    "type": "field",
                    "ip": [
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "203.0.113.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10"
                    ],
                    "outboundTag": "blocked"
                }
            ]
        }
    }
}

客户端配置:

{
    "log": {
	"access": "/var/log/v2rayaccess.log",
	"error": "/var/log/v2rayerror.log",
    "loglevel": "warning"
    },
    "inbound": {
        "port": #########,
        "protocol": "dokodemo-door",
        "settings": {"followRedirect": true}
    },
    "outbound": {
        "tag": "proxy",
        "protocol": "vmess",
        "settings": {
            "vnext": [
                {
                    "address": "#########",
                    "port": 443,
                    "users": [
                        {
                            "id": "#########",
                            "security": "auto",
                            "alterId": 64,
                            "level": 1,
                            "email": "LEDE"
                        }
                        
                    ]
                }
            ]
        },
    
	"streamSettings": {
	"network": "ws",
	"wsSettings": {
       	    "path": "/websocket"
	    },
	"security": "tls",
	"tlsSettings": {
	    "serverName": "#########",
		"allowInsecure": true
	    }

	},
	"mux": {"enabled": true}
},
    "outboundDetour": [
        {
            "protocol": "freedom",
            "settings": {},
            "tag": "direct"
        }
    ],
    "routing": {
        "strategy": "rules",
        "settings": {
            "rules": [
                {
                    "type": "field",
                    "domain": [
                        "gc.kis.scr.kaspersky-labs.com"
                    ],
                    "outboundTag": "direct"
                },
                {
                    "type": "chinasites",
                    "outboundTag": "direct"
                },
                {
                    "type": "field",
                    "ip": [
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "203.0.113.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10"
                    ],
                    "domain": [
                        "geosite:cn"
                    ],
                    "outboundTag": "direct"
                },
                {
                    "type": "chinaip",
                    "outboundTag": "direct"
                }
            ]
        }
    }
}
}

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

服务器端无错误日志

客户端错误日志:

2018/10/29 11:44:09 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:12345: accept4: too many open files
7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

访问日志都正常。类似如下日志
2018/10/29 19:45:47 tcp:source IP:38944 accepted tcp:8.8.8.8:53 
2018/10/29 19:45:47 tcp:source IP:38448 accepted tcp:23.48.201.97:80 

8) 其它相关的配置文件（如 Nginx）和相关日志。
服务器端采用233blog一键脚本，websocket+tls方式
9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

v2ray正常。其它网站访问正常。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

没有其它问题。

请预览一下你填的内容再提交。

**Comment by miy4mori** [comment]
可以尝试在`/etc/systemd/system/v2ray.service`文件中的`[Service]`节加入以下配置
```
; Limit the number of file descriptors; see `man systemd.exec` for more limit settings.
LimitNOFILE=1048576
```
然后执行`sudo systemctl daemon-reload`和`sudo systemctl restart v2ray`

**Comment by VictoriaRaymond** [comment]
https://github.com/shadowsocks/shadowsocks/issues/488
