### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by FatChou** [v2ray/v2ray-core#1345]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
3.51
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
1、通过 gomobile bind --target=ios 编译出core.framework，
2、在APP extension里调用StartInstance(@"protobuf", configData)，configData是config.json
编译后的framework提供的条用方法不多，StartInstance看上去可以传入本地配置
3、尝试创建Config实例，并调用xxX_Unmarshal传入config.json。再通过创建的Config实例New一个Instance再 start。调用xxX_Unmarshal时候报错unexpected EOF。确定传入的json是正确的。
尝试2、3两种后，都不能获取正确结果。
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
1、unexpected EOF
2、proto: can't skip unknown wire type 7
等错误，会导致APP Extension进程挂掉
4) 你期待看到的正确表现是怎样的？
正确启动服务，返回StartInstance实例
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
{
    "log": {
        "access": "log_access",
        "error": "log_error",
        "loglevel": "warning"
    },
    "inboundDetour": [{
        "domainOverride": [
            "http",
            "tls"
        ],
        "port": 1086,
        "listen": "127.0.0.1",
        "protocol": "socks",
        "settings": {
            "auth": "noauth",
            "udp": true
        }
    }],
    "outboundDetour": [{
        "protocol": "freedom",
        "settings": {
            
        },
        "tag": "direct"
    },
    {
        "protocol": "blackhole",
        "settings": {
            
        },
        "tag": "block"
    }
    ],
    "dns": {
        "servers": [
            "localhost",
            "1.1.1.1"
        ]
    },
    "inbound": {
        "port": 1080,
        "listen": "127.0.0.1",
        "protocol": "http",
        "settings": {
            
        }
    },
    "outbound": {
        "protocol": "shadowsocks",
        "settings": {
            "servers": [{
                "method": "chacha20",
                "port": port,
                "password": "123",
                "address": "ip"
            }]
        },
        "mux": {
            "concurrency": 8,
            "enabled": false
        },
        "tag": "proxy"
    },
    "policy": {
        "levels": {
            "0": {
                "uplinkOnly": 0,
                "connIdle": 120,
                "downlinkOnly": 0,
                "handshake": 4
            }
        }
    },
    "routing": {
        "settings": {
            "rules": [
                
            ],
            "domainStrategy": "IPIfNonMatch"
        },
        "strategy": "rules"
    }
}

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
    暂无
```

客户端配置:

```javascript
    // 在这里附上客户端配置
    暂无
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
    暂无
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
    暂无
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
    暂无
```

8) 其它相关的配置文件（如 Nginx）和相关日志。
暂无
9) 如果 V2Ray 无法启动，请附上 `--test` 输出。
暂无
通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。
目前还无法启动
通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by Args** [comment]
嗨 请问有解决方案吗
