### ISSUE TITLE
多端口问题

### ISSUE THREAD

**Issue by changjiangblog** [v2ray/v2ray-core#1346]
如果多个用户共用一个端口，但是uuid不同，那么会降低网速吗？VPS 是100M的带宽，如果4个人UUID不同，但是共用一个端口，并且同时下载文件，那是否每个人的带宽就变成了25M？，如果是4个端口，每个用户的带宽可以变成100M吗？

**Comment by VictoriaRaymond** [comment]
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

此 Issue 会被立即关闭。
