### ISSUE TITLE
windows1809下多进程问题

### ISSUE THREAD

**Issue by changjiangblog** [v2ray/v2ray-core#1348]
windows版本：windows10专业版1809
打开任务管理器后发现存在多个名为：HTTP Auto Proxy Detection Worker Process的进程
![](http://ww1.sinaimg.cn/large/0079MVdAly1fwroq89umgj31ah05egmf.jpg)

且多次打开客户端后该进程仍会继续增加，打开一次客户端，该进程增加一个。
该进程描述如下：
![](http://ww1.sinaimg.cn/large/0079MVdAly1fwrosep9k9j30f40l6aaz.jpg)
最多的时候，我的电脑里有多达30个进程！
望解决。

**Comment by Chandler-Lu** [comment]
你这是v2ray在win下gui的问题吧。。

**Comment by VictoriaRaymond** [comment]
https://github.com/v2ray/v2ray-core/issues/1337

https://github.com/shadowsocks/shadowsocks-windows/issues/1979

**Comment by tlanyan** [comment]
Hello，我（应该）已经解决SS中的这个问题，你们可参考：[系统出现大量HTTP Auto Proxy Detection Worker Process](https://tlanyan.me/many-http-auto-proxy-detection-worker-processes/)
