### ISSUE TITLE
xxnet科学上网前一两年访问vimeo和tumblr都没问题，近一年都不能访问了，

### ISSUE THREAD

**Issue by bevay** [v2ray/v2ray-core#1351]
xxnet科学上网2017年之前访问vimeo和tumblr都没问题，近一两年都不能访问了，
google,facebook,twitter,youtube都能正常访问。
别的科学上网工具比如tunsafe，v2ray，都能正常访问，
但是这些经常失效，不跟xxnet一样稳定，
所以感觉很不方便。有哪位大佬知道怎么解决xxnet不能访问vimeo的问题吗?
![qq 20181102144928](https://user-images.githubusercontent.com/26117987/47897937-a9d84980-deae-11e8-97a2-a1d1854c075b.png)
![qq 20181102145008](https://user-images.githubusercontent.com/26117987/47897942-ae9cfd80-deae-11e8-994d-89623281d39b.png)
tumblr是不能正常登录进入，始终停留在首页位置
vimeo是提示封锁，进行机器人验证，验证成功会让你一直等，等到天荒地老

**Comment by DKestBK** [comment]
?????
