### ISSUE TITLE
gomobile bind --target=android github.com/v2ray-core

### ISSUE THREAD

**Issue by FatChou** [v2ray/v2ray-core#1353]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
4.0
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
github上的源码， 编译aar
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
gomobile: go build -buildmode=c-shared -o=/var/folders/dz/s6p42lmd62x7d7sk4h06h1z40000gn/T/gomobile-work-363127100/android/src/main/jniLibs/armeabi-v7a/libgojni.so gobind failed: exit status 2
gobind
core_android.c:365:1: error: redefinition of 'Java_core_InboundHandlerConfig_getTag'
core_android.c:291:1: note: previous definition is here
core_android.c:539:1: error: redefinition of 'Java_core_OutboundHandlerConfig_getTag'
core_android.c:465:1: note: previous definition is here
core_android.c:558:1: error: redefinition of 'Java_core_OutboundHandlerConfig_getExpire'
core_android.c:453:1: note: previous definition is here
core_android.c:573:1: error: redefinition of 'Java_core_OutboundHandlerConfig_getComment'
core_android.c:445:1: note: previous definition is here
4) 你期待看到的正确表现是怎样的？
正确编译出arr
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
```

客户端配置:

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by l619534951** [comment]
你好，请问最终编译出来了嘛？我也是一样的错误信息，没头绪，看别人的安卓项目不是直接构建的，有点奇怪呀
