### ISSUE TITLE
4.0的inbounds应该怎么用?

### ISSUE THREAD

**Issue by c16ee5a6** [v2ray/v2ray-core#1356]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V2Ray 4.0 (Po)

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
Chrome+Socks

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
除启动信息外日志无其他信息，也不能访问网页，好像没有数据进到core一样。
系统是windows10x64 1803

4) 你期待看到的正确表现是怎样的？
能够通过代理访问网页。

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
outbound只是用了freedom所以没有服务器配置
```

客户端配置（不可用版）:

```javascript
{
  "log": {
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 1080,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {}
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}
```

客户端配置（可用版）:

```javascript
 {
  "log": {
    "loglevel": "warning"
  },
  "inbound": {
    "port": 1080,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {}
  },
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    无
```

客户端错误日志:

```javascript
V2Ray 4.0 (Po) 20181101
A unified platform for anti-censorship.
2018/11/04 09:27:26 [Warning] v2ray.com/core: V2Ray 4.0 started
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    无
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by jinyu121** [comment]
同发现此问题。目前只能inbounds用原来的拆开方案，outbounds可以合起来写。
另
https://github.com/v2ray/v2ray-core/blob/master/release/config/vpoint_socks_vmess.jso 里面也没有将inbound合写成inbounds。
更新文档+更新demo请求

**Comment by cherrot** [comment]
确认，4.0按最新文档编写后并没有bind端口。未来试用文档能否区分版本发布？

**Comment by VictoriaRaymond** [comment]
请试用4.0.2

**Comment by c16ee5a6** [comment]
4.0.2测试可用。

**Comment by DarienRaymond** [comment]
文档就不分版本了，偷懒不想维护多版本体系。现在的文档适用于4.1
