### ISSUE TITLE
geosite 建议添加GFW 列表

### ISSUE THREAD

**Issue by wittyneko** [v2ray/v2ray-core#1365]
既然自带了路由处理，大多数人也只需要gfw列表能访问，为什么不添加到geosite列表。

**Comment by Rucc1** [comment]
参考：https://github.com/gfwlist/gfwlist/blob/master/COPYING.txt 

gfwlist 是 LGPL 开源协议，v2ray 是 MIT 协议，故不能在本项目中引入。

**Comment by Cwek** [comment]
可以试试这个方案，在白话版看见的。
https://github.com/ToutyRater/V2Ray-SiteDAT
这个有gfw的列表。

**Comment by MittWillson** [comment]
不妨提供支持外部URL方式引用并设定定期更新怎么样，just like go package
