### ISSUE TITLE
小白问题，v2ray是怎么把数据伪装成微信视频数据包的，具体怎么实现的呢？

### ISSUE THREAD

**Issue by onloner2012** [v2ray/v2ray-core#1367]
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

此 Issue 会被立即关闭。

If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2ray/discussion/issues) first.

This issue will be closed immediately.

**Comment by Rucc1** [comment]
https://github.com/v2ray/v2ray-core/blob/master/transport/internet/headers/wechat/wechat.go

**Comment by onloner2012** [comment]
非常感谢啊
