### ISSUE TITLE
snap安装v2ray-core后没可执行权限

### ISSUE THREAD

**Issue by jing2uo** [v2ray/v2ray-core#1369]
安装：sudo snap install v2ray-core --edge
版本：v2ray-core          4.2              611   edge      v2ray

/snap/v2ray-core/611/command-v2ctl.wrapper: 4: exec: /snap/v2ray-core/611/bin/v2ctl: Permission denied

ls -alht /snap/v2ray-core/current/bin 
-rw-r--r-- 1 root root  385 Nov  8 05:16 config.json
-rw-r--r-- 1 root root 4.5M Nov  8 05:16 geoip.dat
-rw-r--r-- 1 root root 206K Nov  8 05:16 geosite.dat
-rw-r--r-- 1 root root  15M Nov  8 05:16 v2ctl
-rw-r--r-- 1 root root  13M Nov  8 05:16 v2ray

**Comment by jing2uo** [comment]
是我用错了嘛…
没找到wiki简单说一下snap安装的应该怎么玩

**Comment by Cwek** [comment]
权限不足？

**Comment by jing2uo** [comment]
> 权限不足？

默认确实没有x权限噢，snap这个文件夹是只读的，我也没法手动给它权限。
虽然我自己现在下zip包手动搞定了，但snap部分应该是没法用的状态？

**Comment by jing2uo** [comment]
另外可以ci加个deb嘛？咱现在system文件都写了，打个包更方便安装

**Comment by kslr** [comment]
建议你提交一个PR，要不然短期内不太容易实现。

**Comment by xiaokangwang** [comment]
我并没有在V2Ray的代码中发现和snap相关的内容。因此估计想提PR也是有点困难的。。。

然后 https://snapcraft.io/v2ray-core 这里的发布源也是最近没有活跃的 Raymond 控制的，暂时联系不到。

**Comment by dragonxi** [comment]
（挖坟

试试 sudo snap install v2ray-core --classic
（原本的 --edge 是为了安装最新的稍微不稳定版本，
增加 --classic 是因为默认状态下安装的snap package会有很多安全限制和较低操作权限，
使用 --classic 可以给v2ray-core更多的系统操作权限）

**Comment by jing2uo** [comment]
> （挖坟
> 
> 试试 sudo snap install v2ray-core --classic
> （原本的 --edge 是为了安装最新的稍微不稳定版本，
> 增加 --classic 是因为默认状态下安装的snap package会有很多安全限制和较低操作权限，
> 使用 --classic 可以给v2ray-core更多的系统操作权限）

多谢回复，试过了还是不可以呢。应该是 snap 打包部分有点地方没处理好，我在项目里也没找到相关的代码…

**Comment by kslr** [comment]
这个发布已经放弃

**Comment by zhhuabj** [comment]
可以试试:
sudo apt install build-essential snapd
sudo snap install --classic snapcraft
mkdir v2ray-core && cd v2ray-core
snapcraft init
wget https://raw.githubusercontent.com/v2ray/ext/master/snap/snapcraft.yaml -O snap/snapcraft.yaml
sed -i 's/^grade: stable/grade: devel/g' snap/snapcraft.yaml
sed -i 's/^confinement: strict/confinement: devmode/g' snap/snapcraft.yaml
#add the following lines into snapcraft.yaml after the line 'unzip v2ray.zip -d /tmp/v2ray/'
        chmod +x /tmp/v2ray/v2ray
        chmod +x /tmp/v2ray/v2ctl
snapcraft
sudo snap install ./v2ray-core_4.2_amd64.snap --dangerous --devmode
