### ISSUE TITLE
[ERROR]Trace/breakpoint trap

### ISSUE THREAD

**Issue by benhon2008** [v2ray/v2ray-core#137]
![error](https://cloud.githubusercontent.com/assets/12547424/15111251/6fd522fa-1618-11e6-83c9-e56b023a9779.jpg)

**Comment by v2ray** [comment]
可能是你的 VPS 的问题，详见这篇文章：http://william.shallum.net/random-notes/32-bit-golang-trace-breakpoint-trap-modify_ldt-enosys

解决方案是运行下面的命令：

```
echo 1 > /proc/sys/kernel/modify_ldt
```

**Comment by benhon2008** [comment]
@v2ray 好像我跟链接里的PO主的情况有点不一样……

`
[root@localhost ~]# uname -a
Linux localhost.localdomain 2.6.32-042stab108.5 #1 SMP Wed Jun 17 20:20:17 MSK 2015 i686 i686 i386 GNU/Linux
[root@localhost ~]# strace /usr/bin/v2ray/v2ray
execve("/usr/bin/v2ray/v2ray", ["/usr/bin/v2ray/v2ray"], [/* 21 vars */]) = 0
modify_ldt(1, {entry_number:7, base_addr:0x8575c3c, limit:1048575, seg_32bit:1, contents:0, read_exec_only:0, limit_in_pages:1, seg_not_present:0, useable:1}, 16) = -1 EPERM (Operation not permitted)
--- SIGTRAP {si_signo=SIGTRAP, si_code=SI_KERNEL, si_value={int=3076332496, ptr=0xb75d1bd0}} ---
+++ killed by SIGTRAP +++
Trace/breakpoint trap
[root@localhost ~]# ls /proc/sys/kernel/mod*
/proc/sys/kernel/modprobe  /proc/sys/kernel/modules_disabled
[root@localhost ~]#
`

没有 /proc/sys/kernel/modify_ldt  -_-''

**Comment by benhon2008** [comment]
VPS是OpenVZ的，我描述了下碰到的状况，然后SP的回复如下：
> Client:
> Few days ago, I updated the program for a high version and it is doesn't work any more, then rollback program to earlier version that can working before. But, console output the error information as same as the program high version. I don't know what happened.
> debug info:
> [root@localhost ~]# strace /usr/bin/v2ray/v2ray
> execve("/usr/bin/v2ray/v2ray", ["/usr/bin/v2ray/v2ray"], [/* 21 vars */]) = 0 modify_ldt(1, {entry_number:7, base_addr:0x8575c3c, limit:1048575, seg_32bit:1, contents:0, read_exec_only:0, limit_in_pages:1, seg_not_present:0, useable:1}, 16) = -1 EPERM (Operation not permitted)
> --- SIGTRAP {si_signo=SIGTRAP, si_code=SI_KERNEL, si_value={int=3076332496, ptr=0xb75d1bd0}} ---
> +++ killed by SIGTRAP +++
> Trace/breakpoint trap

> Staff:
> Hello,
> Looks like you would have to use a KVM VPS in order to run this software.
> 
> Thank you.

但是我以前用起来是正常的，升级到1.11.x就开始报错了……

**Comment by benhon2008** [comment]
Solved after reinstall OS.
