### ISSUE TITLE
最新版（4.2）在heroku上部署成功，但无法访问网页。

### ISSUE THREAD

**Issue by jlzsss** [v2ray/v2ray-core#1371]
报错信息如下：
2018/11/09 09:00:49 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://*****.herokuapp.com/): 503 Service Unavailable > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by lgy5** [comment]
建议不要在herokuapp上部署了
