### ISSUE TITLE
为什么4.3的版本 我服务器上删了配置文件，重新更新还是旧版的配置

### ISSUE THREAD

**Issue by huangshayang** [v2ray/v2ray-core#1372]
https://github.com/v2ray/v2ray-core/issues/1362
不是说新版就行了吗

**Comment by VictoriaRaymond** [comment]
自带的配置文件只是示例，需要怎么的配置请自行修改。

**Comment by huangshayang** [comment]
> 自带的配置文件只是示例，需要怎么的配置请自行修改。

那啥时候可以自带的配置可以更新为最新的
