### ISSUE TITLE
无法安装v4.3版本

### ISSUE THREAD

**Issue by JackyNiu** [v2ray/v2ray-core#1373]
[root@vultr ~]# bash go.sh
Installing V2Ray v4.3 on x86_64
Downloading V2Ray.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   608    0   608    0     0    582      0 --:--:--  0:00:01 --:--:--   582
100 11.2M  100 11.2M    0     0   143k      0  0:01:20  0:01:20 --:--:--  288k
Extracting V2Ray package to /tmp/v2ray.
Archive:  /tmp/v2ray/v2ray.zip
  inflating: /tmp/v2ray/config.json  
   creating: /tmp/v2ray/doc/
  inflating: /tmp/v2ray/doc/readme.md  
  inflating: /tmp/v2ray/geoip.dat    
  inflating: /tmp/v2ray/geosite.dat  
   creating: /tmp/v2ray/systemd/
  inflating: /tmp/v2ray/systemd/v2ray.service  
   creating: /tmp/v2ray/systemv/
  inflating: /tmp/v2ray/systemv/v2ray  
  inflating: /tmp/v2ray/v2ctl        
 extracting: /tmp/v2ray/v2ctl.sig    
  inflating: /tmp/v2ray/v2ray        
 extracting: /tmp/v2ray/v2ray.sig    
  inflating: /tmp/v2ray/vpoint_socks_vmess.json  
  inflating: /tmp/v2ray/vpoint_vmess_freedom.json  
cp: cannot stat ‘/tmp/v2ray/v2ray-v4.3-linux-64/v2ray’: No such file or directory
Failed to copy V2Ray binary and resources.

**Comment by rosebe** [comment]
使用新版脚本：https://github.com/v2ray/v2ray-core/blob/master/release/install-release.sh 试一试

**Comment by JackyNiu** [comment]
@rosebe  太谢谢你了，已经搞定。
