### ISSUE TITLE
文件修改时间显示2010年1月1日

### ISSUE THREAD

**Issue by shenyiakng** [v2ray/v2ray-core#1375]
![v](https://user-images.githubusercontent.com/13936073/48391211-8fb92980-e740-11e8-9b06-73d164871e7b.png)
4.0版本开始压缩包内文件日期均显示2010.01.01，不过不影响使用。

**Comment by VictoriaRaymond** [comment]
正常。Bazel生成的文件好像就这样了，没什么动力修复。
