### ISSUE TITLE
More outbound load-balancing/picking mechanisms

### ISSUE THREAD

**Issue by KillingJacky** [v2ray/v2ray-core#1378]
The reason why people have multiple servers out of the WALL is, the network condition is changing constantly, so we're struggling on choosing the fastest one. In most cases, we don't care about the network throughput at all because all oversea VPSs provided huge throughput.

So Round-Robin picking mechanism makes less sense, what we really need is to select the best one (e.g. the fastest one to view youtube video or the one with lowest latency) at the current time. Could you guys please provide an outbound picking mechanism based on the estimation of the target server? Simply the ping latency, further the real loading time of a particular target like google.com.

For me I have 4 ss servers oversea, but I find out that the condition of them changes all the time, maybe this is due to the route shifting of the ISP, I don't know. But the influence on me is that I have to change the target server manually. That's a really annoying thing. I have been using COW for now because it hits the most parts of my requirements but I like the flexibility of v2ray! And I would like to deploy an inland forward server based on v2ray, hope you guys put this feature on your list, thanks in advance!

**Comment by moviefuns** [comment]
Thank you. I need this feature. When some server been blocked, how to smartly find the fast and available server from multi outbound servers is important, or some app without retry mechanism could be in a dead end.

**Comment by nicholascw** [comment]
Issue transferred.
