### ISSUE TITLE
A outbound of load balancing

### ISSUE THREAD

**Issue by Cwek** [v2ray/v2ray-core#1380]
可能有一些外部工具用于实现出口的负载平衡，但希望能在V2Ray里面实现这个功能从而方便配置，而且outbound好像支持proxySettings参数来指向其他outbound作为出口。

我建议提供三种选择模式，每个外出的链接根据选择模式由选择器选出一个作为出口
1.等概率，列出一堆作为outbound的数组，然后每次外出链接建立时随机选出一个。
2.按比例，列出一个以0.01~1的数字为键，outbound的tag为值的对象数组，键的和为1。每次外出链接建立时根据前几次按比例随机抽选。
3.轮盘式，列出一堆作为outbound的数组，然后每次外出链接建立时轮流选出一个，循环使用。

同时建立一个固定出口机制，一个特定目的地址和端口为唯一标记，第一次建立时记下选中的出口，之后每次建立同一个标记的链接刷新接触时间和分配相同的出口，直到超过特定时间或出口无法建立（链接出错）时消除该记录，重新选择出口。

以上为我的建议。

**Comment by ivandeex** [comment]
please keep this open, stale bot

**Comment by 20NE** [comment]
很有必要
