### ISSUE TITLE
Support graceful reloading

### ISSUE THREAD

**Issue by lsylsy2** [v2ray/v2ray-core#1381]
Necessary for multi users, and a easy way to implement https://github.com/v2ray/Planning/issues/4 .
软重启是实现多用户增加/删除，同时不影响平稳使用的很重要需求，同时如果支持了软重启，那么运行时管理用户API的需求也可基本满足

**Comment by Shihira** [comment]
upvote
同需要这个功能

**Comment by zmaplex** [comment]
需要这个功能
