### ISSUE TITLE
传出代理支持http/socks

### ISSUE THREAD

**Issue by fbi007130** [v2ray/v2ray-core#1383]
我的电脑在一个地方，有一个翻墙的代理，就是一个直接的http代理，但不排除有监控，同时我有一个境外的v2ray服务，想通过这个http代理走到我的v2ray上，这样既能确保我数据的安全同时也能避免直接暴露这个v2ray服务给gfw。

**Comment by hanazaki05** [comment]
https://github.com/v2ray/v2ray-core/pull/1813
Thanks `flyxl`, http outbound has been merged
