### ISSUE TITLE
DomainOverride加入QUIC支持

### ISSUE THREAD

**Issue by DarienRaymond** [v2ray/v2ray-core#1385]
From v2ray-core created by [liberal-boy](https://github.com/liberal-boy) : v2ray/v2ray-core#834  

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
3.6

虽然目前QUIC还未被大规模部署，Google旗下大部分网站已经启用QUIC，导致现有的DomainOverride无法满足部分domain规则分流的需求，建议DomainOverride加入QUIC支持。

**Comment by testcaoy7** [comment]
我想要
QUIC传输层（现在已经正式成为HTTP/3了）
