### ISSUE TITLE
关于CPU使用率的问题

### ISSUE THREAD

**Issue by cnperi** [v2ray/v2ray-core#139]
这是我的cpu的使用率图表。我设定的是每8小时restart一次。最后一次restart是我关闭了shadowsocks的udp后重启的，cpu使用率仍稳定上升。
![linode665507](https://cloud.githubusercontent.com/assets/10166311/15138453/8923c52c-16c2-11e6-9dee-6aa98e026364.png)

**Comment by v2ray** [comment]
如果你用的是 1.12.7，请升级到 1.12.8。如果是其它版本，请附上版本号和配置文件。

**Comment by cnperi** [comment]
就是1.12.7，更新为1.12.8后问题解决。
