### ISSUE TITLE
扩充远程控制 API 的功能

### ISSUE THREAD

**Issue by CatMe0w** [v2ray/v2ray-core#1390]
远程 API 很酷，但还可以进一步改善。

1. 让 v2ctl 能够操作 HandlerService
现在，v2ctl 已经能够操作 StatsService。如果能够用它来操作 HandlerService，远程控制 V2Ray 的难度将大大降低。这对非 Go 项目（使用 PHP 或 Node 开发的面板等）将可能很有帮助。

2. 平滑更换 Inbound/Outbound
通过 HandlerService 可以增删传入传出代理，如果能更换掉主 inbound/outbound，就能做到平滑的更换服务器了。这可以改善客户端侧的使用体验，不必通过粗暴地结束进程来更换服务器了。

**Comment by tqrj** [comment]
我想使用PHP来实现v2ray的远程控制，实在是不知道如何下手

**Comment by ix64** [comment]
> 我想使用PHP来实现v2ray的远程控制，实在是不知道如何下手

API使用的是grpc，使用任何而语言都可以调用的都是可以的
php的话可以参考 https://grpc.io/docs/quickstart/php/
