### ISSUE TITLE
建议：官方推行统一的配置二维码标准

### ISSUE THREAD

**Issue by DarienRaymond** [v2ray/v2ray-core#1392]
From v2ray-core created by [pipilupipixia](https://github.com/pipilupipixia) : v2ray/v2ray-core#1139  

如题。现在不同的客户端使用不同的标准（已经至少有两套），因此售卖面板就需要给不用的客户端适配多种标准，这对于v2ray的整个生态链无疑是不利的。
建议官方推行统一的二维码配置标准，并尽可能简单（如base64整个outbound的json配置部分）。

**Comment by zhuxiaoxi** [comment]
确实应该统一一下，希望二维码或链接可以尽可能的简短。当前流行的方案都是把备注信息放在了里面被编码了，导致很长。感觉ss的一种编码方式比较好，把节点备注放在协议最后面用#分割。

**Comment by IrineBrunner** [comment]
能不能一个模块，一个二维码。多扫几次码，然后拼凑起来成一个完整的配置文件。

**Comment by GavinZhengOI** [comment]
@IrineBrunner 
多个二维码在售卖面板当然没什么大问题。
但是如果考虑到用户之间的信息传输呢?
用户之间传递二维码就很麻烦了啊

**Comment by jiuqianyuan** [comment]
什么时候能统一好啊，分享的时候老是要手动更改算法 alterid什么的

**Comment by Cwek** [comment]
最简单的方法就是将json配置文件去除格式后用base64序列化，然后导入的时候允许解析软件要合并的第一层键值对，因为最核心的就是outbound的字段，例如routing等就不一定需要导出。

**Comment by VictoriaRaymond** [comment]
Closing this issue in favor of #1487.
