### ISSUE TITLE
建议将路由中的outboundTag改为数组实现更加可控的多服务器负载均衡。

### ISSUE THREAD

**Issue by cjjdaq** [v2ray/v2ray-core#1395]
当前很多人都拥有多节点，而v2ray用了tls后，对于负载均衡配置比较麻烦。特别是h2，希望将路由中的outboundTag改为数组实现更加可控的多服务器负载均衡。以下是一些建议。

{
  "strategy": "rules",
  "settings": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "domain": [
          "baidu.com",
          "qq.com"
        ],
        "outboundTag": ["server1","server2"],
        "outboundtype":round/random/rts
        "timeout":600

      }
    ]
  }
}
outboundTag:一个数组，数组内每一个元素是一个标识,当存在多个元素时，强制负载均衡。单元素时outboundtype与timeout无效。
outboundtype：round为轮询,random为随机，rts为高可用（最小ping值）。当为rts时，忽略timeout设置，强制为0（默认值为round）
timeout：会话超时，单位秒。0为关闭，当大于0时启用四层会话保持，首次轮询or随机，后续在设定的时间内会话保持。超时后从新轮询or随机再继续会话保持。（默认值为0）

**Comment by HisenZhang** [comment]
> > 负载均衡的话应该实现在应用协议而不是传输协议？比如VMess的vnext配置
> 
> 站在用户的角度看，只要活动服务器在列表中随机挑选就可以了。当然，不知道是否能够开发以及难度有多大了。

其实除了随机, 也可以让用户设置调度的权重. 因为多VPS的时候, 月流量限制不一定相同.
