### ISSUE TITLE
功能请求：路由规则可以增加url匹配吗

### ISSUE THREAD

**Issue by DarienRaymond** [v2ray/v2ray-core#1398]
From v2ray-core created by [523860169](https://github.com/523860169) : v2ray/v2ray-core#1256  

目前，路由只能对域名、端口、ip等进行代理，针对的也是GFW的屏蔽策略，但是像网站主动屏蔽中国ip，或者网站内部分内容对中国IP不可见，就有点缺乏灵活，只能对整个域名进行代理。
比如Apple Store的国际版就屏蔽了中国ip，返回404，而访问中国版就正常
https://itunes.apple.com/us/app/qq/id444934666?mt=8
https://itunes.apple.com/cn/app/qq/id444934666?mt=8
以上两个链接在代理后都能打开，但是不代理的情况下，上面404，下面正常
所以只要代理itunes.apple.com/us/就可以了

**Comment by rufengsuixing** [comment]
https无法嗅探路径，只能到域名为止，除非装证书搞中间人

**Comment by rhjdvsgsgks** [comment]
类似的需求，有些视频网站要求只能某些地方播放某些视频，实际上只有解析部分对位置有限制，希望可以添加类似rewrite的方法，把解析部分让远程服务器完成，解析结果返回本地，本地直连解析出来的服务
