### ISSUE TITLE
在 features.dns.Client 中加入返回 dns.Msg/[]byte 的查询函数

### ISSUE THREAD

**Issue by eycorsican** [v2ray/v2ray-core#1400]
我的项目 [go-tun2socks](https://github.com/eycorsican/go-tun2socks) 整合了 V2Ray 作为代理层，但因为是直接处理 TCP/UDP 流量，所以还是会有 DNS 污染，返回不合适 IP 的问题。

V2Ray 最近版本支持 DNS 按域名来分服务器查询，如果把这个功能也整合进 `go-tun2socks` 的话就可以比较有效解决 DNS 污染问题。

但目前 V2Ray 的 DNS client 只提供返回 []net.IP 的接口，而 `go-tun2socks` 需要的是 DNS 回复的 UDP payload，把 net.IP 封进一个 dns.Msg 中似乎会很麻烦，所以能不能提供直接返回 dns.Msg 的接口？

**Comment by YoulianBoshi** [comment]
thinks

**Comment by VictoriaRaymond** [comment]
新增加了两个interface: [IPv4Lookup](https://github.com/v2ray/v2ray-core/blob/master/features/dns/client.go#L17)和IPv6Lookup。在拿到dns.Client之后，需要断言它是否实现了这两个interface，然后再进行相应类型的查询。
