### ISSUE TITLE
在 Dispatcher 中对 DNS 流量进行嗅探并使用内置的 DNS 客户端来分域名解析

### ISSUE THREAD

**Issue by eycorsican** [v2ray/v2ray-core#1401]
普遍对客户端使用的方式都是 socks inbound 或 http inbound，这时并不会有 DNS 请求进来，但也有其它的使用场景，比如在移动端上用 tun2socks 等方式全局转发 UDP 流量，在路由器上用 dokodemo-door 做透明代理（后者没实践过不太确定工作方式），就会有 DNS 请求从 socks inbound  或者其它地方进入到 Dispatcher，这时如果在 Dispatcher 中对 DNS 请求进行嗅探并对相应域名用内置 DNS 客户端来解析的话，可以较大程度上解决 DNS 的一些问题，不需要任何外部程序（如 dnsmasq）的加持。

在一些情况下，domainOverride 也可以解决 DNS 问题，但也只限于 http/tls 流量。

另外这样做的一个好处是可以加速 DNS 请求，因为是跟 Router 用的同一个 DNS 缓存，很多时候可以直接返回缓存中的结果。

我在自己项目上做了实践，工作得还可以：https://github.com/eycorsican/go-tun2socks/blob/master/proxy/v2ray/proxy.go

**Comment by ToutyRater** [comment]
附议！
我在 https://github.com/v2ray/discussion/issues/24 也有 DNS 相关的提议，但看起来 @eycorsican 的想法更加可行，这样可以解决 DNS 的一些问题。期待添加这个功能。

**Comment by eycorsican** [comment]
然后就可以在路由里面像这样把相应流量路由过去吗？

```json
{
  "type": "field",
  "network": "udp",
  "port": 53,
  "protocol": ["dns"],
  "outboundTag": "dns_outbound"
}
```

**Comment by VictoriaRaymond** [comment]
`protocol`是嗅探出来的所以不能用，只用"udp"+端口应该可以了吧

**Comment by eycorsican** [comment]
我想得没错的话你的意思应该是匹配了 udp + port 的流量到了 `dns_outbound` 后如果不能把数据解析为 DNS 请求或者解析后发现请求类型不是 A、AAAA，就再次 Dispatch 到其它 outbound?

**Comment by VictoriaRaymond** [comment]
嗯，差不多

**Comment by VictoriaRaymond** [comment]
已在 4.15 中加入 DNS outbound。
