### ISSUE TITLE
支持 DNS over TCP

### ISSUE THREAD

**Issue by eycorsican** [v2ray/v2ray-core#1403]
因为 VMess 依靠可靠传输协议，对于要发送到代理服务器的 DNS 请求，如果可以使用 TCP 的话似乎会比较好，因为不需要重传，一般来说代理服务器处理 DNS 请求的速度都很快，UDP 或 TCP 都没太大差异

**Comment by YangtseSu** [comment]
DNS over HTTPS?
DNScrypt?

**Comment by YangtseSu** [comment]
这些dns技术都会导致国内的网站访问慢（解析慢或者cdn），但是基本可以杜绝dns污染。
是否可以增加策略，对于国内的网站采用国内的dns解析。

**Comment by Cwek** [comment]
迂回的话，将core的DNS设给自设的DNS，然后用这个DNS来做DNS over X的工作，例如pdnsd就支持over TCP的。

**Comment by kslr** [comment]
目前已经支持dot还有tcp的需求吗

**Comment by rhjdvsgsgks** [comment]
> 目前已经支持dot还有tcp的需求吗

能否给个配置的例子？翻了manual没找到，也没有搜到什么相关的
