### ISSUE TITLE
关于日志功能的一点建议

### ISSUE THREAD

**Issue by hzlmy2002** [v2ray/v2ray-core#1406]
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

此 Issue 会被立即关闭。

If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2ray/discussion/issues) first.

This issue will be closed immediately.
    在一般情况下，v2ray在用了nginx来转发ws的时候v2ray的access.log中记录的全都是127.0.0.1，需要把nginx配置成透明代理才能显示原始ip，虽然也可以通过对应时间的方法来查，不过很不方便，不知道哪个人用了多少流量在访问什么东西。
    联想到现阶段的email只被用来统计流量使用情况，因此可以考虑在access.log里面采用email+ip的方法来生成日志，可以用用户策略来控制此项功能是否开启（当然也可以直接默认开启最方便）。这个功能在多人使用一台服务器的时候尤其重要。

**Comment by Rucc1** [comment]
> 在一般情况下，v2ray在用了nginx来转发ws的时候v2ray的access.log中记录的全都是127.0.0.1，需要把nginx配置成透明代理才能显示原始ip，虽然也可以通过对应时间的方法来查，不过很不方便，不知道哪个人用了多少流量在访问什么东西。

https://v2ray.com/chapter_00/01_versions.html#20171222-v34

**Comment by hzlmy2002** [comment]
但是一个人的ip地址可能有多个，并且人和ip地址无法一一对应，并不如email直观。

**Comment by Rucc1** [comment]
建议对第二个问题提交一个新 issue

**Comment by VictoriaRaymond** [comment]
Duplicated to https://github.com/v2ray/discussion/issues/65

**Comment by joviqiao** [comment]
支持，我很需要这个功能。。
