### ISSUE TITLE
什么时候一键安装脚本才能自动用新的配置文件？

### ISSUE THREAD

**Issue by huangshayang** [v2ray/v2ray-core#1407]
什么时候一键安装脚本才能自动用新的配置文件？4.4的版本可以吗

**Comment by Rucc1** [comment]
https://github.com/v2ray/v2ray-core/issues/1372#issuecomment-437340581

**Comment by huangshayang** [comment]
> [#1372 (comment)](https://github.com/v2ray/v2ray-core/issues/1372#issuecomment-437340581)

能不能直接替换？不会手动填

**Comment by Rucc1** [comment]
请参考：https://github.com/v2ray/v2ray-core/commit/8c12fb6ff1866e10224b140725943aefd3171fc8
此 commit 已更新默认配置文件
