### ISSUE TITLE
json: cannot unmarshal array into Go struct field Config.inbound of type conf.InboundDetourConfig

### ISSUE THREAD

**Issue by daiaji** [v2ray/v2ray-core#1408]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V2Ray 4.3
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
浏览器
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
服务端报错
4) 你期待看到的正确表现是怎样的？
服务端正常用
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
{
	"log": {
		"access": "/var/log/v2ray/access.log",
		"error": "/var/log/v2ray/error.log"
	},
	"inbound": [{
			"port": 3939,
			"protocol": "vmess",
			"settings": {
				"clients": [{
					"id": "*",
					"alterId": 64
				}]
			},
			"streamSettings": {
				"network": "kcp"
			}
		},
		{
			"port": 18388,
			"protocol": "shadowsocks",
			"settings": {
				"method": "chacha20-ietf",
				"password": "*",
				"udp": true,
				"level": 1
			}
		},
		{
			"port": 3939,
			"protocol": "vmess",
			"settings": {
				"clients": [{
					"id": "*",
					"alterId": 64
				}]
			},
			"streamSettings": {
				"network": "ws"
			}
		}
	],
	"outbound": {
		"protocol": "freedom",
		"settings": {

		}
	},
	"transport": {
		"kcpSettings": {
			"congestion": true
		}
	}
}
```

客户端配置:

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
json: cannot unmarshal array into Go struct field Config.inbound of type conf.InboundDetourConfig
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

```
V2Ray 4.3 (Po) 20181109
A unified platform for anti-censorship.
main: failed to read config file: /etc/v2ray/config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/ext/tools/conf/command: failed to parse json config > v2ray.com/ext/tools/conf/serial: failed to read config file > json: cannot unmarshal array into Go struct field Config.inbound of type conf.InboundDetourConfig

 > exit status 255
```

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

现在的inbound不是简化成数组了吗？
这是数组啊

**Comment by dndnt** [comment]
> > 
> 
> ```js
>  “ inbound ”： [{
> 			 “ port ”： 3939，
> 			 “ protocol ”： “ vmess ”，
> 			 “ settings ”： {
> 				 “ clients ”： [{
> 					 “ id ”： “ * ”，
> 					 “ alterId ”： 64 
> 				}]
> ```
> 
> 这里的第一行应填填“inbounds”

LEDE的v2ray如果用"inbounds"和"outbounds"就会出错

**Comment by Cp0204** [comment]
坑爹啊… 建议文档里说明4.x配置相比3.x改了哪里…
