### ISSUE TITLE
关于日志中区别用户的一点建议

### ISSUE THREAD

**Issue by hzlmy2002** [v2ray/v2ray-core#1409]
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

此 Issue 会被立即关闭。

If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2ray/discussion/issues) first.

This issue will be closed immediately.
        由于流量转发，ip无法与每一个用户一一对应或用户拥有多个ip的问题，建议在日志access.log中由原来的纯ip改为用户email+ip的方式来区别每一个用户。

**Comment by VictoriaRaymond** [comment]
Duplicated to https://github.com/v2ray/discussion/issues/65
