### ISSUE TITLE
关于配合 HAProxy 负载均衡的建议

### ISSUE THREAD

**Issue by david9991** [v2ray/v2ray-core#1410]
我使用 VMess+TLS+HTTP/2+Haproxy 进行负载均衡，但发现一个问题。由于配置文件中 vnext 只配置一个地址，即 haproxy 服务的地址，如：127.0.0.1:7777。当 VMess+TLS+HTTP/2 连接被建立后，v2ray 将一直保持这个连接做为通道。而 Haproxy 是基于连接的负载均衡，因此在只有一个保持的连接的情况下 Haproxy 将无法实现真正的负载均衡。于是我想了一个办法，我把 127.0.0.1 在 host 文件中配置成 d1, d2, d3, d4, d5 这样5个域名，并将他们都配置到 vnext 中，欺骗 v2ray 这是个负载均衡（虽然 haproxy 是个真的负载均衡，只是 v2ray 只通过1个地址无法知道这一点）。结果真是在 haproxy 统计信息中看到了负载均衡的效果，current session 不再是 1。

但这样配置一个是非官方支持的，保不准哪天不好用了。再者这样配置文件也不好维护。可否实现一个支持泛域名的 vnext，比如 d[1-5].example.com，让 v2ray 轮询这个泛域名。或者添加一个参数告诉 v2ray 某一个单独的 vnext 地址背后其实是个负载均衡服务器，v2ray 可以连立一个多连接的连接池以满足负载均衡服务器所需的多连接。

**Comment by wd** [comment]
你这个思路不错，我也用负载均衡，不过我主要是使用故障转移功能，主 vps 不行的时候，自动切备用 vps。

我刚好前几天看到这个 http://xip.io/ ，感觉很适合你。{a,b,c}.127.0.0.1.xip.io  这样不用设置 host 了。

**Comment by betterdoitnow** [comment]
@wd 能大概说说你是如何实现故障转移功能的么？谢谢

**Comment by wd** [comment]
haproxy 的 server 可以设置为 backup，http://cbonte.github.io/haproxy-dconv/1.9/configuration.html#5.2-backup ，只有其他非 backup 的 server 都挂了才会启用。

**Comment by mgsqz** [comment]
> 
> 
> 你这个思路不错，我也用负载均衡，不过我主要是使用故障转移功能，主 vps 不行的时候，自动切备用 vps。
> 
> 我刚好前几天看到这个 http://xip.io/ ，感觉很适合你。{a,b,c}.127.0.0.1.xip.io 这样不用设置 host 了。

好像并不能泛解析
![1](https://user-images.githubusercontent.com/31202580/77278023-34665680-6cf9-11ea-939d-dd7c424dba19.JPG)

**Comment by wd** [comment]
> > 你这个思路不错，我也用负载均衡，不过我主要是使用故障转移功能，主 vps 不行的时候，自动切备用 vps。
> > 我刚好前几天看到这个 http://xip.io/ ，感觉很适合你。{a,b,c}.127.0.0.1.xip.io 这样不用设置 host 了。
> 
> 好像并不能泛解析
> ![1](https://user-images.githubusercontent.com/31202580/77278023-34665680-6cf9-11ea-939d-dd7c424dba19.JPG)

我试了似乎没问题，或许是你的 dns 服务器的问题，你可以试试看换一个。执行 nslookup 之后可以使用 server 命令指定 dns 服务器。

```
 nslookup 127.0.0.1.xip.io                                                                                                                                                                                                              (infra) 620ms  Mon Mar 23 11:29:01 2020
Server:         208.67.222.222
Address:        208.67.222.222#53

Non-authoritative answer:
Name:   127.0.0.1.xip.io
Address: 127.0.0.1
```

**Comment by mgsqz** [comment]
@wd 是的，我的dns服务器故障了，只解析部分地址
