### ISSUE TITLE
功能请求：增加Ｏｐｅｎｓｅｎｓｅ插件支持

### ISSUE THREAD

**Issue by speeedturtle** [v2ray/v2ray-core#1411]
Please describe the new feature you want in detail.
是否会考虑增加ｏｐｎｓｅｎｓｅ插件版本？

**Comment by VictoriaRaymond** [comment]
你需要去opnsense那边提交请求：https://github.com/opnsense/plugins

V2Ray有FreeBSD的build，直接下载安装包，或者从源代码编译都是可以的。
