### ISSUE TITLE
功能请求：我寻思既然开始精简配置 那就把某些没什么大用的选项加默认值吧 还有「settings 即使为空也要写」这种有碍观瞻的东西弄掉吧

### ISSUE THREAD

**Issue by daiaji** [v2ray/v2ray-core#1415]
https://github.com/v2ray/v2ray-core/issues/594#issuecomment-344580579
这边那个
http socks传入代理非要手动加 `"auth": "noauth"` 
默认值不就完事了
反正是本机或者局域网里设的代理谁没事还加认证

**Comment by nobody3u** [comment]
+1

**Comment by VictoriaRaymond** [comment]
socks的那个已经修了，settings会在下一版本修。
