### ISSUE TITLE
求助：服务器显示安装成功，v2ray客户端配置后无法连接

### ISSUE THREAD

**Issue by yuqizhao** [v2ray/v2ray-core#1418]
你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v4.5

你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
使用Chrome 通过VMess翻墙

你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
不知道..

你期待看到的正确表现是怎样的？
正常的上google

请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 443,
    "listen": null,
    "protocol": "vmess",
    "sniffing": null,
    "settings": {
      "auth": null,
      "udp": false,
      "ip": null,
      "clients": [
        {
          "id": "*******************",
          "alterId": 64,
          "email": "t@t.tt",
          "security": null
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "tlsSettings": {
        "allowInsecure": true,
        "serverName": null
      },
      "tcpSettings": null,
      "kcpSettings": null,
      "wsSettings": {
        "connectionReuse": true,
        "path": null,
        "headers": {
          "Host": "*********"
        }
      },
      "httpSettings": null
    }
  },
  "outbound": {
    "tag": null,
    "protocol": "freedom",
    "settings": null,
    "streamSettings": null,
    "mux": null
  },
  "inboundDetour": null,
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": null,
      "tag": "blocked"
    }
  ],
  "dns": null,
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": null,
      "rules": [
        {
          "type": "field",
          "port": null,
          "outboundTag": "blocked",
          "ip": [
            "----------------",
             "----------------",
            "----------------",
            "----------------",
            "----------------",
            "----------------",
                ......

            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "domain": null
        }
      ]
    }
  }
}

客户端配置

{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbound": {
    "port": *****,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "sniffing": {
      "enabled": true,
      "destOverride": [
        "http",
        "tls"
      ]
    },
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "127.0.0.1",
      "clients": null
    },
    "streamSettings": null
  },
  "outbound": {
    "tag": "agentout",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "*************",
          "port": 443,
          "users": [
            {
              "id": "*******************************",
              "alterId": 64,
              "email": "t@t.tt",
              "security": "auto"
            }
          ]
        }
      ],
      "servers": null
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "tlsSettings": {
        "allowInsecure": true,
        "serverName": null
      },
      "tcpSettings": null,
      "kcpSettings": null,
      "wsSettings": {
        "connectionReuse": true,
        "path": null,
        "headers": {
          "Host": "************"
        }
      },
      "httpSettings": null
    },
    "mux": {
      "enabled": false
    }
  },
  "inboundDetour": null,
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {
        "response": null
      },
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "blockout"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": null,
          "outboundTag": "direct",
          "ip": null,
          "domain": [
            "geosite:cn"
          ]
        },
        {
          "type": "field",
          "port": null,
          "outboundTag": "direct",
          "ip": [
            "geoip:cn"
          ],
          "domain": null
        },
        {
          "type": "field",
          "port": null,
          "outboundTag": "direct",
          "ip": [
            "----------------",
             "----------------",
            "----------------",
            "----------------",
            "----------------",
            "----------------",
                ......
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "domain": null
        }
      ]
    }
  }
}

请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 /var/log/v2ray/error.log 文件中。

服务器端错误日志:

[root@host ~]# /var/log/v2ray/error.log
-bash: /var/log/v2ray/error.log: No such file or directory
不知道是不是我运行错了....

客户端错误日志:
配置成功
***
启动服务(2018/11/18 23:44:56)......
V2Ray 4.5.0 (Po) 20181116
A unified platform for anti-censorship.
2018/11/18 23:44:56 [Warning] v2ray.com/core: V2Ray 4.5.0 started
2018/11/18 23:44:57 tcp:127.0.0.1:50377 accepted tcp:clients1.google.com:443 
2018/11/18 23:45:02 [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://域名/): 200 OK > websocket: bad handshake v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://域名/):  > dial tcp 67.230.179.57:443: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2018/11/18 23:45:06 [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://域名/): 200 OK > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2018/11/18 23:45:10 [Warning] [1822532267] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://域名/): 200 OK > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2018/11/18 23:45:10 tcp:127.0.0.1:50396 accepted tcp:clients1.google.com:443 
2018/11/18 23:45:14 [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://域名//): 200 OK > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2018/11/18 23:45:18 [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://域名/): 200 OK > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2018/11/18 23:45:23 [Warning] [1026679852] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://域名/): 200 OK > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2018/11/18 23:45:41 tcp:127.0.0.1:50417 accepted tcp:mtalk.google.com:5228 
2018/11/18 23:45:46 [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://域名/): 200 OK > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2018/11/18 23:45:50 [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://域名/): 200 OK > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2018/11/18 23:45:53 tcp:127.0.0.1:50435 accepted tcp:clients1.google.com:443 
2018/11/18 23:45:54 [Warning] [4087613244] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://域名/): 200 OK > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2018/11/18 23:45:57 [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://域名/): 200 OK > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2018/11/18 23:46:01 [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://域名//): 200 OK > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2018/11/18 23:46:05 [Warning] [2393475841] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://域名/): 200 OK > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2018/11/18 23:46:05 tcp:127.0.0.1:50456 accepted tcp:clients1.google.com:443 
2018/11/18 23:46:10 [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (域名/): 200 OK > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2018/11/18 23:46:14 [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://域名/): 200 OK > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2018/11/18 23:46:18 [Warning] [2877207853] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://域名/): 200 OK > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2018/11/18 23:46:32 tcp:127.0.0.1:50473 accepted tcp:clients2.google.com:443 
2018/11/18 23:46:36 [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://域名/): 200 OK > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2018/11/18 23:46:40 [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://域名/): 200 OK > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2018/11/18 23:46:44 [Warning] [1721719916] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://域名/): 200 OK > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
......
请附上访问日志。在 Linux 中，日志通常在 /var/log/v2ray/access.log 文件中。

[root@host ~]# /var/log/v2ray/access.log
-bash: /var/log/v2ray/access.log: No such file or directory
不知道是不是我运行错了....

**Comment by yuqizhao** [comment]
好像是centos端口没打开

**Comment by Chandler-Lu** [comment]
能不能自己写配置不要用一些乱七八糟的一件脚本

**Comment by 1061302569** [comment]
兄弟我出现了和你一样的情况，该怎么办

**Comment by yuqizhao** [comment]
我后来自己弄好了，具体忘了是哪里的问题，脚本是没有问题的，好像是客户端多配置了几次，抱歉帮不了你，论坛发帖等等专业的回复吧。。。

我本楚狂人 <notifications@github.com> 于 2019年7月8日周一 19:16写道：

**Comment by liuliqiang** [comment]
我也出现了这样的问题，最后定位发现是 ws 的 path 写错了。
修改之后就正常了。
