### ISSUE TITLE
入站http协议不定时提示“failed to read http request”

### ISSUE THREAD

**Issue by goxofy** [v2ray/v2ray-core#1419]
2018/11/19 09:03:26 [Warning] [559726457] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: failed to read http request > read tcp 10.10.41.33:33443->124.89.8.183:61671: read: connection reset by peer

这是运营商的锅还是http的锅

**Comment by VictoriaRaymond** [comment]
不影响使用的话可以不管。错误信息连接被重置。
