### ISSUE TITLE
能否客户端自定义完整的http的header，服务端自适应啊。现在貌似客户端和服务端要一致。今天测试http伪装并没有成功host并无改变

### ISSUE THREAD

**Issue by Echo21bash** [v2ray/v2ray-core#1425]
能否客户端自定义完整的http的header，服务端自适应啊。现在貌似客户端和服务端要一致。今天测试http伪装并没有成功host并无改变

**Comment by Rucc1** [comment]
> 今天测试http伪装并没有成功host并无改变

请提供详细的配置文件和抓包信息

> 能否客户端自定义完整的http的header 中

“完整的header”是指什么？
