### ISSUE TITLE
master 分支上近期的一些更改导致 DNS 解析失败

### ISSUE THREAD

**Issue by eycorsican** [v2ray/v2ray-core#1426]
调用 [`LookupIP()`](https://github.com/v2ray/v2ray-core/blob/master/features/dns/client.go#L13) 解析一个域名后出现以下错误：
```
lookup ip failed: v2ray.com/core/app/dns: returning nil for domain www.icloud.com > lookup www.icloud.com on [::1]:53: read udp [::1]:58619->[::1]:53: read: connection refused
```

确认能正常解析的 commit 是 `91227581e5`，出现问题的 commit 是 `4b885f577579`，问题出现在 iOS 上，这问题看起来有点奇怪我一下子也没什么头绪。

以下两种 DNS 配置均会出现这个问题，看来跟 DNS 配置无关：
```json
{
  "clientIp": "x.x.x.x",
  "servers": [
    "x.x.x.x",
    {
      "address": "x.x.x.x",
      "port": 53,
      "domains": [
        "xxxxxxx"
      ]
    }
  ]
}

{
  "servers": [
    "x.x.x.x",
    "x.x.x.x"
  ]
}
```

另外发现 DNS  配置里就算有配置服务器，也会加多个 localhost，是漏掉个检查条件了？还是个特性？（https://github.com/v2ray/v2ray-core/blob/master/app/dns/server.go#L97）

**Comment by VictoriaRaymond** [comment]
修了localhost的问题 ( 1cc3a4832de343e53c7993904add0bfc9c1764d5 )，随便加了两条log来判断问题的原因。看上去像是localhost的问题？

**Comment by eycorsican** [comment]
在 `4b885f577579` 上 cherry-pick 了 `1cc3a48`，解析域名出现以下错误：
```
v2ray.com/core/app/dns: failed to lookup ip for domain www.apple.com at server udp:223.5.5.5:53 > context deadline exceeded
```
```
v2ray.com/core/app/dns: returning nil for domain www.icloud.com > context deadline exceeded
```
第一条为 core 本身的日志，第二条为我直接调用 `LookupIP()` 返回的错误。

**Comment by VictoriaRaymond** [comment]
9cad27e9bdffa124dc81b1c42a9fd11bbe894983

现在应该可以了

**Comment by eycorsican** [comment]
Great！问题已经修复
