### ISSUE TITLE
客户端的开发是否已经停滞了？

### ISSUE THREAD

**Issue by handleft** [v2ray/v2ray-core#143]
无意中在这里看到的：V2Ray Roadmap : [Product Roadmap](https://docs.google.com/spreadsheets/d/1CmnPzUU8Z0cPOXUQcZRDuaZGii3bOTNv63W4gcwoBF8/pubhtml)

按照这个计划来看，客户端是否已经停了？

**Comment by Rememberli** [comment]
还是有个类似shadowsocks-windows 的gui客户端比较好，至少可以切换服务器啊

**Comment by v2ray** [comment]
暂时没有制作官方客户端的计划，请使用第三方客户端：https://www.v2ray.com/zh_cn/chapter_01/3rd_party.html
