### ISSUE TITLE
add qos 

### ISSUE THREAD

**Issue by cmmdwl** [v2ray/v2ray-core#1430]
希望添加qos设置 多人一起使用时候能够限制一个人最大速度能防止滥用

**Comment by cmmdwl** [comment]
没发现。

**Comment by Yaspee** [comment]
若上述 issue 中提出的`限制连接数和上下行带宽

`不是你期待的`qos`，请详细描述需要限制的具体内容

如果你不了解`带宽`的含义，请参考：
https://zh.wikipedia.org/wiki/带宽_(计算机)
