### ISSUE TITLE
添加纯udp的连接方式

### ISSUE THREAD

**Issue by cmmdwl** [v2ray/v2ray-core#1434]
可以参考openvpn的udp53绕开校园网审查
我目前的操作是udp隧道套v2 不过想原生支持udp
这个功能只需要伪装成dns查询即可
有些地方连dns查询都不需要伪装

**Comment by chanfried** [comment]
同问，v2ray反向代理，bridges和portals，支持UDP么？

**Comment by qazesz1** [comment]
我在用伪装成dns数据的vpn，再加v2ray的时候遇到了问题，见https://github.com/v2ray/discussion/issues/76
请问你有没有类似的使用情景，是否遇到这种情况？

**Comment by qiang-yu** [comment]
伪装成 dns 很容易被封杀的， 53 端口 udp 数据量很大会被监测

最有效的伪装就是  http，任何一个网络都不会阻止 http 的访问的，对于很多地方， udp 都是被严格 qos 控制，基本上处于不能用的状态，包括 dns 的 udp 都被严格控制了

建议用 websocket 协议，正宗的 http，不会被任何网络限制

**Comment by cmmdwl** [comment]
@qiang-yu 你说的没错，不过对于我所处的校园网环境下，夜间只有udp类型的数据包能被发出，因此，如果需要绕过校园网最好使用的就是openvpn ，对于国内来说，阿里云等服务器流量太贵了。。
如果将服务器买在国外，破墙自动就能识别到。。
因此我需要一个纯udp的加密信道，而v2是正好能实现加密和udp的不二之选
我目前的使用方法是udpray+v2，但是这个方法非常不友好，需要配置太多东西了

**Comment by kslr** [comment]
实际使用起来你会遇到很多麻烦，建议还是买4G网卡。

**Comment by cmmdwl** [comment]
> 实际使用起来你会遇到很多麻烦，建议还是买4G网卡。

@kslr 
你是不知道我这4g卡的要死要死的，宿舍片区内4g的-102db 在高点就没信号了，只能靠网线度日。。。
况且4g即使是校园卡最大100g限速，3g的速度imooc都无法正常使用了
然而我的国内阿里云+openvpn套路非常实用，夜间由于断网后qos自动被取消，反而效率更快

**Comment by hyxxsfwy** [comment]
建议尝试 QUIC 连接
