### ISSUE TITLE
日志文件支持自动增加后缀

### ISSUE THREAD

**Issue by Cat7373** [v2ray/v2ray-core#1436]
目前的日志文件配置如：

```json
{
  "log": {
    "access": "/var/log/v2ray/access.log"
  }
}
```

则每次启动的时候都会清空这个文件并重新写出到到这个文件中。

建议当这个文件存在时，可自动将这个文件重命名，如`/var/log/v2ray/access.log.20181126121314`。

或配置文件中的日志路径支持定义格式，如：

```json
{
  "log": {
    "access": "/var/log/v2ray/access.log.%y%M%d"
  }
}
```

这时根据通配符的规则自动创建对应名称的文件，如文件已存在，则不覆盖这个文件，而是以`append`的形式继续追加写出日志。

**Comment by Cat7373** [comment]
其实是想跟 nginx 一样一天一个日志的，emmm 仔细想想似乎也可以直接输出到 stdout，然后自己重定向到想要的地方

**Comment by VictoriaRaymond** [comment]
nginx应该也是用了log rotate的
