### ISSUE TITLE
socks代理给局域网共享socks协议问题

### ISSUE THREAD

**Issue by LsnmxNB** [v2ray/v2ray-core#1439]
无语解决了，v2ray-core的问题，android不能使用v2ray-core的socks协议1080端口，换1081 http能FQ了，真服了v2ray-core默认的socks协议1080端口，居然不能android使用
v2ray/v2ray-core#626
BoyuanJiang commented on 1 Mar
PC端可以使用socks协议，只需android中下载drony，使用SOCKS4a协议代理即可。

@DarienRaymond 感谢作者不厌其烦的关注解答。我刚刚排查到问题了。1、确定防火墙允许PC与手机的通信，相应的端口已打开并处于被监听状态2、v2ray客户端如果要让手机WIFI共享代理，在inbound的代理类型中必须使用http类型的代理。socks类型的，手机端无法直接使用。

总结一下：我原来的配置是这样的。将配置改为加粗的部分就正常了。
"inbound": {
"port": 8010,
"listen": "0.0.0.0",
"protocol": "socks", 这里改为http
"settings": {
"timeout": 0 下面4行全部删除
"auth": "noauth",
"udp": true,
"ip": "127.0.0.1",
"clients": null
},

配置成功
启动服务(2018/11/29 20:00:50)......
V2Ray 4.6.0 (Po) 20181122
A unified platform for anti-censorship.
2018/11/29 20:00:50 [Warning] v2ray.com/core: V2Ray 4.6.0 started
2018/11/29 20:00:54 tcp:10.0.0.108:42451 rejected v2ray.com/core/proxy/socks: unknown Socks version: 67
2018/11/29 20:00:54 [Info] [54501241] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: failed to read request > v2ray.com/core/proxy/socks: unknown Socks version: 67
2018/11/29 20:00:54 tcp:10.0.0.108:42452 rejected v2ray.com/core/proxy/socks: unknown Socks version: 67
2018/11/29 20:00:54 [Info] [4284493634] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: failed to read request > v2ray.com/core/proxy/socks: unknown Socks version: 67
2018/11/29 20:00:54 tcp:10.0.0.108:42453 rejected v2ray.com/core/proxy/socks: unknown Socks version: 67
2018/11/29 20:00:54 [Info] [2105275800] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: failed to read request > v2ray.com/core/proxy/socks: unknown Socks version: 67

**Comment by Cwek** [comment]
这个不能怪作者吧，因为大部分系统的代理只接受HTTP代理，socks代理是不支持的。

**Comment by Cwek** [comment]
android暂时已知能用socks的，有ss-android作者写的ProxyDroid，不过需要root而且很久不更新了。

**Comment by azzvx** [comment]
为啥不用代理转换工具？
socks5 转成 http(s)+socks5+ss
然后手机上直接能用ss的android版了，比设全局代理灵活的多了。
https://github.com/nadoo/glider
