### ISSUE TITLE
关于端口映射的疑问？

### ISSUE THREAD

**Issue by cnperi** [v2ray/v2ray-core#144]
看到v2ray提供端口映射的模式，那么应该能够实现dns的远程查询防止投毒。
我的想法：
本地dns查询-->本地端口-->远程服务器特定端口-->DNS服务器（比如8.8.4.4）
几个疑问：
1、通过v2ray的端口映射，本地端口和远程服务器端口之间的协议，是否是vmess或其他加密/混淆过的？能否防止gfw干扰？
2、这个协议是否支持UDP？在 https://www.v2ray.com/zh_cn/chapter_02/protocols/dokodemo.html 标明只支持tcp，但是在 https://www.v2ray.com/zh_cn/chapter_05/00_config/03_port_map.html 标明支持tcp和udp。
3、我的想法能否实现？

**Comment by v2ray** [comment]
1. 当从 VMess Outbound 传出的时候，是用 VMess 加密的；当从 Freedom 出的时候，是不加密的。
2. 支持，文档已更新。
3. 可以。只不过这个映射端口没有缓存，每次查询都会被传到远端的服务器，如果要缓存的话需要自己加一个 DNS 服务器。

**Comment by cnperi** [comment]
明白了，谢谢 @v2ray 的耐心。
顺便问一句，v2ray项目的透明代理，有开发时间表吗？（目前用的shadowsocks的ss-redir和ss-tunnel想试试v2ray）

**Comment by v2ray** [comment]
VPN 的功能会和手机端同步开发并完善，但还没有具体计划。

**Comment by cnperi** [comment]
收到，谢谢 @v2ray 。
