### ISSUE TITLE
QUIC 无法连接

### ISSUE THREAD

**Issue by david9991** [v2ray/v2ray-core#1440]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

v4.7

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

VMess+QUIC

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

v4.7 中配置 QUIC 后，完全无法连接。Wireshark 中只能看到1个请求包，3个应答的数据包，反反复复一直是这样。
配置我只是把  streamSettings 的 network 改成 "quic"，然后
```
"quicSettings": {
  "security": "none",
  "key": "",
  "header": {
    "type": "none"
  }
}
``` 

4) 你期待看到的正确表现是怎样的？

正常连接

**Comment by zeroricx** [comment]
可以连接 刚测试过

**Comment by david9991** [comment]
为啥呐，为啥呐。我其它啥都没改，只是改的 streamSettings 改成列子给的那样就不好使。
客户端是 macOS，服务端是 Alpine linux。和系统有关？

**Comment by cjjdaq** [comment]
检查下你本身网络udp的连通性呢

**Comment by david9991** [comment]
以前 KCP 是好用的，而且 Wireshark 的确是看到 UDP 包，只是发一个收三个，一会又发一个收三个，反复就一直这样。通应该是通的，只是不知道哪里出了问题。

**Comment by cjjdaq** [comment]
没加tls吗？

**Comment by david9991** [comment]
就按例子
```
"quicSettings": {
  "security": "none",
  "key": "",
  "header": {
    "type": "none"
  }
}
```
这样，文档上说会自动签发一个证书。
但我也在想这个证书的 Common Name 会是啥，是个自签证书还是 Letsencript。正常像 Caddy 签证书肯定是按域名走的，并通过验证的。这里没有配 Host 的地方，他这个「自动签发」的证书是怎么签的？文档最好能更新一下。我现在也是一头雾水。XD

**Comment by ShuoHuang** [comment]
发个完整配置呢

**Comment by wwqgtxx** [comment]
基本上是两个问题：
第一个服务端和客户端版本不一致，比如4.6.0和4.7.0的quic就不兼容
第二个问题就是`streamSettings`的`security`要设置成`none`才能正常工作（其实应该是要保证服务端和客户端一致，只不过我也没有试验过当服务器端设置为`tls`的时候会有什么结果）

**Comment by david9991** [comment]
这会儿又好了……难道是电信的 UDP 间歇性断流？
另外还有个问题，如果说 V2Ray 自动签发一个证书，那这个证书是如何校验的，难道是用 UUID 做为 CN 来校验吗？如果不是这样的，说明文档中说可以禁用 vmess 的加密，那又如何能防止中间人攻击呢？

**Comment by cjjdaq** [comment]
不过quic重连还是有问题，有时候不通了，必须要重启客户端才可以。

**Comment by dongxinb** [comment]
碰到一个奇怪的现象。
下载大文件，例如 https://hnd-jp-ping.vultr.com/vultr.com.100MB.bin。
第一次速度可以达到8M，取消。
第二次速度只能是2M，取消。
第三次速度只能是200K 了，取消。
第四次，一直提示正在连接。此时任何请求都不成功，必须要重启客户端才可以解决。

**Comment by lgcde** [comment]
@david9991 https://blog.csdn.net/dog250/article/details/80935534

**Comment by david9991** [comment]
@lgcde 有空学习一下。;)

**Comment by Gzxhwq** [comment]
这quic现在问题太大，重连是个问题，没有实用性了

**Comment by david9991** [comment]
重连的问题我倒是没注意到……目前还算稳定。

**Comment by RivenNero** [comment]
> 重连的问题我倒是没注意到……目前还算稳定。

请问你是怎么配置的, 我这里 `QUIC` 配置加密之后连接中断, 我提了一个 issue
[QUIC使用 aes-128-gcm 连接关闭](https://github.com/v2ray/v2ray-core/issues/1446)
难道是我配置文件写错了吗?

**Comment by david9991** [comment]
@RivenNero 我仅仅使用 "streamSettings": { "network": "quic"}，其它默认。

**Comment by david9991** [comment]
另外发现
```
"policy": {
    "levels": {
      "0": {
        "handshake": 4,
        "connIdle": 300,
        "uplinkOnly": 0,
        "downlinkOnly": 0,
        "statsUserUplink": false,
        "statsUserDownlink": false,
        "bufferSize": 0
      }
    },
    "system": {
      "statsInboundUplink": false,
      "statsInboundDownlink": false
    }
  }
```
这样好像速度可以快不少。只是试出来的，没有仔细研究过原理。XD

**Comment by testcaoy7** [comment]
我表示我这边QUIC工作一切正常
