### ISSUE TITLE
官方docker进行能否提供tags

### ISSUE THREAD

**Issue by wwqgtxx** [v2ray/v2ray-core#1441]
如题，现在官方的v2ray/official只有最新版本，这样在部署服务端的时候容易出现部署时间不一致导致的版本号之间不兼容，希望官方可以给该镜像加上tags，方便大家选择版本

**Comment by boris1993** [comment]
而且，latest也只是一个名字比较特殊的tag，并不能用来实现自动更新等功能，只有latest反倒会给用户造成困扰
[The misunderstood Docker tag: latest
](https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375)

**Comment by kslr** [comment]
在docker hub 可以简单修改参数实现
