### ISSUE TITLE
支持 GeoLite2 新数据库格式(MaxMind-DB)

### ISSUE THREAD

**Issue by Git-XiaoQin** [v2ray/v2ray-core#1443]
MAXMind现在只免费提供GeoLite2数据库，提供MaxMind-DB(.mmdb文件)、CSV格式下载。请问V2ray路由功能支持mmdb格式文件吗？

MaxMind-DB文件格式规范：http://maxmind.github.io/MaxMind-DB/
GeoLite2下载地址：https://dev.maxmind.com/geoip/geoip2/geolite2/
Golang解析实现：https://github.com/oschwald/geoip2-golang

**Comment by VictoriaRaymond** [comment]
这样有什么好处？你要解决什么问题？

**Comment by Git-XiaoQin** [comment]
> 这样有什么好处？你要解决什么问题？

RuleObject里面有个IP参数 https://www.v2ray.com/chapter_02/03_routing.html
> 一个数组，数组内每一个元素代表一个 IP 范围。当某一元素匹配目标 IP 时，此规则生效。有以下几种形式：

IP: 形如"127.0.0.1"。
CIDR: 形如"10.0.0.0/8".
GeoIP: 形如"geoip:cn"，必须以geoip:（小写）开头，后面跟双字符国家代码，支持几乎所有可以上网的国家。
特殊值："geoip:private" (V2Ray 3.5+)，包含所有私有地址，如127.0.0.1。
从文件中加载 IP: 形如"ext:file:tag"，必须以ext:（小写）开头，后面跟文件名和标签，文件存放在资源目录中，文件格式与geoip.dat相同标签必须在文件中存在。

根据IP归属国家，做流量分流

**Comment by Git-XiaoQin** [comment]
看到这个：https://github.com/v2ray/geoip
