### ISSUE TITLE
每次启动服务器会报个warning

### ISSUE THREAD

**Issue by teraStars** [v2ray/v2ray-core#1447]
1) 你正在使用哪个版本的 V2Ray？
都是4.7
2) 你的使用场景是什么？
在服务器上启动v2ray时，查看日志会出现。
3) 你看到的不正常的现象是什么？
在服务器上启动v2ray时，查看日志/var/log/v2ray/error.log会出现如下warning：

2018/12/02 02:25:49 [Warning] v2ray.com/core/transport/internet/websocket: failed to serve http for WebSocket > accept tcp 127.0.0.1:10000: use of closed network connection

4) 你期待看到的正确表现是怎样的？
没有这个warning。

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 10000,
      "listen": "127.0.0.1",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "******",
            "level": 1,
            "alterId": 233
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/test"
        }
      }
    },
    {
      "port": 10001,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "xxxxx",
            "level": 1,
            "alterId": 233
          }
        ]
      },
      "streamSettings": {
        "network": "kcp",
        "kcpSettings": {
          "mtu": 1350,
          "tti": 50,
          "uplinkCapacity": 8,
          "downlinkCapacity": 80,
          "congestion": false,
          "readBufferSize": 2,
          "writeBufferSize": 2,
          "header": {
            "type": "none"
          }
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked"
      }
    ]
  }
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript

2018/12/02 02:21:39 [Warning] v2ray.com/core/transport/internet/websocket: failed to serve http for WebSocket > acce
pt tcp [::]:10000: use of closed network connection
2018/12/02 02:21:39 [Warning] v2ray.com/core: V2Ray 4.7.0 started
2018/12/02 02:25:49 [Warning] v2ray.com/core/transport/internet/websocket: failed to serve http for WebSocket > acce
pt tcp 127.0.0.1:10000: use of closed network connection
2018/12/02 02:25:50 [Warning] v2ray.com/core: V2Ray 4.7.0 started
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

只要启动就会报这个warning。

8) 其它相关的配置文件（如 Nginx）和相关日志。
我用的caddy，配置如下：
mysite.site {
   gzip
   tls abc@gmail.com 
   root /var/www
  log /usr/local/caddy/caddy.log
  proxy /test localhost:10000 {
    websocket
    header_upstream -Origin
  }
   
}
www.mysite.site {
    redir https://mysite.site
}

请预览一下你填的内容再提交。

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!

**Comment by solerwell** [comment]
请问解决这个问题了么？我也出现了同样的问题
