### ISSUE TITLE
v2ray客户端不能运行

### ISSUE THREAD

**Issue by kevinlovo** [v2ray/v2ray-core#1450]
版本: V2Ray 4.3 (Po) 20181109
系统版本:Manjaro 18.0.0 Illyria Gnome
Kernel: x86_64 Linux 4.14.83-1-MANJARO

pamac 下载安装完,配置config.json后
在终端输入
>v2ray -config /etc/v2ray/config.json
出现:
>V2Ray 4.3 (Po) 20181109
>A unified platform for anti-censorship.
>main: failed to read config file: /etc/v2ray/config.json
> v2ray.com/core/main/json: failed to execute v2ctl to convert config file. 
>v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/ext/tools/conf/command: failed to parse json config 
> v2ray.com/ext/tools/conf/serial: failed to parse json config 
> v2ray.com/ext/tools/conf: invalid field rule 
> v2ray.com/ext/tools/conf: failed to parse domain rule: geosite:cn 
> v2ray.com/ext/tools/conf: failed to load geosite: CN 
> v2ray.com/ext/tools/conf: failed to open file: geosite.dat 
> open /usr/bin/geosite.dat: no such file or directory
 > exit status 255

chmod 777 /etc/v2ray
chmod 777 /etc/v2ray下所有文件
后,输出结果一样

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:
未知;使用网上分享的账号

客户端配置:

```javascript
    //{
  "inbound": {
    "port": 1080,
    "protocol": "socks",
    "settings": {
      "udp": true
    }
  },
  "outbound": {
    "mux": {
      "enabled": true
    },
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "",
          "port": 80,
          "users": [
            {
              "alterId": 0,
              "id": ""
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "security": "none",
      "wsSettings": {
        "path": "/ws"
      }
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "routing": {
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "domain": [
            "geosite:cn"
          ],
          "outboundTag": "direct",
          "type": "field"
        },
        {
          "ip": [
            "geoip:cn",
            "geoip:private"
          ],
          "outboundTag": "direct",
          "type": "field"
        }
      ]
    },
    "strategy": "rules"
  }
}
```

6)  请附上出错时软件输出的错误日志。
 `/var/log/没有v2ray文件夹

服务器端错误日志:

客户端错误日志:

```javascript
    //  `/var/log/没有v2ray文件夹
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
 `/var/log/没有v2ray文件夹
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。
>v2ray --test
>V2Ray 4.3 (Po) 20181109
>A unified platform for anti-censorship.
>main: failed to load config:  > v2ray.com/core/main/confloader/external: config file not readable > >open : no such file or directory

>/usr/bin/v2ray --test --config /etc/v2ray/config.json
>V2Ray 4.3 (Po) 20181109
>A unified platform for anti-censorship.
>main: failed to read config file: /etc/v2ray/config.json 
> v2ray.com/core/main/json: failed to execute v2ctl to convert config file. 
> v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/ext/tools/conf/command: failed to parse json config 
> v2ray.com/ext/tools/conf/serial: failed to parse json config 
> v2ray.com/ext/tools/conf: invalid field rule 
> v2ray.com/ext/tools/conf: failed to parse domain rule: geosite:cn 
> v2ray.com/ext/tools/conf: failed to load geosite: CN 
> v2ray.com/ext/tools/conf: failed to open file: geosite.dat 
> open /usr/bin/geosite.dat: no such file or directory
> exit status 255

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

>journalctl -u v2ray
>-- Logs begin at Fri 2018-11-30 23:26:00 CST, end at Sun 2018-12-02 22:38:02 CST. --
>-- No entries --

请预览一下你填的内容再提交。

**Comment by slanterns** [comment]
>open /usr/bin/geosite.dat: no such file or directory
确定它在吗

**Comment by InoriHeart** [comment]
蛮奇怪的 我用的原版 Arch 没这事

**Comment by kevinlovo** [comment]
> > 打开/usr/bin/geosite.dat：没有这样的文件或目录
> 
> 确定它在吗

查看了下,确实不在,我把/etc/v2ray/下的geoip.dat和geosite.dat复制到/usr/bin后就可以使用了...难道pamac安装好后不能直接使用,还需要自己手动再添加文件吗,这太麻烦了吧

**Comment by leo-mao** [comment]
遇到和楼主同意问题，折腾了一上午，一直以为是配置文件出错了，因为 `v2ray -test -config config.json`始终过不了，太坑了，感觉是aur源打包的人，忘记把geodata复制到/bin下了。

**Comment by ikzk** [comment]
也被坑了一把

**Comment by HungJovin** [comment]
把/etc/v2ray/下的geoip.dat和geosite.dat复制到/usr/bin后就可以使用了

**Comment by bryango** [comment]
这应该是 Arch 打包时的一点缺陷，参见 <https://bugs.archlinux.org/task/60943?project=5&string=v2ray>. 可通过设定环境变量：`V2RAY_LOCATION_ASSET=/etc/v2ray` 解决，如这样启动 v2ray:
```bash
V2RAY_LOCATION_ASSET=/etc/v2ray v2ray
```

**Comment by jdleung** [comment]
etc下面根本没有geoip.dat和geosite.dat这两文件，整部电脑都没有。homebrew和dmg安装都试过了

**Comment by zanxj** [comment]
> etc下面根本没有geoip.dat和geosite.dat这两文件，整部电脑都没有。homebrew和dmg安装都试过了

In /usr/bin/v2ray

**Comment by JackerooLiu** [comment]
我现在还在坑里，还没解决

**Comment by xinwf** [comment]
openwrt, /usr/bin下有这两个文件,依然报错, 小米路由器3

**Comment by pijh** [comment]
V2Ray 4.34.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.6 linux/amd64)
A unified platform for anti-censorship.
2021/02/26 02:46:54 [Info] v2ray.com/core/main/jsonem: Reading config: /etc/v2ray/config.json
main: failed to read config files: [/etc/v2ray/config.json] > v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to parse domain rule: geosite:category-ads > v2ray.com/core/infra/conf: failed to load geosite: category-ads > v2ray.com/core/infra/conf: failed to open file: geosite.dat > open /usr/bin/geosite.dat: no such file or directory

**Comment by pijh** [comment]
v2ray 启动不了，求大神解救

**Comment by zanxj** [comment]
> v2ray 启动不了，求大神解救

配置文件检查过了吗，命令：v2ray -config /usr/local/etc/v2ray/config.json -test （config.json 为默认配置文件）
