### ISSUE TITLE
SendingWorker.Flush & SendingWindow.Flush 实现可能有致命逻辑问题。

### ISSUE THREAD

**Issue by fanpei91** [v2ray/v2ray-core#1456]
```go
func (w *SendingWorker) Flush(current uint32) {
	w.Lock()

	if w.closed {
		w.Unlock()
		return
	}

	cwnd := w.firstUnacknowledged + w.conn.Config.GetSendingInFlightSize()
	if cwnd > w.remoteNextNumber {
		cwnd = w.remoteNextNumber
	}
	if w.conn.Config.Congestion && cwnd > w.firstUnacknowledged+w.controlWindow {
		cwnd = w.firstUnacknowledged + w.controlWindow
	}

	if !w.window.IsEmpty() {
		w.window.Flush(current, w.conn.roundTrip.Timeout(), cwnd)
		w.firstUnacknowledgedUpdated = false
	}

	updated := w.firstUnacknowledgedUpdated
	w.firstUnacknowledgedUpdated = false

	w.Unlock()

	if updated {
		w.conn.Ping(current, CommandPing)
	}
}
```
如果我没理解错，开启了拥塞控制，这里的 `cwnd` 变量值就是类似于 TCP 的能发送多少数据取决于 `min(cwnd, send wnd)` 的值, 只不过在 v2ray里，就是求两者之间最小的`远端主机可以接收的最大序列号`.

但是在调用如下函数里，`cwnd` 却被当成了真正意义上的 `max inflight size` 了, 而不是 `远端主机可以接收的最大序列号` 了。 因此，这里的 `maxInFlightSize` 的值会极大，所以会发送非常多不该发送出去的数据包。

```go
func (sw *SendingWindow) Flush(current uint32, rto uint32, maxInFlightSize uint32) {
	if sw.IsEmpty() {
		return
	}

	var lost uint32
	var inFlightSize uint32

	sw.Visit(func(segment *DataSegment) bool {
		if current-segment.timeout >= 0x7FFFFFFF {
			return true
		}
		if segment.transmit == 0 {
			// First time
			sw.totalInFlightSize++
		} else {
			lost++
		}
		segment.timeout = current + rto

		segment.Timestamp = current
		segment.transmit++
		sw.writer.Write(segment)
		inFlightSize++
		if inFlightSize >= maxInFlightSize {
			return false
		}
		return true
	})

	if sw.onPacketLoss != nil && inFlightSize > 0 && sw.totalInFlightSize != 0 {
		rate := lost * 100 / sw.totalInFlightSize
		sw.onPacketLoss(rate)
	}
}
```

所以用如下约束条件是有问题的：
```go
		if inFlightSize >= maxInFlightSize {
			return false
		}
```
或许应该改成：
```go
		if segment.Number > maxInFlightSize {
			return false
		}
```

v2ray 我拜读没多久，不知是否理解正确？

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!

**Comment by VictoriaRaymond** [comment]
Please keep this open. I will take a look but just don’t have time.

**Comment by k79e** [comment]
果然有数据包发送过多 乃至无限发包的问题. !!!!

**Comment by SekiBetu** [comment]
https://github.com/v2fly/v2ray-core/pull/168
