### ISSUE TITLE
v2ray 支持路由器openwrt系统吗？

### ISSUE THREAD

**Issue by sutun2008** [v2ray/v2ray-core#146]
如题

**Comment by tlze** [comment]
有人问过，不能，Openwrt没有go支持。

**Comment by v2ray** [comment]
由于 golang 的限制，暂不支持 MIPS 芯片的路由器，ARM 和 x86 是支持的。

**Comment by debiansid** [comment]
x86版本的只要按照golang就可以跑了？

**Comment by laosb** [comment]
@debiansid 不需要。只需要build出来的binary。

**Comment by v2ray** [comment]
如果你需要把 V2Ray 烧到 ROM 里，需要自己做一个 OpenWRT 的安装程序；如果不需要，就像在普通 Linux 上一样跑就行了。

**Comment by debiansid** [comment]
没有go环境,而且是trunk版本基于musl的,感觉不行吧

**Comment by debiansid** [comment]
root@openwrt-x86:/mnt/backup/v2ray-v1.13.1-linux-32# ./v2ray 
Trace/breakpoint trap

**Comment by bettermanbao** [comment]
mips32的openwrt路由目前交叉编译后，可以直接运行go 1.42的程序。
今天刚试了编译go写的kcptun，成功运行，只是性能比较堪忧。

**Comment by Portan** [comment]
有没有方法可以在openwrt上运行？因为需要在家庭路由器上部署，openwrt的支持非常需要

**Comment by debiansid** [comment]
Musl可以使用

**Comment by YangtseSu** [comment]
https://github.com/coolsnowwolf/lede/tree/master/package/lean/luci-app-v2ray-pro
