### ISSUE TITLE
周末新买的梅林路由器 Asuswrt-Merlin，连接V2ray超时

### ISSUE THREAD

**Issue by xifarm** [v2ray/v2ray-core#1460]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
   v2ray.com/core: V2Ray 4.7.3 started
   服务器端：V2Ray 4.7.0

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
   周末新买的路由器 Asuswrt-Merlin 当前版本 : 3.0.0.4.384_32799-gfe72567

  Android、Mac、Windows直连VPS的V2ray，没有问题，速度非常好。

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
     curl -x socks5://127.0.0.1:23456 google.com
     curl -x https://127.0.0.1:3333 google.com
     curl -x http://127.0.0.1:3333 google.com
    在路由器内，均超时。
   
4) 你期待看到的正确表现是怎样的？
    我希望能路由器V2ray翻墙

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
 {
  "log" : {
    "access": "/etc/v2ray/access.log",
    "error": "/etc/v2ray/error.log",
    "loglevel": "debug"
  },
  "inbounds": [{
    "port": 443,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "af25***9e259",
          "level": 1,
          "alterId":10
        }
      ]
    }
  }],
  "outbounds": [{
    "protocol": "freedom",
    "settings": {}
  },{
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  }],
  "routing": {
    "rules": [
      {
        "type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "blocked"
      }
    ]
  }
}
```

客户端配置:

```javascript
   {
  "log": {
     "access": "/tmp/mnt/sda1/v2ray/log/access.log",
        "error": "/tmp/mnt/sda1/v2ray/log/error.log",
    "loglevel" : "debug"
  },
  "inbound": {
      "port": 23456,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": true
      }
    },
  "inboundDetour":
  [{
         "port": 3333,
         "listen": "0.0.0.0",
         "protocol": "dokodemo-door",
         "settings": {
             "network": "tcp,udp",
             "followRedirect": true
         }
  }],
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "16****5",
          "port": 443,
          "users": [
            {
              "id": "af25***259",
              "alterId": 10,
              "security": "auto"
            }
          ]
        }
      ]
    },
    "streamSettings":
    {
      "network": "tcp",
      "security": "tls",
      "tlsSettings": { "allowInsecure": true }
    }
  },
  "policy": {
    "levels": {
      "0": {"uplinkOnly": 0}
    }
  }
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    无
```

客户端错误日志:

```javascript
    2018/12/06 04:23:54 [Info] v2ray.com/core/transport/internet/udp: failed to read UDP msg > read udp 127.0.0.1:23456: use of closed network connection
2018/12/06 04:23:54 [Info] v2ray.com/core/transport/internet/udp: failed to read UDP msg > read udp [::]:3333: use of closed network connection
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by jzdxeb** [comment]
路由器上log有吗？(/tmp/mnt/sda1/v2ray/log/access.log或者/tmp/mnt/sda1/v2ray/log/error.log)
配置--test过吗？

**Comment by Hardrain980** [comment]
Client的`"security": "tls"`改成`"security": "none"`，
`"tlsSettings": {}`移除掉。

**Comment by xifarm** [comment]
多谢大家了。

我在tg电报群找到ss科学上网插件了，10分钟配置一下就好了。

有类似问题的小伙伴，欢迎加我微信私下讨论： 21372550

再次谢谢大家。
