### ISSUE TITLE
在日志模块中提供类似 log.SetOutput() 的接口

### ISSUE THREAD

**Issue by eycorsican** [v2ray/v2ray-core#1461]
在 iOS 上调试程序看日志时，一般会用 macOS 上的 `Console` 应用，在代码里调用 NSLog/asl_log 就会把日志输出到 Console 上，这跟 Android 上输出到 Logcat 类似。

但直接在 iOS 上运行 Go 程序时，输出到 os.Stdout 的日志并不会出现在 `Console` 里，这时需要对日志做重定向。如果用 gomobile 编译程序的话，gomobile 自动做了这个 [操作](https://github.com/golang/mobile/blob/master/internal/mobileinit/mobileinit_ios.go)，不过 gomobile 做的这个操作只对 `log` 包 [默认的 logger](https://golang.org/src/log/log.go?#L73)  起作用，v2ray-core 创建了自己的 logger，所以需要自己做这个重定向操作才能让日志输出到 `Console`。

**Comment by VictoriaRaymond** [comment]
大概是这个样子： 9743380e2da31a8162b20773edccd2e37c10dbd1 ？

**Comment by eycorsican** [comment]
`isMobile()` 这样子判断感觉不太合适，而且对于 Android，gomobile 是直接对 os.Stdout 做了重定向所以没这个必要，就我所知目前只有 iOS 需要。

我觉得像 `internet. UseAlternativeSystemDialer()` 一样提供个 `log.UseAlternativeStdoutLogWriter()` 就可以，什么时候要用什么 logger 交给调用者判断就可以。

**Comment by VictoriaRaymond** [comment]
Gomobile对Android也有一个类似的[初始化操作](https://github.com/golang/mobile/blob/master/internal/mobileinit/mobileinit_android.go)，我不太清楚它具体干了什么。

`log.UseAlternativeStdoutLogWriter()` 可以通过[log.RegisterHandler](https://github.com/v2ray/v2ray-core/blob/master/common/log/log.go#L40) 来实现，即不加载app/log，直接写一个文件注册默认的log.Handler。

**Comment by eycorsican** [comment]
用 `log.RegisterHandler` 的话，好像就需要调用者去判断配置文件里是 file 还是 console 类型，还要处理 file logger 那一部分，涉及的东西有点多，就有点超出主题了。

当然要用它来实现的话是可行的。。

**Comment by VictoriaRaymond** [comment]
你需要的功能仅限于调试吧，调试的时候没有输出到file的情况吧。

**Comment by eycorsican** [comment]
我是希望 v2ray-core 可以针对这类情况有一个更优雅的解决方法，如果官方没打算针对这类情况提供支持的话这个 issue 可以关闭了。

我自己已经通过 Go 的编译条件为 ios target 另外提供一个 `CreateStdoutLogWriter()` 函数实现这个功能，但因为修改了 v2ray-core 的代码，实在算不上优雅。

**Comment by VictoriaRaymond** [comment]
那这样吧：30b5bffad4362dc7c5fa0226cc3f0bb748650fd5

**Comment by eycorsican** [comment]
我没来得及测试，不过看起来可以的，足够通用且用起来不会太麻烦
