### ISSUE TITLE
不能使用非网关设备作为透明代理

### ISSUE THREAD

**Issue by a13547** [v2ray/v2ray-core#1464]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    最新版
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
    透明代理部署在路由器上可以正常使用，但是把透明代理部署在局域网中的NAS上则不成功。已在网关中设置DNAT，将TCP流量定向至NAS设备的V2ray dokodemo-door端口，但是不能打开网页，浏览器一直在载入中。
4) 你期待看到的正确表现是怎样的？
V2ray如果作为透明代理，只能部署在路由器上吗？不可以部署在局域网中的其他设备上吗？如果可以的话，应当如何配置呢？配置文件应该是没有问题的，因为在路由器上透明代理可以正常使用，估计问题应该在iptables
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
ipset create custom hash:ip
iptables -t nat -N V2RAY
iptables -t nat -A V2RAY -d vps_ip -j ACCEPT
iptables -t nat -A V2RAY -d 192.168.0.0/16 -j ACCEPT
iptables -t nat -A V2RAY -d 0.0.0.0/8 -j ACCEPT
iptables -t nat -A V2RAY -d 10.0.0.0/8 -j ACCEPT
iptables -t nat -A V2RAY -d 127.0.0.0/8 -j ACCEPT
iptables -t nat -A V2RAY -d 169.254.0.0/16 -j ACCEPT
iptables -t nat -A V2RAY -d 172.16.0.0/12 -j ACCEPT
iptables -t nat -A V2RAY -d 224.0.0.0/4 -j ACCEPT
iptables -t nat -A V2RAY -d 240.0.0.0/4 -j ACCEPT
iptables -t nat -I PREROUTING -m set --match-set custom dst -p tcp -j DNAT --to-destination 192.168.50.2:8081
iptables -t nat -A V2RAY -p tcp -j DNAT --to-destination 192.168.50.2:8081
iptables -t nat -A PREROUTING -p tcp -j V2RAY
exit 0

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
```

客户端配置:

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by Cwek** [comment]
我试过可以，不过还需要路由器上的google地址段路由到你的透明网关上。

**Comment by a13547** [comment]
@Cwek 请问iptables应该如何配置呢？

**Comment by Cwek** [comment]
> @Cwek 请问iptables应该如何配置呢？

我也是按照教程上的基本来配制的，但那是给你的透明网关配置。

你的路由器需要用路由设置，对应Linux做的路由器的话，就添加”ip route replace <你要代理的地址段> proto static via <透明网关的地址>“

**Comment by Cwek** [comment]
另外非路由器的透明网关去截获需要代理的地址，是要用-t <nat|mangle>    -A PREROUTING 。
路由器做透明网关的话，就用-A OUTPUT
