### ISSUE TITLE
V2Ray 4.7.0 (Po) 在 Debian 上无法监听 inbounds 中不同协议的不同端口

### ISSUE THREAD

**Issue by VaslD** [v2ray/v2ray-core#1468]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

2018-12-07 通过 `bash <(curl -L -s https://install.direct/go.sh)` 安装的 V2Ray 4.7.0 (Po).

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

尝试设置 VMess 代理访问 Google 和 GitHub.

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

服务器设置文件中 `inbounds` 已填写多个代理时，第二个代理无法启动。错误为无法绑定至指定的端口。我尝试过非常多的端口，甚至交换第一个和第二个代理使用的端口，第二个代理端口绑定总是失败。

4) 你期待看到的正确表现是怎样的？

如果指定端口均没有在使用，两个代理均可以正常运行。这是升级之前的表现，唯一区别是升级之前使用 `inbound` 和 `inboundDetour` 配置。

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
{
    "log": {
        "error": "/var/log/v2ray/error.log",
        "loglevel": "warning"
    },
    "dns": {
        "servers": [
            "1.1.1.1",
            "8.8.8.8"
        ]
    },
    "inbounds": [
        {
            "tag": "VMess",
            "port": some_number,
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "some_client_ID",
                        "alterId": some_number
                    }
                ],
                "disableInsecureEncryption": true,
                "udp": true
            }
        },
        {
            "tag": "ShadowSOCKS",
            "port": some_number,
            "protocol": "shadowsocks",
            "settings": {
                "method": "aes-256-gcm",
                "password": "some_password",
                "ota": false,
                "network": "tcp,udp"
            },
            "streamSettings": {
                "network": "kcp"
            }
        }
    ],
    "outbounds": [
        {
            "tag": "Direct",
            "protocol": "freedom",
            "settings": {}
        },
        {
            "tag": "Blocked",
            "protocol": "blackhole",
            "settings": {}
        }
    ],
    "transport": {
        "kcpSettings": {
            "some_settings": some_value
        }
    }
}
```

客户端配置:

```javascript
    // 客户端未配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

<img width="481" alt="putty_2018-12-09_16-46-26" src="https://user-images.githubusercontent.com/3415065/49695297-ded56b80-fbd3-11e8-9700-a35de180820a.png">

客户端错误日志:

```javascript
    // 客户端未配置
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 服务器端未运行
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

仅开启第一个代理时的端口占用情况：

<img width="947" alt="putty_2018-12-09_17-04-14" src="https://user-images.githubusercontent.com/3415065/49695340-9a969b00-fbd4-11e8-8933-540338a95a2b.png">

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

见 6)

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

见 6)

**Comment by veekxt** [comment]
`"network": "tcp,udp"` and `"network": "kcp"` conflicting, `kcp` is UDP-based.

**Comment by VaslD** [comment]
@veekxt That explains everything. Thanks. I'll leave a full solution and close this issue.

如果有人遇到了相同问题，需要把 VMess 协议中的 UDP 监听去掉，并在 ShadowSOCKS 协议中设置为只监听 UDP. 示例服务器端配置如下：

```javascript

    "inbounds": [
        {
            "tag": "VMess",
            "port": some_number,
            "protocol": "vmess",
            "settings": {
                "clients": [
                    // User configurations.
                ],
                "disableInsecureEncryption": true
            }
        },
        {
            "tag": "ShadowSOCKS",
            "port": some_number,
            "protocol": "shadowsocks",
            "settings": {
                // User configurations.
                "network": "udp"
            },
            "streamSettings": {
                "network": "kcp"
            }
        }
    ]

```
