### ISSUE TITLE
客户端连不上服务端，报错如下

### ISSUE THREAD

**Issue by sutun2008** [v2ray/v2ray-core#147]
先说一下我的测试条件：０.5 core 256Mb内存  cents＿７＿x８６＿６４  openvz
错误如下：[Error]Faild to open tcp:131.121.7.9:38291:dial tcp 131.121.7.9:38291:connectex:A connection attempt faild because the connected party did not properly respond after a period of time,or established connection failed beacause connected host has failed to respond. 是哪个地方错了?

**Comment by v2ray** [comment]
请附上你服务器和客户端的配置文件。

**Comment by sutun2008** [comment]
俺把系统重新安装了一遍，下面是俺的安装步骤（注：131.121.7.9不是俺的真实ip）
将安装脚本上传至root目录
[root@lun ~]# chmod +x install-release.sh
[root@lun ~]#  ./install-release.sh
Updating software repo via yum.
Installing curl via yum.
Package curl-7.29.0-25.el7.centos.x86_64 already installed and latest version
Installing unzip via yum.
Package unzip-6.0-15.el7.x86_64 already installed and latest version
Downloading https://github.com/v2ray/v2ray-core/releases/download/v1.13/v2ray-linux-64.zip directly.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   595    0   595    0     0   1831      0 --:--:-- --:--:-- --:--:--  1836
100 2378k  100 2378k    0     0   328k      0  0:00:07  0:00:07 --:--:--  368k
Archive:  /tmp/v2ray/v2ray.zip
  inflating: /tmp/v2ray/v2ray-v1.13-linux-64/systemd/v2ray.service
  inflating: /tmp/v2ray/v2ray-v1.13-linux-64/systemv/v2ray
  inflating: /tmp/v2ray/v2ray-v1.13-linux-64/v2ray
  inflating: /tmp/v2ray/v2ray-v1.13-linux-64/vpoint_socks_vmess.json
  inflating: /tmp/v2ray/v2ray-v1.13-linux-64/vpoint_vmess_freedom.json
PORT:35186

**Comment by sutun2008** [comment]
执行了一下：
service v2ray start
显示：
Redirecting to /bin/systemctl start  v2ray.service

**Comment by sutun2008** [comment]
以下是centos7上的配置文件
{
  "port": 35186,
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "1b4ca6f6-f99b-4436-9fc7-5571f76d5c13",
          "level": 1,
          "alterId": 64
        }
      ]
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}

**Comment by sutun2008** [comment]
以下是客户端win7 64位配置文件

{
  "port": 1080,
  "log": {
    "access": ""
  },
  "inbound": {
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "131.121.7.9",
          "port": 35186,
          "users": [
            {
              "id": "1b4ca6f6-f99b-4436-9fc7-5571f76d5c13",
              "alterId": 64
            }
          ]
        }
      ]
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "port": "54-79",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "81-442",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "444-65535",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "domain": [
            "gc.kis.scr.kaspersky-labs.com"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        }
      ]
    }
  }
}

**Comment by sutun2008** [comment]
浏览器的设置及使用参考了：
V2Ray for Windows Client and Debian Server

双击  v2ray.exe  

浏览被封内容出现最顶部错误提示

**Comment by sutun2008** [comment]
找到原因了，防火墙的原因

**Comment by zddewe** [comment]
"找到原因了，防火墙的原因",啥问题咋，，解决的??

**Comment by v2ray** [comment]
应该是防火墙拒绝了要访问的端口

**Comment by wtlusvm** [comment]
@zddewe CentOS7系统自带Firewalld（除非是Minimal安装）。Firewalld默认区域是Public，而该区域默认只开放SSH和DHCPv6 Client服务，没有手动开启v2ray端口前当然无法使用
