### ISSUE TITLE
DigitalOcean使用QUIC或KCP无法访问Twitter等网站

### ISSUE THREAD

**Issue by liurui39660** [v2ray/v2ray-core#1472]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

`V2Ray 4.9.0 (Po) 20181212`

客户端和服务端相同。

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

测试用例：使用Chrome通过VMess代理访问Twitter。

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

简言之：在使用QUIC或KCP传输层配置时无法访问Twitter等网站。

具体测试流程如下：

首先清除客户端和服务端的`access.log`和`error.log`日志文件。

然后先后启动服务端和客户端的V2Ray。

在客户端的Chrome浏览器中输入`https://www.twitter.com/`并访问。

Chrome一直处在`Establishing secure connection...`

一段时间（约十余秒）后失败并显示如下信息：

```
This site can’t be reached

twitter.com took too long to respond.

Try:
Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics

ERR_TIMED_OUT
```

关闭客户端程序，结束。

4) 你期待看到的正确表现是怎样的？

可以正常打开Twitter。

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

我去掉了绝大多数可以去掉的内容，因此配置可能显得有些过度精简。

使用QUIC的场景：

服务器端配置:

```json
{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": "12150",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "3e97a5c6-0d40-45ed-97fb-c43f35ce1ee3"
          }
        ]
      },
      "streamSettings": {
        "network": "quic",
        "quicSettings": {
          "security": "aes-128-gcm",
          "key": "123",
          "header": {
            "type": "wechat-video"
          }
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}
```
没有任何修改

客户端配置:

```json
{
  "log": {
    "access": "D:\\V2Ray\\access.log",
    "error": "D:\\V2Ray\\error.log",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 1081,
      "listen": "127.0.0.1",
      "protocol": "http"
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "SERVER_ADDRESS",
            "port": 12150,
            "users": [
              {
                "id": "3e97a5c6-0d40-45ed-97fb-c43f35ce1ee3"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "quic",
        "quicSettings":{
          "security": "aes-128-gcm",
          "key": "123",
          "header": {
            "type": "wechat-video"
          }
        }
      }
    }
  ]
}
```
其中服务器地址被隐去，其余未修改

端口选1081是故意为之，因为1080端口被另一代理程序占用。

使用KCP的场景：

服务器端配置:

```json
{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": "12150",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "3e97a5c6-0d40-45ed-97fb-c43f35ce1ee3"
          }
        ]
      },
      "streamSettings": {
        "network": "kcp",
        "kcpSettings": {
          "mtu": 1350,
          "tti": 20,
          "uplinkCapacity": 5,
          "downlinkCapacity": 20,
          "congestion": false,
          "readBufferSize": 1,
          "writeBufferSize": 1,
          "header": {
            "type": "none"
          }
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}
```

没有任何修改

KCP的配置来自于<https://www.v2ray.com/chapter_02/transport/mkcp.html>

客户端配置:

```json
{
  "log": {
    "access": "D:\\V2Ray\\access.log",
    "error": "D:\\V2Ray\\error.log",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 1081,
      "listen": "127.0.0.1",
      "protocol": "http"
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "SERVER_ADDRESS",
            "port": 12150,
            "users": [
              {
                "id": "3e97a5c6-0d40-45ed-97fb-c43f35ce1ee3"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "kcp",
        "kcpSettings": {
          "mtu": 1350,
          "tti": 20,
          "uplinkCapacity": 5,
          "downlinkCapacity": 20,
          "congestion": false,
          "readBufferSize": 1,
          "writeBufferSize": 1,
          "header": {
            "type": "none"
          }
        }
      }
    }
  ]
}
```

服务器地址被隐去，除此外没有改动

KCP的配置来自<https://www.v2ray.com/chapter_02/transport/mkcp.html>

端口选1081是故意为之，因为1080端口被另一代理程序占用。

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

使用QUIC和使用KCP的错误日志几乎相同，因此这里只附上了使用QUIC时的日志。

服务器端错误日志:

```
2018/12/13 14:13:28 [Warning] v2ray.com/core: V2Ray 4.9.0 started
```

客户端错误日志:

```
2018/12/13 14:17:29 [Warning] v2ray.com/core: V2Ray 4.9.0 started
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

使用QUIC和使用KCP的访问日志十分类似，因此这里只附上了使用QUIC时的日志。

服务端访问日志:

```javascript

```

什么都没有

客户端访问日志:

```
2018/12/13 14:17:29 127.0.0.1:55568 accepted //capi.grammarly.com:443  
2018/12/13 14:17:33 127.0.0.1:55581 accepted //www.google-analytics.com:443  
2018/12/13 14:17:33 127.0.0.1:55578 accepted //twitter.com:443  
2018/12/13 14:17:33 127.0.0.1:55584 accepted //syndication.twitter.com:443  
2018/12/13 14:17:33 127.0.0.1:55587 accepted //pbs.twimg.com:443  
2018/12/13 14:17:33 127.0.0.1:55590 accepted //abs.twimg.com:443  
2018/12/13 14:17:33 127.0.0.1:55593 accepted //ton.twimg.com:443  
2018/12/13 14:17:34 127.0.0.1:55599 accepted //skydrive.wns.windows.com:443  
2018/12/13 14:17:39 127.0.0.1:55602 accepted //a.wunderlist.com:443  
2018/12/13 14:17:59 127.0.0.1:55614 accepted //f-log-extension.grammarly.io:443  
2018/12/13 14:18:04 127.0.0.1:55616 accepted //twitter.com:443  
```

有一些是来自其他程序的，不过可以看到来自Chrome的`twitter.com`。

8) 补充说明。

如果把客户端和服务端的`"network": "quic"`或`"network": "kcp"`都注释掉，即改为默认的tcp模式，则可以正常使用。即使将客户端`inbounds.protocal`从`http`修改为`socks`，或`inbounds.listen`从`127.0.0.1`修改为`::1`都是这个情况。

tcp, http/2, WebSocket均可正常使用，DomainSocket没有测试。

已确认服务端可以接收和发送udp报文，验证方法如下：

服务端使用`'nc -kul 22222`监听22222端口，从同一服务商在另一地区提供的VPS使用`nc -u SERVER_ADDRESS 22222`后，输入字符并回车发送，服务端可以显示发送的字符，对调二者使服务端发送数据，也可以正常接收。

服务器来自DigitalOcean，Singapore地区，使用域名通过CloudFlare的DNS解析到服务器的Floating IP。

如需其他数据或测试，还望告知。

**Comment by bososha** [comment]
这里对mKCP的配置进行了复现和测试，结果完全可用。另外是仅twitter无法访问还是包括YouTube在内的所有网站均无法访问？

**Comment by liurui39660** [comment]
> 这里对mKCP的配置进行了复现和测试，结果完全可用。另外是仅twitter无法访问还是包括YouTube在内的所有网站均无法访问？

只是以Twitter为例子，实际上是包括YouTube, Google等所有经过V2Ray代理的流量，也包括实际上并没有被GFW屏蔽但是因为路由规则而通过代理的那一部分流量。

实际上我也很奇怪这个问题，我还没有在其他的服务商测试过，不过按照Google的结果，DO除了会屏蔽邮件端口外没有其他限制，而且我的邮件端口都发过工单解禁了。

**Comment by liurui39660** [comment]
我把上面的实验用socks又重新做了一次

采用如下方法使chrome使用socks代理，这可能是一种很笨拙的方法，但至少原本可用的h2+tls现在也是可用的

![image](https://user-images.githubusercontent.com/20491264/50043323-e05bd380-00ac-11e9-858d-1860861d3393.png)

如果用下图的方法

![image](https://user-images.githubusercontent.com/20491264/50043301-8fe47600-00ac-11e9-8d20-336576258f83.png)

会是这样

```log
This site can’t be reached 
twitter.com unexpectedly closed the connection.

Try:
Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics

ERR_CONNECTION_CLOSED
```

如果用下图的方法

![image](https://user-images.githubusercontent.com/20491264/50043291-7fcc9680-00ac-11e9-9b47-1cddd478d795.png)

会是这样

```log
This page isn’t working
twitter.com didn’t send any data.

ERR_EMPTY_RESPONSE
```

这个问题我稍后再自己研究研究

## 新的日志

### 客户端访问日志

```log
2018/12/15 21:06:07 tcp:127.0.0.1:50802 accepted tcp:twitter.com:443 
```

### 服务端访问日志

```log
2018/12/15 21:06:45 223.99.197.193:30436 accepted tcp:twitter.com:443 
```

时间上客户端和服务端其实是先后的，不过我不是同时复制的log所以时间不同

### 客户端错误日志

```log

```
空白

### 服务端错误日志

都不开tls

```log
2018/12/15 21:11:44 [Warning] [2158367158] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.
```

都开tls

```log
2018/12/15 21:14:14 [Warning] [209542783] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.
```

好像和用http协议都差不多

## `curl`

### h2+tls连接twitter.com

```sh
curl -x socks://127.0.0.1:1081/ -i https://www.twitter.com
```

失败，并且到了30秒也不会超时，与此同时客户端和服务端都会收到类似于如下的日志

```log
2018/12/15 21:26:02 tcp:127.0.0.1:52291 accepted tcp:75.126.150.210:443 
```

解析得到的ip地址还变化了一次，一开始返回的是74.86.12.173，不过这两个ip我无论从本地或从服务器上都ping不通

### h2+tls连接新国大官网

```sh
curl -x socks://127.0.0.1:1081/ -i http://www.nus.edu.sg
```

返回大量html代码

客户端和服务端的日志：

```log
2018/12/15 21:35:23 tcp:127.0.0.1:52793 accepted tcp:137.132.21.27:80 
```

### kcp+无tls连接twitter.com

还是返回一个ping不通的地址

本地输出如下

```log
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:30 --:--:--     0
curl: (35) schannel: failed to receive handshake, SSL/TLS connection failed
```

客户端还是accepted

服务端日志：

```log
2018/12/15 21:37:51 [Warning] [3335724596] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.
```

### kcp+无tls连接新国大官网

返回的ip地址137.132.21.27是新国大的页面，虽然不是主页

本地输出如下

```log
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:30 --:--:--     0
curl: (52) Empty reply from server
```

客户端还是accepted

服务端日志：

```log
2018/12/15 21:37:51 [Warning] [2823318782] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.
```

**Comment by bososha** [comment]
我去简单学习了下kcptun，结合抓包信息大概可以得知，它应该就是在udp上覆盖了一层类LLC的东西，利用Control Field的N(R)和N(S)起到滑动窗口编号以进行连接控制的功能。

以下是我这里使用Wireshark（ver 2.6.5）的抓包结果：
![image](https://user-images.githubusercontent.com/16136181/50043705-f15c1300-00b3-11e9-99b2-766ff312b2fe.png)

而你的抓包结果既没有显示LLC，也没有窗口编号和连接控制的内容。另外，配置中设定的mtu是1350，应该是会出现达到最大值的包的（我这里出现了数据段长度为1346的包），但抓到的包长度却连1000都没有超过。

![image](https://user-images.githubusercontent.com/16136181/50043784-5cf2b000-00b5-11e9-966e-2a30c9803db9.png)

结合服务端connection close判断，可能是你的客户端这里出现问题，发包出错导致服务端收到了错误的包验证失败。尝试重新下载安装客户端，尽量不使用第三方GUI再试，并用你手头的其它终端设备进行对比测试。

**Comment by bososha** [comment]
@liurui39660 我的意思是可能出现内部运行的问题，或者系统其它因素影响导致KCP模块未能正常运行。重新下载运行，或者在其它终端（Win/Linux虚拟机，智能手机等）运行以排除可能的问题。

**Comment by caonimac** [comment]
用的redskcks。DigitalOcean可以quic。

**Comment by LsnmxNB** [comment]
QUIC估计是ISP封锁UDP问题
