### ISSUE TITLE
V2Ctl增加从新加载配置文件的命令,或者实现v2ray的软重启!

### ISSUE THREAD

**Issue by lpyedge** [v2ray/v2ray-core#1475]
因为多ip环境下配置新ip接入需要同时配置Inbound,Outbound,和Routing.
利用现在api无法实现必须重新v2ray重新加载config文件,是否考虑实现重新加载配置文件的功能?
如果旧配置内容和新载入的一致就保留连接和端口,不同的关闭连接和端口并开启新端口监听.

**Comment by VictoriaRaymond** [comment]
不支持，实现起来过于麻烦，而且实用价值不高。
