### ISSUE TITLE
使用 HTTP 代理不能用

### ISSUE THREAD

**Issue by MagicLentil** [v2ray/v2ray-core#1484]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V2RAY 4.9 & V2RAYN 2.19
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
使用 Chrome 通过 Http 代理访问 google.com
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
無法連上這個網站 www.google.com 的回應時間過長。
建議做法：

檢查連線狀態
檢查 Proxy 和防火牆
執行 Windows 網路診斷
ERR_TIMED_OUT
4) 你期待看到的正确表现是怎样的？
正常访问
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
配置成功
Vmess-[V2Ray]香港阿里云 - V2Ray(**************)
启动服务(2018/12/24 11:34:19)......
V2Ray 4.9.0 (Po) 20181212
A unified platform for anti-censorship.
2018/12/24 11:34:20 [Warning] v2ray.com/core: V2Ray 4.9.0 started
2018/12/24 11:34:31 tcp:127.0.0.1:4376 accepted tcp:www.gstatic.com:443 
2018/12/24 11:34:31 tcp:127.0.0.1:4379 accepted tcp:www.google-analytics.com:443 
2018/12/24 11:34:31 tcp:127.0.0.1:4381 accepted tcp:www.google.com:443 
2018/12/24 11:34:35 tcp:127.0.0.1:4383 accepted tcp:www.google.com:443 
2018/12/24 11:34:43 tcp:127.0.0.1:4385 accepted tcp:www.google.com:443 
2018/12/24 11:34:44 tcp:127.0.0.1:4387 accepted tcp:www.google.com:443 
2018/12/24 11:34:45 tcp:127.0.0.1:4389 accepted tcp:www.google.com:443 
2018/12/24 11:34:46 tcp:127.0.0.1:4391 accepted tcp:www.google.com:443 
2018/12/24 11:34:55 tcp:127.0.0.1:4394 accepted tcp:gitbook-28427.firebaseio.com:443 
2018/12/24 11:34:58 tcp:127.0.0.1:4397 accepted tcp:clients4.google.com:443 
2018/12/24 11:35:17 tcp:127.0.0.1:4401 accepted tcp:cs.dds.microsoft.com:443 
2018/12/24 11:35:26 tcp:127.0.0.1:4404 accepted tcp:www.microsoft.com:443 
2018/12/24 11:35:26 tcp:127.0.0.1:4405 accepted tcp:www.microsoft.com:443 
2018/12/24 11:36:18 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 47.75.63.103:3443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.] > v2ray.com/core/common/retry: all retry attempts failed
2018/12/24 11:36:42 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 47.75.63.103:3443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.] > v2ray.com/core/common/retry: all retry attempts failed
2018/12/24 11:36:43 tcp:127.0.0.1:4471 accepted tcp:clients4.google.com:443 
2018/12/24 11:36:47 tcp:127.0.0.1:4474 accepted tcp:www.gstatic.com:443 
2018/12/24 11:36:48 tcp:127.0.0.1:4476 accepted tcp:www.google-analytics.com:443 
2018/12/24 11:36:48 tcp:127.0.0.1:4479 accepted tcp:www.baidu.com:443 
2018/12/24 11:36:48 tcp:127.0.0.1:4480 accepted tcp:www.baidu.com:443 
2018/12/24 11:36:49 tcp:127.0.0.1:4482 accepted tcp:www.google.com:443 
2018/12/24 11:36:53 tcp:127.0.0.1:4484 accepted tcp:dc.services.visualstudio.com:443 
2018/12/24 11:36:53 tcp:127.0.0.1:4486 accepted tcp:www.google.com:443 
2018/12/24 11:36:56 tcp:127.0.0.1:4488 accepted tcp:www.google.com:443 
2018/12/24 11:37:18 tcp:127.0.0.1:4493 accepted tcp:tile-service.weather.microsoft.com:80 
2018/12/24 11:37:28 tcp:127.0.0.1:4496 accepted tcp:play.google.com:443 
2018/12/24 11:37:28 tcp:127.0.0.1:4498 accepted tcp:notifications.google.com:443 
2018/12/24 11:37:36 tcp:127.0.0.1:4500 accepted tcp:www.google.com:443 
2018/12/24 11:38:30 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 47.75.63.103:3443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.] > v2ray.com/core/common/retry: all retry attempts failed

服务器端配置:

```javascript
 
[20181224.txt](https://github.com/v2ray/v2ray-core/files/2706584/20181224.txt)
 
  // 在这里附上服务器端配置文件
```

客户端配置:

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by christolan** [comment]
你如果用的是系统代理设置的话，要吧https代理（H）和安全代理（S）都填上127.0.0.1：端口号。

v2ray-core是不带privoxy一类的代理转发软件的，所以你的客户端配置文件决定了你能用哪些代理，不像shadowsocks是所有的代理都转发到了socks代理上。

另外你不贴你的客户端配置，也不贴你的chrome代理设置，让人不是很好判断问题所在。
