### ISSUE TITLE
通过V2Ray上网，隐藏Client IP

### ISSUE THREAD

**Issue by xifarm** [v2ray/v2ray-core#1485]
Please describe the new feature you want in detail.
请问，有无类似的配置？

即，我通过V2Ray上网后，访问google就能hide我的client IP。

类似Squal3 代理软件这样设置: X-Forwarded-For

[SQUID3 IP PROXY 隐藏原IP](http://www.xifarm.com/squid3-ipproxy-hideip/)

**Comment by Cwek** [comment]
本来就可以吧，一般情况只能显示你的代理服务器的对外访问IP。

**Comment by xifarm** [comment]
> 本来就可以吧，一般情况只能显示你的代理服务器的对外访问IP。

好像不是吧。 

我访问google，依然可以看到我的原IP的，有个朋友说，SSR有这个功能，所以我问问V2Ray有无这个配置。

文档我搜索了，没有找到。

**Comment by Cwek** [comment]
> > 本来就可以吧，一般情况只能显示你的代理服务器的对外访问IP。
> 
> 好像不是吧。
> 
> 我访问google，依然可以看到我的原IP的，有个朋友说，SSR有这个功能，所以我问问V2Ray有无这个配置。
> 
> 文档我搜索了，没有找到。

中间夹杂着ss和vmess的，都没有暴露原来的IP。
当然，好像google允许向浏览器申请地理位置查询，是可以查到很精确的所在位置。另外也有一些浏览器方法是可以查询到浏览器的真实IP。前者有可能，后者估计Google用不到（？）
另外不介意的话，提供一个google能知道你真实地址的URL瞧瞧？

**Comment by xifarm** [comment]
http://www.ip111.cn/  

我希望用这个查询(ss验证正确)：

> 从国内测试：显示国内的IP
> 从国外测试： 显示ss服务器的地址
> 从谷歌测试： 显示ss服务器的地址

ss默认的配置是这样的, 是我想要的。

v2Ray我是集成在路由器的，结果是这样的：
> 从国内测试：显示国内的IP
> 从国外测试： 显示国内的IP【如何显示V2Ray 服务器地址 ？】
> 从谷歌测试： 显示V2Ray服务器的地址

**Comment by brick2008** [comment]
看了一下ip111.cn，隐藏ip跟v2ray没什么关系，跟你设置的PAC-list有关，你把“从国外测试”的域名/ip加进去就显示代理的地址了，不过这样做没什么意义，或者说，ip111的隐藏和你说的隐藏不是一回事

**Comment by xifarm** [comment]
受教了，多谢多谢，我思路清晰了很多。

**Comment by worren123** [comment]
你好，请问你解决这个问题了。我服务端用的是centos 7.3，用的最新版的v2ray，我想要隐藏客户端的IP，代理访问时直接显示服务器的IP。这个该怎么做，要做多级代理吗？

**Comment by mohanfeng3** [comment]
你好，请问你解决这个问题了吗？

**Comment by BlackTeaAttenuation** [comment]
楼上几个大佬不知所云，和周志华写的西瓜书一样，给人感觉很吊的样子。
个人解决方法：右键V2ray的图标（下方日期旁边那个栏里），Http代理换成第二个（全局代理），个人可行。

**Comment by AreAllowed** [comment]
你V2ray代理模式设置为全局代理就行了，PAC模式的话你访问国内网站和国外没有被封的网站都是用的你自己的真实IP，全局模式就是全部交给服务器代理，这样显示的就都是服务器的ip了
