### ISSUE TITLE
inbound 多 socks 端口不能同时开启密码验证 和 udp 转发

### ISSUE THREAD

**Issue by cnchill** [v2ray/v2ray-core#1498]
Please read the [instruction](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md) and answer the following questions before submitting your issue. Thank you.
Please answer all the questions with enough information. All issues not following this template will be closed immediately.
If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2ray/discussion/issues) first.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
4.10.0

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
局域网内通过 v2 提供多个socks端口  代理网内机器使用，每个socks端口对应不通的代理服务器

3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)
inbounds -> "settings" 里面 开启  "udp": ture, 后 v2ray 不能正常启动， "udp": false, 就 ok
如果不使用 socks 密码认证，似乎可以开去 udp
-------------------------------------------------------
systemctl status v2ray.service 
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2019-01-05 14:02:01 CST; 1min 6s ago
  Process: 183903 ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json (code=exited, status=23)
 Main PID: 183903 (code=exited, status=23)

1月 05 14:02:01 deb-9 systemd[1]: v2ray.service: Failed with result 'exit-code'.
1月 05 14:02:01 deb-9 systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
1月 05 14:02:01 deb-9 systemd[1]: Stopped V2Ray Service.
1月 05 14:02:01 deb-9 systemd[1]: v2ray.service: Start request repeated too quickly.
1月 05 14:02:01 deb-9 systemd[1]: Failed to start V2Ray Service.
1月 05 14:02:01 deb-9 systemd[1]: v2ray.service: Unit entered failed state.
1月 05 14:02:01 deb-9 systemd[1]: v2ray.service: Failed with result 'exit-code'.
1月 05 14:02:01 deb-9 systemd[1]: v2ray.service: Start request repeated too quickly.
1月 05 14:02:01 deb-9 systemd[1]: Failed to start V2Ray Service.
1月 05 14:02:01 deb-9 systemd[1]: v2ray.service: Failed with result 'exit-code'.
root@deb-9:/etc/v2ray# systemctl restart v2ray.service 
root@deb-9:/etc/v2ray# systemctl status v2ray.service 
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-01-05 14:03:15 CST; 3s ago
 Main PID: 183938 (v2ray)
    Tasks: 10 (limit: 36864)
   CGroup: /system.slice/v2ray.service
           └─183938 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json

1月 05 14:03:15 deb-9 systemd[1]: Started V2Ray Service.
1月 05 14:03:15 deb-9 v2ray[183938]: V2Ray 4.10.0 (Po) 20190103
1月 05 14:03:15 deb-9 v2ray[183938]: A unified platform for anti-censorship.
1月 05 14:03:15 deb-9 v2ray[183938]: 2019/01/05 14:03:15 [Warning] v2ray.com/core: V2Ray 4.10.0 started
-------------------------------------------------------
4) What's your expectation?
找到问题根源并解决问题

5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

Server configuration:

```javascript
    // Please attach your server configuration here.
```

Client configuration:

```javascript
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 17017,
      "tag": "ala-d-in",
      "listen": "0.0.0.0",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "password",
		"accounts":[
		  {
			"user": "xxx",
			"pass": "xxx!"	   
		  }
		],
        "udp": true,
        "ip": "127.0.0.1"
      },
      "streamSettings": null
    },
    {
      "port": 17018,
      "tag": "cla-d-in",
      "listen": "0.0.0.0",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "password",
		"accounts":[
		  {
			"user": "xxx",
			"pass": "xxx!"	   
		  }
		],
        "udp": true,
        "ip": "127.0.0.1"
      },
      "streamSettings": null
    },
	{
      "port": 17019,
      "tag": "cla-c-in",
      "listen": "0.0.0.0",
      "protocol": "socks",
      "sniffing": {
        "enabled": false,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "password",
		"accounts":[
		  {
			"user": "xxx",
			"pass": "xxx!"	   
		  }
		],
        "udp": true,
        "ip": "127.0.0.1"
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "ala-d-out",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "ala.xxx.xxx",
            "port": 443,
            "users": [
              {
                "id": "bf31b252-a238-4d22-9f43-3dfe38655ce5",
                "alterId": 16,
                "email": "t@t.tt",
                "security": "aes-128-gcm"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": true,
          "serverName": null
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/tryicross/",
          "headers": null
        },
        "httpSettings": null
      },
      "mux": {
        "enabled": true
      }
    },
    {
      "tag": "cla-d-out",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "cla.xxx.xxx",
            "port": 443,
            "users": [
              {
                "id": "8f4f9461-28e5-4174-904e-6a51be4b2ac3",
                "alterId": 32,
                "email": "t@t.tt",
                "security": "aes-128-gcm"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": true,
          "serverName": null
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/tryaicross/",
          "headers": null
        },
        "httpSettings": null
      },
      "mux": {
        "enabled": true
      }
    },
	{
      "tag": "cla-c-out",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "cla.xxx.xxx",
            "port": 443,
            "users": [
              {
                "id": "8f4f9461-28e5-4174-904e-6a51be4b2ac3",
                "alterId": 32,
                "email": "t@t.tt",
                "security": "aes-128-gcm"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": true,
          "serverName": null
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/tryicross/",
          "headers": null
        },
        "httpSettings": null
      },
      "mux": {
        "enabled": true
      }
    },	
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "dns":{
     "servers": [
     "1.1.1.1",
     "8.8.4.4",
     "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
		  {
			"type": "field",
			"outboundTag": "ala-d-out",
			"inboundTag": [
			  "ala-d-in"
			]
		  }, 
		  {
			"type": "field",
			"outboundTag": "cla-d-out",
			"inboundTag": [
			  "cla-d-in"
			]
		  }, 
		  {
			"type": "field",
			"outboundTag": "cla-c-out",
			"inboundTag": [
			  "cla-c-in"
			]
		  }
	  ]
    }
  }
}
```

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.

Server error log:

```javascript
    // Please attach your server error log here.
```

Client error log:

```javascript
    // Please attach your client error log here.
```

7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.

```javascript
    // Please attach your server access log here.
```

8) Other configurations (such as Nginx) and logs.

9) If V2Ray doesn't run, please attach output from `--test`.

The command is usually `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`, but may vary according to your scenario.

10) If V2Ray service doesn't run, please attach journal log.

Usual command is `journalctl -u v2ray`.

Please review your issue before submitting.

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
