### ISSUE TITLE
v2ray客户端经常异常退出

### ISSUE THREAD

**Issue by alex1528** [v2ray/v2ray-core#150]
cat /etc/v2ray/config.json
{
  "port": 1080,
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "x.x.x.x",
          "port": 12345,
          "users": [
            {
              "id": "7x4x7x3e-9dxd-4ab6-91d2-4ff8x45dxefe",
              "alterId": 64
            }
          ]
        }
      ]
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "port": "54-79",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "81-442",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "444-65535",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "domain": [
            "gc.kis.scr.kaspersky-labs.com"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        }
      ]
    }
  }
}

/配置文件里的字母 x ,均为替换的/

cat /var/log/daemon.log
......
May 20 14:23:01 ss v2ray[22721]: 2016/05/20 14:23:01 [Warning]Point server started on port 1080
May 20 14:30:13 ss v2ray[22721]: panic: runtime error: invalid memory address or nil pointer dereference
May 20 14:30:13 ss v2ray[22721]: [signal 0xb code=0x1 addr=0x20 pc=0x599089]
May 20 14:30:13 ss v2ray[22721]: goroutine 1050 [running]:
May 20 14:30:13 ss v2ray[22721]: panic(0x880bc0, 0xc82000c070)
May 20 14:30:13 ss v2ray[22721]: /home/travis/.gimme/versions/go1.6.2.linux.amd64/src/runtime/panic.go:481 +0x3e6
May 20 14:30:13 ss v2ray[22721]: github.com/v2ray/v2ray-core/common/io.(*BufferedReader).Read(0xc821712440, 0xc820104010, 0x1ff0, 0x1ff0, 0xc820104000, 0x0, 0x0)
May 20 14:30:13 ss v2ray[22721]: /home/travis/gopath/src/github.com/v2ray/v2ray-core/common/io/buffered_reader.go:42 +0xd9
May 20 14:30:13 ss v2ray[22721]: github.com/v2ray/v2ray-core/common/io.ReadFrom(0x7f3ee1e08db8, 0xc821712440, 0xc8216d6780, 0xc821711280, 0x0, 0x0)
May 20 14:30:13 ss v2ray[22721]: /home/travis/gopath/src/github.com/v2ray/v2ray-core/common/io/reader.go:16 +0x7d
May 20 14:30:13 ss v2ray[22721]: github.com/v2ray/v2ray-core/common/io.(*AdaptiveReader).Read(0xc821646f20, 0xc821711280, 0x0, 0x0)
May 20 14:30:13 ss v2ray[22721]: /home/travis/gopath/src/github.com/v2ray/v2ray-core/common/io/reader.go:45 +0x54
May 20 14:30:13 ss v2ray[22721]: github.com/v2ray/v2ray-core/common/io.Pipe(0x7f3ee1dba638, 0xc821646f20, 0x7f3ee1dba668, 0xc8203a2b10, 0x0, 0x0)
May 20 14:30:13 ss v2ray[22721]: /home/travis/gopath/src/github.com/v2ray/v2ray-core/common/io/transport.go:9 +0x40
May 20 14:30:13 ss v2ray[22721]: github.com/v2ray/v2ray-core/proxy/socks.(*Server).transport.func1(0x7f3ee1e08db8, 0xc821712440, 0x7f3ee1dba568, 0xc8203a2b10, 0xc82046c830)
May 20 14:30:13 ss v2ray[22721]: /home/travis/gopath/src/github.com/v2ray/v2ray-core/proxy/socks/server.go:282 +0x135
May 20 14:30:13 ss v2ray[22721]: created by github.com/v2ray/v2ray-core/proxy/socks.(*Server).transport
May 20 14:30:13 ss v2ray[22721]: /home/travis/gopath/src/github.com/v2ray/v2ray-core/proxy/socks/server.go:285 +0x164
May 20 14:30:13 ss systemd[1]: v2ray.service: main process exited, code=exited, status=2/INVALIDARGUMENT

OS: Debian GNU/Linux 8  64位

**Comment by v2ray** [comment]
Fixed in 1.13.1
