### ISSUE TITLE
all.go 修改无法精简编译了？

### ISSUE THREAD

**Issue by qiang-yu** [v2ray/v2ray-core#1500]
网上搜索到的都是 vbuild 修改  all.go 去除不需要的模块，然后编译就可以精简

但是
1. vbuild 现在已经根本不存在了，现在改成了 bazel 编译，比之前的 vbuild 要安装多更多东西
2. 安装好 bazel 之后，按照之前的修改 all.go 文件，去除不需要的模块，然后编译

修改  all.go ，去除不需要的模块，然后执行下面编译

cd $GOPATH/src/v2ray.com/core
bazel build --action_env=GOPATH=$GOPATH --action_env=PATH=$PATH //release:v2ray_linux_amd64_package

最后得到的 v2ray 文件有 13MB 那么大，完全没有任何精简

3.  我试过，删除 all.go 文件，编译就会失败，说明编译确实会使用 all.go 文件
4. 但是，无论我删除 all.go 的多少个模块，最后编译出来的文件大小都是一样的 13MB，
    感觉修改  all.go 文件里面的内容，完全不起任何作用

**Comment by tefiszx** [comment]
同问。我也遇到了此问题。

**Comment by p4insh11** [comment]
想问一下你后来怎么解决的，我和你效果一样

**Comment by qiang-yu** [comment]
@VictoriaRaymond  我测试了， bazel clean 再 bazel build ， 无效

我修改了 all.go 精简了很多，但是编译出来的 v2ray 依然是 14MB ，一点变化都没有

**Comment by p4insh11** [comment]
> @VictoriaRaymond 我测试了， bazel clean 再 bazel build ， 无效
> 
> 我修改了 all.go 精简了很多，但是编译出来的 v2ray 依然是 14MB ，一点变化都没有

确实是这样，我也清过，编译出来也还是一样大小
