### ISSUE TITLE
[quic]InternalError: error parsing extended header: 4th and 5th bit must be 0

### ISSUE THREAD

**Issue by yyjdelete** [v2ray/v2ray-core#1503]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v4.11
(4.10也有同样问题, 但感觉4.09更新quic包之前没这个问题, 也可能是错觉)

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
下载文件时概率性出现, 出现后连接掉速为0或者直接连接断开.

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
触发了quic的一个assert, 加了header不好用Wireshark看, ~~回头我不加header看看能不能看到什么~~
不加header也会出现, 但我看又不是单纯的`quic.short.packet_type & 24`, 不知道还要什么条件

4) 你期待看到的正确表现是怎样的？

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
{
        "port": 30004,
        "protocol": "vmess",
        "settings": {
            "clients": [{
                "alterId": 64,
                "id": "*****",
                "level": 1
            }]
        },
        "streamSettings": {
            "network": "quic",
      "tlsSettings": null,
      "quicSettings": {
        "security": "none",
        "key": "",
        "header": {
          "type": "wechat-video"
        }
      }
        }
    }
```

客户端配置:

```javascript
{
    "tag": "agentout",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "****",
          "port": 30004,
          "users": [
            {
              "id": "***",
              "alterId": 64,
              "email": "****",
              "security": "aes-128-gcm"
            }
          ]
        }
      ],
      "servers": null
    },
    "streamSettings": {
      "network": "quic",
      "tlsSettings": null,
      "quicSettings": {
        "security": "none",
        "key": "",
        "header": {
          "type": "wechat-video"
        }
      }
    },
    "mux": {
      "enabled": true
    }
  }
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
[Info] v2ray.com/core/transport/internet/quic: failed to accept stream > InternalError: error parsing extended header: 4th and 5th bit must be 0
[Info] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > InternalError: error parsing extended header: 4th and 5th bit must be 0
```

客户端错误日志:

```javascript
[Info] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > InternalError: error parsing extended header: 4th and 5th bit must be 0

//之后可能还会出现
[Info] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > InternalError: cipher: message authentication failed
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by yyjdelete** [comment]
抓了下包和quic的日志, 感觉很可能是quic本身的问题. 两边的发送和接收除了顺序之外数据都是一致的, 但对于异常包, quic解码出来的数据和发送端未编码的数据不一致. 感觉可能在下载的高负荷情况下丢包或者包乱序造成aead解码失败.

---

尝试手动更新了下最新的quic, 发现新版quic仍会触发`4th and 5th bit must be 0`, 但不会再造成上层连接断开了.https://github.com/lucas-clemente/quic-go/commit/131f561be062acce6dd13ccf1f9679ce926a9e77
建议v2再更新下引用的quic

**Comment by wd** [comment]
奇怪，我之前也遇到了这个问题，服务器版本和客户端版本不一样，大概一个是 4.11 一个是 4.09  的样子（可能记的不对，就是差了1-2个小版本的样子），然后当时是把版本都升级一致了就没这个问题了。
