### ISSUE TITLE
建议dokodemo-door转发dns请求增加对iptables的兼容

### ISSUE THREAD

**Issue by FH0** [v2ray/v2ray-core#1505]
想用v2ray实现一个类似ss-tunnel的功能，但是发现以下问题：
```
1.dokodemo-door转发来自dig或者dnsmasq的dns没有问题
2.dokodemo-door转发来自iptables的dns失败，日志文件显示目标地址是127.0.0.1
3.ss-tunnel可以正常转发来自dig,dnsmasq和iptables的dns
```
目前的解决方法：
把流量转发到overture,然后[overture](https://github.com/shawn1m/overture)设置socks代理为v2ray

**Comment by qiang-yu** [comment]
配置  dokodemo-door  监听 7070 端口，并且把数据转发到 8.8.8.8 的 53 端口  udp 

我看你上面的描述，你应该已经配置好上面了

把下面这个文件放到你的 /etc/dnsmasq.d  目录下

https://raw.githubusercontent.com/qiang-yu/publish-cdn/master/gfwlist/gfwlist_localdns.conf

上面两步就搞定了

**Comment by wd** [comment]
@FH0  你转发成功的配置可以贴一个不，我这 dig 都查不了。。。

**Comment by FH0** [comment]
> 配置 dokodemo-door 监听 7070 端口，并且把数据转发到 8.8.8.8 的 53 端口 udp
> 
> 我看你上面的描述，你应该已经配置好上面了
> 
> 把下面这个文件放到你的 /etc/dnsmasq.d 目录下
> 
> https://raw.githubusercontent.com/qiang-yu/publish-cdn/master/gfwlist/gfwlist_localdns.conf
> 
> 上面两步就搞定了

嗯，这样确实可以，主要是不想借助其他的软件(强迫症)
