### ISSUE TITLE
wv2ray.exe尝试访问static.fc2.com

### ISSUE THREAD

**Issue by utopiaseeker** [v2ray/v2ray-core#1507]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

服务端和客户端都是4.11.0版本。另外,用的是PC版的v2rayN。服务端是用233blog的一键脚本安装的。

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
使用 Chrome通过v2rayN全局代理浏览网页
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
360弹出提醒称wv2ray.exe尝试访问static.fc2.com，如下图所示
![qq 20190114085012](https://user-images.githubusercontent.com/46660161/51093012-759bd600-17d9-11e9-9e82-f0dc91c933d6.jpg)
4) 你期待看到的正确表现是怎样的？

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    //  
[服务端.json.txt](https://github.com/v2ray/v2ray-core/files/2753810/json.txt)


```

客户端配置:

```javascript
    //
[客户端.json.txt](https://github.com/v2ray/v2ray-core/files/2753811/json.txt)

```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by slanterns** [comment]
用翻墙软件之前卸掉360不是常识么
总之这个锅和v2ray没有半毛钱关系。

**Comment by njjpx** [comment]
关注，不知道是谁的锅。

**Comment by VictoriaRaymond** [comment]
从域名来看这是一个资源站，有可能是你访问的某个网页外链了那个域名的图片或者广告什么的。如果你不希望访问这个域名可以在本地加一个黑名单。另外fc2.com是一个完全正常的网站，没有必要大惊小怪。

**Comment by utopiaseeker** [comment]
> 从域名来看这是一个资源站，有可能是你访问的某个网页外链了那个域名的图片或者广告什么的。如果你不希望访问这个域名可以在本地加一个黑名单。另外fc2.com是一个完全正常的网站，没有必要大惊小怪。

谢谢作者！

**Comment by utopiaseeker** [comment]
我之前是被360这么一“提醒”，下意识地以为wv2ray.exe本来不应该具有访问网址的功能但它“偷偷”去访问了，而且还是一个我不熟悉的网站，因此我有了疑问。作者这么一解释，应该是暗示了访问网址本就是经过wv2ray.exe的。看来确实是360这个娱乐软件在误导。PS. slanterns火气真不小，其实很多“小白”只要好好沟通，是可以被科普的，建议向作者VictoriaRaymond学习
