### ISSUE TITLE
inbound 代理无法受理 ipv6 请求，malformed proxy host, too many colons in address

### ISSUE THREAD

**Issue by NathanIceSea** [v2ray/v2ray-core#1508]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v4.9 客户端

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
V2ray 的 SOCKS5 inbound 代理不支持受理 ipv6 地址，并且连接尝试在 Log 中不显示
HTTP inbound 代理可以受理 http://[ipv6 address] 地址，但是无法受理 https://[ipv6 address]，error.log 中显示错误的 host 格式

4) 你期待看到的正确表现是怎样的？
SOCKS5 代理可以正常代理 ipv6 地址的请求
HTTP 代理可以正常代理 ipv6 地址的 HTTPS 请求（wget https://[ipv6 address] --no-check-certificate）

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

略

客户端配置:

```javascript
"inbounds": [
        {
            "port": 1080,
            "protocol": "socks",
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            },
            "settings": {
                "auth": "noauth"
            }
        },
        {
            "port": 8800,
            "protocol": "http",
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            },
            "settings": {
                "auth": "noauth"
            }
        },
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

略

客户端错误日志:

HTTP 代理下对 HTTPS ipv6 的请求

```javascript
2019/01/14 14:43:38 [Warning] [34817911] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: malformed proxy host: 2a00:1450:400e:804::2004:443 > address 2a00:1450:400e:804::2004:443: too many colons in address
2019/01/14 14:43:39 [Warning] [1425019556] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: malformed proxy host: 2a00:1450:400e:804::2004:443 > address 2a00:1450:400e:804::2004:443: too many colons in address
2019/01/14 14:43:41 [Warning] [2589386943] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: malformed proxy host: 2a00:1450:400e:804::2004:443 > address 2a00:1450:400e:804::2004:443: too many colons in address
2019/01/14 14:43:44 [Warning] [2216386113] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: malformed proxy host: 2a00:1450:400e:804::2004:443 > address 2a00:1450:400e:804::2004:443: too many colons in address
2019/01/14 14:43:48 [Warning] [1084426183] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: malformed proxy host: 2a00:1450:400e:804::2004:443 > address 2a00:1450:400e:804::2004:443: too many colons in address

```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

HTTP 代理下正常的 HTTP ipv6 请求

```javascript
2019/01/14 15:02:35 127.0.0.1:56915 accepted http://[2a00:1450:400e:808::2004]/  
2019/01/14 15:02:36 127.0.0.1:56915 accepted http://[2a00:1450:400e:808::2004]/favicon.ico  
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

略

**Comment by VictoriaRaymond** [comment]
wget时候，ipv6的地址有[]吗?比如是以下哪种:

* `wget https://[fe80::a00:27ff:fe00:80b9]:443/`
* `wget https://fe80::a00:27ff:fe00:80b9:443/`

**Comment by NathanIceSea** [comment]
> wget时候，ipv6的地址有[]吗?比如是以下哪种:
> 
> * `wget https://[fe80::a00:27ff:fe00:80b9]:443/`
> * `wget https://fe80::a00:27ff:fe00:80b9:443/`

正常的话应当是报 503 这样的代码，可是我测下来都是 ERR_ADDRESS，另外 log 中会有错误信息这样

**Comment by laucenmi** [comment]
我这里错误是：
2019/01/12 14:04:32 [Info] [1503642591] v2ray.com/core/app/proxyman/inbound: failed to get original destination > v2ray.com/core/transport/internet/tcp: failed to call getsockopt
2019/01/12 14:04:32 [Debug] [1503642591] v2ray.com/core/proxy/dokodemo: processing connection from: [2408:8025:..hide...:fc92]:55798
2019/01/12 14:04:32 [Info] [1503642591] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: unable to get destination
2019/01/12 14:04:32 [Info] v2ray.com/core/transport/internet/tcp: failed to call getsockopt > no such file or directory
2019/01/12 14:04:32 [Info] [2749915689] v2ray.com/core/app/proxyman/inbound: failed to get original destination > v2ray.com/core/transport/internet/tcp: failed to call getsockopt
同样的设置, ss-libev可以正常工作

**Comment by pentie** [comment]
经过检查这是wget的BUG，具体描述是：“wget使用https_proxy时候，对于裸IPv6地址的HTTPS URL使用CONNECT方法，主机地址和端口没有使用中括号区分”。

这个BUG有Ubuntu的确认： https://bugs.launchpad.net/ubuntu/+source/wget/+bug/1566930
就是wget会发出这样的请求，导致`malformed address, too many colons`的提示。
```
CONNECT 2001::1:443 HTTP/1.1\r\n
```

测试命令：

```
#v2ray http 监听在::10809

#正常
curl --proxy http://127.0.0.1:10809 -gv -k https://[2001::1]:443/
curl --proxy http://127.0.0.1:10809 -gv -k http://[2001::1]:80/
env http_proxy=http://127.0.0.1:10809 wget -O - http://[2001::1]:80/

#出现本issue错误
env https_proxy=http://127.0.0.1:10809 wget --no-check-certificate -O - https://[2001::1]:443/
```

建议改用curl命令。另外，curl对于没端口的裸ipv6 URL不能识别，即不允许`curl https://[2001::1]/`

因此这个问题对于v2ray项目没有可以改进的地方。建议close。
