### ISSUE TITLE
是4.12发威了吗？还是。

### ISSUE THREAD

**Issue by caonimac** [v2ray/v2ray-core#1509]
从2012年以来，一直没有公网ip，用V2一年多了，一直是Port Restricted Cone NAT。
不久之前4.10也还是Port Restricted Cone NAT。
今天无意中试了一下，居然是FullCone。
一直学不会Dokodemo-door，用的是redsocks。

![tempsnip](https://user-images.githubusercontent.com/35394132/51110978-4d41c500-1835-11e9-95e3-cf554a5d6272.png)

**Comment by VictoriaRaymond** [comment]
恭喜你发现了黑科技

**Comment by wongsyrone** [comment]
使用的是TPROXY吗

**Comment by caonimac** [comment]
> 使用的是TPROXY吗

是的

**Comment by Alion548** [comment]
请问，Youtube的QUIC连接正常(相同问题：https://github.com/v2ray/v2ray-core/issues/1432)吗？

**Comment by p4insh11** [comment]
我看到某个issue上看到了，另外提到了部分UDP包的源地址不能正确返回，能告诉一下是哪部分么
FullCone这简直是黑科技了，小姐姐新年礼物啊
@VictoriaRaymond

**Comment by Alion548** [comment]
> 我看到某个issue上看到了，另外提到了部分UDP包的源地址不能正确返回，能告诉一下是哪部分么
> FullCone这简直是黑科技了，小姐姐新年礼物啊
> @VictoriaRaymond

小姐姐？！

**Comment by caonimac** [comment]
> 请问，Youtube的QUIC连接正常(相同问题：#1432 )吗？

这个一直正常的，现在加载更快。

**Comment by VictoriaRaymond** [comment]
> 另外提到了部分UDP包的源地址不能正确返回，能告诉一下是哪部分么

每个映射的UDP端口都有一个固定的目标地址A，即第一个发出的数据包的目标地址，如果之后从其它地址收到数据，也会返回成A地址发来的数据。

**Comment by qiang-yu** [comment]
这个 FullCone 需要额外的配置吗？

我把 client 和 server 都升级到了 4.12，测试 stun，然而并没有出现 FullCone，依然是 Symmetric

系统是 Debian 8  x64

**Comment by caonimac** [comment]
> 我也测试了一下，服务端和客户端都是4.12，依然是Symmetric，你用了Dokodemo-door还是redsocks?

用的redsocks。

**Comment by qiang-yu** [comment]
> > 我也测试了一下，服务端和客户端都是4.12，依然是Symmetric，你用了Dokodemo-door还是redsocks?
> 
> 用的redsocks。
> Cloudflare + ws +caddy

也就是说，单纯的 v2ray 是做不到 FullCone 效果吧，必须要配合 vpn 软件来做吧？

比如   wireguard --> v2ray-client ---> v2ray-server--wireguard 

v2ray 这是单纯被用作了 tunnel 的作用吧？ 真正实现 FullCone 效果的其实是 VPN 软件本身
(redsocks 起了一个 vpn 作用吧)
