### ISSUE TITLE
官网打不开了

### ISSUE THREAD

**Issue by dly667** [v2ray/v2ray-core#1512]
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

此 Issue 会被立即关闭。

If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2ray/discussion/issues) first.

This issue will be closed immediately.

**Comment by caonimac** [comment]
少了几个字。
你在你的手机或电脑上，官网打不开了。
