### ISSUE TITLE
v2ray 导入vmess://链接

### ISSUE THREAD

**Issue by SeAL80s** [v2ray/v2ray-core#1517]
Please describe the new feature you want in detail.
现在v2ray 只能-config json文件。而v2rayng又不能导出json，那个Bif什么的客户端倒是可以导出json，但是v2ray -config json文件就出错。广大用户一般都是网上找vmess链接的，不管是花钱的还是免费的。能不能让v2ray本身就支持导入和导出vmess形式链接？实现起来麻烦不？

**Comment by tjLEIIQM3** [comment]
不会太麻烦，不过按core的发展方向来看，大概不会加这功能。
（幸好不是linux用户，哈哈）

**Comment by boypt** [comment]
其实config.json文件跟vmess链接是不同的概念，后者大概是前者的子集吧，vmess链接只包括服务器信息和用户信息，也就是config.json里面的outbound和inbound里面的users两个部分。因此vmess链接的信息是不足以让v2ray跑起来的，需要一个类似模板来做补充，然后填充vmess里面的信息，生成的json给v2ray来启动。

可以考虑写个小程序完成这样的功能。

**Comment by liberal-boy** [comment]
这个 scheme 并非 v2ray 指定，也不受官方支持，你可以根据这个 scheme  的定义，自己写配置文件。

**Comment by boypt** [comment]
@SeAL80s @tjLEIIQM3 
那天看了这个issue，然后自己刚好也有类似的需求，顺手撸了个脚本，感兴趣可以试试：
https://github.com/boypt/vmess2json

**Comment by joostshao** [comment]
```
main: failed to read config file: /home/sjt/xx.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/ext/tools/conf/command: failed to parse json config > v2ray.com/ext/tools/conf/serial: failed to parse json config > v2ray.com/ext/tools/conf: failed to parse to outbound detour config. > json: cannot unmarshal string into Go struct field VMessOutboundTarget.port of type uint16

```

建议： 官方直接支持base64之后的配置input
