### ISSUE TITLE
v2ctl 怎么做精简编译呢？

### ISSUE THREAD

**Issue by qiang-yu** [v2ray/v2ray-core#1519]
最近在把 v2ray 集成到 openwrt 里面去，flash 只有 16MB ，用 squashfs （自带压缩的文件系统）

v2ray 可以通过修改  main/distro/all/all.go  文件，去除不需要的模块，从而实现精简编译

可是 v2ctl 依然太大了（13MB多），我们用 v2ctl 只是把 json 转换成 pronbuf  格式，就是一次性的操作而已，没必要占用这么大存储

请教一下， 应该修改哪个文件，可以实现把 v2ctl 精简编译，去除不需要的功能，只需要一个转化json格式就足够了

谢谢

**Comment by boypt** [comment]
你可以尝试手工执行v2ctl convert把你配置的json转换成protobuf，命名为xxx.pb，这样调用v2ray -config xxx.pb就不会调用v2ctl了。虽然麻烦了一步但是可以省下十几M空间

**Comment by VictoriaRaymond** [comment]
同上，v2ctl只是用于支持json格式的配置文件，v2ray不依赖于v2ctl，可以单独运行。

**Comment by qiang-yu** [comment]
> 同上，v2ctl只是用于支持json格式的配置文件，v2ray不依赖于v2ctl，可以单独运行。

额，我这个是集成到 openwrt 里面， 用户是可以修改配置的，也就是说，用户自己配置 json，然后动态运行，不是固定写死不变的，所以没法手动转换，然后永远不变的让用户就使用同一个配置

还是需要精简编译 v2ctl ，请问应该如何操作呢？
