### ISSUE TITLE
Feature Request: Support Tor's Pluggable Transport Plugin protocol

### ISSUE THREAD

**Issue by xiaokangwang** [v2ray/v2ray-core#1528]
Tor's Pluggable Transport protocol allow a separate program to be used as a traffic delivery channel. It would beneficial to support this plugin format in V2Ray. 

It has a [diverse](https://trac.torproject.org/projects/tor/wiki/doc/PluggableTransports/list) ecosystem of Pluggable Transport that support this protocol and most of them is of high quality.

If we wants to support this in V2Ray, there is a few concern needs to be addressed:

Pluggable Transport protocol require host program to execute plugin program, this can be insecure in environment where configure files are retrieved over network.

Pluggable Transport protocol require a seperate binary to be present, this can be difficult on multi-platform deployment or mobile.

**Comment by lwyh** [comment]
You can already use V2Ray with Tor, just not as a PT 
https://lwyh.gitlab.io/tor/2019/02/05/v2ray-tor.html

**Comment by xiaokangwang** [comment]
> You can already use V2Ray with Tor, just not as a PT
> https://lwyh.gitlab.io/tor/2019/02/05/v2ray-tor.html

We are talking about using Tor's Pluggable Transport as transport in V2Ray, not using V2Ray as Tor's Pluggable Transport. Thanks for your information anyway.
