### ISSUE TITLE
[Feature Request]增加指定主出站协议的功能

### ISSUE THREAD

**Issue by Emphasia** [v2ray/v2ray-core#1529]
查阅手册发现路由功能中：`当没有匹配到任何规则时，流量默认由主出站协议发出。` `outbounds:一个数组，每个元素是一个出站连接配置。列表中的第一个元素作为主出站协议。当路由匹配不存在或没有匹配成功时，流量由主出站协议发出。`，是否可以考虑增加 指定主出站协议 的功能（例如和匹配成功一样通过balancerTag或outboundTag选择出站协议进行流量转发然后未指定时默认）？
❤

**Comment by VictoriaRaymond** [comment]
没看懂，请详细描述你的需求

**Comment by tjLEIIQM3** [comment]
也就是退回v3.x时的in(out)bound(Detour)形式咯。
用了一段时间v4.x的in(out)bounds后，我也觉得原来的in(out)bound(Detour)好用点，
特别是通过程序修改（注意是修改不是解释）配置的时，更好处理些。

**Comment by Emphasia** [comment]
> 没看懂，请详细描述你的需求

当前路由功能中，规则匹配成功时走指定balancerTag或outboundTag，匹配失败时走主出站协议（即outbounds数组第一个），能否增加手动指定这个主出站协议？

**Comment by yumenaka** [comment]
“Tag”：“Default” ，手动指定主出站协议？

**Comment by VictoriaRaymond** [comment]
你手动把主outbound放在第一个就可以了。用tag指定的话，会产生在配置错误时tag不存在的情况。

**Comment by Emphasia** [comment]
> 你手动把主outbound放在第一个就可以了。用tag指定的话，会产生在配置错误时tag不存在的情况。

可是这样配置限制了主outbound只能是一个，
在面对最简单那种分流的实现时反而会因此受限，比如：
*国内直连剩余国外通过多道outbounds最简单的轮询*
*bt屏蔽后剩余流量负载均衡*
在设了相应规则以后剩余的流量只能全部被动地涌到唯一的主outbound中，结果就是少数能定义规则的流量被很好的分流而大量的模糊的不好定规则的流量却挤在一起。
只是举例子来说明这种类似的可能情况，现有的配置对这种特殊情况可以通过进进出出绕着圈子间接实现但太累赘浪费了（也可能只是我没想到灵活的解决方案）。

**Comment by Cwek** [comment]
@VictoriaRaymond @Emphasia 
可以用路由解决（最后一个用0.0.0.0/0和::/0拦截下来）。其实4.x改版时就想过，如果主outbound是开成负载平衡的话，就可能无法简单配置，如前述的，需要用显式兜底路由（路由项目用来配置balance）来代替以前隐式的默认路由项目（因为以前只有outbound，现在要二选一）
