### ISSUE TITLE
v2ray 不支持 centos 6 启动方式

### ISSUE THREAD

**Issue by alex1528** [v2ray/v2ray-core#153]
bash <(curl -L -s https://raw.githubusercontent.com/v2ray/v2ray-core/master/release/install-release.sh)
/dev/fd/63: line 76: /usr/bin/v2ray/v2ray: No such file or directory
Downloading https://github.com/v2ray/v2ray-core/releases/download/v1.13.1/v2ray-linux-64.zip directly.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2380k  100 2380k    0     0  33129      0  0:01:13  0:01:13 --:--:-- 30454
Archive:  /tmp/v2ray/v2ray.zip
  inflating: /tmp/v2ray/v2ray-v1.13.1-linux-64/systemd/v2ray.service  
  inflating: /tmp/v2ray/v2ray-v1.13.1-linux-64/systemv/v2ray  
  inflating: /tmp/v2ray/v2ray-v1.13.1-linux-64/v2ray  
  inflating: /tmp/v2ray/v2ray-v1.13.1-linux-64/vpoint_socks_vmess.json  
  inflating: /tmp/v2ray/v2ray-v1.13.1-linux-64/vpoint_vmess_freedom.json  
PORT:13080
UUID:1a09d7b1-62ed-441e-bbe9-77e15233949f
Updating software repo via yum.
Installing daemon via yum.
Error: Nothing to do
/dev/fd/63: line 164: update-rc.d: command not found

#/etc/init.d/v2ray status
/etc/init.d/v2ray: line 29: /lib/init/vars.sh: No such file or directory

**Comment by wtlusvm** [comment]
看这个：https://github.com/v2ray/v2ray-core/issues/118

**Comment by alex1528** [comment]
thanks.
