### ISSUE TITLE
无法在 Docker 的 Alpine 镜像下运行

### ISSUE THREAD

**Issue by undirectlookable** [v2ray/v2ray-core#154]
本着万物皆 Docker 的理想，试着在 Alpine 下跑了一下，使用的是 Releases 中的 `v2ray-linux-64.zip`，`chmod +x v2ray` 后执行 `./v2ray` 报错，在 debian 下没有问题。选择 Alpine 是为了让镜像尽量小。
抱歉此时手边无环境不能贴出具体的报错信息，你可以试一下，很容易复现。

**Comment by v2ray** [comment]
和 #156 是同样的问题吗？都是 Alpine 的。我手头没有 Alphine 的系统，一时半会没法调试。

**Comment by undirectlookable** [comment]
似乎是的，他说32位的不可以，64位可以；我这里刚好相反。

上次只测试了 `v2ray-linux-64.zip`， 今天尝试 `v2ray-linux-32.zip` 竟然没问题。
操作过程：

```shell
> docker run --rm -ti 1science/alpine

root@/ > uname -a
Linux ed0954664eca 4.4.11-moby #1 SMP Mon May 23 20:46:49 UTC 2016 x86_64 Linux

root@/ > wget -q https://github.com/v2ray/v2ray-core/releases/download/v1.13.1/v2ray-linux-64.zip
root@/ > unzip v2ray-linux-64.zip
root@/ > cd v2ray-v1.13.1-linux-64/
root@/v2ray-v1.13.1-linux-64 > chmod +x v2ray

root@/v2ray-v1.13.1-linux-64 > ./v2ray
bash: ./v2ray: No such file or directory
```

**Comment by yuanl** [comment]
Alpine and busybox Linux use a different c library musl which is not compatible with the golang binary. Try another distribution image instead.

Get Outlook for iOS




On Fri, May 27, 2016 at 7:14 PM -0700, "undirectlookable" <notifications@github.com> wrote:












似乎是的，他说32位的不可以，64位可以；我这里刚好相反。



上次只测试了 v2ray-linux-64.zip， 今天尝试 v2ray-linux-32.zip 竟然没问题。

操作过程：

> docker run --rm -ti 1science/alpine

root@/ > uname -a
Linux ed0954664eca 4.4.11-moby #1 SMP Mon May 23 20:46:49 UTC 2016 x86_64 Linux

root@/ > wget -q https://github.com/v2ray/v2ray-core/releases/download/v1.13.1/v2ray-linux-64.zip
root@/ > unzip v2ray-linux-64.zip
root@/ > cd v2ray-v1.13.1-linux-64/
root@/v2ray-v1.13.1-linux-64 > chmod +x v2ray

root@/v2ray-v1.13.1-linux-64 > ./v2ray
bash: ./v2ray: No such file or directory

**Comment by undirectlookable** [comment]
@yuanl  But the 32-bit binary works well, weird.

**Comment by v2ray** [comment]
最新的 V2Ray release 已经修复了这个问题，可以直接在 Alpine Linux 上运行。

**Comment by yuanl** [comment]
That is great. Will save a lot of space.
