### ISSUE TITLE
在iPhone上同样的配置，老版的Kitsunebi没问题，新版用不了

### ISSUE THREAD

**Issue by SnorlaxYum** [v2ray/v2ray-core#1540]
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

此 Issue 会被立即关闭。

If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2ray/discussion/issues) first.

This issue will be closed immediately.

{
  "dns":{
	"servers":[ 
		"8.8.8.8"
    ]
  },
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 1080,  
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp":true 
    },
    "domainOverride": ["http", "tls"]
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [{
        "address": "the.url",
        "port": 80,  
        "users": [{ "id": "秘密","alterId": 64,"security":"none" }]
      }]
    },
    "mux": {
      "enabled": true
    },
    "streamSettings": {
      "network": "ws",
      "security": "none",
      "wsSettings": {
        "path": "/path"
      }
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "transport": {
    "tcpSettings": {
      "connectionReuse": true
    },
    "wsSettings": {
      "connectionReuse": true
    },
    "tlsSettings": {
      "allowInsecure": true
    }
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
       {
         "type": "field",
	 "domain": [
	   "googleapis.cn",
	   "google.cn",
	   "ggpht.cn",
	   "1e100.net"
	 ],
	 "outboundTag": "proxy"
       },
      {
        "type": "field",
        "domain": [
          "geosite:cn"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": [
          "geoip:private",
          "geoip:cn"
        ],
        "outboundTag": "direct"
      }
    ]
    }
  },
  "policy": {
    "levels": {
      "0": {"uplinkOnly": 0}
    }
  }
}

完全没有头绪
访问Google时候，访问日志一条显示:主机为dns:8.8.8.8:53，下面响应显示failed to query ips: context deadline exceeded

**Comment by eycorsican** [comment]
检查下服务端版本，不能低于客户端 v2ray-core 版本，有需要的话升级下
