### ISSUE TITLE
公司内 软件开发 程序员共享IP大量访问 会出现无法访问 超时现象

### ISSUE THREAD

**Issue by aybru** [v2ray/v2ray-core#1552]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V2Ray 4.16.1 (Po) 20190215

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
Chrome 通过 HTTPS 443端口 nginx proxy_pass websocket 大量请求Google。

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
chrome有时候会无响应访问超时

4) 你期待看到的正确表现是怎样的？
 正常访问
 
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
nginx配置
upstream v2ray {
    server 127.0.0.1:10000;
    keepalive 64;
}
    location = /隐藏 {
        access_log  /var/log/nginx/access/v2ray.log  main;
        error_log  /var/log/nginx/error/v2ray.log warn;
        proxy_pass http://v2ray/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-For $remote_addr;
    }
```

客户端配置:

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
v2ray error：
2019/02/15 02:52:32 [Warning] v2ray.com/core/transport/internet/websocket: failed to serve http for WebSocket > accept tcp 127.0.0.1:10000: use of closed network connection
```

客户端错误日志:

```javascript
2019/02/15 18:26:00 tcp:127.0.0.1:65504 rejected  v2ray.com/core/proxy/socks: insufficient header > read tcp 127.0.0.1:1080->127.0.0.1:65504: i/o timeout
2019/02/15 18:26:00 tcp:127.0.0.1:65505 rejected  v2ray.com/core/proxy/socks: insufficient header > read tcp 127.0.0.1:1080->127.0.0.1:65505: i/o timeout
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript

v2ray access:
2019/02/15 05:00:23 IP:3546 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > websocket: close 1006 (abnormal closure): unexpected EOF
2019/02/15 05:27:10 IP:8740 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > websocket: close 1000 (normal)
2019/02/15 05:33:03 IP:9680 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > websocket: close 1006 (abnormal closure): unexpected EOF
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

```javascript
nginx access:
IP - - [15/Feb/2019:01:57:05 -0500] "GET /隐藏 HTTP/1.1" 499 0 "-" "Go-http-client/1.1" "-"
IP - - [15/Feb/2019:01:57:05 -0500] "GET /隐藏 HTTP/1.1" 499 0 "-" "Go-http-client/1.1" "-"
IP - - [15/Feb/2019:03:48:40 -0500] "GET /隐藏 HTTP/1.1" 499 0 "-" "Go-http-client/1.1" "-"
IP - - [15/Feb/2019:03:58:14 -0500] "GET /隐藏 HTTP/1.1" 499 0 "-" "Go-http-client/1.1" "-"

nginx error：
2019/02/15 05:27:22 [error] 7351#7351: *4206 recv() failed (104: Connection reset by peer) while proxying upgraded connection, client: IP, server: 域名, request: "GET /隐藏 HTTP/1.1", upstream: "http://127.0.0.1:10000/ws"
2019/02/15 05:27:22 [error] 7351#7351: *4236 recv() failed (104: Connection reset by peer) while proxying upgraded connection, client: IP, server: 域名, request: "GET /隐藏 HTTP/1.1", upstream: "http://127.0.0.1:10000/ws"
```

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by boypt** [comment]
同机器内的访问会消耗占用fd套接字资源的，可能你系统的默认限制比较小，core处理不了后续请求了，找一篇tcp tunning 的教程对着修改一下限制数吧

**Comment by aybru** [comment]
> 同机器内的访问会消耗占用fd套接字资源的，可能你系统的默认限制比较小，core处理不了后续请求了，找一篇tcp tunning 的教程对着修改一下限制数吧

已经更改 明天观望下

**Comment by aybru** [comment]
老样子 未解决！

**Comment by kslr** [comment]
你有尝试调整keepalive大小吗

**Comment by kslr** [comment]
没有消息了吗

**Comment by aybru** [comment]
kernel.sysrq = 0
fs.file-max = 9999999

net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_tw_recycle = 0
net.ipv4.tcp_keepalive_time = 3600
net.ipv4.ip_local_port_range = 1024 65535
net.ipv4.tcp_rmem = 4096 87380 12582912
net.ipv4.tcp_wmem = 4096 87380 12582912
net.ipv4.tcp_max_syn_backlog = 8192
net.core.netdev_max_backlog = 8192
net.core.rmem_max = 8388608
net.core.wmem_max = 8388608
net.ipv4.tcp_rmem = 4096 87380 8388608
net.ipv4.tcp_wmem = 4096 16384 8388608
net.core.somaxconn = 262140
net.ipv4.tcp_retries2 = 5
net.ipv4.neigh.default.base_reachable_time_ms = 600000
net.ipv4.neigh.default.mcast_solicit = 20
net.ipv4.neigh.default.retrans_time_ms = 250
net.core.default_qdisc=fq
net.ipv4.tcp_congestion_control=bbr
vm.swappiness=10
net.ipv4.tcp_fastopen = 2

**Comment by kslr** [comment]
不是哦，我指nginx的参数。不过你也可以在问题出现时，观察所有连接状态(netstat,Sar)。

**Comment by arslan2012** [comment]
@kslr 我用的是Caddy， timeout设置的是none，也会经常出现和楼主一样的情况

**Comment by kslr** [comment]
@arslan2012 最好新建一个issue 带上日志
Timeout要看情况，不是越长越好

**Comment by GBVF** [comment]
你整份服务器配置和客户机配置发出来看下。  我的需求跟你一样。几百个业务员都用一个V2RAY 我这里没啥事。
