### ISSUE TITLE
src_all.zip is missing some content

### ISSUE THREAD

**Issue by felixonmars** [v2ray/v2ray-core#1553]
When building using the src_all.zip, an error is present:

```
can't load package: package v2ray.com/ext/tools/control/main: cannot find package "v2ray.com/ext/tools/control/main" in any of:
        /usr/lib/go/src/v2ray.com/ext/tools/control/main (from $GOROOT)
        /build/v2ray/src/build/src/v2ray.com/ext/tools/control/main (from $GOPATH)
```

Starting from 4.15.1, and reproduced in 4.16.0/4.16.1.

**Comment by VictoriaRaymond** [comment]
It is now added back in 4.16.2 (still in-progress). Sorry for the interruption.

Please also consider to migrate to the new path, as mentioned in #1541 .

**Comment by felixonmars** [comment]
Thanks!
