### ISSUE TITLE
how to build from source

### ISSUE THREAD

**Issue by debiansid** [v2ray/v2ray-core#156]
Hi there
because my openwrt x86 is base on trunk(musl), so I do not think the binary from release will work, so I want to know how to build from source?

thanks

**Comment by debiansid** [comment]
go get -u github.com/v2ray/v2ray-core
go build github.com/v2ray/v2ray-core/common/platform: /usr/lib/go/pkg/tool/linux_386/compile: signal: trace/breakpoint trap

**Comment by debiansid** [comment]
alpine-x86:~$ go version
go version go1.6.2 linux/386

**Comment by v2ray** [comment]
trace/breakpoint trap is an issue in Golang itself. For example: https://github.com/golang/go/issues/12906

Although the issue has been fixed, but there is still reports complaining similar problems, like https://forum.syncthing.net/t/syncthing-exits-with-trace-breakpoint-trap-due-to-missing-modify-ldt-system-call-in-386-systems/6936

I have no idea how to fix it. Probably use another platform to build.

**Comment by debiansid** [comment]
bin/v2ray-custom-linux-64/v2ray 
V2Ray 1.14 (New Order) Custom
An unified platform for anti-censorship.
2016/05/28 02:10:37 [Error]Failed to read server config file (/home/ezhang/work/bin/v2ray-custom-linux-64/config.json): /home/ezhang/work/bin/v2ray-custom-linux-64/config.jsonopen /home/ezhang/work/bin/v2ray-custom-linux-64/config.json: no such file or directory
2016/05/28 02:10:37 [Error]Failed to read config file

64-bit alpine is good.

**Comment by debiansid** [comment]
libev的ss有个ss-redir v2ray貌似没有 只相当于ss-local.请问未来计划开发这个功能么

**Comment by v2ray** [comment]
有计划，别急

**Comment by debiansid** [comment]
32位还是不行 看来只能换到64位op跑跑了 等v2ray的redir功能

**Comment by v2ray** [comment]
已支持 TCP 的 redir 功能

**Comment by v2ray** [comment]
楼主的问题已查明，在编译的时候使用 CGO_ENABLED=0 禁用 glibc 的静态链接，即可。

**Comment by LinArcX** [comment]
Still i don't know how to build it from source. I also want to build it on void-linux. Anyone can please tell the steps to build from source?
