### ISSUE TITLE
【Feature】 路由配置可以外置吗？像nginx规则一样可以include？

### ISSUE THREAD

**Issue by kkkgo** [v2ray/v2ray-core#1567]
像nginx规则一样可以include？方便维护，场景比如可以外置ipip库方便更新，比如手动维护的地址列表自动下载更新。在官网文档没看到有这个功能，就来提个Feature。

**Comment by kslr** [comment]
Ip在geoip库，数据来自maxmind. 另一个是Domain -list-community

**Comment by kkkgo** [comment]
我知道，我之前搜索过源码发现了，我是知道里面的geodat和dlcdat是外置的，但这些数据不一定是我想要的，比如我想用用ipip的数据CIDR（精确到city），或者自己有一些应用或者游戏地址或者内网应用需要不同的路由，Domain-list-community并不一定适合每个人，个人也不好随便“污染（贡献）“这些列表，如果可以include自己的配置的话会方便很多。

**Comment by kkkgo** [comment]
> Ip在geoip库，数据来自maxmind. 另一个是Domain-list-community 你可以下载这些数据

如果可以外置的话，甚至可以直接用其他应用维护的地址，例如：https://github.com/FQrabbit/SSTap-Rule/tree/master/rules

**Comment by kkkgo** [comment]
另外一个我想提的Feature是，可以import一个或者一组CIDR list或者domain list，然后单独对这个list进行再处理路由，比如有一组某游戏所有的CIDR，里面有台服日服欧服等，使用geoip判断country后分配到不同的outbound，或者根据域名正则再分配等等，这样维护性方便了很多很多。
还有个Feature我想提的是，如果还能对不同的outbound进行速度限制，流量统计能支持统计域名或者ip地址的流量就好了
另外Blackhole的状态码可以自定义就好了，比如某些场景返回200
最后想问下（提个Feature）balancerTag的策略是随机的吗？是否支持故障转移或者按比例分配？
一次提的东西有点多，不好意思

**Comment by kkkgo** [comment]
再提两个：
希望增加路由策略优先级，当适配多条策略的时候很有用；
geoip希望增加地区支持比如asia（AS），增加ipv6支持（指ipv6流量only，比如geoipv6:JP）

**Comment by VictoriaRaymond** [comment]
目前你提的关于外置路由的需求全部都可以能过自定义geosite和geoip解决。你可以选择向 geoip 和 domain-list-community 发起 PR，或者维护一份私有的版本。这些功能 core 都已经支持了。

其它的功能请分别提交不同的 feature request。

**Comment by kkkgo** [comment]
> 目前你提的关于外置路由的需求全部都可以能过自定义geosite和geoip解决。你可以选择向 geoip 和 domain-list-community 发起 PR，或者维护一份私有的版本。这些功能 core 都已经支持了。
> 
> 其它的功能请分别提交不同的 feature request。

官方文档暂无自定义geosite和geoip的操作方法？维护一份私有的版本有难度，首先需要生成dlc.dat？另外domainlist只能是domain，貌似无法加入CIDR？对于geoip，具体应用的具体ip段也不是指定country能解决的，无法满足需求。
举个例子：对于像这种list，如何用自定义geosite和geoip解决？：
https://github.com/FQrabbit/SSTap-Rule/tree/master/rules

**Comment by kkkgo** [comment]
以上总共提了8点feature：
>1、路由配置可以外置 像nginx规则一样可以include
2、可以import一个或者一组CIDR list或者domain list，然后【单独对这个list进行再处理路由】，比如有一组某游戏所有的CIDR，里面有台服日服欧服等，使用geoip判断country后分配到不同的outbound，或者根据域名正则再分配等等，这样维护性方便了很多很多。
3、希望增加路由策略优先级，当适配多条策略的时候很有用（目前文档说明是随机）
4、balancerTag的策略是随机的吗？希望支持故障转移或者按比例分配
5、geoip希望增加地区支持比如asia（AS），增加ipv6支持（指ipv6流量only，比如geoipv6:JP）
6、对不同的outbound进行速度限制，流量统计能支持统计域名或者ip地址的流量
7、Blackhole的状态码可以自定义就好了，比如某些场景返回200
8、sniffing目前是只支持识别bittorrent吗？如果能识别更多协议就更好了，比如ssh，rdp，dns，ftp等等

如果1无法满足，2应该也做不到，剩下的需求不知道是否合理，合理的话我再另外开feature request。

**Comment by VictoriaRaymond** [comment]
2 你可以自定义一个 geosite 或者 geoip。配置文件中是可以加载外部文件的。
3 路由优先级是从上到下，并不是随机
4 应该已经有相关的 issue 了
5 和 2 一样
其它的你分别开不同的 feature request 吧

**Comment by kkkgo** [comment]
>自定义一个 geosite 或者 geoip。配置文件中是可以加载外部文件的

官方文档暂无操作方法或者示例，希望增加示例；

关于第二点我可能表述的不够清楚，目前的v2ray路由规则逻辑是这样的：
ip/domain -> list匹配到出口tag1 ->出口tag1
也就是需要人工先确定tag（出口）再处理list（逻辑上就是你需要先人工把你的同一个出口的ip/domain放在同一个tag里）
而第二点我想要的逻辑是：
程序启动时把一个指定的list里的ip/domain按照指定的规则分类到指定的出口tag，这样就无需人工处理维护，极大提高了维护便利性。

举例，list1里面有上几千行的CIDR，list2有上几千行的domain，并且更新比较频繁，
我需要的效果是，把list1里面的日本ip走日本tag，香港ip走香港tag，list2里面的tw后缀走台湾tag。
那么我需要一个个把list1里面的日本IP分离出来，再写到同一个日本tag里面，一个个把list1里面的香港IP分离出来，再写到同一个香港tag里面，一个个把list2里面的tw后缀分离出来，再写到同一个台湾tag里面

如果实现了第2点，我只需要写以下规则：
规则 
>把”list1“里的geoip:jp走tagjp，
”list1“里的geoip:hk走taghk，
"list2"里的domain:tw走tagtw

这样就无需把list1 list2需要走的出口一个个人工分出来，只需要写几条规则即可。

**Comment by VictoriaRaymond** [comment]
这个和现有的 geosite 和 geoip 的逻辑有什么区别？无非是你需要一个自定义的 .dat 文件而已。你可以看一下 geoip 和 domain-list-community 下的 main.go 文件。自己生成自己需要的 .dat 即可。

至于自定义的 .dat 文件里面的内容怎么分配，看上去你的需求和目前的结构兼容。你需要的是一个预处理程序。上述两个文件都是基于 protobuf 格式，几乎所有的编程语言都可以操作。按需求自己写一个预处理程序即可。

**Comment by kkkgo** [comment]
> 这个和现有的 geosite 和 geoip 的逻辑有什么区别？无非是你需要一个自定义的 .dat 文件而已。你可以看一下 geoip 和 domain-list-community 下的 main.go 文件。自己生成自己需要的 .dat 即可。
> 
> 至于自定义的 .dat 文件里面的内容怎么分配，看上去你的需求和目前的结构兼容。你需要的是一个预处理程序。上述两个文件都是基于 protobuf 格式，几乎所有的编程语言都可以操作。按需求自己写一个预处理程序即可。

嗯，你说的对，是预处理程序，如果官方无法支持只能自己去看main.go和自己写预处理程序了，不过这个门槛对只会使用程序的普通人来说可能有点高，如果能直接集成到core里面就简便很多，分享配置也比较方便（无需同时分享一份预处理程序）。当然官方保持程序简洁不支持也是合理的，谢谢解答。

**Comment by kkkgo** [comment]
还有个场景（或者说是Feature），希望能使用外置的（或者在线的，实现启动时自动更新）Switchy规则，虽然目前路由规则只能识别到域名，但根据计划：
https://github.com/v2ray/v2ray-core/issues/1256
https://github.com/v2ray/v2ray-core/issues/1398
将来是可以适配到URL的，这意味着Switchy规则理论上是可以完美兼容的，如果可以直接用外置的Switchy规则灵活性将大大提高，另外还能直接外置adblock规则而无需繁杂的转换。

**Comment by kkkgo** [comment]
另外根据https://github.com/v2ray/v2ray-core/issues/329 ，了解到官方不会直接使用gfwlist，那么外置适配Switchy规则就是一个很好的解决方案？
