### ISSUE TITLE
客户端被查杀

### ISSUE THREAD

**Issue by gohomo** [v2ray/v2ray-core#157]
win10环境下，win10自带杀软报木马查杀了v2ray客户端，添加信任及替换客户端后闪退，无法再打开。另，服务端添加shadowsocks协议后，shadowsocks客户端无法连接，日志显示连接被积极拒绝。

**Comment by gohomo** [comment]
已解决，是端口问题，我改回单端口后正常打开，动态端口后报毒及闪退

**Comment by gohomo** [comment]
{
  "port": 33333,
  "log" : {
    "access": "",
    "error": "",
    "loglevel": "warning"        
  },
  "inbound": {
    "protocol": "vmess",    
    "settings": {
      "clients": [
        {
          "id": "3b2aaf4e-4117-4bee-8c7e-bcb97bc65dcf",
          "alterId": 64,
          "level": 1
        }
      ]
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "inboundDetour": [
    {
      "protocol": "shadowsocks",
      "port": 44444,
      "settings": {
        "method": "aes-256-cfb",
        "password": "nn07710771",
        "udp": false
		"level": 1
      }
    }
  ],
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}

**Comment by v2ray** [comment]
你的动态端口的配置是怎样的？我在 Windows 10 上无法重现被查杀的情况。

**Comment by gohomo** [comment]
服务商和客户端的端口那我都改成33300-33333的形式，然后客户端就报木马，查看官网教程后修正才恢复

**Comment by gohomo** [comment]
我贴的服务商设置里ss协议的设置有错误的地方吗？原来我已经安装有ss，不知道是否有影响，但我原来安装的ss是可以用的

**Comment by v2ray** [comment]
你的 ss 配置，"udp: false" 后面少了一个逗号，不知道是不是你所指的错误。

**Comment by gohomo** [comment]
udp: false添加,后依然用不了，另官网WIKI上也是没有,的

**Comment by milanolarry** [comment]
v2ray 的公众服务器 (v2ray.cool) 是在北京，不能排除它是木马程序的可能。
