### ISSUE TITLE
[Feature Request]流量统计能支持统计域名或者ip地址的流量

### ISSUE THREAD

**Issue by kkkgo** [v2ray/v2ray-core#1570]
流量统计能支持统计域名或者ip地址的流量

**Comment by joviqiao** [comment]
我想知道现有API能不能一次把一个 email 的上下行流量加一起的结果返回回来？

**Comment by ix64** [comment]
> 我想知道现有API能不能一次把一个 email 的上下行流量加一起的结果返回回来？

API里面的 StatsService.QueryStats
