### ISSUE TITLE
[Feature Request]sniffing识别更多协议

### ISSUE THREAD

**Issue by kkkgo** [v2ray/v2ray-core#1573]
比如ssh，rdp，dns，ftp，smtp，imap等等

**Comment by VictoriaRaymond** [comment]
你要说明你需要哪个协议，并阐述理由。否则这个issue就像”提升v2ray性能”一样，没有可操作性。

**Comment by kkkgo** [comment]
SMTP\IMAP\POP3协议，用于阻止邮件滥发 防止垃圾邮件滥用或者对指定的域名或者IP仅进行代理收发邮件

**Comment by christolan** [comment]
很想问一下sniffing的作用到底是什么？我看了手册没有看懂，自己尝试着关掉也没发现有任何区别，很费解。

**Comment by kkkgo** [comment]
目前是从流量中探测出域名，用于路由规则或者其他功能。另外支持探测出bt协议，在路由规则里可以把他block掉或者指定到某一出口。这些在文档的路由配置里面有提到。
>一个数组，数组内每一个元素表示一种协议。当某一个协议匹配当前连接的流量时，此规则生效。必须开启入站代理中的sniffing选项。

https://github.com/v2ray/manual/blob/a47e56a0941cfbcd06a54680596e7a75e8abf4e0/zh_cn/chapter_02/03_routing.md

**Comment by christolan** [comment]
@kkkgo 原来如此，受教。

我之前v2ray-core开启socks:1080代理之后，配置好系统代理只能上一部分网站，比如Google就上不了，但是我用core开启http:8080代理就一切正常。我以为sniffing的作用是能识别http流量并转换成socks流量，然而并非如此，所以就对sniffing的作用产生了疑问。

话说回来，不知道是否了解为什么系统socks代理不能正常上Google，而proxy switch omega使用socks代理却可以？

**Comment by kkkgo** [comment]
> @kkkgo 原来如此，受教。
> 
> 我之前v2ray-core开启socks:1080代理之后，配置好系统代理只能上一部分网站，比如Google就上不了，但是我用core开启http:8080代理就一切正常。我以为sniffing的作用是能识别http流量并转换成socks流量，然而并非如此，所以就对sniffing的作用产生了疑问。
> 
> 话说回来，不知道是否了解为什么系统socks代理不能正常上Google，而proxy switch omega使用socks代理却可以？

@christolan 这个问题我不清楚，建议你[另开一个issue](https://github.com/v2ray/v2ray-core/issues/new/choose)讨论。如果你是Windows的话，自带的socks支持好像有问题，你可以在v2ray里面添加配置一个[http入站代理](https://github.com/v2ray/manual/blob/master/zh_cn/chapter_02/protocols/http.md)，很多常见的代理客户端也是外挂privoxy来开启http代理给Windows用。

**Comment by christolan** [comment]
@kkkgo 与我的猜想差不多，我的解决方式也是socks与http都开启，不是什么大问题，我就不再另提issue了。谢谢解答。

**Comment by kxmp** [comment]
请问现在流量探测支持dns么

**Comment by StoneMoe** [comment]
> 你要说明你需要哪个协议，并阐述理由。否则这个issue就像”提升v2ray性能”一样，没有可操作性。

就DNS来说，可以用来在透明代理中劫持所有端口的DNS请求而不是仅通过53端口来判断是否为DNS
