### ISSUE TITLE
arm windows版本报错

### ISSUE THREAD

**Issue by Coolkids** [v2ray/v2ray-core#158]
![bug_info](https://cloud.githubusercontent.com/assets/1288503/15625893/684c749a-24e9-11e6-97a2-85c3fa1c3a1e.png)

具体表现是psv1000 3.6系统 使用http代理后做互联网连接测试 其他正常浏览使用暂时没测试出来异常

**Comment by v2ray** [comment]
这是 HTTP 代理的一个已知问题，会在 1.14 修复。

**Comment by v2ray** [comment]
1.14 已发布，请测试。

**Comment by Coolkids** [comment]
多谢  等下回去测试

**Comment by Coolkids** [comment]
测试没报错. 3Q
