### ISSUE TITLE
v2ray不支持tls v1.3？

### ISSUE THREAD

**Issue by timorpic** [v2ray/v2ray-core#1582]
Please describe the new feature you want in detail.
使用Nginx转发tls v1.3流量失败，改名tls v1.2没问题

**Comment by updater1234** [comment]
v2ray现在不支持tls v1.3，不过很快就支持了。毕竟go1.12也已经发布了。

**Comment by njjpx** [comment]
同等待

**Comment by PHCSJC** [comment]
同等待+1

**Comment by sunsan05** [comment]
同等待+1

**Comment by kotori2** [comment]
#1576 dumplicated
