### ISSUE TITLE
配置文件config.json添加json schema文件

### ISSUE THREAD

**Issue by vonhezhou** [v2ray/v2ray-core#1585]
Please describe the new feature you want in detail.
json schema目前还在标准化阶段。如果能够加上支持，能够在支持的编辑器中做合法性校验，语法高亮和自动补全etc通用性强多了。xml很多人都嫌弃，但是配上xml schema，在合适的编辑器里，跟写代码一样的

**Comment by tjLEIIQM3** [comment]
校验方面
core内部用的是protobuf已经有一些校验措施，再加一层schema感觉多余。
客户端方面，最终配置还是交给core，既然core有校验，再加一层schema也是多余。

高亮补全方面
core是不会理这些的。
然后我所知道的客户端里面，除了一个不存在的win版带点编辑功能外，其他的都算不上有编辑功能，更不要提高亮补全了。

当然，我并不是说schema不好，只是觉得让core或者客户端来做这个事情都不合适。
最好是经常使用这个功能人开个repo出来，跟着core同步更新。
或者请求最近出来的那个专门做配置编辑器的项目添加这功能会比较合适。

**Comment by vonhezhou** [comment]
哦，我也是想表达这个想法，可能是表达的不好。core本身可以不用修改任何东西。只是需要开发者把这个schema文件给出来。这样，用户可以使用其它编辑器(比如vim/vs code这样的)来方便且不易出错的方式写配置文件,甚至可以另外开发gui的配置工具。

**Comment by cwxyz007** [comment]
根据 [官方文档](https://www.v2ray.com/chapter_02/01_overview.html) 写了大部分，后续有空会继续补充，没写全的地方都加了 `todo`，欢迎 fork 补充，修正 ~

https://gist.github.com/cwxyz007/4e6dd96774a2ef12a989c884eebe03ab#file-v2ray-schema-json

**Comment by vonhezhou** [comment]
赞赞赞
