### ISSUE TITLE
JAVA 通过 Grpc API 调用添加用户接口没有返回值

### ISSUE THREAD

**Issue by AXslashl** [v2ray/v2ray-core#1586]
我用grpc的时候 如果填入重复的邮箱 会有异常提示已存在某个用户，当我填入邮箱正常的时候就没有任何响应，我怎么判断我是否添加用户成功，最终用v2rayN测试的时候 发现 配置文件中原本配置的用户可以连接没有任何问题，但是自己调用API添加的用户 V2rayN客户端和服务器 不停的握手握手握手，然后断开 然后循环。请问一下这个怎么办

**Comment by joviqiao** [comment]
都不说下怎么解决的呀。。。

**Comment by joviqiao** [comment]
@AXslashl
