### ISSUE TITLE
A unified platform for anti-censorship. main: failed to load config:  > v2ray.com/core/main/confloader/external: config file not readable > open : no such file or directory

### ISSUE THREAD

**Issue by LiosWong** [v2ray/v2ray-core#1587]
v2ray version : V2Ray 4.18.0 (Po) 20190228
os : Debian GNU/Linux 9.7 (stretch)

安装成功后,执行·``sudo ./v2ray stop``后,报错:
V2Ray 4.18.0 (Po) 20190228
A unified platform for `anti-censorship.`
main: failed to load config:  > v2ray.com/core/main/confloader/external: config file not readable > open : no such file or directory

**Comment by kslr** [comment]
-config=绝对路径

**Comment by esverde** [comment]
更改config.jdon的权限即可，
sudo chmod 666 /etc/v2ray/*

**Comment by esverde** [comment]
更改config.json的权限即可，
sudo chmod 666 /etc/v2ray/*

**Comment by Kurphysn** [comment]
> 

你好啊，我碰到了一样的问题，请教一下具体如何操作呢

**Comment by dmaon** [comment]
转到首选项/内核设置并将 v2ray 核心资产和可执行路径更改为您的 2ray 核心目录，您可以从此地址下载 v2ray-core
[](https://github.com/jiangxufeng/v2rayL/releases/download/2.1.3/v2ray-core.tar)
