### ISSUE TITLE
v2ray 以后是否会支持MPTCP

### ISSUE THREAD

**Issue by cjjdaq** [v2ray/v2ray-core#1589]
Please describe the new feature you want in detail.
v2ray 以后是否会支持MPTCP？

**Comment by Ariselia** [comment]
能否详细说明一下需要支持的理由以及可能带来的提升？

**Comment by ccboxes** [comment]
用QUIC可以达到相同的效果。

**Comment by cjjdaq** [comment]
quic用的udp，qos的厉害。

**Comment by daiaji** [comment]
> quic用的udp，qos的厉害。

问题不大HTTP/3要推了
网络运行商应该不会作死螳臂挡车
