### ISSUE TITLE
能否实现 reject 的功能呢(直接拒绝请求)

### ISSUE THREAD

**Issue by lostsnow** [v2ray/v2ray-core#159]
如果能直接 reject 的话 应该就可以 AD block 了(可以简单的加 domian/ip 的规则就行)
现在的 blockhole 试了下 貌似请求会一直 hang 在那 有可能会阻塞浏览器请求

**Comment by v2ray** [comment]
客户端配置是怎样的？Chrome + SwitchyOmega + Socks?

**Comment by lostsnow** [comment]
类似这样的吧(或者如 firefox+foxyproxy+socks) 想屏蔽广告肯定要让客户端全部流量走 v2ray, 然后通过 v2ray reject 请求

**Comment by v2ray** [comment]
我要试一下，理论上 blockhole 可以做到这样的效果。

**Comment by v2ray** [comment]
试了一下，blackhole 没办法回复 HTTP 数据包，只是单纯关闭连接，这时候 Chrome 会尝试重连，于是就等在那里了。回复 HTTP 数据包功能貌似只能做在 HTTP 代理里面，现在还不支持。

**Comment by lostsnow** [comment]
内置 dns 不知道能不能实现呢, 我试了把域名解析成127.0.0.1 但是好像没有效果(依然是正常访问), 不知道配置是不是有问题, 客户端版本是 1.14

```json
{
  //...

  "outboundDetour": [
    //...
    {
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP"
      },
      "tag": "adblock"
    }
  ],
  "dns": {
    "hosts": {
      "baidu.com": "127.0.0.1",
      "www.baidu.com": "127.0.0.1"
    },
    "servers": [
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "domain": [
            "baidu.com",
            "www.baidu.com"
          ],
          "outboundTag": "adblock"
        },
        //...
      ]
    }
  }
}
```

**Comment by v2ray** [comment]
你可以把 loglevel 设成 info 看一下是不是浏览器把 baidu.com 解析成 IP 之后再传进来的。你的配置没有问题。但是我试下来，Chrome 依然会重试。

**Comment by lostsnow** [comment]
嗯 确实还是会重试 大概看了下 surge 貌似用的是 http 代理实现的 他同时开了两个端口 一个 socks 另外一个就是 http 代理

**Comment by v2ray** [comment]
Will add a configurable feature into blackhole. Blackhole will be able to reply with a HTTP response.

**Comment by v2ray** [comment]
会在下一版本中发布
