### ISSUE TITLE
DNS hosts 不生效 谁给个配置参考一下

### ISSUE THREAD

**Issue by dft2000** [v2ray/v2ray-core#1591]
我目前的配置：
"dns": {
        "hosts": {
            "domain:baidu.com": "127.0.0.1",
	    "domain:www.baidu.com":"127.0.0.1"
        },
		"servers": [
            "8.8.8.8",
            "localhost"
        ]
  }
路由策略：
"routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
	    {
            "type": "field",
            "ip": [
                "8.8.8.8"
            ],
            "outboundTag": "proxy"
        },
        {
          "type": "field",
          "ip": [
            "geoip:Private",
			"geoip:cn"
          ],
          "outboundTag": "direct"
        }
     ]
  }
我是要把baidu.com定向到127.0.0.1
但实际上没有生效，访问了直接路由了！
那位能帮帮忙。

**Comment by kslr** [comment]
请阅读
https://www.v2ray.com/chapter_02/04_dns.html
https://www.v2ray.com/chapter_02/03_routing.html
