### ISSUE TITLE
geosite:cn部分无效

### ISSUE THREAD

**Issue by davidfromtheeast** [v2ray/v2ray-core#1594]
Edit:
geosite:cn包括一批结尾以cn结束的域名吧，也就是tld-cn，不过经我测试，路由规则里加入geosite:cn直连后，以cn结尾的网站走的是代理，并没有直连。

这个问题我在其他一些软件的域名规则中也遇到过，好像*.cn这种泛域名规则效果都不好。

**Comment by Chandler-Lu** [comment]
你从哪看的`geosite:cn`是以cn结尾的域名了。。这就是个常见国内网站的列表。。

**Comment by InoriHeart** [comment]
https://v2ray.com/chapter_02/03_routing.html#dlc

cn: 相当于 geolocation-cn 和 tld-cn 的合集。

geolocation-cn: 包含了常见的国内站点的域名。
tld-cn: 包含了所有 .cn 和 .中国 结尾的域名。

这样看 好像有点奇怪？

**Comment by davidfromtheeast** [comment]
> https://v2ray.com/chapter_02/03_routing.html#dlc
> 
> cn: 相当于 geolocation-cn 和 tld-cn 的合集。
> 
> geolocation-cn: 包含了常见的国内站点的域名。
> tld-cn: 包含了所有 .cn 和 .中国 结尾的域名。
> 
> 这样看 好像有点奇怪？

对，我有点粗心，但就是这个意思。
我再试试geosite:tld-cn，看看结果。
