### ISSUE TITLE
[Feature Request]可以提供插件支持吗？

### ISSUE THREAD

**Issue by RaymanNg** [v2ray/v2ray-core#1598]
相关Issue #828 

请问V2Ray有计划提供插件编程的接口吗？

Feature Request的原因
我这边的ISP（恶心的中国移动）经常间歇性屏蔽海外网站，表现为同一个海外网站（例如StackOverflow），上午能连接，到了下午又不能连接，这样的话我经常要切换代理，非常麻烦。
因此我想实现一个类似于[cow](https://github.com/cyfdecyf/cow)的功能，能够先用direct 方式探测目标网站，失败（timeout）后自动切换到代理访问。
cow这个项目已经年久失修了，不太好用了，而且像这种小众功能我觉得还是做成插件比较好。
我希望能尝试一下在V2ray中实现一个类似的插件，请问V2Ray的开发者们有计划提供插件编程接口吗？

**Comment by kslr** [comment]
写一个中继不就好了？COW不就是这个原理呢

**Comment by RaymanNg** [comment]
> 写一个中继不就好了？COW不就是这个原理呢

你的意思就是这样吧？
浏览器 <--> 自己写一个 proxy server <--> V2Ray client <--> V2Ray server

当然自行写一个proxy server 作为中继也是一种办法，只是我觉得要是能够通过插件的形式复用V2Ray的代码进行处理就更好了

**Comment by kslr** [comment]
你要复用什么代码呢？做一个检测不是更简单

**Comment by RaymanNg** [comment]
好的，我有空尝试一下
