### ISSUE TITLE
v2ray-core/spec/guide.md 配置文件中关于引用外部配置路径的描述，可能需要补充

### ISSUE THREAD

**Issue by narcotics726** [v2ray/v2ray-core#16]
经测试，**在Windows 10下**，vpoint_socks_vmess.json中`inbound.file` 以及 `outbound.file`的路径同样需要填写绝对路径。将这三个文件放在同一目录下，然后填写`fileName` 或 `./fileName` 并没有作用，在运行server时报错：
`[Error]Unable to read config file open out_vmess.json: The system cannot find the file specified.`

改写为绝对路径后，一切正常。

测试环境：
> PointA: Windows 10 x64, go version 1.5.1 
PointB: Ubuntu 14.04.1 LTS x86, go version 1.5.1

**Comment by narcotics726** [comment]
PS: 感谢您的付出！

**Comment by falseen** [comment]
是的，win7也是。

**Comment by v2ray** [comment]
Fixed in 2b7fdef2031b14743f8a38c52cc6b957f398d31e， 原因是我用错了 API。

**Comment by v2ray** [comment]
另外我发现 Windows 貌似不支持 SOCKS5 代理，开了一个新的 bug (#20) 来跟踪这件事。
