### ISSUE TITLE
难道"address"处不是设置vps的ip的地方吗？

### ISSUE THREAD

**Issue by luckypoem** [v2ray/v2ray-core#160]
我下载了https://github.com/v2ray/v2ray-core/releases/download/v1.14/v2ray-macos.zip ，
打开config.json,看到了"address": "v2ray.cool" ，但是我ping v2ray.cool得到的IP为220.181.57.217，此ip并非用v2ray-macos.zip里面的v2ray翻墙所得到的ip,为什么？难道"address"处不是设置vps的ip或主机名的地方吗？

**Comment by v2ray** [comment]
是的，address 的确是服务器的 IP（或域名），但是为了保护服务器的安全， V2Ray 的官方服务器设置了两层转发。如果你自己用的话，在 address 里填上你的服务器地址即可。
