### ISSUE TITLE
内存消耗过高，直至耗尽后IO升高，CPU占用升高

### ISSUE THREAD

**Issue by ivyshow** [v2ray/v2ray-core#1601]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
4.9-4.14

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
500用户机场

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
一段时间后，内存占用过高，最后内存耗尽后，IO升高，CPU负载超负荷
以前不常见，最近用户到400多后，每天都有这样的VM出现，甚至昨晚2C2G的VDS也出现这个情况
并且部分VM并没有流量，也会在一定时间后出现这个问题
现在只能每日半夜和晚高峰前重启一次v2ray保证稳定。

"bufferSize": 0,  这个参数也有个疑问，官方文档里这里0是禁用，并且设置后会替换环境变量
但是环境变量这个参数0又是无限制

出现故障的VM监控图
CPU
![image](https://user-images.githubusercontent.com/46221123/54244595-5070dd00-4568-11e9-8ed0-1199c271c33a.png)

内存
![image](https://user-images.githubusercontent.com/46221123/54244608-5ebef900-4568-11e9-84f4-b41d93d210c6.png)
![image](https://user-images.githubusercontent.com/46221123/54244614-68e0f780-4568-11e9-8cc9-7b76248c671f.png)
![image](https://user-images.githubusercontent.com/46221123/54244621-726a5f80-4568-11e9-8415-d1327c7d41ed.png)

IO
![image](https://user-images.githubusercontent.com/46221123/54244640-80b87b80-4568-11e9-8002-7a70142bf319.png)

感谢解答

4) 你期待看到的正确表现是怎样的？
稳定运行，内存消耗降低

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
{
  "log": {
    "loglevel": "debug"
/*    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log"
*/
  },

  "api": {
    "services": [
      "HandlerService",
      "StatsService"
    ],
    "tag": "api"
  },

  "stats": { },
  "inbounds": [
 
    {
      "listen": "127.0.0.1",
      "port": 20086,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    },

    { 
      "port": 32000, 
      "tag": "ivy",
      "listen": "127.0.0.1", 
      "protocol": "vmess",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }, 
      "allocate": {
        "strategy": "always"
      },
      "settings": {
        "udp": true, 
        "clients": []
      }, 
      "streamSettings": {
        "network": "ws", 
        "security": "auto",
        "wsSettings": {
          "allowInsecure": false,
          "connectionReuse": true,
          "path": "/"
        },
        "sockopt": {
        "mark": 0,
        "tcpFastOpen": true
        }
      }
    }

  ], 
 
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": { }
    },

    {
      "protocol": "blackhole", 
      "settings": { }, 
      "tag": "blocked"
    }
  ],

  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "inboundTag": [
            "api"
          ],
          "outboundTag": "api",
          "type": "field"
        },

        {
          "type": "field",
          "outboundTag": "block",
          "protocol": [
            "bittorrent"
          ]
        },

        {
          "type": "field", 
          "ip": [
            "0.0.0.0/8", 
            "10.0.0.0/8", 
            "100.64.0.0/10", 
            "127.0.0.0/8", 
            "169.254.0.0/16", 
            "172.16.0.0/12", 
            "192.0.0.0/24", 
            "192.0.2.0/24", 
            "192.168.0.0/16", 
            "198.18.0.0/15", 
            "198.51.100.0/24", 
            "203.0.113.0/24", 
            "::1/128", 
            "fc00::/7", 
            "fe80::/10"
          ], 
          "outboundTag": "blocked"
        }
      ]
    }
  },

  "policy": {
    "levels": {
      "0": {
        "handshake": 4,
        "connIdle": 300,
        "uplinkOnly": 5,
        "downlinkOnly": 5,
        "bufferSize": 0,
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    }    
  }
}#

```

客户端配置:

```javascript
TLS+Websocket
服务端Nginx前置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript

```

客户端错误日志:

```javascript
无
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by kslr** [comment]
本地策略高于环境变量，并且也不建议使用了。
https://github.com/v2ray/v2ray-core/blob/4eb2b5e607eba50c08aed62ca15b3c6f06583f3a/infra/conf/policy.go#L40

你能进一步提供系统内存数据吗？

**Comment by ivyshow** [comment]
@kslr 需要我提供什么数据呢？

**Comment by lp123sun** [comment]
> @kslr 需要我提供什么数据呢？

监控的软件是什么呢，我也想试试

**Comment by Xyncgas** [comment]
我在windows上面开bt走v2ray的代理在500连接数左右5MB/s下载上传不计左右，内存能到700MB，不知道正不正常我用的是websocket + tls 然后wsSettings用了connection reuse

**Comment by bitching** [comment]
win10客户端提供代理给qBittorrent，内存经常飙到4G+去。。

**Comment by YFLEA** [comment]
我不是程序猿，MacBook Pro，自从下了v2ray电脑风扇就一直转，发烫也很严重，就想翻个墙而已。去看cpu显示说有个v2ray UHelper运行占了110%多。请问有什么解决方法呀？？（纯电脑小白，都不知道如何才能彻底删除软件的那种
