### ISSUE TITLE
几个问题？

### ISSUE THREAD

**Issue by hktalent** [v2ray/v2ray-core#1606]
# 1、配置文件中的id能否通过uuidgen，每次动态生成？
```
没有特别的含义和要求嘛？
整个配置文件中的id必须一致吗？
服务器端端id和客户端的id哪些必须相同呢？
看了官网，没有找到答案

如果server和client不需要一致，且无意义，能否程序自动生成，无需配置？
```
# 2、Dockerfile
https://hub.docker.com/r/v2ray/official/dockerfile
```
为什么前面基于
FROM ubuntu:latest as builder
为什么不前后一致是
FROM alpine:latest


且，没有直接从
gi t clone https://github.com/v2ray/v2ray-core/
那么，这个是可信源吗？
```

**Comment by hktalent** [comment]
https://toutyrater.github.io/app/docker-deploy-v2ray.html

**Comment by hktalent** [comment]
uuidgen linux系统命令

**Comment by kslr** [comment]
1. https://v2ray.com/chapter_02/protocols/vmess.html
2. 编译和运行，请看release/install-release.sh
