### ISSUE TITLE
怎么没有config.json文件？

### ISSUE THREAD

**Issue by luckypoem** [v2ray/v2ray-core#161]
root@AR:~/v2ray-v1.14-linux-32# ls
systemd  systemv  v2ray  vpoint_socks_vmess.json  vpoint_vmess_freedom.json
root@AR:~/v2ray-v1.14-linux-32# chmod 755 v2ray
root@AR:~/v2ray-v1.14-linux-32# ./v2ray
V2Ray v1.14 (New Order) 20160528
An unified platform for anti-censorship.
2016/06/01 00:18:40 [Error]Failed to read server config file (/root/v2ray-v1.14-linux-32/config.json): /root/v2ray-v1.14-linux-32/config.jsonopen /root/v2ray-v1.14-linux-32/config.json: no such file or directory
2016/06/01 00:18:40 [Error]Failed to read config file (/root/v2ray-v1.14-linux-32/config.json): /root/v2ray-v1.14-linux-32/config.jsonopen /root/v2ray-v1.14-linux-32/config.json: no such file or directory
root@AR:~/v2ray-v1.14-linux-32#

**Comment by wtlusvm** [comment]
你没有用一键安装脚本吗？

**Comment by luckypoem** [comment]
hi。 哪里有一键安装脚本？我是在linux vps上，下载https://github.com/v2ray/v2ray-core/releases/download/v1.14/v2ray-linux-32.zip ：

wget https://github.com/v2ray/v2ray-core/releases/download/v1.14/v2ray-linux-32.zip
unzip v2ray-linux-32.zip
cd v2ray-v1.14-linux-32
root@AR:~/v2ray-v1.14-linux-32# ls
systemd systemv v2ray vpoint_socks_vmess.json vpoint_vmess_freedom.json
root@AR:~/v2ray-v1.14-linux-32#

v2ray-v1.14-linux-32目录里没有config.json文件。怎么回事呢？

**Comment by yxxyun** [comment]
https://www.v2ray.com/zh_cn/chapter_01/install.html

**Comment by luckypoem** [comment]
hi
@v2ray ,
我按照https://raw.githubusercontent.com/v2ray/v2ray-core/master/release/install.sh，在我的vps上操作如下：
root@shc:~# GO_AMD64=https://storage.googleapis.com/golang/go1.6.2.linux-amd64.tar.gz
root@shc:~# ARCH=$(uname -m)
root@shc:~# GO_CUR=${GO_AMD64}
root@shc:~# curl -o go_latest.tar.gz ${GO_CUR}
root@shc:~# tar zxvf go_latest.tar.gz -C /usr/local/
root@shc:~# export PATH=$PATH:/usr/local/go/bin/
root@shc:~# mkdir v2ray
root@shc:~# export GOPATH=~/v2ray 
root@shc:~# cd ~/v2ray
root@shc:~/v2ray# go get github.com/v2ray/v2ray-core 
root@shc:~/v2ray# ls
pkg  src
root@shc:~/v2ray# go install github.com/v2ray/v2ray-core/tools/build
root@shc:~/v2ray# ls
bin  pkg  src
root@shc:~/v2ray# ls bin
build
root@shc:~/v2ray# ./bin/build
Building V2Ray (custom) for linux amd64
src/github.com/v2ray/v2ray-core/app/dns/nameserver.go:15:2: cannot find package "github.com/miekg/dns" in any of:
	/usr/local/go/src/github.com/miekg/dns (from $GOROOT)
	/root/v2ray/src/github.com/miekg/dns (from $GOPATH)

Unable to build V2Ray: exit status 1
root@shc:~/v2ray# go get github.com/miekg/dns
root@shc:~/v2ray# ./bin/build
Building V2Ray (custom) for linux amd64
root@shc:~/v2ray# 

在root@shc:~/v2ray# ./bin/build显示为Building V2Ray (custom) for linux amd64，这一次build成功。
root@shc:~/v2ray# ls bin
build  v2ray-custom-linux-64
root@shc:~/v2ray# cd bin
root@shc:~/v2ray/bin# ls
build  v2ray-custom-linux-64
root@shc:~/v2ray/bin# cd v2ray-custom-linux-64
root@shc:~/v2ray/bin/v2ray-custom-linux-64# ls
systemd  systemv  v2ray  vpoint_socks_vmess.json  vpoint_vmess_freedom.json
(这里的v2ray就是可执行文件)
root@shc:~/v2ray/bin/v2ray-custom-linux-64#
root@shc:~/v2ray/bin/v2ray-custom-linux-64# ./v2ray
V2Ray 1.14 (New Order) Custom
An unified platform for anti-censorship.
2016/06/02 03:13:40 [Error]Failed to read server config file (/root/v2ray/bin/v2ray-custom-linux-64/config.json): /root/v2ray/bin/v2ray-custom-linux-64/config.jsonopen /root/v2ray/bin/v2ray-custom-linux-64/config.json: no such file or directory
2016/06/02 03:13:40 [Error]Failed to read config file (/root/v2ray/bin/v2ray-custom-linux-64/config.json): /root/v2ray/bin/v2ray-custom-linux-64/config.jsonopen /root/v2ray/bin/v2ray-custom-linux-64/config.json: no such file or directory
root@shc:~/v2ray/bin/v2ray-custom-linux-64# ls
systemd  systemv  v2ray  vpoint_socks_vmess.json  vpoint_vmess_freedom.json
root@shc:~/v2ray/bin/v2ray-custom-linux-64# cp vpoint_vmess_freedom.json config.json
root@shc:~/v2ray/bin/v2ray-custom-linux-64# ls
config.json  systemv  vpoint_socks_vmess.json
systemd      v2ray    vpoint_vmess_freedom.json
(打开config.json，发现里面access和error的值为/var/log/v2ray/access.log,
/var/log/v2ray/error.log ,而/var/log/里面没有v2ray目录，所以需要新建v2ray目录）
root@shc:~/v2ray/bin/v2ray-custom-linux-64# mkdir /var/log/v2ray/
root@shc:~/v2ray/bin/v2ray-custom-linux-64# ./v2ray
V2Ray 1.14 (New Order) Custom
An unified platform for anti-censorship.
（这一次运行v2ray成功）

**Comment by luckypoem** [comment]
或者不编译v2ray-core,直接在linux vps上，下载可执行文件包https://github.com/v2ray/v2ray-core/releases/download/v1.14/v2ray-linux-32.zip ：

wget https://github.com/v2ray/v2ray-core/releases/download/v1.14/v2ray-linux-32.zip
unzip v2ray-linux-32.zip
cd v2ray-v1.14-linux-32
root@AR:~/v2ray-v1.14-linux-32# ls
systemd systemv v2ray vpoint_socks_vmess.json vpoint_vmess_freedom.json
root@AR:~/v2ray-v1.14-linux-32# cp vpoint_vmess_freedom.json config.json
root@AR:~/v2ray-v1.14-linux-32# ls
config.json systemd systemv v2ray vpoint_socks_vmess.json vpoint_vmess_freedom.json
root@AR:~/v2ray-v1.14-linux-32# mkdir /var/log/v2ray/
root@AR:~/v2ray-v1.14-linux-32# ./v2ray
V2Ray 1.14 (New Order) Custom
An unified platform for anti-censorship.
（这一次运行v2ray也成功了）

**Comment by luckypoem** [comment]
不过在mac客户机器上，我修改了客户机器上的config.json,把里面的v2ray.cool替换为自己的vps的ip，然后运行v2ray,出现如下错误，怎么解决呢？？
yudeMacBook-Air:~ brite$ /Users/brite/Downloads/v2ray-v1.14-macos/v2ray ; exit;
V2Ray v1.14 (New Order) 20160528
An unified platform for anti-censorship.
2016/06/03 10:36:47 [Warning]Point server started on port 1082
2016/06/03 10:37:19 [Error]Raw: Failed to read response header: read tcp 192.168.1.102:61727->103.206.98.170:10086: read: connection reset by peer
2016/06/03 10:37:19 [Warning]VMessOut: Failed to read response: read tcp 192.168.1.102:61727->103.206.98.170:10086: read: connection reset by peer
2016/06/03 10:37:27 [Error]Raw: Failed to read response header: read tcp 192.168.1.102:61730->103.206.98.170:10086: read: connection reset by peer
2016/06/03 10:37:27 [Warning]VMessOut: Failed to read response: read tcp 192.168.1.102:61730->103.206.98.170:10086: read: connection reset by peer
2016/06/03 10:37:36 [Error]Raw: Failed to read response header: read tcp 192.168.1.102:61733->103.206.98.170:10086: read: connection reset by peer
2016/06/03 10:37:36 [Warning]VMessOut: Failed to read response: read tcp 192.168.1.102:61733->103.206.98.170:10086: read: connection reset by peer
2016/06/03 10:37:41 [Error]Raw: Failed to read response header: EOF
2016/06/03 10:37:41 [Warning]VMessOut: Failed to read response: EOF

**Comment by wtlusvm** [comment]
你的IP和端口都暴露了……

**Comment by luckypoem** [comment]
@wtlusvm ,IP和端口都暴露了会怎样呢？别人能连上吗？

**Comment by v2ray** [comment]
connection reset 通常是指 1) 你的 VPS IP 被墙了； 2) VPS 的防火墙配置（或者 V2Ray 端口）不正确。

**Comment by luckypoem** [comment]
hi。
我的VPS IP 没有被墙。V2Ray 端口我使用的是默认的10086，难道它需要修改吗？
至于VPS 的防火墙配置应该没问题吧，我用其他翻墙手段一点问题没有。要不owner建议一下我该运行哪些iptables命令呢？

**Comment by luckypoem** [comment]
hi.

yudeMacBook-Air:v2ray-v1.14-macos brite$ ls
config.json		v2ray
yudeMacBook-Air:v2ray-v1.14-macos brite$ ./v2ray --config=config.json
V2Ray v1.14 (New Order) 20160528
An unified platform for anti-censorship.
2016/06/03 19:14:22 [Warning]Point server started on port 1082

在终端中运行命令 ./v2ray --config=config.json ，这样就能顺利翻墙了。先前我是在finder中，双击v2ray文件而遇错。看样子，只能在终端中运行命令 才行。

**Comment by wtlusvm** [comment]
看样子是没有加配置文件参数导致的？
