### ISSUE TITLE
请添加服务器域名解析能自定义dns解析支持

### ISSUE THREAD

**Issue by lbr-app** [v2ray/v2ray-core#1613]
请添加服务器域名解析能自定义dns解析支持，不然在Android上会出现transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://vzsos.com/bilibili):  > dial tcp: lookup vzsos.com on [::1]:53: read udp [::1]:50331->[::1]:53: read: connection refused v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://vzsos.com/bilibili):  > dial tcp: lookup vzsos.com on [::1]:53: read udp [::1]:58665->[::1]:53: read: connection refused v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://vzsos.com/bilibili):  > dial tcp: lookup vzsos.com on [::1]:53: read udp [::1]:54983->[::1]:53: read: connection refused] > v2ray.com/core/common/retry: all retry attempts failed。

**Comment by lbr-app** [comment]
不知道会不会会被关。

**Comment by Sak94664** [comment]
记得v2ray已经内置了这样的功能了。

hmm，在termux环境下建立resolv.conf然后在proot下跑没问题
或者：
配置个freedom出口，domainStrategy设置为UseIP，rules内配置一下让proxy的域名走那个freedom出口也行。

相关文档：
DNS
https://v2ray.com/chapter_02/04_dns.html
Freedom:
https://v2ray.com/chapter_02/protocols/freedom.html

在网上多查一下，多翻一下文档就行了。

**Comment by lbr-app** [comment]
> 记得v2ray已经内置了这样的功能了。
> 刚试了一下貌似还是不行
> 
> hmm，在termux环境下建立resolv.conf然后在proot下跑没问题
> 或者：
> 配置个freedom出口，domainStrategy设置为UseIP，rules内配置一下让proxy的域名走那个freedom出口也行。
> 
> 相关文档：
> DNS
> https://v2ray.com/chapter_02/04_dns.html
> Freedom:
> https://v2ray.com/chapter_02/protocols/freedom.html
> 
> 在网上多查一下，多翻一下文档就行了。

Android 5.0之下用不了termux。

**Comment by kslr** [comment]
但可以使用adb

**Comment by lbr-app** [comment]
> 但可以使用亚行

什么？adb跟这个问题无关吧。
