### ISSUE TITLE
发现一个疑似能解决断流的方法

### ISSUE THREAD

**Issue by FunDoor** [v2ray/v2ray-core#1615]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
服务端 4.18.0，客户端 4.3 (Po) 20181109
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
这两天开始打开网页后的一瞬间断流，只显示出网页的一小部分
4) 你期待看到的正确表现是怎样的？
流畅观看网页视频
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    {
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbound": {
    "port": *****,
    "listen": null,
    "protocol": "vmess",
    "sniffing": null,
    "settings": {
      "auth": null,
      "udp": false,
      "ip": null,
      "clients": [
        {
          "id": "********************",
          "alterId": 64,
          "email": "*******",
          "security": null
        }
      ]
    },
    "streamSettings": {
      "network": "kcp",
      "security": "",
      "tlsSettings": null,
      "tcpSettings": null,
      "kcpSettings": {
        "mtu": 1350,
        "tti": 50,
        "uplinkCapacity": 100,
        "downlinkCapacity": 100,
        "congestion": true,
        "readBufferSize": 2,
        "writeBufferSize": 2,
        "header": {
          "type": "srtp",
          "request": null,
          "response": null
        }
      },
      "wsSettings": null,
      "httpSettings": null
    }
  },
  "outbound": {
    "tag": null,
    "protocol": "freedom",
    "settings": null,
    "streamSettings": null,
    "mux": null
  },
  "inboundDetour": null,
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": null,
      "tag": "blocked"
    }
  ],
  "dns": null,
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": null,
      "rules": [
        {
          "type": "field",
          "port": null,
          "outboundTag": "blocked",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "domain": null
        }
      ]
    }
  }
}
```

疑似能解决断流的方法：
使用Bitvise SSH Client，通过本地v2ray的socks5代理地址连接到vps，然后打开这款SSH软件自带的socks5代理功能，最后浏览器通过这个代理浏览网页
测试结果浏览网页视频都很流畅。

**Comment by kslr** [comment]
这是错觉，我建议你取消kcp尝试。

你现在只是通过Socket 5传输

Tim <notifications@github.com> 于 2019年3月23日周六 15:49写道：

**Comment by FunDoor** [comment]
从系统的任务管理器观察流量，这确实是v2ray的流量，更何况，我服务端只开了kcp，没开tcp，而且，我的服务器除了22端口，没开放其它tcp端口。

另外，取消kcp，而直接用TCP，一样断流。

**Comment by kslr** [comment]
Bitvise SSH Client，通过本地v2ray的socks5代理地址连接到vps

ssh client -> v2ray server -> remote -> enable socket5 proxy
socket5 -> ssh client -> remote

我理解的对吗？

**Comment by FunDoor** [comment]
v2ray server和ssh server 是同一个服务器。
1 . 建立通道 
local ssh client->local v2ray socket5（port 1080）->local v2ray client->remote v2ray server->remote ssh server，
2. 成功登录ssh后，打开local ssh client的socket5代理功能(port 2080)
3. 浏览器设置连接socket5代理（port 2080）
4. 不断流了

**Comment by kslr** [comment]
https://www.bitvise.com/ssh-client#port-forwarding 根据软件文档，是通过端口转发实现，所以这和v2ray之间的数据没有关系。

这套方案在我还是萌新的时候就被广泛使用了，现在也都被标记了，你这个属于漏网之鱼的错觉。

我建议你继续从断流这个问题下手优化配置文件。

**Comment by FunDoor** [comment]
之前一直都用得好好的，也没改过配置文件。前几天就开始断流了，windows和安卓都一样断流。
我都不明白了，使用我这个解决方法后，数据完全就是经过v2ray传送的，怎么会跟v2ray没关系。
断流的朋友可以试试我这个方法。
至于优化配置文件，配置文件是v2rayN直接复制过去的，不知道还能怎么优化。

**Comment by kslr** [comment]
有很多SSH port forwarding方面的资料。

我看到你使用了Kcp ，断流也是它的经典问题。你可以参照kcptun 文档，也可以换其他协议。比如websocket
