### ISSUE TITLE
Failed to start App|Log: failed to initialize access logger > open /var/log/v2ray/access.log: no such file or directory

### ISSUE THREAD

**Issue by xiaoyang666** [v2ray/v2ray-core#1617]
when i run  sudo ./v2ray --config=config.json

Failed to start App|Log: failed to initialize access logger > open /var/log/v2ray/access.log: no such file or directory
3.4.0
{

  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
   "port": 12345,
   "protocol": "dokodemo-door",
   "domainOverride": ["http", "tls"],
   "settings": {
     "network": "tcp,udp",
     "followRedirect": true
   },
   "sniffing": {
     "enabled": true,
     "destOverride": ["http", "tls"]
   }
  },

  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "000000",
          "port": 443,
          "users": [
            {
              "id": "00000000",
              "alterId": 64
            }
          ]
        }
      ]
    },

    "streamSettings": {
        "network": "ws",
        "security": "tls",
       "sockopt": {
       "mark": 255}
                     }
         },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "port": "54-79",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "81-442",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "444-65535",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "domain": [
            "gc.kis.scr.kaspersky-labs.com"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        }
      ]
    }
  }
}

**Comment by kslr** [comment]
```
failed to initialize access logger > open /var/log/v2ray/access.log: no such file or directory
```
需要保证目录和文件存在
