### ISSUE TITLE
手机正常连接，windows无法正常上网

### ISSUE THREAD

**Issue by kckm** [v2ray/v2ray-core#1618]
这是客户端的log

> 2019/03/2508:38:00 [Debug] v2ray.com/core/app/log: Logger started
2019/03/25 08:38:00 [Warning] v2ray.com/core: V2Ray 4.18.0 started
2019/03/25 08:38:04 [Info] [2304673658] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [www.google.co.jp:443] with URL [//www.google.co.jp:443]
2019/03/25 08:38:04 [Info] [2304673658] v2ray.com/core/app/dispatcher: sniffed domain: www.google.co.jp
2019/03/25 08:38:04 [Info] [2304673658] v2ray.com/core/app/dispatcher: default route for tcp:www.google.co.jp:443
2019/03/25 08:38:04 [Info] [2304673658] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:0.0.0.0:80
2019/03/25 08:38:04 [Info] [2304673658] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.google.co.jp:443 via tcp:0.0.0.0:80
2019/03/25 08:38:04 [Info] [2304673658] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > read tcp 192.168.1.3:52801->0.0.0.0:80: wsarecv: An existing connection was forcibly closed by the remote host.
2019/03/25 08:38:04 [Info] [2304673658] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > io: read/write on closed pipe
2019/03/25 08:38:04 [Info] [3775267485] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [www.google.co.jp:443] with URL [//www.google.co.jp:443]
2019/03/25 08:38:04 [Info] [3775267485] v2ray.com/core/app/dispatcher: sniffed domain: www.google.co.jp
2019/03/25 08:38:04 [Info] [3775267485] v2ray.com/core/app/dispatcher: default route for tcp:www.google.co.jp:443
2019/03/25 08:38:04 [Info] [3775267485] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:0.0.0.0:80
2019/03/25 08:38:04 [Info] [3775267485] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.google.co.jp:443 via tcp:0.0.0.0:80
2019/03/25 08:38:04 [Info] [3775267485] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > read tcp 192.168.1.3:52803->0.0.0.0:80: wsarecv: An existing connection was forcibly closed by the remote host.
2019/03/25 08:38:04 [Info] [3775267485] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > io: read/write on closed pipe
2019/03/25 08:38:04 [Info] [430783410] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [www.google.co.jp:443] with URL [//www.google.co.jp:443]
2019/03/25 08:38:04 [Info] [430783410] v2ray.com/core/app/dispatcher: default route for tcp:www.google.co.jp:443
2019/03/25 08:38:04 [Info] [430783410] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:0.0.0.0:80
2019/03/25 08:38:04 [Info] [430783410] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.google.co.jp:443 via tcp:0.0.0.0:80
2019/03/25 08:38:04 [Info] [430783410] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to write first payload > EOF
2019/03/25 08:38:04 [Info] [430783410] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > io: read/write on closed pipe

请问这些log说明了什么？0.0.0.0打码是server的ip。
具体网页显示：
无法安全地连接到此页面
这可能是因为该站点使用过期的或不安全的 TLS 安全设置。如果这种情况持续发生，请与网站的所有者联系。
系统重装了也这样，时间也基本没有误差。

**Comment by kckm** [comment]
> 2019/03/25 09:59:59 [Info] [1337139539] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: invalid request from 9.9.9.9:52979 > v2ray.com/core/proxy/vmess/encoding: failed to read request header > read tcp 0.0.0.0:80->9.9.9.9:52979: read: connection reset by peer

服务端的log，9999是客户端，0000是服务端

**Comment by kckm** [comment]
_123_

**Comment by xiaokangwang** [comment]
建议你贴一下服务器端日志

**Comment by kckm** [comment]
我用的是host伪装，发现只要把host的域名去掉就可以正常连接，但是加上host域名就会出现以上情况

**Comment by xiaokangwang** [comment]
是不是因为服务器端没有被正确设置呢？

**Comment by kckm** [comment]
> {
  "inbounds": [
    {
      "port": 80,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "xxx",
            "level": 1,
            "alterId": 4
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "tcpSettings": {
          "header": {
            "type": "http",
            "response": {
              "version": "1.1",
              "status": "200",
              "reason": "OK",
              "headers": {
                "Content-Type": ["application/octet-stream", "application/x-msdownload", "text/html", "application/x-shockwave-flash"],
                "Transfer-Encoding": ["chunked"],
                "Connection": ["keep-alive"],
                "Pragma": "no-cache"
              }
            }
          }
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ] 
}

**Comment by xiaokangwang** [comment]
服务器端收到设置中没有伪装会拒绝连接的

**Comment by kckm** [comment]
服务端配置一直没改过，之前windows也是可以正常使用的，只是昨天才出现问题

**Comment by xiaokangwang** [comment]
嗯。。。但是以现在的情况来看我并不能确定具体的问题，因此并不能给出建议的解决方法

**Comment by kkkdxy** [comment]
我也出现了类似情况，满屏EOF……
`D:\v2ray-windows-64\v2ray-v4.18.0-windows-64>v2ray -config=1.json
V2Ray 4.18.0 (Po) 20190228
A unified platform for anti-censorship.
2019/03/27 21:30:53 [Debug] v2ray.com/core/app/log: Logger started
2019/03/27 21:30:53 [Warning] v2ray.com/core: V2Ray 4.18.0 started
2019/03/27 21:30:56 [Info] [973038369] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [www.google.com:443] with URL [//www.google.com:443]
2019/03/27 21:30:56 [Info] [3188700427] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [lh3.googleusercontent.com:443] with URL [//lh3.googleusercontent.com:443]
2019/03/27 21:30:56 [Info] [973038369] v2ray.com/core/app/dispatcher: taking detour [proxy] for [tcp:www.google.com:443]
2019/03/27 21:30:56 [Info] [3438268] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [www.gstatic.com:443] with URL [//www.gstatic.com:443]
2019/03/27 21:30:56 [Info] [4065178402] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [apis.google.com:443] with URL [//apis.google.com:443]
2019/03/27 21:30:56 [Info] [4065178402] v2ray.com/core/app/dispatcher: taking detour [proxy] for [tcp:apis.google.com:443]
2019/03/27 21:30:56 [Info] [2087899815] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [clients5.google.com:443] with URL [//clients5.google.com:443]
2019/03/27 21:30:56 [Info] [2087899815] v2ray.com/core/app/dispatcher: taking detour [proxy] for [tcp:clients5.google.com:443]
2019/03/27 21:30:56 127.0.0.1:58246 accepted //www.google.com:443
2019/03/27 21:30:56 127.0.0.1:58247 accepted //lh3.googleusercontent.com:443
2019/03/27 21:30:56 127.0.0.1:58248 accepted //www.gstatic.com:443
2019/03/27 21:30:56 127.0.0.1:58249 accepted //apis.google.com:443
2019/03/27 21:30:56 127.0.0.1:58250 accepted //clients5.google.com:443
2019/03/27 21:30:56 [Info] [3188700427] v2ray.com/core/app/dispatcher: default route for tcp:lh3.googleusercontent.com:443
2019/03/27 21:30:56 [Info] [3438268] v2ray.com/core/app/dispatcher: taking detour [direct] for [tcp:www.gstatic.com:443]
2019/03/27 21:30:56 [Info] [3438268] v2ray.com/core/proxy/freedom: opening connection to tcp:www.gstatic.com:443
2019/03/27 21:30:56 [Info] [3438268] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.gstatic.com:443
2019/03/27 21:30:57 [Info] [973038369] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via tcp:sangshi.******************.pw:443
2019/03/27 21:30:57 [Info] [3188700427] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:lh3.googleusercontent.com:443 via tcp:sangshi.******************.pw:443
2019/03/27 21:30:57 [Info] [2087899815] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:clients5.google.com:443 via tcp:sangshi.******************.pw:443
2019/03/27 21:30:57 [Info] [4065178402] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:apis.google.com:443 via tcp:sangshi.******************.pw:443
2019/03/27 21:30:57 [Info] [3188700427] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2019/03/27 21:30:57 [Info] [973038369] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2019/03/27 21:30:57 [Info] [973038369] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > io: read/write on closed pipe
2019/03/27 21:30:57 [Info] [2087899815] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
ction ends > context canceled
`
客户端：
`{
  "log": {
    "loglevel": "debug"
  },
  "inbound": {
    "listen": "127.0.0.1",
    "port": 1080,
    "protocol": "http",
    "settings": {
      "auth": "noauth"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "*****************",
          "port": 443,
          "users": [
            {
              "id": "******************************",
              "alterId": 64,
              "security": "auto",
              "level": 0
            }
          ]
        }
      ]
    },
    "tag": "proxy",
    "streamSettings": {
      "network": "h2",
      "security": "tls",
      "httpSettings": {
        "path": "/var/www/ray"
      }
    },
    "mux": {
      "enabled": true,
      "concurrency": 8
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "block"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "geoip:private"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "domain": [
            "regexp:(^|\\.)google(\\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?){1,2}$",
            "regexp:(^|\\.)googleapis(\\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?){1,2}$"
          ],
          "outboundTag": "proxy"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        }
      ]
    }
  }
}`

服务端：
`{
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 443,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "91718d61-18e1-4dcc-8756-e30d75970131",
          "level": 1,
          "alterId": 64
        }
      ]
    },
    "streamSettings":{
       "network":"h2",
       "httpSettings": {
       "path": "/var/www/ray"
      },
       "security": "tls",
       "tlsSettings": {
       "certificates": [
          {
            "certificateFile": "/root/.acme.sh/sangshi.diunaxing.pw/fullchain.cer",
            "keyFile": "/root/.acme.sh/sangshi.diunaxing.pw/sangshi.diunaxing.pw.key"
          }
        ]
       }
     }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}
`

**Comment by xiaokangwang** [comment]
> 我也出现了类似情况，满屏EOF……
> 
> > D:\v2ray-windows-64\v2ray-v4.18.0-windows-64>v2ray -config=1.json
> > V2Ray 4.18.0 (Po) 20190228
> > A unified platform for anti-censorship.
> > 2019/03/27 21:30:53 [Debug] v2ray.com/core/app/log: Logger started
> > 2019/03/27 21:30:53 [Warning] v2ray.com/core: V2Ray 4.18.0 started
> > 2019/03/27 21:30:56 [Info] [973038369] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [www.google.com:443] with URL [//www.google.com:443]
> > 2019/03/27 21:30:56 [Info] [3188700427] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [lh3.googleusercontent.com:443] with URL [//lh3.googleusercontent.com:443]
> > 2019/03/27 21:30:56 [Info] [973038369] v2ray.com/core/app/dispatcher: taking detour [proxy] for [tcp:www.google.com:443]
> > 2019/03/27 21:30:56 [Info] [3438268] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [www.gstatic.com:443] with URL [//www.gstatic.com:443]
> > 2019/03/27 21:30:56 [Info] [4065178402] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [apis.google.com:443] with URL [//apis.google.com:443]
> > 2019/03/27 21:30:56 [Info] [4065178402] v2ray.com/core/app/dispatcher: taking detour [proxy] for [tcp:apis.google.com:443]
> > 2019/03/27 21:30:56 [Info] [2087899815] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [clients5.google.com:443] with URL [//clients5.google.com:443]
> > 2019/03/27 21:30:56 [Info] [2087899815] v2ray.com/core/app/dispatcher: taking detour [proxy] for [tcp:clients5.google.com:443]
> > 2019/03/27 21:30:56 127.0.0.1:58246 accepted //www.google.com:443
> > 2019/03/27 21:30:56 127.0.0.1:58247 accepted //lh3.googleusercontent.com:443
> > 2019/03/27 21:30:56 127.0.0.1:58248 accepted //www.gstatic.com:443
> > 2019/03/27 21:30:56 127.0.0.1:58249 accepted //apis.google.com:443
> > 2019/03/27 21:30:56 127.0.0.1:58250 accepted //clients5.google.com:443
> > 2019/03/27 21:30:56 [Info] [3188700427] v2ray.com/core/app/dispatcher: default route for tcp:lh3.googleusercontent.com:443
> > 2019/03/27 21:30:56 [Info] [3438268] v2ray.com/core/app/dispatcher: taking detour [direct] for [tcp:www.gstatic.com:443]
> > 2019/03/27 21:30:56 [Info] [3438268] v2ray.com/core/proxy/freedom: opening connection to tcp:www.gstatic.com:443
> > 2019/03/27 21:30:56 [Info] [3438268] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.gstatic.com:443
> > 2019/03/27 21:30:57 [Info] [973038369] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via tcp:sangshi.******************.pw:443
> > 2019/03/27 21:30:57 [Info] [3188700427] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:lh3.googleusercontent.com:443 via tcp:sangshi.******************.pw:443
> > 2019/03/27 21:30:57 [Info] [2087899815] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:clients5.google.com:443 via tcp:sangshi.******************.pw:443
> > 2019/03/27 21:30:57 [Info] [4065178402] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:apis.google.com:443 via tcp:sangshi.******************.pw:443
> > 2019/03/27 21:30:57 [Info] [3188700427] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
> > 2019/03/27 21:30:57 [Info] [973038369] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
> > 2019/03/27 21:30:57 [Info] [973038369] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > io: read/write on closed pipe
> > 2019/03/27 21:30:57 [Info] [2087899815] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
> > ction ends > context canceled
> 
> 客户端：
> 
> > {
> > "log": {
> > "loglevel": "debug"
> > },
> > "inbound": {
> > "listen": "127.0.0.1",
> > "port": 1080,
> > "protocol": "http",
> > "settings": {
> > "auth": "noauth"
> > }
> > },
> > "outbound": {
> > "protocol": "vmess",
> > "settings": {
> > "vnext": [
> > {
> > "address": "_****************",
> > "port": 443,
> > "users": [
> > {
> > "id": "****************_*************",
> > "alterId": 64,
> > "security": "auto",
> > "level": 0
> > }
> > ]
> > }
> > ]
> > },
> > "tag": "proxy",
> > "streamSettings": {
> > "network": "h2",
> > "security": "tls",
> > "httpSettings": {
> > "path": "/var/www/ray"
> > }
> > },
> > "mux": {
> > "enabled": true,
> > "concurrency": 8
> > }
> > },
> > "outboundDetour": [
> > {
> > "protocol": "freedom",
> > "settings": {},
> > "tag": "direct"
> > },
> > {
> > "protocol": "blackhole",
> > "settings": {},
> > "tag": "block"
> > }
> > ],
> > "routing": {
> > "strategy": "rules",
> > "settings": {
> > "domainStrategy": "IPIfNonMatch",
> > "rules": [
> > {
> > "type": "field",
> > "ip": [
> > "geoip:private"
> > ],
> > "outboundTag": "direct"
> > },
> > {
> > "type": "field",
> > "domain": [
> > "regexp:(^|\.)google(\.[a-zA-Z0-9](%5Ba-zA-Z0-9-%5D%7B0,61%7D%5Ba-zA-Z0-9%5D)?){1,2}$",
> > "regexp:(^|\.)googleapis(\.[a-zA-Z0-9](%5Ba-zA-Z0-9-%5D%7B0,61%7D%5Ba-zA-Z0-9%5D)?){1,2}$"
> > ],
> > "outboundTag": "proxy"
> > },
> > {
> > "type": "chinaip",
> > "outboundTag": "direct"
> > }
> > ]
> > }
> > }
> > }
> 
> 服务端：
> 
> > {
> > "log" : {
> > "access": "/var/log/v2ray/access.log",
> > "error": "/var/log/v2ray/error.log",
> > "loglevel": "warning"
> > },
> > "inbound": {
> > "port": 443,
> > "protocol": "vmess",
> > "settings": {
> > "clients": [
> > {
> > "id": "********************************",
> > "level": 1,
> > "alterId": 64
> > }
> > ]
> > },
> > "streamSettings":{
> > "network":"h2",
> > "httpSettings": {
> > "path": "/var/www/ray"
> > },
> > "security": "tls",
> > "tlsSettings": {
> > "certificates": [
> > {
> > "certificateFile": "/root/.acme.sh/sangshi************.pw/fullchain.cer",
> > "keyFile": "/root/.acme.sh/sangshi.**********.pw/sangshi.**************.pw.key"
> > }
> > ]
> > }
> > }
> > },
> > "outbound": {
> > "protocol": "freedom",
> > "settings": {}
> > },
> > "outboundDetour": [
> > {
> > "protocol": "blackhole",
> > "settings": {},
> > "tag": "blocked"
> > }
> > ],
> > "routing": {
> > "strategy": "rules",
> > "settings": {
> > "rules": [
> > {
> > "type": "field",
> > "ip": [
> > "0.0.0.0/8",
> > "10.0.0.0/8",
> > "100.64.0.0/10",
> > "127.0.0.0/8",
> > "169.254.0.0/16",
> > "172.16.0.0/12",
> > "192.0.0.0/24",
> > "192.0.2.0/24",
> > "192.168.0.0/16",
> > "198.18.0.0/15",
> > "198.51.100.0/24",
> > "203.0.113.0/24",
> > "::1/128",
> > "fc00::/7",
> > "fe80::/10"
> > ],
> > "outboundTag": "blocked"
> > }
> > ]
> > }
> > }
> > }

请您提供服务器端日志信息以便分析错误原因

**Comment by kkkdxy** [comment]
> 2019/03/27 10:02:48 myip:58651 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/03/27 10:02:49  myip:58651 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/03/27 10:02:49  myip:58651 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/03/27 10:02:50  myip:58651 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/03/27 10:02:51  myip:58651 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/03/27 10:02:52  myip:58651 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/03/27 10:02:54  myip:58651 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/03/27 10:03:00  myip:58651 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/03/27 10:03:01  myip:58651 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/03/27 10:03:04  myip:58651 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/03/27 10:03:05  myip:58651 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user

**Comment by kkkdxy** [comment]
好了，我这边问题解决了……我觉得像证书问题，我用的acme dns alias的方式更新……然后留意到服务端时间和本地时间相差2分钟，打开win10自动设置时间就ok了，手机端没问题大概是……手机默认从网络更新时间23333
