### ISSUE TITLE
能否把pac的计算放在v2ray客户端?

### ISSUE THREAD

**Issue by dboylx** [v2ray/v2ray-core#1619]
Please describe the new feature you want in detail.
能否把pac的计算放在v2ray客户端? 
这样就省的在终端上配制了，而且如果还能动态更新就更好了

**Comment by liuguangw** [comment]
v2rayw、v2rayn了解一下

**Comment by nicholascw** [comment]
feature request now goes to [v2ray/disscussion](https://github.com/v2ray/discussion/issues).
