### ISSUE TITLE
v2ray.exe打开后闪退

### ISSUE THREAD

**Issue by shuangyuxiaoyi** [v2ray/v2ray-core#1624]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
最新的，好像是4.18.0
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
客户端程序打开后闪退。
4) 你期待看到的正确表现是怎样的？
客户端程序打开后正常运行。
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:
{
  "inbounds": [{
    "port": ****, 
    "protocol": "vmess",
    "settings": {
      "clients": [
          { 
              "id": "9bc090b3-1524-44e4-bc8f-79172f04ce7c" ,
              "level": 0,
              "alterId": 4,
              "email": "love@v2ray.com"
           }
          ]
    }
  }],
  "outbounds": [{
    "protocol": "freedom",
    "settings": {}
  }]
}
```javascript
    // 在这里附上服务器端配置文件
```

客户端配置:
{
    "inbounds": [{
      "port": 1080,  
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": true
      }
    }],
    "outbounds": [{
      "protocol": "vmess",
      "settings": {
        "vnext": [{
          "address": "**********", 
          "port": ****,  
          "users": [
              {
                   "id": "9bc090b3-1524-44e4-bc8f-79172f04ce7c", 
                   "alterId": 4,
                   "security": "auto",
                   "level": 0
                }
            ]
        }]
      }
    },{
      "protocol": "freedom",
      "tag": "direct",
      "settings": {}
    }],
    "routing": {
      "domainStrategy": "IPOnDemand",
      "rules": [{
        "type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "direct"
      }]
    }
  }
```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:
无
```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:
不知道客户端的错误日志在什么位置，windows系统。
```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by shuangyuxiaoyi** [comment]
@kslr  这个标签和关闭问题是什么意思啊。。。我后来改了配置文件，用第三方网站生成的配置后，依然是闪退。 但我后来又下了个windows客户端，用火狐浏览器访问提示连接超时，但是客户端这边有生成日志。有个错误日志如下：
2019/03/31 23:53:41 [Warning] v2ray.com/core: V2Ray 4.18.0 started
2019/03/31 23:55:22 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 35.229.192.154:10086: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed
2019/03/31 23:55:47 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 35.229.192.154:10086: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by kslr** [comment]
请按照指南开issue，附上配置和日志

**Comment by iweixubin** [comment]
我的情况是运行着 ss 会闪退，把 ss 退了就可以运行了，希望能帮助路过的地球人~

**Comment by PampasGrass** [comment]
> 我的情况是运行着 ss 会闪退，把 ss 退了就可以运行了，希望能帮助路过的地球人~

按照这位老哥的方法解决了我的问题。

**Comment by bennetcq** [comment]
电脑升级后出现了v2ray.exe闪退，包括trojan.exe也是闪退。其他exe可以运行。后来把Microsoft Defender Application Guard卸载后就可以了。

**Comment by facenano** [comment]
应该重装就可以了。

bennetcq ***@***.***> 于2022年1月4日周二 09:34写道：
