### ISSUE TITLE
v2ray配置了dns后，win10系统的host文件中的内容无法生效

### ISSUE THREAD

**Issue by mmyz1234** [v2ray/v2ray-core#1626]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v4.18.0
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
使用Chrome通过VMess 代理浏览网页
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
v2ray配置了dns后，win10系统的host文件中的内容无法生效。
例如，在C:\Windows\System32\drivers\etc\hosts文件中配置了以下内容
192.168.10.10 project.test
在启动了v2ray代理后无法通过project.test访问要访问的内容，而通过192.168.10.10访问正常。
关闭v2ray代理后能通过project.test访问要访问的内容。
将192.168.10.10 project.test添加到v2ray的dns配置静态 IP 列表，启动v2ray代理后能通过project.test访问要访问的内容
4) 你期待看到的正确表现是怎样的？
在C:\Windows\System32\drivers\etc\hosts文件中配置了192.168.10.10 project.test后，无需再在v2ray配置文件中再次配置该host，启动v2ray代理后能通过project.test正常访问要访问的内容。
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 100,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "",
            "alterId": 4
          }
        ],
        "disableInsecureEncryption": false
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {
      },
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
      },
      "tag": "blocked"
    }
  ],
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked"
      }
    ]
  }
}
```

客户端配置:

```javascript
{
  "log": {
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 1080,
      "protocol": "http",
      "settings": {
        "timeout": 0,
        "allowTransparent": false
      },
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "",
            "port": 100,
            "users": [
              {
                "id": "",
                "alterId": 4,
                "security": "auto"
              }
            ]
          }
        ]
      }
    },
    {
      "protocol": "freedom",
      "settings": {
      },
      "tag": "direct"
    }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "ip": [
          "geoip:private",
          "geoip:cn"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "domain": [
          "geosite:cn"
        ],
        "outboundTag": "direct"
      }
    ]
  },
  "dns": {
    "servers": [
      "8.8.8.8",
      "localhost"
    ]
  }
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by kslr** [comment]
https://www.v2ray.com/chapter_02/03_routing.html

**Comment by kidlj** [comment]
https://www.v2ray.com/chapter_02/protocols/dns.html

**Comment by starryspace** [comment]
同样的问题，hosts文件的优先级不是应该最高的吗？
