### ISSUE TITLE
日志中能否增加Tag的登录信息

### ISSUE THREAD

**Issue by Jetranger** [v2ray/v2ray-core#1627]
Please describe the new feature you want in detail.
目前日志好像只是通过v2ray的一些流量情况，但是不能看出来是哪个端口或者哪个Tag的流量。
PS.能否在说明文档里稍微详细的讲解 一下如何通过Email进行流量统计。Thanks。

**Comment by kslr** [comment]
通过API收集
https://v2ray.com/chapter_02/stats.html
