### ISSUE TITLE
是否能支持如Shadowsockets自动代理模式?

### ISSUE THREAD

**Issue by winimi** [v2ray/v2ray-core#163]
如题，配置启动后，启用自动代理模式。然后增加默认协议和ss协议切换功能？

**Comment by v2ray** [comment]
“Shadowsockets” 是什么？“自动代理模式”又是什么？ Google 了两个名词似乎没有得到和你的描述相符的解释。

如果你是指类似 SwitchyOmega 那样根据 URL 自动判断代理的方式，现在 V2Ray 已可以通过内置的[路由功能](https://www.v2ray.com/zh_cn/chapter_02/03_routing.html)做到同样的效果。

如果你是指自动判断服务器使用的是什么协议然后自动切换，那么答案是不支持，并非所有的协议都有明显的特征可以用于自动识别。

**Comment by xiaokangwang** [comment]
他也可能是指自动设置操作系统的代理服务器配置。

**Comment by me2me2** [comment]
应该是指shadowsocks客户端的那种自动代理模式。开启此模式后，比如我在mac下，诸如tweetbot等客户端也能无需设置正常连接。但又不是全局，也不用依托第三方ProxyCap、Proxifier之类的代理软件。

有自动代理模式还是挺方便的，不然现在上个网，要开一堆的窗口，略尴尬。

**Comment by winimi** [comment]
@me2me2 说的是正确的，不好意思问题没有表达清楚。

**Comment by winimi** [comment]
@v2ray  我指的是mac版shadowsocks中的自动代理模式，我开启后根据需要访的服务器能不能直接访问，如果能直接访问则不走中转服务器，不能访问则通过代理去访问。不需要本地开个监听端口然后用一个浏览器专门通过这个端口访问屏蔽网络。再次抱歉一开始没表达清楚问题。

**Comment by Cenmrev** [comment]
可以试试这个 https://github.com/Cenmrev/V2RayX
~~不保证没bug~~

**Comment by me2me2** [comment]
@Cenmrev 严粽感谢！用老的gfwlist.js改了下替换pac.js，tweetbot等客户端正常访问。这下桌面干净多了~！

**Comment by v2ray** [comment]
这个功能将留给第三方客户端实现。
