### ISSUE TITLE
outbound 协议的 address 由谁负责解析？

### ISSUE THREAD

**Issue by yuzenan888** [v2ray/v2ray-core#1633]
> Discussion 得不到回复，所以发到这里，抱歉！

是系统设置的 DNS（非 V2Ray）吗？如果是的话，可不可以设定由 DnsObject 中的服务器负责解析？

**Comment by kslr** [comment]
是的，设置dns服务器地址

**Comment by yuzenan888** [comment]
嗯，谢谢！建议在文档里面说明一下。

**Comment by YLaido** [comment]
> 嗯，谢谢！建议在文档里面说明一下。
请问解决了吗？能说下大致怎么弄吗？搞个ddns一直不行，之后才发现是阿里自己dns太垃圾，目前解决方案是直接改系统的/etc/resolv.conf ,只是不知道会有什么副作用

**Comment by yuzenan888** [comment]
> > 嗯，谢谢！建议在文档里面说明一下。
> 
> 请问解决了吗？能说下大致怎么弄吗？搞个ddns一直不行，之后才发现是阿里自己dns太垃圾，目前解决方案是直接改系统的/etc/resolv.conf ,只是不知道会有什么副作用

解决了。修改这个 DNS 也只能修改  /etc/resolv.conf 了，不过设置 hosts 也是可以生效的。
