### ISSUE TITLE
能不能在access log 里加上 outbound的tag?

### ISSUE THREAD

**Issue by fcying** [v2ray/v2ray-core#1639]
虽然开 info log 可以看到. 不过那log太多了. 
整合到 access.log 里面看的比较清爽
像下面这样
```
tcp:127.0.0.1:2196 accepted tcp:avatars3.githubusercontent.com:443, detour [proxy]
tcp:127.0.0.1:2196 accepted tcp:www.baidu.com:443, detour [direct]
```

**Comment by kslr** [comment]
为什么？那level name做什么 有更加有力的说明吗

**Comment by fcying** [comment]
level name 调整的是 error.log 里面的细节部分吧, warning打印问题, info打印运行状态. 算是完整log吧, 不单单是网站的访问信息. 

access.log 是要访问网站的信息, 现在只打印了一条要访问的网站的地址, 加上outbound tag后看的比较完整 -- 通过哪条途径访问网站, 而且加这个也不会附加额外的log, 就同一行加几个字符就好了.

**Comment by zhang9709** [comment]
这个感觉不错

**Comment by fcying** [comment]
把access log 放到 routedDispatch 函数里面打印会有问题吗?
试了下 放到 routedDispatch 里面 加上 detourTag 能打印出数据. 
就是担心会不会有access log 却不跑 routedDispatch 的情况, 导致数据同步出错
