### ISSUE TITLE
socks代理报错 但是不影响使用

### ISSUE THREAD

**Issue by Coolkids** [v2ray/v2ray-core#164]
![bug-20160603](https://cloud.githubusercontent.com/assets/1288503/15769931/41570dfc-2992-11e6-9c9a-6eb2f5b8e52a.png)

具体操作:bittorrent 设置连接 - 代理服务器 类型socks5 使用代理进行主机名查询

另外端口映射这个功能走的流量是混淆加密过的么

**Comment by v2ray** [comment]
这个错误不重要，可以忽略。

取决于你的路由设置，由 VMess 转发的流量都是加密的。
