### ISSUE TITLE
[Feature Request] Support Endpoint #1569 as a configure format

### ISSUE THREAD

**Issue by xiaokangwang** [v2ray/v2ray-core#1645]
V2Ray endpoint configures format #1569 is being drafted.

We need to support endpoint as a configure format to simplify the configure process of V2Ray for an average user and promote the standardization of endpoint format.

The following work is needed:

 *   A parser for endpoint format
*    The code to convert endpoint format to pb format
 *   integrate endpoint format parser and converter into V2Ray

**Comment by tjLEIIQM3** [comment]
Annnnd, a json to endpoint converter.
Thank for your work in advance.

But still, i don't think map multilevel data into single-level data is the right way to go.
