### ISSUE TITLE
请支持一下windows phone 10! 

### ISSUE THREAD

**Issue by Xyncgas** [v2ray/v2ray-core#1648]
作为windows phone最后的作品lumia 950微软停止继续提供支持了，请在其生命的最后一段，让v2ray也能够在它上面运行，让这台手机能够为像我一样的人继续提供服务把v2ray用来提供二次生命给这台设备毕竟看视频不错的就是在墙内要是能出去我也能自己写软件来让它做看视频以外更多的事情

**Comment by nftbty** [comment]
有950怎么不刷个win10 arm64版，现在基本完美了，只有摄像头还不能用，最近识别sim卡了，已经可以打电话，很快就可以流量上网。完整版win10可以做更多事了。

**Comment by Leo-Mu** [comment]
> 有950怎么不刷个win10 arm64版，现在基本完美了，只有摄像头还不能用，最近识别sim卡了，已经可以打电话，很快就可以流量上网。完整版win10可以做更多事了。

正解！现在微软正在开发的 WCOS Windows Core Operating System 已经在适配 arm64 了，而且有 X86 模拟器可以运行大部分 win32 应用。足够让 v2ray 流畅使用了。

**Comment by daiaji** [comment]
貌似要越狱才能搞这搞那
那还不如用Win10
最多看看将来Golang的编译器能不能出Win-arm二进制文件
毕竟为了一个DIE OS浪费精力并不值得
