### ISSUE TITLE
http 的 inbound 没有记入 access log？

### ISSUE THREAD

**Issue by everpcpc** [v2ray/v2ray-core#165]
inbound 只有 http 一个，将 log level 改为 debug 和 info 之后 error.log 里的内容都是正常的，但是 access log 始终是空的。

**Comment by v2ray** [comment]
嗯，客户端的协议都还没写 access log，马上补。

**Comment by everpcpc** [comment]
got, thx~

**Comment by v2ray** [comment]
1.16 中增加了一些 access log，正常的连接都记录下来的，不正常的可能有一些没有记。
