### ISSUE TITLE
kcp设置 uplinkcapacity不起作用？设置2M还能跑到200M上行

### ISSUE THREAD

**Issue by 1265578519** [v2ray/v2ray-core#1652]
版本4.18
kcp设置 uplinkcapacity不起作用？设置2M还能跑到200M上行

测试地址 fast.com，在上行测速阶段，本地网络上传竟然可以达到200M，超过运营商提供大小导致网络拥堵。
tcp模式和ss上都没有这个问题。只存在kcp模式下。
![image](https://user-images.githubusercontent.com/6442439/56460350-0800d680-63d4-11e9-97b2-0e8466d5e7b8.png)

客户端配置信息
  "kcpItem": {
    "mtu": 1350,
    "tti": 50,
    "uplinkCapacity": 2,
    "downlinkCapacity": 20,
    "congestion": false,
    "readBufferSize": 2,
    "writeBufferSize": 2
  },

**Comment by kslr** [comment]
https://github.com/v2ray/v2ray-core/issues/460#issuecomment-346646123

**Comment by 1265578519** [comment]
有办法限制他吗。。不要超过运营商最大速率。

**Comment by kslr** [comment]
你试试设置uplinkCapacity到5

**Comment by 1265578519** [comment]
..没有效果，我上面贴了客户端配置信息，用的是2。

**Comment by GBVF** [comment]
我也是

**Comment by dongriljf** [comment]
试试这个
"mtu": 1420,
"tti": 100,
"uplinkCapacity": 2,
"downlinkCapacity": 20,
"congestion": true,
"readBufferSize": 1,
"writeBufferSize": 1,

**Comment by 1265578519** [comment]
楼上提供的方法没有效果，，，算了就这样吧。。毕竟UDP协议估计问题也不好修

**Comment by kslr** [comment]
先别关，有时间了就来处理这个问题

**Comment by changyp6** [comment]
一样的问题。downLink设置了有用，upLink设置了根本没用，直接跑飞掉。
在fast.com上测试，upload speed直接能到200M

**Comment by kslr** [comment]
4.22调整了一些参数

**Comment by 1265578519** [comment]
好的，感谢更新，有时间测一下，现在都没用kcp。。

**Comment by kbr3NwSZ6kFq25** [comment]
现在还有这个问题
