### ISSUE TITLE
能否增加nat端口监听穿透，工作在比特彗星BT网络中让他绿灯

### ISSUE THREAD

**Issue by 1265578519** [v2ray/v2ray-core#1653]
通过比特彗星BT客户端设置127.0.0.1 s5到v2ray，收到请求后，检查到端口打开请求，服务器同时打开端口并且进行端口数据流转发，实现端口开放绿灯，这个功能能否实现。

**Comment by kslr** [comment]
理论上你配置正确，绿灯会不会亮没有影响。

**Comment by 1265578519** [comment]
@kslr 有个问题就是，BT TCP传输中，一定要对方打开端口，除非客户端本身有UDP透传功能。
如果端口未打开，你的客户端只能从本地发起请求连接已打开的人，别人是连接不进来，会导致BT客户端的上传速度过低。当然下载基本影响大不。。主要是上传速率。因为这样别人连接不进来了。

**Comment by kslr** [comment]
你可以修改配置成双向出和入

**Comment by xiaokangwang** [comment]
现在貌似是没有实现动态的端口转发的。
你需要配置一个反向穿刺代理 https://www.v2ray.com/chapter_02/reverse.html
之后配置你的BT客户端监听这个端口

**Comment by 1265578519** [comment]
@xiaokangwang 好的，感谢，下班后研究下。
