### ISSUE TITLE
我希望能添加一个选项，强制使用服务端dns

### ISSUE THREAD

**Issue by 99junlin99** [v2ray/v2ray-core#1655]
我用v2ray 来配置shadowsocks（虽然我知道这样不太好的）。我用了dns解锁nf的服务———netflix-proxy，但是当我使用ss客户端连接v2ray时，服务端的dns似乎会被强制修改为客户端的dns，使得我的dns解锁完全不生效，希望能加个按钮来设置是否启用客户端覆盖服务端dns

**Comment by IceCodeNew** [comment]
用 v2ray 来配置 shadowsocks 没什么不好的。如果你对此存在疑虑，请考虑把代理加密方式改成 vmess。
说回正题，假如 Netflix 判断用户地理位置时会参考用户所使用的 DNS（对此我表示怀疑），那么首先你需要明确告诉大家 netflix-proxy 这个东西究竟是干啥的，因为这不是官方 v2ray 项目中存在的东西。
如果这个东西是哪里的机场主自己改出来的客户端，给你提供连接代理服务器的功能，那么你在官方项目的 GitHub 页提问题是浪费时间，你应该去找提供 netflix-proxy 的人寻求帮助。
最后，你可以考虑用 Proxifier 来管理电脑上所有软件产生的流量，因为 Proxifier 提供了一个选项来使得所有 DNS 解析请求都发往代理服务器进行解析。

**Comment by 99junlin99** [comment]
github可以搜索到netflix-proxy这个项目（https://github.com/ab77/netflix-proxy），具体流程，因为不是搞网络这方面的可能说不太清楚：大概是sniproxy反代netflix然后通过把服务器的dns改成那个反代的服务器ip，从而实现看nf，本质上可能是类似中转？客户端是使用安卓的ss，谷歌商店的那种，而且似乎仅有这一个客户端有问题（win版没测试）而且，当你把客户端dns改成与服务端一样的设置解锁服务商的ip的时候，nf便又可以正常观看，然后surge，surfboard以及clash这种都没有问题，初步判定是他们默认代理地址都用远程dns。稍后我可以上传一下access的日志，（可能我对网络方面确实不太了解，根据日志判断失败吧）access日志里写的便是我客户端（手机安卓版ss）的dns。（回宿舍后发下我的日志）另外不知道为啥配置ss的话我的access日志好像有点问题。。。（还有个小小疑惑，为啥在服务端配置ss加http混淆，客户端却没有这种选项（虽然我觉得可能是他们gui没做的缘故，我会去他们那里进行提问））

**Comment by 99junlin99** [comment]
[access.log](https://github.com/v2ray/v2ray-core/files/3102800/access.log)
我的accesslog,也不知道该遮挡点啥，大概没问题把

**Comment by 99junlin99** [comment]
顺便上传一份配置文件，后缀名修改为txt
[config.txt](https://github.com/v2ray/v2ray-core/files/3102841/config.txt)

**Comment by aishuidedabai** [comment]
NF 是根据ip来判断的，播放IP需原生IP，不可跳转

**Comment by nicholascw** [comment]
请查阅你的浏览器、应用程序或操作系统DNS设置。
