### ISSUE TITLE
[Feature Request] Avoid TLS fingerprint

### ISSUE THREAD

**Issue by emc2314** [v2ray/v2ray-core#1660]
The authors of  [The use of TLS in Censorship Circumvention](https://www.ndss-symposium.org/ndss-paper/the-use-of-tls-in-censorship-circumvention/) (NDSS 2019) develop a library called [uTLS](https://github.com/refraction-networking/utls), which is a fork of the Go standard TLS library. It can mimic the fingerprint of popular TLS client (e.g. Chrome), thus reducing the possibility to be detected.

**Comment by Xyncgas** [comment]
upvote !

**Comment by emc2314** [comment]
Note: Already integrated in commit c072d38e2c365f2966b18ae041f5c9ef820b2e53, but not enabled yet.
Sorry for disturbing, but may I ask what is experiment 8357? @DarienRaymond

**Comment by emc2314** [comment]
在```"tlsSettings"```中加入```"serverName": "experiment:8357"```即可开启 utls, 不知道为啥文档里没有
提到. 可能是不够文档或者不太愿意公开. 总之本 issue 关闭.

**Comment by emc2314** [comment]
仔细看了下, 功能的确还不完善... 只用了 utls 却没有更改指纹. 而且只有 tcp 支持, ws 并没有相关代码.

**Comment by emc2314** [comment]
要支持 ws 需要修改 gorilla/websocket 上游代码, 好难(
