### ISSUE TITLE
v2ray-windows-64 v4.18.1 v2ctl 报错

### ISSUE THREAD

**Issue by winds365** [v2ray/v2ray-core#1666]
跟4.18相同配置，win端报错
`main: failed to read config file: stdin: > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to read config file > internal error: polling on unsupported descriptor type`
用4.18的v2ctl替换可以正常运行
删除policy标签，routing标签只有一条，可以正常运行

**Comment by 0ee010f29436e240703012ce** [comment]
https://github.com/v2ray/v2ray-core/issues/1643#issuecomment-483076378

**Comment by kslr** [comment]
你先降级两个版本使用ctl 下一步修复这个问题
