### ISSUE TITLE
[Feature Request]支持从外部文件中读取hosts对象的域名列表

### ISSUE THREAD

**Issue by forever8938** [v2ray/v2ray-core#1669]
Please describe the new feature you want in detail.
路由功能中，domain可以从文件中读取，如ext:file:tag
https://www.v2ray.com/chapter_02/03_routing.html

内置DNS中，类似的hosts却不支持从文件中读取。而DNS服务器对象的domains支持。
https://www.v2ray.com/chapter_02/04_dns.html

请求支持从文件中加载内置DNS的hosts。这样的话，把gfwlist做成一个文件，给hosts读取，并解析到无效的IP，就可以隐藏DNS请求。配合sniffing，完全不需要查询被墙域名的IP。

**Comment by forever8938** [comment]
这个能支持吗？

**Comment by forever8938** [comment]
请求关注。这个应该是很容易实现，很合理的需求。

**Comment by forever8938** [comment]
请求关注。

**Comment by kslr** [comment]
这没有必要，做hosts维护成本很高，已经有成熟的DNS为什么不使用

**Comment by forever8938** [comment]
> 这没有必要，做hosts维护成本很高，已经有成熟的DNS为什么不使用

我的意思是按照现有的域名列表直接解析到无效IP，秒返回。反正都要sniff出域名，直接交给VPS去解析。dns服务器对象，路由对象都支持从外部文件中读取，为什么就hosts对象不支持？hosts对象可是从自带的geosite.dat里读取的。
https://steemit.com/cn/@v2ray/dns

**Comment by forever8938** [comment]
我的workground是直接把外部文件改名成geosite.dat，然后"geosite:gfw"访问，亲测可以。。。。。。

**Comment by kslr** [comment]
https://github.com/v2ray/v2ray-core/pull/1694

**Comment by forever8938** [comment]
亲测4.19.1，问题依然存在。
#1694解决的事rules对象不能从外部文件读取IP的问题，和hosts对象关系不大。
