### ISSUE TITLE
让部分流量走另一个服务器

### ISSUE THREAD

**Issue by leekunha** [v2ray/v2ray-core#1670]
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

此 Issue 会被立即关闭。

If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2ray/discussion/issues) first.

This issue will be closed immediately.

我想要大部分流量都走服务器a，一部分域名的流量通过a中转到服务器b，如何实现

**Comment by kslr** [comment]
https://v2ray.com/chapter_02/03_routing.html#balancerobject
