### ISSUE TITLE
go.sh 跑在 MX LINUX 配置不完全

### ISSUE THREAD

**Issue by JimmyChangJY** [v2ray/v2ray-core#1674]
go.sh 安裝 V2ray 是我一直以來唯一使用的辦法
在我的其他服務氣 Ubuntu 或是 Linux Mint上面一切都正常
但是我最近開始迷戀上 MX Linux(Debian)
這兩天使用 go.sh 自動安裝 V2ray 
會出現一個問題
就是會缺少  /etc/init.d/v2ray (System V)
很奇怪，其他都一切正常 
就不能下指令 service v2ray start
而且開機不會主動跑 V2ray 
我的補救方式就是把 github 上的 /etc/init.d/v2ray 原文轉貼到我自己的 MX Liunx
這樣可以跑 service v2ray start 了
可以看一下這個問題嗎
謝謝

**Comment by nicholascw** [comment]
尝试复现， LiveCD 状态下观察到发行版对 systemctl 命令返回值为正确，因此脚本默认系统为 systemd 系。wontfix，请向发行版维护者反馈
