### ISSUE TITLE
tls 1.3 only 的正确配置是？

### ISSUE THREAD

**Issue by PHCSJC** [v2ray/v2ray-core#1678]
4.18.1已经支持tls 1.3，感谢作者的付出，看了下官方文档还没提到怎么配置走1.3，请教websocks或h2下如何配置only tls 1.3呢？我这里希望的是只走1.3。
"streamSettings": {
        "network": "h2",
        "security": "tls",
        "tlsSettings": {},

是security的设置为tls1.3吗？还是别的什么呢？

或者说不能设置只走1.3，默认已经兼容1.3了？那有办法监控到现在走的连接是1.3吗？

**Comment by kslr** [comment]
不需要配置，自动就使用了。可以抓包

**Comment by PHCSJC** [comment]
> 不需要配置，优先选择。可以抓包

感谢，已经成功了，tcpdump抓包会，但怎么看是tls 1.3就不会了，我的验证方法是在cf设置里开启最低TLS版本为1.3（我用的cf cdn），发现设置后仍然可以连接。

**Comment by kslr** [comment]
那就上Wireshark

**Comment by whu-inf** [comment]
显示tls1.2和tls的版本兼容性以及wireshark对tls的判断机制有关系。
https://networkengineering.stackexchange.com/questions/55752/why-does-wireshark-show-version-tls-1-2-here-instead-of-tls-1-3
如果是web反代，你可以尝试在web的服务端设置仅支持1.3

**Comment by PHCSJC** [comment]
@whu-inf 感谢提醒，wireshark的确对tls版本的判断有问题，我这里又做了以下测试，确定走的就是TLS 1.3
用nginx反代，设置ssl_protocols TLSv1.3（这个表示只支持tls 1.3的连接），然后用4.18.0版本的v2ray去连接，提示remote error: tls: protocol version not supported]，然后修改nginx的的TLS配置为1.2就成功了，再改回1.3就又不行，说明nginx在配置ssl_protocols TLSv1.3后，确实不再支持老版本的tls 1.2，只支持1.3，4.18.0版本的v2ray也确实只支持tls 1.2

此时换成4.18.1版本的v2ray去连接就成功了，那此时一定就是用tls 1.3去连接的。

**Comment by PHCSJC** [comment]
另外再请教一个问题，tls 1.3方式，sni会加密吗？

**Comment by kslr** [comment]
https://github.com/v2ray/discussion/issues/35

**Comment by kxmp** [comment]
1.3 1.2 乱跳 不知道这个情况你碰到没.
我也感觉来个开关很有必要了 XD

**Comment by HougeLangley** [comment]
一般是随机发包，这个其实没必要强制1.3

**Comment by yylaji** [comment]
mark

**Comment by PigodChen** [comment]
不知道tls1.3的时候走的是"TLS_AES_256_GCM_SHA384:" "TLS_CHACHA20_POLY1305_SHA256:" "TLS_AES_128_GCM_SHA256"哪个加密算法？能不能指定？
