### ISSUE TITLE
[Feature Request] Support of package delay for VMESS protocol 

### ISSUE THREAD

**Issue by 70akaline** [v2ray/v2ray-core#1681]
Please describe the new feature you want in detail.

**Comment by 70akaline** [comment]
As discussed many times, this feature should be supported in future V2ray project. Which will give many convenience to multi-purpose users. 
See previous discussions:
https://github.com/v2ray/v2ray-core/issues/553
https://github.com/v2ray/v2ray-core/issues/578

This is a very large engineering for VMESS protocol to support package relay, need new design, and I think it will spend a long time but it is worth.

**Comment by aryMBLec** [comment]
发现这个问题已被列入5.0版本的目标，可喜可贺。
