### ISSUE TITLE
v2ray process consuming all CPU resources

### ISSUE THREAD

**Issue by Tualua** [v2ray/v2ray-core#1682]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

    4.18.0

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

    Using as SOCKS proxy for OpenVPN tunnel

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

    v2ray process starts consuming CPU resources over time, latency over openvpn tunnel becomes crazy. Restarting v2ray process helps but after some time it starts eating CPU again

4) 你期待看到的正确表现是怎样的？

    not eating all CPU resources

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    {
      "log" : {
          "access": "/var/log/v2ray/access.log",
          "error": "/var/log/v2ray/error.log",
          "loglevel": "warning"
      },
      "inbounds": [{
        "port": 2222,
        "listen": "127.0.0.1",
        "protocol": "vmess",
        "settings": {
          "clients": [
            { # user
              "id": "uuid",
              "level": 1,
              "alterId": 64
            }
          ]
        },
        "streamSettings": {
            "network": "ws",
            "wsSettings": {
            "path": "/path"
            }
          }
      },
  {
      "tag": "tg-in",
      "port": 1111,
      "protocol": "mtproto",
      "settings": {
      "users": [
        {"secret": "secret"}
             ]
  }
  }
],
      "outbounds": [{
        "protocol": "freedom",
        "settings": {}
      },{
        "protocol": "blackhole",
        "settings": {},
        "tag": "blocked"
      },
        {
        "tag": "tg-out",
        "protocol": "mtproto",
        "settings": {}
        }
],
      "routing": {
        "rules": [
          {
            "type": "field",
            "ip": ["geoip:private"],
            "outboundTag": "direct"
          },
          {
            "type": "field",
          "inboundTag": ["tg-in"],
          "outboundTag": "tg-out"
      }
        ]
      }
    }

```

客户端配置:

```javascript
    {
  "log": {
    "access": "/config/user-data/var/log/v2ray/access.log",
    "error": "/config/user-data/var/log/v2ray/error.log",
    "loglevel": "error"
  },

  "inbounds": [
    {
      "port": 1080,
      "listen": "0.0.0.0",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http","tls"]
    },
      "settings": {
        "auth": "noauth",
        "udp": true }
    },
{
   "port": 12345,
   "protocol": "dokodemo-door",
   "settings": {
     "network": "tcp,udp",
     "followRedirect": true
   },
   "sniffing": {
     "enabled": true,
     "destOverride": ["http", "tls"]
   }
 }
    ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "host.domain.tld",
            "port": 443,
            "users": [
              {
                "id": "uuid",
                "alterId": 64,
                "email": "e@mail.com",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "serverName": null
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/path",
          "headers": {
            "Host": "host.domain.tld"
          }
        },
        "httpSettings": null,
        "quicSettings": null,
        "sockopt": {
            "mark": 255
         }
      },
      "mux": {
        "enabled": true
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "dns": null,
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "port": null,
        "outboundTag": "block",
        "ip": null,
        "domain": [
          "geosite:category-ads"
        ]
      }

    ]
  }
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

    <IfModule mod_ssl.c>
    <VirtualHost *:443>
        ServerName host.domain.tld
        ServerAdmin admin
        ErrorLog /var/log/error.log
        CustomLog /var/log/access.log combined
        Include /etc/letsencrypt/options-ssl-apache.conf

        RewriteEngine On
        RewriteCond %{HTTP:Upgrade} =websocket [NC]
        RewriteRule /(.*)           ws://localhost:22222/$1 [P,L]
        RewriteCond %{HTTP:Upgrade} !=websocket [NC]
        RewriteRule /(.*)           http://localhost:80/$1 [P,L]

        SSLProxyEngine On
        Proxypass /path http://127.0.0.1:22222
        ProxyPassReverse /path http://127.0.0.1:22222

        SSLCertificateFile /etc/letsencrypt/live/host.domain.tld/cert.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/host.domain.tld/privkey.pem
        SSLCertificateChainFile /etc/letsencrypt/live/host.domain.tld/chain.pem

    </VirtualHost>
</IfModule>

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by Tualua** [comment]
Forgot to tell - this only client-side problem, server is ok

**Comment by Xyncgas** [comment]
不知道为什么我也有这个问题，我就开了mux con 60, 开bt的时候v2ray能够占用300M到1G多的内存而且就算我下载上传也没什么速度我打个游戏都很卡动不动就跳帧（所有底层配置都是会卡），有时候动不动就给我断开连接看着看着视频就缓冲了游戏也掉了但是google一下有没问题重新打开浏览器上一下google也没问题但一直就卡的要死了而且持续下去不知道什么时候，有时会自己好，有时我把v2ray重启一下把bt关掉又好了，有时我就不开bt打着打着游戏掉了网也上不了了但是断断续续地能够上google等静态页面，很卡的感觉，然后重启一下v2ray就又好了，有时候要再等一下才能够重新上网
服务器24小时cpu跟内存都是50%以下
不翻墙的话（通过路由规则）访问的网页就很正常

**Comment by Tualua** [comment]
Anybody?

**Comment by Tualua** [comment]
Same situation on Oracle Linux 7.6 4.14.35-1902.3.1.el7uek.x86_64 V2Ray 4.20.0
