### ISSUE TITLE
v2ray的ipv4 ipv6优选级问题

### ISSUE THREAD

**Issue by PHCSJC** [v2ray/v2ray-core#1683]
我的软路由上有ipv6，然后我通过v2ray的websocks方式通过cdn连接服务器端，因为跨cdn，所以客户端的配置里必须用域名，在启动时，v2ray会优先用解析出ipv6地址去连接服务器端，可以成功连接，也可以正常使用。

然而，问题在于，ipv6会绕路，延迟有400ms+，ipv4的延迟只有160ms+，导致的结果是速度非常慢，我现在的解决方案是在hosts文件里添加这个域名的ipv4地址，这样就会用ipv4去连接。

请教v2ray是否有参数可以设置优先使用ipv4？或者有没有什么更好的解决方案？谢谢！

**Comment by dongjuanyong** [comment]
ip地址固定的话，加个hosts就完了

**Comment by PHCSJC** [comment]
@dongjuanyong 这样是可以，但问题在于跨cdn了，hosts里加的cdn的地址，而cdn的ip有时候会变。

**Comment by dongjuanyong** [comment]
https://www.v2ex.com/t/493222

**Comment by PHCSJC** [comment]
@dongjuanyong 非常感谢，目前看来也只能这样了。
