### ISSUE TITLE
Fail to parse port field of number type in routing rules

### ISSUE THREAD

**Issue by eycorsican** [v2ray/v2ray-core#1684]
### Version
v4.18.0

### Config
```json
    "routing": {
         "rules": [
             {
                 "type": "field",
                 "port": 53,
                 "outboundTag": "direct"
             }
        ]
    }
```

### Error Message
v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: invalid port list: 53 > json: cannot unmarshal number into Go value of type string

**Comment by verniyb** [comment]
Version 4.18.2? 4.19?
github上release的版本号是4.18.2，但是输出的信息里显示的是4.19？
已经修复了吗？我更新了，但使用一样的config文件还是遇到相同的unmarshal number错误，必须手动写成字符串的形式
`"port": 53,`

**Comment by kslr** [comment]
@verniyb 没有发布更新
