### ISSUE TITLE
多路复用好像有点问题

### ISSUE THREAD

**Issue by k79e** [v2ray/v2ray-core#1688]
2个连接非常快 或者同时发起的时候.
这时候如果多路复用只用了1个tcp连接数
这时候第二个连接就得等第一个完成了之后才能接到数据.
浏览器开2个图片 2个不是同一个域名的. 同时刷新就会那样.
要是等第一个图出点内容 然后刷第二个 这样好像又没问题了.
关了多路复用就没这事情了.

(我测试用的一个图走http 另一个走https 两个域名不一样 ip也不一样)
刚发现一个走http 另一个走乱七八糟端口又好像没问题. 

服务器配置https://pastebin.com/0AEjHFjA
客户端配置https://pastebin.com/9kRVzf6s
版本都是4.18

刚才我又本地测了一下 竟然复现不了了. 不知道为什么 可能对连接延时有关?

**Comment by kslr** [comment]
请按照模板提交访问，方便重现测试。

kxmp <notifications@github.com> 于 2019年5月13日周一 22:48写道：

**Comment by IDSSC** [comment]
mux填64

**Comment by kxmp** [comment]
200的都用了.
