### ISSUE TITLE
动态端口的问题

### ISSUE THREAD

**Issue by jcpapa2x** [v2ray/v2ray-core#169]
你好，我也遇到了#86 里面的问题，按照您的建议，refresh值改成了2，目前能够正常切换端口没有报错，请问可能是什么问题呢？

**Comment by v2ray** [comment]
版本是多少？1.16?

**Comment by jcpapa2x** [comment]
1.15

**Comment by v2ray** [comment]
可以升到 1.16 看看，1.16 有一点点的修复。

**Comment by jcpapa2x** [comment]
升级后试用了会，端口没有报错了。
但是我发现在打开网页的时候有点困难，特别是一些直连的网站，一些元素可能刷不出来，甚至页面假死。使用SS端口几乎就不会出现这个情况。
明天我再取消动态端口试一下。

**Comment by v2ray** [comment]
直连的网站? 这和动态端口没有关系吧

**Comment by jcpapa2x** [comment]
我的意思是不用代理的时候是没问题的，用了代理打开直连网站有这个问题。我也不清楚是动态端口或者路由还是其他什么原因，客户端也没有报错。

**Comment by jcpapa2x** [comment]
今天又试了下，可能是先前我疏忽了，把广告拦截关掉会好很多，有其他问题再开
