### ISSUE TITLE
/usr/bin/geoip.dat: no such file or directory

### ISSUE THREAD

**Issue by LinArcX** [v2ray/v2ray-core#1690]
In linux i use v2ray package and call it with [passing a config file](https://v2ray.com/en/welcome/start.html), but i get an error:

```
╰ v2ray --config=/etc/v2ray/config.json
V2Ray 4.18.0 (Po) 20190228
A unified platform for anti-censorship.
main: failed to read config file: /etc/v2ray/config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to load GeoIP: private > v2ray.com/core/infra/conf: failed to open file: geoip.dat > open /usr/bin/geoip.dat: no such file or directory

 > exit status 255
```
And this is my config.json file:
https://gist.github.com/LinArcX/1eb46bad3a9360a5838181d4f29dee13

**Comment by kslr** [comment]
https://github.com/v2ray/geoip/releases/download/20190509.1/geoip.dat

move to /usr/bin/geoip.dat

**Comment by LinArcX** [comment]
@kslr ok, thank you. it fixes. but now when i start it again it is the output of it:
```
╰ v2ray --config=/etc/v2ray/config.json
V2Ray 4.18.0 (Po) 20190228
A unified platform for anti-censorship.
```
This is the [error log](╰ v2ray --config=/etc/v2ray/config.json
V2Ray 4.18.0 (Po) 20190228
A unified platform for anti-censorship.
)

**Comment by kslr** [comment]
> too many colons in address

**Comment by LinArcX** [comment]
Still same errors.

**Comment by kslr** [comment]
Please follow the template to submit the issue

**Comment by nobk** [comment]
cd to geoip.dat dir
`ln -s geoip.dat geoip
`
I think it is a bug.

**Comment by crimx** [comment]
Looks like the v2ray from arch repo already includes v2ray-geoip as deps but I still got this error.

**Comment by crimx** [comment]
Fixed by

```
ln -s /etc/v2ray/geoip.dat /usr/bin/geoip.dat
```

But shouldn't v2ray also check the `/etc/v2ray/geoip.dat`?
