### ISSUE TITLE
aws lightsail所有系统无法绑定IPV4

### ISSUE THREAD

**Issue by itegec** [v2ray/v2ray-core#1693]
https://lightsail.aws.amazon.com/

所有操作系统均无法绑定IPV4，只能绑定IPV6，全部禁用IPV6后仍然无效, 使用listen : "0.0.0.0" 仍然无效

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
4.18, 4.17, 4.16
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
Chrome找技术资料
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
只能监听IPV6端口
4) 你期待看到的正确表现是怎样的？

无法使用，浏览器一直不能通

**Comment by wuxiangzhou2010** [comment]
aws新加坡 lightsail 亲测可用 把server完整配置发一下吧

**Comment by zcluo** [comment]
日本和韩国一直在用

发自我的 iPhone

**Comment by kotori2** [comment]
日志呢
