### ISSUE TITLE
ipv4 v6优先级建议根据系统配置来决定

### ISSUE THREAD

**Issue by PHCSJC** [v2ray/v2ray-core#1696]
linux系统里有个gai.conf配置文件，这个配置做如下修改可以设置为ipv4优先，这样设置后，用nslookup，ping都会优先走ipv4，但v2ray还是优先走ipv6，建议v2ray也能同样根据这个文件来决定ipv4 v6的优先级。

`precedence ::ffff:0:0/96  100`

**Comment by bitching** [comment]
我觉得就现在这样挺好的，NAT VPS如果默认v4会随时弹验证码，v6基本不会。
