### ISSUE TITLE
http2路径有点问题 版本4.18

### ISSUE THREAD

**Issue by k79e** [v2ray/v2ray-core#1698]
server https://pastebin.com/Si1Pxpi2
client https://pastebin.com/bKscakj0

那个path 如果是正确应该是可以连接 但是如果是错的应该连不上才对.
h2错的果然连不上 但是如果给正确的后面加几个字 还是照样能连上. ws的没这问题.
比如路径是a00
客户端配置a01 结果连不上
改a00 能连上
改a001还是能连上 (这个时候应该连不上才对)

**Comment by kslr** [comment]
半年过去了，有新的变化吗

**Comment by k79e** [comment]
4.21.3服务端测了还是那样

**Comment by k79e** [comment]
V2Ray 4.25.0 测了还是那样
