### ISSUE TITLE
v2ray 有时候访问无速度需要重启服务

### ISSUE THREAD

**Issue by xldsdr124** [v2ray/v2ray-core#1702]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
4.18
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
代理上网，youtube，境外网站，游戏代理
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
有时候访问超时或者无速度加载不出页面，需要多次重启v2ray客户端
4) 你期待看到的正确表现是怎样的？
减少或不发生断流的问题
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    {
	"inbound": {
		"port": 14798,
		"protocol": "vmess",
		"settings": {
			"clients": [
				{
					"id": "uuid",
					"alterId": 82
				},
				{
					"id": "uuid2",
					"alterId": 31
				}
			]
		},
		"streamSettings": {
			"network": "tcp",
			"tcpSettings": {
				"header": { 
					"type": "http",
					"response": {
						"version": "1.1",
						"status": "200",
						"reason": "OK",
						"headers": {
							"Content-Type": ["application/octet-stream", "application/x-msdownload", "text/html", "application/x-shockwave-flash"],
							"Transfer-Encoding": ["chunked"],
							"Connection": ["keep-alive"],
							"Pragma": "no-cache"
						}
					}
				}
			}
		}
	},
	"outbound": {
		"protocol": "freedom",
		"settings": {}
	}
}
```

客户端配置:

```javascript
    {
  "log": {
    "access": "",
    "error": "",
    "loglevel": "error"
  },
  "inbounds": [
    {
      "port": 1080,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "my hongkong vps ip",
            "port": 14798,
            "users": [
              {
                "id": "uuid2",
                "alterId": 31,
                "email": "t@t.tt",
                "security": "chacha20-poly1305"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "tcp",
        "security": "",
        "tlsSettings": null,
        "tcpSettings": {
          "connectionReuse": true,
          "header": {
            "type": "http",
            "request": {
              "version": "1.1",
              "method": "GET",
              "path": [
                "/"
              ],
              "headers": {
                "Host": [
                  "cdn.jsdelivr.net"
                ],
                "User-Agent": [
                  "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36",
                  "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
                ],
                "Accept-Encoding": [
                  "gzip, deflate"
                ],
                "Connection": [
                  "keep-alive"
                ],
                "Pragma": "no-cache"
              }
            },
            "response": null
          }
        },
        "kcpSettings": null,
        "wsSettings": null,
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "dns": {
    "servers": [
      "1.1.1.1"
    ]
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "port": null,
        "outboundTag": "direct",
        "ip": [
          "geoip:private"
        ],
        "domain": null
      },
      {
        "type": "field",
        "port": null,
        "outboundTag": "direct",
        "ip": [
          "geoip:cn"
        ],
        "domain": null
      },
      {
        "type": "field",
        "port": null,
        "outboundTag": "direct",
        "ip": null,
        "domain": [
          "geosite:cn"
        ]
      }
    ]
  }
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
   
```

客户端错误日志:

```javascript
     2019/05/24 11:28:04 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp my server ip:port: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
2019/05/24 11:28:31 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp my server ip:port: connectex: No connection could be made because the target machine actively refused it. dial tcp my server ip:port: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. dial tcp my server ip:port: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by kslr** [comment]
请提供日志

**Comment by a2232189** [comment]
same problem but I don't save v2rayN log before. Next time I found this happened I will offer logs.

**Comment by xldsdr124** [comment]
> 请提供日志

在提问前我没有开启日志，后来我开启了warning或error日志，当出现阻塞，我发现只保留了连接信息，没有提示什么错误

**Comment by xldsdr124** [comment]
> 请提供日志

刚获得了服务端的错误信息，客户端没有任何信息，已经更新至issuse

**Comment by bao007fei** [comment]
一样的情况，仅出现在windows上，时不时断联，几分钟后自动恢复正常。断联时Android端可以正常连接。我想问题应该出现在windows客户端上面。

**Comment by a2232189** [comment]
> > 请提供日志
> 
> 刚获得了服务端的错误信息，客户端没有任何信息，已经更新至issuse

I am confused. You said " 刚获得了**服务端**的错误信息，客户端没有任何信息，已经更新至issuse", I infer that you just uploaded server log, right? However you updated data within `客户端错误日志` , so what kind of log is it, server log or client log?

**Comment by xldsdr124** [comment]
> > > 请提供日志
> > 
> > 
> > 刚获得了服务端的错误信息，客户端没有任何信息，已经更新至issuse
> 
> I am confused. You said " 刚获得了**服务端**的错误信息，客户端没有任何信息，已经更新至issuse", I infer that you just uploaded server log, right? However you updated data within `客户端错误日志` , so what kind of log is it, server log or client log?

Server warning log

**Comment by Xyncgas** [comment]
it's impossible to use after recent versions, of which I have notice as well, because everytime I use bittorrent protocol with around 300 concurrent connection the client just fails, server is fine, I reloaded the application and it starts running again like nothing happened

**Comment by xldsdr124** [comment]
我的服务器操作系统是windows server 2008，我通过注册表修改了windows系统时间同步频率值为7200， 似乎它的问题不再出现，感谢。

**Comment by a2232189** [comment]
> 我的服务器操作系统是windows server 2008，我通过注册表修改了windows系统时间同步频率值为7200， 似乎它的问题不再出现，感谢。

请问原理是什么？ 时间同步频率和这个问题有什么关系？有什么reference能提供参考，谢谢。

**Comment by xldsdr124** [comment]
> > 我的服务器操作系统是windows server 2008，我通过注册表修改了windows系统时间同步频率值为7200， 似乎它的问题不再出现，感谢。
> 
> 请问原理是什么？ 时间同步频率和这个问题有什么关系？有什么reference能提供参考，谢谢。

我也不太明白，https://toutyrater.github.io/prep/start.html，通过这个文档1.1节说明了时间准确性很重要，我想是某些因素影响了服务器时间同步关系。1.尽量保持服务器时区时间和你的客户端设备时间保持一致；2.windows主机修改系统同步频率方法->

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\TimeProviders\NtpClient ]->指向 SpecialPollInterval的值修改为2小时左右，我设置为了7200，但注意也不要设置的太低。

也许linux也有同样的办法
这里并不保证全部都是这个原因，也许是网络线路不稳定导致等其他原因

**Comment by Xyncgas** [comment]
mine got better too, by restarting v2ray. And not using torrent protocols while browsing twitch

**Comment by ntgeralt** [comment]
我顺便提一个小问题，同一个节点 hkbn 1000mbps搭建ssr服务端和v2ray服务端（233一键脚本）。ios 小火箭做客户端，测试一些国外app，载入视频速度总感觉是ssr稍微快点。但电脑用v2ray客户端则是电脑更快，不知怎么问题...

**Comment by gonnalee** [comment]
> 我顺便提一个小问题，同一个节点 hkbn 1000mbps搭建ssr服务端和v2ray服务端（233一键脚本）。ios 小火箭做客户端，测试一些国外app，载入视频速度总感觉是ssr稍微快点。但电脑用v2ray客户端则是电脑更快，不知怎么问题...

我也一样，感觉用app端的v2ray速度差不少。用电脑则很快很流畅

**Comment by ileeoyo** [comment]
> 一样的情况，仅出现在windows上，时不时断联，几分钟后自动恢复正常。断联时Android端可以正常连接。我想问题应该出现在windows客户端上面。

一样的问题，没有任何错误的日志，access.log里看起来也都是正常，但是就是无法访问，需要等待几十秒，或者几分钟就自然好了。同一时间同一网络下，安卓都是正常。只有windows下出现这个问题

**Comment by 8427003** [comment]
+1
V2Ray 4.21.3，日志无错误，无任何异常。客户端windows10， clash for windows。配置都是官网最基础的配置。重启下服务端恢复~

**Comment by mqliutie** [comment]
mac 也断了, 但是小火箭依然能够运行...  访问时候 日志没打印任何东西, 用的是 [V2rayU](https://github.com/yanue/V2rayU)

**Comment by Leeray-Lau** [comment]
> 一样的情况，仅出现在windows上，时不时断联，几分钟后自动恢复正常。断联时Android端可以正常连接。我想问题应该出现在windows客户端上面。

@bao007fei 请问一下，你的v2ray断流的问题解决了嘛？，然后也是win10系统么？我的情况和你一样只发生在windows端，然后经过我这几天的测试，我发现在IOS端，亦或是在路由器上搭建的V2Ray就没再有出现断流的情况了，我的配置是V2Ray + WebSocket + TLS + CDN……

**Comment by bao007fei** [comment]
@Leeray-Lau 现在基本不会断了，但速度还是慢，同一路由下（路由没有使用v2ray，windows和Android分别使用各自的客户端），windows明显慢于Android，十分头疼。
