### ISSUE TITLE
Can we implement support for connecting to another instance using uuid and without using ip address

### ISSUE THREAD

**Issue by Xyncgas** [v2ray/v2ray-core#1703]
Like how syncthing does, https://github.com/syncthing/syncthing.
  So even if the other instance is behind nat, say it's a computer somewhere on the internet, and it may not even have an public ip address, so you would instead let both of the computer talk to the server you own and identify eachother with an uuid, then establish the connection with eachother, and now you can do amazing thing with this.
  sounds challenging right, I know you are excited about this, I want v2ray to become everything it can be.

**Comment by kslr** [comment]
I suggest you use tor

**Comment by Xyncgas** [comment]
No wait this is actually good, with this technology we can connect to any pc on the world
bring freedom to everyone !

**Comment by blinkspark** [comment]
The idea sounds great, but V2ray is not a p2p project. Actually your idea will bring whole new p2p subsystem to the project.
Here is a P2P framework which maybe useful: https://github.com/libp2p/go-libp2p

**Comment by Xyncgas** [comment]
I mean the concept is p2p, of couse it is, just look at the inbound it's asking people to connect to the server, and that's the purest peer to peer, but outbound is like whatever. I know there is a lot coding to be done just by looking at the current go standard library and v2ray's code, but hey you can't make a future without getting your hands dirty.

**Comment by Xyncgas** [comment]
I am patient, trying to be hopeful on this, but yeah it's up to the developers
