### ISSUE TITLE
4.18.2 v2ray linux -version miss matched

### ISSUE THREAD

**Issue by xjasonlyu** [v2ray/v2ray-core#1707]
1) What version of V2Ray are you using 
`4.18.2` from Release Page
2) What's your expectation?
latest v2ray version `4.18.2`
run `v2ray -version`, get
```
V2Ray 4.19 (Let's Fly) Custom
A unified platform for anti-censorship.
```
it would make go.sh update v2ray again and again.

(No configuration needed)

**Comment by kslr** [comment]
4.19.1 fix
