### ISSUE TITLE
从源文件编译版本问题

### ISSUE THREAD

**Issue by ktcunreal** [v2ray/v2ray-core#171]
按照官网教程 
昨天刚编译完v1.16版本(在Win7和Debian8上运行) 一切皆正常 
运行版本显示"V2Ray v1.16 `<`New Order`>` 20160613"
今天重新编译了一下 发现版本回到v1.14了 
显示为“V2Ray1.14` <`New Order`>` Custom"
操作步骤完全一样 都是按照文档中写的:
go get -u github.com/v2ray/v2ray-core
go install github.com/v2ray/v2ray-core/tools/build
$GOPATH/bin/build
之后再也编译不出1.16版本了..
请问这是什么原因…

**Comment by v2ray** [comment]
不用在意版本号，只要确保 pull 到最新的即可。版本号只有在发 release 的那一个 commit 是自动的，其它时候都需要手动更新。有时候我会忘了改手动的部分 :)

**Comment by public15** [comment]
$GOPATH/bin/build 只编译了一个v2ray-custom-linux-64,而win平台的exe没有编译出,是什么问题呢?没有提示错误

**Comment by ktcunreal** [comment]
@v2ray 
噢噢了解了，非常感谢！！

@public15 
可以这样
$GOPATH/bin/build --os=windows --arch=x86 --zip
$GOPATH/bin/build --os=windows --arch=x64 --zip

**Comment by public15** [comment]
多谢，搞掂了
