### ISSUE TITLE
不是说支持多协议吗？？？？？？

### ISSUE THREAD

**Issue by outception** [v2ray/v2ray-core#1710]
```
"inbounds": [
    {
      "port": 1080,
      "listen": "0.0.0.0",
      "protocol": "socks"
    },
    {
      "port": 1080,
      "listen": "0.0.0.0",
      "protocol": "http"
    }
  ]
```

Failed to start v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 1080 > v2ray.com/core/transport/internet: failed to listen on address: 0.0.0.0:1080 > listen tcp 0.0.0.0:1080: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

**Comment by kslr** [comment]
Only one usage of each socket address (protocol/network address/port) is normally permitted.

**Comment by outception** [comment]
2019/06/02 20:38:00 [Warning] v2ray.com/core: V2Ray 4.19 started
2019/06/02 20:38:11 tcp:127.0.0.1:62665 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
2019/06/02 20:38:11 tcp:127.0.0.1:62666 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
2019/06/02 20:38:11 tcp:127.0.0.1:62667 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
2019/06/02 20:38:11 tcp:127.0.0.1:62668 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
2019/06/02 20:38:23 tcp:127.0.0.1:62676 accepted tcp:www.google.com:443 
2019/06/02 20:38:32 tcp:127.0.0.1:62681 accepted tcp:id.google.com:443 
2019/06/02 20:39:36 tcp:127.0.0.1:62683 accepted tcp:clients4.google.com:443 
2019/06/02 20:47:47 tcp:127.0.0.1:62764 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
2019/06/02 20:47:47 tcp:127.0.0.1:62765 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
2019/06/02 20:47:47 tcp:127.0.0.1:62766 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
2019/06/02 20:47:47 tcp:127.0.0.1:62767 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
2019/06/02 20:47:47 tcp:127.0.0.1:62768 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
2019/06/02 20:47:47 tcp:127.0.0.1:62769 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
2019/06/02 20:47:47 tcp:127.0.0.1:62770 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
2019/06/02 20:47:47 tcp:127.0.0.1:62771 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
2019/06/02 20:47:47 tcp:127.0.0.1:62772 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
2019/06/02 20:47:47 tcp:127.0.0.1:62773 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
2019/06/02 20:48:04 tcp:127.0.0.1:62775 accepted tcp:clients4.google.com:443 
2019/06/02 20:52:55 tcp:127.0.0.1:62827 accepted tcp:4.2.2.2:53

**Comment by Gohoy** [comment]
请问这个问题是怎么引起的呢，我不是很理解，之前没有出现过，现在经常出现

**Comment by marxangels** [comment]
原因，错把 http_proxy 请求发送到了监听 socks5 的端口上。
这么久还没解决问题吗？统一端口，做个协议判断又不难。

**Comment by marxangels** [comment]
判断头几个字节就知道是什么协议了，之前稳定用了很久的原版 shadowsosks 客户端就是这样做的，同一个 1080 端口，既监听 http 又监听 socks，兼容性极好。

**Comment by Gohoy** [comment]
好的，我最近才出现的问题，刚才看一下客户端的tcp，发现v2ray 把我所有端口都占用了，我感觉是tcp的问题，我先统一端口试一下，谢谢
