### ISSUE TITLE
centos官方安装脚本出现encoding: invalid user

### ISSUE THREAD

**Issue by 1265578519** [v2ray/v2ray-core#1711]
2019/06/02 20:49:41 我的本地ip:6333 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:49:42 我的本地ip:6334 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:49:42 我的本地ip:6339 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:49:43 我的本地ip:6340 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:49:45 我的本地ip:6341 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:49:46 我的本地ip:6343 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:49:47 我的本地ip:6344 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:49:48 我的本地ip:6347 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:49:48 我的本地ip:6349 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:49:49 我的本地ip:6356 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:49:51 我的本地ip:6358 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:49:54 我的本地ip:6372 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:49:55 我的本地ip:6373 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:49:57 我的本地ip:6375 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:49:59 我的本地ip:6376 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:50:00 我的本地ip:6385 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:50:04 我的本地ip:6388 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:50:10 我的本地ip:6399 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:50:12 我的本地ip:6400 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:50:15 我的本地ip:6402 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:51:33 我的本地ip:6557 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:51:33 我的本地ip:6559 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:51:34 我的本地ip:6560 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:51:34 我的本地ip:6562 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:51:35 我的本地ip:6563 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:51:36 我的本地ip:6567 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:51:37 我的本地ip:6577 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:51:38 我的本地ip:6578 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:51:39 我的本地ip:6580 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:51:40 我的本地ip:6587 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:51:41 我的本地ip:6591 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:51:42 我的本地ip:6593 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:51:44 我的本地ip:6595 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:51:45 我的本地ip:6598 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:51:54 我的本地ip:6614 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:51:57 我的本地ip:6619 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:51:59 我的本地ip:6623 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:52:21 我的本地ip:6653 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:52:22 我的本地ip:6655 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:52:24 我的本地ip:6658 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:52:26 我的本地ip:6659 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:52:45 我的本地ip:6687 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:52:57 我的本地ip:6703 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:52:59 我的本地ip:6704 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:53:00 我的本地ip:6705 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:53:18 我的本地ip:6720 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:53:30 我的本地ip:6724 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 20:53:30 113.128.104.170:35792 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 21:11:17 127.0.0.1:38010 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > read tcp 127.0.0.1:46575->127.0.0.1:38010: i/o timeout
2019/06/02 21:11:22 127.0.0.1:38016 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > read tcp 127.0.0.1:46575->127.0.0.1:38016: i/o timeout
2019/06/02 21:29:32 我的本地ip:5234 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 21:29:35 我的本地ip:5235 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 21:29:35 我的本地ip:5237 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 21:29:36 我的本地ip:5239 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 21:29:37 我的本地ip:5241 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 21:29:38 我的本地ip:5242 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 21:29:40 我的本地ip:5244 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/06/02 21:29:41 我的本地ip:5250 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user

**Comment by 1265578519** [comment]
id和额外id都一致，同一台服务器重装为在centos7系统没出现，就centos6下不行。

**Comment by 1265578519** [comment]
[root@localhost ~]# date
Sun Jun  2 21:46:10 HKT 2019
[root@localhost ~]# ntpdate time.nist.gov
 2 Jun 21:48:53 ntpdate[17067]: step time server 132.163.96.6 offset 152.652611 sec
[root@localhost ~]# date
Sun Jun  2 21:48:57 HKT 2019
[root@localhost ~]#
https://www.v2ray.com/chapter_00/faq.html
解决了，，看了faq后发现centos6的系统时间不对，误差超过了90秒。

**Comment by 1265578519** [comment]
完了，还有几台openvz服务器改不了时间，，怎么办

**Comment by qingfengshi** [comment]
发T

**Comment by 1265578519** [comment]
发t已经解决
