### ISSUE TITLE
kcp下设置"security": "none",配置文件不生效，客户端还是可以提供加密连入

### ISSUE THREAD

**Issue by 1265578519** [v2ray/v2ray-core#1714]
kcp下设置"security": "none",配置文件不生效，客户端还是可以提供加密连入

**Comment by 1265578519** [comment]
服务器端
{
        "log": {
                "access": "/var/log/v2ray/access.log",
                "error": "/var/log/v2ray/error.log",
                "loglevel": "warning"
        },
        "inbounds": [
                {
                        "port": 23000,
                        "protocol": "vmess",
                        "settings": {
                                "clients": [
                                        {
                                                "id": "da5c5b2d-06ca-4363-9b4d-3a9e23ce291d",
                                                "level": 1,
                                                "alterId": 64
                                        }
                                ]
                        },
                        "streamSettings": {
                                "network": "kcp",
                                "security": "none",
                                "kcpSettings": {
                                        "header": {
                                                "type": "none"
                                        }
                                }
                        },
                        "sniffing": {
                                "enabled": true,
                                "destOverride": [
                                        "http",
                                        "tls"
                                ]
                        }
                }
                //include_ss
                //include_socks
                //include_mtproto
                //include_in_config
                //
        ],
        "outbounds": [
                {
                        "protocol": "freedom",
                        "settings": {}
                },
                {
                        "protocol": "blackhole",
                        "settings": {},
                        "tag": "blocked"
                },
                {
                        "protocol": "freedom",
                        "settings": {},
                        "tag": "direct"
                },
                {
                        "protocol": "mtproto",
                        "settings": {},
                        "tag": "tg-out"
                }
                //include_out_config
                //
        ],
        "dns": {
                "server": [
                        "8.8.8.8",
                        "1.1.1.1",
                        "localhost"
                ]
        },
        "routing": {
                "domainStrategy": "IPOnDemand",
                "rules": [
                        {
                                "type": "field",
                                "ip": [
                                        "0.0.0.0/8",
                                        "10.0.0.0/8",
                                        "100.64.0.0/10",
                                        "127.0.0.0/8",
                                        "169.254.0.0/16",
                                        "172.16.0.0/12",
                                        "192.0.0.0/24",
                                        "192.0.2.0/24",
                                        "192.168.0.0/16",
                                        "198.18.0.0/15",
                                        "198.51.100.0/24",
                                        "203.0.113.0/24",
                                        "::1/128",
                                        "fc00::/7",
                                        "fe80::/10"
                                ],
                                "outboundTag": "blocked"
                        },
                        {
                                "type": "field",
                                "inboundTag": ["tg-in"],
                                "outboundTag": "tg-out"
                        }
                        //include_ban_ad
                        //include_rules
                        //
                ]
        },
        "transport": {
                "kcpSettings": {
            "uplinkCapacity": 100,
            "downlinkCapacity": 100,
            "congestion": false
        },
                "sockopt": {
                        "tcpFastOpen": true
                }
        }
}
客户端
    {
      "configVersion": 2,
      "address": "隐藏使用ip",
      "port": 隐藏使用端口,
      "id": "隐藏使用id",
      "alterId": 64,
      "security": "aes-128-gcm",
      "network": "kcp",
      "remarks": "英国",
      "headerType": "utp",
      "requestHost": "",
      "path": "",
      "streamSecurity": "",
      "allowInsecure": "",
      "configType": 1,
      "testResult": "",
      "subid": ""
    }

**Comment by boypt** [comment]
security不适用于mkcp

**Comment by kxmp** [comment]
那个是给h2/ws用的.
