### ISSUE TITLE
V2ray配置好了依旧无法科学上网，时间也是本地时间，请大佬们帮帮忙，新人小白求助。

### ISSUE THREAD

**Issue by Faris236** [v2ray/v2ray-core#1716]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v2ray 4.19.1 版本
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
使用chrome通过VMess科学上网
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
用V2ray上网，国外的网页统统上不去
4) 你期待看到的正确表现是怎样的？
希望v2ray可以正常科学上网，
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

        "log": {
                "access": "/var/log/v2ray/access.log",
                "error": "/var/log/v2ray/error.log",
                "loglevel": "warning"
        },
        "inbounds": [
                {
                        "port": 51585,
                        "protocol": "vmess",
                        "settings": {
                                "clients": [
                                        {
                                                "id": "1a52d0cb-047d-4ef0-bfa2-476844220001",
                                                "level": 1,
                                                "alterId": 233
                                        }
                                ]
                        },
                        "streamSettings": {
                                "network": "tcp"
                        },
                        "sniffing": {
                                "enabled": true,
                                "destOverride": [
                                        "http",
                                        "tls"
                                ]
                        }
                }
                //include_ss
                //include_socks
                //include_mtproto
                //include_in_config
                //

```javascript
    // 在这里附上服务器端配置文件
```

客户端配置:
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "207.246.122.76",
            "port": 51585,
            "users": [
              {
                "id": "1a52d0cb-047d-4ef0-bfa2-476844220001",
                "alterId": 233,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "tcp",
        "security": "",
        "tlsSettings": null,
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": null,
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "dns": null,
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": []
  }
}
```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:
E325: ATTENTION
Found a swap file by the name "/var/log/v2ray/.error.log.swp"
          owned by: root   dated: Tue Jun  4 13:05:53 2019
         file name: /var/log/v2ray/error.log
          modified: no
         user name: root   host name: newyork-nj
        process ID: 10978 (still running)
While opening file "/var/log/v2ray/error.log"
             dated: Tue Jun  4 12:43:11 2019

(1) Another program may be editing the same file.  If this is the case,
    be careful not to end up with two different instances of the same
    file when making changes.  Quit, or continue with caution.
(2) An edit session for this file crashed.
    If this is the case, use ":recover" or "vim -r /var/log/v2ray/error.log"
    to recover the changes (see ":help recovery").
    If you did this already, delete the swap file "/var/log/v2ray/.error.log.swp"
    to avoid this message.
"/var/log/v2ray/error.log" 1L, 67C

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。
-- Logs begin at Tue 2019-06-04 08:59:45 CST, end at Tue 2019-06-04 13:09:46 CST. --
Jun 04 09:16:18 newyork-nj systemd[1]: Started V2Ray Service.
Jun 04 09:16:18 newyork-nj v2ray[3962]: V2Ray 4.19.1 (Let's Fly) Custom
Jun 04 09:16:18 newyork-nj v2ray[3962]: A unified platform for anti-censorship.
Jun 04 09:57:40 newyork-nj systemd[1]: Stopping V2Ray Service...
Jun 04 09:57:40 newyork-nj systemd[1]: Stopped V2Ray Service.
Jun 04 09:57:40 newyork-nj systemd[1]: Started V2Ray Service.
Jun 04 09:57:40 newyork-nj v2ray[10093]: V2Ray 4.19.1 (Let's Fly) Custom
Jun 04 09:57:40 newyork-nj v2ray[10093]: A unified platform for anti-censorship.
Jun 04 10:45:39 newyork-nj systemd[1]: Stopping V2Ray Service...
Jun 04 10:45:39 newyork-nj systemd[1]: Stopped V2Ray Service.
Jun 04 10:46:23 newyork-nj systemd[1]: Started V2Ray Service.
Jun 04 10:46:23 newyork-nj v2ray[10402]: V2Ray 4.19.1 (Let's Fly) Custom
Jun 04 10:46:23 newyork-nj v2ray[10402]: A unified platform for anti-censorship.
Jun 04 10:46:24 newyork-nj v2ray[10402]: 2019/06/04 10:46:24 [Warning] v2ray.com/core: V2Ray 4.19.1 started
Jun 04 12:43:11 newyork-nj systemd[1]: Stopping V2Ray Service...
Jun 04 12:43:11 newyork-nj systemd[1]: Stopped V2Ray Service.
Jun 04 12:43:11 newyork-nj systemd[1]: Started V2Ray Service.
Jun 04 12:43:11 newyork-nj v2ray[10777]: V2Ray 4.19.1 (Let's Fly) Custom
Jun 04 12:43:11 newyork-nj v2ray[10777]: A unified platform for anti-censorship.

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by hahaher123** [comment]
配置里没看见服务端的outbound，客户端的inbound。

**Comment by lk-timeout** [comment]
还有过几天再试，六号之后

**Comment by beckball** [comment]
配置里没看见服务端的outbound，客户端的inbound。
如果你实在不会 请不要修改你使用的一键脚本生成json的任何一个字

**Comment by Kylejustknows** [comment]
@beckball 楼主可能简化了一下他的配置发上来。 客户机和服务器之间的连接信息，看起来好像没有太大错误。
重要的是，服务器端的V2ray日志信息，楼主没有正确发上来。所以无法判断他到底哪里出错，甚至连端口有没有打开都无法判断。
还有请楼主抹一下你的IP和UUID等信息，注意安全。
