### ISSUE TITLE
下载下来后

### ISSUE THREAD

**Issue by a100488** [v2ray/v2ray-core#1718]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

4) 你期待看到的正确表现是怎样的？

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
```

客户端配置:

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by a100488** [comment]
客户端
![image](https://user-images.githubusercontent.com/12635040/58864318-0a4e9400-86e7-11e9-8feb-60b5ab27449d.png)

**Comment by wanken** [comment]
卸载360,要不别用代理

**Comment by forever8938** [comment]
电脑上装国产杀毒软件或者浏览器的，建议留在墙内。

**Comment by kslr** [comment]
wv2ray 不知道哪来的文件，建议你从github重新下载

**Comment by shincysl** [comment]
4.18.0 一定是好的，后面版本可能和编译有关，cylance挂了。主要公司强制cylance。。
https://www.virustotal.com/gui/file/7cae3e00e7f3e5e51e5acc63ba62b69f6a8801471e833c5254e38e2047dc410a/detection
https://www.virustotal.com/gui/file/e7b97efd066d40210b80ed540f97bbfb77fd74f3abc31f982098c5b9b737b090/detection

**Comment by kxmp** [comment]
山六零就是这样的!!!
