### ISSUE TITLE
failed to find an available destination

### ISSUE THREAD

**Issue by tiancai110a** [v2ray/v2ray-core#1719]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
4.19.1
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
客户端不能解析服务器域名，outbound 的address那里使用ip可以，使用域名不行，域名是能正常访问的，我看issue里挂了好几个这种问题，但是没有一个能解决的
4) 你期待看到的正确表现是怎样的？
客户端能解析服务器域名

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
   {
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    // By default, V2Ray writes access log to stdout.
    // "access": "/path/to/access/log/file",

    // By default, V2Ray write error log to stdout.
    // "error": "/path/to/error/log/file",

    // Log level, one of "debug", "info", "warning", "error", "none 
    "loglevel": "warning"
  },  
  "inbounds": [
    {   
      "port": 443, // Vmess 协议服务器监听端口
      "protocol": "vmess",
             "settings": {
        "clients": [
          {   
            "id": "xxxxxxx",
            "level":1,
            "alterId":64
          }   
        ]   
      }   
     //// "streamSettings": {
     //   "network": "tcp",
     //   "security": "tls", // security 要设置为 tls 才会启用 TLS
     //   "tlsSettings": {
     //     "certificates": [
     //       {
     //         "certificateFile": "/etc/v2ray/v2ray.crt", // 证书文件
     //         "keyFile": "/etc/v2ray/v2ray.key" // 密钥文件
     //       }
     //     ]
     //   }
     // //}
    }
    //{
     // "port": 444, // SS 协议服务端监听端口
      //"protocol": "shadowsocks",
     // "settings": {
       // "method": "aes-128-gcm", // 加密方式
       // "password": "tiancai110a" //密码
     // }
    //}
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}
```

客户端配置:

```javascript
 {
  "log": {
    "loglevel": "warning",
    "access": "C:\\v2ray\\log\\access.log",
    "error": "C:\\v2ray\\log\\error.log"
  },
  "inbounds": [
    {
      "port": 8081,
      "protocol": "http",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
      "settings": {
        "auth": "noauth",
        "udp": true
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "domainname",// 
            "port": 443,
            "users": [
              {
                "id": "XXXXXX",
                "alterId": 4
              }
            ]
          }
        ]
      },
	  //"streamSettings": {
        //"network": "tcp",
        //"security": "tls" // 客户端的 security 也要设置为 tls
      //},
	  "mux": {"enabled": true}
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct" //如果要使用路由，这个 tag 是一定要有的，在这里 direct 就是 freedom 的一个标号，在路由中说 direct V2Ray 就知道是这里的 freedom 了 
    }    
  ],
   "dns": {
    "server": [
      "8.8.8.8",
      "1.1.1.1"
    ],
    // 你的 IP 地址，用于 DNS 解析离你最快的 CDN
    "clientIp": xxxxx"
  },
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": ["geosite:cn"] // 中国大陆主流网站的域名
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:cn", // 中国大陆的 IP
          "geoip:private" // 私有地址 IP，如路由器等
        ]
      }
    ]
  }
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

客户端错误日志:
2019/06/05 01:55:46 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp: lookup xxxx.info/: no such host] > v2ray.com/core/common/retry: all retry attempts failed

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

不需要

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by kslr** [comment]
[dial tcp: lookup xxxx.info/: no such host

检查域名和dns

**Comment by jy1989** [comment]
`2020/06/12 12:03:21 [Warning] [1719111606] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp: lookup xxx.xxx.com on [fe80::1]:53: dial udp [fe80::1]:53: connect: no route to host] > v2ray.com/core/common/retry: all retry attempts failed`

问题+1， 莫名其妙的问题，域名和dns都是正常的
