### ISSUE TITLE
点击wv2ray.exe没有反应，进程里也找不到wv2ray，无法访问google。

### ISSUE THREAD

**Issue by hairuo** [v2ray/v2ray-core#1722]
Please answer all the questions with enough information. All issues not following this template will be closed immediately.
If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2ray/discussion/issues) first.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

v4.19.1,
v2ray-windows-64

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

点击v2ray.exe跳出命令窗口后自动消失。无法访问google。
点击wv2ray.exe没有反应，进程里也找不到wv2ray，无法访问google。
windows 7系统。

今天一直是这样，昨天使用wv2ray.exe或v2ray.exe是正常的。
另外，在Mac系统下，采用相同的config.json配置，访问google正常。

3) Please attach full panic log.

You may get panic log using command `journalctl -u v2ray` if your system is Linux (systemd).

4) Please attach your configuration file (**Mask IP addresses before submit this issue**).

```javascript
{
 "outbound": {
  "streamSettings": {
   "network": "kcp", 
   "kcpSettings": {
    "uplinkCapacity": 100, 
    "downlinkCapacity": 100, 
    "readBufferSize": 2, 
    "mtu": 1350, 
    "header": {
     "type": "utp", 
     "request": null, 
     "response": null
    }, 
    "tti": 50, 
    "congestion": false, 
    "writeBufferSize": 2
   }, 
   "wsSettings": null, 
   "tcpSettings": null, 
   "tlsSettings": {}, 
   "security": ""
  }, 
  "tag": "agentout", 
  "protocol": "vmess", 
  "mux": {
   "enabled": true
  }, 
  "settings": {
   "vnext": [
    {
     "users": [
      {
       "alterId": 100, 
       "security": "chacha20-poly1305", 
       "id": "***"
      }
     ], 
     "port": 10250, 
     "address": "*.*.*.*"
   ]
  }
 }, 
 "log": {
  "access": "", 
  "loglevel": "info", 
  "error": ""
 }, 
 "outboundDetour": [
  {
   "tag": "direct", 
   "protocol": "freedom", 
   "settings": {
    "response": null
   }
  }, 
  {
   "tag": "blockout", 
   "protocol": "blackhole", 
   "settings": {
    "response": {
     "type": "http"
    }
   }
  }
 ], 
 "inbound": {
  "streamSettings": null, 
  "settings": {
   "ip": "127.0.0.1", 
   "udp": true, 
   "clients": null, 
   "auth": "noauth"
  }, 
  "protocol": "socks", 
  "port": 1080, 
  "listen": "0.0.0.0"
 }, 
 "inboundDetour": null, 
 "routing": {
  "settings": {
   "rules": [
    {
     "ip": [
      "0.0.0.0/8", 
      "10.0.0.0/8", 
      "100.64.0.0/10", 
      "127.0.0.0/8", 
      "169.254.0.0/16", 
      "172.16.0.0/12", 
      "192.0.0.0/24", 
      "192.0.2.0/24", 
      "192.168.0.0/16", 
      "198.18.0.0/15", 
      "198.51.100.0/24", 
      "203.0.113.0/24", 
      "::1/128", 
      "fc00::/7", 
      "fe80::/10"
     ], 
     "domain": null, 
     "type": "field", 
     "port": null, 
     "outboundTag": "direct"
    }
   ], 
   "domainStrategy": "IPIfNonMatch"
  }, 
  "strategy": "rules"
 }, 
 "dns": {
  "servers": [
   "8.8.8.8", 
   "8.8.4.4", 
   "localhost"
  ]
 }
} 
```

Please review your issue before submitting.

**Comment by sunsan05** [comment]
你在CMD里面运行V2RAY看看报什么错，八成是JSON格式有误。

**Comment by hairuo** [comment]
> 你在CMD里面运行V2RAY看看报什么错，八成是JSON格式有误。

好象是的:

V2Ray 4.19.1 <Let's Fly> Custom
A unified platform for anti-censorship.
main: failed to read config file: E:\*\v2ray-windows-64\config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config.file. > v2ray.com/core/commmon/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to read config file at line 41 char 4 > invalid character ']' after object key: value pair

> exit status 4294967295
