### ISSUE TITLE
想请问一下v2day可以一个ip配置多个端口和密码进行登录吗  

### ISSUE THREAD

**Issue by ntsw0715** [v2ray/v2ray-core#1723]
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

此 Issue 会被立即关闭。

If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2ray/discussion/issues) first.

This issue will be closed immediately.

以前用ss的时候可以开放多个端口和密码给不同的用户使用，想问一下v2ray有实现的可能性吗

**Comment by kslr** [comment]
可以，参考白话文
