### ISSUE TITLE
感觉Tls1.3没必要提供明文sni

### ISSUE THREAD

**Issue by kxmp** [v2ray/v2ray-core#1726]
我用了个别人的1.3的.
然后我发现v2还把sni提供了.
tls1.3可以不提供sni的. 
我感觉是不是v2特意插了下明文sni.
一般好像不特意加入明文sni 是没有明文信息的. (我怎么忘了cdn呢!!! 不过大蜜罐很喜欢mitm别人)

现在有个情况就是这样. 那个cdn背后的机器 已经是被拉黑的了.
所以这个域名 肯定防火墙都知道了. 然后防火墙又看到人们连了个cdn 这域名还写的就是那个被拉黑了的域名. 这太明显了吧 XD.

> In TLS 1.2, the ClientHello, ServerHello and Certificate messages are all sent in clear-text, however in TLS 1.3, the Certificate message is encrypted thereby hiding the server identity from any intermediary. Note that **even if** the SNI is provided (in cleartext) by the client, there is no guarantee that the actual server responding is the one indicated in the SNI from the client.

https://tools.ietf.org/html/draft-ietf-tls-esni-01
esni看起来就是一个_esni.xxx.xxx域名. 然后.... 然后是不是又更容易被污染了 XD
客户端就用这个里面的公钥加密信息就行了 然后放到esni里面.

天哪我现在才反应过来 原来是v2不支持加密sni哇!! 
(我是不是该把这个写成feature request呢)

2019-06-07 19:49:45
看起来我的感觉非常不准. 这个加密sni没那么神. 他走的就是dns查下txt记录 然后用里面的公钥加密.
前段时间我还看到了个没sni的流量. 也不是直接访问ip. 难道是我记错了么. 太奇怪了. 而且我现在还记忆犹新. 然后今天重新一看 又不是那样 :3

**Comment by kslr** [comment]
因为golang还没有支持这一块
