### ISSUE TITLE
[Feature Request] Add a builtin dnscrypt-proxy into v2ray

### ISSUE THREAD

**Issue by iosmanthus** [v2ray/v2ray-core#1727]
For a long time, when breaking through government censorship, DNS security is a serious problem that has been seriously ignored. The built-in DNS server in v2ray is a simple DNS proxy and can't guarantee DNS security including integrity and confidentiality, so it doesn't fit our need anymore. Maybe we need to integrate a `dnscrypt-proxy` client, such as https://github.com/dnscrypt which enables us to use public `doh`/`dot` services.

Maybe it's unnecessary to add such client in `Linux` or `Windows`, but it's really useful in some mobile operating system. Mosts v2ray client in such platforms can only start up a VPN connection, so it's really hard to cooperate with currently `doh` client which need a VPN connection too.

**Comment by chromer030** [comment]
Dnscrypt is a great feature , i hope it will added soon.
