### ISSUE TITLE
希望可以支持“仅代理GFWlist”或“根据ACL进行代理”

### ISSUE THREAD

**Issue by Aidan-K** [v2ray/v2ray-core#1728]
希望可以支持“仅代理GFWlist”或“根据ACL进行代理”

**Comment by azzvx** [comment]
仅代理GFWlist可通过路由实现，需要外部文件h2y.dat(https://github.com/ToutyRater/V2Ray-SiteDAT/blob/master/geofiles/h2y.dat)
```
{
	"type": "field",
	"domain": [
		"ext:h2y.dat:gfw"
	],
	"outboundTag": "proxy"
}
```

**Comment by Kylejustknows** [comment]
我更希望是：

1，客户端智能判断连接——客户端连接某网站时先直接使用freedom试一下，如果数据流被墙被reset等无法连接，客户端然后再自动使用服务器中转。

2， 服务端能够反馈客户机，来劝说客户端直接连接—— 我给朋友用的v2ray客户端里带着旧的过时的GeoIP路由信息，挨个通知他们升级很头疼。如果客户端能和服务器握手，客户端想要访问比如说jandan.net，服务器查了下最新的路由表后回复客户端说：那个网站你直接连接就行啦， 然后客户端就老老实实地直接访问了。

**Comment by kslr** [comment]
使用clash一类的客户端即可解决
