### ISSUE TITLE
建议增加更多的 Outbound 类型

### ISSUE THREAD

**Issue by soffchen** [v2ray/v2ray-core#173]
Shadowsocks, HTTP, HTTPS, Socks5 都可以做成 Outbound 多好，因为现在有了 Dokodemo-door，这个就更有意义了，可以替代 redsocks

**Comment by v2ray** [comment]
欢迎提交 PR :) 

我也很想做这些功能，只是业余时间不够多…

**Comment by xiaokangwang** [comment]
我觉得socks5可以优先考虑。

如果想搞一个公开服务器的话，有时候会怕别人滥用，收律师函。

这时可以把网络流量输入到Tor里面，解决各种问题。

**Comment by v2ray** [comment]
这个 issue 将放在 Trello 管理。https://trello.com/b/mxvCFrh6
