### ISSUE TITLE
V2Ctl无法改名，无法避开流氓软件的监控。

### ISSUE THREAD

**Issue by Kylejustknows** [v2ray/v2ray-core#1734]
论坛内有很多汇报，某些国产的输入法、浏览器、杀毒软件等会偷偷监控和上报用户“使用xx工具科学上网"，导致很多用户私人的服务器IP被封锁。在国内完全避免使用这些国产软件又不现实。

V2ray的主程序、配置文件，都可以胡乱改名，再加个壳等方法，轻松躲开各种监控。
但就是这个V2Ctl，文件名都不能改动，导致非常容易被抓到“用户正在使用v2ray"。
（如果预先把配置文件编译成pb格式，似乎可以不用v2ctl。但这又给每次更改配置带来很多麻烦）

看了一下v2ctl，它占用那么大的体积，只发挥那么小的一点点作用，感觉很奇葩。官方是否考虑把v2ctl直接融合到主程序里得了。
（我竟然还真找到了不少网友编译的v2ray，就是v2ray和v2ctl二合一，融合到一个可执行程序里的）

**Comment by slanterns** [comment]
你改个名，然后写个脚本调用改名后的v2ctl把json转成pb然后拉起v2ray.exe就好了呗。

**Comment by slanterns** [comment]
甚至你可以把v2ray扔到Windows sandbox什么的地方让国产流氓碰不到它。

**Comment by Purple-wind-bell** [comment]
所以，你为什么要安装国产流氓软件？

**Comment by Kylejustknows** [comment]
@purple, 1，我建好一个v2ray，并不是只自己使用，我把它和proxifier打包分发给有需求的老同学、老相好等。 2，很多国产软件，搜狗输入法等，确实比同类软件要强。

**Comment by sunsan05** [comment]
你可以在公司搞一台机器，作为V2RAY客户端，其他电脑用S5代理上去就行了

**Comment by kslr** [comment]
你可以尝试删掉ctl?

**Comment by bufbrane** [comment]
可以用火绒安全软件，提供了文件夹访问监控的功能，能阻止国产流氓软件访问梯子所在的目录。开启文件夹监控的操作方法可以在网上找到。
可是问题来了，如果火绒监守自盗，又该如何防范？

**Comment by Kylejustknows** [comment]
其实二楼给的方案足够好，写一个脚本，每次更新后一运行，改名、生成pb、删除v2ctl一气呵成。

楼上的，我之前说了，我的梯子是在身边的朋友中分享的，没法让所有人都用火绒。

更何况我的一些朋友是电脑超级小白，我只能把制作好的v2ray和proxifier打包成自解压无窗口后台运行脚本，做成“一键全自动梯子”，她们才会用。火绒是啥，哈哈哈哈

**Comment by azzvx** [comment]
> 其实二楼给的方案足够好，写一个脚本，每次更新后一运行，改名、生成pb、删除v2ctl一气呵成。
> 
> 楼上的，我之前说了，我的梯子是在身边的朋友中分享的，没法让所有人都用火绒。
> 
> 更何况我的一些朋友是电脑超级小白，我只能把制作好的v2ray和proxifier打包成自解压无窗口后台运行脚本，做成“一键全自动梯子”，她们才会用。火绒是啥，哈哈哈哈

搞个好点的路由器刷个Openwrt,tomato,dd-drt,梅林什么的固件，然后在路由器上架v2ray才是硬道理。
还可以开透明代理，一劳永逸。流氓软件再NB能查到路由器上？
至于分享给别人用：申请一个动态域名，路由器上做v2ray的socks、ss、http代理的端口映射，然后告诉朋友要fq了就填你的路由器的域名和对应的端口就好了。
v2ray能做代理和用户管理，iptables能做端口限速。

**Comment by Kylejustknows** [comment]
对于我们这搞技术的来说，可能无法理解：大部分的普通人（超过90%），连“代理服务器”是什么东西，他们都不知道，更别说教他们一步步设置有多烦了。还是“一键梯子”好，双击一下就全局翻墙了；如果机子突然断电蓝屏关机，也不会有错误的代理设置留存在系统内，导致其它上网问题。

我家的openwrt上确实跑着v2ray，唯一的问题是，只要使用量稍大，就轻松吃掉所有cpu，然后家里的上网速度还好，但是类似网络对战游戏需要特别低ping的，就会受到影响延迟大增。很折腾。

现在买了阿里云的什么“轻应用”服务器，就把家里路由器上的进程给扔了。 “轻应用”一个月才几块钱，还送2TB流量死都用不完，干嘛非要折腾自己的路由器。

**Comment by azzvx** [comment]
> 对于我们这搞技术的来说，可能无法理解：大部分的普通人（超过90%），连“代理服务器”是什么东西，他们都不知道，更别说教他们一步步设置有多烦了。还是“一键梯子”好，双击一下就全局翻墙了；如果机子突然断电蓝屏关机，也不会有错误的代理设置留存在系统内，导致其它上网问题。
> 
> 我家的openwrt上确实跑着v2ray，唯一的问题是，只要使用量稍大，就轻松吃掉所有cpu，然后家里的上网速度还好，但是类似网络对战游戏需要特别低ping的，就会受到影响延迟大增。很折腾。
> 
> 现在买了阿里云的什么“轻应用”服务器，就把家里路由器上的进程给扔了。 “轻应用”一个月才几块钱，还送2TB流量死都用不完，干嘛非要折腾自己的路由器。

我是把配置好的SS客户端(就是那个SS，SS的客户端功能比较健全)，Win，Linux，安卓，IOS都有，直接发给朋友，解压即用.....
如需手动配置，发一张图手机扫扫二维码或者一个URL就搞定了。
阿里云“轻应用”峰值带宽只有10Mbps，太慢了。另外你确定阿里云上架v2ray是个好主意？

**Comment by Kylejustknows** [comment]
你的朋友们，是多少会些电脑的。
阿里轻应用是30Mbps，够用了。

阿里服务器Linux不敢用，能插入监控的地方太多。
用Win服务器，先干掉阿里监控服务，然后跑autoruns，校验系统内所有文件都是“微软签名”的（除了微软就没有第三方的程序，阿里想看你的进程都看不到）
再开启win自带的文件加密把v2ray文件夹加密（这样阿里想直接挂硬盘看你的文件都看不到），
最后创建一个强windows密码，锁屏。。这样哪怕是FBI都无法知道我的服务器上正在跑着什么。


顺便记录，json转pb的运行命令是： v2ctl config < config.json > config.pb
注意，这里面的<,>不是括号，<的意思是把config.json输入， >是指把stdout输出成config.pb文件。

**Comment by slanterns** [comment]
> 
> 
> 你的朋友们，是多少会些电脑的。
> 阿里轻应用是30Mbps，够用了。
> 
> 阿里服务器Linux不敢用，能插入监控的地方太多。
> 用Win服务器，先干掉阿里监控服务，然后跑autoruns，校验系统内所有文件都是“微软签名”的（除了微软就没有第三方的程序，阿里想看你的进程都看不到）
> 再开启win自带的文件加密把v2ray文件夹加密（这样阿里想直接挂硬盘看你的文件都看不到），
> 最后创建一个强windows密码，锁屏。。这样哪怕是FBI都无法知道我的服务器上正在跑着什么。
> 
> 顺便记录，json转pb的运行命令是： v2ctl config < config.json > config.pb
> 注意，这里面的<,>不是括号，<的意思是把config.json输入， >是指把stdout输出成config.pb文件。

真想看的话连内存都可以给你dump下来，还会担心看不到？Naive.

**Comment by LaurenceSamael** [comment]
如果有360、搜狗等，请卸载。
不要去研究超越你思维范畴的问题，网友的回复都只是义务劳动，不保证绝对有效。最有效的方法只有放弃使用国产软件，若非要执着国产软件那就不要用这台电脑出国了。

**Comment by Kylejustknows** [comment]
@LaurenceSamael 为什么同样的问题, 我要回答很多遍....  我的电脑上是没有任何流氓软件的(因为我们是快乐的技术宅), 但是我的v2ray梯子是分享给我的老同学, 老板, 同事, 好朋友, 还有我老妈.... 等等好多人向我借去使用. 我都是把V2ray打包好, 弄成双击就起飞的形式给他们.

我无法劝所有人都卸载国产软件, 更无法保证别人的电脑上现在和将来都没有流氓软件. 所以只能在我打包前, 完全伪装和隐藏好v2ray执行程序. 否则只要有一个人翻车, v2ray被抓住上传到网监, 整个梯子可能会全翻了. 

@azzvx 我是被逼着使用proxifier而不是SS的自动pac代理打包自动梯子的.  原因是, 1, 用我的梯子的朋友中有些用很奇葩的浏览器压根不支持系统设置的pac代理 (需要手动进浏览器设置添加, 她们不会).  2, 系统pac代理偶尔强关或重启后, 代理配置残留在系统, 导致上不了网 (我之前用pac自动代理打包给朋友时, 每周都要被这破事烦好多次. 对我来说恢复代理设置10秒搞定, 对小白来说断网那是天要塌了能把我手机打爆炸).  3, 系统pac代理所有软件到一个本地端口(最常见的1080是吧), 然后只要看哪个软件在占用1080端口, v2ray或SS的执行程序轻松被流氓软件抓到, 因为上述这些都是明文的.  而proxifier完美解决了所有问题: 动态地全局加载; 不改动任何系统设置不会机器断电重启后上不了网; 对软件透明, 软件压根不知道自己被代理了. 安全性和稳定性强了好多.

**Comment by LaurenceSamael** [comment]
我只能跟你说，这种东西不能分享！！
分享的后果就是翻车了网友也帮不了你，不是你隐藏了万事大吉，今年是有史以来最严格的你还不懂？
能用就自己俏咪咪用，别大肆传播。现在tcp阻断+ban ip，根本是无解。除非你肉身翻墙。

**Comment by Gooooooooooooogle** [comment]
> 可以用火绒安全软件，提供了文件夹访问监控的功能，能阻止国产流氓软件访问梯子所在的目录。开启文件夹监控的操作方法可以在网上找到。
> 可是问题来了，如果火绒监守自盗，又该如何防范？

又不是只有火绒有自定义规则，火绒太小，现阶段估计不会

**Comment by Gooooooooooooogle** [comment]
其实楼主啊，我不知道他们有什么特别需求去翻墙，既然这也不愿意那也不愿意，不翻不就行了，对大多数刷刷抖音看看微博的人来讲，你这样做徒添烦恼

**Comment by zhangjint5** [comment]
> 论坛内有很多汇报，某些国产的输入法、浏览器、杀毒软件等会偷偷监控和上报用户“使用xx工具科学上网"，导致很多用户私人的服务器IP被封锁。在国内完全避免使用这些国产软件又不现实。
> 
> V2ray的主程序、配置文件，都可以胡乱改名，再加个壳等方法，轻松躲开各种监控。
> 但就是这个V2Ctl，文件名都不能改动，导致非常容易被抓到“用户正在使用v2ray"。
> （如果预先把配置文件编译成pb格式，似乎可以不用v2ctl。但这又给每次更改配置带来很多麻烦）
> 
> 看了一下v2ctl，它占用那么大的体积，只发挥那么小的一点点作用，感觉很奇葩。官方是否考虑把v2ctl直接融合到主程序里得了。
> （我竟然还真找到了不少网友编译的v2ray，就是v2ray和v2ctl二合一，融合到一个可执行程序里的）

奇葩想法！改个名字就想蒙混过去，人家做病毒的改个名字就躲掉杀毒软件了呗！

**Comment by fbion** [comment]
mark

**Comment by Kylejustknows** [comment]
> 
> 
> > 论坛内有很多汇报，某些国产的输入法、浏览器、杀毒软件等会偷偷监控和上报用户“使用xx工具科学上网"，导致很多用户私人的服务器IP被封锁。在国内完全避免使用这些国产软件又不现实。
> > V2ray的主程序、配置文件，都可以胡乱改名，再加个壳等方法，轻松躲开各种监控。
> > 但就是这个V2Ctl，文件名都不能改动，导致非常容易被抓到“用户正在使用v2ray"。
> > （如果预先把配置文件编译成pb格式，似乎可以不用v2ctl。但这又给每次更改配置带来很多麻烦）
> > 看了一下v2ctl，它占用那么大的体积，只发挥那么小的一点点作用，感觉很奇葩。官方是否考虑把v2ctl直接融合到主程序里得了。
> > （我竟然还真找到了不少网友编译的v2ray，就是v2ray和v2ctl二合一，融合到一个可执行程序里的）
> 
> 奇葩想法！改个名字就想蒙混过去，人家做病毒的改个名字就躲掉杀毒软件了呗！

光改名肯定不行啊，我说了，改名+加壳。 我个人用的是Themida自定义虚拟机加的重量级的壳。改名后，除非遇到加解密的顶尖高手，没人能看出它内部是一个v2ray。

不过现在，通过预编译成pb格式，摆脱了v2ctl的依赖，我的“一键起飞”包里的所有文件都已经加壳+改名混淆了。用了这几年都没有什么问题。

> 其实楼主啊，我不知道他们有什么特别需求去翻墙，既然这也不愿意那也不愿意，不翻不就行了，对大多数刷刷抖音看看微博的人来讲，你这样做徒添烦恼

如果你真想知道我朋友的需求，我可以简述：几个研究生，需要看google和其它几个文献库；几个留学生朋友，假期回国期间需要查gmail学校发的重要邮件。我家人习惯原因也经常上一个海外华人里非常流行的论坛看新闻，也需要翻。
但主要问题并不是“这也不愿意那也不愿意”，而是一些朋友不会设置那些东西。
