### ISSUE TITLE
HTTPS入站协议支持

### ISSUE THREAD

**Issue by AlseinX** [v2ray/v2ray-core#1735]
上游节点在国外，下游节点在国内，都是公网IP。用于下游节点直接向浏览器提供代理服务（在客户端机器的本地不方便安装v2ray或其他转换代理协议的服务的情况下）
Chrome支持直接使用SOCKS5代理，但是不支持身份验证。也支持HTTP和HTTPS，但是v2ray不支持HTTPS，目前只能用HTTP。
HTTP全是明文，验证信息也可能被窃取，如果真的得自己搭一个前端服务把HTTP加密成HTTPS，这样要多配置和维护一个服务，也很繁琐，故是否考虑支持一下HTTPS呢？

**Comment by hahaher123** [comment]
说起来很奇怪，我配置文件里只有socks代理端口设置，但是用socks端口+1就是http、https代理端口。

还有chrome可以用SwitchyOmega，这个插件支持身份验证。

**Comment by AlseinX** [comment]
> 说起来很奇怪，我配置文件里只有socks代理端口设置，但是用socks端口+1就是http、https代理端口。
> 
> 还有chrome可以用SwitchyOmega，这个插件支持身份验证。

我就是用的SwitchyOmega，它明确指出不支持SOCKS5身份验证是因为Chrome本身不支持。
至于你的情况应该是不可能的，可能你编辑的配置并不是正在生效的配置？
如果真的有HTTPS服务，那么它用的证书又是哪提供的？

**Comment by hahaher123** [comment]
我说下我的使用环境吧。我用虚拟机装linux编译openwrt，宿主机是windows，客户端v2rayN+v2ray-core，开启了局域网接入选项,本地代理端口socks10808。虚拟机设置http/https代理，指向宿主机10809端口。他就真代理起了，v2rayN上能看到访问接入。

**Comment by Ryanstall** [comment]
> 我说下我的使用环境吧。我用虚拟机装linux编译openwrt，宿主机是windows，客户端v2rayN+v2ray-core，开启了局域网接入选项,本地代理端口socks10808。虚拟机设置http/https代理，指向宿主机10809端口。他就真代理起了，v2rayN上能看到访问接入。

+1端口的http代理是v2rayN用privoxy多加了一层代理

**Comment by kslr** [comment]
haproxy 是一个很好的方案

**Comment by cherish0** [comment]
已经支持了啊，但就是认证有点问题，我配置了以后认证失效了。
`{
  "inbounds": [
    {
      "port": 8443,
      "listen": "0.0.0.0",
      "protocol": "HTTP",
      "settings": {
        "timeout": 0,
        "accounts": [
          {
            "user": "xxx",
            "pass": "xxx"  //这边写什么都没用，不需要密码就可以连上。
          }
        ],
        "allowTransparent": false,
        "userLevel": 0
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
          "serverName": "xxx.com",
          "alpn": [
            "http/1.1"
          ],
          "certificates": [
            {
              "certificateFile": "/xxx/proxy.crt",
              "keyFile": "/xxx/proxy.key"
            }
          ]
        }
      }
    }
  ],
  "outbounds": [
    {
      "sendThrough": "0.0.0.0",
      "protocol": "Socks",
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 12345
          }
        ]
      }
    }
  ]
}
`
向上面这样配置，就可以通过https://xxx.com:8443连接代理。

顺便开发者看见也请回答一下，为什么加了tls以后认证的设置会失效。

**Comment by LisirTian** [comment]
![Image](https://github.com/user-attachments/assets/f4856758-5a2d-4f2f-8abf-915a0c7ceff8) 这样好像可以哎
