### ISSUE TITLE
Add Conditional Config on transport/(proxy)?

### ISSUE THREAD

**Issue by xiaokangwang** [v2ray/v2ray-core#174]
不同的KCP配置适用于不同用途。

如果是浏览网页，可以通过利用空闲带宽以换取低延迟，提高网页加载速度。
如果是播放视频，应该尽可能的用带宽传输有效数据，高延迟的问题可以通过视频较大的buffer(连接较大的Receiving Window)进行弥补。

可以通过对于属于不同 tag 的 destination, 应用不同的KCP配置解决这个问题。

**Comment by v2ray** [comment]
现已可以对不同的 outbound 设置不同的 kcpSettings，这个问题已解决。
