### ISSUE TITLE
路由走向诡异

### ISSUE THREAD

**Issue by XXXXXXOOOOOO** [v2ray/v2ray-core#1741]
版本 v4.19.1     v2ray-linux-64.zip 
经过各种测试  www.baidu.com 等国内网站路由走向正常,可以拦截!  但是 pan.baidu.com 路由走向很诡异,始终无法block   手动添加到domain同样无效.
 

"outbounds": [
        {
            "protocol": "freedom",
            "tag": "direct"
        },
        {
            "tag": "blocked",
            "protocol": "blackhole",
            "settings": null
        }
    ]
              

             {
                    "domain": [
                        "geosite:cn",
                    ],
                    "type": "field",
                    "outboundTag": "blocked"
                },

**Comment by XXXXXXOOOOOO** [comment]
只是 pan.baidu.com  无法 拦截  其他都是正常的..

**Comment by XXXXXXOOOOOO** [comment]
客户端只要设置dns 例如 :  8.8.8.8   服务端的拦截就会失效.

**Comment by Windendless** [comment]
{
                "ip": [
                    "geoip:cn"
                ],
                "type": "field",
                "outboundTag": "blocked"
            },

**Comment by Kylejustknows** [comment]
两个猜测
1是 pan.baidu.com 没有在geosite的cn列表中。
2是 pan.baidu.com 使用了黑科技的连接或者CDN技术（因为针对域名的阻拦，是v2ray从你的流量中嗅探出来的。）

**Comment by Windendless** [comment]
应该是百度网盘客户端没有使用标准的http协议

**Comment by XXXXXXOOOOOO** [comment]
问题我找到了  只要 v2ray client 设置 dns 8.8.8.8 他就拦不住了...114.114.114.114  可以正常拦截
