### ISSUE TITLE
服务端为ws tls时， arm和mips客户端性能问题

### ISSUE THREAD

**Issue by ntgeralt** [v2ray/v2ray-core#1743]
![Desktop Screenshot 2019 04 11 - 21 35 20 89](https://user-images.githubusercontent.com/8230651/59337768-cc2f2100-8d33-11e9-91be-14cd8b81b29b.png)

你好，我有个问题：
v2ray 软路由\PC客户端速度有28000kbps+，
树莓派2B安装v2ray做网关时，以及MT7620路由\7621路由执行v2ray配合dokodemo-door，速度一直在10000-13000kbps以内。似乎限制住了。请教一下如何提高。

**Comment by ntgeralt** [comment]
作为客户端的config.json
{
    "log": {
        "access": "./access.log",
        "error": "./error.log",
        "loglevel": "warning"
    },
    "inbounds": [{
        "port": 12345,
        "protocol": "dokodemo-door",
        "sniffing": {
          "enabled": true,
          "destOverride": ["http", "tls"]
        },
        "settings": {
          "network": "tcp",
          "timeout": 30,
          "followRedirect": true
        }
    }],
    "outbounds": [{
        "protocol": "freedom",
        "settings": {}
    }, {
        "protocol": "blackhole",
        "settings": {},
        "tag": "blocked"
    }, {
        "protocol": "vmess",
        "tag": "proxy",
        "settings": {
            "vnext": [{
                "address": "domain.com",
                "port": 443,
                "users": [{
                    "id": "dfab06ea-91f5-07ff-",
                    "security": "none"
                }]
            }]
        },
        "streamSettings": {
            "network" : "ws",
            "security": "tls",
            "wsSettings" : {
                "path" : "/1wfg5jk"
            },
            "tlsSettings" : {
                "serverName" : "domain.com",
                "allowInsecure" : true
            }
        }
    }],
    "routing": {
        "rules": [
            {
                "type": "field",
                "outboundTag": "proxy",
                "domain": [
                    "ext:h2y.dat:gfw"
                ]
            }
        ]
    }
}

**Comment by kslr** [comment]
建议放弃或者上虚拟机

**Comment by azzvx** [comment]
你的客户端CPU单核主频不够。
我的网件R7800(dual-core 1.7GHz)部署v2ray的速度如下：
![QQ截图20190613115422](https://user-images.githubusercontent.com/1546898/59402729-4615e780-8dd2-11e9-8705-b695caf79dbb.png)
另外如果是通过v2ray下载，那么速度能到5MB/s，接近40Mbps。

**Comment by ntgeralt** [comment]
@azzvx 那看来没办法了。我以为能利用上多核

**Comment by ntgeralt** [comment]
另外发现以上这样的配置文件，唯独访问facebook.com经常不出图片。广东电信的宽带，刷新dns、换电脑和换手机测试都这样……

**Comment by ihidao** [comment]
> ![Desktop Screenshot 2019 04 11 - 21 35 20 89](https://user-images.githubusercontent.com/8230651/59337768-cc2f2100-8d33-11e9-91be-14cd8b81b29b.png)
> 
> 你好，我有个问题： v2ray 软路由\PC客户端速度有28000kbps+， 树莓派2B安装v2ray做网关时，以及MT7620路由\7621路由执行v2ray配合dokodemo-door，速度一直在10000-13000kbps以内。似乎限制住了。请教一下如何提高。

请问你在MT7620上是咋运行V2RAY的，我的小米MINI 16/128刷了PADAVAN运行V2RAY可以看到V2RAY进程不断重启
