### ISSUE TITLE
全局模式下无法使用chrome打开所有网址：failed to handler mux client connection & failed to find an available destination

### ISSUE THREAD

**Issue by MasayaSym** [v2ray/v2ray-core#1744]
中文：
提交 Issue 之前请先阅读 Issue 指引，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
答：
客户端：v4.18
服务器：v4.19

你的使用场景是什么？
答：
使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频、浏览google

你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
答：
1、全局模式下无法使用chrome打开所有网址，PAC模式下无法使用chrome打开youtube等网址。
2、客户端（v2rayN）测试服务器延迟正常（<300ms）
3、客户端（v2rayN）测试服务器速度时出现以下字段：
`[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 104.238.152.26:48724: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed`
`远程服务器返回错误: (500) 内部服务器错误。`
除此外，其他日志皆类似于：
`2019/06/12 19:35:13 tcp:127.0.0.1:6608 accepted tcp:android.clients.google.com:443 `

你期待看到的正确表现是怎样的？
可以正常打开网页

请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
服务器配置：
`// 在这里附上服务器端配置文件
{
    "log": {
        "access": "/var/log/v2ray/access.log",
        "error": "/var/log/v2ray/error.log",
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "port": 48724,
            "protocol": "vmess",
                            "listen":"104.238.152.26",
            "settings": {
                "clients": [
                    {
                        "id": "dc10bea3-6409-4271-bcbe-1f66b178dbd9",
                        "level": 1,
                        "alterId": 233
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp"
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            }
        }
        ,
        {
            "protocol": "shadowsocks",
            "port": 27989,
            "settings": {
                "method": "chacha20-ietf-poly1305",
                "password": "233blog.com",
                "network": "tcp,udp",
                "level": 1,
                "ota": false
            }
        }
        //include_socks
        //include_mtproto
        //include_in_config
        //
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {}
        },
        {
            "protocol": "blackhole",
            "settings": {},
            "tag": "blocked"
        },
        {
            "protocol": "freedom",
            "settings": {},
            "tag": "direct"
        },
        {
            "protocol": "mtproto",
            "settings": {},
            "tag": "tg-out"
        }
        //include_out_config
        //
    ],
    "dns": {
        "server": [
            "1.1.1.1",
            "1.0.0.1",
            "8.8.8.8",
            "8.8.4.4",
            "localhost"
        ]
    },
    "routing": {
        "domainStrategy": "IPOnDemand",    
        "rules": [
            {
                "type": "field",
                "ip": [
                    "0.0.0.0/8",
                    "10.0.0.0/8",
                    "100.64.0.0/10",
                    "127.0.0.0/8",
                    "169.254.0.0/16",
                    "172.16.0.0/12",
                    "192.0.0.0/24",
                    "192.0.2.0/24",
                    "192.168.0.0/16",
                    "198.18.0.0/15",
                    "198.51.100.0/24",
                    "203.0.113.0/24",
                    "::1/128",
                    "fc00::/7",
                    "fe80::/10"
                ],
                "outboundTag": "blocked"
            },
            {
                "type": "field",
                "inboundTag": ["tg-in"],
                "outboundTag": "tg-out"
            }
            ,
            {
                "type": "field",
                "domain": [
                    "domain:epochtimes.com",
                    "domain:epochtimes.com.tw",
                    "domain:epochtimes.fr",
                    "domain:epochtimes.de",
                    "domain:epochtimes.jp",
                    "domain:epochtimes.ru",
                    "domain:epochtimes.co.il",
                    "domain:epochtimes.co.kr",
                    "domain:epochtimes-romania.com",
                    "domain:erabaru.net",
                    "domain:lagranepoca.com",
                    "domain:theepochtimes.com",
                    "domain:ntdtv.com",
                    "domain:ntd.tv",
                    "domain:ntdtv-dc.com",
                    "domain:ntdtv.com.tw",
                    "domain:minghui.org",
                    "domain:renminbao.com",
                    "domain:dafahao.com",
                    "domain:dongtaiwang.com",
                    "domain:falundafa.org",
                    "domain:wujieliulan.com",
                    "domain:ninecommentaries.com",
                    "domain:shenyun.com"
                ],
                "outboundTag": "blocked"
            }            ,
                {
                    "type": "field",
                    "protocol": [
                        "bittorrent"
                    ],
                    "outboundTag": "blocked"
                }
            //include_ban_ad
            //include_rules
            //
        ]
    },
    "transport": {
        "kcpSettings": {
            "uplinkCapacity": 100,
            "downlinkCapacity": 100,
            "congestion": true
        },
        "sockopt": {
            "tcpFastOpen": true
        }
    }
}
`
客户端配置:
`
    // 在这里附上客户端配置
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 10808,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "104.238.152.26",
            "port": 48724,
            "users": [
              {
                "id": "dc10bea3-6409-4271-bcbe-1f66b178dbd9",
                "alterId": 233,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "tcp",
        "security": "",
        "tlsSettings": null,
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": null,
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "dns": null,
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": []
  }
}
`

6. 请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 /var/log/v2ray/error.log 文件中。
服务器端错误日志:
`
    // 在这里附上服务器端日志
    2019/06/10 18:50:34 [Warning] v2ray.com/core: V2Ray 4.19.1 started
    2019/06/12 18:45:21 [Warning] v2ray.com/core: V2Ray 4.19.1 started
`
客户端错误日志:
`
    // 在这里附上客户端日志
--------------------------------info[18:29:56]--------------------------------
System.Exception: v2rayN start up

--------------------------------远程服务器返回错误: (500) 内部服务器错误。[18:32:15]--------------------------------
System.Net.WebException: 远程服务器返回错误: (500) 内部服务器错误。
   在 v2rayN.Handler.V2rayUpdateHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

--------------------------------info[18:46:05]--------------------------------
System.Exception: v2rayN start up

--------------------------------info[18:47:23]--------------------------------
System.Exception: v2rayN start up

--------------------------------info[19:10:45]--------------------------------
System.Exception: v2rayN start up

--------------------------------info[19:11:22]--------------------------------
System.Exception: Webserver prefixes http://127.0.0.1:10810/pac/

--------------------------------info[19:11:22]--------------------------------
System.Exception: Webserver running...

--------------------------------在 WebClient 请求期间发生异常。[19:12:03]--------------------------------
System.Net.WebException: 在 WebClient 请求期间发生异常。 ---> System.IO.IOException: 文件“C:\Users\MasayaSym\Desktop\v2rayN-Core\v2rayN-Core\v2ray-windows.zip”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   在 System.Net.WebClient.DownloadFileAsync(Uri address, String fileName, Object userToken)
   --- 内部异常堆栈跟踪的结尾 ---
   在 v2rayN.Handler.V2rayUpdateHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

--------------------------------info[19:12:16]--------------------------------
System.Exception: Webserver Stop 127.0.0.1

--------------------------------info[19:12:16]--------------------------------
System.Exception: Webserver prefixes http://127.0.0.1:10810/pac/

--------------------------------由于线程退出或应用程序请求，已中止 I/O 操作。[19:12:16]--------------------------------
System.Net.HttpListenerException (0x80004005): 由于线程退出或应用程序请求，已中止 I/O 操作。
   在 System.Net.HttpListener.GetContext()
   在 v2rayN.HttpProxyHandler.HttpWebServer.<Run>b__4_0(Object o)

--------------------------------info[19:12:16]--------------------------------
System.Exception: Webserver running...

--------------------------------info[19:12:16]--------------------------------
System.Exception: Webserver Stop 127.0.0.1

--------------------------------句柄无效。[19:12:16]--------------------------------
System.Net.HttpListenerException (0x80004005): 句柄无效。
   在 System.Net.HttpListener.GetContext()
   在 v2rayN.HttpProxyHandler.HttpWebServer.<Run>b__4_0(Object o)

--------------------------------info[19:12:16]--------------------------------
System.Exception: Webserver prefixes http://127.0.0.1:10810/pac/

--------------------------------info[19:12:16]--------------------------------
System.Exception: Webserver running...

--------------------------------基础连接已经关闭: 发送时发生错误。[19:13:51]--------------------------------
System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 v2rayN.Handler.V2rayUpdateHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

--------------------------------info[19:28:20]--------------------------------
System.Exception: Webserver Stop 127.0.0.1

--------------------------------由于线程退出或应用程序请求，已中止 I/O 操作。[19:28:20]--------------------------------
System.Net.HttpListenerException (0x80004005): 由于线程退出或应用程序请求，已中止 I/O 操作。
   在 System.Net.HttpListener.GetContext()
   在 v2rayN.HttpProxyHandler.HttpWebServer.<Run>b__4_0(Object o)

--------------------------------info[19:29:35]--------------------------------
System.Exception: v2rayN start up

--------------------------------info[19:29:35]--------------------------------
System.Exception: Webserver prefixes http://127.0.0.1:10810/pac/

--------------------------------info[19:29:35]--------------------------------
System.Exception: Webserver running...

--------------------------------info[19:31:01]--------------------------------
System.Exception: Webserver Stop 127.0.0.1

--------------------------------由于线程退出或应用程序请求，已中止 I/O 操作。[19:31:01]--------------------------------
System.Net.HttpListenerException (0x80004005): 由于线程退出或应用程序请求，已中止 I/O 操作。
   at System.Net.HttpListener.GetContext()
   at v2rayN.HttpProxyHandler.HttpWebServer.<Run>b__4_0(Object o)

--------------------------------info[19:31:04]--------------------------------
System.Exception: v2rayN start up

--------------------------------info[19:31:05]--------------------------------
System.Exception: Webserver prefixes http://127.0.0.1:10810/pac/

--------------------------------info[19:31:05]--------------------------------
System.Exception: Webserver running...

--------------------------------info[19:31:21]--------------------------------
System.Exception: Webserver Stop 127.0.0.1

--------------------------------由于线程退出或应用程序请求，已中止 I/O 操作。[19:31:21]--------------------------------
System.Net.HttpListenerException (0x80004005): 由于线程退出或应用程序请求，已中止 I/O 操作。
   在 System.Net.HttpListener.GetContext()
   在 v2rayN.HttpProxyHandler.HttpWebServer.<Run>b__4_0(Object o)

--------------------------------远程服务器返回错误: (500) 内部服务器错误。[19:32:50]--------------------------------
System.Net.WebException: 远程服务器返回错误: (500) 内部服务器错误。
   在 v2rayN.Handler.V2rayUpdateHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

`
7. 请附上访问日志。在 Linux 中，日志通常在 /var/log/v2ray/error.log 文件中。
 ` 
    // 在这里附上服务器端日志
    2019/06/10 18:50:34 [Warning] v2ray.com/core: V2Ray 4.19.1 started
    2019/06/12 18:45:21 [Warning] v2ray.com/core: V2Ray 4.19.1 started
`
8. 其它相关的配置文件（如 Nginx）和相关日志。
请预览一下你填的内容再提交。
如果你已经填完上面的问卷，请把下面的英文部份删除，再提交 Issue

**Comment by nicholascw** [comment]
首先提醒你不要公开 uuid 和 服务器.
另外 你的端口号 48724 从我观察来看并不处于LISTEN状态而是CLOSED.
建议检查你的监听端口配置是否有效.

> BSD使用的临时端口范围是1024到4999。
> IANA建议49152至65535作为“动态或私有端口”。
> 许多Linux内核使用32768至61000范围。配置文件/proc/sys/net/ipv4/ip_local_port_range有当前系统设定。

ref: https://zh.wikipedia.org/wiki/%E4%B8%B4%E6%97%B6%E7%AB%AF%E5%8F%A3
