### ISSUE TITLE
同一个vps使用kcptun正常，使用mkcp被封端口QOS

### ISSUE THREAD

**Issue by tefiszx** [v2ray/v2ray-core#1749]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
**4.19**
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
**使用浏览器浏览外网**
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
**使用v2ray的mkcp连接vps的inbound端口，连接一段时间后，连接断开，再也连接不上，更换vps的inbound端口后可以正常连接，过一段时间（5分钟左右）再次断开连接。把vps端口号更换的一下，又恢复正常，但是把vps的端口号换成曾经使用过的且被封的端口，就再也连接不上了。我使用的vps是GCP**
4) 你期待看到的正确表现是怎样的？
**mkcp的连接正常，不断流，我指定的任何一个端口号都能正常连接，而不是被封的端口再也连接不上**
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:
   

客户端配置:

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
   2019/06/14 09:43:20 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/14 09:43:20 [Warning] [622190179] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.
2019/06/14 09:43:20 [Warning] [4013183378] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.
2019/06/14 09:43:20 [Warning] [1858335994] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.
2019/06/14 09:43:20 [Warning] [1076679016] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.
2019/06/14 09:43:20 [Warning] [2909648724] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.
2019/06/14 09:43:20 [Warning] [1723729756] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.
2019/06/14 09:43:20 [Warning] [848031968] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.

```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by forgotmymilk** [comment]
请教kcp怎么配置的，我参考 https://ssr.tools/588 教程配置，怎么配都连接不上。不知道哪里出的问题，能帮我看看吗？谢谢！
截图地址：
https://www.screencast.com/t/sU6lkRiRN

**Comment by blinkspark** [comment]
你服务器ip写错了
1270.0.01 -> 127.0.0.1

**Comment by blinkspark** [comment]
@tefiszx 你这服务器端都报错了怎么会是被封端口呢

**Comment by Kylejustknows** [comment]
@blinkspark 看起来像是，端口被封后，服务器端等待超时了。

没想到，kcp的动态端口，竟然还真的有存在的必要啊。

楼主要不试一试看看？

**Comment by sym233** [comment]
我也遇到了类似的情况，mkcp不通，也是一样的 unable to set read deadline，更换端口可用。
普通连接正常

**Comment by YifengGao666** [comment]
我也遇到了同样的问题。怎么都找不出原因。是不是有些vps运营商不支持kcp？一检测到就封端口
