### ISSUE TITLE
Add statistical data collector and auto connection tagging for v2ray

### ISSUE THREAD

**Issue by xiaokangwang** [v2ray/v2ray-core#175]
v2ray应该具有对于连接的统计数据进行统计的功能，记录每个连接的
- 连接的域名
- 连接的端口
- 连接开始关闭时间
- 连接非空闲平均传输速度(上下行分别记录)
- 连接的速度峰值(上下行分别记录)

记录网络的
- 连接的速度峰值(上下行分别记录)

通过记录这些内容可以更加智能的自动区分流量，为不同的连接自动打上不同的标记，智能的应用不同的配置 #174 ， 更加有效的利用带宽和网络，提高翻墙的体验。

让井底之蛙们知道在更广阔的天地间，还能有另一种活法，比委身于审查更好的活法。

**Comment by v2ray** [comment]
比较好的方式是把原始数据汇报给一个外部程序，由外部程序进行统计和汇总。见：https://github.com/v2ray/Planning/issues/2
