### ISSUE TITLE
quic 教程的两个疑问

### ISSUE THREAD

**Issue by choicky** [v2ray/v2ray-core#1751]
疑问1：如何关闭 VMess的加密？

官网提到 `在使用 QUIC 传输时，可以关闭 VMess 的加密`，那么，如何关闭 VMess的加密呢？

疑问2：已经 tls 了还需要加密吗？

官网提到 `为了避免被探测，建议加密或伪装至少开启一项`，但是，官网有已经提到 `QUIC 强制要求开启 TLS`，为什么已经启用了 tls 还需要 quic 加密或者伪装呢？

**Comment by kingwilliam** [comment]
'
资料来源
https://www.v2ray.com/chapter_02/protocols/vmess.html


{
  "vnext": [
    {
      "address": "127.0.0.1",
      "port": 37192,
      "users": [
        {
          "id": "uuid",
          "alterId": 4,
          "security": "auto",   <- security: "aes-128-gcm" | "chacha20-poly1305" | "auto" | "none" = 关闭
          "level": 0
        }
      ]
    }
  ]
}'

**Comment by choicky** [comment]
多谢多谢。

**Comment by Kylejustknows** [comment]
第二个问题的原因是， TLS已经无法完全避开墙的监控了。 现在墙已经能从TLS加密的数据中，通过神经网络训练、信息指纹、数据尺寸等方法，嗅探出很多用户翻墙上网信息（从而导致很多其他的代理软件的沦陷——反过来说，如果简单地TLS加密就能迷惑住墙，那么v2ray/vmess压根没有存在的必要了）

**Comment by funnypro** [comment]
> 第二个问题的原因是， TLS已经无法完全避开墙的监控了。 现在墙已经能从TLS加密的数据中，通过神经网络训练、信息指纹、数据尺寸等方法，嗅探出很多用户翻墙上网信息（从而导致很多其他的代理软件的沦陷——反过来说，如果简单地TLS加密就能迷惑住墙，那么v2ray/vmess压根没有存在的必要了）

假设 tls 都可以被知道与目标有什么活动信息的话，那么网络就是裸奔了

**Comment by Kylejustknows** [comment]
> 假设 tls 都可以被知道与目标有什么活动信息的话，那么网络就是裸奔了
现在情况是, tls嗅探并无法判断出你具体输入了什么密码, 但是能准确判断出你访问了什么网站.
tls没有数据混淆. 打个比方(这里只是个举例, 实际用的嗅探技术比这精密复杂) : 你访问U管会先读取基础http文档220kb, 再读取logo图片15kb, 读取css 8kb,然后是一堆5kb的视频列表图, 最后是尾部脚本40kb.
防火墙的数据嗅探和指纹分析, 会发现你的一个海外tls链接, 产生了200kb+15kb+8kb+一堆小数据+40kb的流量波峰, 就判定你大概率地正在在用tls加密代理在访问U管首页, 然后就把你服务器的IP直接Ban掉了.

早年很多软件开发者都低估了墙的数据分析能力, 以为用个tls等国际公认的加密就安全了, 结果是shadowsocks和专业vpn提供商大面积的沦陷, 大量服务器被封. 一直到强力的混淆算法和混淆插件被重视后才有所改善. vmess因为后发, 就是做的比较好的了, 一开始就把强加密和强混淆都做进来了.

**Comment by funnypro** [comment]
> > 假设 tls 都可以被知道与目标有什么活动信息的话，那么网络就是裸奔了
> 
> 现在情况是, tls嗅探并无法判断出你具体输入了什么密码, 但是能准确判断出你访问了什么网站.
> tls没有数据混淆. 打个比方(这里只是个举例, 实际用的嗅探技术比这精密复杂) : 你访问U管会先读取基础http文档220kb, 再读取logo图片15kb, 读取css 8kb,然后是一堆5kb的视频列表图, 最后是尾部脚本40kb.
> 防火墙的数据嗅探和指纹分析, 会发现你的一个海外tls链接, 产生了200kb+15kb+8kb+一堆小数据+40kb的流量波峰, 就判定你大概率地正在在用tls加密代理在访问U管首页, 然后就把你服务器的IP直接Ban掉了.
> 
> 早年很多软件开发者都低估了墙的数据分析能力, 以为用个tls等国际公认的加密就安全了, 结果是shadowsocks和专业vpn提供商大面积的沦陷, 大量服务器被封. 一直到强力的混淆算法和混淆插件被重视后才有所改善. vmess因为后发, 就是做的比较好的了, 一开始就把强加密和强混淆都做进来了.

那么，请问
根据你的第二段话，是否所有符合浏览油管的流量都属于在看油管？
而且，你如何证实你说的这话？

**Comment by funnypro** [comment]
> 疑问1：如何关闭 VMess的加密？
> 
> 官网提到 `在使用 QUIC 传输时，可以关闭 VMess 的加密`，那么，如何关闭 VMess的加密呢？
> 
> 疑问2：已经 tls 了还需要加密吗？
> 
> 官网提到 `为了避免被探测，建议加密或伪装至少开启一项`，但是，官网有已经提到 `QUIC 强制要求开启 TLS`，为什么已经启用了 tls 还需要 quic 加密或者伪装呢？

我个人说一下， quic 是传输协议，它需要 tls 来提供支持，所以必须启用 tls（个人不太清楚 quic 是否允许明文（并且目前 quic 标准似乎很混乱

**Comment by kingwilliam** [comment]
个人觉得又不用太过杞人忧天 如连神经网络也用上 那为甚麽不用上天河2号 这谁也翻不了墙。 只要不被墙钉上 就算安全 ，一但给钉上 真的就会出现上面说的状况。

**Comment by Kylejustknows** [comment]
> > 现在情况是, tls嗅探并无法判断出你具体输入了什么密码, 但是能准确判断出你访问了什么网站.
> > tls没有数据混淆. 打个比方(这里只是个举例, 实际用的嗅探技术比这精密复杂) : 你访问U管会先读取基础http文档220kb, 再读取logo图片15kb, 读取css 8kb,然后是一堆5kb的视频列表图, 最后是尾部脚本40kb.
> > 防火墙的数据嗅探和指纹分析, 会发现你的一个海外tls链接, 产生了200kb+15kb+8kb+一堆小数据+40kb的流量波峰, 就判定你大概率地正在在用tls加密代理在访问U管首页, 然后就把你服务器的IP直接Ban掉了.
> > 早年很多软件开发者都低估了墙的数据分析能力, 以为用个tls等国际公认的加密就安全了, 结果是shadowsocks和专业vpn提供商大面积的沦陷, 大量服务器被封. 一直到强力的混淆算法和混淆插件被重视后才有所改善. vmess因为后发, 就是做的比较好的了, 一开始就把强加密和强混淆都做进来了.
> 
> 那么，请问
> 根据你的第二段话，是否所有符合浏览油管的流量都属于在看油管？
> 而且，你如何证实你说的这话？

指纹分析, 不光光是看浏览, 我说了真实情况比这例子更精密复杂, 我只是为了让你看明白举了一个很傻的例子. 并且防火墙现在确实是这样的: 宁愿错杀一千, 也不放过一个(比如eMule使用模糊协议连接国外服务器时会被直接阻断. 我之前自己开发的一个通讯小工具放在国外服务器, 连接也一直被中断. 只要防火墙不确定某个连接是干什么用的, 就很可能进行中断) 具体的指纹嗅探算法怎样抓你使用翻墙技术来看U管, 网上有一些技术大神的分析文章请自己查阅. 但使用"数据包大小"来嗅探是已经确定的方法之一, 所以包括vmass, SSR在内的混淆插件里, 都有用随机大小的垃圾数据增加每段数据长度的代码(一段时间抵御住了早期的指纹分析, 大概一两年吧, 后来防火墙使用了卷积神经网络)

嗅探+大数据分析+神经网络现在非常厉害. 甚至服务软件编写用的是Python还是Go语言, 都能从数据连接和封包的细微之处判断出来(这是技术人员的实验结果, 但推论咱的防火墙同样也有类似的能力).

证明1, 国内使用各种"通道技术"建过梯子, 我非常有经验, 我知道哪些加密技术指纹很明显会被瞬间封IP, 哪些技术有一定混淆能力能翻墙一阵子, 但是刷网站几分钟后, 指纹被识别出来后封端口封IP. (说明防火墙并不是使用100%确定的算法, 而是需要抓包分析一段时间后, 才能判断你是否在翻墙)

证明2, SS早年版本用的强加密(都是国际标准加密), 但被防火墙充分识别完全沦陷, 这些都是历史事实了, 旧帖子旧文章很多. 后来还有被网友找出来的关于SS指纹嗅探技术的论文和专利(请自己搜索, 文章帖子很多). 而防火墙使用人工学习和神经网络也是官方给出来的.  加上国际上通用的, 全世界技术员都以为非常安全的强加密的协议"openvpn" 或者 "ssh tunnel" 或者 "ipsec vpn", 现在都是全面沦陷, 如果你使用, 5分钟内就会被嗅探出来并且封服务器IP. 所以才会有"有中国特色的"通道软件SSR和V2ray的存在啊.

**Comment by Kylejustknows** [comment]
> 个人觉得又不用太过杞人忧天 如连神经网络也用上 那为甚麽不用上天河2号 这谁也翻不了墙。 只要不被墙钉上 就算安全 ，一但给钉上 真的就会出现上面说的状况。

就怕有天开始实行白名单制度: 只有申请过或者经过官方认证的海外网站服务器(比如说微软啊, 苹果啊)能够连接, 其他所有未知的服务器未知的IP地址全部屏蔽. 那时就真的翻不了墙了.

**Comment by ntgeralt** [comment]
我看到楼上有人杞人忧天，杞人忧天的底层源自于对事物不了解，如不了解天河3号算力和全球网站网民数量关系

**Comment by kslr** [comment]
过好当下

**Comment by jackwangshanghai** [comment]
其实的确很神奇，竟然QUIC+VMESS，但是VMESS已经提供加密和和Padding。然后QUIC自己也是TLS加密。为啥QUIC自己还要进行伪装。 就好比 TCP+TLS+VMESS能保证安全的话。那么QUIC+TLS+VMESS为啥就不可以。为啥在QUIC层还要进行伪装或加密，咱一直有这个疑问。

**Comment by Kylejustknows** [comment]
> 
> 
> 其实的确很神奇，竟然QUIC+VMESS，但是VMESS已经提供加密和和Padding。然后QUIC自己也是TLS加密。为啥QUIC自己还要进行伪装。 就好比 TCP+TLS+VMESS能保证安全的话。那么QUIC+TLS+VMESS为啥就不可以。为啥在QUIC层还要进行伪装或加密，咱一直有这个疑问。

不是QUIC想加密，而是QUIC这个协议在谷歌制定的时候，它本身就要求有加密。VMESS也是，协议自身就含有加密。所以就这样了。

**Comment by jackwangshanghai** [comment]
> > 其实的确很神奇，竟然QUIC+VMESS，但是VMESS已经提供加密和和Padding。然后QUIC自己也是TLS加密。为啥QUIC自己还要进行伪装。 就好比 TCP+TLS+VMESS能保证安全的话。那么QUIC+TLS+VMESS为啥就不可以。为啥在QUIC层还要进行伪装或加密，咱一直有这个疑问。
> 
> 不是QUIC想加密，而是QUIC这个协议在谷歌制定的时候，它本身就要求有加密。VMESS也是，协议自身就含有加密。所以就这样了。

当加密和伪装都不启用时，数据包即为原始的 QUIC 数据包，可以与其它的 QUIC 工具对接。为了避免被探测，建议加密或伪装至少开启一项。

我看文档有这句话，所以这个伪装和加密应该不是QUIC自己就有的。QUIC自带的应该是 TLS加密。
而且这个QUICObject Key字段是属于Pre-shared Key。QUIC自带的TLS应该不属于Pre-shared Key。

而且这个加密可以配置为none 也就是不加密。推荐加密和混淆开启一个。所以这个加密肯定不是QUIC 本身要求的加密。

**Comment by Kylejustknows** [comment]
是的,我错了,刚看了下,确实是如此. 它可以加密数层, Vmess自带加密了一次, 开启QUIC加密选项把数据流再加密一次, QUIC传输协议用TLS再加密一次.
我要是墙的管理员, 我看到V2Ray就想吐.

**Comment by CrazyBoyFeng** [comment]
> > 假设 tls 都可以被知道与目标有什么活动信息的话，那么网络就是裸奔了
> 
> 现在情况是, tls嗅探并无法判断出你具体输入了什么密码, 但是能准确判断出你访问了什么网站.
> tls没有数据混淆. 打个比方(这里只是个举例, 实际用的嗅探技术比这精密复杂) : 你访问U管会先读取基础http文档220kb, 再读取logo图片15kb, 读取css 8kb,然后是一堆5kb的视频列表图, 最后是尾部脚本40kb.
> 防火墙的数据嗅探和指纹分析, 会发现你的一个海外tls链接, 产生了200kb+15kb+8kb+一堆小数据+40kb的流量波峰, 就判定你大概率地正在在用tls加密代理在访问U管首页, 然后就把你服务器的IP直接Ban掉了.
> 
> 早年很多软件开发者都低估了墙的数据分析能力, 以为用个tls等国际公认的加密就安全了, 结果是shadowsocks和专业vpn提供商大面积的沦陷, 大量服务器被封. 一直到强力的混淆算法和混淆插件被重视后才有所改善. vmess因为后发, 就是做的比较好的了, 一开始就把强加密和强混淆都做进来了.

tls 本身就是加密，而且 tls1.3 用的就是无特征的 aead 加密，再套一层加密不就等同于是用 aead 给数据部分来两遍加密？如果认为 tls 加密过的数据部分仍然有比较明显的特征或指纹，那么不就相当于认为加密算法不可靠吗？  
流量模型检测也有应对策略：随机 padding 填充，也就是填充随机长度的垃圾数据。切割数据包后带时序传送是另外一种办法，虽然 gfw 如果想的话可以搜集后合并分析。但是这增加了 gfw 的分析成本。  
tls 的连接被识别的问题，我觉得应该更加关注 hello 数据包的明文部分的特征，以及 tls 包头部的冗余信息里的客户端/服务器指纹。  

（我是听人说 tls 后面也需要加密，对这个结论很困惑，从相关搜索进入这个 issue 的。但我一直没找到令我信服的论证，如果阁下有相关资料，希望阁下能与我分享。）

**Comment by Kylejustknows** [comment]
> > > 假设 tls 都可以被知道与目标有什么活动信息的话，那么网络就是裸奔了
> > 
> > 
> > 现在情况是, tls嗅探并无法判断出你具体输入了什么密码, 但是能准确判断出你访问了什么网站.
> > tls没有数据混淆. 打个比方(这里只是个举例, 实际用的嗅探技术比这精密复杂) : 你访问U管会先读取基础http文档220kb, 再读取logo图片15kb, 读取css 8kb,然后是一堆5kb的视频列表图, 最后是尾部脚本40kb.
> > 防火墙的数据嗅探和指纹分析, 会发现你的一个海外tls链接, 产生了200kb+15kb+8kb+一堆小数据+40kb的流量波峰, 就判定你大概率地正在在用tls加密代理在访问U管首页, 然后就把你服务器的IP直接Ban掉了.
> > 早年很多软件开发者都低估了墙的数据分析能力, 以为用个tls等国际公认的加密就安全了, 结果是shadowsocks和专业vpn提供商大面积的沦陷, 大量服务器被封. 一直到强力的混淆算法和混淆插件被重视后才有所改善. vmess因为后发, 就是做的比较好的了, 一开始就把强加密和强混淆都做进来了.
> 
> tls 本身就是加密，而且 tls1.3 用的就是无特征的 aead 加密，再套一层加密不就等同于是用 aead 给数据部分来两遍加密？如果认为 tls 加密过的数据部分仍然有比较明显的特征或指纹，那么不就相当于认为加密算法不可靠吗？
> 流量模型检测也有应对策略：随机 padding 填充，也就是填充随机长度的垃圾数据。切割数据包后带时序传送是另外一种办法，虽然 gfw 如果想的话可以搜集后合并分析。但是这增加了 gfw 的分析成本。
> tls 的连接被识别的问题，我觉得应该更加关注 hello 数据包的明文部分的特征，以及 tls 包头部的冗余信息里的客户端/服务器指纹。
> 
> （我是听人说 tls 后面也需要加密，对这个结论很困惑，从相关搜索进入这个 issue 的。但我一直没找到令我信服的论证，如果阁下有相关资料，希望阁下能与我分享。）

Tls加密够强，但是防探测不强。有这么一段时间，很多人用各种加密算法结果被封，就有很多流言和说法，说xxx加密不行yyy加密被破解等等。现在回头看那段时期，其实很可能并没有哪个加密算法被破解，只是被指纹探测了。

简单的混淆比如说随机padding也不行了，在墙的眼里，你每个包的长度，对比访问youtube的长度，增加的长度符合某范围内的随机特性并且增加量的平均值稳定，也会认定你在看youtube。神经网络从杂乱数据中找到规律的能力非常强。

**Comment by CryptSphere** [comment]
> Tls加密够强，但是防探测不强。有这么一段时间，很多人用各种加密算法结果被封，就有很多流言和说法，说xxx加密不行yyy加密被破解等等。现在回头看那段时期，其实很可能并没有哪个加密算法被破解，只是被指纹探测了。
> 
> 简单的混淆比如说随机padding也不行了，在墙的眼里，你每个包的长度，对比访问youtube的长度，增加的长度符合某范围内的随机特性并且增加量的平均值稳定，也会认定你在看youtube。神经网络从杂乱数据中找到规律的能力非常强。

我以前使用简单的随机填充，每次发布编辑后经常被断开连接，后来我每200次慢慢地改变随机函数的输入参数，然后就能保持连接。

**Comment by AkiyaKiko** [comment]
> 
预言家

**Comment by Kylejustknows** [comment]
> 我以前使用简单的随机填充，每次发布编辑后经常被断开连接，后来我每200次慢慢地改变随机函数的输入参数，然后就能保持连接。

对的。虽然说随机的意思就是没有规律。但“高度随机”，这就是一个数学特性同时也是一个规律。

**Comment by koalabearguo** [comment]
加密混淆太多也用处不大，如果你的服务器IP没有备案过，又天天大流量传输数据，很快你的IP就被照顾了；自己搭建的HTTPS代理服务，都用了7-8年了，就自己查资料用，偶尔看看yt，从来没被照顾过。另外今年用go写了个socks5 over quic的工具，也是天天用，基本没遇到啥问题，就是晚上UDP QOS比较严重，这个国内环境确实有点chedan。
