### ISSUE TITLE
无法直接使用v2ray，必须通过SwitchyOmega

### ISSUE THREAD

**Issue by wc394915432** [v2ray/v2ray-core#1753]
导入vmess地址后并不能直接使用，如果自己手动设置系统代理地址为127.0.0.1:8080会报：rejected v2ray.com/core/proxy/socks: unknown Socks version: 67

最后下了个google chrome 代理插件才终于连接成功，我不知道是故意做成这样的吗？

**Comment by isekai** [comment]
在教程中常见问题写到
```
Socks: Unknown Socks version: 67
可能的原因：
你开启的是 Socks 代理，但在浏览器中配置了 HTTP 代理
解决方案：
在 V2Ray 中配置一个 HTTP 入站代理，然后把浏览器的设置指向这个代理
```

**Comment by wc394915432** [comment]
> 在教程中常见问题写到
> 
> ```
> Socks: Unknown Socks version: 67
> 可能的原因：
> 你开启的是 Socks 代理，但在浏览器中配置了 HTTP 代理
> 解决方案：
> 在 V2Ray 中配置一个 HTTP 入站代理，然后把浏览器的设置指向这个代理
> ```

你好，能说一下在哪里配的吗？我找了一下v2ray配置界面没有找到哪里可以配置HTTP代理，本地监听端口旁边的协议选项是暗的不能修改。

**Comment by kslr** [comment]
https://v2ray.com/chapter_02/protocols/http.html
