### ISSUE TITLE
Cannot install V2ray on Windows Subsystem for Linux (Ubuntu)

### ISSUE THREAD

**Issue by gujia9999** [v2ray/v2ray-core#1757]
I tried to install v2ray via command bash <(curl -L -s https://install.direct/go.sh) on WSL. It appeared not to work.
![image](https://user-images.githubusercontent.com/36025500/59617011-e0768200-9168-11e9-99f9-513b9b4ee419.png)
有没有试过在win10 ubuntu子系统上面安装V2ray? 不知道为什么装不上。。

**Comment by EleComb** [comment]
use 
```
sudo wget https://install.direct/go.sh
```
我用我装上了，你用你也能装上。

**Comment by w2c17lin** [comment]
> use
> 
> ```
> sudo wget https://install.direct/go.sh
> ```
> 
> 我用我装上了，你用你也能装上。

我的不行哎,报错这个，老哥遇见过吗
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to load config:  > v2ray.com/core/main/confloader/external: config file not readable > open : no such file or directory

**Comment by Cwek** [comment]
加载配置文件？

**Comment by w2c17lin** [comment]
> 加载配置文件？

指定了配置文件，还是报错A unified platform for anti-censorship.

**Comment by FPG-Alan** [comment]
> > 加载配置文件？
> 
> 指定了配置文件，还是报错A unified platform for anti-censorship.

这个不是报错， 只是v2ray的声明啦
