### ISSUE TITLE
vmess allows multiple client with same UUID

### ISSUE THREAD

**Issue by vangork** [v2ray/v2ray-core#1759]
1. vmess protocol allows to add multiple clients with same uuid both from config file and api meanwhile same email is prohabited.
Not sure if it is be design. However from the state statistics perspective, there is a bug here as if we config multiple clients with the same UUID but with different emails, all traffic usage will be counted into the lastest added email account as the client side doest has the email param.

2. hope to enable API to list all the avaiable clients as there is no way to check the API added clients.(not sure if it is possible now, at least i cannot refer to any information from the offical document)

thanks!

**Comment by Kylejustknows** [comment]
1. It is not a bug. UUID is the main "ID" and main "password" for the system while email address is only like a sidenote/description. Normally UUID shouldn't be the same for different users, and none of the official nor 3rd-party v2ray client supports connecting using email address as a part of the credential so this won't be changed in the near future. In your case (Same UUID diff emails), there are only 2 options you left to v2ray system: a) lost the count of the traffic ; b) count it onto one of the email among all the emails with the same UUID.

2, I think it is good advice although it is easy to keep a record of "created accounts" elsewhere.

**Comment by Xyncgas** [comment]
as the author have said, it's all luck, and it works now doesnt mean that it will work the next second, since according to documentation this is not recommended, although there is seemingly no harm in letting data through connections made with the same uuid for as long
