### ISSUE TITLE
无法正确获取本地dns&手动设置dns不生效

### ISSUE THREAD

**Issue by rhjdvsgsgks** [v2ray/v2ray-core#1760]
Please read the [instruction](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md) and answer the following questions before submitting your issue. Thank you.
Please answer all the questions with enough information. All issues not following this template will be closed immediately.
If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2ray/discussion/issues) first.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
4.19.1

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
根据[教程](https://docs.google.com/document/d/1lanYeQbELX7pytehvXO8SndZ0iGyivc2XopkMV5HWW0)配置v2ray访问pixiv
设备为手机，ca证书已安装
浏览器为yandex browser，安装了switchyomega，设置代理为socks5 127.0.0.1:1080
3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)
访问pixiv等网站时提示 err_empty_response
访问不通过代理的网站时提示 err_connection_closed

4) What's your expectation?
正常访问网络（至少不通过代理的网站可以正常访问）

5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

Server configuration:

```javascript
    // Please attach your server configuration here.
```

Client configuration:

```javascript
{
    "log":{
        "access":"/storage/emulated/0/v2ray/access.log",
        "error":"/storage/emulated/0/v2ray/error.log",
        "loglevel":"info"
    },
    "inbounds":[
        {
            "port":1080,
            "listen":"127.0.0.1",
            "tag":"socks-inbound",
            "protocol":"socks",
            "settings":{
                "auth":"noauth",
                "udp":false,
                "ip":"127.0.0.1"
            },
            "sniffing":{
                "enabled":true,
                "destOverride":[
                    "http",
                    "tls"
                ]
            }
        },
        {
            "listen":"127.0.0.1",
            "port":443,
            "tag":"tls-in",
            "protocol":"dokodemo-door",
            "settings":{
                "network":"tcp",
                "port":443,
                "followRedirect":true
            },
            "streamSettings":{
                "security":"tls",
                "tlsSettings":{
                    "alpn":[
                        "http/1.1"
                    ],
                    "certificates":[
                        {
                            "usage":"issue",
                            "certificate":[
                                "-----BEGIN CERTIFICATE-----",
                                "-----END CERTIFICATE-----"
                            ],
                            "key":[
                                "-----BEGIN RSA PRIVATE KEY-----",
                                "-----END RSA PRIVATE KEY-----"
                            ]
                        }
                    ]
                }
            }
        }
    ],
    "outbounds":[
        {
            "protocol":"freedom",
            "settings":{

            },
            "tag":"direct"
        },
        {
            "protocol":"blackhole",
            "settings":{

            },
            "tag":"blocked"
        },
        {
            "protocol":"freedom",
            "tag":"no-sni-out",
            "settings":{

            },
            "streamSettings":{
                "security":"tls",
                "tlsSettings":{
                    "alpn":[
                        "http/1.1"
                    ],
                    "serverName":"experiment:8357"
                }
            }
        },
        {
            "protocol":"freedom",
            "tag":"redirect",
            "settings":{
                "redirect":"127.0.0.1:443"
            }
        }
    ],
    "routing":{
        "domainStrategy":"IPOnDemand",
        "rules":[
            {
                "type":"field",
                "domain":[
                    "geosite:category-ads"
                ],
                "outboundTag":"blocked"
            },
            {
                "inboundTag":[
                    "tls-in"
                ],
                "outboundTag":"no-sni-out",
                "type":"field"
            },
            {
                "inboundTag":[
                    "socks-inbound"
                ],
                "domain":[
                    "geosite:pixiv"
                ],
                "port":"443",
                "outboundTag":"redirect",
                "type":"field"
            },
            {
                "inboundTag":[
                    "socks-inbound"
                ],
                "domain":[
                    "geosite:wikimedia"
                ],
                "port":"443",
                "outboundTag":"redirect",
                "type":"field"
            },
            {
                "inboundTag":[
                    "socks-inbound"
                ],
                "domain":[
                    "geosite:reddit"
                ],
                "port":"443",
                "outboundTag":"redirect",
                "type":"field"
            },
            {
                "inboundTag":[
                    "socks-inbound"
                ],
                "domain":[
                    "domain:ptt.cc"
                ],
                "port":"443",
                "outboundTag":"redirect",
                "type":"field"
            },
            {
                "inboundTag":[
                    "socks-inbound"
                ],
                "domain":[
                    "geosite:vimeo"
                ],
                "port":"443",
                "outboundTag":"redirect",
                "type":"field"
            }
        ]
    },
    "dns":{
        "servers":[
            "192.168.1.1"
        ]
    }
}
```

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.

Server error log:

```javascript
    // Please attach your server error log here.
```

Client error log:

```javascript
// 不通过代理的网站
v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: failed to open connection to tcp:api.lbs.yandex.net:443 > v2ray.com/core/common/retry: [dial tcp: lookup api.lbs.yandex.net on [::1]:53: read udp [::1]:48162->[::1]:53: read: connection refused dial tcp: lookup api.lbs.yandex.net on [::1]:53: read udp [::1]:40029->[::1]:53: read: connection refused dial tcp: lookup api.lbs.yandex.net on [::1]:53: read udp [::1]:59638->[::1]:53: read: connection refused dial tcp: lookup api.lbs.yandex.net on [::1]:53: read udp [::1]:36086->[::1]:53: read: connection refused dial tcp: lookup api.lbs.yandex.net on [::1]:53: read udp [::1]:58978->[::1]:53: read: connection refused] > v2ray.com/core/common/retry: all retry attempts failed
// 通过代理的网站
v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: failed to open connection to tcp:pixiv.net:443 > v2ray.com/core/common/retry: [dial tcp: lookup pixiv.net on [::1]:53: read udp [::1]:54407->[::1]:53: read: connection refused dial tcp: lookup pixiv.net on [::1]:53: read udp [::1]:57960->[::1]:53: read: connection refused dial tcp: lookup pixiv.net on [::1]:53: read udp [::1]:55711->[::1]:53: read: connection refused dial tcp: lookup pixiv.net on [::1]:53: read udp [::1]:38252->[::1]:53: read: connection refused dial tcp: lookup pixiv.net on [::1]:53: read udp [::1]:47744->[::1]:53: read: connection refused] > v2ray.com/core/common/retry: all retry attempts failed
```

7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.

```javascript
tcp:127.0.0.1:51581 accepted tcp:api.lbs.yandex.net:443
tcp:127.0.0.1:51582 accepted tcp:pixiv.net:443
```

8) Other configurations (such as Nginx) and logs.

9) If V2Ray doesn't run, please attach output from `--test`.

The command is usually `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`, but may vary according to your scenario.

10) If V2Ray service doesn't run, please attach journal log.

Usual command is `journalctl -u v2ray`.

Please review your issue before submitting.

**Comment by Kylejustknows** [comment]
"dns":{
        "servers":[
            "192.168.1.1"
        ]
    }

我对文档的理解是，如果这里的填的是IP地址，它会指令远程服务器使用这个IP来查询（所以失败了，你的远程服务器无法访问它的192.168.1.1）

> 当使用 localhost 时，本机的 DNS 请求不受 V2Ray 控制，需要额外的配置才可以使 DNS 请求由 V2Ray 转发。

似乎唯一的特例是，如果你填写Localhost，整个DNS系统才会完全锁定在本地区域内，不使用远程服务器来做DNS查询。
所以你应该填写Localhost，然后把本机系统的DNS设置设成192.168.1.1

**Comment by rhjdvsgsgks** [comment]
@Kylejustknows 这个配置好像服务端和客户端都在本地，即使”远程服务器“请求访问192.168.1.1也是可以成功的，我直接也试过dns填localhost，可以因为系统是Android，v2ray并没有获取到系统的dns，所以请求了`[::1]:53`。
但哪怕我已经设置dns，v2ray还是尝试获取本地的dns，所以log中仍然是v2ray在向` [::1]:53:`发送dns请求

**Comment by Xyncgas** [comment]
dns fails for many reasons, maybe you just don't have an internet.. I mean generally with internet available, you can use v2ray to bypass censorship, but if your isp blocks all name resolving ( like in the XINJIANG region ) you might want to use alternative methods to make sure your computer knows what the address of your v2ray server is like by using dnscrypt to resolve all the host names for you or use remote name solving through proxy server with v2ray but then you have to put the server's dns record in for example /Windows/System32/drivers/etc/host in windows for the initial connection to your server ( or it wont work because the client needs the dns-record )

**Comment by rhjdvsgsgks** [comment]
> dns fails for many reasons, maybe you just don't have an internet.. I mean generally with internet available, you can use v2ray to bypass censorship, but if your isp blocks all name resolving ( like in the XINJIANG region ) you might want to use alternative methods to make sure your computer knows what the address of your v2ray server is like by using dnscrypt to resolve all the host names for you or use remote name solving through proxy server with v2ray but then you have to put the server's dns record in for example /Windows/System32/drivers/etc/host in windows for the initial connection to your server ( or it wont work because the client needs the dns-record )

I'm sure that the DNS which I set is really can access, i also tried set the DNS in config as local DNS server. it's still not working, not even access to the dns server.
I just want to make two points:
1. v2ray doesn't access DNS server in the config
2. v2ray can't get DNS from system on Android device
