### ISSUE TITLE
关于<关于DNS及其应用 >https://steemit.com/cn/@v2ray/dns

### ISSUE THREAD

**Issue by ntgeralt** [v2ray/v2ray-core#1762]
关于此文《关于DNS 传出代理的套餐配置如下》
{
  "port": 5353,
  "tag": "dns-in",
  "protocol": "dokodemo-door",
  "settings": {
    "address": "1.1.1.1",
    "port": 53,
    "network": "tcp,udp" // 是的，同时支持 TCP 和 UDP 流量，加了 TLS 之后还可以支持 DoT
  }
}
上面"address": "1.1.1.1",我不是很清楚其意思，假如配合dns分流该如何写。我不是非常geek的玩家，希望有一篇关于dns分流+透明代理样例。

**Comment by kxmp** [comment]
这个配置了根本是不生效的
要路由里面加规则 然后出站加规则. 
就是他里面写的所有规则 都加上才行 否则这个任意门就是个普通的dns 全局都走代理.

**Comment by ntgeralt** [comment]
我还是用回dnsmasq~
