### ISSUE TITLE
按照配置全填了，但就是没法科学/上网

### ISSUE THREAD

**Issue by moekosamaki** [v2ray/v2ray-core#1766]
提交 Issue 

- 之前请先阅读指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。)

除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
Latest version v4.19.1 is already installed.
客户端是v2rayN v2.29
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
火狐设置SOCKS 127.0.0.1 端口2333。进pixiv
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
连不上网
4) 你期待看到的正确表现是怎样的？
可以科学上网
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

{
  "inbounds": [
    {
      "port": 1500, 
      "protocol": "vmess",    
      "settings": {
        "clients": [
          {
            "id": "9【哔——】2-5c3b-4649-87a6-fea22290b1da",  
            "alterId": 233
          }
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",  
      "settings": {}
    }
  ]
}`

客户端配置:
{
  "log": {
    "access": "F:\\dw\\vtn\\Vaccess.log",
    "error": "F:\\dw\\vtn\\Verror.log",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 2333,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "45.【哔——】.190",
            "port": 1500,
            "users": [
              {
                "id": "9【哔——】2-5c3b-4649-87a6-fea22290b1da",
                "alterId": 233,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "tcp",
        "security": "",
        "tlsSettings": null,
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": null,
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "dns": null,
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": []
  }
}

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

2019/06/16 15:41:52 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/16 16:04:26 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/16 16:06:58 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/16 16:08:00 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/16 16:09:26 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/16 16:19:25 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/16 16:22:33 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/16 16:26:37 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/16 16:27:20 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/16 16:27:54 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/16 16:30:13 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/19 11:32:56 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/19 11:42:22 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/19 11:43:51 [Warning] v2ray.com/core: V2Ray 4.19.1 started

客户端错误日志:

2019/06/19 11:31:14 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/19 11:32:45 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 45.76.81.190:1500: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed
2019/06/19 11:38:02 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 45.76.81.190:1500: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed
2019/06/19 11:38:16 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 45.76.81.190:1500: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed
2019/06/19 11:46:45 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/19 11:50:46 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 45.76.81.190:1500: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed
2019/06/19 11:52:09 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 45.76.81.190:1500: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed
2019/06/19 11:53:56 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/19 11:56:52 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/19 12:04:51 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/19 12:05:04 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/19 12:20:40 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/19 12:29:01 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/19 12:29:41 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/19 12:29:55 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/19 14:02:06 [Warning] v2ray.com/core: V2Ray 4.19.1 started

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

此文件为空白

8) 其它相关的配置文件（如 Nginx）和相关日志。
v2rayN填的配置是：
45.【哔——】.190
端口 1500
id 9【哔——】-5c3b-4649-87a6-fea22290b1da
额外id 233
加密方式 auto
协议tcp
别名 233v2.com_45.【哔——】.190
参数设置 本地监听端口 2333
9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

[root@vultr ~]# /usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json
V2Ray 4.19.1 (Let's Fly) Custom
A unified platform for anti-censorship.
Configuration OK.

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

[root@vultr ~]# journalctl -u v2ray
-- Logs begin at Mon 2019-06-17 08:28:17 JST, end at Wed 2019-06-19 14:45:55 JST. --
Jun 19 11:32:56 vultr.guest systemd[1]: Stopping V2Ray Service...
Jun 19 11:32:56 vultr.guest systemd[1]: Stopped V2Ray Service.
Jun 19 11:32:56 vultr.guest systemd[1]: Started V2Ray Service.
Jun 19 11:32:56 vultr.guest v2ray[27344]: V2Ray 4.19.1 (Let's Fly) Custom
Jun 19 11:32:56 vultr.guest v2ray[27344]: A unified platform for anti-censorship.
Jun 19 11:42:22 vultr.guest systemd[1]: Stopping V2Ray Service...
Jun 19 11:42:22 vultr.guest systemd[1]: Stopped V2Ray Service.
Jun 19 11:42:22 vultr.guest systemd[1]: Started V2Ray Service.
Jun 19 11:42:22 vultr.guest v2ray[27459]: V2Ray 4.19.1 (Let's Fly) Custom
Jun 19 11:42:22 vultr.guest v2ray[27459]: A unified platform for anti-censorship.
Jun 19 11:43:51 vultr.guest systemd[1]: Stopping V2Ray Service...
Jun 19 11:43:51 vultr.guest systemd[1]: Stopped V2Ray Service.
Jun 19 11:43:51 vultr.guest systemd[1]: Started V2Ray Service.
Jun 19 11:43:51 vultr.guest v2ray[27530]: V2Ray 4.19.1 (Let's Fly) Custom
Jun 19 11:43:51 vultr.guest v2ray[27530]: A unified platform for anti-censorship.

请预览一下你填的内容再提交。

**Comment by moekosamaki** [comment]
在v2rayN的本地监听端口设置1080显示

fatal error：can't bind to 127.0.0.1:1081:rher may be another privoxy or some other proxy running on port 1081

**Comment by kslr** [comment]
45.76.81.190:1500: i/o timeout

顺着这个错误找，检查网络连通

**Comment by moekosamaki** [comment]
V2Ray里的ss链接也连不上，但是xshell里能登入。不太像ip被ban……

**Comment by moekosamaki** [comment]
裸网试下xh里也没法登入了，该不是真被ban了吧= =

**Comment by moekosamaki** [comment]
换了ip还是不行

**Comment by moekosamaki** [comment]
找到原因了，把系统码换成中文解决了。之前的是日文

**Comment by yefuchao** [comment]
同样的问题，请问什么是系统码？
