### ISSUE TITLE
v2ray-core 如何引用

### ISSUE THREAD

**Issue by ldlqdsdcn** [v2ray/v2ray-core#1768]
请问这个项目如何引用，或者编译？我用 go install github.com/v2ray/v2ray-core编译不了

**Comment by shynome** [comment]
应该是
```
go install github.com/v2ray/v2ray-core/main
```

**Comment by nicholascw** [comment]
https://www.v2fly.org/developer/intro/compile.html

**Comment by ldlqdsdcn** [comment]
@shynome @nicholascw ,我更换golang.org/x/net/proxy类库了。 咱们文档不够详细。做区块链开发，增加代理功能支持。还是谢谢两位了。
