### ISSUE TITLE
这几天v2ray无法登陆推特，其他正常

### ISSUE THREAD

**Issue by cupbk** [v2ray/v2ray-core#1772]
从前天开始，v2ray无法登陆推特，刷新多次只有“retry”出来，但是google搜索或者油管看视频都正常，请问这是什么原因？

**Comment by tjLEIIQM3** [comment]
可能是特朗普不想让你偷看到他的治国方略。

**Comment by kslr** [comment]
你可以用网页刷新，我觉得这和新版twitter设计应该有关系，因为我看到进去后请求都是未认证。

**Comment by cupbk** [comment]
感谢回复，v2ray已经恢复正常
