### ISSUE TITLE
time out issue

### ISSUE THREAD

**Issue by adamgonglj** [v2ray/v2ray-core#1773]
1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
均是V4.19.1

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
using v2rayN to visit google.com via Chrome, using websocket+tls(maybe)+cdn(it worked properly)

3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)

[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > 

v2ray.com/core/transport/internet/websocket: failed to dial to (wss://xxxxx/xxxxx):  > dial tcp x.x.x.x:443: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://xxxxx/xxxxx):  > write tcp 192.168.1.83:65348->x.x.x.x:443: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://xxxxx/xxxxx):  > write tcp 192.168.1.83:65384->x.x.x.x:443: i/o timeout 

2019/06/24 19:09:51 tcp:127.0.0.1:65449 accepted tcp:www.google.com:443 
2019/06/24 19:09:51 tcp:127.0.0.1:65450 accepted tcp:beacons.gcp.gvt2.com:443 
2019/06/24 19:09:51 tcp:127.0.0.1:65452 accepted tcp:beacons.gcp.gvt2.com:443 
2019/06/24 19:09:53 tcp:127.0.0.1:65454 accepted tcp:cello.client-channel.google.com:443 
2019/06/24 19:09:53 tcp:127.0.0.1:65457 accepted tcp:cello.client-channel.google.com:443 

2019/06/24 19:09:59 tcp:127.0.0.1:65463 accepted tcp:docs.google.com:443 

4) What's your expectation?
just open google properly

5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

Server configuration:

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.

Server error log:

```javascript
    // Please attach your server error log here.
```

Client error log:

```javascript
    // Please attach your client error log here.
```

7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.

```javascript
    // Please attach your server access log here.
```

8) Other configurations (such as Nginx) and logs.

9) If V2Ray doesn't run, please attach output from `--test`.

The command is usually `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`, but may vary according to your scenario.

10) If V2Ray service doesn't run, please attach journal log.

Usual command is `journalctl -u v2ray`.

Please review your issue before submitting.

**Comment by adamgonglj** [comment]
logs

2019/05/20 14:35:57 [Warning] v2ray.com/core: V2Ray 4.19 started
2019/05/20 14:36:09 [Warning] v2ray.com/core/transport/internet/websocket: failed to serve http for WebSocket > accept tcp 127.0.0.1:10303: use of closed network connection
2019/05/20 14:37:23 [Warning] v2ray.com/core: V2Ray 4.19 started
2019/05/20 15:39:57 [Warning] v2ray.com/core/transport/internet/websocket: failed to serve http for WebSocket > accept tcp 127.0.0.1:10303: use of closed network connection
2019/05/20 15:39:57 [Warning] v2ray.com/core: V2Ray 4.19 started
2019/05/22 08:02:26 [Warning] v2ray.com/core: V2Ray 4.19 started
2019/05/31 11:46:38 [Warning] v2ray.com/core: V2Ray 4.19 started
2019/05/31 20:14:33 [Warning] v2ray.com/core: V2Ray 4.19 started
2019/05/31 20:15:26 [Warning] v2ray.com/core/transport/internet/websocket: failed to serve http for WebSocket > accept tcp 127.0.0.1:10303: use of closed network connection
2019/05/31 20:15:26 [Warning] v2ray.com/core: V2Ray 4.19 started
2019/06/02 06:29:21 [Warning] v2ray.com/core: V2Ray 4.19 started
2019/06/11 08:50:21 [Warning] v2ray.com/core: V2Ray 4.19 started
2019/06/11 08:51:30 [Warning] v2ray.com/core/transport/internet/websocket: failed to serve http for WebSocket > accept tcp 127.0.0.1:10303: use of closed network connection
2019/06/11 08:51:30 [Warning] v2ray.com/core: V2Ray 4.19 started
2019/06/11 22:05:51 [Warning] v2ray.com/core: V2Ray 4.19 started
2019/06/12 11:08:35 [Warning] v2ray.com/core: V2Ray 4.19 started
2019/06/13 09:36:39 [Warning] v2ray.com/core: V2Ray 4.19 started
2019/06/24 18:41:20 [Warning] v2ray.com/core: V2Ray 4.19 started
2019/06/24 18:49:37 [Warning] v2ray.com/core/transport/internet/websocket: failed to serve http for WebSocket > accept tcp 127.0.0.1:10303: use of closed network connection
2019/06/24 18:49:38 [Warning] v2ray.com/core: V2Ray 4.19 started
2019/06/24 18:50:45 [Warning] v2ray.com/core/transport/internet/websocket: failed to serve http for WebSocket > accept tcp 127.0.0.1:10303: use of closed network connection
2019/06/24 18:50:45 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/24 18:53:00 [Warning] v2ray.com/core/transport/internet/websocket: failed to serve http for WebSocket > accept tcp 127.0.0.1:10303: use of closed network connection
2019/06/24 18:53:00 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/06/24 19:00:53 [Warning] v2ray.com/core/transport/internet/websocket: failed to serve http for WebSocket > accept tcp 127.0.0.1:10303: use of closed network connection

**Comment by adamgonglj** [comment]
I downgrade the core from v4.19.1 to v4.18, then the problem solved.

**Comment by yd-yin** [comment]
I met the same problem. Client log seems good but everything just remains the same before I download v2ray.
Did you downgrade only the client or both client and server? How to downgrade server?

**Comment by adamgonglj** [comment]
maybe your configuration files are not right.

Yin Yingda <notifications@github.com> 于2019年7月5日周五 下午10:19写道：

**Comment by gonnalee** [comment]
use this command :`Journalctl -u v2ray`.
you will get the helpful logs

**Comment by Xyncgas** [comment]
sync your system time with v2ray server's time, and you can also auto calibrate time on linux servers with a selection of ways, because the thing sometimes is that ( not neccesarily applies to you ) virtual machine sold by the providers varies a lot and sometimes with trash vps the clock is not gonna be right or off by a bit every now and then, so calibration is to make sure the time is right, and also make sure your time on the local computer is within 90 seconds of the server's system time ( the time-zone deosnt matter ), it is one of the implementations to prevent attacks from PRC's hacking farms

**Comment by mehdifirefox** [comment]
> time
I change the computer's time. The rest of the programs are disabled

How did you solve this problem?
I change the time of Windows
My apps don't work like a browser

**Comment by mehdifirefox** [comment]
> زمان سیستم خود را با زمان سرور v2ray همگام‌سازی کنید، و همچنین می‌توانید با روش‌های مختلفی زمان را روی سرورهای لینوکس کالیبره کنید، زیرا گاهی اوقات مشکل این است که (الزاماً برای شما صدق نمی‌کند) ماشین مجازی فروخته شده توسط ارائه‌دهندگان بسیار متفاوت است و گاهی اوقات با trash vps ساعت هر از چند گاهی درست یا خاموش نمی شود، بنابراین کالیبراسیون برای اطمینان از مناسب بودن زمان است و همچنین مطمئن شوید که زمان شما در رایانه محلی در 90 ثانیه از زمان سیستم سرور باشد ( the time-zone deosnt matter)، یکی از پیاده سازی ها برای جلوگیری از حملات مزارع هک PRC است.

I change the computer's time. The rest of the programs are disabled
How did you solve this problem?
I change the time of Windows
My apps don't work like a browser

**Comment by Xyncgas** [comment]
Apparently the time between the server & computer should be syncrhonized
it doesn't matter what time zone you set the operating system to be just make sure the minute is accurate
for example : https://time.is/

**Comment by sinaasadiyan** [comment]
Same here, just enabled the "set time automatically" in windows 10 and V2ray started working!

**Comment by ThusharaX** [comment]
I encountered a similar problem with v2ray on Windows 11. Upon discovering this GitHub issue, I clicked the "Sync now" button, and voilà, V2ray started working!

![image](https://github.com/v2ray/v2ray-core/assets/47711719/d343af53-821d-41d0-86c6-c5e37cd2b829)
