### ISSUE TITLE
win10客户端，v2ray偶尔能够正常工作。

### ISSUE THREAD

**Issue by richace** [v2ray/v2ray-core#1777]
1.  v2ray[542]: V2Ray 4.19.1 (Let's Fly) Custom 
 配置成功Vmess- (35***42:2048)
启动服务(2019/6/27 10:19:56)......
V2Ray 4.19.1 (Let's Fly) Custom
A unified platform for anti-censorship.    服务器和客户端版本一致。
win10版本： Microsoft Windows [版本 10.0.17763.475]

2.使用Chrome代理到V2ray本地端口上外网（Google、gmail等不能访问）
3. 无法加载Google等网页
4.---网页正确加载
5.客户端和服务端都是下载时的默认配置，除了ip和uuid没有其他修改。
6. 服务端:2019/06/27 10:03:18 [Warning] v2ray.com/core/transport/internet/websocket: failed to serve http for WebSocket > accept tcp [::]:2048: use of closed network connection
。
客户端：
--------------------------------由于线程退出或应用程序请求，已中止 I/O 操作。[09:10:24]--------------------------------
System.Net.HttpListenerException (0x80004005): 由于线程退出或应用程序请求，已中止 I/O 操作。
   在 System.Net.HttpListener.GetContext()
   在 v2rayN.HttpProxyHandler.HttpWebServer.<Run>b__4_0(Object o)

7. 相同的配置  拷贝到 win7 机器上一切正常。  非常正常。  应该是win10 的问题。

**Comment by kslr** [comment]
请到客户端报告问题。

richace <notifications@github.com> 于 2019年6月27日周四 11:24写道：
