### ISSUE TITLE
b站直播再次出现卡小电视的现象

### ISSUE THREAD

**Issue by liaobin** [v2ray/v2ray-core#178]
以http://live.bilibili.com/3 为例
另外此时客户端显示
2016/06/20 23:02:39 [Warning]Freedom: Failed to open connection to tcp:mtalk.google.com:5228: All retry attempts failed.

不知道是不是有关系

**Comment by v2ray** [comment]
没关系。

你所处的位置在哪？国内？

**Comment by liaobin** [comment]
是的,国内

**Comment by kathylincn** [comment]
这站点服务器不是在国内吗??和V2RAY有什么关系

**Comment by liaobin** [comment]
@kathylincn b站的某些域名没设置成直连,现在用cow配合v2ray,个人觉得效果比自带的路由表舒服

**Comment by v2ray** [comment]
有兴趣的话可以把相关域名提交到这个文件：https://github.com/v2ray/v2ray-core/blob/master/tools/conf/router_chinasites.go

issue 先关了。
