### ISSUE TITLE
How to use v2ray + ipv6 to get access to netflix

### ISSUE THREAD

**Issue by saucebing** [v2ray/v2ray-core#1780]
To bypass the great firewall of China, I use v2ray + tls + ws in my VPS. And then I also want to use netflix. I found that someone can use IPV6 to cheat netflix, so I used Hurricane Electric to create an IPV6 tunnel and I successfully got an IPV6 address and it was also shown in my client when visiting ipv6-test.com. But I could not still watch netflix, do I need to modify some more configuration in v2ray?

**Comment by fedoranhowl** [comment]
try "sendThrough": "", not sure

**Comment by saucebing** [comment]
Thank you, I will try and give the feedback.

**Comment by hyt589** [comment]
@saucebing Did you make it work?

**Comment by saucebing** [comment]
I have used "sendThrough" and I have tried to reject the response from netflix on either ipv4 or ipv6 in iptables following some tricks online, but all of them failed. Does anyone have any idea?

**Comment by fedoranhowl** [comment]
:(

**Comment by saucebing** [comment]
I saw some VPNs, such as ExpressVPN and NordVPN, could bypass netflix limit. And I also saw Shadowsocks configuration could bypass netflix limit online. What magic do they use? If we can give a solution, it will be wonderful.

**Comment by fedoranhowl** [comment]
Pali Tech Society: V2Ray Server, IPv6 Input, IPv4 Output

https://palitechsociety.blogspot.com/2019/07/v2ray-server-ipv6-input-ipv4-output.html?m=1

**Comment by cnbeining** [comment]
@saucebing 

You are digging into a wrong approach as TunnelBroker was blocked by NF ~3 years ago: 

https://www.reddit.com/r/NetflixByProxy/comments/4mhlzd/netflix_is_now_starting_to_block_hurricane/

I shall make no comments on ExpressVPN and NordVPN.
