### ISSUE TITLE
请问v2ray的http inbound 不能按email统计流量使用情况吗？

### ISSUE THREAD

**Issue by FavorMylikes** [v2ray/v2ray-core#1789]
http 的入栈代理如下，虽然文档中并未显示可以在accounts中添加email项，只是作为测试放进来，在其他协议如vess下，可以实现按邮箱统计，http代理似乎无法被统计

    {
      "port": 1080,
      "protocol": "http",
      "settings": {
        "timeout": 0,
        "allowTransparent": false,
        "userLevel": 0,
        "accounts": [
          {
            "email":"username@mail.com",
            "user": "username@mail.com",
            "pass": "password"
          }
        ]
      },
      "tag": "httpin"
    }

**Comment by vcptr** [comment]
只有vmess协议内的user会被统计。
