### ISSUE TITLE
Digitalocean Floating IP

### ISSUE THREAD

**Issue by LiYao703198594** [v2ray/v2ray-core#1791]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
4.19.1
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
Chrome通过Socks代理浏览网页
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
Digitalocean的vps，Ubuntu 16.04 64位系统，刚装完系统，十分干净，有一个正常的ipv4地址与ipv6地址以及浮动ipv4地址，通过ipv6与原来的ipv4地址都可以正常使用v2ray和ssh登陆，但在浮动ip上只能ssh登陆，不能使用v2ray。（如果需要，我可以提供提供地址账号密码）
4) 你期待看到的正确表现是怎样的？
能使用浮动ip运行v2ray服务（这样就不担心ip被封了）
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```
{
"log": {
		"access": "/var/log/v2ray/access.log",
		"error": "/var/log/v2ray/error.log",
		"loglevel": "warning"
	},
	"inbounds": [
		{
			"port": 23333,
			"protocol": "vmess",
			"settings": {
				"clients": [
					{
						"id": "ecc9f251-f70d-cdd3-4225-9714a3827ae7",
						"level": 1,
						"alterId": 233
					}
				],
				"detour": {
					"to": "dynamic"
				}
			},
			"streamSettings": {
                "network": "kcp",
                "kcpSettings": {
                    "header": {
                        "type": "utp"
                    }
                }
			},
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			}
		},
		{
            "port": 23344,
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "ecc9f251-f70d-cdd3-4225-9714a3827ae7",
                        "level": 1,
                        "alterId": 233
                    }
                ],
                "detour": {
                    "to": "dynamic"
                }
            },
            "streamSettings": {
                "network": "kcp",
                "kcpSettings": {
                    "header": {
                        "type": "utp"
                    }
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            }
        },
        {
            "protocol": "vmess",
            "port": "10000-20000",
            "tag": "dynamic",
            "settings": {
                "default": {
                    "level": 1,
                    "alterId": 32
                }
            },
            "allocate": {
                "strategy": "random",
                "concurrency": 2,
                "refresh": 5
            },
            "streamSettings": {
                "network": "kcp",
                "kcpSettings": {
                    "header": {
                        "type": "utp"
                    }
                }
            }
        }
		//include_ss
		//include_socks
		,
        {
            "protocol": "mtproto",
            "port": 2233,
            "tag": "tg-in",
            "settings": {
                "users": [
                    {
                        "secret": "ecc9f251-f70d-cdd3-4225-9714a3827ae7"
                    }
                ]
            }
        }
		//include_in_config
		//
	],
	"outbounds": [
		{
			"protocol": "freedom",
			"settings": {}
		},
		{
			"protocol": "blackhole",
			"settings": {},
			"tag": "blocked"
		},
		{
			"protocol": "freedom",
			"settings": {},
			"tag": "direct"
		},
		{
			"protocol": "mtproto",
			"settings": {},
			"tag": "tg-out"
		}
		//include_out_config
		//
	],
	"dns": {
		"server": [
			"2001:4860:4860::8888",
			"2001:4860:4860::8844",
			"8.8.8.8",
			"8.8.4.4",
			"localhost"
		]
	},
	"routing": {
		"domainStrategy": "IPOnDemand",
		"rules": [
			{
				"type": "field",
				"ip": [
					"0.0.0.0/8",
					"10.0.0.0/8",
					"100.64.0.0/10",
					"127.0.0.0/8",
					"169.254.0.0/16",
					"172.16.0.0/12",
					"192.0.0.0/24",
					"192.0.2.0/24",
					"192.168.0.0/16",
					"198.18.0.0/15",
					"198.51.100.0/24",
					"203.0.113.0/24",
					"::1/128",
					"fc00::/7",
					"fe80::/10"
				],
				"outboundTag": "blocked"
			},
			{
				"type": "field",
				"inboundTag": ["tg-in"],
				"outboundTag": "tg-out"
			}
			,
		{
                    "type": "field",
                    "protocol": [
                        "bittorrent"
                    ],
                    "outboundTag": "blocked"
                }
			//include_ban_ad
			//include_rules
			//
		]
	},
	"transport": {
		"kcpSettings": {
            "uplinkCapacity": 100,
            "downlinkCapacity": 100,
            "congestion": true
        },
		"sockopt": {
			"tcpFastOpen": true
		}
	}
}
 // 在这里附上服务器端配置文件
```

客户端配置:

```
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 1080,
      "listen": "0.0.0.0",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "2001:4860:4860::8888",
            "port": 23333,
            "users": [
              {
                "id": "ecc9f251-f70d-cdd3-4225-9714a3827ae7",
                "alterId": 233,
                "email": "t@t.tt",
                "security": "aes-128-gcm"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "kcp",
        "security": "",
        "tlsSettings": null,
        "tcpSettings": null,
        "kcpSettings": {
          "mtu": 1350,
          "tti": 50,
          "uplinkCapacity": 12,
          "downlinkCapacity": 100,
          "congestion": false,
          "readBufferSize": 2,
          "writeBufferSize": 2,
          "header": {
            "type": "utp",
            "request": null,
            "response": null
          }
        },
        "wsSettings": null,
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "dns": {
    "servers": [
      "2001:4860:4860::8888",
      "2001:4860:4860::8844",
      "8.8.8.8",
      "8.8.4.4",
      "114.114.114.114"
    ]
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": []
  }
} // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
2019/07/04 08:23:32 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/07/04 08:28:26 [Warning] [3381195850] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.
2019/07/04 09:13:40 [Warning] [3289298748] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.
2019/07/04 09:22:59 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/07/04 09:25:33 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/07/04 09:43:18 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/07/04 09:56:50 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/07/04 10:04:05 [Warning] v2ray.com/core: V2Ray 4.19.1 started
2019/07/04 10:04:05 [Warning] [3468750183] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.
2019/07/04 10:40:49 [Warning] [4275697501] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.
2019/07/04 10:40:49 [Warning] [1722829134] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.
2019/07/04 10:41:25 [Warning] [3858245032] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.
2019/07/04 10:41:25 [Warning] [867831423] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.
// 在这里附上服务器端日志
```

客户端错误日志:

```javascript
（这个没有）
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
2019/07/04 10:30:13 udp:[2400:6180::a]:60763 accepted tcp:live.github.com:443 
2019/07/04 10:30:13 udp:[2400:6180::a]:60763 accepted tcp:live.github.com:443 
2019/07/04 10:30:13 udp:[2400:6180::a]:60763 accepted tcp:live.github.com:443 
2019/07/04 10:30:18 udp:[2400:6180::a]:60763 accepted tcp:cloud.digitalocean.com:443 
2019/07/04 10:30:20 udp:[2400:6180::a]:60763 accepted tcp:push.digitalocean.com:443 
2019/07/04 10:30:50 udp:[2400:6180::a]:60763 accepted tcp:steamcommunity.com:443 
2019/07/04 10:31:03 udp:[2400:6180::a]:60763 accepted tcp:download.game.yy.com:80 
2019/07/04 10:31:03 udp:[2400:6180::a]:60763 accepted tcp:yeconfig.game.yy.com:80 
2019/07/04 10:31:07 udp:[2400:6180::a]:60763 accepted tcp:ylog.hiido.com:80 
2019/07/04 10:31:18 udp:[2400:6180::a]:60763 accepted tcp:bam.nr-data.net:443 
2019/07/04 10:31:18 udp:[2400:6180::a]:60763 accepted tcp:crl.pki.goog:80 
2019/07/04 10:31:19 udp:[2400:6180::a]:60763 accepted tcp:activity.windows.com:443 
2019/07/04 10:31:44 udp:[2400:6180::a]:56161 accepted tcp:live.github.com:443 
2019/07/04 10:31:44 udp:[2400:6180::a]:56161 accepted tcp:live.github.com:443 
2019/07/04 10:31:44 udp:[2400:6180::a]:56161 accepted tcp:live.github.com:443 
2019/07/04 10:31:44 udp:[2400:6180::a]:56161 accepted tcp:activity.windows.com:443 
2019/07/04 10:31:49 udp:[2400:6180::a]:56161 accepted tcp:cloud.digitalocean.com:443 
2019/07/04 10:31:53 udp:[2400:6180::a]:56161 accepted tcp:push.digitalocean.com:443 
2019/07/04 10:32:19 udp:[2400:6180::a]:56161 accepted tcp:bam.nr-data.net:443 
2019/07/04 10:32:29 udp:[2400:6180::a]:56161 accepted tcp:clients4.google.com:443 
2019/07/04 10:34:50 udp:[2400:6180::a]:56161 accepted tcp:steamcommunity.com:443 
2019/07/04 10:38:22 udp:[2400:6180::a]:56161 accepted tcp:activity.windows.com:443 
2019/07/04 10:40:02 udp:117.188.129.219:6228 accepted tcp:live.github.com:443 
2019/07/04 10:40:02 udp:117.188.129.219:6228 accepted tcp:live.github.com:443 
2019/07/04 10:40:03 udp:117.188.129.219:6228 accepted tcp:live.github.com:443 
2019/07/04 10:40:08 udp:117.188.129.219:6228 accepted tcp:cloud.digitalocean.com:443 
2019/07/04 10:40:09 udp:117.188.129.219:6230 accepted tcp:avatar.csdn.net:443 
2019/07/04 10:40:09 udp:117.188.129.219:6231 accepted tcp:gh.bdstatic.com:443 
2019/07/04 10:40:09 udp:117.188.129.219:6228 accepted tcp:blog.csdn.net:443 
2019/07/04 10:40:09 udp:117.188.129.219:6228 accepted tcp:blog.csdn.net:443 
2019/07/04 10:40:09 udp:117.188.129.219:6228 accepted tcp:csdnimg.cn:443 
2019/07/04 10:40:09 udp:117.188.129.219:6228 accepted tcp:nbrecsys.4paradigm.com:443 
2019/07/04 10:40:09 udp:117.188.129.219:6230 accepted tcp:gsp0.baidu.com:443 
2019/07/04 10:40:09 udp:117.188.129.219:6230 accepted tcp:entry.baidu.com:443 
2019/07/04 10:40:09 udp:117.188.129.219:6230 accepted tcp:g.csdnimg.cn:443 
2019/07/04 10:40:09 udp:117.188.129.219:6230 accepted tcp:static.mediav.com:443 
2019/07/04 10:40:09 udp:117.188.129.219:6230 accepted tcp:cpro.baidustatic.com:443 
2019/07/04 10:40:09 udp:117.188.129.219:6230 accepted tcp:pagead2.googlesyndication.com:443 
2019/07/04 10:40:09 udp:117.188.129.219:6230 accepted tcp:hm.baidu.com:443 
2019/07/04 10:40:09 udp:117.188.129.219:6231 accepted tcp:www.nkscdn.com:443 
2019/07/04 10:40:10 udp:117.188.129.219:6231 accepted tcp:live.github.com:443 
2019/07/04 10:40:10 udp:117.188.129.219:6231 accepted tcp:live.github.com:443 
2019/07/04 10:40:20 udp:117.188.129.219:6231 accepted tcp:live.github.com:443 
2019/07/04 10:40:20 udp:117.188.129.219:6231 accepted tcp:live.github.com:443 
2019/07/04 10:40:33 udp:117.188.129.219:6233 accepted tcp:nbrecsys.4paradigm.com:443 
2019/07/04 10:40:33 udp:117.188.129.219:6233 accepted tcp:csdnimg.cn:443 
2019/07/04 10:40:33 udp:117.188.129.219:6231 accepted tcp:blog.csdn.net:443 
2019/07/04 10:40:33 udp:117.188.129.219:6231 accepted tcp:blog.csdn.net:443 
2019/07/04 10:40:34 udp:117.188.129.219:6233 accepted tcp:live.github.com:443 
2019/07/04 10:40:34 udp:117.188.129.219:6233 accepted tcp:live.github.com:443 
2019/07/04 10:40:40 udp:117.188.129.219:6233 accepted tcp:cloud.digitalocean.com:443 
2019/07/04 10:40:41 udp:117.188.129.219:6233 accepted tcp:blog.csdn.net:443 
2019/07/04 10:40:44 udp:117.188.129.219:6233 accepted tcp:clients4.google.com:443 
2019/07/04 10:40:45 udp:117.188.129.219:6235 accepted tcp:avatar.csdn.net:443 
2019/07/04 10:40:45 udp:117.188.129.219:6236 accepted tcp:gh.bdstatic.com:443 
2019/07/04 10:40:45 udp:117.188.129.219:6236 accepted tcp:www.nkscdn.com:443 
2019/07/04 10:40:45 udp:117.188.129.219:6233 accepted tcp:blog.csdn.net:443 
2019/07/04 10:40:45 udp:117.188.129.219:6235 accepted tcp:gsp0.baidu.com:443 
2019/07/04 10:40:45 udp:117.188.129.219:6235 accepted tcp:entry.baidu.com:443 
2019/07/04 10:40:45 udp:117.188.129.219:6235 accepted tcp:g.csdnimg.cn:443 
2019/07/04 10:40:45 udp:117.188.129.219:6235 accepted tcp:static.mediav.com:443 
2019/07/04 10:40:45 udp:117.188.129.219:6235 accepted tcp:cpro.baidustatic.com:443 
2019/07/04 10:40:45 udp:117.188.129.219:6235 accepted tcp:pagead2.googlesyndication.com:443 
2019/07/04 10:40:45 udp:117.188.129.219:6235 accepted tcp:hm.baidu.com:443 
2019/07/04 10:40:50 udp:117.188.129.219:6236 accepted tcp:steamcommunity.com:443 
2019/07/04 10:40:56 udp:117.188.129.219:6236 accepted tcp:live.github.com:443 
2019/07/04 10:40:56 udp:117.188.129.219:6236 accepted tcp:live.github.com:443 
2019/07/04 10:41:05 udp:117.188.129.219:6236 accepted tcp:blog.csdn.net:443 
2019/07/04 10:41:10 udp:117.188.129.219:6236 accepted tcp:cloud.digitalocean.com:443 
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。
在通过代理测试下载时使用netstat -apn | grep v2ray命令
tcp   3299128      0 128.199删除:36490   103.6.148.98:8080       ESTABLISHED 4242/v2ray      
tcp   1891340      0 128.199删除:36496   103.6.148.98:8080       ESTABLISHED 4242/v2ray      
tcp   3279012      0 128.199删除:36492   103.6.148.98:8080       ESTABLISHED 4242/v2ray      
tcp   2586904      0 128.199删除:36494   103.6.148.98:8080       ESTABLISHED 4242/v2ray      
tcp   3707712      0 128.199删除:36486   103.6.148.98:8080       ESTABLISHED 4242/v2ray      
tcp   3733028      0 128.199删除:36488   103.6.148.98:8080       ESTABLISHED 4242/v2ray      
tcp6       0      0 :::2233                 :::*                    LISTEN      4242/v2ray      
tcp6       0      0 2400:6180::a:46844 2404:6800:4003:802::443 ESTABLISHED 4242/v2ray      
tcp6       0      0 2400:6180::a:59810 2404:6800:4003:c00::443 ESTABLISHED 4242/v2ray      
tcp6       0      0 2400:6180::a:41536 2a04:4e42::731:443      ESTABLISHED 4242/v2ray      
tcp6       0      0 2400:6180::a:42384 2404:6800:4003:c04::443 ESTABLISHED 4242/v2ray      
udp6       0      0 :::10667                :::*                                4242/v2ray      
udp6       0      0 :::10310                :::*                                4242/v2ray      
udp6       0      0 :::17672                :::*                                4242/v2ray      
udp6       0      0 :::23333                :::*                                4242/v2ray      
udp6       0      0 :::23344                :::*                                4242/v2ray      
udp6       0      0 :::15163                :::*                                4242/v2ray      

客户端使用了v2rayng
配置
{
  "inbound": [
    {
      "localPort": 1080,
      "protocol": "socks",
      "udpEnabled": true,
      "sniffingEnabled": true
    }
  ],
  "logEnabled": false,
  "loglevel": "warning",
  "index": 1,
  "vmess": [
    {
      "configVersion": 2,
      "address": "2001:4860:4860::8888",
      "port": 23333,
      "id": "97466199-778a-46dd-abeb-8fab5270effb",
      "alterId": 233,
      "security": "aes-128-gcm",
      "network": "kcp",
      "remarks": "v2ray6.com_142.93.80.131",
      "headerType": "utp",
      "requestHost": "",
      "path": "",
      "streamSecurity": "",
      "allowInsecure": "",
      "configType": 1,
      "testResult": "",
      "subid": ""
    }
  ],
  "muxEnabled": true,
  "domainStrategy": "IPIfNonMatch",
  "routingMode": "0",
  "useragent": [],
  "userdirect": [],
  "userblock": [],
  "kcpItem": {
    "mtu": 1350,
    "tti": 50,
    "uplinkCapacity": 12,
    "downlinkCapacity": 100,
    "congestion": false,
    "readBufferSize": 2,
    "writeBufferSize": 2
  },
  "sysAgentEnabled": true,
  "listenerType": 3,
  "urlGFWList": "",
  "allowLANConn": true,
  "remoteDNS": "2001:4860:4860::8888,2001:4860:4860::8844,8.8.8.8,8.8.4.4,114.114.114.114",
  "subItem": null,
  "uiItem": {
    "mainQRCodeWidth": 600
  }
}

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。
V2Ray 4.19.1 (Let's Fly) Custom
A unified platform for anti-censorship.
Configuration OK.

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。
Jul 04 08:06:59 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: Started V2Ray Service.
Jul 04 08:06:59 ubuntu-s-1vcpu-1gb-sgp1-01 v2ray[2482]: V2Ray 4.19.1 (Let's Fly) Custom
Jul 04 08:06:59 ubuntu-s-1vcpu-1gb-sgp1-01 v2ray[2482]: A unified platform for anti-censorship.
Jul 04 08:06:59 ubuntu-s-1vcpu-1gb-sgp1-01 v2ray[2482]: main: failed to read config file: /etc/v2ray/config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to e
Jul 04 08:06:59 ubuntu-s-1vcpu-1gb-sgp1-01 v2ray[2482]:  > exit status 255
Jul 04 08:06:59 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: v2ray.service: Main process exited, code=exited, status=23/n/a
Jul 04 08:06:59 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: v2ray.service: Unit entered failed state.
Jul 04 08:06:59 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Jul 04 08:07:40 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: Stopped V2Ray Service.
Jul 04 08:07:40 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: Started V2Ray Service.
Jul 04 08:07:40 ubuntu-s-1vcpu-1gb-sgp1-01 v2ray[2521]: V2Ray 4.19.1 (Let's Fly) Custom
Jul 04 08:07:40 ubuntu-s-1vcpu-1gb-sgp1-01 v2ray[2521]: A unified platform for anti-censorship.
Jul 04 08:07:40 ubuntu-s-1vcpu-1gb-sgp1-01 v2ray[2521]: main: failed to read config file: /etc/v2ray/config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to e
Jul 04 08:07:40 ubuntu-s-1vcpu-1gb-sgp1-01 v2ray[2521]:  > exit status 255
Jul 04 08:07:40 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: v2ray.service: Main process exited, code=exited, status=23/n/a
Jul 04 08:07:40 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: v2ray.service: Unit entered failed state.
Jul 04 08:07:40 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Jul 04 08:08:44 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: Stopped V2Ray Service.
Jul 04 08:08:44 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: Started V2Ray Service.
Jul 04 08:08:44 ubuntu-s-1vcpu-1gb-sgp1-01 v2ray[2565]: V2Ray 4.19.1 (Let's Fly) Custom
Jul 04 08:08:44 ubuntu-s-1vcpu-1gb-sgp1-01 v2ray[2565]: A unified platform for anti-censorship.
Jul 04 08:08:44 ubuntu-s-1vcpu-1gb-sgp1-01 v2ray[2565]: main: failed to read config file: /etc/v2ray/config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to e
Jul 04 08:08:44 ubuntu-s-1vcpu-1gb-sgp1-01 v2ray[2565]:  > exit status 255
Jul 04 08:08:44 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: v2ray.service: Main process exited, code=exited, status=23/n/a
Jul 04 08:08:44 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: v2ray.service: Unit entered failed state.
Jul 04 08:08:44 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Jul 04 08:13:48 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: Stopped V2Ray Service.
Jul 04 08:13:48 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: Started V2Ray Service.
Jul 04 08:13:48 ubuntu-s-1vcpu-1gb-sgp1-01 v2ray[2611]: V2Ray 4.19.1 (Let's Fly) Custom
Jul 04 08:13:48 ubuntu-s-1vcpu-1gb-sgp1-01 v2ray[2611]: A unified platform for anti-censorship.
Jul 04 08:13:48 ubuntu-s-1vcpu-1gb-sgp1-01 v2ray[2611]: main: failed to load config: /etc/v2ray/config.json > v2ray.com/core/main/confloader/external: config file not readable > open /etc/v2ray/config.json: no such file or directory
Jul 04 08:13:48 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: v2ray.service: Main process exited, code=exited, status=23/n/a
Jul 04 08:13:48 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: v2ray.service: Unit entered failed state.
Jul 04 08:13:48 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Jul 04 08:14:15 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: Stopped V2Ray Service.
Jul 04 08:15:10 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: Started V2Ray Service.
Jul 04 08:15:10 ubuntu-s-1vcpu-1gb-sgp1-01 v2ray[2757]: V2Ray 4.19.1 (Let's Fly) Custom
Jul 04 08:15:10 ubuntu-s-1vcpu-1gb-sgp1-01 v2ray[2757]: A unified platform for anti-censorship.
Jul 04 08:15:10 ubuntu-s-1vcpu-1gb-sgp1-01 v2ray[2757]: 2019/07/04 08:15:10 [Warning] v2ray.com/core: V2Ray 4.19.1 started
Jul 04 08:17:24 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: Stopping V2Ray Service...
Jul 04 08:17:24 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: Stopped V2Ray Service.
Jul 04 08:17:24 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: Started V2Ray Service.
Jul 04 08:17:24 ubuntu-s-1vcpu-1gb-sgp1-01 v2ray[2819]: V2Ray 4.19.1 (Let's Fly) Custom
Jul 04 08:17:24 ubuntu-s-1vcpu-1gb-sgp1-01 v2ray[2819]: A unified platform for anti-censorship.
Jul 04 08:17:24 ubuntu-s-1vcpu-1gb-sgp1-01 v2ray[2819]: main: failed to read config file: /etc/v2ray/config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to e
Jul 04 08:17:24 ubuntu-s-1vcpu-1gb-sgp1-01 v2ray[2819]:  > exit status 255
Jul 04 08:17:24 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: v2ray.service: Main process exited, code=exited, status=23/n/a
Jul 04 08:17:24 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: v2ray.service: Unit entered failed state.
Jul 04 08:17:24 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Jul 04 08:18:01 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: Stopped V2Ray Service.
Jul 04 08:20:25 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: Started V2Ray Service.
Jul 04 08:20:25 ubuntu-s-1vcpu-1gb-sgp1-01 v2ray[2915]: V2Ray 4.19.1 (Let's Fly) Custom
Jul 04 08:20:25 ubuntu-s-1vcpu-1gb-sgp1-01 v2ray[2915]: A unified platform for anti-censorship.
Jul 04 08:20:25 ubuntu-s-1vcpu-1gb-sgp1-01 v2ray[2915]: main: failed to create server > v2ray.com/core/app/router: this rule has no effective fields
Jul 04 08:20:25 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: v2ray.service: Main process exited, code=exited, status=23/n/a
Jul 04 08:20:25 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: v2ray.service: Unit entered failed state.
Jul 04 08:20:25 ubuntu-s-1vcpu-1gb-sgp1-01 systemd[1]: v2ray.service: Failed with result 'exit-code'.
（这应该是我先前修改config.json出错是的记录，现在已经撤销更改了）
请预览一下你填的内容再提交。

**Comment by LiYao703198594** [comment]
我在通过ipv4代理下载时使用netstat -apn | grep v2ray命令
tcp   3827680      0 128.199删除:36490   103.6.148.98:8080       ESTABLISHED 4242/v2ray      
tcp   2863748      0 128.199删除:36496   103.6.148.98:8080       ESTABLISHED 4242/v2ray      
tcp   3353504      0 128.199删除:36492   103.6.148.98:8080       ESTABLISHED 4242/v2ray      
tcp   1871568      0 128.199删除:36494   103.6.148.98:8080       ESTABLISHED 4242/v2ray      
tcp   3467680      0 128.199删除:36486   103.6.148.98:8080       ESTABLISHED 4242/v2ray      
tcp        0      0 128.199.130删除:31326   104.85.197.14:443       ESTABLISHED 4242/v2ray      
tcp   3185576      0 128.199删除:36488   103.6.148.98:8080       ESTABLISHED 4242/v2ray      
tcp6       0      0 :::2233                 :::*                    LISTEN      4242/v2ray      
tcp6       0      0 2400:6180a:46844 2404:6800:4003:802::443 ESTABLISHED 4242/v2ray      
tcp6       0      0 2400:6180::a:59810 2404:6800:4003:c00::443 ESTABLISHED 4242/v2ray      
tcp6       0      0 2400:6180::a:41536 2a04:4e42::731:443      ESTABLISHED 4242/v2ray      
tcp6       0      0 2400:6180::a:42384 2404:6800:4003:c04::443 ESTABLISHED 4242/v2ray      
udp6       0      0 :::10667                :::*                                4242/v2ray      
udp6       0      0 :::10310                :::*                                4242/v2ray      
udp6       0      0 :::17672                :::*                                4242/v2ray      
udp6       0      0 :::23333                :::*                                4242/v2ray      
udp6       0      0 :::23344                :::*                                4242/v2ray      
udp6       0      0 :::15163                :::*                                4242/v2ray      

v2ray默认监听（这个我没动）不应该是0.0.0.0吗？
为何监听的是128.199删除的ip。

**Comment by LiYao703198594** [comment]
是不是digitalocean的浮动ip不能接受UDP数据？？
电脑小白，不是太懂！！

**Comment by LiYao703198594** [comment]
发单与客服聊天了，浮动IP不限制udp数据！！

**Comment by fbens** [comment]
客户端的 outbounds 和 服务端的 inbounds 的 port 都是一样的，没有走 https 吗

**Comment by LiYao703198594** [comment]
我采用的是mKCP的bt伪装，这种端口可以不一样吗？？

**Comment by kslr** [comment]
用vmess测试
