### ISSUE TITLE
http代理不支持websocket，也没有给出提示

### ISSUE THREAD

**Issue by forsaken628** [v2ray/v2ray-core#1798]
你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

v4.15.1

你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

我配置了全局代理，然后根据路由指定出口，当前站点为freedom出口。

你看到的不正常的现象是什么？
What did you see?

我使用了UI vrayX，它同时配置了系统代理的http代理和sock代理，在浏览器建立连接的时候有时会使用sock代理，有时使用http代理。在用http代理建立websocket连接时，vray并没有正确处理，也没有返回错误，只是当作一个普通请求转发给了上游服务，而导致上游服务返回了一个非常令人困惑的400错误。

你期待看到的正确表现是怎样的？
What's your expectation?

或者能支持websocket代理，或者直接返回代理服务器不支持websocket

**Comment by kslr** [comment]
400 ban request
