### ISSUE TITLE
无法安全地连接到此页面

### ISSUE THREAD

**Issue by KevinLeung007** [v2ray/v2ray-core#1803]
4.20, Linux-arm
无法安全地连接到此页面, TLS全选也不行，这是怎么了？Google、Youtube同样的问题。

**Comment by KevinLeung007** [comment]
FireFox 错误提示：
建立安全连接失败

连接到 www.google.com 时发生错误。PR_END_OF_FILE_ERROR

    由于不能验证所收到的数据是否可信，无法显示您想要查看的页面。
    建议向此网站的管理员反馈这个问题。

**Comment by kslr** [comment]
Try curl

**Comment by KevinLeung007** [comment]
具体怎么操作啊

**Comment by kslr** [comment]
我觉得最简单的办法就是安装openssl-dev

**Comment by Castleeee** [comment]
我的和你一模一样，服务器端已经安装了openssl，延迟测试也没问题，但是大部分被墙的页面都卡在TLS超时。

**Comment by itshaadi** [comment]
I have a routing rule for `geoip:ir` and `geoip:private`:

```json
            {
                "type": "field",
                "ip": [
                    "geoip:ir",
                    "geoip:private"
                ],
                "outboundTag": "direct",
                "inboundTag": [
                    "socks",
                    "http"
                ]
```

here is how socks inbound looks like:
```
        {
            "port": 1080,
            "listen": "0.0.0.0",
            "protocol": "socks",
            "tag": "socks",
            "settings": {
                "udp": true
            },
            "sniffing": {
                "enabled": true,
		"destOverride": ["http", "tls"]
            }
        }
```
this piece, `"destOverride": ["http", "tls"]` is causing `PR_END_OF_FILE_ERROR` in Firefox. without it this routing rule still works. but why do I need "destOverride"?

I am using v4.21.3 on Ubuntu 19.10

**Comment by yi12357** [comment]
Turn on traffic detection in inbound protocols to use domain-based routing rules.

See https://www.v2ray.com/en/configuration/overview.html#sniffingobject

**Comment by fish-404** [comment]
I try to use v2ray client in my two computers, one can visit websites in Firefox, one can't. They use the same configuration. I'm confused.

**Comment by fish-404** [comment]
> I try to use v2ray client in my two computers, one can visit websites in Firefox, one can't. They use the same configuration. I'm confused.

My problems caused by different versions of V2ray. You may need check V2ray version for Client and Server.
