### ISSUE TITLE
VMess over WebSocket stops working after client upgrade from v3.43 to v4.20.0

### ISSUE THREAD

**Issue by S-Tsunemori** [v2ray/v2ray-core#1805]
1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

> Client: v4.20.0
> Server: used to be v3.0, tried to upgrade to v4.20.0 but problem persist.

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

> Normal proxy usage, access websites, watch YouTube videos, etc.

3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)

> First, I tried to upgrade client (windows-64bit) only. (Server: v3.0 linux-64bit)
> Result: Proxy not working, no error message given.
> Console only shows lines like "tcp:127.0.0.1:xxx accepted tcp:www.google.com:80"

> Then I tried my old client (v3.43)
> Result: works.

> After that I tried to upgrade my server using the official script, upgrade was successful.
> Server is now v4.20.0, however client v4.20.0 still doesn't work.

> Then I tried my old client (v3.43) against the new server (v4.20.0)
> Result: works.

> In the end I tried some other inbound, found that even though the WebSocket one doesn't work, normal vmess connection (I used other tunnel) still works on new version.

4) What's your expectation?

Be able to use WebSocket on new client.

5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

Server configuration:

```javascript
    // no changes made
```

Client configuration:

**OLD config (which I used across v3.0 - v3.43)**
```javascript
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "[MY-SERVER-IP]",
            "port": 443,
            "users": [
              {
                "id": "[MY-USER-ID]",
                "alterId": 64,
                "security": "aes-128-gcm"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/[MY-WS-PATH]/"
        },
        "security": "tls",
        "tlsSettings": {
          "serverName": "[MY-SERVER-DOMAIN].com",
          "allowInsecure": false
        }
      },
      "tag": "outbound-ws"
    },
```
**NEW config (created from scratch, doesn't work either)**
```javascript
    {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "[MY-SERVER-IP]",
          "port": 443,
          "users": [
            {
              "id": "[MY-USER-ID]",
              "alterId": 4,
              "security": "auto",
              "level": 0
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "tlsSettings": {
        "serverName": "[MY-SERVER-DOMAIN].com",
        "allowInsecure": false
      },
      "wsSettings": {
        "path": "/[MY-WS-PATH]/",
        "headers": {
          "Host": "[MY-SERVER-DOMAIN].com"
        }
      }
    },
    "tag": "outbound-ws"
  },
```

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.

Server error log:

```javascript
    // not enabled
```

Client error log:

```javascript
    // none
```

7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.

```javascript
    // not enabled
```

**Comment by Cwek** [comment]
Server's version must be same or larger than Client's version.

**Comment by bufbrane** [comment]
There's some differences between 3.x and 4.x so you should write a new config file for newest version. Good luck

**Comment by Xyncgas** [comment]
check config file, keep wssetings, although tbh just write a new one in 5 mins...
