### ISSUE TITLE
能否用v2ray加密tcp流量

### ISSUE THREAD

**Issue by leekunha** [v2ray/v2ray-core#1806]
我希望使用海外vps部署的openvpn，但是这会导致封IP。所有v2ray有没有可以加密tcp流量的方法？

**Comment by forever8938** [comment]
为什么不直接用v2ray

**Comment by leekunha** [comment]
> 为什么不直接用v2ray

我有自己的特殊需求

**Comment by wangyufeng0615** [comment]
https://www.v2ray.com/chapter_02/protocols/dokodemo.html

**Comment by Lightmani** [comment]
你在openvpn上开启前置代理到v2，所有流量用v2传输，就可以用ov而不用担心被ban了

**Comment by leekunha** [comment]
> 你在openvpn上开启前置代理到v2，所有流量用v2传输，就可以用ov而不用担心被ban了

好的，了解

**Comment by leekunha** [comment]
> https://www.v2ray.com/chapter_02/protocols/dokodemo.html

不是很会用啊

**Comment by Cwek** [comment]
> > https://www.v2ray.com/chapter_02/protocols/dokodemo.html
> 
> 不是很会用啊

应该就是你的ov客户端访问dokodemo的监听端口，dokodemo的目的地址端口指向你的ov服务器端口，指定dokodemo用v2的链路负载。这样ov的流量就负载在v2的流量上了。

**Comment by Xyncgas** [comment]
the more precised description for the use case of the question should be ' could you use openvpn protocol nested within v2ray protocol ( well of course you can ). but honestly asking questions like 'can xxx use v2ray to encrypt tcp connections ' is like omg first of all v2ray encryption is something that you can configure which means this is not an ' either if v2ray supports encryption ' but an ' either if you have read the documentation or tried googling it or asking people in the disccusions'.

the use case of this is pretty understandable for me, using vpn protocol does yeild additional benifit so make sure you route your vpn connections to localhost v2ray, if you don't know how to do it, then use NAT on upper stream router would be an obviously solution. Just in case yes you can route your openvpn connections to localhost v2ray and there is an endless way to do it even if in normal condition the openvpn adaptor on windows actually operates above v2ray which makes v2ray to be nested within the vpn protocol instead.

**Comment by zhfreal** [comment]
除了redirect（dokodemo？）外，还有一种思路：v2ray在客户端提供socks代理，也就是常规配置方式，在openvpn客户端侧配置使用此代理即可。
另外，友情提醒openvpn是真慢，跑流量不建议使用ov，udp或者其它协议小流量可以使用。

**Comment by nicholascw** [comment]
rtfm
