### ISSUE TITLE
使用 kcp 传输时的两个 bug

### ISSUE THREAD

**Issue by lins05** [v2ray/v2ray-core#181]
OS: OS X 10.11.4 + ubuntu 14.04 server
v2ray 版本: 最新 master 和 1.17.2 release 都试过

1. v2ray client 运行一定时间报错 "too many opened files"。这时必须重启 v2ray client 才行
2. rsync/wget  通过 v2ray 代理高速下载 (3~4MB/s) 一段时间之后(~30s) 就卡住了, 不过这时其它通过 v2ray 做代理的程序(如 chrome) 不受影响。这个可以稳定重现。
```
rsync: connection unexpectedly closed (82144211 bytes received so far) [receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [receiver=3.1.2]
rsync: connection unexpectedly closed (52 bytes received so far) [generator]
rsync error: unexplained error (code 255) at io.c(226) [generator=3.1.2]
```

**Comment by Sherman-Liu** [comment]
For the first one, please take a look into Issue #99 opened by me, and this page as well : https://github.com/shadowsocks/shadowsocks/wiki/Optimizing-Shadowsocks

It's not a KCP related bug.

**Comment by v2ray** [comment]
第一个问题是因为 KCP 连接的关闭机制目前做得还不太好，比较容易触发“too many open files”，暂时的解决方案如 @Sherman-Liu 所说。

第二个问题是因为 KCP 发送的数据量过大被 ISP 限制了，这个问题正常修复过程中。

**Comment by lins05** [comment]
感谢两位回复。

> 第二个问题是因为 KCP 发送的数据量过大被 ISP 限制了，这个问题正常修复过程中。  

我用 kcptun ，能达到差不多的速度(3~4MB/s)，但是没有这个问题。

**Comment by testcaoy7** [comment]
KCP很容易断流，几下就停住了，不适合观看YTB，浏览网页好快

**Comment by v2ray** [comment]
这两个问题现在应该都修复了。如果继续碰到断流的情况，请附上详细的数据，如：

* KCP 的配置；
* 使用场景（比如视频、网页，同时开了多少个页面）；
* 当时的传输速度大约是多少，在正常使用多久之后发生断流情况。

**Comment by lins05** [comment]
试了下最新版本，确实都修复了，感谢。
