### ISSUE TITLE
是否有计划内置DNS中增加多源的可能性

### ISSUE THREAD

**Issue by JMVoid** [v2ray/v2ray-core#1811]
在v2ray的未来开发中，是否增强内置DNS的功能，经过配置，可以让内置DNS实现多上游解析。然后根据一定规则决定采用那个来源作为最终的DNS. eg. 大陆DNS解析出来-IPA, 8.8.8.8 解析出来的IP-B. 然后能过配置规则 。如果解析回来的IP-A为境外IP. 则采用IP-B为最终IP给系统使用。

**Comment by kslr** [comment]
没有，这个需求交给dns server更合适
