### ISSUE TITLE
Docker镜像很久没更新了

### ISSUE THREAD

**Issue by coolucifer** [v2ray/v2ray-core#1814]
dockerhub上的最新镜像是五周之前的, 不是和正式版本同步的吗?

**Comment by kslr** [comment]
欢迎你重新制作一份

**Comment by EHfive** [comment]
>https://hub.docker.com/r/v2ray/official/builds

v2ray/official 似乎是设置成跟踪 https://github.com/v2ray/ext 自动构建

或许Devs可以加个tag https://github.com/v2ray/ext/releases 或push空提交 触发Webhook push event 

>https://developer.github.com/webhooks/#events
>https://docs.docker.com/docker-hub/builds/#how-automated-builds-work

**Comment by kslr** [comment]
更新後已經編譯了

**Comment by EHfive** [comment]
https://github.com/v2ray/ext/blob/9eb3057da9bf83f83f4f1bda8528d0567419e709/docker/official/Dockerfile#L5

v2ray/official 应该没有使用最新代码编译, 用的 https://install.direct/go.sh 装V2ray, 只是下载最新Release复制到环境里, 而v2ray/dev是最新代码编译的.


https://github.com/v2ray/v2ray-core/blob/f364173e70c1f54cdd21a69b19db72a2326d427f/release/install-release.sh#L213

(PS: 为什么访问https://install.direct/ 403 , URL被重写成了 http://www.bilibili.com/....)

**Comment by iyjian** [comment]
> (PS: 为什么访问https://install.direct/ 403 , URL被重写成了 http://www.bilibili.com/....)

同问。
