### ISSUE TITLE
Support void linux

### ISSUE THREAD

**Issue by LinArcX** [v2ray/v2ray-core#1815]
Hi and thank you for your great works.
I'm a void-linux user but there isn't any package for it:
https://github.com/void-linux/void-packages/issues/4646

**Comment by iochen** [comment]
If you need, you can try to use a script to install on linux at the moment.
 https://v2ray.com/en/welcome/install.html#install-linux 

I never used void linux before, so I don't know if it works.

**Comment by LinArcX** [comment]
Void use runit as init system.

**Comment by nicholascw** [comment]
We are unable to contribute a package into its official repository and it is currently too costly on building binary packages for all distributions. Also, it's easy to install it manually. #1864
