### ISSUE TITLE
请支持chacha20-ietf-poly1305加密

### ISSUE THREAD

**Issue by HeyElio** [v2ray/v2ray-core#1816]
Shadowsocks协议不支持chacha20-ietf-poly1305，现在很多都用的chacha20-ietf-poly1305

**Comment by updater1234** [comment]
![Screenshot_20190725_173142](https://user-images.githubusercontent.com/31512600/61863451-3249bf00-af02-11e9-9e68-0d016d1f5d32.jpg)
不是已经支持了吗？

**Comment by zcluo** [comment]
支持一直就在用

发自我的 iPhone

**Comment by HeyElio** [comment]
那为什么我用不了
![image](https://user-images.githubusercontent.com/47845580/61867660-48f41400-af0a-11e9-87b7-a1925048a3f3.png)

**Comment by HeyElio** [comment]
> ![Screenshot_20190725_173142](https://user-images.githubusercontent.com/31512600/61863451-3249bf00-af02-11e9-9e68-0d016d1f5d32.jpg)
> 不是已经支持了吗？

我用不了

**Comment by updater1234** [comment]
直接就是chacha20-poly1305

**Comment by updater1234** [comment]
没有ietf

**Comment by HeyElio** [comment]
> 没有ietf

意思还是chacha20-ietf-poly1305用不了吗

**Comment by updater1234** [comment]
用的了，在v2ray里chacha20-poly1305等于chacha20-ietf-poly1305
________________________________

**Comment by updater1234** [comment]
简单的说，就是换了个名称罢了，实际上还是一样的

**Comment by HeyElio** [comment]
应该是我节点的问题

**Comment by zhuzeitou** [comment]
是chacha，你图里的是chaochao……
