### ISSUE TITLE
pixiv无法打开

### ISSUE THREAD

**Issue by zhz1237ok** [v2ray/v2ray-core#1819]
root@debian-s-1vcpu-1gb-sfo2-01:/var/log/v2ray# tail -f error.log 
2019/07/28 11:52:13 [Warning] v2ray.com/core: V2Ray 4.20.0 started
2019/07/28 12:17:45 [Warning] [4022646942] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.
2019/07/28 12:17:48 [Warning] [3880336941] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.
2019/07/28 12:17:50 [Warning] [1192765485] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unable to set read deadline > v2ray.com/core/transport/internet/kcp: Connection closed.

服务器端core是4.20 客户端core是4.20 用的是2dust的v2rayN的UI 2.29版本

不管是租的飞机还是自己搭建的，都是无法访问pixiv，提示

500 Internal Privoxy Error
Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

![image](https://user-images.githubusercontent.com/38283893/62002236-512e9800-b132-11e9-88dd-87aa710ce1dc.png)

而谷歌等其他网站可以正常使用，唯独pixiv有问题

**Comment by zhz1237ok** [comment]
解决了，是我服务器IP被PIXIV封掉了

**Comment by Clouxin** [comment]
请问大佬怎么解决的，也是google能登而pixiv登不上去，小白一个。
net::ERR_CONNECTION_CLOSED是指ip被封吗？
