### ISSUE TITLE
简单配置却无法代理

### ISSUE THREAD

**Issue by OrcaLee** [v2ray/v2ray-core#1821]
在更新v2rayn客户端和内核后出现无法代理的问题。提示信息：
配置成功
Shadowsocks-3.25(192***220:47261)
启动服务(2019/7/29 19:04:44)......
V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
2019/07/29 19:04:46 [Warning] v2ray.com/core: V2Ray 4.20.0 started
安卓客户端正常连接，另一台电脑没有更新，同样的节点也是正常连接。

**Comment by OrcaLee** [comment]
而且现在不管客户端和内核换成什么版本都会有类似的提示信息。

**Comment by iochen** [comment]
类似的提示信息是正常的，说明此软件已启动
```
V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
2019/08/28 16:50:00 [Warning] v2ray.com/core: V2Ray 4.20.0 started
```
