### ISSUE TITLE
docker镜像无法正确启动

### ISSUE THREAD

**Issue by ronysun** [v2ray/v2ray-core#1823]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v2ray的docker镜像 
Digest: sha256:1b3e47d56bb2e012b4a3dfad53e9385cd04cf85025eb504d0039eff046589507
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
docker镜像无法正常启动，提供服务
查看容器日志，报错： 
docker logs v2ray
standard_init_linux.go:211: exec user process caused "exec format error"
4) 你期待看到的正确表现是怎样的？
可以通过docker镜像提供v2ray服务

系统信息：
Linux zlink 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:40:37 UTC 2019 i686 i686 i686 GNU/Linux

 docker version
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Wed Jul  3 12:15:14 2019
 OS/Arch:           linux/386
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       2d0083d
  Built:            Mon Jul  1 19:31:12 2019
  OS/Arch:          linux/386
  Experimental:     false

**Comment by wi1dcard** [comment]
很可能是平台不正确，默认的镜像似乎是 For Linux AMD64。
