### ISSUE TITLE
router suspended

### ISSUE THREAD

**Issue by MichealStone** [v2ray/v2ray-core#1824]
When v2ray uses large traffic, there is a chance that the entire route will be suspended due to v2ray not connected to the server, and the link will not be in any background.

**Comment by crysislinux** [comment]
does your router support hardware FPU? A go grogram needs a lot of resource on embedded devices, especially one that doesn't support hardware FPU.

**Comment by MichealStone** [comment]
> 你的路由器是否支持硬件FPU？go grogram在嵌入式设备上需要大量资源，尤其是不支持硬件FPU的资源。

I think it should be supported. I am using intel E3-1260L and 6G memory. The system used is PVE system.
