### ISSUE TITLE
v2ray的负载均衡可否加入类似tcproute2的自动选择最快线路的功能。

### ISSUE THREAD

**Issue by cjjdaq** [v2ray/v2ray-core#1825]
https://github.com/GameXG/TcpRoute2
目前v2的负载均衡只会简单的随机选择出口
目前TcpRoute2的策略是 TcpPing ，即同时使用多个线路建立连接，最终使用最快建立连接的线路处理请求。
当某条线路访问某网站出现异常(响应超时、连接重置等)时将会被记录下来，下次访问同一网站时将跳过这个线路。
缓存10分钟上次检测到的最快线路方便以后使用

**Comment by cjjdaq** [comment]
目前是将v2ray的多个出口，用socks5入口，多个socks5加入tcproute2中进行线路优化，通过redsokcs给iptables用，有点麻烦啊，要是v2ray能集成线路优化就好了。


2019/08/01 17:31:06 [强制代理服务器DNS解析] 对目的地址是 173.194.167.136:443 的请求进行了重定向，新目标：r3---sn-a5mlrnek.googlevideo.com:443
缓存命中：r3---sn-a5mlrnek.googlevideo.com:443 代理：bwg2 IP：173.194.167.136:443 
2019/08/01 17:31:06 [强制代理服务器DNS解析] 对目的地址是 173.194.167.136:443 的请求进行了重定向，新目标：r3---sn-a5mlrnek.googlevideo.com:443
缓存命中：r3---sn-a5mlrnek.googlevideo.com:443 代理：ay IP：173.194.167.136:443 
2019/08/01 17:31:09 记录代理转发错误：连接建立时间 5.178074948 小于60秒，已发出 68 数据，但未收到任何数据。详细信息，代理名称:ay, 域名:88.208.54.117:10999, IP:88.208.54.117:10999，错误：EOF
2019/08/01 17:31:12 [强制代理服务器DNS解析] 对目的地址是 74.125.170.201:443 的请求进行了重定向，新目标：r3---sn-n4v7sn7s.googlevideo.com:443
2019/08/01 17:31:12 [强制代理服务器DNS解析] 对目的地址是 74.125.170.201:443 的请求进行了重定向，新目标：r3---sn-n4v7sn7s.googlevideo.com:443
2019/08/01 17:31:12 为 r3---sn-n4v7sn7s.googlevideo.com:443 找到了最快的稳定连接 74.125.170.201:443 ，线路：gia2.
2019/08/01 17:31:12 为 r3---sn-n4v7sn7s.googlevideo.com:443 找到了最快的稳定连接 74.125.170.201:443 ，线路：gia2.
2019/08/01 17:31:13 [强制代理服务器DNS解析] 对目的地址是 74.125.170.201:443 的请求进行了重定向，新目标：r3---sn-n4v7sn7s.googlevideo.com:443
2019/08/01 17:31:13 [强制代理服务器DNS解析] 对目的地址是 74.125.170.201:443 的请求进行了重定向，新目标：r3---sn-n4v7sn7s.googlevideo.com:443
2019/08/01 17:31:13 [强制代理服务器DNS解析] 对目的地址是 172.217.5.78:443 的请求进行了重定向，新目标：www.youtube.com:443
缓存命中：r3---sn-n4v7sn7s.googlevideo.com:443 代理：gia2 IP：74.125.170.201:443 
缓存命中：r3---sn-n4v7sn7s.googlevideo.com:443 代理：gia2 IP：74.125.170.201:443 
缓存命中：www.youtube.com:443 代理：ay IP：216.58.217.206:443 
2019/08/01 17:31:13 [强制代理服务器DNS解析] 对目的地址是 172.217.5.78:443 的请求进行了重定向，新目标：www.youtube.com:443
2019/08/01 17:31:13 [强制代理服务器DNS解析] 对目的地址是 172.217.5.78:443 的请求进行了重定向，新目标：www.youtube.com:443
缓存命中：www.youtube.com:443 代理：ay IP：216.58.217.206:443 
缓存命中：www.youtube.com:443 代理：ay IP：216.58.217.206:443 
2019/08/01 17:31:13 [强制代理服务器DNS解析] 对目的地址是 172.217.5.78:443 的请求进行了重定向，新目标：www.youtube.com:443
缓存命中：www.youtube.com:443 代理：ay IP：216.58.217.206:443 
2019/08/01 17:31:13 [强制代理服务器DNS解析] 对目的地址是 173.194.29.25:443 的请求进行了重定向，新目标：r3---sn-5uaezn6r.googlevideo.com:443
2019/08/01 17:31:13 [强制代理服务器DNS解析] 对目的地址是 173.194.29.25:443 的请求进行了重定向，新目标：r3---sn-5uaezn6r.googlevideo.com:443
2019/08/01 17:31:13 为 r3---sn-5uaezn6r.googlevideo.com:443 找到了最快的稳定连接 173.194.29.25:443 ，线路：bwg2.
2019/08/01 17:31:13 为 r3---sn-5uaezn6r.googlevideo.com:443 找到了最快的稳定连接 173.194.29.25:443 ，线路：bwg2.
2019/08/01 17:31:14 [强制代理服务器DNS解析] 对目的地址是 172.217.11.78:443 的请求进行了重定向，新目标：s.ytimg.com:443
2019/08/01 17:31:14 为 s.ytimg.com:443 找到了最快的稳定连接 172.217.11.78:443 ，线路：gia2.
2019/08/01 17:31:15 [强制代理服务器DNS解析] 对目的地址是 216.58.217.196:443 的请求进行了重定向，新目标：www.google.com:443
2019/08/01 17:31:15 为 www.google.com:443 找到了最快的稳定连接 216.58.217.196:443 ，线路：gia2.

**Comment by kslr** [comment]
Welcome PR

**Comment by JUNKC** [comment]
数据包在网络中每个路由器都会默认选择最优路径转发，，，
你这个在路由协议中就包含了，而且数据包怎么走不是由客户端控制的，每个路由器会自己维护一个路由表，根据已知的路由表选择最优路径转发，某个线路不通的时候也会快速切换另一条线路

**Comment by AnyoeDove** [comment]
v2ray 的负载均衡能用吗...我配置 balancerTag 就 balancer xxx not found

**Comment by MaruKoh** [comment]
v2ray的负载均衡不支持外部路由文件
V2Ray 4.18.0 (Po) 20190228
A unified platform for anti-censorship.
main: failed to read config file: Kernel/config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to load IPs: cn from v2fly.dat > v2ray.com/core/infra/conf: failed to open file: geoip.dat > open /data/5G/V2Proxy/Kernel/geoip.dat: no such file or directory
4.20版本也不支持

**Comment by cjjdaq** [comment]
已经改用clash客户端了

**Comment by MaruKoh** [comment]
负载均衡貌似开发者们不主推这个功能,客户端很容易出楼上的错误,4.19.1说是修复了固定geoip.dat的设定,支持外部路由文件,测试下来还是不支持外部路由文件…

**Comment by teraStars** [comment]
这个功能很需要。
可惜一直没推出，虽然有一个，却是儿戏般地随机选取outbound，等于没用。
最简单地算法维持一个队列就行，速度慢的，出问题的，挪到队列最后。永远取队列第一个。
可惜我也不懂go语言。没法写。

**Comment by teraStars** [comment]
> v2ray 的负载均衡能用吗...我配置 balancerTag 就 balancer xxx not found

用倒是也能用，但没什么意义，随机选一个出口出来，balance所有的代码一共就那么几行。

**Comment by wjx0912** [comment]
@cjjdaq   只根据ping还不够，ping值最小也不表示网速最高。最好能根据实际下载速度
