### ISSUE TITLE
在v2ray服务器上运行open VPN客户端后，掉线

### ISSUE THREAD

**Issue by OPPO9008** [v2ray/v2ray-core#1826]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
截至8月1日最新版本
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
手机使用v2ray连接v2ray服务器，v2ray服务器运行open VPN回国（免流）
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
v2ray服务器运行open VPN后，ssh，v2ray全部无法连接。登录VPS商的后台ping 8.8.8.8能连通
4) 你期待看到的正确表现是怎样的？
连接v2ray后，出现的是open VPN的IP
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:
{
        "log": {
                "access": "/var/log/v2ray/access.log",
                "error": "/var/log/v2ray/error.log",
                "loglevel": "warning"
        },
        "inbounds": [
                {
                        "port": 80,
                        "protocol": "vmess",
                        "settings": {
                                "clients": [
                                        {
                                                "id": "eaa5
954-＊＊＊＊＊＊＊＊b7ccb5a11",
                                                "level": 1,
                                                "alterId":
33
                                        }
                                ]
                        },
                        "streamSettings": {
                                "network": "tcp",
                                "tcpSettings": {
                                          1,1          顶 端

客户端配置:

{
  "dns": {
    "servers": [
      "1.1.1.1"
    ]
  },
  "inbounds": [
    {
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "tag": "socks"
    },
    {
      "port": 10809,
      "protocol": "http",
      "settings": {
        "userLevel": 8
      },
      "tag": "http"
    }
  ],
  "log": {
    "loglevel": "warning"
  },
  "outbounds": [
    {
      "mux": {
        "enabled": false
      },
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "",
            "port": 80,
            "users": [
              {
                "alterId": 233,
                "id": "eaa5b954-4-96b9-e3bb7ccb5a11",
                "level": 8,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "",
        "tcpSettings": {
          "connectionReuse": true,
          "header": {
            "request": {
              "version": "1.1",
              "method": "GET",
              "path": [
                "/"
              ],
              "headers": {
                "User-Agent": [
                  "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36",
                  "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
                ],
                "Accept-Encoding": [
                  "gzip, deflate"
                ],
                "Connection": [
                  "keep-alive"
                ],
                "Pragma": "no-cache",
                "Host": [
                  "lt.hn.189.cn:1082"
                ]
              }
            },
            "type": "http"
          }
        }
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    }
  ],
  "policy": {
    "levels": {
      "8": {
        "connIdle": 300,
        "downlinkOnly": 1,
        "handshake": 4,
        "uplinkOnly": 1
      }
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": []
  },
  "stats": {}
}
6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by kslr** [comment]
openvpn后你的网络就变了

**Comment by OPPO9008** [comment]
> openvpn后你的网络就变了
那么开启open vpn后，v2ray是否监听ens18网卡上的端口，只是所有流量都被转发到tun虚拟网卡上了？能否用iptables让80端口进来的流量不用转发到tun网卡，或者服务器放行v2ray服务端，v2ray服务端再连接本机回环地址上的sock／HTTP代理实现？

**Comment by OPPO9008** [comment]
问题已经解决了把需要回国的域名解析后缓存在IP set里，iptables匹配打上mask转发到tun网卡的https://bigeagle.me/2016/02/ipset-policy-routing/
https://blog.sorz.org/p/openwrt-outwall/
