### ISSUE TITLE
路由设置中api tag放在geoip:private路由设置之后本地v2ctl api访问会被block

### ISSUE THREAD

**Issue by oriengy** [v2ray/v2ray-core#1828]
1) 你正在使用哪个版本的 V2Ray？
4.9和4.20
3) 你看到的不正常的现象是什么？
在localhost上使用v2ctl api命令调用API时，一直卡住，既不会超时也不会返回信息
现象同issue #1216 
4) 你期待看到的正确表现是怎样的？
在v2ctl api 调用的端口与config.json文件中配置的端口一致时，调用v2ctl api命令能够迅速返回信息
5) 服务器端配置:
1.当routing.rules项配置如下时，能正常使用
        "rules": [
            {
                "inboundTag": [
                    "api"
                ],
                "outboundTag": "api",
                "type": "field"
            },
            {
                "type": "field",
                "ip": [
                    "geoip:private"
                ],
                "outboundTag": "blocked"
            }
    ]
2.当routing.rules项配置如下时(其他配置不变，两规则顺序调换)，出现上述异常
        "rules": [
            {
                "type": "field",
                "ip": [
                    "geoip:private"
                ],
                "outboundTag": "blocked"
            },
            {
                "inboundTag": [
                    "api"
                ],
                "outboundTag": "api",
                "type": "field"
            }
    ]

推测采用2配置时，本地v2ctl api 发出的请求destination为127.0.0.1，被geoip:private匹配到然后被blocked，所以请求无法被第二个规则匹配到。出现上述异常。

如果你们认为我的推测没问题的话，麻烦修改一下代码逻辑，把api写成一个默认优先的规则或者在v2ray.com首页的文档中写清楚。

以及v2ctl api连接不成功时也没有任何反馈，可以考虑增加超时和提示？

因为这个坑网上没有任何资料，花了我几个小时。麻烦你们完善一下，避免一下这种坑再次有人踩吧。

**Comment by muddyEYEs** [comment]
先转发API的tag，把geoip:private放到后面即可。

**Comment by oriengy** [comment]
> 先转发API的tag，把geoip:private放到后面即可。

我知道要这样做，我是想说文档里写清楚，不要让后面的人踩坑

**Comment by muddyEYEs** [comment]
> > 先转发API的tag，把geoip:private放到后面即可。
> 
> 我知道要这样做，我是想说文档里写清楚，不要让后面的人踩坑

其实这样的写法不严谨吧，严谨一些可以指定 tag 。

**Comment by wattic** [comment]
同碰到这个问题，感谢踩坑。routing这段的文档有点乱，感觉流量统计这部分的routing配置和现在最新的配置并不是一个格式，有个 "strategy": "rules",和路由文档不一致。

**Comment by lp123sun** [comment]
> 1. 你正在使用哪个版本的 V2Ray？
>    4.9和4.20
> 2. 你看到的不正常的现象是什么？
>    在localhost上使用v2ctl api命令调用API时，一直卡住，既不会超时也不会返回信息
>    现象同issue #1216
> 3. 你期待看到的正确表现是怎样的？
>    在v2ctl api 调用的端口与config.json文件中配置的端口一致时，调用v2ctl api命令能够迅速返回信息
> 4. 服务器端配置:
>    1.当routing.rules项配置如下时，能正常使用
>    "rules": [
>    {
>    "inboundTag": [
>    "api"
>    ],
>    "outboundTag": "api",
>    "type": "field"
>    },
>    {
>    "type": "field",
>    "ip": [
>    "geoip:private"
>    ],
>    "outboundTag": "blocked"
>    }
>    ]
>    2.当routing.rules项配置如下时(其他配置不变，两规则顺序调换)，出现上述异常
>    "rules": [
>    {
>    "type": "field",
>    "ip": [
>    "geoip:private"
>    ],
>    "outboundTag": "blocked"
>    },
>    {
>    "inboundTag": [
>    "api"
>    ],
>    "outboundTag": "api",
>    "type": "field"
>    }
>    ]
> 
> 推测采用2配置时，本地v2ctl api 发出的请求destination为127.0.0.1，被geoip:private匹配到然后被blocked，所以请求无法被第二个规则匹配到。出现上述异常。
> 
> 如果你们认为我的推测没问题的话，麻烦修改一下代码逻辑，把api写成一个默认优先的规则或者在v2ray.com首页的文档中写清楚。
> 
> 以及v2ctl api连接不成功时也没有任何反馈，可以考虑增加超时和提示？
> 
> 因为这个坑网上没有任何资料，花了我几个小时。麻烦你们完善一下，避免一下这种坑再次有人踩吧。

能把能用的格式发个出来么，参照这里设置的用不了：
https://guide.v2fly.org/advanced/traffic.html#%E6%B5%81%E9%87%8F%E4%BF%A1%E6%81%AF%E7%9A%84%E5%A4%84%E7%90%86
