### ISSUE TITLE
关于内存占用

### ISSUE THREAD

**Issue by Coolkids** [v2ray/v2ray-core#184]
![qq 20160628114627](https://cloud.githubusercontent.com/assets/1288503/16403313/69d8faae-3d26-11e6-999d-285a016a1916.png)
![qq 20160628114552](https://cloud.githubusercontent.com/assets/1288503/16403312/692be3be-3d26-11e6-8139-84d361a5a512.png)
客户端/服务端版本：1.17.3  使用kcp协议 客户端 kcpSettings.downlinkCapacity = 40，服务器端 kcpSettings.uplinkCapacity = 12
使用http代理挂下载时间长了内存占用会直线上升（感觉socks也有这个问题）， win64客户端最高到吃满所有可用内存，没有内存回收。内存占用越高下载的速度越慢，重启客户端后能恢复。

另外cpu占用比原来低了很多赞一个。

**Comment by v2ray** [comment]
下载的时候速度多少？只有在 KCP 才有这个问题吗？

**Comment by Coolkids** [comment]
直连只能用kcp，其他模式根本没速度。
内存在100M内的时候下载速度可以到3MB/s   内存占用超过100M后下降速度开始下降只到这里0KB/s  客户端配置文件开启了dns设置。  
目前1.17.1版本关闭了tcp重连，关闭了dns， 内存占用109M，下载速度也有2MB/s  使用正常

**Comment by v2ray** [comment]
大概是因为现在版本的 KCP 释放连接太慢，多线程下载的时候不能有效地清理已关闭的连接。之后的版本会修复这一问题。

**Comment by v2ray** [comment]
请问你用的是哪个下载工具？下一个 release 之前我试一下。

**Comment by Coolkids** [comment]
bittorrent   设置 > 连接 使用http代理 使用代理进行点对点连接

**Comment by v2ray** [comment]
昨天试了一下 1.18.2，aria2 开了 16 线程下载，服务器内存占用 160MB 左右，客户端 50MB 以下。更多的线程会导致服务器端的内存继续上升，直到占满（下载完成之后会自动释放）。这个问题暂时没有很好的解决方案。

客户端的内存占用看上去很奇怪。如果在 1.18.x 中还能重现，请告知。
