### ISSUE TITLE
负载均衡无法正常使用外部路由文件

### ISSUE THREAD

**Issue by MaruKoh** [v2ray/v2ray-core#1846]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
4.18
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
国内域名走tag:c 国外域名走tag:g
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
客户端 v2ray无法正常启动
4) 你期待看到的正确表现是怎样的？
正常启动
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
```

客户端配置:

```javascript
 {
  "inbounds": [
    {
      "port": 1080,
      "protocol": "dokodemo-door",
      "settings": {
        "network": "tcp",
        "followRedirect": true
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    },
    {
      "port": 1081,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "1.1.1.1",
            "port": 1082,
            "users": [
              {
                "id": "c87d3346-686b-4083-93bb-1437cf666666",
                "alterId": 1,
                "security": "aes-128-cfb"
              }
            ]
          }
        ]
      },
      "tag": "c",
      "streamSettings": {
        "network": "tcp",
        "tcpSettings": {
          "header": {
            "type": "http",
            "request": {
              "version": "1.1",
              "method": "GET",
              "path": [
                "http://lt.hn.189.cn:1082/"
              ],
              "headers": {
                "Host": [
                  "lt.hn.189.cn:1082"
                ]
              }
            }
          }
        }
      }
    },
     {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "1.2.3.4",
            "port": 1082,
            "users": [
              {
                "id": "2a565b90-5797-41fb-8706-2a7c04e9781e",
                "alterId": 1,
                "security": "aes-128-cfb"
              }
            ]
          }
        ]
      },
      "tag": "g",
      "streamSettings": {
        "network": "tcp",
        "tcpSettings": {
          "header": {
            "type": "http",
            "request": {
              "version": "1.1",
              "method": "GET",
              "path": [
                "http://lt.hn.189.cn:1082/"
              ],
              "headers": {
                "Host": [
                  "lt.hn.189.cn:1082"
                ]
              }
            }
          }
        }
      }
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "block"
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
    "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "outboundTag": "block",
        "domain": [
          "ext:v2fly.dat:ad"
        ]
      },
      {
        "type": "field",
        "ip": [
          "ext:v2fly.dat:cn"
        ],
        "balancerTag": "balancer"        
      },
       {
        "type": "field",
        "domain": [
          "ext:v2fly.dat:gfw"
        ],
        "balancerTag": "b2"        
      }
     ],
      "balancers": [
      {
        "tag": "balancer",
        "selector": [
           "c"
          ]
        },
      {
        "tag": "b2",
        "selector": [
           "g"
          ]
       }
     ]
  }
} // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。
V2Ray 4.18.0 (Po) 20190228
A unified platform for anti-censorship.
main: failed to read config file: Kernel/config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to load IPs: cn from v2fly.dat > v2ray.com/core/infra/conf: failed to open file: geoip.dat > open /data/5G/V2Proxy/Kernel/geoip.dat: no such file or directory

 > exit status 255

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by MaruKoh** [comment]
4.19.1 4.20也不行

**Comment by teraStars** [comment]
我等会看看，但应该和外部路由没关系，我现在就用了外部路由+balancer，没啥问题，正常能用。
不过现在这个负载均衡就是个玩笑，没必要用它。你直接用inbound和outbound绑在route里就行了。

**Comment by teraStars** [comment]
你这个有明显的问题。是不是安装软件搞错了？
你的配置里就没用到geoip.dat，怎么会跑这个路径取拿geoip.dat呢？ /data/5G/V2Proxy/Kernel/geoip.dat

**Comment by MaruKoh** [comment]
是v2ray的程序指定了geoip.dat
用外部路由文件的IP也要去geoip.dat查找,
所以只能用官方的geoip.dat

**Comment by MaruKoh** [comment]
当/data/5G/V2Proxy/Kernel目录有geoip.dat这个文件,v2ray正常启动,配置指定的是ext:v2fly.dat:cn,v2ray程序是不会从v2fly.dat的cn规则拿IP,会去geoip.dat拿IP。
所以结论就是不支持外部路由文件(IP,CIDR规则)

**Comment by Cwek** [comment]
好像4.18之后有外部push了一个加载外部geodata的问题，原因是方法写错了。

**Comment by MaruKoh** [comment]
4.19的那个push但是并没有解决那个问题

**Comment by ToutyRater** [comment]
[domainStrategy 配置](https://v2ray.com/chapter_02/03_routing.html#routingobject)
* "AsIs": 只使用域名进行路由选择。默认值。
* "IPIfNonMatch": 当域名没有匹配任何规则时，将域名解析成 IP（A 记录或 AAAA 记录）再次进行匹配；
     * 当一个域名有多个 A 记录时，会尝试匹配所有的 A 记录，直到其中一个与某个规则匹配为止；
     * 解析后的 IP 仅在路由选择时起作用，转发的数据包中依然使用原始域名；
* "IPOnDemand": 当匹配时碰到任何基于 IP 的规则，将域名立即解析为 IP 进行匹配；

你应该用 IPOnDemand 而不是 IPIfNonMatch
