### ISSUE TITLE
域名解析时的权限问题

### ISSUE THREAD

**Issue by FH0** [v2ray/v2ray-core#1849]
udp已经通过tproxy转发到v2ray

使用dig命令，向 208.67.222.222:5353查询dns，正常返回，向 208.67.222.222:53查询dns，查询失败
![qq_pic_merged_1566193036572](https://user-images.githubusercontent.com/32861476/63242449-ff3ce600-c289-11e9-8141-768f57254a49.jpg)

日志显示权限不足，v2ray是用非root用户运行的
`2019/08/19 05:46:25 [Info] [3787368634] v2ray.com/core/transport/internet: failed to bind source address to [208 67 222 222] > permission denied`

希望非root用户运行的v2ray向53端口查询域名也能像向5353端口查询域名那样正常返回域名解析结果

**Comment by Cwek** [comment]
4.CAP_NET_BIND_SERVICE
从 2.1 版本开始，Linux 内核有了能力的概念，这使得普通用户也能够做只有超级用户才能完成的工作，这包括使用端口。

获取CAP_NET_BIND_SERVICE能力，即使服务程序运行在非root帐户下，也能够banding到低端口。使用的方法： 
root账户下执行

`
setcap cap_net_bind_service=+eip <v2ray的程序路径，对脚本无效>
`

 ———————————————— 
版权声明：本文为CSDN博主「Becivells」的原创文章，遵循CC 4.0 by-sa版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/Becivells/article/details/52842019

**Comment by updater1234** [comment]
setcap cap_net_bind_service=+ep /usr/bin/v2ray/v2ray
试一下执行这个命令然后重新启动一下，会不会有效。

**Comment by FH0** [comment]
> setcap cap_net_bind_service=+ep /usr/bin/v2ray/v2ray
> 试一下执行这个命令然后重新启动一下，会不会有效。

可以了，感谢
