### ISSUE TITLE
go.sh安装后无法使用service v2ray start来启动服务

### ISSUE THREAD

**Issue by paladiny** [v2ray/v2ray-core#1854]
使用go.sh安装，发觉脚本并没有把 systemv目录下的v2ray 拷贝到/etc/init.d下
系统：Linux hk 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64 GNU/Linux

**Comment by updater1234** [comment]
现在都是用systemctl来管理了吧

**Comment by wwqgtxx** [comment]
systemctl start v2ray
