### ISSUE TITLE
v2ray.com/core/transport/internet/kcp: Read/Write timeout

### ISSUE THREAD

**Issue by xiebruce** [v2ray/v2ray-core#1855]
kcp模式用一段时间就会有这个问题：
```
xxx.xxx.xxx.xxx:xxxx rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > v2ray.com/core/transport/internet/kcp: Read/Write timeout
```
其中`xxx.xxx.xxx.xxx:xxxx`是ip和端口。

用不用tls都有这问题，怀疑是ISP Qos的问题？这个问题一时半会儿测不出来，连续几天甚至一周使用kcp模式就会有感受，有人说把它伪装成TCP能解决？据说kcptun已经实现了？

相似问题：https://github.com/v2ray/v2ray-core/issues/1347

**Comment by xiebruce** [comment]
没有一个回复就这么关掉了？

**Comment by kslr** [comment]
你希望得到什么

**Comment by xiebruce** [comment]
@kslr 我想知道一下：这个问题是已经解决了？还是有计划会解决？还是已经确定解决不了，又或者是其它原因？？

**Comment by kslr** [comment]
kcp本身是有这个劣势的，其他几乎没有信息，我也不知道该如何回复。

**Comment by xiebruce** [comment]
@kslr 哦哦，好的
