### ISSUE TITLE
NodeJS 调用 v2ray API 问题

### ISSUE THREAD

**Issue by ghost** [v2ray/v2ray-core#1856]
参考 go 版本调用 API 的例子，作者另写了个 `serial.ToTypedMessage` 方法，于是我也照葫芦画瓢写了个类似的方法，由于不知道 protobuf nodejs-sdk 如何获取包名，所以我用手动传参来延缓这个问题：
```
function getTypedMessage (type, input) {
            message = new serial.message.TypedMessage()
            message.setType(type)
            message.setValue(input.serializeBinary())
            return message
}
operation.setUser(getTypedMessage(
            'v2ray.core.proxy.vmess.Account', user
))
```
然而会提示 `message.getLevel is not a function` （此 message 为 protobuf 生成的 sdk 中的变量，不是 `getTypedMessage` 中的 message ），是不是 `serializeBinary` 函数用的不对呢？还有如果有大佬知道 protobuf nodejs 版本如何获取包名也麻烦告知一下谢谢。

**Comment by muddyEYEs** [comment]
已解决，眼花了，setUser 并不是 TypedMessage 类型。

**Comment by muddyEYEs** [comment]
哦对了，protobuf 在 nodejs 中 如何获取 class name 还没解决，知道的大佬麻烦告知一下，谢谢。

**Comment by zcmimi** [comment]
可以给个完整代码码？
