### ISSUE TITLE
能否先实现一个简单的负载均衡策略让大家用用？

### ISSUE THREAD

**Issue by teraStars** [v2ray/v2ray-core#1857]
Please describe the new feature you want in detail.
这个功能还是挺有必要的，有时这个服务器慢，有时那个慢，现在我都是自己手工去客户端软件v2rayN上切换。但这样操作会比较麻烦，而且这样切换时，必须用客户端软件的配置文件，导致失去了v2ray强大的灵活性。
这个功能提出了也很久了，但现在一直只有一个最简单的随机抽一个outbound出来连接的策略，这样的策略没什么意义。
我也能理解要真正做出一个好的负载均衡策略，有难度。
那么能否先实现一个最简单的平衡策略，维持一个队列，当发现节点速度比较慢或者联不通时，将这个节点放到队列最后，然后永远取第一个。

**Comment by MaruKoh** [comment]
这个功能可以去看下kitsunebi-android 
https://p.codekk.com/detail/5cfa6cc4fd1c9b26e2fccf5f

**Comment by teraStars** [comment]
> 这个功能可以去看下kitsunebi-android
> https://p.codekk.com/detail/5cfa6cc4fd1c9b26e2fccf5f
谢谢推荐。

**Comment by DaedalusT** [comment]
不建议使用，IP频繁变动不是件好事，相反会变得很麻烦

**Comment by strongbugman** [comment]
IP变动频率可以配置嘛，确实存在某段时间某个服务器更慢、某个更快的情况
