### ISSUE TITLE
v2ctl 连接被拒绝

### ISSUE THREAD

**Issue by CGQAQ** [v2ray/v2ray-core#1859]
1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
4.20
```
 .\v2ctl.exe api --server="127.0.0.1:10888" StatsService.GetStats "name: """"inbound>>>statin>>>traffic>>>downlink"""" reset: false"

rejected  v2ray.com/core/proxy/socks: unknown Socks version: 80
```

on windows

![image](https://user-images.githubusercontent.com/15936231/63586893-1f93da00-c5d5-11e9-8460-8d89cbaeb748.png)

**Comment by kslr** [comment]
please use socks5

**Comment by CGQAQ** [comment]
v2ctl.exe 和 v2ray.exe， 哪个可以设置socks5啊
v2ray配置文件
```
  "inbounds": [
    {
      "port": 10888,
      "listen": "127.0.0.1",
      "protocol": "socks",
```
难道v2ctl默认不是socks5？
