### ISSUE TITLE
打开部分网站会出现无法打开情况或者等待时间过长

### ISSUE THREAD

**Issue by ljm000** [v2ray/v2ray-core#186]
打开部分网站会出现无法打开情况或者等待时间过长，要重新在提交或者打开一次才能打开。

使用TCP和KCP均出现这样的问题，动态端口和固定端口均出现这样的问题。

国内网络。

<img>http://i.imgur.com/4ZMkAGN.png</img>
<img>http://i.imgur.com/niNWHVR.png</img>

**Comment by v2ray** [comment]
客户端或服务器端的 V2Ray 有配置 DNS 么？https://www.v2ray.com/zh_cn/chapter_02/04_dns.html

在配置了 DNS 的情况，有一定机率会碰到上述问题，刷新页面可以解决。

**Comment by crystoneme** [comment]
碰到了相同的问题，也是打开半天才出来。
还有一个情况就是一直在上传，上传的速度比下载的还大，网页加载完毕还是如此。

**Comment by jinlongplus** [comment]
客户端或服务器端的 V2Ray 有配置 DNS 么？https://www.v2ray.com/zh_cn/chapter_02/04_dns.html

在配置了 DNS 的情况，有一定机率会碰到上述问题，刷新页面可以解决。

--------------------------------------------------------------------------------------------
大神，看不懂DNS该怎么配置，能不能指导一下，谢谢。我不明白的点是：
1. DNS这个配置是在客户端上配置，还是在服务器端上配置?
如果是在客户端上配置，对应的servers是填我的VPS地址吗?那服务器端又配置什么呢?
如果是在服务端上配置，那客户端又配置些什么使DNS查询会发送到服务端呢?

2. "IPIfNonMatch": 当域名没有匹配任何规则时，将域名解析成 IP（A 记录）再次进行匹配
这个配置是客户端还是服务端的，这个解析是谁来解析，发送到别的DNS服务器上吗，还是V2RAY本身就是自己会解析地址?

**Comment by liaobin** [comment]
建议用cow配合使用

**Comment by kathylincn** [comment]
用kcp模式打开网站响应速度不要太快哦.用TCP打开感觉有一秒的延迟,换成KCP简直就是秒开了.
就是YOUTUBE看的时候,速度不及TCP模式.
TCP模式用WIN客户端看YOUTUBE的话,速度能上6W.但是换成ARM客户端,速度只有1.2W.
这差距也太大了吧?ARM版的是不是消减了性能了啊?我ARM运行的时候,CPU和内存都没满啊.
KCP模式用WIN客户端的话,速度只有1.2W.和ARM版的TCP模式差不多了都.唯一的好处就是网页响应快点.

**Comment by kathylincn** [comment]
而且KCP如果参数不调好的话,还不如不用.没调之前看U2B.只有3000~5000,所以参数很重要.不过不管调不调参数,打开网页的响应时间都是不变的.很快很快.

**Comment by crazyyi** [comment]
同问，为什么DNS设置会这么麻烦？用Shadowsocks好像没遇到类似问题。

**Comment by netroby** [comment]
https://github.com/v2ray/v2ray-core/issues/560
