### ISSUE TITLE
客户端内存泄漏

### ISSUE THREAD

**Issue by caoli5288** [v2ray/v2ray-core#1861]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
4.20

2) 你的使用场景是什么？
路由器上透明代理

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
内存泄漏，有多少吃多少，路由器总共4g内存，不限制的话内存能被v2ray吃光，然后路由器卡到爹妈不应，限了内存后内存满了cpu就经常100%
```
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O           PIDS
1aa42ef6a035        v2ray               0.80%               123.9MiB / 128MiB   96.80%              0B / 0B             4.1kB / 0B          15
```

4) 你期待看到的正确表现是怎样的？
按理说不会这样的

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": ""
  },
  "inbounds": [
    {
      "port": 1080,
      "listen": "0.0.0.0",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true
      }
    },
    {
      "port": 12345,
      "protocol": "dokodemo-door",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "streamSettings": {
        "sockopt": {
          "tproxy": "tproxy"
        }
      },
      "settings": {
        "network": "tcp,udp",
        "followRedirect": true
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "",
            "port": 443,
            "users": [
              {
                "id": "",
                "alterId": 64,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "wsSettings": {
          "connectionReuse": true,
          "path": "/x"
        }
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom"
    },
    {
      "tag": "block",
      "protocol": "blackhole"
    }
  ],
  "dns": {
    "servers": [
      "1.1.1.1",
      {
        "address": "114.114.114.114",
        "port": 53,
        "domains": [
          "geosite:cn"
        ]
      },
      "localhost"
    ]
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "outboundTag": "block",
        "domain": [
          "geosite:category-ads"
        ]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "geosite:cn"
        ]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:private",
          "geoip:cn"
        ]
      }
    ]
  }
}

```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

日志无异常

**Comment by caoli5288** [comment]
没有人答复吗

**Comment by lfznnzq** [comment]
给你参考
``{
        "inbounds":[
                {  //任意门，用于透明代理
                "protocol": "dokodemo-door", 
                "port": 1080, 
                "listen": "0.0.0.0", 
                "settings": {
                        "network": "tcp, udp", 
                        "timeout": 30, 
                        "followRedirect": true
                        },
                "sniffing": {
                        "enabled": true,
                        "destOverride": ["http", "tls"]
                        },
                "tag": "in-0"  //入口0标识
                },
                {  //socks5，用于浏览器代理
                "port":"1081",
                "protocol":"socks",
                "settings":{
                        "auth":"noauth",
                        "udp":true
                                },
                "sniffing": {
                        "enabled": true,
                        "destOverride": ["http", "tls"]
                        },
                "tag": "in-1"  //入口1标识
                },
                { //http代理，用于系统代理
                "port":"1082",
                "protocol":"http",
                "settings":{},
                "sniffing": {
                        "enabled": true,
                        "destOverride": ["http", "tls"]
                        },
                "tag": "in-2"  //入口2标识
                },
                { //任意门，备用dns解析
                "protocol": "dokodemo-door", 
                "port": 5353, 
                "settings": {
                        "address": "8.8.8.8", 
                        "port": 53, 
                        "network": "udp", 
                        "timeout": 0
                        }
                }
                        ],
        "outbounds":[
                {
                "protocol":"vmess",
                "settings":{
                        "vnext":[
                                {
                                "address":"1.1.1.1",
                                "port":3333,
                                "users":[
                                        {
                                        "id":"7e8bb2bc-958f-4ecd-ba03-8f1cdc4b3930",
                                        "alterId":32
                                        }
                                                ]
                                }
                                        ]
                                },
                "streamSettings":{
                        "network":"kcp",
                        "security":"none",
                        "kcpSettings":{},
                        "sockopt": {"mark": 255}
                        },
                "tag": "proxy"  //代理标识
                },
                {
                "sendThrough" : "0.0.0.0",
                "tag":"direct",   //直连标识
                "protocol":"freedom",
                "settings":{},
                "sockopt": {"mark": 255}
                },
                {
                "tag":"blocked",
                "protocol":"blackhole",
                "settings":{}
                }
                        ],
        "routing":{
                "domainStrategy":"AsIs",
                "rules":[
                        { //8.8.8.8走代理
                        "type": "field",
                        "ip": ["8.8.8.8"],
                        "outboundTag": "proxy"
                        },
                        { //被屏蔽的域名走代理，可自行添加
                        "type": "field",
                        "outboundTag": "proxy",
                        "domain": [
                        "google.com",
                        "youtube.com"
                                ]
                        },
                        { //入口0标识的流量直连
                        "type":"field",
                        "inboundTag": ["in-0"],
                        "outboundTag":"direct"
                        },
                        { //入口1标识的流量直连
                        "type":"field",
                        "inboundTag": ["in-1"],
                        "outboundTag":"direct"
                        },
                        { //入口2标识的流量直连
                        "type":"field",
                        "inboundTag": ["in-2"],
                        "outboundTag":"direct"
                        }
                        ]
                }
}

**Comment by lfznnzq** [comment]
给你参考
`{
        "inbounds":[
                {  //任意门，用于透明代理
                "protocol": "dokodemo-door", 
                "port": 1080, 
                "listen": "0.0.0.0", 
                "settings": {
                        "network": "tcp, udp", 
                        "timeout": 30, 
                        "followRedirect": true
                        },
                "sniffing": {
                        "enabled": true,
                        "destOverride": ["http", "tls"]
                        },
                "tag": "in-0"  //入口0标识
                },
                {  //socks5，用于浏览器代理
                "port":"1081",
                "protocol":"socks",
                "settings":{
                        "auth":"noauth",
                        "udp":true
                                },
                "sniffing": {
                        "enabled": true,
                        "destOverride": ["http", "tls"]
                        },
                "tag": "in-1"  //入口1标识
                },
                { //http代理，用于系统代理
                "port":"1082",
                "protocol":"http",
                "settings":{},
                "sniffing": {
                        "enabled": true,
                        "destOverride": ["http", "tls"]
                        },
                "tag": "in-2"  //入口2标识
                },
                { //任意门，备用dns解析
                "protocol": "dokodemo-door", 
                "port": 5353, 
                "settings": {
                        "address": "8.8.8.8", 
                        "port": 53, 
                        "network": "udp", 
                        "timeout": 0
                        }
                }
                        ],
        "outbounds":[
                {
                "protocol":"vmess",
                "settings":{
                        "vnext":[
                                {
                                "address":"1.1.1.1",
                                "port":3333,
                                "users":[
                                        {
                                        "id":"7e8bb2bc-958f-4ecd-ba03-8f1cdc4b3930",
                                        "alterId":32
                                        }
                                                ]
                                }
                                        ]
                                },
                "streamSettings":{
                        "network":"kcp",
                        "security":"none",
                        "kcpSettings":{},
                        "sockopt": {"mark": 255}
                        },
                "tag": "proxy"  //代理标识
                },
                {
                "sendThrough" : "0.0.0.0",
                "tag":"direct",   //直连标识
                "protocol":"freedom",
                "settings":{},
                "sockopt": {"mark": 255}
                },
                {
                "tag":"blocked",
                "protocol":"blackhole",
                "settings":{}
                }
                        ],
        "routing":{
                "domainStrategy":"AsIs",
                "rules":[
                        { //8.8.8.8走代理
                        "type": "field",
                        "ip": ["8.8.8.8"],
                        "outboundTag": "proxy"
                        },
                        { //被屏蔽的域名走代理，可自行添加
                        "type": "field",
                        "outboundTag": "proxy",
                        "domain": [
                        "google.com",
                        "youtube.com"
                                ]
                        },
                        { //入口0标识的流量直连
                        "type":"field",
                        "inboundTag": ["in-0"],
                        "outboundTag":"direct"
                        },
                        { //入口1标识的流量直连
                        "type":"field",
                        "inboundTag": ["in-1"],
                        "outboundTag":"direct"
                        },
                        { //入口2标识的流量直连
                        "type":"field",
                        "inboundTag": ["in-2"],
                        "outboundTag":"direct"
                        }
                        ]
                }
}`

**Comment by wd** [comment]
v2ray 的内存占用似乎是很高，也没有办法，你可以考虑定期重启一下服务看看。

不过你在路由器上面可以跑 docker？docker 本身也占用不少内存的，建议直接跑 v2ray 不要用 docker 了。

**Comment by caoli5288** [comment]
@wd 一开始我也是直接跑的，结果v2ray占掉1个g，吃不消

**Comment by wd** [comment]
这个确实有点多了，我这好像还没有那么严重。你的是自己弄的软路由？

**Comment by caoli5288** [comment]
@wd 对的，

**Comment by lfznnzq** [comment]
帮你改了一下。。。
{
	"inbounds": [
                {  //socks5，用于浏览器代理
                "port":"1080",
                "protocol":"socks",
                "settings":{
                        "auth":"noauth",
                        "udp":true
                                },
                "sniffing": {
                        "enabled": true,
                        "destOverride": ["http", "tls"]
                        },
                "tag": "in-0"  //入口0标识
                },
				{ //任意门，用于透明代理
                "protocol": "dokodemo-door",
                "port": 12345,
                "listen": "0.0.0.0",
                "settings": {
                        "network": "tcp, udp",
                        "timeout": 30,
                        "followRedirect": true
                        },
                "sniffing": {
                        "enabled": true,
                        "destOverride": ["http", "tls"]
                        },
                "tag": "in-1"  //入口1标识
                }
				],
	"outbounds": [
				{
				"tag": "proxy", //代理标识
				"protocol": "vmess",
				"settings": {
				"vnext": [
					{
					"address": "",
					"port": 443,
					"users": [
						{
						"id": "",
						"alterId": 64,
						"email": "t@t.tt",
						"security": "auto"
						}
						]
					}
					]
					},
				"streamSettings": {
					"network": "ws",
					"security": "tls",
					"wsSettings": {
					"connectionReuse": true,
					"path": "/x"
						}
					}
				},
				{
				"tag": "direct",
				"protocol": "freedom"
				},
				{
				"tag": "block",
				"protocol": "blackhole"
				}
				],
        "routing":{
                "domainStrategy":"AsIs",
                "rules":[
                        { //8.8.8.8走代理
                        "type": "field",
                        "ip": ["8.8.8.8"],
                        "outboundTag": "proxy"
                        },
                        { //被屏蔽的域名走代理，可自行添加
                        "type": "field",
                        "outboundTag": "proxy",
                        "domain": [
                        "google.com",
                        "youtube.com"
                                ]
                        },
                        { //入口0标识的流量直连
                        "type":"field",
                        "inboundTag": ["in-0"],
                        "outboundTag":"direct"
                        },
                        { //入口1标识的流量直连
                        "type":"field",
                        "inboundTag": ["in-1"],
                        "outboundTag":"direct"
                        }
                        ]
                }
}

**Comment by caoli5288** [comment]
@lfznnzq 谢谢了，不过不适合，我的需求是国内之外默认走代理，而不是只过墙

**Comment by zhaoyxdt** [comment]
透明代理+策略路由建议用ipset+dnsmasq，比较省资源。

**Comment by xmdmk** [comment]
应该是socks有问题，内存泄漏，不用socks协议就没事
