### ISSUE TITLE
Vmess+websocket limit simultaneous connections (IPs) per UUID

### ISSUE THREAD

**Issue by UralZima** [v2ray/v2ray-core#1865]
Hello. First thank you for creating such great product! 
I have a v2ray server v4.20, configured in websocket+vmess mode, it works fine.

My server will use multiple users (500-1000), and I want to limit simultaneous connections to one UUID, because these users can share the settings and UUID to anyone and my server will be overloaded with unwanted users. 

I know this feature is not implemented in v2ray itself, so I am asking for help how to implement this using some bash scripts or anything else.

I have some thoughts:

1. I have v2ray's access.log and it shows ip address, but not showing client email or UUID. If I can get email-<>-ip, I can parse that log file and if script finds multiple simultaneous IPs for same user, script will ban that user (remove from config)
But access.log don't have this information, and API also don't provide that info. Maybe it's possible to include it in access.log?

2. If the 1st variant is impossible, the only way I see - create 1000 vmess ports with different websocket paths, like /ws1, /ws2 etc. Give each user own websocket path and uuid. And then parse nginx access log and find abusers and ban them.

Please help finding a way for implementing ip limit per UUID. 
Thanks!

**Comment by kslr** [comment]
so,  https://github.com/v2ray/v2ray-core/pull/1767

**Comment by UralZima** [comment]
@ksir, thanks for the info. 
Then another question. Is it possible to modify "clients" section in config.json without restarting v2ray? like sending HUP signal to reread config. I tried to find in issues, and it seems not implemented. 

I found on the API page:
HandlerService: Add a new user to an inbound proxy (VMess only). 
But I didn't found any documentation or examples for doing it. Does the API modify config.json to persist newly added users? Or how it works?

**Comment by GeorgeGhost** [comment]
@UralZima can you upload a script you described in step one if you have done it? 
Thanks in advance

**Comment by UralZima** [comment]
I wrote it in console php. It is running from cron every 3 minutes. email is uid@something.
``
#!/usr/bin/php
<?php
require_once(__DIR__."/conn.php");

$log=file_get_contents("/var/log/v2ray/access.log");
$lines=explode("\n",$log);
$ips=array();
foreach($lines as $line)
{
	$d=explode(" ",trim($line));
	if(count($d)==6)
	{
		preg_match("#[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+#",$d[2],$ip);
		$ip=$ip[0];
		preg_match("#email:([0-9]+)@#",$d[5],$uid);
		if(isset($uid[1]))
		{
			$uid=$uid[1];
			#echo "uid $uid, ip $ip\n";
			if(!isset($ips[$uid]) || !in_array($ip,$ips[$uid]))
			$ips[$uid][]=$ip;
		}
	}
}

foreach($ips as $uid => $uips)
{
	echo "uid $uid: ".count($uips)." ips\n";
	if(count($uips)>3)
	{
		echo "banning $uid!\n";
		mysql_query("update users set active=0 where id=".$uid." limit 1") or die(mysql_error());
	}
}

shell_exec("echo > /var/log/v2ray/access.log");
``

**Comment by Juancollado2003** [comment]
> I wrote it in console php. It is running from cron every 3 minutes. email is uid@something.
> https://pastebin.com/10MU1ByC

Hi @UralZima, I tried your script and it ask for a file conn.php, if I create a empty file with that name then script run but doea nothing, it doesn't work, any help please?

**Comment by Julian-Zu** [comment]
Is there any new progress about banning the unwanted connection?

**Comment by lotexteam** [comment]
> Hello. First thank you for creating such great product!
> I have a v2ray server v4.20, configured in websocket+vmess mode, it works fine.
> 
> My server will use multiple users (500-1000), and I want to limit simultaneous connections to one UUID, because these users can share the settings and UUID to anyone and my server will be overloaded with unwanted users.
> 
> I know this feature is not implemented in v2ray itself, so I am asking for help how to implement this using some bash scripts or anything else.
> 
> I have some thoughts:
> 
> 1. I have v2ray's access.log and it shows ip address, but not showing client email or UUID. If I can get email-<>-ip, I can parse that log file and if script finds multiple simultaneous IPs for same user, script will ban that user (remove from config)
>    But access.log don't have this information, and API also don't provide that info. Maybe it's possible to include it in access.log?
> 2. If the 1st variant is impossible, the only way I see - create 1000 vmess ports with different websocket paths, like /ws1, /ws2 etc. Give each user own websocket path and uuid. And then parse nginx access log and find abusers and ban them.
> 
> Please help finding a way for implementing ip limit per UUID.
> Thanks!

Hi. Did you found solution?

**Comment by UralZima** [comment]
hello. sorry for late reply
after applying pull request https://github.com/v2ray/v2ray-core/pull/1767
I wrote a console-php script, which runs at cron every minute
https://pastebin.com/byZzQxav
you need to adapt it to your needs.

**Comment by UralZima** [comment]
This will ban this user in your system. nothing else. my system generates v2ray config from my mysql database, and push only active users. Each user is warned about simultaneous connections and know that will receive ban if will share to someone

**Comment by UralZima** [comment]
I wrote a simple php admin interface for managing users, put paidtill date, auto ban on end date or exceeding limit 3 ips per uuid. If you interested, I can sell it to someone and help integrate. uralzima@autistici.org

**Comment by ANZHONGGEN** [comment]
if you can build v2ray project,
client side when every start app ,then make global variable random number, websocket setting header, add this number 
header:{
private_num: random_num
private_id: uuid
}
and server side:
nginx websocket add middle pipe app check session

**Comment by skrittdev** [comment]
> I wrote it in console php. It is running from cron every 3 minutes. email is uid@something.
> https://pastebin.com/10MU1ByC



> hello. sorry for late reply
> after applying pull request #1767
> I wrote a console-php script, which runs at cron every minute
> https://pastebin.com/byZzQxav
> you need to adapt it to your needs.

Your script has a flaw, if 2 devices are connected in the same network (with the same ip), they will be counted as one device.
Is it possible to somehow check this?

**Comment by Kimberlysz** [comment]
> hello. sorry for late reply
> after applying pull request #1767
> I wrote a console-php script, which runs at cron every minute
> https://pastebin.com/byZzQxav
> you need to adapt it to your needs.

Thank you for your support here, I appreciate your time. 
I would love to pay if you can help me set up IP limits so at least if my customer share with different people, there's a IP limit.
Since I guess the v2ray I am using don't have conn.php, I just deleted 
    require_once(__DIR__."/conn.php");`

and set crontab -e and add cron jobs 
    */3  *  *  *  *  /path2directory

I am not sure if this will work or not. the v2ay I use is just build from v2fly.org official ones.

Finally I'd love to pay if you can help me set this right. I appreciate you in advance.

**Comment by xkjdox** [comment]
> > I wrote it in console php. It is running from cron every 3 minutes. email is uid@something.
> > https://pastebin.com/10MU1ByC
> 
> > hello. sorry for late reply
> > after applying pull request #1767
> > I wrote a console-php script, which runs at cron every minute
> > https://pastebin.com/byZzQxav
> > you need to adapt it to your needs.
> 
> Your script has a flaw, if 2 devices are connected in the same network (with the same ip), they will be counted as one device. Is it possible to somehow check this?

uhh sir how to set the limit ?

**Comment by lotexteam** [comment]
> > > I wrote it in console php. It is running from cron every 3 minutes. email is uid@something.
> > > https://pastebin.com/10MU1ByC
> > 
> > 
> > > hello. sorry for late reply
> > > after applying pull request #1767
> > > I wrote a console-php script, which runs at cron every minute
> > > https://pastebin.com/byZzQxav
> > > you need to adapt it to your needs.
> > 
> > 
> > Your script has a flaw, if 2 devices are connected in the same network (with the same ip), they will be counted as one device. Is it possible to somehow check this?
> 
> uhh sir how to set the limit ?

Hello. If you need, i have api on go, and billing on laravel, which controls connections, and can remove key without restarting, ant set limit to each key.

**Comment by attacking6** [comment]
> > > I wrote it in console php. It is running from cron every 3 minutes. email is uid@something.
> > > https://pastebin.com/10MU1ByC
> > 
> > 
> > > hello. sorry for late reply
> > > after applying pull request #1767
> > > I wrote a console-php script, which runs at cron every minute
> > > https://pastebin.com/byZzQxav
> > > you need to adapt it to your needs.
> > 
> > 
> > Your script has a flaw, if 2 devices are connected in the same network (with the same ip), they will be counted as one device. Is it possible to somehow check this?
> 
> uhh sir how to set the limit ?

did you got any respone?

**Comment by mircoc99** [comment]
@attacking6 Salam refigh Rahi baraye limit user peyda kardi belakhare be ma ham yad bedi?

**Comment by attacking6** [comment]
> @attacking6 Salam refigh Rahi baraye limit user peyda kardi belakhare be ma ham yad bedi?

nope

**Comment by es2008** [comment]
> > @attacking6 Salam refigh Rahi baraye limit user peyda kardi belakhare be ma ham yad bedi?
> 
> nope

salam, yeki chand rooz pish eddea karde bood ke mishe va mikhad amoozeshesho bezare vali felan ke khabari nist!

**Comment by arian6874** [comment]
> 

ki? too hamin github ya too youtube?

**Comment by AliDeV7** [comment]
ehtemalan mishe az tarighe UUID har account fahmid, farda roosh kar mikonam bebinam mitoonam codesho benvisam

**Comment by attacking6** [comment]
@AliDeV7 @arian6874 @es2008  https://github.com/vaxilu/x-ui/pull/179

**Comment by AliDeV7** [comment]
> @AliDeV7 @arian6874 @es2008 [vaxilu/x-ui#179](https://github.com/vaxilu/x-ui/pull/179)

testesh kardam vali vase man IP nemindaze, hamishe khaliyee nemidoonam moshkelesh chiye

**Comment by eee7654** [comment]
mn rah vase limit gozashtan az nazar zamani vase har config dorost kardam ba nginx az nazar conn hamzmn fek konam yekam kar mibare

**Comment by AliDeV7** [comment]
> mn rah vase limit gozashtan az nazar zamani vase har config dorost kardam ba nginx az nazar conn hamzmn fek konam yekam kar mibare

ini ke @attacking6 gozashtano bebin, oonja ye nafar codesho neveshte kamel test kardam okeye ham hast

**Comment by es2008** [comment]
too in link raveshe ghofl kardane account ro kamel tozih dade
https://www.youtube.com/watch?v=VXyNI9xzoXA

**Comment by AliDeV7** [comment]
> too in link raveshe ghofl kardane account ro kamel tozih dade https://www.youtube.com/watch?v=VXyNI9xzoXA

khoobeha vali samte server bayad handle beshe injoor chiza, nemishe tarafo majboor koni ke bere oon app o nasb kone bara inke etelaate devicesh o bede

**Comment by es2008** [comment]
> > too in link raveshe ghofl kardane account ro kamel tozih dade https://www.youtube.com/watch?v=VXyNI9xzoXA
> 
> khoobeha vali samte server bayad handle beshe injoor chiza, nemishe tarafo majboor koni ke bere oon app o nasb kone bara inke etelaate devicesh o bede

بهرحال به از هیچیه
البته اپ مود شده V2ray هم هست که قسمت شیر رو برداشته و امکان اشتراک گذاری کد رو نداره

**Comment by net-pioneer** [comment]
hi  , i actually wrote a script which able to detect and ban the account which conntected to more than 2 devices . 
it is possible and the way i choose is to detect connections of each account's ip address .
if there is 2 different Ips detected the script ban and disable that account ! 

don't forget that you will get conntected IPs whitch user is not connected ! so you should write some Bash to Filter Real Connected users.

**Comment by AliDeV7** [comment]
> hi , i actually wrote a script which able to detect and ban the account which conntected to more than 2 devices . it is possible and the way i choose is to detect connections of each account's ip address . if there is 2 different Ips detected the script ban and disable that account !
> 
> don't forget that you will get conntected IPs whitch user is not connected ! so you should write some Bash to Filter Real Connected users.

can you shared with us?

**Comment by net-pioneer** [comment]
> > hi , i actually wrote a script which able to detect and ban the account which conntected to more than 2 devices . it is possible and the way i choose is to detect connections of each account's ip address . if there is 2 different Ips detected the script ban and disable that account !
> > don't forget that you will get conntected IPs whitch user is not connected ! so you should write some Bash to Filter Real Connected users.
> 
> can you shared with us?

Of course dadash

**Comment by net-pioneer** [comment]
https://github.com/net-pioneer/v2ray-connection-limiter/blob/main/main.py

it's my code . might help you .
#zan-zendegi-azadi

**Comment by technoell** [comment]
> -

Hello
Can you help me how can I add your code to my x-ui ?
I'm beginner
Thank you

**Comment by technoell** [comment]
> https://github.com/net-pioneer/v2ray-connection-limiter
> 
> it's my code . might help you . #zan-zendegi-azadi

Hello
Can you help me how can I add your code to my x-ui ?
I'm beginner
Thank you

**Comment by es2008** [comment]
dadash damet garm, in code ro bayad koja vared konim?

**Comment by net-pioneer** [comment]
@es2008 @technoell 

install python  (min v3.7) and python pip
next install :
pip3 install requests

some servers has netstat by default . if your sever doesn;t have netsate so install it (debian : apt install net-tools)

and run script on background >> nohup python3 main.py &

note : 
to code ye link hast ke vase notification account block shode be telegrame ! ke mitoni tosh token bot va chat_id telegrameto bezani bet notifi bede . (chatid az bot cid bot ham mitoni begiri). age nmikhi on ye khato vardar

**Comment by net-pioneer** [comment]
dar hale hazer fgt account haye ro barassi mikone ke gablaz run kardan in script to panel tarif shode . 
vase hamin mozo majbori vase barasi user haye jadid ino bebandi bad dobare ejra koni.
(baraye bastanesham kill <PID> , pid ham az ps -aux | grep python3 miad)
update badi inam ezafe mikonam ke user haye jadid ham detect kone .

**Comment by technoell** [comment]
> @es2008 @technoell
> 
> install python (min v3.7) and python pip next install : pip3 install requests
> 
> some servers has netstat by default . if your sever doesn;t have netstat so install it (debian : apt install net-tools)
> 
> and run script on background >> nohup python3 main.py &
> 
> note : to code ye link hast ke vase notification account block shode be telegrame ! ke mitoni tosh token bot va chat_id telegrameto bezani bet notifi bede . (chatid az bot cid bot ham mitoni begiri). age nmikhi on ye khato vardar

Do these steps have to be executed inside VPS?
Python is installed in my laptop

I know I am asking very simple questions, but I would appreciate it if you could give me more detailed guidance

**Comment by net-pioneer** [comment]
ok Version 2 has uploaded on my repository . it's not able to detect new users aswell and minor issues fixed .

https://github.com/net-pioneer/v2ray-connection-limiter

**Comment by net-pioneer** [comment]
> > @es2008 @technoell
> > install python (min v3.7) and python pip next install : pip3 install requests
> > some servers has netstat by default . if your sever doesn;t have netstat so install it (debian : apt install net-tools)
> > and run script on background >> nohup python3 main.py &
> > note : to code ye link hast ke vase notification account block shode be telegrame ! ke mitoni tosh token bot va chat_id telegrameto bezani bet notifi bede . (chatid az bot cid bot ham mitoni begiri). age nmikhi on ye khato vardar
> 
> Do these steps have to be executed inside VPS? Python is installed in my laptop
> 
> I know I am asking very simple questions, but I would appreciate it if you could give me more detailed guidance


this Script should work on VPS dude !!! it's doesn't related to your labtop
those step should be execute on your vps terminal

**Comment by technoell** [comment]
> > > @es2008 @technoell
> > > install python (min v3.7) and python pip next install : pip3 install requests
> > > some servers has netstat by default . if your sever doesn;t have netstat so install it (debian : apt install net-tools)
> > > and run script on background >> nohup python3 main.py &
> > > note : to code ye link hast ke vase notification account block shode be telegrame ! ke mitoni tosh token bot va chat_id telegrameto bezani bet notifi bede . (chatid az bot cid bot ham mitoni begiri). age nmikhi on ye khato vardar
> > 
> > 
> > Do these steps have to be executed inside VPS? Python is installed in my laptop
> > I know I am asking very simple questions, but I would appreciate it if you could give me more detailed guidance
> 
> this Script should work on VPS dude !!! it's doesn't related to your labtop those step should be execute on your vps terminal


with this code i install python
sudo apt update
sudo apt install software-properties-common
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt install python3.9

with this code i install pip
sudo apt install python3-pip

with this code i install netstat 
sudo apt install net-tools

I have no idea about step 4
Please give more guidance

**Comment by net-pioneer** [comment]
> 
first rival read about _max_allowed_connections  in document.
and then
 
transfer main.py to your server 
and run it >> python3 main.py

if you wanna put it in background >> nohup python3 main.py &

**Comment by net-pioneer** [comment]
> > > > @es2008 @technoell
> > > > install python (min v3.7) and python pip next install : pip3 install requests
> > > > some servers has netstat by default . if your sever doesn;t have netstat so install it (debian : apt install net-tools)
> > > > and run script on background >> nohup python3 main.py &
> > > > note : to code ye link hast ke vase notification account block shode be telegrame ! ke mitoni tosh token bot va chat_id telegrameto bezani bet notifi bede . (chatid az bot cid bot ham mitoni begiri). age nmikhi on ye khato vardar
> > > 
> > > 
> > > Do these steps have to be executed inside VPS? Python is installed in my laptop
> > > I know I am asking very simple questions, but I would appreciate it if you could give me more detailed guidance
> > 
> > 
> > this Script should work on VPS dude !!! it's doesn't related to your labtop those step should be execute on your vps terminal
> 
> with this code i install python sudo apt update sudo apt install software-properties-common sudo add-apt-repository ppa:deadsnakes/ppa sudo apt install python3.9
> 
> with this code i install pip sudo apt install python3-pip
> 
> with this code i install netstat sudo apt install net-tools
> 
> I have no idea about step 4 Please give more guidance

first rival read about _max_allowed_connections in document.
and then

transfer main.py to your server
and run it >> python3 main.py

if you wanna put it in background >> nohup python3 main.py &

**Comment by technoell** [comment]
> > > > > @es2008 @technoell
> > > > > install python (min v3.7) and python pip next install : pip3 install requests
> > > > > some servers has netstat by default . if your sever doesn;t have netstat so install it (debian : apt install net-tools)
> > > > > and run script on background >> nohup python3 main.py &
> > > > > note : to code ye link hast ke vase notification account block shode be telegrame ! ke mitoni tosh token bot va chat_id telegrameto bezani bet notifi bede . (chatid az bot cid bot ham mitoni begiri). age nmikhi on ye khato vardar
> > > > 
> > > > 
> > > > Do these steps have to be executed inside VPS? Python is installed in my laptop
> > > > I know I am asking very simple questions, but I would appreciate it if you could give me more detailed guidance
> > > 
> > > 
> > > this Script should work on VPS dude !!! it's doesn't related to your labtop those step should be execute on your vps terminal
> > 
> > 
> > with this code i install python sudo apt update sudo apt install software-properties-common sudo add-apt-repository ppa:deadsnakes/ppa sudo apt install python3.9
> > with this code i install pip sudo apt install python3-pip
> > with this code i install netstat sudo apt install net-tools
> > I have no idea about step 4 Please give more guidance
> 
> ## first rival read about _max_allowed_connections in the document.
> and then
> ## pip3 install requests
> pip3 install schedule
> 
> transfer main.py to your server and run it >> python3 main.py
> 
> if you wanna put it in background >> nohup python3 main.py & and test the program



For last question
Is your code work with this version of script?
https://github.com/FranzKafkaYu/x-ui
this is new(1.6.2) and support english

what is this means : put it in background or without background

transfer main.py to your server means with such WinSCP program i use to transfer ? and where ? in root ?

Sorry for so many questions
But as I said, I am a beginner
thank you for your helping

**Comment by net-pioneer** [comment]
> > > > > > @es2008 @technoell
> > > > > > install python (min v3.7) and python pip next install : pip3 install requests
> > > > > > some servers has netstat by default . if your sever doesn;t have netstat so install it (debian : apt install net-tools)
> > > > > > and run script on background >> nohup python3 main.py &
> > > > > > note : to code ye link hast ke vase notification account block shode be telegrame ! ke mitoni tosh token bot va chat_id telegrameto bezani bet notifi bede . (chatid az bot cid bot ham mitoni begiri). age nmikhi on ye khato vardar
> > > > > 
> > > > > 
> > > > > Do these steps have to be executed inside VPS? Python is installed in my laptop
> > > > > I know I am asking very simple questions, but I would appreciate it if you could give me more detailed guidance
> > > > 
> > > > 
> > > > this Script should work on VPS dude !!! it's doesn't related to your labtop those step should be execute on your vps terminal
> > > 
> > > 
> > > with this code i install python sudo apt update sudo apt install software-properties-common sudo add-apt-repository ppa:deadsnakes/ppa sudo apt install python3.9
> > > with this code i install pip sudo apt install python3-pip
> > > with this code i install netstat sudo apt install net-tools
> > > I have no idea about step 4 Please give more guidance
> > 
> > 
> > ## first rival read about _max_allowed_connections in the document.
> > and then
> > ## pip3 install requests
> > pip3 install schedule
> > transfer main.py to your server and run it >> python3 main.py
> > if you wanna put it in background >> nohup python3 main.py & and test the program
> 
> For last question Is your code work with this version of script? https://github.com/FranzKafkaYu/x-ui this is new(1.6.2) and support english
> 
> what is this means : put it in background or without background
> 
> transfer main.py to your server means with such WinSCP program i use to transfer ? and where ? in root ?
> 
> Sorry for so many questions But as I said, I am a beginner thank you for your helping


it should work ! i don't now but most of v2ray versions are same . 
if you run python3 main.py and see your account name list . it should work 75% ! i tested on what i posted on the document.

without background >> if you close putty (ssh) programs stops .

**Comment by es2008** [comment]
> > > > > > @es2008 @technoell
> > > > > > install python (min v3.7) and python pip next install : pip3 install requests
> > > > > > some servers has netstat by default . if your sever doesn;t have netstat so install it (debian : apt install net-tools)
> > > > > > and run script on background >> nohup python3 main.py &
> > > > > > note : to code ye link hast ke vase notification account block shode be telegrame ! ke mitoni tosh token bot va chat_id telegrameto bezani bet notifi bede . (chatid az bot cid bot ham mitoni begiri). age nmikhi on ye khato vardar
> > > > > 
> > > > > 
> > > > > Do these steps have to be executed inside VPS? Python is installed in my laptop
> > > > > I know I am asking very simple questions, but I would appreciate it if you could give me more detailed guidance
> > > > 
> > > > 
> > > > this Script should work on VPS dude !!! it's doesn't related to your labtop those step should be execute on your vps terminal
> > > 
> > > 
> > > with this code i install python sudo apt update sudo apt install software-properties-common sudo add-apt-repository ppa:deadsnakes/ppa sudo apt install python3.9
> > > with this code i install pip sudo apt install python3-pip
> > > with this code i install netstat sudo apt install net-tools
> > > I have no idea about step 4 Please give more guidance
> > 
> > 
> > ## first rival read about _max_allowed_connections in the document.
> > and then
> > ## pip3 install requests
> > pip3 install schedule
> > transfer main.py to your server and run it >> python3 main.py
> > if you wanna put it in background >> nohup python3 main.py & and test the program
> 
> For last question Is your code work with this version of script? https://github.com/FranzKafkaYu/x-ui this is new(1.6.2) and support english
> 
> what is this means : put it in background or without background
> 
> transfer main.py to your server means with such WinSCP program i use to transfer ? and where ? in root ?
> 
> Sorry for so many questions But as I said, I am a beginner thank you for your helping

Thanx for your Cooperation, could you please tell me which item from codes list must be replaced by our xu-i configuration?

**Comment by es2008** [comment]
I have transfer main.py to root folder of server and run it. but puuty app was remained on run mode as attached picture!
please help me ...

**Comment by net-pioneer** [comment]
> I have transfer main.py to root folder of server and run it. but puuty app was remained on run mode as picture in below link! please help me ... https://ibb.co/ZmYH2DK

nohup python3 main.py &

**Comment by es2008** [comment]
> 
But with this command as you sent, I have error too. please see the bellow image:
https://ibb.co/cD2xCq3

**Comment by net-pioneer** [comment]
> > 
> 
> But with this command as you sent, I have error too. please see the bellow image: https://ibb.co/cD2xCq3

nope ! it's working perfectly ! just press ctrl+c to break up ! and script working on background .
also you can see that process on this command >> ps -aux
and if you set telegram for notification you will see after disabling acc it will notify u

**Comment by technoell** [comment]
> 



> > > 
> > 
> > 
> > But with this command as you sent, I have error too. please see the bellow image: https://ibb.co/cD2xCq3
> 
> nope ! it's working perfectly ! just press ctrl+c to break up ! and script working on background . also you can see that process as well, so to see running processes with this command >> ps -aux and if you set telegram for notification you will see after disabling acc it will notify u

Hello
I install these and I see my CPU and Memory used 100% so i decide remove all, still My CPU and Memory is 100%

These code for install:
sudo apt update
sudo apt install software-properties-common
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt install python3.9
sudo apt install python3-pip
sudo apt install net-tools
pip3 install requests
pip3 install schedule
nohup python3 main.py &

These code for remove :
sudo apt remove software-properties-common
sudo apt remove python3.9
sudo apt remove python3-pip
sudo apt-get remove net-tools



What commands did I forget to completely delete and not execute the code?

**Comment by hoshangjan** [comment]
> nope ! it's working perfectly ! just press ctrl+c to break up ! and script working on background .
> also you can see that process as well, so to see running processes with this command >> ps -aux

How to increase the limit from 1 person to 3 people? Which line should I edit?? :DDD

**Comment by mohsenzadehkebria** [comment]
سلام دوستان این مشکل چطوری حل میشه؟
WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://mydomain.pw/):  > read tcp 100.112.37.194:41555->172.67.206.194:443: i/o timeout v2ray.com/core/transport

**Comment by hamedAligholizade** [comment]
that was awesome but is there any way to unblock the inbound if simultaneous connections are less than _max_allowed_connections ?
I tried enableAccount func in elif of run() in AccessChecker class, but there is some thing wrong with the terminal command that gives us the connection_count.
thanks. @net-pioneer

**Comment by hamedAligholizade** [comment]
> that was awesome but is there any way to unblock the inbound if simultaneous connections are less than _max_allowed_connections ? I tried enableAccount func in elif of run() in AccessChecker class, but there is some thing wrong with the terminal command that gives us the connection_count. thanks. @net-pioneer

I was silly with asking that question but improved script and blocked users will be unblocked when connections reduce to _max_allowed_connections

**Comment by SKRapToR20** [comment]
> > that was awesome but is there any way to unblock the inbound if simultaneous connections are less than _max_allowed_connections ? I tried enableAccount func in elif of run() in AccessChecker class, but there is some thing wrong with the terminal command that gives us the connection_count. thanks. @net-pioneer
> 
> I was silly with asking that question but improved script and blocked users will be unblocked when connections reduce to _max_allowed_connections

how did you do that bro ? i mean how did you unblock users that have been blocked when connection reduced to _max_allowed_connections ?

**Comment by mohaxray** [comment]
> @es2008 @technoell
> 
> install python (min v3.7) and python pip next install : pip3 install requests pip3 install schedule
> 
> some servers has netstat by default . if your sever doesn;t have netstat so install it (debian : apt install net-tools)
> 
> and run script on background >> nohup python3 main.py &
> 
> note : to code ye link hast ke vase notification account block shode be telegrame ! ke mitoni tosh token bot va chat_id telegrameto bezani bet notifi bede . (chatid az bot cid bot ham mitoni begiri). age nmikhi on ye khato vardar

salam , mamnonam vase script khobet . man alan moshkele user count daram toye server v2ray . age emkanesh hast mishe rahnamaee koni mano ? sepas :))
