### ISSUE TITLE
请问 Linux 服务端使用一键安装脚本安装后如何对软件进行完全卸载，感谢回答。

### ISSUE THREAD

**Issue by qnxsgwy** [v2ray/v2ray-core#187]
请问 Linux 服务端使用一键安装脚本安装后如何对软件进行完全卸载，在服务器上安装时出现了问题，看了说明中并没有卸载指令，请问是需要手动进行卸载么？如果必须手动的话大致怎么样操作才能进行卸载呢？感谢回答。

**Comment by v2ray** [comment]
如果你只是要重装的话，再次运行安装脚本即可，不必先卸载。卸载步骤如下，其中 systemd 和 sysv 二选一，取决于你的系统。

停用并卸载服务（systemd）：
systemctl stop v2ray
systemctl disable v2ray

停用并卸载服务（sysv）：
service v2ray stop
update-rc.d -f v2ray remove

然后删除以下文件：
/etc/v2ray/* (配置文件)
/usr/bin/v2ray/* (程序)
/var/log/v2ray/* (日志)
/lib/systemd/system/v2ray.service (systemd 启动项)
/etc/init.d/v2ray (sysv 启动项)

差不多就是这样了

**Comment by qnxsgwy** [comment]
嗯嗯，明白了，十分感谢。

**Comment by xinyouyule** [comment]
信游感谢分享

**Comment by kentcc88** [comment]
bash: update-rc.d: command not found

**Comment by fish-404** [comment]
我的systemd启动项不在`/lib`里而在`\etc`中

**Comment by ArmanZarif** [comment]
hi. how can reset x-ui password ?
