### ISSUE TITLE
不得不问，省略号处是什么？

### ISSUE THREAD

**Issue by marxangels** [v2ray/v2ray-core#1876]
![image](https://user-images.githubusercontent.com/42709228/64826072-1dc89f80-d5f2-11e9-9470-f3dda80b5047.png)

本来不想问，可是这一步走不下去了
```
set http_proxy=http://localhost:1081
go get -u v2ray.com/core
package v2ray.com/core: unrecognized import path "v2ray.com/core" (https fetch: Get http://www.v2ray.com/core/?go-get=1: redirected from secure URL https://v2ray.com/core?go-get=1 to insecure URL http://www.v2ray.com/core/?go-get=1)
```

**Comment by clockzhong** [comment]
> > ‘…’ 其实是go的一种语法糖。
> > 它的第一个用法主要是用于函数有多个不定参数的情况，可以接受多个不确定数量的参数。
> > 第二个用法是slice可以被打散进行传递。

别玩这些花活，很容易导致go语言版本的间的不兼容，这些有明显“技术坑”性质的“糖”还是要少吃，大家翻墙都不容易，整简单点，方便你我
