### ISSUE TITLE
v1.18 的 shadowsocks 貌似有问题。

### ISSUE THREAD

**Issue by cnperi** [v2ray/v2ray-core#188]
升级了两台vps（一台开了vmess和shadowsocks，一台只用了shadowsocks）的v2ray到v1.18，shadowsocks协议貌似有问题了。
1、未升级前，使用v1.17.1版本，两台vps都正常；
2、升级到v1.18后，两台都不能用shadowsocks了，显示为 handshake failed（手机ss），错误记录（warning下为空）
2016/07/04 03:53:23 [Debug]AuthenticationReader: Unexpected auth: []
2016/07/04 03:53:23 [Debug]IO: Pipe exits as Packet is corrupted.
2016/07/04 03:53:23 [Debug]IO: Pipe exits as EOF
2016/07/04 03:53:23 [Debug]IO: Pipe exits as EOF
2016/07/04 03:53:23 [Debug]IO: Pipe exits as EOF
2016/07/04 03:53:25 [Info]Shadowsocks: Tunnelling request to tcp:91.108.56.166:443
2016/07/04 03:53:25 [Info]DefaultDispatcher: Default route for tcp:91.108.56.166:443
2016/07/04 03:53:25 [Info]Freedom: Opening connection to tcp:91.108.56.166:443
2016/07/04 03:53:25 [Info]Dailing Raw TCP to tcp:91.108.56.166:443

配置未动。

**Comment by v2ray** [comment]
1.18.1 修复了这个问题。
