### ISSUE TITLE
如何使用这个对应的config文件：{"add":"103.44.61.67","aid":"233","host":"","id":"457143c7-d3f6-4efb-9271-4bca5695f05f","net":"tcp","path":"","port":26773,"ps":"SSRTOOL.COM","tls":"","type":"none","v":"2"}

### ISSUE THREAD

**Issue by hongyi-zhao** [v2ray/v2ray-core#1882]
有下面的v2rayN配置：
{"add":"103.44.61.67","aid":"233","host":"","id":"457143c7-d3f6-4efb-9271-4bca5695f05f","net":"tcp","path":"","port":26773,"ps":"SSRTOOL.COM","tls":"","type":"none","v":"2"}

怎么修改为v2ray格式？

尝试了许多都不行。

**Comment by Cwek** [comment]
服务器：103.44.61.67
端口：26773
alterId：233
id：457143c7-d3f6-4efb-9271-4bca5695f05f
ps字段没看出对应什么，连接应该是纯tcp

剩下的，RTFM

**Comment by kslr** [comment]
https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2)
