### ISSUE TITLE
最新版本v2ray不能传输数据

### ISSUE THREAD

**Issue by hongyi-zhao** [v2ray/v2ray-core#1883]
所用配置：

```
{
  "inbounds": [
    {
      "port": 1080,
      "protocol": "socks",
      "settings": {
        "udp": true
      }
    }
  ],

    "outbounds": [
        {
            "protocol": "vmess",
            "settings": {
                "vnext": [
                    {
                        "address": "103.44.61.67",
                        "port": 26773,
                        "users": [
                            {
                                "id": "457143c7-d3f6-4efb-9271-4bca5695f05f",
                                "alterId": 233,
                                "security": "auto"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp"

            }
        }
    ]


}
```

clash能够使用上面的对应配置成功联网。

但是 v2ray 给出如下错误：

```
$ ./v2ray -config ../config.json 
V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
2019/09/15 09:11:22 [Warning] v2ray.com/core: V2Ray 4.20.0 started
2019/09/15 09:11:33 [Warning] [3727399436] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 103.44.61.67:26773: connect: no route to host] > v2ray.com/core/common/retry: all retry attempts failed
```

**Comment by Cwek** [comment]
明显的，连接不上，检查下你这个配置的机器能不能连接上目标机器，ping又好，ncat又好。

**Comment by Brightfl** [comment]
将360安全卫士退出试试， 我的最新版的360卫士就会阻止v2ray修改系统代理注册表项，  btw: 360杀毒不需要退出， 360杀毒不管这个系统项修改

**Comment by hongyi-zhao** [comment]
@Brightfl  我是linux ，哪有 360 啊

**Comment by hongyi-zhao** [comment]
@Cwek 
$ ping -c4 103.44.61.67
PING 103.44.61.67 (103.44.61.67) 56(84) bytes of data.
64 bytes from 103.44.61.67: icmp_seq=1 ttl=51 time=47.4 ms
64 bytes from 103.44.61.67: icmp_seq=2 ttl=51 time=47.1 ms
64 bytes from 103.44.61.67: icmp_seq=3 ttl=51 time=46.9 ms
64 bytes from 103.44.61.67: icmp_seq=4 ttl=51 time=48.1 ms

--- 103.44.61.67 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3003ms
rtt min/avg/max/mdev = 46.980/47.434/48.118/0.460 ms

**Comment by hongyi-zhao** [comment]
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch

**Comment by kslr** [comment]
dial tcp 103.44.61.67:26773: connect: no route to hos

**Comment by hongyi-zhao** [comment]
@kslr  Is this mean that the server is down?

**Comment by kslr** [comment]
try ping

**Comment by hongyi-zhao** [comment]
@kslr  I've posted the ping result in this thread as follows:

$ ping -c2 103.44.61.67
PING 103.44.61.67 (103.44.61.67) 56(84) bytes of data.
64 bytes from 103.44.61.67: icmp_seq=1 ttl=51 time=47.4 ms
64 bytes from 103.44.61.67: icmp_seq=2 ttl=51 time=55.6 ms

--- 103.44.61.67 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms

**Comment by zhjgit** [comment]
Recently, the v2ray server TCP has failed, and my attempts to use `telnet IP:port` have failed.At present, I only have to listen on TCP ports,The transport protocol used is TCP
```
Trying 97.xxx.xxx.34...
Connected to 97.xxx.xxx.34.
Escape character is '^]'.
Connection closed by foreign host.
```

**Comment by zhjgit** [comment]
I tried two v2ray servers and both failed, including using the old version of v2ray, when using the TCP protocol. @kslr

**Comment by kslr** [comment]
@zhjgit check server

**Comment by zhjgit** [comment]
The newly purchased VPS server, and also the re-installed v2ray server, also has this problem.You can try it.

**Comment by Cwek** [comment]
[https://www.maketecheasier.com/fix-no-route-to-host-error-linux/](url)
telnet  103.44.61.67
或者检查下两边服务器的iptables

**Comment by hongyi-zhao** [comment]
werner@localhost:~$ telnet 103.44.61.67
Trying 103.44.61.67...
telnet: Unable to connect to remote host: No route to host

$ sudo iptables-save 
$

**Comment by Cwek** [comment]
很明显，是你的客户端根本连不上服务端，要么客户端的iptables OUT做了限制，要么就是服务端的端口没打开。

**Comment by hongyi-zhao** [comment]
@Cwek 你已经看到了，我的 iptables 根本没有任何内容：

$ sudo iptables-save 
$

而且，我尝试了众多vmess，没有一个成功的。

**Comment by zlylong** [comment]
建议检查一下系统时间

**Comment by QGB** [comment]
"failed to find an available destination"

**Comment by Cwek** [comment]
ping得通，可能L3端口被城墙堵塞了，用ncat检查端口能不能打开（nc -zvn <地址> <端口>），如果无法打开的话，估计端口被端了。
