### ISSUE TITLE
v2ray.com/core/proxy/vmess/encoding: invalid user

### ISSUE THREAD

**Issue by randerswan** [v2ray/v2ray-core#1885]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
4.20.0

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
Chrome 77.0.3865.75，无法打开Google主页

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
v2ray能正常的打开，但是一旦打开网页，就提示“v2ray.com/core/proxy/socks: unknown Socks version: 71”

4) 你期待看到的正确表现是怎样的？
V2Ray能正确代理访问Google

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:
{
        "log": {
                "access": "/var/log/v2ray/access.log",
                "error": "/var/log/v2ray/error.log",
                "loglevel": "warning"
        },
        "inbounds": [
                {
	"port": 35732,
	"protocol": "vmess",
	"settings": {
		"clients": [
			{
				"id": "xxxx-xxxx-xxxx-xxxx-xxxxxxxxxx",
				"level": 1,
				"alterId": xxx
			}
		],
		"detour": {
			"to": "dynamic"
		}
	},
	"streamSettings": {
		"network": "kcp",
		"kcpSettings": {
			"header": {
				"type": "dtls"
			}
		}
	},
	"sniffing": {
		"enabled": true,
		"destOverride": [
			"http",
			"tls"
		]
	}
},
        {
            "protocol": "vmess",
            "port": "10000-20000",
            "tag": "dynamic",
            "settings": {
                "default": {
                    "level": 1,
                    "alterId": 32
                }
            },
            "allocate": {
                "strategy": "random",
                "concurrency": 2,
                "refresh": 5
            },
            "streamSettings": {
                "network": "kcp",
                "kcpSettings": {
                    "header": {
                        "type": "dtls"
                    }
                }
            }
        }
                //include_ss
                //include_socks
                //include_mtproto
                //include_in_config
                //
        ],
        "outbounds": [
                {
                        "protocol": "freedom",
                        "settings": {}
                },
                {
                        "protocol": "blackhole",
                        "settings": {},
                        "tag": "blocked"
                },
                {
                        "protocol": "freedom",
                        "settings": {},
                        "tag": "direct"
                },
                {
                        "protocol": "mtproto",
                        "settings": {},
                        "tag": "tg-out"
                }
                //include_out_config
                //
        ],
        "dns": {
                "server": [
                        "1.1.1.1",
                        "1.0.0.1",
                        "8.8.8.8",
                        "8.8.4.4",
                        "localhost"
                ]
        },
        "routing": {
                "domainStrategy": "IPOnDemand",
                "rules": [
                        {
                                "type": "field",
                                "ip": [
                                        "0.0.0.0/8",
                                        "10.0.0.0/8",
                                        "100.64.0.0/10",
                                        "127.0.0.0/8",
                                        "169.254.0.0/16",
                                        "172.16.0.0/12",
                                        "192.0.0.0/24",
                                        "192.0.2.0/24",
                                        "192.168.0.0/16",
                                        "198.18.0.0/15",
                                        "198.51.100.0/24",
                                        "203.0.113.0/24",
                                        "::1/128",
                                        "fc00::/7",
                                        "fe80::/10"
                                ],
                                "outboundTag": "blocked"
                        },
                        {
                                "type": "field",
                                "inboundTag": ["tg-in"],
                                "outboundTag": "tg-out"
                        }
                        ,
                        {
                                "type": "field",
                                "domain": [
                                        "domain:epochtimes.com",
                                        "domain:epochtimes.com.tw",
                                        "domain:epochtimes.fr",
                                        "domain:epochtimes.de",
                                        "domain:epochtimes.jp",
                                        "domain:epochtimes.ru",
                                        "domain:epochtimes.co.il",
                                        "domain:epochtimes.co.kr",
                                        "domain:epochtimes-romania.com",
                                        "domain:erabaru.net",
                                        "domain:lagranepoca.com",
                                        "domain:theepochtimes.com",
                                        "domain:ntdtv.com",
                                        "domain:ntd.tv",
                                        "domain:ntdtv-dc.com",
                                        "domain:ntdtv.com.tw",
                                        "domain:minghui.org",
                                        "domain:renminbao.com",
                                        "domain:dafahao.com",
                                        "domain:dongtaiwang.com",
                                        "domain:falundafa.org",
                                        "domain:wujieliulan.com",
                                        "domain:ninecommentaries.com",
                                        "domain:shenyun.com"
                                ],
                                "outboundTag": "blocked"
                        }                       ,
                {
                    "type": "field",
                    "protocol": [
                        "bittorrent"
                    ],
                    "outboundTag": "blocked"
                }
                        //include_ban_ad
                        //include_rules
                        //
                ]
        },
        "transport": {
                "kcpSettings": {
            "uplinkCapacity": 100,
            "downlinkCapacity": 100,
            "congestion": true
        },
                "sockopt": {
                        "tcpFastOpen": true
                }
        }
}

客户端配置:

// Config file of V2Ray. This file follows standard JSON format, with comments support.
// Uncomment entries below to satisfy your needs. Also read our manual for more detail at
// https://www.v2ray.com/
{
  "log": {
    // By default, V2Ray writes access log to stdout.
    // "access": "/path/to/access/log/file",

    // By default, V2Ray write error log to stdout.
    // "error": "/path/to/error/log/file",

    // Log level, one of "debug", "info", "warning", "error", "none"
    "loglevel": "warning"
  },
  // List of inbound proxy configurations.
  "inbounds": [{
    // Port to listen on. You may need root access if the value is less than 1024.
    "port": 4956,

    // IP address to listen on. Change to "0.0.0.0" to listen on all network interfaces.
    "listen": "127.0.0.1",

    // Tag of the inbound proxy. May be used for routing.
    "tag": "socks-inbound",

    // Protocol name of inbound proxy.
    "protocol": "vmess",

    // Settings of the protocol. Varies based on protocol.
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    },

    // Enable sniffing on TCP connection.
    "sniffing": {
      "enabled": true,
      // Target domain will be overriden to the one carried by the connection, if the connection is HTTP or HTTPS.
      "destOverride": ["http", "tls"]
    }
  }],
  // List of outbound proxy configurations.
  "outbounds": [{
  // Protocol name of the outbound proxy.
	"protocol": "vmess",
	
	// Settings of the protocol. Varies based on protocol.
	"settings": {
		"vnext": [
			{
				"address": "xxx.xxx.xxx.xxx",
				"port": xxxxx,
				"users": [
					{
						"id": "xxxxx-xxxxx-xxxxx-xxxx-xxxxxxxxx",
						"alterId": xxx
					}
				]
			}
		]
	},
	
	// Tag of the outbound. May be used for routing.
	"tag": "proxy"
},{
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  }],

  // Transport is for global transport settings. If you have multiple transports with same settings
  // (say mKCP), you may put it here, instead of in each individual inbound/outbounds.
  //"transport": {},

  // Routing controls how traffic from inbounds are sent to outbounds.
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules":[
      {
        // Blocks access to private IPs. Remove this if you want to access your router.
        "type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "blocked"
      },
      {
        // Blocks major ads.
        "type": "field",
        "domain": ["geosite:category-ads"],
        "outboundTag": "blocked"
      }
    ]
  },

  // Dns settings for domain resolution.
  "dns": {
    // Static hosts, similar to hosts file.
    "hosts": {
      // Match v2ray.com to another domain on CloudFlare. This domain will be used when querying IPs for v2ray.com.
      "domain:v2ray.com": "www.vicemc.net",

      // The following settings help to eliminate DNS poisoning in mainland China.
      // It is safe to comment these out if this is not the case for you.
      "domain:github.io": "pages.github.com",
      "domain:wikipedia.org": "www.wikimedia.org",
      "domain:shadowsocks.org": "electronicsrealm.com"
    },
    "servers": [
      "1.1.1.1",
      {
        "address": "114.114.114.114",
        "port": 53,
        // List of domains that use this DNS first.
        "domains": [
          "geosite:cn"
        ]
      },
      "8.8.8.8",
      "localhost"
    ]
  },

  // Policy controls some internal behavior of how V2Ray handles connections.
  // It may be on connection level by user levels in 'levels', or global settings in 'system.'
  "policy": {
    // Connection policys by user levels
    "levels": {
      "0": {
        "uplinkOnly": 0,
        "downlinkOnly": 0
      }
    },
    "system": {
      "statsInboundUplink": false,
      "statsInboundDownlink": false
    }
  },

  // Stats enables internal stats counter.
  // This setting can be used together with Policy and Api. 
  //"stats":{},

  // Api enables gRPC APIs for external programs to communicate with V2Ray instance.
  //"api": {
    //"tag": "api",
    //"services": [
    //  "HandlerService",
    //  "LoggerService",
    //  "StatsService"
    //]
  //},

  // You may add other entries to the configuration, but they will not be recognized by V2Ray.
  "other": {}
}

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:
root@ShortStarchy-VM:/var/log/v2ray# ls -l
total 4
-rw------- 1 root root  0 Sep 18 10:31 access.log
-rw------- 1 root root 67 Sep 18 10:31 error.log

客户端错误日志:

c:\v264>v2ray.exe
V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
2019/09/18 11:56:49 [Warning] v2ray.com/core: V2Ray 4.20.0 started
2019/09/18 11:56:53 tcp:127.0.0.1:5540 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 67
2019/09/18 11:56:53 tcp:127.0.0.1:5539 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
2019/09/18 11:56:53 tcp:127.0.0.1:5541 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 67
2019/09/18 11:56:53 tcp:127.0.0.1:5538 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
2019/09/18 11:56:53 tcp:127.0.0.1:5542 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
2019/09/18 11:56:54 tcp:127.0.0.1:5543 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 67
2019/09/18 11:56:54 tcp:127.0.0.1:5545 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
2019/09/18 11:56:54 tcp:127.0.0.1:5544 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
2019/09/18 11:56:54 tcp:127.0.0.1:5547 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
access.log大小为0

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by randerswan** [comment]
---------- V2Ray安装信息 -------------

 V2Ray 传输协议 = mKCP_dtls_dynamicPort

 V2Ray 端口 = 35732

 V2Ray 动态端口范围 = 10000 - 20000

 是否配置 Shadowsocks = 未配置

---------- END -------------



---------- V2Ray 配置信息 -------------

 地址 (Address) = xxx.xxx.xxx.xxx

 端口 (Port) = xxxxx

 用户ID (User ID / UUID) = xxxx-xxxx-xxx-xxxx-xxxxxxx

 额外ID (Alter Id) = xxx

 传输协议 (Network) = kcp

 伪装类型 (header type) = dtls

 备注: 动态端口已启用...

---------- END -------------

**Comment by kslr** [comment]
https://www.v2ray.com/chapter_00/faq.html

**Comment by randerswan** [comment]
> 
> 
> https://www.v2ray.com/chapter_00/faq.html

无法访问，有可以打开的连接吗？
