### ISSUE TITLE
Does v2ray has client for ubuntu system?

### ISSUE THREAD

**Issue by pia** [v2ray/v2ray-core#1887]
I only found client for windows, ios, android, does v2ray has client for ubuntu system?

**Comment by ijacksonliu** [comment]
You can download it
By Google v2ray linux.
But it can only run in terminal.
I have done it today.

**Comment by pia** [comment]
solved. 
--------------------
wget https://install.direct/go.sh
sudo bash go.sh
/etc/v2ray/config.json  # config
sudo systemctl start/stop/restart v2ray

then a socks proxy is ready.
