### ISSUE TITLE
我用的是ws+v2ray的方式。出现以下错误，不知是哪里出了问题

### ISSUE THREAD

**Issue by taibin23** [v2ray/v2ray-core#1888]
n > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://nepal2india.top/): 521 Origin Down > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2019/09/20 18:47:19 tcp:127.0.0.1:1171 accepted tcp:google.com:443 
2019/09/20 18:47:19 tcp:127.0.0.1:1174 accepted tcp:www.gstatic.com:443 
2019/09/20 18:47:19 tcp:127.0.0.1:1175 accepted tcp:lh3.googleusercontent.com:443 
2019/09/20 18:47:19 tcp:127.0.0.1:1177 accepted tcp:www.google.com:443 
2019/09/20 18:47:19 tcp:127.0.0.1:1179 accepted tcp:rm.api.weibo.com:443 
2019/09/20 18:47:23 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://nepal2india.top/): 521 Origin Down > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by kslr** [comment]
duplicate #1883 1748

**Comment by Urt1rsLiu** [comment]
我也遇到了一样的问题, v2ray服务是active, 请问楼主怎么解决的
