### ISSUE TITLE
v1.18的shadowsocks出现问题。

### ISSUE THREAD

**Issue by qnxsgwy** [v2ray/v2ray-core#189]
1.17正常使用，一直使用在开启一次性认证状态。升级1.18后shadowsocks打开一次性认证就无法使用，日志文件正常，浏览器报错ERR_CONNECTION_CLOSED，关闭一次性认证之后才可以使用，是新版本需要手动开启一次性认证么？

**Comment by v2ray** [comment]
1.18.1 修复了这个问题。
