### ISSUE TITLE
使用cloudflare + tls + websocket + nginx 遇到的问题

### ISSUE THREAD

**Issue by zsedc800** [v2ray/v2ray-core#1896]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
版本都是4.20.0
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
使用Chrome通过socks/vmess 代理访问Google
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
网页无法访问，NGINX 日志提示 [23/Sep/2019:12:48:56 +0000]  "GET /ray HTTP/1.1" 404 153 "-" "Go-http-client/1.1" "12.234.55.5" 但是绕过cdn直接访问v2ray 端口是没有问题的
4) 你期待看到的正确表现是怎样的？
网页正常访问，
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
{
  "inbounds": [{
    "port": 29300,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "7ac625a5-6ea2-4957-b04a-164e86e5ab4b",
          "alterId": 64,
          "security": "auto"
        },
        {
          "id": "6d6f4f46-beff-489a-8ad7-462e023359c8",
          "alterId": 64,
          "security": "auto"
        },
        {
          "id": "4d24c649-dfaf-8a85-1499-e6842d9f457d",
          "alterId": 64,
          "security": "auto"
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "wsSettings": {
        "path": "/ray"
      }
    }
  }],
  "outbounds": [{
    "protocol": "freedom",
    "settings": {}
  },{
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  }],
  "routing": {
    "rules": [
      {
        "type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "blocked"
      }
    ]
  }
}

```

客户端配置:

```javascript
    // 在这里附上客户端配置
{
  "log": {
    "error": "",
    "loglevel": "info",
    "access": ""
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "ip": "",
        "userLevel": 0,
        "timeout": 0,
        "udp": false,
        "auth": "noauth"
      },
      "tag": "socks-inbound",
      "port": "1080"
    }
  ],
  "outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "wsSettings": {
          "path": "ray",
          "headers": {
            "host": ""
          }
        },
        "tlsSettings": {
          "allowInsecure": true
        },
        "security": "tls",
        "network": "ws"
      },
      "tag": "",
      "settings": {
        "vnext": [
          {
            "address": "mydomain",
            "users": [
              {
                "id": "7ac625a5-6ea2-4957-b04a-164e86e5ab4b",
                "alterId": 64,
                "level": 0,
                "security": "auto"
              }
            ],
            "port": 443
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": null
    },
    {
      "tag": "blocked",
      "protocol": "blackhole",
      "settings": null
    }
  ],
  "dns": {
    "servers": [
      ""
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": []
    }
  },
  "transport": {}
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
服务端v2ray 日志没有，判断是NGINX没有转发到
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
 v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:play.google.com:443 via tcp:mydomain:443
2019/09/23 21:11:21 [Info] [43447878] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > websocket: close 1006 (abnormal closure): unexpected EOF
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

nginx 配置
```
 location /ray {
            proxy_redirect off;
            proxy_pass http://127.0.0.1:29300;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $http_host;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            if ($http_upgrade = "websocket" ){
                proxy_pass http://127.0.0.1:29300;
          }
       }
```

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by rampageX** [comment]
客户端配置：
```
"streamSettings": {
        "wsSettings": {
          "path": "ray",
          "headers": {
            "host": ""
          }
        },
```
path 是不是少了个 “/”,应该是 /ray

**Comment by zsedc800** [comment]
与path路径无关，今天早上分析了一下，发现nginx 日志是有的，说明cdn成功将流量转发过来了，问题应该是nginx没有转发到v2ray 服务上。于是分别查看了一下http 和 https 虚拟主机的日志，发现一个诡异的情况，流量被打到HTTP 虚拟主机上了。所以在HTTP 80 server 配置了location /ray 转发。结果证实了我的判断，流量通了，成功翻墙了。
    但是为啥呢？cdn 转发的时候用的是HTTP？那我的tls数据是在哪里被解密的呢？很奇怪？

**Comment by shenlijun** [comment]
1.是不是ray少了/
2.我客户端抄了说明没有分开写
"streamSettings": {
        "network": "ws",
        "security": "tls",
        "wsSettings": {
          "path": "/xxx"
        }
      }

**Comment by shenlijun** [comment]
nginx那个的server应该听443端口？
再80端口用rewrite，直接把http转到https

**Comment by shenlijun** [comment]
就不需要再80配置location

**Comment by zsedc800** [comment]
path / 后面是加了的 nginx 那边一开始就是监听的443 的server 在做转发，是后面通过日志发现其实流量没有走到 443 的server 而是走到了80端口的server，于是就是试着在80端口的server配置location 转发结果发现转发成功了，v2ray 正常翻墙了。现在的问题是，为什么cdn转发过来的流量不是走https协议。

**Comment by shenlijun** [comment]
> path / 后面是加了的并没有什么效果问题不在这里。 nginx 那边一开始就是监听的443 的server 在做转发，是后面通过日志发现其实流量没有走到 443 的server 而是走到了80端口的server，于是就是试着在80端口的server配置location 转发结果发现转发成功了，v2ray 正常翻墙了。现在的问题是，为什么cdn转发过来的流量不是走https协议。

我是直接抄的白话教程的配置，好像和你的不太一样，那个配置一开始就走的443不走80，我在80的rewrite是做别的用途的。如果你走80就没有tls，不加密的话配置这么一大堆就没意义了

**Comment by zsedc800** [comment]
我也用白话教程搭过 ws + tls + nginx的方案，那个方案没问题确实走了443 但是，我这边加上cdn后就出现了我目前碰到的情况。客户端 --> cdn这个过程没问题肯定走了tls的，我怀疑cdn ---> vps nginx 这个阶段，cdn使用了HTTP，要不然就没办法解释了。

**Comment by goldlin** [comment]
Cloudflare -> SSL/TLS -> encryption mode: Full or Full(strict)

**Comment by ke1079556** [comment]
这是cf里没开https吧

**Comment by zsedc800** [comment]
确实，使用full strict 模式后https 日志看到有流量了
