### ISSUE TITLE
v2ray+websocket+tls+apache死活连接不上

### ISSUE THREAD

**Issue by vastsnow** [v2ray/v2ray-core#1903]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
4.20.0

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
使用AC66Ub1路由器Koolshare科学上网插件

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
访问超时，显示连接失败

4) 你期待看到的正确表现是怎样的？
能正常访问Google

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
服务器是ec2的AWS Linux AMI 系统

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
{
  "log": {
    "loglevel": "warning",
    "access": "/var/log/v2ray/access.log", // 这是 Linux 的路径
    "error": "/var/log/v2ray/error.log"
  },
"inbounds": [{
    "port": 37140,
    "listen":"127.0.0.1",
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "xxx",
          "level": 1,
          "alterId":48
        }
      ]
    },
        "streamSettings":{
         "network":"ws",
         "wsSettings":{
         "path":"/ray"
         }
        }
  }],
  "outbounds": [{
    "protocol": "freedom",
    "settings": {}
  }
  ]
}

```

客户端配置:

```javascript
    // 在这里附上客户端配置
{
  "inbounds": [{
    "port": 1080,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "sniffing": {
      "enabled": true,
      "destOverride": ["http", "tls"]
    },
    "settings": {
      "auth": "noauth",
      "udp": false
    }
  }],
  "outbounds": [{
    "protocol": "vmess",
    "settings": {
      "vnext": [{
        "address": "xxx",
        "port": 443,
        "users": [{
          "id": "xxx",
          "alterId": 48
        }]
      }]
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "wsSettings": {
        "path": "/ray"
      }
    }
  }]
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
2019/09/24 13:23:16 [Warning] v2ray.com/core: V2Ray 4.20.0 started
2019/09/24 16:15:00 [Warning] v2ray.com/core/transport/internet/websocket: faile
d to serve http for WebSocket > accept tcp 127.0.0.1:37140: use of closed networ
k connection
2019/09/24 16:15:00 [Warning] v2ray.com/core: V2Ray 4.20.0 started


```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
【2019年09月25日 23:39:58】: ======================= 梅林固件 - 【科学上网】 ========================
【2019年09月25日 23:39:58】:
【2019年09月25日 23:39:58】: ------------------------- 启动【科学上网】 -----------------------------
【2019年09月25日 23:39:59】: 删除ss相关的名单配置文件.
【2019年09月25日 23:39:59】: 重启dnsmasq服务...
【2019年09月25日 23:40:00】: 清除iptables规则和ipset...
【2019年09月25日 23:40:03】: 创建ipset名单
【2019年09月25日 23:40:03】: 添加自定义dnsmasq设置到/tmp/custom.conf
【2019年09月25日 23:40:04】: 自动判断使用国内优先模式，不加载cdn.conf
【2019年09月25日 23:40:04】: 创建gfwlist的软连接到/jffs/etc/dnsmasq.d/文件夹.
【2019年09月25日 23:40:04】: 使用自定义的v2ray json配置文件...
【2019年09月25日 23:40:04】: 解析V2Ray配置文件...
【2019年09月25日 23:40:04】: V2Ray配置文件写入成功到/koolshare/ss/v2ray.json
【2019年09月25日 23:40:04】: 检测到你的json配置的v2ray服务器：xxx不是ip格式！
【2019年09月25日 23:40:04】: 为了确保v2ray的正常工作，建议配置ip格式的v2ray服务器地址！
【2019年09月25日 23:40:04】: 尝试解析v2ray服务器的ip地址，DNS：xxx
【2019年09月25日 23:40:05】: v2ray服务器的ip地址解析成功：xxx
【2019年09月25日 23:40:05】: 测试V2Ray配置文件.....
【2019年09月25日 23:40:09】: Configuration OK.
【2019年09月25日 23:40:09】: V2Ray配置文件通过测试!!!
【2019年09月25日 23:40:10】: v2ray启动成功，pid：23653
【2019年09月25日 23:40:10】: 开启dns2socks，用于dns解析...
【2019年09月25日 23:40:11】: 加载nat规则!
【2019年09月25日 23:40:11】: 写入iptables规则到nat表中...
【2019年09月25日 23:40:11】: 加载ACL规则：【xxx】【全部端口】模式为：不通过SS
【2019年09月25日 23:40:11】: 加载ACL规则：【剩余主机】【全部端口】模式为：gfwlist模式
【2019年09月25日 23:40:12】: 开启DNS劫持功能功能，防止DNS污染...
【2019年09月25日 23:40:12】: 重启dnsmasq服务...
【2019年09月25日 23:40:13】: 添加ss规则定时更新任务，每天3自动检测更新规则.
【2019年09月25日 23:40:13】: ------------------------ 【科学上网】 启动完毕 ------------------------
【2019年09月25日 23:40:14】:
【2019年09月25日 23:40:14】: Across the Great Wall we can reach every corner in the world!
【2019年09月25日 23:40:14】:
【2019年09月25日 23:40:14】: ======================= 梅林固件 - 【科学上网】 ========================
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志

访问日志是空的

```

8) 其它相关的配置文件（如 Nginx）和相关日志。

使用的apache,作为子域名挂着。

<IfModule mod_ssl.c>
<VirtualHost *:443>
ServerName xxx
SSLEngine On
SSLProtocol -All +TLSv1 +TLSv1.1 +TLSv1.2
SSLCipherSuite HIGH:!aNULL
SSLCertificateFile xxx/fullchain.pem
SSLCertificateKeyFile xxx/privkey.pem

<LocationMatch "/ray/">
ProxyPass ws://127.0.0.1:37140/ray/ upgrade=WebSocket
ProxyAddHeaders Off
ProxyPreserveHost On
RequestHeader set Host %{HTTP_HOST}s
RequestHeader set X-Forwarded-For %{REMOTE_ADDR}s
</LocationMatch>

Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>

以下是apache的access_log

xxx - - [25/Sep/2019:15:23:32 +0000] "GET /ray HTTP/1.1" 404 201 "-" "Go-http-client/1.1"
xxx- - [25/Sep/2019:15:23:37 +0000] "GET /ray HTTP/1.1" 404 201 "-" "Go-http-client/1.1"
xxx- - [25/Sep/2019:15:23:38 +0000] "GET /ray HTTP/1.1" 404 201 "-" "Go-http-client/1.1"
xxx- - [25/Sep/2019:15:23:40 +0000] "GET /ray HTTP/1.1" 404 201 "-" "Go-http-client/1.1"
xxx- - [25/Sep/2019:15:23:40 +0000] "GET /ray HTTP/1.1" 404 201 "-" "Go-http-client/1.1"
xxx- - [25/Sep/2019:15:23:41 +0000] "GET /ray HTTP/1.1" 404 201 "-" "Go-http-client/1.1"
xxx- - [25/Sep/2019:15:23:45 +0000] "GET /ray HTTP/1.1" 404 201 "-" "Go-http-client/1.1"

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

启动是正常的

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

大概是apache的问题罢，但是重复检查过好多偏设置和白皮书和另外一个issue推荐的一样设置也不行。
apache里面相关的 mod像ws ,ssl ,proxy相关的都启用了。

站点上还挂着一个wordpress ,是访问正常的，直接用https访问子域名是默许的apache空页面，访问域名/ray/提示500错误。

折腾了两天，实在不知道是哪里的原因了，请教各位大佬。

**Comment by ke1079556** [comment]
"path":"/ray"改成"path":"/ray/"，服务器和客户端全改，再试试。

**Comment by the0demiurge** [comment]
我也遇到了同样的问题，按照@ke1079556 改过了也完全没有变化
```
xxxxx - - [xxxx] "GET /path/ HTTP/1.1" 404 653 "-" "Go-http-client/1.1"
```

**Comment by the0demiurge** [comment]
问题已解决，因为我不熟悉apache2的配置所以配置写得不对。
<location>标签直接放到letsencrypts创建的配置文件中的virtualhost标签内就可以转发了，不要再新建一个virtualhost到443

**Comment by vastsnow** [comment]
@ke1079556 
感谢，改了以后发现有反应了，但是access.log里面很多以下错误，error.log倒是没有新内容
rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > websocket: close 1000 (normal)
是还有问题么？有那么几个瞬间还能访问到Google，不过大部分时间都超时了，不知道是不是因为网站的速度太慢了

**Comment by kslr** [comment]
这个错误是因为请求没有被转发成功

**Comment by vastsnow** [comment]
@kslr 请教，是不是apache的设置有问题呢？

**Comment by kslr** [comment]
我不懂apache
