### ISSUE TITLE
用http全局代理正常，但是dokodemo-door就遇到failed to process outbound traffic 错误

### ISSUE THREAD

**Issue by herozzm** [v2ray/v2ray-core#1907]
1) 版本 V2Ray？
目前最新版:linux 64，直接下载在openwrt上运行

2) 使用场景？
路由器（ip：192.168.1.5）安装使用，局域网其他客户端透明代理失败使用chrome查看youtube，但使用了socks5和http全局代理就没问题

3) 不正常的现象？
全局代理http和socks5正常（被墙网站正常打开），透明代理dokodemo-door失败（被墙网站无法打开）

4) 正确表现是
透明代理dokodemo-door正常

5) 配置
v2ray的config.json：
```json
{
  "log": {
    "loglevel": "debug",
    "access": "/tmp/tmp/access.log",
    "error": "/tmp/tmp/error.log"
  },
  "inbounds": [
    {
      "port": 1080,
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth"
      }
    },
    {
      "port": 8080,  //客户端直接设置这个代理就正常
      "protocol": "http",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    },
    {
      "port": 12345,  //这个透明代理会失败
      "protocol": "dokodemo-door",
      "settings": {
        "network": "tcp",
        "timeout": 5,
        "followRedirect": true
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    },
    {
      "protocol": "dokodemo-door",
      "port": 5311,
      "settings": {
        "address": "8.8.8.8",
        "port": 53,
        "network": "udp",
        "timeout": 0,
        "followRedirect": false
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "服务器地址",
            "port": 543,
            "users": [
              {
                "id": "用户id",
                "alterId": 2
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "sockopt": {
          "mark": 255
        }
      },
      "mux": {
        "enabled": false
      }
    }
  ]
}
```

服务器端配置:
略

客户端配置:
openwrt的iptables配置，使用dnsmasq自动生成gfwlist黑名单ipset，同时将黑名单的dns查询转发到v2ray端口了，如下格式
```shell
server=/youtube.com/127.0.0.1#5311
ipset=/youtube.com/gfwlist
```
```shell
iptables -t nat -A PREROUTING-p tcp -m set --match-set gfwlist dst -j REDIRECT --to-ports 12345
iptables -t nat -A OUTPUT -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-ports 12345
```
根据日志，iptables转发成了

6)  出错时软件输出的错误日志。

服务器端错误日志:
直接全局代理没问题，所以无关服务端吧，略过

客户端错误日志:
```javascript
2019/09/27 05:39:47 [Debug] v2ray.com/core/app/log: Logger started
2019/09/27 05:39:47 [Warning] v2ray.com/core: V2Ray 4.20.0 started
2019/09/27 05:39:53 [Debug] [1837201471] v2ray.com/core/proxy/dokodemo: processing connection from: 127.0.0.1:63316
2019/09/27 05:39:53 [Info] [1837201471] v2ray.com/core/app/dispatcher: default route for udp:8.8.8.8:53
2019/09/27 05:39:53 [Info] [1837201471] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:18t85f.hk.static.ipv4.oreodns.com:543
2019/09/27 05:39:53 [Info] [1837201471] v2ray.com/core/proxy/vmess/outbound: tunneling request to udp:8.8.8.8:53 via tcp:18t85f.hk.static.ipv4.oreodns.com:543
2019/09/27 05:40:10 [Info] [1837201471] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > context canceled
2019/09/27 05:40:10 [Info] [1837201471] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled
```
看日志得知dns查询没问题（也在其他pc端用`dig @192.168.1.5 youtube.com`测试正常返回），最后一句出口流量失败

目前只能给每个客户端手动设置代理使用，无法透明代理，用了3.x版本存在同样问题

**Comment by lfznnzq** [comment]
/etc/firewall.user

ipset -N gfwlist iphash
iptables -t nat -A PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 12345

**Comment by herozzm** [comment]
> /etc/firewall.user
> 
> ipset -N gfwlist iphash
> iptables -t nat -A PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 12345
有新建的ipset，代码是这样的
```shell
ipset create gfwlist hash:ip
iptables -t nat -A PREROUTING-p tcp -m set --match-set gfwlist dst -j REDIRECT --to-ports 12345
iptables -t nat -A OUTPUT -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-ports 12345
```

**Comment by lfznnzq** [comment]
> > /etc/firewall.user
> > ipset -N gfwlist iphash
> > iptables -t nat -A PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 12345
> > 有新建的ipset，代码是这样的
> 
> ```shell
> ipset create gfwlist hash:ip
> iptables -t nat -A PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-ports 12345
> iptables -t nat -A OUTPUT -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-ports 12345
> ```
> 
> openwrt的防火墙已经彻底关闭
> 
> ```shell
> /etc/init.d/firewall disable
> /etc/init.d/firewall stop
> ```
参考
https://www.right.com.cn/forum/thread-938058-1-1.html

**Comment by herozzm** [comment]
> > > /etc/firewall.user
> > > ipset -N gfwlist iphash
> > > iptables -t nat -A PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 12345
> > > 有新建的ipset，代码是这样的
> > 
> > 
> > ```shell
> > ipset create gfwlist hash:ip
> > iptables -t nat -A PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-ports 12345
> > iptables -t nat -A OUTPUT -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-ports 12345
> > ```
> > 
> > 
> > openwrt的防火墙已经彻底关闭
> > ```shell
> > /etc/init.d/firewall disable
> > /etc/init.d/firewall stop
> > ```
> 
> 参考
> https://www.right.com.cn/forum/thread-938058-1-1.html

和我配置的差不多，原理也是一样，就是用dnsmasq-full将gfwlist的域名转到v2ray的5311的dns转发，然后用iptables将gfwlist的网站转到12345端口透明代理。
我的就是不行，我重置opewnrt，一步步安装他的弄一下看看行不行，比我多了一个iptables-mod-nat-extra，其他全部一样

**Comment by rampageX** [comment]
OUTPUT 那条链的规则先去掉试试

**Comment by lfznnzq** [comment]
> > > > /etc/firewall.user
> > > > ipset -N gfwlist iphash
> > > > iptables -t nat -A PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 12345
> > > > 有新建的ipset，代码是这样的
> > > 
> > > 
> > > ```shell
> > > ipset create gfwlist hash:ip
> > > iptables -t nat -A PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-ports 12345
> > > iptables -t nat -A OUTPUT -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-ports 12345
> > > ```
> > > 
> > > 
> > > openwrt的防火墙已经彻底关闭
> > > ```shell
> > > /etc/init.d/firewall disable
> > > /etc/init.d/firewall stop
> > > ```
> > 
> > 
> > 参考
> > https://www.right.com.cn/forum/thread-938058-1-1.html
> 
> 和我配置的差不多，原理也是一样，就是用dnsmasq-full将gfwlist的域名转到v2ray的5311的dns转发，然后用iptables将gfwlist的网站转到12345端口透明代理。
> 我的就是不行，我重置opewnrt，一步步安装他的弄一下看看行不行，比我多了一个iptables-mod-nat-extra，其他全部一样

等v2ray启动完成，用命令查看有没有解析ip
ipset list gfwlist

**Comment by herozzm** [comment]
> ipset list gfwlist
ipset list 看到gfwlist都有的，看日志得知iptables转发过来到v2ray是成功的



> OUTPUT 那条链的规则先去掉试试

都试了，不行

**Comment by herozzm** [comment]
> > > /etc/firewall.user
> > > ipset -N gfwlist iphash
> > > iptables -t nat -A PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 12345
> > > 有新建的ipset，代码是这样的
> > 
> > 
> > ```shell
> > ipset create gfwlist hash:ip
> > iptables -t nat -A PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-ports 12345
> > iptables -t nat -A OUTPUT -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-ports 12345
> > ```
> > 
> > 
> > openwrt的防火墙已经彻底关闭
> > ```shell
> > /etc/init.d/firewall disable
> > /etc/init.d/firewall stop
> > ```
> 
> 参考
> https://www.right.com.cn/forum/thread-938058-1-1.html

恩山这个很多步骤不全，比如dns转发到v2ray的5353端口，是我的哪个方法的简配版，我也严格按照他的这个弄了，行不通

**Comment by lfznnzq** [comment]
> > > > /etc/firewall.user
> > > > ipset -N gfwlist iphash
> > > > iptables -t nat -A PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 12345
> > > > 有新建的ipset，代码是这样的
> > > 
> > > 
> > > ```shell
> > > ipset create gfwlist hash:ip
> > > iptables -t nat -A PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-ports 12345
> > > iptables -t nat -A OUTPUT -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-ports 12345
> > > ```
> > > 
> > > 
> > > openwrt的防火墙已经彻底关闭
> > > ```shell
> > > /etc/init.d/firewall disable
> > > /etc/init.d/firewall stop
> > > ```
> > 
> > 
> > 参考
> > https://www.right.com.cn/forum/thread-938058-1-1.html
> 
> 恩山这个很多步骤不全，比如dns转发到v2ray的5353端口，是我的哪个方法的简配版，我也严格按照他的这个弄了，行不通

等v2ray启动完成，用命令查看有没有解析ip
ipset list gfwlist

**Comment by herozzm** [comment]
> ipset list gfwlist
有的解析到的，并已经转到了v2ray的端口进行代理，代理失败

[截图](https://i.loli.net/2019/09/28/OB7jCXZFcg9QPSk.png)

**Comment by lfznnzq** [comment]
> > ipset list gfwlist
> > 有的解析到的，并已经转到了v2ray的端口进行代理，代理失败
> 
> [截图](https://i.loli.net/2019/09/28/OB7jCXZFcg9QPSk.png)

安装组件
opkg install iptables-mod-nat-extra ip

检查/etc/firewall.user
ipset -N gfwlist iphash
iptables -t nat -A PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 1080

电脑的网卡要自动获取ip。

**Comment by herozzm** [comment]
> > > ipset list gfwlist
> > > 有的解析到的，并已经转到了v2ray的端口进行代理，代理失败
> > 
> > 
> > [截图](https://i.loli.net/2019/09/28/OB7jCXZFcg9QPSk.png)
> 
> v2ray透明代理去掉sniffing项，同时添加"listen": "0.0.0.0",
> 
> 安装组件
> opkg install iptables-mod-nat-extra ip
> 
> 检查/etc/firewall.user
> ipset -N gfwlist iphash
> iptables -t nat -A PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 12345
> 
> 电脑的网卡要自动获取ip。

搞定了，不是iptables的问题，而是config.json
这个问题用了我一个星期时间来测试，我用的是ipset黑名单模式，只有黑名单的才会使用v2ray，而透明代理中使用了
```json
 "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
```
提取域名去匹配规则，而我需要默认就走代理，没有写路由规则，导致出口失败，去掉这个规则即可

**Comment by herozzm** [comment]
> > > ipset list gfwlist
> > > 有的解析到的，并已经转到了v2ray的端口进行代理，代理失败
> > 
> > 
> > [截图](https://i.loli.net/2019/09/28/OB7jCXZFcg9QPSk.png)
> 
> v2ray透明代理去掉sniffing项，同时添加"listen": "0.0.0.0",
> 
> 安装组件
> opkg install iptables-mod-nat-extra ip
> 
> 检查/etc/firewall.user
> ipset -N gfwlist iphash
> iptables -t nat -A PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 12345
> 
> 电脑的网卡要自动获取ip。

多谢大神

**Comment by forever8938** [comment]
> > > > ipset list gfwlist
> > > > 有的解析到的，并已经转到了v2ray的端口进行代理，代理失败
> > > 
> > > 
> > > [截图](https://i.loli.net/2019/09/28/OB7jCXZFcg9QPSk.png)
> > 
> > 
> > v2ray透明代理去掉sniffing项，同时添加"listen": "0.0.0.0",
> > 安装组件
> > opkg install iptables-mod-nat-extra ip
> > 检查/etc/firewall.user
> > ipset -N gfwlist iphash
> > iptables -t nat -A PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 12345
> > 电脑的网卡要自动获取ip。
> 
> 搞定了，不是iptables的问题，而是config.json
> 这个问题用了我一个星期时间来测试，我用的是ipset黑名单模式，只有黑名单的才会使用v2ray，而透明代理中使用了
> 
> ```json
>  "sniffing": {
>         "enabled": true,
>         "destOverride": [
>           "http",
>           "tls"
>         ]
>       }
> ```
> 
> 提取域名去匹配规则，而我需要默认就走代理，没有写路由规则，导致出口失败，去掉这个规则即可

跟sniffing根本没关系，你只有一个出口，没规则就是默认走那个出口。sniffing能解决dns污染问题，即使你做了防污染，开启sniffing也可以使日志更直观，我一直都开着。

**Comment by forever8938** [comment]
你这个问题没有解决。如果你把所有tcp流量转发到12345，再写路由规则直连国内域名，你会发现有时候国内的网站打不开，特别是手机微信会刷不出来。
