### ISSUE TITLE
v2ray前置http代理

### ISSUE THREAD

**Issue by 370750149** [v2ray/v2ray-core#1908]
局域网内机器必须通过一个http代理服务才能访问外网,看过之前的sock前置代理解决方案,但是http代理不适用,怎么解决?像ss客户端是可以设置前置代理(正向代理)的.

**Comment by Yamazaki-wu** [comment]
@370750149 请问你在哪里看到的socks前置代理，我收集了几个公益节点都是ws+tls+web，官方文档说：出站代理配置。当出站代理生效时，此出站协议的streamSettings将不起作用
有没有办法解决啊？

**Comment by kslr** [comment]
你可以试试编译最新代码

**Comment by 370750149** [comment]
谢谢你的建议,我看新版代码是提供了前置http代理的
可是我缺少可以编译工作的环境,还是等你们发布新版了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kslr"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月8日(星期二) 晚上11:41
收件人:&nbsp;"v2ray/v2ray-core"<v2ray-core@noreply.github.com&gt;;
抄送:&nbsp;"Mr.罗"<370750149@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [v2ray/v2ray-core] v2ray前置http代理 (#1908)




你可以试试编译最新代码

**Comment by kxmp** [comment]
我也想知道前置s5怎么弄
