### ISSUE TITLE
希望v2ray能在动态端口启用时自动调整iptables规则

### ISSUE THREAD

**Issue by libfrozen** [v2ray/v2ray-core#1923]
Please describe the new feature you want in detail.
在iptables的INPUT链默认规则被设为DROP时，如果启用了动态端口，那么十几分钟后就无法继续科学上网了。希望新版本能解决这个问题。

**Comment by kslr** [comment]
你可以补充一些配置和日志吗

**Comment by rufengsuixing** [comment]
动态端口有ip段，既然想用动态，服务端就开放那个段的input

**Comment by libfrozen** [comment]
{
      "protocol": "vmess",
      "port": "10000-20000",
      "tag": "dynamicPort110daff",
      "settings": {
      "default": {
      "alterId": 64
      }
}

**Comment by libfrozen** [comment]
动态端口相关的配置
