### ISSUE TITLE
access.log中显示accepted了未知的IP地址

### ISSUE THREAD

**Issue by silencehunt** [v2ray/v2ray-core#1926]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
4.20
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
梅林路由器上刷入客户端，后面带所有设备。
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
access.log中显示accepted了未知的IP地址，该地址不是路由器的外网地址。但是又出现了对该IP地址的rejected操作，原因是：v2ray.com/core/proxy/vmess/encoding: invalid user
从access.log中可以看到，服务端先是用invalid user拒绝了该IP的连接，但是接着又接收了该IP的连接。
1.我的服务端的ID里分配了两个ID，分别是用在我的路由器上和给我朋友用。ID没有外泄，这是可以绝对保证的。
2.我觉得奇怪的是，为什么对同一个IP地址，会先由于用户名无效而拒绝它的连接，过一段时间又会接收它。
3.从access.log可以看到，该IP地址使用不同端口一直在尝试建立连接，但都由于invalid user而被拒绝。但是一旦服务端接受了该IP地址后，就会一直接收下去。
4) 你期待看到的正确表现是怎样的？
对未知的IP地址一律rejected
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
{
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": ***,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "###",
          "level": 1,
          "alterId": 64
        },
        {
          "id": "???",
          "level": 1,
          "alterId": 64
        }
      ]
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  }
}

```

客户端配置:

```javascript
    // 在这里附上客户端配置
{
	"log": {
		"access": "/dev/null",
		"error": "/tmp/v2ray_log.log",
		"loglevel": "error"
	},
	"inbound": {
		"port": 23456,
		"listen": "0.0.0.0",
		"protocol": "socks",
		"settings": {
			"auth": "noauth",
			"udp": true,
			"ip": "127.0.0.1",
			"clients": null
		},
		"streamSettings": null
	},
	"inboundDetour": [
		{
			"listen": "0.0.0.0",
			"port": 3333,
			"protocol": "dokodemo-door",
			"settings": {
				"network": "tcp,udp",
				"followRedirect": true
			}
		}
	],
	"outbound": {
		"tag": "agentout",
		"protocol": "vmess",
		"settings": {
			"vnext": [
				{
					"address": "***",
					"port": ***,
					"users": [
						{
							"id": "###",
							"alterId": 64,
							"security": "auto"
						}
					]
				}
			],
			"servers": null
		},
		"streamSettings": {
			"network": "tcp",
			"security": "",
			"tlsSettings": null,
			"tcpSettings": null,
			"kcpSettings": null,
			"wsSettings": null,
			"httpSettings": null
		},
		"mux": {
			"enabled": false,
			"concurrency": 8
		}
	}
}

```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
2019/10/05 11:45:01 219.143.154.64:53881 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/10/05 11:45:01 219.143.154.64:53882 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/10/05 11:45:11 219.143.154.64:53886 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/10/05 11:54:11 219.143.154.64:53972 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/10/05 11:55:01 219.143.154.64:53981 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/10/05 11:55:01 219.143.154.64:53982 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/10/05 11:55:11 219.143.154.64:53985 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/10/05 11:55:18 219.143.154.64:53989 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/10/05 12:05:01 219.143.154.64:54082 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/10/05 12:05:01 219.143.154.64:54081 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/10/05 12:05:12 219.143.154.64:54085 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/10/05 12:09:11 219.143.154.64:54126 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/10/05 12:15:01 219.143.154.64:54163 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/10/05 12:15:01 219.143.154.64:54164 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/10/05 12:15:12 219.143.154.64:54173 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/10/05 12:43:02 219.143.154.64:49757 accepted tcp:mobile.pipe.aria.microsoft.com:443 
2019/10/05 12:43:02 219.143.154.64:49756 accepted tcp:mobile.pipe.aria.microsoft.com:443 
2019/10/05 12:43:04 219.143.154.64:49770 accepted tcp:www.voachinese.com:443 
2019/10/05 12:43:04 219.143.154.64:49773 accepted tcp:tags.tiqcdn.com:443 
2019/10/05 12:43:04 219.143.154.64:49771 accepted tcp:accounts.google.com:443 
2019/10/05 12:43:04 219.143.154.64:49774 accepted tcp:www.youtube.com:443 
2019/10/05 12:43:04 219.143.154.64:49778 accepted tcp:www.voachinese.com:443 
2019/10/05 12:43:04 219.143.154.64:49782 accepted tcp:gdb.voanews.com:443 
2019/10/05 12:43:05 219.143.154.64:49787 accepted tcp:s.ytimg.com:443 
2019/10/05 12:43:05 219.143.154.64:49789 accepted tcp:dev.visualwebsiteoptimizer.com:443 
2019/10/05 12:43:05 219.143.154.64:49792 accepted tcp:voa-lh.akamaihd.net:443 
2019/10/05 12:43:05 219.143.154.64:49793 accepted tcp:voanews-vh.akamaihd.net:443 
2019/10/05 12:43:05 219.143.154.64:49798 accepted tcp:clients1.google.com:443 
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by kslr** [comment]
219.143.154.64:53881 是谁的

**Comment by silencehunt** [comment]
> 219.143.154.64:53881 是谁的

问题就在这儿，我也不知道这个IP是谁的。我的路由器是北京联通的线路，我朋友是歌华有线的线路。那个时间段里，路由器肯定是自动连在服务端上的。另外我确认过了，我朋友那个时间段没有去连服务端。所以也不知道这个IP地址是从哪儿来的，但是这个IP地址我查了一下，属于北京电信。

**Comment by silencehunt** [comment]
还有奇怪的现象，就在几分钟前，我把服务端上的ID都修改了，就是重新生成了一批UUID，而且还没告诉任何人。但是启动v2ray后，access.log里，还有这样的内容。
2019/10/06 08:25:29 182.138.214.93:49730 rejected  v2ray.com/core/proxy/vmess/encoding: duplicated session id, possibly under replay attack
2019/10/06 08:25:33 182.138.214.93:50282 rejected  v2ray.com/core/proxy/vmess/encoding: duplicated session id, possibly under replay attack
2019/10/06 08:25:33 123.157.193.134:57750 rejected  v2ray.com/core/proxy/vmess/encoding: duplicated session id, possibly under replay attack
2019/10/06 08:25:33 123.157.193.134:57833 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
我查了一下，这两个IP地址分别属于成都电信和杭州联通。请问出现duplicated session id大概会是什么原因？难道随机生成的UUID都有可以发生重复吗？

**Comment by kslr** [comment]
你的朋友是不是又分享给其他人了 最后成了公交车

**Comment by Cwek** [comment]
如果没办法的话，可以用fail2ban或者iptables来ban地址。

我的处理方法，对于保证不会出错的线路（例如中继线路），可以用fail2ban设严格的判断规则直接ban掉。

**Comment by silencehunt** [comment]
> 你的朋友是不是又分享给其他人了 最后成了公交车

不可能，就像我前面说的，我还没有告诉任何人，日志里就已经出现了duplicated session id。有什么办法能把重复的session id打印在日志文件里吗？起码能让我查一下重复的是哪一个啊。

**Comment by silencehunt** [comment]
今天继续观察日志，发现出现了不少的invalid user错误。请问错误里invalid user和duplicated session id分别有什么含义？到底哪个对应的是用户名错误？

**Comment by Cwek** [comment]
有可能是被扫端口 或者客户端的协议配置错误？

**Comment by forever8938** [comment]
明显是党在主动探测
