### ISSUE TITLE
Can somebody complie a version with PPC32 structure?

### ISSUE THREAD

**Issue by wuxeon** [v2ray/v2ray-core#1928]
My router model (Netgear WNDR 4700) ,its soc is apm821xx that build in ppc32 struture.
Can somebody complie a version with PPC32 structure?Thanks.

**Comment by Rucc1** [comment]
Please wait the implementation from Golang upstream.
Ref: https://github.com/golang/go/issues/22885

**Comment by wuxeon** [comment]
> 
> 
> Please wait the implementation from Golang upstream.
> Ref: [golang/go#22885](https://github.com/golang/go/issues/22885)
Thanks for your reply.
I am not a programmer and I am not good at Golang.

**Comment by barracuda156** [comment]
@Rucc1 Has anything happened since then re `ppc32`? I would like to add Darwin PPC support.
