### ISSUE TITLE
Need more encrypt methods of SS

### ISSUE THREAD

**Issue by ahdung** [v2ray/v2ray-core#1931]
like `rc4-md5`, thanks.

**Comment by kslr** [comment]
Welcome Pull Request

**Comment by encombhat** [comment]
Wouldn't recommend, rc4-md5 is not cryptographic secure.

**Comment by ahdung** [comment]
@encombhat But as a user, which encryption method is used is not something he can decide, if someone is using SS in rc4-md5 mode, then he has to continue using SS instead of v2ray. Support breadth determine the number of users.
