### ISSUE TITLE
请教linux如何共享给局域网中的手机

### ISSUE THREAD

**Issue by kktt007** [v2ray/v2ray-core#1935]
windows有开起选项的功能,尝试过可以用
现在是archlinux,然后想共享给局域网手机用,之前的配置是ssr+privoxy(监听系统http设置的8118端口)使用,现在想替换为v2ray,请教如何共享给局域网手机,

**Comment by rufengsuixing** [comment]
请使用带图形界面的客户端如v2rayng

**Comment by kktt007** [comment]
> v2rayng

v2rayNG是给安卓用的，别灌水

**Comment by hejikunhjk** [comment]
"inbounds": [
  "listen": "0.0.0.0",
  "protocol": "http",
  "port": 8118,
]

参考字段~~~~手机设http代理

**Comment by kktt007** [comment]
> "inbounds": [
> "listen": "0.0.0.0",
> "protocol": "http",
> "port": 8118,
> ]
> 
> 参考字段~~~~手机设http代理

我设了没用咩,为什么不行呢,目前是用privoxy监听.
首先windwos下只能在客户端中开启http,并且用socks+1的端口,直接改这个不行,还会恢复默认
其次在linux下设置过,发现还是不能用咩.
