### ISSUE TITLE
RoutingObject -> RuleObject 里面的属性配置希望可以增加非判断

### ISSUE THREAD

**Issue by lpyedge** [v2ray/v2ray-core#1943]
RoutingObject -> RuleObject 里面的属性配置希望可以增加非判断
例如我希望屏蔽某个网站
但是又想对某个用户单独开启
可以通过域名屏蔽访问
然后user属性是!userA
这样除了userA用户都无法访问这个域名了

**Comment by Sodium-Aluminate** [comment]
希望加入完整的逻辑算符（`和``或``异或``非`）以及运行别的文件（便于其他事情）的操作
