### ISSUE TITLE
配置成功  未找到v2ray-core,下载地址:https://github.com/v2ray/v2ray-core/releases

### ISSUE THREAD

**Issue by nachotju** [v2ray/v2ray-core#1946]
Please read the [instruction](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md) and answer the following questions before submitting your issue. Thank you.
Please answer all the questions with enough information. All issues not following this template will be closed immediately.
If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2ray/discussion/issues) first.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)

4) What's your expectation?

5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

Server configuration:

```javascript
    // Please attach your server configuration here.
```

Client configuration:

```javascript
    // Please attach your client configuration here.
```

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.

Server error log:

```javascript
    // Please attach your server error log here.
```

Client error log:

```javascript
    // Please attach your client error log here.
```

7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.

```javascript
    // Please attach your server access log here.
```

8) Other configurations (such as Nginx) and logs.

9) If V2Ray doesn't run, please attach output from `--test`.

The command is usually `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`, but may vary according to your scenario.

10) If V2Ray service doesn't run, please attach journal log.

Usual command is `journalctl -u v2ray`.

Please review your issue before submitting.

**Comment by Cangol** [comment]
me too

**Comment by Daymake** [comment]
我也是这样的提示

**Comment by Jasonandy** [comment]
me too in win7 x64

**Comment by T-01** [comment]
若你下载的 v2rayN 出现了以下提示

启动服务(2021/6/10 11:51:15)...
找不到Core，下载地址: https://github.com/v2fly/v2ray-core/releases

则说明你没有安装 v2ray-core（核心）因为 V2Ray Windows 客户端主要有两个，一个是 v2ray-core（v2ray 核心，官方客户端），另一个是 v2rayN（基于 v2ray-core 的开一个 GUI 可视化客户端），其中 v2ray-core 可以单独使用，而 v2rayN 则是基于 v2ray-core 的一个辅助可视化工具。
解决方法：
你需要打开 https://github.com/v2ray/v2ray-core/releases 下载你对应的 v2ray-core，然后把 V2Ray-core zip 包里面的东西移动到 V2rayN 的文件夹里，或者将 v2rayN 里的 v2rayN.exe 拖入到 V2Ray-core 文件夹内
然而最简单的办法则是直接下载 V2rayN 完整版（选择 v2rayN-Core.zip）：
https://github.com/2dust/v2rayN/releases/latest

**Comment by nachotju** [comment]
您好，lyx已收到邮件。
