### ISSUE TITLE
建立连接的问题

### ISSUE THREAD

**Issue by kathylincn** [v2ray/v2ray-core#195]
默认只设个监听端口就行了,我想问的是,这样只设监听端口,不设监听IP的话.是不是本机所有的IP都可以连?
还有,支持IPV6连接吗?本机有IPV6的情况下,这样设置的监听对IPV6有效没有.

**Comment by v2ray** [comment]
* 不指定 IP 的话，默认监听 0.0.0.0，即本机所有 IP
* 支持的，在不指定 IP 的情况下，监听的时候会同时监听 v6 和 v4 的 IP，发送数据的时候会优先选择 v6 地址。
