### ISSUE TITLE
架构名称错误

### ISSUE THREAD

**Issue by azgh** [v2ray/v2ray-core#1953]
硬件规格：小米路由3G

操作系统：OpenWrt 18.06.4

执行操作：`bash <(curl -L -s https://install.direct/go.sh)`

发现问题：
1. 当硬件架构为：mipsel_24kc 时；
![截屏2019-10-18下午1 08 22](https://user-images.githubusercontent.com/11712776/67067378-b9789d00-f1a8-11e9-91ee-b7c6504b4077.png)
2. 脚本执行检测架构时，将架构错误识别为mips，而不是正确的mipsel。
![截屏2019-10-18下午1 06 06](https://user-images.githubusercontent.com/11712776/67067389-c4333200-f1a8-11e9-98e6-10fef43bd463.png)

原因分析：
**脚本架构里，mipsel被错误的写成mipsle**，在运行时，无法识别mipsel，而错误的识别为mips，导致自动安装脚本下载并安装了错误的包。

请核实，谢谢。

**Comment by kslr** [comment]
尝试执行一下lscpu呢

azgh <notifications@github.com> 於 2019年10月18日週五 下午12:58寫道：

**Comment by azgh** [comment]
@kslr ，分别`uname -m`和`cat /proc/cpuinfo |grep 'cpu model'`，如下：

```
root@OpenWrt:~# uname -m
mips
root@OpenWrt:~# cat /proc/cpuinfo |grep 'cpu model'
cpu model		: MIPS 1004Kc V2.15
```

但是进入系统，默认的源为：

```
src/gz openwrt_core https://downloads.openwrt.org/releases/18.06.4/targets/ramips/mt7621/packages
src/gz openwrt_kmods https://downloads.openwrt.org/releases/18.06.4/targets/ramips/mt7621/kmods/4.14.131-1-94e97c3b21ec52cb72cec4eaff828985
src/gz openwrt_base https://downloads.openwrt.org/releases/18.06.4/packages/mipsel_24kc/base
src/gz openwrt_luci https://downloads.openwrt.org/releases/18.06.4/packages/mipsel_24kc/luci
src/gz openwrt_packages https://downloads.openwrt.org/releases/18.06.4/packages/mipsel_24kc/packages
src/gz openwrt_routing https://downloads.openwrt.org/releases/18.06.4/packages/mipsel_24kc/routing
src/gz openwrt_telephony https://downloads.openwrt.org/releases/18.06.4/packages/mipsel_24kc/telephony
```

有些迷惑了。

**Comment by azgh** [comment]
@kslr ，运行`opkg print-architecture`得到：
```
root@OpenWrt:~# opkg print-architecture | awk '{print $2}'
all
noarch
mipsel_24kc
```
到底该用哪个更糊涂了。

**Comment by kslr** [comment]
你先手动尝试用那个版本文件可以增常工作

**Comment by lfznnzq** [comment]
openwrt系统不能用脚本安装

**Comment by azgh** [comment]
@lfznnzq 小米路由试了几次都没成功，不知道x86架构是否相对容易？

**Comment by taxtigerno1** [comment]
我的歌华链路由是mt7621,cupinfo显示是mips 1004kc，但是open print却是mipsel1004kc，但是好像选项上都没1004kc可以选择，试过编译成mips和mipsel安装都是启动出错，

![Image](https://github.com/user-attachments/assets/024f8f09-535d-4baa-9564-9a2bc9ba712e)

怎么办？
