### ISSUE TITLE
建议增加 rtsp 协议伪装

### ISSUE THREAD

**Issue by zwc456baby** [v2ray/v2ray-core#1959]
似乎没有在哪里看到采用 rtsp 协议伪装的功能建议
先贴一段百度百科的描述

> HTTP与RTSP相比，HTTP请求由客户机发出，服务器作出响应；使用RTSP时，客户机和服务器都可以发出请求，即RTSP可以是双向的。RTSP是用来控制声音或影像的多媒体串流协议，并允许同时多个串流需求控制，传输时所用的网络通讯协定并不在其定义的范围内，服务器端可以自行选择使用TCP或UDP来传送串流内容，它的语法和运作跟HTTP 1.1类似

优点
- rtsp 基于 tcp 或 udp 
- 作为视屏流协议，更适合大流量传输时的伪装。

**Comment by changyp6** [comment]
RTSP是多媒体传输控制协议，本身就没流量，最多就是DESCRIBE, SETUP, PLAY, TEARDOWN, GET PARAMETER这几个控制命令。

如果要伪装，最多是伪装成RTP的数据流。
RTP的打包，就是RTP包头 + Payload
不同的数据的Payload有固定格式，而且，RTP的包是基于UDP的，如果要用TCP传RTP的包，当然也可以，但是效率低下。
防火墙识别RTP的数据包，非常方便，很有可能，公司的防火墙，就会直接把RTP的包drop掉。

伪装成RTP，那意思就是告诉防火墙 “墙！请丢掉我吧！”
