### ISSUE TITLE
能否添加shadowsocksR支持？

### ISSUE THREAD

**Issue by q623928815** [v2ray/v2ray-core#196]
如题，貌似SSR的翻墙被查几率更低，伪装了TCP头

**Comment by v2ray** [comment]
暂时不考虑没有完整文档的协议，SSR 的文档中没有对于协议头部的清楚的描述，类似 [SS 官方文档这样的](https://shadowsocks.org/en/spec/protocol.html)。

没有文档的话，第三方开发者很难知道什么时候协议会变化，并且没有判断实现的正确性的标准。

**Comment by darklx** [comment]
还是很期待这个功能！

**Comment by 1354092549** [comment]
再次提议支持该功能

**Comment by Cwek** [comment]
如果主要的SSR服务端开发主能整理出一份统一的协议说明的话，或者可行，否则白期待。

**Comment by 1354092549** [comment]
首先SSR已经放弃了（但在可预见的将来仍可能继续被大规模使用，某些验证特性对多租户平台极其友好）
另外参照源码实现应该问题不大
整个社区都是以C#版SSR源码即规范的方式实现的第三方SSR客户端

**Comment by AlleriaWindy** [comment]
我也提议支持该功能

**Comment by 0x0004** [comment]
跪求支持ssr
