### ISSUE TITLE
v2ray运行一个星期左右，内存占用过大，一直不释放。（附pprof内存图）

### ISSUE THREAD

**Issue by ansoda** [v2ray/v2ray-core#1961]
![image](https://user-images.githubusercontent.com/5748600/67491835-104e0d00-f6a8-11e9-8373-1b93a63495ec.png)

**Comment by Kylejustknows** [comment]
你的编译或者系统有问题了吧? 我的也持续开启了一两个月了, 刚刚看了下使用内存不到10MB... 你这好家伙吃了快1GB内存了. 

因为别人都没有你这情况, v2ray代码自身有问题的可能性很小, 请仔细检查检查系统.

**Comment by ansoda** [comment]
我用的是github官方编译的好amd64 linux版本，我把连接的bufferSize改为1024KB再等段时间看看。

**Comment by ansoda** [comment]
{
	  "inbounds": [
		{
		  "port": 53,
		  "tag": "dns-in",
		  "protocol": "dokodemo-door",
		  "settings": {
			"address": "1.1.1.1",
			"port": 53,
			"network": "tcp,udp"
		  }
		},
		{
		  "port": 1080,
		  "protocol": "socks",
		  "settings": {
			"udp": true
		  },
		  "sniffing": {
			"enabled": false,
			"destOverride": [
			  "http",
			  "tls"
			]
		  }
		},
		{
		  "port": 1081,
		  "protocol": "shadowsocks",
		  "settings": {
			"method": "aes-256-cfb",
			"password": "xxxxxxxx",
			"network": "tcp,udp"
		  }
		}
	  ],
	  "outbounds": [
		{
		  "protocol": "vmess",
		  "tag": "proxy",
		  "settings": {
			"vnext": [
			  {
				"address": "xx.xx.xx.xx",
				"port": 13000,
				"users": [
				  {
					"id": "168fb91d-b3f4-d4ca-76f5-9fd870658e09",
					"alterId": 4,
					"security": "auto",
					"level": 0
				  }
				]
			  },
			  {
				"address": "xx.xx.xx.xx",
				"port": 13000,
				"users": [
				  {
					"id": "168fb91d-b3f4-d4ca-76f5-9fd870658e09",
					"alterId": 4,
					"security": "auto",
					"level": 0
				  }
				]
			  },
			  {
				"address": "xx.xx.xx.xx",
				"port": 13000,
				"users": [
				  {
					"id": "168fb91d-b3f4-d4ca-76f5-9fd870658e09",
					"alterId": 4,
					"security": "auto",
					"level": 0
				  }
				]
			  }
			]
		  },
		  "streamSettings": {
			"network": "tcp"
		  },
		  "mux": {
			"enabled": true,
			"concurrency": 8
		  }
		},
		{
		  "protocol": "freedom",
		  "tag": "direct",
		  "settings": {}
		},
		{
		  "protocol": "dns",
		  "tag": "dns-out"
		}
	  ],
	  "routing": {
		"domainStrategy": "AsIs",
		"rules": [
		  {
			"type": "field",
			"inboundTag": [
			  "dns-in"
			],
			"outboundTag": "dns-out"
		  },
		  {
			"type": "field",
			"ip": [
			  "1.1.1.1",
			  "8.8.8.8"
			],
			"outboundTag": "proxy"
		  },
		  {
			"type": "field",
			"ip": [
			  "114.114.114.114",
			  "223.5.5.5"
			],
			"outboundTag": "direct"
		  },
		  {
			"type": "field",
			"outboundTag": "direct",
			"domain": [
			  "geosite:cn"
			]
		  },
		  {
			"type": "field",
			"outboundTag": "direct",
			"ip": [
			  "geoip:private",
			  "geoip:cn",
			  "172.17.0.0/16"
			]
		  }
		]
	  },
	  "dns": {
		"hosts": {},
		"servers": [
		  "1.1.1.1",
		  "8.8.8.8",
		  {
			"address": "114.114.114.114",
			"port": 53,
			"domains": [
			  "geosite:cn"
			]
		  }
		],
		"clientIp": "xx.xx.xx.xx",
		"tag": "dns_inbound"
	  },
	  "log": {
		"access": "access.log",
		"error": "error.log",
		"loglevel": "warning"
	  },
	  "policy": {
		"levels": {
		  "0": {
			"handshake": 4,
			"connIdle": 300,
			"uplinkOnly": 2,
			"downlinkOnly": 5,
			"statsUserUplink": false,
			"statsUserDownlink": false,
			"bufferSize": 1024
		  }
		},
		"system": {
		  "statsInboundUplink": false,
		  "statsInboundDownlink": false
		}
	  }
	}

**Comment by ansoda** [comment]
![image](https://user-images.githubusercontent.com/5748600/67870261-84395b00-fb69-11e9-80c1-bca9b2872741.png)

**Comment by ansoda** [comment]
我用的是github上面的官方编译的v2ray-linux-64.zip，V2Ray 4.20.0版本。

**Comment by ansoda** [comment]
[memory.pdf](https://github.com/v2ray/v2ray-core/files/3793279/memory.pdf)

**Comment by cnsilvan** [comment]
我也发现这个问题了，老版本以前没发现这个问题。

**Comment by Losalado** [comment]
问题有解决吗 我也遇到同样的情况

**Comment by jackyicu** [comment]
我的也是, 快占用1G内存了, 楼上的有解决方案吗? 谢谢.

**Comment by Losalado** [comment]
> 我的也是, 快占用1G内存了, 楼上的有解决方案吗? 谢谢.

我感觉是iptables和dokodemo door之间的问题 我有看到很多的回环流量 触发时间不能确定 最后会导致内存占用过高 cpu的占有率也有问题 我查了很多的iptables的设置 不能找出问题在哪里

**Comment by Kylejustknows** [comment]
因为这个问题很特，有这个问题的朋友，能不能把系统情况汇报一下啊，用的什么操作系统；v2ray用了哪些比较独特的设置；

**Comment by Losalado** [comment]
> > 我的也是, 快占用1G内存了, 楼上的有解决方案吗? 谢谢.
> 
> 我感觉是iptables和dokodemo door之间的问题 我有看到很多的回环流量 触发时间不能确定 最后会导致内存占用过高 cpu的占有率也有问题 我查了很多的iptables的设置 不能找出问题在哪里

这里提供一个可能的解决方法，在透明代理的的入站协议中（socks或者dokodemo）不启用udp，我这边好像已经没有问题了。

**Comment by shangming-wang** [comment]
我也遇到这个问题，运行一段时间buff/cache使用很多。
![image](https://user-images.githubusercontent.com/33543682/75168090-4d630280-5761-11ea-912e-829e1dd441c6.png)
![image](https://user-images.githubusercontent.com/33543682/75168187-6f5c8500-5761-11ea-82d0-25c4ec498247.png)

**Comment by qiangliu8183** [comment]
iptables的问题

**Comment by jackyicu** [comment]
> > > 我的也是, 快占用1G内存了, 楼上的有解决方案吗? 谢谢.
> > 
> > 
> > 我感觉是iptables和dokodemo door之间的问题 我有看到很多的回环流量 触发时间不能确定 最后会导致内存占用过高 cpu的占有率也有问题 我查了很多的iptables的设置 不能找出问题在哪里
> 
> 这里提供一个可能的解决方法，在透明代理的的入站协议中（socks或者dokodemo）不启用udp，我这边好像已经没有问题了。

这样的话dns岂不是得用另外的方案了?

**Comment by Losalado** [comment]
> > > > 我的也是, 快占用1G内存了, 楼上的有解决方案吗? 谢谢.
> 
> > > 
> 
> > > 
> 
> > > 我感觉是iptables和dokodemo door之间的问题 我有看到很多的回环流量 触发时间不能确定 最后会导致内存占用过高 cpu的占有率也有问题 我查了很多的iptables的设置 不能找出问题在哪里
> 
> > 
> 
> > 这里提供一个可能的解决方法，在透明代理的的入站协议中（socks或者dokodemo）不启用udp，我这边好像已经没有问题了。
> 
> 
> 
> 这样的话dns岂不是得用另外的方案了?

dns我也有用是没有问题的，我这里不是所有的udp都有问题，只是dokodemo和iptables配合的udp数据会有问题

**Comment by HaoweiCh** [comment]
补充一个线索。最近在玩 warzone。ss chacha20 走得 udp

我专门开显示器看内存。玩一把游戏玩着玩着 cpu 负载就100%了，阿里云的小鸡

有道友给个思路？

**Comment by deorth-boffin** [comment]
再补充一个信息，我使用amd64官方编译版也有这个问题，arm64官方编译版则没有。。

**Comment by zhangbo-miuNEST** [comment]
AC88U，官方梅林，自己编译的v2ray，发现top显示v2ray进程的VSZ是790m，%VSZ是156.9。

```
{
  "policy": {
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true
    }
  },
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "proxy",
      "port": 8080,
      "listen": "192.168.2.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "address": null,
        "clients": null
      },
      "streamSettings": null
    },
    {
      "tag": "api",
      "port": 1105,
      "listen": "127.0.0.1",
      "protocol": "dokodemo-door",
      "sniffing": null,
      "settings": {
        "auth": null,
        "udp": false,
        "ip": null,
        "address": "127.0.0.1",
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "xxx.com",
            "port": 443,
            "users": [
              {
                "id": "yyyy",
                "alterId": 233,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "allowInsecureCiphers": false,
          "serverName": "xxx.com"
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/xxxyyy",
          "headers": {
            "Host": "xxx.com"
          }
        },
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "stats": {},
  "api": {
    "tag": "api",
    "services": [
      "StatsService"
    ]
  },
  "dns": null,
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "port": null,
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "ip": null,
        "domain": null
      }
    ]
  }
}
```

**Comment by HaoweiCh** [comment]
> AC88U，官方梅林，自己编译的v2ray，发现top显示v2ray进程的VSZ是790m，%VSZ是156.9。
> 路由器对外是ws + tls连接，对内是http、socks。
> 
> ```
> {
>   "policy": {
>     "system": {
>       "statsInboundUplink": true,
>       "statsInboundDownlink": true
>     }
>   },
>   "log": {
>     "access": "",
>     "error": "",
>     "loglevel": "warning"
>   },
>   "inbounds": [
>     {
>       "tag": "proxy",
>       "port": 8080,
>       "listen": "192.168.2.1",
>       "protocol": "socks",
>       "sniffing": {
>         "enabled": true,
>         "destOverride": [
>           "http",
>           "tls"
>         ]
>       },
>       "settings": {
>         "auth": "noauth",
>         "udp": true,
>         "ip": null,
>         "address": null,
>         "clients": null
>       },
>       "streamSettings": null
>     },
>     {
>       "tag": "api",
>       "port": 1105,
>       "listen": "127.0.0.1",
>       "protocol": "dokodemo-door",
>       "sniffing": null,
>       "settings": {
>         "auth": null,
>         "udp": false,
>         "ip": null,
>         "address": "127.0.0.1",
>         "clients": null
>       },
>       "streamSettings": null
>     }
>   ],
>   "outbounds": [
>     {
>       "tag": "proxy",
>       "protocol": "vmess",
>       "settings": {
>         "vnext": [
>           {
>             "address": "xxx.com",
>             "port": 443,
>             "users": [
>               {
>                 "id": "yyyy",
>                 "alterId": 233,
>                 "email": "t@t.tt",
>                 "security": "auto"
>               }
>             ]
>           }
>         ],
>         "servers": null,
>         "response": null
>       },
>       "streamSettings": {
>         "network": "ws",
>         "security": "tls",
>         "tlsSettings": {
>           "allowInsecure": false,
>           "allowInsecureCiphers": false,
>           "serverName": "xxx.com"
>         },
>         "tcpSettings": null,
>         "kcpSettings": null,
>         "wsSettings": {
>           "connectionReuse": true,
>           "path": "/xxxyyy",
>           "headers": {
>             "Host": "xxx.com"
>           }
>         },
>         "httpSettings": null,
>         "quicSettings": null
>       },
>       "mux": {
>         "enabled": true,
>         "concurrency": 8
>       }
>     },
>     {
>       "tag": "direct",
>       "protocol": "freedom",
>       "settings": {
>         "vnext": null,
>         "servers": null,
>         "response": null
>       },
>       "streamSettings": null,
>       "mux": null
>     },
>     {
>       "tag": "block",
>       "protocol": "blackhole",
>       "settings": {
>         "vnext": null,
>         "servers": null,
>         "response": {
>           "type": "http"
>         }
>       },
>       "streamSettings": null,
>       "mux": null
>     }
>   ],
>   "stats": {},
>   "api": {
>     "tag": "api",
>     "services": [
>       "StatsService"
>     ]
>   },
>   "dns": null,
>   "routing": {
>     "domainStrategy": "IPIfNonMatch",
>     "rules": [
>       {
>         "type": "field",
>         "port": null,
>         "inboundTag": [
>           "api"
>         ],
>         "outboundTag": "api",
>         "ip": null,
>         "domain": null
>       }
>     ]
>   }
> }
> ```

内存，虚拟内存占比高是正常的。，你有外接usb 然后搞虚拟内存吗？

**Comment by gd4Ark** [comment]
安装脚本迁移到 https://github.com/v2fly/fhs-install-v2ray 后，我也遇到了这个问题，最终采用 docker 部署解决。

**Comment by gd4Ark** [comment]
安装脚本迁移到  https://github.com/v2fly/fhs-install-v2ray 后，我也遇到这个问题了

**Comment by gd4Ark** [comment]
编译安装 v4.26.0 没有这个问题

**Comment by stevehsu77** [comment]
遇到同样问题，用4.26就不会有问题吗？

**Comment by gd4Ark** [comment]
> 遇到同样问题，用4.26就不会有问题吗？

运行几天后又出现该问题，重启服务能暂时缓解

**Comment by zhangbo-miuNEST** [comment]
> 
> 内存，虚拟内存占比高是正常的。，你有外接usb 然后搞虚拟内存吗？

对，我外接USB大硬盘，装的entware。
