### ISSUE TITLE
建议添加个限制mux并发未使用完 新建连接的配置

### ISSUE THREAD

**Issue by k79e** [v2ray/v2ray-core#1963]
开多路复用的时候 有时候连接数没用满 程序就又新建了新的连接.(连接数配置多大都没用 估计是网络卡了还是怎么了他就新建连接了)
能否加个设置让他不新建连接 如果网络卡了就用当前这个连接数重试不就行了
一句话: 一个tcp连接上的mux承载数量没有用完的时候 程序就又新建了其他tcp连接 目前缺乏配置来限制这个行为

h2虽然没那问题但是有时候条件限制 不方便使用那个模式...

**Comment by Kylejustknows** [comment]
多数用户都要求流畅性, 更别说有些用v2ray做代理加速游戏的, 都希望自己的数据包尽快在1毫秒内被转发出去, 最最最怕的就是某一条快递线路卡顿导致一串包裹被延迟. 所以代码里的逻辑应该是, 发现有点不通畅就尽快新建连接, 不犹豫. 

如果像你说的, 比较严格地限制新连接(旧的没用完, 就不准建立新的), 那么一但某条"旧的链接"真的出了问题(访问国外各种不稳定很常见), 那就是所有程序的数据包卡住等待, 然后你又不准人家建立新连接, 那么你说吧等待多少秒后你才允许v2ray "正式地"放弃旧的连接, 3秒? 5秒? 这样的设置, 对网络本来就不是很稳定的用户来说是个灾难.

你说可以设个选项开关这个设置, 但你的这个要求真的太小众了, 而且我也真的看不出它的实际用处是什么(你公司网络对tpc握手数量有限制?)

**Comment by kxmp** [comment]
网络卡了跟连接没有什么大关系吧 真卡了建立再多连接不也照样卡
从已经存在的连接发送数据反而速度更快好吧 新建连接要有握手时间 老连接不需要.

而且你还提到快慢线路 你这v2是接了多少个服务器 还会自动换 太高端了吧.
你的回复根本就是文不对题 你感觉我所说很无理别理我就行 打这么多字还转移话题有什么意义.

**Comment by Kylejustknows** [comment]
>你的回复根本就是文不对题 你感觉我所说很无理别理我就行 打这么多字还转移话题有什么意义.

我可能是这里不多的, 真的看懂了你想表达的是什么的人. 因为我个人曾经花了大量时间研究mux代码和机制.

我说的是: 你的提议, 会导致一个连接卡住时, 整个网络所有软件都卡住 (因为你要求每个握手的最大连接数没用完, 就不准建立新连接), 然后出现这情况, 就必须建立一个超时机制, 在几秒钟无反应后才允许放弃那个握手连接. (我没说什么快慢线路啊?  我也没说什么服务器自动换啊? 你这几句话是哪里来的?)

> "网络卡了跟连接没有什么大关系吧 真卡了建立再多连接不也照样卡"

并不是这样的. 出国网络在国内很多地区非常不稳定, 连接不断地丢包卡死, 但是新连接又能成功握手, 某连接过一会被卡住(可能是防火墙干扰, 也可能是出口带宽不够丢包, 也可能是电信局的跨国QoS等等原因), 但是重新握手又能连上, 
这事真的很常见!! 甚至V2Ray的mkcp连接方式还就真的是专为这样的垃圾网络的用户设计的, 通过不断的连接, 轰炸一般地不停地发包, 使对海外连接不稳定的用户也能比较流畅地上网. 

我唯一的问题是(纯好奇), 你不想让v2ray主动创建新连接的原因是什么啊, 能给你的网络带来什么好处吗? 拿出来说说呗, 也许对v2ray将来的开发方向有启示.

**Comment by kxmp** [comment]
你自己说的啊

> "最最最怕的就是某一条**快递线路**卡顿导致一串包裹被延迟"

**Comment by kxmp** [comment]
目前网络已经卡了
观察到是老连接速度卡. 然后我打开b网站 b网站是当初容易卡的. 我发现竟然不卡. 这时候他果然是新建了一个连接. 因为卡的时候我看只有1个连接.

这时候我凡夫测卡的网站 测了几次发现决定是卡无疑 一次都没快过
于是我做了包级丢包检测 检测的就是卡了的这个的全程数据包. 一次就够了吧 因为每次都卡 再怎么测也都那样.

问题就显露出来.  丢包是0.

**Comment by kxmp** [comment]
开眼见了
同一个本地端口 就是同一个mux的tcp连接
竟然分化出来了速度快和速度慢. 还是用的和当初测试一样的资源 资源a是a网站 资源b是b网站
2个域名不一样. 这决定不是网络波动.......
出现慢的情况我立刻测试另一个资源 他是全速的
况且我又做了包级检测 根本就是0丢包么. 来回测了好几次都是... 慢的快的都是0丢包

**Comment by wenzhuning** [comment]
> 开多路复用的时候 有时候连接数没用满 程序就又新建了新的连接.(连接数配置多大都没用 估计是网络卡了还是怎么了他就新建连接了) 能否加个设置让他不新建连接 如果网络卡了就用当前这个连接数重试不就行了 一句话: 一个tcp连接上的mux承载数量没有用完的时候 程序就又新建了其他tcp连接 目前缺乏配置来限制这个行为
> 
> h2虽然没那问题但是有时候条件限制 不方便使用那个模式...

你可能没理解，mux子连接不是并发请求的，如果其中一条子连接卡住，那么后面的子连接请求就不能处理，如果按照你的要去，那么就会导致断网

**Comment by wenzhuning** [comment]
> 多数用户都要求流畅性, 更别说有些用v2ray做代理加速游戏的, 都希望自己的数据包尽快在1毫秒内被转发出去, 最最最怕的就是某一条快递线路卡顿导致一串包裹被延迟. 所以代码里的逻辑应该是, 发现有点不通畅就尽快新建连接, 不犹豫.
> 
> 如果像你说的, 比较严格地限制新连接(旧的没用完, 就不准建立新的), 那么一但某条"旧的链接"真的出了问题(访问国外各种不稳定很常见), 那就是所有程序的数据包卡住等待, 然后你又不准人家建立新连接, 那么你说吧等待多少秒后你才允许v2ray "正式地"放弃旧的连接, 3秒? 5秒? 这样的设置, 对网络本来就不是很稳定的用户来说是个灾难.
> 
> 你说可以设个选项开关这个设置, 但你的这个要求真的太小众了, 而且我也真的看不出它的实际用处是什么(你公司网络对tpc握手数量有限制?)

mux这个问题在线路差的情况下是致命的，子连接如果能并发请求，互不干扰，那就不会有阻塞这个问题了，一直希望有大佬能解决这个问题，但是貌似不受重视
