### ISSUE TITLE
不同等级不同路由规则

### ISSUE THREAD

**Issue by imrbg** [v2ray/v2ray-core#1967]
目前的配置中是否可以对不同level的email设置不同routing？
是否可以通过tag实现？
简单搜了下没有找到相关文档

**Comment by kslr** [comment]
你可以分配不同的账户

**Comment by fuyinhua** [comment]
请问原来的那 作者哪去了，不开发了吗？

**Comment by fuyinhua** [comment]
好像只开发到4.18.0

**Comment by imrbg** [comment]
没有理解不同的账户指什么
我的意思是多个routing object 不同的email采用不一样的规则
比如一部分email或者tag可以访问xxx.com
另一部分不行

> 你可以分配不同的账户

**Comment by kslr** [comment]
不能，必须通过Inbound

**Comment by ToutyRater** [comment]
```
{
  "type": "field",
  "domain": [
    "domain:qq.com"
  ],
  "user": [
    "user1@mail.com",
    "user2@mail.com"
  ],
  "outboundTag": "direct"
},
{
  "type": "field",
  "domain": [
    "domain:qq.com"
  ],
  "user": [
    "user3@mail.com"
  ],
  "outboundTag": "block"
}
```
根据 level 无法实现，因为路由没有关于 level 的匹配项。根据 email 是可以的，像这样的规则，user1@mail.com 和 user2@mail.com 可以连 qq.com，user3@mail.com 则不行。
手册有特别说明，**当多个属性同时指定时，这些属性需要同时满足，才可以使当前规则生效。**

**Comment by imrbg** [comment]
非常感谢，测试成功
