### ISSUE TITLE
[Warning]VMessOut: Failed to read response: EOF

### ISSUE THREAD

**Issue by wenjinlibug** [v2ray/v2ray-core#197]
kcp经常出现这种错误

V2Ray v1.18.2 (New Order) 20160704
An unified platform for anti-censorship.
2016/07/06 16:59:31 [Warning]Point: started on port 1180
2016/07/06 17:01:11 [Warning]VMessOut: Failed to read response: EOF
2016/07/06 17:02:55 [Warning]VMessOut: Failed to read response: EOF
2016/07/06 17:03:16 [Warning]VMessOut: Failed to read response: EOF
2016/07/06 17:03:25 [Warning]VMessOut: Failed to read response: EOF
2016/07/06 17:03:35 [Warning]VMessOut: Failed to read response: EOF
2016/07/06 17:03:37 [Warning]VMessOut: Failed to read response: EOF

**Comment by testcaoy7** [comment]
遭受干扰所致，我也遇到过这个问题，更换UUID后恢复，生成新的ID：https://www.uuidgenerator.net/

**Comment by wenjinlibug** [comment]
@testcaoy7 
换了uuid也一样。

**Comment by tlze** [comment]
我的同样故障，关了kcp，开tcp就好了。

**Comment by wenjinlibug** [comment]
@tlze 
开TCP后就一直这样

V2Ray v1.18.2 (New Order) 20160704
An unified platform for anti-censorship.
2016/07/10 22:41:07 [Warning]Point: started on port 1180
2016/07/10 22:42:27 [Warning]Socks: Unknown protocol version 67
2016/07/10 22:42:27 [Warning]Socks: failed to read authentication: Invalid protocol version.
2016/07/10 22:42:27 [Warning]Socks: Unknown protocol version 71
2016/07/10 22:42:27 [Warning]Socks: failed to read authentication: Invalid protocol version.

**Comment by v2ray** [comment]
@wenjinlibug 你用 HTTP 代理客户端连接了 socks

**Comment by wenjinlibug** [comment]
@v2ray 
把端口改了重设代理还是一样。

V2Ray v1.18.2 (New Order) 20160704
An unified platform for anti-censorship.
2016/07/11 14:38:44 [Warning]Point: started on port 1181
2016/07/11 15:25:23 [Warning]Socks: Unknown protocol version 67
2016/07/11 15:25:23 [Warning]Socks: failed to read authentication: Invalid protocol version.
2016/07/11 15:25:23 [Warning]Socks: Unknown protocol version 71
2016/07/11 15:25:23 [Warning]Socks: failed to read authentication: Invalid protocol version.

**Comment by testcaoy7** [comment]
@wenjinlibug 确保你的客户端使用SOCKS5

**Comment by wenjinlibug** [comment]
@v2ray 
为了确保是用SOCK5协议，我特意将端口改了，这样就不会出现未知的软件设置错误。
所以我确定是使用SOCK5没错。

**Comment by wenjinlibug** [comment]
@testcaoy7 @v2ray 
OK,又排查了一次，是EagleGet的代理配置问题。
不知道他们怎么想的，配置里sock代理不是sock5就算了、却硬是要写成“socks”代理。

改掉以后似乎KCP也没问题了，目前一切正常。之前所有错误都是这东西惹的祸。

**Comment by aflyhorse** [comment]
偶尔会刷一波这样的错误
Failed to read authentication: Invalid protocol version.
Socks: Unknown protocol version 71
确认使用的是socks5代理（因为是偶然现象，通常过一会就会好

**Comment by v2ray** [comment]
2.8 修复了 kcp 大量并发连接下不正常的问题。
