### ISSUE TITLE
armv6 binary release was built with wrong toolchain

### ISSUE THREAD

**Issue by nvksie** [v2ray/v2ray-core#1977]
1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
v4.21.2

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
run v2ray on raspberrypi model b+

3) Please attach full panic log.

pi@raspberrypi:/tmp/xxx $ md5sum v2ray v2ray_armv7
5686bb79d6c9cf5761aab8095f813379  v2ray
5686bb79d6c9cf5761aab8095f813379  v2ray_armv7
pi@raspberrypi:/tmp/xxx $ ./v2ray
Illegal instruction
pi@raspberrypi:/tmp/xxx $ ./v2ray_armv7
Illegal instruction
pi@raspberrypi:/tmp/xxx $ uname -m
armv6l

4) Please attach your configuration file (**Mask IP addresses before submit this issue**).

```javascript
{
  "log" : {
    "access": "/tmp/v2ray_access.log",
    "error": "/tmp/v2ray_error.log",
    "loglevel": "warning"
  },
  "inbounds": [{
    "port": 10086,
    "protocol": "vmess",
    "settings": {
      "clients": [
	{
          "id": "4b497108-6082-4ad3-a322-80bd988d10f6",
          "level": 1,
          "alterId": 64
        }
      ]
    }
  }],
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.168.0.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}
```

**Comment by rendaa** [comment]
我也遇到同样问题，4.20之后（不含该版）的发布包内的v2ctl和v2ray执行都报错：Illegal instruction.

**Comment by vcptr** [comment]
golang does not use a toolchain to to cross compile, the compiler and linker IS inside golang.
Thus, using a targeted armv7 binary on an armv6l CPU, it's not expected to work. If the previous versions works, that's unexpected. The main change is that, the 4.21.x release uses go1.13.3 version of golang.

We recommend that user using a special CPU to cross compile the project from source with correspond variables, in your case, should set `GOARCH=arm GOARM=6` as env viriable. Reference: https://github.com/golang/go/wiki/GoArm

**Comment by nvksie** [comment]
> golang does not use a toolchain to to cross compile, the compiler and linker IS inside golang.
> Thus, using a targeted armv7 binary on an armv6l CPU, it's not expected to work. If the previous versions works, that's unexpected. The main change is that, the 4.21.x release uses go1.13.3 version of golang.
> 
> We recommend that user using a special CPU should cross compile the project from source with corresponding variables, in your case, set `GOARCH=arm GOARM=6` as env viriable. Reference: https://github.com/golang/go/wiki/GoArm

thanks! I have compiled the correct binary with your reply.
but the strange thing is, In the previous version (<= 4.20), 'v2ray' was compiled for armv6 and 'v2ray_armv7' was compiled for armv7. now they are no different, same md5, but still two files

**Comment by vcptr** [comment]
> > golang does not use a toolchain to to cross compile, the compiler and linker IS inside golang.
> > Thus, using a targeted armv7 binary on an armv6l CPU, it's not expected to work. If the previous versions works, that's unexpected. The main change is that, the 4.21.x release uses go1.13.3 version of golang.
> > We recommend that user using a special CPU should cross compile the project from source with corresponding variables, in your case, set `GOARCH=arm GOARM=6` as env viriable. Reference: https://github.com/golang/go/wiki/GoArm
> 
> thanks! I have compiled the correct binary with your reply.
> but the strange thing is, In the previous version (<= 4.20), 'v2ray' was compiled for armv6 and 'v2ray_armv7' was compiled for armv7. now they are no different, same md5, but still two files.
> so 'v2ray_armv7' will be removed in the next version?

before go1.13, `GOARM=6` is default when `GOARCH=arm`, our release script compile one binary without suffix all by default, and another with suffix `_armv7` with `GOARM=7`.

As of now using go1.13, some adjustment is needed, maybe next release the armv6 version would be back.

**Comment by ZenBoy999** [comment]
I guess a separate armv6l should be in the release for a lot Raspberry Pi 3B users. 
model name	: ARMv6-compatible processor rev 7 (v6l)
