### ISSUE TITLE
广告过滤异常

### ISSUE THREAD

**Issue by imrbg** [v2ray/v2ray-core#1978]
{"type":"field","outboundTag":"block","domain":["geosite:qihoo360","geosite:category-ads-all","sogou.com","sogoucdn.com"]}
不正常
同样的category-ads不正常
{"type":"field","outboundTag":"block","domain":["geosite:qihoo360","sogou.com","sogoucdn.com"]}
正常

V2Ray 4.21.1 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to read config file: /etc/v2ray/config.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to parse domain rule: geosite:category-ads-all > v2ray.com/core/infra/conf: failed to load geosite: CATEGORY-ADS-ALL > v2ray.com/core/infra/conf: country not found: CATEGORY-ADS-ALL

**Comment by kslr** [comment]
请升级到最新版本

**Comment by fanchangyong** [comment]
4.22.1版本，用`geosite:category-ads-all`做广告过滤也不行。请问哪个版本是确定可用的呢
