### ISSUE TITLE
远程配置加载

### ISSUE THREAD

**Issue by imrbg** [v2ray/v2ray-core#1980]
输入命令
/usr/bin/v2ray/v2ray --config https://domain.com/config.json
显示
V2Ray 4.21.2 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
之后无限等待

输入命令
/usr/bin/v2ray/v2ray -test -config  https://domain.com/config.json
显示
V2Ray 4.21.2 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
Configuration OK.

**Comment by kslr** [comment]
try latest
