### ISSUE TITLE
如果导入v2ray-core模块，强制被锁定在4.19.1时

### ISSUE THREAD

**Issue by kslr** [v2ray/v2ray-core#1983]
暂时可以用以下方法解决，这是因为切换go mod的后遗症。

```go
module github.com/your/project

go 1.13

require (
  v2ray.com/core v4.19.1+incompatible
)

replace v2ray.com/core => github.com/v2ray/v2ray-core v4.21.3+incompatible
```

**Comment by teddysun** [comment]
虽然 replace 了版本，但在执行 `go mod tidy` 时还是会出现以下错误：

`verifying github.com/v2ray/v2ray-core@v4.21.3+incompatible/go.mod: github.com/v2ray/v2ray-core@v4.21.3+incompatible/go.mod: reading https://sum.golang.org/lookup/github.com/v2ray/v2ray-core@v4.21.3+incompatible: 410 Gone`

**Comment by teddysun** [comment]
设置好下面的环境变量后，顺利编译成功。
```
go env -w GOPROXY=direct
go env -w GOSUMDB=off
```
但是在 tag v4.21.3里 core.go 里的版本号依然为 4.21.2，这就导致了明明编译的是 v4.21.3，结果启动 v2ray-plugin 的时候输出的日志里还是 4.21.2。如下所示：

> V2Ray 4.21.2 (V2Fly, a community-driven edition of V2Ray.) Custom
> A unified platform for anti-censorship.
> [Warning] v2ray.com/core: V2Ray 4.21.2 started


建议作者重新做一下 tag

**Comment by darren** [comment]
v2ray.com 似乎做了不应该的重定向？ 从https转到http:

```
WORK=/tmp/go-build983303037
# get https://v2ray.com/core?go-get=1
# get //v2ray.com/core?go-get=1: Get http://www.v2ray.com/core/?go-get=1: redirected from secure URL https://v2ray.com/core?go-get=1 to insecure URL http://www.v2ray.com/core/?go-get=1
go: errors parsing go.mod:
go.mod:5: unrecognized import path "v2ray.com/core" (https fetch: Get http://www.v2ray.com/core/?go-get=1: redirected from secure URL https://v2ray.com/core?go-get=1 to insecure URL http://www.v2ray.com/core/?go-get=1)
go.mod:7: unrecognized import path "v2ray.com/core" (https fetch: Get http://www.v2ray.com/core/?go-get=1: redirected from secure URL https://v2ray.com/core?go-get=1 to insecure URL http://www.v2ray.com/core/?go-get=1)
```

禁用GORPOXY不是个好方法。

**Comment by kslr** [comment]
历史包裹

Darren Hoo <notifications@github.com> 于 2020年1月1日周三 下午2:22写道：

**Comment by wi1dcard** [comment]
> 设置好下面的环境变量后，顺利编译成功。
> 
> ```
> go env -w GOPROXY=direct
> go env -w GOSUMDB=off
> ```
> 
> 但是在 tag v4.21.3里 core.go 里的版本号依然为 4.21.2，这就导致了明明编译的是 v4.21.3，结果启动 v2ray-plugin 的时候输出的日志里还是 4.21.2。如下所示：
> 
> > V2Ray 4.21.2 (V2Fly, a community-driven edition of V2Ray.) Custom
> > A unified platform for anti-censorship.
> > [Warning] v2ray.com/core: V2Ray 4.21.2 started
> 
> 建议作者重新做一下 tag

Another solution is to set the GOPRIVATE env.

```bash
GOPRIVATE=github.com/v2ray/v2ray-core
```
