### ISSUE TITLE
DNS 服务器的 ServerObject 增加不缓存选项

### ISSUE THREAD

**Issue by zw4832** [v2ray/v2ray-core#1984]
Please describe the new feature you want in detail.
DNS 服务器的 `ServerObject` 增加不缓存选项

因为 V2RAY 的文档介绍了 CoreDNS, 就去学习使用了一下 CoreDNS. 注意到 CoreDNS 的 cache 插件中有一个配置选项是 `prefetch`，它通过判断一个域名是否被频繁查询确定是否要预提取。但 DNS 服务器的缓存机制会干扰这种判断。CoreDNS 做了缓存后，V2RAY 的 DNS 服务器就不需要缓存了。所以希望把是否缓存做成可配置的。

**Comment by kslr** [comment]
有什么区别呢

**Comment by zw4832** [comment]
> 有什么区别呢

CoreDNS 的查询功能和可配置性更多一些，比如说 `prefetch` 可以在一个频繁查询的域名 TTL 过期前去提前查询。还可以通过 CoreDNS 配置缓存时间等等。

V2RAY 目前没有这样的功能，也不应该关注此类功能。但是 V2RAY 可以提供一个选项，把 DNS 的缓存关了，以更好地和 CoreDNS 配合。

**Comment by vcptr** [comment]
不需要v2ray DNS时候只需要让udp 53直接走代理出去即可，v2的内置dns主要工作是路由策略为IPOndemand和IPIfNonMatch模式下解析结果来做路由匹配，如果设置为AsIs v2不需要用到dns.
