### ISSUE TITLE
IPv4 priority on bugy ipv6 network

### ISSUE THREAD

**Issue by matthew728960** [v2ray/v2ray-core#1987]
> 简述
每到晚上YouTube速度就会骤降，视频慢到不能播放。记过排查，从客户端到服务器延迟和速度都正常。因为IPv6是He.net穿透的（搬瓦工KVM），ping了一下洛杉矶节点66.220.18.42，延迟竟然到50ms多，中国白天的时候延迟只有不到 0.5 ms。可能是因为中国晚上是美国白天，很多人在用拖慢了节点速度。在服务器中把he-IPv6出口删掉后，速度回到正常状态。

### Request Feature: IPv4 priority option

IPv6还未普及，相对于IPv4也不太稳定，特别是对于穿透使用IPv6的服务器来说，节点出了问题会有很大的影响，IPv4优先有助于排查网络问题。

而且我有时候会遇到用wget下载文件会解析到IPv6上，但IPv6端又无法访问或者速度极慢的情况

**Comment by Magicloud** [comment]
Confirmed the issue. Right now my server does not work at all due to all client connections are from tunneled IPv4. No error in error.log. Access.log shows no log on problematic time point.

**Comment by Magicloud** [comment]
Updated to latest version, and set "listen" in config.json to "0.0.0.0". But:
```
LISTEN  0      128                         *:32768                      *:*     
SYN-RECV0      0       [::ffff:server.ipv4]:32768 [::ffff:client.ipv4]:13754 
```
