### ISSUE TITLE
arm版本无法运行

### ISSUE THREAD

**Issue by seers** [v2ray/v2ray-core#1988]
v4.20.0的arm版在路由器上可以运行，v4.21.3无法运行
#uname -a
#Linux RT-AC66U_B1 2.6.36.4brcmarm #1 SMP PREEMPT Wed Sep 4 10:12:19 CST 2019 armv7l ASUSWRT
报错Illegal instruction

**Comment by vcptr** [comment]
see #1977

**Comment by nvksie** [comment]
after go1.13
`GOARM=5` is default when `GOARCH=arm`, not 7
```
$ go version
go version go1.13.3 linux/amd64
$ env GOARCH=arm go env | grep GOARM
GOARM="5"
```

**Comment by vcptr** [comment]
> after go1.13
> `GOARM=5` is default when `GOARCH=arm`, not 7
> 
> ```
> $ go version
> go version go1.13.3 linux/amd64
> $ env GOARCH=arm go env | grep GOARM
> GOARM="5"
> ```

You are right. The golang source suggested that at cross compile env, GOARM=5 is the default.

https://github.com/golang/go/blob/10855608bc9361aec0f17f22bf24313a3d07ec85/src/cmd/dist/util.go#L394

as the fact is contrary to my guessing, I reverted the related commit.
Still, I've no idea about why go1.13 creates exact same binary for for `GOARM=""` and `GOARM="7"`,  but this are unrelated to our project.

**Comment by dengke80622** [comment]
same issue on raspberry 2b
root@OpenWrt:~# uname -a
Linux OpenWrt 4.14.109 #0 SMP Thu Apr 4 04:46:13 2019 armv7l GNU/Linux
----------------
root@OpenWrt:~# /usr/bin/v2ray/v2ray_4.21.0 -version
im;pattff runtime: next_0x555555557858dddftes co0x13154des:
 t.span.baseue=] fo0x15e828alΔ= in0x15e7dd       float literaointer out of rangeruntime: panic before mallo     c heap initialized
runtime: text offset base p:
                                        ; %s:%d:%pc semaRoot rotateRi0x25e11    sp:text/x-ecmascr0x118111dd=.eEp0xdB goal,  0x11841018.0x1181108d**Segmentation fault
--------------------------------
root@OpenWrt:~# /usr/bin/v2ray/4.21.0/v2ray -version
Segmentation fault

**Comment by linzhanyu** [comment]
same issus on Raspberry pi 1B

pi@rspi1 ~/v2ray/v $ gdb v2ray
GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/pi/v2ray/v/v2ray...(no debugging symbols found)...done.
(gdb) r
Starting program: /home/pi/v2ray/v/v2ray 

Program received signal SIGILL, Illegal instruction.
0x0004e7b8 in ?? ()
(gdb) disass /r 0x0004e7b8,0x0004e7c8
Dump of assembler code from 0x4e7b8 to 0x4e7c8:
=> 0x0004e7b8:	00 0a b7 ee	vmov.f32	s0, #112	; 0x70
   0x0004e7bc:	40 0a 30 ee	vsub.f32	s0, s0, s0
   0x0004e7c0:	08 0a 8d ed	vstr	s0, [sp, #32]
   0x0004e7c4:	00 0b b7 ee	vmov.f64	d0, #112	; 0x70
End of assembler dump.

May be related to the NEON instruction set at compile time but not supported by ARMv6 CPU

**Comment by StayTherapy** [comment]
[The Go compilation environment variables](https://golang.org/doc/install/source#environment) $GOARM :

> $GOARM (for arm only; default is auto-detected if building on the target processor, 6 if not)
This sets the ARM floating point co-processor architecture version the run-time should target. If you are compiling on the target system, its value will be auto-detected.
> GOARM=5: use software floating point; when CPU doesn't have VFP co-processor
> GOARM=6: use VFPv1 only; default if cross compiling; usually ARM11 or better cores (VFPv2 or better is also supported)
> GOARM=7: use VFPv3; usually Cortex-A cores
> If in doubt, leave this variable unset, and adjust it if required when you first run the Go executable. The GoARM page on the Go community wiki contains further details regarding Go's ARM support.

So, if you don't want to change your running environment , you have to [recompile](https://www.v2ray.com/developer/intro/compile.html) and set `GOARM=5` even if the hardware is armv7.

**Comment by kslr** [comment]
Try 4.22.0

**Comment by holyfight6** [comment]
4.22.0 works, thank you.
