### ISSUE TITLE
请问如何设置dokodemo-door给iptables转发

### ISSUE THREAD

**Issue by cutemanworking** [v2ray/v2ray-core#199]
机器有双网卡， 一个接外网， 一个接内网。想通过iptables将内网nat请求转发给v2ray，在config.json中设置如下：
```javascript
"inbound":
  {
     "protocol": "socks",
     "port": 1090,
     "settings": {
     "auth": "noauth",
     "udp": false,
     "ip": "192.168.77.10" 
   }
  },
  "inboundDetour": [
    {
      "protocol": "http",
      "port": 8090,
      "settings": {}
    },
    {
      "protocol": "dokodemo-door",
      "port": 5500,
      "settings": {
        "address": "8.8.4.4",
        "port": 53,
        "network": "tcp,udp",
        "timeout": 0
      }
    },
    {
      "protocol": "dokodemo-door",
      "address": "",
      "port": 5600,
      "network": "tcp",
      "timeout": 0,
      "followRedirect": true
    }
  ],
```

运行/usr/bin/v2ray/v2ray --test --config=./config.json时出错，请问设置哪里错了?
panic: interface conversion: interface {} is nil, not *dokodemo.Config

goroutine 1 [running]:
panic(0x8e4520, 0xc82035bcc0)
	/home/travis/.gimme/versions/go1.6.2.linux.amd64/src/runtime/panic.go:481 +0x3e6
github.com/v2ray/v2ray-core/proxy/dokodemo.(*Factory).Create(0xc29968, 0x7f34d782cad8, 0xc8204f4cc0, 0x0, 0x0, 0xc820418e70, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/v2ray/v2ray-core/proxy/dokodemo/dokodemo.go:189 +0xf7
github.com/v2ray/v2ray-core/proxy/internal.CreateInboundHandler(0xc820606800, 0xd, 0x7f34d782cad8, 0xc8204f4cc0, 0x0, 0x0, 0x0, 0xc820418e70, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/v2ray/v2ray-core/proxy/internal/handler_cache.go:68 +0x2df
github.com/v2ray/v2ray-core/proxy/repo.CreateInboundHandler(0xc820606800, 0xd, 0x7f34d782cad8, 0xc8204f4cc0, 0x0, 0x0, 0x0, 0xc820418e70, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/v2ray/v2ray-core/proxy/repo/repo.go:10 +0x9e
github.com/v2ray/v2ray-core/shell/point.NewInboundDetourHandlerAlways(0x7f34d782cad8, 0xc8204f4cc0, 0xc82060e1e0, 0x6, 0x0, 0x0)
	/home/travis/gopath/src/github.com/v2ray/v2ray-core/shell/point/inbound_detour_always.go:32 +0x2e3
github.com/v2ray/v2ray-core/shell/point.NewPoint(0xc820591110, 0x19, 0x0, 0x0)
	/home/travis/gopath/src/github.com/v2ray/v2ray-core/shell/point/point.go:129 +0x157b
main.main()
	/home/travis/gopath/src/github.com/v2ray/v2ray-core/release/server/main.go:83 +0x84d

**Comment by v2ray** [comment]
你的最下方的  dokodemo-door (port = 5600) 没有写 settings。

**Comment by cutemanworking** [comment]
配置改成下面的样子后通过了测试: 

  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "info"
  },
  "inbound":
  {
     "protocol": "socks",
     "port": 1090,
     "settings": {
     "auth": "noauth",
     "udp": false,
     "ip": "0.0.0.0"
   }
  },
  "inboundDetour": [
    {
      "protocol": "http",
      "port": 8090,
      "settings": {}
    },
    {
      "protocol": "dokodemo-door",
      "port": 5500,
      "settings": {
      "address": "8.8.4.4",
      "port": 53,
      "network": "tcp,udp",
      "timeout": 0
      }
    },
    {
      "protocol": "dokodemo-door",
      "port": 5600,
      "settings": {
        "address": "",
        "network": "tcp",
        "timeout": 0,
        "followRedirect": true
      }
    }
  ],

但执行下面的iptables语句后局域网内的其它机器出不去, 是不是我iptables语句有错?
sudo iptables -t nat -N v2ray
sudo iptables -t mangle -N v2ray
sudo iptables -t nat -A v2ray -d 外网IP -j RETURN
sudo iptables -t nat -A v2ray -p tcp -j REDIRECT --to-ports 1090
sudo iptables -t nat -A PREROUTING -p tcp -j v2ray
sudo iptables -t mangle -A PREROUTING -j v2ray

**Comment by cnperi** [comment]
sudo iptables -t nat -A v2ray -p tcp -j REDIRECT --to-ports 1090
这句不对吧？你把流量转发给socks代理了
应该是
sudo iptables -t nat -A v2ray -p tcp -j REDIRECT --to-ports 5600
吧？

**Comment by cutemanworking** [comment]
你说得对。 改正过来后就测试成功了。 感谢!
