### ISSUE TITLE
route配置里面的执行顺序是什么?

### ISSUE THREAD

**Issue by loftgame** [v2ray/v2ray-core#1991]
顺序1
```
"rules": [{
				"type": "field",
				"outboundTag": "direct",
				"network": "tcp",
				"domain": [
					"geosite:cn"
				],
				"ip": [
					"geoip:private",
					"geoip:cn"
				]
			},
			{
				"type": "field",
				"balancerTag": "gcpus",
				"network": "tcp",
				"ip": [
					"geoip:us"
				],
				"domain": [
					"geosite:google",
					"domain:youtube.com",
					"domain:iqiyi.com"
				]
			}
]
```
顺序2
```
"rules": [
			{
				"type": "field",
				"balancerTag": "gcpus",
				"network": "tcp",
				"ip": [
					"geoip:us"
				],
				"domain": [
					"geosite:google",
					"domain:youtube.com",
					"domain:iqiyi.com"
				]
			},{
				"type": "field",
				"outboundTag": "direct",
				"network": "tcp",
				"domain": [
					"geosite:cn"
				],
				"ip": [
					"geoip:private",
					"geoip:cn"
				]
			}
]
```

在rule里面有冲突配置 
1 geosite:cn 走 direct.
2 但是 iqiyi.com在第二个配置里面走 gcpus。

我无论如何改变顺序都无法改变 iqiyi.com走 direct的结果 。请问rule里面的规则如果冲突执行的顺序是什么？
![TIM图片20191031172538](https://user-images.githubusercontent.com/6296099/67934771-7afccc80-fc03-11e9-8b96-0e9154aa655d.png)

**Comment by kingwilliam** [comment]
看你的代码 我想您对routing了解还不够 你可先看看 白话文教学 内的 关于路由规则的注意事项。 如还是不明代码那处出问题可再提问。

https://toutyrater.github.io/basic/routing/notice.html

**Comment by loftgame** [comment]
看明白了.

1. 1 ip 和domain是 and关系.
2. 2 route 里面的规则如果有冲突  前面配置的优先级最高..   应该是检查到一个规则满足就直接出去了.


  我对1 有点小疑问哈..  我的使用场景  一般都需要or..  就是满足这些ip 或者满足这些域名并集.. 一般用and就是同时满足ip和域名 交集关系感觉很少.

**Comment by engrecho** [comment]
有几点建议：
1、不太清楚 ip 和 domain做成“与”的意义，真正大家能通俗理解的是“或”关系吧，建议还是修改一下？我能想到的就是当我访问某个域名时，由于同一域名下会解析到不同IP，所以做成的“与”关系？但是这种场景是不是少了点

2、似乎这个是官方文档吧？https://www.v2ray.com/chapter_02/03_routing.html，建议将官方文档注明 ip 和 domain的关系
