### ISSUE TITLE
bug: undefined: log.ContextWithAccessMessage

### ISSUE THREAD

**Issue by bqf9979** [v2ray/v2ray-core#1995]
../../github.com/v2ray/v2ray-core/proxy/socks/server.go:120:10: undefined: log.ContextWithAccessMessage
../../github.com/v2ray/v2ray-core/proxy/socks/server.go:232:11: undefined: log.ContextWithAccessMessage

**Comment by kslr** [comment]
流程呢？

**Comment by bqf9979** [comment]
common.Must(common.RegisterConfig((*socks.ServerConfig)(nil), func(ctx context.Context, config interface{}) (interface{}, error) {
		return socks.NewServer(ctx, config.(*socks.ServerConfig))
	}))

**Comment by bqf9979** [comment]
看了下缺少定义,有个log2.ContextWithAccessMessage有这个定义
