### ISSUE TITLE
请问，v2ray如何同时监听ip4和ipv6呢？

### ISSUE THREAD

**Issue by dylanbai8** [v2ray/v2ray-core#1996]
求助，v2ray如何同时监听ip4和ipv6呢？

官方文档里面没有提到，

写两行listen不起作用。

"listen": "",

**Comment by kingwilliam** [comment]
因不知您的系统有多少ip, 所以只用一般方案回答

如不配置 listen 即等同 监听所有ip
不配置 不是 "listen": "",
即全行不键入 或 // "listen": "",

**Comment by dylanbai8** [comment]
@kingwilliam 你好，非常感谢解答。

我现在的配置是listen全行不键入，我要的目的是同时监听一个ip4和一个ipv6.

之前只有ip4，一切正常

添加了ipv6后，ipv6正常，ip4不监听无法链接。

ip4没有被墙，我怀疑是不是ipv6某个地方没有配置对？

------------------------

之前的提问我表述有问题，我想问的是，listen行如何同时监听一个ip4和一个ipv6。

我测试了

```
"listen": "x.x.x.x",
"listen": "x.x.x.x.x.x.x.x",
 ```

和

```
"listen": "x.x.x.x,x.x.x.x.x.x.x.x",
```

都不起作用。官方文档里也没有说明。

**Comment by kingwilliam** [comment]
您的系统是 windows 还是 linux ?

**Comment by dylanbai8** [comment]
@kingwilliam 你好，服务器是centos7。

经过多次测试：

listen只指定ip4时 ip4正常监听，

listen只指定ipv6时 ipv6正常监听，

listen指定 0.0.0.0 时只监听 ipv6，

listen全行不键入时只监听 ipv6

添加两行listen分别指定ip4和ipv6时，只有第二行listen生效。

**Comment by lucifer9** [comment]
@dylanbai8 你说的后两种情况，即 “listen指定 0.0.0.0 时只监听 ipv6，listen全行不键入时只监听 ipv6”，请问这个时候客户端用 IPv4 去连接服务器的 v4 的 IP，能连上吗

**Comment by dylanbai8** [comment]
> @dylanbai8 你说的后两种情况，即 “listen指定 0.0.0.0 时只监听 ipv6，listen全行不键入时只监听 ipv6”，请问这个时候客户端用 IPv4 去连接服务器的 v4 的 IP，能连上吗

再次感谢！
客户端 安卓v2rayNG
ip4连接不上
ipv6客户端正常链接

**Comment by noeruh** [comment]
listen 0.0.0.0 就是监听所有地址包括v4和v6，你可能误解了netstat的输出，建议telnet特定v4或v6地址来测试

**Comment by dylanbai8** [comment]
https://github.com/shadowsocks/v2ray-plugin/issues/12

v2ray-plugin/issues 里面 有一个类似的问题

不知道是不是同样的原因。

**Comment by dylanbai8** [comment]
> listen 0.0.0.0 就是监听所有地址包括v4和v6，你可能误解了netstat的输出，建议telnet特定v4或v6地址来测试

感谢帮助。
不管netstat输出如何，我都使用安卓v2rayNG进行了链接测试。
貌似v4和v6不能同时使用，求助测试

**Comment by lucifer9** [comment]
所以你是否介意用别的客户端试试呢，或者看一下 net.ipv6.conf.all.disable_ipv6 还有 net.ipv6.bindv6only 的值，顺便问下 server 是什么系统呢

**Comment by dylanbai8** [comment]
哎 你说的这些我都测试过了。可能是v2ray就不支持同时使用ip4和ipv6。

**Comment by lucifer9** [comment]
![批注 2019-11-01 174615.jpg](https://i.loli.net/2019/11/01/7q4JzRLTEFanrKh.jpg)

**Comment by dylanbai8** [comment]
噢！那我再研究研究。我server 是centos7
感谢帮助。

**Comment by azzvx** [comment]
CenOS7的server，openwrt的client
listen不写，server上netstat 看到只有一个"tcp6      0      :::xxxx      :::*      LISTEN      xxxx/v2ray"的条目，但是client通过v4 v6的地址都能连上。

**Comment by dylanbai8** [comment]
@azzvx 感谢帮助

那这么排除下来，应该是我的ipv6相关配置有问题了。能不能分享一下你的centos7添加ipv6教程。
我自己是按照Google找到的教程来配置的。

**Comment by man2018** [comment]
@dylanbai8 大佬，你搞定v2ray同时监听IPv6和IPv4了吗？

**Comment by dylanbai8** [comment]
@man2018 没有搞定。还是不知道问题出在哪里了。

**Comment by befantasy** [comment]
今天遇到了同样的问题。。。请问楼主找到解决方案了吗

**Comment by befantasy** [comment]
感觉好像是我这个镜像不支持ipv6
我在docker里部署的，v2ray版本是4.19
最后面那一行很奇怪。。。带上了127.0.0.1

```
/var/log/v2ray # netstat -apn |grep v2ray                                                                                                                                                           
tcp        0      0 192.168.1.3:52206       45.76.242.33:443        ESTABLISHED 1/v2ray                                                                                                             
tcp        0      0 127.0.0.1:49688         127.0.0.1:2333          ESTABLISHED 1/v2ray                                                                                                             
tcp        0      0 :::2333                 :::*                    LISTEN      1/v2ray                                                                                                             
tcp        0      0 ::ffff:127.0.0.1:2333   ::ffff:127.0.0.1:49688  ESTABLISHED 1/v2ray  
```

**Comment by lastmile2000** [comment]
Just use listen:"0.0.0.0", in the v2ray json config file.
though, the netstat -tulnp show port listening at ipv6 only. Not your expectation both ipv4 and ipv6.  but in actual, the ipv4 is changed to ipv6 . Sample 123.123.123.123  is changed to  ::ffff:123.123.123.123. so listen to ipv6 port can provide both ipv4 and ipv6 connection. 
If I use 127.0.0.1, then only IPv4 port listen. 
v2ray  verified at centos7 vps.  It was said just  to remove listen, the default one is ipv6. but I haven't tested.

**Comment by amaothree** [comment]
Debian10遇到了同样的问题，与楼主的描述一摸一样。用的cloudcone的默认镜像。

**Comment by hsupu** [comment]
Ubuntu 20.04 问题相同，感觉是 IPv6 优先相关的情况，即使 `listen: 0.0.0.0` 也是只监听 IPv6，很神奇。这应该是个 bug。

**Comment by klr1018** [comment]
请问楼主解决了么，校园网想用ipv6免流上iPv4，貌似v2ray只支持v4翻q呢

**Comment by xingkoo** [comment]
实测ipv4和ipv6分另设置监听可以有效工作。
```
"inbounds": [
                {
                        "port": 12345,
                        "protocol": "vmess",
                        "listen": "ipv4",
                        "settings": {
                                "clients": [
                                        {
                                                "id": "3be6224a-98c7-4bd1-a55f-aaaaaaaaaa",
                                                "level": 1,
                                                "alterId": 0
                                        }
                                ]
                        },
                        "streamSettings": {
                                "network": "kcp",
                                "kcpSettings": {
                                        "header": {
                                                "type": "srtp"
                                        }
                                }
                        },
                        "sniffing": {
                                "enabled": true,
                                "destOverride": [
                                        "http",
                                        "tls"
                                ]
                        }
                },

                {
                        "port": 12345,
                        "protocol": "vmess",
                        "settings": {
                                "clients": [
                                        {
                                                "id": "3be6224a-98c7-4bd1-a55f-aaaaaaaaa",
                                                "level": 1,
                                                "alterId": 0
                                        }
                                ]
                        },
                        "streamSettings": {
                                "network": "kcp",
                                "kcpSettings": {
                                        "header": {
                                                "type": "srtp"
                                        }
                                }
                        },
                        "sniffing": {
                                "enabled": true,
                                "destOverride": [
                                        "http",
                                        "tls"
                                ]
                        }
                }
                //include_ss
                //include_socks
                //include_mtproto
                //include_in_config
                //
        ],
```

**Comment by zmhu** [comment]
使用nginx做一下反向代理问题就解决了
思路如下
https://macgeeker.com/linux/v2ray-ipv6/
