### ISSUE TITLE
Remove SNI not work with some website

### ISSUE THREAD

**Issue by 6533200333** [v2ray/v2ray-core#1998]
Please read the [instruction](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md) and answer the following questions before submitting your issue. Thank you.
Please answer all the questions with enough information. All issues not following this template will be closed immediately.
If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2ray/discussion/issues) first.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
4.21.3, also test on 4.18.0, 4.20.0
2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
Access website which are blocked by sni rst.
3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)
Not work for some website e.g. www.voanews.com, www.rfa.org, www.pornhub.com
4) What's your expectation?
Work for all websites which are blocked by sni rst
5) Please attach your configuration file (**Mask IP addresses before submit this issue**).
Server configuration:
No server. Works locally.

Client configuration:

```javascript
"inbounds": [
    {
        "port": 18888,
        "listen": "127.0.0.1",
        "tag": "socks-inbound",
        "protocol": "socks",
        "settings": {
            "auth": "noauth",
            "udp": true,
            "ip": "127.0.0.1"
        },
        "sniffing": {
            "enabled": true,
            "destOverride": [
                "http",
                "tls"
            ]
        }
    },
    {
        "listen": "127.0.0.1",
        "port": 77777,
        "protocol": "dokodemo-door",
        "settings": {
            "network": "tcp",
            "followRedirect": true
        },
        "streamSettings": {
            "security": "tls",
            "tlsSettings": {
                "alpn": [
                    "h2"
                ],
                "certificates": [
                    {
                        "usage": "issue",
                        "certificate": [
                            "..."
                        ],
                        "key": [
                            "..."
                        ]
                    }
                ]
            }
        },
        "tag": "no-sni-inbound"
    }
],
"outbounds": [
    {
        "protocol": "freedom",
        "tag": "direct"
    },
    {
        "protocol": "freedom",
        "settings": {
            "redirect": "127.0.0.1:77777"
        },
        "tag": "no-sni-redirect-outbound"
    },
    {
        "protocol": "freedom",
        "settings": {
            "domainStrategy": "UseIP",
            "redirect": ":443"
        },
        "streamSettings": {
            "security": "tls",
            "tlsSettings": {
                "allowInsecure": true,
                "allowInsecureCiphers": true,
                "alpn": [
                    "h2"
                ]
            }
        },
        "tag": "no-sni-outbound"
    }
],
"routing": {
    "domainStrategy": "AsIs",
    "rules": [
        {
            "type": "field",
            "domain": [
                "..."
            ],
            "inboundTag": "socks-inbound",
            "outboundTag": "no-sni-redirect-outbound"
        },
        {
            "type": "field",
            "inboundTag": "no-sni-inbound",
            "outboundTag": "no-sni-outbound"
        }
    ]
}
```

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.

Server error log:
No server.
```javascript
    // Please attach your server error log here.
```

Client error log:

```javascript
2019/11/01 23:05:12 [Info] [539881033] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.voanews.com:443
2019/11/01 23:05:12 [Info] [539881033] v2ray.com/core/app/dispatcher: sniffed domain: www.voanews.com
2019/11/01 23:05:12 [Info] [539881033] v2ray.com/core/app/dispatcher: taking detour [no-sni-redirect-outbound] for [tcp:www.voanews.com:443]
2019/11/01 23:05:12 tcp:127.0.0.1:11304 accepted tcp:www.voanews.com:443 [no-sni-redirect-outbound]
2019/11/01 23:05:12 [Info] [539881033] v2ray.com/core/proxy/freedom: opening connection to tcp:127.0.0.1:77777
2019/11/01 23:05:12 [Info] [539881033] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:127.0.0.1:77777
2019/11/01 23:05:12 [Info] [3948075443] v2ray.com/core/app/dispatcher: taking detour [no-sni-outbound] for [tcp:www.voanews.com:0]
2019/11/01 23:05:12 [Info] [3948075443] v2ray.com/core/proxy/freedom: opening connection to tcp:www.voanews.com:443
2019/11/01 23:05:13 [Info] [3948075443] v2ray.com/core/proxy/freedom: dialing to to tcp:104.122.18.18:443
2019/11/01 23:05:13 [Info] [3948075443] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:104.122.18.18:443
2019/11/01 23:05:14 [Info] [3948075443] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > v2ray.com/core/proxy/freedom: failed to process response > read tcp xxx.xxx.xxx.xxx:xxx->104.122.18.18:443: wsarecv: An existing connection was forcibly closed by the remote host.
2019/11/01 23:05:14 [Info] [3948075443] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2019/11/01 23:05:14 [Info] [539881033] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/11/01 23:05:20 [Info] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/11/01 23:05:20 [Info] v2ray.com/core/transport/internet/udp: failed to handle UDP input > io: read/write on closed pipe
```

7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.
No server.
```javascript
    // Please attach your server access log here.
```

This config works for www.quora.com, reddit.com, imgur.com, www.pixiv.net, zh.wikipedia.org . Thanks for any help!

**Comment by kingwilliam** [comment]
Only look your coding cannot understand what you want to do. Can you provide all client and server both side coding (Pls remember hide the server address and any uuid) and provide more description.

**Comment by jslll135** [comment]
@kingwilliam Sorry, let me make it clear. I want to use v2ray as a local proxy to bypass sni rst. I follow this post https://steemit.com/cn/@v2ray/sni . Because it's difficult to use a transparent proxy, I set a socks proxy (socks-inbound) and redirect (no-sni-redirect-outbound) to the transparent proxy (no-sni-inbound) . So there is no server. The path is socks-inbound -> no-sni-redirect-outbound -> no-sni-inbound -> no-sni-outbound . This config works with some websites ( www.quora.com, reddit.com, imgur.com, www.pixiv.net, zh.wikipedia.org) but not works with others ( www.voanews.com, www.rfa.org, www.pornhub.com) .

**Comment by kingwilliam** [comment]
the original page already say this technical is not always accept, depend by the web server.


"Domain Fronting 实际上不是一个合理的用法，网站完全可以拒绝这类连接，比如 Google 和 Amazon 就主动在自己的所有服务中拒绝这项技术。"

"Domain Fronting is actually not a reasonable use, and websites can reject such connections. For example, Google and Amazon actively reject this technology in all of their services."


could you consider build the vps v2ray server to let you cross over the firewall?

**Comment by jslll135** [comment]
Yeah, this technical won't work with some websites. However,  www.voanews.com, www.rfa.org, www.pornhub.com accept https without sni. They are listed [here](https://github.com/URenko/Accesser/blob/master/template/pac) and accesser works with them.

**Comment by Cwek** [comment]
> Yeah, this technical won't work with some websites. However, [www.voanews.com](http://www.voanews.com), [www.rfa.org](http://www.rfa.org), [www.pornhub.com](http://www.pornhub.com) accept https without sni. They are listed [here](https://github.com/URenko/Accesser/blob/master/template/pac) and accesser works with them.

Yes, that means that some sites do not have strict SNI verification, so you can use erase SNI for Domain fronting.

The Domain fronting itself is a hack method. Don't expect to be versatile and need to adapt to the case.

**Comment by jslll135** [comment]
I found the problem, The config in the blog use h2 while some websites do not support h2. Browser will connect to V2Ray with h2 but v2ray will connect to server with h1. For compatibility we should set alpn to http/1.1 instead.
