### ISSUE TITLE
Add support for Socks5 TCP Bind command

### ISSUE THREAD

**Issue by v2ray** [v2ray/v2ray-core#2]
Socks5 TCP Bind command (0x02) is used to bind a local port with certain connection, to allow remote server send data initiatively. This feature allows software like FTP client to work on passive mode.

This is not a first priority feature in V2Ray. If you are interested in implementing this, please send a PR.

**Comment by v2ray** [comment]
I don't see this feature would be useful anyway. Closing this issue to reduce the number of issue. Should anyone really need this feature, please open a new issue.

**Comment by zyf0330** [comment]
Hello.
I have set route for private addr to Direct, but v2ray still gives error `rejected  proxy/socks: TCP bind is not supported.` for kdeconnect share file between phone and pc.
