### ISSUE TITLE
如何在win10上配置Shadowsocks服务器？？？

### ISSUE THREAD

**Issue by gbaoye** [v2ray/v2ray-core#200]
请原谅我的愚蠢，我不想知道它的原理及如何运作！

我想知道的是贴上你那傻瓜式的代码，或是在配置文件中说明，或是完全删除旧的配置文件，贴上全新的Shadowsocks配置文件

------------来自傻瓜的问候

**Comment by wenjinlibug** [comment]
@gbaoye 
我觉得这个是不是自己努力一下比较好？
官方主页https://www.v2ray.com/zh_cn/

**Comment by gbaoye** [comment]
我觉得这不太好吧？？？

2016-07-10 14:25 GMT+08:00 wenjinlibug <notifications@github.com>:

**Comment by Sherman-Liu** [comment]
If you can't speak Chinese, please just leave your comment in your native language, such as English, don't use translator, thank you.

**Comment by v2ray** [comment]
https://www.v2ray.com/zh_cn/chapter_05/00_config/06_shadowsocks.html
