### ISSUE TITLE
mKCP功能，在Docker下不能用。

### ISSUE THREAD

**Issue by JSpringYC** [v2ray/v2ray-core#2001]
测试了一下官方提供的`v2ray/official`镜像，与我自己基于Ubuntu最新版的镜像，发现如果配置了`streamSettings`后，程序能正常启动，但是用`telnet`命令Ping端口Ping不通，客户端也无法连接。

请问是依赖问题吗？

**Comment by wwqgtxx** [comment]
docker映射端口的时候加`/udp`了么

**Comment by JSpringYC** [comment]
没有

**Comment by JSpringYC** [comment]
已确认，在Docker中，要配置UDP的端口映射，如：-p 51001:51001 -p 51001/udp: 51001/udp。
只配置UDP的端口的话，会无法使用mKCP.
此问题已解决。
