### ISSUE TITLE
ubuntu 18.06 LTS 如何实现终端翻墙

### ISSUE THREAD

**Issue by NEWgaofeng** [v2ray/v2ray-core#2009]
Please answer all the questions with enough information. All issues not following this template will be closed immediately.
If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2ray/discussion/issues) first.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

3) Please attach full panic log.

You may get panic log using command `journalctl -u v2ray` if your system is Linux (systemd).

4) Please attach your configuration file (**Mask IP addresses before submit this issue**).

```javascript
    // Please attach your configuration here.
```

Please review your issue before submitting.
我的config.json
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 1080,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "sniffing": {
      "enabled": true,
      "destOverride": [
        "http",
        "tls"
      ]
    },
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "127.0.0.1",
      "clients": null
    },
    "streamSettings": null
  },
  "outbound": {
    "tag": "agentout",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "sz-special-xx-1.lanan.world",
          "port": 33333,
          "users": [
            {
              "id": "1ca22f7d-xxxxxxxxxxxxx-c5c3ff1de278",
              "alterId": 2,
              "email": "t@t.tt",
              "security": "aes-128-gcm"
            }
          ]
        }
      ],
      "servers": null
    },
    "streamSettings": {
      "network": "tcp",
      "security": "",
      "tlsSettings": null,
      "tcpSettings": null,
      "kcpSettings": null,
      "wsSettings": null,
      "httpSettings": null
    },
    "mux": {
      "enabled": true
    }
  },
  "inboundDetour": null,
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {
        "response": null
      },
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "blockout"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": null,
          "outboundTag": "direct",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "domain": null
        }
      ]
    }
  }
}
__________________________________________________________________________
启动v2ray之后,我用谷歌浏览器安装了switch插件 实现的访问谷歌.
但是我最近在学习kubernetes 下载一些镜像,需要实现终端翻墙.
求助一下,各位大佬,感谢!

**Comment by UJX6N** [comment]
k8s走的http协议吧。那......

inbound从socks模式改成http模式（或者加一个其他端口的http模式inbound），然后在终端里

export http_proxy="127.0.0.1:1080"
export https_proxy="127.0.0.1:1080"

**Comment by NEWgaofeng** [comment]
我做了如下操作:
1.将v2ray修改为http方式 
2.在swith的proxy修改成http 浏览器还是可以访问谷歌的
3.export http_proxy="127.0.0.1:8080"
   export https_proxy="127.0.0.1:8080"
最后进行测试:结果如下

 curl www.google.com
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>

<head>
  <title>503 - Forwarding failure (Privoxy@localhost)</title>
  <meta http-equiv="Content-Style-Type" content="text/css">
  <meta http-equiv="Content-Script-Type" content="text/javascript">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="robots" content="noindex,nofollow">
  <link rel="shortcut icon" href="http://config.privoxy.org/error-favicon.ico">
  <style type="text/css">

/*
 * CSS for Privoxy CGI and script output
 *
 * Id: cgi-style.css,v
 */
</body>
</html>

浏览器访问谷歌成功证明http方式可以访问,现在终端执行代理命令
export http_proxy="127.0.0.1:8080"
export https_proxy="127.0.0.1:8080"
还是报错了503

**Comment by UJX6N** [comment]
你装了privoxy或者tor之类的？没必要啊，就用v2ray就行了

**Comment by NEWgaofeng** [comment]
我的config.json
{
"log": {
"access": "",
"error": "",
"loglevel": "warning"
},
"inbound": {
"port": 1080,
"listen": "127.0.0.1",
"protocol": "socks",
"sniffing": {
"enabled": true,
"destOverride": [
"http",
"tls"
]
},
"settings": {
"auth": "noauth",
"udp": true,
"ip": "127.0.0.1",
"clients": null
},
"streamSettings": null
},
"outbound": {
"tag": "agentout",
"protocol": "vmess",
"settings": {
"vnext": [
{
"address": "sz-special-xx-1.lanan.world",
"port": 33333,
"users": [
{
"id": "1ca22f7d-xxxxxxxxxxxxx-c5c3ff1de278",
"alterId": 2,
"email": "t@t.tt",
"security": "aes-128-gcm"
}
]
}
],
"servers": null
},
"streamSettings": {
"network": "tcp",
"security": "",
"tlsSettings": null,
"tcpSettings": null,
"kcpSettings": null,
"wsSettings": null,
"httpSettings": null
},
"mux": {
"enabled": true
}
},
"inboundDetour": null,
"outboundDetour": [
{
"protocol": "freedom",
"settings": {
"response": null
},
"tag": "direct"
},
{
"protocol": "blackhole",
"settings": {
"response": {
"type": "http"
}
},
"tag": "blockout"
}
],
"dns": {
"servers": [
"8.8.8.8",
"8.8.4.4",
"localhost"
]
},
"routing": {
"strategy": "rules",
"settings": {
"domainStrategy": "IPIfNonMatch",
"rules": [
{
"type": "field",
"port": null,
"outboundTag": "direct",
"ip": [
"0.0.0.0/8",
"10.0.0.0/8",
"100.64.0.0/10",
"127.0.0.0/8",
"169.254.0.0/16",
"172.16.0.0/12",
"192.0.0.0/24",
"192.0.2.0/24",
"192.168.0.0/16",
"198.18.0.0/15",
"198.51.100.0/24",
"203.0.113.0/24",
"::1/128",
"fc00::/7",
"fe80::/10"
],
"domain": null
}
]
}
}
}
我的inbound在cofig.json配置当中是1080

**Comment by NEWgaofeng** [comment]
修改成
export http_proxy="127.0.0.1:1080"
export https_proxy="127.0.0.1:1080"
依旧不能ping  www.google.com

**Comment by NEWgaofeng** [comment]
root@lyg:~# netstat -lntup | grep 1080
tcp        0      0 127.0.0.1:1080          0.0.0.0:*               LISTEN      1352/v2ray          
root@lyg:~# ping www.google.com
PING www.google.com (199.59.150.49) 56(84) bytes of data.
__________________________________________________________________________
var FindProxyForURL = function(init, profiles) {
    return function(url, host) {
        "use strict";
        var result = init, scheme = url.substr(0, url.indexOf(":"));
        do {
            result = profiles[result];
            if (typeof result === "function") result = result(url, host, scheme);
        } while (typeof result !== "string" || result.charCodeAt(0) === 43);
        return result;
    };
}("+proxy", {
    "+proxy": function(url, host, scheme) {
        "use strict";
        if (/^127\.0\.0\.1$/.test(host) || /^::1$/.test(host) || /^localhost$/.test(host)) return "DIRECT";
        return "PROXY 127.0.0.1:1080";
    }
});

这个是我导出的RAC文件

**Comment by UJX6N** [comment]
但你的1080是socks模式呀

我的參考配置

`
"inbounds":[
      {
         "port":1080,
         "listen":"127.0.0.1",
         "protocol":"socks",
         "settings":{
            "udp":true
         },
         "sniffing":{
            "enabled":true,
            "destOverride":[
               "http",
               "tls"
            ]
         }
      },
      {
         "port":8000,
         "listen":"0.0.0.0",
         "protocol":"http",
         "settings":{

         },
         "sniffing":{
            "enabled":true,
            "destOverride":[
               "http",
               "tls"
            ]
         }
      }
   ],
`

这样有两个inboud，分别是1080的socks代理、8000的http代理，可以分别使用，比方你在浏览器里可以用1080的socks代理，在终端用8000的http代理，这时，需要在终端设置：

export http_proxy="127.0.0.1:8000"
export https_proxy="127.0.0.1:8000"

**Comment by DebianLynx** [comment]
如果是只代理一个程序的话可以采用proxychains进行代理，在终端运行程序前加上proxychains 比如proxychains  google-chrome ,那么就可以仅代理这个程序的网络，默认配置文件在/etc/proxychains.conf ，添加来自v2ray的http或者socks即可。在debian的官方源里有，ubuntu应该也有，详细可以看官方文档。

**Comment by NEWgaofeng** [comment]
问题已经解决,谢谢各位帮忙,愿好!

**Comment by NEWgaofeng** [comment]
proxychains4 命令行代理已经实现了 如果在宿主机的workstation里用的话 需要实现全局代理,现在还在研究当中

**Comment by forrestlmj** [comment]
this save my day thx

**Comment by theonels** [comment]
> 问题已经解决,谢谢各位帮忙,愿好!

请教一下怎么解决的？遇到同样的问题

**Comment by goupper** [comment]
export https_proxy="127.0.0.1:8080"
export http_proxy="127.0.0.1:8080"
