### ISSUE TITLE
shadowsocks不起作用

### ISSUE THREAD

**Issue by oldmannt** [v2ray/v2ray-core#201]
請教個問題
v2ray 的 client 可以正常工作，但shoadowsocks不起作用

/usr/bin/v2ray/v2ray --version
V2Ray v1.18.2 (New Order) 20160704
運行在aws, ec2, Ubuntu 14.04.3 LTS

服務端的日志：
2016/07/10 23:39:55 [Warning]Shadowsocks: Failed to read IV: read tcp 服務器ip:9936->客戶端ip:58312: i/o timeout

服務器配置config.json如下

```javascript
{
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 8964,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "c2dc2d06-4596-11e6-beb8XXXXXX",
          "level": 1,
          "alterId": 10
        },
        {
          "id": "414a7390-4598-11e6-beb8XXXXXX",
          "level": 1,
          "alterId": 10
        }
      ]
    }
  },
  "inboundDetour": [
    {
      "port": 9936,
      "protocol": "shadowsocks", 
      "settings": {
        "method": "aes-256-cfb",
        "password": "1qaz2wsx",     
        "udp": false
      }
    }
  ],
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  },
  "transport": {
    "kcpSettings": {
      "uplinkCapacity": 10,
      "downlinkCapacity": 10
    }
  }
}
```

**Comment by v2ray** [comment]
Shadowsocks 客户端用的是哪一个？

**Comment by oldmannt** [comment]
mac 下的 shadowsocks
https://github.com/shadowsocks/shadowsocks-iOS/releases/download/2.6.3/ShadowsocksX-2.6.3.dmg

**Comment by chamberchain** [comment]
既然有了V2RAY。为何还要用SHADOWSOCKS？这个放弃好久了。专心搞好V2RAY不好吗？难道是因为V2RAY没有安卓版？

**Comment by Sherman-Liu** [comment]
Wow, 'The whole world moves around you' alert!, just because you don't use SS, doesn't mean others don't need it, get it? Grow up FFS.

You suggest others develop a 'clean version' just because you need it? How about you go AFK for a while?

**Comment by chamberchain** [comment]
好吧。你赢了。我只是觉得SS是有客户端的。一定要搅在一起容易出问题。
不用给我帽子。我的发言无意造成：The whole world moves around you。也不意味着：develop a 'clean
version' just because you need it
提高一下你的逻辑能力好吗？

2016-07-15 17:03 GMT+08:00 Sherman-Liu <notifications@github.com>:

**Comment by Sherman-Liu** [comment]
Your suggestion only lifts the maintenance difficulty, and developers' work intensity, I failed to see that develop a different version will do anything good to V2Rays' users, especially nowadays multi-terminal users.

Talking about improving logic skills, how about learning some real English then?

**Comment by chamberchain** [comment]
multi-terminal user：SS自身没有终端？
必须给你差评了。
你觉得你有逻辑能力是因为你说的”real English"?
这样的逻辑能力真的。。。。。。。
那么：你又胜利了。

**Comment by Sherman-Liu** [comment]
Shadowsocks do have its own server version, but, the meaning for the included version of Shadowsocks in the V2Ray is to reduce maintenance difficulty, since running both Shadowsocks standalone edition and V2ray Service on the same server would cause much more problem than now.

**It's so pathetic to see a man struggled to argue with others, in his own little mind.** 

**Why would you shot yourself in the foot?**

**Comment by chamberchain** [comment]
基于你的自信和优越我觉得没有理由浪费时间了。就此打住。


2016-07-18 0:36 GMT+08:00 Sherman-Liu <notifications@github.com>:

**Comment by Sherman-Liu** [comment]
So Pathetic.

**Comment by hetykai** [comment]
我的也不行

**Comment by tiansj** [comment]
那个姓刘的好古怪啊，语文是体育老师教的。

**Comment by wind315** [comment]
我的也是SS不行，我是来找解决方法的，结果来看了一通口水战也是醉了

**Comment by wswaw** [comment]
我是来淆习real English的。:grinning:

**Comment by wind315** [comment]
请教openshift上面是不是不能部署v2ray的shadowsocks？如果能部署SS，需要注意些啥？我部署了，但不能连接，一直提示“2018/11/22 01:17:07 10.131.0.1:43098 rejected  v2ray.com/core/proxy/shadowsocks: failed to read IV > read tcp 10.130.4.38:8080->10.131.0.1:43098: read: connection reset by peer”

**Comment by dangelization** [comment]
我的也是 客户端 shadowsocks: failed to read IV > EOF
客户端和服务器都是用的v2ray里面的shadowsocks，v2ray版本是4.7.0
