### ISSUE TITLE
发现v2ray连接断开有严重bug，导致go routine很长时间不能释放。

### ISSUE THREAD

**Issue by confeliped** [v2ray/v2ray-core#2011]
![image](https://user-images.githubusercontent.com/57243233/68111162-7ac53f80-ff29-11e9-8701-ef8baa4bec94.png)

### 目前v2ray连接断开策略是：

- 如果copy(reader1, link1.writer)成功，则close link1.writer

- 如果copy(reader1,link1.writer)或者copy(link1.reader, writer1)有任何一个发生错误,则interrupt link1

- 如果copy(reader2, link2.writer)成功，则close link2.writer;如果出错，则什么也不做

### 这样出现了一个导致copy(link1.reader, writer1)一直退不出的bug:
如果copy(reader1, link1.writer)成功，但是copy(reader2, link2.writer)错误，由于copy(link1.reader, writer1)中会先读取link1.reader后写writer1, 此时读link1.reader永远不会被返回错误，那么copy(link1.reader, writer1)会被永久性挂起

**Comment by eycorsican** [comment]
关于第三点

> 如果copy(reader2, link2.writer)成功，则close link2.writer;如果出错，则什么也不做

以 freedom 为例，假设你指的 copy(reader2, link2.writer) 是这一行: https://github.com/v2ray/v2ray-core/blob/5e1d8f8e69a0e08b6f73b6ae865a9daeb3e179d9/proxy/freedom/freedom.go#L172

如果出错，会返回一个错误，接收这个错误的是这里：https://github.com/v2ray/v2ray-core/blob/5e1d8f8e69a0e08b6f73b6ae865a9daeb3e179d9/app/proxyman/outbound/handler.go#L107

返回错误的话，会 interrupt link2.writer 和 link2.reader

**Comment by confeliped** [comment]
@eycorsican 一针见血，我忽略了outound中handler.go会处理错误情况，感谢你的指正，谢谢。这个issue可以关闭了。
