### ISSUE TITLE
 API statistics have unrealized issues

### ISSUE THREAD

**Issue by zdm2008** [v2ray/v2ray-core#2013]
After calling the API to remove Inbound, the inbound statistics corresponding to the stat API are not deleted.

**Comment by vcptr** [comment]
Stats and Inbonds are two individual modules, the removal of inbound does not affect stats objects.
Currently there's no plan on linking their corresponding.

**Comment by zdm2008** [comment]
So, is it possible to provide an interface that can delete statistics?
