### ISSUE TITLE
v2ray + nginx + cloudflare 502: Bad Gateway error

### ISSUE THREAD

**Issue by SoumeshBanerjee** [v2ray/v2ray-core#2016]
So I have the following setup 

Client <-> Cloudflare <-> Nginx <-> v2ray ---------> [internet]

If I visit the site (from browser) its working properly. The problem is when `/websocket` path is requested CloudFlare shows a 502: BadRequest page.

In `nginx` all the request to `/websocket` are proxied to the v2ray running locally.

Here are the configs

#### nginx

```
server {
	root /var/www/html;
	
	index index.html index.htm index.nginx-debian.html;

	server_name example.com;

	location / {
		try_files $uri $uri/ =404;
	}

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


	location /websocket/ {
		proxy_redirect off;
		proxy_pass http://127.0.0.1:8388;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_set_header Host $http_host;
	}
}

server {
    if ($host = example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


	listen 80 default_server;
	listen [::]:80 default_server;

	server_name www.example.com;
    return 404; # managed by Certbot
}```


#### v2ray server

```json
{
"inbounds": [
        {
            "port": 8388,
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                    }
                ],
                "streamSettings": {
                    "network": "ws",
                    "wsSettings": {
                        "path": "/websocket/"
                    }
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {}
        }
    ]
}
```

#### v2ray client config

```json
{
  "inbounds": [
    {
      "port": 1080,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": true
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "example.com",
            "port": 443,
            "users": [
              {
                "id": "f7cb26c5-663e-4040-818c-5b06843cccfb"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "\/websocket\/"
        },
        "security": "tls",
        "tlsSettings": {
          "serverName": "example.com",
          "allowInsecure": false
        }
      }
    },
    {
      "protocol": "freedom",
      "tag": "direct",
      "settings": {}
    }
  ],
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "direct"
      }
    ]
  }
}
```

#### nginx error log

````
2019/11/06 09:26:10 [error] 7877#7877: *593 upstream prematurely closed connection while reading response header from upstream, client: 255.255.255.255, server: example.com, request: "GET /websocket/ HTTP/1.1", upstream: "http://127.0.0.1:8388/websocket/", host: "example.com", referrer: "https://example.com/websocket/"
````

#### v2ray client log

````
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
2019/11/06 16:38:48 [Warning] v2ray.com/core: V2Ray 4.21.3 started
2019/11/06 16:43:55 [Warning] [3777055153] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://example.com/websocket/): 502 Bad Gateway > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
````

#### v2ray version
`V2Ray 4.21.3`

**Comment by kslr** [comment]
Cancel Cloudflare test

**Comment by SoumeshBanerjee** [comment]
I have canceled it now.
`v2ray` server gives error now "

```
2019/11/06 19:56:01 [Info] [1507363104] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: invalid request from 127.0.0.1:50286 > v2ray.com/core/proxy/vmess/encoding: invalid user
```

**Comment by i553041** [comment]
> So I have the following setup
> 
> Client <-> Cloudflare <-> Nginx <-> v2ray ---------> [internet]
> 
> If I visit the site (from browser) its working properly. The problem is when `/websocket` path is requested CloudFlare shows a 502: BadRequest page.
> 
> In `nginx` all the request to `/websocket` are proxied to the v2ray running locally.
> 
> Here are the configs
> 
> #### nginx
> ```
> server {
> 	root /var/www/html;
> 	
> 	index index.html index.htm index.nginx-debian.html;
> 
> 	server_name example.com;
> 
> 	location / {
> 		try_files $uri $uri/ =404;
> 	}
> 
>     listen [::]:443 ssl ipv6only=on; # managed by Certbot
>     listen 443 ssl; # managed by Certbot
>     ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem; # managed by Certbot
>     ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem; # managed by Certbot
>     include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
>     ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
> 
> 
> 	location /websocket/ {
> 		proxy_redirect off;
> 		proxy_pass http://127.0.0.1:8388;
> 		proxy_http_version 1.1;
> 		proxy_set_header Upgrade $http_upgrade;
> 		proxy_set_header Connection "upgrade";
> 		proxy_set_header Host $http_host;
> 	}
> }
> 
> server {
>     if ($host = example.com) {
>         return 301 https://$host$request_uri;
>     } # managed by Certbot
> 
> 
> 	listen 80 default_server;
> 	listen [::]:80 default_server;
> 
> 	server_name www.example.com;
>     return 404; # managed by Certbot
> }```
> 
> 
> #### v2ray server
> 
> ```json
> {
> "inbounds": [
>         {
>             "port": 8388,
>             "protocol": "vmess",
>             "settings": {
>                 "clients": [
>                     {
>                         "id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
>                     }
>                 ],
>                 "streamSettings": {
>                     "network": "ws",
>                     "wsSettings": {
>                         "path": "/websocket/"
>                     }
>                 }
>             }
>         }
>     ],
>     "outbounds": [
>         {
>             "protocol": "freedom",
>             "settings": {}
>         }
>     ]
> }
> ```
> 
> #### v2ray client config
> ```json
> {
>   "inbounds": [
>     {
>       "port": 1080,
>       "listen": "127.0.0.1",
>       "protocol": "socks",
>       "settings": {
>         "udp": true
>       }
>     }
>   ],
>   "outbounds": [
>     {
>       "protocol": "vmess",
>       "settings": {
>         "vnext": [
>           {
>             "address": "example.com",
>             "port": 443,
>             "users": [
>               {
>                 "id": "f7cb26c5-663e-4040-818c-5b06843cccfb"
>               }
>             ]
>           }
>         ]
>       },
>       "streamSettings": {
>         "network": "ws",
>         "wsSettings": {
>           "path": "\/websocket\/"
>         },
>         "security": "tls",
>         "tlsSettings": {
>           "serverName": "example.com",
>           "allowInsecure": false
>         }
>       }
>     },
>     {
>       "protocol": "freedom",
>       "tag": "direct",
>       "settings": {}
>     }
>   ],
>   "routing": {
>     "domainStrategy": "IPOnDemand",
>     "rules": [
>       {
>         "type": "field",
>         "ip": [
>           "geoip:private"
>         ],
>         "outboundTag": "direct"
>       }
>     ]
>   }
> }
> ```
> 
> #### nginx error log
> ```
> 2019/11/06 09:26:10 [error] 7877#7877: *593 upstream prematurely closed connection while reading response header from upstream, client: 255.255.255.255, server: example.com, request: "GET /websocket/ HTTP/1.1", upstream: "http://127.0.0.1:8388/websocket/", host: "example.com", referrer: "https://example.com/websocket/"
> ```
> 
> #### There are no error logs for v2ray server and its running properly.
> #### v2ray client log
> ```
> V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
> A unified platform for anti-censorship.
> 2019/11/06 16:38:48 [Warning] v2ray.com/core: V2Ray 4.21.3 started
> 2019/11/06 16:43:55 [Warning] [3777055153] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://example.com/websocket/): 502 Bad Gateway > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
> ```
> 
> #### v2ray version
> `V2Ray 4.21.3`
I also use ur method to access internet,use TLS 1.3,I don't have any problem

first,if u use cloudflare CDN (proxied orange cloud),nginx please use cloudflare certificate in SSL/TLS -> Edge Certificate -> gen an 15 years certificate，and TLS use FULL (Strict)，Minimum TLS Version use 1.3

then nginx use cloudflare certificate,and in the host config file,add the following line under ssl_certificate

ssl_protocols TLSv1.3;

ssl_ecdh_curve X25519:P-256:P-384:P-224:P-521;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-CHACHA20-POLY1305:ECDHE+AES128:RSA+AES128:ECDHE+AES256:RSA+AES256:ECDHE+3DES:RSA+3DES;

location /websocket/ {   <----use /websocket is ok,also ur v2ray server & client side also use ""path": "/websocket"

u can make a host name in cloudflare,such as proxy.example.com,and also create a config file in nginx for proxy.example.com,don't use CDN,direct (Grey cloud),then use let's encrypt certificate,use direct connect,the speed is faster then CDN.

that's mean,use cloudflare CDN (Orange cloud),then use cloudflare certificate

direct access,(Grey cloud)use let's encrypt certificate

if ur v2ray client do not support TLS 1.3,please ignore all TLS1.3 setting,I use the latest version shadowrocket as my client,it support TLS 1.3,so I can use TLS 1.3

hope it can help

**Comment by SoumeshBanerjee** [comment]
Yes the problem was with the path, changing `/websocket/` to `/websocket` fixed the problem

Thanks @i553041
