### ISSUE TITLE
v2ray: unrecognized service

### ISSUE THREAD

**Issue by shi755455234** [v2ray/v2ray-core#2017]
第9种.
 [root /]# /usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.Configuration OK.

[root /]# service v2ray start
v2ray: unrecognized service

Exit code: 1

**Comment by treert** [comment]
解决了？GCloud Debian 9 系统有同样的问题

**Comment by treert** [comment]
> 解决了？GCloud Debian 9 系统有同样的问题

第一次安装出错，第二次安装成功（但实际也出错了）。安装时加上`-f`参数，强制安装就好了。
