### ISSUE TITLE
v2ray作为内网网关时，公网访问局域网的服务器出错

### ISSUE THREAD

**Issue by pypykim** [v2ray/v2ray-core#2018]
Client:V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) OpenWrt - Release 1
Server:V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.

https://github.com/kuoruan/luci-app-v2ray/issues/39

**Comment by twskipper** [comment]
iptables-save看一下
