### ISSUE TITLE
Source code archive from release page seem to be mistaged 

### ISSUE THREAD

**Issue by karuboniru** [v2ray/v2ray-core#2019]
[This Link from Release Page](https://github.com/v2ray/v2ray-core/archive/v4.21.3.tar.gz) is listed in `v4.21.3`, but `core.go` contains 
```
const (
	version  = "4.21.2"
	build    = "Custom"
	codename = "V2Fly, a community-driven edition of V2Ray."
	intro    = "A unified platform for anti-censorship."
)
```
I think you mistagged the source release version.

**Comment by kslr** [comment]
fix
