### ISSUE TITLE
Support force outbound to connect remote destination by IPv4 or IPv6 or both

### ISSUE THREAD

**Issue by xiaokangwang** [v2ray/v2ray-core#202]
应该支持选择要使用的网络是IPv4还是IPv6，设置后程序仅尝试使用这个网络连接。

大概功能上的实现就是network参数提交进 tcp4 tcp6 udp4 udp6 而不是 tcp udp。

使用KCP的时候会因为udp无状态，不能自动选择网络版本。 这时需要能够强制指定使用的网络。

有的网站的IPv6服务器配置不正确，在优先使用IPv6失败后因为代理的原因不能自动切换到IPv4服务器，这时需要能够通过配置要求程序仅使用IPv4。

**Comment by v2ray** [comment]
现在有一个 sendThrough 参数可以做到类似的功能。如果你需要部署多台机器的话，这个选项不具有通用性。

另外不理解这句话“在优先使用IPv6失败后因为代理的原因不能自动切换到IPv4服务器”，能否给个例子？

**Comment by xiaokangwang** [comment]
socks5连接的时候只能指定要连接的域名 比如 fakedomain.123.com 有 A 记录 和 AAAA 记录， 其中AAAA记录错误，连接的话 60秒后 connection timeout. 浏览器IPv6连接几秒钟不成功会尝试使用IPv4连接，体验流畅， v2ray每次都connection timeout，无法访问。

**Comment by v2ray** [comment]
这个 issue 将放在 Trello 管理。
