### ISSUE TITLE
在校园网下 invalid user

### ISSUE THREAD

**Issue by cjwzk** [v2ray/v2ray-core#2023]
v2 在校园网环境下就会
2019/11/10 13:11:11 221.194.139.106:10058 accepted tcp:www.google.com:80 
2019/11/10 13:11:11 221.194.139.101:23018 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/11/10 13:11:11 221.194.139.106:8751 accepted tcp:www.google.com:80 
2019/11/10 13:11:11 221.194.139.101:27509 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/11/10 13:11:13 221.194.139.106:51802 accepted tcp:www.google.com:80 
2019/11/10 13:11:14 221.194.139.101:2626 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
时间、用户ID都验证无误 
相同配置 在移动互联网都情况下
2019/11/10 13:12:20 117.136.47.145:9625 accepted tcp:www.google.com:80 
2019/11/10 13:12:20 117.136.47.145:9626 accepted tcp:www.google.com:80 
2019/11/10 13:12:21 117.136.47.145:9627 accepted tcp:www.google.com:80 
2019/11/10 13:12:21 117.136.47.145:9628 accepted tcp:www.google.com:80 
2019/11/10 13:12:22 117.136.47.145:9629 accepted udp:8.8.8.8:53 
2019/11/10 13:12:23 117.136.47.145:9630 accepted tcp:www.google.com:80 
2019/11/10 13:12:25 117.136.47.145:9631 accepted udp:8.8.8.8:53 
2019/11/10 13:12:33 117.136.47.145:9632 accepted udp:8.8.8.8:53 
2019/11/10 13:12:45 117.136.47.145:9633 accepted tcp:www.google.com:443

详细配置

{
  "dns": {
    "hosts": {
      "domain:googleapis.cn": "googleapis.com"
    },
    "servers": [
      "8.8.8.8",
      {
        "address": "223.5.5.5",
        "domains": [
          "geosite:cn"
        ],
        "port": 53
      }
    ]
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "tag": "socks"
    },
    {
      "listen": "127.0.0.1",
      "port": 10809,
      "protocol": "http",
      "settings": {
        "userLevel": 8
      },
      "tag": "http"
    },
    {
      "listen": "127.0.0.1",
      "port": 10807,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "8.8.8.8",
        "network": "tcp,udp",
        "port": 53
      },
      "tag": "dns-in"
    }
  ],
  "log": {
    "loglevel": "none"
  },
  "outbounds": [
    {
      "mux": {
        "enabled": false
      },
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "",
            "port": ,
            "users": [
              {
                "alterId": 233,
                "id": "9ae1a02e-7bf9-4122-a1bf-7ca2189d5b28",
                "level": 8,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": ""
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    },
    {
      "protocol": "dns",
      "tag": "dns-out"
    }
  ],
  "policy": {
    "levels": {
      "8": {
        "connIdle": 300,
        "downlinkOnly": 1,
        "handshake": 4,
        "uplinkOnly": 1
      }
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "dns-in"
        ],
        "outboundTag": "dns-out",
        "type": "field"
      },
      {
        "ip": [
          "8.8.8.8"
        ],
        "outboundTag": "proxy",
        "port": "53",
        "type": "field"
      },
      {
        "ip": [
          "223.5.5.5"
        ],
        "outboundTag": "direct",
        "port": "53",
        "type": "field"
      },
      {
        "domain": [
          "domain:googleapis.cn"
        ],
        "outboundTag": "proxy",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "ip": [
          "geoip:cn"
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "domain": [
          "geosite:cn"
        ],
        "outboundTag": "direct",
        "type": "field"
      }
    ]
  },
  "stats": {}
}

**Comment by kingwilliam** [comment]
因校园可能有透明代理(如squid),可否加入 tls ? 但不一定可以 因校园安全理由 一样可以用squid做MITM. 只能测试.

**Comment by N-kun** [comment]
> 因校园可能有透明代理（如squid），可否加入tls测试？但加入tls后不一定成功因校园安全理由一样可以用squid做MITM。只能测试。

谢谢 马上要考试了 考完试我试试

**Comment by johnrosen1** [comment]
https://www.johnrosen1.com/v2ray-cdn/ cdn总不能直接封锁吧
