### ISSUE TITLE
在iOS上使用，15M内存问题，导致连接中断？ 

### ISSUE THREAD

**Issue by wfkbyni** [v2ray/v2ray-core#2025]
这个问题请问从何处入手可以解决呢？ 纠结中。。。

**Comment by wfkbyni** [comment]
大哥，这个没有日志，就是iOS的PacketTunnel有15M内存限制，在访问大体量网站的时候，会超过15M内存限制，导致app的连接断开 ，配置也很简单，如下：

**Comment by wfkbyni** [comment]
{
    "outbound":{
        "protocol":"vmess",
        "settings":{
            "vnext":[
                {
                    "address":"",
                    "port":0,
                    "users":[
                        {
                            "id":"",
                            "alterId":0
                        }
                    ]
                }
            ]
        },
        "mux":{
            "enabled":true,
            "concurrency":100
        }
    }
}

**Comment by wfkbyni** [comment]
访问网站和看视频这些是没有问题的，就是在体量比较大的网站下，很不稳定。

**Comment by wfkbyni** [comment]
{
    "outbound":{
        "protocol":"vmess",
        "settings":{
            "vnext":[
                {
                    "address":"",
                    "port":0,
                    "users":[
                        {
                            "id":"",
                            "alterId":0
                        }
                    ]
                }
            ]
        },
        "mux":{
            "enabled":true,
            "concurrency":1000
        }
    }
}

**Comment by wfkbyni** [comment]
{
    "outbound":{
        "protocol":"vmess",
        "settings":{
            "vnext":[
                {
                    "address":"",
                    "port":0,
                    "users":[
                        {
                            "id":"",
                            "alterId":0
                        }
                    ]
                }
            ]
        },
        "mux":{
            "enabled":true,
            "concurrency":1000
        }
    }
}

**Comment by kslr** [comment]
你是如何确定是15m问题的

**Comment by wfkbyni** [comment]
是的 我确定




| |
舒永超
邮箱：wfkbyni@126.com
|

签名由 网易邮箱大师 定制

在2019年11月11日 20:09，Kslr 写道：

你是如何确定是15m问题的

**Comment by kslr** [comment]
那应该也需要联系客户端的作者

**Comment by wfkbyni** [comment]
看视频可以一直看 如果访问资源特别多的网站内存就会炸掉




| |
舒永超
邮箱：wfkbyni@126.com
|

签名由 网易邮箱大师 定制

在2019年11月11日 20:13，Kslr 写道：

那应该也需要联系客户端的作者

**Comment by wfkbyni** [comment]
我就是作者 现在遇到这个问题




| |
舒永超
邮箱：wfkbyni@126.com
|

签名由 网易邮箱大师 定制

在2019年11月11日 20:13，Kslr 写道：

那应该也需要联系客户端的作者

**Comment by wfkbyni** [comment]
不知道能否加你qq 给予我们一些支持 我的qq 461170711




| |
舒永超
邮箱：wfkbyni@126.com
|

签名由 网易邮箱大师 定制

在2019年11月11日 20:14，舒永超 写道：
我就是作者 现在遇到这个问题




| |
舒永超
邮箱：wfkbyni@126.com
|

签名由 网易邮箱大师 定制

在2019年11月11日 20:13，Kslr 写道：

那应该也需要联系客户端的作者

**Comment by kslr** [comment]
你可以看下既往issue 或者挑选需要的部分编译

**Comment by wfkbyni** [comment]
我认真的看完了所有issue 但没找到具体的解决办法  




| |
舒永超
邮箱：wfkbyni@126.com
|

签名由 网易邮箱大师 定制

在2019年11月11日 20:22，Kslr 写道：

你可以看下既往issue 或者挑选需要的部分编译

**Comment by wfkbyni** [comment]
大哥，能一起解决一下问题吗？

**Comment by lucifer9** [comment]
Go 就这样啊，要不你试试看 C 的实现，https://github.com/nicholascw/vmecs

**Comment by wfkbyni** [comment]
> Go 就这样啊，要不你试试看 C 的实现，https://github.com/nicholascw/vmecs

你用这个实现过吗？？

**Comment by lucifer9** [comment]
实现什么？按照它的 README，它就是个 VMESS 协议的 C 实现。要是你发现有不对的，就跟原作者提 issue 或者 pr 呗

**Comment by RDchengbiao** [comment]
请问怎么在ios中使用，没有看到ios的安装包呀？  本人使用的ios13，现在的shadowrocket需要收费，但是我没有国外的银行卡，无法支付，请问大神们都是怎么在ios上使用支持vmess协议的客户端的？

**Comment by kslr** [comment]
> 请问怎么在ios中使用，没有看到ios的安装包呀？ 本人使用的ios13，现在的shadowrocket需要收费，但是我没有国外的银行卡，无法支付，请问大神们都是怎么在ios上使用支持vmess协议的客户端的？

1. 可以使用银联卡
2. 可以购买礼品卡，但需要安全的渠道

**Comment by Cyberbolt** [comment]
请问解决了吗？iOS 17.3.1 仍然遇到 15 MB 内存限制 
[link](https://github.com/eycorsican/leaf/issues/453)
