### ISSUE TITLE
用同样的方式连3家vps，有一家连不上

### ISSUE THREAD

**Issue by moekosamaki** [v2ray/v2ray-core#2026]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V2Ray 版本: v4.21.3   
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
使用 Chrome 通过 Socks5 上谷歌
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
上不了网页
4) 你期待看到的正确表现是怎样的？
能科学上网
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

{
	"log": {
		"access": "/var/log/v2ray/access.log",
		"error": "/var/log/v2ray/error.log",
		"loglevel": "warning"
	},
	"inbounds": [
		{
			"port": 26501,
			"protocol": "vmess",
                            "listen":"173【】7.8",
			"settings": {
				"clients": [
					{
						"id": "726ebc67-d7e9-45ed-b1d9-006057e8b630",
						"level": 1,
						"alterId": 233
					}
				]
			},
			"streamSettings": {
				"network": "tcp"
			},
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			}
		}
		//include_ss
		//include_socks
		//include_mtproto
		//include_in_config
		//
	],
	"outbounds": [
		{
			"protocol": "freedom",
			"settings": {}
		},
		{
			"protocol": "blackhole",
			"settings": {},
			"tag": "blocked"
		},
		{
			"protocol": "freedom",
			"settings": {},
			"tag": "direct"
		},
		{
			"protocol": "mtproto",
			"settings": {},
			"tag": "tg-out"
		}
		//include_out_config
		//
	],
	"dns": {
		"server": [
			"1.1.1.1",
			"1.0.0.1",
			"8.8.8.8",
			"8.8.4.4",
			"localhost"
		]
	},
	"routing": {
		"domainStrategy": "IPOnDemand",	
		"rules": [
			{
				"type": "field",
				"ip": [
					"0.0.0.0/8",
					"10.0.0.0/8",
					"100.64.0.0/10",
					"127.0.0.0/8",
					"169.254.0.0/16",
					"172.16.0.0/12",
					"192.0.0.0/24",
					"192.0.2.0/24",
					"192.168.0.0/16",
					"198.18.0.0/15",
					"198.51.100.0/24",
					"203.0.113.0/24",
					"::1/128",
					"fc00::/7",
					"fe80::/10"
				],
				"outboundTag": "blocked"
			},
			{
				"type": "field",
				"inboundTag": ["tg-in"],
				"outboundTag": "tg-out"
			}
			,
			{
			

	"type": "field",
				"domain": [
					"domain:epochtimes.com",
					"domain:epochtimes.com.tw",
					"domain:epochtimes.fr",
					"domain:epochtimes.de",
					"domain:epochtimes.jp",
					"domain:epochtimes.ru",
					"domain:epochtimes.co.il",
					"domain:epochtimes.co.kr",
					"domain:epochtimes-romania.com",
					"domain:erabaru.net",
					"domain:lagranepoca.com",
					"domain:theepochtimes.com",
					"domain:ntdtv.com",
					"domain:ntd.tv",
					"domain:ntdtv-dc.com",
					"domain:ntdtv.com.tw",
					"domain:minghui.org",
					"domain:renminbao.com",
					"domain:dafahao.com",
					"domain:dongtaiwang.com",
					"domain:falundafa.org",
					"domain:wujieliulan.com",
					"domain:ninecommentaries.com",
					"domain:shenyun.com"
				],
				"outboundTag": "blocked"
			}			,
                {
                    "type": "field",
                    "protocol": [
                        "bittorrent"
                    ],
                    "outboundTag": "blocked"
                }
			//include_ban_ad
			//include_rules
			//
		]
	},
	"transport": {
		"kcpSettings": {
            "uplinkCapacity": 100,
            "downlinkCapacity": 100,
            "congestion": true
        },
		"sockopt": {
			"tcpFastOpen": true
		}
	}
}

客户端配置:

{
  "policy" : {
    "levels" : {
      "0" : {
        "uplinkOnly" : 0
      }
    }
  },
  "dns" : {
    "servers" : [
      "localhost"
    ]
  },
  "outboundDetour" : [
    {
      "protocol" : "freedom",
      "tag" : "direct",
      "settings" : {

      }
    }
  ],
  "inbound" : {
    "listen" : "127.0.0.1",
    "port" : 1081,
    "protocol" : "socks",
    "settings" : {
      "auth" : "noauth",
      "udp" : false,
      "ip" : "127.0.0.1"
    }
  },
  "inboundDetour" : [
    {
      "listen" : "127.0.0.1",
      "allocate" : {
        "strategy" : "always",
        "refresh" : 5,
        "concurrency" : 3
      },
      "port" : 8001,
      "protocol" : "http",
      "tag" : "httpDetour",
      "domainOverride" : [
        "http",
        "tls"
      ],
      "streamSettings" : {

      },
      "settings" : {
        "timeout" : 0
      }
    }
  ],
  "log" : {
    "error" : "\/var\/folders\/s3\/qkx6zfpx1px10_0s7zzj507m0000gn\/T\/com.wms.v2rayx.log.B9E5E066-59B3-42DD-B6BC-BAEE9734BEBB\/error.log",
    "loglevel" : "无",
    "access" : "\/var\/folders\/s3\/qkx6zfpx1px10_0s7zzj507m0000gn\/T\/com.wms.v2rayx.log.B9E5E066-59B3-42DD-B6BC-BAEE9734BEBB\/access.log"
  },
  "routing" : {
    "strategy" : "rules",
    "settings" : {
      "domainStrategy" : "IPIfNonMatch",
      "rules" : [
        {
          "domain" : [
            "localhost",
            "geosite:cn"
          ],
          "type" : "field",
          "outboundTag" : "direct"
        },
        {
          "type" : "field",
          "outboundTag" : "direct",
          "ip" : [
            "geoip:private",
            "geoip:cn"
          ]
        }
      ]
    }
  },
  "outbound" : {
    "sendThrough" : "0.0.0.0",
    "mux" : {
      "enabled" : false,
      "concurrency" : 8
    },
    "protocol" : "vmess",
    "settings" : {
      "vnext" : [
        {
          "address" : "173.【】.8",
          "port" : 26501,
          "users" : [
            {
              "id" : "726ebc67-d7e9-45ed-b1d9-006057e8b630",
              "alterId" : 233,
              "security" : "auto",
              "level" : 0
            }
          ],
          "remark" : "Unnamed Server"
        }
      ]
    },
    "streamSettings" : {
      "wsSettings" : {
        "path" : "",
        "headers" : {
          "Host" : "youraddress.com"
        }
      },
      "tlsSettings" : {
        "serverName" : "youraddress.com",
        "allowInsecure" : false
      },
      "httpSettings" : {
        "path" : "",
        "host" : [
          ""
        ]
      },
      "tcpSettings" : {
        "header" : {
          "type" : "none"
        }
      },
      "kcpSettings" : {
        "header" : {
          "type" : "none"
        },
        "mtu" : 1350,
        "congestion" : false,
        "tti" : 20,
        "uplinkCapacity" : 5,
        "writeBufferSize" : 1,
        "readBufferSize" : 1,
        "downlinkCapacity" : 20
      },
      "network" : "tcp",
      "security" : "none"
    }
  }
}
6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

2019/11/11 18:12:29 [Warning] v2ray.com/core: V2Ray 4.21.3 started

客户端错误日志:
2019/11/12 00:37:35 [Warning] [3696917371] App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: failed to find an available destination > Retry: [dial tcp 173.82.57.8:63012: connect: connection refused] > Retry: all retry attempts failed
2019/11/12 00:37:35 [Warning] [3062346533] App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: failed to find an available destination > Retry: [dial tcp 173.82.57.8:63012: connect: connection refused] > Retry: all retry attempts failed
2019/11/12 00:37:38 [Warning] [2819190609] App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: failed to find an available destination > Retry: [dial tcp 173.82.57.8:63012: connect: connection refused] > Retry: all retry attempts failed
2019/11/12 00:37:38 [Warning] [1698331908] App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: failed to find an available destination > Retry: [dial tcp 173.82.57.8:63012: connect: connection refused] > Retry: all retry attempts failed
2019/11/12 00:37:42 [Warning] [655321571] App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: failed to find an available destination > Retry: [dial tcp 173.82.57.8:63012: connect: connection refused] > Retry: all retry attempts failed
2019/11/12 00:37:43 [Warning] Core: V2Ray v3.26 started
2019/11/12 00:43:24 [Warning] Core: V2Ray v3.26 started
2019/11/12 00:43:29 [Warning] Core: V2Ray v3.26 started
2019/11/12 00:45:54 [Warning] [1409243058] Proxy|HTTP: failed to read response from suconfig.apple.com > io: read/write on closed pipe
2019/11/12 00:45:54 [Warning] [2026804816] Proxy|HTTP: failed to read response from suconfig.apple.com > io: read/write on closed pipe
2019/11/12 00:45:59 [Warning] Core: V2Ray v3.26 started
2019/11/12 00:50:33 [Warning] Core: V2Ray v3.26 started
2019/11/12 00:51:47 [Warning] Core: V2Ray v3.26 started
7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

invalid user
2019/11/11 23:48:15 123.185.154.160:4661 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/11/11 23:48:16 123.185.154.160:4660 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/11/11 23:48:16 123.185.154.160:4663 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/11/11 23:48:17 123.185.154.160:4657 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/11/11 23:48:18 123.185.154.160:4662 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/11/11 23:48:20 123.185.154.160:4664 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/11/11 23:48:22 123.185.154.160:4665 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
2019/11/11 23:48:24 123.185.154.160:4666 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user

8) 其它相关的配置文件（如 Nginx）和相关日志。
？

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。
root@moeko:~# /usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
Configuration OK.

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。
root@moeko:~# journalctl -u v2ray
-- Logs begin at Mon 2019-11-11 17:10:54 CST, end at Mon 2019-11-11 23:52:16 CST
Nov 11 18:12:29 moeko systemd[1]: Stopping V2Ray Service...
Nov 11 18:12:29 moeko systemd[1]: Starting V2Ray Service...
Nov 11 18:12:29 moeko systemd[1]: Started V2Ray Service.
Nov 11 18:12:29 moeko v2ray[9416]: V2Ray 4.21.3 (V2Fly, a community-driven editi
Nov 11 18:12:29 moeko v2ray[9416]: A unified platform for anti-censorship.
lines 1-6/6 (END)

请预览一下你填的内容再提交。

**Comment by vincenlai** [comment]
有没有检查时间是否一致呢？
