### ISSUE TITLE
V2RAY4.21.0及以上版本均不能在斐讯k3上运行，请问该怎么办？

### ISSUE THREAD

**Issue by zxlhhyccc** [v2ray/v2ray-core#2027]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

4) 你期待看到的正确表现是怎样的？

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
```

客户端配置:

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by wclmgcd** [comment]
用大雕源码编译的可以运行啊

**Comment by zxlhhyccc** [comment]
> 用大雕源码编译的可以运行啊

大屌的是4.20.0版本，我提的是4.21.0及以上版本

**Comment by qiang-yu** [comment]
用老版本，必要用新版啊，新版的一些修改你根本用不上，没必要，我现在还用着 4.14.0 呢，稳如狗

**Comment by JoeHoy233** [comment]
4.21.3测试没问题啊

**Comment by zxlhhyccc** [comment]
> 好像是4.21.0以上版本用的go问题，其他issue也提到了，不过我自己用脚本编译可以用
请问你用的哪个脚本？能分享一下吗？

**Comment by JoeHoy233** [comment]
> > 好像是4.21.0以上版本用的go问题，其他issue也提到了，不过我自己用脚本编译可以用
> > 请问你用的哪个脚本？能分享一下吗？

v2的网站有构建说明，我直接用那个脚本弄得，按照说明改一下脚本的参数就可以编译出来了，默认编译出来的需要配合v2ctl使用。
https://www.v2ray.com/developer/intro/compile.html

**Comment by he583899772** [comment]
我用官改的k3,官改的4.14的，我也想着更新，试了很多，无论是自己编译的还是用官方的，官方的只能4.20可以，最后在下面的大佬已经编译好的，最新的可用，但是无法替换官改自带的，显示只读，应该是烧录代码的吧，但是我用mount -o挂载替换，但是重启之后消失，只要把挂载命令放到启动项就行了，以后就自己更新版本了
https://github.com/felix-fly/v2ray-openwrt/releases
v2ray-linux-arm.zip

**Comment by kslr** [comment]
Try 4.22.0
