### ISSUE TITLE
增加outbound的流量统计功能

### ISSUE THREAD

**Issue by supppig** [v2ray/v2ray-core#2029]
看了一下stat的文档，流量统计功能无论是用户流量还是全局流量，都是在inbound触发的。
能不能在outbound处进行流量统计？
有这个需求的主要目的，是想知道每个outbuound走了多少流量，好优化配置。。。

**Comment by etoutools** [comment]
朋友，你的流量统计能根据用户分类吗，我的按照官方的文档配置，只能看到总的流量统计信息，email配了。

**Comment by supppig** [comment]
> 朋友，你的流量统计能根据用户分类吗，我的按照官方的文档配置，只能看到总的流量统计信息，email配了。

我看到不能outbound统计流量（用户也只是在inbound起效），就没有继续研究下去了。解决不到我的痛点。
不过应该可以的吧，功能应该不会失效。

**Comment by ix64** [comment]
> 朋友，你的流量统计能根据用户分类吗，我的按照官方的文档配置，只能看到总的流量统计信息，email配了。

是[本地策略](https://www.v2ray.com/chapter_02/policy.html)里相应的LevelPolicy未配置吧
