### ISSUE TITLE
更新到1.19后彻底无法使用

### ISSUE THREAD

**Issue by zhouzhiwen2000** [v2ray/v2ray-core#203]
日志：客户端：2016/07/12 13:11:53 [Warning]Point: started on port 1081
2016/07/12 13:12:36 [Warning]VMessOut: Failed to read response: EOF
2016/07/12 13:12:44 [Warning]VMessOut: Failed to read response: EOF
2016/07/12 13:12:52 [Warning]VMessOut: Failed to read response: EOF
2016/07/12 13:12:54 [Warning]VMessOut: Failed to read response: EOF
2016/07/12 13:12:56 [Warning]VMessOut: Failed to read response: EOF
2016/07/12 13:13:27 [Warning]VMessOut: Failed to read response: EOF
服务端：
2016/07/04 09:55:56 [Warning]Freedom: Failed to open connection to tcp:140.205.122.66:53: All retry attempts failed.
2016/07/04 09:55:56 [Warning]Freedom: Failed to open connection to tcp:198.11.138.254:53: All retry attempts failed.
2016/07/04 09:56:06 [Warning]Freedom: Failed to open connection to tcp:182.140.167.191:53: All retry attempts failed.
2016/07/04 09:58:32 [Warning]Freedom: Failed to open connection to tcp:wsiwyuwbl:80: All retry attempts failed.
2016/07/04 09:58:32 [Warning]Freedom: Failed to open connection to tcp:bomfyunurkx:80: All retry attempts failed.
2016/07/04 09:58:34 [Warning]Freedom: Failed to open connection to tcp:uklrlayrvc:80: All retry attempts failed.
2016/07/04 09:58:54 [Warning]Freedom: Failed to open connection to tcp:198.11.138.254:53: All retry attempts failed.
2016/07/04 09:58:56 [Warning]Freedom: Failed to open connection to tcp:140.205.122.66:53: All retry attempts failed.
2016/07/04 09:58:56 [Warning]Freedom: Failed to open connection to tcp:198.11.138.254:53: All retry attempts failed.
2016/07/04 09:58:56 [Warning]Freedom: Failed to open connection to tcp:140.205.122.66:53: All retry attempts failed.
2016/07/04 09:59:58 [Warning]Freedom: Failed to open connection to tcp:61.240.144.10:53: All retry attempts failed.
2016/07/04 10:00:02 [Warning]Freedom: Failed to open connection to tcp:61.240.144.10:53: All retry attempts failed.

**Comment by chnt7305** [comment]
不会啊，我昨天刚升级的，但是没有用TLS

**Comment by zhouzhiwen2000** [comment]
已解决

**Comment by chnt7305** [comment]
什么原因呢？
