### ISSUE TITLE
设置路由规则失效，全局走代理。

### ISSUE THREAD

**Issue by azgh** [v2ray/v2ray-core#2031]
macOS Catalina系统的V2Ray-core，出现不能分流，即使设置路由规则，仍全局代理的情况。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V2ray for macOS，homebrew `brew install v2ray-core`，4.23.1版本。
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
代理看YouTube。
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
设置路由规则后，国内网站仍然走代理，而不是直连。
4) 你期待看到的正确表现是怎样的？
根据路由规则，国内网站和ip直连，国外走代理。
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
客户端配置:
```
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPOnDemand",
      "rules": [
        {
          "type": "field",
          "domain": [
            "geosite:cn"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "geoip:cn",
            "geoip:private"
          ],
          "outboundTag": "direct"
        }
      ]
    }
  }
```
两台mac，均如此，不知道是配置的问题，还是程序的问题，请帮忙查看。

**Comment by kingwilliam** [comment]
Outbounds?

**Comment by blackknifes** [comment]
我的为毛开了pac，但还是所有连接都走v2ray。。。。。v2ray一出问题，连国内网站都访问不了

**Comment by kingwilliam** [comment]
请提供client config.json 和 debug log

**Comment by azgh** [comment]
> 如何发现全都是走代理？请提供debug log 和 outbound.

回答问题如下：

1. 使用百度搜索ip，得到自己的ip地址为代理地址;

2. outbound如下:
```
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "###",
            "port": $$$,
            "users": [
              {
                "id": "***",
                "alterId": 64
              },
          {
            "address": "###",
            "port": $$$,
            "users": [
              {
                "id": "***",
                "alterId": 64
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "wsSettings": {
          "path": "/@@@"
        }
      }
    }
  ],
```
3. debug log没找到。

除了不走路由全局走代理外，访问国内国外均正常，以前使用的版本（忘记版本号了）没有路由失效的情况，访问一切正常，最近升级后，出现的问题。

**Comment by kingwilliam** [comment]
看完你的outbound, 真的没freedom tag direct? 还是隐藏了？

**Comment by szwhy** [comment]
遇到了相同的问题，Windows客户端
连192.168.1.1都走代理去了

**Comment by szwhy** [comment]
`{
  "log": {
    "access": "",
    "loglevel": "warning"
  },

  "inbounds": [
	{
	  "port": #####,
	  "listen": "0.0.0.0",
	  "protocol": "socks",
	  "settings": {
	    "auth": "noauth",
		"udp": false,
		"ip": "127.0.0.1",
		"userLevel": 2
      },
	  "tag": "socks",
	  "sniffing": {
	    "enabled": true,
		"destOverride": ["http", "tls"]
	  }
	},
    {
      "port": #####,
      "listen": "0.0.0.0",
      "protocol": "http",
      "settings": {
        "timeout": 0,
	    "allowTransparent": false,
	    "userLevel": 2
      },
	  "tag": "http",
	  "sniffing": {
	    "enabled": true,
		"destOverride": ["http", "tls"]
	  }
    }
  ],

  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "##########",
            "port": #####,
            "users": [
              {
                "id": "###############",
                "alterId": #####,
                "security": "auto"
              }
            ]
          }
        ]
      },
	  "tag": "proxy",
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "wsSettings": {
          "path": "##########"
        }
      },
      "mux": {
        "enabled": false,
		"concurrency": 8
      }
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "adblock"
    }
  ],

  "dns": {
    "hosts": {
	  "nj.baidupcs.com": "127.0.0.1"
	},
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
	  "localhost"
    ]
  },

  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
		"domain": [
		  "geosite:cn"
		],
        "ip": [
          "0.0.0.0/8",
          "10.0.0.0/8",
          "100.64.0.0/10",
          "127.0.0.0/8",
          "169.254.0.0/16",
          "172.16.0.0/12",
          "192.0.0.0/24",
          "192.0.2.0/24",
          "192.168.0.0/16",
          "198.18.0.0/15",
          "198.51.100.0/24",
          "203.0.113.0/24",
          "::1/128",
          "fc00::/7",
          "fe80::/10",
          "geoip:private",
	      "geoip:cn"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "domain": [
		  "geosite:category-ads",
          "geo2.adobe.com"
        ],
        "outboundTag": "adblock"
      }
    ]
  }
}
`

**Comment by szwhy** [comment]
`
{
  "log": {
    "access": "",
    "loglevel": "warning"
  },

  "inbounds": [
	{
	  "port": #####,
	  "listen": "0.0.0.0",
	  "protocol": "socks",
	  "settings": {
	    "auth": "noauth",
		"udp": false,
		"ip": "127.0.0.1",
		"userLevel": 2
      },
	  "tag": "socks",
	  "sniffing": {
	    "enabled": true,
		"destOverride": ["http", "tls"]
	  }
	},
    {
      "port": #####,
      "listen": "0.0.0.0",
      "protocol": "http",
      "settings": {
        "timeout": 0,
	    "allowTransparent": false,
	    "userLevel": 2
      },
	  "tag": "http",
	  "sniffing": {
	    "enabled": true,
		"destOverride": ["http", "tls"]
	  }
    }
  ],

  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "##########",
            "port": #####,
            "users": [
              {
                "id": "###############",
                "alterId": #####,
                "security": "auto"
              }
            ]
          }
        ]
      },
	  "tag": "proxy",
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "wsSettings": {
          "path": "##########"
        }
      },
      "mux": {
        "enabled": false,
		"concurrency": 8
      }
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "adblock"
    }
  ],

  "dns": {
    "hosts": {
	  "nj.baidupcs.com": "127.0.0.1"
	},
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
	  "localhost"
    ]
  },

  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
		"domain": [
		  "geosite:cn"
		],
        "ip": [
          "0.0.0.0/8",
          "10.0.0.0/8",
          "100.64.0.0/10",
          "127.0.0.0/8",
          "169.254.0.0/16",
          "172.16.0.0/12",
          "192.0.0.0/24",
          "192.0.2.0/24",
          "192.168.0.0/16",
          "198.18.0.0/15",
          "198.51.100.0/24",
          "203.0.113.0/24",
          "::1/128",
          "fc00::/7",
          "fe80::/10",
          "geoip:private",
	      "geoip:cn"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "domain": [
		  "geosite:category-ads",
          "geo2.adobe.com"
        ],
        "outboundTag": "adblock"
      }
    ]
  }
}
`

**Comment by szwhy** [comment]
我的客户端配置
```javascript
{
  "log": {
    "access": "",
    "loglevel": "warning"
  },

  "inbounds": [
	{
	  "port": #####,
	  "listen": "0.0.0.0",
	  "protocol": "socks",
	  "settings": {
	    "auth": "noauth",
		"udp": false,
		"ip": "127.0.0.1",
		"userLevel": 2
      },
	  "tag": "socks",
	  "sniffing": {
	    "enabled": true,
		"destOverride": ["http", "tls"]
	  }
	},
    {
      "port": #####,
      "listen": "0.0.0.0",
      "protocol": "http",
      "settings": {
        "timeout": 0,
	    "allowTransparent": false,
	    "userLevel": 2
      },
	  "tag": "http",
	  "sniffing": {
	    "enabled": true,
		"destOverride": ["http", "tls"]
	  }
    }
  ],

  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "##########",
            "port": #####,
            "users": [
              {
                "id": "###############",
                "alterId": #####,
                "security": "auto"
              }
            ]
          }
        ]
      },
	  "tag": "proxy",
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "wsSettings": {
          "path": "##########"
        }
      },
      "mux": {
        "enabled": false,
		"concurrency": 8
      }
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "adblock"
    }
  ],

  "dns": {
    "hosts": {
	  "nj.baidupcs.com": "127.0.0.1"
	},
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
	  "localhost"
    ]
  },

  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
		"domain": [
		  "geosite:cn"
		],
        "ip": [
          "0.0.0.0/8",
          "10.0.0.0/8",
          "100.64.0.0/10",
          "127.0.0.0/8",
          "169.254.0.0/16",
          "172.16.0.0/12",
          "192.0.0.0/24",
          "192.0.2.0/24",
          "192.168.0.0/16",
          "198.18.0.0/15",
          "198.51.100.0/24",
          "203.0.113.0/24",
          "::1/128",
          "fc00::/7",
          "fe80::/10",
          "geoip:private",
	      "geoip:cn"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "domain": [
		  "geosite:category-ads",
          "geo2.adobe.com"
        ],
        "outboundTag": "adblock"
      }
    ]
  }
}
```

**Comment by szwhy** [comment]
debug log

```javascript
2019/11/24 17:15:28 [Info] [1396447410] v2ray.com/core/proxy/socks: TCP Connect request to tcp:192.168.1.1:80
2019/11/24 17:15:28 [Info] [2543901712] v2ray.com/core/proxy/socks: TCP Connect request to tcp:192.168.1.1:80
2019/11/24 17:15:28 [Info] [2543901712] v2ray.com/core/app/dispatcher: sniffed domain: 192.168.1.1
2019/11/24 17:15:28 [Info] [2543901712] v2ray.com/core/app/dispatcher: default route for tcp:192.168.1.1:80
2019/11/24 17:15:28 [Info] [2543901712] v2ray.com/core/transport/internet/websocket: creating connection to tcp:我的服务器地址:端口
2019/11/24 17:15:28 tcp:127.0.0.1:52858 accepted tcp:192.168.1.1:80 [proxy]
2019/11/24 17:15:28 [Info] [1396447410] v2ray.com/core/app/dispatcher: default route for tcp:192.168.1.1:80
2019/11/24 17:15:28 [Info] [1396447410] v2ray.com/core/transport/internet/websocket: creating connection to tcp:我的服务器地址:端口
2019/11/24 17:15:28 tcp:127.0.0.1:52857 accepted tcp:192.168.1.1:80 [proxy]
2019/11/24 17:15:28 [Info] [1396447410] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:192.168.1.1:80 via tcp:我的服务器地址:端口
2019/11/24 17:15:29 [Info] [2543901712] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:192.168.1.1:80 via tcp:我的服务器地址:端口
2019/11/24 17:15:29 [Info] [1396447410] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > websocket: close 1000 (normal)
2019/11/24 17:15:29 [Info] [1396447410] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2019/11/24 17:15:29 [Info] [2543901712] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > websocket: close 1000 (normal)
2019/11/24 17:15:29 [Info] [2543901712] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2019/11/24 17:15:29 [Info] [3667022046] v2ray.com/core/proxy/socks: TCP Connect request to tcp:192.168.1.1:80
2019/11/24 17:15:29 [Info] [3667022046] v2ray.com/core/app/dispatcher: sniffed domain: 192.168.1.1
2019/11/24 17:15:29 [Info] [3667022046] v2ray.com/core/app/dispatcher: default route for tcp:192.168.1.1:80
2019/11/24 17:15:29 [Info] [3667022046] v2ray.com/core/transport/internet/websocket: creating connection to tcp:我的服务器地址:端口
2019/11/24 17:15:29 tcp:127.0.0.1:52862 accepted tcp:192.168.1.1:80 [proxy]
2019/11/24 17:15:29 [Info] [3667022046] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:192.168.1.1:80 via tcp:我的服务器地址:端口
2019/11/24 17:15:29 [Info] [3667022046] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > websocket: close 1000 (normal)
2019/11/24 17:15:29 [Info] [3667022046] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
```

**Comment by szwhy** [comment]
> 请提供client config.json 和 debug log

能否麻烦您看一下，感谢

**Comment by szwhy** [comment]
@kingwilliam 
能否麻烦您看一下，感谢

**Comment by azgh** [comment]
> 看完你的outbound, 真的没freedom tag direct? 还是隐藏了？

@kingwilliam 路由规则在上面，没有freedom，有direct的tag，所有的outbund规则由一楼和五楼组成，没有隐藏。

**Comment by kingwilliam** [comment]
> > 看完你的outbound, 真的没freedom tag direct? 还是隐藏了？
> 
> @kingwilliam 路由规则在上面，没有freedom，有direct的tag，所有的outbund规则由一楼和五楼组成，没有隐藏。

```
	"outbounds": [
		{
			"protocol": "vmess",
				"settings": {
					...
			}
		},
		// 在原始outbounds内, vmess後, 加入以下代码
		{
			"tag": "direct",
			"protocol": "freedom",
			"settings": {}
		}
	],
```

**Comment by azgh** [comment]
@kingwilliam 感谢，按照您的配置，问题解决了。
