### ISSUE TITLE
请求添加前置代理功能！

### ISSUE THREAD

**Issue by Ren9527** [v2ray/v2ray-core#2033]
需要多层代理，但v2ray不像SSR那样能设置前置代理，很不方便！请求开发者添加该功能

**Comment by wangshengxin1998** [comment]
https://guide.v2fly.org/advanced/outboundproxy.html#%E5%9F%BA%E6%9C%AC%E4%BB%A3%E7%90%86%E8%BD%AC%E5%8F%91

这里有前置代理的配置文件,只是GUI还没有适配,需要手动写配置文件

**Comment by kslr** [comment]
https://github.com/v2fly/v2ray-step-by-step/blob/dev/app/parent.md
