### ISSUE TITLE
send_through功能支持分别指定ipv4和ipv6地址

### ISSUE THREAD

**Issue by emiyalee1005** [v2ray/v2ray-core#2035]
场景是这样的，服务器的有多个ipv4和ipv6地址，然后我想单独为某个账号指定一条出站规则，如果访问的域名支持ipv6，则以指定的ipv6地址出站访问，否则以指定的ipv4地址访问。

但是目前send_through参数只支持指定一个ip地址，无法做到分别区分指定ipv4和ipv6地址。目前的建议是增加两个参数send_through_ipv4和send_through_ipv6，然后优先匹配使用iipv6

**Comment by cnsilvan** [comment]
内置dns解决。

**Comment by eycorsican** [comment]
可以配置两个除 tag 和 和 send_through 外其它参数一致的 outbound，一个 ipv4，一个 ipv6，然后路由相应流量到相应 outbound。

**Comment by emiyalee1005** [comment]
> 可以配置两个除 tag 和 和 send_through 外其它参数一致的 outbound，一个 ipv4，一个 ipv6，然后路由相应流量到相应 outbound。

那路由配置里怎么区分ip4和6的流量
