### ISSUE TITLE
服务器端可以自动更新吗？还是必须卸载后重装？

### ISSUE THREAD

**Issue by qingfengshi** [v2ray/v2ray-core#204]
如题，不知道服务器端版本是不是可以自动更新，或者使用某一命令进行更新？

**Comment by Talent30** [comment]
bash <(curl -L -s https://raw.githubusercontent.com/v2ray/v2ray-core/master/release/install-release.sh)

**Comment by v2ray** [comment]
自动更新话，可以配置 crontab 定时运行上述脚本
