### ISSUE TITLE
config.json 有支持 文件包含 吗

### ISSUE THREAD

**Issue by ghostry** [v2ray/v2ray-core#2047]
比如 outbounds配置了20个服务器,他们属于2个balancers,

然后要配置4个配置文件,他们使用相同的outbounds和balancers,但是有不同的rules.

这个时候,如果单独配置,每个json文件都写outbounds和balancers,就非常麻烦,有几个config.json文件就要维护多少份,

如果有文件包含,用起来就方便很多.只维护一份outbounds和balancers,

功能类似caddy的 import ,nginx的include.

比如在caddy创建多网站,可以在主配置文件用 `import /caddy/conf/vhosts/*.conf`引入多个网站配置文件.

v2ray希望可以在主配置文件引入其他文件定义的outbounds,balancers这些,以方便维护.

**Comment by kslr** [comment]
这个需求比较小众，会给普通用户带来麻烦，建议自己实现
