### ISSUE TITLE
最近是不是墙升级了，v2ray用不了

### ISSUE THREAD

**Issue by oldedifier** [v2ray/v2ray-core#2051]
我是按照这个教程 [搭建的V2ray服务](https://github.com/xiaoming2028/FreeNet/wiki/) ，但是家里的宽带不定期阻断所有国际连接，查看日志发现自建的三个 V2ray 同时无法连接（其中一个 [V2ray 服务器](https://affiliates.hostwinds.com/hostwinds.php?id=7011&tid2=github&url=1216) 已经用了快两年了），又在几分钟后同时恢复，只不过一开始延迟超级高

无法连接 V2ray 服务器期间，其他没有被墙的国外网站也无法访问，有人情况和我一样吗？

**Comment by sixgod21** [comment]
我是在大流量后，突然断流。并且PING不通服务器，也无法SSH 连接服务器。但是用ping.chinaz.com 测试这台服务器还能Ping通，我的这个情况感觉像是本地运营商的问题。其他线路暂时没影响。

**Comment by hypasc** [comment]
好像是滴哎,好多都有这种情况

**Comment by mrwtong** [comment]
tcp换成kcp暂时解决了这个问题

**Comment by redstoneleo** [comment]
> 我是在大流量后，突然断流。并且PING不通服务器，也无法SSH 连接服务器。但是用ping.chinaz.com 测试这台服务器还能Ping通，我的这个情况感觉像是本地运营商的问题。其他线路暂时没影响。
我的情况和你的一样，开始看YouTube的时候一会儿就断了，但是过几分钟就又恢复

**Comment by redstoneleo** [comment]
@hypasc 你怎么知道“好多都是这种情况”的？

**Comment by hypasc** [comment]
因为好多个群里好多人都在说------------------ 原始邮件 ------------------
发件人: "redstoneleo"<notifications@github.com>
发送时间: 2019年11月26日(星期二) 凌晨0:10
收件人: "v2ray/v2ray-core"<v2ray-core@noreply.github.com>;
抄送: "hyp"<hypasc@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [v2ray/v2ray-core] 最近是不是墙升级了，v2ray用不了 (#2051)



@hypasc 你怎么知道“好多都是这种情况”的？
 
&mdash;

**Comment by hypasc** [comment]
或许只是我了解到的群吧，不想争------------------ 原始邮件 ------------------
发件人: "redstoneleo"<notifications@github.com>
发送时间: 2019年11月26日(星期二) 凌晨0:10
收件人: "v2ray/v2ray-core"<v2ray-core@noreply.github.com>;
抄送: "hyp"<hypasc@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [v2ray/v2ray-core] 最近是不是墙升级了，v2ray用不了 (#2051)



@hypasc 你怎么知道“好多都是这种情况”的？
 
&mdash;

**Comment by redstoneleo** [comment]
大家能报一下出现这种问题的主机商和套餐吗？我的是亚马逊lightsail 3.5美元的套餐，之前用EC2没碰到过这种问题

**Comment by mrwtong** [comment]
> 大家能报一下出现这种问题的主机商和套餐吗？我的是亚马逊lightsail 3.5美元的套餐，之前用EC2没碰到过这种问题

GCP HK
周一出现这个问题
