### ISSUE TITLE
关于 V2Ray 随机出口

### ISSUE THREAD

**Issue by ghost** [v2ray/v2ray-core#2053]
最近墙的策略更新，当与境外 IP 交互流量到达一定体积时会封禁几分钟（或断流），测试将流量切分变小有较好效果：

1.  客户端连接境内支持 IPv6 的中转机的 IPv4 地址；
2. 中转机使用一个随机的 IPv6 地址连接服务端的一个随机的 IPv6 地址；
3. 最后，服务端使用 IPv4 地址将流量放松出去。

但有一个问题，中转机的每一个出口对象都需配置详细内容且 IPv6 地址数量一般很多，导致配置非常麻烦。不知道能不能设计一个新功能：

- 出口地址类型为字符串时，与当前无异；
- 出口地址类型为数组时，随机使用数组内的某一地址。

**Comment by m1heng** [comment]
分流其实可以走负载均衡，但是目前缺少一个较好的分流策略。
比如像你所说的随机选择一个（也就意味着全时段随机），如果有一个不可用地址或一个不可用服务器，很有可能会造成客户端产生网络不稳定的情况。

**Comment by neetnux** [comment]
> 分流其实可以走负载均衡，但是目前缺少一个较好的分流策略。
> 比如像你所说的随机选择一个（也就意味着全时段随机），如果有一个不可用地址或一个不可用服务器，很有可能会造成客户端产生网络不稳定的情况。

是的，其实我就是这个意思，不稳定的这个情况是存在的，但是这是使用者的问题，而且这个问题大概在负载均衡里也是存在的。

**Comment by m1heng** [comment]
> > 分流其实可以走负载均衡，但是目前缺少一个较好的分流策略。
> > 比如像你所说的随机选择一个（也就意味着全时段随机），如果有一个不可用地址或一个不可用服务器，很有可能会造成客户端产生网络不稳定的情况。
> 
> 是的，其实我就是这个意思，不稳定的这个情况是存在的，但是这是使用者的问题，而且这个问题大概在负载均衡里也是存在的。

#1924 可以关注一下这个PR，这里正在初步尝试制作一个新的负载均衡策略，但我的意见是能不能做成插件化，所有人都可以开发自己的策略并共享给大家。

**Comment by neetnux** [comment]
> > > 分流其实可以走负载均衡，但是目前缺少一个较好的分流策略。
> > > 比如像你所说的随机选择一个（也就意味着全时段随机），如果有一个不可用地址或一个不可用服务器，很有可能会造成客户端产生网络不稳定的情况。
> > 
> > 
> > 是的，其实我就是这个意思，不稳定的这个情况是存在的，但是这是使用者的问题，而且这个问题大概在负载均衡里也是存在的。
> 
> #1924 可以关注一下这个PR，这里正在初步尝试制作一个新的负载均衡策略，但我的意见是能不能做成插件化，所有人都可以开发自己的策略并共享给大家。

想到一种办法，通过 DNS 做随机出口或负载均衡。在 v2ray 配置里添加一个自己的 DNS server，当出口设置为某个指定的域名时，每次 DNS server 解析的结果是变化的。至于这个变化的规则，就可以较为简单的通过自己的代码来实现了，这样侵入性还比较小。

**Comment by forever8938** [comment]
如果墙这样封IP，什么手段都没用。
