### ISSUE TITLE
增加websocket压缩功能 pls.

### ISSUE THREAD

**Issue by xqdoo00o** [v2ray/v2ray-core#2054]
尽管[upstream](https://godoc.org/github.com/gorilla/websocket#hdr-Compression_EXPERIMENTAL) 仅是实验性功能，这个功能还是值得添加上，毕竟对于大数据包 应该还是有些用处的。

**Comment by speedyworldclub** [comment]
关注

**Comment by okudayukiko** [comment]
望增加TCP/WebSocket压缩。可以选择压缩算法和压缩程度。
