### ISSUE TITLE
安装V2ray时网络断开，重装时提示已安装，其他命令又不可用

### ISSUE THREAD

**Issue by people-m** [v2ray/v2ray-core#2061]
使用代码：bash <(curl -L -s https://install.direct/go.sh) 安装时突然断网，然后V2ray就无法操作了
VPS系统是：CentOS Linux 7.3.
使用的相关代码见下方内容

[root@calm-nerds-1 ~]# bash <(curl -L -s https://install.direct/go.sh)
Latest version v4.21.3 is already installed.
[root@calm-nerds-1 ~]# v2ray info
-bash: v2ray: command not found
[root@calm-nerds-1 ~]# v2ray uninstall
-bash: v2ray: command not found
[root@calm-nerds-1 ~]# v2ray status
-bash: v2ray: command not found
[root@calm-nerds-1 ~]# ^C

现在无法重装和卸载，也无法进行其他操作，谷歌上也没找到类似情况说明

**Comment by kslr** [comment]
把系统重装了不就好了

**Comment by people-m** [comment]
我装的有其他东西，想知道有没有不用重装系统的方法

**Comment by people-m** [comment]
我装的有其他东西，想知道有没有不用重装系统的方法

**Comment by Cwek** [comment]
把脚本下载下来，强制安装一次，或者直接到/usr/bin/v2ray/ 文件夹检查文件，或者删掉。

**Comment by Cwek** [comment]
> [root@calm-nerds-1 ~]# v2ray info
>-bash: v2ray: command not found
>[root@calm-nerds-1 ~]# v2ray uninstall
>-bash: v2ray: command not found
>[root@calm-nerds-1 ~]# v2ray status

另外v2ray里面没有这些命令的

**Comment by people-m** [comment]
> > [root@calm-nerds-1 ~]# v2ray info
> > -bash: v2ray: command not found
> > [root@calm-nerds-1 ~]# v2ray uninstall
> > -bash: v2ray: command not found
> > [root@calm-nerds-1 ~]# v2ray status
> 
> 另外v2ray里面没有这些命令的

我在233的教程里面看到的，我最开始安装的就是233一键脚本。我还以为这些命令是通用的！

**Comment by forever8938** [comment]
别用第三方脚本

**Comment by Cwek** [comment]
请手动安装手写脚本，只有官方组提供的安装脚本。
不会写配置脚本，学别人玩什么Linux。

**Comment by ileeoyo** [comment]
v2ray自身没有这些安装管理命令。可以用下官方有个一键安装脚本安装下。v2ray理论上只有一个core执行文件和一个config文件有用，其实手动拷贝到服务器也可以

**Comment by kslr** [comment]
只需要删除/usr/bin/v2ray/目录和systemd文件就可以了
