### ISSUE TITLE
软路由DNS被墙网站解析无响应

### ISSUE THREAD

**Issue by misswolf** [v2ray/v2ray-core#2065]
提交 Issue 之前请先阅读 Issue 指引，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用Discussion进行讨论。

1 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
 客户端 V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) OpenWrt - Release 1

2 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
 在虚拟机里安装openwrt作为软路由使用，curl -x socks5://192.168.1.18:10808 facebook.com -v 正常，但 dig facebook.com @192.168.1.18无返回

3 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
	直接使用代理端口上网正常，配置dnsmasq把指定的域名解析转发,没有得到响应

4 你期待看到的正确表现是怎样的？
  期待正常响应被墙的DNS解析，返回无污染的解析解果

5 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

6 服务器端配置:
 
7 客户端配置:
 {
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "debug"
  },
  "inbounds": [
    {
      "tag":"dns-in",
      "port": 5353,
      "protocol": "dokodemo-door",
      "settings": {
        "network": "tcp,udp",
        "followRedirect": true
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "streamSettings": {
        "sockopt": {
		  "mark": 100,
		  "tcpFastOpen": true,
          "tproxy": "tproxy" 
        }
      }
    },
    {
	  "tag": "proxy",
      "port": 10808, 
      "protocol": "socks", 
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
      "settings": {
        "auth": "noauth"
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",  
      "settings": {
        "vnext": [
		  {
            "address": "x.x.x.x",
            "port": x,
            "users": [
              {
                "id": "xxxx",
                "alterId": 0,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "sockopt": {
          "mark": 255
        }
      },
      "mux": {
        "enabled": true
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP"
      },
      "streamSettings": {
        "sockopt": {
          "mark": 255
        }
      }      
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    },
    {
      "tag": "dns-out",
      "protocol": "dns",
      "streamSettings": {
        "sockopt": {
          "mark": 255
        }
      }  
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",  
      "1.1.1.1",  
      "114.114.114.114", 
      {
        "address": "223.5.5.5", 
        "port": 53,
        "domains": [
          "geosite:cn",
          "ntp.org"
        ]
      }
    ]
  },
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {  
        "type": "field",
        "inboundTag": [
          "dns-in"
        ],
        "port": 5353,
        "network": "udp",
        "outboundTag": "dns-out" 
      },    
      {  
        "type": "field",
        "inboundTag": [
          "dns-in"
        ],
        "port": 123,
        "network": "udp",
        "outboundTag": "direct" 
      },    
      {
        "type": "field", 
        "ip": [ 
          "223.5.5.5",
          "114.114.114.114"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": [ 
          "8.8.8.8",
          "1.1.1.1"
        ],
        "outboundTag": "proxy"  
      },
      { 
        "type": "field", 
        "domain": [
          "geosite:category-ads-all"
        ],
        "outboundTag": "block"
      },
      { 
        "type": "field",
        "protocol":["bittorrent"], 
        "outboundTag": "direct"
      },
      {  
        "type": "field", 
        "ip": [
          "geoip:private",
          "geoip:cn"
        ],
        "outboundTag": "direct"
      },
      { 
        "type": "field", 
        "domain": [
          "geosite:cn"
        ],
        "outboundTag": "direct"
      }
    ]
  }
}
8 请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 /var/log/v2ray/error.log 文件中。
服务器端错误日志:

无

客户端错误日志:

2019/11/29 03:52:44 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:192.168.1.18:5353
2019/11/29 03:52:44 [Debug] [2087477094] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.1.39:61485
2019/11/29 03:52:44 [Info] [2087477094] v2ray.com/core/transport/internet: failed to bind source address to [192 168 1 18] > address already in use
2019/11/29 03:52:44 [Info] [2087477094] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:192.168.1.18:5353]
2019/11/29 03:52:44 [Info] [2087477094] v2ray.com/core/proxy/dns: handling DNS traffic to udp:192.168.1.18:5353
2019/11/29 03:52:44 [Debug] v2ray.com/core/app/dns: querying DNS for: facebook.com.
2019/11/29 03:52:44 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:8.8.8.8:53
2019/11/29 03:52:44 [Info] v2ray.com/core/transport/internet/udp: establishing new connection for udp:8.8.8.8:53
2019/11/29 03:52:44 [Info] v2ray.com/core/app/dispatcher: taking detour [proxy] for [udp:8.8.8.8:53]
2019/11/29 03:52:44 [Info] v2ray.com/core/common/mux: dispatching request to udp:8.8.8.8:53
2019/11/29 03:52:44 [Info] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:x.x.x.x:x
2019/11/29 03:52:44 [Info] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:v1.mux.cool:9527 via tcp:x.x.x.x:x
2019/11/29 03:52:44 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > read tcp 192.168.1.18:50766->x.x.x.x:x: read: connection reset by peer
2019/11/29 03:52:44 [Info] v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2019/11/29 03:52:44 [Info] v2ray.com/core/transport/internet/udp: failed to handle UDP input > EOF
2019/11/29 03:52:46 [Info] [2261353391] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > context canceled
2019/11/29 03:52:48 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain facebook.com at server udp:8.8.8.8:53 > context deadline exceeded
2019/11/29 03:52:48 [Debug] v2ray.com/core/app/dns: querying DNS for: facebook.com.
2019/11/29 03:52:48 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:1.1.1.1:53
2019/11/29 03:52:48 [Info] v2ray.com/core/transport/internet/udp: establishing new connection for udp:1.1.1.1:53
2019/11/29 03:52:48 [Info] v2ray.com/core/app/dispatcher: taking detour [proxy] for [udp:1.1.1.1:53]
2019/11/29 03:52:48 [Info] v2ray.com/core/common/mux: dispatching request to udp:1.1.1.1:53
2019/11/29 03:52:48 [Info] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:x.x.x.x:x
2019/11/29 03:52:48 [Info] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:v1.mux.cool:9527 via tcp:x.x.x.x:x
2019/11/29 03:52:48 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > read tcp 192.168.1.18:50768->x.x.x.x:x: read: connection reset by peer
2019/11/29 03:52:48 [Info] v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2019/11/29 03:52:48 [Info] v2ray.com/core/transport/internet/udp: failed to handle UDP input > EOF
2019/11/29 03:52:49 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:192.168.1.18:5353
2019/11/29 03:52:49 [Debug] v2ray.com/core/app/dns: querying DNS for: facebook.com.
2019/11/29 03:52:49 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:8.8.8.8:53
2019/11/29 03:52:49 [Info] v2ray.com/core/transport/internet/udp: establishing new connection for udp:8.8.8.8:53
2019/11/29 03:52:49 [Info] v2ray.com/core/app/dispatcher: taking detour [proxy] for [udp:8.8.8.8:53]
2019/11/29 03:52:49 [Info] v2ray.com/core/common/mux: dispatching request to udp:8.8.8.8:53
2019/11/29 03:52:49 [Info] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:x.x.x.x:x
2019/11/29 03:52:49 [Info] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:v1.mux.cool:9527 via tcp:x.x.x.x:x
2019/11/29 03:52:49 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > read tcp 192.168.1.18:50770->x.x.x.x:x: read: connection reset by peer
2019/11/29 03:52:49 [Info] v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2019/11/29 03:52:49 [Info] v2ray.com/core/transport/internet/udp: failed to handle UDP input > EOF
2019/11/29 03:52:52 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain facebook.com at server udp:1.1.1.1:53 > context deadline exceeded
2019/11/29 03:52:53 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain facebook.com at server udp:8.8.8.8:53 > context deadline exceeded
2019/11/29 03:52:53 [Debug] v2ray.com/core/app/dns: querying DNS for: facebook.com.
2019/11/29 03:52:53 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:1.1.1.1:53
2019/11/29 03:52:53 [Info] v2ray.com/core/transport/internet/udp: establishing new connection for udp:1.1.1.1:53
2019/11/29 03:52:53 [Info] v2ray.com/core/app/dispatcher: taking detour [proxy] for [udp:1.1.1.1:53]
2019/11/29 03:52:53 [Info] v2ray.com/core/common/mux: dispatching request to udp:1.1.1.1:53
2019/11/29 03:52:53 [Info] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:x.x.x.x:x
2019/11/29 03:52:53 [Info] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:v1.mux.cool:9527 via tcp:x.x.x.x:x
2019/11/29 03:52:53 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > read tcp 192.168.1.18:50772->x.x.x.x:x: read: connection reset by peer
2019/11/29 03:52:53 [Info] v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2019/11/29 03:52:53 [Info] v2ray.com/core/transport/internet/udp: failed to handle UDP input > EOF
2019/11/29 03:52:54 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:192.168.1.18:5353
2019/11/29 03:52:54 [Debug] v2ray.com/core/app/dns: querying DNS for: facebook.com.
2019/11/29 03:52:54 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:8.8.8.8:53
2019/11/29 03:52:54 [Info] v2ray.com/core/transport/internet/udp: establishing new connection for udp:8.8.8.8:53
2019/11/29 03:52:54 [Info] v2ray.com/core/app/dispatcher: taking detour [proxy] for [udp:8.8.8.8:53]
2019/11/29 03:52:54 [Info] v2ray.com/core/common/mux: dispatching request to udp:8.8.8.8:53
2019/11/29 03:52:54 [Info] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:x.x.x.x:x
2019/11/29 03:52:54 [Info] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:v1.mux.cool:9527 via tcp:x.x.x.x:x
2019/11/29 03:52:54 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > read tcp 192.168.1.18:50774->x.x.x.x:x: read: connection reset by peer
2019/11/29 03:52:54 [Info] v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2019/11/29 03:52:54 [Info] v2ray.com/core/transport/internet/udp: failed to handle UDP input > EOF
2019/11/29 03:52:57 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain facebook.com at server udp:1.1.1.1:53 > context deadline exceeded
2019/11/29 03:52:58 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain facebook.com at server udp:8.8.8.8:53 > context deadline exceeded
2019/11/29 03:52:58 [Debug] v2ray.com/core/app/dns: querying DNS for: facebook.com.
2019/11/29 03:52:58 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:1.1.1.1:53
2019/11/29 03:52:58 [Info] v2ray.com/core/transport/internet/udp: establishing new connection for udp:1.1.1.1:53
2019/11/29 03:52:58 [Info] v2ray.com/core/app/dispatcher: taking detour [proxy] for [udp:1.1.1.1:53]
2019/11/29 03:52:58 [Info] v2ray.com/core/common/mux: dispatching request to udp:1.1.1.1:53
2019/11/29 03:52:58 [Info] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:x.x.x.x:x
2019/11/29 03:52:58 [Info] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:v1.mux.cool:9527 via tcp:x.x.x.x:x
2019/11/29 03:52:58 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > read tcp 192.168.1.18:50776->x.x.x.x:x: read: connection reset by peer
2019/11/29 03:52:58 [Info] v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2019/11/29 03:52:58 [Info] v2ray.com/core/transport/internet/udp: failed to handle UDP input > EOF
2019/11/29 03:53:02 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain facebook.com at server udp:1.1.1.1:53 > context deadline exceeded
2019/11/29 03:53:18 [Info] [2087477094] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > context canceled

请附上访问日志。在 Linux 中，日志通常在 /var/log/v2ray/access.log 文件中。

其它相关的配置文件（如 Nginx）和相关日志。
无

如果 V2Ray 无法启动，请附上 --test 输出。
通常的命令为 /usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json。请按实际情况修改。

如果 V2Ray 服务运行不正常，请附上 journal 日志。
通常的命令为 journalctl -u v2ray。

请预览一下你填的内容再提交。

**Comment by kslr** [comment]
read tcp 192.168.1.18:50768->x.x.x.xx read: connection reset by peer

**Comment by misswolf** [comment]
服务器不支持DNS包？通过它上被墙的网站是正常的

**Comment by kslr** [comment]
不，这看起来是你的局域网ip 这哪来的

**Comment by misswolf** [comment]
2019/11/29 03:52:58 [Debug] v2ray.com/core/app/dns: querying DNS for: facebook.com.
2019/11/29 03:52:58 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:1.1.1.1:53
2019/11/29 03:52:58 [Info] v2ray.com/core/transport/internet/udp: establishing new connection for udp:1.1.1.1:53
2019/11/29 03:52:58 [Info] v2ray.com/core/app/dispatcher: taking detour [proxy] for [udp:1.1.1.1:53]
2019/11/29 03:52:58 [Info] v2ray.com/core/common/mux: dispatching request to udp:1.1.1.1:53
2019/11/29 03:52:58 [Info] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:x.x.x.x:x
2019/11/29 03:52:58 [Info] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:v1.mux.cool:9527 via tcp:x.x.x.x:x
2019/11/29 03:52:58 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > read tcp 192.168.1.18:50776->x.x.x.x❌ read: connection reset by peer

这个流程是DNS查询facebook.com,发送数据UDP包到1.1.1.1:53 ，transport把请求转换为TCP请求V2RAY服务器，read tcp 192.168.1.18:50776->x.x.x.x❌ read: connection reset by peer， 软路由(192.168.1.18:50776)-->V2RAY服务器发生了连接被重置
正常FQ请求curl -x socks5://192.168.1.18:10808 facebook.com -v 
下面日志是正常的
2019/11/29 07:46:13 [Info] [2909475604] v2ray.com/core/proxy/socks: TCP Connect request to tcp:93.46.8.89:80
2019/11/29 07:46:13 [Info] [2909475604] v2ray.com/core/app/dispatcher: sniffed domain: facebook.com
2019/11/29 07:46:13 [Debug] v2ray.com/core/app/dns: querying DNS for: facebook.com.
2019/11/29 07:46:13 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:8.8.8.8:53
2019/11/29 07:46:13 [Info] v2ray.com/core/transport/internet/udp: establishing new connection for udp:8.8.8.8:53
2019/11/29 07:46:13 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:8.8.8.8:53
2019/11/29 07:46:13 [Info] v2ray.com/core/app/dispatcher: taking detour [proxy] for [udp:8.8.8.8:53]
2019/11/29 07:46:13 [Info] v2ray.com/core/common/mux: dispatching request to udp:8.8.8.8:53
2019/11/29 07:46:13 [Info] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:144.202.77.121:21000
2019/11/29 07:46:13 [Info] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:v1.mux.cool:9527 via tcp:144.202.77.121:21000
2019/11/29 07:46:13 [Debug] v2ray.com/core/app/dns: updating IP records for domain:facebook.com.
2019/11/29 07:46:13 [Debug] v2ray.com/core/app/dns: updating IP records for domain:facebook.com.
2019/11/29 07:46:13 [Info] [2909475604] v2ray.com/core/app/dispatcher: default route for tcp:facebook.com:80
2019/11/29 07:46:13 [Info] [2909475604] v2ray.com/core/common/mux: dispatching request to tcp:facebook.com:80

**Comment by sorrygfw** [comment]
同样的配置运行在PC端，dns能解析吗？
在ubuntu里可以输入nslookup看解析的dns
nslookup回车
再输入
server 127.0.0.1 (inbound dns-in listen地址）
set port=5353
www.facebook.com

**Comment by johnrosen1** [comment]
https://www.johnrosen1.com/ubuntu-router/ 非本机dns解析得开一个任意门
