### ISSUE TITLE
v2ray+WS+TLS+nginx反代，忽然連不上。

### ISSUE THREAD

**Issue by i553041** [v2ray/v2ray-core#2073]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

4.21.3

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

V2ray+WS+TLS+NGINX(CDN)進行科學上網

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

使用Cloudflare的CDN，即是點亮橙雲，正常，但當不使用CDN，灰雲時，卻無論如何都無法使用WS+TLS+NGINX，之前一直都可以，我沒動過任何設定，大約是一個星期前，突然出問題，即是使用CDN，正常，不使用CDN，完全連不上。初時以為是證書出事，已經重新建立一個host，使用let'sencrypt再次建立證書，在瀏覽器上輸入我新建立的host，能用https連上，「表面上」，有一個正常的網站，而且連上https://h2.mysite.com/websocket，還會顯示Bad Request，但當用小火箭連接我新開的那個host就無法再上網了。

IP沒被牆，如果被牆了，那我也不能用瀏覧器以https連上我新開的host。

4) 你期待看到的正确表现是怎样的？

不使用CDN都能連上。因為CDN太慢了。

亦即是使用WS+TLS+NGINX直連。

(以前一直都可以，就是不知道為甚麼忽然會連不上。)

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
   {
	"routing":{
		"settings":{
			"rules":[
				{
					"ip":[
						"0.0.0.0/8",
						"10.0.0.0/8",
						"100.64.0.0/10",
						"127.0.0.0/8",
						"169.254.0.0/16",
						"172.16.0.0/12",
						"192.0.0.0/24",
						"192.0.2.0/24",
						"192.168.0.0/16",
						"198.18.0.0/15",
						"198.51.100.0/24",
						"203.0.113.0/24",
						"::1/128",
						"fc00::/7",
						"fe80::/10"
					],
					"type":"field",
					"outboundTag":"blocked"
				}
			]
		},
		"rules":[
			{
				"inboundTag":[
					"api"
				],
				"type":"field",
				"outboundTag":"api"
			}
		],
		"strategy":"rules"
	},
	"log":{
		"access":"/var/log/v2ray_access.log",
		"loglevel":"debug",
		"error":"/var/log/v2ray_error.log"
	},
"stats": {},
"api": {
		"tag": "api",
		"services": [
			"HandlerService",
			"LoggerService",
			"StatsService"
		]
	},
"policy": {
		"levels": {
			"0": {
				"statsUserUplink": true,
				"statsUserDownlink": true
			}
		},
		"system": {
			"statsInboundUplink": true,
			"statsInboundDownlink": true
		}
	},
	"inbound":{
		"settings":{
			"clients":[
				{
					"email": "user1@user.com",
					"security":"none",
					"level": 0,
					"id":"UUID-1",
					"alterId":64
				},
                                {
         				 "email": "user2@user.com",
					 "id": "UUID-2",
         				 "level": 0,
         				 "alterId": 64
       			        },
				{
                                         "email": "user3@user.com",
					 "id": "UUID-3",
                                         "level": 0,
                                         "alterId": 64
                                },
				{
                                         "email": "user4@user.com",
					 "id": "UUID-4",
                                         "level": 0,
                                         "alterId": 64
                                },
				{
                                         "email": "user5@user.com",
					 "id": "UUID-5",
                                         "level": 0,
                                         "alterId": 64
                                },
				{
					 "email": "user6@user.com",
                                         "id": "UUID-6",
                                         "level": 0,
                                         "alterId": 64
                                },
 				{
					 "email": "user7@user.com",
                                         "id": "UUID-7",
                                         "level": 0,
                                         "alterId": 64
                                },
				{
                                         "email": "user8@user.com",
                                         "id": "UUID-8",
                                         "level": 0,
                                         "alterId": 64
                                },
				{
                                         "email": "user9@user.com",
                                         "id": "UUID-9",
                                         "level": 0,
                                         "alterId": 64
                                }
			]
		},
		"protocol":"vmess",
		"allocate":{
			"strategy":"always"
		},
		"port":17031,
		"streamSettings":{
			"wsSettings":{
				"path":"/websocket",
				"connectionReuse":false
			},
			"network":"ws"
		},
		"listen":"127.0.0.1"
	},
	"stats":{},
	"outbound":{
		"settings":{},
		"protocol":"freedom"
	},
	"api":{
		"tag":"api",
		"services":[
			"HandlerService",
			"LoggerService",
			"StatsService"
		]
	},
	"inbounds":[
		{
			"settings":{
				"address":"127.0.0.1"
			},
			"protocol":"dokodemo-door",
			"port":42757,
			"tag":"api",
			"listen":"127.0.0.1"
		}
	],
	"outboundDetour":[
		{
			"settings":{},
			"protocol":"blackhole",
			"tag":"blocked"
		}
	],
	"policy":{
		"system":{
			"statsInboundUplink":true,
			"statsInboundDownlink":true
		}
	}
}
```

客户端配置: (Shadowrocket) 

```javascript
{
  "method" : "none",
  "uuid" : "UUID-1",
  "file" : "\/websocket",
  "updated" : 1575212050.343178,
  "plugin" : "none",
  "weight" : 1575211761,
  "tls" : true,
  "host" : "h2.mysite.com",
  "type" : "Vmess",
  "flag" : "HK",
  "password" : "UUID-1",
  "created" : 1575211761.702858,
  "obfs" : "websocket",
  "obfsParam" : "",
  "port" : 443
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
2019/12/01 22:46:53 [Info] [2292256513] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: failed to transfer request > websocket: close 1006 (abnormal closure): unexpected EOF
2019/12/01 22:46:53 [Info] [2292256513] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > v2ray.com/core/proxy/freedom: failed to process request > io: read/write on closed pipe
2019/12/01 22:46:54 [Info] [747330150] v2ray.com/core/proxy/vmess/inbound: received request for tcp:mail.newvision.com.hk:995
2019/12/01 22:46:54 [Info] [747330150] v2ray.com/core/app/dispatcher: default route for tcp:mail.newvision.com.hk:995
2019/12/01 22:46:54 [Info] [747330150] v2ray.com/core/proxy/freedom: opening connection to tcp:mail.newvision.com.hk:995
2019/12/01 22:46:54 [Info] [747330150] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:mail.newvision.com.hk:995
2019/12/01 22:46:58 [Info] [1499585355] v2ray.com/core/proxy/vmess/inbound: received request for tcp:p62-keyvalueservice.icloud.com:443
2019/12/01 22:46:58 [Info] [1499585355] v2ray.com/core/app/dispatcher: default route for tcp:p62-keyvalueservice.icloud.com:443
2019/12/01 22:46:58 [Info] [1499585355] v2ray.com/core/proxy/freedom: opening connection to tcp:p62-keyvalueservice.icloud.com:443
2019/12/01 22:46:58 [Info] [1499585355] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:p62-keyvalueservice.icloud.com:443
2019/12/01 22:47:26 [Info] [1499585355] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: failed to transfer request > websocket: close 1006 (abnormal closure): unexpected EOF
2019/12/01 22:47:26 [Info] [1499585355] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > v2ray.com/core/proxy/freedom: failed to process request > io: read/write on closed pipe
2019/12/01 22:47:34 [Info] [664055473] v2ray.com/core/proxy/vmess/inbound: received request for tcp:p62-keyvalueservice.icloud.com:443
2019/12/01 22:47:34 [Info] [664055473] v2ray.com/core/app/dispatcher: default route for tcp:p62-keyvalueservice.icloud.com:443
2019/12/01 22:47:34 [Info] [664055473] v2ray.com/core/proxy/freedom: opening connection to tcp:p62-keyvalueservice.icloud.com:443
2019/12/01 22:47:34 [Info] [664055473] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:p62-keyvalueservice.icloud.com:443
2019/12/01 22:47:55 [Info] [747330150] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: failed to transfer request > websocket: close 1006 (abnormal closure): unexpected EOF
2019/12/01 22:47:55 [Info] [747330150] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/12/01 22:48:04 [Info] [664055473] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: failed to transfer request > websocket: close 1006 (abnormal closure): unexpected EOF
2019/12/01 22:48:04 [Info] [664055473] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > v2ray.com/core/proxy/freedom: failed to process request > io: read/write on closed pipe
2019/12/01 22:48:15 [Info] [2216736631] v2ray.com/core/proxy/vmess/inbound: received request for tcp:p62-keyvalueservice.icloud.com:443
2019/12/01 22:48:15 [Info] [2216736631] v2ray.com/core/app/dispatcher: default route for tcp:p62-keyvalueservice.icloud.com:443
2019/12/01 22:48:15 [Info] [2216736631] v2ray.com/core/proxy/freedom: opening connection to tcp:p62-keyvalueservice.icloud.com:443
2019/12/01 22:48:15 [Info] [2216736631] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:p62-keyvalueservice.icloud.com:443
2019/12/01 22:48:17 [Info] [2216736631] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: failed to transfer request > websocket: close 1006 (abnormal closure): unexpected EOF
2019/12/01 22:48:17 [Info] [2216736631] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/12/01 22:48:27 [Info] [2478203068] v2ray.com/core/proxy/vmess/inbound: received request for tcp:p62-keyvalueservice.icloud.com:443
2019/12/01 22:48:27 [Info] [2478203068] v2ray.com/core/app/dispatcher: default route for tcp:p62-keyvalueservice.icloud.com:443
2019/12/01 22:48:27 [Info] [2478203068] v2ray.com/core/proxy/freedom: opening connection to tcp:p62-keyvalueservice.icloud.com:443
2019/12/01 22:48:27 [Info] [2478203068] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:p62-keyvalueservice.icloud.com:443
2019/12/01 22:48:30 [Info] [2478203068] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: failed to transfer request > websocket: close 1006 (abnormal closure): unexpected EOF
2019/12/01 22:48:30 [Info] [2478203068] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/12/01 22:49:23 [Info] [2860124964] v2ray.com/core/proxy/vmess/inbound: received request for tcp:gateway.icloud.com:443
2019/12/01 22:49:23 [Info] [2860124964] v2ray.com/core/app/dispatcher: default route for tcp:gateway.icloud.com:443
2019/12/01 22:49:23 [Info] [2860124964] v2ray.com/core/proxy/freedom: opening connection to tcp:gateway.icloud.com:443
2019/12/01 22:49:23 [Info] [2860124964] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:gateway.icloud.com:443
2019/12/01 22:49:26 [Info] [2860124964] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: failed to transfer request > websocket: close 1006 (abnormal closure): unexpected EOF
2019/12/01 22:49:26 [Info] [2860124964] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled

```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

server {
    listen 80;
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name h2.mysite.com;
    root /var/www/h2.mysite.com;
    index index.html;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ecdh_curve X25519:P-256:P-384:P-224:P-521;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-CHACHA20-POLY1305:ECDHE+AES128:RSA+AES128:ECDHE+AES256:RSA+3DES;
    ssl_certificate /etc/letsencrypt/live/h2.mysite.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/h2.mysite.com/privkey.pem;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_session_tickets on;
    ssl_stapling        on;
    ssl_stapling_verify on;

 location /websocket {
        proxy_redirect off;
        proxy_pass http://127.0.0.1:17031;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $http_x_forwarded_for;
        proxy_set_header X-Forwarded-For $http_x_forwarded_for;
}
    location = /favicon.ico {
        log_not_found off;
}
}

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by i553041** [comment]
kslr君你好，我見到你加了Need Logs這個label，但請問我還要提供甚麼log呢？

nginx的error.log？

小火箭直連(WS+TLS+NGINX)連不上，但Nginx的error log不見有紀錄。

小火箭的log我找不到在那裡。

V2ray的Error Log：

2019/12/02 01:09:48 [Info] [1546857067] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > io: read/write on closed pipe
2019/12/02 01:10:14 [Info] [3238156514] v2ray.com/core/proxy/vmess/inbound: received request for tcp:s-bid.rmp.rakuten.com:443
2019/12/02 01:10:14 [Info] [3238156514] v2ray.com/core/app/dispatcher: default route for tcp:s-bid.rmp.rakuten.com:443
2019/12/02 01:10:14 [Info] [3238156514] v2ray.com/core/proxy/freedom: opening connection to tcp:s-bid.rmp.rakuten.com:443
2019/12/02 01:10:14 [Info] [3238156514] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:s-bid.rmp.rakuten.com:443
2019/12/02 01:10:17 [Info] [1000630047] v2ray.com/core/proxy/vmess/inbound: received request for tcp:www.google-analytics.com:443
2019/12/02 01:10:17 [Info] [1000630047] v2ray.com/core/app/dispatcher: default route for tcp:www.google-analytics.com:443
2019/12/02 01:10:17 [Info] [1000630047] v2ray.com/core/proxy/freedom: opening connection to tcp:www.google-analytics.com:443
2019/12/02 01:10:17 [Info] [1000630047] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.google-analytics.com:443
2019/12/02 01:10:17 [Info] [1000630047] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.google-analytics.com:443
2019/12/02 01:10:18 [Info] [1000630047] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.google-analytics.com:443
2019/12/02 01:10:18 [Info] [1000630047] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.google-analytics.com:443
2019/12/02 01:10:18 [Info] [1000630047] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.google-analytics.com:443
2019/12/02 01:10:18 [Info] [1000630047] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: failed to open connection to tcp:www.google-analytics.com:443 > v2ray.com/core/common/retry: [dial tcp: lookup www.google-analytics.com on 127.0.0.1:53: no such host] > v2ray.com/core/common/retry: all retry attempts failed
2019/12/02 01:10:18 [Info] [1000630047] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > io: read/write on closed pipe
2019/12/02 01:10:22 [Info] [4251300841] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: failed to transfer request > websocket: close 1006 (abnormal closure): unexpected EOF
2019/12/02 01:10:22 [Info] [4251300841] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/12/02 01:10:24 [Info] [2157565677] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: failed to transfer request > websocket: close 1006 (abnormal closure): unexpected EOF
2019/12/02 01:10:24 [Info] [2157565677] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/12/02 01:10:27 [Info] [563943065] v2ray.com/core/proxy/vmess/inbound: received request for tcp:docs.google.com:443
2019/12/02 01:10:27 [Info] [563943065] v2ray.com/core/app/dispatcher: default route for tcp:docs.google.com:443
2019/12/02 01:10:27 [Info] [563943065] v2ray.com/core/proxy/freedom: opening connection to tcp:docs.google.com:443
2019/12/02 01:10:27 [Info] [563943065] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:docs.google.com:443
2019/12/02 01:10:28 [Info] [1011526416] v2ray.com/core/proxy/vmess/inbound: received request for tcp:accounts.google.com:443
2019/12/02 01:10:30 [Info] [1011526416] v2ray.com/core/app/dispatcher: default route for tcp:accounts.google.com:443
2019/12/02 01:10:30 [Info] [1011526416] v2ray.com/core/proxy/freedom: opening connection to tcp:accounts.google.com:443
2019/12/02 01:10:30 [Info] [1011526416] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:accounts.google.com:443
2019/12/02 01:10:42 [Info] [592123418] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > context canceled
2019/12/02 01:10:42 [Info] [1610030124] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/12/02 01:10:42 [Info] [592123418] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/12/02 01:10:42 [Info] [1610030124] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > io: read/write on closed pipe
2019/12/02 01:10:42 [Info] [2840756633] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > context canceled
2019/12/02 01:10:42 [Info] [2840756633] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/12/02 01:10:47 [Info] [2428601830] v2ray.com/core/proxy/vmess/inbound: received request for tcp:www.google-analytics.com:443
2019/12/02 01:10:47 [Info] [2428601830] v2ray.com/core/app/dispatcher: default route for tcp:www.google-analytics.com:443
2019/12/02 01:10:47 [Info] [2428601830] v2ray.com/core/proxy/freedom: opening connection to tcp:www.google-analytics.com:443
2019/12/02 01:10:47 [Info] [2428601830] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.google-analytics.com:443
2019/12/02 01:10:47 [Info] [2428601830] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.google-analytics.com:443
2019/12/02 01:10:48 [Info] [2428601830] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.google-analytics.com:443
2019/12/02 01:10:48 [Info] [2428601830] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.google-analytics.com:443
2019/12/02 01:10:48 [Info] [2428601830] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.google-analytics.com:443
2019/12/02 01:10:48 [Info] [2428601830] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: failed to open connection to tcp:www.google-analytics.com:443 > v2ray.com/core/common/retry: [dial tcp: lookup www.google-analytics.com on 127.0.0.1:53: no such host] > v2ray.com/core/common/retry: all retry attempts failed
2019/12/02 01:10:48 [Info] [2428601830] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > io: read/write on closed pipe
2019/12/02 01:11:14 [Info] [3238156514] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: failed to transfer request > websocket: close 1006 (abnormal closure): unexpected EOF
2019/12/02 01:11:14 [Info] [3238156514] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/12/02 01:11:17 [Info] [3476343562] v2ray.com/core/proxy/vmess/inbound: received request for tcp:www.google-analytics.com:443
2019/12/02 01:11:17 [Info] [3476343562] v2ray.com/core/app/dispatcher: default route for tcp:www.google-analytics.com:443
2019/12/02 01:11:17 [Info] [3476343562] v2ray.com/core/proxy/freedom: opening connection to tcp:www.google-analytics.com:443
2019/12/02 01:11:17 [Info] [3476343562] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.google-analytics.com:443
2019/12/02 01:11:17 [Info] [3476343562] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.google-analytics.com:443
2019/12/02 01:11:18 [Info] [3476343562] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.google-analytics.com:443
2019/12/02 01:11:18 [Info] [3476343562] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.google-analytics.com:443
2019/12/02 01:11:18 [Info] [3476343562] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.google-analytics.com:443
2019/12/02 01:11:18 [Info] [3476343562] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: failed to open connection to tcp:www.google-analytics.com:443 > v2ray.com/core/common/retry: [dial tcp: lookup www.google-analytics.com on 127.0.0.1:53: no such host] > v2ray.com/core/common/retry: all retry attempts failed
2019/12/02 01:11:18 [Info] [3476343562] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > io: read/write on closed pipe
2019/12/02 01:11:27 [Info] [563943065] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: failed to transfer request > websocket: close 1006 (abnormal closure): unexpected EOF
2019/12/02 01:11:27 [Info] [563943065] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > v2ray.com/core/proxy/freedom: failed to process request > io: read/write on closed pipe
2019/12/02 01:11:28 [Info] [1011526416] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: failed to transfer request > websocket: close 1006 (abnormal closure): unexpected EOF
2019/12/02 01:11:28 [Info] [1011526416] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/12/02 01:11:47 [Info] [4046110774] v2ray.com/core/proxy/vmess/inbound: received request for tcp:www.google-analytics.com:443
2019/12/02 01:11:47 [Info] [4046110774] v2ray.com/core/app/dispatcher: default route for tcp:www.google-analytics.com:443
2019/12/02 01:11:47 [Info] [4046110774] v2ray.com/core/proxy/freedom: opening connection to tcp:www.google-analytics.com:443
2019/12/02 01:11:47 [Info] [4046110774] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.google-analytics.com:443
2019/12/02 01:11:47 [Info] [4046110774] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.google-analytics.com:443
2019/12/02 01:11:48 [Info] [4046110774] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.google-analytics.com:443
2019/12/02 01:11:48 [Info] [4046110774] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.google-analytics.com:443
2019/12/02 01:11:48 [Info] [4046110774] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.google-analytics.com:443
2019/12/02 01:11:48 [Info] [4046110774] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: failed to open connection to tcp:www.google-analytics.com:443 > v2ray.com/core/common/retry: [dial tcp: lookup www.google-analytics.com on 127.0.0.1:53: no such host] > v2ray.com/core/common/retry: all retry attempts failed
2019/12/02 01:11:48 [Info] [4046110774] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > io: read/write on closed pipe
2019/12/02 01:12:17 [Info] [67031280] v2ray.com/core/proxy/vmess/inbound: received request for tcp:www.google-analytics.com:443
2019/12/02 01:12:17 [Info] [67031280] v2ray.com/core/app/dispatcher: default route for tcp:www.google-analytics.com:443
2019/12/02 01:12:17 [Info] [67031280] v2ray.com/core/proxy/freedom: opening connection to tcp:www.google-analytics.com:443
2019/12/02 01:12:17 [Info] [67031280] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.google-analytics.com:443
2019/12/02 01:12:17 [Info] [67031280] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.google-analytics.com:443
2019/12/02 01:12:18 [Info] [67031280] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.google-analytics.com:443
2019/12/02 01:12:18 [Info] [67031280] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.google-analytics.com:443
2019/12/02 01:12:18 [Info] [67031280] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.google-analytics.com:443
2019/12/02 01:12:18 [Info] [67031280] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: failed to open connection to tcp:www.google-analytics.com:443 > v2ray.com/core/common/retry: [dial tcp: lookup www.google-analytics.com on 127.0.0.1:53: no such host] > v2ray.com/core/common/retry: all retry attempts failed
2019/12/02 01:12:18 [Info] [67031280] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > io: read/write on closed pipe

**Comment by kslr** [comment]
: [dial tcp: lookup www.google-analytics.com on 127.0.0.1:53: no such host] 

你的本地网路工作正常吗

**Comment by i553041** [comment]
> : [dial tcp: lookup www.google-analytics.com on 127.0.0.1:53: no such host]
> 
> 你的本地网路工作正常吗
感謝你這麼晚了還回覆我！

正常的，我在VPS上安裝了AdguardHome，用來攔截廣告：

![99FA3158-6B28-4FAC-88F2-C6A7E689AA19](https://user-images.githubusercontent.com/53026952/69917672-76962e80-14a3-11ea-9c6d-f8a947d61c51.jpeg)

**Comment by kslr** [comment]
那你可以取消dns代理测试下并且校准一下时间

**Comment by i553041** [comment]
> 那你可以取消dns代理测试下并且校准一下时间

試了，而且我還試過Shadowrocket、i2Ray、Quantumult，也連不上。

**Comment by kslr** [comment]
防火墙呢

**Comment by i553041** [comment]
> 防火墙呢

一直都是把Linux防火牆徹底關閉的，只是在路由器以port forward開啟要用的port，例如443，把路由器當作防火牆，以前一直在用也沒問題，這個問題是一個星期前忽然發生的。

不知道是IOS的問題還是v2ray的問題。

越來越懷疑是IOS問題。

因為我昨晚用Mac機的客戶端v2rayU測試，我可以正常連上。

我想在安卓那邊再測試一下，我沒有安卓手機，我和家人朋友的手機都是iphone的，就算有朋友用安卓手機也不懂操作這個。

有個冒昩請求，請問kslr君有安卓手機嗎？如有，我能否把我v2ray的設置電郵給你，你幫我用安卓手機機測試一下可以嗎？先謝謝你了！

如果安卓都能連上，那就是IOS設置了甚麼限制之類的了！

只想知道是IOS問題還是v2ray問題！

**Comment by kslr** [comment]
不好意思，我没有时间测试。 你可以试试在虚拟机里面做个windows尝试

**Comment by i553041** [comment]
> 不好意思，我没有时间测试。 你可以试试在虚拟机里面做个windows尝试

不要緊，經過一番研究後，問題解決了，不是v2ray的問題，是小火箭的問題，我在他們的TG群組內，見到這一段訊息：

因为耗内存严重, Shadowrocket 2.1.39(880) 版本暂时禁用tls1.3.
如果特别需要tls1.3 可以申请TestFlight版本, 或者等正式版新版.

原來是官方在最新版本的小火箭裡故意拿走了TLS1.3的支持，但不知為何，nginx的設定檔又忽然用不到TLS1.2，(或者說nginx忽然只支持TLS1.3)，由於nginx不知何故，「只支持TLS1.3」，所以小火箭拿走了TLS1.3而連不上，其他IOS客戶端(i2Ray、Quantumult)，由於還不支持TLS1.3，所以也連不上。

重新設置一次支持TLS1.2及1.3的ssl protocols及ssl ciphers就回復正常了。

無論如何，都謝謝kslr君的熱心幫忙。
