### ISSUE TITLE
sniffing 的一个 Bug

### ISSUE THREAD

**Issue by FH0** [v2ray/v2ray-core#2075]
在使用 BifrostV 代理迅雷时，开启传入探测（sniffing）后，迅雷无法下载，在关闭传入探测（sniffing）后，迅雷正常下载

这个问题在 v2rayNG 上也同样出现了

查看日志，发现嗅探出 res.res.res.res 这个域名，但经过上网查询，发现没有这个后缀的域名

应该是 sniffing 嗅探出了问题

**Comment by johnrosen1** [comment]
吸血雷别用，qbittorrent多好用，https://www.johnrosen1.com/qbt/

**Comment by FH0** [comment]
> 吸血雷别用，qbittorrent多好用，https://www.johnrosen1.com/qbt/

内网环境我只能找到迅雷了，你说的那个要公网的

**Comment by johnrosen1** [comment]
> > 吸血雷别用，qbittorrent多好用，https://www.johnrosen1.com/qbt/
> 
> 内网环境我只能找到迅雷了，你说的那个要公网的

no,内网只是速度比公网慢而已，大不了去要个公网ip，又不是什么难事。

**Comment by FH0** [comment]
关闭
