### ISSUE TITLE
设置的国内直连路由策略不工作，任何网站都走代理

### ISSUE THREAD

**Issue by a13519** [v2ray/v2ray-core#2078]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
4.20.0
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
OpenWRT transparant proxy, and curl a banned site for testing like google.com
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
设置的国内直连的 direct routing， 不工作，这包括预设的china domain 或 ip，或者是手动的domain 和 ip 添加都无效
4) 你期待看到的正确表现是怎样的？
设置的直连routing可以奏效
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
{
  "log": {
    "loglevel": "debug",
    "access": "/root/v2ray/access.log",
    "error": "/root/v2ray/error.log"
  },
  "inbounds": [
    {
      "port": "1081", 
      "protocol": "socks", 
      "listen": "0.0.0.0",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
      "settings": {
        "auth": "noauth"  
      }
    },
    {
      "port": 12345, 
      "protocol": "dokodemo-door",
      "settings": {
        "network": "tcp,udp",
        "timeout": 30,
        "followRedirect": true 
      },
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      }
    }
  ],
  "outbounds" : [
    {
      "sendThrough" : "0.0.0.0",
      "mux" : {
        "enabled" : false,
        "concurrency" : 8
      },
      "protocol" : "vmess",
      "settings" : {
        "vnext" : [
          {
            "address" : "xxxx",
            "users" : [
              {
                "id" : "xxxx",
                "alterId" : 32,
                "security" : "chacha20-poly1305",
                "level" : 0
              }
            ],
            "port" : xxx
          }
        ]
      },
      "tag" : "ss",
      "streamSettings" : {
        "sockopt" : {
		  "mark": 255
        }
      }
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "routings" : {
      "name" : "cn_direct",
      "domainStrategy" : "AsIs",
      "rules" : [
        {
          "type" : "field",
          "outboundTag" : "direct",
          "domain" : [
            "domain:icanhazip.com"
          ]
        },
        {
          "type" : "field",
          "outboundTag" : "direct",
          "domain" : [
            "geosite:cn"
          ]
        },
        {
          "type" : "field",
          "outboundTag" : "direct",
          "ip" : [
            "geoip:private",
            "geoip:cn"
          ]
        },
        {
          "type": "field",
          "network": "tcp,udp",
          "outboundTag": "ss"
        } 
      ]
    }
}

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
```

客户端配置:

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
2019/12/03 08:06:28 [Info] [1847575767] v2ray.com/core/proxy/socks: TCP Connect request to tcp:140.205.94.189:443
2019/12/03 08:06:28 [Info] [1847575767] v2ray.com/core/app/dispatcher: sniffed domain: taobao.com
2019/12/03 08:06:28 [Info] [1847575767] v2ray.com/core/app/dispatcher: default route for tcp:taobao.com:443
2019/12/03 08:06:28 [Info] [1847575767] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:xxxx：x x x x
2019/12/03 08:06:29 [Info] [1847575767] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:taobao.com:443 via tcp:xxxx:xxxx
2019/12/03 08:06:31 [Info] [1847575767] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled
2019/12/03 08:06:31 [Info] [1847575767] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
2019/12/03 07:33:51 tcp:127.0.0.1:47122 accepted tcp:139.178.81.233:443 
2019/12/03 07:34:43 tcp:127.0.0.1:47126 accepted tcp:139.178.81.233:443 
2019/12/03 07:35:17 tcp:127.0.0.1:47130 accepted tcp:101.89.125.238:443 
2019/12/03 07:36:30 tcp:127.0.0.1:47134 accepted tcp:101.89.125.239:443 
2019/12/03 07:37:11 tcp:127.0.0.1:47138 accepted tcp:140.205.94.189:443 
2019/12/03 07:41:38 tcp:127.0.0.1:47142 accepted tcp:140.205.220.96:443 
2019/12/03 07:46:08 tcp:127.0.0.1:47146 accepted tcp:140.205.94.189:443 
2019/12/03 07:46:42 tcp:127.0.0.1:47150 accepted tcp:139.178.81.233:443 
2019/12/03 07:46:52 tcp:127.0.0.1:47154 accepted tcp:104.20.16.242:443 
2019/12/03 07:47:09 tcp:127.0.0.1:47158 accepted tcp:104.20.17.242:80 
2019/12/03 07:47:46 tcp:127.0.0.1:47162 accepted tcp:104.20.16.242:80 
2019/12/03 07:48:34 tcp:127.0.0.1:47166 accepted tcp:104.20.17.242:80 
2019/12/03 08:06:18 tcp:127.0.0.1:47170 accepted tcp:104.20.17.242:80 
2019/12/03 08:06:22 tcp:127.0.0.1:47174 accepted tcp:104.20.16.242:80 
2019/12/03 08:06:28 tcp:127.0.0.1:47178 accepted tcp:140.205.94.189:443 
2019/12/03 08:15:11 tcp:127.0.0.1:47184 accepted tcp:104.20.17.242:80 
2019/12/03 08:16:58 tcp:127.0.0.1:47188 accepted tcp:104.20.17.242:80 
2019/12/03 08:17:08 tcp:127.0.0.1:47192 accepted tcp:104.20.17.242:80 
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

可以启动

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

=========================================
测试了很多国内国外网站都无效，不管怎么修改rounting都是这样，icanhazip.com 显示都是代理的ip地址。
另外rules里面的domain设置是应该有”domain：“prefix吗？
        {
          "type" : "field",
          "outboundTag" : "direct",
          "domain" : [
            "domain:icanhazip.com"
          ]
        }
还是
        {
          "type" : "field",
          "outboundTag" : "direct",
          "domain" : [
            "icanhazip.com"
          ]
        }
=========================================

**Comment by kingwilliam** [comment]
> 提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
> 除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
> 如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。
> 
> 1. 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
>    4.20.0
> 2. 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
>    OpenWRT transparant proxy, and curl a banned site for testing like google.com
> 3. 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
>    设置的国内直连的 direct routing， 不工作，这包括预设的china domain 或 ip，或者是手动的domain 和 ip 添加都无效
> 4. 你期待看到的正确表现是怎样的？
>    设置的直连routing可以奏效
> 5. 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
>    {
>    "log": {
>    "loglevel": "debug",
>    "access": "/root/v2ray/access.log",
>    "error": "/root/v2ray/error.log"
>    },
>    "inbounds": [
>    {
>    "port": "1081",
>    "protocol": "socks",
>    "listen": "0.0.0.0",
>    "sniffing": {
>    "enabled": true,
>    "destOverride": ["http", "tls"]
>    },
>    "settings": {
>    "auth": "noauth"
>    }
>    },
>    {
>    "port": 12345,
>    "protocol": "dokodemo-door",
>    "settings": {
>    "network": "tcp,udp",
>    "timeout": 30,
>    "followRedirect": true
>    },
>    "sniffing": {
>    "enabled": true,
>    "destOverride": ["http", "tls"]
>    }
>    }
>    ],
>    "outbounds" : [
>    {
>    "sendThrough" : "0.0.0.0",
>    "mux" : {
>    "enabled" : false,
>    "concurrency" : 8
>    },
>    "protocol" : "vmess",
>    "settings" : {
>    "vnext" : [
>    {
>    "address" : "xxxx",
>    "users" : [
>    {
>    "id" : "xxxx",
>    "alterId" : 32,
>    "security" : "chacha20-poly1305",
>    "level" : 0
>    }
>    ],
>    "port" : xxx
>    }
>    ]
>    },
>    "tag" : "ss",
>    "streamSettings" : {
>    "sockopt" : {
>    "mark": 255
>    }
>    }
>    },
>    {
>    "protocol": "freedom",
>    "settings": {},
>    "tag": "direct"
>    }
>    ],
>    "routings" : {
>    "name" : "cn_direct",
>    "domainStrategy" : "AsIs",
>    "rules" : [
>    {
>    "type" : "field",
>    "outboundTag" : "direct",
>    "domain" : [
>    "domain:icanhazip.com"
>    ]
>    },
>    {
>    "type" : "field",
>    "outboundTag" : "direct",
>    "domain" : [
>    "geosite:cn"
>    ]
>    },
>    {
>    "type" : "field",
>    "outboundTag" : "direct",
>    "ip" : [
>    "geoip:private",
>    "geoip:cn"
>    ]
>    },
>    {
>    "type": "field",
>    "network": "tcp,udp",
>    "outboundTag": "ss"
>    }
>    ]
>    }
>    }
> 
> 服务器端配置:
> 
> ```js
>     // 在这里附上服务器端配置文件
> ```
> 
> 客户端配置:
> 
> ```js
>     // 在这里附上客户端配置
> ```
> 
> 1. 请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
> 
> 服务器端错误日志:
> 
> ```js
>     // 在这里附上服务器端日志
> ```
> 
> 客户端错误日志:
> 
> ```js
> 2019/12/03 08:06:28 [Info] [1847575767] v2ray.com/core/proxy/socks: TCP Connect request to tcp:140.205.94.189:443
> 2019/12/03 08:06:28 [Info] [1847575767] v2ray.com/core/app/dispatcher: sniffed domain: taobao.com
> 2019/12/03 08:06:28 [Info] [1847575767] v2ray.com/core/app/dispatcher: default route for tcp:taobao.com:443
> 2019/12/03 08:06:28 [Info] [1847575767] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:xxxx：x x x x
> 2019/12/03 08:06:29 [Info] [1847575767] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:taobao.com:443 via tcp:xxxx:xxxx
> 2019/12/03 08:06:31 [Info] [1847575767] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled
> 2019/12/03 08:06:31 [Info] [1847575767] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
> ```
> 
> 1. 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
> 
> ```js
> 2019/12/03 07:33:51 tcp:127.0.0.1:47122 accepted tcp:139.178.81.233:443 
> 2019/12/03 07:34:43 tcp:127.0.0.1:47126 accepted tcp:139.178.81.233:443 
> 2019/12/03 07:35:17 tcp:127.0.0.1:47130 accepted tcp:101.89.125.238:443 
> 2019/12/03 07:36:30 tcp:127.0.0.1:47134 accepted tcp:101.89.125.239:443 
> 2019/12/03 07:37:11 tcp:127.0.0.1:47138 accepted tcp:140.205.94.189:443 
> 2019/12/03 07:41:38 tcp:127.0.0.1:47142 accepted tcp:140.205.220.96:443 
> 2019/12/03 07:46:08 tcp:127.0.0.1:47146 accepted tcp:140.205.94.189:443 
> 2019/12/03 07:46:42 tcp:127.0.0.1:47150 accepted tcp:139.178.81.233:443 
> 2019/12/03 07:46:52 tcp:127.0.0.1:47154 accepted tcp:104.20.16.242:443 
> 2019/12/03 07:47:09 tcp:127.0.0.1:47158 accepted tcp:104.20.17.242:80 
> 2019/12/03 07:47:46 tcp:127.0.0.1:47162 accepted tcp:104.20.16.242:80 
> 2019/12/03 07:48:34 tcp:127.0.0.1:47166 accepted tcp:104.20.17.242:80 
> 2019/12/03 08:06:18 tcp:127.0.0.1:47170 accepted tcp:104.20.17.242:80 
> 2019/12/03 08:06:22 tcp:127.0.0.1:47174 accepted tcp:104.20.16.242:80 
> 2019/12/03 08:06:28 tcp:127.0.0.1:47178 accepted tcp:140.205.94.189:443 
> 2019/12/03 08:15:11 tcp:127.0.0.1:47184 accepted tcp:104.20.17.242:80 
> 2019/12/03 08:16:58 tcp:127.0.0.1:47188 accepted tcp:104.20.17.242:80 
> 2019/12/03 08:17:08 tcp:127.0.0.1:47192 accepted tcp:104.20.17.242:80 
> ```
> 
> 1. 其它相关的配置文件（如 Nginx）和相关日志。
> 2. 如果 V2Ray 无法启动，请附上 `--test` 输出。
> 
> 可以启动
> 
> 1. 如果 V2Ray 服务运行不正常，请附上 journal 日志。
> 
> 通常的命令为 `journalctl -u v2ray`。
> 
> 请预览一下你填的内容再提交。
> 
> # =========================================
> 测试了很多国内国外网站都无效，不管怎么修改rounting都是这样，icanhazip.com 显示都是代理的ip地址。
> 另外rules里面的domain设置是应该有”domain：“prefix吗？
> {
> "type" : "field",
> "outboundTag" : "direct",
> "domain" : [
> "domain:icanhazip.com"
> ]
> }
> 还是
> {
> "type" : "field",
> "outboundTag" : "direct",
> "domain" : [
> "icanhazip.com"
> ]
> }

您的问题可能不只一个, 要一步步解决

参考
https://www.v2ray.com/chapter_02/03_routing.html
没prefix才正确
{
	"type" : "field",
	"outboundTag" : "direct",
	"domain" : [
		"icanhazip.com"
	]
}

**Comment by kingwilliam** [comment]
您的问题可能不只一个, 要一步步解决

参考
https://www.v2ray.com/chapter_02/03_routing.html
没prefix才正确
```
{
	"type" : "field",
	"outboundTag" : "direct",
	"domain" : [
		"icanhazip.com"
	]
}
```

**Comment by kingwilliam** [comment]
试试删除 "name" : "cn_direct", 

前
```
"routings" : {
	"name" : "cn_direct", 
	"domainStrategy" : "AsIs",

```
後
```
"routings" : {
	"domainStrategy" : "AsIs",
```

**Comment by a13519** [comment]
谢谢提示，我已经更改，但还是不能匹配 icanhazip.com：

curl -x socks5://127.0.0.1:1081 icanhazip.com
<vpn ip>

**Comment by a13519** [comment]
删除  "name" : "cn_direct"
好像还是那样子

**Comment by kingwilliam** [comment]
看您更新後的routing应该能正常运作, 如还是不能, 可否在测试後给debug.log 看看

```
"routings" : {
	"domainStrategy" : "AsIs",
	"rules" : [
		{
			"type" : "field",
			"outboundTag" : "direct",
			"domain" : [
				"icanhazip.com"
			]
		},
		{
			"type" : "field",
			"outboundTag" : "direct",
			"domain" : [
				"geosite:cn"
			]
		},
		{
			"type" : "field",
			"outboundTag" : "direct",
			"ip" : [
				"geoip:private",
				"geoip:cn"
			]
		},
		{
			"type": "field",
			"network": "tcp,udp",
			"outboundTag": "ss"
		}
	]
}
```

**Comment by a13519** [comment]
Thanks for replying!

config log已经设成“debug”，删除老log重新启动，用curl测试后 得到error.log：
两个outbound 组成balancer“

root@OpenWrt-Main:~# curl -x socks5://127.0.0.1:1081 icanhazip.com
<one outbound ipv6 address>
root@OpenWrt-Main:~# curl -x socks5://127.0.0.1:1081 icanhazip.com
<one outbound ipv4 address>

————————————————————————————————————
39:42 [Debug] v2ray.com/core/app/log: Logger started
2019/12/03 09:39:42 [Warning] v2ray.com/core: V2Ray 4.20.0 started
2019/12/03 09:39:55 [Info] [412175294] v2ray.com/core/proxy/socks: TCP Connect request to tcp:104.20.16.242:80
2019/12/03 09:39:55 [Info] [412175294] v2ray.com/core/app/dispatcher: sniffed domain: icanhazip.com
2019/12/03 09:39:55 [Info] [412175294] v2ray.com/core/app/dispatcher: default route for tcp:icanhazip.com:80
2019/12/03 09:39:55 [Info] [412175294] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:103.xx.xx.xx:xx
2019/12/03 09:39:58 [Info] [412175294] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:icanhazip.com:80 via tcp:103.xx.xx.xx:xx
2019/12/03 09:39:59 [Info] [412175294] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled
2019/12/03 09:39:59 [Info] [412175294] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2019/12/03 09:40:30 [Debug] v2ray.com/core/app/log: Logger started
2019/12/03 09:40:30 [Warning] v2ray.com/core: V2Ray 4.20.0 started
2019/12/03 09:40:36 [Info] [304050734] v2ray.com/core/proxy/socks: TCP Connect request to tcp:104.20.16.242:80
2019/12/03 09:40:36 [Info] [304050734] v2ray.com/core/app/dispatcher: sniffed domain: icanhazip.com
2019/12/03 09:40:36 [Info] [304050734] v2ray.com/core/app/dispatcher: default route for tcp:icanhazip.com:80
2019/12/03 09:40:36 [Info] [304050734] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:103.xx.xx.xx:xx
2019/12/03 09:40:37 [Info] [304050734] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:icanhazip.com:80 via tcp:103.xx.xx.xx:xx
2019/12/03 09:40:40 [Info] [304050734] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled
2019/12/03 09:40:40 [Info] [304050734] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2019/12/03 09:40:41 [Info] [2245436690] v2ray.com/core/proxy/socks: TCP Connect request to tcp:104.20.17.242:80
2019/12/03 09:40:41 [Info] [2245436690] v2ray.com/core/app/dispatcher: sniffed domain: icanhazip.com
2019/12/03 09:40:41 [Info] [2245436690] v2ray.com/core/app/dispatcher: default route for tcp:icanhazip.com:80
2019/12/03 09:40:41 [Info] [2245436690] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:103.xx.xx.xx:xx
2019/12/03 09:40:42 [Info] [2245436690] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:icanhazip.com:80 via tcp:103.xx.xx.xx:xx
2019/12/03 09:40:43 [Info] [2245436690] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled
2019/12/03 09:40:43 [Info] [2245436690] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
————————————————————————————————————

**Comment by a13519** [comment]
测试了访问我局域网的host都不走代理，但好像域名解析的都走代理，为什么？

**Comment by kingwilliam** [comment]
"routings" : { 多了's'

"routing" : { 修改後再试一试

**Comment by a13519** [comment]
哇，目光如电！哈哈，确实是，明天测试一下。感谢

**Comment by a13519** [comment]
fix 了，谢谢kingwilliam
