### ISSUE TITLE
multi client redundancy

### ISSUE THREAD

**Issue by jwsheen** [v2ray/v2ray-core#2079]
User client(pc) -- v2ray client(Proxy, stand alone) -- firewall -- v2ray server(stand alone) -- internet
when v2ray client is fail, just should do restart v2ray client.
If yes multi v2ray clients -- multi v2ray server, it help high service redundancy  .

**Comment by kslr** [comment]
Why

**Comment by jwsheen** [comment]
Thank you for your reply. 
It made me think again.
