### ISSUE TITLE
最新的1.19.2的服务器端老是无故退出

### ISSUE THREAD

**Issue by helloyan** [v2ray/v2ray-core#208]
有时候会报错
2016/07/14 07:06:27 [Info]Raw: Failed to read request header: read tcp 106.185.42.113:63000->114.230.122.30:64397: i/o timeout
2016/07/14 07:06:29 [Info]Raw: Failed to read request header: read tcp 106.185.42.113:63000->114.230.122.30:64396: i/o timeout
2016/07/14 07:07:55 [Debug]IO: Pipe exits as EOF
2016/07/14 07:07:55 [Debug]IO: Pipe exits as EOF

有时候什么错也没有，就是退出了。

已换回1.18.2

**Comment by helloyan** [comment]
基本确认是开启了动态端口导致的问题，可能是某端口被占用导致进程退出（在日志中有记录），是否可以加上判断？

**Comment by v2ray** [comment]
Fixed in edd9885d0ecc95b4e6a026aef55fc71662ad4647
