### ISSUE TITLE
怎么安装iPhone V2Ray App？V2Ray不支持IE？

### ISSUE THREAD

**Issue by okudayukiko** [v2ray/v2ray-core#2081]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V2Ray 4.21.3
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
Windows 10
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
用IE浏览器，很多网页（包括google.com）都无法打开。
用Firefox浏览器，google.com可以打开。
iPhone怎么安装付费的V2Ray App（如Kitsunebi）？有非中国内地的Apple ID，但Kitsunebi要付费。试过下载网上的Kitsunebi IPA文件，用iTunes安装到iPhone后打不开App，闪退。
4) 你期待看到的正确表现是怎样的？

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:
```javascript
{ // 配置文件内容 }
```
客户端配置:
```javascript
{ // 配置文件内容 }
{
    "log": {
        "loglevel": "warning"
    },
    "inbound": {
        "listen": "127.0.0.1",
        "port": 1080,
        "protocol": "socks",
        "settings": {
            "auth": "noauth",
            "udp": true,
            "ip": "127.0.0.1"
        }
    },
    "outbound": {
        "protocol": "vmess",
        "settings": {
            "vnext": [
                {
		    "address": "ip",
                    "port": port,
                    "users": [
                        {
                            "id": "id",
                            "level": level,
                            "alterId": alterId
                        }
                    ]
                }
            ]
        }
    },
    "outboundDetour": [
        {
            "protocol": "freedom",
            "settings": {},
            "tag": "direct"
        }
    ]
}
```
6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:
```javascript
    // 在这里附上服务器端日志
```
无
客户端错误日志:
```javascript
    // 在这里附上客户端日志
```
无
7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
```javascript
    // 在这里附上服务器端日志
```
无
8) 其它相关的配置文件（如 Nginx）和相关日志。
无
9) 如果 V2Ray 无法启动，请附上 `--test` 输出。
通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。
无
10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。
通常的命令为 `journalctl -u v2ray`。
请预览一下你填的内容再提交。
无

**Comment by kslr** [comment]
1. 使用礼品卡购买
2. 使用http入站
