### ISSUE TITLE
代理BT Torrents流量时，V2ray出现内存泄漏情况

### ISSUE THREAD

**Issue by Alion548** [v2ray/v2ray-core#2084]
Torrents 有大量UDP请求，可能是这个原因导致内存泄漏。
![image](https://user-images.githubusercontent.com/8340545/70209679-e2aab800-176b-11ea-886a-83de486fde2c.png)

连接过程：
qBittorrent --【socks5】--> v2ray --> 【vmess】--> server

![image](https://user-images.githubusercontent.com/8340545/70209904-5b117900-176c-11ea-9579-6e7229dbdf99.png)
![image](https://user-images.githubusercontent.com/8340545/70209914-65337780-176c-11ea-80a4-12bd0cd509a4.png)

![image](https://user-images.githubusercontent.com/8340545/70209988-88f6bd80-176c-11ea-811b-cce70233bbb8.png)

**Comment by kslr** [comment]
试试关掉utp ?
