### ISSUE TITLE
V2RAY 能否使用BBR拥塞算法 (内核开启BBR的前提下）

### ISSUE THREAD

**Issue by tlsalex** [v2ray/v2ray-core#2088]
Please describe the new feature you want in detail.
v2ray 虽然可以用shadowsock 协议，如果我的理解正确，那意味着v2ray也可以使用BBR算法，当然我还没在v2ray里使用过shadowsock 协议。
用了一段时间v2ray (vmess协议),总感觉网速比较慢，远达不到SSR 使用BBR时的流畅程度

我的问题是：
1. 在v2ray使用 VMESS协议时，能使用BBR 拥塞算法吗？
2. 假如v2ray使用shaddowsock 协议，就能使用BBR了吗？（内核开启BBR的前提下）
3. v2ray 使用shaddowsock 协议， 会像使用shaddowsock 软件那样容易被防火墙检测出来吗？

**Comment by kslr** [comment]
https://en.wikipedia.org/wiki/TCP_congestion_control#TCP_BBR

**Comment by tlsalex** [comment]
很是不明白，所给的链接，似乎与我所问的问题没多大直接的关系
我知道v2ray能使用shadowsocks协议，但我问的不是如何在v2ray里配置shadowsockets.

**Comment by tlze** [comment]
内核开了就行，应用层是自动支持的，不用另外开。
