### ISSUE TITLE
这个fail问题一直找不到解决思路，哪位大神帮看看啊

### ISSUE THREAD

**Issue by man2018** [v2ray/v2ray-core#2089]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v4.21.3
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
直接连接v2服务器进行翻墙就会出现，只要有翻墙行为
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
2019/12/07 13:59:14 [Info] [1700625768] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: failed to transfer request > websocket: close 1000 (normal)
2019/12/07 13:59:14 [Info] [1700625768] v2ray.com/core/app/proxyman/inbound: failed to close connection > v2ray.com/core/transport/internet/websocket: failed to close connection > v2ray.com/core/transport/internet/websocket: websocket: close sent
2019/12/07 13:59:14 [Info] [1700625768] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/12/07 13:59:28 [Info] [249808495] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: failed to transfer request > websocket: close 1006 (abnormal closure): unexpected EOF
2019/12/07 13:59:28 [Info] [249808495] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
4) 你期待看到的正确表现是怎样的？
我不希望有这些fail
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
```

客户端配置:

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:
2019/12/07 13:59:14 [Info] [1700625768] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: failed to transfer request > websocket: close 1000 (normal)
2019/12/07 13:59:14 [Info] [1700625768] v2ray.com/core/app/proxyman/inbound: failed to close connection > v2ray.com/core/transport/internet/websocket: failed to close connection > v2ray.com/core/transport/internet/websocket: websocket: close sent
2019/12/07 13:59:14 [Info] [1700625768] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/12/07 13:59:28 [Info] [249808495] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: failed to transfer request > websocket: close 1006 (abnormal closure): unexpected EOF
2019/12/07 13:59:28 [Info] [249808495] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```
没有什么报错，是用quanx
7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```
2019/12/07 13:59:14 [Info] [1700625768] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: failed to transfer request > websocket: close 1000 (normal)
2019/12/07 13:59:14 [Info] [1700625768] v2ray.com/core/app/proxyman/inbound: failed to close connection > v2ray.com/core/transport/internet/websocket: failed to close connection > v2ray.com/core/transport/internet/websocket: websocket: close sent
2019/12/07 13:59:14 [Info] [1700625768] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2019/12/07 13:59:28 [Info] [249808495] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: failed to transfer request > websocket: close 1006 (abnormal closure): unexpected EOF
2019/12/07 13:59:28 [Info] [249808495] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by kingwilliam** [comment]
很想帮您 但甚麽也没有 爱莫能助。 可以的话 给出 各户 服务器  档案

**Comment by man2018** [comment]
> 很想帮您 但甚麽也没有 爱莫能助。 可以的话 给出 各户 服务器 档案

我发到这上面，稍等

**Comment by man2018** [comment]
[config.txt](https://github.com/v2ray/v2ray-core/files/3934890/config.txt)
[nginx.txt](https://github.com/v2ray/v2ray-core/files/3934891/nginx.txt)
[www.xxx.com.txt](https://github.com/v2ray/v2ray-core/files/3934892/www.xxx.com.txt)
这3个文件分别是Lnmp1.6环境下的相关文件，目前这些配置可以愉快的翻，但就是有那种fail错误

**Comment by man2018** [comment]
我客户端用的是quantumult x，除了规则之外就是vmess=www.xxx.com:443, method=chacha20-ietf-poly1305, password= 19e23d80-3a4d-4277-b37b-79d5d8456f95, obfs-host=www.xxx.com, obfs=wss, obfs-uri=/ray, fast-open=false, udp-relay=false, tag=xxx

**Comment by man2018** [comment]
> 很想帮您 但甚麽也没有 爱莫能助。 可以的话 给出 客户 服务器 档案
