### ISSUE TITLE
Invalid user

### ISSUE THREAD

**Issue by zhouzhiwen2000** [v2ray/v2ray-core#209]
[Warning]VMessIn: Invalid request from ***.***.***.***:466**: Invalid user

**Comment by zhouzhiwen2000** [comment]
id一样，alterId也一样

**Comment by zhouzhiwen2000** [comment]
动态端口没开
日志里端口不是设置的端口

**Comment by Sherman-Liu** [comment]
Check your time, on both the server and your computer.

**Comment by zhouzhiwen2000** [comment]
一样的
