### ISSUE TITLE
路由的代码有优化空间

### ISSUE THREAD

**Issue by supppig** [v2ray/v2ray-core#2095]
https://github.com/v2ray/v2ray-core/blob/master/app/router/config.go
这个文件里面的func (rr *RoutingRule) BuildCondition() (Condition, error)

conds的加入顺序有问题，Domain判断的加入应该放在较后的位置，而不是一个。因为Domain的判断肯定是耗费cpu的，应该放在最后执行。

例如有一个config
{
  "inbounds"[
  {
      "tag": "proxy-all",
      ...
  },
  {
      "tag": "proxy-cn-only",
      ...
  }],
 "routing":{
  "domainStrategy": "AsIs",
  "rules": [
    {
      "type": "field",
      "domain": [
        "geosite:cn"
      ],
      "inboundTag": [
        "proxy-cn-only"
      ],
      "outboundTag": "proxy"
    },
    {
      "type": "field",
      "inboundTag": [
        "proxy-cn-only"
      ],
      "outboundTag": "direct"
    },
    {
    ....其他规则
    }
]
}
如果服务器收到一个来自于proxy-all的请求，过路由判断第一条时，最优解应该是在首先判断inboundTag，返回假之后就直接继续第二条了。
然而，现在的程序会先过一次domain的判断，再过inboundTag的判断（返回假）。

我建议是，应该先判断最简单的条件，最后再判断复杂耗费cpu的条件，这样才有效率。

我git只会最基本的命令，英文四级没过，所以就不pull requests了。提个建议，大神们帮我改了吧，谢谢~~

**Comment by ileeoyo** [comment]
这源代码都看懂了，git按理说也不是啥子难事。我看是偷懒哈哈

**Comment by supppig** [comment]
> 这源代码都看懂了，git按理说也不是啥子难事。我看是偷懒哈哈

我也是个go的菜鸟。才刚学。对于git，用的最多的也是clone和pull，没试过push。真不是偷懒，不敢班门弄斧啊。。。

v2ray我有特殊的需求，比较看重效率。而且用起来总感觉有bug，所以代码都粗略的看了看。
对于我的需求来说，v2ray功能太多太杂了，效率不高。于是自己造轮子了。现在轮子也造了大半了，快能跑起来了。。。

**Comment by mzz2017** [comment]
子串匹配器的那部分为什么不使用ac自动机？

**Comment by supppig** [comment]
> 子串匹配器的那部分为什么不使用ac自动机？

v2ray的亮点是大而全，而不是效率高。目标就是能用。
例如http outbound那块，如果配置了auth的话，每次都要算 base64(username:password)，累不累啊，缓存也不弄一个。

**Comment by supppig** [comment]
没人优化效率就算了吧= =！
已经自己按需求写了一个超级简化版的v2ray了，相当好用。
