### ISSUE TITLE
关于Golang版本的问题

### ISSUE THREAD

**Issue by v3ray** [v2ray/v2ray-core#21]
[安装教程](https://github.com/V2Ray/v2ray-core/blob/master/spec/install.md)下载安装Google官方的1.5的golang包，但Ubuntu官方源提供一个[1.2.1](http://packages.ubuntu.com/trusty/golang-go)版本的golang编译器。

为什么不直接使用官方源提供的版本？1.2有功能缺失的？

**Comment by v2ray** [comment]
主要是性能差别，1.5 和 1.3 都有巨大的性能提升，特别是 1.5 对 GC 的改进，效果非常明显。

功能上，只要 1.2 能编译通过，应该没什么大问题。

**Comment by v3ray** [comment]
谢谢指出。 :smiley_cat:
