### ISSUE TITLE
v2ray是否可以局域网共享？

### ISSUE THREAD

**Issue by xayane** [v2ray/v2ray-core#210]
弱问下，电脑A通过v2ray可以连接使用，同一个局域网下的另外一台电脑B是否也可以通过电脑A来连接使用？电脑A中的v2ray的配置文件需要怎么修改？

**Comment by v2ray** [comment]
可以的，客户端配置文件中有一个 "listen": "127.0.0.1", 把 127.0.0.1 改成 0.0.0.0 就可以了。另外要配置你的防火墙使用运行 V2Ray 的机器可以被其它电脑访问。

**Comment by xayane** [comment]
3Q，谢谢，搞定了！

**Comment by qingfengshi** [comment]
我现在主要是将v2ray与iPad共享。将客户端配置里的listen改为“0.0.0.0”后，在iPad的wifi连接中添加http proxy，但是iPad无法连接Google

**Comment by xayane** [comment]
可以问下作者是否支持http proxy 的pac。
因为我直接使用的手动设置，所有流量都是经过v2ray，所以ipad和iphone是可以连接的google的哈。

**Comment by qingfengshi** [comment]
多谢，手动的OK，我之前一直使用自动的，看来pac还是不行

**Comment by dingkple** [comment]
@xayane 能贴下配置么, 现在mac里正常, 但是iOS里依旧不行, core-version: v2.15.1

**Comment by jiahe224** [comment]
配置文件在哪啊

**Comment by CHIZI-0618** [comment]
多谢，搞了一晚上没弄好，按照你的方法已弄好

**Comment by SunAo-Oct** [comment]
> 多谢，搞了一晚上没弄好，按照你的方法已弄好

怎么搞得

**Comment by fbion** [comment]
> 我现在主要是将v2ray与iPad共享。将客户端配置里的listen改为“0.0.0.0”后，在iPad的wifi连接中添加http proxy，但是iPad无法连接Google

"inbounds": [

    {
      "port": 1024, // 监听端口
      "protocol": "http",
      "settings": {
        "timeout:":0,
        "accounts":[
          {
            "user":"aa",
            "pass":"bb"
          }
        ],
        "allowTransparent":false,
        "userLevel":0
      }
    }
    
  ],

可以测试下http支持域名嗅探吗
"sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
吗

**Comment by lovelyJason** [comment]
客户端的config.json文件是在哪个路径下啊,我用的mac v2rayX

**Comment by kelejichitao** [comment]
mark

**Comment by Micraow** [comment]
我用安卓手机能行吗？

**Comment by CHIZI-0618** [comment]
> 我用安卓手机能行吗？

当然可以

**Comment by Micraow** [comment]
那么请问能给个实操方法吗？
或者是具体如何进行共享？

**Comment by jiahe224** [comment]
1.电脑能正常翻
2.打开翻墙软件里的允许局域网（LAN）连接
3.打开设置里的移动热点（win10）
4.打开命令提示符输入 ipconfig 后回车，记录无线网WLAN的IPv4地址（类似192.168.1.5这种）
5.手机/平板/其它电脑连接此热点后，在连接的高级选项里设置HTTP代理，模式为手动，服务器就是上面的IPv4地址，端口的话，如果是V2rayN或clash，端口为1081，如果是SSR，端口是1080，别搞错
6.重新连接热点，即可翻墙

**Comment by CHIZI-0618** [comment]
> 1.电脑能正常翻
> 2.打开翻墙软件里的允许局域网（LAN）连接
> 3.打开设置里的移动热点（win10）
> 4.打开命令提示符输入 ipconfig 后回车，记录无线网WLAN的IPv4地址（类似192.168.1.5这种）
> 5.手机/平板/其它电脑连接此热点后，在连接的高级选项里设置HTTP代理，模式为手动，服务器就是上面的IPv4地址，端口的话，如果是V2rayN或clash，端口为1081，如果是SSR，端口是1080，别搞错
> 6.重新连接热点，即可翻墙

没那么麻烦，电脑不用开热点。
电脑设置好后，手机与电脑连接同一WiFi，在手机WLAN高级设置里选择代理，地址填写电脑ip，端口填写http端口，保存。手机即可正常上网。
如果是手机流量想要共享的话，需要配置正确后打开热点，其他设备同上

**Comment by Lbosen** [comment]
我想让电视翻，但是电视不能设置代理啊

**Comment by CHIZI-0618** [comment]
> 我想让电视翻，但是电视不能设置代理啊

你看看电视的WLAN里的高级设置能不能手动设置代理。
或者网关翻墙？（这个我也不是很懂）
或者直接上软路由吧。

**Comment by 54huanan** [comment]
> 1.电脑能正常翻
> 2.打开翻墙软件里的允许局域网（LAN）连接
> 3.打开设置里的移动热点（win10）
> 4.打开命令提示符输入 ipconfig 后回车，记录无线网WLAN的IPv4地址（类似192.168.1.5这种）
> 5.手机/平板/其它电脑连接此热点后，在连接的高级选项里设置HTTP代理，模式为手动，服务器就是上面的IPv4地址，端口的话，如果是V2rayN或clash，端口为1081，如果是SSR，端口是1080，别搞错
> 6.重新连接热点，即可翻墙

成功了，谢谢。
有个问题，我电脑v2rayN监听的端口是1080，pac的端口是1082。手机使用共享代理用1080端口失败，1081却成功了。
为啥啊？

**Comment by WrathGluttony** [comment]
> 可以的，客户端配置文件中有一个 "listen": "127.0.0.1", 把 127.0.0.1 改成 0.0.0.0 就可以了。另外要配置你的防火墙使得运行 V2Ray 的机器可以被其它电脑访问。

您好，打搅一下，请问我用v2rayN v4.11最新版，在v2rayN中勾选了“来自局域网的连接”选项，手机端设置了代理IP（电脑本机IP）和端口号10809，但是手机无法科学上网，请问是哪里出问题了？
我用clash for windows的Windows客户端，允许局域网，手机是可以科学上网的；但是用v2rayN就不行了
我看了youbute的教程，是简单，但是我这里不知道为什么不行

**Comment by singularity2000** [comment]
> > 可以的，客户端配置文件中有一个 "listen": "127.0.0.1", 把 127.0.0.1 改成 0.0.0.0 就可以了。另外要配置你的防火墙使得运行 V2Ray 的机器可以被其它电脑访问。
> 
> 您好，打搅一下，请问我用v2rayN v4.11最新版，在v2rayN中勾选了“来自局域网的连接”选项，手机端设置了代理IP（电脑本机IP）和端口号10809，但是手机无法科学上网，请问是哪里出问题了？
> 我用clash for windows的Windows客户端，允许局域网，手机是可以科学上网的；但是用v2rayN就不行了
> 我看了youbute的教程，是简单，但是我这里不知道为什么不行

你好，你需要重启一下你家的路由器，然后再按照标准步骤操作一遍，一切就都解决了。

**Comment by zhaolyja** [comment]
> 1.电脑能正常翻 2.打开翻墙软件里的允许局域网（LAN）连接 3.打开设置里的移动热点（win10） 4.打开命令提示符输入 ipconfig 后回车，记录无线网WLAN的IPv4地址（类似192.168.1.5这种） 5.手机/平板/其它电脑连接此热点后，在连接的高级选项里设置HTTP代理，模式为手动，服务器就是上面的IPv4地址，端口的话，如果是V2rayN或clash，端口一般为1081或10809（具体看V2rayN客户端底部的HTTP地址），如果是SSR，端口是1080，别搞错 6.重新连接热点，即可翻墙

您好，我按照上述步骤进行操作，也重新启动了路由器，还是无法连接switch，请问是什么原因呢？

**Comment by WrathGluttony** [comment]
> > 1.电脑能正常翻 2.打开翻墙软件里的允许局域网（LAN）连接 3.打开设置里的移动热点（win10） 4.打开命令提示符输入 ipconfig 后回车，记录无线网WLAN的IPv4地址（类似192.168.1.5这种） 5.手机/平板/其它电脑连接此热点后，在连接的高级选项里设置HTTP代理，模式为手动，服务器就是上面的IPv4地址，端口的话，如果是V2rayN或clash，端口一般为1081或10809（具体看V2rayN客户端底部的HTTP地址），如果是SSR，端口是1080，别搞错 6.重新连接热点，即可翻墙
> 
> 您好，我按照上述步骤进行操作，也重新启动了路由器，还是无法连接switch，请问是什么原因呢？

在Win10的防火墙，添加xray.exe和v2fly.exe通过防火墙

**Comment by zhaolyja** [comment]
> 
我用的shadowrocket，通过的是v2ray_privoxy.exe和v2rayn.exe吗？此外我还看到一个wv2ray.exe，也需要通过吗？

**Comment by zhaolyja** [comment]
> > > 1.电脑能正常翻 2.打开翻墙软件里的允许局域网（LAN）连接 3.打开设置里的移动热点（win10） 4.打开命令提示符输入 ipconfig 后回车，记录无线网WLAN的IPv4地址（类似192.168.1.5这种） 5.手机/平板/其它电脑连接此热点后，在连接的高级选项里设置HTTP代理，模式为手动，服务器就是上面的IPv4地址，端口的话，如果是V2rayN或clash，端口一般为1081或10809（具体看V2rayN客户端底部的HTTP地址），如果是SSR，端口是1080，别搞错 6.重新连接热点，即可翻墙
> > 
> > 
> > 您好，我按照上述步骤进行操作，也重新启动了路由器，还是无法连接switch，请问是什么原因呢？
> 
> 在Win10的防火墙，添加xray.exe和v2fly.exe通过防火墙

我用的shadowrocket，通过的是v2ray_privoxy.exe和v2rayn.exe吗？此外我还看到一个wv2ray.exe，也需要通过吗？

**Comment by WrathGluttony** [comment]
> > > > 1.电脑能正常翻 2.打开翻墙软件里的允许局域网（LAN）连接 3.打开设置里的移动热点（win10） 4.打开命令提示符输入 ipconfig 后回车，记录无线网WLAN的IPv4地址（类似192.168.1.5这种） 5.手机/平板/其它电脑连接此热点后，在连接的高级选项里设置HTTP代理，模式为手动，服务器就是上面的IPv4地址，端口的话，如果是V2rayN或clash，端口一般为1081或10809（具体看V2rayN客户端底部的HTTP地址），如果是SSR，端口是1080，别搞错 6.重新连接热点，即可翻墙
> > > 
> > > 
> > > 您好，我按照上述步骤进行操作，也重新启动了路由器，还是无法连接switch，请问是什么原因呢？
> > 
> > 
> > 在Win10的防火墙，添加xray.exe和v2fly.exe通过防火墙
> 
> 我用的shadowrocket，通过的是v2ray_privoxy.exe和v2rayn.exe吗？此外我还看到一个wv2ray.exe，也需要通过吗？

shadowrocket没用过，您可以试试通过

**Comment by zhaolyja** [comment]
> > > > > 1.电脑能正常翻 2.打开翻墙软件里的允许局域网（LAN）连接 3.打开设置里的移动热点（win10） 4.打开命令提示符输入 ipconfig 后回车，记录无线网WLAN的IPv4地址（类似192.168.1.5这种） 5.手机/平板/其它电脑连接此热点后，在连接的高级选项里设置HTTP代理，模式为手动，服务器就是上面的IPv4地址，端口的话，如果是V2rayN或clash，端口一般为1081或10809（具体看V2rayN客户端底部的HTTP地址），如果是SSR，端口是1080，别搞错 6.重新连接热点，即可翻墙
> > > > 
> > > > 
> > > > 您好，我按照上述步骤进行操作，也重新启动了路由器，还是无法连接switch，请问是什么原因呢？
> > > 
> > > 
> > > 在Win10的防火墙，添加xray.exe和v2fly.exe通过防火墙
> > 
> > 
> > 我用的shadowrocket，通过的是v2ray_privoxy.exe和v2rayn.exe吗？此外我还看到一个wv2ray.exe，也需要通过吗？
> 
> shadowrocket没用过，您可以试试通过

好滴，谢谢啦！

**Comment by Dell911** [comment]
配置文件改成 0.0.0.0 他老是又自动改回127.0.0.1怎么办

**Comment by real-jiakai** [comment]
1. 安卓手机打开v2rayNG软件，设置里面打开允许来自局域网连接。
2. 手机开启热点分享
3. windows电脑连接手机热点
4. win+r打开cmd窗口，输入ipconfig
5. 找到无线局域网适配器WLAN最下方的默认网关。具体见下图：

![image](https://user-images.githubusercontent.com/82650452/193563521-5d7884c1-480f-4301-aecc-80bfd31c4e5a.png)

6. 打开windows电脑的网络与internet设置，点击代理。
7. 手动设置代理，使用代理服务器，编辑代理IP地址为step5得到的默认网关，端口填入10809。
8. 起飞。

**Comment by greader3** [comment]
> 配置文件改成 0.0.0.0 他老是又自动改回127.0.0.1怎么办

现在不用在配置文件里改了，即使在配置文件里改，重启v2rayn后，也会覆盖。局域网里访问http,默认是10811 socks是10810
![微信截图_20221026083639](https://user-images.githubusercontent.com/96658901/197907401-f284ded4-f9c5-4424-a509-a1553788b67f.png)

**Comment by getr00t** [comment]
> > 配置文件改成 0.0.0.0 他老是又自动改回127.0.0.1怎么办
> 
> 现在不用在配置文件里改了，即使在配置文件里改，重启v2rayn后，也会覆盖。局域网里访问http,默认是10811 socks是10810 ![微信截图_20221026083639](https://user-images.githubusercontent.com/96658901/197907401-f284ded4-f9c5-4424-a509-a1553788b67f.png)

我使用的是vmess为什么这样手机还是无法联网你

**Comment by tank863523** [comment]
自己建ChatGPT需要使用web服务器，这个服务器怎么使用代理。试了好几种问chatGPT给的代码没法使用v2ray的代理。网上也没搜到。

**Comment by Gohoy** [comment]
> 配置文件改成 0.0.0.0 他老是又自动改回127.0.0.1怎么办

请问解决了吗，我也是这个问题，并且直接使用下面的默认端口 是connection refused

**Comment by Faustina0106** [comment]
我的设备按照说明填写好参数后，联网显示无法获取IP，有大神知道怎么解决吗

**Comment by zmm1996** [comment]
![image](https://github.com/user-attachments/assets/60380508-f5a6-4d8d-831e-3678bda6a651)

1、开启运行局域网连接
2、右下角显示局域网端口就可以了

**Comment by yao2friend** [comment]
请问为什么就telegram不能用，YouTube chrome就可以，而且电脑端也可以访问telegram

**Comment by EluneAdore** [comment]
> 请问为什么就telegram不能用，YouTube chrome就可以，而且电脑端也可以访问telegram

同样的问题，手机端TG无法使用
