### ISSUE TITLE
API通信加密和认证

### ISSUE THREAD

**Issue by ix64** [v2ray/v2ray-core#2100]
目前的API通信是完全没有认证和加密的，这导致当前API仅能在本地使用，无法进行远程控制。
考虑到gRPC本身便是支持TLS通信和Token Header认证的，仅需适配，工作量应该不会很大。
因此，希望能够支持API的通信加密和认证。

**Comment by Cwek** [comment]
直接套vmess转接就行了？

**Comment by ix64** [comment]
哦 这样 倒是没想到。
谢谢你！我试一试。
