### ISSUE TITLE
没有那个exe可执行文件

### ISSUE THREAD

**Issue by abc-123-sudo** [v2ray/v2ray-core#2106]
请问我下载的是v2ray-core-4.21.3，但是解压后发现怎么没有exe的可执行文件啊，在Git找了几个都是这样的问题，请问我该怎么办，有教程吗

![3](https://user-images.githubusercontent.com/58934360/70893270-b6bdeb00-2025-11ea-9cfa-58a02d24a5f8.png)

**Comment by kslr** [comment]
找Windows客户端
