### ISSUE TITLE
新功能：“可以配置一个用户id的客户端连接数目”

### ISSUE THREAD

**Issue by JohnGuoy** [v2ray/v2ray-core#2107]
目前一个用户id可以被多个客户端软件使用，例如同时被v2rayN和shadowrocket小火箭连接。如何限制一个用户id只能被一个客户端软件使用？

希望增加新功能：“可以配置一个用户id的客户端连接数目”。其实就是类似其他vpn的“一个vpn账户支持3台客户端设备”这样的功能。

Thanks，要是出了这个功能，我会捐赠v2ray。

**Comment by kslr** [comment]
你要做机场的话为什么不考虑分析日志

**Comment by JohnGuoy** [comment]
那我fork下来自己实现这个功能
