### ISSUE TITLE
为什么我的电脑装不了v2ray啊？求解

### ISSUE THREAD

**Issue by kkyuu223** [v2ray/v2ray-core#2108]
![image](https://user-images.githubusercontent.com/50545800/70961428-bde40800-20bc-11ea-9636-b725e3d9e0f6.png)
我大开里面的文件v2ray.exe就出现以下界面
![image](https://user-images.githubusercontent.com/50545800/70961470-d7854f80-20bc-11ea-933c-a67902a8ce69.png)
我下的安装包是：v2ray-windows-64.zip   
电脑配置：
![image](https://user-images.githubusercontent.com/50545800/70961598-39de5000-20bd-11ea-8eee-cc69ecf09140.png)
萌新一个.有哪方面出错了？

**Comment by qingfengshi** [comment]
配置文件有错误吧，需要仔细检查一下，包括标点符号

**Comment by kslr** [comment]
我猜你需要打开wv2ay

**Comment by zhinengyongyingshu** [comment]
你下错了 v2rayN才是傻瓜安装版 其他的都要命令行这些 不是普通人用的
