### ISSUE TITLE
V2ray very high ping and slow speeds for both Vmess and SS for no reason. Server client issue.

### ISSUE THREAD

**Issue by OneHappyForever** [v2ray/v2ray-core#2111]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

4.21.3

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

Chrome FAST.com VMESS v2ray and Shadowsocks

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

The Ping and speed in "more info" is much higher when using the v2ray app. 

When using v2ray server running vmess and shadowsocks, ping is around 500ms and speed around 40Mbps. When running Shadowsocks python version, ping is 130 ms and speed is 70Mbps and over. Same server. 

This is not a vmess issue. This is a v2ray server program issue, as running shadowsocks on the v2ray server client also produces high ping and slow speeds. 

THIS IS THE SAME ACROSS SERVERS, on many servers.

4) 你期待看到的正确表现是怎样的？

Same ping and speed on both shadowsocks-python and v2ray for shadowsocks at least.

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

{
	"log": {
		"access": "/var/log/v2ray/access-new.log",
		"error": "/var/log/v2ray/error-new.log",
		"loglevel": "warning"
	},
	"inbounds": [
		{
      "port": 222, // Listening port 
      "protocol": "shadowsocks",
      "settings": {
        "method": "chacha20",
        "ota": false,
        "password": "password" // Password of Shadowsocks
      }
    }
	],
	"outbounds": [
		{
			"protocol": "freedom",
			"settings": {}
		}
	],
	"dns": {
		"server": [
			"1.1.1.1",
			"1.0.0.1",
			"8.8.8.8",
			"8.8.4.4",
			"localhost"
		]
	},
	"transport": {
		"sockopt": {
			"tcpFastOpen": true
		}
	}
}

```javascript
    // 在这里附上服务器端配置文件
```

客户端配置:

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by OneHappyForever** [comment]
Config for server already provided. Config for client is just v2rayN on windows, using shadowsocks setup and vmess setup in accord with server side config. I can connect no issues.

As for logs:
error.log:

2019/12/17 14:56:05 [Warning] v2ray.com/core: V2Ray 4.21.3 started
2019/12/17 14:57:02 [Warning] v2ray.com/core: V2Ray 4.21.3 started
2019/12/17 15:01:49 [Warning] v2ray.com/core: V2Ray 4.21.3 started
2019/12/17 15:03:22 [Warning] v2ray.com/core: V2Ray 4.21.3 started
2019/12/17 15:04:32 [Warning] v2ray.com/core: V2Ray 4.21.3 started
2019/12/17 15:06:30 [Warning] v2ray.com/core: V2Ray 4.21.3 started
2019/12/17 15:07:03 [Warning] v2ray.com/core: V2Ray 4.21.3 started
2019/12/17 15:10:37 [Warning] v2ray.com/core: V2Ray 4.21.3 started

access.log:

2019/12/17 15:11:31 47.100.115.181:50241 accepted tcp:ipv4-c001-hkg001-ix.1.oca.nflxvideo.net:443 
2019/12/17 15:11:31 47.100.115.181:50244 accepted tcp:safebrowsing.googleapis.com:443 
2019/12/17 15:11:36 47.100.115.181:50247 accepted tcp:ipv4-c028-sin001-ix.1.oca.nflxvideo.net:443 
2019/12/17 15:11:49 47.100.115.181:50254 accepted tcp:api.fast.com:443 
2019/12/17 15:11:49 47.100.115.181:50253 accepted tcp:ichnaea-web.netflix.com:443 
2019/12/17 15:11:50 47.100.115.181:50257 accepted tcp:ipv4-c022-hkg001-ix.1.oca.nflxvideo.net:443 
2019/12/17 15:11:50 47.100.115.181:50266 accepted tcp:ipv4-c020-sin001-ix.1.oca.nflxvideo.net:443 
2019/12/17 15:11:50 47.100.115.181:50267 accepted tcp:ipv4-c020-hkg001-ix.1.oca.nflxvideo.net:443 
2019/12/17 15:11:50 47.100.115.181:50269 accepted tcp:ipv4-c654-sjc002-dev-ix.1.oca.nflxvideo.net:443 
2019/12/17 15:11:50 47.100.115.181:50268 accepted tcp:ipv4-c031-sin001-ix.1.oca.nflxvideo.net:443

**Comment by kslr** [comment]
Check your network

**Comment by OneHappyForever** [comment]
Same network. Test is done just minutes from each other. If the network was bad, why is one test so much better/faster than the other? I did multiple tests.

**Comment by kslr** [comment]
There are no suspicious events in the log. Also,  your measurement method is wrong, ping is ICMP data, this only means that your network was slow at the time.

**Comment by OneHappyForever** [comment]
Ok, I found the issue. The DNS server I was using was getting fast.com to use testing servers in the us, whereas shadowsocks-python was using different DNS servers that was faster.

Thanks for your time and help :) Much appreciated
