### ISSUE TITLE
Looking forward to "-reload"

### ISSUE THREAD

**Issue by BlackMask007** [v2ray/v2ray-core#2115]
我目前遇到一个问题，在动态管理用户时添加或删除r2ray用户都需要重启v2ray服务来重新加载配置，这样给其他已建立连接通讯的用户带来了影响，造成了已连接客户通讯不稳定。希望在这方面可以改进。
配置重载功能是实现多用户增加/删除同时不影响其他在线用户使用的需求，如果在v2ray运行过程中支持重新载入配置文件，那么大大提高了动态用户管理。

**Comment by ix64** [comment]
可以通过api来动态配置用户

**Comment by BlackMask007** [comment]
谢谢你的解答，我刚刚接触v2ray，请问有应用的实例吗？或者方便多用户管理的开源项目，可以向我推荐一下吗？

MengYX <notifications@github.com> 于2019年12月21日周六 下午8:17写道：

**Comment by ix64** [comment]
都是基于grpc的
可以参考一下这里
https://github.com/v2ray/v2ray-core/blob/master/infra/control/api.go
https://github.com/v2ray/v2ray-core/blob/master/testing/scenarios/command_test.go

**Comment by BlackMask007** [comment]
谢谢

MengYX <notifications@github.com> 于2019年12月22日周日 下午12:42写道：

**Comment by BlackMask007** [comment]
@ix64  谢谢
