### ISSUE TITLE
Archlinux 登录服务器日志显示不存在的用户

### ISSUE THREAD

**Issue by littlesum** [v2ray/v2ray-core#2118]
Please read the [instruction](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md) and answer the following questions before submitting your issue. Thank you.
Please answer all the questions with enough information. All issues not following this template will be closed immediately.
If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2ray/discussion/issues) first.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
last version
server ubuntu 18.03 lts v2ray 4.21.3
client archlinux v2ray 4.21.3
client win7 64 v2ray 4.21.3
安卓 v2rayng 
2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
vmess ws tls nginx
3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)
安卓v2ray ng win客户端 全部都能使用，但是archlinux用同样的config.json 连不上！
ubuntu 服务器端显示 不存在的用户
4) What's your expectation?

5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

Server configuration:

```javascript
    // Please attach your server configuration here.
```

Client configuration:

```javascript
    // Please attach your client configuration here.
```

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.

Server error log:

```javascript
    // Please attach your server error log here.
```

Client error log:

```javascript
    // Please attach your client error log here.
```

7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.

```javascript
    // Please attach your server access log here.
```

8) Other configurations (such as Nginx) and logs.

9) If V2Ray doesn't run, please attach output from `--test`.

The command is usually `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`, but may vary according to your scenario.

10) If V2Ray service doesn't run, please attach journal log.

Usual command is `journalctl -u v2ray`.

Please review your issue before submitting.

**Comment by littlesum** [comment]
server
2019/12/22 09:34:26 [Info] [1556717838] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: invalid request from 127.0.0.1:40974 > v2ray.com/core/proxy/vmess/encoding: invalid user 2019/12/22 09:34:27 [Info] [2092320435] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: invalid request from 127.0.0.1:40976 > v2ray.com/core/proxy/vmess/encoding: invalid user 2019/12/22 09:34:27 [Info] [1231521234] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: invalid request from 127.0.0.1:40980 > v2ray.com/core/proxy/vmess/encoding: invalid user 2019/12/22 09:34:31 [Info] [1571260656] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: invalid request from 127.0.0.1:41008 > v2ray.com/core/proxy/vmess/encoding: invalid user 2019/12/22 09:34:31 [Info] [2413321782] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: invalid request from 127.0.0.1:41034 > v2ray.com/core/proxy/vmess/encoding: invalid user 2019/12/22 09:34:54 [Info] [828792322] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: invalid request from 127.0.0.1:41078 > v2ray.com/core/proxy/vmess/encoding: invalid user 2019/12/22 09:34:54 [Info] [2889290407] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: invalid request from 127.0.0.1:41080 > v2ray.com/core/proxy/vmess/encoding: invalid user 2019/
019/12/22 09:37:38 127.0.0.1:41236 rejected v2ray.com/core/proxy/vmess/encoding: invalid user 2019/12/22 09:37:38 127.0.0.1:41238 rejected v2ray.com/core/proxy/vmess/encoding: invalid user 2019/12/22 09:37:55 127.0.0.1:41242

**Comment by littlesum** [comment]
client
failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal) 2019/12/22 09:34:00 [Warning] [1978316095] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal) 2019/12/22 09:34:00 [Warning] [3363322375] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal) 2019/12/22 09:34:00 [Warning] [3069663252] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal) 2019/12/22 09:34:00 tcp:127.0.0.1:51338 accepted tcp:lh3.googleusercontent.com:443 [out-0] 2019/12/22 09:34:00 tcp

**Comment by littlesum** [comment]
换成安卓客户端 日志如下
ot@m:~# tail /var/log/v2ray/access.log 
2019/12/22 09:41:13 127.0.0.1:41680 accepted tcp:app-measurement.com:443 [direct] 
2019/12/22 09:41:14 127.0.0.1:41684 accepted tcp:aweme-swan.snssdk.com:443 [direct] 
2019/12/22 09:41:15 127.0.0.1:41688 accepted tcp:szshort.weixin.qq.com:80 [direct] 
2019/12/22 09:41:15 127.0.0.1:41690 accepted tcp:203.119.128.4:80 [direct] 
2019/12/22 09:41:16 127.0.0.1:41696 accepted tcp:www.google.com:80 [direct] 
2019/12/22 09:41:17 127.0.0.1:41700 accepted udp:220.243.131.110:443 [direct] 
2019/12/22 09:41:26 127.0.0.1:41702 accepted udp:1.1.1.1:53 [direct] 
2019/12/22 09:41:26 127.0.0.1:41704 accepted tcp:adash.man.aliyuncs.com:80 [direct] 
2019/12/22 09:41:48 127.0.0.1:41712 accepted udp:1.1.1.1:53 [direct] 
2019/12/22 09:41:48 127.0.0.1:41714 accepted tcp:www.google.com:443 [direct]

**Comment by littlesum** [comment]
windows 下测试也是正常的 搞不明白archlinux 哪里不对

**Comment by kslr** [comment]
时间

**Comment by littlesum** [comment]
> 时间

好的 那我搞个ntp 试试

**Comment by littlesum** [comment]
closed  
把时间搞了下来就一切正常了 ！忽视这个问题了！坑死我了！
