### ISSUE TITLE
windows 客户端能做好用点不？

### ISSUE THREAD

**Issue by waitandsoon** [v2ray/v2ray-core#212]
windows 客户端能做好用点不？
真难用啊。。。。。

**Comment by Sherman-Liu** [comment]
Please leave constructive comments, not just complain.

**Comment by v2ray** [comment]
欢迎为 V2Ray 开发客户端：https://www.v2ray.com/zh_cn/chapter_01/3rd_party.html

**Comment by yjd** [comment]
@v2ray 
chrome访问上面的网站。
客户端和服务器不支持常用的 SSL 协议版本或加密套件。导致此问题的原因通常是服务器要求使用 RC4，而这种加密方式根据当前标准已不够安全

**Comment by v2ray** [comment]
@yjd 你的 Chrome 是什么版本？看上去像是 CloudFlare 输出了一个不正常的加密方式

**Comment by yjd** [comment]
@v2ray 
 CentBrowser 1.8  https://www.centbrowser.com/history.html
2k3系统

**Comment by v2ray** [comment]
看文档似乎是 Windows 2003 的问题，它有可能不支持新的 TLS 算法，然后 Chrome 又不支持老的，于是报错了。

https://support.microsoft.com/en-us/kb/3050509

**Comment by yjd** [comment]
@v2ray 收到。看来是2k3只支持到tls 1.0 的问题。
已经打了补丁，又用
https://portal.chicagonettech.com/kb/a179/maximizing-ssl-security-for-windows-server-2003-ssl-tls.aspx配置还是不行。
chrome老版本是有开启的选项，新的没了。

**Comment by v2ray** [comment]
所以还是用最新版的 Windows 吧

**Comment by yjd** [comment]
@v2ray 同2k3环境下，刚发现走xx-net代理是可以打开的，是xx导入了一个ca证书有关？走ssr和直连不行跟上面讨论的一样。
正在入门v2ray-core配置。
