### ISSUE TITLE
sniffing 流程优化

### ISSUE THREAD

**Issue by FH0** [v2ray/v2ray-core#2126]
![image](https://user-images.githubusercontent.com/32861476/71392430-f6e32600-2642-11ea-8618-ff2edc6a2bc9.png)

上面是 v2ray 目前的 sniffing 流程，但没有考虑域名解析结果为空的结果，应该改成下面的流程。

**Comment by kslr** [comment]
Res本身也不是一个合法的域名 你可试试写到hosts

**Comment by FH0** [comment]
> Res本身也不是一个合法的域名 你可试试写到hosts

这个方法可以，但如果 IP 变化的话会失效。

**Comment by kslr** [comment]
如果你设置了dns就必须要转交处理，但是一个错误的使用方式我觉得是没有兼容的必要

**Comment by FH0** [comment]
> 如果你设置了dns就必须要转交处理，但是一个错误的使用方式我觉得是没有兼容的必要

好吧，res.res.res.res 这个问题确实是迅雷的锅，但第二种处理流程兼容性确实会更好。

**Comment by RRRRRm** [comment]
@FH0 所以您的解决方案是什么

**Comment by RRRRRm** [comment]
我也遇到了这个问题

**Comment by FH0** [comment]
> @FH0 所以您的解决方案是什么

目前我修改了源码，增加了判断
