### ISSUE TITLE
v2ray-linux-arm 4.21.3 crash for asus AC5300.(ASUSWRT-Merlin)

### ISSUE THREAD

**Issue by zw963** [v2ray/v2ray-core#2128]
1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

v2ray-linux-arm 4.21.3

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

Asus AC5300

3) reproduce

More older version (4.20.0) work well for my ASUS router, but, when update to 4.21.3, it get broken.

```sh
admin@RT-AC5300-25B0:/tmp/home/root/v2ray1# ./v2ray -version
Illegal instruction
```

4.20.0 working

```
admin@RT-AC5300-25B0:/tmp/home/root/v2ray# ./v2ray -version
V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.

admin@RT-AC5300-25B0:/tmp/home/root/v2ray1# uname -a
Linux RT-AC5300-25B0 2.6.36.4brcmarm #1 SMP PREEMPT Wed Jul 31 13:38:44 EDT 2019 armv7l ASUSWRT-Merlin
```

Thank you.

**Comment by kslr** [comment]
This is due to a problem with the arm version, I suggest you keep the 4.20.0 version

**Comment by kslr** [comment]
Try 4.22.0

**Comment by zw963** [comment]
It working,  thank you!

**Comment by zw963** [comment]
@kslr , 4.22.1 not working again for AC5300.

**Comment by kslr** [comment]
Check CPU platform

**Comment by zw963** [comment]
@kslr , same router, i just want to say, my router was not working with 4.21.3, but it working on 4.22.0 after you resolve this issue, but, it not working again on 4.22.1.

```sh
admin@RT-AC5300-25B0:/tmp/home/root# uname -a
Linux RT-AC5300-25B0 2.6.36.4brcmarm #1 SMP PREEMPT Tue Dec 31 22:31:51 EST 2019 armv7l ASUSWRT-Merlin

admin@RT-AC5300-25B0:/tmp/home/root# cat /proc/cpuinfo
Processor       : ARMv7 Processor rev 0 (v7l)
processor       : 0
BogoMIPS        : 2798.38

processor       : 1
BogoMIPS        : 2798.38

Features        : swp half thumb fastmult edsp
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc09
CPU revision    : 0

Hardware        : Northstar Prototype
Revision        : 0000
Serial          : 0000000000000000
```

**Comment by zw963** [comment]
I double check again, not working.


```sh
admin@RT-AC5300-25B0:/tmp/home/root/121# ./v2ray
Illegal instruction
admin@RT-AC5300-25B0:/tmp/home/root/121# ./v2ray_armv6
Illegal instruction
admin@RT-AC5300-25B0:/tmp/home/root/121# ./v2ray_armv7
Illegal instruction

admin@RT-AC5300-25B0:/tmp/home/root/121# /opt/sbin/v2ray -version
V2Ray 4.22.0 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.

```
if you need me help to test, please let me know, thank you.

**Comment by kslr** [comment]
try arm64

**Comment by zw963** [comment]
> try arm64

```sh
admin@RT-AC5300-25B0:/tmp/home/root/122# ./v2ray
./v2ray: line 1: ELF�P�@�@8@@@@�����dd�d�deff: not found
./v2ray: line 2: �: not found
./v2ray: line 1: syntax error: unexpected word (expecting ")")
admin@RT-AC5300-25B0:/tmp/home/root/122# ./v2ctl
./v2ctl: line 1: syntax error: unterminated quoted string
```

Should we reenable this issue? @kslr

**Comment by zw963** [comment]
Are you still consider fix this broken for this ASUS ARM router? i guess i need limit to only download version 4.22.0 on my router automate scirpt if we have no plan to support router yet. 

thank you.

**Comment by kslr** [comment]
try new arm file

**Comment by zw963** [comment]
@kslr , sorry, where is the download address for new fixed precompile ARM binary?

**Comment by kslr** [comment]
https://github.com/v2ray/v2ray-core/releases/download/v4.22.1/v2ray-linux-arm.zip

**Comment by zw963** [comment]
@kslr , 4.22.1 is working again, thank you!
