### ISSUE TITLE
v2ray-windows-32 在64位win上使用会有问题吗

### ISSUE THREAD

**Issue by ysbreh** [v2ray/v2ray-core#2129]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
最新版

v2ray-windows-32 在64位win上使用会有问题吗，我使用目前是正常的，会不会有什么问题，有必要一定使用v2ray-windows-64吗？

**Comment by kslr** [comment]
没有

ysbreh <notifications@github.com> 於 2019年12月25日週三 下午12:29寫道：
