### ISSUE TITLE
KCP/mKCP 协议能否增加加密设置选项？

### ISSUE THREAD

**Issue by poly-1** [v2ray/v2ray-core#2131]
有个问题可能需要在帮助文档里面说明，即当前内置的mKCP默认是否进行了加密？

如果当前是直接转发加密后的VMess数据包，是否会容易导致干扰？能否像KCPTun一样配置额外的加密方式？

**Comment by kslr** [comment]
为什么直接转发会导致干扰？ 什么是额外的加密

**Comment by poly-1** [comment]
> 为什么直接转发会导致干扰？ 什么是额外的加密

因为不加密的话，至少VMess协议的头部是明文，攻击者是不是会较为容易的进行篡改？再进行一次加密至少可以使VMess头部没那么容易被篡改

好比https+tls虽然很安全，但可以被中间人攻击，虽然中间人攻击我们可以察觉，但还是导致了证书错误以至于通信中断。但如果https+tls在VMess隧道上传输，中间人攻击的难度大幅上升。

其实，我比较想知道当前mKCP协议的具体实现，因为KCPTun默认是会自带加密的，相当于双层加密。当前的mKCP就是直接转发加密后的VMess数据包吗？

**Comment by kslr** [comment]
@xiaokangwang

**Comment by Steve789** [comment]
我没记错的话，TLS1.2/1.3是可以防止中间人攻击的。

**Comment by Steve789** [comment]
mkcp似乎是V2ray里面不太推荐使用的配置。

**Comment by poly-1** [comment]
> 我没记错的话，TLS1.2/1.3是可以防止中间人攻击的。

这里讨论的是 mKCP + VMess， 而使用 mKCP + TLS 是一种很扯的用法。

> mkcp似乎是V2ray里面不太推荐使用的配置。

mKCP 在一些丢包率高的网络环境有奇效。

**Comment by jinmiaoluo** [comment]
如果需要稳定的服务的话. 不推荐使用 mKCP + VMess.

我用过一段时间. 在 6 月 4 号前后. 服务器的端口被封了. 后来转为了 VMess +
TLS + WebSocket.

**Comment by YifengGao666** [comment]
mKCP + VMess确实会导致封端口。 不开kcp虽然安全但是速度会慢很多。真的很难取舍...

看到有篇专利说可以识别mKCP的头部，不知道是不是真的。



> 如果需要稳定的服务的话. 不推荐使用 mKCP + VMess. 我用过一段时间. 在 6 月 4 号前后. 服务器的端口被封了. 后来转为了 VMess + TLS + WebSocket.
> […](#)
> On Wed, Jan 22, 2020 at 07:52:20PM -0800, poly-1 wrote: > 我没记错的话，TLS1.2/1.3是可以防止中间人攻击的。 这里讨论的是 mKCP + VMess， 而使用 mKCP + TLS 是一种很扯的用法。 > mkcp似乎是V2ray里面不太推荐使用的配置。 mKCP 在一些丢包率高的网络环境有奇效。 -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: [#2131 (comment)](https://github.com/v2ray/v2ray-core/issues/2131#issuecomment-577492394)

**Comment by okudayukiko** [comment]
现阶段用TLS比较安全（可能自签名TLS都被识别了）

**Comment by poly-1** [comment]
@jinmiaoluo @okudayukiko 我知道TLS比较安全，但该issue讨论的是mkcp以及是否应该给mkcp提供额外加密的问题，为什么非要把TLS扯进来？你的意思是使用 mkcp + TLS 作为额外加密来解决我一开始提的问题吗？
