### ISSUE TITLE
连接服务器时用户总被判定为invalid user

### ISSUE THREAD

**Issue by DanielFeak** [v2ray/v2ray-core#2132]
在使用如下配置时从今天起的某个时段就再也无法通过服务器连接网络，之前已经有这种情况但一直没有完全阻断，今天彻底无法连接了，服务器那边显示自己的IP为invalid user
服务器相关配置：(id已经隐藏)
"inbounds":[{
    // Port to listen on. You may need root access if the value is less than 1024.
    "port": 25565,

    // IP address to listen on. Change to "0.0.0.0" to listen on all network interfaces

    // Tag of the inbound proxy. May be used for routing.
    // Protocol name of inbound proxy.
    "protocol": "vmess",

    // Settings of the protocol. Varies based on protocol.
    "settings": {
        "clients":[{"id":"****","alterid":64}]
    },
        "streamSettings":{
                "network":"ws",
                "wsSettings":{"path":"/ray"}
        }
}],
用的caddy伪装，未使用域名，用的本机ip
客户端配置：
"inbound": {
    "port": 1081,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "127.0.0.1"
    },
    "destOverride": ["http","tls"]

  },
  "inboundDetour": [
    {
      "protocol": "http",
      "port": 8081,
      "listen": "127.0.0.1",
      "allocate": {
        "strategy": "always",
        "refresh": 5,
        "concurrency": 3
      },
      "settings": {},
      "streamSettings": {},
      "domainOverride": [ "http", "tls" ]
    }
  ],
  "log": { "loglevel": "none" },
  "outbound": {
    "sendThrough": "0.0.0.0",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "remark": "sample",
          "address": "*****",
          "port": *,
          "users": [
            {
              "id": "*****",
              "alterId": 64,
              "security": "aes-128-cfb"
            }
          ]
        }
      ]
    },

**Comment by kslr** [comment]
ref https://github.com/v2ray/v2ray-core/issues/535#issuecomment-568895390
