### ISSUE TITLE
error in server when I want to create v2ray proxy node.

### ISSUE THREAD

**Issue by appleyuchi** [v2ray/v2ray-core#2135]
same as https://github.com/v2ray/v2ray-core/issues/2133

could anyone tell me how to solve?

Which part of documentation is relevant to my problem?

**Comment by DolorHunter** [comment]
You need a certification before you turn TLS on.
Read the [guide](https://guide.v2fly.org/advanced/tls.html) first or turn off TLS.
Both solutions work.

**Comment by DolorHunter** [comment]
Stongly recomand you to read the reply in #2133 again.
