### ISSUE TITLE
用户流量统计

### ISSUE THREAD

**Issue by ztc1997** [v2ray/v2ray-core#214]
目前是否支持对每个用户（email）统计流量？我似乎没有找到这个功能，如果有，怎么做？如果没有，是否考虑将来加入

**Comment by v2ray** [comment]
会的，等 proxy 部分完成，之后会开放 API。

**Comment by ztc1997** [comment]
@v2ray 建议项目里面加个todo-list，方便协作，也让一般用户知道还有什么功能将被做出来

**Comment by v2ray** [comment]
有的，就是这个 enhancement 标签

**Comment by v2ray** [comment]
moved to https://github.com/v2ray/Planning/issues/2
