### ISSUE TITLE
路由器梅林科學上網插件無法連接 V2Ray + Nginx + TLS

### ISSUE THREAD

**Issue by jpun1127** [v2ray/v2ray-core#2140]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V2Ray v4.21.3
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
 V2Ray + Nginx + TLS
用路由器連接v2ray服務器作為透明代理，用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频

V2RAY 服務器:
Google Cloud VPS (Ubuntu 16.04 LTS)
V2RAY
Nginx (用EasyEngine內置Nginx和 Let’s Encrypt搭建)

V2RAY客户端:
ASUS 86U
刷梅林固件 (Kooshare Merlin 384.14)
梅林固件科學上網插件 (V 1.8.1)

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

用IOS Shadowrocket(小火箭）連接V2RAY服務端一切正常，也可以收看YouTube 視頻，訪問google.com或Facebook等

但是用路由器梅林固件科學上網插件時是可以連接，但國外鏈接一直出現紅色X, 無法訪問國外網站，而且服務端和客戶端的日誌也沒有報錯

国外链接 【2019-12-28 19:47:54】 X
国内链接 【2019-12-28 19:47:54】 ✓  34 ms 

4) 你期待看到的正确表现是怎样的？

国外链接 【2019-12-28 19:47:54】 ✓  76 ms
国内链接 【2019-12-28 19:47:54】 ✓  34 ms 

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

    {
        "log": {
                "access": "/var/log/v2ray/access.log",
                "error": "/var/log/v2ray/error.log",
                "loglevel": "warning"
        },
        "inbound": {
                "port": 40454,
                "protocol": "vmess",
                "settings": {
                        "clients": [{
                                "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                                "level": 1,
                                "alterId": 64,
                                "security": "auto"
                        }]
                },
                "streamSettings":{
                        "network":"ws",
                        "security": "auto",
                        "wsSettings":{
                                "path": "/enterv2ray/"
                                }
                        }
        },
        "outbound": {
                "protocol": "freedom",
                "settings": {}
        },
        "outboundDetour": [
            {
                "protocol": "blackhole",
                "settings": {},
                "tag": "blocked"
            }
        ],
        "routing": {
            "strategy": "rules",
            "settings": {
                "rules": [
                    {
                        "type": "field",
                        "ip": [
                            "0.0.0.0/8",
                            "10.0.0.0/8",
                            "100.64.0.0/10",
                            "127.0.0.0/8",
                            "169.254.0.0/16",
                            "172.16.0.0/12",
                            "192.0.0.0/24",
                            "192.0.2.0/24",
                            "192.168.0.0/16",
                            "198.18.0.0/15",
                            "198.51.100.0/24",
                            "203.0.113.0/24",
                            "::1/128",
                            "fc00::/7",
                            "fe80::/10"
                        ],
                        "outboundTag": "blocked"
                    }
                ]
            }
        }
    }

客户端配置:

{
	"log": {
		"access": "/dev/null",
		"error": "/tmp/v2ray_log.log",
		"loglevel": "error"
	},
	"inbounds": [
		{
			"port": 23456,
			"listen": "0.0.0.0",
			"protocol": "socks",
			"settings": {
				"auth": "noauth",
				"udp": true,
				"ip": "127.0.0.1",
				"clients": null
			},
			"streamSettings": null
		},
		{
			"listen": "0.0.0.0",
			"port": 3333,
			"protocol": "dokodemo-door",
			"settings": {
				"network": "tcp,udp",
				"followRedirect": true
			}
		}
	],
	"outbounds": [
		{
			"tag": "agentout",
			"protocol": "vmess",
			"settings": {
				"vnext": [
					{
						"address": "xxxxxxx.cf",
						"port": 443,
						"users": [
							{
								"id": "xxxxxxxxxxxxxxxxxxxxxxxxxxx",
								"alterId": 64,
								"security": "auto"
							}
						]
					}
				],
				"servers": null
			},
			"streamSettings": {
				"network": "ws",
				"security": "tls",
				"tlsSettings": {
					"allowInsecure": true,
					"serverName": null
				},
				"tcpSettings": null,
				"kcpSettings": null,
				"wsSettings": {
					"connectionReuse": true,
					"path": "/enterv2ray/",
					"headers": null
				},
				"httpSettings": null
			},
			"mux": {
				"enabled": true,
				"concurrency": 8
			}
		}
	]
}

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

這是用Shadowrocket (小火箭）成功連上V2Ray服務端access.log和error.log的日誌,一切正常
019/12/28 19:36:02 tcp:127.0.0.1:35968 accepted tcp:api.facebook.com:443 
2019/12/28 19:36:02 tcp:127.0.0.1:35968 accepted tcp:b-api.facebook.com:443 
2019/12/28 19:36:02 tcp:127.0.0.1:35968 accepted tcp:graph.facebook.com:443 
2019/12/28 19:36:02 tcp:127.0.0.1:35968 accepted tcp:b-graph.facebook.com:443 
2019/12/28 19:36:02 tcp:127.0.0.1:35968 accepted tcp:lithium.facebook.com:443 
2019/12/28 19:36:02 tcp:127.0.0.1:35968 accepted tcp:edge-mqtt.facebook.com:443 
2019/12/28 19:36:02 tcp:127.0.0.1:35968 accepted tcp:scontent-hkg3-1.xx.fbcdn.net:443 
2019/12/28 19:36:03 tcp:127.0.0.1:35968 accepted tcp:external-hkg3-1.xx.fbcdn.net:443 
2019/12/28 19:36:04 tcp:127.0.0.1:35968 accepted tcp:scontent-hkg3-2.xx.fbcdn.net:443 

2019/12/22 22:06:33 [Warning] v2ray.com/core: V2Ray 4.21.3 started
2019/12/22 22:13:52 [Warning] v2ray.com/core: V2Ray 4.21.3 started
2019/12/27 14:08:54 [Warning] v2ray.com/core: V2Ray 4.21.3 started
2019/12/28 19:36:04 tcp:127.0.0.1:35968 accepted tcp:static.xx.fbcdn.net:443 
2019/12/28 19:36:04 tcp:127.0.0.1:35968 accepted tcp:video-hkg3-2.xx.fbcdn.net:443 
2019/12/28 19:36:04 tcp:127.0.0.1:35968 accepted tcp:video-hkg3-1.xx.fbcdn.net:443 
2019/12/28 19:36:10 tcp:127.0.0.1:35968 accepted tcp:i.ytimg.com:443 
2019/12/28 19:36:10 tcp:127.0.0.1:35968 accepted tcp:youtubei.googleapis.com:443

用路由器梅林科學上網插件連上後，無法訪問國外網站, V2Ray服務端access.log和error.log並沒有報錯

客户端错误日志:
客戶端上的v2ray_log.log也沒有報錯

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。
root@instance-1:/var/www/xxx.xxxx/conf/nginx# cat v2ray.conf

    location /enterv2ray/ {
    proxy_redirect off;
    proxy_pass http://127.0.0.1:40454;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    }

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。
V2RAY 能正常啟動

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。
V2RAY 服務運行正常
请预览一下你填的内容再提交。

**Comment by kslr** [comment]
如果没有任何日志，说明配置错误，没有转发流量过来等等

**Comment by jpun1127** [comment]
已用v2ray --test --config /etc/v2ray/config.json測試過config.json, 也反覆核對過IOS Shadowrocket(小火箭)和科學上網V2Ray插件上的設定, 也沒有甚麼差異: 仍然只是Shadowrocket(小火箭)可以連接各網站, 路遊器上的科學上網插件就不能。

請問有沒有其他甚麼方法可以監測是否有流量從客戶端轉發到服務端? 或是除了V2Ray的日誌以外, 有沒有其他系統上的日誌可以檢測到問題在哪裡?

**Comment by jpun1127** [comment]
附上--test結果和科學上網V2Ray插件的設定供你參考:

服務端
root@instance-1:/usr/bin/v2ray# ./v2ray --test --config /etc/v2ray/config.json
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
Configuration OK.

客戶端
RT-AC86U-66B8:/jffs/.koolshare# v2ray --test --config /koolshare/ss/v2ray.json
V2Ray 4.21.3 (user) 20191126-155424
A unified platform for anti-censorship.
Configuration OK.

![image](https://user-images.githubusercontent.com/59246122/71553194-da315e80-2a45-11ea-97d0-41c2b3fd6845.png)

**Comment by kslr** [comment]
你阅读下梅林插件的指南吧，可能启动后需要做什么设置
