### ISSUE TITLE
 failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)

### ISSUE THREAD

**Issue by yerphon** [v2ray/v2ray-core#2143]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
服务端为Docker Hub的最新V2ray，客户端为V2ray Core最新版
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
  Chrome上谷歌
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
有时好，有时坏。我手机用V2rayNG却一直能使用？
4) 你期待看到的正确表现是怎样的？
都能用
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
服务器端配置:

```javascript
    `{
  "log": {
    "loglevel": "warning",
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log"
  },
  "inbounds": [
    {
      "port": ,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "",
            "alterId": 64
          }
        ]
      },
      "streamSettings": {
        "network":"ws"
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}`
```

客户端配置:

```javascript
    `{
  "log": {
    "loglevel": "warning",
    "access": "D:\\Applications\\v2ray-windows\\access.log",  
    "error": "D:\\Applications\\v2ray-windows\\error.log"
  },
  "inbounds": [
    {
      "port": 1080,
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
      "settings": {
        "auth": "noauth",
        "udp": true
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "",
            "port": ,  
            "users": [
              {
                "id": "",
                "alterId": 64
              }
            ]
          }
        ]
      },
	  "streamSettings":{
        "network":"ws"
	  }
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct" //如果要使用路由，这个 tag 是一定要有的，在这里 direct 就是 freedom 的一个标号，在路由中说 direct V2Ray 就知道是这里的 freedom 了
    } 
  ],
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": ["geosite:cn"] // 中国大陆主流网站的域名
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:cn", // 中国大陆的 IP
          "geoip:private" // 私有地址 IP，如路由器等
        ]
      }
    ]
  }
}`
```

**Comment by Aerotic** [comment]
[Warning] [4114992353] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
这是我的报错log

**Comment by assmdx** [comment]
如果系统是win7,打开右下角时间和日期设置，同步一下时间就可以了

**Comment by OpenWaygate** [comment]
[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF

这是怎么回事啊? 今天突然电脑端的V2rayN显示这个, 但我可以ssh服务器, 手机上也能用, 就电脑上不行.

**Comment by wangtl175** [comment]
我的时间已经同步，但是也报这个错误，然后我换一下端口又可以用了

**Comment by taurusbo** [comment]
我本地用的win10，服务器用的centos。也出现这个报错连接不上，找了很多资料都说是时间没有同步，我给本地和服务器的时间同步服务器都调成一样，然后自动同步，错误依旧。然后我把win10的时间同步关掉，手动把时间调成和服务器一样的，就可以了。

**Comment by tvp100** [comment]
`[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF`
centos7配置旁路由，一用迅雷下种子就这样。
什么原因请问？
