### ISSUE TITLE
Cannot run on mtk7621a platform

### ISSUE THREAD

**Issue by caoli5288** [v2ray/v2ray-core#2147]
Hi I download latest mipsle version in release page and got this.
```
# ./v2ray
Illegal instruction
```

OS: openwrt version 19.7-rc2 (build from official codebase).

**Comment by forever8938** [comment]
You have to compile openwrt with FPU Emulator enabled, or use softfloat binaries.

**Comment by caoli5288** [comment]
@forever8938 THX
