### ISSUE TITLE
Dns记录的识别和重复查询问题

### ISSUE THREAD

**Issue by k79e** [v2ray/v2ray-core#2151]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
4.22.0
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
开任意门 让他做dns转发器
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
1. 遇到**空域名**的时候 日志显示**rcode:3** **同时打破路由规则** (e.g cn域名让他查询dns A 然而他用了dns B也查了一遍) 而且看起来他不仅是破了路由规则 还要把**所有dns服务器都用一遍**才成.
不仅如此 **就算**第一个cn服务器返回了记录 v2也不会管 他会一直查询下去 **直到所有**dns都用完为止 这时候**才返回**给应用程序dns结果. (也就是查询端才能收到结果)

2. 已存在域名 如果查询aaaa记录 他就算**立刻收到空响应**(合法响应 但是没有answers字段)
e.g 还是上述路由 还是查询cn域名(已存在cn域名的aaaa记录 aaaa是空记录)
这时候 就算收到空记录 v2会等4秒 然后报错. https://github.com/v2ray/v2ray-core/issues/2144#issuecomment-570027691
更夸张的 4秒之后报错的同时他会和问题1一样 继续使用其他dns 查询一遍. 如果用了第二个dns那就要等2x4=8秒 总时间了!! 更多dns没测试. 目前环境只有2个dns. 一个国内一个国外.
4) 你期待看到的正确表现是怎样的？
无论怎样的情况 只要收到合法dns请求 就应当转发给应用程序.
判断依据应当使用dns flags的位组https://en.wikipedia.org/wiki/Domain_Name_System#DNS_message_format
我不知道no such name是否有判断机制 目前日志里面也显示的有rcode:3

rfc规范不太懂 但是rcode应该一共就那么几种.
所以如果使用了第一个bit 是1.(是回答类型) 最后4个位组(rcode)也是正常的. 就应当立刻转发收到的dns结果.

note: 位组是2个字节 也就是16bit. 位置是dns回显报文的3-4 hex字节.

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:
不需要服务端 或者客户端就是服务端

客户端配置:
{
"listen": "127.0.0.2",
"port": 53,
"tag": "dns",
"protocol": "dokodemo-door",
"settings": {
"address": "8.8.8.8",
"port": 53,
"network": "tcp,udp" 
	}
}
.....

  "dns": {
    "servers": [
	{#"network":"tcp",
        "address": "xxxx", //**国外dns**
	"port": 非53端口 },
	      {
        "address": "127.0.0.1",
        "port": 53,
        "domains": ["geosite:cn","xxxx","xxxx","xxxx"]
      }  
    ]
  }

路由
 "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "port": null,
        "outboundTag": "direct",
        "ip": null,
        "domain": [
          "xxxxxx"
        ]
      },
{
  "type": "field",
  "inboundTag": ["dns"],
  "outboundTag": "dns-out"
},
      {
        "type": "field",
        "port": null,
        "outboundTag": "direct",
        "ip": [
          "geoip:private"
        ],
        "domain": null
      },
      {
        "type": "field",
        "port": null,
        "outboundTag": "direct",
        "ip": [
          "geoip:cn"
        ],
        "domain": null
      },
      {
        "type": "field",
        "port": null,
        "outboundTag": "direct",
        "ip": null,
        "domain": [
          "geosite:cn"
        ]
      }

----------------------------------------------------------
日志
TypeA -> [] 105.006ms
....
TypeA -> [] 486.0278ms

;; Query time: 592 msec
;; SERVER: 127.0.0.2#53(127.0.0.2)
我只开了info日志 不需要的内容我都删了.

更详细日志
2020/01/01 15:31:28 [Info] v2ray.com/core/proxy/freedom: opening connection to u
dp:127.0.0.1:53
2020/01/01 15:31:28 [Info] v2ray.com/core/app/dns: UDP:127.0.0.1:53 got answere:
 域名A. TypeA -> [] 118.0068ms
2020/01/01 15:31:28 [Info] v2ray.com/core/app/dns: failed to lookup ip for domai
n 域名A at server UDP:127.0.0.1:53 > rcode: 3
2020/01/01 15:31:28 [Info] v2ray.com/core/transport/internet/udp: establishing n
ew connection for udp:国外dns
2020/01/01 15:31:28 [Info] v2ray.com/core/app/dispatcher: default route for udp:
国外dns
2020/01/01 15:31:28 [Info] v2ray.com/core/proxy/freedom: opening connection to u
dp:国外dns
2020/01/01 15:31:28 [Info] v2ray.com/core/app/dns: UDP:国外dns got answe
re: 域名A. TypeA -> [] 414.0236ms
2020/01/01 15:31:28 [Info] v2ray.com/core/app/dns: failed to lookup ip for domai
n 域名A at server UDP:国外dns > rcode: 3

414+118=**532ms**

dig
;; Query time: 533 msec
;; SERVER: 127.0.0.2#53(127.0.0.2)

------------------
log 2 国内域名 存在的域名 aaaa是空记录

2020/01/01 15:38:27 [Info] v2ray.com/core/proxy/freedom: opening connection to u
dp:127.0.0.1:53
2020/01/01 **15:38:27** [Info] v2ray.com/core/app/dns: UDP:127.0.0.1:53 got answere:
 域名A. TypeAAAA -> [] **0s**
2020/01/01 **15:38:31** [Info] v2ray.com/core/app/dns: failed to lookup ip for domai
n 域名A at server UDP:127.0.0.1:53 > context deadline exceeded
2020/01/01 15:38:31 [Info] v2ray.com/core/transport/internet/udp: establishing n
ew connection for udp:**国外dns**
2020/01/01 15:38:31 [Info] v2ray.com/core/app/dispatcher: default route for udp:
国外dns
2020/01/01 15:38:31 [Info] v2ray.com/core/proxy/freedom: opening connection to u
dp:国外dns
2020/01/01 15:38:31 [Info] v2ray.com/core/app/dns: UDP:国外dns got answe
re: 域名A. TypeAAAA -> [] **227.013ms**
2020/01/01 **15:38:35** [Info] v2ray.com/core/app/dns: **failed to lookup** ip for domai
n 域名A at server UDP:国外dns > context deadline exceeded
2020/01/01 15:38:40 [Info] v2ray.com/core/app/proxyman/outbound: failed to proce
ss outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context ca
nceled

log2是没有answers字段 只有个权威记录 里面内容的类型是soa

如果那个空记录按照dns flags的位组判断是响应的类型 第一个bit是1  算作有效记录那就不存在这些问题了. 这样理论就不会等到超时了.
而且就算他不超时 是rcode3 还是会轮寻.

轮寻看起来又是另一个问题.

**Comment by k79e** [comment]
我发现不配置路由规则
接到rcode3是正常返回记录的 也不重复查询(查询不存在的域名 无论是不是aaaa记录)

**Comment by kslr** [comment]
try 4.22.1

**Comment by k79e** [comment]
已存在域名的aaaa记录 如果aaaa记录是空 查询问题已解决
未存在域名 查询aaaa记录 仍然有问题. 不符合路由配置. 依然乱飞.
未存在域名 查询a记录 还是如上所说.

也就是另一个ticket主要提到的已存域名的空记录问题已经好了
本ticket主要提到的是未存在域名的查询问题依然无解.

主要是打破了域名分流的规则. 而且第一个记录收到的时候 他还不视为有效记录. 这2个问题真是很严重.

> 2020/01/02 **13:06:02** [Info] v2ray.com/core/transport/internet/udp: establishing n
ew connection for udp:127.0.0.1:53
2020/01/02 13:06:02 [Info] v2ray.com/core/app/dispatcher: taking detour [direct]
 for [udp:127.0.0.1:53]
2020/01/02 13:06:02 [Info] v2ray.com/core/proxy/freedom: opening connection to u
dp:127.0.0.1:53
2020/01/02 **13:06:02** [Info] v2ray.com/core/app/dns: UDP:127.0.0.1:53 got answere:
 test.t.cn. TypeA -> [] 1ms //瞬间得结果 但是rcode:3看起来没被视为有效结果 
2020/01/02 13:06:02 [Info] v2ray.com/core/app/dns: failed to lookup ip for domai
n test.t.cn at server UDP:127.0.0.1:53 > **rcode: 3**
2020/01/02 **13:06:02** [Info] v2ray.com/core/transport/internet/udp: establishing n
ew connection for udp:国外dns //打破了cn域名仅仅使用国内dns的规则 而且就算重试理论也要根据路由才对 用127.0.0.1那个重试才行.
2020/01/02 13:06:02 [Info] v2ray.com/core/app/dispatcher: default route for udp:
国外dns
2020/01/02 13:06:02 [Info] v2ray.com/core/proxy/freedom: opening connection to u
dp:国外dns
2020/01/02 **13:06:02** [Info] v2ray.com/core/app/dns: UDP:国外dns got answe
re: test.t.cn. TypeA -> [] 240.2034ms
2020/01/02 13:06:02 [Info] v2ray.com/core/app/dns: failed to lookup ip for domai
n test.t.cn at server UDP:国外dns > rcode: 3

我的疑问是既然rcode3看起来没被算作合法相应 (造成使用其他dns查询?)
为什么第二个结果也是rcode3 但是程序这时候返回了记录.
根据dig的时间上 明确就是所有dns都查完了一遍 轮流查完了才得的结果.

**Comment by k79e** [comment]
发现了一个其他问题 如果查询 cname ns等记录
他什么都不走了. 直接走的任意门那个8888. 应该按照dns配置来查询才对吧?

**Comment by k79e** [comment]
Please reopen the ticket :smiley:

**Comment by k79e** [comment]
我才发现要访问domains匹配的域名才会出现这个问题!!
否则rcode 3直接正常转发.
