### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by GildedHonour** [v2ray/v2ray-core#2155]
Whom could I discuss with contributing to the project?

**Comment by kslr** [comment]
1. https://github.com/orgs/v2fly/projects/3

**Comment by GildedHonour** [comment]
Alright. I could only take the tasks in English.
Also, I've come not as a volunteer. Should I send you an email?

**Comment by kslr** [comment]
Do you only accept work?  We cannot provide salary.

**Comment by GildedHonour** [comment]
I'm not talking about salary.

**Comment by GildedHonour** [comment]
Check your email.
