### ISSUE TITLE
api添加用户，如何指定用户“inbounds tag”/“outbound tag” ? 

### ISSUE THREAD

**Issue by BlackMask007** [v2ray/v2ray-core#2156]
api添加用户，如何指定用户“inbounds tag”/“outbound tag” ? 
如何来实现服务器多ip出口控制？

例如：
一台服务器有4个外网ip地址（10.10.10.100、10.10.10.101、10.10.10.102、10.10.10.103）；
所有用户从10.10.10.100入；
添加一个A用户，指定A用户从10.10.10.101出；
添加一个B用户，指定B用户从10.10.10.102出；
添加一个C用户，指定C用户从10.10.10.103出；

**Comment by azzvx** [comment]
为10.10.10.101、10.10.10.102、10.10.10.103分别设置3个outbound。
routing里可以指定每个user的outbound tag。
