### ISSUE TITLE
希望能够为完善和发展配置的备份和交换功能制定标准

### ISSUE THREAD

**Issue by elanpang** [v2ray/v2ray-core#2162]
1 制定统一的url订阅协议，方便生态的统一和发展，支持批量服务器订阅和更新，支持qr扫码订阅。
2 增加服务器分组功能。
3 制定统一的标准格式，支持可分组的服务器批量导入导出，基于文件交换的方式。

主要就是一些标准化制定的建议，现在各家的gui程序多少都不太统一，不利于生态发展。
可以考虑单独开一个项目，用于起草，编号，维护制定一些标准。

**Comment by cxgreat2014** [comment]
支持。

因为协议特性被检测的原因，现在 SSR 已死，v2ray 已在成为事实上的翻墙标准的路上，期望 v2ray 能把订阅的大旗官方扛起来一下，更利于项目未来发展与使用。

**Comment by liberal-boy** [comment]
url 标准格式已经制定 #1569
“服务器分组功能”的定义？

**Comment by elanpang** [comment]
> url 标准格式已经制定 #1569
> “服务器分组功能”的定义？

就是server可以分组啦，建立group，有时候server太多了不好管理：）

**Comment by cxgreat2014** [comment]
![image](https://user-images.githubusercontent.com/15062548/88030135-73080280-cb6d-11ea-89a8-1ab8253fad46.png)
请求增加分组功能，哈哈
