### ISSUE TITLE
(4.22.1 ARM package) "Illegal instruction" error

### ISSUE THREAD

**Issue by rendaa** [v2ray/v2ray-core#2164]
Same issue has been described in [https://github.com/v2ray/v2ray-core/issues/2128](url)
It was fixed in 4.22.0 ARM binary release, but comes again in the 4.22.1 release.

```
# v2ray --version
Illegal instruction
```

**Comment by kslr** [comment]
Select a specific version of the arm

**Comment by rendaa** [comment]
# v2ray --version 
Illegal instruction
# v2ray_armv7 --version 
Illegal instruction
# v2ray_armv6 --version 
Illegal instruction

**Comment by kslr** [comment]
[v2ray-linux-arm64.zip](https://github.com/v2ray/v2ray-core/files/4024792/v2ray-linux-arm64.zip)




[归档.zip](https://github.com/v2ray/v2ray-core/files/4024820/default.zip)

**Comment by rendaa** [comment]
32bit binaries (files in default.zip):
```
# v2ray --version 
Illegal instruction
# v2ray_armv7 --version 
Illegal instruction
# v2ray_armv6 --version 
Illegal instruction
```
64bit binary (files in v2ray-linux-arm64.zip):
`bash: ./v2ray: cannot execute binary file: Exec format error`

**Comment by kslr** [comment]
try https://github.com/v2fly/V2FlyBleedingEdgeBinary/releases/download/unstable-556f4bf743dd7c74d504b48c96696ac953664680/v2ray-linux-arm.zip

**Comment by rendaa** [comment]
The one which has no architecture filename part works.
Thank you!
```
# v2ray --version
V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/arm)
A unified platform for anti-censorship.
# v2ray_armv6 --version 
Illegal instruction
# v2ray_armv7 --version 
Illegal instruction
```

**Comment by kslr** [comment]
I have updated the arm binary.

**Comment by rendaa** [comment]
Got it! Thank you!
