### ISSUE TITLE
SSL handshake timed out

### ISSUE THREAD

**Issue by Wudelin** [v2ray/v2ray-core#2169]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
最新版
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
android APP通过 Shadowsocket协议连接服务端
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
SSL handshake timed out
4) 你期待看到的正确表现是怎样的？

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
{
  "inbounds": [
    {
      "port": 1024, // 监听端口
      "protocol": "shadowsocks",
      "settings": {
        "method": "aes-128-gcm",
        "ota": true, // 是否开启 OTA
        "password": "sspasswd"
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",  
      "settings": {}
    }
  ]
}

```

客户端配置:

```javascript
    // 在这里附上客户端配置
{
    "dns":{
        "servers":[
            "1.1.1.1"
        ]
    },
    "inbounds":[
        {
            "listen":"127.0.0.1",
            "port":10808,
            "protocol":"socks",
            "settings":{
                "auth":"noauth",
                "udp":true,
                "userLevel":8
            },
            "sniffing":{
                "destOverride":[
                    "http",
                    "tls"
                ],
                "enabled":false
            },
            "tag":"socks"
        },
        {
            "listen":"127.0.0.1",
            "port":10809,
            "protocol":"http",
            "settings":{
                "userLevel":8
            },
            "tag":"http"
        }
    ],
    "log":{
        "loglevel":"warning"
    },
    "outbounds":[
        {
            "mux":{
                "enabled":false
            },
            "protocol":"shadowsocks",
            "settings":{
                "servers":[
                    {
                        "address":"xxxx",
                        "level":8,
                        "method":"aes-128-gcm",
                        "ota":false,
                        "password":"sspasswd",
                        "port":1024
                    }
                ]
            },
            "streamSettings":{
                "network":"tcp"
            },
            "tag":"proxy"
        },
        {
            "protocol":"freedom",
            "settings":{

            },
            "tag":"direct"
        },
        {
            "protocol":"blackhole",
            "settings":{
                "response":{
                    "type":"http"
                }
            },
            "tag":"block"
        }
    ],
    "policy":{
        "levels":{
            "8":{
                "connIdle":300,
                "downlinkOnly":1,
                "handshake":4,
                "uplinkOnly":1
            }
        },
        "system":{
            "statsInboundUplink":true,
            "statsInboundDownlink":true
        }
    },
    "routing":{
        "domainStrategy":"IPIfNonMatch",
        "rules":[
            {
                "ip":[
                    "geoip:private"
                ],
                "outboundTag":"direct",
                "type":"field"
            }
        ]
    },
    "stats":{

    }
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
SSL handshake timed out
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by Wudelin** [comment]
01-08 10:51:58.896 17423 17584 I GoLog   : udp:127.0.0.1:49229 accepted udp:1.1.1.1:53 [proxy]

01-08 10:54:44.770 19174 19174 I GoLog   : new v2ray core
01-08 10:54:44.771 19174 19174 I GoLog   : start v2ray core
01-08 10:54:44.772 19174 19194 I GoLog   : [Warning] v2ray.com/core: V2Ray 4.22.1 started
01-08 10:54:44.773 19174 19174 D com.v2ray.ang: m,1500 a,26.26.26.1,30 r,0.0.0.0,0
01-08 10:54:44.785 19174 19174 D com.v2ray.ang: [/data/app/com.v2ray.ang-p9udncQ5IG4m9DS6ltfqMw==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice]
01-08 10:54:44.794 19174 19174 D com.v2ray.ang: Process[pid=19207, hasExited=false]
01-08 10:54:44.794 19174 19174 D com.v2ray.ang: /data/user/0/com.v2ray.ang/files/sock_path
01-08 10:54:44.846 19174 19209 D com.v2ray.ang: sendFd tries: 0

01-08 10:54:59.314 19174 19209 D com.v2ray.ang: measureV2rayDelay: Get http://www.google.com/gen_204: context deadline exceeded
01-08 10:55:10.882 19174 19309 I GoLog   : fdConn FileConn Close Fd: 64 Err: file file+net Socket: getsockopt: bad file descriptor
01-08 10:55:28.847 19174 19330 I GoLog   : fdConn unix.Connect err, Close Fd: 69 Err: software caused connection abort
01-08 10:55:28.847 19174 19192 I GoLog   : fdConn unix.Connect err, Close Fd: 57 Err: software caused connection abort
01-08 10:55:28.847 19174 19217 I GoLog   : fdConn unix.Connect err, Close Fd: 50 Err: software caused connection abort
01-08 10:55:28.848 19174 19217 I GoLog   : fdConn unix.Connect err, Close Fd: 50 Err: network is unreachable
01-08 10:55:28.848 19174 19330 I GoLog   : fdConn unix.Connect err, Close Fd: 51 Err: network is unreachable
01-08 10:55:28.849 19174 19200 I GoLog   : fdConn unix.Connect err, Close Fd: 59 Err: software caused connection abort
01-08 10:55:28.849 19174 19200 I GoLog   : fdConn unix.Connect err, Close Fd: 50 Err: network is unreachable
01-08 10:55:28.850 19174 19199 I GoLog   : fdConn unix.Connect err, Close Fd: 56 Err: software caused connection abort
01-08 10:55:28.850 19174 19308 I GoLog   : fdConn unix.Connect err, Close Fd: 67 Err: software caused connection abort
01-08 10:55:28.850 19174 19199 I GoLog   : fdConn unix.Connect err, Close Fd: 50 Err: network is unreachable
01-08 10:55:28.851 19174 19308 I GoLog   : fdConn unix.Connect err, Close Fd: 51 Err: network is unreachable
01-08 10:55:28.852 19174 19192 I GoLog   : fdConn unix.Connect err, Close Fd: 53 Err: network is unreachable
01-08 10:55:28.949 19174 19308 I GoLog   : fdConn unix.Connect err, Close Fd: 51 Err: network is unreachable
01-08 10:55:28.949 19174 19200 I GoLog   : udp:127.0.0.1:46564 accepted udp:1.1.1.1:53 [proxy]
01-08 10:55:28.949 19174 19284 I GoLog   : fdConn unix.Connect err, Close Fd: 51 Err: network is unreachable
01-08 10:55:28.950 19174 19192 I GoLog   : fdConn unix.Connect err, Close Fd: 50 Err: network is unreachable
01-08 10:55:28.950 19174 19330 I GoLog   : fdConn unix.Connect err, Close Fd: 56 Err: network is unreachable
01-08 10:55:28.950 19174 19284 I GoLog   : fdConn unix.Connect err, Close Fd: 51 Err: network is unreachable
01-08 10:55:28.951 19174 19330 I GoLog   : fdConn unix.Connect err, Close Fd: 50 Err: network is unreachable
01-08 10:55:28.951 19174 19330 I GoLog   : fdConn unix.Connect err, Close Fd: 50 Err: network is unreachable
01-08 10:55:28.952 19174 19284 I GoLog   : fdConn unix.Connect err, Close Fd: 50 Err: network is unreachable
01-08 10:55:28.962 19174 19330 I GoLog   : tcp:127.0.0.1:46740 accepted tcp:123.58.9.95:443 [proxy]
01-08 10:55:28.963 19174 19192 I GoLog   : tcp:127.0.0.1:46744 accepted tcp:123.58.9.95:443 [proxy]
01-08 10:55:28.963 19174 19330 I GoLog   : fdConn unix.Connect err, Close Fd: 57 Err: network is unreachable
01-08 10:55:28.963 19174 19284 I GoLog   : fdConn unix.Connect err, Close Fd: 53 Err: network is unreachable
01-08 10:55:28.963 19174 19330 I GoLog   : fdConn unix.Connect err, Close Fd: 57 Err: network is unreachable
01-08 10:55:28.963 19174 19284 I GoLog   : fdConn unix.Connect err, Close Fd: 53 Err: network is unreachable
01-08 10:55:29.051 19174 19284 I GoLog   : fdConn unix.Connect err, Close Fd: 52 Err: network is unreachable
01-08 10:55:29.065 19174 19330 I GoLog   : fdConn unix.Connect err, Close Fd: 52 Err: network is unreachable
01-08 10:55:29.065 19174 19200 I GoLog   : fdConn unix.Connect err, Close Fd: 53 Err: network is unreachable
01-08 10:55:29.151 19174 19200 I GoLog   : fdConn unix.Connect err, Close Fd: 56 Err: network is unreachable
01-08 10:55:29.151 19174 19308 I GoLog   : fdConn unix.Connect err, Close Fd: 52 Err: network is unreachable
01-08 10:55:29.151 19174 19330 I GoLog   : fdConn unix.Connect err, Close Fd: 59 Err: network is unreachable
01-08 10:55:29.152 19174 19330 I GoLog   : fdConn unix.Connect err, Close Fd: 52 Err: network is unreachable
01-08 10:55:29.153 19174 19201 I GoLog   : fdConn unix.Connect err, Close Fd: 57 Err: network is unreachable
01-08 10:55:29.153 19174 19308 I GoLog   : fdConn unix.Connect err, Close Fd: 52 Err: network is unreachable
01-08 10:55:29.254 19174 19284 I GoLog   : fdConn unix.Connect err, Close Fd: 52 Err: network is unreachable
01-08 10:55:29.266 19174 19284 I GoLog   : fdConn unix.Connect err, Close Fd: 52 Err: network is unreachable
01-08 10:55:29.266 19174 19200 I GoLog   : fdConn unix.Connect err, Close Fd: 53 Err: network is unreachable
01-08 10:55:29.453 19174 19308 I GoLog   : fdConn unix.Connect err, Close Fd: 57 Err: network is unreachable
01-08 10:55:29.454 19174 19308 I GoLog   : fdConn unix.Connect err, Close Fd: 52 Err: network is unreachable
01-08 10:55:29.454 19174 19217 I GoLog   : fdConn unix.Connect err, Close Fd: 64 Err: network is unreachable
01-08 10:55:29.454 19174 19200 I GoLog   : fdConn unix.Connect err, Close Fd: 53 Err: network is unreachable
01-08 10:55:29.454 19174 19217 I GoLog   : fdConn unix.Connect err, Close Fd: 52 Err: network is unreachable
01-08 10:55:29.455 19174 19330 I GoLog   : fdConn unix.Connect err, Close Fd: 62 Err: network is unreachable
01-08 10:55:29.555 19174 19330 I GoLog   : fdConn unix.Connect err, Close Fd: 52 Err: network is unreachable
01-08 10:55:29.568 19174 19201 I GoLog   : fdConn unix.Connect err, Close Fd: 52 Err: network is unreachable
01-08 10:55:29.569 19174 19200 I GoLog   : fdConn unix.Connect err, Close Fd: 56 Err: network is unreachable
01-08 10:55:29.706 19174 19200 I GoLog   : udp:127.0.0.1:38354 accepted udp:1.1.1.1:53 [proxy]
01-08 10:55:29.707 19174 19192 I GoLog   : fdConn unix.Connect err, Close Fd: 52 Err: network is unreachable
01-08 10:55:29.707 19174 19192 I GoLog   : fdConn unix.Connect err, Close Fd: 52 Err: network is unreachable

01-08 10:55:29.854 19174 19217 I GoLog   : [Warning] [2045800725] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/shadowsocks: failed to find an available destination > v2ray.com/core/common/retry: [software caused connection abort network is unreachable] > v2ray.com/core/common/retry: all retry attempts failed
01-08 10:55:29.854 19174 19217 I GoLog   : [Warning] [991935336] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/shadowsocks: failed to find an available destination > v2ray.com/core/common/retry: [software caused connection abort network is unreachable] > v2ray.com/core/common/retry: all retry attempts failed
01-08 10:55:29.855 19174 19217 I GoLog   : [Warning] [895506293] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/shadowsocks: failed to find an available destination > v2ray.com/core/common/retry: [software caused connection abort network is unreachable] > v2ray.com/core/common/retry: all retry attempts failed
01-08 10:55:29.855 19174 19217 I GoLog   : [Warning] [1516136007] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/shadowsocks: failed to find an available destination > v2ray.com/core/common/retry: [software caused connection abort network is unreachable] > v2ray.com/core/common/retry: all retry attempts failed
01-08 10:55:29.855 19174 19194 I GoLog   : [Warning] [378227836] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/shadowsocks: failed to find an available destination > v2ray.com/core/common/retry: [software caused connection abort network is unreachable] > v2ray.com/core/common/retry: all retry attempts failed
01-08 10:55:29.856 19174 19194 I GoLog   : [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/shadowsocks: failed to find an available destination > v2ray.com/core/common/retry: [software caused connection abort network is unreachable] > v2ray.com/core/common/retry: all retry attempts failed
01-08 10:55:29.875 19174 19284 I GoLog   : udp:127.0.0.1:49678 accepted udp:1.1.1.1:53 [proxy]
01-08 10:55:29.875 19174 19194 I GoLog   : Using Prepared: 47.74.226.235
01-08 10:55:29.955 19174 19217 I GoLog   : [Warning] [1345759558] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/shadowsocks: failed to find an available destination > v2ray.com/core/common/retry: [network is unreachable] > v2ray.com/core/common/retry: all retry attempts failed
01-08 10:55:29.969 19174 19217 I GoLog   : [Warning] [3280763777] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/shadowsocks: failed to find an available destination > v2ray.com/core/common/retry: [network is unreachable] > v2ray.com/core/common/retry: all retry attempts failed
01-08 10:55:29.970 19174 19217 I GoLog   : [Warning] [3891461618] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/shadowsocks: failed to find an available destination > v2ray.com/core/common/retry: [network is unreachable] > v2ray.com/core/common/retry: all retry attempts failed
01-08 10:56:01.137 19174 19192 I GoLog   : tcp:127.0.0.1:46780 accepted tcp:123.58.9.95:443 [proxy]
01-08 10:56:02.419 19174 19200 I GoLog   : fdConn unix.Connect err, Close Fd: 56 Err: software caused connection abort
01-08 10:56:02.419 19174 19217 I GoLog   : fdConn unix.Connect err, Close Fd: 52 Err: software caused connection abort
01-08 10:56:02.420 19174 19194 I GoLog   : fdConn unix.Connect err, Close Fd: 59 Err: software caused connection abort
01-08 10:56:02.421 19174 19194 I GoLog   : fdConn unix.Connect err, Close Fd: 59 Err: network is unreachable
01-08 10:56:02.421 19174 19194 I GoLog   : fdConn unix.Connect err, Close Fd: 57 Err: software caused connection abort
01-08 10:56:02.422 19174 19217 I GoLog   : fdConn unix.Connect err, Close Fd: 52 Err: network is unreachable
01-08 10:56:02.423 19174 19200 I GoLog   : fdConn unix.Connect err, Close Fd: 54 Err: network is unreachable
01-08 10:56:02.423 19174 19194 I GoLog   : fdConn unix.Connect err, Close Fd: 57 Err: network is unreachable
01-08 10:56:02.535 19174 19194 I GoLog   : fdConn unix.Connect err, Close Fd: 52 Err: network is unreachable
01-08 10:56:02.535 19174 19201 I GoLog   : fdConn unix.Connect err, Close Fd: 55 Err: network is unreachable
01-08 10:56:02.535 19174 19217 I GoLog   : fdConn unix.Connect err, Close Fd: 57 Err: network is unreachable
01-08 10:56:02.536 19174 19308 I GoLog   : fdConn unix.Connect err, Close Fd: 60 Err: network is unreachable
01-08 10:56:02.737 19174 19217 I GoLog   : fdConn unix.Connect err, Close Fd: 56 Err: network is unreachable
01-08 10:56:02.737 19174 19194 I GoLog   : fdConn unix.Connect err, Close Fd: 55 Err: network is unreachable
01-08 10:56:02.737 19174 19194 I GoLog   : fdConn unix.Connect err, Close Fd: 60 Err: network is unreachable
01-08 10:56:02.737 19174 19194 I GoLog   : fdConn unix.Connect err, Close Fd: 52 Err: network is unreachable
01-08 10:56:03.039 19174 19217 I GoLog   : fdConn unix.Connect err, Close Fd: 52 Err: network is unreachable
01-08 10:56:03.042 19174 19308 I GoLog   : fdConn unix.Connect err, Close Fd: 59 Err: network is unreachable
01-08 10:56:03.042 19174 19217 I GoLog   : fdConn unix.Connect err, Close Fd: 56 Err: network is unreachable
01-08 10:56:03.043 19174 19201 I GoLog   : fdConn unix.Connect err, Close Fd: 54 Err: network is unreachable
01-08 10:56:03.441 19174 19194 I GoLog   : [Warning] [3011909548] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/shadowsocks: failed to find an available destination > v2ray.com/core/common/retry: [software caused connection abort network is unreachable] > v2ray.com/core/common/retry: all retry attempts failed
01-08 10:56:03.444 19174 19194 I GoLog   : [Warning] [4269827634] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/shadowsocks: failed to find an available destination > v2ray.com/core/common/retry: [software caused connection abort network is unreachable] > v2ray.com/core/common/retry: all retry attempts failed
01-08 10:56:03.444 19174 19194 I GoLog   : [Warning] [212162866] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/shadowsocks: failed to find an available destination > v2ray.com/core/common/retry: [software caused connection abort network is unreachable] > v2ray.com/core/common/retry: all retry attempts failed
01-08 10:56:03.444 19174 19284 I GoLog   : [Warning] [3781675095] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/shadowsocks: failed to find an available destination > v2ray.com/core/common/retry: [software caused connection abort network is unreachable] > v2ray.com/core/common/retry: all retry attempts failed

client-log

**Comment by kslr** [comment]
这些错误是你本地网络不可用或者不稳定

**Comment by Wudelin** [comment]
.....我在测一测

**Comment by joukoranta** [comment]
@Wudelin 
我把你的配置文件修改了一下，你再试一下。

-----------------------------------------------------------
服务端config.json
https://paste.ubuntu.com/p/cDt3f6xXns/
客户端config.json
https://paste.ubuntu.com/p/PMmFpkSPsz/
-----------------------------------------------------------
