### ISSUE TITLE
使用动态端口，是否有利于避开审查？

### ISSUE THREAD

**Issue by qingfengshi** [v2ray/v2ray-core#217]
在台式机上（固定ip），之前使用tcp连接，刚开始的时候速度很好，但是使用两天后能够发现速度明显下降。然后更改配置文件，使用kcp连接，速度恢复。因此怀疑是因为较长时间向同一个ip（我的vps）发送http或https请求，被gfw探测，进行了干扰。（速度测试方法：直接打开YouTube，观察是否能够持续观看高线宽视频。）
鉴于同时使用动态端口和kcp时，会发生断流的问题，那么在使用kcp连接的同时，有必要使用动态端口吗？使用动态端口对在较长时间内规避审查有没有帮助？多谢了。

**Comment by v2ray** [comment]
动态端口的断流发生在动态端口刷新的时候，你可以 1) 延长刷新时间 2) 把一些长连接用路由的方式转发到非动态端口上。

如果你只是看 YouTube，5 分钟的刷新时间够用了。

动态端口通常有助于规避审查，但取决于你的 ISP 的做法。

**Comment by helloyan** [comment]
能否提供一个完整的开启KCP和动态端口的服务器和客户端配置文件供参考

**Comment by v2ray** [comment]
Server: https://github.com/v2ray/v2ray-core/blob/master/testing/scenarios/data/test_4_server.json
Client: https://github.com/v2ray/v2ray-core/blob/master/testing/scenarios/data/test_4_client.json

**Comment by qingfengshi** [comment]
谢谢@v2ray
在v2ray中，同一个加密方式，可以配置一个非动态端口和一个动态端口吗？当然，非动态端口不在动态端口的端口范围内。还是必须要使用路由转发？

**Comment by helloyan** [comment]
用了，用了 以后速度飙升，非常好，有网友折腾出来刷到路由器里的方法吗？
另外，SS是否可以利用这个来加速，客户端如何来配置

**Comment by v2ray** [comment]
我说的路由是指 V2Ray 内置的路由功能，类似这个（routing 部分）：https://www.v2ray.com/zh_cn/chapter_05/00_config/07_vps_relay.html

你需要配置一个带 detour 的 vmess （即动态端口），一个不带的，然后使用  routing 来指定走哪一个 vmess。

**Comment by qingfengshi** [comment]
OK，懂了。我之前理解的是直接使用路由列表指向某一个端口。
非常感谢

**Comment by huangan0110** [comment]
im fine thankyou and you
