### ISSUE TITLE
V2ray官方网站的Api问题

### ISSUE THREAD

**Issue by shouziws** [v2ray/v2ray-core#2172]
查看了V2Ray的Api并没有明确提出如何使用只是简单描绘了grpc调用，我如何使用api的StatsService和HandlerService还有内置日志功能呢

**Comment by alinuxsa** [comment]
可以参考一下这个 [调用 V2Ray 提供的 API 接口进行用户增删及流量统计查询操作](https://medium.com/@TachyonDevel/%E8%B0%83%E7%94%A8-v2ray-%E6%8F%90%E4%BE%9B%E7%9A%84-api-%E6%8E%A5%E5%8F%A3%E8%BF%9B%E8%A1%8C%E7%94%A8%E6%88%B7%E5%A2%9E%E5%88%A0%E6%93%8D%E4%BD%9C-adf9ff972973)

**Comment by shouziws** [comment]
> 可以参考一下这个 [调用 V2Ray 提供的 API 接口进行用户增删及流量统计查询操作](https://medium.com/@TachyonDevel/%E8%B0%83%E7%94%A8-v2ray-%E6%8F%90%E4%BE%9B%E7%9A%84-api-%E6%8E%A5%E5%8F%A3%E8%BF%9B%E8%A1%8C%E7%94%A8%E6%88%B7%E5%A2%9E%E5%88%A0%E6%93%8D%E4%BD%9C-adf9ff972973)

好的，谢谢，我查看一下

**Comment by shouziws** [comment]
> 可以参考一下这个 [调用 V2Ray 提供的 API 接口进行用户增删及流量统计查询操作](https://medium.com/@TachyonDevel/%E8%B0%83%E7%94%A8-v2ray-%E6%8F%90%E4%BE%9B%E7%9A%84-api-%E6%8E%A5%E5%8F%A3%E8%BF%9B%E8%A1%8C%E7%94%A8%E6%88%B7%E5%A2%9E%E5%88%A0%E6%93%8D%E4%BD%9C-adf9ff972973)

你好，我根据上面的接口还有其他方法已经能够把流量统计寻找到了，但是对用户进行增删我没有再之中或者在google搜索中找到对其有描述如何编译调用的情况，请问该怎么办

**Comment by aryMBLec** [comment]
> > 可以参考一下这个 [调用 V2Ray 提供的 API 接口进行用户增删及流量统计查询操作](https://medium.com/@TachyonDevel/%E8%B0%83%E7%94%A8-v2ray-%E6%8F%90%E4%BE%9B%E7%9A%84-api-%E6%8E%A5%E5%8F%A3%E8%BF%9B%E8%A1%8C%E7%94%A8%E6%88%B7%E5%A2%9E%E5%88%A0%E6%93%8D%E4%BD%9C-adf9ff972973)
> 
> 你好，我根据上面的接口还有其他方法已经能够把流量统计寻找到了，但是对用户进行增删我没有再之中或者在google搜索中找到对其有描述如何编译调用的情况，请问该怎么办

这篇文章源码都放出来，怎么编译请自学go语言，当然也可以用其他gRPC调试工具。目前没有现成的工具直接一键调用，v2ctl只做了查询功能，没有做用户管理功能。

**Comment by Ehco1996** [comment]
@shouziws 
可以参考一下我这个项目
封装了一些api的基本调用

**Comment by smallprogram** [comment]
我也来凑凑热闹
https://github.com/smallprogram/V2rayControl
