### ISSUE TITLE
About of version publish

### ISSUE THREAD

**Issue by dx0eu** [v2ray/v2ray-core#2173]
Hi,

I have a question: The version `v4.22.1` is it reposted? since i am maintaining a v2ray chromebook distribution.

https://github.com/skycocker/chromebrew/pull/3739

So i would be very confused if the same version is released twice. I have a project to auto build the new v2ray version to publish to chromebrew, will not be built if the version already exists.

I wish when publish a new version should be change version number.

**Comment by kslr** [comment]
arm version updated, this is an incorrect compilation
