### ISSUE TITLE
docker使用centos镜像 v2ray如何运行

### ISSUE THREAD

**Issue by shouziws** [v2ray/v2ray-core#2174]
目前我是使用Docker拉取的centos镜像 在镜像中通过bash <(curl -L -s https://install.direct/go.sh)
对v2ray进行了安装，此时docker镜像是没有service和systemctl功能的，我应该如何运行v2ray 包含启动 暂停 重启？

**Comment by kslr** [comment]
这些问题请查阅docker images readme

**Comment by kslr** [comment]
对于docker来说这样设计是不合理的，你让它不要后台运行就行了

**Comment by shouziws** [comment]
那我如何在不使用service和systemctl的情况下启动v2ray

**Comment by shouziws** [comment]
> 对于docker来说这样设计是不合理的，你让它不要后台运行就行了

那我如何在不使用service和systemctl的情况下启动v2ray

**Comment by kslr** [comment]
这些问题在docker文档中都有详细的描述和解释，建议你先阅读，有一个大概的了解。

**Comment by shouziws** [comment]
> 
> 
> 这些问题在docker文档中都有详细的描述和解释，建议你先阅读，有一个大概的了解。

你好，关于这个问题 我确实有在官网研究了许久且自己也测试了多次 确实不能运行
在教程中：https://v2ray.com/chapter_00/install.html
启动的方式有2种 
/etc/systemd/system/v2ray.service
/etc/init.d/v2ray
我自己启动v2ray是使用的: systemctl restart v2ray
但是我想问的是 有没有不通过服务的形式启动，而是能够直接运行/usr/bin/v2ray/下的v2ray程序

**Comment by kslr** [comment]
请阅读Docker文档
