### ISSUE TITLE
[feature request]  IP 列表支持not操作!

### ISSUE THREAD

**Issue by BlackLongCock** [v2ray/v2ray-core#2177]
比如DNS配置里的"expectIPs": ["geoip:!cn"]
这样就不用单独为非cn的ip单独弄一个IP列表。
使用国外的dns时可以只得到国外IP

**Comment by lucifer9** [comment]
这个用途在哪里呢
比如 dl.google.com，从国内发起查询，解析到 203.208.39.* 的某个国内 IP的话，这就是正确的结果啊。

**Comment by Soylent-Green-Yummy** [comment]
> 这个用途在哪里呢
> 比如 dl.google.com，从国内发起查询，解析到 203.208.39.* 的某个国内 IP的话，这就是正确的结果啊。

我正是希望过滤掉这种结果。即，国外dns server解析出虽然正确，却不好用的国内IP。

现在v2ray的dns配置功能已经很适合进行dns分流了，用作路由器的dns服务器。我是这样用的

`{
  "servers": [
    {
      "address": "cn-dns-server",
      "domains": [
        "geosite:cn"
      ],
      "expectIPs": [
        "geoip:cn"
      ]
    },

{
      "address": "foreign-dns-server",
      "expectIPs": [
        "geoip:!cn"
      ]
    },
    "fallback-dns-server-in-China",
    "localhost"
  ]

} `

关键是第二个dns，即foreign dns server，我不希望它解析出国内的IP，因为国外dns解析出的国内结果都不好，所以只希望对这个服务器的返回结果进行过滤 `"expectIPs": [
        "geoip:!cn"
      ]`

目前v2ray尚不支持`geoip:!cn`这种not操作，只能用cn的IP列表手动生成非cn的IP列表，比较麻烦。

**Comment by lucifer9** [comment]
然而针对我举的例子，那个解析出来的结果对于国内用户来说是友好的，足以跑满带宽且不用代理。
其实你不想要国内IP，只要指定解析某些域名的那个DNS必须走代理，自然就不会给你国内IP了吧

**Comment by Soylent-Green-Yummy** [comment]
> 然而针对我举的例子，那个解析出来的结果对于国内用户来说是友好的，足以跑满带宽且不用代理。
> 其实你不想要国内IP，只要指定解析某些域名的那个DNS必须走代理，自然就不会给你国内IP了吧

是的

但是国内域名实在太多了，全部手动指定非人力可为。我试过国外常见的dns，用来解析国内域名，都必然有一部分国内网站得到极不友好的IP，dns加上ecs也不理想。

我也了解社区有维护国内常见域名的列表，我也在第一个dns那里用上了。但是实在是不足，还会有很多国内域名查询进入第二个dns，得到不友好的结果

**Comment by lucifer9** [comment]
我通常是配置第一个dns为 114.114.114.114，所有进来的域名都先走这个，但是我只接受国内IP的解析结果。如果返回的是国外IP，则继续交给 8.8.8.8。一般这个时候，如果访问的网站有国内CDN，114会给我合适的结果；如果是被污染的域名，或者本身没有国内CDN，那基本上也就是需要走代理的了，8.8.8.8 也不会让我失望。

**Comment by Soylent-Green-Yummy** [comment]
> 我通常是配置第一个dns为 114.114.114.114，所有进来的域名都先走这个，但是我只接受国内IP的解析结果。如果返回的是国外IP，则继续交给 8.8.8.8。一般这个时候，如果访问的网站有国内CDN，114会给我合适的结果；如果是被污染的域名，或者本身没有国内CDN，那基本上也就是需要走代理的了，8.8.8.8 也不会让我失望。

类似的配置我一开始也用过。
但我很不愿意把dns 查询都发给国内dns server。
算是隐私洁癖吧。

在上文给出的配置解决了这个让我担忧隐私的问题。也正是我现在在使用的。
只有手动生成一份非cn的IP列表这个事情，不完美，有点dirty，毕竟已经有了一份社区维护的cn IP列表，程序也有expectIPs的逻辑判断了。
简单讲，我希望的东西，大约就是增加一个not expected IP的判断

**Comment by lucifer9** [comment]
然而你有考虑过 geosite:cn 永远不可能完备么？
而且这又绕回了国外站点有国内CDN的情况下，你这种配置反而要走代理的问题。

**Comment by forever8938** [comment]
直接用默认的国内DNS不就行了吗。写一条hosts把被墙域名随便解析到一个IP，即可防止泄漏。其他网站就用默认的国内DNS解析，反正上游都是国外的DNS。

**Comment by Soylent-Green-Yummy** [comment]
> 然而你有考虑过 geosite:cn 永远不可能完备么？
geosite:cn 的确是不可能完备的，其实包含这个的第一个dns server可以去掉，这样也可以的。简单讲就是国外dns server只有国外IP结果，国内dns sever只有国内IP结果

```
{
  "servers": [
   {
      "address": "foreign-dns-server",
      "expectIPs": [
        "geoip:!cn"
      ]
    },
    "fallback-dns-server-in-China",
    "localhost"
  ]

} 
```

> 而且这又绕回了国外站点有国内CDN的情况下，你这种配置反而要走代理的问题。

并不一定啊，即便解析得到的是国外IP，也可能是直连，并不一定需要代理

**Comment by Soylent-Green-Yummy** [comment]
> 直接用默认的国内DNS不就行了吗。写一条hosts把被墙域名随便解析到一个IP，即可防止泄漏。其他网站就用默认的国内DNS解析，反正上游都是国外的DNS。

我的想法：
1. gfwlist也难以保证被墙域名100%覆盖，hosts实在写不完
1. 因为上一条，所以干脆国内外域名分开解析

**Comment by Soylent-Green-Yummy** [comment]
`"expectIPs": ["geoip:!cn" ]`
这种写法虽然目前不支持，但也有workaround
只是比较笨：把除cn外的所有country code写一遍，数量有两百多个。
坏处是，启动v2ray时，时间需要几分钟，cpu单核心满载，内存占用增加100多MB。启动完毕后恢复正常

**Comment by lucifer9** [comment]
既然有想要国内dns server只返回国内结果，国外的只返回国外结果，那为啥不干脆做到国外IP全用代理连接呢
讲真，解析某些域名并不算很严重的迹象。因为fb，google到处发广告，你随便访问正常网站哪怕国内的都少不了要被动的去解析一两把他们的域名。反而是会主动用正确的IP连接更可疑一些。所以国外全走代理吧。

**Comment by forever8938** [comment]
> > 直接用默认的国内DNS不就行了吗。写一条hosts把被墙域名随便解析到一个IP，即可防止泄漏。其他网站就用默认的国内DNS解析，反正上游都是国外的DNS。
> 
> 我的想法：
> 
> 1. gfwlist也难以保证被墙域名100%覆盖，hosts实在写不完
> 2. 因为上一条，所以干脆国内外域名分开解析

gfwlist已经覆盖了绝大部分被墙域名，如果你有其他经常上的被墙网站，自己加上几条hosts就行。gfwlist可以从域名文件中读取，只要一行。
