### ISSUE TITLE
Supporting substitute of the default Dialer, this is a prerequisite of Libv2ray's support of Android VPNService mode

### ISSUE THREAD

**Issue by xiaokangwang** [v2ray/v2ray-core#218]
需要能够设置v2ray-core 的[Dialer](https://github.com/v2ray/v2ray-core/blob/master/transport/internet/dialer.go#L59)，并由Libv2ray（V2RayGO， V2Ray安卓手机版）[protect](https://developer.android.com/reference/android/net/VpnService.html#protect(int))由V2Ray发起的连接。 防止连接循环。

这部分代码会由我来写，可以在这里先讨论实现这个功能的借口。

**Comment by v2ray** [comment]
你先给个 proposal 吧，不太清楚你的需求，比如参数等。

**Comment by xiaokangwang** [comment]
需要实现在Dial的时候先调用函数保护socket（这个操作需要在connect之前），
比如shadowsocks[里面](https://github.com/shadowsocks/shadowsocks-libev/blob/d4aabcb40b4bcbca352269a1474a19de691950d0/src/local.c#L268)

**Comment by xiaokangwang** [comment]
对现有代码改动比较少的方法就是实现一个Dialer

**Comment by xiaokangwang** [comment]
比如可以新增一个函数 MustSubstituteDialer(dialer net.Dialer) error 调用后可以要求V2Ray使用这个Dialer来创建TCP和UDP连接。

**Comment by v2ray** [comment]
这个 protect socket 具体是干什么的？

Golang 里面拿到 net.Conn 的 fd 不太方便，目前我只知道 tcpConn 的方法，udpConn 还没试过。

**Comment by xiaokangwang** [comment]
protect 确保由V2Ray发起的连接直接通向互联网而不是被Android's VPNService转发到V2Ray的inbound,

正确情况下：

Chrome <--> Android VPNService <---> V2Ray <------> Internet

如果V2Ray的连接没有被保护就会
```
Chrome <--> Android VPNService <---> V2Ray 
        |<-----------------------------<|
```

形成循环

P.S.:要在SYN发出之前就protect。

**Comment by xiaokangwang** [comment]
只需要替换Dialer

**Comment by v2ray** [comment]
你打算怎么这个 Dialer 传进来？通过 language binding，还是用 Go 实现一个 Dialer，然后用配置文件来切换？

**Comment by xiaokangwang** [comment]
用Go实现一个，我自己Go部分的程序会调用v2ray-core的代码来注册这个自己写的Dialer

**Comment by xiaokangwang** [comment]
就是和proxy一样，调用函数来注册

**Comment by v2ray** [comment]
那就新增一个 interface:

```go
type SystemDialer interface {
  Dial(src v2net.Address, dest v2net.Destination) (net.Conn, error)
}
```

注册和使用的方式和 proxy 一样，如何？

**Comment by xiaokangwang** [comment]
我这里实现一个[net.Dialer](https://golang.org/src/net/dial.go#L17)的接口比较方便, 有必要使用v2net的定义么？

**Comment by v2ray** [comment]
net.Dialer 是一个 struct，怎么实现不一样功能？

**Comment by v2ray** [comment]
你是指这样？

```go
type SystemDialer interface {
  Dial(network, address string) (Conn, error)
}
```

**Comment by xiaokangwang** [comment]
嗯

**Comment by xiaokangwang** [comment]
我自己不是特别熟悉v2ray的代码，用v2ray自己定义的struct容易出现很难处理的bug。

**Comment by v2ray** [comment]
那还需要一个 factory 方法用来构造 dialer，比如：

```go
type SystemDialerFactory interface{
  Create(*net.Dialer) (SystemDialer, error)
}
```

**Comment by xiaokangwang** [comment]
我目前没有想到利用Golang自己的Dialer的方法，需要用syscall建立连接后想办法塞到net.Conn里

**Comment by v2ray** [comment]
SystemDialerFactory 只是用 Dialer 来传数据，全部展开的话有点麻烦，直接就重用 Dialer 的定义好了，具体实现可以根据实际情况来。

**Comment by xiaokangwang** [comment]
好，我先写我自己的代码，在自己这里改一下v2ray-core，等能用了再讨论如何整合。

**Comment by xiaokangwang** [comment]
Closing as #218 is merged.
