### ISSUE TITLE
Failed to execute v2ctl > signal: segment fault

### ISSUE THREAD

**Issue by linux40** [v2ray/v2ray-core#2184]
I'm sorry for report this error by screenshot. The network I use do not allow me ssh to my VPS, so I could not paste the error messages. Following is `systemctl status v2ray` after `systemctl start v2ray`:
![screenshot](https://user-images.githubusercontent.com/31679941/72673900-4b938880-3aab-11ea-9ad8-87c83fcd89a3.png)
My configuration for v2ray is simple: 
![config](https://user-images.githubusercontent.com/31679941/72673938-bfce2c00-3aab-11ea-9684-41c02c8773cb.png)
V4.22.0 has no problem.

**Comment by forever8938** [comment]
cd to /usr/bin/v2ray and run v2ray from command line and see if it works. 
BTW, you better not use default configuration from tutorial, I mean the path /ray, otherwise your IP will be fucked very quickly.

**Comment by linux40** [comment]
Thank you for your notice, i will change a path.

It is strange that as i installed the newest v2ray via `go.sh`, and installed v2ray-4.22.0 via `go.sh -l`, i have to install the newest v2ray back via `go.sh -f`. Because `go.sh -l` do not change the record about the version of installed v2ray. And after doing `go.sh -f` and restarting v2ray again, the newest v2ray works and does not crash.
