### ISSUE TITLE
Cannot start v2ray after running https://install.direct/go.sh for upgrade on Centos 7

### ISSUE THREAD

**Issue by alexyangjie** [v2ray/v2ray-core#2186]
1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

4.22.1

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

General browsing

3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)

The installation/update script of `https://install.direct/go.sh` produces error "Failed to install daemon. Please install it manually." when updating the core. This is on CentOS 7, with both systemd and initscripts installed on the system. 

After commit https://github.com/v2ray/v2ray-core/commit/77a151080c45190c49aac8b0bf9ed480136e8ec9#diff-4aa23e53f82478f6a56caa25b4c8ff43R311 (line 311), the script will always try to install the old init.d version of v2ray config when it detects the `service` command in the system, resulting in this error message. 

This error is preventing the v2ray.service from restart after upgrade. 

4) What's your expectation?

The installation script should always use systemd if it detects it on the system. 

5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

<Not related to the issue>

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.

Server error log:
Installing V2Ray v4.22.1 on x86_64
Downloading V2Ray: https://github.com/v2ray/v2ray-core/releases/download/v4.22.1/v2ray-linux-64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   608    0   608    0     0   1345      0 --:--:-- --:--:-- --:--:--  1348
100 11.6M  100 11.6M    0     0   717k      0  0:00:16  0:00:16 --:--:-- 1644k
Extracting V2Ray package to /tmp/v2ray.
Archive:  /tmp/v2ray/v2ray.zip
  inflating: /tmp/v2ray/config.json
   creating: /tmp/v2ray/doc/
  inflating: /tmp/v2ray/doc/readme.md
  inflating: /tmp/v2ray/geoip.dat
  inflating: /tmp/v2ray/geosite.dat
   creating: /tmp/v2ray/systemd/
  inflating: /tmp/v2ray/systemd/v2ray.service
   creating: /tmp/v2ray/systemv/
  inflating: /tmp/v2ray/systemv/v2ray
  inflating: /tmp/v2ray/v2ctl
 extracting: /tmp/v2ray/v2ctl.sig
  inflating: /tmp/v2ray/v2ray
 extracting: /tmp/v2ray/v2ray.sig
  inflating: /tmp/v2ray/vpoint_socks_vmess.json
  inflating: /tmp/v2ray/vpoint_vmess_freedom.json
Shutting down V2Ray service.
Updating software repo
Installing daemon
Error: Nothing to do
**Failed to install daemon. Please install it manually.**

7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.

<Not related>

8) Other configurations (such as Nginx) and logs.

N/A

9) If V2Ray doesn't run, please attach output from `--test`.

N/A

10) If V2Ray service doesn't run, please attach journal log.

N/A

Please review your issue before submitting.

**Comment by xiaoyaoyuxin** [comment]
我在centos7.3上升级，也遇到了
Installing daemon
Error: Nothing to do
Failed to install daemon. Please install it manually.
的问题。

以前都没有问题的，不知道怎么回事。

**Comment by fgggid** [comment]
It is caused by installInitScript function in install-release.sh.
```bash
installInitScript(){
    if [[ -n "${SYSTEMCTL_CMD}" ]] && [[ ! -f "/etc/systemd/system/v2ray.service" && ! -f "/lib/systemd/system/v2ray.service" ]]; then
        cp "${VSRC_ROOT}/systemd/v2ray.service" "/etc/systemd/system/"
        systemctl enable v2ray.service
    elif [[ -n "${SERVICE_CMD}" ]] && [[ ! -f "/etc/init.d/v2ray" ]]; then
        installSoftware "daemon" || return $?
        cp "${VSRC_ROOT}/systemv/v2ray" "/etc/init.d/v2ray"
        chmod +x "/etc/init.d/v2ray"
        update-rc.d v2ray defaults
    fi
}
```
Obviously CentOS 7 is using systemd and you are updating v2ray, you already have `/etc/systemd/system/v2ray.service`, then first condition will be false, it will fall into second branch which is wrong, there is no `daemon` package for CentOS.

Maybe here we need a flag to indicate which init system we are using - systemd or sysvinit.
