### ISSUE TITLE
quic golang lib 更新一波？

### ISSUE THREAD

**Issue by 29e7e280-0d1c-4bba-98fe-f7cd3ca7500a** [v2ray/v2ray-core#2187]
quic golang lib 更新一波？

**Comment by kslr** [comment]
现在没有人在做这个事情，你有兴趣吗

**Comment by lucifer9** [comment]
@netroby @kslr 测试了一下，上游的quic-go已经改得太多，现在一边用上游最近的release 0.14.0，一边用项目自带的quic的话，两边无法建立连接。如果没什么特别的需求，最好还是等上游有个长期稳定的版本再一起改吧。

**Comment by 29e7e280-0d1c-4bba-98fe-f7cd3ca7500a** [comment]
@kslr 
[upgrade-quic-go-to-lastest.zip](https://github.com/v2ray/v2ray-core/files/4563891/upgrade-quic-go-to-lastest.zip)

已完成 quic-go 更新，同步上游quic-go 到最新， 自测无问题， 工作正常， 收发数据包，流畅。

**Comment by lucifer9** [comment]
quic 同一个版本自己跟自己连都没问题，就是还没个稳定版以至于更新了以后就没法跟目前在用的老版本互联。
