### ISSUE TITLE
Redirecting instead of 404 in case of http2 path mismatch

### ISSUE THREAD

**Issue by ccaapton** [v2ray/v2ray-core#2189]
As shown here [here](https://github.com/v2ray/v2ray-core/blob/5dd85717fcbc2f6b2175c6e9e258e8e964c0d0d3/transport/internet/http/hub.go#L64), when the incoming http2 request url has path mismatch with server configuration, the server will return 404. Is it possible to redirect these kind of requests to other configured hosts/ports, like 127.0.0.1:80?

This logic would be  similar to [trojan](https://github.com/trojan-gfw/trojan/), and it makes the proxy less detectable.

**Comment by forever8938** [comment]
Use caddy.

**Comment by aeroxy** [comment]
Agreed. SSR has a feature where it can redirect all none-SSR connections to a different port, can we do the same for http2?

**Comment by aeroxy** [comment]
> Use caddy.

I don't think caddy works for http2 tho. Caddy is working more like NGINX and you redirect the connections before it reaches V2Ray, that's not gonna work with this http2 obfs method.

**Comment by aeroxy** [comment]
If there is a reverse proxy that can redirect http2 requests with certain paths to V2Ray's port and all none http2 requests and all http2 requests that do not match certain paths to another port, please recommend. Also if possible, please attach the configurations.

**Comment by forever8938** [comment]
caddy surely supports http2, just google "v2ray caddy http2" and you'll get several tutorials right on the first page.

**Comment by aeroxy** [comment]
Whether caddy or any other reverse proxies support http2 is irrelevant @forever8938. Caddy will need to decrypt the http2 request before forwarding it to v2ray, and then encrypt and ignore the certificate. Meaning there is this internal handshake that is not necessary and slows down the connection significantly.

**Comment by aeroxy** [comment]
The point being, if v2ray wants to support http2 streaming, then it should have a built-in reverse proxy (however simple it maybe) as it would be the first agent to receive the handshake (and should be).
