### ISSUE TITLE
多路复用诡异卡顿问题

### ISSUE THREAD

**Issue by k79e** [v2ray/v2ray-core#2194]
我一开始还以为服务器或者网有问题 结果后面发现不是.
就是一老连接或者也不知道怎么回事 也不是特老 就很容易触发速度变慢的问题.
目前配置用的是让v2 over http代理(任意门走代理的那种) 现在这个情况下很容易复现.(其他配置也都有这问题)
一天出现很多次.

结果我后来才发现 多路复用如果新建一个连接 这时候速度就不卡.
所以这意味着 网速不卡的时候 我这里一个连接卡 另一个连接不卡. 不清楚这是怎么回事.

一开始我还以为 服务器那里 或者代理那里 用了什么基于流量的限速 而且还是基于会话的
因为我一关闭v2再打开 瞬间没事了.
然而不是. 哪里有这么先进的规则.  我后来发现 卡顿的时候 跟走了多少流量并没有什么直接关系.
跟已存连接建立时间 好像也没什么固定关系.(可能有关系?)

但是我记得以前就有这个问题 我还记得曾经观察过流量 是ack发送速率不正常??
![2019-11-07_182924](https://user-images.githubusercontent.com/6483602/73151307-9ba2c880-4105-11ea-86ba-e6b423805587.png)
![2019-11-07_182944](https://user-images.githubusercontent.com/6483602/73151316-a65d5d80-4105-11ea-8350-cf6800f86e62.png)

这是当初的图 当初看过 都是0丢包. 14586是速度慢的
看起来在分组上面 这些分片的延时很不稳定 速度快的是极其稳定.
为什么数据包收到的时间差别这么大 数据流不稳定呢. 那还不是本地发送的ack磨蹭了呗...

分片长度
![2019-11-07_182928](https://user-images.githubusercontent.com/6483602/73151375-f9371500-4105-11ea-841a-313a8e7908d2.png)
![2019-11-07_182947](https://user-images.githubusercontent.com/6483602/73151377-fd633280-4105-11ea-99b7-d45204ed1c71.png)
109k和750k+的差别 
注意速度慢的 他网速不仅100k上下晃悠 始终上不去 分片也比较散 这不知道为什么.

![2019-11-07_182935](https://user-images.githubusercontent.com/6483602/73151477-431ffb00-4106-11ea-83a9-c27232cf27bb.png)
![2019-11-07_182958](https://user-images.githubusercontent.com/6483602/73151479-487d4580-4106-11ea-9f37-39a0becc740b.png)
tcptrace
接收同样的一个资源 卡的时候10多秒还没收完.

![2019-11-07_182938](https://user-images.githubusercontent.com/6483602/73151498-5e8b0600-4106-11ea-995e-95be9f6ab631.png)
![2019-11-07_183002](https://user-images.githubusercontent.com/6483602/73151501-621e8d00-4106-11ea-99f7-bbfc19c9cbb2.png)
绿色是接收窗口 点是发出字节

惨了 数据包没留 这都是收数据的 发数据的没记录. 
但是那个接收窗口为什么一开始就很大 而不是从小变大 这是堵塞么?
0丢包来什么堵塞哦...

总之问题看起来好像是接收窗口的滑动很诡异!! 
这可能是卡的时候 接收窗口未复位? 导致的堵塞假象?

2020-01-27 15:45:42
我抓到了稍微有点慢的 发现了特征
1. 零散大小的数据包开始出现.
2. 同时我发送出去的ack竟然不是空包 是带有payload的ack 不知道为什么.
3. 就在我发送非空ack的时候 就是收到零散数据包比较多的时间段.
4. 全程0pkt loss. 0 dup ack.

2020-01-27 16:17:15
可能发现根源了
是第一个零散包过来 我这边ack确认慢了25ms. 应该立刻就发出去的才是.
不知道是为什么 是buffer相关的问题么?
而且我发现rtt图出现波动 就是ack确认的速度慢了. 不知道这是为什么
e.g 这个包都是连续的 是规律端口的
361 .3xx s
362 .3xx s 卡
363 .3xx c 这个和前面几个 都是.3xx ms的时间 //ack确认361
375 .4xx s
376 .4xx c 这个和上面那个 都是.4xx 慢了100ms的时间 //确认375
s是服务器发送的 c是客户端发送的
363空包确认361
376直接确认375. 这里没有ack确认363
362 和 375间隔差不多100ms 可能是**因为362收到之后** 没发送ack
(精确时差是95ms)

我发现开始卡的这个包 都没有被直接ack 而是后面慢了100ms的那个包 直接ack掉.
这不是应该本方不发送ack那边就不发数据么.
就比如这个362号封包是被361和375夹着的 这是为什么我不太懂.
他最近的确认包就是这2个

后面紧接着的ack确认的是他上面的包 我感觉应该直接确认362才对吧.
或者361 362一起才是啊

我好像记得 是ack如果确认后面的 就相当于前面也被确认了 所以夹着是没问题的.
但是夹着的这个包 和后面的数据流 有一个间隔 有时差的话就惨了. 这到底是为什么.
凭什么本机就确认上一个包 不确认下面那个362 明明362才是一串数据流最后的一个包(在.3xx时间里面)
如果是那样 还不如干脆一个包确认362完事了.

而且362号封包 是.3xx **小数点后面第三位数** 数字**一样的** 一连串封包的最后一个.
~~v2怎么能发送一个ack确认361号包呢. 是不是时间判断出了什么问题 还是有什么缓冲区搞的问题?~~

我对这方面很不懂 希望有专家的话来解释下

我发现 更早的 3位数小数点 也就是1ms之前的 另一串数据包 本机**也是确认的倒数第二个**.
但是由于后方数据包是紧接着过来的 没时差 所以感觉不到慢

为什么**数据流有短暂的中断** 有人懂这个么? 是服务器繁忙? 那谁能解释 新建一个连接又不卡了.
如果繁忙的话一直卡才是吧.

零散大小的包又是另一个问题 这好像跟那个数据流有不连贯是不同的问题
我发现零散大小的包都是psh,ack

//我后面发现数据流如果在短暂时间内有点间断 是正常的 但是过于频繁应该就不正常.

2020-02-11 20:24:27
我发现挂长连接容易这样.

**Comment by k79e** [comment]
我抓了个速度快的
![2020-01-27_133921](https://user-images.githubusercontent.com/6483602/73152332-7b293d00-410a-11ea-96e9-99c92fe51a2d.png)
![2020-01-27_133929](https://user-images.githubusercontent.com/6483602/73152333-7bc1d380-410a-11ea-920b-0301fe6f25fc.png)

rtt
![2020-01-27_134014](https://user-images.githubusercontent.com/6483602/73152391-baf02480-410a-11ea-8bb6-e91c38cca6e0.png)
![2020-01-27_134021](https://user-images.githubusercontent.com/6483602/73152393-bc215180-410a-11ea-8c6c-23b79a776401.png)

吞吐量
![2020-01-27_134053](https://user-images.githubusercontent.com/6483602/73152408-c6435000-410a-11ea-82aa-299ac8f78393.png)
![2020-01-27_134101](https://user-images.githubusercontent.com/6483602/73152412-c9d6d700-410a-11ea-9da2-55474201fd0f.png)

tcptrace
![2020-01-27_134114](https://user-images.githubusercontent.com/6483602/73152425-d78c5c80-410a-11ea-8f15-30bd1a42e07e.png)
![2020-01-27_134119](https://user-images.githubusercontent.com/6483602/73152428-da874d00-410a-11ea-81b8-daaa10772a1e.png)
这次双向都留了

**Comment by Fr33raNg3r** [comment]
是否是BBR或者类似的TCP丢包导致？

**Comment by k79e** [comment]
我看了以前留的流数据
发现数据流有点间隔不是什么大问题 只要在rtt范围内就没事
下载40多m的数据 rtt就跳20下
这和几百k 跳几十下 而且还乱七八糟 差别大了
而且当初那个图 有丢包和无丢包 都没有零散数据包
客户端发送len大于0的ack都没有. 无论有丢包还是没丢包.

![image](https://user-images.githubusercontent.com/6483602/73164309-aae93c80-412c-11ea-9695-1a17f9b020e0.png)
所以目前最大问题应该就是这个莫名其妙的零散数据包

**Comment by kingwilliam** [comment]
我也有类似的经历，但我没有数据支持，我说说我的情况和估计的情况。

1. 估计同多路复用有关（下文再补充）
2. ws+mux 和 h2 同样出现
3. 只用ws（停用mux）情况会有非常大改善
4. 情况只在翻墙出外出现（如已不能翻科学上网 连接国内网还是完全正常） ，但在墙外连接v2还是正常。
5. 重启客户v2又可正常科学上网（我是用x86建v2透明代理）但回复正常後 不定时情况又再出现 由数分钟到数小时不等。重启vps v2没帮助。
6. 我客户v2是经路由上网 如发现不能“科学上网”时 在路由 kill all connection, 网页还是不停转圈 v2不会重健连接。

补充第1点：
7. 曾经试过 旧的连接完全正常 但新的就不能连接。实例是 我在浏览一个网页 但已不能ssh vps（要经过v2自由门） 但网页还是正常 但关闭所有网页後就再不能 科学，只能重启客户v2 又再回复正常。
8. 我是经过 v2 自由门 ssh vps ,我两边v2都设定10M buffer, 在ssh 其间 最初是正常的 但不久後就越来越慢 慢到 ls -l 是由飞快的 到 出2行停几秒 再几行停数秒 到 出几字停数秒 到2-3分钟都没反应 但有时就非常奇怪 等30秒到1分钟(只是纪忆)特然飞快的全list出来 估计是 连接回复vps buffer全吐出来.

现在情况：
- 是不是墙在干扰连接，真的不能确定。是否因多路复用时，连接受干扰後断开，但v2又察觉不到引至不能“科学”也要再测试。
- 上述所有连接都有TLS的。
- vps 是 caddy->v2.
- 但早前有文说 RSA4096 可能有改善,我也由let's encrypt 2048转 自签RSA4096sha512测试。现在已回复tls+h2真的好像没再断线（还在测试中）。

**Comment by kslr** [comment]
我个人建议在使用中关闭MUX

**Comment by emiyalee1005** [comment]
一样得问题。。。

**Comment by k79e** [comment]
我有疑问.
都有什么情况下是无丢包 窗口缩小?

我发现是一个长连接触发的问题. 但是另一种长连接没问题. 比如youtube视频.

//我抓包没抓握手 是中途抓的 窗口缩放因数不变的话应该都是256

**Comment by k79e** [comment]
我都怀疑是不是mux里面冒出了碎片包. 所以网速慢的时候 封包大小比较错乱?
