### ISSUE TITLE
V2ray无故重启，log显示是「out of memory」，但当时并无任何客户端连接。

### ISSUE THREAD

**Issue by i553041** [v2ray/v2ray-core#2197]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

4.22.1

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

v2ray + WS + TLS + Nginx + CDN ，在手机以Shadowrocket科学上网

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

其实科学上网一切正常，只是v2ray忽然无故重启，syslog显示是out of memory。

我的v2ray_access.log，最后一条是今天22:14:40，

2020/01/28 22:14:40 xxx.xxx.xxx.xxx:34678 accepted tcp:safebrowsing.googleapis.com:443 email:abc@cde.com 

而v2ray_error.log，显示我今晚23:02:43重启过v2ray：

2020/01/28 23:02:43 [Warning] v2ray.com/core: V2Ray 4.22.1 started

于是我去查syslog，去找23:02的纪录，见到如下错误：

Jan 28 23:02:41 ubuntu kernel: [595150.834751] Out of memory: Kill process 22008 (v2ray) score 0 or sacrifice child
Jan 28 23:02:41 ubuntu kernel: [595150.846699] Killed process 22008 (v2ray) total-vm:809236kB, anon-rss:19212kB, file-rss:2692kB, shmem-rss:0kB
Jan 28 23:02:41 ubuntu kernel: [595150.879013] oom_reaper: reaped process 22008 (v2ray), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
Jan 28 23:02:41 ubuntu systemd[1]: v2ray.service: Main process exited, code=killed, status=9/KILL
Jan 28 23:02:41 ubuntu systemd[1]: v2ray.service: Failed with result 'signal'.
Jan 28 23:02:41 ubuntu systemd[1]: v2ray.service: Service RestartSec=100ms expired, scheduling restart.
Jan 28 23:02:41 ubuntu systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 1.
Jan 28 23:02:41 ubuntu systemd[1]: Stopped V2Ray Service.
Jan 28 23:02:41 ubuntu systemd[1]: Started V2Ray Service.
Jan 28 23:02:41 ubuntu v2ray[23226]: V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 linux/arm)
Jan 28 23:02:41 ubuntu v2ray[23226]: A unified platform for anti-censorship.

v2ray无缘无故的重启了，而且是out of memory，我肯定当时是没有客户端连接的，如果有客户端连接，v2ray_access.log最后显示的时间不㑹是22:14分啊？

我记得之前已经试过一次，我还奇怪怎么㑹忽然没了流量纪录，因为我自己建立了一个traffic.sh用来查看使用者流量，上次打指令查流量时，发现流量纪录清空了，我当时没想过是v2ray忽然重启，我还以为是自己重启过v2ray只是忘了，这次，我打traffic.sh再次查看v2ray的流量纪录，发现流量纪录又被清空了，这次我颇为肯定我没动过v2ray服务，于是我就查log了。

4) 你期待看到的正确表现是怎样的？

不明白为何out of memory，肯定不想v2ray无故重启。

以下为23:02分内的syslog纪录，我还要提供甚么配置档/纪录档吗？使用上是一切正常的：

Jan 28 23:02:41 ubuntu kernel: [595150.834092] dhcpcd-run-hook invoked oom-killer: gfp_mask=0x14000c0(GFP_KERNEL), nodemask=(null), order=2, oom_score_adj=0
Jan 28 23:02:41 ubuntu kernel: [595150.834102] dhcpcd-run-hook cpuset=/ mems_allowed=0
Jan 28 23:02:41 ubuntu kernel: [595150.834120] CPU: 1 PID: 23221 Comm: dhcpcd-run-hook Not tainted 4.15.0-1052-raspi2 #56-Ubuntu
Jan 28 23:02:41 ubuntu kernel: [595150.834122] Hardware name: BCM2835
Jan 28 23:02:41 ubuntu kernel: [595150.834151] [<80112b74>] (unwind_backtrace) from [<8010d85c>] (show_stack+0x20/0x24)
Jan 28 23:02:41 ubuntu kernel: [595150.834161] [<8010d85c>] (show_stack) from [<809e9110>] (dump_stack+0xcc/0x110)
Jan 28 23:02:41 ubuntu kernel: [595150.834173] [<809e9110>] (dump_stack) from [<8028ff24>] (dump_header+0x80/0x268)
Jan 28 23:02:41 ubuntu kernel: [595150.834183] [<8028ff24>] (dump_header) from [<8028f008>] (oom_kill_process+0x330/0x5b4)
Jan 28 23:02:41 ubuntu kernel: [595150.834190] [<8028f008>] (oom_kill_process) from [<8028fc00>] (out_of_memory+0x134/0x34c)
Jan 28 23:02:41 ubuntu kernel: [595150.834199] [<8028fc00>] (out_of_memory) from [<80295e80>] (__alloc_pages_nodemask+0xcfc/0x11c8)
Jan 28 23:02:41 ubuntu kernel: [595150.834207] [<80295e80>] (__alloc_pages_nodemask) from [<8029636c>] (__get_free_pages+0x20/0x60)
Jan 28 23:02:41 ubuntu kernel: [595150.834217] [<8029636c>] (__get_free_pages) from [<8011a17c>] (pgd_alloc+0x28/0x110)
Jan 28 23:02:41 ubuntu kernel: [595150.834226] [<8011a17c>] (pgd_alloc) from [<8012829c>] (mm_init+0xf4/0x188)
Jan 28 23:02:41 ubuntu kernel: [595150.834234] [<8012829c>] (mm_init) from [<801298f8>] (copy_process.part.5+0x970/0x19d4)
Jan 28 23:02:41 ubuntu kernel: [595150.834242] [<801298f8>] (copy_process.part.5) from [<8012ab04>] (_do_fork+0xe0/0x4a8)
Jan 28 23:02:41 ubuntu kernel: [595150.834249] [<8012ab04>] (_do_fork) from [<8012afe8>] (SyS_clone+0x30/0x38)
Jan 28 23:02:41 ubuntu kernel: [595150.834260] [<8012afe8>] (SyS_clone) from [<80108f40>] (ret_fast_syscall+0x0/0x28)
Jan 28 23:02:41 ubuntu kernel: [595150.834264] Mem-Info:
Jan 28 23:02:41 ubuntu kernel: [595150.834274] active_anon:4473 inactive_anon:4486 isolated_anon:12
Jan 28 23:02:41 ubuntu kernel: [595150.834274]  active_file:42854 inactive_file:40900 isolated_file:12
Jan 28 23:02:41 ubuntu kernel: [595150.834274]  unevictable:0 dirty:5 writeback:0 unstable:0
Jan 28 23:02:41 ubuntu kernel: [595150.834274]  slab_reclaimable:79056 slab_unreclaimable:8697
Jan 28 23:02:41 ubuntu kernel: [595150.834274]  mapped:3323 shmem:56 pagetables:682 bounce:0
Jan 28 23:02:41 ubuntu kernel: [595150.834274]  free:4514 free_pcp:105 free_cma:0
Jan 28 23:02:41 ubuntu kernel: [595150.834283] Node 0 active_anon:17892kB inactive_anon:17944kB active_file:171416kB inactive_file:163600kB unevictable:0kB is>
Jan 28 23:02:41 ubuntu kernel: [595150.834294] Normal free:18056kB min:3244kB low:4052kB high:4860kB active_anon:17792kB inactive_anon:17944kB active_file:171>
Jan 28 23:02:41 ubuntu kernel: [595150.834296] lowmem_reserve[]: 0 0
Jan 28 23:02:41 ubuntu kernel: [595150.834305] Normal: 3983*4kB (UE) 276*8kB (UE) 0*16kB 0*32kB 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 18>
Jan 28 23:02:41 ubuntu kernel: [595150.834339] 79429 total pagecache pages
Jan 28 23:02:41 ubuntu kernel: [595150.834370] 11 pages in swap cache
Jan 28 23:02:41 ubuntu kernel: [595150.834373] Swap cache stats: add 183483, delete 183472, find 1227767/1332991
Jan 28 23:02:41 ubuntu kernel: [595150.834376] Free swap  = 32012008kB
Jan 28 23:02:41 ubuntu kernel: [595150.834379] Total swap = 32106472kB
Jan 28 23:02:41 ubuntu kernel: [595150.834383] 242688 pages RAM
Jan 28 23:02:41 ubuntu kernel: [595150.834385] 0 pages HighMem/MovableOnly
Jan 28 23:02:41 ubuntu kernel: [595150.834388] 6524 pages reserved
Jan 28 23:02:41 ubuntu kernel: [595150.834390] 65536 pages cma reserved
Jan 28 23:02:41 ubuntu kernel: [595150.834393] [ pid ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
Jan 28 23:02:41 ubuntu kernel: [595150.834419] [  598]     0   598     7644      454    77824      191             0 systemd-journal
Jan 28 23:02:41 ubuntu kernel: [595150.834426] [  625]     0   625     4353      263    22528      219         -1000 systemd-udevd
Jan 28 23:02:41 ubuntu kernel: [595150.834436] [ 1171]   100  1171     3262      388    20480      136             0 systemd-network
Jan 28 23:02:41 ubuntu kernel: [595150.834443] [ 1195]     0  1195    10143      409    32768      221             0 accounts-daemon
Jan 28 23:02:41 ubuntu kernel: [595150.834449] [ 1196]     0  1196     3008      425    18432      155             0 systemd-logind
Jan 28 23:02:41 ubuntu kernel: [595150.834456] [ 1197]     0  1197    13055      314    36864      295             0 ModemManager
Jan 28 23:02:41 ubuntu kernel: [595150.834462] [ 1199]   102  1199     6354      230    20480      241             0 rsyslogd
Jan 28 23:02:41 ubuntu kernel: [595150.834468] [ 1201]     0  1201     3602      342    16384       38             0 irqbalance
Jan 28 23:02:41 ubuntu kernel: [595150.834475] [ 1204]     0  1204   237616      385    81920     1223          -900 snapd
Jan 28 23:02:41 ubuntu kernel: [595150.834481] [ 1215]     0  1215      356        0    10240       21             0 courierlogger
Jan 28 23:02:41 ubuntu kernel: [595150.834487] [ 1216]     0  1216     5564      530    30720     1260             0 networkd-dispat
Jan 28 23:02:41 ubuntu kernel: [595150.834493] [ 1217]     0  1217      910      226    14336       45             0 authdaemond
Jan 28 23:02:41 ubuntu kernel: [595150.834500] [ 1218]   103  1218     1557      489    14336       74          -900 dbus-daemon
Jan 28 23:02:41 ubuntu kernel: [595150.834507] [ 1219]     0  1219     2170      311    16384       89             0 wpa_supplicant
Jan 28 23:02:41 ubuntu kernel: [595150.834513] [ 1220]     0  1220    16764      694    51200      299             0 NetworkManager
Jan 28 23:02:41 ubuntu kernel: [595150.834520] [ 1234]     0  1234      440      270    12288       36             0 dhcpcd
Jan 28 23:02:41 ubuntu kernel: [595150.834526] [ 1240]     0  1240      910      110    12288       53             0 authdaemond
Jan 28 23:02:41 ubuntu kernel: [595150.834532] [ 1246]     0  1246     9158      420    26624      133             0 polkitd
Jan 28 23:02:41 ubuntu kernel: [595150.834538] [ 1270]     0  1270     8775      502    34816     1301             0 unattended-upgr
Jan 28 23:02:41 ubuntu kernel: [595150.834545] [ 1272]     0  1272    51764      352    61440      917             0 php-fpm7.3
Jan 28 23:02:41 ubuntu kernel: [595150.834551] [ 1277]     0  1277    21183      954    45056     1270             0 fail2ban-server
Jan 28 23:02:41 ubuntu kernel: [595150.834557] [ 1339]     0  1339     1725      332    16384       38             0 cron
Jan 28 23:02:41 ubuntu kernel: [595150.834563] [ 1358]     0  1358      771      305    12288       44             0 atd
Jan 28 23:02:41 ubuntu kernel: [595150.834569] [ 1369]     0  1369     1422      270    14336       32             0 agetty
Jan 28 23:02:41 ubuntu kernel: [595150.834576] [ 1371]     0  1371     2315      315    14336      154         -1000 sshd
Jan 28 23:02:41 ubuntu kernel: [595150.834582] [ 1390]     0  1390     1041      215    12288       31             0 agetty
Jan 28 23:02:41 ubuntu kernel: [595150.834588] [ 1413]     0  1413     3789      184    24576      181             0 saslauthd
Jan 28 23:02:41 ubuntu kernel: [595150.834594] [ 1548]    33  1548    51909      331    61440     1213             0 php-fpm7.3
Jan 28 23:02:41 ubuntu kernel: [595150.834600] [ 1549]    33  1549    51870      310    61440     1247             0 php-fpm7.3
Jan 28 23:02:41 ubuntu kernel: [595150.834607] [ 1598]   116  1598     5232      375    22528      146             0 systemd-timesyn
Jan 28 23:02:41 ubuntu kernel: [595150.834613] [ 1671]     0  1671     6128      494    32768     3850             0 miniserv.pl
Jan 28 23:02:41 ubuntu kernel: [595150.834619] [ 5761]     0  5761     3037      241    12288       59             0 gpg-agent
Jan 28 23:02:41 ubuntu kernel: [595150.834626] [16172]     0 16172     1136      226    14336       68             0 vsftpd
Jan 28 23:02:41 ubuntu kernel: [595150.834633] [22008]     0 22008   202309     5476    67584      816             0 v2ray
Jan 28 23:02:41 ubuntu kernel: [595150.834640] [22045]     0 22045     1831      209    14336      210             0 nginx
Jan 28 23:02:41 ubuntu kernel: [595150.834648] [22046]    33 22046     2015      307    16384      341             0 nginx
Jan 28 23:02:41 ubuntu kernel: [595150.834654] [22047]    33 22047     1932      291    14336      278             0 nginx
Jan 28 23:02:41 ubuntu kernel: [595150.834660] [22048]    33 22048     1975      163    14336      317             0 nginx
Jan 28 23:02:41 ubuntu kernel: [595150.834666] [22049]    33 22049     2024      185    16384      373             0 nginx
Jan 28 23:02:41 ubuntu kernel: [595150.834672] [25253]    33 25253      862      238    10240       43             0 fcgiwrap
Jan 28 23:02:41 ubuntu kernel: [595150.834679] [ 4932] 65534  4932     7065      812    30720     1148             0 trojan
Jan 28 23:02:41 ubuntu kernel: [595150.834685] [16307]     0 16307     2753      331    18432      216             0 sshd
Jan 28 23:02:41 ubuntu kernel: [595150.834691] [16310]  1000 16310     3301      308    22528      277             0 systemd
Jan 28 23:02:41 ubuntu kernel: [595150.834697] [16311]  1000 16311     8942       17    30720      629             0 (sd-pam)
Jan 28 23:02:41 ubuntu kernel: [595150.834704] [16367]  1000 16367     2753      259    18432      223             0 sshd
Jan 28 23:02:41 ubuntu kernel: [595150.834710] [16368]  1000 16368     1883      274    16384      269             0 bash
Jan 28 23:02:41 ubuntu kernel: [595150.834716] [16450]  1000 16450     2168      309    18432       97             0 su
Jan 28 23:02:41 ubuntu kernel: [595150.834723] [16451]     0 16451     1730      273    12288      109             0 bash
Jan 28 23:02:41 ubuntu kernel: [595150.834730] [22411]     0 22411   203951     3984    55296     1182             0 AdGuardHome
Jan 28 23:02:41 ubuntu kernel: [595150.834737] [22829]     0 22829     4905     3453    32768       57             0 du
Jan 28 23:02:41 ubuntu kernel: [595150.834746] [23221]     0 23221      373       97    10240        0             0 dhcpcd-run-hook
Jan 28 23:02:41 ubuntu kernel: [595150.834751] Out of memory: Kill process 22008 (v2ray) score 0 or sacrifice child
Jan 28 23:02:41 ubuntu kernel: [595150.846699] Killed process 22008 (v2ray) total-vm:809236kB, anon-rss:19212kB, file-rss:2692kB, shmem-rss:0kB
Jan 28 23:02:41 ubuntu kernel: [595150.879013] oom_reaper: reaped process 22008 (v2ray), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
Jan 28 23:02:41 ubuntu systemd[1]: v2ray.service: Main process exited, code=killed, status=9/KILL
Jan 28 23:02:41 ubuntu systemd[1]: v2ray.service: Failed with result 'signal'.
Jan 28 23:02:41 ubuntu systemd[1]: v2ray.service: Service RestartSec=100ms expired, scheduling restart.
Jan 28 23:02:41 ubuntu systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 1.
Jan 28 23:02:41 ubuntu systemd[1]: Stopped V2Ray Service.
Jan 28 23:02:41 ubuntu systemd[1]: Started V2Ray Service.
Jan 28 23:02:41 ubuntu v2ray[23226]: V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 linux/arm)
Jan 28 23:02:41 ubuntu v2ray[23226]: A unified platform for anti-censorship.

先谢谢帮忙。

**Comment by kslr** [comment]
降低alertID

**Comment by i553041** [comment]
> 降低alertID

謝謝，已調低了，再看會不會這樣，觀察一段時間再匯報！
