### ISSUE TITLE
机器的时间非常重要，请保持时间同步！

### ISSUE THREAD

**Issue by v3ray** [v2ray/v2ray-core#22]
装上之后，查了一个晚上。才发现本地时间不对了。修改之后果然就工作了。希望在README里面说明一下这点，因为debug log非常不足。

**Comment by v2ray** [comment]
谢谢指出，会加上去的。

**Comment by fudingyu** [comment]
是需要修改本地时间吗？

**Comment by v3ray** [comment]
本地时间和服务器时间要同步。你可以理解为，本地机器时间的UTC表示，和服务器时间的UTC表示，是一样的。

**Comment by fudingyu** [comment]
在本地放了一个客户端和服务器端 测试成功了

但是我的服务器放在美国，我把时区调成了 UTC-05:00美国东部时间，还是不行！

**Comment by v3ray** [comment]
美国服务器的时间和时区换回本地的是一样的吗？

另外，不一定是时间的问题，远程的话，端口设置也是另外一个问题。

**Comment by fudingyu** [comment]
端口肯定都是一样的。

就是一直报这个错！
[Error]Failed to open tcp:xxxx:27183: dial tcp xxxx:27183: con
nectex: No connection could be made because the target machine actively refused
it.

**Comment by fudingyu** [comment]
时区核对过了，两边的UTC都是一样的。

**Comment by fudingyu** [comment]
时间相差不过5秒钟之内

**Comment by v3ray** [comment]
> 时间相差不过5秒钟之内

解决了？

**Comment by fudingyu** [comment]
必然是没有解决！！！！

**Comment by v2ray** [comment]
[Error]Failed to open tcp:xxxx:27183: dial tcp xxxx:27183: con
nectex: No connection could be made because the target machine actively refused
it.

这个错误是因为服务器端的 27183 端口没有开放，请检查一下 VPS 是否有额外的防火墙设置，以及服务器端的端口是否设成了 27183。

**Comment by fudingyu** [comment]
换了一台服务器，好像能连上了，但是客户端却一直提示
[Error]VMessOut: Failed to read VMess response (0 bytes): read tcp 192.168.0.145
:46337->58.64.185.36:27183: wsarecv: An existing connection was forcibly closed
by the remote host.

服务器一直提示
[Warning]VMessIn: Invalid request from (202.101.72.73:46360): Invalid authentication.


两边的ID都是对的

**Comment by v2ray** [comment]
改一下端口试试，这个端口已经公开了很久，不排除已经被盯上了。

另外请确保客户端和服务器的时间是一致的。Linux 和 Mac OS 可以用“date -u”来看 UTC 时间，当前时间大约是这个：

Thu Oct 29 10:15:31 UTC 2015

**Comment by fudingyu** [comment]
嗯，我再试试看。

**Comment by fudingyu** [comment]
把美国用sudo dpkg-reconfigure tzdata命令改了时区变成香港之后果然可以连接了！

香港服务器，我是直接下载的Linux64的包，搞不好是下载的包的问题哦？
