### ISSUE TITLE
服务器端更新到最新版本的稳定性问题

### ISSUE THREAD

**Issue by qingfengshi** [v2ray/v2ray-core#220]
服务器端更新到最新版本，貌似变得很不稳定。

我之前一直使用的是1.18.2版本，使用上没有问题。更新到最新版本后，使用一段时间后客户端总会出现报错：
[warning]VMess | Outbound: Failed to read response: EOF
今天一直折腾这事，之前一直认为是动态端口的问题，然后改回静态端口。后来发现VPS不能启动v2ray服务，重装系统并重新运行v2ray后，一直使用静态端口，然后连接一段时间以后，开始连接不上，并重复弹出以上错误。

我现在不能肯定是server端运行不稳定，但这是一个可能原因，作为反馈。似乎自动安装脚本只能安装最新版本的程序，请问有之前版本的安装脚本吗？谢谢

**Comment by v2ray** [comment]
你可以使用 ```install-release.sh --version 1.18.2``` 来安装 1.18.2 版本。

**Comment by qingfengshi** [comment]
完整的是
bash <(curl -L -s https://raw.githubusercontent.com/v2ray/v2ray-core/master/release/install-release.sh --version 1.18.2)
吗？太感谢您了。
看来我得学习点Linux了，您有没有什么入门书籍可以推荐？

**Comment by v2ray** [comment]
用 Curl 可能不行，你需要先把脚本下载下来：

```
curl -L https://raw.githubusercontent.com/v2ray/v2ray-core/master/release/install-release.sh
chmod +x ./install-release.sh
./install-release.sh --version 1.18.2
```

**Comment by v2ray** [comment]
Linux 的东西我基上是 Google 出来的，我也没看过系统的书。

**Comment by qingfengshi** [comment]
好的，非常感谢

**Comment by BenhoNNNN** [comment]
@qingfengshi 《鸟哥私房菜》
