### ISSUE TITLE
v2ray.sig v2ctl.sig is empty in v2ray-linux-64.zip

### ISSUE THREAD

**Issue by atzlinux** [v2ray/v2ray-core#2215]
v2ray.sig v2ctl.sig is empty in v2ray-linux-64.zip.

**Comment by atzlinux** [comment]
最新版的 64 位 Linux zip 文件，解压缩后，里面的 v2ray.sig v2ctl.sig 为空，无法验证签名。

**Comment by okudayukiko** [comment]
Windows版V2Ray也是。
