### ISSUE TITLE
关于v2ray的前置代理问题

### ISSUE THREAD

**Issue by jakkpop** [v2ray/v2ray-core#2217]
v2ray服务器<--Vmess-->v2ray客户端<--http-->http客户端
v2ray可以实现这个吗？
参考[白话文指南](https://guide.v2fly.org/basics/vmess.html#%E9%85%8D%E7%BD%AE%E5%89%8D%E7%9A%84%E5%87%86%E5%A4%87) 尝试了几天，也没有成功！

1. config.json如下：
> {
>   "log": {
>     "access": "/var/log/v2ray/access.log",
>     "error": "/var/log/v2ray/error.log",
>     "loglevel": "warning"
>   },
>   "inbounds": [
>     {
>       "protocol": "http",
>       "settings": {
>         "servers": [
>           {
>             "address": "xxx.com",
>             "port": 10000,
>             "users": [
>               {
>                 "user": "xxx",
>                 "pass": "xxxx"
>               }
>             ]
>           }
>         ]
>       },
>       "tag": "HTTP"
>     }  
>   ],	
>   "outbounds": [
>     {
>       "tag": "proxy",
>       "protocol": "vmess",
>       "settings": {
>         "vnext": [
>           {
>             "address": "xoxo.com",
>             "port": 57203,
>             "users": [
>               {
>                 "id": "98f5824e-3550-xxxxx-xxxx-xxxxx",
>                 "alterId": 64,
>                 "email": "t@t.tt",
>                 "security": "auto"
>               }
>             ]
>           }
>         ],
>         "tag": "VMESS",
>         "proxySettings": {
>           "tag": "HTTP"  
>         },        
>         "servers": null,
>         "response": null
>       },
>       "streamSettings": {
>         "network": "ws",
>         "security": "tls",
>         "tlsSettings": {
>           "allowInsecure": true,
>           "serverName": null
>         },
>         "tcpSettings": null,
>         "kcpSettings": null,
>         "wsSettings": {
>           "connectionReuse": true,
>           "path": "/",
>           "headers": null
>         },
>         "httpSettings": null,
>         "quicSettings": null
>       },
>       "mux": {
>         "enabled": true
>       }
>     },
>     {
>       "tag": "direct",
>       "protocol": "freedom",
>       "settings": {
>         "vnext": null,
>         "servers": null,
>         "response": null
>       },
>       "streamSettings": null,
>       "mux": null
>     },
>     {
>       "tag": "block",
>       "protocol": "blackhole",
>       "settings": {
>         "vnext": null,
>         "servers": null,
>         "response": {
>           "type": "http"
>         }
>       },
>       "streamSettings": null,
>       "mux": null
>     }
>   ],
>   "stats": null,
>   "api": null,
>   "dns": null,
>   "routing": {
>     "domainStrategy": "IPIfNonMatch",
>     "rules": [
>       {
>         "type": "field",
>         "port": null,
>         "inboundTag": [
>           "api"
>         ],
>         "outboundTag": "api",
>         "ip": null,
>         "domain": null
>       }
>     ]
>   }
> }

2.在浏览器使用上面代理，无法通过，v2ray也没有输出错误信息。

请帮忙看一下，或者有没有成功的配置范例参考一下，感谢！

**Comment by kumitom** [comment]
我的需求是通过一个V2RAY节点来访问另一个被墙的V2RAY节点，从而实现以被墙节点的IP来访问网络。2个节点都是ws+tls的，试了一天无法解决。将默认outbound的流量转入dokodemo-door时一直提示failed to dial wss://127.0.0.1:xxxx 什么的，放弃了………………

**Comment by twzchi** [comment]
作者说了 这是一种代理转发~只能转发IP 不能转发域名~~
