### ISSUE TITLE
建议官方发布用golang 1.14构建的二进制release

### ISSUE THREAD

**Issue by netroby** [v2ray/v2ray-core#2218]
Golang 1.14rc1优化了time相关的性能，提升比较明显。可以重新构建，release新的二进制执行文件

**Comment by mzz2017** [comment]
目前golang的稳定版本是1.13.7吧

**Comment by ix64** [comment]
目前 golang 1.14 runtime 貌似还存在性能问题吧？
https://github.com/golang/go/issues/37086
https://github.com/golang/go/issues/37121

**Comment by netroby** [comment]
1.14已经发布了。 @mzz2017 @ix64

**Comment by aryMBLec** [comment]
1.14已经发布了，希望及时用新版编译发布

**Comment by naoki66** [comment]
Building targets
go: github.com/v2ray/v2ray-core@v4.22.1+incompatible: reading https://goproxy.cn/github.com/v2ray/v2ray-core/@v/v4.22.1+incompatible.mod: 404 Not Found

**Comment by netroby** [comment]
@kslr 老板，来一发，构建一发。。坐等新release，把4.22.1重构一下，性能应该有提升

**Comment by netroby** [comment]
```
# ./v2ray -version
V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14 linux/amd64)
A unified platform for anti-censorship.

```
我已经自己构建了，自己用。

**Comment by YanzheL** [comment]
如果想提前尝试Go 1.14编译的容器镜像，可以用我的[Dockerfile](https://github.com/YanzheL/dockerfiles/blob/master/v2ray/build.dockerfile)

```shell
docker pull leeyanzhe/v2ray
```

**Comment by LsnmxNB** [comment]
@YanzheL  @naoki66  大佬能不能发个golang 1.14构建的二进制v2ray-linux-64.zip
，不会编译啊

**Comment by YanzheL** [comment]
> @YanzheL @naoki66 大佬能不能发个golang 1.14构建的二进制v2ray-linux-64.zip
> ，不会编译啊

下面这个编译好的包，是从我上面的[Dockerfile](https://github.com/YanzheL/dockerfiles/blob/master/v2ray/build.dockerfile) 里的 builder 步骤里提取出来的。
Go 1.14, v2ray-core 4.22.1
[v2ray-linux-64.zip](https://github.com/v2ray/v2ray-core/files/4306117/v2ray-linux-64.zip)

**Comment by LsnmxNB** [comment]
@YanzheL 谢谢大佬已经用你提供的更新

**Comment by LsnmxNB** [comment]
@YanzheL Go 1.14编译的v2ray-core 4.22.1速度提升很明显

**Comment by LsnmxNB** [comment]
补充一个秋水逸冰go 1.14编译出来的win二进制文件
使用 v2rayN 的用户，可以下载我在 go 1.14 环境下最新编译的 v2ray-core 用于 Windows 系统下的二进制文件。

下载地址：
https://dl.lamp.sh/files/wv2ray_386.exe
https://dl.lamp.sh/files/wv2ray_amd64.exe

https://dl.lamp.sh/files/v2ctl_386.exe
https://dl.lamp.sh/files/v2ctl_amd64.exe

**Comment by kslr** [comment]
> @YanzheL Go 1.14编译的v2ray-core 4.22.1速度提升很明显

有实验吗

**Comment by LsnmxNB** [comment]
@kslr 同一环境下服务端客户端核心切成Go 1.14编译的v2ray-core 4.22.1，表现在处理数据更快了，你可以试试就知道了

**Comment by mzz2017** [comment]
> Go 1.14采用了基于系统信号的异步抢占调度，在Unix/Linux/Mac上直接进行系统调用，那么一旦在系统调用执行过程中进程收到系统中断信号，这些系统调用就会失败，并以EINTR错误返回，尤其是低速系统调用，包括：读写特定类型文件(管道、终端设备、网络设备)、进程间通信等。在这样的情况下，我们就需要自己处理EINTR错误。一个最常见的错误处理方式就是重试。

最新代码中应该没有对syscall的错误进行适配，如果在低速设备中，遇到tproxy的dokodemo入口和mark出口，可能反而会造成性能的下降，需要进行测试。

测试工具可以用[victoria那套](https://github.com/v2ray/experiments)，有人做一下吗。

**Comment by LsnmxNB** [comment]
@mzz2017 victoria不会用啊，Go 1.14主要提升性能，每个软件都不可能完美的，早用早享受

**Comment by LsnmxNB** [comment]
go1.14.1 稳定更新了， @YanzheL  大佬来个 go1.14.1 编译的v2ray-linux-64.zip 谢谢
@kslr 考虑下上go1.14.1 编译吧，大佬

**Comment by 2444989513** [comment]
> go1.14.1稳定更新了，@YanzheL 大佬来个go1.14.1编译的v2ray-linux-64.zip谢谢
> @kslr考虑下上go1.14.1编译吧，大佬

https://github.com/2444989513/Backup-v2ray

go1.14.1

**Comment by LsnmxNB** [comment]
@2444989513  谢谢大佬，太感谢了

**Comment by LsnmxNB** [comment]
@2444989513 go1.14.2 发布了

**Comment by YanzheL** [comment]
> @2444989513 go1.14.2 发布了

老哥，没必要总是紧跟Go小版本更新吧

**Comment by LsnmxNB** [comment]
@YanzheL 哈哈，他哪好像是机器定时更新的

**Comment by mzz2017** [comment]
minor point release，不值得专门跟进

------------------ 原始邮件 ------------------
发件人: LsnmxNB <notifications@github.com&gt;
发送时间: 2020年4月10日 11:51
收件人: v2ray/v2ray-core <v2ray-core@noreply.github.com&gt;
抄送: mzz <m@mzz.pub&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[v2ray/v2ray-core] 建议官方发布用golang 1.14构建的二进制release (#2218)





 
@2444989513 go1.14.2 发布了

**Comment by YanzheL** [comment]
> minor point release，不值得专门跟进

1.14大版本可以考虑一下

**Comment by ix64** [comment]
https://github.com/v2ray/v2ray-core/commit/f099c1e53d9104bbef1a0c0c1bf0d1520663955b CI已经修改啦，不用吵吵，下一次Release开始都会自动使用最新的1.14.x构建
