### ISSUE TITLE
现在默认是绕过国内IP和内网IP，如果我希望所有网段都走代理。。。

### ISSUE THREAD

**Issue by waitandsoon** [v2ray/v2ray-core#222]
现在默认是绕过国内IP和内网IP，如果我希望所有网段都走代理。。。
应该怎么设置？

还有能不能把配置文件做得结构化更好一点。
比如kcp选项是否能简单点。
官方提供的配置文件示例按着走完总是不成功。

**Comment by alex1528** [comment]
+1

**Comment by zhouzhiwen2000** [comment]
客户端router内容删光就行

**Comment by zhouzhiwen2000** [comment]
客户端router内容删光

**Comment by liaobin** [comment]
把chinasites和chinasip部分删除即可

**Comment by v2ray** [comment]
Assuming fixed.

**Comment by wyl2000** [comment]
客户端router内容删光就行，这个不行，把chinasites和chinasip部分删除即可，这个也不行，提示配置文件有问题，默认的就正常，可以给个例子吗？由于chrome加omega非常好用，一般不用PAC之类的再去多此致一举，代理规则完全用omega扩展。只改客户端设置就可以了吗？客户端的设置，最新版的V2ray{
  "log": {
    "loglevel": "warning"
  },
  "inbound": {
    "port": 7**0,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "4********5",
          "port": 8**1,
          "users": [
            {
              "id": "5a***********f-0d47b8***dcf",
              "alterId": 64,
              "security": "auto"
            }
          ]
        }
      ]
    },
    "mux": {
      "enabled": true
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": "1-52",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "54-79",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "81-442",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "444-65535",
          "outboundTag": "direct"
        },
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        }
      ]
    }
  }
}
我的服务端设置
{
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 8**1,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "5a69*******-4f23******bf-*****9c2dcf",
          "level": 1,
          "alterId": 64
        }
      ]
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}
目前使用非常好，就是有这个小缺点，代理控制不是靠扩展完成的，毕竟国内有些ISP自己还封锁国内的小说网站，这时只能用代理才能看。
