### ISSUE TITLE
v2ray 传输协议ws 访问google显示证书错误

### ISSUE THREAD

**Issue by yerphon** [v2ray/v2ray-core#2227]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
服务端latest 客户端v2rayN v2.52 
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
Chrome  通过Socks 访问google.com
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
您的连接不是私密连接
攻击者可能会试图从 www.google.com 窃取您的信息（例如：密码、通讯内容或信用卡信息）。了解详情
NET::ERR_CERT_COMMON_NAME_INVALID
Subject: *.facebook.com

Issuer: DigiCert SHA2 High Assurance Server CA

Expires on: 2020年4月15日

Current date: 2020年2月7日

证书错误
4) 你期待看到的正确表现是怎样的？
能上google.com，突然之间就不行了。
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    {
  "log": {
    "loglevel": "warning",
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log"
  },
  "inbounds": [
    {
      "port": 1095,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "",
            "alterId": 64
          }
        ]
      },
      "streamSettings": {
        "network":"ws"
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}
```

客户端配置:

```javascript
    {
  "policy": null,
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "proxy",
      "port": 10808,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "address": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "",
            "port": 1095,
            "users": [
              {
                "id": "",
                "alterId": 64,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": null,
        "tlsSettings": null,
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": null,
          "headers": null
        },
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "stats": null,
  "api": null,
  "dns": {
    "servers": [
      "1.1.1.1"
    ]
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "port": null,
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "ip": null,
        "domain": null
      }
    ]
  }
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript

error.log无多余的错误
```

客户端错误日志:

```javascript
   2020/02/07 23:54:52 tcp:127.0.0.1:49597 accepted tcp:t.co:443 [proxy] 
2020/02/07 23:54:53 tcp:127.0.0.1:49602 accepted tcp:www.facebook.com:443 [proxy] 
2020/02/07 23:54:54 tcp:127.0.0.1:49610 accepted tcp:www.facebook.com:443 [proxy] 
2020/02/07 23:55:11 tcp:127.0.0.1:49644 accepted tcp:www.facebook.com:443 [proxy] 
2020/02/07 23:55:11 tcp:127.0.0.1:49649 accepted tcp:www.facebook.com:443 [proxy] 
2020/02/07 23:55:41 tcp:127.0.0.1:49691 accepted tcp:www.facebook.com:443 [proxy] 
2020/02/07 23:56:45 tcp:127.0.0.1:49776 accepted tcp:www.google.com:443 [proxy] 
2020/02/07 23:56:45 tcp:127.0.0.1:49777 accepted tcp:www.google.com:443 [proxy] 
2020/02/07 23:56:45 tcp:127.0.0.1:49791 accepted tcp:www.google.com:443 [proxy] 
2020/02/07 23:56:45 tcp:127.0.0.1:49794 accepted tcp:www.google.com:443 [proxy] 
2020/02/07 23:56:45 tcp:127.0.0.1:49796 accepted tcp:www.google.com:443 [proxy] 
2020/02/07 23:57:47 tcp:127.0.0.1:49889 accepted tcp:www.google.com:443 [proxy] 
2020/02/07 23:57:47 tcp:127.0.0.1:49892 accepted tcp:www.google.com:443 [proxy] 
2020/02/07 23:57:49 tcp:127.0.0.1:49895 accepted tcp:www.google.com:443 [proxy] 
2020/02/07 23:59:02 tcp:127.0.0.1:50033 accepted tcp:mtalk.google.com:5228 [proxy] 
2020/02/08 00:00:09 tcp:127.0.0.1:50139 accepted tcp:www.facebook.com:443 [proxy] 
2020/02/08 00:04:03 tcp:127.0.0.1:50411 accepted tcp:mtalk.google.com:5228 [proxy] 
2020/02/08 00:05:01 tcp:127.0.0.1:50475 accepted tcp:clients4.google.com:443 [proxy] 
2020/02/08 00:05:26 tcp:127.0.0.1:50504 accepted tcp:analytics.twitter.com:443 [proxy] 
2020/02/08 00:09:03 tcp:127.0.0.1:50769 accepted tcp:mtalk.google.com:5228 [proxy] 
2020/02/08 00:09:54 tcp:127.0.0.1:50924 accepted tcp:steamcommunity.com:443 [proxy] 
2020/02/08 00:09:55 tcp:127.0.0.1:50941 accepted tcp:steamcommunity.com:443 [proxy] 
2020/02/08 00:11:24 tcp:127.0.0.1:51066 accepted tcp:github-production-user-asset-6210df.s3.amazonaws.com:443 [proxy] 
2020/02/08 00:14:03 tcp:127.0.0.1:51248 accepted tcp:mtalk.google.com:5228 [proxy] 

```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
      2020/02/07 15:54:53 tcp:59.39.148.62:6641 accepted tcp:www.facebook.com:443 
2020/02/07 15:54:53 tcp:59.39.148.62:6641 accepted tcp:www.facebook.com:443 
2020/02/07 15:55:11 tcp:59.39.148.62:7275 accepted tcp:www.facebook.com:443 
2020/02/07 15:55:11 tcp:59.39.148.62:7275 accepted tcp:www.facebook.com:443 
2020/02/07 15:55:41 tcp:59.39.148.62:7275 accepted tcp:www.facebook.com:443 
2020/02/07 15:56:45 tcp:59.39.148.62:6641 accepted tcp:www.google.com:443 
2020/02/07 15:56:45 tcp:59.39.148.62:6641 accepted tcp:www.google.com:443 
2020/02/07 15:56:45 tcp:59.39.148.62:7403 accepted tcp:www.google.com:443 
2020/02/07 15:56:45 tcp:59.39.148.62:7403 accepted tcp:www.google.com:443 
2020/02/07 15:56:45 tcp:59.39.148.62:7403 accepted tcp:www.google.com:443 
2020/02/07 15:57:47 tcp:59.39.148.62:6641 accepted tcp:www.google.com:443 
2020/02/07 15:57:47 tcp:59.39.148.62:6641 accepted tcp:www.google.com:443 
2020/02/07 15:57:48 tcp:59.39.148.62:7501 accepted tcp:www.google.com:443 
2020/02/07 15:59:02 tcp:59.39.148.62:6641 accepted tcp:mtalk.google.com:5228 
2020/02/07 16:00:08 tcp:59.39.148.62:6641 accepted tcp:www.facebook.com:443 
2020/02/07 16:04:02 tcp:59.39.148.62:6641 accepted tcp:mtalk.google.com:5228 
2020/02/07 16:05:01 tcp:59.39.148.62:6641 accepted tcp:clients4.google.com:443 
2020/02/07 16:05:25 tcp:59.39.148.62:6641 accepted tcp:analytics.twitter.com:443 
2020/02/07 16:09:02 tcp:59.39.148.62:6641 accepted tcp:mtalk.google.com:5228 
2020/02/07 16:09:53 tcp:59.39.148.62:6641 accepted tcp:steamcommunity.com:443 
2020/02/07 16:09:54 tcp:59.39.148.62:6641 accepted tcp:steamcommunity.com:443 
2020/02/07 16:11:25 tcp:59.39.148.62:6641 accepted tcp:github-production-user-asset-6210df.s3.amazonaws.com:443 
2020/02/07 16:14:03 tcp:59.39.148.62:6641 accepted tcp:mtalk.google.com:5228 
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by kslr** [comment]
检查你本地计算机，为什么GOOGLE会使用FACEBOOK的证书

**Comment by 0ldw** [comment]
我之前在Linux系统上用ssh隧道和Wireguard时也遇到过这种问题，访问Google和Wikipedia莫名其妙变为Facebook证书，有时刷新一下就好了，自从换了win10用v2ray后还没出现过这个问题。没准vps被中间人攻击了，你是不是再用vultr？

**Comment by yerphon** [comment]
> 我之前在Linux系统上用ssh隧道和Wireguard时也遇到过这种问题，访问Google和Wikipedia莫名其妙变为Facebook证书，有时刷新一下就好了，自从换了win10用v2ray后还没出现过这个问题。没准vps被中间人攻击了，你是不是再用vultr？

不是vultr，我在服务器上ping google是有响应的

**Comment by daiaji** [comment]
是在哪里发生了中间人攻击？

**Comment by tomac4t** [comment]
请检查服务器和本机的 DNS 设置。

**Comment by yerphon** [comment]
> 是在哪里发生了中间人攻击？

这个难说唉

**Comment by okudayukiko** [comment]
用WS+Let's Encrypt TLS。目前没问题。

**Comment by lushann** [comment]
已在使用 ws + Let's Encrypt TLS ，刚才google还是用的facebook的证书 重启了一下客户端好了。

**Comment by KurumiSerori** [comment]
+1 MacOS，服务器在Linode
ws + Let's Encrypt + CloudFlare, 不只是Google会出现这个问题，但大部分时间都是发生在Google上，证书变成Facebook系的，过一会会自动变正常。

**Comment by McLeeX** [comment]
是不是DNS被劫持了，或者使用的运营商的DNS？我曾经碰过同样的问题，换了公共DNS之后就好了

**Comment by KurumiSerori** [comment]
> 是不是DNS被劫持了，或者使用的运营商的DNS？我曾经碰过同样的问题，换了公共DNS之后就好了

在多地多种网络环境下都碰到了这种情况，还蛮谜的，按道理来说估计跟本地环境有关，但想来想去没想到本地什么进程能有这种效果。关键是只有经过v2ray的网络访问会被劫持，其他网站不会。
我准备切换一下DNS观察一段时间。

**Comment by McLeeX** [comment]
> > 是不是DNS被劫持了，或者使用的运营商的DNS？我曾经碰过同样的问题，换了公共DNS之后就好了
> 
> 在多地多种网络环境下都碰到了这种情况，还蛮谜的，按道理来说估计跟本地环境有关，但想来想去没想到本地什么进程能有这种效果。关键是只有经过v2ray的网络访问会被劫持，其他网站不会。
> 我准备切换一下DNS观察一段时间。

刚在我本地win10机器用nslookup查了几次解析，返回是这样的：
```
> nslookup www.google.com 8.8.8.8
服务器:  dns.google
Address:  8.8.8.8

非权威应答:
名称:    www.google.com
Addresses:  173.252.102.16
          199.59.150.11

> nslookup www.google.com 8.8.8.8
服务器:  dns.google
Address:  8.8.8.8

非权威应答:
名称:    www.google.com
Addresses:  69.171.228.74
          31.13.81.1

> nslookup www.google.com 114.114.114.114
服务器:  public1.114dns.com
Address:  114.114.114.114

非权威应答:
名称:    www.google.com
Addresses:  2404:6800:4008:802::2004
          208.101.60.87
```
每次查到的IP都不一样，但是这些IP用 https://ipinfo.io/ 查询指向的是facebook或者其他不清楚的服务器。无论本地用哪个DNS解析都是这个结果，我觉得和本地DNS污染之类的有关系。之前配置过DNS这个问题后来就消失了。

**Comment by KurumiSerori** [comment]
> > > 是不是DNS被劫持了，或者使用的运营商的DNS？我曾经碰过同样的问题，换了公共DNS之后就好了
> > 
> > 
> > 在多地多种网络环境下都碰到了这种情况，还蛮谜的，按道理来说估计跟本地环境有关，但想来想去没想到本地什么进程能有这种效果。关键是只有经过v2ray的网络访问会被劫持，其他网站不会。
> > 我准备切换一下DNS观察一段时间。
> 
> 刚在我本地win10机器用nslookup查了几次解析，返回是这样的：
> 
> ```
> > nslookup www.google.com 8.8.8.8
> 服务器:  dns.google
> Address:  8.8.8.8
> 
> 非权威应答:
> 名称:    www.google.com
> Addresses:  173.252.102.16
>           199.59.150.11
> 
> > nslookup www.google.com 8.8.8.8
> 服务器:  dns.google
> Address:  8.8.8.8
> 
> 非权威应答:
> 名称:    www.google.com
> Addresses:  69.171.228.74
>           31.13.81.1
> 
> > nslookup www.google.com 114.114.114.114
> 服务器:  public1.114dns.com
> Address:  114.114.114.114
> 
> 非权威应答:
> 名称:    www.google.com
> Addresses:  2404:6800:4008:802::2004
>           208.101.60.87
> ```
> 
> 每次查到的IP都不一样，但是这些IP用 https://ipinfo.io/ 查询指向的是facebook或者其他不清楚的服务器。无论本地用哪个DNS解析都是这个结果，我觉得和本地DNS污染之类的有关系。之前配置过DNS这个问题后来就消失了。

```
~ kurumi$ nslookup www.google.com 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	www.google.com
Address: 75.126.33.156

kurumi$ nslookup www.google.com 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	www.google.com
Address: 216.58.200.36

kurumi$ nslookup www.google.com 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	www.google.com
Address: 31.13.64.33

kurumi$ nslookup www.google.com 114.114.114.114
Server:		114.114.114.114
Address:	114.114.114.114#53

Non-authoritative answer:
Name:	www.google.com
Address: 31.13.81.1
```
按照你说的方式查了一下，分别来自softlayer, google 和 facebook 以及 facebook，第二个IP打开也确实访问了Google的服务器。测试了一下，上游的DNS服务器应该是存在污染的。

不知道自己配置DNS是否会有帮助。或者最近在考虑用一下DOH，但比较担心延迟问题。

**Comment by 1265578519** [comment]
1.1.1.1这个dns不要用，换成8.8.8.8

**Comment by txdywy** [comment]
dns被污染或者劫持了，用tcp不要用udp，或者能走代理

GeekZhe <notifications@github.com> 于 2020年3月1日周日 下午5:41写道：

**Comment by FreddyZeng** [comment]
试试找一个在vps附近的google ip，然后配置host锁定。还有常用的网址也可以这样。或者把v2ray的客户端允许不安全证书开启就不会这样了，我试了一下，不会再出现SSL error

**Comment by symant233** [comment]
我用的 ss, 访问 `twitter` 有的时候也会变成证书是 `*.facebook.com`. 所以应该不是 v2ray 的问题, 准备换个DNS试试...

**Comment by Kiritow** [comment]
遇到这个问题的话可以尝试一下关闭IPv6，或者把IPv6的配置补全（虽然已经是上古issue但是因为出现在google搜索结果比较靠前所以还是决定补上）

**Comment by polarstormx** [comment]
> 遇到这个问题的话可以尝试一下关闭IPv6，或者把IPv6的配置补全（虽然已经是上古issue但是因为出现在google搜索结果比较靠前所以还是决定补上）

@Kiritow  请问下补全IPv6配置是指什么? 我最近也遇到了这个问题,google搜索时会出现这个facebook的证书,过一阵子后恢复正常.

**Comment by Waste2Time** [comment]
是否与server端dns相关？

两个server一个可以正常连接，另一个时好时坏，最近访问Google返回*.facebook.com或*.internal.org的证书。在有问题的server上ping reddit会返回facebook的ip地址。
![Screenshot 2024-11-13 131441](https://github.com/user-attachments/assets/094ce9b2-4be6-4637-910e-521b8739039d)

**Comment by Waste2Time** [comment]
> 是否与server端dns相关？
> 
> 两个server一个可以正常连接，另一个时好时坏，最近访问Google返回*.facebook.com或*.internal.org的证书。在有问题的server上ping reddit会返回facebook的ip地址。 ![Screenshot 2024-11-13 131441](https://private-user-images.githubusercontent.com/71972188/385600674-094ce9b2-4be6-4637-910e-521b8739039d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTAzOTMsIm5iZiI6MTczMTQ5MDA5MywicGF0aCI6Ii83MTk3MjE4OC8zODU2MDA2NzQtMDk0Y2U5YjItNGJlNi00NjM3LTkxMGUtNTIxYjg3MzkwMzlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA5MjgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhOTVlYmI4YzBkYTFlYjU0YjU2OWViOWI0ZmQxZmRiNzExOTRhYTAwZGQzMjViYmQzYjM2NDRmN2E5ZjcwMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CDODGvmg0yd1gqYTRjQQrepP-JnexIh7_1yGC6UUllM)

的确与服务器DNS相关，与客户端DNS无关。可以先排查下服务端能否正常ping到Google等。
