### ISSUE TITLE
when to release mobile client?

### ISSUE THREAD

**Issue by Wyvern** [v2ray/v2ray-core#223]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please answer the following questions before submitting your issue. Thank you.

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
1) What version of V2Ray are you using?

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
2) What your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

3) 你看到的不正常的现象是什么？
3) What did you see?

4) 你期待看到的正确表现是怎样的？
4) What do you expected to see instead?

5) 请附上你的配置文件。
5) Please attach your configuration file.

**Comment by v2ray** [comment]
Please take a look at third party clients that support V2Ray: https://www.v2ray.com/chapter_01/3rd_party.html
