### ISSUE TITLE
[Feature Request] Add "include" another config file support in JSON config file

### ISSUE THREAD

**Issue by miyatsu** [v2ray/v2ray-core#2230]
Let's say we have a config file which enable TCP, KCP and WebSocket in transport config part.

If we wannt to remove TCP transport support, we have to remove/comment the entire "tcpSettings". Next time if we wannt to add it back, we have to edit the same file again to add/uncomment the "tcpSettings", that is a lot of work if we have dozens of v2ray server/client config file to edit.

It is nice to have "include" feature support in v2ray config file like nginx, dnsmasq etc. So that we can put the common config text or one machine-spesific config text into another config file, and "include" this file in global config.json.

And some of the config require the same configuration in client and server side to make it work like tcpSetting with HTTP header, it is a little hard to maintaining the same common config part in both client.conf and server.conf.

This should make the config file look like this:

Server Side:
```
{
    "include":
    [
        "outbounds.conf.json",
        "inbounds.conf.json",

        // Chose TCP header as HTTP
        //"transport.tcp.none.conf.json",
        "transport.tcp.http.conf.json",

        // Uncomment this line to add VPS in US spesific config
        //"us.vps.conf.json",
        "jp.vps.conf.json"
    ]
}
```
Client Side:
```
{
    "inbounds":
    {...},
    "outbounds":
    {....},

    "include":
    [
        // Chose TCP header as HTTP
        //"transport.tcp.none.conf.json",
        "transport.tcp.http.conf.json",

        // Client Spesific Config Gose Here
        "raspberrypi.conf.json"
    ]
}
```

Moreover, the v2ray can automatic include each json file in this directory: /etc/v2ray/config.d/*.json

Similar feature request issue can be find here: #1567

**Comment by kslr** [comment]
see https://github.com/v2ray/v2ray-core/pull/2154

**Comment by miyatsu** [comment]
@kslr Oh, I see. I will keep this issue opened until that PR merged.
