### ISSUE TITLE
麻烦帮我看个错误 有一台机器连不上 同样的配置文件我把vmess地址更换其它服务器可以连上

### ISSUE THREAD

**Issue by littlesum** [v2ray/v2ray-core#2232]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

4) 你期待看到的正确表现是怎样的？

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
```

客户端配置:

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

2020/02/10 04:30:30 [Warning] [721424631] v2ray.com/core/app/proxyman
/outbound: failed to process outbound traffic > v2ray.com/core/proxy/
vmess/outbound: failed to find an available destination > v2ray.com/c
ore/common/retry: [v2ray.com/core/transport/internet/websocket: faile
d to dial WebSocket > v2ray.com/core/transport/internet/websocket: fa
iled to dial to (wss://xx/xx):  > x509: certificate is va
lid for www.hyatt.com, www.meetingsondemand.hyatt.com, www.hyattconne
ct.com, www.hyatt.jobs, thrive.hyatt.com, support.prod.hyatt.com, sup
port.hyatt.com, sspr.hyattidm.com, search.hyatt.jobs, sccm.hyatt.com,
 public.hyatt.com, hyattconnect.com, hyatt.jobs, gpiapp.prod.hyatt.co
m, gpiapp.hyatt.com, ecalert.hyatt.com, crl.hyatt.com, cfgmgr.prod.hy
att.com, cfgmgr.hyatt.com, careers.hyatt.com, not vps地址] > v2r
ay.com/core/common/retry: all retry attempts failed

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

25.77.93.155, server: xxx, request: "GET /mess HTTP/1.1", upstream: "http://127.0.0.1:44222/mess", host: "xxx"
2020/02/10 10:50:13 [error] 523#523: *5521 recv() failed (104: Connection reset by peer) while proxying upgraded connection, client: 1
17.28.213.00, server: xxx, request: "GET /mess HTTP/1.1", upstream: "http://127.0.0.1:44222/mess", host: "lxx"
2020/02/10 10:50:15 [error] 523#523: *5564 recv() failed (104: Connection reset by peer) while proxying upgraded connection, client: 1
17.28.213.69, server: xxx, request: "GET /mess HTTP/1.1", upstream: "http://127.0.0.1:44222/mess", host: "xxx"
                  

2020/02/10 10:45:04 [error] 523#523: *5279 recv() failed (104: Connection reset by peer) while proxying upgraded connection, client: 1
25.77.93.155, server: cxx, request: "GET /mess HTTP/1.1", upstream: "http://127.0.0.1:44222/mess", host: "cxx"

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

问题是这样的 这台服务器其它客户端可以连接 但是我做网关的机器没办法连接 客户端同样的配置文件 我把vmess那段一换 换一台服务器就正常！而且日志显示的地址 hyatt那些地址我没有访问啊 不知道哪来的 搞不明白什么问题！
我用了这台服务器作dns服务器会有影响么？

**Comment by kslr** [comment]
证书无效

**Comment by littlesum** [comment]
> 证书无效

这段描述里面确实有证书的相关词语 但我看像是描述后面那段网站证书无效  而且我有web服务 能看到有小锁的！

**Comment by littlesum** [comment]
测试了好几遍 服务器其它客户端可以正常使用 说明是客户端配置问题 客户端配置文件 我仅仅更改vmess 里面那段id address 就可以正常使用 但是换回这台服务器里面就报这个错！ 实在搞不明白什么问题

**Comment by kslr** [comment]
反正检查证书就对了，只有这点信息，我也只能这么说

**Comment by littlesum** [comment]
> 反正检查证书就对了，只有这点信息，我也只能这么说

刚又查了下 发现nginx 也有报错日志 其它地方没有报错日志 帮看下 谢谢🙏

**Comment by kslr** [comment]
你需要的只是按照模板填写信息，不要把时间浪费在一问一打上
