### ISSUE TITLE
出站协议出错：无法与Socks服务器建立连接

### ISSUE THREAD

**Issue by just-a-b** [v2ray/v2ray-core#2235]
**非常感谢您提供这么好的软件**，也感谢您能花时间看我的 Issue

提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    V2Ray客户端 -> V2Ray服务端 -> Tor代理 
    ps: 服务端通过 docker compose 部署

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
    outbound 规则（Socks协议）无法正常连接开放 Socksv5 端口的 Tor代理（配置在下面）
    但是我通过在V2Ray容器中执行 curl -x 命令却可以正常访问 Tor代理
    查看错误日志提示无法与Socks服务器建立连接

4) 你期待看到的正确表现是怎样的？
   正常连接开放 Socksv5 端口的 Tor代理

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

    V2Ray 服务和 Tor 服务均通过容器部署

    这是我的 docker-compose.yml（无关的配置已省略）
```yaml
version: '3'
services:
    v2ray:
        image: v2ray/official
        container_name: proxy.v2ray
    tor:
        image: osminogin/tor-simple
        container_name: proxy.tor
        expose:
            - 9050/tcp
            - 9050/udp
```

服务器端配置:
```javascript
   {
  "inbounds": [
    {
      "port": 8000,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "direct-uuid",
            "alterId": 255,
            "email": "direct@email.com"
          },
          {
            "id": "tor-uuid",
            "alterId": 255,
            "email": "tor@email.com"
          }
        ]
      },
      "tag": "in-0",
      "streamSettings": {
        "network": "ws",
        "security": "none",
        "wsSettings": {
          "path": "/vmess"
        }
      }
    }
  ],
  "outbounds": [
    {
      "tag": "blocked",
      "protocol": "blackhole",
      "settings": {}
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "tor",
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "proxy.tor",
            "port": 9050
          }
        ]
      }
    }
  ],
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "source": [
          "0.0.0.0/0"
        ],
        "user": [
          "direct@email.com"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "source": [
          "0.0.0.0/0"
        ],
        "user": [
          "tor@email.com"
        ],
        "outboundTag": "tor"
      }
    ]
  }
}
```

客户端配置:
```javascript
   流量正常到达服务端所以我觉得没问题，客户端未开启嗅探
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
     [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: server rejects request: 7
```

客户端错误日志:

```javascript
   不涉及客户端
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

*主要是一些DNS请求*
```javascript
    客户端IP accepted udp:1.1.1.1:53 [tor] email:tor@email.com
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

*Tor代理的配置 https://github.com/osminogin/docker-tor-simple*

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

*启动正常*
通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

*运行正常*
通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by just-a-b** [comment]
我同样尝试以下方案，均没有有效解决：
 - 去掉客户端的嗅探
 - 将 `address: "proxy.tor"` 中的域名换成容器网络的 IP

**Comment by just-a-b** [comment]
tcp 是能过去的，udp 过不去。

**Comment by just-a-b** [comment]
解决了。

貌似 Tor 是通过发送 TCP 域名（0x03）来做 Remote DNS 解析的，
我错误的以为是通过 UDP 来解析的，所以才会拒绝接受 UDP 包。

**Comment by zzp-x** [comment]
@just-a-b 你好，我现在也遇到了和你一样的问题，请问你当初是怎么解决的呢，改用别的协议吗？
