### ISSUE TITLE
mux报错了

### ISSUE THREAD

**Issue by k79e** [v2ray/v2ray-core#2239]
2020/02/12 21:57:53 [Info] [1138302253] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2020/02/12 21:57:53 [Info] [1138302253] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2020/02/12 21:57:56 [Info] v2ray.com/core/common/**mux: failed to write to downstream.** closing session 34 > io: read/write on closed pipe
2020/02/12 21:57:57 [Info] [1650791325] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2020/02/12 21:57:57 [Info] [1650791325] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2020/02/12 21:57:57 [Info] [3945659391] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2020/02/12 21:57:57 [Info] [3945659391] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2020/02/12 21:57:58 [Info] [3016786000] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2020/02/12 21:57:58 [Info] [3016786000] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2020/02/12 21:57:58 [Info] [2436875642] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2020/02/12 21:57:58 [Info] [2436875642] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2020/02/12 21:57:58 [Info] [740400307] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2020/02/12 21:57:58 [Info] [740400307] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2020/02/12 21:57:58 [Info] [3571374126] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2020/02/12 21:57:58 [Info] [3571374126] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2020/02/12 21:57:58 [Info] [3563090180] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2020/02/12 21:57:58 [Info] [3563090180] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2020/02/12 21:58:01 [Info] [1097740267] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2020/02/12 21:58:01 [Info] [1097740267] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2020/02/12 21:58:01 [Info] [618451262] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2020/02/12 21:58:01 [Info] [618451262] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2020/02/12 21:58:02 [Info] [2557936553] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2020/02/12 21:58:02 [Info] [2557936553] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe

2020/02/12 21:58:15 [Info] [157649084] v2ray.com/core/common/mux: failed to fetch all input > io: read/write on closed pipe
2020/02/12 21:58:26 [Info] v2ray.com/core/common/**mux: failed to read metadata** > io: read/write on closed pipe

2020/02/12 21:58:27 [Info] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > **websocket: close 1000 (normal)**

2020/02/12 21:58:58 [Info] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > **websocket: close 1006 (abnormal closure): unexpected EOF**

用的ws over web(tls) 
这次不仅是一个老连接卡了 新连接速度快. 这个卡了的根本连资源都打不开了. 就不动了.
于是我复制下来了几个报错的信息.
我只开了info日志 是不是不够呢.

**Comment by k79e** [comment]
这好像是网站出问题了 广告过滤有点问题...

**Comment by heitu001** [comment]
2020/02/15 16:34:10 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
