### ISSUE TITLE
希望能够增加能够查看到连接该端口的IP日志

### ISSUE THREAD

**Issue by Hanyokign** [v2ray/v2ray-core#2245]
增加了info的log后能够看到连接日志，但是并不能准确看到那个IP是经由哪个vmess的端口连接的。例如我的朋友分别使用了2个vmess的端口，我日志里面能够看到有不同的IP但是并不能由连接端口得知哪个才是他们的IP。可以参照一手ssr里面的连接查询。可提供一定donate

**Comment by kslr** [comment]
你可以使用“邮件”

**Comment by Hanyokign** [comment]
什么邮件。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Kslr <notifications@github.com&gt;
发送时间: 2020年2月14日 01:49
收件人: v2ray/v2ray-core <v2ray-core@noreply.github.com&gt;
抄送: Hanyouking <873169775@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[v2ray/v2ray-core] 希望能够增加能够查看到连接该端口的IP日志 (#2245)




你可以使用“邮件”

**Comment by DolorHunter** [comment]
https://www.v2ray.com/chapter_02/stats.html
https://guide.v2fly.org/advanced/traffic.html
