### ISSUE TITLE
安裝腳本無法使用在 MX LINUX

### ISSUE THREAD

**Issue by JimmyChangJY** [v2ray/v2ray-core#2249]
MX LINUX 現在在https://distrowatch.com/
排名第一已經好一陣子
MX LINUX 基於 Debian 
但是我們的安裝腳本如果安裝在 MX LINUX下
卻無法使用
安裝完畢後打 service v2ray start
會顯示 v2ray: unrecognized service

**Comment by kslr** [comment]
systemctl

**Comment by JimmyChangJY** [comment]
systemctl 也是一樣
