### ISSUE TITLE
Proposal: Support Checking certificate public key instead of  checking CA and chain

### ISSUE THREAD

**Issue by xiaokangwang** [v2ray/v2ray-core#225]
Currently, V2Ray can either blindly accept all certificates or accept one issued a trusted CA(which can be very difficult for average user). I would like to propose a change so that user can pin public key(s) at tls configure.

If one or more key public have been pinned, V2Ray will regard any certificate that have its public key pinned valid, and otherwise invalid. This will prevent any MITM attack as long as attacker don’t have the private key corresponding to pinned publickey.  Since it is always the end user that generate certificate, they have a limited set of certificate to use and it is easy for them to pin the public than asking CA to sign their CSR.

The golang’s default mechanism is suitable for situation when user is connecting to arbitrary sites, and needs to accept arbitrary number of certificate, which is different than currently that of V2Ray’s.  By supporting this feature, TLS encryption can be used more frequently on V2Ray, improving security and decrease configuring difficulty.

**Comment by v2ray** [comment]
Tracked by https://trello.com/c/HzjJgL2l/9-allow-tls-client-to-add-trusted-ceritificates

This is not feasible for now in Go 1.7. There is no API to retrieve system CAs in Windows. We can use all system CAs (by default), or use the public key provided by customer, but not both.

I suggest postpone this work item to sometime after Go 1.8 release.
