### ISSUE TITLE
Centos 监听 0.0.0.0 时只监听 tcp6，无法监听 tcp4

### ISSUE THREAD

**Issue by dongrenwen** [v2ray/v2ray-core#2250]
Centos 7.5 使用版本 4.22.1，监听 0.0.0.0 时，只会监听 tcp6 而不会监听 tcp4，导致在没有 IPV6 的服务器上无法正常使用。

**Comment by okudayukiko** [comment]
0.0.0.0对应::0
用nmtui看看IP配置是否正确
