### ISSUE TITLE
更新到1.22版本后无法使用，同时做一些反馈

### ISSUE THREAD

**Issue by qingfengshi** [v2ray/v2ray-core#226]
升级1.22后，第一台电脑中V2ray中的vmess协议不能连接，和网络环境有关系，更换一个地方上网，网络环境应该相同（都是一个公司网络，需要登录认证后上外网），IP不同，第二台电脑使用vmess连接服务器，就是OK的。但是相同网络环境下，无论v2ray中的shadowsocks总是可用的。因此，不知这是不是vmess协议本身有的问题？

针对之前的使用的一些反馈。
之前版本的使用中，发现vmess连接会不时中断。比如浏览器15分钟没有任何操作，再连接Google时可能就不能连接了；有时看着YouTube视频，连接也会中断；但v2ray软件内部的shadowsocks代理在同一时间还是可用的。过一段时间vmess又可用，无论是否重启客户端软件。不知这是否是vmess协议本身的特性导致的？

下面是具体描述。

我现在服务器端和客户端使用的都是V1.22，服务器端为Ubuntu 14.04 x86_64系统，客户端为Window7 64位系统。通过Chrome连接代理浏览墙外网站，特别是Google。之前使用V1.21.2的服务器端版本，V1.19.2的客户端版本，基本可以正常浏览（具有的问题放最后陈述）。今天将服务器端和客户端版本更新后，不能连接墙外网站。如果修改配置文件，将本地代理从http改为socks，gmail能打开，但是Google打不开，同时客户端不报错。以下为我的服务器端和客户端的配置文件，在更新前和更新后，配置文件都没有变化（隐藏了ip和uuid）：

服务器端：
```javascript
{
 "port":1045,
 "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "myuuid",
          "level": 1,
          "alterId": 99
        }
      ],
      "features": {
        "detour": {
          "to": "detour"
        }
      }
    },
    "streamSettings": {
          "network": "kcp"
                       }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "inboundDetour": [
    {
      "protocol": "vmess",
      "port": "10050-13500",
      "tag": "detour",
      "settings": {},
      "streamSettings": {
      "network": "kcp"
    },
      "allocate": {
        "strategy": "random",
        "concurrency": 2,
        "refresh": 5
      }
    }
  ],
"inboundDetour":[
  {
    "protocol": "shadowsocks",
    "port": 1001,
    "settings": {
      "method": "aes-256-cfb",
      "password": "mypassword",
      "udp": false
                }
    },
  {
    "protocol": "shadowsocks",
    "port": 1002,
    "settings": {
      "method": "aes-256-cfb",
      "password": "mypassword",
      "udp": false
                }
    }
],
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  },
  "transport": {
    "kcpSettings": {
      "uplinkCapacity": 10,
      "downlinkCapacity": 10
    }
  }
}
```

客户端配置文件：

```javascript
{
  "log": {
    "loglevel": "warning"
  },
  "inbound": {
    "port": 1090,
    "listen": "0.0.0.0",
    "protocol": "http",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "myserverip",
          "port": 1045,
          "users": [
            {
              "id": "myuuid",
              "alterId": 99
            }
          ]
        }
      ]
    },
    "streamSettings": {
          "network": "kcp"
                       }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": "1-52",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "54-79",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "81-442",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "444-65535",
          "outboundTag": "direct"
        },
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        }
      ]
    }
  },
  "transport": {
    "kcpSettings": {
      "uplinkCapacity": 10,
      "downlinkCapacity": 100
    }
  }
}
```

在连不通的过程中，服务器端一直有报错：
2016/08/03 02:50:23 [Warning]Freedom: Failed to open connection to tcp:37.61.54.158:443: All retry attempts failed.
2016/08/03 02:50:23 [Warning]Freedom: Failed to open connection to tcp:37.61.54.158:443: All retry attempts failed.
2016/08/03 02:50:23 [Warning]Freedom: Failed to open connection to tcp:37.61.54.158:443: All retry attempts failed.
2016/08/03 02:50:28 [Warning]Freedom: Failed to open connection to tcp:37.61.54.158:443: All retry attempts failed.
2016/08/03 02:50:42 [Warning]Freedom: Failed to open connection to tcp:37.61.54.158:443: All retry attempts failed.
2016/08/03 02:50:54 [Warning]Point: Unable to find an inbound handler with tag: detour
2016/08/03 02:52:55 [Warning]Point: Unable to find an inbound handler with tag: detour
2016/08/03 03:01:16 [Warning]Point: Unable to find an inbound handler with tag: detour
2016/08/03 03:01:46 [Warning]Point: Unable to find an inbound handler with tag: detour
2016/08/03 03:05:17 [Warning]Point: Unable to find an inbound handler with tag: detour
2016/08/03 03:07:41 [Warning]Point: Unable to find an inbound handler with tag: detour
2016/08/03 03:08:54 [Warning]Point: Unable to find an inbound handler with tag: detour
2016/08/03 03:09:55 [Warning]Point: Unable to find an inbound handler with tag: detour
2016/08/03 03:10:25 [Warning]Point: Unable to find an inbound handler with tag: detour

客户端不能打开Google，但是没有任何报错。在此基础上，由于我配置了shadowsocks代理，发现在同一时间，shadowsocks代理可以正常使用，但是Vmess部分就不能使用。

**Comment by wangyi2005** [comment]
37.61.54.158，你懂的
另有疑问：socks5代理难道不是发送域名远程解析吗？反而http代理是发送域名？

**Comment by qingfengshi** [comment]
不是吧，我在更新之前一直可以连接的，更新之后就不能连接，不会那么巧吧

**Comment by benhon2008** [comment]
什么会访问 37.61.54.158 ？

**Comment by qingfengshi** [comment]
他的意思是受到DNS污染，某些网站会指向那个ip

**Comment by benhon2008** [comment]
用了很多年的DNS加密查询代理，现在需要带参数-T运行，
嫌弃前台命令提示符窗口的话可以加开机后台；
DNSCrypt
https://www.opendns.com/about/innovations/dnscrypt/

快速切换DNS配置的小工具，一键清理DNS缓存；
DNS Jumper
http://www.sordum.org/7952/dns-jumper-v2-0/

翻墙时切换到加密DNS，上中华局域网就切换本地DNS。

另外 V2ray 的 DNS转发的功能就成功过一次，再测试又被污染了，没时间探究原因。。。

**Comment by qingfengshi** [comment]
我不是很明白的是，配置文件里已经制定了使用Google的DNS服务器，可是为什么还是被污染呢？

**Comment by qingfengshi** [comment]
服务器端和客户端都已升级到最新版本，之前可以连接的电脑还是可以连接。
在不能连接Google的网络环境下，发现在客户端不报错的情况下，服务器端会重复出现以下错误：
2016/08/08 02:36:25 [Warning]Freedom: Failed to open connection to tcp:37.61.54.158:80: All retry attempts failed.
2016/08/08 02:36:54 [Warning]Point: Unable to find an inbound handler with tag: detour

其中ip 37.61.54.158是一个被污染后的垃圾ip，也就是说，我的网络环境可能遭受到较强的DNS污染。这里有两个问题：
（1）在需要通过代理的流量中，域名不是发送到vps，而后转发到远端服务器（如8.8.8.8）解析的吗？
（2）我的配置文件如上，应该没有问题，为什么服务器端会重复出现第二种错误？这会是什么原因导致的？

**Comment by v2ray** [comment]
可能是 V2Ray 的 DNS 出了什么问题。默认设置中最后会 fallback 到 localhost 就是用本机的 DNS 解析，这样可能会受到污染。

等有空了研究一下 DNS 的问题。

**Comment by qingfengshi** [comment]
我今天按照#230的方法，在服务器端做了一个端口映射，然后将端口端口加到客户端的DNS里，还是不能连接Google。我想使用端口映射的办法，应该是让代理流量都走映射端口进行DNS解析了，看来还有别的问题导致连接失败。

**Comment by qingfengshi** [comment]
更新一下。
今天找了一个路由，两台电脑同时连接在这台路由上，这样两台电脑在互联网中就是同一个IP，网络环境也相同。发现之前vmess不能连接的电脑还是不能连接，但是另一台电脑能够稳定连接，不会出现中途掉线的情况。
因此，我想我之前提出的问题，应该是我使用的电脑本身的问题，并不是v2ray软件的问题。这个问题可以关闭了。
谢谢之前与我讨论的各位朋友，麻烦大家了。

**Comment by qingfengshi** [comment]
看到一位朋友说是迅雷的问题，卸载迅雷极速版，好了。
