### ISSUE TITLE
老板好。能否编译Win10 ARM64版本？

### ISSUE THREAD

**Issue by tonchee05** [v2ray/v2ray-core#2261]
老板好。能否编译Win10 ARM64版本？
设备：Matebook E 2019 (Snapdragon 850)
今年还有Surface Pro X, Galaxy book S等设备会采用Snapdragon处理器，运行Win10 ARM64版本。
谢谢！

**Comment by HaoweiCh** [comment]
why not compile yourself?

**Comment by nicholascw** [comment]
tldr: Golang不支持。
https://github.com/golang/go/wiki/GoArm
https://github.com/golang/go/wiki/Windows
