### ISSUE TITLE
mac启动v2ray后报错：failed to process outbound traffic，failed to read header

### ISSUE THREAD

**Issue by plh76** [v2ray/v2ray-core#2262]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
客户端为mac版本的，先为4.21.0, 改成4.22.0版本仍然出现同样的问题，服务器端为4.22.1
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
firefox通过v2ray上网。客户端的inbounds协议为socks协议，outbounds协议为vmess；服务器端inbounds为vmess，outbounds为freedom。并采用了mkcp
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
我大约是1个月前安装的v2ray+mkcp，起初上网速度非常快且稳定。中间对软件未做任何修改，约2周前开始无法上网，通过mac终端运行v2ray后，通过firefox上网（全局代理），firefox下方提示“正在与**.com TLS握手，但无法进入**.com，约2分钟后mac终端提示：
[Warning] [4158630593] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF

4) 你期待看到的正确表现是怎样的？
正常上网
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```
{  
"inbounds": [    
{    
"port": 1*****,    
"protocol": "vmess",    
"settings": {
"clients": [
{
"id": "a939*****",
"level": 1,
"alterId": 64
}
] 
},    
"streamSettings": {
"network": "mkcp",
"kcpSettings": {
"uplinkCapacity": 5,
"downlinkCapacity": 100,
"congestion": true,
"header": {"type": "dtls"
}   
}  
} 
}
],  
"outbounds": [
{    
"protocol": "freedom",    
"settings": {}  
} 
]
}
```

客户端配置:

```
{
  "inbounds": [
    {
      "port": 1080, // 监听端口
      "protocol": "socks", // 入口协议为 SOCKS 5
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
      "settings": {
        "auth": "noauth"  //socks的认证设置，noauth 代表不认证，由于 socks 通常>在客户端使用，所以这里不认证
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess", // 出口协议
      "settings": {
        "vnext": [
          {
            "address": "***"
            "port": ****,
"users": [
              {
                "id": "a939***"
 "alterId": 64 // 此处的值也应当与服务器相同
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "mkcp",
        "kcpSettings": {
          "uplinkCapacity": 5,
          "downlinkCapacity": 100,
          "congestion": true,
          "header": {
            "type": "dtls"
          }
        }
      }
    }
  ]
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:
请见谅，小白一个，找不到日志，但我感觉是客户端的问题

客户端错误日志:
2020/02/18 21:51:24 [Warning] [142340472] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/02/18 21:51:24 [Warning] [4023533887] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/02/18 21:51:33 [Warning] [2883793874] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/02/18 21:51:35 [Warning] [4126825767] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/02/18 21:51:36 [Warning] [2163117559] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF

```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
请见谅，小白一个，找不到日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。
不知道在哪里，请见谅

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。
V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 linux/amd64)
A unified platform for anti-censorship.
Configuration OK.

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。
- Logs begin at Sun 2020-02-1* **:**:20 UTC, end at Tue 2020-02-1* 14:04:22 UTC. --
Feb 1* 17:00:40 ip-***-26-*-99 systemd[1]: Started V2Ray Service.
Feb 1* 17:00:40 ip-***-26-*-99 v2ray[9095]: V2Ray 4.22.1 (V2Fly, a community-driven editio
Feb 1* 17:0*:40 ip-172-26-1-99 v2ray[9095]: A unified platform for anti-censorship.
Feb 1* 17:1*:14 ip-1**-26-1-99 v2ray[9095]: 2020/02/**:**:14 [Warning] [642295451] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: unabl （这一行后面还有文字，但在lightsail中显示不全了）

**Comment by kslr** [comment]
停止使用MKCP

**Comment by zeenpz** [comment]
同样问题，求解

**Comment by plh76** [comment]
> 停止使用MKCP
谢谢你的回答。我将config文件中关于mkcp的下列内容删除了：
"streamSettings": {
        "network": "mkcp",
        "kcpSettings": {
          "uplinkCapacity": 5,
          "downlinkCapacity": 100,
          "congestion": true,
          "header": {
            "type": "dtls"
}
}
}

重新启动v2ray，则报错如下：
2020/02/19 20:53:52 [Warning] [3913453840] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp **.**.**.**:port*: i/o timeout dial tcp **.**.**.**:port*: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
感觉又出现了新的问题。

**Comment by plh76** [comment]
> 停止使用MKCP

我删除了config文件中关于mkcp的下列配置
"streamSettings": {
        "network": "mkcp",
        "kcpSettings": {
          "uplinkCapacity": 5,
          "downlinkCapacity": 100,
          "congestion": true,
          "header": {
            "type": "dtls"
}
}
}
重新启动v2ray，出现下列报错：
2020/02/19 20:53:52 [Warning] [3913453840] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp **.**.**.**:port*: i/o timeout dial tcp **.**.**.**:port*: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
还是不明白

**Comment by zeenpz** [comment]
我这边是客户端和服务器版本问题导致，我把客户端版本降为2.28就正常了

**Comment by didila** [comment]
同样的issues错误看了第四个，都是配置复杂化，把自己搞死的缘故

**Comment by skyroam** [comment]
> 停止使用MKCP

@kslr 现在不能配置kcp了吗？

**Comment by haozhiqianga** [comment]
o 这个问题解决了吗

**Comment by tim-bob** [comment]
我也遇到了
