### ISSUE TITLE
FreeBSD下无法自启动

### ISSUE THREAD

**Issue by brydio** [v2ray/v2ray-core#2267]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v2ray-4.20.0（pkg install安装）

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
把v2ray装在jail里

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
重启jail后v2ray无法自启动，需要手动执行service v2ray start

4) 你期待看到的正确表现是怎样的？

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
```

客户端配置:

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by lucifer9** [comment]
你手动启动下试试看，pkg 装上的，我记得好像那两个 dat 是坏的？手动启动如果是这个错，自己下载下新的覆盖一下就行了。
另外 FreeBSD 要自动启动的话，改 /etc/rc.conf 了吧

**Comment by brydio** [comment]
> 你手动启动下试试看，pkg 装上的，我记得好像那两个 dat 是坏的？手动启动如果是这个错，自己下载下新的覆盖一下就行了。
> 另外 FreeBSD 要自动启动的话，改 /etc/rc.conf 了吧

/etc/rc.conf修改过了，很奇怪nginx和php-fpm都可以自启动，唯独v2ray不行
试过手动运行，怎么运行都可以跑起来，放到自启动里就无效。
一会试试覆盖运行

**Comment by brydio** [comment]
> 你手动启动下试试看，pkg 装上的，我记得好像那两个 dat 是坏的？手动启动如果是这个错，自己下载下新的覆盖一下就行了。
> 另外 FreeBSD 要自动启动的话，改 /etc/rc.conf 了吧

覆盖后可以手动跑起来，自启动依然不行，我附上init.d看看能不能优化一下

```
#!/bin/sh
#
# $FreeBSD: branches/2020Q1/net/v2ray/files/v2ray.in 500991 2019-05-08 03:23:29Z loader $
#

# PROVIDE: v2ray
# KEYWORD: shutdown

# Add these lines to /etc/rc.conf.local or /etc/rc.conf to enable `v2ray':
#
# v2ray_enable (bool):          Set to "NO" by default.
#                               Set it to "YES" to enable v2ray
# v2ray_config (path):          Set to "/usr/local/etc/v2ray/config.json" by default
#                               Set it to the v2ray server config
# v2ray_logdir (path):          Set to "/var/log/v2ray" by default.
#                               Set it to the directory of v2ray log files
# v2ray_env (str):              Set to "" by default.
#                               Set it to the desired environment variables

. /etc/rc.subr

name="v2ray"
rcvar="${name}_enable"

: ${v2ray_enable="NO"}
: ${v2ray_config="/usr/local/etc/$name/config.json"}
: ${v2ray_logdir="/var/log/${name}"}
: ${v2ray_env=""}
: ${v2ray_user="v2ray"}
: ${v2ray_group="v2ray"}

asset_env="V2RAY_LOCATION_ASSET=/usr/local/share/$name"
pidfile="/var/run/$name.pid"
procname="/usr/local/bin/$name"
command="/usr/sbin/daemon"
command_args="-c -p ${pidfile} /usr/bin/env ${asset_env} ${v2ray_env} ${procname} -config ${v2ray_config}"
required_files="${v2ray_config}"

start_precmd="v2ray_startprecmd"

v2ray_startprecmd() {
        touch "${pidfile}"
        chown ${v2ray_user}:${v2ray_group} "${pidfile}"
        mkdir -p "${v2ray_logdir}"
        chown -R ${v2ray_user}:${v2ray_group} "${v2ray_logdir}"
}

load_rc_config "$name"
run_rc_command "$1"
```

**Comment by littlesum** [comment]
直接写个简单点启动脚本
然后添加到 /etc/rc.local就行了！
/etc/rc.local 可能默认不存在 你自己创建就行了！
具体可以’ man rc.local’

启动脚本 
 
`#!/bin/sh
#local v2ray config
/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json`

为了安全可以指定用户运行
‘sudo -u v2ray /usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json`

**Comment by unknowndev233** [comment]
或许你可以抄一份在 freebsd 的其他服务的 rc 文件
推荐抄与 v2ray 启动行为相似的，例如说都在前台工作

**Comment by brydio** [comment]
> 或许你可以抄一份在 freebsd 的其他服务的 rc 文件
> 推荐抄与 v2ray 启动行为相似的，例如说都在前台工作

这两天放那里没有折腾了，回头写一个看看

**Comment by brydio** [comment]
> 直接写个简单点启动脚本
> 然后添加到 /etc/rc.local就行了！
> /etc/rc.local 可能默认不存在 你自己创建就行了！
> 具体可以’ man rc.local’
> 
> 启动脚本
> 
> ``
> #!/bin/sh
> 
> # local v2ray config
> /usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json
> 
> ``
> 为了安全可以指定用户运行
> `sudo -u v2ray /usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json `

试过了，可能是最新的freebsd的bug，放进去似乎并不执行，回头把输出定向到log看看到底发生了啥

**Comment by unknowndev233** [comment]
> > 你手动启动下试试看，pkg 装上的，我记得好像那两个 dat 是坏的？手动启动如果是这个错，自己下载下新的覆盖一下就行了。
> > 另外 FreeBSD 要自动启动的话，改 /etc/rc.conf 了吧
> 
> 覆盖后可以手动跑起来，自启动依然不行，我附上init.d看看能不能优化一下
> 
> ```
> #!/bin/sh
> #
> # $FreeBSD: branches/2020Q1/net/v2ray/files/v2ray.in 500991 2019-05-08 03:23:29Z loader $
> #
> 
> # PROVIDE: v2ray
> # KEYWORD: shutdown
> 
> # Add these lines to /etc/rc.conf.local or /etc/rc.conf to enable `v2ray':
> #
> # v2ray_enable (bool):          Set to "NO" by default.
> #                               Set it to "YES" to enable v2ray
> # v2ray_config (path):          Set to "/usr/local/etc/v2ray/config.json" by default
> #                               Set it to the v2ray server config
> # v2ray_logdir (path):          Set to "/var/log/v2ray" by default.
> #                               Set it to the directory of v2ray log files
> # v2ray_env (str):              Set to "" by default.
> #                               Set it to the desired environment variables
> 
> . /etc/rc.subr
> 
> name="v2ray"
> rcvar="${name}_enable"
> 
> : ${v2ray_enable="NO"}
> : ${v2ray_config="/usr/local/etc/$name/config.json"}
> : ${v2ray_logdir="/var/log/${name}"}
> : ${v2ray_env=""}
> : ${v2ray_user="v2ray"}
> : ${v2ray_group="v2ray"}
> 
> asset_env="V2RAY_LOCATION_ASSET=/usr/local/share/$name"
> pidfile="/var/run/$name.pid"
> procname="/usr/local/bin/$name"
> command="/usr/sbin/daemon"
> command_args="-c -p ${pidfile} /usr/bin/env ${asset_env} ${v2ray_env} ${procname} -config ${v2ray_config}"
> required_files="${v2ray_config}"
> 
> start_precmd="v2ray_startprecmd"
> 
> v2ray_startprecmd() {
>         touch "${pidfile}"
>         chown ${v2ray_user}:${v2ray_group} "${pidfile}"
>         mkdir -p "${v2ray_logdir}"
>         chown -R ${v2ray_user}:${v2ray_group} "${v2ray_logdir}"
> }
> 
> load_rc_config "$name"
> run_rc_command "$1"
> ```
> 
> 怀疑是输出后需要按任意键继续导致启动失败

建议执行脚本看看
