### ISSUE TITLE
  My v2ray server VPS prohibits ICMP Protocol. Can v2ray client connect server?

### ISSUE THREAD

**Issue by kiddingl** [v2ray/v2ray-core#2268]
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

此 Issue 会被立即关闭。

If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2ray/discussion/issues) first.

This issue will be closed immediately.

**Comment by kiddingl** [comment]
My v2ray server vps prohubits icmp, can't local client can't connect v2ray-server

**Comment by kiddingl** [comment]
如果vps上禁止了icmp协议，我的本地的客户端能够连接vps上的v2ray-server吗？

**Comment by kslr** [comment]
No problems

**Comment by kiddingl** [comment]
> No problems
tahnks you
