### ISSUE TITLE
使用了代理转发 streamSettings 会失效

### ISSUE THREAD

**Issue by OPPO9008** [v2ray/v2ray-core#2269]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V2Ray 4.22.1
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
PC -> v2ray -> 公司http代理 -> v2ray服务器 -> 目标网站
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
客户端配置http代理后，无法上网
4) 你期待看到的正确表现是怎样的？
 streamSettings 不失效，成功fq
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
 无，不是我的网站
```

客户端配置:

```javascript
    
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
  2020/02/21 14:02:38 [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > io: read/write on closed pipe
2020/02/21 14:02:42 127.0.0.1:34672 accepted http://bbs.liuxingw.com/ [proxy] 
2020/02/21 14:02:42 [Warning] [2617364224] v2ray.com/core/proxy/http: failed to read response from bbs.liuxingw.com > io: read/write on closed pipe
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by didila** [comment]
这log摆明了是客户端的问题，你一直查服务端有什么用？
有时候别乱看网上教程，先将基本的配置搞好，再弄其它的部分。

**Comment by silencer001** [comment]
你这明显是客户端的配置问题啊
话说，最新版已经支持outbound是http代理了？

**Comment by OPPO9008** [comment]
> 这log摆明了是客户端的问题，你一直查服务端有什么用？
> 有时候别乱看网上教程，先将基本的配置搞好，再弄其它的部分。

我不是说服务器有问题，意思是不能使用HTTP前置代理连接v2Ray

**Comment by OPPO9008** [comment]
> 你这明显是客户端的配置问题啊
> 话说，最新版已经支持outbound是http代理了？

对啊！我那句话说是服务器的问题了，第二，公司特殊环境，上网要走HTTP代理，我想让我的v2Ray走HTTP代理实现fq

**Comment by silencer001** [comment]
> > 你这明显是客户端的配置问题啊
> > 话说，最新版已经支持outbound是http代理了？
> 
> 对啊！我那句话说是服务器的问题了，第二，公司特殊环境，上网要走HTTP代理，我想让我的v2Ray走HTTP代理实现fq

你贴下你客户端的配置帮你看看，我昨天试了下4.22.1可以走http前置

**Comment by KyonLi** [comment]
https://v2ray.com/chapter_02/01_overview.html#outboundobject

![image](https://user-images.githubusercontent.com/7446107/75653850-568c2c00-5c99-11ea-8803-98c2330be17c.png)
