### ISSUE TITLE
为什么我的透明代理对ipv6无效？

### ISSUE THREAD

**Issue by shenlijun** [v2ray/v2ray-core#2270]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

    v4.22.1

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

    各种你懂的

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

    同样的服务端VPS，openwrt路由器做透明代理，ipv6不会走v2ray，而pc客户端可以。
    ipv6-test.com测试，透明代理显示的是openwrt的ip6，pc客户端显示VPS的ip6

4) 你期待看到的正确表现是怎样的？

    openwrt透明代理，ipv6也走v2ray

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
    {
  "inbounds": [{
    "port": xxxx,
    "listen":"127.0.0.1",
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "xxxx",
          "level": 1,
          "alterId": 64
        }
      ]
    },
    "streamSettings": {
       "network": "ws",
       "wsSettings": {
        "path": "/xxxx"
        }
     }
  }],
  "outbounds": [{
    "protocol": "freedom",
    "settings": {}
  },{
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  }],
  "routing": {
    "rules": [
      {
       	"type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "blocked"
      }
    ]
  }
}

```

客户端配置:

照搬白话教程的设置，https://toutyrater.github.io/app/tproxy.html
```javascript
    // 在这里附上客户端配置
   {
	"log": {
		"access": "/dev/null"
	},
	"dns": {
		"servers": [
			"1.1.1.1",
			"8.8.8.8",
			"114.114.114.114",
			{
				"address": "223.5.5.5",
				"port": 53,
				"domains": [
					"geosite:cn",
					"ntp.org",
					"xxxx"
				]
			}
		]
	},
	"routing": {
		"domainStrategy": "IPOnDemand",
		"rules": [
			{
				"type": "field",
				"port": "53",
				"network": "udp",
				"inboundTag": [
					"transparent"
				],
				"outboundTag": "dns_out"
			},
			{
				"type": "field",
				"port": "123",
				"network": "udp",
				"inboundTag": [
					"transparent"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"ip": [
					"223.5.5.5",
					"114.114.114.114"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"ip": [
					"1.1.1.1",
					"8.8.8.8"
				],
				"outboundTag": "proxy"
			},
			{
				"type": "field",
				"domain": [
					"geosite:category-ads-all"
				],
				"outboundTag": "block"
			},
			{
				"type": "field",
				"protocol": [
					"bittorrent"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"ip": [
					"geoip:private",
					"geoip:cn"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"domain": [
					"geosite:cn"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"domain": [
					"geosite:speedtest"
				],
				"outboundTag": "direct"
			}
		]
	},
	"inbounds": [
		{
			"port": 1081,
			"protocol": "dokodemo-door",
			"settings": {
				"followRedirect": true,
				"network": "tcp,udp"
			},
			"streamSettings": {
				"sockopt": {
					"tproxy": "tproxy"
				}
			},
			"tag": "transparent",
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			}
		},
		{
			"port": 1080,
			"protocol": "socks",
			"settings": {
				"auth": "noauth",
				"udp": false
			},
			"streamSettings": {
				"sockopt": {
					
				}
			},
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			}
		}
	],
	"outbounds": [
		{
			"protocol": "vmess",
			"settings": {
				"vnext": [
					{
						"address": "xxxx",
						"port": 443,
						"users": [
							{
								"id": "xxxx",
								"alterId": 64,
								"level": 1
							}
						]
					}
				]
			},
			"streamSettings": {
				"network": "ws",
				"security": "tls",
				"tlsSettings": {
					"allowInsecure": false,
					"allowInsecureCiphers": false,
					"disableSystemRoot": false,
					"certificates": [
						
					]
				},
				"wsSettings": {
					"path": "/xxxx"
				},
				"sockopt": {
					"mark": 255
				}
			},
			"tag": "proxy",
			"mux": {
				"enabled": true,
				"concurrency": 8
			}
		},
		{
			"protocol": "freedom",
			"settings": {
				"domainStrategy": "UseIP"
			},
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			},
			"tag": "direct"
		},
		{
			"protocol": "blackhole",
			"settings": {
				"response": {
					"type": "http"
				}
			},
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			},
			"tag": "block"
		},
		{
			"protocol": "dns",
			"settings": {
				
			},
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			},
			"tag": "dns_out"
		}
	]
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by shenlijun** [comment]
不知道是v2ray配置的问题还是openwrt防火墙规则的问题？
防火墙是这样的：

表: Mangle
链 PREROUTING (策略: ACCEPT, 100264 数据包, 99.31 MB 流量)
数据包        流量             目标        协议    入口      出口      源地址       目标地址   选项
96.67 K       10.66 MB      V2RAY     all        br-lan    *            0.0.0.0/0     0.0.0.0/0    -         
152             11.01 KB       V2RAY     all        *            *            0.0.0.0/0     0.0.0.0/0    mark match 0x1

链 OUTPUT (策略: ACCEPT, 126633 数据包, 128.91 MB 流量)
数据包	流量	目标	协议	入口	出口	源地址	目标地址	选项	备注
126.63 K	128.91 MB	V2RAY_MASK	all	*	*	0.0.0.0/0	0.0.0.0/0	-	-

链 V2RAY (2 引用)
链 PREROUTING, 规则 #1
链 PREROUTING, 规则 #2
数据包	流量	目标	协议	入口	出口	源地址	目标地址	选项	备注
0 	0 B	RETURN	all	*	*	0.0.0.0/0	0.0.0.0/0	mark match 0xff	-
3.28 K	212.90 KB	TPROXY	udp	*	*	0.0.0.0/0	192.168.232.1	udp dpt:53 TPROXY redirect 0.0.0.0:1081 mark 0x1/0x1	-
30.59 K	2.72 MB	RETURN	all	*	*	0.0.0.0/0	0.0.0.0/0	match-set v2ray_dst_direct_v4 dst	-
63.72 K	7.76 MB	TPROXY	tcp	*	*	0.0.0.0/0	0.0.0.0/0	TPROXY redirect 0.0.0.0:1081 mark 0x1/0x1	-

链 V2RAY_MASK (1 引用)
链 OUTPUT, 规则 #1
数据包	流量	目标	协议	入口	出口	源地址	目标地址	选项	备注
42.46 K	7.56 MB	RETURN	all	*	*	0.0.0.0/0	0.0.0.0/0	mark match 0xff	-
84.37 K	121.52 MB	RETURN	all	*	*	0.0.0.0/0	0.0.0.0/0	match-set v2ray_dst_direct_v4 dst	-
71 	2.84 KB	MARK	tcp	*	*	0.0.0.0/0	0.0.0.0/0	MARK set 0x1	-
137 	10.41 KB	MARK	udp	*	*	0.0.0.0/0	0.0.0.0/0	MARK set 0x1	-

**Comment by shenlijun** [comment]
求指点啊啊啊

**Comment by shenlijun** [comment]
这个把UseIP改成UseIPv6就可以，呃
		{
			"protocol": "freedom",
			"settings": {
				"domainStrategy": "UseIP"
			},
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			},
			"tag": "direct"
		},

**Comment by shenlijun** [comment]
改回去UseIP忽然也可以了，呃

**Comment by shenlijun** [comment]
[v2ray-error.log](https://github.com/v2ray/v2ray-core/files/4237247/v2ray-error.log)
@kslr

**Comment by forever8938** [comment]
IPv6的透明代理要用iptables6

**Comment by shenlijun** [comment]
> IPv6的透明代理要用ip6tables

应该是这样的

**Comment by kslr** [comment]
最新代码已经修复了这个问题
