### ISSUE TITLE
无法连接 failed to handler mux client connection

### ISSUE THREAD

**Issue by Sonata-Wang** [v2ray/v2ray-core#2284]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
服务器：V2Ray 4.22.1  安卓手机客户端：1.1.15  win7客户端：2.29
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
使用 Chrome 通过VMess 代理上Google和观看 YouTube 视频
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
**已经将vps的时间和客户端时间同步了，且关闭防火墙
但是依旧无法连接**
手机客户端显示：io:read/write on closed pipe
win7上v2rayN客户端显示：
[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp xx.xx.xx.xx:xxxx: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. dial tcp xx.xx.xx.xx:xxxxx: connectex: No connection could be made because the target machine actively refused it. dial tcp xx.xx.xx.xx:xxxx: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed
4) 你期待看到的正确表现是怎样的？
希望能正常连接
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
{
	"log": {
		"access": "/var/log/v2ray/access.log",
		"error": "/var/log/v2ray/error.log",
		"loglevel": "warning"
	},
	"dns": {},
	"stats": {},
	"inbounds": [
		{
			"port": 14904,
			"protocol": "vmess",
			"settings": {
				"clients": [
					{
						"id": "a6dca37a-e907-463f-8a6e-8e091425d11a",
						"alterId": 16
					}
				]
			},
			"tag": "in-0",
			"streamSettings": {
				"network": "tcp",
				"security": "none",
				"tcpSettings": {}
			}
		}
	],
	"outbounds": [
		{
			"tag": "direct",
			"protocol": "freedom",
			"settings": {}
		},
		{
			"tag": "blocked",
			"protocol": "blackhole",
			"settings": {}
		}
	],
	"routing": {
		"domainStrategy": "AsIs",
		"rules": [
			{
				"type": "field",
				"ip": [
					"geoip:private"
				],
				"outboundTag": "blocked"
			}
		]
	},
	"policy": {},
	"reverse": {},
	"transport": {}
}
```

客户端配置:

```javascript
{
  "log":{},
  "dns":{},
  "stats":{},
  "inbounds":[],
  "outbounds":[
    {
      "protocol":"vmess",
      "settings":{
        "vnext":[
          {
            "address":"xxxxx",
            "port":14904,
            "users":[
              {
                "id":"xxxxxx",
                "alterId":16
              }
            ]
          }
        ]
      },
      "tag":"out-0",
      "streamSettings":{
        "network":"tcp",
        "security":"none",
        "tcpSettings":{}
      }
    },
    {
      "tag":"direct",
      "protocol":"freedom",
      "settings":{}
    },
    {
      "tag":"blocked",
      "protocol":"blackhole",
      "settings":{}
    }
  ],
  "routing":{
    "domainStrategy":"IPOnDemand",
    "rules":[
      {
        "type":"field",
        "ip":[
          "geoip:private"
        ],
        "outboundTag":"direct"
      }
    ]
  },
  "policy":{},
  "reverse":{},
  "transport":{}
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
无
```

客户端错误日志:

```javascript
[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp xxxx:xxx: connectex: No connection could be made because the target machine actively refused it. dial tcp 23.105.219.157:14904: i/o timeout dial tcp xxxxxx:xxxxx: connectex: No connection could be made because the target machine actively refused it. dial tcp xxxxxx:xxxxxx: i/o timeout dial tcp xxxxxx:xxx: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.] > v2ray.com/core/common/retry: all retry attempts failed

```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
无
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。
V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 linux/amd64)
A unified platform for anti-censorship.
Configuration OK.

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by kslr** [comment]
> No connection could be made because the target machine actively refused it.

**Comment by Sonata-Wang** [comment]
> > No connection could be made because the target machine actively refused it.

大佬可以说的具体点吗，我对这部分是小白。。。
我已经尝试过同步时间，关闭防火墙，安装之前的版本，也查了ip没有被墙，但是还是没办法连接
系统是Debian9 x86_64

**Comment by Sunnycheey** [comment]
是不是因为服务端和客户端的Id不一致，导致连接请求被拒绝？

**Comment by kslr** [comment]
1. 检查防火墙
2. 检查服务是否启动
循环

**Comment by miracle922** [comment]
[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
这是什么原因啊lz
小白一枚

**Comment by miracle922** [comment]
> [警告]无法处理多路复用器客户端连接> v2ray.com/core/proxy/vmess/outbound：连接结束> v2ray.com/core/proxy/vmess/outbound：无法读取标头> v2ray.com/core/proxy/ vmess / encoding：无法读取响应标头> websocket：关闭1000（正常）
> 这是什么原因啊lz
> 小白一枚

不知道干了啥前几天还能用的
