### ISSUE TITLE
V2Ray出现间歇性断流，无规律

### ISSUE THREAD

**Issue by johnnycxm** [v2ray/v2ray-core#2286]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
客户端版本4.22.1，服务端未知（现成的机场）
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
通过Chrome或者其他浏览器，无法访问youtube、google等站点。
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
间歇性断流，无法访问墙外站点。重启v2ray客户端偶尔正常，但稍后又终端。多次重启有可能正常。墙内站点多数时候正常访问，但也有偶尔无法访问的情况，ping 丢包严重（非宽带问题，不走v2ray的路由访问正常）
4) 你期待看到的正确表现是怎样的？
稳定正常的访问墙外站点。
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
```

客户端配置:

```javascript
    {
    "log": {
        "loglevel": "warning",
        "access": "/var/log/v2ray/access.log",
        "error": "/var/log/v2ray/error.log"
    },
    "inbounds": [
        {
            "tag": "transparent",
            "port": 12345,
            "protocol": "dokodemo-door",
            "settings": {
                "network": "tcp,udp",
                "followRedirect": true
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            },
            "streamSettings": {
                "sockopt": {
                    "tproxy": "tproxy"
                }
            }
        },
        {
            "port": 1080,
            "protocol": "socks",
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            },
            "settings": {
                "auth": "noauth"
            }
        }
    ],
    "outbounds": [
        {
            "tag": "proxy",
            "protocol": "vmess",
            "settings": {
                "vnext": [
                    {
                        "address": "myadress",
                        "port": xxxx,
                        "users": [
                            {
                                "email": "email",
                                "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                                "alterId": 2
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "security": "auto",
                "connectionReuse": true,
                "wsSettings": {
                    "path": ""
                },
                "headers": {
                    "Host": "myhost"
                },
                "sockopt": {
                    "mark": 255
                }
            },
            "mux": {
                "enabled": true
            }
        },
        {
            "tag": "direct",
            "protocol": "freedom",
            "settings": {
                "domainStrategy": "UseIP"
            },
            "streamSettings": {
                "sockopt": {
                    "mark": 255
                }
            }
        },
        {
            "tag": "dns-out",
            "protocol": "dns",
            "streamSettings": {
                "sockopt": {
                    "mark": 255
                }
            }
        }
    ],
    "dns": {
        "servers": [
            "8.8.8.8",
            "1.1.1.1",
            "114.114.114.114",
            {
                "address": "223.5.5.5",
                "port": 53,
                "domains": [
                    "geosite:cn",
                    "ntp.org",
                    "geosite:speedtest",
                    "myaddress",
                    "myhost"
                ]
            }
        ]
    },
    "routing": {
        "domainStrategy": "IPOnDemand",
        "rules": [
            {
                "type": "field",
                "inboundTag": [
                    "transparent"
                ],
                "port": 53,
                "network": "udp",
                "outboundTag": "dns-out"
            },
            {
                "type": "field",
                "inboundTag": [
                    "transparent"
                ],
                "port": 123,
                "network": "udp",
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "ip": [
                    "223.5.5.5",
                    "114.114.114.114"
                ],
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "ip": [
                    "8.8.8.8",
                    "1.1.1.1"
                ],
                "outboundTag": "proxy"
            },
            {
                "type": "field",
                "protocol":["bittorrent"],
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "outboundTag": "direct",
                "ip": [
                    "geoip:private",
                    "geoip:cn"
                ]
            },
            {
                "type": "field",
                "outboundTag": "direct",
                "domain": [
                    "geosite:cn",
                    "geosite:speedtest"
                ]
            }
        ]
    }
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript

```
客户端出现大量的此类日志，大概有几千行
客户端错误日志:

```javascript
    2020/02/26 22:10:57 [Info] [4181480843] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:40522: use of closed network connection
2020/02/26 22:10:57 [Info] [3180538590] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:38747: use of closed network connection
2020/02/26 22:10:57 [Info] [4181480843] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/02/26 22:10:57 [Info] [3180538590] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/02/26 22:10:57 [Info] [1225722524] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:52701: use of closed network connection
2020/02/26 22:10:57 [Info] [726718968] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:40744: use of closed network connection
2020/02/26 22:10:57 [Info] [1225722524] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/02/26 22:10:57 [Info] [726718968] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/02/26 22:10:57 [Info] [3334639214] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/02/26 22:10:57 [Info] [1145687361] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:42566: use of closed network connection
2020/02/26 22:10:57 [Info] [2575043231] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/02/26 22:10:57 [Info] [116458819] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:43959: use of closed network connection
2020/02/26 22:10:57 [Info] [3570260032] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/02/26 22:10:57 [Info] [3947571149] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:56905: use of closed network connection
2020/02/26 22:10:57 [Info] [116458819] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/02/26 22:10:57 [Info] [3947571149] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/02/26 22:10:57 [Info] [2327703784] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:40906: use of closed network connection
2020/02/26 22:10:57 [Info] [580409609] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:60464: use of closed network connection   
2020/02/26 22:11:02 [Debug] [3174956059] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.2.2:59378
2020/02/26 22:11:02 [Info] [3174956059] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:192.168.2.2:53]
2020/02/26 22:11:02 [Info] [3174956059] v2ray.com/core/proxy/dns: handling DNS traffic to udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] [3190483425] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.2.2:59754
2020/02/26 22:11:02 [Info] [3190483425] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:192.168.2.2:53]
2020/02/26 22:11:02 [Info] [3190483425] v2ray.com/core/proxy/dns: handling DNS traffic to udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] [2779085973] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.2.2:35456
2020/02/26 22:11:02 [Info] [2779085973] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:192.168.2.2:53]
2020/02/26 22:11:02 [Info] [2779085973] v2ray.com/core/proxy/dns: handling DNS traffic to udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] [1819369678] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.2.2:56088
2020/02/26 22:11:02 [Info] [1819369678] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:192.168.2.2:53]
2020/02/26 22:11:02 [Info] [1819369678] v2ray.com/core/proxy/dns: handling DNS traffic to udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] [2294997437] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.2.2:53965
2020/02/26 22:11:02 [Info] [2294997437] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:192.168.2.2:53]
2020/02/26 22:11:02 [Info] [2294997437] v2ray.com/core/proxy/dns: handling DNS traffic to udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] [2851601310] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.2.2:49799
2020/02/26 22:11:02 [Info] [2851601310] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:192.168.2.2:53]
2020/02/26 22:11:02 [Info] [2851601310] v2ray.com/core/proxy/dns: handling DNS traffic to udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] [4239849170] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.2.2:50538
2020/02/26 22:11:02 [Info] [4239849170] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:192.168.2.2:53]
2020/02/26 22:11:02 [Info] [4239849170] v2ray.com/core/proxy/dns: handling DNS traffic to udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] [2016935011] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.2.2:54641
2020/02/26 22:11:02 [Info] [2016935011] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:192.168.2.2:53]
2020/02/26 22:11:02 [Info] [2016935011] v2ray.com/core/proxy/dns: handling DNS traffic to udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] [3928215664] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.2.2:38155
2020/02/26 22:11:02 [Info] [3928215664] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:192.168.2.2:53]
2020/02/26 22:11:02 [Info] [3928215664] v2ray.com/core/proxy/dns: handling DNS traffic to udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] [77695693] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.2.2:53743
2020/02/26 22:11:02 [Info] [77695693] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:192.168.2.2:53]
2020/02/26 22:11:02 [Info] [77695693] v2ray.com/core/proxy/dns: handling DNS traffic to udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] [2768195775] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.2.2:57244
2020/02/26 22:11:02 [Info] [2768195775] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:192.168.2.2:53]
2020/02/26 22:11:02 [Info] [2768195775] v2ray.com/core/proxy/dns: handling DNS traffic to udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] [3176426139] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.2.2:43206
2020/02/26 22:11:02 [Info] [3176426139] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:192.168.2.2:53]
2020/02/26 22:11:02 [Info] [3176426139] v2ray.com/core/proxy/dns: handling DNS traffic to udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] [2283219694] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.2.2:55247
2020/02/26 22:11:02 [Info] [2283219694] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:192.168.2.2:53]
2020/02/26 22:11:02 [Info] [2283219694] v2ray.com/core/proxy/dns: handling DNS traffic to udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] [3440381211] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.2.2:43491
2020/02/26 22:11:02 [Info] [3440381211] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:192.168.2.2:53]
2020/02/26 22:11:02 [Info] [3440381211] v2ray.com/core/proxy/dns: handling DNS traffic to udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:192.168.2.2:53
2020/02/26 22:11:02 [Debug] [3100807199] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.2.2:56976
2020/02/26 22:11:02 [Info] [3100807199] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:192.168.2.2:53]
2020/02/26 22:11:02 [Info] [3100807199] v2ray.com/core/proxy/dns: handling DNS traffic to udp:192.168.2.2:53
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by kslr** [comment]
关闭DNS试试

**Comment by johnnycxm** [comment]
> 关闭DNS试试

谢谢，确实是dns的问题，把所有dns请求转发到v2ray客户端所到53端口导致的问题

**Comment by elliot-bia** [comment]
测试了一下, 可能是路由的策略导致的
```
     "domainStrategy": "IPOnDemand",  
```

现在更换为`IPIfNonMatch`,  正在测试中

参考资料:  https://steemit.com/cn/@v2ray/dns

![image](https://user-images.githubusercontent.com/40572216/98794470-0e3a2600-2444-11eb-91b8-477f24bc1273.png)

**Comment by zhuziyi1989** [comment]
果然我这里也是DNS导致  

https://cloudflare-dns.com/dns-query 这个大坑

`
2020/08/05 12:31:46 [Warning] V2Ray 4.40.1 started
2021/08/05 12:33:21 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 12:33:21 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 12:35:41 [Warning] proxy/vmess/encoding: Critical Warning: potentially invalid user: a non VMessAEAD connection is received. From 2022 Jan 1st, this kind of connection will be rejected by default. You should update or replace your client software now. This message will not be shown for further violation on this inbound.
2021/08/05 12:36:49 [Error] app/dns: failed to retrieve response > context canceled
2021/08/05 12:36:49 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 12:36:55 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 12:43:47 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 12:43:47 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 12:49:34 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 12:49:34 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 12:49:35 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 12:49:35 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 12:49:35 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 12:49:35 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 12:49:35 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 12:49:35 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:00:39 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:08:16 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:11:51 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:11:51 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:11:51 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:13:12 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:13:12 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:13:14 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:13:14 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:22:32 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:22:32 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:26:58 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:26:58 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:26:58 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:26:58 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:27:29 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:27:29 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:27:29 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:27:29 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:27:29 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:27:32 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:27:32 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:27:32 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:27:32 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:27:32 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:27:41 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:27:41 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:27:41 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:27:41 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:27:41 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:27:41 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:27:41 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:27:55 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:27:55 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:27:55 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:29:02 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:34:11 [Warning] V2Ray 4.40.1 started
2021/08/05 13:34:12 [Warning] proxy/vmess/encoding: Critical Warning: potentially invalid user: a non VMessAEAD connection is received. From 2022 Jan 1st, this kind of connection will be rejected by default. You should update or replace your client software now. This message will not be shown for further violation on this inbound.
2021/08/05 13:34:13 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:34:48 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:34:48 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
2021/08/05 13:52:36 [Error] app/dns: failed to retrieve response > Post "https://cloudflare-dns.com/dns-query": context canceled
/var/log/v2ray/error.log/var/log/v2ray/error.log/var/log/v2ray/error.log
`

**Comment by erbanku** [comment]
@zhuziyi1989 
## `8.8.8.8/dns-query` 也太坑
```
2022/06/06 09:22:55 [Error] app/dns: failed to retrieve response > Post "https://8.8.8.8/dns-query": context canceled
2022/06/06 09:22:55 [Error] app/dns: failed to retrieve response > Post "https://8.8.8.8/dns-query": context canceled
2022/06/06 09:23:22 [Error] app/dns: failed to retrieve response > Post "https://8.8.8.8/dns-query": context canceled
2022/06/06 09:23:22 [Error] app/dns: failed to retrieve response > Post "https://8.8.8.8/dns-query": context canceled
2022/06/06 09:23:57 [Error] app/dns: failed to retrieve response > Post "https://8.8.8.8/dns-query": context canceled
2022/06/06 09:23:57 [Error] app/dns: failed to retrieve response > Post "https://8.8.8.8/dns-query": context canceled
2022/06/06 09:24:38 [Error] app/dns: failed to retrieve response > Post "https://8.8.8.8/dns-query": context canceled
2022/06/06 09:24:38 [Error] app/dns: failed to retrieve response > Post "https://8.8.8.8/dns-query": context canceled
2022/06/06 09:25:34 [Error] app/dns: failed to retrieve response > Post "https://8.8.8.8/dns-query": context canceled
2022/06/06 09:25:34 [Error] app/dns: failed to retrieve response > Post "https://8.8.8.8/dns-query": context canceled
```

**Comment by FrankRoc** [comment]
谷歌也经常遇到 请问有没有好点的DNS 配置呢?

**Comment by elliot-bia** [comment]
建议使用自建的dns服务，  例如 dnsmaq之类的

**Comment by Zmingjun** [comment]
> 谷歌也经常遇到请求有没有好点的DNS配置呢？ ![图片](https://user-images.githubusercontent.com/22234082/191904157-f7d67512-ad85-451b-bd13-498d8c77b57e.png)

我也是这个问题，这个问题可能会导致vpn断流或者关闭，不知道你有没有遇到相同的情况，或者有好的解决方法吗

**Comment by haytoo** [comment]
一样的问题，你们解决了吗，怎么解决的呀。
