### ISSUE TITLE
请求 Inbound 部分允许监听多个地址

### ISSUE THREAD

**Issue by unknowndev233** [v2ray/v2ray-core#2288]
我发现在一个 Inbound 里只能监听一个地址
不过这样在一些情况下比较麻烦，例如说：
1. 我需要 0.0.0.0 和 [::] 来监听所有的 IPv4 和 IPv6 地址，但是我只能分别在两个 Inbound 分别监听 v4 与 v6，这样会造成配置文件有一些无意义内容
2. 因为一些需求，我需要在一个 Inbound 上设置需要监听的数个地址，虽然可以增加 Inbound 来达到目的，但是配置文件会变长，并且在未来可能因此难以维护

**Comment by lucifer9** [comment]
1. 大部分情况下，不写 "listen" 或者只写 "listen": "0.0.0.0"，就会同时监听 v4 和 v6 了。至少 Golang 是这么实现的。(https://golang.org/src/net/dial.go?s=9855:9903#L687)
2. 这个可以考虑自己写脚本根据不同端口之类的每次启动时候新生成需要的配置文件？

**Comment by unknowndev233** [comment]
> 1. 大部分情况下，不写 "listen" 或者只写 "listen": "0.0.0.0"，就会同时监听 v4 和 v6 了。至少 Golang 是这么实现的。(https://golang.org/src/net/dial.go?s=9855:9903#L687)
> 2. 这个可以考虑自己写脚本根据不同端口之类的每次启动时候新生成需要的配置文件？

我想监听 127.0.0.1 和 ::1 来进行双栈的 websocket 反代，但是我现在没有一个优雅的解决办法
想过用 localhost 但是 v2ray 不会进行解析

**Comment by lucifer9** [comment]
v2ray 配置里面，啥也不写是同时监听 0.0.0.0 和 ::，其他地址貌似都得写俩
不过你这个问题还真不是 v2ray 的锅。既然你只需要监听本机，那肯定 v2ray 前面还有个 nginx 之类的吧？那你只要反向代理的地址和v2ray监听的地址一致就行啊。比如 nginx 里面 proxy_pass 写 127.0.0.1，v2ray 也监听127.0.0.1 就可以了。再往前客户端或者 cdn 过来是访问 nginx 的，只要 
nginx 是在监听双栈就行了对吧。

**Comment by unknowndev233** [comment]
> v2ray 配置里面，啥也不写是同时监听 0.0.0.0 和 ::，其他地址貌似都得写俩
> 不过你这个问题还真不是 v2ray 的锅。既然你只需要监听本机，那肯定 v2ray 前面还有个 nginx 之类的吧？那你只要反向代理的地址和v2ray监听的地址一致就行啊。比如 nginx 里面 proxy_pass 写 127.0.0.1，v2ray 也监听127.0.0.1 就可以了。再往前客户端或者 cdn 过来是访问 nginx 的，只要
> nginx 是在监听双栈就行了对吧。

v2ray 只监听 127.0.0.1 uhn不会出现双栈问题？

**Comment by lucifer9** [comment]
> > v2ray 配置里面，啥也不写是同时监听 0.0.0.0 和 ::，其他地址貌似都得写俩
> > 不过你这个问题还真不是 v2ray 的锅。既然你只需要监听本机，那肯定 v2ray 前面还有个 nginx 之类的吧？那你只要反向代理的地址和v2ray监听的地址一致就行啊。比如 nginx 里面 proxy_pass 写 127.0.0.1，v2ray 也监听127.0.0.1 就可以了。再往前客户端或者 cdn 过来是访问 nginx 的，只要
> > nginx 是在监听双栈就行了对吧。
> 
> v2ray 只监听 127.0.0.1 不会出现双栈问题？

不会啊，如果你看到问题的话，可以贴 log 来分析一下。

**Comment by unknowndev233** [comment]
> > > v2ray 配置里面，啥也不写是同时监听 0.0.0.0 和 ::，其他地址貌似都得写俩
> > > 不过你这个问题还真不是 v2ray 的锅。既然你只需要监听本机，那肯定 v2ray 前面还有个 nginx 之类的吧？那你只要反向代理的地址和v2ray监听的地址一致就行啊。比如 nginx 里面 proxy_pass 写 127.0.0.1，v2ray 也监听127.0.0.1 就可以了。再往前客户端或者 cdn 过来是访问 nginx 的，只要
> > > nginx 是在监听双栈就行了对吧。
> > 
> > 
> > v2ray 只监听 127.0.0.1 不会出现双栈问题？
> 
> 不会啊，如果你看到问题的话，可以贴 log 来分析一下。

好的

**Comment by unknowndev233** [comment]
> > > v2ray 配置里面，啥也不写是同时监听 0.0.0.0 和 ::，其他地址貌似都得写俩
> > > 不过你这个问题还真不是 v2ray 的锅。既然你只需要监听本机，那肯定 v2ray 前面还有个 nginx 之类的吧？那你只要反向代理的地址和v2ray监听的地址一致就行啊。比如 nginx 里面 proxy_pass 写 127.0.0.1，v2ray 也监听127.0.0.1 就可以了。再往前客户端或者 cdn 过来是访问 nginx 的，只要
> > > nginx 是在监听双栈就行了对吧。
> > 
> > 
> > v2ray 只监听 127.0.0.1 不会出现双栈问题？
> 
> 不会啊，如果你看到问题的话，可以贴 log 来分析一下。

不过感觉这个功能可能在其他地方会有用处

**Comment by wl223600** [comment]
如果你nginx配置写的地址是localhost，而不是127.0.0.1。恰巧v2的监听地址写了127.0.0.1，那么可能会出现少数::1连接失败（服务器nginx会有log，v2不会有），随后使用127.0.0.1继续通讯的情况。对于出站，仍然是依据服务器或客户端域名实际解析情况进行，一般不会有因为nginx配置问题导致客户端上不了ipv6地址的情况。

**Comment by unknowndev233** [comment]
> 如果你nginx配置写的地址是localhost，而不是127.0.0.1。恰巧v2的监听地址写了127.0.0.1，那么可能会出现少数::1连接失败（服务器nginx会有log，v2不会有），随后使用127.0.0.1继续通讯的情况。对于出站，仍然是依据服务器或客户端域名实际解析情况进行，一般不会有因为nginx配置问题导致客户端上不了ipv6地址的情况。

只用 IPv4 交互没问题？

**Comment by unknowndev233** [comment]
> > > v2ray 配置里面，啥也不写是同时监听 0.0.0.0 和 ::，其他地址貌似都得写俩
> > > 不过你这个问题还真不是 v2ray 的锅。既然你只需要监听本机，那肯定 v2ray 前面还有个 nginx 之类的吧？那你只要反向代理的地址和v2ray监听的地址一致就行啊。比如 nginx 里面 proxy_pass 写 127.0.0.1，v2ray 也监听127.0.0.1 就可以了。再往前客户端或者 cdn 过来是访问 nginx 的，只要
> > > nginx 是在监听双栈就行了对吧。
> > 
> > 
> > v2ray 只监听 127.0.0.1 不会出现双栈问题？
> 
> 不会啊，如果你看到问题的话，可以贴 log 来分析一下。

我现在意识到一个问题，这个功能某些情况下对客户端很有用
