### ISSUE TITLE
内置 DNS 加入请求类型 (A/AAAA) 选项，以实现优先请求 IPv6 地址

### ISSUE THREAD

**Issue by S-Tsunemori** [v2ray/v2ray-core#2289]
目前我在配置服务器端 IPv6 优先的时候无奈使用了这种 DNS 配置：

```json
servers: [
  {
    "address": "2001:4860:4860::8888",
    "expectIPs": [ "::/0" ]
  },
  "8.8.8.8"
]
```
因为 Freedom 出口仅支持指定单个 SendThrough，若指定了 IPv6 会导致无法访问 IPv4 网站，故只好设置了两个 Freedom 出口，通过内置 DNS 解析的结果是否为 IPv6 来决定是否路由到对应 IPv6 的出口。

---

4.15 引入 DNS 出站协议之后，客户端内置 DNS 可能接受来自外部的请求。若客户端仅请求了 A 记录，则无法获得 IPv6 地址。若请求的域名是一个仅有 AAAA 记录的域名（如 ipv6.google.com）会导致无法访问（A 记录返回空结果），即使服务端有 IPv6 出口。

希望给内置 DNS 的 ServerObject 新增一个请求类型项，类似这种感觉：

内置 DNS 的 [ServerObject](https://v2ray.com/chapter_02/04_dns.html#serverobject)
```json
{
  "address": "2001:4860:4860::8888",
  "query": "AAAA" 
},
{
  "address": "8.8.8.8",
  "query": "A" 
},
{
  "address": "1.1.1.1",
  "query": "AsIs" 
}
```

设置了 query 项的，当对该服务进行请求时使用指定的请求类型，未设置时默认 "AsIs" 维持原有行为，不进行修改。

这样一来：
1. 不需要先请求两个结果然后再通过 expectIPs 剔除不需要的 IPv4 / IPv6 结果。
2. 即使客户端对仅有 IPv6 的域名请求了 A 记录，只要服务器支持 IPv6 也可以正常访问（不知为何我在 Android 上观察到了这种现象）

**Comment by fbion** [comment]
mark

**Comment by lucifer9** [comment]
不知你服务器什么系统。Linux 的话默认应该就是 ipv6 优先啊，/etc/gai.conf 了解一下？freedom直接AsIs就行了。不放心的话，/etc/resolv.conf 里面加上 options inet6

**Comment by mzz2017** [comment]
> 若客户端仅请求了 A 记录，则无法获得 IPv6 地址。

这种情况仅发生在客户端ipv6被禁用的情况下，如果你想在仅支持ipv4的客户端使用一个支持ipv4/ipv6的代理来访问ipv6的站点，那除非这个代理在有ipv6地址时返回一个fakeip以迫使客户端发出请求。
