### ISSUE TITLE
Panic on FreeBSD 12.1

### ISSUE THREAD

**Issue by ToutyRater** [v2ray/v2ray-core#2302]
Please answer all the questions with enough information. All issues not following this template will be closed immediately.
If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2ray/discussion/issues) first.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
Latest code built by myself https://github.com/v2ray/v2ray-core/commit/9789a946f452ba9b4f003cb82859d517a64cbf76

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
Test transparent proxy.

3) Please attach full panic log.

You may get panic log using command `journalctl -u v2ray` if your system is Linux (systemd).
```
panic: gob: cannot encode nil pointer of type *net.UDPAddr

goroutine 11 [running]:
encoding/gob.(*Encoder).EncodeValue(0xc00009c320, 0xc73da0, 0x0, 0x16, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/encoder.go:223 +0x769
encoding/gob.(*Encoder).Encode(0xc00009c320, 0xc73da0, 0x0, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/encoder.go:176 +0xa4
v2ray.com/core/transport/internet/udp.ReadUDPMsg(0xc00000e658, 0xc000122000, 0x800, 0x800, 0xc0000ce200, 0x100, 0x100, 0xc000067138, 0xc0000e7980, 0xc00004c7b0, ...)
	/root/go/src/v2ray.com/core/transport/internet/udp/hub_freebsd.go:33 +0x11f
v2ray.com/core/transport/internet/udp.(*Hub).start(0xc00000dda0)
	/root/go/src/v2ray.com/core/transport/internet/udp/hub.go:90 +0x1c4
created by v2ray.com/core/transport/internet/udp.ListenUDP
	/root/go/src/v2ray.com/core/transport/internet/udp/hub.go:61 +0x35c
```

4) Please attach your configuration file (**Mask IP addresses before submit this issue**).

```javascript
    // Please attach your configuration here.
{
  "log": {
    "loglevel": "debug"
  },
  "inbounds": [
    {
      "tag": "tproxy-in",
      "port": 12345,
      "protocol": "dokodemo-door",
      "settings": {
        "network": "tcp,udp",
        "followRedirect": true
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "streamSettings": {
        "sockopt": {
          "tcpFastOpen": true,
          "tproxy": "tproxy"
        }
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
      },
      "streamSettings": {
        "sockopt": {
          "mark": 255
        }
      }
    }
  ]
}

```

Please review your issue before submitting.

**Comment by lucifer9** [comment]
"tproxy": "tproxy" 去掉。tproxy 只有 Linux 支持。FreeBSD 下，使用 pf 做为防火墙即可。目前代码并没有支持 ipfw, ipf。

**Comment by ToutyRater** [comment]
I see.
