### ISSUE TITLE
1.23.1版本的问题

### ISSUE THREAD

**Issue by wangyi2005** [v2ray/v2ray-core#231]
SwitchyOmega作为chrome代理
v2ray配置socks5 1080，打开网页时，客户端连续出现
[Warning]Socks: failed to read request: EOF
[Warning]Socks: failed to read request: EOF
[Warning]Socks: failed to read request: EOF

**Comment by v2ray** [comment]
Chrome 有时会创建一个新连接，什么数据都不发就关掉。如果不影响正常使用，这个错误可以忽略。

**Comment by wangyi2005** [comment]
好像是迅雷的问题，卸载迅雷极速版就OK！
