### ISSUE TITLE
使用proxySettings设置前置代理后，WebSocket的传输配置失效。

### ISSUE THREAD

**Issue by zouquan741** [v2ray/v2ray-core#2314]
### 1) 你正在使用哪个版本的 V2Ray？
前后端均为4.22.1。
### 2) 你的使用场景是什么？
Chrome 通过 VMess 代理访问任意网站。
### 3) 你看到的不正常的现象是什么？
ws+tls的配置下，只要设置了proxySettings（前置代理），所有网站都是connection_closed或者empty_response。
服务端、客户端均无报错。
### 4) 你期待看到的正确表现是怎样的？
正常访问。
### 5) 请附上你的配置。
![image](https://user-images.githubusercontent.com/13255981/76011990-7b5df900-5f50-11ea-893d-cc112a9fd51c.png)
### 6) 问题分析。
为了方便观察，去除tls后，分别对有无设置proxySettings两种情况用Wireshark进行抓包。

- 有proxySettings：

![image](https://user-images.githubusercontent.com/13255981/76013407-d133a080-5f52-11ea-80ed-7acf980538f9.png)
发现并没有WebSocket协议，server无法识别直接返回bad request。

- 无proxySettings：

![image](https://user-images.githubusercontent.com/13255981/76013568-122bb500-5f53-11ea-9848-963183fefbea.png)
这个是正常的WebSocket协议。

- 将streamSettings->network改为tcp后，有proxySettings的情况下也能连通了。
- 是否开启tls对结果没有影响，这个我已经验证过了。
- 1090端口的socks代理是使用gost创建的，转发到公司的外网http代理，所以在网卡抓包出现http connect是正常的。（知道最近支持了http outbound，还没测试过直接使用http前置代理会不会有这个问题）

**Comment by fbion** [comment]
"log": {
    "loglevel": "debug",
    "access": "access.log",
    "error": "error.log"
  },

看error.log

**Comment by kingwilliam** [comment]
在v2用proxysettings, 即最少已有2台v2服务器。

ServerA -（TCP）-> ServerB

使用了代理转发 streamSettings 会失效，即只能是非 TLS、无 HTTP 伪装的 TCP 传输协议

出于 [新 V2Ray 白话文指南](https://guide.v2fly.org/advanced/outboundproxy.html#%E9%93%BE%E5%BC%8F%E4%BB%A3%E7%90%86%E8%BD%AC%E5%8F%91)

**Comment by zouquan741** [comment]
> 用白话说 即在v2内用proxysettings 2台v2服务器 serverA和serverB 之间只能用 tcp 不能有tls 不能用其他。
> 
> ServerA -（TCP）-> ServerB
> 
> 使用了代理转发 streamSettings 会失效，即只能是非 TLS、无 HTTP 伪装的 TCP 传输协议
> 
> 出于 [新 V2Ray 白话文指南](https://guide.v2fly.org/advanced/outboundproxy.html#%E9%93%BE%E5%BC%8F%E4%BB%A3%E7%90%86%E8%BD%AC%E5%8F%91)
> 
> 但v2就是灵活度高
> 
> 你可在serverA
> 多inbounds
> Tag: in-direct
> Tag: in-redirect
> 
> Route
> Inboundtag: in-redirect
> Outbound tag: out-serverB
> 
> Outbounds
> Tag: out-serverB
> 
> 这样 ServerA to ServerB 就甚麽也可以
> 但前提是 ServerA 是你自家的

首先并不是streamSettings都会失效，开了tls的情况下抓包看tls是生效的。
其次我并不是两台server，只是为了穿过公司的外网代理。

https://v2ray.com/chapter_02/protocols/http.html
![image](https://user-images.githubusercontent.com/13255981/76045736-ef23f400-5f98-11ea-8954-e30db822923a.png)

从最近支持的http outbound来看，是支持这种用法的。
用redirect当然可以解决问题，但是麻烦，为什么不直接支持前置代理下使用ws？ws也tcp的，并不需要任何修改就能穿过http或者socks前置代理。
