### ISSUE TITLE
DNS 分流问题，expectIPs和domains同时设置，domains限制无效

### ISSUE THREAD

**Issue by LongBlackCock** [v2ray/v2ray-core#2315]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v4.22.1

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
DNS 分流不正确，domain指定 geosite:cn ,但是  pornhub.com 也被解析了

4) 你期待看到的正确表现是怎样的？
pornhub.com 不要被第一个域名服务器解析，直接让第二个服务器解析

客户端配置:

```javascript
 "dns": {
    "servers": [
      {
        "address": "https+local://223.6.6.6/dns-query",
        "domains": [
          "geosite:cn"
        ],
        "expectIPs": [
          "geoip:cn"
        ]
      },
      {
        "address": "https+local://1.1.1.1/dns-query"
      }
    }
```

客户端错误日志:

```javascript

[Info] v2ray.com/core/app/dns: DOHL//223.6.6.6 querying: pornhub.com.
[Info] v2ray.com/core/app/dns: DOHL//223.6.6.6 got answere: pornhub.com. TypeA -> [75.126.124.34] 21.423569ms
[Info] v2ray.com/core/app/dns: failed to lookup ip for domain pornhub.com at server DOHL//223.6.6.6 > expectIPs not match
```

**Comment by RandomCivil** [comment]
pornhub....兄弟是真的nb哈哈

**Comment by fbion** [comment]
{
       "address": "https+local://1.1.1.1/dns-query"
       "domains": [
        "pornhub",
         "geosite:geolocation-!cn",
       ]
     },

**Comment by BlackLongCock** [comment]
@fbion 你好，我想搞清楚的是为何domains限定了geosite:cn，不在其内的pornhub.com却还是被解析了一遍。
要不是后面设置了expectIPs进行了限定，返回的错误IP又刚好不是中国的，否则就出现污染了。

是expectIPs会让domains限定无效化吗？
这是v2ray的设计还是bug？

**Comment by KirbyKFC** [comment]
> domains: [string]
> 一个域名列表，此列表包含的域名，将优先使用此服务器进行查询。域名格式和路由配置中相同。

请熟读文档，domains的作用在于对匹配域名优先使用指定的DNS服务器，而不是限制该DNS只解析匹配的域名。
你所描述的情况，因为ph没有匹配到任何domains，所以按顺序轮询。

**Comment by LongBlackCock** [comment]
@KirbyKFC 原来如此，看来是我读文档的时候理解出现了偏差。

这样的话，我只要调整一下顺序就可以解决问题了。

谢谢你的解释

**Comment by k79e** [comment]
我有点不明白.(很不明白)
为啥调换一下顺序就解决了!!? 这是个怎么回事??
