### ISSUE TITLE
v2ctl自签名根证书无法被chrome信任

### ISSUE THREAD

**Issue by mzz2017** [v2ray/v2ray-core#2318]
### 相关代码
位于`common/protocol/tls/cert`的代码被`v2ctl`所引用，用于生成证书。

### 使用场景

使用v2ray-core以MITM的方式消除SNI，以规避一些站点的SNI封锁，达到无需代理爬墙。

### 问题描述

在使用该根证书自签的证书过程中，chrome出现`NET::ERR_CERT_AUTHORITY_INVALID`问题。
chrome出现上述报错，firefox正常，chromium正常
版本分别为：79.0.3945.88，71.0，80.0.3987.132

使用openssl生成根证书并自签正常。

OS：manjaro

我最开始认为是chrome对证书内容的要求变得严格而导致的不兼容，但查阅资料尝试修复失败。

![image](https://user-images.githubusercontent.com/30586220/76180972-8c319780-61fa-11ea-9df6-8e347a10d535.png)

**Comment by mzz2017** [comment]
好吧，debug了一上午最后发现是需要重启chrome

**Comment by kslr** [comment]
你的manjaro配置显卡了吗

**Comment by mzz2017** [comment]
> 你的manjaro配置显卡了吗

已解决，但我改了点代码以支持更多的证书类型，等下PR。
