### ISSUE TITLE
v2ray不能访问网络

### ISSUE THREAD

**Issue by cyssxt** [v2ray/v2ray-core#2321]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
2.1.0
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
通过v2rayU的vmess代理访问谷歌
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
谷歌访问失败
4) 你期待看到的正确表现是怎样的？
手机端同样配置能访问谷歌
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
客户端配置:
{
"log": {
"error": "",
"loglevel": "info",
"access": ""
},
"inbounds": [
{
"listen": "127.0.0.1",
"protocol": "socks",
"settings": {
"udp": false,
"auth": "noauth"
},
"port": "1081"
},
{
"listen": "127.0.0.1",
"protocol": "http",
"settings": {
"timeout": 360
},
"port": "1088"
}
],
"outbounds": [
{
"mux": {
"enabled": false,
"concurrency": 8
},
"protocol": "vmess",
"streamSettings": {
"wsSettings": {
"path": "/serv",
"headers": {
"host": "us.nettt.xyz"
}
},
"tlsSettings": {
"allowInsecure": true
},
"security": "tls",
"network": "ws"
},
"tag": "proxy",
"settings": {
"vnext": [
{
"address": "us.nettt.xyz",
"users": [
{
"id": "DF074072-2D7A-653A-4FF2-750DB83789A8",
"alterId": 1,
"level": 0,
"security": "aes-128-gcm"
}
],
"port": 443
}
]
}
},
{
"tag": "direct",
"protocol": "freedom",
"settings": {
"domainStrategy": "AsIs",
"redirect": "",
"userLevel": 0
}
},
{
"tag": "block",
"protocol": "blackhole",
"settings": {
"response": {
"type": "none"
}
}
}
],
"dns": {},
"routing": {
"settings": {
"domainStrategy": "AsIs",
"rules": []
}
},
"transport": {}
}

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
rocess outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://us.nettt.xyz/serv):  > dial tcp: lookup us.nettt.xyz on 192.168.3.1:53: read udp 192.168.0.113:60725->192.168.3.1:53: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://us.nettt.xyz/serv):  > dial tcp: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://us.nettt.xyz/serv):  > dial tcp: lookup us.nettt.xyz on 192.168.3.1:53: read udp 192.168.0.113:51958->192.168.3.1:53: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://us.nettt.xyz/serv):  > dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2020/03/10 16:39:13 [Info] [4226428636] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2020/03/10 16:39:13 [Info] [4226428636] v2ray.com/core/transport/internet/websocket: creating connection to tcp:us.nettt.xyz:443
2020/03/10 16:39:14 [Info] [4226428636] v2ray.com/core/transport/internet/websocket: creating connection to tcp:us.nettt.xyz:443
2020/03/10 16:39:14 [Info] [4184944925] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
2020/03/10 16:39:14 [Info] [4184944925] v2ray.com/core/transport/internet/websocket: creating connection to tcp:us.nettt.xyz:443
2020/03/10 16:39:14 [Info] [4226428636] v2ray.com/core/transport/internet/websocket: creating connection to tcp:us.nettt.xyz:443
2020/03/10 16:39:15 [Info] [4184944925] v2ray.com/core/transport/internet/websocket: creating connection to tcp:us.nettt.xyz:443
2020/03/10 16:39:15 [Info] [4184944925] v2ray.com/core/transport/internet/websocket: creating connection to tcp:us.nettt.xyz:443
2020/03/10 16:39:15 [Warning] [4226428636] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://us.nettt.xyz/serv):  > dial tcp: lookup us.nettt.xyz on 192.168.3.1:53: read udp 192.168.0.113:51958->192.168.3.1:53: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://us.nettt.xyz/serv):  > dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2020/03/10 16:39:16 [Warning] [4184944925] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://us.nettt.xyz/serv):  > dial tcp: lookup us.nettt.xyz on 192.168.3.1:53: read udp 192.168.0.113:51958->192.168.3.1:53: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://us.nettt.xyz/serv):  > dial tcp: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://us.nettt.xyz/serv):  > dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by cyssxt** [comment]
这个ip：192.168.3.1:53 如何获取的

**Comment by mzz2017** [comment]
> 这个ip：192.168.3.1:53 如何获取的

这是你网关作为本地DNS了吧，`cat /etc/resolv.conf`

**Comment by cyssxt** [comment]
> cat /etc/resolv.conf

感谢就是这个问题，已经解决
