### ISSUE TITLE
一键脚本安装后curl localhost:10000 报HTTP/1.1 400 Bad Request

### ISSUE THREAD

**Issue by wanghaisheng** [v2ray/v2ray-core#2323]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
4.22.1
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
400
4) 你期待看到的正确表现是怎样的？
200
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
---------- V2Ray 配置信息 -------------

 地址 (Address) = *

 端口 (Port) = 10000

 用户ID (User ID / UUID) = 850194d1-21a8-4058-8ca3-fffffff

 额外ID (Alter Id) = 233

 传输协议 (Network) = ws

 伪装类型 (header type) = none
```

客户端配置:

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
root@docker-s-1vcpu-2gb-sgp1-01:~# cat /var/log/v2ray/error.log
2020/03/11 15:37:56 [Warning] v2ray.com/core: V2Ray 4.22.1 started
2020/03/11 15:43:13 [Warning] v2ray.com/core: V2Ray 4.22.1 started
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

**Comment by kslr** [comment]
如果是我理解的那个400，你可以用nginx反向代理

**Comment by wanghaisheng** [comment]
@kslr 
实际上就是nginx pass给127.0.0.1:10000时 我访问域名报错 我尝试直接在服务器本机访问 v2ray配置文件里监听了127.0.0.1  似乎并没有成功？
```
{
  "inbounds": [
    {
      "port": 10000,
      "listen":"127.0.0.1",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "你的UUID",
            "alterId": 64
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
        "path": "/"
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}
```

**Comment by kslr** [comment]
那你需要在NGINX里面对流量分流，WS转发给V2 HTTP自行处理

**Comment by wanghaisheng** [comment]
@kslr 
ngin 我已经pass设置了，问题是我怎么测试v2 http是否成功可以访问 我目前用curl -i http://127.0.0.1:10000 是报错

**Comment by devinstever** [comment]
这样直接访问报错400是正常的，因为v2ray不是一个web服务器，你用get方式尝试请求当然不行了。
它肯定无法理解你的请求。
