### ISSUE TITLE
v2ray也被GFW检测到了

### ISSUE THREAD

**Issue by yongqingxie** [v2ray/v2ray-core#2325]
![TIM图片20200312123041](https://user-images.githubusercontent.com/24885976/76487417-55a78700-645d-11ea-9589-8f528eb0aee7.jpg)

**Comment by fbion** [comment]
mark
出处？

**Comment by dongqiceo** [comment]
Packet Tracer？这就没有真实性了，如果是公务人员，还是不要泄露机密
