### ISSUE TITLE
请问DOH还能被劫持么

### ISSUE THREAD

**Issue by k79e** [v2ray/v2ray-core#2331]
我一开始是服务器端用的 结果发现用了跟没用一样
服务器端就一个这个
[Info] v2ray.com/core/app/dns: DNS: created Remote DOH client for https://1.1.1.1/dns-query, prer
esolved Dests: [tcp:1.1.1.1:443]
然后就没什么其他信息了 开debug也没用.

然后我换客户端使用了 反正远程解析都一样吧 结果好了有结果了但是测试之后发现dns跟没换一样
 v2ray.com/core/app/dns: DOH//cloudflare-dns.com got answere .....

ipleak之类网站测试发现dns还是aws的. 不对劲把 他不是应该显示的是cloudflare才对么.

我dns就是写的这个位置的
{
  "log": {},
  "api": {},
  "**dns**": {},
  "stats": {},
  "routing": {},
  "policy": {},
  "reverse": {},
  "inbounds": [],
  "outbounds": [],
  "transport": {}
}
应该没问题啊 以前在无劫持的地方用 就是客户端用了dns 然后测试就显示的是对应dns 并没有问题.
现在是被劫持的这个机器 无论用什么doh咋跟没用一个样. 他怎么可能把doh也给透明代理了!??

我有个疑问 我在服务器端开了doh 然后本机v2也走自定义dns
这样服务器端的配置是不是作废了? 那如果在服务器端开那个dns设置有啥用?

**Comment by k79e** [comment]
真是想多了 肯定是机器那边做手脚了

**Comment by k79e** [comment]
不 不是机器被做手脚 是v2ray有bug.
tls还能劫持 证书还正常的 要那样还了得了!!!

**Comment by k79e** [comment]
https://github.com/v2ray/v2ray-core/issues/2332

**Comment by k79e** [comment]
v2自己把自己给"劫持"了

**Comment by k79e** [comment]
这个内置dns是不是服务器上配置了没效果
只有客户端上使用才行?

**Comment by Loyalsoldier** [comment]
不想被"劫持"，就不要在服务端开启 destOverride。因为开启 destOverride 后，DNS 的解析结果只当作路由策略选择的参考，最终发起的连接还是域名连接，所以会有所谓的“DNS 泄漏”，因为这样的话服务器本身设置的 DNS 还需要解析一遍。
