### ISSUE TITLE
DNS远程解析有bug

### ISSUE THREAD

**Issue by k79e** [v2ray/v2ray-core#2332]
测试版本双向用的4.22.0 我认为没必要更新最新版 如果dns请求机制未作修改的话.
况且我也没看见新版提到修复这类问题 只有个什么超时的问题
而且doh还用了跟没用一样https://github.com/v2ray/v2ray-core/issues/2331

现在才反应过来是dns请求是并行的. (在服务器端并行)

服务器测试环境resolv.conf 只有一个119.29.29.29的dns
本机使用远程解析1.2.4.8
查询t.cn之后发现服务器上的确有1.2.4.8的流量(这不是废话么当然我发现路由规则不开的话 或者写的空的routeing 如下所示 dns不起作用)
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [] }
然后把ip写进规则里面 但是这个规则同时包括域名信息. 这样dns也不起作用
      {
        "type": "field",
        "port": null,
        "outboundTag": "direct",
        "ip": "server_IP",
        "domain": [
          "testdomian.addr"
        ]
      }
要写个直连规则 让服务器ip走直连这样dns才起作用 不知道这是不是bug.
//我说的不起作用就是远程dns变成了本机查询 没走远程.

好了 说严重的.
就是1.2.4.8在服务器端流量出现之后 **还要**再走一遍系统默认dns. 这样就是并行查询了. 这属于dns泄露.
比如我用一个无日志的dns服务器 然后v2服务器端还再从系统默认dns那里查询一遍. 这不是多此一举么 而且还会泄露隐私. 
更严重的 如果doh也存在这个问题 doh根本就跟没有用一样. 因为请求是并行的.
doh有没有问题我还没测 不清楚 但是目前看起来是有问题. 因为用了doh之后检测不到dns的更换区别.

2020/03/15 19:06:00 [Info] [959937896] v2ray.com/core/proxy/socks: TCP Connect r
equest to tcp:t.cn:80
2020/03/15 19:06:00 tcp:127.0.0.1:15439 accepted tcp:t.cn:80
2020/03/15 19:06:00 [Debug] v2ray.com/core/app/dns: UDP:**1.2.4.8:53** cache HIT t.c
n -> [xxxxx]
注意这时候已经被缓存 但是请求之后 服务器端依然有流量 就是用的119的地址在查询.
这时候无论请求多少次 服务器就会发起多少个向119那个dns的dns请求.

doh测了 测之前又发现了另一个问题https://github.com/v2ray/v2ray-core/issues/2334
然后测试之后发现 doh也是一样. 都存在并行请求的现象.

**Comment by fbion** [comment]
mark

**Comment by fbion** [comment]
https://github.com/v2ray/discussion/issues/588

**Comment by k79e** [comment]
我的路由用的是**IPIfNonMatch**
和他不一样 他的是asis

**Comment by k79e** [comment]
不对啊 588到底在说什么

**Comment by k79e** [comment]
管它的 还好我发现了bug 这个问题已经存在好多个版本了 但是我一直没反应过来

**Comment by k79e** [comment]
4.22.0客户端+最新版也有复现

**Comment by fbion** [comment]
> 管它的 还好我发现了bug 这个问题已经存在好多个版本了 但是我一直没反应过来
> 但是以为是服务端有dns劫持 透明代理之类的 因为以前用的解析是普通dns.
> 直到用了doh之后我才发现问题的严重性......
> ipleak.net之类的dns测试根本看不出使用前后的变化.
> 这些在线测试还真方便 无需抓包也能看起来dns有没有问题.

我是说v2ray判断一个域名直连还是走国外
要先去解析IP的
再根据ip判断

**Comment by k79e** [comment]
没ip怎么判断啊 你那个域名又不在geosite里面
你就算不用代理 不是还要查dns么

**Comment by fbion** [comment]
放config.json看看

**Comment by k79e** [comment]
现在dns不就一个设置么
  "dns": {
    "servers": [
      "xxxxxx"
    ]
