### ISSUE TITLE
程序初始启动DOH域名解析泄露问题

### ISSUE THREAD

**Issue by k79e** [v2ray/v2ray-core#2334]
![image](https://user-images.githubusercontent.com/6483602/76700348-928bac00-66f1-11ea-8cac-853b3dcee915.png)

就是本机使用doh
2020/03/15 19:15:44 [Debug] v2ray.com/core/app/log: Logger started
2020/03/15 19:15:44 [Info] v2ray.com/core/app/dns: DNS: created **Remote DOH client** for https://i.233py.com/dns-query, preresolved Dests: xxxx

让他走远程查询 模式是doh
然后呢 这个时候程序启动时候会卡稍微一会 然后才出来doh的字样. 为什么呢 有时候多试几次就不卡了.
为什么呢? 因为他在用本机默认dns请求doh

你看 我本机都抓出来了.

这个初始的 给doh服务器的dns解析应该也走远程查询才是 

是我路由表有问题么 我路由表就这一个
      {
        "type": "field",
        "port": null,
        "outboundTag": "direct",
        "ip": [
          "192.168.1.x"
        ],
        "domain": null
      }
走国内地址和域名测试的都是走代理 所以应该我这里配置没问题.

**Comment by fbion** [comment]
mark

**Comment by KirbyKFC** [comment]
没记错的话对doh服务器域名的解析是通过系统DNS进行的，如果想隐藏这条解析你可以改动系统DNS或者设置hosts或者直接使用IP。

**Comment by k79e** [comment]
为什么要用系统dns解析?
我又不是用的local doh 我用的是远程doh.

**Comment by k79e** [comment]
如果你说远程dns也是走本机查询
那doh域名将来被封了 是不是也很大的麻烦?

**Comment by KirbyKFC** [comment]
> preresolved Dests: xxxx

之前就是这样的，DNS服务器初始化的时候会查询IP，然后发起DNS查询也是发到这个IP而不是域名。这个方式确实是存在缺陷的，所以下个release会变成更合理的方式，参见[#2305](https://github.com/v2ray/v2ray-core/pull/2305)。

**Comment by k79e** [comment]
真是太好了 :D

**Comment by early860** [comment]
DOH https remote mode: .... Also, skips routing rules, sending the doh request directly via the default outbound.

限定default outbound不是优雅的方案。一般DOH Server国内外各设一个，使用同一outbound线路不是最优，如有故障更是一起瘫痪。
希望后续能提供DOH的路由选项。
