### ISSUE TITLE
请求DNS over TLS支持

### ISSUE THREAD

**Issue by URARUA** [v2ray/v2ray-core#2335]
如题...DoT在各个方面上来说个人体验优于DoH,且性能方面占一定优势
在某些地方也看到有说实现难度更小...

**Comment by IceCodeNew** [comment]
你是不是在谷歌 hosts 群里，

**Comment by AJsama** [comment]
> 你是不是在谷歌 hosts 群里，

是的，那你大概也知道提出这个申请的原因

**Comment by k79e** [comment]
可能是你的错觉 dot我都不知道怎么建立持久连接
一个查询要建立一次tls 然后查完了就关掉了.
你知道什么保持连接的dot客户端么?

**Comment by okudayukiko** [comment]
昨天發現，在Android平台下，用V2Ray+DNS over TLS看視頻，比不啟用DOT快多了。我用的是日本VPS。可能跨國的網路通訊（訪問DNS 8.8.8.8），用TCP比用UDP更有優勢。
