### ISSUE TITLE
UPLOAD TEST ERROR，ws模式下，如果用作nginx等反代限制网速后，容易出错

### ISSUE THREAD

**Issue by 1265578519** [v2ray/v2ray-core#2340]
UPLOAD TEST ERROR，ws模式下，如果用作nginx等反代限制网速后，容易出错
限速200KB的情况，下行已经跑完很久了，但是V2还在工作，然后speedtest就超时了，帮忙看下是什么问题，是不是v2有什么写入缓冲区导致的？
![2020-03-17_02-25-43](https://user-images.githubusercontent.com/6442439/76788952-dae0c200-67f6-11ea-8602-4c22f4bc1fe1.gif)

**Comment by 1265578519** [comment]
还是说，因为连接的是NGINX，服务器上的v2实际上跑的网速不止2m，然后导致了测速过程v2起码跑了好几十Mbps，然后经过NGINX后，被缓冲在了NGINX的缓冲区里面？然后陆续丢下来到客户端？我猜的。。如果真的是这样的话，有什么好的解决方案吗。

**Comment by k79e** [comment]
https://github.com/v2ray/v2ray-core/issues/1969

**Comment by 1265578519** [comment]
我主要限速就出现这种毛病了

**Comment by zhangjint5** [comment]
wss实际是封装的tcp协议，又不是Web页面，不存在缓冲把！

其二，凭啥判断速度就得以speedtest为基准！我服务器限制仅允许出站访问80/tcp,443/tcp,和53端口，speedtest就卡在2M左右，开启全端口访问就显示正常，实际上我服务器下载浏览速度都很快的！
所以！凭啥判断速度就得以speedtest为基准！
