### ISSUE TITLE
[Discussion]询问速度问题

### ISSUE THREAD

**Issue by peterjtang** [v2ray/v2ray-core#2342]
我分别使用了阿里云、谷哥云、切换了不同的节点（如香港、台湾、新加坡）。
协议是vmiss+WS+TLS
使用了广东移动、联通4G、移动4G。youtube的详细统计，始终最高不超过5000kbps
我试搭了软路由(硬装或虚拟机)都没有效果，看其它人随随便便都有5~10万kbps，苦恼找不到原因。。
{"outbounds":[{"protocol":"vmess","settings":{"vnext":[{"address":"******","port":443,"users":[{"id":"***********","alterId":233,"security":"auto"}]}]},"streamSettings":{"network":"ws","security":"tls","tlsSettings":{"serverName":"****"},"wsSettings":{"path":"/tn2","headers":{"Host":"****"}}},"mux":{"enabled":true}},{"protocol":"freedom","settings":{},"tag":"direct"},{"protocol":"blackhole","settings":{},"tag":"blocked"},{"protocol":"dns","tag":"dns-out"}],"inbounds":[{"port":"1099","protocol":"dokodemo-door","settings":{"network":"tcp,udp","timeout":0,"followRedirect":true},"sniffing":{"enabled":true,"destOverride":["http","tls"]}},{"port":2133,"tag":"dns-in","protocol":"dokodemo-door","settings":{"address":"119.29.29.29","port":53,"timeout":0,"network":"tcp,udp"}},{"port":2333,"protocol":"socks","settings":{"auth":"noauth","udp":true}},{"port":6666,"protocol":"http","settings":{"auth":"noauth","udp":true}}],"dns":{"servers":[{"address":"119.29.29.29","port":53,"domains":["geosite:cn"],"expectIPs":["geoip:cn"]},{"address":"1.1.1.1","port":53,"domains":["geosite:geolocation-!cn"]},"8.8.8.8","localhost"]},"routing":{"domainStrategy":"IPOnDemand","rules":[{"type":"field","inboundTag":["dns-in"],"outboundTag":"dns-out"},{"type":"field","ip":["geoip:private"],"outboundTag":"blocked"},{"type":"field","ip":["geoip:cn"],"outboundTag":"direct"},{"type":"field","domain":["geosite:cn"],"outboundTag":"direct"}]}}

**Comment by forever8938** [comment]
这配置叫人怎么看？

**Comment by peterjtang** [comment]
> 这配置叫人怎么看？

你看需要什么信息，我再发一下。
