### ISSUE TITLE
使用DOH时 空域名不被视为有效记录

### ISSUE THREAD

**Issue by k79e** [v2ray/v2ray-core#2347]
双边都是最新版4.22.1

2020/03/18 19:04:27 [Info] v2ray.com/core/app/dns: DOH//dns.quad9.net querying:
addr_MASK.
2020/03/18 19:04:28 [Info] v2ray.com/core/app/dns: DOH//dns.quad9.net got answer
e: addr_MASK. TypeA -> [] 331.0189ms //我没有删除ip信息 这就是个空域名
2020/03/18 19:04:28 [Info] v2ray.com/core/app/dns: DOH//dns.quad9.net got answer
e: addr_MASK. TypeAAAA -> [] 331.0189ms
2020/03/18 19:04:31 [Info] v2ray.com/core/app/dns: failed to lookup ip for domai
n addr_MASK at server DOH//dns.quad9.net > context deadline exceeded
2020/03/18 19:04:31 [Info] v2ray.com/core/app/router: resolve ip for addr_MASK > v
2ray.com/core/app/dns: returning nil for domain addr_MASK > context deadline excee
ded
注意27秒-31是4秒 所以超时了 虽然0.3秒就收到了记录 下面第二次也一样.
这个第二次是v2自己重试的 我curl配置的--retry 0
2020/03/18 19:04:31 [Info] v2ray.com/core/app/dns: DOH//dns.quad9.net querying:
addr_MASK.
2020/03/18 19:04:32 [Info] v2ray.com/core/app/dns: DOH//dns.quad9.net got answer
e: addr_MASK. TypeAAAA -> [] 327.0187ms
2020/03/18 19:04:32 [Info] v2ray.com/core/app/dns: DOH//dns.quad9.net got answer
e: addr_MASK. TypeA -> [] 327.0187ms
2020/03/18 19:04:35 [Info] v2ray.com/core/app/dns: failed to lookup ip for domai
n addr_MASK at server DOH//dns.quad9.net > context deadline exceeded
2020/03/18 19:04:35 [Info] v2ray.com/core/app/router: resolve ip for addr_MASK > v
2ray.com/core/app/dns: returning nil for domain addr_MASK > context deadline excee
ded
2020/03/18 19:04:35 [Info] [121456475] v2ray.com/core/app/dispatcher: default ro
ute for tcp:addr_MASK:80
2020/03/18 19:04:35 [Info] [121456475] v2ray.com/core/common/mux: dispatching re
quest to tcp:addr_MASK:80

使用浏览器直接访问不存在的域名 或者curl -x socks5h://xxxx --retry 0 域名
然后就复现了.
我不知道这个事情为啥又出现了. 上次不是有个人也提到什么 有a记录和aaaa的一个什么情况?
总之也是个卡4秒超时的. 记不清楚具体是什么了.
对了 是普通dns查询. 我刚才又试了 普通的没问题 是rcode3 被缓存.
这个走了doh之后 又和上次一样 是空域名不被识别.

**Comment by fbion** [comment]
mark

**Comment by mzz2017** [comment]
#2212

**Comment by k79e** [comment]
还是那样啊 我用的上一版的v2ctl 和最新的测试版exe
还是空域名被视为无效然后卡4秒 然后继续请求然后再卡4秒....

**Comment by k79e** [comment]
原来是忘了关请求重试了... 我再看看去
发现还是那样.....
普通查询倒是被缓存 doh还是老样子

**Comment by mzz2017** [comment]
4.23.0还没正式发布，你可以用master分支自己编译




mzz2017
m@mzz.pub




------------------ 原始邮件 ------------------
发件人: k79e <notifications@github.com&gt;
发送时间: 2020年3月22日 23:27
收件人: v2ray/v2ray-core <v2ray-core@noreply.github.com&gt;
抄送: mzz <m@mzz.pub&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[v2ray/v2ray-core] 使用DOH时 空域名不被视为有效记录 (#2347)





 
原来是忘了关请求重试了... 我再看看去
 发现还是那样.....
 普通查询倒是被缓存 doh还是老样子

**Comment by k79e** [comment]
还以为测试版能用了呢......

**Comment by mzz2017** [comment]
我才看到4.23.0已经发布了，这个版本还是有问题吗

**Comment by k79e** [comment]
有啊 我提到的就是测试版的....
我明显看到了doh两次查询 都是带延时的 所以没被缓存... 然后还都分别卡了4秒....

**Comment by mzz2017** [comment]
复现步骤是？

**Comment by k79e** [comment]
用s5远程解析
curl -x socks5h://       --retry 0  

随便一个不存在的域名 复现不了就查t.co的子域名 随便输入个就行

**Comment by k79e** [comment]
任意门刚才也测试了 没有重复查询的情况 但是是有4秒超时....
x 14:12:46 [Info] v2ray.com/core/app/dns: DOH//dns.quad9.net got answer
e: xxxx. TypeA -> [] 693.0396ms
x 14:12:49 [Info] v2ray.com/core/app/dns: failed to lookup ip for domai
n xxxx at server DOH//dns.quad9.net > context deadline exceeded

**Comment by mzz2017** [comment]
我成功复现了这个问题，但在[#2211](https://github.com/v2ray/v2ray-core/tree/d520bc2b569ab3dd4bee7a23539f07fb5fc5696d)是没有问题的，看来是后面的commit又搞炸了

**Comment by mzz2017** [comment]
最新版本手动编译没有问题。
已找到原因，最新的4.23.0的pre release实际上是
```bash
V2Ray 4.22.0 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
```
