### ISSUE TITLE
提议：为mKCP增加fake TCP header

### ISSUE THREAD

**Issue by testcaoy7** [v2ray/v2ray-core#235]
许多运营商有着严格的QoS策略，严重限制了UDP包的发送速度，这使得mKCP的传输速率还不如TCP，却白白浪费了许多流量。为骗过QoS，ShadowVPN曾经使用为UDP包增加fake TCP header的方式，成功骗过了运营商的QoS机制。请问v2ray能否也增加这一功能呢？

**Comment by BenhoNNNN** [comment]
我覺得還好，自從 v1.23+ 用了 SRTP 偽裝，

家中 20Mb 帶寬能跑滿；公司 50 Mb 帶寬也能上 4MB+ 。

**Comment by v2ray** [comment]
如 @BenhoNNNN 所说，你可以试一下 V2Ray 带的 SRTP 伪装。详见：https://www.v2ray.com/chapter_02/05_transport.html

把 UDP 伪装成 TCP 不现实。

**Comment by PterX** [comment]
@v2ray  你好，想请教下header怎么配置，我安装官网的配置提示如下错误。

```
2016/09/30 16:56:08 [Error]KCP|Config: Failed to parse header config: Unknown config ID.
2016/09/30 16:56:08 [Error]Point: Failed to load server config: Point: Failed to parse config: Unknown config ID.
2016/09/30 16:56:08 [Error]Failed to read config file (/dev/shm/config.json): /dev/shm/config.jsonPoint: Failed to parse config: Unknown config ID.
```
这个错误是在加了header之后报出的。

部分配置文件如下
```
  "transport": {
    "tcpSettings": {
      "connectionReuse": true
    },
    "kcpSettings": {
      "congestion": true,
      "mtu":1350,
      "uplinkCapacity": 5,
      "downlinkCapacity": 10,
      "readBufferSize": 1,
      "writeBufferSize": 1,
      "header": {
          "type": "srtp"
      }
    }
  }
```

麻烦解答下疑惑。

**Comment by v2ray** [comment]
客户端和服务器需要同时配置同样的 header

**Comment by wangyu-** [comment]
@testcaoy7 
我有一个用rawsocket把udp伪装成tcp或者icmp的方案，可以骗过udp Qos :
https://github.com/wangyu-/udp2raw-tunnel
