### ISSUE TITLE
能不能多个inbound入口共用一组UUID

### ISSUE THREAD

**Issue by fyhong** [v2ray/v2ray-core#2353]
例如我下面,如果我想开两个端口， 然后设置不同的inbound走不同的出口outbound, 我必须写两组inbound, 有没有办法多个inbound共用一个UUID来实现
我试过在inbounds设置"port": "8080-8084",
然后用以下的路由功能，让8084走us出口，发现在无效的。(估计这个路由功能是指访问外网时的端口)
  "routing": {
    "domainStrategy": "IPOnDemand",
    "strategy": "rules",
    "rules": [
      { "type": "field",
      	"port": [ "8084"	],
       "outboundTag": "us"
      }
    ]
  }

以下是我的inbound设置
{
  "inbounds": [  
  {  
    "tag": "8084", "port": 8084, "protocol": "vmess",
    "settings": {
      "clients": [
{ "id": "1a787916-1045-997b-95c2-f9194f73a705" }
]
    },
    "streamSettings":{ "network":"ws"}
  },

{
    "tag": "8080", "port": 8080, "protocol": "vmess",
    "settings": {
      "clients": [
{ "id": "1a787916-1045-997b-95c2-f9194f73a705" }

]
    },
"streamSettings":{ "network":"ws"}
  },
]
}

**Comment by fyhong** [comment]
能不能在后面的版本路由功能加一个类似"inboundTag"的功能。
"inboundPort":

**Comment by bbhxwl** [comment]
兄弟，好像uuid添加200个以上，程序就无法连接了，知道为什么吗？

**Comment by inmaldrerah-e** [comment]
这是一个软件设计理念问题。我觉得这是不应该做出的改变。V2Ray是一个*模块化的*代理软件，inbounds输入，routing和dns处理数据，outbounds输出，其他模块提供辅助，所以某一个inbound应该将它获取的数据以一个整体的形式交付给routing，然后routing再把数据匹配后交给outbound。这里的两个inbound尽管使用相同的协议，但本身的作用和意义不同，没道理合在一起。
