### ISSUE TITLE
what

### ISSUE THREAD

**Issue by linkea131** [v2ray/v2ray-core#2355]
Installing V2Ray vhttps://api.github.com/repos/v2ray/v2ray-core/releases/22545481 on x86_64
Downloading V2Ray: https://github.com/v2ray/v2ray-core/releases/download/vhttps://api.github.com/repos/v2ray/v2ray-core/releases/22545481/v2ray-linux-64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     63      0 --:--:-- --:--:-- --:--:--    63
[/tmp/v2ray/v2ray.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/v2ray/v2ray.zip or
        /tmp/v2ray/v2ray.zip.zip, and cannot find /tmp/v2ray/v2ray.zip.ZIP, period.
Archive:  /tmp/v2ray/v2ray.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/v2ray/v2ray.zip or
        /tmp/v2ray/v2ray.zip.zip, and cannot find /tmp/v2ray/v2ray.zip.ZIP, period.
Failed to copy V2Ray binary and resources.
[ERROR]  install V2ray failure

**Comment by arshammi** [comment]
Hello.
I have the same problem when I want to unzip v2ray-linux-64.zip

error message:
End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of v2ray-linux-64 or
        v2ray-linux-64.zip, and cannot find v2ray-linux-64.ZIP, period.

How can I solve it?
