### ISSUE TITLE
invalide user 很奇怪的问题,

### ISSUE THREAD

**Issue by wimotek7824** [v2ray/v2ray-core#2356]
同一台windows服务器.  在openwrt连接访问使用都正常

在手机上 或电脑上 客户端v2rayn 就是出现错误 ,  invalid user    查了资料  说是服务器端时间不同步, 但设置了 时间都一样. 还是解决不了问题 . 

![image](https://user-images.githubusercontent.com/62458019/77220013-6ef3b600-6b76-11ea-8645-461584d02c66.png)

**Comment by 1265578519** [comment]
ID对不对

**Comment by wimotek7824** [comment]
> ID对不对

时间, 端口,ID alterID 设置都是对的.   

经过我不断的尝试,  和查找issue.   猜测是伪装类型设置不对引起的.   最后得到证实. 

客户端设置成http伪装.   服务器端没有相关设置.   就会引起这类问题.   

openwrt里虽然也选了http伪装. 但没有设置http host  path参数  可能设置无效果. 所以成功连接. 


以上供大家参考.  网上和帮助里没有说明这种解决方法.

**Comment by wimotek7824** [comment]
rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header

还有客户端提示什么  我现在不记了.   issue里大多数提示时间不对.  实际上有可能是伪装设置不对引起的.

**Comment by 1265578519** [comment]
http伪装需要在服务端中安装nginx，然后反代TCP到v2ray服务端才行，经过一层http，v2ray不知道有没有相关配置可以直接实现
