### ISSUE TITLE
进程被杀

### ISSUE THREAD

**Issue by ToutyRater** [v2ray/v2ray-core#236]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please answer the following questions before submitting your issue. Thank you.

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
1) What version of V2Ray are you using?
    server: v1.23.1, Ubuntu 14.04 x86_64
    client: v1.23.1, Windows 8.1

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
2) What your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
    使用 chrome 通过 VMess 浏览网页及看 YouTube 视频

3) 你看到的不正常的现象是什么？
3) What did you see?
    上网时实然无法联网，排查时发现服务器端 V2Ray 的进程没有了，需要启动 V2Ray。此前，V2Ray 一直正常运行。问题发生前没有对服务器进行过任何操作（今天之内）。错误日志找不到相关日志，且不知如何复现，只在 15 时左右（时区东 8 区）发生了几次。以下是进程被杀前后的部分日志：

> 2016/08/13 14:44:44 [Warning]Freedom: Failed to open connection to tcp:180.153.9.189:53: All retry attempts failed.
2016/08/13 14:45:41 [Warning]Freedom: Failed to open connection to tcp:125.39.208.193:53: All retry attempts failed.
2016/08/13 14:45:41 [Warning]Freedom: Failed to open connection to tcp:183.232.126.141:53: All retry attempts failed.
2016/08/13 14:45:45 [Warning]Freedom: Failed to open connection to tcp:183.232.126.141:53: All retry attempts failed.
2016/08/13 14:45:45 [Warning]Freedom: Failed to open connection to tcp:180.153.9.189:53: All retry attempts failed.
2016/08/13 14:45:45 [Warning]Freedom: Failed to open connection to tcp:125.39.208.193:53: All retry attempts failed.
2016/08/13 14:46:00 [Warning]Freedom: Failed to open connection to tcp:61.135.157.156:53: All retry attempts failed.
2016/08/13 14:46:00 [Warning]Freedom: Failed to open connection to tcp:125.39.240.113:53: All retry attempts failed.
2016/08/13 14:46:05 [Warning]Freedom: Failed to open connection to tcp:61.135.157.156:53: All retry attempts failed.
2016/08/13 14:46:05 [Warning]Freedom: Failed to open connection to tcp:125.39.240.113:53: All retry attempts failed.
2016/08/13 14:49:17 [Warning]Point: started on port 13**
2016/08/13 14:49:45 [Warning]Freedom: Failed to open connection to tcp:xc:80: All retry attempts failed.
2016/08/13 14:53:13 [Warning]Point: started on port 13**
2016/08/13 14:59:14 [Warning]Point: started on port 13**
2016/08/13 15:04:33 [Warning]Point: started on port 13**
2016/08/13 15:04:37 [Warning]Freedom: Failed to open connection to tcp:88.221.81.192:53: All retry attempts failed.
2016/08/13 15:04:41 [Warning]Freedom: Failed to open connection to tcp:88.221.81.192:53: All retry attempts failed.
2016/08/13 15:04:46 [Warning]Freedom: Failed to open connection to tcp:88.221.81.192:53: All retry attempts failed.
2016/08/13 15:04:46 [Warning]Freedom: Failed to open connection to tcp:88.221.81.192:53: All retry attempts failed.

服务器配置：
```javascript
{
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "protocol": "vmess",
    "port": 13**,
    "settings": {
      "clients": [
        {
          "id": "----",
          "level": 1,
          "alterId": 64
        }
      ]
    }, 
   "streamSettings": {
    "network": "tcp"
   }
  },
  "inboundDetour": [
    {
      "protocol": "vmess", 
      "port": 13**,
      "settings": {
        "clients": [ 
          {
            "id": "----",
            "level": 1,
            "alterId": 64 
          }
        ]
      },
      "streamSettings": {
       "network": "kcp"
      }
    },
    {
      "protocol": "shadowsocks",  
      "port": 13**, 
      "settings": {
        "method": "aes-256-cfb", 
        "password": "K8sstl0s", 
        "udp": false    
      }
    }
  ],

  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },


  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  },
  "transport":{
    "tcpSettings": {
      "connectionReuse": true
    },
    "kcpSettings": {
      "mtu": 1450,
      "tti": 10,
      "uplinkCapacity": 20,
      "downlinkCapacity": 100,
      "header": {
        "type": "srtp"
      }
    }
  }
}
```
客户端配置：
```javascript
{
  "port": 8080,
  "log": {
  "access": "",
  "error": "",
  "loglevel": "info"  
  },
  "dns": {
  "servers": [
      "8.8.8.8",
      "208.67.222.222",
	  "8.8.4.4",
	  "localhost"
  ]
  },
  "inbound": {
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "0.0.0.0"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "*.*.*.*",
          "port": 13**,
          "users": [
            {
              "id": "----"
            }
          ]
        }
      ]
    },
	"streamSettings": {
      "network": "kcp"
	}
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
	{
      "protocol": "blackhole",
      "tag": "adblock",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
	  "domainStrategy": "IPIfNonMatch",
      "rules": [
		{
		  "type": "field",
		  "domain": [
			"baidu.com",
			"qq.com",
			"*oneplusbbs.com*",
			"10086.cn"
		  ],
		  "outboundTag": "direct"
		},
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        },
		{
          "type": "field",
          "domain": [
            "msg.71.am",
			"simba.taobao.com",
			"googleadservices.com"
		   ],
          "outboundTag": "adblock"
        }
      ]
    }
  },
   
  "transport": {
    "kcpSettings": {
      "uplinkCapacity": 10,
      "downlinkCapacity": 100,
      "header": {
        "type": "srtp"
      }
    }
  }
}

```

**Comment by v2ray** [comment]
如果系统支持的话，你可以用 `journalctl -u v2ray.service` 看一下退出时的错误信息。

**Comment by ToutyRater** [comment]
试验之后，我的系统不支持。我 Google 了一下发现这是与 Systemd 相关的，我从来没有接触过 Systemd，我不太会用 Linux ，恐怕要花好一段时间来学习 Systemd。要是有发现，再来反馈
