### ISSUE TITLE
"tproxy" cannot work under non root permission! Without any error

### ISSUE THREAD

**Issue by zhangjint5** [v2ray/v2ray-core#2361]
"tproxy" cannot work under non root permission! Without any error

Due to security needs, all my v2ray processes are running under the "nobody" account instead of the root account!

Before the client working in Socks5 mode, there was no problem.

But when you configure "dokodemo-door" today, using "tproxy" mode will never work, and there is no error message. It took 4 hours to find out by accident that it is normal to work the v2ray process under the root account!

This problem does not affect the redirect mode, only the tproxy mode.

It is recommended to check whether this function really requires root permission. If it can't be run in non root, it is recommended to have a prompt for error message!

##########################################

“tproxy”不能在非root权限下工作！没有任何报错信息

出于安全需要，我的所有v2ray进程都在“nobody”帐户下运行，而不是在root帐户下运行！

之前客户机以Socks5模式工作，没有任何问题。

但是，当您今天配置“dokodemo door”时，使用“tproxy”模式将无法工作，并且没有错误消息帮助调试。折腾了4个小时，偶然一次发现在root帐户下运行v2ray进程就工作正常了!

此问题不影响tproxy=redirect模式，仅影响tproxy=tproxy模式。

建议开发人员检查此功能是否确实需要root权限。如果确实不能在非root账号下运行，建议运行时提示错误消息！

**Comment by FH0** [comment]
v2ray可以在非root的情况下使用，但是不能代理1024以下的端口

**Comment by zhangjint5** [comment]
> v2ray可以在非root的情况下使用TPROXY，但是不能代理1024以下的端口

I know that I haven't used port below 1024, and I can see that v2ray is listening to port through netstat!

If the port below 1024 is used under a non root account, the port cannot be monitored successfully!

################################################
这我知道，我没有使用 1024 以下端口，并且通过 netstat 看到v2ray已经在监听端口了！
如果是因为在非root账号下使用1024以下端口，是无法成功监听端口的！

**Comment by lucifer9** [comment]
Linux 系统的话，如果是用systemd的，看下v2ray的service文件是不是有写 `CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE`

**Comment by zhangjint5** [comment]
> y

正解！非常感谢！
结合你的提示下我参考了一下 shadowsocks-libev-redir@.service 文件的 CapabilityBoundingSet 配置项，解决了！
