### ISSUE TITLE
可以增加 Trojan 协议吗？

### ISSUE THREAD

**Issue by tian4546** [v2ray/v2ray-core#2369]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

4) 你期待看到的正确表现是怎样的？

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
```

客户端配置:

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by updater1234** [comment]
#1404

**Comment by alexyangjie** [comment]
我也希望v2ray能支持trojan协议，至少是作为客户端支持(outbound)。近一段时间很多机场的trojan协议开始逐渐流行起来。v2ray的定位是一个platform, 不仅支持其自有协议vmess，还能支持其他比较流行的协议，例如shadowsocks。增加Trojan支持能让v2ray适应不断变化的机场环境，保留现有用户。这和哪个协议好没有关系，只要使用人群越来越多，v2ray都可以考虑加入。

**Comment by depfish** [comment]
+1

**Comment by kslr** [comment]
由于和 Trojan go 授权协议不同，只能重新实现，目前没有人在这上面工作。

也许你们可以试试 VLESS 从设计思想上是一致的。

github-actions[bot] <notifications@github.com> 于 2020年8月27日周四 上午9:31写道：

**Comment by alexyangjie** [comment]
> 由于和 Trojan go 授权协议不同，只能重新实现，目前没有人在这上面工作。 也许你们可以试试 VLESS 从设计思想上是一致的。 github-actions[bot] <notifications@github.com> 于 2020年8月27日周四 上午9:31写道：
> […](#)

太可惜了，不是说trojan有多好，主要是很多机场现在开始用trojan协议，这将大大降低v2ray作为客户端的吸引力。现在只能靠socks出站协议和trojan-go客户端来弥补不足。

**Comment by kslr** [comment]
没办法，基本也是靠兴趣驱动。如果有人愿意做就可以有，没有就没有了。

现在时代在加速发展，不知还会有什么变化。这些方案也只能应对一时，不如向未来看
