### ISSUE TITLE
[Error]V2Ray v1.23+ 作为 PuTTY 代理会报错

### ISSUE THREAD

**Issue by BenhoNNNN** [v2ray/v2ray-core#237]
1) 版本
v1.23.1

2) 使用场景
场景1：HTTP > Server A > GFW > Server 1 > Free
场景2：HTTP > Server B > GFW > Server 2 > Free
场景3：Socks5 > Client > GFW > Server 3 > Free

3) 不正常的现象
PuTTY ERROR :
![2016-08-14](https://cloud.githubusercontent.com/assets/12547424/17645476/af1d2b80-61d9-11e6-9663-e635b1edee71.png)

先说明一下背景，楼主的 ISP 很邪门儿。如果在家用同个 IP 既连接了墙外服务器的 SSH 端口，
又连接过业务端口（以前是 SS，现在是 V2Ray）的话，用不了多久（快则几分钟，慢则几小时），
墙外服务器的 SSH 连接就会被干扰（巨高的延时或直接被 BAN），屡试不爽。

所以升级、维护墙外的服务器，都是在 PuTTY 里设置代理来交叉访问进行的，比如：

维护 Server 1 时，用代理服务器 Server B （出口 Server 2）连过去；
维护 Server 2 时，就用电脑本地 V2Ray 客户端（出口 Server 3）连过去；
维护 Server 3 时，用代理服务器 Server A （出口 Server 1）连过去；
墙内的服务器都直连。

第一次发现这个问题就在前天吧，v1.23 升 v1.23.1 的时候，PuTTY 老断连（如图）。

我在 v1.23 以前都用的是 v1.18 一直都很稳定没啥问题。
升 v1.23 是因为想试试 SRTP 伪装，效果也确实很好（带宽都能跑满）

用了两天看到有个 kcp fix v1.23.1 就准备去升级，第一次发现问题就在升级的时候。

PuTTY 老是报错断线（快则几秒钟，慢则十几秒），因为服务器是 CentOS 6 跑不了脚本，
每次升级都是手动操作——kill 进程、解压替换 v2ray、再跑起 V2Ray。
先前以为是网络问题就没在意，反正操作不复杂，手速快点一台服务器半分钟就能搞定。
每台服务器都因为报错重连了两三次，断断续续也都升级好了，用起来也没问题。

但是刚才，准备再搭台新服务器的时候，又是这个报错。新服务器要配置环境，
不是重连几次，就能勉强操作完的……Google 了下 PuTTY 社区，
按照社区里教程修改了 PuTTY 的设置，但还是不行。

想了下问题可能出在 V2Ray 上。停用 SRTP 伪装、停用 mKCP 都试了，还是不行。

v1.18 及以前的版本用来代理 PuTTY 都没问题，v1.23 才开始出现 PuTTY 报错问题。
v1.18 与 v1.23 中间的版本没用过，不清楚。看了下官方更新日志 v1.19 ~ v1.23，
好像有对网络通信方面的修改，不确定跟这个有没有关。

**Comment by BenhoNNNN** [comment]
solved

**Comment by v2ray** [comment]
是什么问题？

**Comment by BenhoNNNN** [comment]
@v2ray 原因不明，所有客户端与服务端全升到 v1.24.3 ，就没有报错了。
