### ISSUE TITLE
使用非Vmess出站协议时 dns查询失败重试不符路由规则

### ISSUE THREAD

**Issue by k79e** [v2ray/v2ray-core#2371]
比如出站使用s5代理 或者根本不用 就走freedom(例如任意门做dns)
要先开启如下路由 然后设置个s5的出站 s5的就不发了.
然后走curl -x socks5h:// 查询一下不存在的地址或者直接浏览器开个页面也行
//到底是超时还是失败了会触发我也不清楚 目前测试的是失败触发的.

  "routing": {
    "domainStrategy": "**IPIfNonMatch**",
    "rules": [
      {
        "type": "field",
        "port": null,
        "outboundTag": "direct",
        "ip": [
          "geoip:private"
        ],
        "domain": null
      },
      {
        "type": "field",
        "port": null,
        "outboundTag": "direct",
        "ip": [
          "geoip:cn"
        ],
        "domain": null
      },
      {
        "type": "field",
        "port": null,
        "outboundTag": "direct",
        "ip": null,
        "domain": [
          "geosite:cn"
        ]
      }
    ]
  }
}

设置dns 
  "dns": {
    "servers": [
	{#"network":"tcp",
        "address": "https://i.233py.com/dns-query",
	"#port": 53 },
	      {
        "address": "127.0.0.1",
        "port": 53,
        "domains": ["geosite:cn","addrmask.cc","update.googleapis.com","translate.googleapis.com"]
      }  
    ]

这个时候配置了cn域名查询dns B:127.0.0.1 其他域名走dns A (doh)
然后呢 此时查询一个不存在的域名或者存在的域名(查询不存在的域名有利于**重现查询失败**)
我都是查询的不存在的域名

然后他走doh失败之后 会重新使用第二个dns 也就是走国内的那个dns 这样dns流量就泄露了!!!!!
我认为他再怎么重试 也得用**路由指定的dns吧**

**Comment by k79e** [comment]
#2256

**Comment by k79e** [comment]
log
日期 15:25:40 [Info] [794198670] v2ray.com/core/proxy/socks: TCP Connect r
equest to tcp:不存在的域名:80
日期 15:25:40 [Info] v2ray.com/core/app/dns: DOH//i.233py.com querying: 1.
t.co.
日期 15:25:40 [Info] v2ray.com/core/app/dispatcher: default route for tcp:
104.27.164.27:443
日期 15:25:40 [Info] v2ray.com/core/transport/internet/tcp: dialing TCP to
 tcp:127.0.0.1:9051
日期 15:25:40 [Info] v2ray.com/core/app/dispatcher: default route for tcp:
104.27.165.27:443
日期 15:25:40 [Info] v2ray.com/core/transport/internet/tcp: dialing TCP to
 tcp:127.0.0.1:9051
日期 15:25:41 [Info] v2ray.com/core/app/dns: DOH//i.233py.com got answere:
 不存在的域名. TypeAAAA -> [] 1.558007s
日期 15:25:41 [Info] v2ray.com/core/app/proxyman/outbound: failed to proce
ss outbound traffic > v2ray.com/core/proxy/socks: connection ends > context canc
eled
日期 15:25:42 [Info] v2ray.com/core/app/dns: DOH//i.233py.com got answere:
 不存在的域名. TypeA -> [] 2.2014101s
日期 15:25:42 [Info] v2ray.com/core/app/proxyman/outbound: failed to proce
ss outbound traffic > v2ray.com/core/proxy/socks: connection ends > context canc
eled
日期 15:25:44 [Info] v2ray.com/core/app/dns: failed to lookup ip for domai
n 不存在的域名 at server DOH//i.233py.com > context deadline exceeded
日期 15:25:44 [Debug] v2ray.com/core/app/dns: UDP:127.0.0.1:53 querying DN
S for: 不存在的域名.	//使用了第二个dns
日期 15:25:44 [Debug] v2ray.com/core/transport/internet/udp: dispatch requ
est to: udp:127.0.0.1:53
日期 15:25:44 [Info] v2ray.com/core/transport/internet/udp: establishing n
ew connection for udp:127.0.0.1:53
日期 15:25:44 [Debug] v2ray.com/core/transport/internet/udp: dispatch requ
est to: udp:127.0.0.1:53
日期 15:25:44 [Info] v2ray.com/core/app/dispatcher: taking detour [direct]
 for [udp:127.0.0.1:53]
日期 15:25:44 [Info] v2ray.com/core/proxy/freedom: opening connection to u
dp:127.0.0.1:53
日期 15:25:44 [Info] v2ray.com/core/app/dns: UDP:127.0.0.1:53 got answere:
 不存在的域名. TypeAAAA -> [] 193.2006ms
日期 15:25:44 [Debug] v2ray.com/core/app/dns: UDP:127.0.0.1:53 updating IP
 records for domain:不存在的域名.
日期 15:25:44 [Info] v2ray.com/core/app/dns: failed to lookup ip for domai
n 不存在的域名 at server UDP:127.0.0.1:53 > rcode: 3
日期 15:25:44 [Info] v2ray.com/core/app/router: resolve ip for 不存在的域名 > rc
ode: 3
日期 15:25:44 [Info] v2ray.com/core/app/dns: DOH//i.233py.com querying: 1.
t.co.
日期 15:25:44 [Info] v2ray.com/core/app/dispatcher: default route for tcp:
104.27.164.27:443
日期 15:25:44 [Info] v2ray.com/core/transport/internet/tcp: dialing TCP to
 tcp:127.0.0.1:9051
日期 15:25:44 [Info] v2ray.com/core/app/dispatcher: default route for tcp:
104.27.165.27:443
日期 15:25:44 [Info] v2ray.com/core/transport/internet/tcp: dialing TCP to
 tcp:127.0.0.1:9051
日期 15:25:44 [Info] v2ray.com/core/app/dns: UDP:127.0.0.1:53 got answere:
 不存在的域名. TypeA -> [] 389.4015ms
日期 15:25:44 [Debug] v2ray.com/core/app/dns: UDP:127.0.0.1:53 updating IP
 records for domain:不存在的域名.
日期 15:25:45 [Info] v2ray.com/core/app/dns: DOH//i.233py.com got answere:
 不存在的域名. TypeA -> [] 1.3040054s
日期 15:25:45 [Info] v2ray.com/core/app/proxyman/outbound: failed to proce
ss outbound traffic > v2ray.com/core/proxy/socks: connection ends > context canc
eled
日期 15:25:45 [Info] v2ray.com/core/app/dns: DOH//i.233py.com got answere:
 不存在的域名. TypeAAAA -> [] 1.4146066s
日期 15:25:45 [Info] v2ray.com/core/app/proxyman/outbound: failed to proce
ss outbound traffic > v2ray.com/core/proxy/socks: connection ends > context canc
eled
日期 15:25:48 [Info] v2ray.com/core/app/dns: failed to lookup ip for domai
n 不存在的域名 at server DOH//i.233py.com > context deadline exceeded
日期 15:25:48 tcp:127.0.0.1:22261 accepted tcp:不存在的域名:80 [proxy]
日期 15:25:48 [Debug] v2ray.com/core/app/dns: UDP:127.0.0.1:53 cache HIT 1
.t.co -> [] > rcode: 3
日期 15:25:48 [Info] v2ray.com/core/app/dns: failed to lookup ip for domai
n 不存在的域名 at server UDP:127.0.0.1:53 > rcode: 3
日期 15:25:48 [Info] v2ray.com/core/app/router: resolve ip for 不存在的域名 > rc
ode: 3
日期 15:25:48 [Info] [794198670] v2ray.com/core/app/dispatcher: default ro
ute for tcp:不存在的域名:80
日期 15:25:48 [Info] [794198670] v2ray.com/core/transport/internet/tcp: di
aling TCP to tcp:127.0.0.1:9051
日期 15:25:51 [Info] [794198670] v2ray.com/core/app/proxyman/inbound: conn
ection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
日期 15:25:51 [Info] [794198670] v2ray.com/core/app/proxyman/outbound: fai
led to process outbound traffic > v2ray.com/core/proxy/socks: connection ends >
context canceled
日期 15:25:52 [Info] v2ray.com/core/app/proxyman/outbound: failed to proce
ss outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context ca
nceled
日期 15:25:52 [Info] v2ray.com/core/transport/internet/udp: failed to hand
le UDP input > io: read/write on closed pipe

**Comment by KirbyKFC** [comment]
#2315

**Comment by k79e** [comment]
所以我该用expectIPs么?
这个到底能不能和domain之类的一起用呢?

**Comment by k79e** [comment]
我不明白 我用了domain之外加了expectip给那个第二个dns 还是那样.
我关掉了domain然后只开expectip 还是那样... expectip不是限制dns用的么?

我的疑问就是 这域名都是空的 ip就没有 expectip他怎么检测是不是列表里面的! xD

**Comment by k79e** [comment]
所以这就不是bug 目前就没有锁定dns的这个功能啊....
还好下个版本没有空记录识别问题 好歹能缓解下
