### ISSUE TITLE
v4.23.1的多文件配置问题

### ISSUE THREAD

**Issue by yomnxkcs** [v2ray/v2ray-core#2380]
#### 1.使用`-confdir`参数时,环境变量`V2RAY_LOCATION_CONFIG`将失效

例如
```bash
export V2RAY_LOCATION_CONFIG="/path/to/config/"
v2ray -confdir "/dir/to/cfgs"
```
这时v2ray只会读取`cfgs`里面的配置，而不会读取`/path/to/config/config.json`

#### 2.`-confdir`和`-config`的优先级问题
个人认为`-confdir`指定的是相对固定的配置，而`-config`指定的是经常变化的配置。感觉目前的覆盖顺序不太合理，应该反过来用`-config`去覆盖`-confdir`

**Comment by kslr** [comment]
第二个问题是历史遗留
