### ISSUE TITLE
sniffing 导致 https 连接失败

### ISSUE THREAD

**Issue by AlvinZhu** [v2ray/v2ray-core#2383]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
4.23.1
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
操作系统：ArchLinux ，Linux 5.5.11，openssl 1.1.1.e，curl 7.69.1
使用curl访问HTTPS链接
测试命令：
```sh
proxychains curl -4vsSkL https://cbu01.alicdn.com/img/ibank/2019/571/069/13022960175_1961964237.220x220.jpg
```
其中proxychains设置指向v2ray的socks代理。
或者用iptables配置透明代理也可以复现。
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
`curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number`
4) 你期待看到的正确表现是怎样的？
HTTPS正常连接
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
客户端配置:

```javascript
   "inbounds": [
        {
            "port": 1080,
            "tag": "socks-inbound",
            "protocol": "socks",
            "settings": {
                "auth": "noauth",
                "udp": True
            },
            "sniffing": {
                "enabled": True,
                "destOverride": [
                    "http",
                    "tls"
                ]
            }
        }
    ],
    "dns": {
        "servers": [
            "8.8.4.4",
            "8.8.8.8",
            "1.0.0.1",
            "223.5.5.5",
            {
                "address": "114.114.114.114",
                "port": 53,
                "domains": [
                    "geosite:cn"
                ]
            }
        ]
    },
    "routing": {
        "domainStrategy": "IPOnDemand",
        "rules": [
            {
                "type": "field",
                "ip": [ "223.5.5.5", "114.114.114.114"],
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "ip": [ "8.8.4.4", "8.8.8.8", "1.0.0.1"],
                "outboundTag": "proxy"
            },
            {
                "type": "field",
                "outboundTag": "direct",
                "ip": [
                    "geoip:private" 
                ]
            },
            {
                "type": "field",
                "domain": [
                    "geosite:category-ads-all"
                ],
                "outboundTag": "blocked"
            }
        ]
    },
    "outbounds": [
        {
            "tag": "direct",
            "protocol": "freedom",
            "settings": {
                "domainStrategy": "UseIP"
            },
            "streamSettings": {
                "sockopt": {
                    "mark": 255
                }
            }
        },
        {
            "protocol": "blackhole",
            "settings": {
                "response": {
                    "type": "http"
                }
            },
            "tag": "blocked"
        },
         {"protocol": "vmess",
          "tag": "proxy"...}
    ]
```

临时解决方案：
关闭inbounds配置中的sniffing后正常。
当然，上文提供的测试连接不存在DNS劫持问题，可以关闭sniffing来使HTTPS正常连接，如果有DNS劫持，那就不行了。
可能相关的issue: https://github.com/istio/istio/issues/18110

**Comment by kslr** [comment]
你的操作系统和openssl呢

**Comment by AlvinZhu** [comment]
> 你的操作系统和openssl呢

用的是ArchLinux ，Linux 5.5.11，openssl 1.1.1.e，curl 7.69.1

**Comment by KirbyKFC** [comment]
```
{
                "type": "field",
                "domain": [
                    "geosite:category-ads-all"
                ],
                "outboundTag": "blocked"
}

2020/03/29 10:19:55 [Info] [2104164] v2ray.com/core/app/dispatcher: taking detour [block] for [tcp:cbu01.alicdn.com:443]
```

cbu01.alicdn.com在category-ads-all的屏蔽列表里，你需要额外设置cbu01.alicdn.com的路由规则或者在geosite中去除等等。如果你实在觉得它不该被屏蔽，你可以去domain-list-community反馈，但大概率不会被接受。

**Comment by AlvinZhu** [comment]
> ```
> {
>                 "type": "field",
>                 "domain": [
>                     "geosite:category-ads-all"
>                 ],
>                 "outboundTag": "blocked"
> }
> 
> 2020/03/29 10:19:55 [Info] [2104164] v2ray.com/core/app/dispatcher: taking detour [blocked] for [tcp:cbu01.alicdn.com:443]
> ```
> 
> cbu01.alicdn.com在category-ads-all的屏蔽列表里，你需要额外设置cbu01.alicdn.com的路由规则或者在geosite中去除等等。如果你实在觉得它不该被屏蔽，你可以去domain-list-community反馈，但大概率不会被接受。

经过测试确实是这样。谢谢！
