### ISSUE TITLE
请问能否更新下v2ray内置的mtproto

### ISSUE THREAD

**Issue by LordPenguin666** [v2ray/v2ray-core#2384]
TLS版的mtproto出了挺久的了，但是v2这边好像一直都没有更新

**Comment by kslr** [comment]
这得看有没有人愿意做这块工作，如果任何人看到这条消息，都可以随时参与进来

**Comment by e03ccd3df65a2d128247** [comment]
mtproto貌似已经被墙识别

**Comment by e03ccd3df65a2d128247** [comment]
it seems mtproto could be detected by the gfw.

**Comment by zhfish** [comment]
这么容易被检测到的，还是别了吧

**Comment by tutacc** [comment]
fakeTLS暂时不会被检测

**Comment by phlinhng** [comment]
> it seems mtproto could be detected by the gfw.

it was the original mtproto that could be detected, not the latest version of mtproto with "fakeTLS" mode. Although it is called fake TLS  but the  fakeTLS mode actually use real TLS transportation to enveloped telegram stream. [@9seconds/mtg](https://github.com/9seconds/mtg) is a famous implement of fakeTLS mtproto using golang.
