### ISSUE TITLE
没法联网，求帮忙看看

### ISSUE THREAD

**Issue by HuLian21** [v2ray/v2ray-core#239]
WIN10 1037 
客户端服务端均是最新版，核对了端口、地址、ID均没问题，火狐不能上网
配置文件在[https://github.com/RayFantasyStudio/V2Ray-Android](url)客户端上可用
![sp160816_001848](https://cloud.githubusercontent.com/assets/21038789/17671381/5ce43090-6349-11e6-9f42-071959667b27.png)
![sp160816_001910](https://cloud.githubusercontent.com/assets/21038789/17671382/5d1c5a1a-6349-11e6-846f-733be43d9c02.png)

![sp160816_003459](https://cloud.githubusercontent.com/assets/21038789/17671401/6be87312-6349-11e6-96db-0cf08ca2c501.png)

另求shadowrocket上VMASS协议设置方法 比如ID码是否要去横杠

**Comment by HuLian21** [comment]
![sp160816_002106](https://cloud.githubusercontent.com/assets/21038789/17671502/e5de4c46-6349-11e6-9959-cba55a0a5574.png)

**Comment by BenhoNNNN** [comment]
HTTP 协议链接 SOCKS 协议的端口？

**Comment by HuLian21** [comment]
@BenhoNNNN 我觉得不是这个问题吧 
![sp160816_130210](https://cloud.githubusercontent.com/assets/21038789/17688483/37097b3c-63b2-11e6-9864-4703c342826c.png)
问题应该出在验证账号上，等我有空换组UUID试试看

**Comment by jimmyye** [comment]
@HuLian21 正确的配置应该是只设置socks，其他留空。且建议选上“远程dns”。
如果用你的配置，所有http请求都通过http代理走了，并没有走socks。参考：
http://www.thomaszhao.cn/2015/02/03/about-ie-proxy/
https://bugzilla.mozilla.org/show_bug.cgi?id=449251

**Comment by HuLian21** [comment]
@jimmyye 多谢指正

**Comment by v2ray** [comment]
相信已经解决了，没解决的话请 re-open。
