### ISSUE TITLE
請問下TLS設置裏ECC證書的EC PARAMETERS怎麽設置

### ISSUE THREAD

**Issue by wenjinlibug** [v2ray/v2ray-core#2390]
V2ray版本：4.23.1
目前ECC握手不是很正常，程序似乎無法識別Key裏的EC PARAMETERS段。

**Comment by kslr** [comment]
默认改ECDSA256了，其他没有变化

**Comment by k79e** [comment]
很早老版本我做测试用的就是ecc证书 从没发现什么问题.....
