### ISSUE TITLE
如何在v2ray 中使用Socks 协议作为出站object

### ISSUE THREAD

**Issue by tlsalex** [v2ray/v2ray-core#2393]
环境：
有一台centos 系统的VPS，运行着v2ray

A 家庭使用 172.16.0.0/24私有网段，A-pc1 电脑通过ssh的 端口转发功能，向VPS建立了一条动态反向隧道，假设这条反向隧道在VPS上监听了127.0.0.1:2020.

B 家庭使用 172.16.1.0/24私有网段，B-pc1 电脑通过ssh的 端口转发功能，向VPS建立了一条动态反向隧道，假设这条反向隧道在VPS上监听了127.0.0.1:3030.

这时在VPS上的sshd就成为了一个 SOCKS  proxy工具。

这时从我的电脑用ssh 建立了一条正向隧道到VPS上，
假设使用的是 -L 127.0.0.1:4040:127.0.0.1:2020, 那我通过本地的127.0.0.1:4040 就可以访问到A家庭里172.16.0.0/2网段的网络资源了。
假设使用的是 -L 127.0.0.1:5050:127.0.0.1:3030, 那我通过本地的127.0.0.1:5050 就可以访问到B家庭里 172.16.1.0/24网段的网络资源了。

而我希望的是-我只需要建立一条正向隧道，根据目标地址，进行路由，从不同的socket proxy出去。
v2ray里有路由功能，我想借此功能实现需求。

socks 协议放在 inbound 里是没有问题的，但放在outbound的时候，就出问题了，出现了一下提示
main: failed to create server > v2ray.com/core/proxy/socks: 0 target server

不知道这算不算是一个功能的request , 还是说v2ray本来就已经实现了这功能，只是我配置错了

以上假设A B 家的电脑都无法装v2ray, VPS上的v2ray 纯粹作为一个路由器提供路由功能。

**Comment by k79e** [comment]
https://www.v2ray.com/chapter_02/protocols/socks.html

**Comment by tlsalex** [comment]
Hey man, thanks so much, it the method work quite well in my case.
Thank you again.

**Comment by wjsw1781** [comment]
我这里无法打开这个页面 能否告诉我下怎么配置?
