### ISSUE TITLE
About :bash <(curl -L -s https://install.direct/go.sh)

### ISSUE THREAD

**Issue by ntgeralt** [v2ray/v2ray-core#2397]
Hello, I'd like to suggest a few problems with your official one-click script:
1·Using tar seems better than zip/unzip.
2·Some environment do not have bash.only support curl https.

bash <(curl -L -s https://install.direct/go.sh)
curl https://install.direct/go.sh | sudo bash

**Comment by dctxmei** [comment]
Hello ntgeralt.

The reason for this script to use zip/unzip is that currently the released content of V2Ray is still in zip format.

The way the script is executed is independent of the content of the script itself.

**Comment by ntgeralt** [comment]
Since I tried to run the V2Ray official code on BSD system, I found it would not work.But the precompiled files work fine.
Thank you for your reply.

**Comment by dctxmei** [comment]
> Since I tried to run the V2Ray official code on BSD system, I found it would not work.But the precompiled files work fine.
> Thank you for your reply.

Here is a Bash script written for OpenBSD:
https://github.com/v2fly/openbsd-install-v2ray
