### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by t3573393** [v2ray/v2ray-core#24]
希望有如下的实现建议：
1. 采用 peer to peer 的实现， 不需要有固定的服务器和客户端
2. 中心的地址服务器采用 邮件或者是 不容易屏蔽的文件系统进行管理， 或者是网盘
3. 地址互相复制的原则， 去中心化，自动多点备份地址
4. 加密算法的实现，和平台无关， 为脚本或者是库自带的
5. 管理工具使用网页，不需要开发客户端程序，启动之后自动打开浏览器管理页面
6. 参考lantern的实现， 最好是做成脚本级别的，文件小，方便找

**Comment by v2ray** [comment]
1 / 2 / 3: V2Ray 是有计划做成集群模式，可以由一台控制机进行统一调配，但具体的部署还得看用户的财力，像 lantern 那样免费又多服务器的方式，没有强大的资金支持是做不出来的。
4: 已经是这样的了
5: 很好的建议，会采纳的
6: 不明白什么意思

**Comment by t3573393** [comment]
6 的意思是 做成宿主程序的模式， 所以来的库 或者是 运行环境 不能被墙， 需要运行的核心逻辑代码（经常改的-也就是说更新需要改变的地方）使用脚本，而且文件小的， 方便传播。

**Comment by v2ray** [comment]
Closing as inactivity for more than 7 days.
