### ISSUE TITLE
功能建议：加入自启动和后台运行

### ISSUE THREAD

**Issue by lewisec** [v2ray/v2ray-core#240]
目前用第三方客户端实现开机自启动和后台运行，但是卡巴斯基10会报毒。
可否考虑把这个做到软件里，实现成基础功能？谢谢。

**Comment by BenhoNNNN** [comment]
加个计划任务最简单

**Comment by laosb** [comment]
这个东西实在不应该是v2ray完成的。各操作系统都有自己的一套实现，很容易的。

**Comment by v2ray** [comment]
这个功能会由其它的客户端完成，v2ray-core 将不提供此类功能。简单的做法可以如上所述写一个脚本，比如 Linux 版就有一个脚本用于安装服务。
