### ISSUE TITLE
[BUG] [严重] Http客户端入站时 DNS查询问题

### ISSUE THREAD

**Issue by k79e** [v2ray/v2ray-core#2400]
如果不设定dns **默认使用系统dns**查询dns.
HTTP协议是不需要先查询dns再连接的.
他host里面直接有host还查询个什么哦. 这个行为是多此一举的.
http默认就是远程查询的. 所以这个应该修复下吧.

所以正确行为应该是 不设定dns的情况下 http入站代理接到请求 不查询dns直接就发请求才是.
如果设定了dns 就去查询相应的dns.

这情况应该属于http vmess之间转换出了问题. (应该是行为不规范)
我想了想就更不对劲了 既然是vmess 他就支持远程解析. 
~所以如果是http入站+vmess出站 即使配置了dns设定 远程解析应该也不允许走本地是吧.~ (又测了下发现远程查询没问题 只有不设定dns的时候有问题)
程序识别下http里面的头部 然后传递给vmess不就行了. 又不是http入+freedom或者其他协议出.
我提到的这情况是vmess出战协议下的事情哇!!! 所以这问题好像更严重了!! 太可怕了太可怕了太可怕了 这不是愚人节!!!!

所以应该是http入 vmess出
客户端不配置dns 应该服务端用机器的系统配置dns来查询.
客户端配置的 服务端走对应的远程查询

http入 其他协议出 那就得视情况而定了
h入h出的 默认就不管dns 由http服务端自己解析去 除非客户端指定dns 那样由客户端自己连接去.

h入 s5出的 s5没法指定远程解析随意用dns 但是可以配置远程解析 这样跟dns又没什么关系了!!? 不清楚目前是咋样处理的. 好像也没什么开关

**Comment by k79e** [comment]
杂项
于是我配置了无效dns 程序进行了查询 当然也失败了
然后卡了一会 网络还是能接通 数据还是正常传输. 所以是多了一步无必要的查询. (因为不配置的时候还是会乱查)

**Comment by KirbyKFC** [comment]
http入站和vmess出站并没有你描述的会查询DNS的问题，能附上相关的配置和日志吗？

**Comment by k79e** [comment]
你确定你抓了流量么?
date:29 [Info] [1618153925] v2ray.com/core/proxy/http: **request** to Me
thod [GET] Host [133-addrmask] with URL [http://133-addrmask/]
date:29 127.0.0.1:57028 accepted http://133-addrmask/ [proxy]
date:29 [Info] [1618153925] v2ray.com/core/app/dispatcher: default r
oute for tcp:133-addrmask:80
date:29 [Info] [1618153925] v2ray.com/core/common/mux: dispatching r
equest to tcp:133-addrmask:80
date:29 [Info] v2ray.com/core/transport/internet/websocket: creating
 connection to tcp:srvaddr:443
date:36 [Info] v2ray.com/core/proxy/vmess/outbound: tunneling reques
t to tcp:v1.mux.cool:9527 via tcp:srvaddr:443
date:38 [Warning] [1618153925] v2ray.com/core/app/proxyman/inbound:
connection ends > v2ray.com/core/proxy/http: connection ends > v2ray.com/core/pr
oxy/http: failed to write response > write tcp 127.0.0.1:localport->127.0.0.1:57028:
wsasend: An existing connection was forcibly closed by the remote host.
date:38 [Info] [1618153925] v2ray.com/core/common/mux: failed to fet
ch all input > io: read/write on closed pipe
date:38 [Info] v2ray.com/core/common/mux: failed to write to downstr
eam. closing session 1 > io: read/write on closed pipe
date:45 [Info] v2ray.com/core/common/mux: failed to read metadata >
io: read/write on closed pipe
date:45 [Info] failed to handler mux client connection > v2ray.com/c
ore/proxy/vmess/outbound: connection ends > websocket: close 1000 (normal)

![image](https://user-images.githubusercontent.com/6483602/78167364-eed82500-7480-11ea-9a4c-ebc7523b35dc.png)
日志上面是**看不到什么的**

{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "debug"
  },
  "inbounds": [
    {
      "port": 1234,
      "listen": "127.0.0.1",
      "protocol": "http",
      "sniffing": {
        "enabled": false,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": false,
        "ip": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
......
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": true,
          "serverName": "servaddr.mask"
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/mask",
          "headers": {
            "Host": "serv"
          }
        },
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "dns": {
    "servers": [
      "1.2.3.4"
    ]
  },
"transport": {
  "sockopt": {
    "mark": 0,
    "tcpFastOpen": false,
    "tproxy": "off"
  }
},
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
	      {        "type": "field",
		"inboundTag": "dns-in",
        "outboundTag": "dns-out"
      },
      {
        "type": "field",
        "port": null,
        "outboundTag": "direct",
        "ip": null,
        "domain": [
          "addrmask.cc"
        ]
      },
      {
        "type": "field",
        "port": null,
        "outboundTag": "direct",
        "ip": [
          "geoip:private"
        ],
        "domain": null
      },
      {
        "type": "field",
        "port": null,
        "outboundTag": "direct",
        "ip": [
          "geoip:cn"
        ],
        "domain": null
      },
      {
        "type": "field",
        "port": null,
        "outboundTag": "direct",
        "ip": null,
        "domain": [
          "geosite:cn"
        ]
      }
    ]
  }
}

**Comment by KirbyKFC** [comment]
你的DNS流量记录不足以证明这个DNS查询来自http入站或vmess出站，因为你的配置启用了额外的DNS查询。

**Comment by k79e** [comment]
不是 配置里面写的有dns 测试时候是关闭dns的.(你可以看日志 里面没有dns查询信息)
而且现在发现http入站+http出站的时候 也是会查系统dns 这个完全没必要.

**Comment by k79e** [comment]
不配置远程dns查询 s5和http入站都会 查本机dns 这个正常不?

**Comment by KirbyKFC** [comment]
我指的不是DNS配置本身而是会用到DNS的配置。

我建议你阅读文档了解一下v2ray的路由策略中IPIfNonMatch的意义。

https://v2ray.com/chapter_02/03_routing.html

在你日志和配置体现的场景中，133-addrmask走了默认路由，代表没有匹配到任何规则，所以必定经过一次dns查询。

**Comment by k79e** [comment]
所以开了路由如果不设定dns他就只走本地了哇!!!!

**Comment by k79e** [comment]
这个IPOnDemand到底是啥意思啊 前一个是域名里面的ip不匹配然后就解析
那这个是啥意思 他要是遇见了域名会咋办? 他是一切都解析一遍的意思么?

**Comment by KirbyKFC** [comment]
IPIfNonMatch是用域名匹配不到后才解析成IP，用IP再匹配一遍。
IPOnDemand根据文档的描述是匹配碰到有IP的规则时会直接解析成IP进行匹配，但我好像在哪里见到过说IPOnDemand会在路由匹配开始时就先解析出IP。我因为不用这种策略所以不是很关心，你可以通过在纯域名规则下使用IPOnDemand验证解析域名的时机。

**Comment by k79e** [comment]
找到区别了 第三个模式是 不管国内外 都一律走远程解析.
第二个是 如果有国内的 路由未配置分流 只有一个地址的话 默认用本地dns解析国内域名.

**Comment by ttimasdf** [comment]
一堆json还不用code block括起来……让别人怎么看
