### ISSUE TITLE
release的v2rayN和v2rayN-Core无法下载，请问哪里可以下版本啊

### ISSUE THREAD

**Issue by Xiao-tangyuan** [v2ray/v2ray-core#2406]
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

此 Issue 会被立即关闭。

If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2ray/discussion/issues) first.

This issue will be closed immediately.

**Comment by kslr** [comment]
https://github.com/2dust/v2rayN/releases

**Comment by Xiao-tangyuan** [comment]
我能请教一下这个地址下的软件，一直无法下载是为什么呢？另存为之后，进度条不动，过好久提示无法下载，自动终止

**Comment by kslr** [comment]
https://tmp.link/f/5e86be6667b4c
https://tmp.link/f/5e86be6f1cb11
