### ISSUE TITLE
关于配置的疑惑

### ISSUE THREAD

**Issue by ToutyRater** [v2ray/v2ray-core#241]
发现配置可以有两种，一种是
```javascript
{
  "port": xxxx,
  "inbound"{},
  ......
}
```
另一种是
```javascript
{
  "inbound"{
    "port": xxxx,
    ......
  },
  ......
}
```
试过两种写法都可以正常使用，但我看了 v1.11 之后的 releases，发现在 v1.14 之前的配置文件用的都是第一种，而从 v1.15 开始配置的格式就变成了第二种，是不是意味着现在推荐的格式是第二种？更甚者将来可能取消对第一种格式的支持？

**Comment by v2ray** [comment]
现在的推荐配置是第二种，将来会取消对第一种的支持。

**Comment by ToutyRater** [comment]
了解了
