### ISSUE TITLE
Hope add speed limit and device number limit🤞

### ISSUE THREAD

**Issue by ghost** [v2ray/v2ray-core#2411]
Hello every project V authors, I am able to more proples can understand my issue,so i use two languages to write this issue,but my english level is not well,sorry.
  译：Project V 的所有开发者们，你们好，为了更多的人能阅读我的issue，所以我使用两种语言来写这个issue，但是很抱歉我的英语水平不是很好。

 I don't know how many peoples have this requirement,but you know the best proxy server like Bandwagon CN2-GIA is very expensive. I want the high speed,but the follow is to much for myself.So some times I want buy a server with my friend.But you konw ,they may lend the server to other people,I can't control their shares. So I think this feature is very important.
  译：我不知道有多少人有这个需求，但是你们应该了解过，高质量的代理服务器，例如搬瓦工的CN2-GIA的服务器是非常昂贵的。我想体验服务器的高速度，但是那些流量对我一个人使用而言又太多，所以有时候想和朋友一起合租服务器使用。但是他们有可能将服务器借给其他人使用，我不能控制他们的分享。所以我认为这个需求非常重要。

  I hope the project V can add the speed limit and device number limit,then we can brow the server to other people.Thanks for all your very good project.
  译：我希望Project V 可以加入速度限制和设备数量限制的相关功能，这样我们就可以将我们的服务器借给其他人使用了。非常感谢你们贡献的非常好的项目。😘

**Comment by jimmygiven** [comment]
https://github.com/v2ray/v2ray-core/issues/1514

**Comment by tedjsmeng** [comment]
Same
跟同事分享很贵的服务器，总有少数人对“公共物品”的使用好不怜惜，一下就把流量吃完了，特别希望有分配流量配额到账户的功能

**Comment by amColinzzz** [comment]
> Same
> 跟同事分享很贵的服务器，总有少数人对“公共物品”的使用好不怜惜，一下就把流量吃完了，特别希望有分配流量配额到账户的功能

是的，我也是基于此想法，但是第三方各种面板，都支持不了，除非v2ray原生支持。

**Comment by liberal-boy** [comment]
> Same
> 跟同事分享很贵的服务器，总有少数人对“公共物品”的使用好不怜惜，一下就把流量吃完了，特别希望有分配流量配额到账户的功能

流量配额可以记录每个用户使用的流量，达到配额删除用户就可以了。这个目前的api就可以实现。

**Comment by tedjsmeng** [comment]
但目前的v2ctl api不支持统计ws的流量啊…

**Comment by amColinzzz** [comment]
> 但目前的v2ctl api不支持统计ws的流量啊…

好像支持吧。

**Comment by liberal-boy** [comment]
> 但目前的v2ctl api不支持统计ws的流量啊…

只要代理协议是 ss 或者 vmess 都可以统计，与底层传输协议无关。

**Comment by tedjsmeng** [comment]
进度更新——如何查用户流量？
https://gist.github.com/eycorsican/aa8cdc1d39c3fa355c499f89a15b9753
原来要开启很多参数才能查询，只开policy是不够的

**Comment by hikaruchang** [comment]
>https://github.com/v2ray/v2ray-core/issues/1514
我在这个issue有回复。

正在尝试加入限速Rate（https://github.com/hikaruchang/v2ray-core/blob/1f9f11f9929b45215053c661166e7d791bdc35f5/app/dispatcher/rate.go），至于限制终端数，首先得对“设备”做定义，到底是session，还是按设备（如上报mac地址）计算。
