### ISSUE TITLE
tproxy的一些问题

### ISSUE THREAD

**Issue by zhfish** [v2ray/v2ray-core#2413]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
4.23.1
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
透明转发 youtube, netflix
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
tproxy 经常超时， redirect通畅无比
4) 你期待看到的正确表现是怎样的？
主要看视频，tcp转发
tproxy是内核支持，理论上应该比redirect效率高些？
udp没测试过
提个issue，看看有没有同学情况一样？ 
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
```
https://guide.v2fly.org/app/transparent_proxy.html
https://guide.v2fly.org/app/tproxy.html
```
这里的标准配置

**Comment by dctxmei** [comment]
這裡的「经常超时」，是指完全不可用，還是間斷性不可用？

**Comment by zhfish** [comment]
连接开始时超时严重，重试几次开始有流量，因为是看视频，一个连接成功转发，可以保持几十分钟，但高峰速度不及redirect的1/3

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："Dct Mei "<notifications@github.com&gt;;
发送时间：2020年4月6日(星期一) 凌晨1:10
收件人："v2ray/v2ray-core" <v2ray-core@noreply.github.com&gt;;
抄送："zhfish "<wangchen@zhfish.net&gt;;"Author "<author@noreply.github.com&gt;;
主题：Re: [v2ray/v2ray-core] tproxy的一些问题 (#2413)
-----------------------------------

 

 
這裡的「经常超时」，是指完全不可用，還是間斷性不可用？

**Comment by dctxmei** [comment]
僅僅是 v4.23.1 出現這個問題麼？請確認一下是否類似於 #2402 的情況。

**Comment by zhfish** [comment]
我是3月份的版本开始用的透明代理

并没注意cpu和内存的情况，我去看一下
