### ISSUE TITLE
V2Ray的TLS能否支持加载DH Param文件？

### ISSUE THREAD

**Issue by okudayukiko** [v2ray/v2ray-core#2414]
Please describe the new feature you want in detail.
V2Ray的TLS加载DH Param文件，可以增强TLS的安全性。最近折腾某VPN得到的灵感。
https://www.v2ray.com/en/configuration/transport.html#tlsobject

**Comment by okudayukiko** [comment]
经测试VMESS+TLS（没有DH PARAM）速度比VMESS+TLS（有DH PARAM）慢。

**Comment by kdrx** [comment]
@okudayukiko

**Comment by okudayukiko** [comment]
> @okudayukiko
> 能否贴出tls with dh param的配置？

用V2Ray+Nginx或V2Ray+Stunnel

**Comment by kdrx** [comment]
> > @okudayukiko
> > 能否贴出tls with dh param的配置？
> 
> 用V2Ray+Nginx或V2Ray+Stunnel

我用haproxy也实现了，多谢分享。

**Comment by Joker0086** [comment]
完全前向保密在 TLSv1.2 之前是可选的，但它不是 TLSv1.3 的可选项，因为所有 TLSv1.3 密码套件都使用 ECDHE。

**Comment by liberal-boy** [comment]
golang 标准库的 tls 实现是在每次握手时生成 ECDHE Parameters。v2ray 默认选用的都是支持 前向安全的握手方法，目前可以认为不存在安全问题。

**Comment by okudayukiko** [comment]
> golang 标准库的 tls 实现是在每次握手时生成 ECDHE Parameters。v2ray 默认选用的都是支持 前向安全的握手方法，目前可以认为不存在安全问题。

Nginx虽然是X25519密钥交换，但V2+Nginx加载dhparam后明显比不加载dhparam快。Nginx的`ssl_certificate`和V2的`certificateFile`似乎只加载`-----BEGIN CERTIFICATE-----`和`-----END CERTIFICATE-----`段落，直接使用`openssl dhparam 2048 >> v2ray.crt`不加载证书里的DH Paramters（`----- BEGIN DH PARAMTERS-----`和`-----END DH PARAMTERS-----）。

**Comment by liberal-boy** [comment]
> > golang 标准库的 tls 实现是在每次握手时生成 ECDHE Parameters。v2ray 默认选用的都是支持 前向安全的握手方法，目前可以认为不存在安全问题。
> 
> V2Ray+Nginx加载dhparam后比不加载dhparam快速、稳定。Nginx的`ssl_certificate`和V2Ray的`certificateFile`似乎只加载`-----BEGIN CERTIFICATE-----`和`-----END CERTIFICATE-----`段落，使用`openssl dhparam 2048 >> v2ray.crt`不会加载证书里的DH Paramters（`----- BEGIN DH PARAMTERS-----`和`-----END DH PARAMTERS-----`）。
> V2Ray+Nginx加载dhparam后比V2Ray自带TLS稳定。

1. 握手时生成 ECDHE Parameters 和预生成相比应该是不会有安全性上的区别，如果有相关的技术文章请提供给我们参考。
2. golang 的 TLS 标准库不提供指定 ECDHE Parameters 的方法，如果你希望 V2Ray 支持指定，请先给 golang 发起 issue。

**Comment by liberal-boy** [comment]
dhparam 是一个`安全质数`，dhe 才需要安全质数，而 ecdhe 是不需要安全质数的，golang 支持 ecdhe 而不支持 dhe，所以当然是不需要指定 dhparam。ecdhe 时 dhe 的圆锥曲线加强版本，安全性公认是 ecdhe 比 dhe 强，可能 ecdhe 更消耗资源，但是我不知道你认为的`不够安全`有什么理由。

**Comment by okudayukiko** [comment]
> dhparam 是一个`安全质数`，dhe 才需要安全质数，而 ecdhe 是不需要安全质数的，ecdhe 是 dhe 的圆锥曲线加强版本，使用圆锥椭圆曲线参数替代安全质数。golang 支持 ecdhe 而不支持 dhe，所以当然是不需要指定 dhparam。安全性公认是 ecdhe 比 dhe 强，我不知道你认为的`指定 dhparam 更安全`有什么理由。

我只发现V2+Nginx和ocserv用了dhparam后，速度和稳定性快很多。现在都是用ECDHE。

**Comment by okudayukiko** [comment]
> dhparam 是一个`安全质数`，dhe 才需要安全质数，而 ecdhe 是不需要安全质数的，ecdhe 是 dhe 的圆锥曲线加强版本，使用圆锥椭圆曲线参数替代安全质数。golang 支持 ecdhe 而不支持 dhe，所以当然是不需要指定 dhparam。安全性公认是 ecdhe 比 dhe 强，我不知道你认为的`指定 dhparam 更安全`有什么理由。

原因应该是Nginx+V2Ray没有禁用DH和DHE，所以才会出现加载`dhparam`后快速和稳定的现象。至于Nginx+V2Ray比V2Ray TLS快速，可能因为V2Ray使用了AES-256-GCM，而我手动修改Nginx配置使用AES-128-GCM。

**Comment by liberal-boy** [comment]
> > dhparam 是一个`安全质数`，dhe 才需要安全质数，而 ecdhe 是不需要安全质数的，ecdhe 是 dhe 的圆锥曲线加强版本，使用圆锥椭圆曲线参数替代安全质数。golang 支持 ecdhe 而不支持 dhe，所以当然是不需要指定 dhparam。安全性公认是 ecdhe 比 dhe 强，我不知道你认为的`指定 dhparam 更安全`有什么理由。
> 
> 原因应该是Nginx+V2Ray没有禁用DH和DHE，所以才会出现加载`dhparam`后快速和稳定的现象。至于Nginx+V2Ray比V2Ray TLS快速，可能因为V2Ray使用了AES-256-GCM，而我手动修改Nginx配置使用AES-128-GCM。

对于 x86/amd64 加解密性能通常不是瓶颈，而且 V2Ray 在 tls12 第一顺位的加密套件是 `TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305`， 在 tls13 是 `TLS_AES_128_GCM_SHA256`。

**Comment by okudayukiko** [comment]
> > > dhparam 是一个`安全质数`，dhe 才需要安全质数，而 ecdhe 是不需要安全质数的，ecdhe 是 dhe 的圆锥曲线加强版本，使用圆锥椭圆曲线参数替代安全质数。golang 支持 ecdhe 而不支持 dhe，所以当然是不需要指定 dhparam。安全性公认是 ecdhe 比 dhe 强，我不知道你认为的`指定 dhparam 更安全`有什么理由。
> > 
> > 
> > 原因应该是Nginx+V2Ray没有禁用DH和DHE，所以才会出现加载`dhparam`后快速和稳定的现象。至于Nginx+V2Ray比V2Ray TLS快速，可能因为V2Ray使用了AES-256-GCM，而我手动修改Nginx配置使用AES-128-GCM。
> 
> 对于 x86/amd64 加解密性能通常不是瓶颈，而且 V2Ray 在 tls12 第一顺位的加密套件是 `TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305`， 在 tls13 是 `TLS_AES_128_GCM_SHA256`。

V2Ray TLS比V2Ray+Nginx慢得多。抓包也没看到什么线索。

**Comment by liberal-boy** [comment]
@okudayukiko v2ray 的 tls 是 go 标准库的实现，如果你认为实现有问题应该向 golang 而不是 v2ray 提出。关于关闭 tls11 和部分加密套件可能不安全的问题建议开新 issue 讨论。
