### ISSUE TITLE
路由器的V2ray无法升级了，提示这边/download/页面404

### ISSUE THREAD

**Issue by ymcoming** [v2ray/v2ray-core#2424]
问题如下，确实https://github.com/v2ray/v2ray-core/releases/download/这个页面显示404了，但以前都能正常升级，是页面有改动吗？

--------------------------------------------------------------------------------------
【09:00:43】: 开始检查 v2ray 最新版本。。。
【09:00:44】: 当前版本：v4.21.3
【09:00:44】: 最新版本：### Fix\r\n* TLS Default Use ECDSA256\r\n* Config Priority https://github.com/v2ray/v2ray-core/commit/ab616d91ae32ffeb8167822dfb022c596fe5aecd\r\n* FreeBSD 11 Tproxy\r\n* Compatible Old Inbound\r\n* CentOS Install Script\r\n* Systemd Improve\r\n* Test Fix
【09:00:44】: 准备升级到最新版本，开始下载
--09:00:44--  https://github.com/v2ray/v2ray-core/releases/download/
Resolving github.com... 13.250.177.223
Connecting to github.com|13.250.177.223|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
 09:00:44 ERROR 404: Not Found.

**Comment by dctxmei** [comment]
這個與 v2ray-core 本身無關。

**Comment by lhtdeg** [comment]
大概看了下，这是由于插件获取不到最新版本导致的，到/koolshare/scripts/v2ray_config.sh修改check_update_v2ray部分内容即可。

**Comment by ahxsong** [comment]
同样更新不了。请问你找到解决方法了么

**Comment by xiaojj** [comment]
直接下载下来.copy到 /koolshare/bin下面。

**Comment by ntgeralt** [comment]
koolshare拿着一个错误的下载地址，还不可更改。

**Comment by huhai586** [comment]
> 大概看了下，这是由于插件获取不到最新版本导致的，到/koolshare/scripts/v2ray_config.sh修改check_update_v2ray部分内容即可。

在一脸懵逼的时候，看到这个回答，果然有用，非常感谢啊
