### ISSUE TITLE
gitbook 动态端口配置样例有误

### ISSUE THREAD

**Issue by RogerChern** [v2ray/v2ray-core#243]
https://www.v2ray.com/chapter_03/00_dynport.html

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V2Ray v1.24.4 (New Order) 20160819

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
Not related

3) 你看到的不正常的现象是什么？
服务器端检测到随机监听端口，但客户端始终用主端口连接服务器

4) 你期待看到的正确表现是怎样的？
客户端随机连接服务器随机端口

5) 修正方案
```
    "settings": {
      "clients": [
        {
          "id": "UUID",
          "level": 1,
          "alterId": 64
        }
      ],
   # "features": {        // 特性设置
   #   "detour": {        // 绕路设置
   #     "to": "detour"   // 指定绕路协议的标签，要和“一”中的标签一样
   #   }
   # }
      "detour": {
        "to": "detour"
      }
    }
```

**Comment by v2ray** [comment]
已修改，现在两种方式都支持，但的确之前的写法是过时了。

**Comment by qingfengshi** [comment]
@RogerChern
请问一下，你是使用什么方式查看v2ray使用的本地端口的？我在cmd中使用netstat查看到v2ray使用的本地传出端口和我设置的范围不同。

**Comment by v2ray** [comment]
传出端口？传出端口是系统自动分配的，不能自己设置。

**Comment by qingfengshi** [comment]
在动态端口中，不是有服务器端指定通讯端口的么？我因此理解为客户端的传出端口由服务器端指定，并且与服务器端相同。

**Comment by RogerChern** [comment]
netstat -anp | grep v2ray
每次会额外 LISTEN concurrency 个端口，范围倒是和 inboundDetour 里设置得相同

2016-08-21 15:11 GMT+08:00 qingfengshi <notifications@github.com>:
