### ISSUE TITLE
每次启动都提示can't bind 127.0.0.1:2334

### ISSUE THREAD

**Issue by huzhiwei995** [v2ray/v2ray-core#2432]
有时候启动会提示端口被占用，每次要管理员cmd输：netsh winsock reset 重启电脑，好麻烦，上网查了都是上一个没关闭的，但是我每次用完就关闭软件的
版本：v2.53

错误日志：

--------------------------------info[00:06:41]--------------------------------
System.Exception: v2rayN start up
--------------------------------info[00:07:32]--------------------------------
System.Exception: Webserver prefixes http://*:2335/pac/
--------------------------------拒绝访问。[00:07:32]--------------------------------
System.Net.HttpListenerException (0x80004005): 拒绝访问。
   在 System.Net.HttpListener.AddAllPrefixes()
   在 System.Net.HttpListener.Start()
   在 v2rayN.Base.HttpWebServer..ctor(String[] prefixes, Func`2 method)
--------------------------------info[00:07:32]--------------------------------
System.Exception: Webserver InitServer 拒绝访问。
--------------------------------info[00:07:32]--------------------------------
System.Exception: WebserverB at 127.0.0.1
--------------------------------CurrentDomain_UnhandledException[00:07:32]--------------------------------
System.Net.Sockets.SocketException (0x80004005): 以一种访问权限不允许的方式做了一个访问套接字的尝试。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Bind(EndPoint localEP)
   在 System.Net.Sockets.TcpListener.Start(Int32 backlog)
   在 v2rayN.Base.HttpWebServerB.StartListen()
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()
--------------------------------info[00:17:14]--------------------------------
System.Exception: v2rayN start up
--------------------------------info[00:17:15]--------------------------------
System.Exception: Webserver prefixes http://*:2335/pac/
--------------------------------拒绝访问。[00:17:15]--------------------------------
System.Net.HttpListenerException (0x80004005): 拒绝访问。
   在 System.Net.HttpListener.AddAllPrefixes()
   在 System.Net.HttpListener.Start()
   在 v2rayN.Base.HttpWebServer..ctor(String[] prefixes, Func`2 method)
--------------------------------info[00:17:15]--------------------------------
System.Exception: Webserver InitServer 拒绝访问。
--------------------------------info[00:17:15]--------------------------------
System.Exception: WebserverB at 127.0.0.1
--------------------------------CurrentDomain_UnhandledException[00:17:15]--------------------------------
System.Net.Sockets.SocketException (0x80004005): 以一种访问权限不允许的方式做了一个访问套接字的尝试。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Bind(EndPoint localEP)
   在 System.Net.Sockets.TcpListener.Start(Int32 backlog)
   在 v2rayN.Base.HttpWebServerB.StartListen()
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()
--------------------------------info[00:22:43]--------------------------------
System.Exception: v2rayN start up
--------------------------------info[00:22:44]--------------------------------
System.Exception: Webserver prefixes http://*:2335/pac/
--------------------------------拒绝访问。[00:22:45]--------------------------------
System.Net.HttpListenerException (0x80004005): 拒绝访问。
   在 System.Net.HttpListener.AddAllPrefixes()
   在 System.Net.HttpListener.Start()
   在 v2rayN.Base.HttpWebServer..ctor(String[] prefixes, Func`2 method)
--------------------------------info[00:22:45]--------------------------------
System.Exception: Webserver InitServer 拒绝访问。
--------------------------------info[00:22:45]--------------------------------
System.Exception: WebserverB at 127.0.0.1
--------------------------------CurrentDomain_UnhandledException[00:22:45]--------------------------------
System.Net.Sockets.SocketException (0x80004005): 以一种访问权限不允许的方式做了一个访问套接字的尝试。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Bind(EndPoint localEP)
   在 System.Net.Sockets.TcpListener.Start(Int32 backlog)
   在 v2rayN.Base.HttpWebServerB.StartListen()
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()
--------------------------------info[00:31:18]--------------------------------
System.Exception: v2rayN start up
--------------------------------info[00:31:19]--------------------------------
System.Exception: Webserver prefixes http://*:2335/pac/
--------------------------------拒绝访问。[00:31:19]--------------------------------
System.Net.HttpListenerException (0x80004005): 拒绝访问。
   在 System.Net.HttpListener.AddAllPrefixes()
   在 System.Net.HttpListener.Start()
   在 v2rayN.Base.HttpWebServer..ctor(String[] prefixes, Func`2 method)
--------------------------------info[00:31:19]--------------------------------
System.Exception: Webserver InitServer 拒绝访问。
--------------------------------info[00:31:19]--------------------------------
System.Exception: WebserverB at 127.0.0.1
--------------------------------CurrentDomain_UnhandledException[00:31:19]--------------------------------
System.Net.Sockets.SocketException (0x80004005): 以一种访问权限不允许的方式做了一个访问套接字的尝试。
   在 System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Bind(EndPoint localEP)
   在 System.Net.Sockets.TcpListener.Start(Int32 backlog)
   在 v2rayN.Base.HttpWebServerB.StartListen()
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()
--------------------------------info[00:36:23]--------------------------------
System.Exception: v2rayN start up
--------------------------------info[00:36:26]--------------------------------
System.Exception: Webserver prefixes http://*:2335/pac/
--------------------------------拒绝访问。[00:36:26]--------------------------------
System.Net.HttpListenerException (0x80004005): 拒绝访问。
   在 System.Net.HttpListener.AddAllPrefixes()
   在 System.Net.HttpListener.Start()
   在 v2rayN.Base.HttpWebServer..ctor(String[] prefixes, Func`2 method)
--------------------------------info[00:36:26]--------------------------------
System.Exception: Webserver InitServer 拒绝访问。
--------------------------------info[00:36:26]--------------------------------
System.Exception: WebserverB at 127.0.0.1
--------------------------------info[00:36:26]--------------------------------
System.Exception: WebserverB running...
--------------------------------info[00:36:26]--------------------------------
System.Exception: WebserverB Request 127.0.0.1
--------------------------------info[00:36:26]--------------------------------
System.Exception: WebserverB Request 127.0.0.1

**Comment by KirbyKFC** [comment]
v2rayN的问题你应该发到v2rayN那边去
https://github.com/2dust/v2rayN/issues

**Comment by kslr** [comment]
也许你可以试试用管理员启动
