### ISSUE TITLE
Failed to reset devices.list: Operation not permitted

### ISSUE THREAD

**Issue by Nicotinamide** [v2ray/v2ray-core#2435]
Apr 15 17:19:18 srv10433 systemd[1]: Stopped V2Ray - A unified platform for anti-censorship.
Apr 15 17:19:18 srv10433 systemd[1]: v2ray.service: Failed to reset devices.list: Operation not permitted
Apr 15 17:19:18 srv10433 systemd[1]: v2ray.service: Failed to set invocation ID on control group /system.slice/v2ray.service, ignoring: Operation not permitted
Apr 15 17:19:18 srv10433 systemd[1]: Started V2Ray - A unified platform for anti-censorship.
Apr 15 17:19:18 srv10433 v2ray[662]: V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/amd64)
Apr 15 17:19:18 srv10433 v2ray[662]: A unified platform for anti-censorship.
Apr 15 17:19:18 srv10433 v2ray[662]: 2020/04/15 17:19:18 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
Apr 15 17:19:18 srv10433 v2ray[662]: v2ctl> Read config:  /etc/v2ray/config.json

**Comment by Stanfording** [comment]
Is there a solution to this? v2ray.service: Failed to reset devices.list: Operation not permitte

**Comment by xuzhongpeng** [comment]
Any solutions?
