### ISSUE TITLE
Cant go get -u -insecure v2ray.com/core@v4.23.1

### ISSUE THREAD

**Issue by CGQAQ** [v2ray/v2ray-core#2438]
go get v2ray.com/core@v4.23.1: v2ray.com/core@v4.23.1: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v4

consider to have the v4 root folder according to [Module_compatibility_and_semantic_versioning](https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning)

**Comment by kslr** [comment]
https://github.com/v2ray/v2ray-core/issues/1983

**Comment by CGQAQ** [comment]
![image](https://user-images.githubusercontent.com/15936231/79630009-824b6e80-8180-11ea-990d-3983eb7e897b.png)

**Comment by kslr** [comment]
nobody

**Comment by Ehco1996** [comment]
or we can push one release and downgraude tag version to v1.xxx?
