### ISSUE TITLE
速度很快，但是某些网站的图片加载不出来

### ISSUE THREAD

**Issue by Jason4774** [v2ray/v2ray-core#244]
您好，
     我使用的是v2ray-windows-64.zip，然后速度很快，不过最近发现某些网站的图片加载不出来，不知道什么原因，因为我使用蓝灯的时候是可以加载出来的，所以反馈一下这个问题，看看能不能解决，
图片加载不出来的网站是：
使用蓝灯后可以看见，如下：
我的配置文件，就是默认，未做修改：
{
  "log": {
    "loglevel": "warning"
  },
  "inbound": {
    "port": 1080,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "v2ray.cool",
          "port": 10086,
          "users": [
            {
              "id": "23ad6b10-8d1a-40f7-8ad0-e3e35cd38297",
              "alterId": 64
            }
          ]
        }
      ]
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": "1-52",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "54-79",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "81-442",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "444-65535",
          "outboundTag": "direct"
        },
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        }
      ]
    }
  },
  "transport": {
    "kcpSettings": {
      "uplinkCapacity": 1,
      "downlinkCapacity": 10
    }
  }
}
我是windows10，希望您有空的时候能帮忙看看，谢谢。

**Comment by BenhoNNNN** [comment]
测试没问题，尝试下全局走 V2Ray ，没问题的话，排查下 DNS 或者图床服务器的连通性。

**Comment by Jason4774** [comment]
谢谢您的回复，全局之后可以了，之前不行因为我是蓝灯测试的时候是全局，v2ray的时候是有一个规则表自动切换，但是我想问一下，我虽然之前是v2ray自动切换，但是我已经在SwitchyOmega添加条件让这个网站走v2ray代理了，这样和全局不一样吗？为什么这样不行全局可以。我之前一直觉得添加条件不是就让他走这个代理和全局让他走这个代理一样吗？
麻烦您有空的时候回复我一下，谢谢。

哦对了，我不是用来找毛片的，这个网页是之前有人给我推荐pac代理服务器的，要找毛片也不在这里找是吧。

**Comment by wtlusvm** [comment]
网站的域名是t66y.com（我点进去才发现是……老司机带带我！）
而图片网址域名是uploadhouse.com。
所以你懂为什么在SwitchyOmega添加条件也不行了吗？

**Comment by Jason4774** [comment]
这个是别人发给我分享pac服务器的，我是年轻司机。所以不要误会，谢谢你的回复，我懂了。

**Comment by liaobin** [comment]
v2ray自带的路由表可能不是那么完美,建议配合其他pac软件使用,如https://github.com/cyfdecyf/cow 或者是https://github.com/renzhn/MEOW

**Comment by Jason4774** [comment]
谢谢，测试了cow和meow。发现就那个网站而言，cow还是有点问题，不过cow比自动切换规则表好多了，但是使用meow就完美了，上面那个网页中的图片也可以加载出来了。现在已经集成到我的浏览器里面了。完美。谢谢。
