### ISSUE TITLE
新特性: Http3.0支持

### ISSUE THREAD

**Issue by 29e7e280-0d1c-4bba-98fe-f7cd3ca7500a** [v2ray/v2ray-core#2441]
## 提议

本提议,旨在增加Http 3.0 作为v2ray 数据传输通道之一

## 参考资料

golang版本的  http3 实现
https://github.com/lucas-clemente/quic-go/tree/master/http3

https://quicwg.org/base-drafts/draft-ietf-quic-http.html#name-http-3-protocol-overview

**Comment by rprx** [comment]
quic？

**Comment by VoidxHoshi** [comment]
> quic？

HTTP/3是HTTP over QUIC

**Comment by zhfish** [comment]
quic在中国网络环境下很难推啊

**Comment by rhjdvsgsgks** [comment]
但如果能走cdn就不一样了

**Comment by myfingerhurt** [comment]
联通下使用QUIC非常稳定。

**Comment by moralrebuild** [comment]
大势所趋，期待

**Comment by phlinhng** [comment]
> quic？

quic還沒有定稿吧，目前v2Ray內建的是老版本的QUIC
期待未來完善後可以加進去

**Comment by charley008** [comment]
3.0?

**Comment by phlinhng** [comment]
> 3.0?

In October 2018, the IETF's HTTP and QUIC Working Groups jointly decided to call the HTTP mapping over QUIC **"HTTP/3"** in advance of making it a worldwide standard.
