### ISSUE TITLE
nginx+wss反代失败

### ISSUE THREAD

**Issue by liuyuran** [v2ray/v2ray-core#2442]
1) 你正在使用哪个版本的 V2Ray？
4.23.1

2) 你的使用场景是什么？
搭建双层跳板，并使用个人博客的域名做wss伪装。

3) 你看到的不正常的现象是什么？
使用nginx反代wss后无法连接，但是监听0.0.0.0后使用原始ws地址可以连接。

4) 你期待看到的正确表现是怎样的？
nginx反代生效。

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
{
	"log": {
		"access": "/var/log/v2ray/access.log",
		"error": "/var/log/v2ray/error.log",
		"loglevel": "warning"
	},
	"inbounds": [
		{
			"port": 10983,
			"protocol": "vmess",
			"settings": {
				"clients": [
					{
						"id": "...",
						"level": 1,
						"alterId": 233
					}
				]
			},
			"streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/diamond"
        }
			}
		}
	],
	"outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "...",
            "port": 10983,
            "users": [
              {
                "id": "...",
                "level": 1,
                "alterId": 233
              }
            ]
          }
        ]
      }
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "blocked"
      }
    ]
  }
}



    location /diamond {
      proxy_pass http://127.0.0.1:10983;
      proxy_redirect off;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      # proxy_set_header Host $http_host;
      # proxy_set_header X-Real-IP $remote_addr;
      # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
```

客户端配置:

```javascript
    "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "...",
            "port": 443,
            "users": [
              {
                "id": "10c1f027-2783-4abd-aedf-d64db923b544",
                "alterId": 233,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": null,
        "tlsSettings": null,
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/diamond",
          "headers": {
            "Host": "..."
          }
        },
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
    }
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

没有日志

客户端错误日志:

```javascript
    [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://.../diamond): 502 Bad Gateway > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

没有日志

8) 其它相关的配置文件（如 Nginx）和相关日志。

以下为nginx日志
```javascript
2020/04/19 09:41:10 [error] 6#6: *255 connect() failed (111: Connection refused) while connecting to upstream, client: ..., server: ..., request: "GET /diamond HTTP/1.1", upstream: "http://127.0.0.1:10983/diamond", host: "..."
... - - [19/Apr/2020:09:41:10 +0000] "GET /diamond HTTP/1.1" 502 494 "-" "Go-http-client/1.1" "-"
```

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

启动正常

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

启动正常

虽然其实结果上看是可以使用，我还是很好奇到底是什么东西导致nginx访问不通的，我记得有个Issue里提过不能加Host请求头，然后我删了也没效果。

**Comment by kslr** [comment]
https://guide.v2fly.org/advanced/wss_and_web.html#%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%85%8D%E7%BD%AE

**Comment by liuyuran** [comment]
拷贝location部分后依然如故，从返回值502可以看出，问题在于
`connect() failed (111: Connection refused) while connecting to upstream`
后面的日志可以看出的确成功转发到了本机的指定端口
之后我尝试使用http协议转发非tls的ws协议，日志依然显示connection refused，我所使用的测试配置如下：
`server {
	listen 80;
	server_name  ...;
    location /diamond {
        if ($http_upgrade != "websocket") {
            return 404;
        }
        proxy_redirect off;
        proxy_pass http://127.0.0.1:10983;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        # Show real IP in v2ray access.log
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}`
`"vnext": [
          {
            "address": "...",
            "port": 80,
            "users": [
              {
                "id": "...",
                "alterId": 233,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ]`
那么应该不是我设置的公用https配置的原因？

**Comment by kslr** [comment]
你这个是什么定制版吗，我看到很多参数，如果你不清楚的话就按照指南中的模板

**Comment by myfingerhurt** [comment]
@kslr 我猜他是用v2rayNG导出的

**Comment by liuyuran** [comment]
是的，v2rayN……

**Comment by linux40** [comment]
> https://guide.v2fly.org/advanced/wss_and_web.html#%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%85%8D%E7%BD%AE
这个教程对于 caddy 的配置有错，`protocols` 和 `ciphers` 要在 `tls {` 和 `}` 之间。

**Comment by linux40** [comment]
> https://guide.v2fly.org/advanced/wss_and_web.html#%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%85%8D%E7%BD%AE

这个教程关于 caddy 的配置有错，`protocols` 和 `ciphers` 要在 `tls {` 和 `}` 之间。

**Comment by frankli0324** [comment]
你这服务端配置在无限套娃啊
![image](https://user-images.githubusercontent.com/20221896/80357595-c986dd00-88ad-11ea-88c7-b5d3953fbc71.png)


btw，看了 你repo 的issue，我更加理解cn为什么要w github了，气抖冷

**Comment by liuyuran** [comment]
> 你这服务端配置在无限套娃啊
> 把送到outbound的流量又送回inbound的操作有亿点看不懂
> ⬇️供参考
> ![image](https://user-images.githubusercontent.com/20221896/80357595-c986dd00-88ad-11ea-88c7-b5d3953fbc71.png)
> 
> 正确服务端"outbounds"配置如下：
> 
> ```json
> {
> 	"outbounds": [{
> 		"protocol": "freedom"
> 	}, {
>       	"protocol": "blackhole",
>       	"settings": {},
>       	"tag": "blocked"
>     }]
> }
> ```
> 
> 其他地方不用动
> 
> btw，看了 你repo 的issue，我更加理解cn为什么要w github了，气抖冷

不理解- -，我一直小心翼翼的避免被注意到，到底是什么东西让你产生了微妙的错觉？
还有，我在主楼就说过了，我直接连接域名+端口+ws端口是可以正常运作的，只是连接nginx反代的伪装域名+wss后无法运作，因为我的第一层跳板在香港阿里云上，如果你不知道这意味着什么，我也不想主动说明。
然后，outbound指向的是我在日本的一台服务器，在那里同样有一个v2ray节点，这一点如果不知道“跳板”是什么意思可能很困难，但这不是贸然出言讽刺的理由。

**Comment by frankli0324** [comment]
最后一句没说你（

**Comment by frankli0324** [comment]
你在服务器上`nc -l 10983`看收不收得到来自nginx的请求？

主要我一开始看到一堆人提的issue，什么间谍都张口就来了，就有点暴躁
而且看到你的inbounds和outbounds的端口号是一致的，就思维定势了

**Comment by frankli0324** [comment]
你在服务器上`nc -l 10983`看收不收得到来自nginx的请求？

**Comment by liuyuran** [comment]
测试结果是这样：
```curl http://127.0.0.1:10983/diamond -> 接收到了```
```curl http://<我的域名>/diamond -> 返回404，但根据nginx配置是正常现象```

关闭404伪装后
```curl http://<我的域名>/diamond -> 没接收到```

破案了，可能因为某些原因nginx没成功转发websocket数据包，那这就不是v2ray范畴内的问题了，我自己再钻研一下nginx配置去……感谢各位，结帖

PS：nc是linux下用于测试网络通畅性的命令，可以短暂监听指定端口，并输出接收到的第一个包的信息
