### ISSUE TITLE
能否指定TLS的加密算法

### ISSUE THREAD

**Issue by okudayukiko** [v2ray/v2ray-core#2445]
Please describe the new feature you want in detail.
V2RAY的TLS能否指定Ciphers（加密算法）和TLS版本（TLS 1.2和TLS 1.3），希望TLS支援使用CHACHA20-POLY1305或AES-128-GCM，因為這兩者比AES-256-GCM省電。
https://www.v2ray.com/chapter_02/05_transport.html#tlsobject

**Comment by kslr** [comment]
你可以在http server上指定

**Comment by okudayukiko** [comment]
> 
> 
> 你可以在http server上指定

用dynamic port時就沒辦法。

**Comment by okudayukiko** [comment]
> 
> 
> 你可以在http server上指定

另外如果Client端可以選擇TLS加密算法，也多一個選擇。

**Comment by okudayukiko** [comment]
在某些低端服務器（用cat /proc/cpuinfo看了下我的VPS還是E3V3）上用AES-256-GCM比較吃力。用Web server軟件做前端TLS可以是可以但 比較麻煩；不方便VMess dynamic port功能（雖然用HAProxy也可以做VMess+TLS dynamic port，但客戶端不能選擇TLS加密算法還是是不方便）。

**Comment by kslr** [comment]
我建议直接修改代码
https://github.com/v2ray/v2ray-core/blob/master/transport/internet/tls/config.go#L189

**Comment by okudayukiko** [comment]
Nginx等使用OpenSSL Lib的軟件，可以通過修改`/etc/ssl/openssl.cnf`變更TLS加密算法設定。

**Comment by okudayukiko** [comment]
表現就是服務器CPU使用率不高但一換ChaCha20-Poly1305算法就馬上流暢。

**Comment by Steve789** [comment]
一般浏览网页情况如何？我猜一般还是能打开的。看视频卡更像网络问题，因为视频传输需要更高的带宽，我特地测试一下，客户端流畅观看1080P视频的情况下，服务器单核心cpu负载很低。(v2ray=WS+TLS+cloudflare+caddy)

**Comment by okudayukiko** [comment]
> 一般浏览网页情况如何？我猜一般还是能打开的。看视频卡更像网络问题，因为视频传输需要更高的带宽，我特地测试一下，客户端流畅观看1080P视频的情况下，服务器单核心cpu负载很低。(v2ray=WS+TLS+cloudflare+caddy)

我更改Wi-Fi路由器的一個配置後，Wi-Fi速度由原來72Mbps變為433Mbps，網速快了很多。

**Comment by Steve789** [comment]
你的路由器离你的上网设备很近，而你的代理服务器离你很远。

**Comment by okudayukiko** [comment]
> 你的路由器离你的上网设备很近，而你的代理服务器离你很远。

又如，剛剛發現將塑料手機殼拆下後，用手機的V2Ray看視頻也清晰了。原來這麼講究。
不過AES-GCM確實比CHACHA20-POLY1305耗電。

**Comment by kslr** [comment]
太玄学了吧，要用数据去测试

**Comment by okudayukiko** [comment]
V2Ray能否支援客戶端證書驗證？
![Screenshot](https://user-images.githubusercontent.com/17502357/80679104-d3e3e980-8aee-11ea-98bb-e137c53e309e.jpg)
![Screenshot](https://user-images.githubusercontent.com/17502357/80679184-f8d85c80-8aee-11ea-8a26-320f063fca0f.jpg)
`"usage": "verify"`並不是強制性證書驗證。

**Comment by liberal-boy** [comment]
TLS 加密套件协商应该是由服务端选择加密套件的。

**Comment by okudayukiko** [comment]
> TLS 加密套件协商应该是由服务端选择加密套件的。

客戶端和服務端都可以選擇加密算法。

**Comment by liberal-boy** [comment]
> > TLS 加密套件协商应该是由服务端选择加密套件的。
> 
> 客戶端和服務端都可以選擇加密算法。

客户端告诉服务端支持的加密套件，最终由服务端决定，大部分服务端实现是按照服务端的顺序选择双方都支持的第一个加密套件。

**Comment by okudayukiko** [comment]
V2Ray能否支持多證書（如Nginx支持RSA+ECDSA）？用OpenSSL追了下，V2Ray不支持多證書（如RSA+ECDSA）。
