### ISSUE TITLE
機場問題

### ISSUE THREAD

**Issue by escpthree** [v2ray/v2ray-core#2449]
機場屏蔽了某些特定網站，有技術手段能解決嗎？

**Comment by kslr** [comment]
一般取决于实现方式，但还是遵守TOS比较好

**Comment by escpthree** [comment]
Supbitch?

**Comment by facenano** [comment]
Supbitch!

賤狗臭閪鄧兆瑩 ***@***.***> 于2021年11月11日周四 上午11:28写道：
