### ISSUE TITLE
服务端是否有可能同时开放基于mKCP与基于原先TCP的VMess？

### ISSUE THREAD

**Issue by htfy96** [v2ray/v2ray-core#245]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please answer the following questions before submitting your issue. Thank you.

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
1.24.3

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
使用Socks/VMess浏览网页。但有的地方KCP不被墙，有的地方KCP被干扰。

3) 你看到的不正常的现象是什么？
被干扰的情况下，基于KCP的VMess协议无法联通。在服务端尝试在InboundDetour中增加VMess配置项
```
      { 
                "protocol": "vmess", 
                "port": "60000-61000", 
                 "settings": {
                "clients": [ 
                        { 
                                "id": "__",   
                                "level": 1   
                        } 
                ]}, 
            "allocate": {   
                "strategy": "random", 
                "concurrency": 5,    
                "refresh": 5        
            } 
        },
```
发现仍然不能在不启用KCP的客户端连上
4) 你期待看到的正确表现是怎样的？
通过配置实现一个服务端同时提供VMess over mKCP 和 VMess over TCP两个在不同端口的服务

**Comment by v2ray** [comment]
写两个 inbound 即可，比如 inbound 是 TCP:

```javascript
"inbound": {
  "protocol": "vmess", 
  "port": 10000, 
  "settings": { /* 略过 */}
}
```

再加一个 KCP 的 inboundDetour:

"inboundDetour": [
{
  "protocol": "vmess", 
  "port": 10001, 
  "settings": { /* 略过 */},
  "streamSettings": {
    "network": "kcp"
  }
}
// 其它 detour
]
```

（以上配置纯手写，可能用小错误。）

两个 VMess 的端口可以相同（因为一个是 TCP，一个是 UDP），并可以分别配置动态端口。

**Comment by htfy96** [comment]
学习了，有空我来写一个配置生成器

**Comment by BenhoNNNN** [comment]
@htfy96 #配置生成器可以有#

**Comment by 923372148** [comment]
码
