### ISSUE TITLE
v2ray的DNS本地解析不生效

### ISSUE THREAD

**Issue by H0u5er** [v2ray/v2ray-core#2450]
最近买了NAS，但是路由器无法做静态DNS映射表，所以考虑用v2ray在浏览器实现本地DNS解析，但是发现本地DNS解析似乎不生效。

1.我的环境
笔记本IP：192.168.1.16/24

NAS 管理地址：192.168.1.251/24
NAS Web Portal : 5001 (HTTPS)
计划将 drive.example.com 解析为 192.168.1.251

网关：192.168.1.1（路由器）
默认DNS：1.1.1.1

2.v2ray配置
以下配置是简化和脱敏后的结果，平时v2ray使用上没有其他问题，DoH也正常。domainStrategy试过使用IPIfNonMatch，本地DNS解析不生效问题依然存在。

```json
{
  "log": {
    "access": "/var/log/v2ray/access.out",
    "error": "/var/log/v2ray/error.out",
    "loglevel": "debug"
  },
  "dns": {
  "hosts": {
    "drive.example.com": "192.168.1.251"
  },
    "servers": [
      {
        "address": "223.5.5.5",
        "port": 53,
        "domains": [
          "geosite:cn"
        ],
        "expectIPs": [
          "geoip:cn"
        ]
      },
      {
        "address": "https://1.1.1.1/dns-query",
        "port": 53,
        "domains": [
          "geosite:geolocation-!cn",
          "geosite:speedtest"
        ]
      },
      "1.1.1.1",
      "localhost"
    ]
  },
  "inbounds": [
    {
      "port": hidden,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": false,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": "127.0.0.1"
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "users": [
              {
                "id": "hidden",
                "alterId": hidden,
                "security": "auto"
              }
            ],
            "address": "hidden",
            "port": 443
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false
        },
        "wsSettings": {
          "path": "/hidden"
        }
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {}
    }
  ],
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "domain": [
          "geosite:category-ads",
          "domain:baidu.com"
        ],
        "outboundTag": "block"
      },
      {
        "type": "field",
        "domain": [
          "domain:cloudflare-dns.com",
          "domain:cip.cc"
        ],
        "outboundTag": "proxy"
      },
      {
        "type": "field",
        "ip": [
          "1.1.1.1"
        ],
        "outboundTag": "proxy"
      },
      {
        "type": "field",
        "domain": [
          "geosite:cn",
          "domain:internal.local"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": [
          "223.5.5.5",
          "geoip:cn",
          "geoip:private"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "port": "5001",
        "outboundTag": "direct"
      }
    ]
  }
}
```

3. 日志记录
有看到 returning一个IP地址回来，但是浏览器提示ERR_TIMED_OUT，也不知道如何查看这个return IP的值，Wireshark抓包发现笔记本依然向网关请求解析drive.example.com，并且得到了网关上默认DNS的回复，因此认为本地DNS解析在浏览器层面并没有生效。

检查过笔记本hosts文件和resolved.conf，均正常。

177 2020/04/22 22:29:26 [Info] [1152479830] v2ray.com/core/proxy/socks: TCP Connect request to tcp:drive.example.com:5001
178 2020/04/22 22:29:26 [Info] v2ray.com/core/app/dns: returning 1 IPs for domain drive.example.com
179 2020/04/22 22:29:26 [Info] [1152479830] v2ray.com/core/app/dispatcher: taking detour [direct] for [tcp:drive.example.com:5001]
180 2020/04/22 22:29:26 [Info] [1152479830] v2ray.com/core/proxy/freedom: opening connection to tcp:drive.example.com:5001
181 2020/04/22 22:29:26 [Info] [1152479830] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:drive.example.com:5001
182 2020/04/22 22:29:26 [Info] [1152479830] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:drive.example.com:5001
183 2020/04/22 22:29:26 [Info] [1779114442] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:drive.example.com:5001
184 2020/04/22 22:29:26 [Info] [1779114442] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
185 2020/04/22 22:29:27 [Info] [1779114442] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:drive.example.com:5001
186 2020/04/22 22:29:27 [Info] [1779114442] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: failed to open con    nection to tcp:drive.example.com:5001 > v2ray.com/core/common/retry: [dial tcp: lookup drive.example.com on 192.168.1.1:53: no such host dial tcp: operation was canc    eled] > v2ray.com/core/common/retry: all retry attempts failed
187 2020/04/22 22:29:36 [Info] [1152479830] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:drive.example.com:5001
188 2020/04/22 22:29:47 [Info] [1152479830] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:drive.example.com:5001
189 2020/04/22 22:29:56 [Info] [2041919711] v2ray.com/core/proxy/socks: TCP Connect request to tcp:drive.example.com:5001
190 2020/04/22 22:29:56 [Info] v2ray.com/core/app/dns: returning 1 IPs for domain drive.example.com

附上Wireshark截图
![Screenshot 2020-04-22 at 22.44.07.png](https://i.loli.net/2020/04/22/s7hSHYXQBVZKlxp.png)

**Comment by kslr** [comment]
你的代理是如何设置的？如何保证dns流量

**Comment by H0u5er** [comment]
> 你的代理是如何设置的？如何保证dns流量

macOS下安装brew安装v2ray-core，配合Chrome的SwitchyOmega，平时DOH解析都正常，macOS和Chrome均为最新版，如果需要再附上

**Comment by kslr** [comment]
试试在终端启动chrome 使用代理参数
或者系统全局代理一下

**Comment by H0u5er** [comment]
> 试试在终端启动chrome 使用代理参数
> 或者系统全局代理一下

1. 原本的情况是，移除全部SwitchyOmega的profile，然后自定义一个profile，全部协议均指向default，即指向本地的v2ray端口，这种情况下之前测试过twitter.com，日志中可见DoH的A记录；
2.由于没有其他SwitchyOmega的profile，使用“system proxy”的情况下访问 https://drive.example.com:5001, Chrome 解析错误，ERR_NAME_NOT_RESOLVED


附上系统环境：
macOS 10.15.4 (19E287)
Chrome Version 81.0.4044.92 (Official Build) (64-bit)
Homebrew 2.2.11
V2Ray 4.23.1
SwitchyOmega Version 2.5.21

**Comment by kslr** [comment]
https://github.com/v2ray/v2ray-core/issues/1717

**Comment by H0u5er** [comment]
参考由onplus/v2ray-SiteDAT提供的工具，打算编译一个叫dns.dat的文件，但是文件有问题，请问是我的做法有问题吗？做法如下：

- 下载windows版本v2ray-SiteDAT工具，删除sites文件夹内的全部文件，创建一个名为internal的文件
- internal文件的内容是 drive.example.com
- 运行程序，得到geosite.dat, 重命名为dns.dat
- 拷贝dns.dat 到macOS下的v2ray目录
- v2ray 检测config.json 无法通过


**错误信息如下**
```
houser@Housers-MacBook-Pro bin % ./v2ray --test --config /usr/local/etc/v2ray/config.json
V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 darwin/amd64)
A unified platform for anti-censorship.
main: failed to read config files: [/usr/local/etc/v2ray/config.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: 
v2ctl> Read config:  /usr/local/etc/v2ray/config.json
v2ray.com/core/infra/conf: failed to parse DNS config > v2ray.com/core/infra/conf: invalid external resource: ext:dns.dat > exit status 255
houser@Housers-MacBook-Pro bin % 


houser@Housers-MacBook-Pro bin % ls
dns.dat		geoip.dat	  geosite.dat	v2ctl		v2ray
houser@Housers-MacBook-Pro bin % tree
.
├── dns.dat
├── geoip.dat
├── geosite.dat
├── v2ctl
└── v2ray

0 directories, 5 files
houser@Housers-MacBook-Pro bin % 
```

**新增DNS后的 config.json 配置如下（部分）**
```
......

  "dns": {
  "hosts": {
    "ext:dns.dat": "192.168.1.251"
  },  
    "servers": [
      {   
        "address": "223.5.5.5",
        "port": 53, 
        "domains": [
          "geosite:cn"

......

```

**请问是生成dat的过程有问题吗？**
- 不保留原有sites文件夹内的全部文件，创建internal文件并写入drive.example.com；
- 仅保留cn文件，不修改文件名的情况下，清理cn文件内容后写入drive.example.com；
- 保留原有的cn，proxy，reject，direct四个文件，不修改文件名的情况下，清理四个文件内容后分别写入drive.example.com；

以上情况我都测试过了，均无法通过v2ray对config.json文件检查，参考《漫谈各种黑科技式-dns-技术在代理环境中的应用》一文的例子，是不是必须要用挂载dat文件来实现类似hosts的功能？

```
"dns": {
  "hosts": {
    "www.google.com": "127.0.0.1"
  }
}
```

**Comment by H0u5er** [comment]
修改文件权限之后，依然无法通过 config.json 文件检查。


```
houser@Housers-MacBook-Pro bin % ls -hl
total 70944
-r--r--r--  1 houser  admin   147B Apr 23 07:29 dns.dat
-r--r--r--  1 houser  admin   4.9M Jan  1  2010 geoip.dat
-r--r--r--  1 houser  admin   750K Jan  1  2010 geosite.dat
-r-xr-xr-x  1 houser  admin    12M Jan  1  2010 v2ctl
-r-xr-xr-x  1 houser  admin    17M Jan  1  2010 v2ray
houser@Housers-MacBook-Pro bin % pwd
/usr/local/Cellar/v2ray-core/4.23.1/bin
houser@Housers-MacBook-Pro bin % 
```

**Comment by kslr** [comment]
你原来的办法应该没有问题，试试把domainStrategy改成UseIP 把其他不需要的都先删除，测试一下

**Comment by KirbyKFC** [comment]
v2ray的DNS模块默认情况是用作路由的，从freedom出去的流量的DNS解析默认是使用系统DNS的，要使用v2ray内置的DNS模块的话需要手动设置UseIP。

**Comment by H0u5er** [comment]
参考Freedom章节，添加domainStrategy设置，本地DNS解析已经解决问题，thanks！


```
    {   
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
      "domainStrategy": "UseIPv4"    
}
    },  
    {   
      "tag": "block",
      "protocol": "blackhole",
      "settings": {}
    }   
```
