### ISSUE TITLE
V2ary更新失败

### ISSUE THREAD

**Issue by UnlimitedM214** [v2ray/v2ray-core#2453]
--2020-04-25 15:42:23--  https://github.com/v2ray/v2ray-core/releases/download/https://api.github.com/repos/v2ray/v2ray-core/releases/24822244/v2ray-linux-64.zip
Resolving github.com (github.com)... 140.82.112.3
Connecting to github.com (github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-04-25 15:42:24 ERROR 404: Not Found.

**Comment by dctxmei** [comment]
這個連結地址就是錯誤的，還能怎麼更新呢？

**Comment by UnlimitedM214** [comment]
> 這個連結地址就是錯誤的，還能怎麼更新呢？
没法办，可是检查更新后就只能默认是这个地址

**Comment by dctxmei** [comment]
> > 這個連結地址就是錯誤的，還能怎麼更新呢？
> > 没办法，检查更新后就只能默认是这个地址

這個與 v2ray-core 無關的。

**Comment by kslr** [comment]
你需要联系该作者，更新脚本
