### ISSUE TITLE
v2ray的链式代理HTTP：客户端config.json采用链式转发配置遇到proxySettings 与 streamSettings冲突

### ISSUE THREAD

**Issue by youngerliyg** [v2ray/v2ray-core#2455]
目前越来越多的WS+TLS+V2RAY的配置得到应用，其中有一个场景被多个用户的ISSUE或者DISCUSSION涉及，就是客户端需要经过代理才能访问到V2RAY服务器，即需要配置链式代理来解决。但是，当配置链式代理proxySettings，发现与streamSettings是冲突的，导致了问题“WS+TLS+V2RAY（配置了streamSettings）场景下链式代理proxySetting无法使用”. 

所以来feature request区提请这个feature的实现，谢谢。

在https://github.com/v2ray/v2ray-core/issues/1736 中有两三个场景述及，在友站文章“https://ailitonia.com/archives/v2ray%E5%AE%8C%E5%85%A8%E9%85%8D%E7%BD%AE%E6%8C%87%E5%8D%97/comment-page-1/#outboundproxy” 也对此进行讨论。

    你正在使用哪个版本的 V2Ray？
    V2Ray 4.23.1

    你的使用场景是什么？
    客户端：WIN10，使用Firefox，运行V2RAYN，进行科学上网。
    服务器：WS+TLS+V2RAY

    你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

由于公司网络还有一个强制HTTP代理（使用用户名和密码验证），所以在应用链式转发配置期望如下：WIN10 Firefox -> 客户端V2RAYN -> HTTP 代理 ------((( INTERNET )))------> V2RAY 服务器 ->GOOGLE or YOUTUBE.

客户端应用链式转发后客户端总是说TIMEOUT，访问外网失败（不仅GOOGLE访问不了，连国内网站度娘什么的也访问不了）。具体客户端V2RAYN的config.json在下文附上。
于此同时，如果在家庭环境（无需HTTP代理）V2RAYN客户端不用配置链式转发，访问国内国外网站正常。

    你期待看到的正确表现是怎样的？
    期望V2RAY可以支持通过HTTP代理后访问V2RAY服务器。

    请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    客户端链式转发的配置是参考了如下配置指南，在V2RAYN原config.json基础上做了增加和修改：
    代理转发：https://toutyrater.github.io/advanced/outboundproxy.html
    HTTP协议格式：https://www.v2ray.com/chapter_02/protocols/http.html

"outbounds": [
{
"tag": "proxy",
"protocol": "vmess",
"settings": {
"vnext": [
{
"address": "v2ray server IP address",
"port": v2ray server port,
"users": [
{
"id": "11111-22222-33333-44444-5555",
"alterId": 64,
"email": "abc@cde.fgh",
"security": "auto"
}
]
}
],
"servers": null,
"response": null
},
"streamSettings": {
"network": "ws",
"security": "tls",
"tlsSettings": {
"allowInsecure": false,
"serverName": "www.myowndomainname.com"
},
"tcpSettings": null,
"kcpSettings": null,
"wsSettings": {
"connectionReuse": true,
"path": "/superlooooooooooooooooooooooongrandom_id",
"headers": {
"Host": "www.myowndomainname.com"
}
},
"httpSettings": null,
"quicSettings": null
},
"mux": {
"enabled": true,
"concurrency": 8
},
"proxySettings": {
"tag": "http_proxy"
}
},
{
"tag": "http_proxy",
"protocol": "http",
"settings": {
"servers": [
{
"address": "192.168.8.1",
"port": 58888,
"users": [
{
"user": "myusername",
"pass": "mypassword"
}
]
}
]
}
},
{
"tag": "direct",
"protocol": "freedom",
"settings": {
"vnext": null,
"servers": null,
"response": null
},
"streamSettings": null,
"mux": null
},
{
"tag": "block",
"protocol": "blackhole",
"settings": {
"vnext": null,
"servers": null,
"response": {
"type": "http"
}
},
"streamSettings": null,
"mux": null
}
],

服务器端配置:
服务器端已经核实过，如果没有HTTP代理的情况下，直接用WIN10 Firefox ->V2RAYN -> V2RAY服务器是成功的。

**Comment by KyonLi** [comment]
我用clash的relay解决了这个问题

**Comment by youngerliyg** [comment]
> 
> 
> 我用clash的relay解决了这个问题

也有人建议用任意门dokodemo-door来解决，几次尝试失败了，我还在调试中。。。

**Comment by KyonLi** [comment]
dokodemo-door我也成功了，不过有点繁琐，整体思路就是用dokodemo-door把你最终要使用的远程代理服务器的端口映射到本地，在这个过程中通过route指定一个前置代理。然后把本地映射过来的这个端口当作一个普通的代理服务器配置连接就可以了。

**Comment by youngerliyg** [comment]
> 
> 
> dokodemo-door我也成功了，不过有点繁琐，整体思路就是用dokodemo-door把你最终要使用的远程代理服务器的端口映射到本地，在这个过程中通过route指定一个前置代理。然后把本地映射过来的这个端口当作一个普通的代理服务器配置连接就可以了。

感谢指教，今晚刚刚验证dokodemo-door成功。我把详细信息附在 https://github.com/v2ray/discussion/issues/651 中了。
