### ISSUE TITLE
Ubuntu20.04使用v2ray客户端科学上网时的问题

### ISSUE THREAD

**Issue by liaoran** [v2ray/v2ray-core#2458]
OS：Ubuntu20.04 LTS
v2ray版本：4.23.1
下载使用的v2ray-linux-64
终端命令行输入：./v2ray --config=文件路径/config.json
我是将在Windows10下能**正常使用**的config.json直接复制到Ubuntu上使用的。出现的问题：
`2020/04/27 06:52:54 [Warning] [3936813242] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)`
是不是Windows10能**正常使用**的配置文件，不能直接在Ubuntu上使用？

**Comment by xqzr** [comment]
贴配置。。

**Comment by liaoran** [comment]
客户端配置：
![ConfigInfo](https://user-images.githubusercontent.com/6219520/80485903-c9114380-898c-11ea-914f-dfab737ed546.png)
服务端配置：
按照v2ray官方新白话文指南上的配置进行的。

**Comment by liaoran** [comment]
客户端配置：
```
{
  "inbounds": [
    {
      "port": 1080,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
      "settings": {
        "auth": "noauth",
        "udp": false
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "xxx.xxx",
            "port": 443,
            "users": [
              {
                "id": "xxxxx",
                "alterId": 64
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "wsSettings": {
          "path": "/ray"
        }
      }
    }
  ]
}
```
服务端配置：
按照官方网站新白话文指南服务端配置进行的。

**Comment by liaoran** [comment]
问题已解决，同步Windows系统时间即可。
