### ISSUE TITLE
动态端口不能打开

### ISSUE THREAD

**Issue by qingfengshi** [v2ray/v2ray-core#246]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please answer the following questions before submitting your issue. Thank you.

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
1) What version of V2Ray are you using?
V2.0.0

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
2) What your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
使用http代理，通过switchyomega，通过vmess上Google或看YouTube视频

3) 你看到的不正常的现象是什么？
3) What did you see?
在配置文件中配置了动态端口，但是在服务器端查看端口使用情况发现实际没有使用动态端口，一直使用的是主端口，不会进行端口切换
![image](https://cloud.githubusercontent.com/assets/20433996/17888426/777a4d30-695d-11e6-9915-810c6382fcdb.png)

服务器端报错：
2016/08/23 11:04:23 [Warning]Point: Unable to find an inbound handler with tag: detour
2016/08/23 11:04:54 [Warning]Point: Unable to find an inbound handler with tag: detour
2016/08/23 11:05:17 [Warning]Point: Unable to find an inbound handler with tag: detour
2016/08/23 11:05:17 [Warning]Point: Unable to find an inbound handler with tag: detour
2016/08/23 11:05:17 [Warning]Point: Unable to find an inbound handler with tag: detour
2016/08/23 11:05:17 [Warning]Point: Unable to find an inbound handler with tag: detour
2016/08/23 11:05:17 [Warning]Point: Unable to find an inbound handler with tag: detour
2016/08/23 11:05:18 [Warning]Point: Unable to find an inbound handler with tag: detour
2016/08/23 11:05:19 [Warning]Point: Unable to find an inbound handler with tag: detour
2016/08/23 11:05:19 [Warning]Point: Unable to find an inbound handler with tag: detour
2016/08/23 11:05:33 [Warning]Point: Unable to find an inbound handler with tag: detour
2016/08/23 11:06:03 [Warning]Point: Unable to find an inbound handler with tag: detour

4) 你期待看到的正确表现是怎样的？
4) What do you expected to see instead?
能够使用动态端口

5) 请附上你的配置文件。
5) Please attach your configuration file.
服务器端配置文件：

```javascript
{
 "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 1045,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "uuid",
          "level": 1,
          "alterId": 99
        }
      ],
        "detour": {
          "to": "detour"
        }
    },
    "streamSettings": {
        "network": "kcp"
     }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "inboundDetour": [
    {
      "protocol": "vmess",
      "port": "1050",
      "tag": "detour",
      "settings": {},
      "streamSettings": {
        "network": "tcp"
      }
    }
  ],
  "inboundDetour": [
    {
      "protocol": "vmess",
      "port": "10050-10500",
      "tag": "detour",
      "settings": {
        "default": {
          "level": 1,
          "alterId": 99
        }
      },
      "streamSettings": {
        "network": "kcp"
      },
      "allocate": {
        "strategy": "random",
        "concurrency": 3,
        "refresh": 5
      }
    }
  ],
"inboundDetour":[
  {
    "protocol": "shadowsocks",
    "port": 10001,
    "settings": {
      "method": "chacha20",
      "password": "mypassword",
      "udp": false
    }
  },
  {
    "protocol": "shadowsocks",
    "port": 10002,
    "settings": {
      "method": "aes-256-cfb",
      "password": "mypassword",
      "udp": false
    }
  }
],
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  },
  "transport": {
    "kcpSettings": {
      "uplinkCapacity": 10,
      "downlinkCapacity": 10,
      "header": {
        "type": "none"
      }
    }
  }
}
```

**Comment by v2ray** [comment]
你的两个 vmess inboundDetour 都有 tag "detour"，冲突了，把 tcp 的那个删掉即可。

**Comment by qingfengshi** [comment]
将tcp里的tag删了，动态端口还是没有打开
![image](https://cloud.githubusercontent.com/assets/20433996/17919927/bdbf6130-6a03-11e6-87d0-eeabf2bfdeec.png)
使用shadowsocket还是连接不上。
我都开始怀疑是不是vps不允许动态端口了，我使用的是搬瓦工

**Comment by ToutyRater** [comment]
我的也是搬瓦工。要不你试试把 strategy 的 always 改成 random 看看有没有用

**Comment by ToutyRater** [comment]
说反了，是把 random 改成 always

**Comment by qingfengshi** [comment]
搞了一晚上，终于明白问题出在哪里了。
inbounddetour不能分开写，所有可能的绕路方式写在一个inbounddetour里就OK了
