### ISSUE TITLE
V2Ray能否安装在原版梅林上？不是Koolshare的改版

### ISSUE THREAD

**Issue by wans10** [v2ray/v2ray-core#2460]
V2Ray能否安装在原版梅林上？不是Koolshare的改版，求高人指点。路由器为华硕AC1900P

**Comment by kingwilliam** [comment]
可以（我试过），但我当时的 asus-merlin.內没有 iptables tproxy module 所以做 透明代理时只能代理tcp 不能代理udp.

详细我都是看 企业号https://enterpr1se.info/2017/10/v2ray-gfw-asuswrt-merlin/

**Comment by kingwilliam** [comment]
但要留意v2非常吃cpu,就算x86也不见得跑得快舒服（intel 3150N也只得12mbit/s vmess+tls+ws）， 华硕和草莓路由可能得10mbit/s甚至<5mbit/s
