### ISSUE TITLE
纯小白，从25号凌晨开始突然无法使用v2ray翻出去了，想求助一下看是服务器问题还是我设置问题

### ISSUE THREAD

**Issue by SpearOfFate** [v2ray/v2ray-core#2464]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V2.40
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
Chrome浏览器，Switchy Omega插件情景模式socks5，代理模式PAC
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

之前一直是使用朋友搭的服务器，扫描二维码连接的，从没出过什么问题，v2版本是2.40。翻墙方式是Chrome浏览器，Switchy Omega插件情景模式socks5，代理模式PAC。25号开始突然无法使用了，具体情况就是使用Chrome在切换到v2的情景模式下打开任何网页都显示ERR_TIMED_OUT，响应时间过长，在询问了朋友之后他给了另一个服务器的二维码，我扫描连上之后，打开网页显示的则是ERR_CONNECTION_CLOSED。他那边显示是可以用的，我本地设置DNS是8888和223.5.5.5，现在socks4和socks5均无法使用，更新v2版本之后还是不行，想询问一下有没有dalao们对这种情况发生的原因有没有可能的推测，或者简单的排除故障的操作，因为第一个服务器是由我俩共同的朋友（第三个人）在管理，这个人已经失联一个多月，不知道什么情况联系不上，所以也无法判断到底是不是服务器故障。

4) 你期待看到的正确表现是怎样的？
可以正常使用
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
```

客户端配置:

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by luneice** [comment]
同学你提供的东西不全，没法给你看哪里有问题。

**Comment by txdywy** [comment]
可能要换个朋友。。。

SpearOfFate <notifications@github.com> 于 2020年5月1日周五 上午3:08写道：
