### ISSUE TITLE
V2Ray 客户端 TLS的Bug，Windows、iOS和Android皆有。

### ISSUE THREAD

**Issue by okudayukiko** [v2ray/v2ray-core#2466]
Please read the [instruction](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md) and answer the following questions before submitting your issue. Thank you.
Please answer all the questions with enough information. All issues not following this template will be closed immediately.
If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2ray/discussion/issues) first.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 windows/amd64)

4) What's your expectation?
V2Ray客户端使用TLS且设置`"allowInsecure": false`。
如果客户端的`address`使用服务端域名，正常连接。
如果客户端的`address`使用服务端IP地址，`"serverName"`使用服务端域名，可能速度比上者慢。
5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

Client configuration:

```javascript
    // Please attach your client configuration here.
{
	"outbounds": [
		{
			"protocol": "vmess",
			"settings": {
				"vnext": [
					{
						"address": "",
						"port": "",
						"users": [
							{
								"id": "",
								"security": "auto"
							}
						]
					}
				]
			},
			"streamSettings": {
				"network": "tcp",
				"security": "tls",
				"tlsSettings": {
					"allowInsecure": false,
					"serverName": null
				}
			}
		}
	]
}
```

Please review your issue before submitting.

**Comment by okudayukiko** [comment]
![Screenshot](https://user-images.githubusercontent.com/17502357/80820692-f585c380-8c09-11ea-9f1a-49a9d1a2a871.jpg)
![Screenshot](https://user-images.githubusercontent.com/17502357/80820698-fa4a7780-8c09-11ea-90e3-2a845487d736.jpg)

**Comment by okudayukiko** [comment]
另外V2Ray能否listen到socket file（Linux）或named pipe（Windows）？

**Comment by kslr** [comment]
only linux
