### ISSUE TITLE
balancers 支持多种策略算法提议

### ISSUE THREAD

**Issue by weaving118** [v2ray/v2ray-core#2469]
Please describe the new feature you want in detail.
## 背景
路由协议中， `balancers` 现在默认是随机算法，比较单薄，不能满足如主备，ip_hash，按链路质量智能选择等

个人需求是按链路质量智能选择

## 提议
1, `balancers` 支持 `strategy` 配置，如 
```json
{
    "balancers": [
        {
            "tag": "balancer",
            "selector": [
                "proxy"
            ],
            "strategy": "round-robin"  // 负载均衡
        }
    ]
}
```

目前想到的有：
- `round-robin`: 轮询 默认策略
- `ip_hash`: 以目标IP hash，目标IP一样，出口一致
- `source_hash`: 以来源IP  hash, 来源IP一样， 出口一致
- `quality`：按线路质量，计算方案参考下面的
- `backup`: 备份线路

2, `outbounds` 支持 `quality` 配置，如
```json
{
    "outbounds": [
        {
            "protocol": "vmess",
            "quality": {
                "icmp": {
                    "server": "ip_address"  // 探测的IP地址，一般就是你的VPS地址了
                },
                "http": {
                    "url": "http://url"  // 探测的HTTP地址，给一个bin文件测试下载，没实际想到怎么做，只抛砖引玉下
                }
            }
        }
    ]
}
```
v2ray 根据quality的配置，如icmp，计算`round-trip min/avg/max/stddev`, `packet loss`，综合计算得到一个权重

## 如果没有这个， 传统的方案是
telegraf 监控下vps

![image](https://user-images.githubusercontent.com/57900564/80909599-11997a00-8d5c-11ea-9e87-22309956a3c1.png)

自己再写个脚本切换咯

如果内置这种策略，那么v2ray就更加的`smart`和厉害了。

**Comment by weaving118** [comment]
https://github.com/v2ray/v2ray-core/issues/2463， 这个Issue抽象就是`quality`策略需求

**Comment by tutacc** [comment]
目前只能用haproxy做负载均衡了

**Comment by weaving118** [comment]
没实际方案和需求处理人，先关了。

**Comment by IMconnor** [comment]
> 目前只能用haproxy做负载均衡和故障转移了

@tutacc 你好，用haproxy在客户端（linux网关）实现负载均衡和故障转移，配置和该链接
[https://www.mail-archive.com/haproxy@formilux.org/msg34273.html](url)
中描述的场景类似，v2ray是wss加web的模式，所以没办法像ss一样直接在haproxy里面把代理地址写在backend列表里，需要间接的，启动多个v2ray实例。

问题是在本地启动多个v2ray实例后，tcp健康检查（比如tcp-check）应该是没啥意义的，因为只是和本地回环地址建立tcp连接，检查不了这些socks5代理是否“健康”…，在haproxy里http检查好像也不能利用这些个socks5代理实现健康检查。

想知道你是怎么利用haproxy实现负载均衡的？

**Comment by tutacc** [comment]
> > 目前只能用haproxy做负载均衡和故障转移了
> 
> @tutacc 你好，用haproxy在客户端（linux网关）实现负载均衡和故障转移，配置和该链接
> [https://www.mail-archive.com/haproxy@formilux.org/msg34273.html](url)
> 中描述的场景类似，v2ray是wss加web的模式，所以没办法像ss一样直接在haproxy里面把代理地址写在backend列表里，需要间接的，启动多个v2ray实例。
> 
> 问题是在本地启动多个v2ray实例后，tcp健康检查（比如tcp-check）应该是没啥意义的，因为只是和本地回环地址建立tcp连接，检查不了这些socks5代理是否“健康”…，在haproxy里http检查好像也不能利用这些个socks5代理实现健康检查。
> 
> 想知道你是怎么利用haproxy实现负载均衡的？

直接使用[glider](https://github.com/nadoo/glider/)即可
