### ISSUE TITLE
failed to handler mux client connection

### ISSUE THREAD

**Issue by xwsaidph** [v2ray/v2ray-core#2470]
请问我用了WS+TSL+https+域名伪装
请问v2ray客户端测试68ms 但是测试速度就显示the remote server returned an error (503) server unavailable 
并且也不能联网

客户端里的错误代码是
[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.xxxx.club/youku.com):  > x509: certificate is valid for xxx.club, www.xxxx.club, not https://iqiyi.com/] > v2ray.com/core/common/retry: all retry attempts failed

这是客户端的配置

{
  "policy": null,
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "proxy",
      "port": 10xxx,
      "listen": "1xx.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "address": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "www.25xxx.club",
            "port": 443,
            "users": [
              {
                "id": "ad9a99c5-559c-4d5x5-84c4-e1719xxxefacb",
                "alterId": 64,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "serverName": "https://iqiyi.com/"
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/youku.com",
          "headers": {
            "Host": "https://iqiyi.com/"
          }
        },
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "stats": null,
  "api": null,
  "dns": null,
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "port": null,
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "ip": null,
        "domain": null
      }
    ]
  }
}

这个是v2ray客户端导出来的服务器配置（我是新手，不知道这样是否正确的导出配置了）

{
  "policy": null,
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": null,
      "port": 443,
      "listen": null,
      "protocol": "vmess",
      "sniffing": null,
      "settings": {
        "auth": null,
        "udp": false,
        "ip": null,
        "address": null,
        "clients": [
          {
            "id": "ad9a99c5-559c-4d55-84c4-e1719c8efacb",
            "alterId": 64,
            "email": "t@t.tt",
            "security": null
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "serverName": "https://iqiyi.com/"
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/youku.com",
          "headers": {
            "Host": "https://iqiyi.com/"
          }
        },
        "httpSettings": null,
        "quicSettings": null
      }
    }
  ],
  "outbounds": null,
  "stats": null,
  "api": null,
  "dns": null,
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": []
  }
}

时间已经校准了

不知道是什么原因，怎么样才能正常上网冲浪，求大神指导！

**Comment by kingwilliam** [comment]
因你的资料不够完整 只能尽现在有资料给点意见
(wss://www.xxxx.club/youku.com): > x509: certificate is valid for xxx.club, www.xxxx.club, not
你应该是有 xxx.club 电子证书 但你的server config 看不见

servername hostname 不用 https://
