### ISSUE TITLE
通过dokodemo-door进来的流量能不能也加个access log?

### ISSUE THREAD

**Issue by fcying** [v2ray/v2ray-core#2475]
inbound 是vmess socks http的流量.
都能看到类似这种的 access log
```
2020/05/10 16:44:33 tcp:192.168.1.10:13381 accepted tcp:live.github.com:443 [proxy]
2020/05/10 16:46:14 tcp:192.168.1.10:13427 accepted tcp:www.baidu.com:443 [direct]
```
通过dokodemo-door(全局透明代理)进来的流量, 在access log里面没东西. 

能不能给dokodemo-door进来的流量, 也加个access log?

**Comment by cyberskycat** [comment]
V2Ray version 4.23.4 
dokodemo-door 进来的流量没有日志,查问题困难
