### ISSUE TITLE
如软件开启时无网络连接 后续恢复网络之后域名不会自动重新解析

### ISSUE THREAD

**Issue by devinstever** [v2ray/v2ray-core#2480]
1) 你正在使用哪个版本的 V2Ray
4.19.1

2) 你的使用场景是什么
在电脑及移动设备正常使用该软件代理上网

3) 你看到的不正常的现象是什么
当配置文件里填写的节点地址为域名时。如果开启软件时没有网络连接，则后续设备网络连接恢复后，配置文件中相应的域名不会自动重新解析。

4) 你期待看到的正确表现是怎样的
如果地址为域名，则应在第一次尝试解析失败（dns服务器未应答）后，增加继续重试的间隔

**Comment by kingwilliam** [comment]
这个应是您的 系统(os) 或 路由(router) dns cache/buffer 有关.

**Comment by kingwilliam** [comment]
如真的介怀v2 tls ciphers这刻不够安全, 可考虑在v2前安装如haproxy程式.

再修改config到
```
global
    ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
    ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11 no-tlsv12 no-tls-tickets
```

这样应该比预设安全
