### ISSUE TITLE
Support kernel TLS

### ISSUE THREAD

**Issue by enihcam** [v2ray/v2ray-core#2481]
[Kernel TLS](https://www.kernel.org/doc/html/latest/networking/tls.html)
and
[Kernel TLS Offload](https://www.kernel.org/doc/html/latest/networking/tls-offload.html)

**Comment by nicholascw** [comment]
Guess it should be done by Golang rather than us as you are providing only Linux kernel documentation.

**Comment by enihcam** [comment]
> Guess it should be done by Golang rather than us as you are providing only Linux kernel documentation.

https://blog.filippo.io/playing-with-kernel-tls-in-linux-4-13-and-go/
