### ISSUE TITLE
kcp 模式报错

### ISSUE THREAD

**Issue by jekoie** [v2ray/v2ray-core#2483]
kcp模式之前用的好好的，现在用不了，报这样的提示错误。
**2020/05/15 14:17:18 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF**

**Comment by apfsx** [comment]
did you ever figure this out, i have same issued

**Comment by jekoie** [comment]
@apfsx No, i don't want to reconfigure my server so i use websocks style. Any ideas you have to solve it?

**Comment by teadrinker2015** [comment]
Same problem. I'm using a docker version. I just forgot to expose my port as udp ( default is tcp-only in docker compose )
"2020:2020"->"2020:2020/udp" fixed it
