### ISSUE TITLE
KCP method show "failed to process outbound traffic"

### ISSUE THREAD

**Issue by jekoie** [v2ray/v2ray-core#2485]
### Server Version: 
***V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/amd64)
A unified platform for anti-censorship.***

Server config:
```json
{
  "inbounds": [
    {
      "port": 9000,
      "listen": "0.0.0.0",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "93088c49-f7d9-41c3-8f54-9a2b86fd3999",
            "alterId": 32
          }
        ]
      },
      "streamSettings": {
        "network": "kcp",
        "security": "none",
        "kcpSettings": {
          "mtu": 1350,
          "tti": 20,
          "uplinkCapacity": 20,
          "downlinkCapacity": 20,
          "congestion": true,
          "readBufferSize": 20,
          "writeBufferSize": 20,
          "header": {
            "type": "utp"
          }
        }
      },
      "tag": "",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "rules": [
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  }
}
```
Client Config: 
![][1]

V2RayN show error log:
>启动服务(2020/5/16 9:28:18)......
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
2020/05/16 09:28:19 [Warning] v2ray.com/core: V2Ray 4.21.3 started
2020/05/16 09:28:19 tcp:127.0.0.1:51352 accepted tcp:clients4.google.com:443 [proxy] 
2020/05/16 09:28:21 tcp:127.0.0.1:51353 accepted tcp:www.google.com:443 [proxy] 
2020/05/16 09:28:29 tcp:127.0.0.1:51354 accepted tcp:www.google.com:443 [proxy] 
2020/05/16 09:28:29 tcp:127.0.0.1:51355 accepted tcp:www.google.com:443 [proxy] 
2020/05/16 09:28:29 tcp:127.0.0.1:51356 accepted tcp:www.google.com:443 [proxy] 
2020/05/16 09:28:30 tcp:127.0.0.1:51357 accepted tcp:www.google.com:443 [proxy] 
2020/05/16 09:28:49 [Warning] [699876753] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/05/16 09:28:51 [Warning] [4245525612] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/05/16 09:28:51 tcp:127.0.0.1:51358 accepted tcp:www.google.com:443 [proxy] 
2020/05/16 09:28:59 [Warning] [1886607717] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/05/16 09:28:59 [Warning] [4269412278] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/05/16 09:28:59 [Warning] [1248733380] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/05/16 09:28:59 tcp:127.0.0.1:51359 accepted tcp:www.google.com:443 [proxy] 
2020/05/16 09:29:00 [Warning] [2767908606] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/05/16 09:29:05 tcp:127.0.0.1:51360 accepted tcp:www.google.com:443 [proxy] 
2020/05/16 09:29:16 tcp:127.0.0.1:51361 accepted tcp:mtalk.google.com:5228 [proxy] 
2020/05/16 09:29:21 [Warning] [1144922230] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/05/16 09:29:29 [Warning] [2120866097] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/05/16 09:29:35 [Warning] [2843445562] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/05/16 09:29:46 tcp:127.0.0.1:51363 accepted tcp:74.125.203.188:5228 [proxy] 
2020/05/16 09:29:46 [Warning] [3419031464] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/05/16 09:29:51 tcp:127.0.0.1:51364 accepted tcp:www.google.com:443 [proxy] 
2020/05/16 09:30:16 [Warning] [3351446065] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF

## Is here one know how to do and know what happened?

[1]: https://user-images.githubusercontent.com/6836400/82107543-35e15780-975b-11ea-9922-36971045df1e.png

**Comment by teadrinker2015** [comment]
Same problem. I'm using a docker version. I just forgot to expose my port as udp ( default is tcp-only in docker compose )
"2020:2020"->"2020:2020/udp" fixed it
