### ISSUE TITLE
[建议] 添加自动端口转发的功能

### ISSUE THREAD

**Issue by ToutyRater** [v2ray/v2ray-core#249]
就目前来说，仍然无法得知墙的具体工作方式是什么，听说已经有部分 shadowsocks 和 shadowsocks-rss的服务器 ip 被封，但消息确切来源不清楚，无法确定真实度。

就个人看法，我是很看好 v2ray 发展，其潜力巨大。但是如今 v2ray 的用户量比起 shadowsocks 和 shadowsocks-rss 还远远不如，还未经过墙的考验。在主观感觉上我认为在同样的用户量条件下 v2ray 被检测到的概率会低一些，但这个概率应当是越低越好。现在我有一个想法也许能够进一步降低 v2ray 被检测到的机率。即添加一个功能，能够自动端口转发，实现：
在一个 vps 上部署有 http (https) 的网站，端口为如 10000 等非常见的 80 (443) 端口。同时此 vps 部署有 v2ray，v2ray 监听的端口是 80 (443) 。**当 v2ray 接收到来自 80 (443) 端口的数据包，先判断是否是 v2ray 客户端发送过来的翻墙数据，如果是则放行让其正常翻墙，如果不是则将数据包转发到 10000 端口** (或者进一步判断是否是正常的网页访问请求，是则转发，否则丢弃)。

如果有了这样的一个功能，再加上即将放出的 http outboud 的功能，两者配合使用的情况下应该会更加让墙难以识别出是翻墙流量。

（这是我一时之间想到的，也许有不妥当甚至是不对的地方，大家多包涵，`行内的莫鄙视`，`行外的不要喷`，有问题可以和气讨论（咦~~~ 我为什么要写这句话））

**Comment by v2ray** [comment]
此功能已在计划中，不同的层次的伪装会陆续上线。

**Comment by ToutyRater** [comment]
想得真周到
