### ISSUE TITLE
[Feature Request] http outbound支持連接https與http/2代理服務器

### ISSUE THREAD

**Issue by darhwa** [v2ray/v2ray-core#2491]
目前的http outbound只能支持plain http/1.1。雖然配置文件名義上支持tls，但諷刺的是，tcp.Dial裏把alpn限定爲單有"h2"，而http.Process又完全沒有支持h2的機制，造成http/1.1 over tls與h2都無法工作。

#2488 是爲解決這個問題。應用之後http outbound就可以連h2代理，比如帶forwardproxy插件的caddy。

**Comment by darhwa** [comment]
使用http outbound與caddy forwardproxy連，就類似於naiveproxy的工作方式。

**Comment by wd** [comment]
看到你的代码应该是合并了，我编译了最新的 master 代码可以支持我的 https 代理的，之前折腾老半天不行，以为是配置问题，原来是不支持，也是服气了。。。
