### ISSUE TITLE
Able to run on openwrt

### ISSUE THREAD

**Issue by v2ray** [v2ray/v2ray-core#25]
It would be great that V2Ray is able to run on a router so that the whole family surf the internet without blocking.

Current difficulties are:
* golang doesn't have a compiler option for openwrt;
* V2Ray still uses too much ram (~10M) which doesn't fit for a regular router.

**Comment by ohyeah521** [comment]
yes ，rom rand mem is a big problem for router.

**Comment by braveguywallce** [comment]
this has to be written by C again so it may fit for the Router, like the
shadowsocks-libev edition.

2015-09-24 19:06 GMT+08:00 ohyeah521 <notifications@github.com>:

**Comment by thrieu** [comment]
I am eager for that, thanks for your distribution. It's a great job for the human being.

**Comment by pminmax945** [comment]
@thrieu  if your router is ARM (or MIPS64 ,almost none) based , you can cross compile v2ray-core with google's go .or your router is MIPS32 based, you can try with gcc-go

**Comment by thrieu** [comment]
@pminmax945 年后试试。

**Comment by bettermanbao** [comment]
I can run golang helloworld on my $8 openwrt router, AR9341 MIPS32 with 16M ROM + 64M RAM. I will try to cross complie v2ray, to see if it could be fit into my router. But I have one suggestion, if v2ray could support the function like ss-redir, it would be perfect to install on router.

**Comment by v2ray** [comment]
V2Ray now has releases for ARM and MIPS64. They are capable to run on a router with less than 32M free memory.

There is no plan to support MIPS32 due to golang's restriction.
There is no plan to integrate with OpenWRT build system either at the moment.

**Comment by bettermanbao** [comment]
@v2ray I believe v2ray should be no problem to cross compile into mips32, I have successfully run kcptun (https://github.com/xtaci/kcptun) on my mips32 router. kcptun is written in go for fast data transfer using UDP. The only one I'm concerning is the performance, since most mips32 cpu is not powerful.
