### ISSUE TITLE
反馈问题 中文目录 配置测试

### ISSUE THREAD

**Issue by yjd** [v2ray/v2ray-core#250]
环境:
版本:V2Ray v2.0 (One for all) 20160820
系统:Debian GNU/Linux 8 (jessie)
代理方式:Chrome 通过 Socks/VMess 代理访问

问题:
1，windows客户端日志路径包含中文就出错。
举例

```
"log" : {
  "access": "D:\\access.txt",
  "error": "d:\\我的文档\\error.txt",
  "loglevel": "warning"
},
```

错误:
`2016/08/30 15:36:57 [Error]Failed to create error logger on file (d:\�ҵ��ĵ�\erro
r.txt): open d:\�ҵ��ĵ�\error.txt: The system cannot find the path specified.
2016/08/30 15:36:57 [Error]Failed to create Point server: open d:\�ҵ��ĵ�\error.t
xt: The system cannot find the path specified.`
这种问题采用unicode读写应该就能解决？

2，看了文档用:bash <(curl -L -s https://install.direct/go.sh)安装
测试配置文件:
/usr/bin/v2ray/v2ray -test /etc/v2ray/config.json
错误:
`V2Ray v2.0 (One for all) 20160820
An unified platform for anti-censorship.
2016/08/30 15:43:27 [Error]Failed to read server config file (/usr/bin/v2ray/config.json): /usr/bin/v2ray/config.jsonopen /usr/bin/v2ray/config.json: no such file or directory
2016/08/30 15:43:27 [Error]Failed to read config file (/usr/bin/v2ray/config.json): /usr/bin/v2ray/config.jsonopen /usr/bin/v2ray/config.json: no such file or directory`
读的位置竟然是错的？
本身配置内容是正确的能正常运行。估计读错位置

**Comment by yjd** [comment]
另外go安装脚本是把执行文件放在 /usr/bin/v2ray/v2ray 下多了v2ray目录。
导致在其他目录不能直接打v2ray命令（环境变量问题）需要全路径。
我自己手工把v2ray移到/usr/bin/v2ray。并改了下systemd服务配置文件里的路径。
方便调试测试不同配置文件。直接打v2ray -config kcp.json

**Comment by yjd** [comment]
同vps，ss和v2ray对比，用了kcp速度确实要快很多。

**Comment by v2ray** [comment]
1. d:\\我的文档 这个目录是否已经存在？V2Ray 不会自动创建目录的，运行前需要确保目录存在并有权限访问。

2. /usr/bin/v2ray/v2ray -test **-config** /etc/v2ray/config.json

3. 你可以把 /usr/bin/v2ray 加到 PATH 里。现在 v2ray 只有一个程序文件，但不排除将来有多个文件的情况，故放在一个独立的目录中。

**Comment by yjd** [comment]
1，不存在。新购买新安装的debian系统。第一次安装。问题应该是还是go脚本上。
2，这个我明白。我意思是linux一般丢执行文件或执行脚本在/usr/bin下。头一次遇到还创了个目录^_^
3，这样考虑，那明白了。不过我现在直接文件拷贝到我自己独立目录当绿色版使用了方便到处拷贝写个sh   执行。

**Comment by v2ray** [comment]
输出的方格是 console 的编码导致的，由于 Windows 的历史原因，不一定默认使用 Unicode，在输入输出的时候会有一些问题。V2Ray 的程序中默认 Unicode，没有对系统的编码进行适配。

这个问题在 core 中就不修了，交给客户端解决吧。
