### ISSUE TITLE
能不能加一个负载均衡，择优选择服务器的功能

### ISSUE THREAD

**Issue by Pseudo11** [v2ray/v2ray-core#2503]
Please describe the new feature you want in detail.
目前程序自带的轮询功能不好用，不能选择最快服务器，而且遇到出错服务器也不会绕过，会导致网页不能打开。这个功能对于现在网络现状来讲，是非常有必要的！请作者考虑下能否增加一个这样的功能，提升用户的体验度！

**Comment by azazjjyjjy** [comment]
最快怎么定义？延迟还是速度？延迟的话我觉得意义不大，故障转移功能和掉包最少的线路可能是最重要的

**Comment by ActiveIce** [comment]
用haproxy反代可以解决

**Comment by YijunYuan** [comment]
Duplicate of #1924

**Comment by yomnxkcs** [comment]
用haproxy要不要同时开很多个v2ray-core客户端，或者写很多个rounting把inbound/outbound一对一对连接起来？如果是这样，那服务器比较多的时候添加、删除会不会很麻烦？

> 用haproxy反代可以解决

**Comment by ActiveIce** [comment]
> 用haproxy要不要同时开很多个v2ray-core客户端，或者写很多个rounting把inbound/outbound一对一对连接起来？如果是这样，那服务器比较多的时候添加、删除会不会很麻烦？
> 
> > 用haproxy反代可以解决

不用  一个haproxy可以连接到多台服务器上面的v2ray后端  配置只需要写haproxy的  很简单

**Comment by yomnxkcs** [comment]
> > 用haproxy要不要同时开很多个v2ray-core客户端，或者写很多个rounting把inbound/outbound一对一对连接起来？如果是这样，那服务器比较多的时候添加、删除会不会很麻烦？
> > > 用haproxy反代可以解决
> 
> 不用 一个haproxy可以连接到多台服务器上面的v2ray后端 配置只需要写haproxy的 很简单

查了下haproxy的信息，我怀疑我们不在同一个频道上。我想实现的是在客户端，通过haproxy对机场提供的不受自己控制的多个服务器进行负载均衡。那些服务器可能使用vmess的ws/quic/tcp等各种传输协议。这种情况也可以用haproxy吗？可以简要写下配置示例吗？

**Comment by ActiveIce** [comment]
> > > 用haproxy要不要同时开很多个v2ray-core客户端，或者写很多个rounting把inbound/outbound一对一对连接起来？如果是这样，那服务器比较多的时候添加、删除会不会很麻烦？
> > > > 用haproxy反代可以解决
> > 
> > 
> > 不用 一个haproxy可以连接到多台服务器上面的v2ray后端 配置只需要写haproxy的 很简单
> 
> 查了下haproxy的信息，我怀疑我们不在同一个频道上。我想实现的是在客户端，通过haproxy对机场提供的不受自己控制的多个服务器进行负载均衡。那些服务器可能使用vmess的ws/quic/tcp等各种传输协议。这种情况也可以用haproxy吗？可以简要写下配置示例吗？

如果使用了很多不同的协议  haproxy也做不了

**Comment by rampageX** [comment]
glider

**Comment by yomnxkcs** [comment]
好的。感谢！

> > > > 用haproxy要不要同时开很多个v2ray-core客户端，或者写很多个rounting把inbound/outbound一对一对连接起来？如果是这样，那服务器比较多的时候添加、删除会不会很麻烦？
> > > > > 用haproxy反代可以解决
> > > 
> > > 
> > > 不用 一个haproxy可以连接到多台服务器上面的v2ray后端 配置只需要写haproxy的 很简单
> > 
> > 
> > 查了下haproxy的信息，我怀疑我们不在同一个频道上。我想实现的是在客户端，通过haproxy对机场提供的不受自己控制的多个服务器进行负载均衡。那些服务器可能使用vmess的ws/quic/tcp等各种传输协议。这种情况也可以用haproxy吗？可以简要写下配置示例吗？
> 
> 如果使用了很多不同的协议 haproxy也做不了

**Comment by 983231013** [comment]
首先，“最优”这个都没个基准，有了基准才说解决方法吧

**Comment by CHN008** [comment]
推荐使用trojan-qt5客户端，带有负载均衡功能。也支持很多协议，Vmess它也是支持的。

![trojan-qt5](https://user-images.githubusercontent.com/16646697/83642909-fed7c680-a5e1-11ea-93c4-87ad1bcb14df.png)

**Comment by Jason-2048** [comment]
> 推荐使用trojan-qt5客户端，带有负载均衡功能。也支持很多协议，Vmess它也是支持的。
> 
> ![trojan-qt5](https://user-images.githubusercontent.com/16646697/83642909-fed7c680-a5e1-11ea-93c4-87ad1bcb14df.png)

v2ray支持负载均衡，不过目前的只有轮询和随机，你这个估计也差不多。v2ray负载均衡的文档，官网的博客都有

**Comment by 1265578519** [comment]
这是gui的事情吧。。。和核心无关
