### ISSUE TITLE
萌新求助：failed to process outbound traffic 和 failed to find an available destination 

### ISSUE THREAD

**Issue by wangleibiancheng** [v2ray/v2ray-core#2506]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v2ray-core v2.1.0
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
使用 Chrome观看 YouTube 视频
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 72.19.12.55:36778: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
4) 你期待看到的正确表现是怎样的？
能翻墙就行
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

客户端配置:

```javascript
    // 在这里附上客户端配置
这是advance里面的情况
![image](https://user-images.githubusercontent.com/34955445/83207132-0718a780-a185-11ea-95be-d00c0fc6da7c.png)


  }，
  “运输”： {}
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
  v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 72.19.12.55:36778: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed


```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 darwin/amd64)
A unified platform for anti-censorship.
2020/05/29 07:37:30 [Info] v2ray.com/core/app/dns: DNS: created localhost client
2020/05/29 07:37:30 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1080
2020/05/29 07:37:30 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1090
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by VaslD** [comment]
友情提示：在 GitHub 上开 issue 强烈建议不要把个人信息明文贴出来；这次你泄漏了服务器地址和用户 ID，任何人都可以使用你的（或你购买的）服务器和帐号中转流量。

然后说问题，你的本地配置（国内计算机上）很可能有错误。建立在“你想直接翻墙”这个前提下，你本地使用的配置文件应该是你贴在“服务器端配置”的文件，而非你现在使用了贴在“客户端配置”的文件。原谅我使用了你的服务器和用户 ID 在国内网络做了测试，可以上 YouTube。

所以解决方法就是在你查看“客户端配置”的地方（设置软件或配置文件）把配置替换成“服务器配置”的内容；除非你有特殊需求和代理方式，否则不需要做其它任何修改。

**Comment by dwaynewei** [comment]
@VaslD  我也遇到了这个issue，同样的错误提示。   请问是把服务端的/etc/v2ray/config.json里的内容copy到client端的配置文件位置吗  看不太明白怎么解决这个问题 谢谢

**Comment by VaslD** [comment]
@dwaynewei 这个错误提示本意是出口无效（既当前计算机连接不到配置文件中的出口服务器）。我测试了原提问者两个配置文件中的参数，贴在“服务器”的部分可以用来访问 YouTube（当作出口），所以提了上述解决方案。

你遇到相同错误不代表配置文件需要调换。有可能是服务器已失效（“被墙”）、当前计算机完全没有网络、或者配置文件参数有误。

**Comment by wangleibiancheng** [comment]
> 友情提示：在 GitHub 上开 issue 强烈建议不要把个人信息明文贴出来；这次你泄漏了服务器地址和用户 ID，任何人都可以使用你的（或你购买的）服务器和帐号中转流量。
> 
> 然后说问题，你的本地配置（国内计算机上）很可能有错误。建立在“你想直接翻墙”这个前提下，你本地使用的配置文件应该是你贴在“服务器端配置”的文件，而非你现在使用了贴在“客户端配置”的文件。原谅我使用了你的服务器和用户 ID 在国内网络做了测试，可以上 YouTube。
> 
> 所以解决方法就是在你查看“客户端配置”的地方（设置软件或配置文件）把配置替换成“服务器配置”的内容；除非你有特殊需求和代理方式，否则不需要做其它任何修改。

谢谢你的解答

**Comment by wangleibiancheng** [comment]
> @dwaynewei 这个错误提示本意是出口无效（既当前计算机连接不到配置文件中的出口服务器）。我测试了原提问者两个配置文件中的参数，贴在“服务器”的部分可以用来访问 YouTube（当作出口），所以提了上述解决方案。
> 
> 你遇到相同错误不代表配置文件需要调换。有可能是服务器已失效（“被墙”）、当前计算机完全没有网络、或者配置文件参数有误。

特别奇怪，我后面更新了我的brew之后，就可以翻墙了。我没有更新我的v2ray里面的东西

**Comment by dwaynewei** [comment]
@VaslD   这样的哈  懂了。   
情况1：被墙。  服务器IP一直可以ping通，昨晚到今天上午基本零丢包，刚刚ping的有25%丢包。  telnet + IP的结果是 operation timed out，unable to connect to remote address.    更换了两次端口，服务端的端口跟服务器是开启状态，但电脑上v2rayN的日志里还是一样的错误。 

情况2：当前计算机没有网络。   应该是有网络，在电脑上的v2rayN设置里换到另一个稳定的VPS可以正常使用

情况3：配置文件参数有误。   服务器端的v2ray配置是按照那种三条命令直接安装的，没有自定义配置文件。 电脑上的v2ray配置是import的服务端v2ray 配置生成的url链接，主要参数试过几次还没有发现错误。   

请问这个情况就是被墙了吗？

**Comment by VaslD** [comment]
@dwaynewei 很有可能。我也没有任何办法「确认」某服务器是否被墙，所以基本上换端口也连不通就考虑换个服务器吧。另外你看下原作者说的方法有没有帮助，如果你不用 macOS 和 brew 包管理器就忽略。

**Comment by Mr-zhengyuxiao** [comment]
11**听   0**  @VaslD 4 ****迟_ 呵____71听@_

**Comment by oooker** [comment]
我的是服务器端口TCP port没有打开，把安装脚本里设置的默认端口打开就行了。
firewalld
firewall-cmd

**Comment by Carlos-Saron** [comment]
2021/05/16 00:19:43 127.0.0.1:60236接受//www.google.com：443[代理]

2021/05/16 00:19:43[警告][2652764687]github.com/v2fly/v2ray-core/v4/app/proxyman/outbound:处理出站流量失败>github.com/v2fly/v2ray-core/v4/proxy/vmess/outbound:连接结束>github.com/v2fly/v2ray-core/v4/proxy/vmess/outbound:读取头失败>github.com/v2fly/v2ray-core/v4/proxy/vmess/encoding:读取失败响应头>tls:必须在tls.Config中指定ServerName或unsecureskipverify

2021/05/16 00:19:43 127.0.0.1:60238接受//www.google.com：443[代理]

2021/05/16 00:19:43[警告][3233721459]github.com/v2fly/v2ray-core/v4/app/proxyman/outbound:无法处理出站流量>github.com/v2fly/v2ray-core/v4/proxy/vmess/outbound:连接结束>github.com/v2fly/v2ray-core/v4/proxy/vmess/outbound:读取头失败>github.com/v2fly/v2ray-core/v4/proxy/vmess/encoding:读取失败响应头>tls:必须在tls.Config中指定ServerName或unsecureskipverify


大佬，看看帮忙这是什么情况，换了个网络就成这样了

**Comment by Carlos-Saron** [comment]
@oooker

**Comment by VaslD** [comment]
看 Releases 写 v2ray 最近更新了 TLS 相关功能和文档，如果升级了版本建议对照一下文档看看配置。

另外检查下是否开着其它代理、VPN、HTTP 分析和包检查工具 (Proxyman, Wireshark)，考虑先停止或退出以确认是不是工具干扰引起的。

**Comment by hoshidango** [comment]
我也遇到了这个问题，用的是 vultr 的服务器，服务器显示默认防火墙关闭，但实际上它并没有开启 tcp 端口，我用的是 debian os，使用了 sudo ufw allow xxxx 之后就可以正常使用了（tcping 通了，原来不通）
