### ISSUE TITLE
求教 几个概念性问题

### ISSUE THREAD

**Issue by maxchendt** [v2ray/v2ray-core#251]
1   v2ray 服务器和客服端的软件相同，只是配置文件不同，对吗？

2   关于原版 Shadowsocks 协议，服务器端 inboundDetour 起了 Shadowsocks 协议，是不是服务器端不需要安装 Shadowsocks 软件了？也就是说 v2ray 此时相当于提供了 ss-server 服务？

3   对于v2ray中转服务器，如下方式中转ss可以吗？
   a     用端口映射方式，中转服务器直接连ss-server
   b    中转方式， ss client <--> v2ray 中转 <--vmss--> v2ray server <--> ss server。 **应该是不可行的**。如果可行，请问如何将  v2ray 中转 中的 inboundDetour （用 什么协议？Shadowsocks 协议？ ） 与 outboundDetour （用 vmss协议）串起来？类似的， v2ray server 上，又如何将inboundDetour （vmss 协议），转给 outboundDetour （ 用什么协议？Shadowsocks协议？）， 能给给示范性的配置json吗 （虽然 ss流量封装在）

4  v2ray中转服务器，用 haproxy 中转 v2ray （tcp方式我成功用 haproxy中转），性能和开销都比v2ray好。v2ray 中转方式的优势可能只是提供国内外自动路由，这是我的理解，对吗？

**Comment by ToutyRater** [comment]
1. 对
2. 是的
3. a 方式亲测没问题；b 方式不行，如果出 ss 协议的 outbound 则可以实现（似乎已在计划中）
4. 我没有使用过也不了解 haproxy ，对此不作评价。对于 `v2ray 中转方式的优势可能只是提供国内外自动路由`这样的判断我认为不够中肯，v2ray 耗性能是事实，提供路由功能也是事实，如果需要较低的性能消耗及路由功能可以有其它选择（如 cow+shadowsocks）。v2ray 的优点还有 TLS 、kcp、多传入多传出等。选择合适自己的就好

**Comment by v2ray** [comment]
楼上回答基本正确。

对于 3， 现在已有 Shadowsocks outbound，可以用于 3.b 的中转。

**Comment by tufu9441** [comment]
@maxchendt 麻烦请教一下您所说的4具体是如何实现的？我在中转服务器上用iptables或者haproxy都没能尝试成功转发v2ray的流量，我用的是v2ray+websocket+tls+caddy的方式。

**Comment by maxchendt** [comment]
用了一段时间，两三年不用该方式了
`cat /etc/haproxy/haproxy.cfg`

相关内容如下(网络都为IPv4/v6双栈环境, 给出的是真实配置，bwg 的 服务器已经弃用)

```
global
        ulimit-n  51200
        user haproxy
        group haproxy
        daemon

defaults
        log global
        mode    tcp
        option  dontlognull
	timeout connect 1000ms
        timeout client 150000ms
        timeout server 150000ms

#v2ray, 5g.bwg
listen v42683
        bind *:42683
#        server srv42683 104.224.152.205:42683 maxconn 4096
        server v6sr42683 2607:8700:102:fae4:::42683 maxconn 4096

```

**Comment by tufu9441** [comment]
谢谢您！我在网上有找到过跟您类似的配置用于SS的中继，但是我一直未能尝试成功，可能是由于我用的是websocket+tls+web的方式？wss的流量好像无法直接转发过去。
2019年6月23日 +0800 09:41 塔哥 (CHEN Deng-Ta) <notifications@github.com>，写道：

**Comment by zc813** [comment]
@tufu9441 您后来解决了吗？我只用 TLS+TCP 也没有中转成功。不开 TLS 就可以。困惑。

**Comment by tufu9441** [comment]
@zc813 没有，现在不折腾中转了。

**Comment by peter-tank** [comment]
@zc813 https://github.com/v2ray/v2ray-core/issues/1736

**Comment by depfish** [comment]
@tufu9441 @zc813 

感觉ws + tls 是不能用tcp直接中转的方式(nginx tcp / haproxy/ iptables)，貌似只能用v2ray来中转

**Comment by Mon-ius** [comment]
PROXY protocol
