### ISSUE TITLE
Add Windows ARMv7 build

### ISSUE THREAD

**Issue by MarksonHon** [v2ray/v2ray-core#2516]
Please describe the new feature you want in detail.
Although Microsoft Windows 10 ARM64 (Win10 A64)  can use the x86 version v2ray but it is slow on this OS, and an ARMv7 build can be faster on Win10 A64, so please provide an Windows ARMv7 build please, thanks.

**Comment by kslr** [comment]
try https://github.com/v2ray/v2ray-core/releases/download/v4.23.2/v2ray-linux-arm.zip

**Comment by MarksonHon** [comment]
> try https://github.com/v2ray/v2ray-core/releases/download/v4.23.2/v2ray-linux-arm.zip

This is **the Linux version** but I need **Windows ARMv7 version** 🤣
Trojan-Go has provide Windows ARMv7 version, and v2ray is also wirtten in Golang, so I think it may not be a diffcult job to do.

**Comment by rprx** [comment]
应该是 ARMv8 的 AArch64 吧？

**Comment by MarksonHon** [comment]
> 应该是 ARMv8 的 AArch64 吧？

目前Golang还没有把ARM64整合，所以目前只能编译32位的。而32位的Golang现在能做。

**Comment by nicholascw** [comment]
dup with #2261 . Wont fix until Golang supports Win ARM64.

**Comment by wangfys** [comment]
@nicholascw  Hello, Go1.17.1 has supported Windows/ARM64 already. Is it possible to support it now?
