### ISSUE TITLE
install-direct.sh doesn't verify zip file signature?

### ISSUE THREAD

**Issue by galvasis193** [v2ray/v2ray-core#2519]
I believe many users use https://install.direct/go.sh to install v2ray to their system.
But downloadV2ray function in this script don't seem to verify zip file signature.
Am I correct?

https://github.com/v2ray/v2ray-core/blob/4b81ba947f89218ea7c99362b43beeeb5c3cf37b/release/install-release.sh#L173

**Comment by galvasis193** [comment]
Maybe developers could publish their gpg public key and modify build script so that users can verify if their downloaded package is from a trusted source?

I'd like to contribute to this.

**Comment by kslr** [comment]
Yes we need to fix this
