### ISSUE TITLE
tls websocket nginx 连接失败问题 非时间问题

### ISSUE THREAD

**Issue by Aimer-ite** [v2ray/v2ray-core#2520]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

用的搬瓦工的vps 系统是Debain 9
校对过时间 使用v2ray默认配置正常连接 nginx搭载的网站用http https正常连接 连接domain/ray界面显示404
litsen10000端口改成别的端口还是无法连接
etc中有seLinux地址内只有semanage.conf文件 输入setsebool找不到命令
纠结好几天了 不知道怎么下手 求大佬帮忙排下错

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
服务器 v4.23.2
客户端 v4.23.1
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
Chrome使用SOCKS Proxy插件
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
Error_Connection_Closed
4) 你期待看到的正确表现是怎样的？
正常连接google
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
   {
  "log":{
     "access": "/etc/v2ray/access.log",

     "error": "/etc/v2ray/error.log",

    "loglevel": "warning"

},
"inbound": {
    "port": 10000, 
    "listen":"127.0.0.1",
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "", 
          "alterId": 64
        }
      ]
    },
    "streamSettings":{ 
      "network":"ws", 
      "security": "auto", 
      "wsSettings": {
         "connectionReuse": true,
         "path": "/ray" 
     }
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ]

}
```

客户端配置:

```javascript
    // 在这里附上客户端配置
   {
  "log": {
    // By default, V2Ray writes access log to stdout.
     "access": "D:\\v2Ray\\access.log",

    // By default, V2Ray write error log to stdout.
     "error": "D:\\v2Ray\\error.log",

    // Log level, one of "debug", "info", "warning", "error", "none"
    "loglevel": "warning"
  },
  // List of inbound proxy configurations.
  "inbounds": [{
    // Port to listen on. You may need root access if the value is less than 1024.
    "port": 1080,

    // IP address to listen on. Change to "0.0.0.0" to listen on all network interfaces.
    //"listen": "127.0.0.1",

    // Tag of the inbound proxy. May be used for routing.
    //"tag": "socks-inbound",

    // Protocol name of inbound proxy.
    "protocol": "socks",

    // Settings of the protocol. Varies based on protocol.
    "settings": {
      "auth": "noauth",
      "udp": false
      //"ip": "127.0.0.1"
    },

    // Enable sniffing on TCP connection.
    "sniffing": {
      "enabled": true,
      // Target domain will be overriden to the one carried by the connection, if the connection is HTTP or HTTPS.
      "destOverride": ["http", "tls"]
    }
  }],
  // List of outbound proxy configurations.
  "outbounds": [{
    "protocol": "vmess",
	 "settings": {
        "vnext": [
          {
            "address": "",
            "port": 443,
            "users": [
              {
                "id": "",
                "alterId": 64
              }
            ]
          }
        ]
	},
	"streamSetting": {
	  //"network": "tcp",
	  "network": "ws",
	  "security": "tls",
	  
	  "wsSettings": {
	    "path": "/ray"
	  }
	},
    "mux": {"enabled": true}
  },
"routing": {
    "domainStrategy": "IPOnDemand",
    "rules":[
      //{
        // Blocks access to private IPs. Remove this if you want to access your router.
        //"type": "field",
        //"ip": [
		       //"geoip:private"
		       //"geoip:cn"
			   //],
        //"outboundTag": "direct"
      //},
	  {
	    "type": "field",
		"domain": ["geosite:cn"],
		"outboundTag": "direct"
	  }
    ]
  }
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
   2020/05/31 03:17:32 [Warning] v2ray.com/core: V2Ray 4.23.1 started
2020/05/31 04:32:19 [Warning] v2ray.com/core: V2Ray 4.23.1 started
2020/05/31 04:52:31 [Warning] v2ray.com/core: V2Ray 4.23.2 started
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
  2020/05/31 15:22:56 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/05/31 15:23:12 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/05/31 15:23:57 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp MyVpsIp:443: i/o timeout dial tcp MyVpsIp:443: connectex: A socket operation was attempted to an unreachable network. dial tcp: lookup MyDomain: no such host] > v2ray.com/core/common/retry: all retry attempts failed
2020/05/31 16:33:54 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > EOF
2020/05/31 16:34:11 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > read tcp MyIp:64546->MyVpsIp:443: wsarecv: An invalid argument was supplied.
2020/05/31 16:34:14 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp MyVpsIp:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions.] > v2ray.com/core/common/retry: all retry attempts failed
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
   空的
```

8) 其它相关的配置文件（如 Nginx）和相关日志。
Nginx配置
server {
    listen       443 ssl http2 default_server;
    listen       [::]:443 ssl http2 default_server;
    server_name  www.aimeritev3.us;
    root         /usr/share/nginx/html;

    ssl_certificate "conf.d/key/aimeritev3.crt";
    ssl_certificate_key "conf.d/key/aimeritev3.key";
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location /ray {
    if ($http_upgrade != "websocket") { # WebSocket协商失败时返回404
        return 404;
    }
    proxy_redirect off;
    proxy_pass http://127.0.0.1:10000;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    }
}

访问日志 

84.17.34.150 - - [31/May/2020:04:53:20 -0400] "\x05H\xFA\x1E\x1C\x82\xDAh\x95@*\xF1\xE9\xD6\xA1\x9F\x84-\x16\x87\x018\xE5\xEB\x1D\xB78\xDD\x90LQ/\x14\xE7\x1A\x06L\xCD\x05F\xDC\xE0\x0B\xE6\xBB{\xC3\x10]h6 %\x998\xE2\xE1B\x19L3\x1C\xD1\xCEl\xEE'0\xFA\x8F,\x1E\x13\xF5\xF5\x03\xA6F\xCA\x09'A\x92O\xF0\xF6I\xB7\xF2\x9C\xE5=\xF5\xBFa\x9CRs\xA0\xDC\xC9,H|L\x93\x981\xD1\x0F7G7hg\xE7U\xF4\x05\x86w\x90\x97\xE0\xD4$TK\xF28f,\x1B\x98O\xFC\x8E\x09f.\xEC\xB3\xFF\xA3\xA9\x80\xF7\xB6\x09\x95\x19\x8B3m9b~((\xDE\xB5\xE92\xCEN\xCET\x04^\xB6\x83<p\xE6\xA9\xB4\x899Q\xA1RXk\x9E\x13\xF1\xF7:\x12b\x83;D\xBF\xD7\xF7\x09g\xE8\xE2\x98\x81\xAFb\xFD\xF0\x84\xDB\x89\xB1\xBA\xF6\xC2\x11\xD0\xC2\xFC\xA0[\x1C\x12`\xED\x22\xC38W7\xEA9\xE6:d\x89\xD4\xED\xF3\x84\x93\xED\xC7\x91\xC8\xCC\x93\xAB\x89\x0ER\x1F\x8D\xAF\xBA\xB6.X\xDA\x0B\x0B\xD7\xE9\x82\xC0Y3\x06\x98\xA79k\xF4c\xE48j\x13\xC1\xEEa\x8Cp\xEA,~\x93\xE4\x8F\xBE\xBB\xDEk\xEC8\x17b@~5\x94\xF7\xCC\xA7\x97\xF6\x12d\x91$d\x93\x10>\x8F\xA3P\xB5Hsp\x97ygU|\x85Q\xAA\xCB\x98=\x01\xA57\x98\xFF\x8B\x96q\xC3 1p\x80\xF1\x09\xB9\x0C\xED\xC7 \xA83\xA3\xBE\x03'@-\x9B\xD3P\xD8@\xBC\xBF@)\xC7\xCB\xC5uvz\xBD\x19" 400 173 "-" "-"
84.17.34.150 - - [31/May/2020:04:54:03 -0400] "\x1D\xC4SZ\x86\xFD\xCA\xAF\xFAk\xE9\xA1\x97\xFF\x84\xC3N=\xAA\x10\xEB\x97.\xDD\xDBs8P\x02BE\xD3hx\xDE\xFA\x91\xA0\xB0jNu\xA3\xE0\xE3\xB0S\xAEBP1\xA0\xA2\xA4\xC1R\xEB\x80)\x97X\xB5\xE4\xD8\x83\x19\x8D\x1Bq\x8B\x18\x9DV\x05a\x89\x8D`\x16\xB1we\xFB\x92\xD78}\x09n\x9C\x86@v\x1A9\xD8\xE34\xD0\x8A\xCF%\xFC\x1A\xD9)l\xEC\x1B\xD1\xE6\xA4\xB7\xDF\xB4? \xA4\xE3I1@J\xC6\x15\xDBKc2\xED\xA4\xE2l%\xD5\x95\x98\xD5j1P\xF6\xE8'9B\xB6\xF4mxx\x11\xFF_B\xCD\x997{\xEC\x84\x80X\xBF\xB1\x93\x81\x97\xE4\x87\x03\xB9<\x1F\xB1`|]\xED\xFF\x0E;yw\xED\xB1\xD5@\x87\xFF\x81\xC6Y\xC4\xD4\x9C\xBB\xB3\xF6\xBF\xFB\x9A\x9A\xCDyk\xC5c\x0C.\x82W\xB8\xB5\xAB\xBAW\x1A\xFF\xDAY\xE2\x8BPtr\x01\x00" 400 173 "-" "-"
84.17.34.150 - - [31/May/2020:04:54:04 -0400] "I\xF3\xCE\x9B\xB0WCm9\x87\xD9\xDF6{fEd\x7F\xF2\x89j7\x99a\xC1\xB5\xAF_\x19T\xF5\xAB\xE9\x84\xFA\x10\x00\xF5!\xE5\x15\x1F\xB0DF\x97\xC6#K6;\xD4\xB3\x5C*z\x13\x15\x89\x9FU(5\x9Dj\x80\xCD\xD0Yd\xE2\xB9\xCA6\x87g\x14" 400 173 "-" "-"
84.17.34.150 - - [31/May/2020:04:54:08 -0400] "9\xDC\xACS;\xB9\x1D\xDF\x10\x91\xAA@\xF7\x1FV\x14\xEC\xD1v\xB6\xE3\xA9\xE5\xA5\xAC.\xA2\xE7}i\xE8\xEB\x13\xA4n\xAC\x97\x00\x97\xEF\x02$V`\xE1\xA9*\xECl\xC7\x83\xF5r\xD8|i\xB5\x0Bz\xE1\x1B\x87V\x19\xF1v%\x15>j?\x15\xC7TH\x05il\xF3\xAFPK+" 400 173 "-" "-"

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。
正常启动

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by nicholascw** [comment]
需要升级客户端。#2518
