### ISSUE TITLE
v4.23.2 版本客户端在树莓派运行时出现 segfault

### ISSUE THREAD

**Issue by zhoubowen-sky** [v2ray/v2ray-core#2525]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
 > 客户端服务端版本均为 v4.23.2
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
 > 服务器运行 v2ray+ws+tls+nginx ，客户端使用树莓派Armv7对局域网提供http代理，局域网设备使用http代理上网
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
 > 树莓派armv7客户端 的进程运行不到两分钟就异常退出。将客户端程序在前台手动启动提示如下：
root@rasp:/usr/local/sbin/v2ray# /usr/local/sbin/v2ray/v2ray -confdir /usr/local/sbin/v2ray/config
V2Ray 4.23.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.1 linux/arm)
A unified platform for anti-censorship.
2020/06/01 16:28:37 Using confdir from arg: /usr/local/sbin/v2ray/config
2020/06/01 16:28:39 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  /usr/local/sbin/v2ray/config/config.json
段错误
root@rasp:/usr/local/sbin/v2ray# 
4) 你期待看到的正确表现是怎样的？
 > 能够正常使用
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
{
    "inbounds": [
        {
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            },
            "port": 10001,
            "listen": "127.0.0.1",
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "xxxxxx",
                        "alterId": 64,
                        "security": "auto",
                        "level": 0
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "wsSettings": {
                    "path": "/xxxx"
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {}
        },
        {
            "protocol": "blackhole",
            "settings": {},
            "tag": "block"
        }
    ],
    "routing": {
        "domainStrategy": "AsIs",
        "rules": [
            {
                "type": "field",
                "outboundTag": "block",
                "protocol": [
                    "bittorrent"
                ]
            }
        ]
    },
    "log": {
        "access": "/xxx/access.log",
        "error": "/xxx/error.log",
        "loglevel": "warning"
    },
    "policy": {
        "levels": {
            "0": {
                "handshake": 6,
                "connIdle": 300,
                "uplinkOnly": 4,
                "downlinkOnly": 8,
                "statsUserUplink": false,
                "statsUserDownlink": false,
                "bufferSize": 4096
            }
        },
        "system": {
            "statsInboundUplink": false,
            "statsInboundDownlink": false
        }
    }
}
```

客户端配置:

```javascript
    // 在这里附上客户端配置
{
    "log": {
        "access": "/var/log/v2ray/access.log",
        "error": "/var/log/v2ray/error.log",
        "loglevel": "warning"
    },
    "dns": {
        "servers": [
            "114.114.114.114",
            {
                "address": "8.8.8.8",
                "port": 53,
                "domains": [
                    "geosite:geolocation-!cn",
                    "geosite:speedtest",
                    "ext:h2y.dat:gfw"
                ]
            }
        ]
    },
    "inbounds": [
        {
            "port": 10001,
            "protocol": "http",
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            },
            "settings": {
                "auth": "noauth"
            }
        },
        {
            "port": 10002,
            "protocol": "socks",
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            },
            "settings": {
                "auth": "noauth"
            }
        }
    ],
    "outbounds": [
        {
            "tag": "direct",
            "protocol": "freedom",
            "settings": {}
        },
        {
            "tag": "block",
            "protocol": "blackhole",
            "settings": {}
        },
        {
            "tag": "proxy1",
            "protocol": "vmess",
            "settings": {
                "vnext": [
                    {
                        "address": "xxxx.com",
                        "port": 443,
                        "users": [
                            {
                                "id": "xxxx",
                                "alterId": 64,
                                "security": "auto",
                                "level": 0
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "security": "tls",
                "wsSettings": {
                    "path": "/xxxx"
                }
            },
            "mux": {
                "enabled": true,
                "concurrency": 30
            }
        },
        {
            "tag": "proxy2",
            "protocol": "vmess",
            "settings": {
                "vnext": [
                    {
                        "address": "xxxx",
                        "port": 443,
                        "users": [
                            {
                                "id": "xxxx",
                                "alterId": 64,
                                "security": "auto",
                                "level": 0
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "security": "tls",
                "wsSettings": {
                    "path": "/xxx"
                }
            },
            "mux": {
                "enabled": true,
                "concurrency": 30
            }
        }
    ],
    "policy": {
        "levels": {
            "0": {
                "handshake": 6,
                "connIdle": 300,
                "uplinkOnly": 4,
                "downlinkOnly": 8,
                "statsUserUplink": false,
                "statsUserDownlink": false,
                "bufferSize": 2048
            }
        },
        "system": {
            "statsInboundUplink": false,
            "statsInboundDownlink": false
        }
    },
    "routing": {
        "domainStrategy": "IPOnDemand",
        "balancers": [
            {
                "tag": "proxy",
                "selector": [
                    "proxy1",
                    "proxy2"
                ]
            }
        ],
        "rules": [
            {
                "type": "field",
                "balancerTag": "proxy",
                "domain": [
                    "ext:h2y.dat:gfw",
                    "v2fly.org",
                    "telegram.org",
                    "docker.com",
                    "raspberrypi.org",
                    "bintray.com"
                ]
            },
            {
                "type": "field",
                "outboundTag": "block",
                "domain": [
                    "ext:h2y.dat:ad"
                ]
            },
            {
                "type": "field",
                "outboundTag": "direct",
                "network": "udp,tcp"
            }
        ]
    }
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
2020/05/29 22:51:28 [Warning] v2ray.com/core: V2Ray 4.23.1 started
2020/05/30 04:00:16 [Warning] v2ray.com/core: V2Ray 4.23.1 started
2020/05/31 04:00:16 [Warning] v2ray.com/core: V2Ray 4.23.1 started
2020/06/01 04:00:17 [Warning] v2ray.com/core: V2Ray 4.23.1 started
2020/06/01 16:15:05 [Warning] v2ray.com/core: V2Ray 4.23.2 started
error.log只有上述日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
2020/06/01 16:19:41 [Warning] v2ray.com/core: V2Ray 4.23.2 started
2020/06/01 16:20:47 [Warning] v2ray.com/core: V2Ray 4.23.2 started
2020/06/01 16:22:48 [Warning] v2ray.com/core: V2Ray 4.23.2 started
2020/06/01 16:24:55 [Warning] v2ray.com/core: V2Ray 4.23.2 started
2020/06/01 16:26:18 [Warning] v2ray.com/core: V2Ray 4.23.2 started
2020/06/01 16:28:40 [Warning] v2ray.com/core: V2Ray 4.23.2 started
客户端error.log同样只有上述内容，但是前台启动进程后有如下日志

root@rasp:/usr/local/sbin/v2ray# /usr/local/sbin/v2ray/v2ray -confdir /usr/local/sbin/v2ray/config
V2Ray 4.23.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.1 linux/arm)
A unified platform for anti-censorship.
2020/06/01 16:28:37 Using confdir from arg: /usr/local/sbin/v2ray/config
2020/06/01 16:28:39 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  /usr/local/sbin/v2ray/config/config.json
段错误
root@rasp:/usr/local/sbin/v2ray# 


上述【段错误】三个字为客户端程序前台启动运行一小会后闪退，打印的内容。

```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

程序启动正常，但启动后不到两分钟就闪退，经检测配置文件是正常的，
root@rasp:/usr/local/sbin/v2ray# ./v2ray --test --confdir /usr/local/sbin/v2ray/config/
V2Ray 4.23.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.1 linux/arm)
A unified platform for anti-censorship.
2020/06/01 16:43:02 Using confdir from arg: /usr/local/sbin/v2ray/config/
2020/06/01 16:43:05 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  /usr/local/sbin/v2ray/config/config.json
Configuration OK.
root@rasp:/usr/local/sbin/v2ray# 

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by zhoubowen-sky** [comment]
>【补充】下载 4b81ba947f89218ea7c99362b43beeeb5c3cf37b 节点的代码，在树莓派ARMv7上自行编译v2ray二进制程序运行无异常，从项目release下载的二进制文件(https://github.com/v2ray/v2ray-core/releases/download/v4.23.2/v2ray-linux-arm.zip) 运行有上述有异常。
编译环境如下：
root@rasp:/tmp/4.23.2# go version
go version go1.14.3 linux/arm
root@rasp:/tmp/4.23.2# gcc --version
gcc (Raspbian 8.3.0-6+rpi1) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

不排除是项目使用的CI交叉编译引起的问题

**Comment by kslr** [comment]
试试最新的

**Comment by zhoubowen-sky** [comment]
- 4.23.3版本依旧存在此BUG。
> root@rasp:/usr/local/sbin/v2ray# ```./v2ray_4.23.3 -version```
V2Ray 4.23.3 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.1 linux/arm)
A unified platform for anti-censorship.
root@rasp:/usr/local/sbin/v2ray# ```./v2ray_4.23.3 -confdir config/```
V2Ray 4.23.3 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.1 linux/arm)
A unified platform for anti-censorship.
2020/06/02 10:24:41 Using confdir from arg: config/
2020/06/02 10:24:43 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  config/config.json
段错误
root@rasp:/usr/local/sbin/v2ray# ```date```
2020年 06月 02日 星期二 10:25:45 CST
root@rasp:/usr/local/sbin/v2ray# 

- 4.23.1 版本是没有这个问题的
> 如果编译参数一直没变过，则可能是从4.23.2之后项目更换或新增了某个依赖库所致

**Comment by kslr** [comment]
这可能需要一点时间，你可以继续尝试深入调查

**Comment by gitgayhub** [comment]
> * 【补充】基本判定为项目使用的CI交叉编译环境的问题
> 
> > 下载 [4b81ba9](https://github.com/v2ray/v2ray-core/commit/4b81ba947f89218ea7c99362b43beeeb5c3cf37b) 节点的代码，在树莓派ARMv7上自行编译v2ray二进制程序运行无异常，从项目release下载的二进制文件(https://github.com/v2ray/v2ray-core/releases/download/v4.23.2/v2ray-linux-arm.zip) 运行有上述有异常。
> 
> * 树莓派ARMv7编译环境如下：
> 
> > root@rasp:/tmp/4.23.2# go version
> > `go version go1.14.3 linux/arm`
> > root@rasp:/tmp/4.23.2# gcc --version
> > `gcc (Raspbian 8.3.0-6+rpi1) 8.3.0`
> > root@rasp:~# uname -a
> > `Linux rasp 4.19.118-v7+ #1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l GNU/Linux`
> 
> * 重现此BUG方式如下：
> 
> > 在MacOS上交叉编译arm使用的二进制
> > 编译环境如下：
> > `go version go1.14.3 darwin/amd64`
> > `Apple clang version 11.0.3 (clang-1103.0.32.62)`
> > 编译参数：
> > `GOOS=linux GOARCH=arm go build -a`
> 
> 使用上述方式交叉编译的arm二进制文件在树莓派ARMv7上运行能够重现此BUG。

我在树莓派3B上编译的版本还是有一样的问题，go是1.14.4，其他版本和你的一模一样

**Comment by gitgayhub** [comment]
使用go version 1.13.12编译最新的v2ray v4.23.4不再出现错误，猜测官方的编译环境升级了go版本到1.14.x导致的兼容问题
上传到了奶牛快传
https://c-t.work/s/e515c625637145

**Comment by zhoubowen-sky** [comment]
> 使用go version 1.13.12编译最新的v2ray v4.23.4不再出现错误，猜测官方的编译环境升级了go版本到1.14.x导致的兼容问题
> 上传到了奶牛快传
> https://c-t.work/s/e515c625637145

我采用

> 使用go version 1.13.12编译最新的v2ray v4.23.4不再出现错误，猜测官方的编译环境升级了go版本到1.14.x导致的兼容问题
> 上传到了奶牛快传
> https://c-t.work/s/e515c625637145

我用go 1.14.4 在树莓派上编译没问题。项目使用了CGO，你在树莓派3B上用go1.14.4编译有问题的编译参数是什么，CGO_ENABLED开了吗？

**Comment by gitgayhub** [comment]
> 我用go 1.14.4 在树莓派上编译没问题。项目使用了CGO，你在树莓派3B上用go1.14.4编译有问题的编译参数是什么，CGO_ENABLED开了吗？

我用的[https://www.v2ray.com/developer/intro/compile.html](url)的命令，设置了CGO_ENABLED=0，改成=1后使用go v1.14.4编译出来的v2ray没问题了

**Comment by gitgayhub** [comment]
加上CGO_ENABLED=1编译出来的v2ray在树莓派3B上运行没有问题，但是放到同样armv7的openwrt路由器上却提示 -ash: ./v2ray: not found
uname -a
Linux OpenWrt 4.14.171 #0 SMP Thu Feb 27 21:05:12 2020 armv7l GNU/Linux

**Comment by BurningC4** [comment]
4.24.2和4.25.0版本在树莓派4B运行时会出现
`v2ray.service: Main process exited, code=killed, status=11/SEGV
v2ray.service: Failed with result 'signal'.`
基本上两三秒一次，偶尔能挺几分钟
降级到4.23.4后不会再出现问题
`# uname --all
Linux alarmpi 5.4.45-1-ARCH #1 SMP PREEMPT Mon Jun 15 03:53:46 UTC 2020 armv7l GNU/Linux`

**Comment by BurningC4** [comment]
4.24.2和4.25.0版本在树莓派4B运行时会出现
`v2ray.service: Main process exited, code=killed, status=11/SEGV`
`v2ray.service: Failed with result 'signal'.`
基本上两三秒一次，偶尔能挺几分钟
降级到4.23.4后不会再出现问题
`uname -a`
`Linux alarmpi 5.4.45-1-ARCH #1 SMP PREEMPT Mon Jun 15 03:53:46 UTC 2020 armv7l GNU/Linux`

**Comment by kslr** [comment]
> 4.24.2和4.25.0版本在树莓派4B运行时会出现
> `v2ray.service: Main process exited, code=killed, status=11/SEGV`
> `v2ray.service: Failed with result 'signal'.`
> 基本上两三秒一次，偶尔能挺几分钟
> 降级到4.23.4后不会再出现问题
> `uname -a`
> `Linux alarmpi 5.4.45-1-ARCH #1 SMP PREEMPT Mon Jun 15 03:53:46 UTC 2020 armv7l GNU/Linux`

Use 4.25.1
