### ISSUE TITLE
Cannot Reproduce Build for 4.23.3

### ISSUE THREAD

**Issue by DuckSoft** [v2ray/v2ray-core#2527]
Seems master@v2ray/v2ray-core is broken and cannot be built.
![图片](https://user-images.githubusercontent.com/7822648/83420053-9d382080-a458-11ea-828d-9c08799c0cbc.png)
This will affect downstream automation pipelines. Please fix.

**Comment by ActiveIce** [comment]
我遇到同样的错误

**Comment by demonstan** [comment]
![image](https://user-images.githubusercontent.com/7578819/83428135-71bb3300-a464-11ea-966b-cf67b12ea051.png)
我bazel build遇到了这样的错误

**Comment by ActiveIce** [comment]
最新的commit已经可以通过自动化编译了  close吧

**Comment by DuckSoft** [comment]
咳，严格意义上应该发新版本的，直接发 4.23.4 的。
撤回了……emmm……好吧，okay……
