### ISSUE TITLE
我想问个多账号的问题

### ISSUE THREAD

**Issue by bbhxwl** [v2ray/v2ray-core#2528]
不知道为什么一问就被关闭，不知道是哪里违规您告诉我一下好吗，这真的对我很重要，就是v2后端配置想预留多个uuid，为了添加账号不掉线，但是uuid添加到200个的时候，程序就无法正常使用（不能连接），不知道为什么，希望能解答一下。拜托大神了。

**Comment by kslr** [comment]
第一次就回答你了，另外没有配置和日志会被关闭，想必你每次发时都能看到。

**Comment by bbhxwl** [comment]
> 第一次就回答你了，另外没有配置和日志会被关闭，想必你每次发时都能看到。
> 不要浪费所有人时间，这样的一句话你再问10遍，也不能得到正确的答案

不好意思，我是新手，马上补发。对不起

**Comment by bbhxwl** [comment]
> 第一次就回答你了，另外没有配置和日志会被关闭，想必你每次发时都能看到。
> 不要浪费所有人时间，这样的一句话你再问10遍，也不能得到正确的答案
客户端连接提示的错误是  
2020/06/02 02:25:14 [Warning] [2931229164] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://13.115.109.190:365/XLycVF3d/):  > dial tcp 13.115.109.190:365: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
服务器的error.log和access.log 都没有任何数据。
配置文件如下。
[config.zip](https://github.com/v2ray/v2ray-core/files/4712853/config.zip)

**Comment by kslr** [comment]
单个工作正常吗

**Comment by bbhxwl** [comment]
> 单个工作正常吗

测试了1个uuid正常，刚才测试200个也正常，又测试了一下1000个，不正常。没有错误日志，不知道为什么，好像端口也没开放，单个账号和200个账号好用的时候，端口是有开放。

**Comment by kslr** [comment]
把alert降到0呢
另外一些机场是通过路径分流的，不会用很多UUID来减轻压力

**Comment by bbhxwl** [comment]
> 把alert降到0呢
> 另外一些机场是通过路径分流的，不会用很多UUID来减轻压力

能指点一下路径分流，如果有人到期了，能让这个人不能使用么？这些应该都是基于uuid是吧？我刚刚尝试手动运行 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json    
V2Ray 4.23.3 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.1 linux/amd64)
A unified platform for anti-censorship.
2020/06/01 18:36:29 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  /etc/v2ray/config.json
fatal error: runtime: out of memory

应该是内存不足导致的，1G内存，1000个账号好像不行。我再试试加大内存看看是这个问题么。1000个uuid不应该占用这么多内存的吧。

**Comment by bbhxwl** [comment]
我大概测试出来，确实是内存不足导致的，512M内存服务器大概能添加100来个uuid，2G内存的服务器，添加了500个uuid，剩余323M内存，应该封顶是600多个uuid，500个uuid的配置文件config.json  大约是86.7 KB ，内存占用大概900MB，大神能给指点一下优化么？谢谢您
              total        used        free      shared  buff/cache   available
Mem:           1836        1038         323          16         474         600
Swap:             0           0           0

**Comment by kslr** [comment]
1G是远远不够的，alert要设置0
路径就是改代码，你可以在日志哪里修改

**Comment by bbhxwl** [comment]
> 1G是远远不够的，alert要设置0
> 路径就是改代码，你可以在日志哪里修改

大神说的修改alert为0，是下载源代码修改？我只学过C#，修改config.json没办法是吧？

**Comment by kslr** [comment]
你在配置里写的是64，我指的就是这个

**Comment by bbhxwl** [comment]
> 你在配置里写的是64，我指的就是这个

我懂了，那个额外id，谢谢，这个我以为就类似密码一样的东西，不知道具体作用。

**Comment by bbhxwl** [comment]
> 你在配置里写的是64，我指的就是这个

真的可以了，500个账号，改成0以后，内存只用了110M，算系统占用。这是什么原理。

**Comment by kslr** [comment]
vmess协议有讲，在文档里
