### ISSUE TITLE
最新v4.23.3编译出错

### ISSUE THREAD

**Issue by winds365** [v2ray/v2ray-core#2534]
最新v4.23.3编译出错，go1.14.3和go1.14.4报同样错误
```
bazel build --action_env=GOPATH=$GOPATH --action_env=PATH=$PATH //release:v2ray_linux_amd64_package --sandbox_debug --verbose_failures
INFO: Analyzed target //release:v2ray_linux_amd64_package (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /gopath/src/v2ray.com/core/main/BUILD:8:12: error executing shell command: '/bin/bash -c cd ${SPWD} && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on GOCACHE=${TMPDIR}/gocache go build -o bazel-out/k8-fastbuild/bin/main/linux/amd64/v2ray -compiler gc -gcflags "all=-t...' failed (Exit 1): linux-sandbox failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/4993ff8a7fdbcbc7590627b0a295b7b4/sandbox/linux-sandbox/7/execroot/v2ray_core && \
  exec env - \
    GOPATH=/gopath \
    PATH=/usr/local/go/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    TMPDIR=/tmp \
  /root/.cache/bazel/_bazel_root/install/ba7765e6f39a679257358196b530585b/linux-sandbox -t 15 -w /root/.cache/bazel/_bazel_root/4993ff8a7fdbcbc7590627b0a295b7b4/sandbox/linux-sandbox/7/execroot/v2ray_core -w /tmp -w /dev/shm -D -- /bin/bash -c 'cd ${SPWD} && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on GOCACHE=${TMPDIR}/gocache go build -o bazel-out/k8-fastbuild/bin/main/linux/amd64/v2ray -compiler gc -gcflags "all=-trimpath=${GOPATH}/src" -asmflags "all=-trimpath=${GOPATH}/src" -ldflags '\''-s -w'\'' -tags '\'''\'' v2ray.com/core/main') linux-sandbox failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/4993ff8a7fdbcbc7590627b0a295b7b4/sandbox/linux-sandbox/7/execroot/v2ray_core && \
  exec env - \
    GOPATH=/gopath \
    PATH=/usr/local/go/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    TMPDIR=/tmp \
  /root/.cache/bazel/_bazel_root/install/ba7765e6f39a679257358196b530585b/linux-sandbox -t 15 -w /root/.cache/bazel/_bazel_root/4993ff8a7fdbcbc7590627b0a295b7b4/sandbox/linux-sandbox/7/execroot/v2ray_core -w /tmp -w /dev/shm -D -- /bin/bash -c 'cd ${SPWD} && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on GOCACHE=${TMPDIR}/gocache go build -o bazel-out/k8-fastbuild/bin/main/linux/amd64/v2ray -compiler gc -gcflags "all=-trimpath=${GOPATH}/src" -asmflags "all=-trimpath=${GOPATH}/src" -ldflags '\''-s -w'\'' -tags '\'''\'' v2ray.com/core/main')
src/main/tools/linux-sandbox.cc:156: linux-sandbox-pid1 has PID 9164
src/main/tools/process-tools.cc:118: sigaction(32, &sa, nullptr) failed
src/main/tools/process-tools.cc:118: sigaction(33, &sa, nullptr) failed
src/main/tools/linux-sandbox-pid1.cc:176: working dir: /root/.cache/bazel/_bazel_root/4993ff8a7fdbcbc7590627b0a295b7b4/sandbox/linux-sandbox/7/execroot/v2ray_core
src/main/tools/linux-sandbox-pid1.cc:195: writable: /root/.cache/bazel/_bazel_root/4993ff8a7fdbcbc7590627b0a295b7b4/sandbox/linux-sandbox/7/execroot/v2ray_core
src/main/tools/linux-sandbox-pid1.cc:195: writable: /tmp
src/main/tools/linux-sandbox-pid1.cc:195: writable: /dev/shm
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /dev
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /dev/pts
src/main/tools/linux-sandbox-pid1.cc:266: remount rw: /dev/shm
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /dev/hugepages
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /dev/mqueue
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /run
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /run/lock
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /run/user/0
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/kernel/security
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/unified
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/systemd
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/memory
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/cpuset
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/net_cls,net_prio
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/cpu,cpuacct
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/devices
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/blkio
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/rdma
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/perf_event
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/freezer
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/pids
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/pstore
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/bpf
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/kernel/debug
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/kernel/tracing
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /proc
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /proc/sys/fs/binfmt_misc
src/main/tools/linux-sandbox-pid1.cc:266: remount rw: /root/.cache/bazel/_bazel_root/4993ff8a7fdbcbc7590627b0a295b7b4/sandbox/linux-sandbox/7/execroot/v2ray_core
src/main/tools/linux-sandbox-pid1.cc:266: remount rw: /root/.cache/bazel/_bazel_root/4993ff8a7fdbcbc7590627b0a295b7b4/sandbox/linux-sandbox/7/execroot/v2ray_core
src/main/tools/linux-sandbox-pid1.cc:266: remount rw: /tmp
src/main/tools/linux-sandbox-pid1.cc:266: remount rw: /dev/shm
src/main/tools/process-tools.cc:118: sigaction(32, &sa, nullptr) failed
src/main/tools/process-tools.cc:118: sigaction(33, &sa, nullptr) failed
/bin/bash: line 0: cd: HOME not set
src/main/tools/linux-sandbox-pid1.cc:423: waitpid returned 2
src/main/tools/linux-sandbox-pid1.cc:443: child exited with code 1
src/main/tools/linux-sandbox.cc:206: child exited normally with exitcode 1
Target //release:v2ray_linux_amd64_package failed to build
INFO: Elapsed time: 0.166s, Critical Path: 0.03s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**Comment by kslr** [comment]
https://github.com/v2fly/v2ray-core/commit/09295f7ef6a210a48b17e0c93ec9dcedaf6f6e90

**Comment by winds365** [comment]
> [v2fly@09295f7](https://github.com/v2fly/v2ray-core/commit/09295f7ef6a210a48b17e0c93ec9dcedaf6f6e90)

改了之后还是报错
`
root@debian:/gopath/src/v2ray.com/core# bazel build --action_env=GOPATH=$GOPATH --action_env=PATH=$PATH //release:v2ray_linux_amd64_package --sandbox_debug --verbose_failures
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //release:v2ray_linux_amd64_package (8 packages loaded, 25 targets configured).
INFO: Found 1 target...
ERROR: /gopath/src/v2ray.com/core/infra/control/main/BUILD:8:12: error executing shell command: '/bin/bash -c CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on GOCACHE=${TMPDIR}/gocache go build -o bazel-out/k8-fastbuild/bin/infra/control/main/linux/amd64/v2ctl -compiler gc -gcflags "all=-t...' failed (Exit 1): linux-sandbox failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/4993ff8a7fdbcbc7590627b0a295b7b4/sandbox/linux-sandbox/2/execroot/v2ray_core && \
  exec env - \
    GOPATH=/gopath \
    PATH=/usr/local/go/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    TMPDIR=/tmp \
  /root/.cache/bazel/_bazel_root/install/ba7765e6f39a679257358196b530585b/linux-sandbox -t 15 -w /root/.cache/bazel/_bazel_root/4993ff8a7fdbcbc7590627b0a295b7b4/sandbox/linux-sandbox/2/execroot/v2ray_core -w /tmp -w /dev/shm -D -- /bin/bash -c 'CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on GOCACHE=${TMPDIR}/gocache go build -o bazel-out/k8-fastbuild/bin/infra/control/main/linux/amd64/v2ctl -compiler gc -gcflags "all=-trimpath=${GOPATH}/src" -asmflags "all=-trimpath=${GOPATH}/src" -ldflags '\''-s -w'\'' -tags '\''confonly'\'' v2ray.com/core/infra/control/main') linux-sandbox failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/4993ff8a7fdbcbc7590627b0a295b7b4/sandbox/linux-sandbox/2/execroot/v2ray_core && \
  exec env - \
    GOPATH=/gopath \
    PATH=/usr/local/go/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    TMPDIR=/tmp \
  /root/.cache/bazel/_bazel_root/install/ba7765e6f39a679257358196b530585b/linux-sandbox -t 15 -w /root/.cache/bazel/_bazel_root/4993ff8a7fdbcbc7590627b0a295b7b4/sandbox/linux-sandbox/2/execroot/v2ray_core -w /tmp -w /dev/shm -D -- /bin/bash -c 'CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on GOCACHE=${TMPDIR}/gocache go build -o bazel-out/k8-fastbuild/bin/infra/control/main/linux/amd64/v2ctl -compiler gc -gcflags "all=-trimpath=${GOPATH}/src" -asmflags "all=-trimpath=${GOPATH}/src" -ldflags '\''-s -w'\'' -tags '\''confonly'\'' v2ray.com/core/infra/control/main')
src/main/tools/linux-sandbox.cc:156: linux-sandbox-pid1 has PID 5728
src/main/tools/process-tools.cc:118: sigaction(32, &sa, nullptr) failed
src/main/tools/process-tools.cc:118: sigaction(33, &sa, nullptr) failed
src/main/tools/linux-sandbox-pid1.cc:176: working dir: /root/.cache/bazel/_bazel_root/4993ff8a7fdbcbc7590627b0a295b7b4/sandbox/linux-sandbox/2/execroot/v2ray_core
src/main/tools/linux-sandbox-pid1.cc:195: writable: /root/.cache/bazel/_bazel_root/4993ff8a7fdbcbc7590627b0a295b7b4/sandbox/linux-sandbox/2/execroot/v2ray_core
src/main/tools/linux-sandbox-pid1.cc:195: writable: /tmp
src/main/tools/linux-sandbox-pid1.cc:195: writable: /dev/shm
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /dev
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /dev/pts
src/main/tools/linux-sandbox-pid1.cc:266: remount rw: /dev/shm
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /dev/mqueue
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /dev/hugepages
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /run
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /run/lock
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /run/user/0
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/kernel/security
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/unified
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/systemd
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/devices
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/perf_event
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/net_cls,net_prio
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/cpu,cpuacct
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/blkio
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/pids
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/rdma
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/cpuset
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/freezer
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/cgroup/memory
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/pstore
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/fs/bpf
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/kernel/debug
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /sys/kernel/tracing
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /proc
src/main/tools/linux-sandbox-pid1.cc:266: remount ro: /proc/sys/fs/binfmt_misc
src/main/tools/linux-sandbox-pid1.cc:266: remount rw: /root/.cache/bazel/_bazel_root/4993ff8a7fdbcbc7590627b0a295b7b4/sandbox/linux-sandbox/2/execroot/v2ray_core
src/main/tools/linux-sandbox-pid1.cc:266: remount rw: /root/.cache/bazel/_bazel_root/4993ff8a7fdbcbc7590627b0a295b7b4/sandbox/linux-sandbox/2/execroot/v2ray_core
src/main/tools/linux-sandbox-pid1.cc:266: remount rw: /tmp
src/main/tools/linux-sandbox-pid1.cc:266: remount rw: /dev/shm
src/main/tools/process-tools.cc:118: sigaction(32, &sa, nullptr) failed
src/main/tools/process-tools.cc:118: sigaction(33, &sa, nullptr) failed
can't load package: cannot find module providing package v2ray.com/core/infra/control/main: working directory is not part of a module
src/main/tools/linux-sandbox-pid1.cc:423: waitpid returned 2
src/main/tools/linux-sandbox-pid1.cc:443: child exited with code 1
src/main/tools/linux-sandbox.cc:206: child exited normally with exitcode 1
Target //release:v2ray_linux_amd64_package failed to build
INFO: Elapsed time: 4.153s, Critical Path: 0.07s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
`

**Comment by teddysun** [comment]
多说一句，4.23.3 的 commit history 很明显是比较乱的，应该是 merge 时出的问题。
而且我注意到多了一个 archive 分支，看起来像是 4.23.3 发布之前的最新代码。

因此我想建议从 archive 分支回滚一下，具体做法就是先重命名一下 master，再将 archive 重命名为 master，最后再将最新的代码（4.23.2 到 4.23.3 之间的） merge 到 master 里。

**Comment by karuboniru** [comment]
unable to build here, with [log from COPR](https://download.copr.fedorainfracloud.org/results/yanqiyu/v2ray/fedora-rawhide-x86_64/01421308-v2ray/builder-live.log.gz), seems to be from wrong tagging.

**Comment by kslr** [comment]
> 多说一句，4.23.3 的 commit history 很明显是比较乱的，应该是 merge 时出的问题。
> 而且我注意到多了一个 archive 分支，看起来像是 4.23.3 发布之前的最新代码。
> 
> 因此我想建议从 archive 分支回滚一下，具体做法就是先重命名一下 master，再将 archive 重命名为 master，最后再将最新的代码（4.23.2 到 4.23.3 之间的） merge 到 master 里。

现在没办法退回去了，接下来我来重新处理一下编译和CI的更新和迁移

**Comment by kslr** [comment]
```
bazel build --action_env=GOPATH=$GOPATH --action_env=PATH=$PATH --action_env=SPWD=$PWD --action_env=GOCACHE=$(go env GOCACHE) --spawn_strategy local //release:all
```

**Comment by winds365** [comment]
> ```
> bazel build --action_env=GOPATH=$GOPATH --action_env=PATH=$PATH --action_env=SPWD=$PWD --action_env=GOCACHE=$(go env GOCACHE) --spawn_strategy local //release:all
> ```

使用原来的文件可以正常编译https://github.com/v2ray/v2ray-core/blob/archive/infra/bazel/build.bzl
