### ISSUE TITLE
[Error]VMess|Outbound: Failed to find an available destination:All retry attempts failed.

### ISSUE THREAD

**Issue by returnstairgy** [v2ray/v2ray-core#254]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please answer the following questions before submitting your issue. Thank you.

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
服务器版本未知，bash <(curl -L -s https://raw.githubusercontent.com/v2ray/v2ray-core/master/release/install-release.sh) 这个链接自动安装的
客户端版本为v2.0
1) What version of V2Ray are you using?

3) 你看到的不正常的现象是什么？
3) What did you see?

[Error]VMess|Outbound: Failed to find an available destination:All retry attempts failed.
json里的id、远程端口和服务器地址换了之后打开youtube和其他国外网站，均出现上述错误

4) 你期待看到的正确表现是怎样的？
4) What do you expected to see instead?
打开youtube和其他网站没有延迟并且客户端界面没显示任何错误
5) 请附上你的配置文件。
5) Please attach your configuration file.

服务端：
{
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 29197,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "869660bd-c972-472c-ac48-b5368dce128d",
          "level": 1,
          "alterId": 64
        }
      ]
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",

客户端：

{
  "log": {
    "loglevel": "warning"
  },
  "inbound": {
    "port": 1080,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "163.44.174.202",
          "port": 29197,
          "users": [
            {
              "id": "869660bd-c972-472c-ac48-b5368dce128d",
              "level": 1,
              "alterId": 64
            }
          ]
        }
      ]
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": "1-52",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "54-79",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "81-442",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "444-65535",
          "outboundTag": "direct"
        },
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        }
      ]
    }
  },
  "transport": {
    "kcpSettings": {
      "uplinkCapacity": 1,
      "downlinkCapacity": 10
    }
  }
}

**Comment by wtlusvm** [comment]
删除服务器配置文件后，再次执行bash <(curl -L -s https://raw.githubusercontent.com/v2ray/v2ray-core/master/release/install-release.sh)更新服务器版本后再试

**Comment by zjhong** [comment]
客户端 allowInsecure 改为ture，这种问题就解决了。

**Comment by DarienRaymond** [comment]
目测是服务器配置问题，请确认时间同步且端口在防火墙中开放。

**Comment by zenglian** [comment]
> 客户端 allowInsecure 改为ture，这种问题就解决了。

allowInsecure 在哪个文件，哪个位置？
