### ISSUE TITLE
请教大佬 ： v2ray + tsl + nginx反向代理，报错：failed to dial to (wss://**my.domain/my_path**): 403 Forbidden > websocket: bad handshake]， 多谢啦！

### ISSUE THREAD

**Issue by Arrowyi** [v2ray/v2ray-core#2540]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
**服务器： V2Ray 4.23.3 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.1 linux/amd64)
A unified platform for anti-censorship.
客户端：V2RayN 3.5**

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
**使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频，上google查找资料**

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
**Window10 开启 v2rayN 客服端，chrome switchyomege 设置系统代理，打不开任何网页， 客服端报错：(见下面 客户端报错)**

4) 你期待看到的正确表现是怎样的？
**可以正常访问网址，包括google, youtube等。**

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
{
    "log":{
        "loglevel":"warning",
        "access":"/var/log/v2ray/access.log",
        "error":"/var/log/v2ray/error.log"
    },
  "inbounds": [{
    "port": **v2ray-port**,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "**my-uuid**",
          "level": 1,
          "alterId": 64
        }
      ]
    },
    "streamSettings":{
        "network":"ws",
        "wsSettings":{
            "path":"/**my_path**"
        }
    },
    "listen":"127.0.0.1"
  }],
  "outbounds": [{
    "protocol": "freedom",
    "settings": {}
  },{
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  }]
  }
}

```

客户端配置:

```javascript
{
  "policy": null,
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "proxy",
      "port": 10808,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "address": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "**my.domain**",
            "port": 443,
            "users": [
              {
                "id": "**my_uuid**",
                "alterId": 64,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": true,
          "serverName": "**my.domain**"
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/**my_path**",
          "headers": {
            "Host": "**my.domain**"
          }
        },
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "stats": null,
  "api": null,
  "dns": null,
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "port": null,
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "ip": null,
        "domain": null
      }
    ]
  }
}
```
nginx 配置：
```javascript
server {
    listen 80;
    server_name **my.domain**；
    rewrite ^(.*)https://$server_name$1 permanent;
}
server {
    listen 443 ssl;
    server_name **my.domain**;
    charset utf-8;


    ssl on;
    ssl_protocols TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
    ssl_ecdh_curve secp384r1;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_session_tickets off;
    ssl_certificate /usr/local/nginx/conf/ssl/nginx_bundle.crt;
    ssl_certificate_key /usr/local/nginx/conf/ssl/**my.domain**.key;

    access_log /var/log/nginx/arrowyi.access.log;
    error_log /var/log/nginx/arrowyi.error.log;

    root /usr/share/nginx/html;
    location / {
        index index.html;
    }

    location /**my_path** {
        proxy_redirect off;
        proxy_pass http://127.0.0.1:v2ray-port;
        proxy_http_version 1.1;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
2020/06/02 09:14:15 [Warning] v2ray.com/core: V2Ray 4.23.3 started
2020/06/02 10:23:33 [Warning] v2ray.com/core: V2Ray 4.23.3 started
2020/06/03 03:57:21 [Warning] v2ray.com/core: V2Ray 4.23.3 started

```

客户端错误日志:

```javascript
bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2020/06/03 14:08:16 tcp:127.0.0.1:51778 accepted tcp:outlook.telenav.com:443 [proxy] 
2020/06/03 14:08:16 tcp:127.0.0.1:51781 accepted tcp:statics.teams.cdn.office.net:443 [proxy] 
2020/06/03 14:08:24 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://**my.domain/my_path**): 403 Forbidden > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2020/06/03 14:08:25 tcp:127.0.0.1:51788 accepted tcp:telenav.cn:443 [proxy] 
2020/06/03 14:08:25 tcp:127.0.0.1:51791 accepted tcp:teams.microsoft.com:443 [proxy] 
2020/06/03 14:08:32 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://**my.domain/my_path**): 403 Forbidden > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2020/06/03 14:08:33 tcp:127.0.0.1:51798 accepted tcp:telenav.cn:443 [proxy] 
2020/06/03 14:08:34 tcp:127.0.0.1:51801 accepted tcp:checkappexec.microsoft.com:443 [proxy] 
2020/06/03 14:08:41 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://**my.domain/my_path**): 403 Forbidden > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2020/06/03 14:08:42 tcp:127.0.0.1:51811 accepted tcp:checkappexec.microsoft.com:443 [proxy] 
2020/06/03 14:08:42 tcp:127.0.0.1:51812 accepted tcp:telenav.cn:443 [proxy] 
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

**文件为空**

8) 其它相关的配置文件（如 Nginx）和相关日志。
**Nginx error log为空
access log:**

```javascript
12.127.77.114 - - [03/Jun/2020:03:59:10 +0000] "GET /my_path HTTP/1.1" 400 12 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36"
12.127.77.114 - - [03/Jun/2020:03:59:11 +0000] "GET /my_path HTTP/1.1" 400 12 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36"
12.127.77.114 - - [03/Jun/2020:03:59:28 +0000] "GET /my_path HTTP/1.1" 400 12 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36"
66.240.205.34 - - [03/Jun/2020:04:15:09 +0000] "H\x00\x00\x00tj\xA8\x9E#D\x98+\xCA\xF0\xA7\xBBl\xC5\x19\xD7\x8D\xB6\x18\xEDJ\x1En\xC1\xF9xu[l\xF0E\x1D-j\xEC\xD4xL\xC9r\xC9\x15\x10u\xE0%\x86Rtg\x05fv\x86]%\xCC\x80\x0C\xE8\xCF\xAE\x00\xB5\xC0f\xC8\x8DD\xC5\x09\xF4" 400 173 "-" "-"
178.128.194.144 - - [03/Jun/2020:05:00:51 +0000] "GET / HTTP/1.1" 400 271 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/70.0"
178.128.194.144 - - [03/Jun/2020:05:00:52 +0000] "\x00\xFFK\x00\x00\x00\xE2\x00 \x00\x00\x00\x0E2O\xAAC\xE92g\xC2W'\x17+\x1D\xD9\xC1\xF3,kN\x17\x14" 400 173 "-" "-"
```

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。
**V2Ray 4.23.3 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.1 linux/amd64)
A unified platform for anti-censorship.
Configuration OK.**

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。
**Jun 03 03:57:20 vultrguest systemd[1]: Stopping V2Ray Service...
Jun 03 03:57:20 vultrguest systemd[1]: Stopped V2Ray Service.
Jun 03 03:57:20 vultrguest systemd[1]: Started V2Ray Service.
Jun 03 03:57:21 vultrguest v2ray[26844]: V2Ray 4.23.3 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.1 linux/amd64)
Jun 03 03:57:21 vultrguest v2ray[26844]: A unified platform for anti-censorship.
Jun 03 03:57:21 vultrguest v2ray[26844]: 2020/06/03 03:57:21 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
Jun 03 03:57:21 vultrguest v2ray[26844]: v2ctl> Read config:  /etc/v2ray/config.json**

请预览一下你填的内容再提交。

**附加信息：**
**1. VPS 为CentOS8, firewall 配置:**

```javascript
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: ens3
  sources:
  services: cockpit dhcpv6-client http https ssh
  ports: v2ray-port/tcp
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
```
**2. 浏览器访问https://mydomain 可以显示nginx欢迎界面， 访问https://mydomain/my_path, 显示bad request**

**Comment by kslr** [comment]
403 Forbidden nginx proxy路径错误了

**Comment by Arrowyi** [comment]
@kslr 大佬请明示
我的nginx配置：
    **location /my_path** {
        proxy_redirect off;
        proxy_pass http://127.0.0.1:v2ray-port;
        proxy_http_version 1.1;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

服务端配置：
"inbounds": [{
    "port": v2ray-port,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "my-uuid",
          "level": 1,
          "alterId": 64
        }
      ]
    },
    "streamSettings":{
        "network":"ws",
        "wsSettings":{
            **"path":"/my_path"**
        }
    },
    "listen":"127.0.0.1"
  }],

客户端配置：
"outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "my.domain",
            "port": 443,
            "users": [
              {
                "id": "my_uuid",
                "alterId": 64,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": true,
          "serverName": "my.domain"
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          **"path": "/my_path",**
          "headers": {
            "Host": "my.domain"
          }
        },
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],

proxy的路径都是配置的/my_path, 这个我检查过了， 请教下，还有哪里可能出问题？ 

多谢啦。。

**Comment by kslr** [comment]
你可以读一下 Guide.v2fly.org 按照实例校准一下

**Comment by Arrowyi** [comment]
@kslr  Hi 大佬， 我按照demo重新修改了下，把path也修改成demo的了，但是得到了新的错误：
v2ray.com/core/transport/internet/websocket: failed to dial to (wss://my.domain/ray):  > read tcp 172.16.60.148:56526->xx.xx.xx.xx:443: wsarecv: An existing connection was forcibly closed by the remote host. 
这个是啥问题啊？

**Comment by Arrowyi** [comment]
@kslr  demo的配置在我本地好像有些问题：
server {
  listen 443 ssl;
  **listen [::]:443 ssl;**
  
  ssl_certificate       /etc/v2ray/v2ray.crt;
  ssl_certificate_key   /etc/v2ray/v2ray.key;
  ssl_session_timeout 1d;
  ssl_session_cache shared:MozSSL:10m;
  ssl_session_tickets off;
  
  ssl_protocols         TLSv1.2 **TLSv1.3**;

nginx 配置如上图 粗体字的配置在我本机 不能配， 配置了 就会发生刚才的错误，我有把这两项配置去掉了， 然后错误又回到了 ：
v2ray.com/core/transport/internet/websocket: failed to dial to (wss://my.domain/ray): 403 Forbidden > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed.
请问下 大佬 还有其他可疑的点么？

**Comment by Arrowyi** [comment]
@kslr 大佬 
把v2ray的log 级别搞到info, 得到如下问题：
2020/06/03 23:24:02 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2020/06/03 23:24:02 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2020/06/03 23:24:03 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2020/06/03 23:24:03 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2020/06/03 23:24:06 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2020/06/03 23:24:06 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2020/06/03 23:24:08 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2020/06/03 23:24:11 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2020/06/03 23:24:14 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2020/06/03 23:24:18 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2020/06/03 23:24:20 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2020/06/03 23:24:25 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2020/06/03 23:24:31 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2020/06/03 23:24:33 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header

客服端配置：
···javascript
2020/06/03 23:24:02 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2020/06/03 23:24:02 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2020/06/03 23:24:03 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2020/06/03 23:24:03 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2020/06/03 23:24:06 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2020/06/03 23:24:06 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2020/06/03 23:24:08 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2020/06/03 23:24:11 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2020/06/03 23:24:14 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2020/06/03 23:24:18 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2020/06/03 23:24:20 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2020/06/03 23:24:25 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2020/06/03 23:24:31 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2020/06/03 23:24:33 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
```

服务端配置:
```javascript
{
    "log":{
        "loglevel":"info",
        "access":"/var/log/v2ray/access.log",
        "error":"/var/log/v2ray/error.log"
    },
  "inbounds": [{
    "port": 27783,
    "protocol": "vmess",
    "listen":"127.0.0.1",
    "settings": {
      "clients": [
        {
          "id": "uuid",
          "level": 1,
          "alterId": 64
        }
      ]
    },
    "streamSettings":{
        "network":"ws",
        "wsSettings":{
            "path":"/awesomepath"
        }
    }
  }],
  "outbounds": [{
    "protocol": "freedom",
    "settings": {}
  },{
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  }],
  "routing": {
    "rules": [
      {
        "type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "blocked"
      }
    ]
  }
  }
}

```

nginx 配置：
```javascript
server {
    listen 80;
    server_name my.domain;
    rewrite ^(.*)https://$server_name$1 permanent;
}
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name my.domain;


    ssl on;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
    ssl_ecdh_curve secp384r1;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_session_tickets off;
    ssl_certificate /usr/local/nginx/conf/ssl/nginx_bundle.crt;
    ssl_certificate_key /usr/local/nginx/conf/ssl/my.domain.key;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    root /usr/share/nginx/html;
    location / {
        index index.html;
    }

    location /awesomepath {
        proxy_redirect off;
        proxy_pass http://127.0.0.1:27783;
        proxy_http_version 1.1;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

```

这次能帮看下是啥问题么？ 多谢啦

**Comment by Alampdow** [comment]
> @kslr 大佬
> 把v2ray的log 级别搞到info, 得到如下问题：
> 2020/06/03 23:24:02 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
> 2020/06/03 23:24:02 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
> 2020/06/03 23:24:03 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
> 2020/06/03 23:24:03 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
> 2020/06/03 23:24:06 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
> 2020/06/03 23:24:06 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
> 2020/06/03 23:24:08 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
> 2020/06/03 23:24:11 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
> 2020/06/03 23:24:14 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
> 2020/06/03 23:24:18 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
> 2020/06/03 23:24:20 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
> 2020/06/03 23:24:25 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
> 2020/06/03 23:24:31 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
> 2020/06/03 23:24:33 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
> 
> 客服端配置：
> 
> ```js
> {
>   "policy": null,
>   "log": {
>     "access": "",
>     "error": "",
>     "loglevel": "warning"
>   },
>   "inbounds": [
>     {
>       "tag": "proxy",
>       "port": 10808,
>       "listen": "127.0.0.1",
>       "protocol": "socks",
>       "sniffing": {
>         "enabled": true,
>         "destOverride": [
>           "http",
>           "tls"
>         ]
>       },
>       "settings": {
>         "auth": "noauth",
>         "udp": true,
>         "ip": null,
>         "address": null,
>         "clients": null
>       },
>       "streamSettings": null
>     }
>   ],
>   "outbounds": [
>     {
>       "tag": "proxy",
>       "protocol": "vmess",
>       "settings": {
>         "vnext": [
>           {
>             "address": "my.domain",
>             "port": 443,
>             "users": [
>               {
>                 "id": "uuid",
>                 "alterId": 64,
>                 "email": "t@t.tt",
>                 "security": "none"
>               }
>             ]
>           }
>         ],
>         "servers": null,
>         "response": null
>       },
>       "streamSettings": {
>         "network": "ws",
>         "security": "tls",
>         "tlsSettings": {
>           "allowInsecure": true,
>           "serverName": "my.domain"
>         },
>         "tcpSettings": null,
>         "kcpSettings": null,
>         "wsSettings": {
>           "connectionReuse": true,
>           "path": "/awesomepath",
>           "headers": {
>             "Host": "my.domain"
>           }
>         },
>         "httpSettings": null,
>         "quicSettings": null
>       },
>       "mux": {
>         "enabled": true,
>         "concurrency": 8
>       }
>     },
>     {
>       "tag": "direct",
>       "protocol": "freedom",
>       "settings": {
>         "vnext": null,
>         "servers": null,
>         "response": null
>       },
>       "streamSettings": null,
>       "mux": null
>     },
>     {
>       "tag": "block",
>       "protocol": "blackhole",
>       "settings": {
>         "vnext": null,
>         "servers": null,
>         "response": {
>           "type": "http"
>         }
>       },
>       "streamSettings": null,
>       "mux": null
>     }
>   ],
>   "stats": null,
>   "api": null,
>   "dns": null,
>   "routing": {
>     "domainStrategy": "IPIfNonMatch",
>     "rules": [
>       {
>         "type": "field",
>         "port": null,
>         "inboundTag": [
>           "api"
>         ],
>         "outboundTag": "api",
>         "ip": null,
>         "domain": null
>       }
>     ]
>   }
> }
> ```
> 
> 服务端配置:
> 
> ```js
> {
>     "log":{
>         "loglevel":"info",
>         "access":"/var/log/v2ray/access.log",
>         "error":"/var/log/v2ray/error.log"
>     },
>   "inbounds": [{
>     "port": 27783,
>     "protocol": "vmess",
>     "listen":"127.0.0.1",
>     "settings": {
>       "clients": [
>         {
>           "id": "uuid",
>           "level": 1,
>           "alterId": 64
>         }
>       ]
>     },
>     "streamSettings":{
>         "network":"ws",
>         "wsSettings":{
>             "path":"/awesomepath"
>         }
>     }
>   }],
>   "outbounds": [{
>     "protocol": "freedom",
>     "settings": {}
>   },{
>     "protocol": "blackhole",
>     "settings": {},
>     "tag": "blocked"
>   }],
>   "routing": {
>     "rules": [
>       {
>         "type": "field",
>         "ip": ["geoip:private"],
>         "outboundTag": "blocked"
>       }
>     ]
>   }
>   }
> }
> ```
> 
> nginx 配置：
> 
> ```js
> server {
>     listen 80;
>     server_name my.domain;
>     rewrite ^(.*)https://$server_name$1 permanent;
> }
> server {
>     listen 443 ssl;
>     listen [::]:443 ssl;
>     server_name my.domain;
> 
> 
>     ssl on;
>     ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
>     ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
>     ssl_ecdh_curve secp384r1;
>     ssl_prefer_server_ciphers on;
>     ssl_session_cache shared:SSL:10m;
>     ssl_session_timeout 10m;
>     ssl_session_tickets off;
>     ssl_certificate /usr/local/nginx/conf/ssl/nginx_bundle.crt;
>     ssl_certificate_key /usr/local/nginx/conf/ssl/my.domain.key;
> 
>     access_log /var/log/nginx/access.log;
>     error_log /var/log/nginx/error.log;
> 
>     root /usr/share/nginx/html;
>     location / {
>         index index.html;
>     }
> 
>     location /awesomepath {
>         proxy_redirect off;
>         proxy_pass http://127.0.0.1:27783;
>         proxy_http_version 1.1;
>         proxy_set_header Connection "upgrade";
>         proxy_set_header Host $http_host;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     }
> }
> ```
> 
> 客户端报错为：
> 
> ```js
> 2020/06/03 23:52:24 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://my.domain/awesomepath): 400 Bad Request > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
> ```
> 
> 这次能帮看下是啥问题么？ 多谢啦

你Nginx配置少了一行，你仔细看白话文，把那行加上
