### ISSUE TITLE
最新版本 Windows 32 位安装包 Windows Defender 报毒

### ISSUE THREAD

**Issue by jleaves** [v2ray/v2ray-core#2546]
### 预期行为
不报毒

### 实际行为
Windows Defender 对下载的 zip 文件报毒（v4.23.4）

<img width="374" alt="{DC33EF4F-7EBE-4741-9AF9-E586039F127C}" src="https://user-images.githubusercontent.com/42891851/83840322-db6f6180-a730-11ea-81f9-959242847691.png">

### 备注

Windows 64 位的 zip 包不报毒

**Comment by jleaves** [comment]
#2dust/v2rayN#857

**Comment by proxysu** [comment]
我也遇到了，我的系统是win10专业版，最新的更新补丁，32位报毒，64位正常。

**Comment by didila** [comment]
win10，64位报毒+1

**Comment by 5m17h** [comment]
那么到底有毒没？哪个进程早操作可疑了？

**Comment by xiaokangwang** [comment]
已经确认杀毒软件报告病毒。 https://www.virustotal.com/gui/file/6c41f5802d0453a6b829818f33ca0bd0837bf07f4dd547bdc5946b31489293ca/detection

**Comment by xiaokangwang** [comment]
在几个开发者本机编译的程序也会被报告为病毒。因此这个杀毒软件的报告是误报，我近期和杀毒软件开发商讨论一下这个问题。

**Comment by xiaokangwang** [comment]
而且好像杀毒软件的病毒库还会针对V2进行更新。。。。

**Comment by xiaokangwang** [comment]
已经向 Avast， Symantec， Microsoft, McAfee 报告检测错误，我等下继续报告。

**Comment by xiaokangwang** [comment]
![image](https://user-images.githubusercontent.com/1883569/83966868-66965600-a8ef-11ea-8ea2-c2ddd122e96f.png)

**Comment by xiaokangwang** [comment]
![image](https://user-images.githubusercontent.com/1883569/83967024-972abf80-a8f0-11ea-8967-21318cba2b9a.png)

**Comment by xiaokangwang** [comment]
已经向 SecureAPlus, avast , aegislab, avira, ikarus 报告检测错误，瑞星就算了不自投罗网了。

**Comment by liaoran** [comment]
Not only Rising, but also other domestic anti-virus software, don’t report it,you know.

**Comment by xiaokangwang** [comment]
![image](https://user-images.githubusercontent.com/1883569/84022424-ce64a380-a9b8-11ea-9fcc-10a04a1292f5.png)

**Comment by proxysu** [comment]
最新版本4.24.2，windows 32位与64位，Windows Defender已不再报毒，win10 pro 1909

**Comment by xiaokangwang** [comment]
![image](https://user-images.githubusercontent.com/1883569/84383307-a4141f80-ac1e-11ea-95eb-936968a2e92c.png)

**Comment by xiaokangwang** [comment]
> 最新版本4.24.2，windows 32位与64位，Windows Defender已不再报毒，win10 pro 1909

我使劲联系微软从病毒库里面删掉的，发布一次联系一次。

**Comment by xiaokangwang** [comment]
![image](https://user-images.githubusercontent.com/1883569/84385781-c0b25680-ac22-11ea-876f-2e7a6d3f3e9d.png)

**Comment by weeshinwang** [comment]
Windows Defender报病毒

v4.25.1 Windows X64版本

受影响程序：
v2rayN-Core\v2ctl.exe

检测到的威胁
Trojan:Win32/Spursint.F!cl

**Comment by just4xcx** [comment]
v4.28.2 也被Defender报病毒了
![v2ray-reported-trojan](https://user-images.githubusercontent.com/48905496/94218282-b3da1a00-ff16-11ea-82ad-ea448da79241.png)
