### ISSUE TITLE
[Feature Request] 可变协议格式

### ISSUE THREAD

**Issue by bhoppi** [v2ray/v2ray-core#2550]
最近有不少关于V2Ray如何改进协议的话题，我也参与了讨论。今天我突然有了另外一种思路，可不可以允许VMess协议格式可变，并可以通过配置文件修改？初步想法如下：
暂不考虑认证部分和数据部分，仅对指令部分调整。首先给指令部分的字段按照默认顺序命名为0~D（即版本号为字段0，数据加密 IV为字段1，…，校验 F为字段D）。然后我们可以在配置文件里指定这些字段的顺序，比如：`"schema": "1032654879CABD"`，如不指定就是默认的`"0123456789ABCD"`。当然这个顺序并非可以任意指定，需要满足一些约束，比如D要在最后，5、6要在一起，A要在B前面，以及一些安全性约束比如C的位置等等。当然这些约束不需要用户来考虑，可以提供API和命令行例如`v2ctl randschema`来自动生成该项配置。
这个方案的好处：1.首先是抗主动检测能力大大提升；2.只要代码实现得当，能够做到几乎不会损失性能；3.能够与现有格式兼容（当然并非真正的完全兼容，需要正确地使用才行）。

**Comment by 33lyl** [comment]
提议很好，就是感觉会进入一种奇怪循环？

**Comment by bhoppi** [comment]
> 
> 
> 提议很好，就是感觉会进入一种奇怪循环？

这个“奇怪循环”具体是指？

**Comment by liushengqi000** [comment]
就是预置密码对指令区加密。没有预置密码就不加密，一般用XOR就够了，乱序不会更安全。

**Comment by bhoppi** [comment]
> 
> 
> 就是预置密码对指令区加密。没有预置密码就不加密，一般用XOR就够了，乱序不会更安全。

XOR无法抵挡密文填充攻击，而且现在的指令区已经有加密了。

**Comment by bhoppi** [comment]
我后来考虑了一下，我这个方案只能保证大部分用户的安全，却会造成一小部分“不幸”的用户，被封了都找不到原因。有一个解决的办法，schema不要事先指定，而是每个包都有一个随机的字段顺序，并增加一个schema字段指明当前数据包的字段顺序。
