### ISSUE TITLE
[Feature Request] 做一个 Chromium / Firefox 插件，接管 v2ray WSS 等请求

### ISSUE THREAD

**Issue by rprx** [v2ray/v2ray-core#2552]
本来我是在想，[VLess](https://github.com/v2ray/v2ray-core/issues/2547) 足够简单，甚至可以推出个 Chrome 插件，就不用担心 TLS 指纹问题了

然后想到更通用的方法是：**做一个 Chromium / Firefox 插件，接管 v2ray WSS 等请求**

### 重点：每个人的浏览器版本略有不同，TLS 指纹和你平时浏览网页时完全一样

---

之前开了个讨论 https://github.com/v2ray/discussion/issues/706 ，最好的落脚点还是直接用 Chromium 的代码
这样也相当于是用 Chrome 的网络层，除了对 iOS 设备不太友好（iOS 连 Firefox 都装不了插件）
不过，局域网内有一个开着的浏览器就行（路由器翻墙买个树莓派？）

当然，这只是一种解决方案，和其它解决方案也不冲突，欢迎讨论其它解决方案

**Comment by rprx** [comment]
不过这个方法需要：
1. Chrome 插件可以监听端口，或者其它通信方式（尚未确认）
2. Chrome 插件可以建立纯 TLS 连接（WebSocket 倒不需要担心）

**Comment by rprx** [comment]
@Kylejustknows 类似于你的接口想法

**Comment by 1608637229** [comment]
不是很懂，那是不是只能浏览翻了。其他的桌面软件能支持吗

**Comment by rprx** [comment]
> 
> 
> 不是很懂，那是不是只能浏览翻了。其他的桌面软件能支持吗

不是只能浏览器翻，是 v2ray 程序的 WSS、HTTP/2 等请求转交给浏览器插件发出

比如：其它桌面软件 -> v2ray -> 浏览器插件 -> 你的服务器 -> 最终请求地址

为了用浏览器的 TLS 指纹，中间多了“浏览器插件”这一层而已，其它没任何变化

**Comment by rprx** [comment]
或者可以改一下 Chromium 的代码编译出独立程序，为 v2ray 提供 WSS 代请求等，无需 hard code 进 v2ray 里。更多的，就像 @Kylejustknows 在 #2547 中描述的一样。

**Comment by 89650021** [comment]
> 
> 
> [已确认 Chrome 插件可以监听端口。](https://crxdoc-zh.appspot.com/apps/app_network)
> 
> 似乎不能发起纯 TLS 连接，但 WSS 和 HTTP/2 还是可以的，QUIC 应该也可以。
> 
> （其中 [WS](https://zh.wikipedia.org/wiki/WebSocket) 的 [Base64](https://zh.wikipedia.org/wiki/Base64) 编码会使数据量膨胀 33% 左右，VMess + WSS 一直以来都是这样。）

On January 15, 2020 Google announced that Chrome will begin phasing out support for Chrome Apps across all operating systems starting in March 2020

**Comment by rprx** [comment]
> 
> 
> > [已确认 Chrome 插件可以监听端口。](https://crxdoc-zh.appspot.com/apps/app_network)
> > 似乎不能发起纯 TLS 连接，但 WSS 和 HTTP/2 还是可以的，QUIC 应该也可以。
> > （其中 [WS](https://zh.wikipedia.org/wiki/WebSocket) 的 [Base64](https://zh.wikipedia.org/wiki/Base64) 编码会使数据量膨胀 33% 左右，VMess + WSS 一直以来都是这样。）
> 
> On January 15, 2020 Google announced that Chrome will begin phasing out support for Chrome Apps across all operating systems starting in March 2020

我记得这件事，因为用的人少被砍掉了，没有留意到那个链接是 Chrome Apps 而不是扩展程序。
看来这并不是一个长久的方法，还是直接用 Chromium 的代码吧（或者 Electron？）
