### ISSUE TITLE
[Feature Request] 在V2Ray配置文件routing中加入指定geoip/site路径的功能

### ISSUE THREAD

**Issue by TheWanderingCoel** [v2ray/v2ray-core#2553]
Please describe the new feature you want in detail.
V2Ray目前提供了一个``V2RAY_LOCATION_ASSET``环境变量可以供直接使用二进制的用户/GUI客户端使用，对于把V2Ray当做库使用的来说，没有办法设置geoip/site路径的路径而导致V2Ray会搜索程序的目录，很少有人会把geoip/site.dat放在``/usr/local/bin``或者``xx.app/Contents/MacOS/``里。希望V2Ray能加一个这样的设置,感谢。

**Update**:
使用``qputenv``或者``setenv``均无法让v2ray检测另外一个目录

**Comment by littlesum** [comment]
linux 可以做个软链接

**Comment by TheWanderingCoel** [comment]
> linux 可以做个软链接

主要是要一个跨平台式的方案，像同类别的软件可以在json配置文件里指定位置就挺不错的。

**Comment by xiaokangwang** [comment]
V2Ray have considered this already. Change NewFileReader in the https://github.com/v2fly/v2ray-core/blob/master/common/platform/filesystem/file.go .
