### ISSUE TITLE
大量报错 failed to drain connection DrainSize = 2299 14 1 > v2ray.com/core/proxy/vmess/encoding: invalid user

### ISSUE THREAD

**Issue by 89650021** [v2ray/v2ray-core#2554]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
服务器 aws debain 10, nginx1.14.2, cloudflare CDN  v2ray 4.23.4
手机客户端Kitsunebi，位于墙内/墙外 电脑客户端v2ray本体 操作系统 windows10/debian10 位于墙外
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
墙外手机/电脑客户端连接一切正常 墙内连接大量报错
4) 你期待看到的正确表现是怎样的？

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:
{
          "log": {
                      "access": "xxxx",
                          "error": "xxxx",
                              "loglevel": "warning"
                                },
                                  "inbounds": [
                                              {
                                                            "port": ,
                                                                  "listen": "127.0.0.1",
                                                                        "protocol": "vmess",
                                                                              "settings": {
                                                                                              "clients": [
                                                                                                                {
                                                                                                                                    "id": "",
                                                                                                                                                "alterId": 64
                                                                                                                                                          }
                                                                                                                                                                ]
                                                                                                                                                              },
                                                                                                                                                            "streamSettings": {
                                                                                                                                                                    "network": "ws",
                                                                                                                                                                    "wsSettings": {
                                                                                                                                                                      "path": ""
                                                                                                                                                              }
                                                                                                                                                            }
                                                                                                                                                                }
                                                                                                                                                          ],
                                                                                                                                                            "outbounds": [
                                                                                                                                                                {
                                                                                                                                                              "protocol": "freedom",
                                                                                                                                                            "settings": {}
                                                                                                                                                                },
                                                                                                                                                            {
                                                                                                                                                                  "protocol": "blackhole",
                                                                                                                                                                "settings": {},
                                                                                                                                                              "tag": "block"
                                                                                                                                                          }
                                                                                                                                                            ],
                                                                                                                                                              "routing": {
                                                                                                                                                          "domainStrategy": "IPOnDemand",
                                                                                                                                                              "rules": [
                                                                                                                                                            {
                                                                                                                                                                    "type": "field",
                                                                                                                                                                    "outboundTag": "block",
                                                                                                                                                                    "ip": ["geoip:cn"]
                                                                                                                                                                  },
                                                                                                                                                                {
                                                                                                                                                                "type": "field",
                                                                                                                                                                "outboundTag": "block",
                                                                                                                                                                "domain": ["geosite:cn"]
                                                                                                                                                              }
                                                                                                                                                          ]
                                                                                                                                                            }
}

客户端配置:
{
"log": {
    "loglevel": "debug"
  },
  "inbounds": [
    {
      "port": 1080,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": false,
        "destOverride": ["http", "tls"]
      },
      "settings": {
        "auth": "noauth",
        "udp": false
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "",
            "port": 443,
            "users": [
              {
                "id": "",
                "alterId": 64
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "wsSettings": {
          "path": ""
        }
      }
    }
  ]
}

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

none

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
大量类似这种的日志
2020/XXXX XXXX:58880 rejected  v2ray.com/core/proxy/vmess/encoding: failed to drain connection DrainSize = 2299 14 1 > v2ray.com/core/proxy/vmess/encoding: invalid user
偶尔可见：
2020/XXXX XXXX:58968 accepted tcp:android.clients.google.com:443
墙外客户端连接未见报错

8) 其它相关的配置文件（如 Nginx）和相关日志。
nginx 日志
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 4 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 4 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 6957 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 4 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 5464 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 8796 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 5510 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 4402 "-" "Upgrade" "websocket" "Go-http-client/1.1"
172.68.189.88 - 客户端地址 - - [] "GET https://XXXX HTTP/1.1" 101 0 "-" "Upgrade" "websocket" "Go-http-client/1.1"

====
nginx.conf:

user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
}

http {
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        server_tokens off;
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        ssl_protocols  TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;  
        log_format main
        '$remote_addr - $http_x_forwarded_for - $remote_user [$time_local] '
        '"$request_method $scheme://$host$request_uri $server_protocol" '
        '$status $body_bytes_sent "$http_origin" "$http_connection" "$http_upgrade" "$http_user_agent"';

        access_log /var/log/nginx/access.log main;
        error_log /var/log/nginx/error.log warn;

        gzip on;   
        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}

====
site-enabled

server {
  listen 443 ssl;
  listen [::]:443 ssl;

  ssl_certificate      xxxxx;
  ssl_certificate_key   xxxxxx;
  ssl_session_timeout 1d;
  ssl_session_cache shared:MozSSL:10m;
  ssl_session_tickets off;

  ssl_protocols         TLSv1.2 TLSv1.3;
  ssl_ciphers           ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
  ssl_prefer_server_ciphers off;
    server_name        xxxxx;
    location /xxxxxx {
      if ($http_upgrade != "websocket") {
          return xxxxxx;
      }
      proxy_redirect off;
      proxy_pass http://127.0.0.1:xxxxx;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      }
        location / {      return xxxxxxx;}
}
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    return xxxxx
}

}

请预览一下你填的内容再提交。

**Comment by darhwa** [comment]
nginx里指定了ws反向代理的路径，但是v2ray客户端设置path是空的。

**Comment by zmaplex** [comment]
今天升级到 4.23.4 后也出现这个情况。
```
2020/06/10 19:08:09 120.239.36.14:18988 rejected  v2ray.com/core/proxy/vmess/encoding: failed to drain connection DrainSize = 388 34 26 > v2ray.com/core/proxy/vmess/encoding: invalid user
2020/06/10 19:08:10 223.73.20.170:12262 rejected  v2ray.com/core/proxy/vmess/encoding: failed to drain connection DrainSize = 388 34 18 > v2ray.com/core/proxy/vmess/encoding: invalid user
2020/06/10 19:08:12 120.239.36.14:19010 rejected  v2ray.com/core/proxy/vmess/encoding: failed to drain connection DrainSize = 388 34 1 > v2ray.com/core/proxy/vmess/encoding: invalid user
```

**Comment by Excited-Frog** [comment]
我也是

**Comment by wklzxv** [comment]
我也是，4.23.4这个bug，网络变得好差，一会连得上一会连不上

**Comment by 70599** [comment]
请确认服务端与客户端之间时间是否同步（时区无所谓）

**Comment by zmaplex** [comment]
> 请确认服务端与客户端之间时间是否同步（时区无所谓）

同步的

**Comment by 89650021** [comment]
> nginx里指定了ws反向代理的路径，但是v2ray客户端设置path是空的。是否是这个原因？

隐私问题隐去了

**Comment by GeneKong** [comment]
V2Ray 4.25.1 默认配置也有这个问题，不过windows的v2rayN可用，linux默认配置也不行；

**Comment by GeneKong** [comment]
我的问题是服务器时间不同步导致的，

**Comment by Greatsaltedfish** [comment]
我也是遇到差不多的情况的情况，vmess+ws+tls,用caddy转发
v2ray(V2Ray 4.28.0 )服务器配置如下：
`{
  "log":{
     "access":"/var/log/v2ray/access.log",
     "error":"/var/log/v2ray/error.log",
     "loglevel":"debug"
  },
  "dns":{
      "hosts":{
       "domain.me":"127.0.0.1"
      },
      "servers":[
          "8.8.8.8",
          "8.8.4.4",
          "1.1.1.1"
      ]
  },
  "policy":{
    "levels":{
       "0":{
        "handshake": 4,
        "connIdle": 300,
        "uplinkOnly": 2,
        "downlinkOnly": 5,
        "statsUserUplink": false,
        "statsUserDownlink": false,
        "bufferSize": 10240
       }
       
    },
    "system":{
        "statsInboundUplink": true,
        "statsInboundDownlink": true
      }

  },
"inbounds":[
    {
        "port":2333,
        "listen":"127.0.0.1",
        "protocol":"vmess",
        "settings":{
           "clients":[
               {
                   "id":"abc",
                   "alterId":76,
                   "level":0
               }
           ]

        },
        "steamSettings":{
          "network":"ws",
          "wsSettings":{
              "path":"/yyyvay"
              
          }

        }
    }
],"outbounds":[
    {
        "protocol":"freedom",
        "settings":{}
    },
    {
    "protocol": "blackhole",
    "settings": {},
    "tag": "block"
    }
],"routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
    {
    "type": "field",
    "outboundTag": "block",
    "ip": ["geoip:cn"]
    },
    {
    "type": "field",
    "outboundTag": "block",
    "domain": ["geosite:cn"]
    }
    ]
    }
}`

caddy(v2.1.1 h1)配置如下：
`abc.abc.abc:443
{

   log {
 output  file  /var/log/caddy/caddy.log
   }

 route /abcray*{
     reverse_proxy localhost:43333
}

}
`
v2ray的错误日至：
`2020/09/12 04:32:50 [Info] [2012935574] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: invalid request from 127.0.0.1:55984 > v2ray.com/core/proxy/vmess/encoding: failed to drain connection DrainSize = 230 43 7 > v2ray.com/core/proxy/vmess/encoding: invalid user > v2ray.com/core/proxy/vmess: Not Found`
caddy的错误日至;
`{"level":"error","ts":1599887336.375621,"logger":"http.log.access.log0","msg":"handled request","request":{"method":"GET","uri":"/","proto":"HTTP/2.0","remote_addr":"1.1.1.1","host":"abc.abc.abc","headers":{"User-Agent":["Mozilla/5.0 (X11; Linux i686; rv:10.0) Gecko/20100101 Firefox/10.0"],"Accept-Encoding":["gzip"]},"tls":{"resumed":false,"version":772,"ciphersuite":4865,"proto":"h2","proto_mutual":true,"server_name":"abc.abc.abc"}},"common_log":"1.1.1.1 - - [11/Sep/2020:22:08:56 -0700] \"GET / HTTP/2.0\" 502 0","duration":0.001538303,"size":0,"status":502,"resp_headers":{"Server":["Caddy"]}}
`
