### ISSUE TITLE
麻烦问下v2ctl api查询流量，可以远程查询么？

### ISSUE THREAD

**Issue by bbhxwl** [v2ray/v2ray-core#2556]
麻烦问下v2ctl api查询流量，可以远程查询么？我看说gRPC，我做C#的，还没了解过这个，这个是不能用get或post远程获取是吧？

**Comment by CalmLong** [comment]
可以远程查询，但是只能用 gRPC 远程调用，不能直接使用 GET 或者 POST 直接获取

gRPC 支持这些语言：https://grpc.io/docs/languages/

这里有篇文章可以参考：https://medium.com/@TachyonDevel/%E8%B0%83%E7%94%A8-v2ray-%E6%8F%90%E4%BE%9B%E7%9A%84-api-%E6%8E%A5%E5%8F%A3%E8%BF%9B%E8%A1%8C%E7%94%A8%E6%88%B7%E5%A2%9E%E5%88%A0%E6%93%8D%E4%BD%9C-adf9ff972973

获取到的数据都是 `user>>>123@gmail.com>>>traffic>>>downlink` 这种格式的，通常需要自己解析一下
