### ISSUE TITLE
使用supervisor托管v2ray出错

### ISSUE THREAD

**Issue by JimLee1996** [v2ray/v2ray-core#256]
版本 linux-32 release v2.0

服务器环境 debian7

错误提示v2ray: ERROR (spawn error)

配置文件
v2ray配置文件直接采用官方建议

supervisor配置文件如下
`[program:v2ray]
directory=/usr/local/v2ray
command=/usr/local/v2ray/v2ray -config /usr/local/v2ray/config.json
process_name=%(program_name)s
autostart=true
redirect_stderr=true
stdout_logfile=/var/log/v2ray.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=0
`
错误日志信息
`V2Ray v2.0 (One for all) 20160820
An unified platform for anti-censorship.
2016/09/06 14:39:57 [Error]Failed to create access logger on file (/var/log/v2ray/access.log): /var/log/v2ray/access.logopen /var/log/v2ray/access.log: no such file or directory
2016/09/06 14:39:57 [Error]Failed to create access logger on file (/var/log/v2ray/access.log): /var/log/v2ray/access.logopen /var/log/v2ray/access.log: no such file or directory
2016/09/06 14:39:57 [Error]Failed to create Point server: open /var/log/v2ray/access.log: no such file or directory`

**Comment by chamberchain** [comment]
我用centos7（systemd我感觉挺好的，supervisor个人感觉太老了）。 猜测是v2ray权限不够。没有权限创建两个日志文件。

**Comment by JimLee1996** [comment]
谢谢！

**Comment by helloyan** [comment]
你成功了吗，我托管的错误是 Exited too quickly，官方解释是不支持daemon模式，但是v2ray在此情况下应该不是daemon，很奇怪

**Comment by JimLee1996** [comment]
还没有成功。。。已经不用了

**Comment by jiahut** [comment]
blew config works well. 

```config
[program:v2ray] 
command=/usr/local/bin/v2ray -config  /path/to/v2ray-client.conf
autostart=true
process_name=%(program_name)s
redirect_stderr=true 
stdout_logfile=/usr/local/var/log/v2ray.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=0
```

> supervisord  --version
4.0.3
