### ISSUE TITLE
客户端配置多个DNS服务器、且规则有重叠时，用哪个DNS服务器进行解析？

### ISSUE THREAD

**Issue by wlnirvana** [v2ray/v2ray-core#2560]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

V2Ray 4.23.4 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.1 linux/arm)

2) 你的使用场景是什么？

对DNS servers中的部分domains规则（如大陆已经解封的fonts.googleapis.com）进行override，实现DNS分流

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

DNS解析规则重叠/冲突时，无法override，且优先级规则不清晰

4) 你期待看到的正确表现是怎样的？

我在旁路由上配置了DNS和透明代理，且使用的[`geosite:geolocation-!cn`](https://github.com/Loyalsoldier/v2ray-rules-dat)中包含了`fonts.googleapis.com`。但按如下客户端配置无法强制使用alidns解析fonts.googleapis.com，`nslookup fonts.googleapis.com 192.168.1.2`时仍然会走1.1.1.1，解析出类似`172.217.194.95`的地址。

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

客户端配置:

```javascript
  "dns": {
    "servers": [
      {
        "address": "https+local://dns.alidns.com/dns-query",
        "domains": [
          "geosite:cn",
          "fonts.googleapis.com"
        ]
      },
      {
        "address": "https://1.1.1.1/dns-query",
        "domains": [
          "geosite:geolocation-!cn",
          "geosite:speedtest"
        ]
      },
      "223.5.5.5"
    ]
  },
```

**Comment by wenjinlibug** [comment]
@wlnirvana 还有当同时存在ipv4和ipv6的dns规则时会怎样？比如
```
  "dns": {
    "servers": [
      {
        "address": "127.0.0.1",
      },
      {
        "address": "::1",
      }
    ]
 },
```
总觉得v2ray并没有正确的填好A记录和AAAA记录。
