### ISSUE TITLE
15 seconds TCP Keep-Alive, high battery drain on mobile devices (golang default)

### ISSUE THREAD

**Issue by ValdikSS** [v2ray/v2ray-core#2564]
1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

Official binaries of `V2Ray 4.24.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.4 linux/amd64)` on both server and client side.

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

I use it as socks5 proxy.

3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)

V2ray sends TCP Keep-Alive packets every 15 seconds, on **every** connected TCP socket (V2ray server-client connections, V2ray outgoing connections to other servers), which leads to high battery usage on mobile devices.

4) What's your expectation?

I expect Keep-Alive interval to be configurable. As V2ray sets `connIdle` to 300 seconds by default, Keep-Alive interval should be around 260 seconds by default.

V2ray should allow to increase TCP Keep-Alive (in the policy settings) or to disable it completely.
15 seconds is a [golang default value](https://go-review.googlesource.com/c/go/+/107196/) and it's way too short. For comparison, Linux sets default keep-alive value to 2 hours (which is probably too high).

5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

Server configuration:

Happens on all vmess and shadowsocks configurations.

Client configuration:

Happens on all vmess and shadowsocks configurations.

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.

8) Other configurations (such as Nginx) and logs.

Keep-Alive packets could be seen with wireshark or tcpdump, on any destination (v2ray server → client, v2ray client → server, v2ray server → remote server).

**Comment by xiaokangwang** [comment]
I think make it configurable should be fine. However, I have no idea what default value should be used.

**Comment by ValdikSS** [comment]
As V2ray sets `connIdle` to 300 seconds by default, Keep-Alive interval should be around 260 seconds by default. On mobile devices with proper network timeout configuration I usually set 900 seconds connection timeout and 600 seconds keep-alive interval.

**Comment by bokemanoh** [comment]
Is 4.24 also affected?

**Comment by ValdikSS** [comment]
@bokemanoh Every version built with go 1.13 and newer is affected.

**Comment by ValdikSS** [comment]
Basically you need to supply `net.Dialer` with `KeepAlive` option. It should be added somewhere to `transport/internet/system_dialer.go` (for connecting sockets)

https://github.com/v2ray/v2ray-core/blob/f9935d0e93eacb62df9ea9d47db685ec1d25c102/transport/internet/system_dialer.go#L69-L74

 or to `applyInboundSocketOptions` / `applyOutboundSocketOptions` for listening/connecting

https://github.com/v2ray/v2ray-core/blob/f9935d0e93eacb62df9ea9d47db685ec1d25c102/transport/internet/sockopt_linux.go#L77

**Comment by ValdikSS** [comment]
I can prepare the patch but I'm not experienced in Go or in V2ray code base, so it may be not perfect. I guess it should be easy and straightforward for anyone with Go experience to fix this.

**Comment by darhwa** [comment]
15s is really too short for a default tcp keepalive idle time. Firefox uses 600s on both desktop and mobile. Chrome uses 45s on desktop, and intentionally doesn't enable it on mobile (https://github.com/chromium/chromium/blob/25292af6cee762330490f47e79e09a071dc4b5a9/net/socket/tcp_socket_posix.cc#L372-L387).

Another idea is just to follow chrome's strategy (45s on desktop and disabled on mobile).

**Comment by therealak12** [comment]
I'm trying to do something for this.
Should the MR be made here or in the [v2fly repository](https://github.com/v2fly/v2ray-core/)?

**Comment by kslr** [comment]
> I'm trying to do something for this.
> Should the MR be made here or in the [v2fly repository](https://github.com/v2fly/v2ray-core/)?

fly

**Comment by therealak12** [comment]
Hi. I think this issue can be considered resolved.
https://github.com/v2fly/v2ray-core/pull/962

**Comment by xiaokangwang** [comment]
Yes, I haven't text it yet. Is there any contributor willing to validate the effect of the option?

**Comment by ValdikSS** [comment]
Does **not** seem to be fixed in v2fly v4.41.1.

Test 1:
1. Run v2fly v4.41.1 with default config.json (remove `geoip:private` block first)
2. start `nc -l -p 4141`
3. execute `curl --proxy socks5://127.0.0.1:1080 127.0.0.1:4141`

Result: 15 second keep-alive *from v2fly to socks client* (1080 → client source port)

Adding `"streamSettings": {"sockopt": {"tcpKeepAliveInterval": 900}},` to both `inbounds` and `outbounds` directives did not change anything.

**Comment by ValdikSS** [comment]
We change the wrong parameter. `TCP_KEEPIDLE` should be changed, not `TCP_KEEPINTVL`.

>TCP_KEEPIDLE (since Linux 2.4)
>        The  time  (in  seconds)  the  connection needs to remain idle before TCP starts sending keepalive probes, if the socket option SO_KEEPALIVE has been set on this socket.  This option should not be used in code intended to be portable.
>
>TCP_KEEPINTVL (since Linux 2.4)
>        The time (in seconds) between individual keepalive probes.  This option should not be used in code intended to be portable.

Go sets both TCP_KEEPINTVL and TCP_KEEPIDLE to 15. Leaving TCP_KEEPINTVL to 15 looks fine to me (Linux default is 75). TCP_KEEPCNT is not changed and kept to standard 9, so 15*9 = 135 seconds before connection teardown, after TCP_KEEPIDLE had an effect.

**Comment by ValdikSS** [comment]
Made a proper fix: https://github.com/v2fly/v2ray-core/pull/1276

**Comment by ValdikSS** [comment]
Issue is fixed in the latest v2fly, not in v2ray.

**Comment by ccaapton** [comment]
> Issue is fixed in the latest v2fly, not in v2ray.

There is a [golang api](https://golang.hotexamples.com/examples/net/Dialer/KeepAlive/golang-dialer-keepalive-method-examples.html) for keep-alive timeout settings, so there is not need for separate implementation for each OS. Besides, it seems android does not benefit from this fix.

**Comment by ValdikSS** [comment]
> There is a [golang api](https://golang.hotexamples.com/examples/net/Dialer/KeepAlive/golang-dialer-keepalive-method-examples.html) for keep-alive timeout settings, so there is not need for separate implementation for each OS.

It does not work properly, more details here: https://github.com/golang/go/issues/48622

> Besides, it seems android does not benefit from this fix.

The v2ray configuration file should be modified on the client as well to apply increased timeout.
Users of other (non-golang) client software would benefit from server-side-only modification, for example, if v2ray is used as a shadowsocks server.

**Comment by ValdikSS** [comment]
bump
