### ISSUE TITLE
aead加密的话，服务端要不要进行操作？

### ISSUE THREAD

**Issue by 1265578519** [v2ray/v2ray-core#2566]
testsEnabled: "VMessAEAD" | "none"

这个在客户端上加上就行了嘛？服务端会自动识别的吗

**Comment by Eintler** [comment]
same question

**Comment by 1265578519** [comment]
@Eintler 文档写了，不用操作，直接在客户端启用就行了

**Comment by Eintler** [comment]
@1265578519 Thanks
