### ISSUE TITLE
希望在更新vmess協議時加入前向糾錯

### ISSUE THREAD

**Issue by wenjinlibug** [v2ray/v2ray-core#2569]
不知道是大陸國內對外封鎖變得比以往更嚴厲，還是因為肺炎導致網絡缺少維護，網絡情況顯然比以往更加糟糕。
最近隨機丟包的情況也越來越嚴重，就我所用的網絡來說從原本繁忙時段10%左右丟包率一下上升到40%，因此我認為前向糾錯可能是必須的，畢竟往後情況只會更加糟糕。

**Comment by kslr** [comment]
那你也许该试试kcp

**Comment by wenjinlibug** [comment]
> 那你也许该试试kcp

事實上我是從SS轉KCP再轉QUIC、TCP、TLS+WS+CDN一路轉戰過來的，可以說是一路上跟“牆”鬥智斗勇，服務器封了再開開了又封，目前除了QUIC和TLS+WS外基本都會在數天內被識別出來導致服務器被封，而QUIC被QoS的情況相當嚴重、繁忙時段流量甚至降到數k，所以唯一可用的其實只有TLS+WS+CDN。

**Comment by lxhao61** [comment]
基本赞同版主建议。希望增强或出现更多类似KCP或QUIC（HTTP/3）的插件应用，以抵抗目前越来越大的延迟与丢包率。

**Comment by lxhao61** [comment]
> > 那你也许该试试kcp
> 
> 事實上我是從SS轉KCP再轉QUIC、TCP、TLS+WS+CDN一路轉戰過來的，可以說是一路上跟“牆”鬥智斗勇，服務器封了再開開了又封，目前除了QUIC和TLS+WS外基本都會在數天內被識別出來導致服務器被封，而QUIC被QoS的情況相當嚴重、繁忙時段流量甚至降到數k，所以唯一可用的其實只有TLS+WS+CDN。

**Comment by liberal-boy** [comment]
> > 那你也许该试试kcp
> 
> 事實上我是從SS轉KCP再轉QUIC、TCP、TLS+WS+CDN一路轉戰過來的，可以說是一路上跟“牆”鬥智斗勇，服務器封了再開開了又封，目前除了QUIC和TLS+WS外基本都會在數天內被識別出來導致服務器被封，而QUIC被QoS的情況相當嚴重、繁忙時段流量甚至降到數k，所以唯一可用的其實只有TLS+WS+CDN。

目前基于 UDP 的协议基本都会被 qos，而 TCP 已经自带后向纠错，加上前向纠错纯属画蛇添足。

**Comment by wenjinlibug** [comment]
> > > 那你也许该试试kcp
> > 
> > 
> > 事實上我是從SS轉KCP再轉QUIC、TCP、TLS+WS+CDN一路轉戰過來的，可以說是一路上跟“牆”鬥智斗勇，服務器封了再開開了又封，目前除了QUIC和TLS+WS外基本都會在數天內被識別出來導致服務器被封，而QUIC被QoS的情況相當嚴重、繁忙時段流量甚至降到數k，所以唯一可用的其實只有TLS+WS+CDN。
> 
> 目前基于 UDP 的协议基本都会被 qos，而 TCP 已经自带后向纠错，加上前向纠错纯属画蛇添足。

请大神解释如何使用。
据我这段时间了解到的是TCP设计初衷就是保证连接性，所以有加入丢包重传机制，目前我调试了一下、增大tcp_reordering和开启tcp_sack等选项似乎得到比较好的效果，不过带来的副作用也非常明显，随着tcp_reordering的增加响应速度明显下降。

**Comment by BI7PRK** [comment]
关于被lock或者被QoS的情况。我个人的总结是不要单纯寄望于武器。除了武器之外，还有一个因素就是使用技巧。刀再利，没有功夫也没用。

我的稳定方案是：
+ 3个VPS. （都在USA）
+ VLESS+XTLX
+ 用【连接观测】进行主备自动切换。
在Server端进行以下配置非常有必要。目的是杜绝这样的链路：user (CN)-->vps (OUTSIDE)-->server(CN). 一去一回会被识别。
```JSON
"routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "domain": [
                    "geosite:cn"
                ],
                "outboundTag": "block",
                "type": "field"
            },
            {
                "ip": [
                    "geoip:cn"
                ],
                "outboundTag": "block",
                "type": "field"
            }
        ]
    }
```

效果如何？

![Snipaste_2022-09-30_11-18-54](https://user-images.githubusercontent.com/24989210/193184109-f3a2cf61-1845-4952-81c9-8c0a7fab52ea.png)
