### ISSUE TITLE
网页经常出现无法加载

### ISSUE THREAD

**Issue by agzfan** [v2ray/v2ray-core#257]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please answer the following questions before submitting your issue. Thank you.

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
1) What version of V2Ray are you using?
v2ray-windows-64.zip (v2.0)
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
2) What your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
chrome+Proxy SwitchyOmega 墙外所有网站
3) 你看到的不正常的现象是什么？
3) What did you see?
经常出现页面里某些连接加载失败
4) 你期待看到的正确表现是怎样的？
4) What do you expected to see instead?
不用刷新页面.....
5) 请附上你的配置文件。
5) Please attach your configuration file.
客户端配置
{
  "log": {
    "loglevel": "warning"
  },
  "inbound": {
    "port": 1080,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "00000",
          "port": 00000,
          "users": [
            {
              "id": "00000",
              "alterId": 64
            }
          ]
        }
      ]
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        }
      ]
    }
  },
  "transport": {
    "kcpSettings": {
      "uplinkCapacity": 10,
      "downlinkCapacity": 10
    }
  }
}

服务器端
{
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 20000,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "00000",
          "level": 1,
          "alterId": 64
        }
      ],
      "features": {
        "detour": {
          "to": "detour"
        }
      }
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  },
  "inboundDetour": [
    {
      "protocol": "vmess",
      "port": "20000-20100",
      "tag": "detour",
      "settings": {},
      "allocate": {
        "strategy": "random",
        "concurrency": 10,
        "refresh": 5
      }
    }
  ],
  "transport": {
    "kcpSettings": {
      "uplinkCapacity": 50,
      "downlinkCapacity": 50
    }
  }
## }

https://github.com/v2ray/v2ray-core/issues/186
和上面这个问题类似
比如打开youtube,SwitchyOmega会经常显示youtube加载失败,youtube建立的连接里某些无法连接,要刷新页面才行
很多网站都是如此,我一开始以为是vps的问题,后来换了好几个都出现这种问题,vps的网络质量很好,我ping 180-200,50次估计才会有1个丢包ping
尝试过删掉客户端上的dns和路由还有动态端口,都没效果,用firefox裸奔没插件也出现这个问题
vps用来锐速,在没锐速度vps上也试过了,还是有这个问题
以上问题出现的几率很大,特别是那种一个页面元素多大站,比如图片的e绅士,视频的youtube
不会是gfw的干扰吧?系统是debian7,线路是联通

**Comment by yjd** [comment]
我到是比如开一天。大部分时间没连接。然后要用的时候打开y2b等墙外网站。打不开。
把本地客户端重启下无效。必须登入远程vps重启下服务端才生效。
目前还是主用ssr，v2当备用。

**Comment by agzfan** [comment]
补充点资料
今天我又用了另一种方法做了实验
客户端--->v2ray--->ssh--->网站
用这个方法没有出现加载失败的问题,加了个ssh意味着只有单线程连接
我没有用过ss不知道ss是否有这种问题,晚点我试着装一个ss实验下

**Comment by agzfan** [comment]
装了shadowsocks-libev发现完全没上面的情况
有2个站点非常明显的反映出我v2ray的问题,2个站分别是pornhub和tumblr,具体可以google,没有广告的意思,纯粹技术行为......用v2ray的可以去试试这2个站点特别是pornhub

客户端--->v2ray--->网站
pornhub,第一次打开没发现问题,但是你随便点一个视频进去,就发现问题了,然后在点其他视频,有没发现浏览器页面那个一直在转圆圈?很多图根本刷不出来,而且这个网站特别特别卡,pornhub这个站特别明显!在怎么刷新都没用,根本打不开,同一台服务器ss秒开
tumblr也有同样问题,用v2ray很多视频图片无法刷新,而且经常卡住,ss没有问题

我用了动态端口,以前看到有人用远程桌面会断流,我实际使用中也就开始的时候会断,后来一直保持了10几个小时不断

**Comment by chamberchain** [comment]
我也有这样的问题。查看了一下服务端的error.log，客户端的IP有时候验证为invalid user. 这会不会是造成常常断流的原因呢？

**Comment by wtlusvm** [comment]
服务器内存够大的话将客户端的"alterId" 改成256 试试。

**Comment by agzfan** [comment]
我试了最新的2.1.2版,还有1.14后的几个版本
都出现了上面的问题.....
试着建立了一个虚拟机,什么软件都没装,无解
还是了中间加一个kcptun,无解......

**Comment by Jason4774** [comment]
http://www.cnblogs.com/shenjieblog
我也发现有的网站加载异常，比如这个网站加载的时候一直转圈，用其他的代理工具就是正常的。而且感觉v2ray的速度慢了一些呢？该怎么解决啊？谢谢

**Comment by Jason4774** [comment]
还有很多其他的网站也是一样的。

**Comment by Jason4774** [comment]
我不是用的linux的，是windows的。

**Comment by agzfan** [comment]
经测试v2ray建立的ss服务器,没有上面这个问题

**Comment by Jason4774** [comment]
这个是前段时间服务器遭受DDOS攻击的时候不能用，现在已经好了，谢谢你的回复。

**Comment by joyhope** [comment]
v2ray 我也遇到网页比较难打开。 我删除route里面的china 相关部分，强制全局翻。在这个情况下，访问sina，基本上也没也无法打开。 

我的配置基本上就是默认安装的配置。v2ray的存在问题的可能性比较大。

**Comment by Jason4774** [comment]
那次应该就是月底流量用完了吧。现在已经好了 。

**Comment by v2ray** [comment]
请验证服务器和客户端的系统时间，时间相差必须小于2分钟。另外 2.14 中修复了一些可能导致并发连接效率差的问题。
