### ISSUE TITLE
实测 GFW 可以间歇性阻断v2ray vmess链接

### ISSUE THREAD

**Issue by realabertian** [v2ray/v2ray-core#2571]
GFW表现为 间隔阻断v2ray链接, 放行10秒, 阻断2分钟 (时间不准确), 严重怀疑v2ray-vmess协议已经被破

**Comment by txdywy** [comment]
不用怀疑了

realabertian <notifications@github.com> 于 2020年6月13日周六 下午8:18写道：

**Comment by okudayukiko** [comment]
中国移动全家桶最近似乎已经全面切割海外IP，包括V2Ray+CloudFlare等方案都失效了。换中国电信就好了。
