### ISSUE TITLE
多ip出口问题

### ISSUE THREAD

**Issue by bbhxwl** [v2ray/v2ray-core#2572]
我看到之前有人问的
https://github.com/v2ray/v2ray-core/issues/2276
看配置文件可以设置某个ip进口对应某个ip出口，可以设置监听0.0.0.0，能不能自动设置对应的ip呢？比如设置0.0.0.0，访问1.1.1.1这个ip，出口自动就是1.1.1.1，不用每个ip都设置？

**Comment by bbhxwl** [comment]
我的配置文件如下，我是直接在 
"port": 10086,
"protocol": "dokodemo-door",
 这个下面追加
"tag": "in-01
      "listen: "1.1.1.1",
      ...
这个么？后面这个... 没有什么其他数据吧？只加这2个字段就行吗？想求一个具体配置文件看下格式。保留api 调用接口这个。
{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "info"
  },
  "inbounds": [
    {
      "port":365,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "883ccae6-b60e-438f-b19-f6c5a0b5e8f2",
            "alterId": 1,
            "email": "default9705356@v2.com"
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "none",
        "tlsSettings": {},
        "tcpSettings": {},
        "kcpSettings": {},
        "httpSettings": {},
        "wsSettings": {
          "path": "/XLycVF3d/",
          "headers": {
            "Host": "baidu.com"
          }
        },
        "quicSettings": {}
      },
      "tag": "A"
    },
    {
      "listen": "127.0.0.1",
      "port": 10086,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "ip": [
          "0.0.0.0/8",
          "10.0.0.0/8",
          "100.64.0.0/10",
          "169.254.0.0/16",
          "172.16.0.0/12",
          "192.0.0.0/24",
          "192.0.2.0/24",
          "192.168.0.0/16",
          "198.18.0.0/15",
          "198.51.100.0/24",
          "203.0.113.0/24",
          "::1/128",
          "fc00::/7",
          "fe80::/10"
        ],
        "outboundTag": "blocked"
      },
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      }
    ]
  },
  "stats": {},
  "api": {
    "services": [
"HandlerService",
    "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "policy": {
    "levels": {
      "0": {
        "statsUserDownlink": true,
        "statsUserUplink": true
      }
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true
    }
  }
}

**Comment by CHORDZHUO** [comment]
同求方法

**Comment by liushengqi000** [comment]
我想知道配合cdn时有没有自动随机子域名配合随机cdn ip连接的方法
