### ISSUE TITLE
大量的连接关闭 断流

### ISSUE THREAD

**Issue by jonwinters** [v2ray/v2ray-core#2575]
最新问题 是树莓派的最新版本  客户端不断地的出现段错误
因为我用了守护进程 所以会断地断开重连

[core.zip](https://github.com/v2ray/v2ray-core/files/4803864/core.zip)

core文件已经上传

**Comment by Kylejustknows** [comment]
看了一下日志，你的服务器根本没有被客户机连接到。

如果我是你，会先测试一下你自己的网站，看看你https直接连接服务器有没有问题。
如果你的网站被封了，那是另一回事了。

如果你的https连接没有问题，但是躲在https后面的v2ray就是没法被连接，那么，1你自己机器上的防火墙查查看，2你的服务器nginx或者caddy等等配置有故障

**Comment by jonwinters** [comment]
> 看了一下日志，你的服务器根本没有被客户机连接到。
> 
> 如果我是你，会先测试一下你自己的网站，看看你https直接连接服务器有没有问题。
> 如果你的网站被封了，那是另一回事了。
> 
> 如果你的https连接没有问题，但是躲在https后面的v2ray就是没法被连接，那么，1你自己机器上的防火墙查查看，2你的服务器nginx或者caddy等等配置有故障

老哥 我基本上排查到问题了
因为我的路由 走了openvpn 到办公室 然后办公室的CN2 再走到我的香港服务器
办公室直连是没有问题的，但是家里经过路由openvpn再到香港就出问题了 现在还在排查中

**Comment by jonwinters** [comment]
> 看了一下日志，你的服务器根本没有被客户机连接到。
> 
> 如果我是你，会先测试一下你自己的网站，看看你https直接连接服务器有没有问题。
> 如果你的网站被封了，那是另一回事了。
> 
> 如果你的https连接没有问题，但是躲在https后面的v2ray就是没法被连接，那么，1你自己机器上的防火墙查查看，2你的服务器nginx或者caddy等等配置有故障

问题也不在openvpn 因为我用了supervisord作为守护进程运行的 实际上v2ray 在我的树莓派客户端有好多次 段错误退出 重启的情况..

**Comment by nobk** [comment]
v2ray执行程序的强壮性(鲁棒性?)的确有些问题，不同架构的编译器差异吗？
4.25.0的arm版我这里也频繁自己退出，然而mipsel版又正常。

**Comment by rprx** [comment]
@jonwinters @nobk 

把所有依赖升级到最新版本然后手动编译即可解决。
