### ISSUE TITLE
4.24.2  windows 32位版本运行不了

### ISSUE THREAD

**Issue by cheng-max** [v2ray/v2ray-core#2578]
4.24.2 windows32位版本程序运行windows2003 32系统时出错，提示不是有效的32位程序。

**Comment by GST998** [comment]
# 那就试试64位

**Comment by cyilin** [comment]
4.24.2使用的是golang 1.14，最低windows版本要求是windows 7。
2003/xp请找旧版v2ray用。

**Comment by cheng-max** [comment]
具体是哪个版本可运行在32位WIN2003下呢？谢谢

**Comment by kslr** [comment]
4.23.1
