### ISSUE TITLE
如何配置指定国内网站翻墙访问？

### ISSUE THREAD

**Issue by lewisec** [v2ray/v2ray-core#258]
在办公室使用v2ray。
公司互联网出口的上网行为管理设备限制使用126.com邮箱。
能不能在v2ray上配置，实现访问www.126.com的流量都翻墙？实现穿越深信服的效果？

**Comment by v2ray** [comment]
在标准配置中，把下面的两段删除即可：

```javascript
{
  "type": "chinasites",
  "outboundTag": "direct"
},
```

```javascript
{
  "type": "chinaip",
  "outboundTag": "direct"
}
```

**Comment by lewisec** [comment]
谢谢老大回复。
这样配置会把所有的国内网站都走代理。
如何设置指定的url不direct？
感觉应该是在配置文件里，routing一节里添加，但是没搞懂具体怎么配。
