### ISSUE TITLE
路由规则判断逻辑存在问题

### ISSUE THREAD

**Issue by anyktx** [v2ray/v2ray-core#2586]
路由规则判断逻辑存在问题，在于 文件 app/router/condition.go: func (v *ConditionChan) Apply(ctx *Context)中，应该是匹配任一规则则使用路由，而在程序中处理的逻辑是没有匹配任一规则则不使用路由。
所以导致任何路由规则都不能生效。昨天提交了 Pull request(#2585 ) 但是被判断为存在问题。希望测试更改

**Comment by qydysky** [comment]
对于一条路由规则，“当多个属性同时指定时，这些属性需要同时满足，才可以使当前规则生效”，应该没错吧

**Comment by qqqaadd** [comment]
对于一条路由规则，“当多个属性同时指定时，这些属性需要同时满足，才可以使当前规则生效”，应该没错吧

**Comment by anyktx** [comment]
这样的设计的话那判断逻辑是没问题的。但是，一次请求判定中，判定domain和ip和不可能同时满足，因为这两个不是在一个阶段所以是不能同时满足的。


"AsIs": 只使用域名进行路由选择。默认值。
"IPIfNonMatch": 当域名没有匹配任何规则时，将域名解析成 IP（A 记录或 AAAA 记录）再次进行匹配；
当一个域名有多个 A 记录时，会尝试匹配所有的 A 记录，直到其中一个与某个规则匹配为止；
解析后的 IP 仅在路由选择时起作用，转发的数据包中依然使用原始域名；
"IPOnDemand": 当匹配时碰到任何基于 IP 的规则，将域名立即解析为 IP 进行匹配；
以上也表明，不应该是全部满足时才使用。有判断DomainStrategy的逻辑，但是之后判断也是要全部符合后才会为true。


在使用中，配置了如果路由规则 ：


  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "outboundTag": "direct",
"domain": [
"www.ip.cn"
],
        "ip": [
          "geoip:cn"
        ]
      }
    ]
  }


direct 配置为fredom直接访问；inbound 协议为 http 代理协议。
期望的是域名为 www.ip.cn 或为 cn 的IP时直接访问，实际情况是任何访问都不会直接访问。


我认为，domain 和 ip 规则应该为 "或" 逻辑，或二者只中选其一；而与其他规则可以为 "与" 逻辑。
谢谢




在 2020-06-22 13:00:56，"qqqaadd" <notifications@github.com> 写道：

对于一条路由规则，“当多个属性同时指定时，这些属性需要同时满足，才可以使当前规则生效”，应该没错吧

**Comment by qqqaadd** [comment]
我做了如下配置。
```
//直联
{
      "protocol": "freedom",
      "tag": "drOut",
      "settings": {
        "level": 1
      },
      "mux": {
        "enabled": false
      }
    }
```
```
//转直连
{
        "protocol": "freedom",
        "tag": "drtOut",
        "proxySettings": {
          "tag": "drOut"
        },
        "mux" : {
          "enabled": false
        }
    }
```
```
//路由
{
        "type": "field",
        "outboundTag": "drtOut",
        "domain": ["domain:w3school.com.cn"],
        "ip": [
          "geoip:cn"
        ]
      }
{
        "type": "field",
        "outboundTag": "drOut",
        "ip": [
          "geoip:cn",
          "geoip:private",
          "0.0.0.0",
          "255.255.255.255"
        ]
      }
```
```
//accer.log
2020/06/22 18:34:25 [Info] [2328313027] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.w3school.com.cn:443
2020/06/22 18:34:25 [Info] v2ray.com/core/app/dns: UDP:192.168.50.1:53 got answere: www.w3school.com.cn. TypeA -> [120.55.40.41] 4.9877ms
2020/06/22 18:34:25 [Info] [2328313027] v2ray.com/core/app/dispatcher: taking detour [drtOut] for [tcp:www.w3school.com.cn:443]
2020/06/22 18:34:25 [Info] [2328313027] v2ray.com/core/proxy/freedom: opening connection to tcp:www.w3school.com.cn:443
2020/06/22 18:34:25 [Info] [2328313027] v2ray.com/core/proxy/freedom: opening connection to tcp:www.w3school.com.cn:443
2020/06/22 18:34:25 [Info] [2328313027] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.w3school.com.cn:443
```
```
//其他域名走了另一规则
2020/06/22 18:36:20 [Info] [4100593548] v2ray.com/core/proxy/socks: TCP Connect request to tcp:api.bilibili.com:443
2020/06/22 18:36:20 [Info] v2ray.com/core/app/dns: UDP:192.168.50.1:53 got answere: api.bilibili.com. TypeA -> [110.43.34.72 110.43.34.66 139.159.252.156 139.159.241.37 110.43.34.184 139.159.246.60] 4.9851ms
2020/06/22 18:36:20 [Info] [4100593548] v2ray.com/core/app/dispatcher: taking detour [drOut] for [tcp:api.bilibili.com:443]
2020/06/22 18:36:20 [Info] [4100593548] v2ray.com/core/proxy/freedom: opening connection to tcp:api.bilibili.com:443
2020/06/22 18:36:20 [Info] [4100593548] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:api.bilibili.com:443
```
看起来符合逻辑。如果想判断为cn域名或为cn的ip，为什么不写成两条规则呢，一条只有域名判断，另一条只有ip判断，同时指向同个出口。`

**Comment by anyktx** [comment]
没有理解设计精神，谢谢指点🙏！发自我的华为手机-------- 原始邮件 --------发件人： qqqaadd <notifications@github.com>日期： 2020年6月22日周一 18:41收件人： v2ray/v2ray-core <v2ray-core@noreply.github.com>抄送： anyktx <ayktx@163.com>, Author <author@noreply.github.com>主    题： Re: [v2ray/v2ray-core] 路由规则判断逻辑存在问题 (#2586)

我做了如下配置。

//直联

{

      "protocol": "freedom",

      "tag": "drOut",

      "settings": {

        "level": 1

      },

      "mux": {

        "enabled": false

      }

    }



//转直连

{

        "protocol": "freedom",

        "tag": "drtOut",

        "proxySettings": {

          "tag": "drOut"

        },

        "mux" : {

          "enabled": false

        }

    }



//路由

{

        "type": "field",

        "outboundTag": "drtOut",

        "domain": ["domain:w3school.com.cn"],

        "ip": [

          "geoip:cn"

        ]

      }

{

        "type": "field",

        "outboundTag": "drOut",

        "ip": [

          "geoip:cn",

          "geoip:private",

          "0.0.0.0",

          "255.255.255.255"

        ]

      }



//accer.log

2020/06/22 18:34:25 [Info] [2328313027] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.w3school.com.cn:443

2020/06/22 18:34:25 [Info] v2ray.com/core/app/dns: UDP:192.168.50.1:53 got answere: www.w3school.com.cn. TypeA -> [120.55.40.41] 4.9877ms

2020/06/22 18:34:25 [Info] [2328313027] v2ray.com/core/app/dispatcher: taking detour [drtOut] for [tcp:www.w3school.com.cn:443]

2020/06/22 18:34:25 [Info] [2328313027] v2ray.com/core/proxy/freedom: opening connection to tcp:www.w3school.com.cn:443

2020/06/22 18:34:25 [Info] [2328313027] v2ray.com/core/proxy/freedom: opening connection to tcp:www.w3school.com.cn:443

2020/06/22 18:34:25 [Info] [2328313027] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.w3school.com.cn:443



//其他域名走了另一规则

2020/06/22 18:36:20 [Info] [4100593548] v2ray.com/core/proxy/socks: TCP Connect request to tcp:api.bilibili.com:443

2020/06/22 18:36:20 [Info] v2ray.com/core/app/dns: UDP:192.168.50.1:53 got answere: api.bilibili.com. TypeA -> [110.43.34.72 110.43.34.66 139.159.252.156 139.159.241.37 110.43.34.184 139.159.246.60] 4.9851ms

2020/06/22 18:36:20 [Info] [4100593548] v2ray.com/core/app/dispatcher: taking detour [drOut] for [tcp:api.bilibili.com:443]

2020/06/22 18:36:20 [Info] [4100593548] v2ray.com/core/proxy/freedom: opening connection to tcp:api.bilibili.com:443

2020/06/22 18:36:20 [Info] [4100593548] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:api.bilibili.com:443



看起来符合逻辑。如果想判断为cn域名或为cn的ip，为什么不写成两条规则呢，一条只有域名判断，另一条只有ip判断，同时指向同个出口。`
