### ISSUE TITLE
请教：客户端使用v2ray做代理时，如何设置多WAN口路由？

### ISSUE THREAD

**Issue by rendaa** [v2ray/v2ray-core#2588]
先简述一下实际的使用环境，一个路由器通过两个WAN口接入两家ISP的线路，WAN1所接的ISP提供了公网IP，WAN2没有公网IP（更无法设置反向的NAT），而使用中是需要通过DDNS将WAN1口的公网IP映射给一个域名、以便从外网通过这个域名来访问一些内网的服务的。

DDNS的更新是某个NAS自己完成的，它通过访问厂商设置在公网上的一些网页来反馈出访问那个网页的公网IP（为避免啰嗦的描述，以下暂称这样的服务为checkip服务），再由NAS上的程序来自动更新DDNS域名所对应的IP。如果访问checkip服务时走的是WAN2，那么就会更新成WAN2的IP，但实际上这样就会不能访问内网的服务了。

所以在路由器上我是通过MultiWAN Routing这样的机制来进行限制，对那些checkip服务器都一律只从WAN1口访问。这在NAS的网络设置不走代理上网（直接走网关，就是这路由器）时，是能完全符合预期要求的。

然而，如果NAS设为走代理（具体地，代理由安装在路由器上的v2ray程序提供，NAS走的是HTTP类型的代理），这时我在v2ray的config.json中 routing rules 加入了处理方式为 direct 的策略，本意是让v2ray直接把这些流量作为直连的流量，扔回路由器继续处理，但实际使用中却发现，经v2ray扔回的访问那些checkip服务器的流量，却不能再被 MultiWAN Routing 有效地限制从WAN1口发出，而有一些是从WAN2口出去的。这就造成有时候动态域名解析到的IP地址成了WAN2口的那个、而无法从外网访问。

所以我的问题是，如何调整v2ray、和/或 路由器的设置，以便能在通过v2ray代理访问时，使对某些域名或IP或端口的访问，能走指定的 WAN 出口？

希望以上描述能让人看明白，这问题的使用背景可能有点小众，但还是希望能遇到能帮助解答或者给点建议的朋友。

**Comment by kslr** [comment]
自己写个ddns报告不就好了

**Comment by rendaa** [comment]
> 自己写个ddns更新不就好了，WAN是在路由按逻辑负载

主要是想继续用NAS厂商提供的那个域名，然而厂商没有透露它的DDNS的更新接口，虽然能抓包看到部分内容，但有些加密或会变化的内容无法自己生成……

**Comment by linfeel** [comment]
整那么复杂干嘛，该路由干的事情让路由干，该v2ray干的事情让v2ray干。在路由上写策略，只让特定的流量走v2ray就好了，干嘛让v2ray干路由该干的事。

**Comment by rendaa** [comment]
> 整那么复杂干嘛，该路由干的事情让路由干，该v2ray干的事情让v2ray干。在路由上写策略，只让特定的流量走v2ray就好了，干嘛让v2ray干路由该干的事。

可能问题的描述太长了，有点没说明白，简单说是那个NAS需要设成走代理，可是走代理的话路由策略就根本不起作用，所以想问的不是让v2ray干路由的事，而是怎么能让v2ray不影响路由策略。

**Comment by linfeel** [comment]
大概理解你的意思，感觉还是在MultiWAN Routing上面找找原因吧，毕竟数据包本身并不能决定在路由上怎么走，还是看规则怎么配置。盲猜，有错见谅。
