### ISSUE TITLE
[建议] 将 mKCP 功能做为分连接配置

### ISSUE THREAD

**Issue by ToutyRater** [v2ray/v2ray-core#259]
目前 V2Ray 的 mKCP 是全局的配置，只要配置了 KCP，无论哪个 inbound 使用了 KCP，如 tti、 uplinkCapacity 这些 KCP 的配置在每个 inbound 中都是一样的。KCP 比较适合在网络环境稳定的情况下使用，但是，就算使用的网络是稳定的，大多数人长期使用的网络也不止一个（公司、家里、手机流量、学校、实验室等）。这些网络的状况基本不会一样，在目前全局配置的 KCP 之下只能对其中一个网络调整到最佳效果。如果 KCP 做成分连接配置，假如常用的网络有 3 个，那么就可以为这 3 个网络配置 3 个 inboud，在这 3 个 inboud 中的 KCP 可以针对这 3 个网络进行不同的配置达到最佳效果，在使用不同的时连接对应不同的 inboud。

**Comment by liberal-boy** [comment]
感觉你的表达不太清楚，你的意思是要给每个kcp使用不同的底层传输参数？

**Comment by ToutyRater** [comment]
@liberal-boy 对，是这个意思

**Comment by v2ray** [comment]
功能已完成，由于一些内部的原因 json 配置暂时没法做，还要等一段时间。

**Comment by v2ray** [comment]
将在下一个版本开放这个功能。
