### ISSUE TITLE
v4.25.0使用Socks连接速度很慢

### ISSUE THREAD

**Issue by superjack6** [v2ray/v2ray-core#2592]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

**客户端: v4.25.0 服务端: v4.25.0**

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

**软路由OpenWRT使用V2ray（已升级到v4.25.0），开放一个socks端口自用**

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

**升级4.25.0以后，电脑端使用V2rayN和手机端使用V2rayNG(均已升级到v4.25.0) 通过软路由socks端口访问外网，速度非常慢，更换成老版本后，速度正常。在此期间，浏览器通过SwitchyOmega的socks代理使用速度一直正常。**

4)客户端配置

{
  "inbounds": [
    {
      "tag": "proxy",
      "port": 2626,
      "listen": "0.0.0.0",
      "protocol": "socks",
      "sniffing": {
        "enabled": false,
        "destOverride": [
          "http",
          "tls"
        ]
      },
     
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "xxx.xxxxx.xxx",
            "port": 443,
            "users": [
              {
                "id": "5xxx4939-e175-4xx3-b743-538xx0bcxx9",
                "alterId": 3,
                "email": "123@321",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "1.1.1.1"
    ]
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "port": null,
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "ip": null,
        "domain": null
      },
      {
        "type": "field",
        "port": null,
        "inboundTag": null,
        "outboundTag": "direct",
        "ip": [
          "geoip:private"
        ],
        "domain": null
      }
    ]
  }
}
]
}

5.日志显示：
2020/06/24 02:29:34 tcp:127.0.0.1:10193 rejected  v2ray.com/core/proxy/socks: insufficient header > EOF
2020/06/24 02:29:34 tcp:127.0.0.1:10195 rejected  v2ray.com/core/proxy/socks: insufficient header > EOF

6.补充：

以看youtube为例，打开youtube页面和点开视频的时候非常慢，一旦视频开始播放，就可以获得很好的速度。但是看别的视频或打开别的网页，速度依然慢。感觉连接建立以后，速度就正常了。

**Comment by wenjinlibug** [comment]
@superjack6 
```
"sniffing": {
"enabled": true, #需要打開協議嗅探才能區分http和tls
"destOverride": [
"http",
"tls"
]
```
socks的inbound需要打開udp: true才能代理udp流量
否則dns查詢會明文發到網上去，不用說當然被墻。
我猜樓主打開網頁慢的原因之一就是dns被墻
