### ISSUE TITLE
Add Windows ARM32 build

### ISSUE THREAD

**Issue by tigerinus** [v2ray/v2ray-core#2595]
Unlike https://github.com/v2ray/v2ray-core/issues/2516 requesting for a Windows ARM64 build, this is about requesting for a Windows ARM32 build.

I have an old Surface RT2 running ARM32 version of Windows. Can't do much with it other than watching videos and reading news. Having a ARM32 v2ray client would definitely help a lot.

Appreciated!

**Comment by rprx** [comment]
可以先手动交叉编译 https://github.com/v2ray/discussion/issues/756

```
$env:CGO_ENABLED=0
$env:GOARCH="arm"

go build -o v2ray.exe -trimpath -ldflags "-s -w" ./main
go build -o wv2ray.exe -trimpath -ldflags "-s -w -H windowsgui" ./main
go build -o v2ctl.exe -trimpath -ldflags "-s -w" -tags confonly ./infra/control/main
```

**Comment by kslr** [comment]
You can use arm5,6,7

**Comment by rprx** [comment]
@kslr 

https://docs.microsoft.com/zh-cn/windows/arm/

他指的是 windows arm build，或许考虑以后编译时加入？（可以类似 v2ray-linux-arm.zip 的文件结构）

**Comment by rprx** [comment]
@kslr 

https://docs.microsoft.com/zh-cn/windows/arm/

他指的是 windows arm build，或许考虑以后编译时加入？（可以类似 v2ray-linux-arm.zip 的文件结构）

**Comment by kslr** [comment]
GOOS=windows
GOARCH=arm
GOARM=7

这样么

**Comment by rprx** [comment]
@kslr 

对，GOARM 分别取值 5/6/7 编译，所有文件打包成 v2ray-windows-arm.zip，就像 linux arm 的一样

以后 arm64 的 windows 也越来越多了，等 golang 支持 windows arm64 时，多加个 v2ray-windows-arm64.zip

**Comment by kslr** [comment]
https://github.com/v2fly/V2FlyBleedingEdgeBinary/releases/tag/unstable-62813a9edee6d1e4480eb62d81202aa42e31f19f
