### ISSUE TITLE
Zero config before launching V2Ray process

### ISSUE THREAD

**Issue by v2ray** [v2ray/v2ray-core#26]
V2Ray should provide a UI for configuration, even for the first run. Ideally the UI is provided in the form of webpage for cross platform reasons (#24). V2Ray should be able to run with default config shipping with the binary, and users just use the UI to config it.

**Comment by laosb** [comment]
LGTM. If you have ever heard of Lantern, I guess V2Ray should has a simple way to config like Lantern.

[Lantern](https://getlantern.org)

(I'm not a member of Team Lantern.)

**Comment by v2ray** [comment]
Closing this for now. V2Ray client is now able to run without any modification on released packages (to connect to official server). UI tool will be provided separately (in platform dependent way).
