### ISSUE TITLE
v2ray增加MT7621的多线程调用

### ISSUE THREAD

**Issue by ttmi9002** [v2ray/v2ray-core#2603]
大大，我在使用小米路由器3G上也碰到了这个问题，MT7621处理器运行v2ray只有单线程调用，表现为使用Chrome浏览单个youtube视频最大码率是15mps，CPU占用25%；但如果浏览两个youtube视频最大码率分别分12mbps和11mpbs，CPU占用50%，总码率为23mps。证明v2ray对单个浏览只调用一个线程，无法完全发挥MT7261的处理性能。对比斐讯N1盒子，浏览单个youtube视频最大码率能到360-400mps,CPU占用能跑满。
所以希望v2ray添加MT7621多线程调用。

**Comment by 1265578519** [comment]
刚刚我看了另一个贴，才知道这CPU有多么烂，单核心性能上和台式电脑差距了16倍性能。。

**Comment by nobk** [comment]
那个是openssl的成绩，要真能让单核达到那个成绩，其实也够用了，64字节包的速度也有近9MB/s了 ，目前v2ray的实现还达不到那个成绩，只有2.5MB/s，能把三线程用起来估计可以到5MB/s，就能满足大部分4K视频流的需求了。
```
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-256 cbc       8271.81k     8993.15k     9169.56k     9223.82k     9212.60k     9237.09k
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-10.35  sec  3.12 MBytes  2.53 Mbits/sec                  sender
[  5]   0.00-10.35  sec  2.45 MBytes  1.98 Mbits/sec                  receiver

```

**Comment by nobk** [comment]
OpenSSL bindings for Go 替代 Go crypt原装加密库也许能提高性能到openssl benchmark的水平，近9MB/s的单核解密速度看4K视频足够，多线程加解密功能也许也能借助OpenSSL开启。
https://github.com/Jarijaas/openssl

**Comment by CalmLong** [comment]
一个树莓派价格也不贵，还可以有更好的性能，其他的程序也都可以跑在上面，原来的路由器还能继续工作。

**Comment by ttmi9002** [comment]
据说MT7621的无法多线程是因为MT7621没有硬件FPU，所以v2ray用的是FPU模拟器，这个FPU模拟器不支持多线程调用。不知道是不是这个原因

**Comment by ttmi9002** [comment]
> 那个是openssl的成绩，要真能让单核达到那个成绩，其实也够用了，64字节包的速度也有近9MB/s了 ，目前v2ray的实现还达不到那个成绩，只有2.5MB/s，能把三线程用起来估计可以到5MB/s，就能满足大部分4K视频流的需求了。
> 
> ```
> type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
> aes-256 cbc       8271.81k     8993.15k     9169.56k     9223.82k     9212.60k     9237.09k
> [ ID] Interval           Transfer     Bandwidth
> [  5]   0.00-10.35  sec  3.12 MBytes  2.53 Mbits/sec                  sender
> [  5]   0.00-10.35  sec  2.45 MBytes  1.98 Mbits/sec                  receiver
> ```

是的，MT7621经过优化后的性能不差的。MT7621有点特殊，youtube只能单线程调用速度会慢些，但Netflix可以多线程调用速度快
v2ray(v4.24.1) ws+TLS模式，TLS算法改用ECDHE-PSK-CHACHA20-POLY1305，这比AES-128-GCM速度提升20%。
Youtube的速度能到18mbps，youtube只能单线程跑，但这个速度能刚好放4K视频了。
Netflix可以多线程，速度到30mbps。这个速度看4K视频非常顺畅。

如果是K2p或NEWwifi3，使用breed超频到1200Mhz，速度还有提升，
单线程速度能到24mbps，多线程速度能到40mbps，性能已经相当可观了。
所以只要优化好，MT7621是完全能满足4K播放需求的

**Comment by felix-fly** [comment]
mt7621做tls加解密性能是不行，可也上个树莓派4b放旁边，主路由不变，轻松上百兆，预算也比软路由少很多，有兴趣可以试试我的这种方式 [https://github.com/felix-fly/openwrt-raspberry/blob/master/guide.md](https://github.com/felix-fly/openwrt-raspberry/blob/master/guide.md) @ttmi9002

**Comment by ntgeralt** [comment]
我只想说MT7621 OC 1.1Ghz shadowsocks四线程油管50000Kbps+
