### ISSUE TITLE
Windows Defender报病毒

### ISSUE THREAD

**Issue by weeshinwang** [v2ray/v2ray-core#2605]
v4.25.1 Windows X64版本

受影响程序：
v2rayN-Core\v2ctl.exe

检测到的威胁
Trojan:Win32/Spursint.F!cl

不知道是否是误报

**Comment by weeshinwang** [comment]
![附图](https://i.loli.net/2020/06/26/cFWDE9Ljz7G2f1R.jpg)

**Comment by guanhemeng** [comment]
About AV warnings
We are aware some anti-virus software detects V2Ray as malware, which it isn't, but we can't afford to pay the fee needed to make them not detect V2Ray as malware. Microsoft's AV detects V2Ray as "Trojan:Win32/Wacatac.C!ml" , "Program:Win32/Wacapew.C!ml" each time we release a new version, and I have to manually contact them each time to remove it from the malware database. If you have more information to report please leave them here. These AVs are known to generate false-positive results: "Microsoft", "McAfee", "Cylance", "Symantec", "F-Secure", "SecureAge APEX", "Cybereason", "Cynet", "MaxSecure", "F-Secure", "Avira", "AVAST", "AVG", "Rising"(瑞星).
from:https://github.com/v2ray/v2ray-core/releases/tag/v4.24.2

**Comment by weeshinwang** [comment]
@guanhemeng
Thanks 😄😄

**Comment by Niupa** [comment]
Yes, this issue take place in win10 AV detector and report as Trojan:Win32/Zpevdo.B while opening zip file "v2rayN-Core.zip"
<img width="340" alt="截圖 2021-01-15 下午5 53 48" src="https://user-images.githubusercontent.com/70770085/104710343-ee342500-575a-11eb-9acc-6c5d4dc3d5d7.png">
