### ISSUE TITLE
不知道怎么突然用不了了？是个例吗？

### ISSUE THREAD

**Issue by Jason4774** [v2ray/v2ray-core#261]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please answer the following questions before submitting your issue. Thank you.

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
1) What version of V2Ray are you using?
2.0
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
2) What your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
chrome
3) 你看到的不正常的现象是什么？
3) What did you see?
突然用不了了
4) 你期待看到的正确表现是怎样的？
4) What do you expected to see instead?
正常代理
5) 请附上你的配置文件。
5) Please attach your configuration file.
就是原配置文件
希望是个例，我用其他的代理服务器是正常的。
谢谢。

**Comment by qingfengshi** [comment]
你之前使用的是哪个版本？是不是没有更新服务端？

**Comment by Jason4774** [comment]
我一直使用的是2.0，没有修改过任何设置，需要修改什么吗？谢谢

**Comment by qingfengshi** [comment]
报错信息发一下吧

**Comment by Jason4774** [comment]
V2Ray v2.1.2 (One for all) 20160919
An unified platform for anti-censorship.
2016/09/21 01:32:30 [Warning]Point: started on port 1080
2016/09/21 01:32:40 [Warning]Freedom: Failed to open connection to tcp:7xnarc.com1.z0.glb.clouddn.com:80: All retry attempts failed.
2016/09/21 01:32:55 [Warning]VMess|Outbound: Failed to read response from udp:8.8.8.8:53: read tcp 10.253.52.54:3229->45.32.57.169:10086: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2016/09/21 01:33:13 [Warning]VMess|Outbound: Failed to read response from tcp:www.youtube.com:443: read tcp 10.253.52.54:3270->45.32.57.169:10086: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2016/09/21 01:33:25 [Warning]VMess|Outbound: Failed to read response from tcp:cr-input.mxpnl.net:443: read tcp 10.253.52.54:3280->45.32.57.169:10086: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2016/09/21 01:33:27 [Warning]VMess|Outbound: Failed to read response from tcp:www.youtube.com:443: read tcp 10.253.52.54:3289->45.32.57.169:10086: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
![image](https://cloud.githubusercontent.com/assets/19594338/18681655/995919f0-7f9b-11e6-806e-09609d167479.png)

**Comment by Jason4774** [comment]
我这次用的2.1.2最新版本，然后什么都没有改，浏览器也设置了1080socks5代理，以前是正常的，现在用不了。

**Comment by v2ray** [comment]
看上去像是远程主机挂了或是被墙了

**Comment by Jason4774** [comment]
谢谢回复，所以是我电脑的问题，或者我网络的问题还是v2ray的问题呢？我想说是不是v2ray里面的服务器挂了。毕竟我用其他的代理服务器是可以的。请问你的可以正常使用吗？该怎么解决呢？谢谢

**Comment by v2ray** [comment]
哦，原来你用的是官方服务器。大概是因为刚才 Vultr [受到攻击](https://twitter.com/Vultr/status/778146523007881216) 导致的。现在可以了。

**Comment by Jason4774** [comment]
谢谢，试了，果然可以，还想请问一下除了我使用的这个官方的还有其他的服务器吗？我一直用的你这里的这个呢。

**Comment by v2ray** [comment]
没有了，目前只有这一个

**Comment by Jason4774** [comment]
因为我看你说“原来你用的是官方服务器”，还以为有其他的呢

**Comment by Jason4774** [comment]
你好，请问一下，为了兼容32位电脑，我使用32位的windows版的v2ray速度会不会慢一点？如果不影响的话我想使用32位的，这样可以兼容32位电脑。谢谢
