### ISSUE TITLE
入口socks5监听ipv6时，UDP ASSOCIATE返回内容不正确

### ISSUE THREAD

**Issue by springzfx** [v2ray/v2ray-core#2610]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
```
客户端 4.25.0, 4.25.1， 不涉及服务端
```

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
```
本地inbound socks5的udp连接
```
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
```
当inbound socks5监听ipv6地址时，发送UDP ASSOCIATE请求， 返回内容不正确
steps to reproduce:
1. set v2ray socks listen on [::1]:1082
2. send an udp ASSOCIATE
3. replied with ASSOCIATED address 127.0.0.1:1082, 而这个地址不可用
```
![image](https://user-images.githubusercontent.com/8992037/85942766-f616ae00-b95d-11ea-9fad-09a3bab5f31f.png)

4) 你期待看到的正确表现是怎样的？
```
UDP ASSOCIATE请求时，返回的地址是可用的。
```
这个bug只涉及到inbound socks5， 所以此处省略以下要填的部分。

**Comment by kingwilliam** [comment]
https://www.v2fly.org/chapter_02/protocols/socks.html

Socks
InboundConfigurationObject

```
{
    "auth": "noauth",
    "accounts": [
        {
            "user": "my-username",
            "pass": "my-password"
        }
    ],
    "udp": true,
    "ip": "127.0.0.1", <- 试试填入你内网IP
    "userLevel": 0
}
```

或可否讲解如何send udp packet到v2 socks5

**Comment by springzfx** [comment]
> 或可否讲解如何send udp packet到v2 socks5

socks5协议标准：[rfc1928](https://tools.ietf.org/html/rfc1928)
写个socks5的client进行测试即可，可参考[gosocks5](https://github.com/springzfx/gosocks5), [socks5.go](https://github.com/springzfx/tproxy2socks-go/blob/master/socks5/socks5.go)
