### ISSUE TITLE
麻烦问一下查询全部用户流量的问题

### ISSUE THREAD

**Issue by bbhxwl** [v2ray/v2ray-core#2611]
我使用下面的命令/usr/bin/v2ray/v2ctl  api --server=127.0.0.1:10086 StatsService.QueryStats 'pattern: "" reset: false'

好像每次查询的结果都是
stat: <
  name: "inbound>>>A>>>traffic>>>uplink"
  value: 4066092446
>
stat: <
  name: "inbound>>>A>>>traffic>>>downlink"
  value: 27958396482
>
stat: <
  name: "inbound>>>api>>>traffic>>>uplink"
  value: 174
>
stat: <
  name: "inbound>>>api>>>traffic>>>downlink"
  value: 24
>

只有4个结果，我记得之前会显示某个邮箱，使用的流量数量。我应该怎么改变呢？我尝试在参数里面增加了个user  ，比如/usr/bin/v2ray/v2ctl  api --server=127.0.0.1:10086 StatsService.QueryStats 'pattern: "user" reset: false'

没有任何数据，不知道为什么

**Comment by bbhxwl** [comment]
![QQ图片20200702015329](https://user-images.githubusercontent.com/26525599/86276614-c1c61a80-bc07-11ea-853a-97028445ec15.png)
查询的流量是这样的。以前不是这样的，以前会显示某个邮箱的流量使用了多少

**Comment by HCLAC** [comment]
您好，那一版可以拿到用户的流量？
