### ISSUE TITLE
Can you export windows dll to the program call?

### ISSUE THREAD

**Issue by zdm2008** [v2ray/v2ray-core#2612]
Can you export windows dll to the program call?

Because V2ray is mistaken for a Trojan program by popular antivirus software, I wonder if you can export dll to the program to call, should be able to solve this problem.

**Comment by kslr** [comment]
This requires a windows developer

**Comment by yomnxkcs** [comment]
This approach will not work. No matter the app is compiled into an exe file or a dll file, antivirus software will still report it as a virus. The best solution would be finding out the code that caused the false positive. But this is very difficult. Submitting a false positive report is a relatively easy solution.

**Comment by Aaronwang81** [comment]
根本问题是没签名，没通过杀毒软件扫描。
基本上所有类VPN软件如果不签名，不送给杀软扫描都会有这种情况。

**Comment by yomnxkcs** [comment]
监于v2ray的特殊性，提前送杀毒软件检查不太可行。添加签名估计也没多大作用。如果杀毒软件对有签名的软件放松检查，那么真正的病毒制作者就可以利用这点，先发布个无害的带签名软件，等检查通过之后再添加病毒代码。

题外话，v2ray用到现在我的windows defender也没报过一次病毒，不知道为什么最近好几个issue说wd报毒。

**Comment by Aaronwang81** [comment]
> 监于v2ray的特殊性，提前送杀毒软件检查不太可行。添加签名估计也没多大作用。如果杀毒软件对有签名的软件放松检查，那么真正的病毒制作者就可以利用这点，先发布个无害的带签名软件，等检查通过之后再添加病毒代码。
> 
> 题外话，v2ray用到现在我的windows defender也没报过一次病毒，不知道为什么最近好几个issue说wd报毒。

签名与每个版本送审需要一起进行的，单独一个没效果。
其实最简单的办法就是自己添加到白名单，相信用v2ray的人应该能接受这个吧。墙都翻了，还不能加个白名单。。
defender不报毒我归结于defender查杀力默认不够强烈。是一款中规中矩的杀软，少量放过，但误报也少。其他杀软的主动防御，什么自学习引擎，或多或少都会增加误报率。还有就是。。政治正确。

**Comment by BurningC4** [comment]
更新之后哈希变了，白名单就会失效

**Comment by Aaronwang81** [comment]
> 更新之后哈希变了，白名单就会失效

把整个目录（文件夹）添加为例外或者排除就可以了。添加单个文件会有更新的问题。

**Comment by kslr** [comment]
目前在发布后手动向微软报告误杀可以解决问题，但这不是一个长久之计，有兴趣的可以帮助在发布后手动报告。

https://www.microsoft.com/en-us/wdsi/filesubmission
