### ISSUE TITLE
Server is updated to 4.25.1 but v2rayN-core client shows 4.23.4 connected

### ISSUE THREAD

**Issue by sioulisn** [v2ray/v2ray-core#2613]
Hi guys!

I think it is just a wrong message. Can you please confirm?
My server is updated at 4.25.1 but when I am connected to it, my v2rayN-core client shows 4.23.4 version at logs.
I am sure the server is updated because I have tried the KCP wechat-video and it is not getting banned as it was happening before the updates.
Do you have to suggest me any better client for windows? 

SERVER:
v2ray.service` - V2Ray Service
   Loaded: loaded (/lib/systemd/system/v2ray.service; enabled; vendor preset: en
   Active: active (running) since Tue 2020-06-30 10:49:46 CST; 2h 36min ago
     Docs: https://www.v2ray.com/
           https://www.v2fly.org/
 Main PID: 8395 (v2ray)
    Tasks: 8 (limit: 1078)
   Memory: 41.3M
   CGroup: /system.slice/v2ray.service
           └─8395 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json

Jun 30 10:49:46 localadmin systemd[1]: Started V2Ray Service.
Jun 30 10:49:46 localadmin v2ray[8395]: V2Ray 4.25.1 (V2Fly, a community-driven
Jun 30 10:49:46 localadmin v2ray[8395]: A unified platform for anti-censorship.
Jun 30 10:49:46 localadmin v2ray[8395]: 2020/06/30 10:49:46 [Info] v2ray.com/cor
Jun 30 10:49:46 localadmin v2ray[8395]: v2ctl> Read config:  `/etc/v2ray/config.j

V2RAYN-CORE CLIENT  v3.19
Vmess-****************
启动服务(30/6/2020 1:21:31 μμ)...
V2Ray 4.23.4 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.1 windows/386)
A unified platform for anti-censorship.
2020/06/30 13:21:31 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  **********\v2rayN-Core\config.json
2020/06/30 13:21:31 [Warning] v2ray.com/core: V2Ray 4.23.4 started

**Comment by yushum** [comment]
What V2RayN shows is the local V2Ray-Core version, all you need to do is update the local Core.

**Comment by sioulisn** [comment]
i have the latest v3.19 version of v2rayN maybe they don't have added the latest core version (windows v2rayN-core)?

**Comment by sioulisn** [comment]
oh ok!! i got it. I will update it

**Comment by sioulisn** [comment]
May I ask here about iphone-ios  client also?
I m using Shadowrocket, how can I know which v2ray-core it uses? I can see that Shadowrocket is more unstable than my windows client in general.
Is there any other ios client that it is updated more often and it is more stable?

**Comment by yushum** [comment]
Shadowrocket does not use V2Ray-core. In fact, all such apps on iOS neither used V2Ray-core.
Shadowrocket is the app with the most supported protocols and the easiest to use on iOS. 
If I had to recommend it, I would recommend QuantumultX. It doesn't support many protocols, but it is the fastest, and is also highly playable, similar to Surge (except for the price).
