### ISSUE TITLE
当 core 使用多配置文件时，inbound 指定的端口未监听

### ISSUE THREAD

**Issue by EpLiar** [v2ray/v2ray-core#2614]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

4.25.1

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

正常搭代理

3) 你看到的不正常的现象是什么？

在服务端使用 fhs-install-v2ray 脚本安装结束后，修改配置文件并启动，端口未监听

4) 你期待看到的正确表现是怎样的？

端口监听，正常工作

5) 请附上你的配置

由于 V2Ray 只需要一个 inbound 和 outbound 即可工作，且该 Bug 不需要服务端配合，因此只列出可以复现 bug 的配置

05_inbounds.json

```json
{
  "port": 8080,
  "protocol": "http",
  "settings": {}
}
```

06_outbounds.json

```json
{
  "protocol": "freedom",
  "tag": "direct",
  "settings": {}
}
```

其余 json 文件留空，即 `{}`

以上所对应的单文件配置为：

```json
{
  "log": {},
  "inbounds": [
    {
       "port": 8080,
       "protocol": "http",
       "settings": {}
    }
  ],
  "outbounds": [
    {
       "protocol": "freedom",
       "settings": {},
       "tag": "direct"
    }
  ],
  "routing": {},
  "transport": {},
  "dns": {},
  "reverse": {},
  "policy": {},
  "stats": {}
}
```

6)  复现步骤

由于 `-confdir` 选项会读取指定目录下所有的配置文件，因此为了不影响准确性，单文件放置在其他目录或在测试结束后创建一个

以上 bug 在 Ubuntu Live 以及 Windows 复现成功，现只贴出 Mac 的测试结果

```shell
$ v2ray -confdir .
```

运行之后新开一个 shell，使用 [tcping](https://github.com/cloverstd/tcping) 对端口进行 tcp ping，无回应

![image](https://user-images.githubusercontent.com/23559565/86191156-e626e600-bb78-11ea-88b0-8d5818d650ce.png)

退出并使用单配置文件启动，tcp ping 相应端口，可以收到回应

```shell
$ v2ray -config config.json
```

![image](https://user-images.githubusercontent.com/23559565/86191527-e07dd000-bb79-11ea-9cbf-a51cf9681fe9.png)

为了确保测试准确性，我模拟服务器的配置写进 05_inbounds.json，使用 `-confdir` 选项启动，bug 复现

```json
{
  "port": 12345,
  "protocol": "vmess",
  "settings": {
    "clients": [
      {
        "id": "d28e99bd-d6eb-45f5-87d3-678f04564f9d",
        "alterId": 4
      }
    ]
  },
  "tag": "tcp-in",
  "streamSettings": {
    "network": "tcp",
    "security": "none",
    "tcpSettings": {}
  }
}
```

![image](https://user-images.githubusercontent.com/23559565/86192309-d8269480-bb7b-11ea-97b6-20e1e9cb4886.png)

由于官方推荐使用的 fhs-install-v2ray 安装脚本默认为多配置文件，因此该 bug 需要尽快修复

欢迎大家提供测试结果以及勘误，谢谢～

**Comment by kslr** [comment]
@vcptr

**Comment by vcptr** [comment]
建议认真阅读多配置文件的使用文档： https://www.v2fly.org/chapter_02/multiple_config.html

inbounds.json的内容应该是
```json
{
  "inbounds": [
    {
       "port": 8080,
       "protocol": "http",
       "settings": {}
    }
  ]
}
```

而**不是**
```json
{
  "port": 8080,
  "protocol": "http",
  "settings": {}
}
```

**Comment by EpLiar** [comment]
> https://www.v2fly.org/chapter_02/multiple_config.html

fine

还以为文件名对应了 object 就不用写 "inbounds" 了
