### ISSUE TITLE
2.1.2版本很难访问被屏蔽的网站，如google

### ISSUE THREAD

**Issue by vieuxport** [v2ray/v2ray-core#262]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please answer the following questions before submitting your issue. Thank you.

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
1) What version of V2Ray are you using?

2.1.1 / 2.1.2

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
2) What your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

chrome，访问google和其它一些被国内屏蔽的网站

3) 你看到的不正常的现象是什么？
3) What did you see?

无法正常打开网站，说网站响应时间过长，在console中有如下一些提示

[Warning]VMess|Outbound: Failed to read response from tcp:github-cloud.s3.amazonaws.com:443: Packet is corrupted.

 [Warning]VMess|Outbound: Failed to read response from udp:8.8.8.8:53: read tcp 192.168.0.103:53094->45.32.57.169:10086: wsarecv: An established connection was aborted by the software in your host machine.

4) 你期待看到的正确表现是怎样的？
4) What do you expected to see instead?

能够快速访问被屏蔽的网站

5) 请附上你的配置文件。
5) Please attach your configuration file.

2.1.2 win64 包中的配置

**Comment by v2ray** [comment]
应该是当时官方服务器的问题，现在已修复
