### ISSUE TITLE
该项目被主流杀毒软件报病毒

### ISSUE THREAD

**Issue by zdm2008** [v2ray/v2ray-core#2622]
该项目编译的windows exe 32/64位程序都被主流杀毒软件报病毒，开发人员或高频使用的用户可以向这些杀毒厂商提交误报反馈。
请项目管理人员将该贴加入Wiki，并在首页README文件加入引导链接提示。

**360（重要，占中国90%的市场份额，提交需中国手机）:**
https://open.soft.360.cn/report.php

金山：
https://www.ijinshan.com/virus_report/

瑞星（需注册登录账户）：
https://data.rising.com.cn/

**Microsoft:（！！！非常重要！！！）**
https://www.microsoft.com/en-us/wdsi/filesubmission

Norton:
https://symsubmit.symantec.com/

AVG:
https://www.avg.com/en-us/false-positive-file-form

Avast:
https://www.avast.com/false-positive-file-form.php

McAfee:
https://www.mcafee.com/enterprise/en-us/threat-center/detection-dispute-form.html

卡巴斯基:
https://opentip.kaspersky.com/

F-Secure:
https://www.f-secure.com/en/business/support-and-downloads/submit-a-sample

SecureAge APEX:
https://www.secureaplus.com/zh-tw/features/antivirus/report-false-positive/

Avira:
https://www.avira.com/en/analysis/submit

**Comment by IlO0OlI** [comment]
Virus Total扫描当前最新Windows 4.25.1版本，发现只对32位程序报毒，其中两个国产杀软，分别是深信服和瑞星。64位程序没有杀软报毒。
被国产杀软报毒是好事，看不下去可用你自己的手机号实名提交。

**Comment by littleBanshee** [comment]
![image](https://user-images.githubusercontent.com/27776182/86806230-3fc46e80-c0ab-11ea-8587-71c492b3ff31.png)

**Comment by Smallthing** [comment]
报毒就报毒 咋地了

**Comment by jimmygiven** [comment]
该项目编译的windows exe 32/64位程序都被主流杀毒软件报病毒，开发人员或高频使用的用户可以向这些杀毒厂商提交误报反馈。
请项目管理人员将该贴加入Wiki，并在首页README文件加入引导链接提示。

What for？

**Comment by okudayukiko** [comment]
用V2Ray就不要用360

**Comment by Mistofs** [comment]
360流氓软件起家。
让它杀，杀到那些用电脑来控制社会不让你翻墙，油嘴滑舌在骗人又只会偷鸡摸狗地拿国际上已有的技术来生成是原创安全防护(病毒库，当年核心虚拟化，防火墙的几层防御什么的都是国外要么有论文要么做出来)的那些人电脑大爆炸！

**Comment by limaofu** [comment]
呵呵，实名反馈

**Comment by dna1982** [comment]
这个人是吃错药了么？

**Comment by NetHeritage** [comment]
楼上这位，请文明理性交流。

**Comment by dna1982** [comment]
> 楼上这位，请文明理性交流。

这位爷，在一个FQ项目里，单独开一个Issue，建议维护者，使用实名制的手机号，去向360（国安出钱私有化的公司），提交FQ软件的报毒反馈。
这还不是吃错药了？

**Comment by LaurenceSamael** [comment]
我严重怀疑这家伙是公安之类的部门派来钓鱼执法的！
如此脑残的说话都能从你口中说出，若你不是钓鱼执法，那你肯定是个脑子不健全思维有问题的人。
怀疑一个软件有毒，大可不用！这个软件的性质是干嘛的，自己没点逼数吗？跑来项目组让项目负责人实名认证？第二个cloud woody？
怎么现在越来越多脑残了？肯请管理员删帖吧！看见这种无脑言论真的让我戾气暴增！

**Comment by deep00007** [comment]
我能不能这样理解：FQ的人，用实名手机向伪安全流氓提交反馈？这不是无脑行为么？

**Comment by qazhw** [comment]
都什么智障，报毒你去解决不是应该的？？还让用户替你报毒买单？？？
