### ISSUE TITLE
负载均衡的扩展需求

### ISSUE THREAD

**Issue by ghost** [v2ray/v2ray-core#2628]
当outbound中vnext有多个服务端时，会采取轮询方式，希望可以加几个功能，见下文

1.选择策略，round - 轮询，random - 随机, fifo - 自上而下。

2.指定服务端连接的最大失败次数，当与一个服务端建立连接失败次数超过此设定值时，此服务端会被标记为死亡节点(Dead)，死亡节点不会被选择使用。

3.指定死亡服务端的超时时间，当一个服务端被标记为死亡服务端后，在此设定的时间间隔内不会被选择使用，超过此设定时间间隔后，会再次参与服务端选择。

**Comment by Leoyuwei** [comment]
希望可以给`routing` 里面的`rules`加一个 **outboundTagBackup** 的标签，用于指定出口访问。

当**outboundTag** 标签的服务器连接不上，就使用  **outboundTagBackup** 里面的

**Comment by ddasddd** [comment]
你说的这些功能有点像客户端的fallback、load-balance，感觉服务端没必要加这些功能

**Comment by AgainCrazyCode** [comment]
是的，希望像nginx的upstream一样，可以检测服务器的存活情况
