### ISSUE TITLE
vmess 协议可能存在的特征

### ISSUE THREAD

**Issue by sakeven** [v2ray/v2ray-core#263]
根据 ss 的原协议（加入 OTA 之前）特征，猜想vmess 协议可能也存在类似的特征。
vmess 协议头部使用16字节的认证信息，这个认证是否就是可能存在的特征弱点？
按以下步骤验证：
1. 发送1 个字节数据给 v2ray 服务器，由于数据不完整，服务器等待剩余数据，于是连接超时
2. 发送2 个字节数据给 v2ray 服务器，由于数据不完整，服务器等待剩余数据，于是连接超时
3. 直到发送15 个字节数据给 v2ray 服务器，连接仍然会超时。
4. 当发送16个字节的数据时，由于无法通过认证，连接立刻被断开。

于是，我们可以发送16次连接，只有当发送16个字节时，连接才会被离开断开，其余15次都超时。（实际上16个字节及以上的数据，都会马上断开连接）
结果图如下：
<img width="540" alt="2016-09-21 23 08 37" src="https://cloud.githubusercontent.com/assets/4099405/18717174/b62116da-8051-11e6-86c2-0cae436649ff.png">

[验证代码](https://gist.github.com/sakeven/47ec2a6d9a1359b0a1978c8a9aae1b06)
v2ray 版本：v2ray-v2.1.2-macos
配置：
```
{
  "log" : {
    "access": "access.log",
    "error": "error.log",  
    "loglevel": "warning"                 
  },
  "inbound": {
    "port": 37192, 
    "protocol": "vmess",  
    "settings": {
      "clients": [
        {
          "id": "3b129dec-72a3-4d28-aeee-028a0fe86e22",  
          "level": 1 
        }
      ]
    }
  },
  "outbound": {
    "protocol": "freedom",  
    "settings": {}
  },
  "inboundDetour": [
    {
      "protocol": "vmess",  
      "port": "30001-30010", 
      "settings": {
        "clients": [ 
          {
            "id": "3b129dec-72a3-4d28-aeee-028a0fe86e22",
            "level": 1
          }
        ]
      }
    }
  ],
  "outboundDetour": [
    {
      "protocol": "blackhole",  
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",  
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}
```

**Comment by v2ray** [comment]
最终效果就是读取了 16 字节之后中断连接，几乎对于任意 16 字节的内容都会中断连接。

1. 发送的内容和中断连接的规律不存在任何联系；
2. 任何一个协议的服务器（包括 HTTP 服务器），都有可能实现成先读取 16 字节缓冲区，再做进一步的判断，并且当内容不合法的时候中断连接；

所以你描述的现象并不能做为服务器是 VMess 的充分条件。

**Comment by sakeven** [comment]
嗯

**Comment by 73883999** [comment]
不能作为充分条件，可党抓人都不需要充分条件，何况只是断个网

**Comment by shoaly** [comment]
> 不能作为充分条件，可党抓人都不需要充分条件，何况只是断个网

这些混淆都是防止被探测到, 当锁定目标, 开抓, 并不会在意这些细节, 境内境外都一样的结果: 直接抓就完事了
