### ISSUE TITLE
希望shadowsocks支持rc4-md5加密

### ISSUE THREAD

**Issue by t66y100** [v2ray/v2ray-core#2630]
我在主路由器linksys ea6200运行ss-redir，把gfwlist流量转发到局域网内运行着v2ray的x86 debian。
最新版本4.25.1 x86 v2ray，没有rc4-md5加密。

希望能考虑到局域网用户，可以继续支持rc4-md5加密，谢谢。

**Comment by t66y100** [comment]
好吧

**Comment by forever8938** [comment]
试试这个，透明代理转socks。
https://github.com/zfl9/ipt2socks

**Comment by kslr** [comment]
现在 Shadowsocks 可以选择 none

**Comment by t66y100** [comment]
> 试试这个，透明代理转socks。
> https://github.com/zfl9/ipt2socks

感谢分享，已经用上了，之前是不会编译。

**Comment by t66y100** [comment]
> 现在 Shadowsocks 可以选择 none

好的，又多一个选择。

**Comment by forever8938** [comment]
> 现在 Shadowsocks 可以选择 none

说的v2ray吧，ss-libev应该不支持。
ss的加密设为none，服务端不能启动。https://github.com/v2ray/v2ray-core/issues/1135
```
V2Ray 4.26.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.4 linux/386)
A unified platform for anti-censorship.
2020/07/17 11:28:07 Using default config:  /root/v2/config.json
main: failed to read config files: [/root/v2/config.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl:
v2ctl> Read config:  /root/v2/config.json
v2ray.com/core/infra/conf: unknown cipher method: none > exit status 255
```


官网也没说支持none
https://www.v2ray.com/chapter_02/protocols/shadowsocks.html

**Comment by kslr** [comment]
> > 现在 Shadowsocks 可以选择 none
> 
> 说的v2ray吧，ss-libev应该不支持。
> ss的加密设为none，服务端不能启动。#1135
> 
> ```
> V2Ray 4.26.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.4 linux/386)
> A unified platform for anti-censorship.
> 2020/07/17 11:28:07 Using default config:  /root/v2/config.json
> main: failed to read config files: [/root/v2/config.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl:
> v2ctl> Read config:  /root/v2/config.json
> v2ray.com/core/infra/conf: unknown cipher method: none > exit status 255
> ```
> 
> 官网也没说支持none
> https://www.v2ray.com/chapter_02/protocols/shadowsocks.html

https://github.com/v2fly/v2ray-core/commit/2e20d34f847a255792df51c88191fc96d5c4d81d

**Comment by wangshengxin1998** [comment]
试试XTLS的[XRay核心](https://github.com/XTLS/Xray-core),它支持SS的旧式加密,是v2ray的分支

**Comment by mazhihua05** [comment]
萌新给各位大佬请安了   有个问题想请教一下大家 望不吝赐教  我的小飞机加密方式一共就五个  分享的免费节点的加密方式好多我的小飞机都没有 请问该怎么解决
