### ISSUE TITLE
chrome下播放视频出现异常断流

### ISSUE THREAD

**Issue by Greeed-islanl** [v2ray/v2ray-core#2638]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
service 4.26.0
openwrt passwall 3.9-13 V2ARY 4.26.0 and openwrt SSR PLUS+ V2Ray 4.26.0
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
在openwrt GFW规则全局代理内网设备环境下 使用 Chrome 观看 YouTube 视频
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
chrome下播放视频出现异常断流

4) 你期待看到的正确表现是怎样的？

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:
{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "info"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 56151,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    },
    {
      "port": ***,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "***",
            "alterId": 32,
            "email": "admin@qq.com"
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "none",
        "tlsSettings": {},
        "tcpSettings": {},
        "kcpSettings": {},
        "httpSettings": {},
        "wsSettings": {
          "path": "***",
          "headers": {
            "Host": ""
          }
        },
        "quicSettings": {}
      },
      "domain": "new.keepstar.net"
    },
    {
      "port": ***,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "***",
            "alterId": 16,
            "email": "***"
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "none",
        "tlsSettings": {},
        "tcpSettings": {},
        "kcpSettings": {},
        "httpSettings": {},
        "wsSettings": {
          "path": "/***",
          "headers": {
            "Host": ""
          }
        },
        "quicSettings": {}
      },
      "domain": "***"
    },
    {
      "port": ***,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "***",
            "alterId": 16,
            "email": "***"
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "none",
        "tlsSettings": {},
        "tcpSettings": {},
        "kcpSettings": {},
        "httpSettings": {},
        "wsSettings": {
          "path": "/***",
          "headers": {
            "Host": ""
          }
        },
        "quicSettings": {}
      },
      "domain": "***"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "ip": [
          "0.0.0.0/8",
          "10.0.0.0/8",
          "100.64.0.0/10",
          "169.254.0.0/16",
          "172.16.0.0/12",
          "192.0.0.0/24",
          "192.0.2.0/24",
          "192.168.0.0/16",
          "198.18.0.0/15",
          "198.51.100.0/24",
          "203.0.113.0/24",
          "::1/128",
          "fc00::/7",
          "fe80::/10"
        ],
        "outboundTag": "blocked"
      },
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      }
    ]
  },
  "stats": {},
  "api": {
    "services": [
      "StatsService"
    ],
    "tag": "api"
  },
  "policy": {
    "levels": {
      "0": {
        "statsUserDownlink": true,
        "statsUserUplink": true
      }
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true
    }
  }
}

客户端配置:
{
 "log": {
  "access": "",
  "error": "",
  "loglevel": "info"
 },
 "inbounds": [
  {
   "port": 1080,
   "listen": "0.0.0.0",
   "protocol": "socks",
   "settings": {
    "auth": "noauth",
    "udp": true,
    "ip": "127.0.0.1",
    "clients": null
   },
   "streamSettings": null
  }
 ],
 "outbounds": [
  {
   "protocol": "vmess",
   "settings": {
    "vnext": [
     {
      "address": "***",
      "port": ***,
      "users": [
       {
        "id": "***",
        "alterId": 32,
        "security": "aes-128-gcm"
       }
      ]
     }
    ]
   },
   "streamSettings": {
    "network": "ws",
    "security": "none",
    "tlsSettings": {},
    "tcpSettings": {},
    "kcpSettings": {},
    "httpSettings": {},
    "wsSettings": {
     "path": "***",
     "headers": {
      "Host": ""
     }
    },
    "quicSettings": {}
   },
   "mux": {
    "enabled": true
   }
  },
  {
   "protocol": "freedom",
   "settings": {
    "response": null
   },
   "tag": "direct"
  }
 ],
 "dns": {
  "servers": [
   "8.8.8.8",
   "8.8.4.4",
   "localhost"
  ]
 },
 "routing": {
  "domainStrategy": "IPIfNonMatch",
  "rules": [
   {
    "type": "field",
    "ip": [
     "geoip:private"
    ],
    "outboundTag": "direct"
   },
   {
    "type": "field",
    "domain": [
     "geosite:cn"
    ],
    "outboundTag": "direct"
   },
   {
    "type": "field",
    "domain": [
     "geoip:cn"
    ],
    "outboundTag": "direct"
   }
  ]
 }
}

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
2020/07/18 12:47:39 [Info] [22601485] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: failed to transfer request > websocket: close 1006 (abnormal closure): unexpected EOF
2020/07/18 12:47:39 [Info] [22601485] v2ray.com/core/common/mux: unexpected EOF > v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2020/07/18 12:47:39 [Info] [2672212953] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: failed to transfer request > websocket: close 1006 (abnormal closure): unexpected EOF
2020/07/18 12:47:39 [Info] [22601485] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2020/07/18 12:47:39 [Info] [22601485] v2ray.com/core/common/mux: session 1 ends. > io: read/write on closed pipe
2020/07/18 12:47:39 [Info] [2672212953] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2020/07/18 12:47:39 [Info] [2672212953] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2020/07/18 12:47:39 [Info] [2672212953] v2ray.com/core/common/mux: unexpected EOF > v2ray.com/core/common/mux: failed to read metadata > io: read/write on closed pipe
2020/07/18 12:47:39 [Info] [2672212953] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2020/07/18 12:47:39 [Info] [2672212953] v2ray.com/core/common/mux: session 4 ends. > io: read/write on closed pipe
2020/07/18 12:47:39 [Info] [2672212953] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2020/07/18 12:47:39 [Info] [2672212953] v2ray.com/core/common/mux: session 5 ends. > io: read/write on closed pipe
2020/07/18 12:47:39 [Info] [2672212953] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2020/07/18 12:47:39 [Info] [2672212953] v2ray.com/core/common/mux: session 6 ends. > io: read/write on closed pipe
2020/07/18 12:47:39 [Info] [2672212953] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2020/07/18 12:47:39 [Info] [2672212953] v2ray.com/core/common/mux: session 7 ends. > io: read/write on closed pipe
2020/07/18 12:47:39 [Info] [2672212953] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2020/07/18 12:47:39 [Info] [2672212953] v2ray.com/core/common/mux: session 8 ends. > io: read/write on closed pipe
2020/07/18 12:47:39 [Info] [2672212953] v2ray.com/core/common/mux: session 1 ends. > io: read/write on closed pipe
2020/07/18 12:47:39 [Info] [2672212953] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2020/07/18 12:47:39 [Info] [2672212953] v2ray.com/core/common/mux: session 2 ends. > io: read/write on closed pipe
2020/07/18 12:47:39 [Info] [2672212953] v2ray.com/core/common/mux: session 3 ends. > io: read/write on closed pipe

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

2020/07/18 12:46:07 tcp:116.233.215.37:44388 accepted tcp:8.8.8.8:53 
2020/07/18 12:46:10 tcp:116.233.215.37:44460 accepted tcp:8.8.8.8:53 
2020/07/18 12:46:34 tcp:116.233.215.37:44388 accepted tcp:8.8.8.8:53 
2020/07/18 12:46:35 tcp:116.233.215.37:44460 accepted tcp:8.8.8.8:53 
2020/07/18 12:46:42 tcp:116.233.215.37:44388 accepted tcp:8.8.8.8:53 
2020/07/18 12:46:45 tcp:116.233.215.37:44468 accepted tcp:clients4.google.com:443 
2020/07/18 12:46:46 tcp:116.233.215.37:44468 accepted tcp:translate.googleapis.com:443 
2020/07/18 12:46:50 tcp:116.233.215.37:44468 accepted tcp:dns.google:443 
2020/07/18 12:46:51 tcp:116.233.215.37:44468 accepted tcp:www.youtube.com:443 
2020/07/18 12:46:53 tcp:116.233.215.37:44468 accepted tcp:fonts.googleapis.com:443 
2020/07/18 12:46:59 tcp:116.233.215.37:44468 accepted tcp:content-autofill.googleapis.com:443 
2020/07/18 12:47:08 tcp:116.233.215.37:44468 accepted tcp:clients1.google.com:443 
2020/07/18 12:47:23 tcp:116.233.215.37:44468 accepted tcp:mtalk.google.com:443 
2020/07/18 12:47:36 tcp:116.233.215.37:44480 accepted tcp:s.ytimg.com:443 
2020/07/18 12:47:41 tcp:116.233.215.37:44482 accepted udp:8.8.4.4:53 
2020/07/18 12:47:44 tcp:116.233.215.37:44484 accepted tcp:www.youtube.com:443 

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by Greeed-islanl** [comment]
尝试切换TCP/MKCP/H2或者切换TLS OFF/ON 均出现以上问题
关MUX也会断流
修改MTU 无效
其他客户段没有任何问题

**Comment by DolorHunter** [comment]
本地网络问题或者是服务器线路的问题. 后者可以用在 https://ping.pe/ 测试一下.

**Comment by mbcc2006** [comment]
"udp": true, 改成false.这个问题我知道这是google的quic链接大量占用udp链接造成的.大约一个连接能产生500个udp链接,你的服务器瞬间饱和.我的选择是去chrome://flags/#enable-quic选择disabled.
如果没有改善,那再看其他配置

**Comment by Greeed-islanl** [comment]
好的我知道了，我换了服务器情况好很多，之前好像是服务器上行带# 宽不够我udp流量....
