### ISSUE TITLE
V2Ray panic crash with UDP usage after several hours

### ISSUE THREAD

**Issue by johnwigley** [v2ray/v2ray-core#2649]
Tested on Linux X64 on several different systems.

Client configured to use dokodemo-door inbound and VMess outbound to server, with TProxy IPtables redirect to Dokodemo-door.

When UDP is enabled and in use, for example downloading torrent, typically after several hours V2Ray server will crash with error message similar to log except.

Although the crash appears to relate to a TCP connection, this only seems to happen after UDP is being used. If only TCP redirects then it does not seem to crash.

Possibly resource leak, like open files, or mem leak?

On both client and server: Ulimit -n 1048576

Can supply any further details, or configs as required?

Server crash log:

2020/07/20 21:18:29 [Info] [3384710955] v2ray.com/core/proxy/vmess/inbound: received request for udp:171.101.162.62:10982
2020/07/20 21:18:29 [Info] [526507806] v2ray.com/core/proxy/vmess/inbound: received request for udp:104.6.163.198:51413
2020/07/20 21:18:29 [Info] [526507806] v2ray.com/core/app/dispatcher: default route for udp:104.6.163.198:51413
2020/07/20 21:18:29 [Info] [526507806] v2ray.com/core/proxy/freedom: opening connection to udp:104.6.163.198:51413
2020/07/20 21:18:29 [Info] [3384710955] v2ray.com/core/app/dispatcher: default route for udp:171.101.162.62:10982
2020/07/20 21:18:29 [Info] [3384710955] v2ray.com/core/proxy/freedom: opening connection to udp:171.101.162.62:10982
2020/07/20 21:18:29 82.17.113.105:41872 accepted udp:104.6.163.198:51413 [direct]
2020/07/20 21:18:29 82.17.113.105:41852 accepted udp:171.101.162.62:10982 [direct]
2020/07/20 21:18:29 [Info] [3717240870] v2ray.com/core/proxy/vmess/inbound: received request for udp:161.0.155.181:53682
2020/07/20 21:18:29 [Info] [3717240870] v2ray.com/core/app/dispatcher: default route for udp:161.0.155.181:53682
2020/07/20 21:18:29 82.17.113.105:42122 accepted udp:161.0.155.181:53682 [direct]
2020/07/20 21:18:29 [Info] [3717240870] v2ray.com/core/proxy/freedom: opening connection to udp:161.0.155.181:53682
2020/07/20 21:18:29 [Info] [3785203613] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: failed to open connection to tcp:178.26.125.219:55644 > v2ray.com/core/common/retry: [dial tcp 178.26.125.219:55644: connect: connection timed out dial tcp 178.26.125.219:55644: connect: no route to host dial tcp 178.26.125.219:55644: connect: connection timed out] > v2ray.com/core/common/retry: all retry attempts failed
2020/07/20 21:18:29 [Info] [3785203613] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > io: read/write on closed pipe
2020/07/20 21:18:29 [Info] [1313625749] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:184.160.177.222:1
panic: extending out of bound

goroutine 6605 [running]:
v2ray.com/core/common/buf.(*Buffer).Extend(...)
        v2ray.com/core/common/buf/buffer.go:62
v2ray.com/core/common/crypto.(*AuthenticationWriter).seal(0xc0187ac050, 0xc008c01800, 0x800, 0x800, 0x0, 0x1, 0x1)
        v2ray.com/core/common/crypto/auth.go:258 +0x56c
v2ray.com/core/common/crypto.(*AuthenticationWriter).writePacket(0xc0187ac050, 0xc01b1eca90, 0x1, 0x1, 0x0, 0x0)
        v2ray.com/core/common/crypto/auth.go:316 +0x166
v2ray.com/core/common/crypto.(*AuthenticationWriter).WriteMultiBuffer(0xc0187ac050, 0xc01b1eca90, 0x1, 0x1, 0x0, 0x0)
        v2ray.com/core/common/crypto/auth.go:343 +0xc5
v2ray.com/core/proxy/vmess/inbound.transferResponse(0xefdc60, 0xc0183ed830, 0xc0183ddc70, 0xc0183ed7a0, 0xc01c4d0740, 0xefe8a0, 0xc01b169688, 0xc0183ed8f0, 0xa93953, 0xefe8a0)
        v2ray.com/core/proxy/vmess/inbound/inbound.go:192 +0xe4
v2ray.com/core/proxy/vmess/inbound.(*Handler).Process.func2(0x0, 0x0)
        v2ray.com/core/proxy/vmess/inbound/inbound.go:304 +0x31d
v2ray.com/core/common/task.Run.func1(0xc01b169698, 0xc018786c00, 0xc0183bac00)
        v2ray.com/core/common/task/task.go:28 +0x2b
created by v2ray.com/core/common/task.Run
        v2ray.com/core/common/task/task.go:27 +0xd7

**Comment by rprx** [comment]
后续进展在 #2659
