### ISSUE TITLE
配置文件中的服务端域名 如果同时存在ipv4和ipv6地址 则在仅ipv4网络时无法正常连接

### ISSUE THREAD

**Issue by devinstever** [v2ray/v2ray-core#2656]
使用场景：
正常代理上网

一句话描述问题：
配置文件中填写的服务端域名 如果同时存在ipv4和ipv6地址 则在仅ipv4网络时无法正常连接

问题详情：
我有一个域名是 xx.com，它同时拥有ipv4和ipv6地址，当我把它填入到配置文件里并尝试连接时，它总是优先使用ipv6地址。
在同时具备ipv4和ipv6地址的网络中，这并没有什么问题，但是如果一来到仅ipv4网络中，它就无法正常连接使用了，因为它总是尝试连接ipv6地址，即使是网络不可达也会继续尝试连接ipv6地址，不会使用ipv4地址进行连接。（测试时已经确保两个地址在中国大陆没有被封锁或者网络不可达）

预期行为：
如果能自适应就好了（也就是在ipv6的网络中优先使用ipv6地址，但是在仅ipv4网络中可以直接忽略ipv6地址）

为什么有必要解决该问题：
因为越来越多的机场主和个人都用上了IPV6环境。并支持双地址连接服务器。所以该问题会严重困扰一部分普通用户。

相关日志：
07-31 17:24:50.687 I/GoLog   (14273): loading v2ray config
07-31 17:24:50.688 I/GoLog   (14273): Preparing Domain: [my domain]:443
07-31 17:24:51.087 I/GoLog   (14273): new v2ray core
07-31 17:24:51.089 I/GoLog   (14273): start v2ray core
07-31 17:24:51.137 D/com.v2ray.ang(14273): [/data/app/com.v2ray.ang-87iFhAzgSmvNYvsemfeiAw==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:20001, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice, --netif-ip6addr, da26:2626::2]
07-31 17:24:51.141 D/com.v2ray.ang(14273): Process[pid=14308, hasExited=false]
07-31 17:24:51.141 D/com.v2ray.ang(14273): /data/user/0/com.v2ray.ang/files/sock_path
07-31 17:24:51.162 I/tun2socks(14308): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
07-31 17:24:51.218 D/com.v2ray.ang(14273): sendFd tries: 0
07-31 17:24:51.220 I/tun2socks(14308): NOTICE(tun2socks): entering event loop
07-31 17:24:51.468 I/GoLog   (14273): Dial pending prepare  ... [my domain]:443
07-31 17:24:51.468 I/GoLog   (14273): Dial pending prepare  ... [my domain]:443
07-31 17:24:51.710 I/GoLog   (14273): Prepare Result:
07-31 17:24:51.710 I/GoLog   (14273):  Domain: [my domain]
07-31 17:24:51.710 I/GoLog   (14273):  Port: 443
07-31 17:24:51.710 I/GoLog   (14273):  IPs: [2606:4700:3031::6818:74a8 104.26.11.110]
07-31 17:24:51.713 I/GoLog   (14273): fdConn unix.Connect err, Close Fd: 55 Err: network is unreachable
07-31 17:24:51.713 I/GoLog   (14273): switched to next IP: 104.26.11.110
07-31 17:24:51.714 I/GoLog   (14273): fdConn unix.Connect err, Close Fd: 42 Err: network is unreachable
07-31 17:24:51.714 I/GoLog   (14273): switch too quickly
07-31 17:24:52.007 I/GoLog   (14273): Using Prepared: 2606:4700:3031::6818:74a8
07-31 17:24:54.714 I/GoLog   (14273): fdConn unix.Connect err, Close Fd: 42 Err: network is unreachable

**Comment by darhwa** [comment]
注意看你的日誌，嘗試ipv6地址[2606:4700:3031::6818:74a8 104.26.11.110]連不通後，立馬重新嘗試104.26.11.110，仍然連不通。所以，問題恐怕不在v2ray這。估計是某些運營商連cloudflare地址本身有問題。

建議在配置裏面把服務器地址改成這個ipv4地址，再試試看能不能連上。
