### ISSUE TITLE
Warning：failed to process outbound traffic

### ISSUE THREAD

**Issue by twzchi** [v2ray/v2ray-core#2663]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
使用了VLESS最新的VLESS PREVIEW 1.2版本
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
使用V2rayNG (V2ray_GUI :3.19,V2ray_Core:4.26.0)
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
使用VLESS配置的时候收到的警告讯息
No.1：
[Warning] [1382970553] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vless/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp IP:443: operation was canceled dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
No.2:
[Warning] [1177012021] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vless/outbound: connection ends > v2ray.com/core/proxy/vless/outbound: failed to decode response header > v2ray.com/core/proxy/vless/encoding: failed to read response version > EOF
4) 你期待看到的正确表现是怎样的？

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:
{
  "inbounds": [
    {
      "port":443,
      "protocol":"vless",
      "settings": {
        "decryption":"none",
        "clients": [
          {
            "id": "UUID",
            "level": 0
          }
        ]
      },
     "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
          "certificates": [
            {
              "certificateFile": "/etc/v2ray/v2ray.crt",
              "keyFile": "/etc/v2ray/v2ray.key"
            }
          ]
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}
```javascript
    // 在这里附上服务器端配置文件
```

客户端配置:
{
"inbounds": [
    {
      "port": 10808,
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
      "settings": {
        "auth": "noauth"
      }
    }
  ],
    "outbounds": [
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "www.FreeNet.com",
                        "port": 443,
                        "users": [
                            {
                                "encryption": "none",
                                "id": "UUID",
                                "level": 0
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls"
            }
        }
    ]
}

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by twzchi** [comment]
如果使用V2ray的VMESS配置不会出现这个警告讯息

**Comment by rprx** [comment]
服务端 inbound 有日志吗

**Comment by rprx** [comment]
目前看起来是你的网络问题，可以使用的 VMess 是否在同一台机器上？请及时提供更多信息，以便进一步确定问题所在。

**Comment by goatlove** [comment]
相似的问题和日志，我刚刚也遇到了。一直用的没有问题，早上手贱，在服务器端的配置文件streamsetting里，添加了"security": "tls", 就无法连接了。刚才把这段删了，就不报错，可以连上了websocket。把你服务器端配置里这段删掉试试，好像只能在客户端配置里添加这一段，不能在服务器端配置文件。

**Comment by rprx** [comment]
@goatlove 

如果服务端不是用 v2ray 处理 TLS，当然不能加上这一项。。。但他是在服务端用 v2ray 处理 TLS，情况有所不同。

**Comment by twzchi** [comment]
> 服务端 inbound 有日志吗
服务端就只有这个日志
2020/08/05 16:49:55 [Warning] v2ray.com/core: V2Ray 4.26.0 started

**Comment by goatlove** [comment]
哦哦。 我这里是Nginx出来的tls。

**Comment by twzchi** [comment]
> 目前看起来是你的网络问题，可以使用的 VMess 是否在同一台机器上？请及时提供更多信息，以便进一步确定问题所在。

我试试  VLESS PREVIEW 1.3 版本

**Comment by twzchi** [comment]
> 哦哦。 我这里是Nginx处理的tls。

我直接是TCP +TLS

**Comment by twzchi** [comment]
估计是我vps 的问题 ，有时候ping 的时候会丢包~ping 4次 会丢包1次

**Comment by rprx** [comment]
@twzchi 

看起来请求从未到达过服务端，可以确定是网络问题。或许你可以把本地也当服务端来试一下（

**Comment by twzchi** [comment]
测试了最新的 VLESS PREVIEW 1.3 版本 差不多1个小时 ，没有报Warning

**Comment by rprx** [comment]
@twzchi 

我可以说这和版本无关。。。

**Comment by twzchi** [comment]
> @twzchi
> 
> 我可以说这和版本无关。。。

请问下 安卓客户端什么时候可以发布下吗？或者出个教程 怎么打包安卓客户端   ,之前试了，但是不支持安卓10

**Comment by rprx** [comment]
@twzchi 

明天 v2ray-core 会发布 v4.27.0，等客户端跟进就行了

**Comment by twzchi** [comment]
好的

**Comment by Kurt-AFei** [comment]
问题怎么解决的？我有几乎一样的问题

**Comment by zhnet** [comment]
你们都是怎么解决的？

**Comment by qaz1234560** [comment]
使用V2RayN6.21  警告信息2023/04/12 19:03:31 [Warning] [854656841] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [dial tcp 198.23.137.17:65501: operation was canceled] > common/retry: all retry attempts failed
