### ISSUE TITLE
VLESS(4.26.0) 报Warnning 

### ISSUE THREAD

**Issue by twzchi** [v2ray/v2ray-core#2665]
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2ray/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
VLESS PREVIEW 1.3(采用的是TCP+TLS 模式)

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
   V2rayN 版本3.19

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
   服务器Warnning 
4) 你期待看到的正确表现
是怎样的？

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:
```json
{
  "inbounds": [
    {
      "port":443,
      "protocol":"vless",
      "settings": {
        "decryption":"none",
        "clients": [
          {
            "id": "UUID",
            "level": 0
          }
        ]
      },
     "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
          "certificates": [
            {
              "certificateFile": "/etc/v2ray/v2ray.crt",
              "keyFile": "/etc/v2ray/v2ray.key"
            }
          ]
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}
```

客户端配置:
```json
{
"inbounds": [
    {
      "port": 10808,
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
      "settings": {
        "auth": "noauth"
      }
    }
  ],
    "outbounds": [
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "www.FreeNet.com",
                        "port": 443,
                        "users": [
                            {
                                "encryption": "none",
                                "id": "UUID",
                                "level": 0
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls"
            }
        }
    ]
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:
2020/08/05 17:00:20 [Warning] [1473489512] v2ray.com/core/app/proxyman/inbound:                                                                                                              connection ends > v2ray.com/core/proxy/vless/inbound: invalid request from                                                                                                              IP:29950 > v2ray.com/core/proxy/vless/encoding: failed to read request ver                                                                                                             sion > tls: unsupported SSLv2 handshake received

2020/08/05 17:00:20 [Warning] [2531702145] v2ray.com/core/app/proxyman/inbound:                                                                                                              connection ends > v2ray.com/core/proxy/vless/inbound: invalid request from                                                                                                              IP:28128 > v2ray.com/core/proxy/vless/encoding: failed to read request ver                                                                                                             sion > tls: unsupported SSLv2 handshake received

2020/08/05 17:00:20 [Warning] [1137558339] v2ray.com/core/app/proxyman/inbound:                                                                                                              connection ends > v2ray.com/core/proxy/vless/inbound: invalid request from                                                                                                              IP:28150 > v2ray.com/core/proxy/vless/encoding: failed to read request ver                                                                                                             sion > tls: unsupported SSLv2 handshake received

2020/08/05 17:03:25 [Warning] v2ray.com/core: V2Ray 4.26.0 started
2020/08/05 17:09:14 [Warning] [999680593] v2ray.com/core/app/proxyman/inbound: c                                                                                                             onnection ends > v2ray.com/core/proxy/vless/inbound: invalid request from                                                                                                              IP:52028 > v2ray.com/core/proxy/vless/encoding: invalid request version

2020/08/05 17:09:14 [Warning] [6575565] v2ray.com/core/app/proxyman/inbound: con                                                                                                             nection ends > v2ray.com/core/proxy/vless/inbound: invalid request from                                                                                                              IP:52074 > v2ray.com/core/proxy/vless/encoding: failed to read request versi                                                                                                             on > tls: first record does not look like a TLS handshake

2020/08/05 17:15:09 [Warning] v2ray.com/core: V2Ray 4.26.0 started
2020/08/05 17:18:47 [Warning] v2ray.com/core: V2Ray 4.26.0 started
2020/08/05 17:35:37 [Warning] [3838745531] v2ray.com/core/app/proxyman/inbound:                                                                                                              connection ends > v2ray.com/core/proxy/vless/inbound: invalid request from                                                                                                              IP:36316 > v2ray.com/core/proxy/vless/encoding: invalid request version

2020/08/05 20:03:46 [Warning] [1169852821] v2ray.com/core/app/proxyman/inbound:                                                                                                              connection ends > v2ray.com/core/proxy/vless/inbound: invalid request from                                                                                                           IP:59782 > v2ray.com/core/proxy/vless/encoding: failed to read request ver                                                                                                             sion > tls: first record does not look like a TLS handshake

2020/08/05 20:29:17 [Warning] [3737505757] v2ray.com/core/app/proxyman/inbound:                                                                                                              connection ends > v2ray.com/core/proxy/vless/inbound: invalid request from                                                                                                 IP:4080 > v2ray.com/core/proxy/vless/encoding: failed to read request ver                                                                                                             sion > read tcp IP:443->IP:4080: i/o timeout

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:
2020/08/05 20:57:32 [Warning] [3052694223] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vless/outbound: connection ends > v2ray.com/core/proxy/vless/outbound: failed to decode response header > v2ray.com/core/proxy/vless/encoding: failed to read response version > EOF

2020/08/05 20:57:40 [Warning] [3392836414] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vless/outbound: connection ends > v2ray.com/core/proxy/vless/outbound: failed to decode response header > v2ray.com/core/proxy/vless/encoding: failed to read response version > EOF

2020/08/05 20:58:30 [Warning] [355430102] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vless/outbound: connection ends > v2ray.com/core/proxy/vless/outbound: failed to decode response header > v2ray.com/core/proxy/vless/encoding: failed to read response version > EOF
```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

V2Ray 4.26.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.6 linux/amd64)
A unified platform for anti-censorship.
Configuration OK.

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by twzchi** [comment]
@rprx  你看看这个 有日志了

**Comment by twzchi** [comment]
在Win10 客户端V2rayN（3.19）开启了MUX 开启了UDP

**Comment by rprx** [comment]
看起来你的 TLS 被降级攻击了，GFW 新手段？

**Comment by rprx** [comment]
看起来服务端是比较零星的日志，时间跨度有点大。有可能是你的 443 端口被扫了，属于正常情况

至于客户端，如果实际上是可以使用的，只是偶尔一两个连接出现问题，也属于正常情况。

此外，建议设置协议回落（

**Comment by rprx** [comment]
我似乎需要说明一下 VLESS 和 VMess 在日志上的区别：VLESS 只要遇到了异常情况就会视作 Warning，而 VMess 把很多异常情况视作 Info。所以对于 VLESS，偶尔的异常情况 Warning 如果不影响实际使用，则可以被忽略。

**Comment by twzchi** [comment]
> 我似乎需要说明一下 VLESS 和 VMess 在日志上的区别：VLESS 只要遇到了异常情况就会视作 Warning，而 VMess 把很多异常情况视作 Info。所以对于 VLESS，偶尔的异常情况 Warning 如果不影响实际使用，则可以被忽略。

我试试使用这个脚本iptablescript(原文参考:https://sharadchhetri.com/how-to-protect-from-port-scanning-and-smurf-attack-in-linux-server-by-iptables/) 防止端口被扫描

**Comment by rprx** [comment]
@twzchi 

没有必要，简单设置协议回落即可。

**Comment by twzchi** [comment]
> @twzchi
> 
> 没有必要，简单设置协议回落即可。

好的 我添加一下~ 试试

**Comment by twzchi** [comment]
> @twzchi
> 
> 没有必要，简单设置协议回落即可。

你看看 我这样写回落协议对不对


{
  "inbounds": [
    {
      "port":443,
      "protocol":"vless",
      "settings": {
        "decryption":"none",
         "fallback": {
  "addr": "127.0.0.1",
    "port": 443,
    "unix": "",
    "xver": 0
},
        "clients": [
          {
            "id": "UUID",
            "level": 0
          }
        ]
      },
     "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
          "alpn":["http/1.1"],
          "certificates": [
            {
              "certificateFile": "/etc/v2ray/v2ray.crt",
              "keyFile": "/etc/v2ray/v2ray.key"
            }
          ]
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}
是否用 动态端口会快些呢？

**Comment by rprx** [comment]
@twzchi 

没有问题。这里如果用动态端口则是减分项，现在 VLESS 也暂不支持。
