### ISSUE TITLE
vless在ws+tls+web传输组合里需要配置fallback么？

### ISSUE THREAD

**Issue by qiangliu8183** [v2ray/v2ray-core#2668]
请教各位，配置文档只说fallback 项是可选的，通常用于 TCP+TLS 传输组合。

**Comment by rprx** [comment]
没有必要，也不会生效。文档的“通常”是在留口子，因为并没有死死限制传输组合，实际上可以玩出其它花样。

但为了照顾大多数初级用户，我决定先修改一下文档（

**Comment by mixool** [comment]
≥ rprx x:没有必要，因为这是协议层面的，ws 在前面

**Comment by mixool** [comment]
能举例一些 花样么

**Comment by qiangliu8183** [comment]
> 没有必要，也不会生效。文档的“通常”是在留口子，因为并没有死死限制传输组合，实际上可以玩出其它花样。
> 
> 但为了照顾大多数初级用户，我决定先修改一下文档（

谢谢赐教

**Comment by o0HalfLife0o** [comment]
已有的vmess配置改成vless只需要改动几行就可以了
服务端：改protocol，删alterid，加decryption
```
      "protocol": "vless",
      "tag": "inbound_ws",
      "settings": {
        "clients": [
          {
            "id": "********************",
            "level": 0
          }
        ],
        "decryption": "none"
      },
```
客户端：改protocol和security，删alterid
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "*************",
            "port": 443,
            "users": [
              {
                "id": "*****************",
                "encryption": "none",
                "level": 0
              }
            ]
          }
        ]
      },

**Comment by qiangliu8183** [comment]
> 已有的vmess配置改成vless只需要改动几行就可以了，其他完全不用动就能正常使用
> 服务端：改protocol，删alterid，加decryption
> 
> ```
>       "protocol": "vless",
>       "tag": "inbound_ws",
>       "settings": {
>         "clients": [
>           {
>             "id": "********************",
>             "level": 0
>           }
>         ],
>         "decryption": "none"
>       },
> ```
> 
> 客户端：改protocol和security，删alterid
> 
> ```
>       "protocol": "vless",
>       "settings": {
>         "vnext": [
>           {
>             "address": "*************",
>             "port": 443,
>             "users": [
>               {
>                 "id": "*****************",
>                 "encryption": "none",
>                 "level": 0
>               }
>             ]
>           }
>         ]
>       },
> ```

又换回vmess了，软路由tproxy透明代理，用vless手机总提示wifi连接有问题，换回vmess就正常了

**Comment by rprx** [comment]
@qiangliu8183 

VLESS 没有这种特性。。。可能是自定义配置有问题，等 NG 出 UI 吧

**Comment by rprx** [comment]
@qiangliu8183 

VLESS 没有这种特性。。。可能是自定义配置有问题，等 NG 出 UI 吧（如果是直接在手机上使用

如果不是直接在手机上使用，请描述得再具体些
