### ISSUE TITLE
Please add an option to enable TCP_NODELAY (+TCP_QUICKACK)

### ISSUE THREAD

**Issue by enihcam** [v2ray/v2ray-core#2671]
`TCP_NODELAY` is a socket setting that disables Nagle's algorithm and allows packets to be sent across the network individually (without queuing ACKs one by one). Together with applying `TCP_QUICKACK`, each of packets can be ack-ed immediately. This is especially useful for links with high packet loss rate, because of the smaller transmission granularity.

**Comment by bzgszlk** [comment]
Does this achieve similar effect to ServerSpeeder and BBR?

I'd very much like to see such improvement which lets me ditch ServerSpeeder on Windows since there is no other BBR equivalent for Windows, upload speed without such implementation is hindered too much by high latency connections.

**Comment by enihcam** [comment]
> Does this achieve similar effect to ServerSpeeder and BBR?
> 
> I'd very much like to see such improvement which lets me ditch ServerSpeeder on Windows since there is no other BBR equivalent for Windows, upload speed without such implementation is hindered too much by high latency connections.

they are totally different and has no direct connection.
