### ISSUE TITLE
v2ray无法连接

### ISSUE THREAD

**Issue by suuhui** [v2ray/v2ray-core#2673]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
- v2rayN:V3.21
- v2ray-core:V4.27.0
- 系统：win10

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
        使用chrome通过vmess访问google

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
        网页无法访问，日志见下方

4) 你期待看到的正确表现是怎样的？
        正常访问google

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

无

客户端配置:

```javascript
    {
  "policy": null,
  "log": {
    "access": "D:\\Program Files\\v2rayN-Core\\Vaccess.log",
    "error": "D:\\Program Files\\v2rayN-Core\\Verror.log",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "proxy",
      "port": 10808,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "address": null,
        "clients": null,
        "decryption": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "********",
            "port": 80,
            "users": [
              {
                "id": "*************",
                "alterId": 0,
                "email": "t@t.tt",
                "security": "auto",
                "encryption": null
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": null,
        "tlsSettings": null,
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/9oprghre2fo1nkxz",
          "headers": {
            "Host": "hk-2.scnyc.vip"
          }
        },
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "stats": null,
  "api": null,
  "dns": null,
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "port": null,
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "ip": null,
        "domain": null
      }
    ]
  }
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

客户端错误日志:

```javascript
    2020/08/10 12:21:38 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://***.***.pro/**********): 520 Origin Error > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
2020/08/10 12:21:34 tcp:127.0.0.1:55381 accepted tcp:mtalk.google.com:5228 [proxy] 
2020/08/10 12:21:35 tcp:127.0.0.1:55400 accepted tcp:mtalk.google.com:5228 [proxy] 
2020/08/10 12:21:37 tcp:127.0.0.1:50227 accepted tcp:google.com:443 [proxy] 
2020/08/10 12:21:39 tcp:127.0.0.1:50229 accepted tcp:google.com:443 [proxy] 
```

8) 其它相关的配置文件（如 Nginx）和相关日志。
无

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。
无

**Comment by okudayukiko** [comment]
1、伺服器和客戶端AlterId不對。
2、VMess內置Encryption不要選擇Null。
3、安裝最新Linux內核5.6，開啟BBR，對V2Ray提速明顯。
4、Chrome/IE/Edge預設用的是SOCKS4協定，請用Privoxy程式將SOCKS5代理轉換為HTTP代理+HTTPS代理。

**Comment by wzhuan520** [comment]
看看是不是熊时间不对。时间选根据市区更新成最标准的。

**Comment by wangyumei1369** [comment]
你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
客户端v2rayN:V5.26
服务器v2rayN: v4.45.2
系统：win10

你的使用场景是什么？
我用CHROME浏览器访问谷歌

你看到的不正常的现象是什么？
我在阿里云搭建CENTOS的3种协议，VMESS,SSR,SOCKS5，只有SOCKS5可以正常上网，另外两种连接后没有网络。网页无法访问，

错误日志见下方
2022/06/26 08:44:10 [Warning] V2Ray 4.45.2 started
2022/06/26 09:05:13 [Warning] V2Ray 4.45.2 started
2022/06/26 09:17:43 [Error] app/dns: failed to retrieve response > Post "https://dns.google/dns-query": context canceled
2022/06/26 09:20:22 [Warning] V2Ray 4.45.2 started
2022/06/26 09:23:22 [Warning] V2Ray 4.45.2 started
2022/06/26 09:26:05 [Error] app/dns: failed to retrieve response > Post "https://dns.google/dns-query": context canceled
2022/06/26 09:26:05 [Error] app/dns: failed to retrieve response > Post "https://dns.google/dns-query": context canceled

你期待看到的正确表现是怎样的？
正常访问google

请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
服务器端配置:
---------- V2Ray 配置信息 -------------

 地址 (Address) = 47.245.25.42

 端口 (Port) = 27056

 用户ID (User ID / UUID) = c7fd95b5-15c7-48d3-b4cf-de61bd8a39f9

 额外ID (Alter Id) = 0

 传输协议 (Network) = tcp

 伪装类型 (header type) = none

 备注: 广告拦截已开启..

---------- END -------------

客户端配置:
VMESS客户端配置
地址：47.245.25.42
端口：27056
用户ID：c7fd95b5-15c7-48d3-b4cf-de61bd8a39f9
加密方式：AUTO

客户端配置是扫描二维码导入的，不会出错的，我放附件里了。

我折腾几天了，麻烦大神帮忙，谢谢。
