### ISSUE TITLE
服务器端 centos/rhel 反向代理无法连接使用造成安全连线失败

### ISSUE THREAD

**Issue by hstonc** [v2ray/v2ray-core#2675]
1) 你正在使用哪个版本的 V2Ray？
4.27.0(服务器)和4.23.0(客户端)
2) 你的使用场景是什么？
访问google.com
3) 你看到的不正常的现象是什么？

建立安全连接失败
连接到 google.com 时发生错误。PR_END_OF_FILE_ERROR

    由于不能验证所收到的数据是否可信，无法显示您想要查看的页面。
    建议向此网站的管理员反馈这个问题。

5) 请附上你的配置。

服务器端配置:

```javascript
{
  "log": {
    "loglevel": "warning",
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log"
  },
  "inbounds": [
    {
      "port": 12345,
      "listen":"127.0.0.1",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "c1693cff-4fd9-48da-9117-1e75da31d144",
            "alterId": 64
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
        "path": "/ray"
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}
```

客户端配置:

```javascript
{
  "inbounds": [
    {
      "port": 1080,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
      "settings": {
        "auth": "noauth",
        "udp": false
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "mydomain.me",
            "port": 443,
            "users": [
              {
                "id": "c1693cff-4fd9-48da-9117-1e75da31d144",
                "alterId": 64
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "wsSettings": {
          "path": "/ray"
        }
      }
    }
  ]
}

```

6)  请附上出错时软件输出的错误日志。

服务器端错误日志:

无记录

客户端错误日志:

```javascript
2020/08/11 15:37:00 [Warning] [2288886780] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://mydomain.me/ray): 404 Not Found > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2020/08/11 15:37:06 [Warning] [2891921708] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://mydomain.me/ray): 404 Not Found > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2020/08/11 15:37:10 [Warning] [3117159509] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://mydomain.me/ray): 404 Not Found > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
```

7) 请附上访问日志。

无记录

8) 其它相关的Apache 配置(网页可正常访问)

```javascript
<VirtualHost *:443>
  SSLEngine on
  
  SSLCertificateFile /etc/cloudflare/mydomain.me.pem
  SSLCertificateKeyFile /etc/cloudflare/mydomain.me.key
  
  SSLProtocol             all -SSLv3 -TLSv1 -TLSv1.1
  SSLCipherSuite          ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
  SSLHonorCipherOrder     off
  SSLSessionTickets       off
  
  <Location "/ray/">
    ProxyPass ws://127.0.0.1:12345/ray/ upgrade=WebSocket
    ProxyAddHeaders Off
    ProxyPreserveHost On
    RequestHeader append X-Forwarded-For %{REMOTE_ADDR}s
  </Location>
</VirtualHost>
```

**Comment by hstonc** [comment]
服务器系统( CentOS SELinux 8 x64 )客户端系统(Windows 10)

**Comment by 1608637229** [comment]
建议客户端升级4.27

**Comment by darhwa** [comment]
v2ray里ws路径是`/ray`，apache里路径是`/ray/`，不一致，这应该是导致404的原因。

另外说句题外话，你们这样通通把ws/h2路径设置为`/ray`，真的好吗？随便搜一搜，#2641 #2520 #2501 #2458 ，等等，都是用这个不知从哪个网上教程抄来的路径。GFW只要主动探测这个路径，就立马暴露你的主机是在提供v2ray服务了。测试方法：用`curl -I https://YOUR_DOMAIN/ray`看看，返回的状态码是200（你网页服务器和v2ray都配置无误的话），而换个随机路径应该是404。

**Comment by hstonc** [comment]
> 
> 
> v2ray里ws路径是`/ray`，apache里路径是`/ray/`，不一致，这应该是导致404的原因。
> 
> 另外说句题外话，你们这样通通把ws/h2路径设置为`/ray`，真的好吗？随便搜一搜，#2641 #2520 #2501 #2458 ，等等，都是用这个不知从哪个网上教程抄来的路径。GFW只要主动探测这个路径，就立马暴露你的主机是在提供v2ray服务了。测试方法：用`curl -I https://YOUR_DOMAIN/ray`看看，返回的状态码是200（你网页服务器和v2ray都配置无误的话），而换个随机路径应该是404。

感谢，我去试试看，这些都是官方的白话文教程和社区版白话文教程都是怎样写的

**Comment by hstonc** [comment]
> 
> 
> v2ray里ws路径是`/ray`，apache里路径是`/ray/`，不一致，这应该是导致404的原因。
> 
> 另外说句题外话，你们这样通通把ws/h2路径设置为`/ray`，真的好吗？随便搜一搜，#2641 #2520 #2501 #2458 ，等等，都是用这个不知从哪个网上教程抄来的路径。GFW只要主动探测这个路径，就立马暴露你的主机是在提供v2ray服务了。测试方法：用`curl -I https://YOUR_DOMAIN/ray`看看，返回的状态码是200（你网页服务器和v2ray都配置无误的话），而换个随机路径应该是404。

感谢，我去试试看，这些都是官方的白话文教程和社区版白话文教程都是这样写的

**Comment by jerry-ch-issue** [comment]
> v2ray里ws路径是`/ray`，apache里路径是`/ray/`，不一致，这应该是导致404的原因。
> 
> 另外说句题外话，你们这样通通把ws/h2路径设置为`/ray`，真的好吗？随便搜一搜，#2641 #2520 #2501 #2458 ，等等，都是用这个不知从哪个网上教程抄来的路径。GFW只要主动探测这个路径，就立马暴露你的主机是在提供v2ray服务了。测试方法：用`curl -I https://YOUR_DOMAIN/ray`看看，返回的状态码是200（你网页服务器和v2ray都配置无误的话），而换个随机路径应该是404。


/ray 路径是官网推荐的白话文教程里的，他没说这个路径对于主机安全有影响，只是说要保持一致。应该是前两年我们这种小白刚接触v2ray，看的都是这个教程，后来随着普及，这个基本就是默认配置了，方便了墙的探测。

个人实践证明GFW的确一直探测这个路径。之前就有人让改，但是没意识到严重性，导致后面连续几个月不定时的阻断连接，只要连接时间稍长，每小时都会发生。前天刚好有需要连接到VPS，就顺手改了路径，客户端也都改掉了。三天了，没有发生过之前的阻断连接现象。

**Comment by darhwa** [comment]
@hstonc 也许是我前面的叙述不够清楚。你应该要么把apache配置改成跟v2ray一样（`ray`后面没有`/`），要么把v2ray配置改成跟apache一样（`ray`后面加上`/`）。

**Comment by darhwa** [comment]
@jerry-ch-issue 
> 个人实践证明GFW的确一直探测这个路径

有服务器上的日志证明吗？

**Comment by hstonc** [comment]
> @hstonc 也许是我前面的叙述不够清楚。你应该要么把apache配置改成跟v2ray一样（`ray`后面没有`/`），要么把v2ray配置改成跟apache一样（`ray`后面加上`/`）。

@darhwa 其实以及改好了，现在的问题是服务器端和客户端已经没有任何错误日志，但依旧安全连线失败，我附上了apache错误日志

**Comment by darhwa** [comment]
如果你主机是centos/rhel，这篇可能有用：https://confluence.atlassian.com/bitbucketserverkb/permission-denied-in-apache-logs-when-used-as-a-reverse-proxy-790957647.html

**Comment by jerry-ch-issue** [comment]
> @jerry-ch-issue
> 
> > 个人实践证明GFW的确一直探测这个路径
> 
> 有服务器上的日志证明吗？

额，不知道怎么弄，v2ray的日志应该是没有的，nginx日志不会看

**Comment by hstonc** [comment]
> 
> 
> 如果你主机是centos/rhel，这篇可能有用：https://confluence.atlassian.com/bitbucketserverkb/permission-denied-in-apache-logs-when-used-as-a-reverse-proxy-790957647.html

@darhwa 解决了，非常感谢
