### ISSUE TITLE
好像又不能用了？

### ISSUE THREAD

**Issue by Jason4774** [v2ray/v2ray-core#268]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please answer the following questions before submitting your issue. Thank you.

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
1) What version of V2Ray are you using?
2.1.2windows版
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
2) What your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

3) 你看到的不正常的现象是什么？
3) What did you see?
无法使用
4) 你期待看到的正确表现是怎样的？
4) What do you expected to see instead?
正常代理
5) 请附上你的配置文件。
5) Please attach your configuration file.
原配置文件

![qq 20160930122138](https://cloud.githubusercontent.com/assets/19594338/18981659/fd2a3580-8712-11e6-94ac-d2a68dc98277.png)

**Comment by liaobin** [comment]
发配置文件啊...

**Comment by Jason4774** [comment]
是原配置文件还用我发吗？

**Comment by liaobin** [comment]
用自带服务器的真少见,改下dns试试

**Comment by Jason4774** [comment]
我不会使用，我以为就直接用就好了，请问怎么修改成其他的服务器呢？我是小白，请多多指教、。

**Comment by liaobin** [comment]
按官方文档在vps上搭建即可

**Comment by Jason4774** [comment]
那得要有vps才行，所以我还是算了，谢谢你的回复，不过我一直用的自带的服务器，之前还挺快的，前段时间遭受DDOS攻击有一段时间不能用，今天又不行了。

**Comment by liaobin** [comment]
看这个错误信息应该是dns的问题,你改了看看,另外也可能是月底服务器流量使用完了...

**Comment by Jason4774** [comment]
请问dns改成什么好呢？谢谢。
![image](https://cloud.githubusercontent.com/assets/19594338/18986967/0142dbf8-8732-11e6-997a-4e9ae2884211.png)
这儿吗？改成什么dns好？

**Comment by liaobin** [comment]
保留localhost即可

**Comment by Jason4774** [comment]
试过不行。下个月试试。谢谢你的回复。
