### ISSUE TITLE
Reload configuration cause v2ray to exit

### ISSUE THREAD

**Issue by nielspeen** [v2ray/v2ray-core#269]
v2.2.1

Reloading the configuration by sending a HUP signal (as suggest by the included systemv script) causes v2ray to exit.

If sending a HUP signal is not the correct method, is  there a different method to reload  the configuration file without restarting v2ray?

**Comment by v2ray** [comment]
So far there is no way to reload configuration without restarting V2Ray program.

This functionality may be added in the future, but you have to restart the process (such as `service v2ray restart`) for now.

**Comment by nielspeen** [comment]
Understood. Would be a great feature to have. 

Either reloading the config, or using an external database for "clients". Currently I have to restart (and disconnect all my users) several times a day when I add new users.

**Comment by v2ray** [comment]
Acknowledged
