### ISSUE TITLE
增加一个反向的出口连接，

### ISSUE THREAD

**Issue by limaofu** [v2ray/v2ray-core#2693]
目前v2ray的outbounds出口方向都是当前结点作为客户端对目标发起一个连接，
我的想法是增加一个outbound方向的监听端口，让目标对我发起tcp连接，类似于内网穿透
这样就能让处于内网的设备也能作为代理。

也就是说出口outbounds方向的连接不是由自己这个结点发起的，而是由目标（下一跳）结点发起的tcp连接。好处就是可以进行内网穿透。

**Comment by genufish** [comment]
目标如何知道何时向哪个ip发起连接？而且客户端内网的比较多。不过反向出口连接做成的话，chrome可以拿来做ws中继减少tls特征

**Comment by limaofu** [comment]
希望能增加 上下行分享链路，出去时用一个节点，回来时再转另一结点回来。可以利用上下行流量不对等的结点。有些结点出去时（上行）流量大，但回来（下行）几乎为0，有些结点下行流量不限速，却上行几乎为0. 所以我想在外边多放几个，至少放2个结点。出去时连接上行不限速的，回来的流量由代理结点转到外边的第2个结点（下行不限制）的发回给我，我这边监听某个端口就行。

**Comment by limaofu** [comment]
增加一个反向的出口连接，目的是 为了更方便地做 内网穿透，目前的v2ray的内网穿透方式很不方便。
增加了反向的出口连接后，在代理上只要开放一个inbounds的任意门入口，然后转到 那个反向的出口连接就行了。
因为 反向的出口连接是 给 要做内网穿透的设备去连接的。
