### ISSUE TITLE
请教这两个v2ray有什么不同，前者4.27.0，后者3.21

### ISSUE THREAD

**Issue by lyjhyjyes** [v2ray/v2ray-core#2694]
https://github.com/v2ray/v2ray-core/releases
https://github.com/2dust/v2rayN/releases
请教这两个v2ray有什么不同，前者4.27.0，后者3.21
之前一直用后者v2rayN，不记得从哪里下载的，可能是机场配的软件，今天删除发现占用了8G硬盘，太可怕。。你们有这样的问题吗

**Comment by kslr** [comment]
可以阅读 2dust 的 readme

**Comment by sagasm** [comment]
3.21是v2rayN(gui)的版本,4.27是v2ray-core的版本.

**Comment by lyjhyjyes** [comment]
> 3.21是v2rayN(gui)的版本,4.27是v2ray-core的版本.

明白，4.27不会用，直接用3.21
