### ISSUE TITLE
似乎是UDP包导致爆炸

### ISSUE THREAD

**Issue by Smallthing** [v2ray/v2ray-core#2695]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
4.27.0
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
ss vless 双协议多端口
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
服务器崩溃
4) 你期待看到的正确表现是怎样的？
服务器正常运作

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

``Aug 24 10:02:17 user v2ray[58414]: V2Ray 4.27.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.6 linux/amd64)
Aug 24 10:02:17 user v2ray[58414]: A unified platform for anti-censorship.
Aug 24 10:02:17 user v2ray[58414]: 2020/08/24 10:02:17 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
Aug 24 10:02:17 user v2ray[58414]: v2ctl> Read config:  /etc/v2ray/config.json
Aug 24 10:02:19 user v2ray[58414]: panic: extending out of bound
Aug 24 10:02:19 user v2ray[58414]: goroutine 7 [running]:
Aug 24 10:02:19 user v2ray[58414]: v2ray.com/core/common/buf.(*Buffer).Extend(...)
Aug 24 10:02:19 user v2ray[58414]: #011v2ray.com/core/common/buf/buffer.go:62
Aug 24 10:02:19 user v2ray[58414]: v2ray.com/core/proxy/shadowsocks.(*AEADCipher).EncodePacket(0xc000258dd0, 0xc000099ae0, 0x20, 0x20, 0xc0001bb080, 0x1bb, 0x0)
Aug 24 10:02:19 user v2ray[58414]: #011v2ray.com/core/proxy/shadowsocks/config.go:202 +0x2db
Aug 24 10:02:19 user v2ray[58414]: v2ray.com/core/proxy/shadowsocks.EncodeUDPPacket(0xc000206300, 0xc0004ca000, 0x7cd, 0x800, 0xc000206300, 0x0, 0xc000050700)
Aug 24 10:02:19 user v2ray[58414]: #011v2ray.com/core/proxy/shadowsocks/protocol.go:220 +0x2af
Aug 24 10:02:19 user v2ray[58414]: v2ray.com/core/proxy/shadowsocks.(*Server).handlerUDPPayload.func1(0xeb2700, 0xc00021c3c0, 0xc00027c380)
Aug 24 10:02:19 user v2ray[58414]: #011v2ray.com/core/proxy/shadowsocks/server.go:82 +0x10e
Aug 24 10:02:19 user v2ray[58414]: v2ray.com/core/transport/internet/udp.handleInput(0xeb2700, 0xc00021c3c0, 0xc000222760, 0xeb3ac0, 0xc00003407c, 0x3000001bb, 0xc000222080)
Aug 24 10:02:19 user v2ray[58414]: #011v2ray.com/core/transport/internet/udp/dispatcher.go:116 +0xb2
Aug 24 10:02:19 user v2ray[58414]: created by v2ray.com/core/transport/internet/udp.(*Dispatcher).getInboundRay
Aug 24 10:02:19 user v2ray[58414]: #011v2ray.com/core/transport/internet/udp/dispatcher.go:77 +0x53d

**Comment by rprx** [comment]
（差点以为是 VLESS 的问题

**Comment by Smallthing** [comment]
请问这个需要修改哪些部分呢
我看日志应该是ss udp部分出的问题

**Comment by rprx** [comment]
> 
> 
> 请问这个需要修改哪些部分呢
> 我看日志应该是ss udp部分出的问题

需要先说明如何触发及触发概率

**Comment by perfect-network** [comment]
> > 请问这个需要修改哪些部分呢
> > 我看日志应该是ss udp部分出的问题
> 
> 需要先说明如何触发及触发概率

v2ray28 啥时候发布啊，带佬
