### ISSUE TITLE
希望能增加 上下行分离链路

### ISSUE THREAD

**Issue by limaofu** [v2ray/v2ray-core#2696]
希望能增加 上下行分离链路，出去时用一个节点，回来时再转另一结点回来。可以利用上下行流量不对等的结点。有些结点出去时（上行）流量大，但回来（下行）几乎为0，有些结点下行流量不限速，却上行几乎为0. 所以我想在外边多放几个，至少放2个结点。出去时连接上行不限速的，回来的流量由代理结点转到外边的第2个结点（下行不限制）的发回给我，我这边监听某个端口就行。

**Comment by limaofu** [comment]
代理结点1为客户端的接入代理，代理2为最终的代理，负责和目标服务器通信，目标返回的流量转发给结点3，结点3再发回给结点1，所以结点1上要监听某个端口。这3个代理结点间的流量要嵌套一层外壳，可以叫作 ”上下行流量分离协议“，以便在结点1那边把收到的下行流量匹配到同一个客户的tcp会话

**Comment by limaofu** [comment]
![上下行流量分离协议报文](https://user-images.githubusercontent.com/54393027/91114537-bd275b00-e6ba-11ea-81cd-a450c8ce4414.png)

**Comment by limaofu** [comment]
漏了一个字段，发起结点的端口

**Comment by limaofu** [comment]
![上下行流量分离协议报文2](https://user-images.githubusercontent.com/54393027/91114781-4c347300-e6bb-11ea-9d56-5c652710da6a.png)

**Comment by limaofu** [comment]
漏了验证字段，就是中转结点给发起结点监听端口发 下行流量时，如果判断是合法的下行流量。要加一个验证字段。

**Comment by limaofu** [comment]
![上下行流量分离协议报文3](https://user-images.githubusercontent.com/54393027/91115044-e399c600-e6bb-11ea-8753-f41d109df434.png)

**Comment by rprx** [comment]
可以做到“上下行分离”的效果，甚至还可以用不同的协议，就是写起来略微麻烦。

我之前想到了一种使纯 TCP 更安全的方案，有一点像，比如先通过通道 A（TLS）交换加密密钥、再通过 B（TCP）传输加密信息。

**Comment by limaofu** [comment]
这个上下行流量分离协议可由vmess封装，在使用vmess时可加一个setting属性，比如 ”usedistrixx“: true

**Comment by limaofu** [comment]
我是说上传数据时用结点2，下载数据时用结点3返回。

**Comment by limaofu** [comment]
或者更麻烦点，不使用tcp层，使用udp，这样上行流量就真的是只上传数据，不接收返回消息，包括（之前的tcp响应控制消息）。返回的消息由结点3返回。纯单向的流量。

**Comment by limaofu** [comment]
![上下行流量分离协议报文4](https://user-images.githubusercontent.com/54393027/91115645-3b84fc80-e6bd-11ea-8c04-0ded6ef05cbb.png)

**Comment by genufish** [comment]
下行数据由服务器发起下行链路的话，感觉客户端需要公网ip。比较容易的还是客户端发起2个连接，一个专门上行，一个专门下行。

**Comment by limaofu** [comment]
呖，还是您说的有效率，只要2台服务器了，

**Comment by 0x0004** [comment]
目测出发点是有的服务器只计单向流量，然后想用这个节省成本？
