### ISSUE TITLE
增加反向的inbounds和outbounds，方便做内网穿透

### ISSUE THREAD

**Issue by limaofu** [v2ray/v2ray-core#2697]
v2ray现有的内网穿透不够方便，
我的想法是增加 reverse反向的Inbounds和outbounds，也就是让内网设备（欲做穿透的）的inbounds主动向公网代理的outbound发起tcp连接。这样在公网代理那边创建一个dokodemo任意门监听某端口，再转为127.0.0.1:某端口，再把此任意门流量向 反向的outbound发出。 发出后，内网设备的反向的inbound就收到了，直接再走freedom就是访问本内网设备的127.0.0.1:某端口

**Comment by limaofu** [comment]
![反向in_outbounds](https://user-images.githubusercontent.com/54393027/91144331-751e2d80-e6e6-11ea-937b-f3fa1d80a30b.png)

**Comment by limaofu** [comment]
同时规定，反向outbound只能有一个客户端连接。

**Comment by limaofu** [comment]
一个反向inbound也只能向一个outbound发起连接。

**Comment by limaofu** [comment]
这样可以设置多个任意门，实现多个端口的内网穿透。

**Comment by xloypaypa** [comment]
> 同时规定，反向outbound只能有一个客户端连接。

> 一个反向inbound也只能向一个outbound发起连接。

假设如下场景：2台公网代理+3台内网web，并且都会有动态扩容。因此，2台公网机器的配置是一样的，3台内网的机器也是配置一样。
不知道如果限制一条链接，会不会对这类场景有影响？

**Comment by limaofu** [comment]
一台公网代理上可设置多个 反向的outbound 出口， 每个出口只允许一个内网的某个反向Inbound连接
