### ISSUE TITLE
求助，更新v2ray后，配置好文件且检查无语法错误单连接不上

### ISSUE THREAD

**Issue by DannyLiTHEBEST** [v2ray/v2ray-core#2702]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
服务器使用当前最新发行版本，客户端为V2rayN v3.19
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
使用Chromium连接google
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
访问超时
4) 你期待看到的正确表现是怎样的？
能够正常访问谷歌这类网站
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:
{ "inbounds": [
    {
      "port": 443, 
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "？？？",
            "alterId": 64
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls", 
        "tlsSettings": {
          "certificates": [
            {
              "certificateFile": "/usr/local/etc/v2ray/v2ray.crt", // 证书文件
              "keyFile": "/usr/local/etc/v2ray/v2ray/v2ray.key" // 密钥文件
            }
          ]
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}

```javascript
    // 在这里附上服务器端配置文件
```

客户端配置:
{
  "policy": null,
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "proxy",
      "port": 1080,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "address": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "？？？",
            "port": 443,
            "users": [
              {
                "id": "？？？",
                "alterId": 64,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "serverName": null
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": null,
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "stats": null,
  "api": null,
  "dns": null,
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "port": null,
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "ip": null,
        "domain": null
      }
    ]
  }
}
```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:
无
```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:
2020/08/26 13:25:47 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp: lookup ？？？: no such host] > v2ray.com/core/common/retry: all retry attempts failed
2020/08/26 13:25:48 tcp:127.0.0.1:57651 accepted tcp:ogs.google.com:443 [proxy] 
2020/08/26 13:25:50 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp: lookup ？？？: no such host] > v2ray.com/core/common/retry: all retry attempts failed
2020/08/26 13:25:54 tcp:127.0.0.1:57654 accepted tcp:www.google.com:443 [proxy] 
2020/08/26 13:25:54 tcp:127.0.0.1:57656 accepted tcp:www.google.com:443 [proxy] 
2020/08/26 13:25:56 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp: lookup ？？？: no such host] > v2ray.com/core/common/retry: all retry attempts failed
2020/08/26 13:25:57 tcp:127.0.0.1:57659 accepted tcp:www.google.com:443 [proxy] 
2020/08/26 13:25:57 tcp:127.0.0.1:57660 accepted tcp:www.google.com:443 [proxy] 
2020/08/26 13:25:59 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp: lookup ？？？: no such host] > v2ray.com/core/common/retry: all retry attempts failed

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```
无
8) 其它相关的配置文件（如 Nginx）和相关日志。
无
9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by limaofu** [comment]
"streamSettings": {
"network": "tcp",
"security": "tls",
"tlsSettings": {
"allowInsecure": false,
"serverName": null
},
客户端这个allowInsecure要改为true，因为你的ssl证书可能是自签名的。

**Comment by DannyLiTHEBEST** [comment]
> “ streamSettings”：{
> “ network”：“ tcp”，
> “ security”：“ tls”，
> “ tlsSettings”：{
> “ allowInsecure”：false，
> “ serverName”：null
> }，
> 客户端这个allowInsecure要改为true，因为你的ssl证书可能是自签名的。
感谢您的回复，但是我找这样修改以后又出现了这样的错误信息
v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp ？？？: i/o timeout dial tcp ？？？: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by DannyLiTHEBEST** [comment]
经过检查，发现是服务器tcp端口被ping，没办法了，谢谢帮助

**Comment by DannyLiTHEBEST** [comment]
经过检查，发现是该ip的tcp端口被墙，感谢帮助

**Comment by JorgeLiu** [comment]
> 经过检查，发现是该ip的tcp端口被墙，感谢帮助

长城真神奇，还能墙指定端口
