### ISSUE TITLE
增加底层传输协议为icmp-echo

### ISSUE THREAD

**Issue by limaofu** [v2ray/v2ray-core#2706]
使用icmp-echo-request和reply来做为底层的数据传输。

**Comment by genufish** [comment]
只要限制icmp速率每秒1包就彻底没救了

**Comment by kingwilliam** [comment]
icmp和很多port如dns53很久前已有人做过 好快就没了 原因是icmp和dns53有什麽可能有大量资料传送。

就算ssh23墙定义linux logon 只容许少量资料传送。 大流量也只许短时间。 长时间大流量必封。

**Comment by limaofu** [comment]
Oh, 希儿特，影响科技的不是技术本身，

**Comment by jack9603301** [comment]
通常防火墙不会检查ICMP数据包通讯，并且个人也不会有真正意义的大流量，ICMP属于控制协议，一般路由器根本不会限制其速度，因为你的任何通讯 和连接，包括正常的TCP，都必须经过ICMP控制协议的控制，所谓echo限速一般也就wrt玩家和服务器去做而已。主干是不会做此类限制的，此实现完全可以实现，虽然我是BGP ipip over wg over pingtunnel 已经很长时间没有中断了，之前udp2raw都会因为链路问题晚上下线

**Comment by jack9603301** [comment]
> 只要限制icmp速率每秒1包就彻底没救了

这个只有可能是wrt玩家和自己的服务器群的网络内 对自己管理的数据包进行echo限速，主干是不会这么做的

**Comment by jack9603301** [comment]
> icmp和很多port如dns53很久前已有人做过 好快就没了 原因是icmp和dns53有什麽可能有大量资料传送。
> 
> 就算ssh23墙定义linux logon 只容许少量资料传送。 大流量也只许短时间。 长时间大流量必封。

现在也有 pingtunnel 我就用的这个 实际上就流量而言 个人传输的流量和主干传输的icmp流量比是一粒沙子而言，因为icmp是一种关键的控制协议，主干路由器是不会限制它的，除非是对端服务器机房进行的限制，但这个量级到不了DDOS的程度，不会触发限制。

必须懂原理，ICMP的存在比较特殊，它对每个tcp和udp传输至关重要，我们说的ping也只是echo而言，再说如果有人跑NMS，其探测流量说不定都比pingtunnel的传输流量大（每分钟一次24小时不间断）
