### ISSUE TITLE
v2ray在软路由网关上没有通过代理服务器

### ISSUE THREAD

**Issue by om2mo** [v2ray/v2ray-core#2707]
1) 你正在使用哪个版本的 V2Ray？
**服务端/客户都 = V2Ray 4.27.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.6 linux/arm64)**

2) 你的使用场景是什么？
**使用Linux作为软路由，V2RAY透明代理给客户机**

3) 你看到的不正常的现象是什么？
**客户机都可以正常v2ray，但是网关（也就是Linux设备）没有通过v2ray代理，导致curl无法下载文件，wget速度很慢。**
<img width="421" alt="2020-08-28 12_51_18-192 168 1 1 - root@ubuntu_ ~ - Xshell 6 (Free for Home_School)" src="https://user-images.githubusercontent.com/4419299/91522753-96248f80-e92d-11ea-88c7-60ee02feca52.png">
curl没有通过代理，想要下载文件wget很慢

4) 你期待看到的正确表现是怎样的？

**网关像客户机一样通过v2ray上网**

<img width="565" alt="2020-08-28 12_51_55-192 168 1 1 - root@ubuntu_ ~ - Xshell 6 (Free for Home_School)" src="https://user-images.githubusercontent.com/4419299/91522826-be13f300-e92d-11ea-9cc3-6931c65e38a7.png">

5) 请附上你的配置

有什么需要改的地方吗？网关是双网卡，eth0接pon dsl，eth1接内网机器

```
*mangle
:PREROUTING ACCEPT [29415:28484134]
:INPUT ACCEPT [41971:30282834]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [33843:29701400]
:POSTROUTING ACCEPT [33843:29701400]
:V2RAY - [0:0]
:V2RAY_MASK - [0:0]
-A PREROUTING -j V2RAY
-A FORWARD -o ppp0 -p tcp -m tcp --tcp-flags SYN,RST SYN -m tcpmss --mss 1400:65495 -j TCPMSS --clamp-mss-to-pmtu
-A OUTPUT -j V2RAY_MASK
-A V2RAY -d 127.0.0.1/32 -j RETURN
-A V2RAY -d 224.0.0.0/4 -j RETURN
-A V2RAY -d 255.255.255.255/32 -j RETURN
-A V2RAY -d 192.168.0.0/16 -p tcp -j RETURN
-A V2RAY -d 192.168.0.0/16 -p udp -m udp ! --dport 53 -j RETURN
-A V2RAY -i eth1 -p udp -j TPROXY --on-port 12345 --on-ip 0.0.0.0 --tproxy-mark 0x1/0xffffffff
-A V2RAY -i eth1 -p tcp -j TPROXY --on-port 12345 --on-ip 0.0.0.0 --tproxy-mark 0x1/0xffffffff
-A V2RAY_MASK -d 224.0.0.0/4 -j RETURN
-A V2RAY_MASK -d 255.255.255.255/32 -j RETURN
-A V2RAY_MASK -d 192.168.0.0/16 -p tcp -j RETURN
-A V2RAY_MASK -d 192.168.0.0/16 -p udp -m udp ! --dport 53 -j RETURN
-A V2RAY_MASK -m mark --mark 0xff -j RETURN
-A V2RAY_MASK -i eth1 -p udp -j MARK --set-xmark 0x1/0xffffffff
-A V2RAY_MASK -i eth1 -p tcp -j MARK --set-xmark 0x1/0xffffffff
COMMIT
```

**Comment by om2mo** [comment]
/etc/resolv.con里面随便填啥dns解析都是污染的，但是客户机都不影响，网速也没慢

root@ubuntu:~# nslookup google.com
Server:         114.114.114.114
Address:        114.114.114.114#53

Non-authoritative answer:
Name:   google.com
Address: 8.7.198.46

root@ubuntu:~# nslookup google.com
Server:         114.114.114.114
Address:        114.114.114.114#53

Non-authoritative answer:
Name:   google.com
Address: 46.82.174.69

root@ubuntu:~# nslookup google.com
Server:         114.114.114.114
Address:        114.114.114.114#53

Non-authoritative answer:
Name:   google.com
Address: 46.82.174.69

**Comment by om2mo** [comment]
我在网关查询一个IP的时候，比如nslookup google.com，在日志中没有出现。而客户机查询的时候可以看到，这说明本机网关没有代理成功吗？

**Comment by qiangliu8183** [comment]
V2RAY_MASK就不要加”-i eth1“了

**Comment by om2mo** [comment]
> 本机的V2RAY_MASK就不要加”-i eth1“了

哦，那是我在做测试，结果是一样的

**Comment by qiangliu8183** [comment]
完整的iptables贴出来看看

**Comment by om2mo** [comment]
> 完整的iptables贴出来看看，我这里的环境和你一样，一切正常

完整的就是那个其他没有了，网关要装dnsmasq吗

**Comment by darhwa** [comment]
> -A V2RAY_MASK -i eth1 -p udp -j MARK --set-xmark 0x1/0xffffffff
-A V2RAY_MASK -i eth1 -p tcp -j MARK --set-xmark 0x1/0xffffffff

你在 OUTPUT 链上来个`-i eth1`是什么意思？`-i`是匹配收到数据包的设备，这里应该用`-o eth0`吧（假设你发包的设备是`eth0`）。
