### ISSUE TITLE
openbsd binary please

### ISSUE THREAD

**Issue by sunk** [v2ray/v2ray-core#271]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please answer the following questions before submitting your issue. Thank you.

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
1) What version of V2Ray are you using?
V2Ray v2.0 (One for all) 20160820

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
2) What your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
Trying to setup v2ray on my OpenBSD box (amd64). Notice that OpenBSD already dropped support of linux binaries and freebsd binaries so I cannot use those instead.

3) 你看到的不正常的现象是什么？
3) What did you see?
I cannot find an OpenBSD binary of v2ray.

4) 你期待看到的正确表现是怎样的？
4) What do you expected to see instead?
It would be nice to have an OpenBSD binary release, or at least compiling instructions.

5) 请附上你的配置文件。
5) Please attach your configuration file.
same as the default configuration.

**Comment by v2ray** [comment]
会在下一个版本中发布openbsd的二进制文件。
