### ISSUE TITLE
用v2ray做透明代理，设置v2ray开机自启动后CPU占用率高

### ISSUE THREAD

**Issue by BlackWaters** [v2ray/v2ray-core#2722]
Please answer all the questions with enough information. All issues not following this template will be closed immediately.
If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2fly/discussion/issues) first.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
4.27.5

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

用V2ray在旁路由上做透明代理，发现设置开机自启动v2ray后v2ray CPU占用率很高，但是只要重新启动`v2ray service v2ray restart`就会恢复正常

3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)
以下是开机后，top命令看到的v2ray CPU占用

![image](https://user-images.githubusercontent.com/20432310/92359350-a9014600-f11d-11ea-9b8b-842072674be7.png)

执行`service v2ray restart`后，v2ray的CPU占用

![image](https://user-images.githubusercontent.com/20432310/92359427-cfbf7c80-f11d-11ea-92dc-06bf4172af8a.png)

4) What's your expectation?

希望开机自启动时，v2ray CPU占用率能降下来

5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

Server configuration:

```javascript
   {
        "log": {
        "access" : "/usr/v2raylog/access.log",
        "error" : "/usr/v2raylog/access.log",
        "loglevel" : "warning"
        },
  "inbounds": [{
    "port": *****,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "*****",
          "level": **,
          "alterId": **
        }
      ]
    }
  }],
  "outbounds": [{
    "protocol": "freedom",
    "settings": {}
  },{
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  }],
  "routing": {
    "rules": [
      {
        "type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "blocked"
      }
    ]
  }
}
```

Client configuration:

旁路由上的config

```javascript
{
    "log":
    {
        "access": "/usr/local/etc/v2ray/access.log",
        "error": "/usr/local/etc/v2ray/error.log",
        "loglevel": "warning"
    },
  "inbounds": [
    {
      "tag":"transparent",
      "port": 12345,
      "protocol": "dokodemo-door",
      "settings": {
        "network": "tcp,udp",
        "followRedirect": true
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "streamSettings": {
        "sockopt": {
          "tproxy": "tproxy" // 透明代理使用 TPROXY 方式
        }
      }
    },
    {
      "port": 1080,
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
      "settings": {
        "auth": "noauth"
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
            {
            "address": "*****",
            "port": *****,
            "users": [
              {
                "id": "*****",
                "alterId": **
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "sockopt": {
          "mark": 255
        }
      },
      "mux": {
        "enabled": true
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP"
      },
      "streamSettings": {
        "sockopt": {
          "mark": 255
        }
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    },
    {
      "tag": "dns-out",
      "protocol": "dns",
      "streamSettings": {
        "sockopt": {
          "mark": 255
        }
      }
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8", // 非中中国大陆域名使用 Google 的 DNS
      "1.1.1.1", // 非中中国大陆域名使用 Cloudflare 的 DNS(备用)
      "114.114.114.114", // 114 的 DNS (备用)
      {
        "address": "223.5.5.5", //中国大陆域名使用阿里的 DNS
        "port": 53,
        "domains": [
          "geosite:cn",
          "ntp.org",   // NTP 服务器
        ]
      }
    ]
  },
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      { // 劫持 53 端口 UDP 流量，使用 V2Ray 的 DNS
        "type": "field",
        "inboundTag": [
          "transparent"
        ],
        "port": 53,
        "network": "udp",
        "outboundTag": "dns-out"
      },
      { // 直连 123 端口 UDP 流量（NTP 协议）
        "type": "field",
        "inboundTag": [
          "transparent"
        ],
        "port": 123,
        "network": "udp",
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": [
          // 设置 DNS 配置中的国内 DNS 服务器地址直连，以达到 DNS 分流目的
          "223.5.5.5",
          "114.114.114.114"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": [
          // 设置 DNS 配置中的国内 DNS 服务器地址走代理，以达到 DNS 分流目的
          "8.8.8.8",
          "1.1.1.1"
        ],
        "outboundTag": "proxy" 
      },
      { // 广告拦截
        "type": "field",
        "domain": [
          "geosite:category-ads-all"
        ],
        "outboundTag": "block"
      },
      { // BT 流量直连
        "type": "field",
        "protocol":["bittorrent"],
        "outboundTag": "direct"
      },
      { // 直连中国大陆主流网站 ip 和 保留 ip
        "type": "field",
        "ip": [
          "geoip:private",
          "geoip:cn"
        ],
        "outboundTag": "direct"
      },
      { // 直连中国大陆主流网站域名
        "type": "field",
        "domain": [
          "geosite:cn"
        ],
        "outboundTag": "direct"
      }
    ]
  }
}
```

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.

Server error log:

空，无error

Client error log:

client上之前未设置写log

7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.

8) Other configurations (such as Nginx) and logs.

9) If V2Ray doesn't run, please attach output from `--test`.

The command is usually `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`, but may vary according to your scenario.

10) If V2Ray service doesn't run, please attach journal log.

Usual command is `journalctl -u v2ray`.

Please review your issue before submitting.

**Comment by 1265578519** [comment]
设置10秒延迟开机启动试一下？

**Comment by youwei5683** [comment]
iptables 规则改成下面这样，白话文的规则缺了一句 
# 代理局域网设备
iptables -t mangle -N V2RAY
iptables -t mangle -A V2RAY -d 127.0.0.1/32 -j RETURN
iptables -t mangle -A V2RAY -d 224.0.0.0/4 -j RETURN 
iptables -t mangle -A V2RAY -d 255.255.255.255/32 -j RETURN 
iptables -t mangle -A V2RAY -d 192.168.0.0/16 -p tcp -j RETURN # 直连局域网，避免 V2Ray 无法启动时无法连网关的 SSH，如果你配置的是其他网段（如 10.x.x.x 等），则修改成自己的
iptables -t mangle -A V2RAY -d 192.168.0.0/16 -p udp ! --dport 53 -j RETURN # 直连局域网，53 端口除外（因为要使用 V2Ray 的 
iptables -t mangle -A V2RAY -p udp -j TPROXY --on-port 12345 --tproxy-mark 1 # 给 UDP 打标记 1，转发至 12345 端口
iptables -t mangle -A V2RAY -p tcp -j TPROXY --on-port 12345 --tproxy-mark 1 # 给 TCP 打标记 1，转发至 12345 端口
iptables -t mangle -I V2RAY -m mark --mark 0xff -j RETURN # 防止环路
iptables -t mangle -A PREROUTING -j V2RAY # 应用规则

**Comment by BlackWaters** [comment]
感谢大家回复~

我今天发现只要开启一段时间后，CPU占用率也会升上来...

我继续检查下问题，https://github.com/v2ray/v2ray-core/issues/2722#issuecomment-688574092 和 https://github.com/v2ray/v2ray-core/issues/2722#issuecomment-688106220 提供的方法我都会试下，感谢

**Comment by lostz** [comment]
在前面搭建一个dns分流插件,不要用v2ray 作为主dns.

**Comment by ring66066** [comment]
同樣的情況，只要不訪問dns就沒問題，本人用[dnsproxy](https://github.com/AdguardTeam/dnsproxy/releases)做dns上游，自己編譯一個，用cloudflare或opendns的doh，再用dnsmasq分流一下gfw域名。
