### ISSUE TITLE
Replace mKCP with kcptun

### ISSUE THREAD

**Issue by acc557** [v2ray/v2ray-core#2735]
The upstream kcptun supports many appealing features like FEC and smux , which is currently not available from mKCP.

**Comment by acc557** [comment]
Other reasons see #2530 (and #1749 #1527), #1416 and  #540

**Comment by acc557** [comment]
Also see #2253 #2131

**Comment by kslr** [comment]
Strictly speaking, it's completely different

**Comment by acc557** [comment]
True. Is there any particular strength of mKCP, compared to other KCP-based protocol like kcptun?

**Comment by kslr** [comment]
Regardless of the outcome, we all need people to work

**Comment by acc557** [comment]
Fair enough. Close for now.
