### ISSUE TITLE
2.3.3的"loglevel": "info"设置无效

### ISSUE THREAD

**Issue by wwqgtxx** [v2ray/v2ray-core#274]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please answer the following questions before submitting your issue. Thank you.

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
1) What version of V2Ray are you using?
2.3.3

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
2) What your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
正常使用

3) 你看到的不正常的现象是什么？
3) What did you see?
设置"loglevel": "info"之后并没有以前版本INFO级别的消息出现

4) 你期待看到的正确表现是怎样的？
4) What do you expected to see instead?

5) 请附上你的配置文件。
5) Please attach your configuration file.

{
  "log": {
    "loglevel": "info"
  },
....................................

**Comment by v2ray** [comment]
无法重现，请检查你的配置。

**Comment by wwqgtxx** [comment]
经过检查，已经在2.4.2版本中修复了
