### ISSUE TITLE
中转流量出错。

### ISSUE THREAD

**Issue by bbhxwl** [v2ray/v2ray-core#2742]
我中转服务器A没问题，中转服务器B就出错，

error.log如下，不知道为什么。

2020/09/22 01:26:06 [Info] [3456782988] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: Failed To Decrypt Length > cipher: message authentication failed

**Comment by Scarecrow928** [comment]
我用vmess中转流量，也遇到这个问题了，可能是版本不一致，我服务器用4.28的时候会报这个错，到4.27就不会了

**Comment by bbhxwl** [comment]
> 我用vmess中转流量，也遇到这个问题了，可能是版本不一致，我服务器用4.28的时候会报这个错，到4.27就不会了

有可能，我晚点看看版本，没注意过

**Comment by rainysia** [comment]
我也是..4.27 OK.

**Comment by kslr** [comment]
让alterid不为0

**Comment by kayoch1n** [comment]
> 我用vmess中转流量，也遇到这个问题了，可能是版本不一致，我服务器用4.28的时候会报这个错，到4.27就不会了

哎，更新的版本也不能向后兼容，只能改成跟服务器同一个版本了的

**Comment by link2022** [comment]
> 让alterid不为0

我测试 让alterid=2 .发现
 v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic
 > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header 
 > v2ray.com/core/proxy/vmess/encoding: unexpected response header. Expecting 134 but actually 44
但是我中转的v2 和 目标的代理v2  alterid 是一致的

**Comment by tian-yan** [comment]
在CentOS 8上把V2RAY当客户端用，alterid不是0， 配置(端口，UUID，服务器地址，alterID等)和服务器端一致。
试了 v2ray-linux-64.zip的4.37.3 / 4.38.3两个版本，都是出现这个错误。
>proxy/vmess/encoding: Failed To Decrypt Length > cipher: message authentication failed

如果是版本的问题，打算降级到更老的版本试试，但就是不知道怎么降级？怎么卸载当前的版本？
下面是DEBUG level的error.log输出：
```
2021/05/13 21:51:52 [Debug] app/log: Logger started
2021/05/13 21:51:52 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:1080
2021/05/13 21:51:52 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:1081
2021/05/13 21:51:52 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
2021/05/13 21:51:52 [Info] transport/internet/udp: listening UDP on 127.0.0.1:1080
2021/05/13 21:51:52 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1081
2021/05/13 21:51:52 [Warning] V2Ray 4.38.3 started
2021/05/13 21:52:03 [Info] [4152395123] proxy/http: request to Method [GET] Host [baidu.com] with URL [http://baidu.com/]
2021/05/13 21:52:03 [Info] [4152395123] app/dispatcher: default route for tcp:baidu.com:80
2021/05/13 21:52:03 [Info] [4152395123] transport/internet/tcp: dialing TCP to tcp:MY_VMESS.com:11111
2021/05/13 21:52:03 [Info] [4152395123] proxy/vmess/outbound: tunneling request to tcp:baidu.com:80 via tcp:MY_VMESS.com:11111
2021/05/13 21:52:04 [Info] [4152395123] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: Failed To Decrypt Length > cipher: message authentication failed
2021/05/13 21:52:04 [Warning] [4152395123] proxy/http: failed to read response from baidu.com > io: read/write on closed pipe
2021/05/13 21:52:04 [Info] [4152395123] app/proxyman/inbound: connection ends > proxy/http: failed to read http request > EOF
```

**Comment by tian-yan** [comment]
在配置文件中，Inbound方向配置不变，在outbound方向上，不使用VMESS协议，换成ShadowSocks协议，就正常工作了。
