### ISSUE TITLE
用任意门开放内置DNS导致UDP死循环

### ISSUE THREAD

**Issue by Yochee** [v2ray/v2ray-core#2743]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    4.18 - 4.28.2都试过了，都有问题

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    i.   路由、网关ip为192.168.1.1，没装v2ray，dnsmasq、iptables都没改过，可以认为就是个普通路由器
    ii.  在ip为192.168.1.2的windows电脑上启用v2ray，用任意门开放53端口作为本地的dns服务器。网卡设置全部默认，dns是路由器上dnsmasq通告的192.168.1.1

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
    cmd执行nslookup www.baidu.com 192.168.1.2(或者127.0.0.1)超时

4) 你期待看到的正确表现是怎样的？
    正确解析dns

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
服务器端配置:
    和服务器无关，略
客户端配置:
    只贴最简版本的，测试下来内置dns不管是用默认的localhost还是设置成别的8.8.8.8或者223.5.5.5都有这个问题。
	{
	  "inbound": {
		"port": 53,
		"protocol": "dokodemo-door",
		"settings": {
		  "address": "127.0.0.1",
		  "port": 53,
		  "network": "tcp,udp"
		}
	  },
	  "outbound": {
		"protocol": "dns"
	  }
	}

6)  请附上出错时软件输出的错误日志。
    略

7) 请附上访问日志。
    截取部分如下:
2020/09/23 09:29:43 [Info] [719753730] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54015
2020/09/23 09:29:43 127.0.0.1:54132 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54134 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 [Info] [2815480779] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54073
2020/09/23 09:29:43 127.0.0.1:54135 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54137 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 [Info] [1959868373] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54078
2020/09/23 09:29:43 127.0.0.1:54141 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54143 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54147 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54150 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54156 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 [Info] [3566513386] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54081
2020/09/23 09:29:43 [Info] [636071948] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54085
2020/09/23 09:29:43 127.0.0.1:54159 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54161 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54163 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 [Info] [530661510] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54089
2020/09/23 09:29:43 127.0.0.1:54165 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54166 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54168 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 [Info] [3584812822] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54095
2020/09/23 09:29:43 127.0.0.1:54170 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54171 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54175 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54177 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54181 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54182 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 [Info] [3743572660] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54102
2020/09/23 09:29:43 127.0.0.1:54186 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 [Info] [2583622813] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54105
2020/09/23 09:29:43 127.0.0.1:54188 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54190 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54198 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54200 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54205 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54207 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 [Info] [1170370404] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54126
2020/09/23 09:29:43 127.0.0.1:54209 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 [Info] [2043652291] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54130
2020/09/23 09:29:43 127.0.0.1:54212 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 [Info] [1006574324] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54139
2020/09/23 09:29:43 127.0.0.1:54214 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54216 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 [Info] [3098950929] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54145
2020/09/23 09:29:43 127.0.0.1:54219 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 [Info] [2478378554] v2ray.com/core/app/dispatcher: default route for udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54221 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54222 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54223 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 [Info] [842965147] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54152
2020/09/23 09:29:43 [Info] [2014117037] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54154
2020/09/23 09:29:43 127.0.0.1:54225 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54227 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54231 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54234 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54236 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54238 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54240 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54241 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54243 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54246 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54250 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54253 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 [Info] [1170161125] v2ray.com/core/app/dispatcher: default route for udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54255 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54258 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54261 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 [Info] [2699329855] v2ray.com/core/app/dispatcher: default route for udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54263 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54265 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54270 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54272 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54273 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 [Info] [1493924921] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54179
2020/09/23 09:29:43 127.0.0.1:54282 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 [Info] [1237083067] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54184
2020/09/23 09:29:43 [Info] [4128044256] v2ray.com/core/app/dispatcher: default route for udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54284 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 [Info] [2998662672] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54203
2020/09/23 09:29:43 127.0.0.1:54286 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 [Info] [896434055] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54210
2020/09/23 09:29:43 127.0.0.1:54287 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 [Info] [1834415688] v2ray.com/core/app/dispatcher: default route for udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54289 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 [Info] [3223628411] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54229
2020/09/23 09:29:43 127.0.0.1:54291 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54292 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54294 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 127.0.0.1:54296 accepted udp:127.0.0.1:53
2020/09/23 09:29:43 [Info] [3479720045] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54232
2020/09/23 09:29:43 127.0.0.1:54299 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54301 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54302 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54306 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54308 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54310 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54312 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54314 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54317 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54322 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54325 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54329 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54333 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54335 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54337 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54338 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54340 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54343 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54344 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54346 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54348 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54350 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54351 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54353 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54355 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54356 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54364 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54365 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 [Info] [3355464784] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54245
2020/09/23 09:29:44 [Info] [2936048378] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54248
2020/09/23 09:29:44 127.0.0.1:54367 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 [Info] [1074708337] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54252
2020/09/23 09:29:44 127.0.0.1:54369 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 [Info] [2501478228] v2ray.com/core/app/dispatcher: default route for udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54370 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54372 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54374 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 [Info] [1869372131] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54260
2020/09/23 09:29:44 127.0.0.1:54375 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54377 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54379 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54380 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 [Info] [1199672087] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54267
2020/09/23 09:29:44 127.0.0.1:54382 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 [Info] [1856067816] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54269
2020/09/23 09:29:44 127.0.0.1:54383 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 [Info] [883048073] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54297
2020/09/23 09:29:44 127.0.0.1:54385 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54387 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54389 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54391 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54393 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54394 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54399 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54403 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54406 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54408 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54410 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54413 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54415 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54417 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54418 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54422 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54425 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54428 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54430 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54431 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:54432 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 127.0.0.1:64560 accepted udp:127.0.0.1:53
2020/09/23 09:29:44 [Info] [771416708] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54304
2020/09/23 09:29:44 [Info] [2656911665] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54315
2020/09/23 09:29:44 [Info] [3288668046] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54318
2020/09/23 09:29:44 [Info] [3340975683] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54320
2020/09/23 09:29:44 [Info] [330887097] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54324
2020/09/23 09:29:44 [Info] [1240191123] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54327
2020/09/23 09:29:44 [Info] [4077839871] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54331
2020/09/23 09:29:44 [Info] [28534048] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54334
2020/09/23 09:29:44 [Info] [2058540048] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54341
2020/09/23 09:29:44 [Info] [4003008027] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54396
2020/09/23 09:29:44 [Info] [3031981764] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54398
2020/09/23 09:29:44 [Info] [3631717131] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54401
2020/09/23 09:29:44 [Info] [4030741645] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54404
2020/09/23 09:29:44 [Info] [2788497445] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54411
2020/09/23 09:29:44 [Info] [8378163] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54420
2020/09/23 09:29:44 [Info] [1771896267] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54423
2020/09/23 09:29:44 [Info] [2916366320] v2ray.com/core/proxy/dokodemo: received request for 127.0.0.1:54426
2020/09/23 09:29:44 [Info] v2ray.com/core/proxy/dns: ip query > lookup www.google.com.lan.: no such host
2020/09/23 09:29:46 [Info] v2ray.com/core/proxy/dns: ip query > lookup www.google.com.: no such host
2020/09/23 09:29:48 [Info] v2ray.com/core/proxy/dns: ip query > lookup www.google.com.: no such host
2020/09/23 09:29:56 [Info] [471652339] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:62461: use of closed network connection
2020/09/23 09:29:56 [Info] [3514323373] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:63101: use of closed network connection
2020/09/23 09:29:56 [Info] [3514323373] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/09/23 09:29:56 [Info] [1749393446] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:62687: use of closed network connection
2020/09/23 09:29:56 [Info] [471652339] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/09/23 09:29:56 [Info] [4275801055] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:62645: use of closed network connection
2020/09/23 09:29:56 [Info] [1749393446] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/09/23 09:29:56 [Info] [135747309] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:51555: use of closed network connection
2020/09/23 09:29:56 [Info] [914841721] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:60592: use of closed network connection
2020/09/23 09:29:56 [Info] [2352954135] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:57826: use of closed network connection
2020/09/23 09:29:56 [Info] [2916366320] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:54427: use of closed network connection
2020/09/23 09:29:56 [Info] [914841721] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/09/23 09:29:56 [Info] [2352954135] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/09/23 09:29:56 [Info] [2712518801] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:56941: use of closed network connection
2020/09/23 09:29:56 [Info] [135747309] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/09/23 09:29:56 [Info] [1273884596] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:58854: use of closed network connection
2020/09/23 09:29:56 [Info] [2712518801] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/09/23 09:29:56 [Info] [332702930] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/09/23 09:29:56 [Info] [201153177] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:60550: use of closed network connection
2020/09/23 09:29:56 [Info] [201153177] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/09/23 09:29:56 [Info] [1381336074] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:61520: use of closed network connection
2020/09/23 09:29:56 [Info] [1381336074] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/09/23 09:29:56 [Info] [1257425759] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:57709: use of closed network connection
2020/09/23 09:29:56 [Info] [1257425759] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/09/23 09:29:56 [Info] [208163987] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:52049: use of closed network connection
2020/09/23 09:29:56 [Info] [208163987] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/09/23 09:29:56 [Info] [1655710035] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:60874: use of closed network connection
2020/09/23 09:29:56 [Info] [1655710035] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/09/23 09:29:56 [Info] [3909332410] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:65294: use of closed network connection
2020/09/23 09:29:56 [Info] [3909332410] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/09/23 09:29:56 [Info] [1928601686] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:60133: use of closed network connection
2020/09/23 09:29:56 [Info] [1928601686] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/09/23 09:29:56 [Info] [3150734560] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:50046: use of closed network connection
2020/09/23 09:29:56 [Info] [3150734560] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/09/23 09:29:56 [Info] [5022292] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:60286: use of closed network connection
2020/09/23 09:29:56 [Info] [2243481689] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:52075: use of closed network connection
2020/09/23 09:29:56 [Info] [1707898239] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:50756: use of closed network connection
2020/09/23 09:29:56 [Info] [2908934553] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:64072: use of closed network connection
2020/09/23 09:29:56 [Info] [2550906538] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/09/23 09:29:56 [Info] [1975971723] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:63050: use of closed network connection
2020/09/23 09:29:56 [Info] [635799993] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:61979: use of closed network connection
2020/09/23 09:29:56 [Info] [3695452034] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:64442: use of closed network connection
2020/09/23 09:29:56 [Info] [3192222186] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:60373: use of closed network connection
2020/09/23 09:29:56 [Info] [635799993] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/09/23 09:29:56 [Info] [3695452034] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/09/23 09:29:56 [Info] [3192222186] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/09/23 09:29:56 [Info] [430587901] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:59585: use of closed network connection
2020/09/23 09:29:56 [Info] [3041388489] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:56129: use of closed network connection
2020/09/23 09:29:56 [Info] [715726939] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/dns: connection ends > read udp [::]:60404: use of closed network connection

8) 其它相关的配置文件（如 Nginx）和相关日志。
    无

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。
    略

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。
    略

**Comment by flyingbat** [comment]
+1 V2rayN更新至V2Ray-Core 4.28.2之后也会出现   127.0.0.1:5958 accepted tcp:127.0.0.1:0 [api] 之后，导致无法Proxy

**Comment by forever8938** [comment]
你贴的这个配置没有用到内置DNS，而且地址是127.0.0.1，肯定是死循环。只要把127.0.0.1改成192.168.1.1即可。

当使用内置DNS时，dokodemo里设置的地址理论上可以是127.0.0.1，但实际情况是会死循环，需要改成其他地址。这应该是个BUG。

**Comment by logic4nil** [comment]
我没有复现， 不知道为啥…

**Comment by flyingbat** [comment]
> 我没有复现， 不知道为啥…

我遇到过这种情况，是在用V2rayN更新 4.28.2的时候出现的，表现是127.0.0.1:54415 accepted tcp:127.0.0.1:53，我还原成4.27.0就没有问题了，后来我把服务器重装了最新的版本，V2rayN再更新 4.28.2就没有这个问题了

**Comment by Yochee** [comment]
> 你贴的这个配置没有用到内置DNS，而且地址是127.0.0.1，肯定是死循环。只要把127.0.0.1改成192.168.1.1即可。
> 
> ```
> {
>     "inbounds": [
>         {
>             "tag": "dns",
>             "protocol": "dokodemo-door",
>             "port": 53,
>             "settings": {
>                 "address": "192.168.1.1", // 127.0.0.1死循环，显然
>                 "port": 53,
>                 "network": "tcp,udp"
>             }
>         }
>     ],
>     "outbounds": [
>         {
>             "tag": "direct",
>             "protocol": "freedom"
>         }
>     ]
> }
> ```
> 
> 当使用内置DNS时，dokodemo里设置的地址理论上可以是127.0.0.1，但实际情况是会死循环，需要改成其他地址。这应该是个BUG。
> 
> ```
> {
>     "dns": {
>         "servers":[
>             "114.114.114.114"
>         ]
>     },
>     "inbounds": [
>         {
>             "tag": "dns",
>             "protocol": "dokodemo-door",
>             "port": 53,
>             "settings": {
>                 "address": "1.1.1.1", // 127.0.0.1死循环，why？
>                 "port": 53,
>                 "network": "tcp,udp"
>             }
>         }
>     ],
>     "outbounds": [
>         {
>             "tag": "direct",
>             "protocol": "freedom"
>         },
>         {
>             "tag": "dns",
>             "protocol": "dns"
>         }
>     ],
>     "routing": {
>         "rules": [
>             {
>                 "type": "field",
>                 "outboundTag": "dns",
>                 "inboundTag": ["dns"]
>             }
>         ]
>     }
> }
> ```

dns启用了，没贴上来。而且试了下不启用也一样有问题。
试了下把任意门的目标ip改成了8.8.8.8，没问题了，我还以为反正会被内置dns拦截这里随便填呢，看来应该不能是私有ip
