### ISSUE TITLE
安卓下 termux 环境里，如何使用 v2ray-core

### ISSUE THREAD

**Issue by shawokou123** [v2ray/v2ray-core#2746]
我之前在安卓系统里，下载 termux，然后安装privoxy再安装 shadowscoks命令行版本，既可以在  termux下 正常使用代理。

同理，如果想在 termux环境里，使用  v2ray-core，该怎么办？下载 哪个版本的  v2ray-core  ?

**Comment by dongqiceo** [comment]
你需要解决很多依赖，基本不可能

shawokou123 <notifications@github.com> 于2020年9月29日周二 上午10:28写道：

**Comment by Jaivv** [comment]
直接用透明代理就行

**Comment by nL6DHZc3RhMnC** [comment]
根据你的处理器版本，选择linux-XXX的预编译包（现在出的新手机一般都是linux-arm64-v8a），可以直接运行
但如果你是用域名去访问目标服务器的，那这个域名的dns解析会有些问题，参考下面的文章
https://github.com/v2ray/v2ray-core/issues/1909
https://github.com/fatedier/frp/issues/700
https://github.com/golang/go/issues/8877
解决方法有是用magisk提供的v2ray/使用v2ray的dokodemo-door协议或其他工具在本地53端口建立dns服务器（需root）/在termux环境自行编译v2ray
还有就是终端模拟器就已经可以运行v2ray了，不一定需要termux

**Comment by limaofu** [comment]
安卓可用 v2rayNG

**Comment by forever8938** [comment]
arm的基本都可以。建议使用entware而不是termux。

**Comment by shawokou123** [comment]
> arm的基本都可以。建议使用entware而不是termux。

entware??
