### ISSUE TITLE
4.28.2的v2ray-macos-64.zip MD5 和 v2ray-macos-64.zip.dgst不一样？

### ISSUE THREAD

**Issue by xmurobi** [v2ray/v2ray-core#2747]
在4.82.2下载的大小
Google云Linux ： 12579788 Sep 18 21:43 v2ray-macos-64.zip  
本机器MacOS ：12579788  9 29 21:47 v2ray-macos-64.zip
md5sum 均为9354821d273b2c526e9fcc1f44ec1814， 和4.28.2 v2ray-macos-64.zip.dgst里的md5 131f8511eb6dee0c6da5a912c5e08045 不同

**Comment by xmurobi** [comment]
这是什么状况？被替换了？

**Comment by kslr** [comment]
sha256sum

**Comment by xmurobi** [comment]
@kslr 
本机： sha256sum v2ray-macos-64.zip
faf15e6adf34dfe8d9908ac7668aed18ed510d5b186a0a554478cfdb3d8a8ad5  v2ray-macos-64.zip
云端：sha256sum v2ray-macos-64.zip
faf15e6adf34dfe8d9908ac7668aed18ed510d5b186a0a554478cfdb3d8a8ad5  v2ray-macos-64.zip

不一样。。。

**Comment by kslr** [comment]
这哪里不一样

**Comment by xmurobi** [comment]
MD5= 131f8511eb6dee0c6da5a912c5e08045
SHA1= db5f33608207aec78739ef4ffa489186b7cb1a21
SHA256= 18629a1453c504a954c3aa0f25f219c92a56cb54b3353411360bb5a59707edf7
SHA512= c7a138c88088a45d115a0cac29cb282dd73de966b76bf92daed340265b583e70f1a90942c90a5af324a1a3a9906f19b0862a79e51401128330bc0b3ae8febfd7

**Comment by xmurobi** [comment]
@kslr 
囧，好像弄成上次的了。。。
