### ISSUE TITLE
使用核心为4.29.0版本的v2ray遇到的问题

### ISSUE THREAD

**Issue by mcbbsandnz** [v2ray/v2ray-core#2749]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v2ray核心版本为4.29.0,v2rayn为3.23
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
v2ray的vless的tcp+tls回落模式
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
可以正常使用,但时不时会出现一个错误信息:
2020/09/30 19:58:58 [Warning] [2283692078] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vless/outbound: connection ends > v2ray.com/core/proxy/vless/outbound: failed to decode response header > v2ray.com/core/proxy/vless/encoding: failed to read response version > EOF
4) 你期待看到的正确表现是怎样的？

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:
{
"log": {
    "access": "access.log",
    "error": "error.log",
    "loglevel": "warning"
  },
    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "xxx", 
                        "level": 0,
                        "email": "xxx.com"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "alpn": "h2",
                        "dest": 80                                               
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "alpn": [
                        "h2",
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "xxx", 
                            "keyFile": "xxx" 
                        }
                    ]
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}
客户端配置:
{
  "policy": null,
  "log": {
    "access": "xxx",
    "error": "xxx",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "proxy",
      "port": 10808,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "address": null,
        "clients": null,
        "decryption": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "xxx",
            "port": 443,
            "users": [
              {
                "id": "xxx",
                "alterId": 0,
                "email": "xxx",
                "security": "auto",
                "encryption": "none"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "serverName": null
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": null,
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": false,
        "concurrency": -1
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "stats": null,
  "api": null,
  "dns": null,
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "port": null,
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "ip": null,
        "domain": null
      },
      {
        "type": "field",
        "port": null,
        "inboundTag": null,
        "outboundTag": "direct",
        "ip": null,
        "domain": [
          "xxx"
        ]
      }
    ]
  }
}
6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
服务器端错误日志:
2020/09/30 19:44:16 [Warning] [861781352] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vless/inbound: failed to find the default "alpn" config
客户端错误日志:
2020/09/30 01:33:39 [Warning] [1615685897] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vless/outbound: connection ends > v2ray.com/core/proxy/vless/outbound: failed to decode response header > v2ray.com/core/proxy/vless/encoding: failed to read response version > EOF
2020/09/30 19:58:49 [Warning] [1857284747] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vless/outbound: connection ends > v2ray.com/core/proxy/vless/outbound: failed to decode response header > v2ray.com/core/proxy/vless/encoding: failed to read response version > EOF
2020/09/30 19:58:58 [Warning] [2283692078] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vless/outbound: connection ends > v2ray.com/core/proxy/vless/outbound: failed to decode response header > v2ray.com/core/proxy/vless/encoding: failed to read response version > EOF

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
并没有错误信息
8) 其它相关的配置文件（如 Nginx）和相关日志。
nginx错误日志:
2020/09/30 19:56:49 [error] 356#0: *2 open() "/etc/nginx/html/.git/config" failed (2: No such file or directory), client: 某个ip, server: xxx.com, request: "GET /.git/config HTTP/1.1", host: "xxx.com:80"
2020/09/30 19:56:49 [error] 356#0: *4 open() "/etc/nginx/html/v2/_catalog" failed (2: No such file or directory), client: 某个ip, server: xxx.com, request: "GET /v2/_catalog HTTP/1.1", host: "xxx.com:80"
2020/09/30 19:56:49 [error] 356#0: *5 open() "/etc/nginx/html/.env" failed (2: No such file or directory), client: 某个ip, server: xxx.com, request: "GET /.env HTTP/1.1", host: "xxx.com:80"
nginx启用的网站配置:
server {
    listen 80;
    server_name xxx.com;
}
9) 如果 V2Ray 无法启动，请附上 `--test` 输出。
可以正常运行,v2ray配置经过指令判断后显示ok

请预览一下你填的内容再提交。

**Comment by rprx** [comment]
正常现象。

**Comment by mcbbsandnz** [comment]
> 正常现象。

感谢回复,但还是想请教下为什么会出现这个问题,有办法把它解决吗

**Comment by rprx** [comment]
https://www.v2fly.org/config/protocols/vless.html#%E4%B8%80%E4%BA%9B%E8%AF%B4%E6%98%8E

**Comment by mcbbsandnz** [comment]
> https://www.v2fly.org/config/protocols/vless.html#%E4%B8%80%E4%BA%9B%E8%AF%B4%E6%98%8E

感谢,对了,想问下我的服务器配置没有什么问题吧

**Comment by rprx** [comment]
回落配置存在两个问题，请自行探究。

**Comment by leopardciaw** [comment]
openwrt编译的时候出现下面错误
make[3]: *** [/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/v2ray-core-4.29.0/.built] Error 2
Makefile:308: recipe for target '/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/v2ray-core-4.29.0/.built' failed
make[2]: *** [package/small/v2ray/compile] Error 2
make[3]: Leaving directory '/workdir/openwrt/package/small/v2ray'
time: package/small/v2ray/compile#3.46#1.09#4.11
package/Makefile:111: recipe for target 'package/small/v2ray/compile' failed

不知道什么情况。

**Comment by mcbbsandnz** [comment]
> 回落配置存在两个问题，请自行探究。

对了,在尝试改了下服务端的配置后,运行了10几分钟就不会再出现原来的异常提示了,不知道是不是和我的回落配置错误有关
改过的配置:
{
    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "xxx", 
                        "level": 0,
                        "email": "xxx.com"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "alpn": "",
                        "dest": 80,                                              
                        "xver":0
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "xxx", 
                            "keyFile": "xxx" 
                        }
                    ]
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}
