### ISSUE TITLE
使用v2ray里的Shadowsocks时NAT类型为Symmetric

### ISSUE THREAD

**Issue by Rakau** [v2ray/v2ray-core#2752]
1) 你正在使用哪个版本的 V2Ray？4.30

2) 你的使用场景是什么？使用PS4和Switch进行UDP联机游戏

3) 你看到的不正常的现象是什么？连接时NAT类型为Symmetric受到联机限制无法联机

4) 你期待看到的正确表现是怎样的？NAT类型为Full Cone

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

{
    "stats": {},
    "api": {
        "tag": "api",
        "services": [
            "StatsService"
        ]
    },
    "policy": {
        "levels": {
            "0": {
                "statsUserUplink": true,
                "statsUserDownlink": true
            }
        },
        "system": {
            "statsInboundUplink": true,
            "statsInboundDownlink": true
        }
    },
    "inbounds": [
        {
            "port": 8080,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "email": "X",
                        "id": "X",
                        "flow": "xtls-rprx-origin",
                        "level": 0
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": "/dev/shm/default.sock",
                        "xver": 1
                    },
                    {
                        "alpn": "h2",
                        "dest": "/dev/shm/h2c.sock",
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "alpn": [
                        "h2",
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "/etc/v2ray/fullchain.pem",
                            "keyFile": "/etc/v2ray/privkey.pem"
                        }
                    ]
                }
            }
        },
        {
            "port": 13333,
            "protocol": "shadowsocks",
            "settings": {
                "method": "chacha20-ietf-poly1305",
                "password": "X",
                "network":"tcp,udp"
            }
        },
        {
            "listen": "127.0.0.1",
            "port": 10085,
            "protocol": "dokodemo-door",
            "settings": {
                "address": "127.0.0.1"
            },
            "tag": "api"
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {}
        }
    ],
    "routing": {
        "settings": {
            "rules": [
                {
                    "inboundTag": [
                        "api"
                    ],
                    "outboundTag": "api",
                    "type": "field"
                }
            ]
        },
        "strategy": "rules"
    },
    "dns": {
        "server": [
            "8.8.8.8",
            "localhost"
        ]
    }
}

**Comment by Rakau** [comment]
我用ss-Libev则是Fullcone，v2ray能解决这个问题吗?

**Comment by kslr** [comment]
没有该计划

**Comment by Rakau** [comment]
> 没有该计划

好的，了解了

**Comment by 1265578519** [comment]
https://github.com/v2ray/v2ray-core/issues/2616
老问题，目前还没修

**Comment by XuuKoo** [comment]
这个问题似乎是v2ray整个平台都有，用啥协议都一样。
或者你可以试试Trojan。

**Comment by ClarkeCheng** [comment]
我测得的是FullCone，就用v2ray里的SS，客户端用的是Netch
![image](https://user-images.githubusercontent.com/17330505/95614882-d8e39680-0a99-11eb-8930-a3da6ea3420d.png)
![image](https://user-images.githubusercontent.com/17330505/95615101-3a0b6a00-0a9a-11eb-8955-2acc95cac105.png)

**Comment by 1265578519** [comment]
> Netch

Netch误报，nattyoetester这款测试软件也有问题，你可以实际进游戏查看nat。

**Comment by XuuKoo** [comment]
> 我测得的是FullCone，就用v2ray里的SS，客户端用的是Netch
> ![image](https://user-images.githubusercontent.com/17330505/95614882-d8e39680-0a99-11eb-8930-a3da6ea3420d.png)
> ![image](https://user-images.githubusercontent.com/17330505/95615101-3a0b6a00-0a9a-11eb-8955-2acc95cac105.png)

用这个新版本测才是对的：
https://github.com/HMBSbige/NatTypeTester/releases/tag/3.3

**Comment by ClarkeCheng** [comment]
@1265578519 原来是这样，我用GTA5测了一下，看来我之前对v2ray太自信了

这是用v2ray里的shadowsocks
![image](https://user-images.githubusercontent.com/17330505/95642565-c427f280-0adb-11eb-87a1-13464bdae2fa.png)
这是shadowsocks-libev
![image](https://user-images.githubusercontent.com/17330505/95642363-a9a14980-0ada-11eb-9750-16a910ded9cc.png)

@XuuKoo 感谢提醒，我换了这个版本，终于发现有区别了

这是用v2ray里的shadowsocks
![image](https://user-images.githubusercontent.com/17330505/95641954-18c96e80-0ad8-11eb-819e-5c4f7c59e5a0.png)
这是shadowsocks-libev
![image](https://user-images.githubusercontent.com/17330505/95641987-48787680-0ad8-11eb-8563-3d4b17231679.png)

**Comment by XuuKoo** [comment]
> @1265578519 原来是这样，我用GTA5测了一下，看来我之前对v2ray太自信了
> 
> 这是用v2ray里的shadowsocks
> ![image](https://user-images.githubusercontent.com/17330505/95642565-c427f280-0adb-11eb-87a1-13464bdae2fa.png)
> 这是shadowsocks-libev
> ![image](https://user-images.githubusercontent.com/17330505/95642363-a9a14980-0ada-11eb-9750-16a910ded9cc.png)
> 
> @XuuKoo 感谢提醒，我换了这个版本，终于发现有区别了
> 
> 这是用v2ray里的shadowsocks
> ![image](https://user-images.githubusercontent.com/17330505/95641954-18c96e80-0ad8-11eb-819e-5c4f7c59e5a0.png)
> 这是shadowsocks-libev
> ![image](https://user-images.githubusercontent.com/17330505/95641987-48787680-0ad8-11eb-8563-3d4b17231679.png)

我最开始也是看necth和老版的nattypetester测的，发现诶是1，但是发现怎么大家都在说v2ray的udp有问题，后来才知道是测试工具的问题。再后来我发现是v2ray这个平台有问题，用啥协议udp都有问题。😂😂😂

**Comment by ClarkeCheng** [comment]
@XuuKoo 这样啊，你有测v2ray内置的trojan协议吗，我准备测一下看看支不支持FullCone

**Comment by XuuKoo** [comment]
> @XuuKoo 这样啊，你有测v2ray内置的trojan协议吗，我准备测一下看看支不支持FullCone

测过了，不支持。netch显示2（一看也是错的）。
我为了不想裸连udp，目前用的trojan-go，前置tls解密由haproxy负责。
不过另一个帖子有测试，trojan的udp发送接收效率（速度）只有v2ray的30%几。但是我感觉游戏的udp数据量不大，应该影响不大吧。

**Comment by Rakau** [comment]
> > @XuuKoo 这样啊，你有测v2ray内置的trojan协议吗，我准备测一下看看支不支持FullCone
> 
> 测过了，不支持。netch显示2（一看也是错的），实际还是4。
> 我为了不想裸连udp，目前用的trojan-go，前置tls解密由haproxy负责。
> 不过另一个帖子有测试，trojan的udp发送接收效率（速度）只有v2ray的30%几。但是我感觉游戏的udp数据量不大，应该影响不大吧。

一般联机也就1KB~几十KB不等，数据量需求不高，但有些游戏对NAT类型要求很高所以才有Fullcone的需求
