### ISSUE TITLE
使用V2ray搭的梯子，突然不能在iPad和iPhone上面翻墙了

### ISSUE THREAD

**Issue by jserm** [v2ray/v2ray-core#2756]
使用V2ray搭的梯子，突然不能在iPad和iPhone上面翻墙了，iOS系统是14，但是window PC和安卓都翻墙，测试了节点，完全正常，我测试一些免费的节点，在iPhone可以翻墙，我后面也更新了acme.sh证书，还是不行，该问题是突然出现的，以前一直好好的

**Comment by Liuhuifeng** [comment]
same issue
