### ISSUE TITLE
你好，RoutingObject的attrs不工作

### ISSUE THREAD

**Issue by 0CrazyGuy9** [v2ray/v2ray-core#2759]
{
				"type": "field",
				"attrs": "attrs[':path'].endswith('jpg')",
				"outboundTag": "res_server"
}

当访问https://xxx/xxx.jpg，没有走res_server，没有触发这条路由

**Comment by wenzhuning** [comment]
一样，我测试这个attrs路由也不起作用，作者一直没修复这个问题

**Comment by dunea** [comment]
我试的也不行，貌似是inbounds要使用http才行？
