### ISSUE TITLE
Work transferred to https://github.com/v2fly/v2ray-core

### ISSUE THREAD

**Issue by kslr** [v2ray/v2ray-core#2761]

**Comment by a1341450200** [comment]
今天试用了vless+tls之后发现比vmess+tls确实快了不少，但后面发现如果一两分钟后不打开新网页就会报错，出现 [Warning] [2421617315] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vless/inbound: failed to dial to /dev/shm/h2.sock > v2ray.com/core/common/retry: [dial unix /dev/shm/h2.sock: connect: no such file or directory] >v2ray.com/core/common/retry: all retry attempts failed
这个告警，然后让网页缓冲一会过了这个告警就好了，然后还是跟之前一样快，这是什么原因造成的

**Comment by a1341450200** [comment]
今天试用了vless+tls发现确实比vmess+tls快了不少，可是后面发现如果过一两分钟不打开新网页然后重新打开网页就会出现这个告警[Warning] [2421617315] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vless/inbound: failed to dial to /dev/shm/h2.sock > v2ray.com/core/common/retry: [dial unix /dev/shm/h2.sock: connect: no such file or directory] > v2ray.com/core/common/retry: all retry attempts failed
然后等缓冲一会过了这个告警就好了，速度也跟之前一样，不知道是什么原因造成的。

**Comment by acc557** [comment]
Try archive this repo or clear master branch and people will move :)

**Comment by yanchenyuvip** [comment]
最新版，同样都服务器，下载github文件，手机版几乎满速，电脑版最新客户端，几k/s，望尽快解决

**Comment by yanchenyuvip** [comment]
无

**Comment by yanchenyuvip** [comment]
无
