### ISSUE TITLE
Server waiting a long time for password, instead of error message

### ISSUE THREAD

**Issue by medariox** [v2ray/v2ray-core#277]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please answer the following questions before submitting your issue. Thank you.

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
1) What version of V2Ray are you using?
V2Ray v2.4.2 (One for all) 20161024

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
2) What your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
Simple connect via SOCKS5 proxy with authentication.

3) 你看到的不正常的现象是什么？
3) What did you see?
Server waiting a long time for password, although there is none provided in the request.

4) 你期待看到的正确表现是怎样的？
4) What do you expected to see instead?
An error message server side, telling me that the password is missing/wrong for the given user.

5) 请附上你的配置文件。
5) Please attach your configuration file.

```
{
  "log": {
    "loglevel": "debug"
  },
  "inbound": {
    "port": 1080,
    "listen": "0.0.0.0",
    "protocol": "socks",
    "settings": {
      "auth": "password",
      "accounts": [{"user": "myuser", "pass": "mypass"}],
      "udp": true,
      "ip": "0.0.0.0"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "v2ray.cool",
          "port": 10086,
          "users": [
            {
              "id": "23ad6b10-8d1a-40f7-8ad0-e3e35cd38297",
              "alterId": 64
            }
          ]
        }
      ]
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": "1-52",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "54-79",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "81-442",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "444-65535",
          "outboundTag": "direct"
        },
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        }
      ]
    }
  },
  "transport": {
    "kcpSettings": {
      "uplinkCapacity": 1,
      "downlinkCapacity": 10
    }
  }
}
```

This happens for the SOCKS5 protocol (with authentication) when there is an authentication attempt without a username and password or just without password provided. This causes the server to wait a long time (forever?) and the client to expect the answer (which it will never get).
I'd expect some error message returned from the server like there is right now for a missing username.

Thank you very much.

**Comment by v2ray** [comment]
A hard timeout (16 seconds) is added for socks handshake. When such case happens, V2Ray will write back an error (0xFF) and close the connection.

This change will be included in the next release (2.15)
