### ISSUE TITLE
kcp模式下页面刷新TCP中断应当立即断开当前链接的udp流量？

### ISSUE THREAD

**Issue by 1265578519** [v2ray/v2ray-core#2771]
这种问题在speedtest等测速上传的时候特别明显，测速完成后，流量还会持续跑20来秒，此时刷新页面，关闭浏览器都无效，只有在gui上点击立即重启服务器，才会进行释放连接。
早些年反映的uplinkCapacity功能不起作用，发送速率超过设定值。。也还存在呢

**Comment by k79e** [comment]
那是个老bug 20秒算好的
没给你跑个几十分钟算表现好了

**Comment by SekiBetu** [comment]
此BUG与MUX的开启有极大关联，经过一次修复后仍旧存在，建议关闭MUX功能
