### ISSUE TITLE
routing里有2个outboundTag应该怎么写？

### ISSUE THREAD

**Issue by bobwang3** [v2ray/v2ray-core#2773]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
4.31.0
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
之前按toutyrater.github.io的操作指引，在服务端加了禁止BT的功能。
后来又按guide.v2fly.org上的操作指引，在服务端加了流量统计功能。

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
这2个功能都要在routing里写outboundTag，我不知道应该怎么写。我现在只能2选1写了流量统计的outboundTag

4) 你期待看到的正确表现是怎样的？
希望同时实现禁止BT与流量统计功能。

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置: 

```javascript
    "routing": {
  	"domainStrategy": "AsIs",
    "settings": {
      "rules": [
        {
          "inboundTag": [
            "api"
          ],
          "outboundTag": "api",
          "type": "field"
          //"outboundTag": "block", （禁用BT的outboundTag block被我注释掉了）
          //"protocol": [
          //  "bittorrent"
          //]
        }
      ]
    },
    "strategy": "rules"
  }
```

客户端配置:

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by forever8938** [comment]
分开写两个rule

**Comment by bobwang3** [comment]
> 分开写两个rule

"routing": {
  	"domainStrategy": "AsIs",
    "settings": {
      "rules": [
        {
          "inboundTag": [
            "api"
          ],
          "outboundTag": "api",
          "type": "field"
        }
      ],
      "rules": [
        {
          "outboundTag": "block",
          "protocol": [
            "bittorrent"
          ]
        }
      ]
    },
    "strategy": "rules"
  }
在setting里加2个rule会无法运行

**Comment by forever8938** [comment]
哪来的settings？没有settings这一层。

**Comment by bobwang3** [comment]
> 哪来的settings？没有settings这一层。

https://guide.v2fly.org/advanced/traffic.html 这里教的

**Comment by forever8938** [comment]
写错了，要么就是过时了。以[这里](https://www.v2fly.org/config/routing.html#routingobject)为准。

**Comment by bobwang3** [comment]
> 写错了，要么就是过时了。以[这里](https://www.v2fly.org/config/routing.html#routingobject)为准。

感谢，已经处理好了。
