### ISSUE TITLE
Openwrt 无法更新到最新的版本，提示下载错误请看下！

### ISSUE THREAD

**Issue by 52nt** [v2ray/v2ray-core#2778]
=======================================================================================================
【2020年10月21日 22:14:38】: 开始检查 v2ray 最新版本。。。
【2020年10月21日 22:14:40】: 当前版本：v4.28.2
【2020年10月21日 22:14:40】: 最新版本：v4.31.0
【2020年10月21日 22:14:40】: 准备升级到最新版本，开始下载
--2020-10-21 22:14:40--  https://github.com/v2ray/v2ray-core/releases/download/v4.31.0/v2ray-linux-64.zip
Resolving github.com... 192.30.255.112
Connecting to github.com|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-21 22:14:41 ERROR 404: Not Found.

【2020年10月21日 22:14:41】: 最新版本下载失败，请检查网络到github的连通后再试！

**Comment by 52nt** [comment]
[](url)

**Comment by alexliu1009** [comment]
同样的问题，我还停留在v4.18.0,请问你是怎么解决的？
