### ISSUE TITLE
License issue of new dependency xtls library

### ISSUE THREAD

**Issue by rogers0** [v2ray/v2ray-core#2789]
I'm package maintainer of v2ray for debian/ubuntu.
- https://tracker.debian.org/golang-v2ray-core

As discussed https://github.com/XTLS/Go/issues/9
xtls is not fully licensed under open source, so we cannot maintain v2ray in debian/ubuntu anymore, except if you help to remove xtls.

I know this is not easy for you, but seems there's not much choices for maintaining this package in debian/ubuntu.
Thank you!

**Comment by rprx** [comment]
很抱歉地告知您，经过短暂的内部讨论，看起来我们只能先暂停对 debian package 的支持。

> I know this is not easy for you

Actually it's very easy.
Thank you.

**Comment by kslr** [comment]
Don't worry, let's solve this problem

**Comment by xiaokangwang** [comment]
Hi,

I am the developer and one of maintainer of V2Fly, and support the Open Source project to the furthest extent. I can help you with continuing to package V2Ray without copyright issue.

Debian version of V2Ray removes VSign with script provided in the source tree https://github.com/v2fly/v2ray-core/blob/master/release/mutilate/removeVSign.sh .  (For reason other than copyright issue.)

I could provide you a similar script to remove non-free code from V2Ray and continue to package V2Ray as a free and open source software.

Xiaokang Wang

**Comment by kslr** [comment]
根据投票结果决定移除 XTLS

**Comment by rprx** [comment]
是的，需要说明，为了避免对 v2 的非议，移除 XTLS 是我的提议，并且早就进行了投票。

我会做个 v2 的超集独自包含 XTLS，这件事也准备很久了。https://github.com/XTLS/X-ray

**Comment by kslr** [comment]
https://github.com/v2fly/v2ray-core/commit/623cb24644d5f075358c9eae4699dcbbe1409b3b

**Comment by minusmulticoloredper** [comment]
v2ray-core提供插件接口，然后把XTLS做成插件不就行了？
