### ISSUE TITLE
QR Codes for VMess

### ISSUE THREAD

**Issue by nielspeen** [v2ray/v2ray-core#279]
One of the things that makes Shadowsocks user-friendly (and popular) is the ability to use a QR Code to setup the client apps.

Is there a QR Code definition for VMess clients? If not, are you considering to create one?

**Comment by xiaokangwang** [comment]
## TL;DR Short answer:

There isn't a standardized format for QR code in V2Ray, but there will be one in the near future.

## Detailed answer

The implementation of QR code have been discussed previously.

The usage of QR code is independent from v2ray-core and it is the developer of GUI client that decide whether to support it and standardize internal format.

The developer of Actinium and I have made the decision to support QR code in a near future and I will be responsible for drafting standard.

**Comment by nielspeen** [comment]
That's good news. Thanks!

**Comment by qingyede** [comment]
like this
vmess://id:alterId@server:server_port
after // use base64 Serialization

**Comment by artingharibi** [comment]
vmess: // ID: alterId @ سرور: SERVER_PORT 
پس // استفاده از base64 ترتیب
