### ISSUE TITLE
关于v2ray的路由规则，生效是否有上下顺序的优先级？

### ISSUE THREAD

**Issue by lewisec** [v2ray/v2ray-core#280]
v2ray的配置中，有关路由部分，chinasites和chinaip两块目前的设定是"outboundTag": "direct"
如果我想让某一个国内的网站也走代理，而不是direct，应该是在route部分新建一条：
        {
          "type": "field",
          "domain": [
            "126.com",
          ],
          "outboundTag": "direct"
        },
同时，在客户端配置中
  "outboundDetour": [
    {
      "protocol": "vmess",
      "settings": {},
      "tag": "direct"
    }
  ],

如果我这个理解没有错的话，那么有两个问题。
1.服务器端的配置要不要改？怎么改？
2.126.com已经在chinasites里面了，路由部分会不会冲突？这样修改能不能起效？

预期目标：
某个指定的国内网站也走v2ray的代理，毕竟v2ray的通信是加密的，可以实现匿名性，也可以穿越公司网络的审查监管。

**Comment by v2ray** [comment]
如果你已经有一个 tag = "direct" 的 outbound 的话，新的 outbound 不能再用这个 tag，可以随意指定一个 tag，比如 "new"，只要路由中也指同样的 tag 即可。

1. 不用
2. 不冲突，有效

**Comment by lewisec** [comment]
按照前述配置后，客户端的v2ray启不来。双击运行，任务管理器看到进程名，接着消失。
我的配置如下：
{
  "log": {
    "loglevel": "warning"
  },
  "inbound": {
    "port": 1080,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    }
  },
  "outbound": {
    "protocol": "vmess",
	"streamSettings": {
	 "network": "kcp"
	 },
    "settings": {
      "vnext": [
        {
          "address": "*.*.*.*",
          "port": 5555,
          "users": [
            {
              "id": "*-*-*-*-*",
              "alterId": 64
            }
          ]
        }
      ]
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
   "outboundDetour": [
    {
      "protocol": "vmess",
      "settings": {},
      "tag": "email"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": "1-52",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "domain": "126.com",
          "outboundTag": "email"
        },
        {
          "type": "field",
          "port": "54-79",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "81-442",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "444-65535",
          "outboundTag": "direct"
        },
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        }
      ]
    }
  },
  "transport": {
    "tcpSettings": {
      "connectionReuse": true
    },
    "kcpSettings": {
      "uplinkCapacity": 8,
      "mtu": 1450,
      "tti": 50,
      "downlinkCapacity": 100,
      "congestion": true,
      "header": {
        "type": "srtp"
      }
    }
  }
}

**Comment by lewisec** [comment]
去服务器上看了下，没有报错日志。

再把服务器端的配置贴出来，请老大帮忙看看哪里错了。
{
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 5555,
    "protocol": "vmess",
    "streamsettings":{
      "network": "kcp"
    },
    "settings": {
      "clients": [
        {
          "id": "2-d-4c-b8-44",
          "level": 1,
          "alterId": 64
        }
      ],
      "features": {
        "detour": {
          "to": "detour"
        }
      }
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "inboundDetour": [
    {
      "protocol": "vmess",
      "port": "30000-31000",
      "tag": "detour",
      "settings":{},
      "streamSettings": {
      "network": "kcp"
     },
      "allocate": {
       "strategy": "random",
       "concurrency": 2,
       "refresh": 5
      }
     }
   ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  },
  "transport": {
    "tcpSettings": {
      "connectionReuse": true
    },
    "kcpSettings": {
      "uplinkCapacity": 8,
      "mtu": 1450,
      "tti": 50,
      "downlinkCapacity": 100,
      "congestion": true,
      "header": {
        "type": "srtp"
      }
    }
  }
}

**Comment by v2ray** [comment]
```
   "outboundDetour": [
    {
      "protocol": "vmess",
      "settings": {},
      "tag": "email"
    }
```

这一段里的 settings 一定要有内容的，可以参照 outbound 中的写法，留空会报错。

**Comment by lewisec** [comment]
感谢老大的耐心指导。可能是我理解有问题，加了settings内容还是会报错，进程启不来。
再贴一下新的客户端配置，麻烦再给看一看？
谢谢！
{
  "log": {
    "loglevel": "warning"
  },
  "inbound": {
    "port": 1080,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    }
  },
  "outbound": {
    "protocol": "vmess",
	"streamSettings": {
	 "network": "kcp"
	 },
    "settings": {
      "vnext": [
        {
          "address": "1.1.1.7",
          "port": 5555,
          "users": [
            {
              "id": "24-d-c-b-4",
              "alterId": 64
            }
          ]
        }
      ]
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "outboundDetour": [
    {
    "protocol": "vmess",
    "settings": {
	    "vnext": [
        {
          "address": "1.1.1.8",
          "port": 5555,
          "users": [
            {
              "id": "2-d4-4c-b8-4b74",
              "alterId": 64
            }
          ]
        }
      ]
	}
    "tag": "email"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": "1-52",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "54-79",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "81-442",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "domain": "126.com",
		  ],
          "outboundTag": "email"
        },
        {
          "type": "field",
          "port": "444-65535",
          "outboundTag": "direct"
        },
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        }
      ]
    }
  },
  "transport": {
    "tcpSettings": {
      "connectionReuse": true
    },
    "kcpSettings": {
      "uplinkCapacity": 8,
      "mtu": 1450,
      "tti": 50,
      "downlinkCapacity": 100,
      "congestion": true,
      "header": {
        "type": "srtp"
      }
    }
  }
}

**Comment by v2ray** [comment]
你可以在客户端把 loglevel 设为 info 看一下 v2ray 收到的是什么数据。如果接收到的是 IP 地址而非域名，那你配置 126.com 是无效的。另外 info 中也会显示出路由判断的过程。

**Comment by lewisec** [comment]
v2ray的info日志截图：
![sp161104_143908](https://cloud.githubusercontent.com/assets/7078444/19996854/78e21864-a29d-11e6-9ae4-659fe7b8c2d9.png)

从这里面看，没有看到有126域名的信息。我抓包看了下过程，客户端先和我的vps通信，接着http请求了126的服务器，因为126服务器在我们公司出口网关的黑名单，所以链接被网关设备断开了。
下面截图中的220.181开头的ip就是网易邮箱的服务器地址，104开头的是我的vps地址。
![sp161104_144144](https://cloud.githubusercontent.com/assets/7078444/19996884/c5f14eb8-a29d-11e6-819c-f9de14a28324.png)

我的猜想是，dns解析还是走的v2ray上配置的google的解析，但是解析出来是ip，ip指向了126的server ip，客户端直接请求服务器ip去了。
如果这个猜想是对的，那v2ray的router中，是不是就不能写
``` json
        {
          "type": "field",
          "domain": "126.com",
          "outboundTag": "email"
        },
```

是不是应该改成ip呢？具体应该怎么改？求教。

**Comment by v2ray** [comment]
你是在浏览器上用的网易邮箱？部分浏览器支持 socks5 的远程 DNS 功能，比如 Firefox： http://superuser.com/a/1072468 如果还是不行可以尝试 HTTP 代理。

如果要在路由上改，前题是你知道网易邮箱的 IP 地址或 IP 段：

```json
 {
  "type": "field",
  "ip": ["x.x.x.x", "y.y.y.y"],
  "outboundTag": "email"
},
```

其中 x.x.x.x 和 y.y.y.y 修改成网易的 IP 地址。
