### ISSUE TITLE
vless+ws+tls环境访问不了youtube

### ISSUE THREAD

**Issue by a1341450200** [v2ray/v2ray-core#2803]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
     V2Ray 4.28.2   v2ray客户端:v2ray-core 4.28.2   v2rayN-v3.27    nginx版本:1.18.0
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    使用Chrome通过ws+tls+vless方式代理观看YouTube视频
3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
    能获取自己的静态网页，但进入ws路径时显示502错误报告，无法访问YouTube
4) 你期待看到的正确表现是怎样的？
     能访问YouTube
5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
  v2ray服务端配置：
   {
"log": {
        "access": "/var/log/v2ray/access.log",
        "error": "/var/log/v2ray/error.log",
        "loglevel": "warning"
    },
  "inbounds": [
    {
      "port":1080,
      "listen": "127.0.0.1", 
      "tag": "VLESS-in", 
      "protocol": "VLESS", 
      "settings": {
        "clients": [
          {
            "id": "xx",
            "alterId": 0
          }
        ],
	    "decryption": "none"
      }, 
      "streamSettings": {
        "network": "ws", 
        "wsSettings": {
        "path":"/websocket/"
        }
      }
    }
  ], 
  "outbounds": [
    {
      "protocol": "freedom", 
      "settings": { }, 
      "tag": "direct"
    }, 
    {
      "protocol": "blackhole", 
      "settings": { }, 
      "tag": "blocked"
    }
  ], 
  "dns": {
    "servers": [
      "https+local://1.1.1.1/dns-query",
	  "1.1.1.1",
	  "1.0.0.1",
	  "8.8.8.8",
	  "8.8.4.4",
	  "localhost"
    ]
  },
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "VLESS-in"
        ],
        "outboundTag": "direct"
      }
    ]
  }
}// 在这里附上服务器端配置文件

```

客户端配置:

```javascript
   {
  "policy": null,
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "proxy",
      "port": 10808,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "address": null,
        "clients": null,
        "decryption": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "xx",
            "port": 443,
            "users": [
              {
                "id": "xx",
                "alterId": 0,
                "email": "t@t.tt",
                "security": "auto",
                "encryption": "none",
                "flow": ""
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "serverName": null
        },
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": {
          "connectionReuse": true,
          "path": "/websocket/",
          "headers": null
        },
        "httpSettings": null,
        "quicSettings": null,
        "xtlsSettings": null
      },
      "mux": {
        "enabled": false,
        "concurrency": -1
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "stats": null,
  "api": null,
  "dns": null,
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "port": null,
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "ip": null,
        "domain": null
      }
    ]
  }
} // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
   服务器错误日志和访问日志没法触发产生，以下是 journalctl -u v2ray  命令的日志
11月 25 20:31:44 localhost.localdomain v2ray[20892]: 2020/11/25 20:31:44 tcp:127.0.0.1:55284 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
11月 25 20:31:44 localhost.localdomain v2ray[20892]: 2020/11/25 20:31:44 tcp:127.0.0.1:55286 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
11月 25 20:31:45 localhost.localdomain v2ray[20892]: 2020/11/25 20:31:45 tcp:127.0.0.1:55288 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
11月 25 20:31:45 localhost.localdomain v2ray[20892]: 2020/11/25 20:31:45 tcp:127.0.0.1:55290 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
11月 25 20:31:45 localhost.localdomain v2ray[20892]: 2020/11/25 20:31:45 tcp:127.0.0.1:55292 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
11月 25 20:31:46 localhost.localdomain v2ray[20892]: 2020/11/25 20:31:46 tcp:127.0.0.1:55294 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
11月 25 20:31:46 localhost.localdomain v2ray[20892]: 2020/11/25 20:31:46 tcp:127.0.0.1:55296 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
 // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    [Warning] [761151381] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vless/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.nueye.top/websocket/): 502 Bad Gateway > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed// 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    没触发访问日志// 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。
nginx接入日志：
192.168.0.102 - - [25/Nov/2020:18:08:46 +0800] "GET /websocket/ HTTP/1.1" 502 494 "-" "Go-http-client/1.1" "-"
192.168.0.102 - - [25/Nov/2020:18:08:46 +0800] "GET /websocket/ HTTP/1.1" 502 494 "-" "Go-http-client/1.1" "-"
192.168.0.102 - - [25/Nov/2020:18:08:46 +0800] "GET /websocket/ HTTP/1.1" 502 494 "-" "Go-http-client/1.1" "-"
192.168.0.102 - - [25/Nov/2020:18:08:46 +0800] "GET /websocket/ HTTP/1.1" 502 494 "-" "Go-http-client/1.1" "-"
nginx错误日志
2020/11/25 20:35:56 [error] 13510#13510: *401 upstream prematurely closed connection while reading response header from upstream, client: 192.168.0.102, server: localhost, request: "GET /websocket/ HTTP/1.1", upstream: "http://127.0.0.1:1080/websocket/", host: "xx"
nginx配置：
http {
   map $http_upgrate $connection_upgrade{
    default upgrade;
    '' close;
     }
}
server {
        listen  443 ssl http2;
        ssl_certificate       /etc/v2ray/v2ray.crt;
        ssl_certificate_key   /etc/v2ray/v2ray.key;
        ssl_protocols         TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers           HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;
        server_name           xx;
        root                  /var/www/xx;
        index                 index.html;
        location /websocket/ { # 与 V2Ray 配置中的 path 保持一致
             proxy_redirect off;
             proxy_pass http://127.0.0.1:1080;#假设WebSocket监听在环回地址的10000端口上
             proxy_http_version 1.1;
             proxy_set_header Upgrade $http_upgrade;
             proxy_set_header Connection "upgrade";
             proxy_set_header Host $http_host;

           # Show realip in v2ray access.log
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
}
9) 如果 V2Ray 无法启动，请附上 `--test` 输出。
V2Ray 4.28.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 linux/amd64)
A unified platform for anti-censorship.
2020/11/25 20:41:48 Using config from env:  /usr/bin/v2ray/config.json
2020/11/25 20:41:48 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  /usr/bin/v2ray/config.json
Configuration OK.
通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。
11月 25 13:56:26 localhost.localdomain v2ray[4872]: 2020/11/25 13:56:26 tcp:127.0.0.1:53174 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
11月 25 13:56:28 localhost.localdomain v2ray[4872]: 2020/11/25 13:56:28 tcp:127.0.0.1:53176 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
11月 25 13:56:29 localhost.localdomain v2ray[4872]: 2020/11/25 13:56:29 tcp:127.0.0.1:53178 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
11月 25 13:59:46 localhost.localdomain v2ray[4872]: 2020/11/25 13:59:46 tcp:127.0.0.1:53180 rejected  v2ray.com/core/proxy/socks: unknown Socks version: 71
通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by rong280** [comment]
兄弟，问题解决了吗？我在电脑端也是youtube一直加载不出来，其他都可以，手机端youtube可以正常看

**Comment by kslr** [comment]
socks5 和 http 代理是不同的

**Comment by a1341450200** [comment]
> socks5和http代理是不同的
那我该如何实现nginx反代到v2ray呢，我看了官方文档用nginx实现反代也是用 proxy_pass http://127.0.0.1:1080的哦

**Comment by a1341450200** [comment]
> 兄弟，问题解决了吗？我在电脑端也是youtube一直加载不出来，其他都可以，手机端youtube可以正常看

呃，还没解决，应该是nginx的做websocket反代有问题，我看了网上nginx的websocket反代配置都是这样，我查了v2ray的端口也是运行的，就是不知道为什么连不上v2ray

**Comment by yxd0379** [comment]
> > 兄弟，问题解决了吗？我在电脑端也是youtube一直加载不出来，其他都可以，手机端youtube可以正常看
> 
> 呃，还没解决，应该是nginx的做websocket反代有问题，我看了网上nginx的websocket反代配置都是这样，我查了v2ray的端口也是运行的，就是不知道为什么连不上v2ray

根据你的客户端inbound，入栈应该是socks5://，比如
```bash
curl google.com -v --proxy socks5://127.0.0.1:10808
```
我猜可能是你的 .bashrc 配置的有问题，比如配成了 `http_proxy=http://127.0.0.1:10808` 实际应该是 `http_proxy=socks5://127.0.0.1:10808`
