### ISSUE TITLE
啟動v2ray後發現國內的所有網站正常，就是油管FB，Google等幾個上不去

### ISSUE THREAD

**Issue by hzysheep** [v2ray/v2ray-core#2804]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    -- 安裝在CentOS 8 上的当前 V2Ray 版本: v4.33.0  /  当前 V2Ray 管理脚本版本: v3.42；客戶端為：v2rayN-Core. V3.5

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
   -- 我現在香港，使用香港本地的（HKBN）網絡，本來訪問以上各網站正常，但啟用並連接v2ray後就出現了以上奇怪現象；使用時是使用Chrome / Edge 通過 Vmess 觀看youtube及訪問facebook。

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
   --但例如百度，taobao或是bing，wechat都很正常，但Whatsapp一連接就立即斷線, 而在Windows 10的客戶端上連接時可以使用Ctrl+P去查看即時ping result；以及可以看到即時的流量速度。 我的公網IP：61.92.214.xxx。

4) 你期待看到的正确表现是怎样的？

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:
---------- V2Ray 配置信息 -------------

 地址 (Address) = 61.92.214.xxx

 端口 (Port) = 233

 用户ID (User ID / UUID) = cfa7a9d6-457f-4347-a348-34635f6fd2dd

 额外ID (Alter Id) = 0

 传输协议 (Network) = tcp

 伪装类型 (header type) = none
```javascript
    // 在这里附上服务器端配置文件
```

客户端配置:

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。
[root@MiWiFi-R4A-srv ~]# journalctl -u v2ray
-- Logs begin at Wed 2020-11-25 20:53:41 CST, end at Wed 2020-11-25 23:39:55 CST. --
11月 25 20:53:55 localhost.localdomain systemd[1]: Started V2Ray Service.
11月 25 20:53:55 localhost.localdomain v2ray[1116]: V2Ray 4.33.0 (V2Fly, a communit>
11月 25 20:53:55 localhost.localdomain v2ray[1116]: A unified platform for anti-cen>
11月 25 20:53:55 localhost.localdomain v2ray[1116]: 2020/11/25 20:53:55 [Info] v2ra>

请预览一下你填的内容再提交。

**Comment by luoji111** [comment]
你好
请你参考我下面给出的原因来一一排查
1.服务器配置错误
解决方法:换一个可以用的服务器测试，如果仍然失败，请参考原因2
2.V2ray客户端配置问题
请打开你的V2ray客户端的 设置 对话框，手机客户端请先检查 分应用代理 选项，检查你的浏览器(假如你是访问的网页请检查这个)或者是其他对应应用;其次，请检查 域名设置 选项栏中的 规则 选项，查看需要访问的网页或相关应用所需要打开的网站是否在屏蔽名单上

**注意，下列情况只针对于开启并使用了局域网连接的客户端，未打开或未使用请忽略，该步骤同样适合电脑客户端**

手机客户端的最极端的设置错误情况是 局域网映射连接配置失误(仅适用于通过局域网走代理)，请检查对应的映射IP和对应的端口输入是否正确(HTTP协议在默认情况下端口请填10809)
---------------
电脑端还是按照刚才的步骤打开客户端设置，首先请检查代理模式，调整到使用http代理(全局)，然后请检查代理设置和域名规则设置即可

**Comment by wsa01378** [comment]
多为DNS污染，重新插拔一下网线或重启上网设备即可

**Comment by lyx32** [comment]
vmess协议不要裸tcp和mkcp。几乎秒挂。

**Comment by Kylejustknows** [comment]
是的! 这两天我(我在海外) 身边的朋友回国，我把我的老梯子（一个真实的公司网站服务器）升级了一下v2最新版本然后发给他用。用的是最安全方案v2+ws+tls，之前很多年跑得都正常。（专为偶尔回国情况准备的）

结果是：
服务器绝对正常（公司网页国内外都能访问）
V2 Core客户端我是打压缩包发给朋友，配置绝对正确 （同样的配置，我从国外连上v2，代理速度几百M。DNS也是走代理的）
但是国内使用，访问国内网站正常！！就是访问google等不停地断连（客户端没有做国内外分流，默认全部走代理）

一番调试和测试：
国内连接v2，没有被封，但一旦访问海外域名，就被大量干扰和中断：
服务器日志显示，大概90%的连接被rejected，有10%的数据连接成功。
在使用vmess + ws 时，显示的错误是 failed to read request header 
在使用vless + h2时，显示的错误是 failed to read request version
因为仍然有10%的数据被放过，所有如果不停地刷新google.com，刷几十次偶尔能成功访问一次。

初步结论：
墙最近几个月，有了某种升级，对海外域名和tls或request进行某种注入和攻击。（加密理论上这不应该能被做到的，但我不敢低估墙）

**Comment by alexallen1** [comment]
@Kylejustknows  东莞一切正常，你觉得地区问题的话 换多几个服 找多几个相同案例
![image](https://user-images.githubusercontent.com/79105799/118619655-612bd600-b7f7-11eb-97e6-5c35179ac521.png)
