### ISSUE TITLE
400 Bad Request > websocket: bad handshake 

### ISSUE THREAD

**Issue by holefrog** [v2ray/v2ray-core#2808]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
服务器：V2Ray 4.31.0 

客户端：
开始更新 v2rayN...
3.29 已是最新版本。
开始更新 v2rayCore...
v4.33.0 已是最新版本。

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
firefox 通过 Socks/VMess 代理观看 YouTube 视频。

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
客户端提示：
.....ay.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://70.69.20.193/): 400 Bad Request > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed

4) 你期待看到的正确表现是怎样的？
之前 ws+tls服务器，一直可以正常使用。现在希望套CloudFlare 能正常访问。
4.1)先尝试直接： ws+tls 套CF， 一直得到的是web server down 错误。如果跳过CF，直接用旧的 ws+tls服务器，一切正常。

4.2)后尝试： ws+tls+nginx 套CF
无论是否套CF，都得到：400 Bad Request > websocket: bad handshake错误

4.3)firefox 访问套CF后的域名 xxx.yyy.zzz，提示：
建立安全连接失败

连接到 xxx.yyy.zzz 时发生错误。

    由于不能验证所收到的数据是否可信，无法显示您想要查看的页面。
    建议向此网站的管理员反馈这个问题。

详细了解…

4.4) cloudflare设置
WebSocket已经打开
SSL/TLS 加密模式为 灵活

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
{
	"log": {
		"access": "/var/log/v2ray/access.log",
		"error": "/var/log/v2ray/error.log",
		"loglevel": "debug"
	},
	"inbounds": [
		{
			"port": "10086",    //同nginx上的环回地址端口保持一致
			"listen":"127.0.0.1", //只监听 127.0.0.1，避免除本机外的机器探测到开放了 10086 端口
			"tag": "vmess-inbound",
			"protocol": "vmess",
			"settings": {
				"clients": [
					{
						"id": "xxxxxx-daae-4b6c-xxxxxx-bec9c9f43eb7",
						"alterId": 256
					}
				]
			},
			"streamSettings": {
				"network": "ws",
				"security": "tls",
				"httpSettings":{
					"host": "xxxx.yyyy.zzz",
					"path": "/"
				},
				"tlsSettings": {
					"certificates": [
						{
							"certificateFile": "/etc/letsencrypt/live/xxxx.yyyy.zzz/fullchain.pem",
							"keyFile": "/etc/letsencrypt/live/xxxx.yyyy.zzz/privkey.pem"
						}
					]
				}
			}
		}
	],
	"outbounds": [
		{
			"protocol": "freedom",
			"settings": {}
		}
	],
	"dns": {
		"servers": [
			{
				"address": "x.x.x.x",
				"port": 5353,
				"domains": ["domain:v2ray.com"],
				"expectIPs": ["geoip:cn"]
			},
			"8.8.8.8",
			"8.8.4.4",
			"localhost"
		],
		"expectIPs": ["geoip:cn"]
	}
}

```

客户端配置:

```javascript
    // 在这里附上客户端配置
{
  "policy": {
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true
    }
  },
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "proxy",
      "port": 1080,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true
      }
    },
    {
      "tag": "api",
      "port": 1241,
      "listen": "127.0.0.1",
      "protocol": "dokodemo-door",
      "settings": {
        "udp": false,
        "address": "127.0.0.1"
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "x.x.x.x",
            "port": 443,
            "users": [
              {
                "id": "xxxx-daae-xxxx8f3c-bec9c9f43eb7",
                "alterId": 256,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "serverName": "xxx.yyy.zzz"
        },
        "wsSettings": {
          "path": "/",
          "headers": {
            "Host": "xxx.yyy.zzz"
          }
        }
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    }
  ],
  "stats": {},
  "api": {
    "tag": "api",
    "services": [
      "StatsService"
    ]
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api"
      }
    ]
  }
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
2020/12/08 23:47:19 [Warning] v2ray.com/core: V2Ray 4.31.0 started
2020/12/08 23:48:13 [Debug] v2ray.com/core/app/log: Logger closing
2020/12/08 23:48:21 [Debug] v2ray.com/core/app/log: Logger started
2020/12/08 23:48:21 [Info] v2ray.com/core/app/dns: DNS: created udp client inited for x.x.x.x:5353
2020/12/08 23:48:21 [Info] v2ray.com/core/app/dns: DNS: created udp client inited for 8.8.8.8:53
2020/12/08 23:48:21 [Info] v2ray.com/core/app/dns: DNS: created udp client inited for 8.8.4.4:53
2020/12/08 23:48:21 [Info] v2ray.com/core/app/dns: DNS: created localhost client
2020/12/08 23:48:22 [Debug] v2ray.com/core/app/proxyman/inbound: creating stream worker on 127.0.0.1:10086
2020/12/08 23:48:22 [Info] v2ray.com/core/transport/internet/websocket: listening TCP(for WS) on 127.0.0.1:10086
2020/12/08 23:48:22 [Warning] v2ray.com/core: V2Ray 4.31.0 started
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
  日志空白
```

8) 其它相关的配置文件（如 Nginx）和相关日志。
nginx.conf内容如下：
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 768;
	# multi_accept on;
}

http {
    server_tokens off;
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 120s;
    keepalive_requests 10000;
    types_hash_max_size 2048;
    include /etc/nginx/mime.types;

    access_log off;
    error_log /dev/null;

    server {
        listen 80;
        listen [::]:80;
        server_name xxx.yyy.zzz;

        location / {
            proxy_redirect off;
            proxy_pass http://127.0.0.1:10086;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $http_host;
        }
    }

    server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;      
        server_name xxx.yyy.zzz;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
        ssl_prefer_server_ciphers on;
        ssl_certificate /etc/letsencrypt/live/xxx.yyy.zzz/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/xxx.yyy.zzz/privkey.pem;
        location / {
            proxy_redirect off;
            proxy_pass http://127.0.0.1:10086;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by holefrog** [comment]
如果直接访问VPS的ip： 
1） http://vpsip
结果是：
The webpage cannot be found
 
  HTTP 400 
    
Most likely causes:
•There might be a typing error in the address.
•If you clicked on a link, it may be out of date.
 
What you can try:    

  Retype the address.  
  Go back to the previous page.  
   Go to  and look for the information you want.  
 
More information  More information   
This error (HTTP 400 Bad Request) means that Internet Explorer was able to connect to the web server, but the webpage could not be found because of a problem with the address.

For more information about HTTP errors, see Help.
 

2） https://vpsip
结果是：

This site is not secure
This might mean that someone’s trying to fool you or steal any info you send to the server. You should close this site immediately.
Recommended iconClose this tab

More information  More information  

The hostname in the website’s security certificate differs from the website you are trying to visit. 
Error Code: DLG_FLAGS_SEC_CERT_CN_INVALID

Not recommended iconGo on to the webpage (not recommended)

**Comment by holefrog** [comment]
过去不套CF时，ws+tls用的是免费域名aaa.bbb.ccc。
因为套CF要更新原来域名的name servers，原免费域名不能修改name servers。因此，重新申请了新的域名xxx.yyy.zzz ，并为此域名重新申请了Let's Encrypt的证书。
套CF后，在https://www.ssllabs.com/ssltest/analyze.html检查证书结果，Grade全是B级。

**Comment by holefrog** [comment]
重启vps后，访问youtube时，客户端显示错误： 
502 Bad Gateway > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed

直接访问域名：
 Error 502 Ray ID: 31290b78b2b1fd1 • 2020-12-09 09:05:36 UTC
Bad gateway

Host Error

**Comment by kslr** [comment]
502  Bad gateway

**Comment by holefrog** [comment]
> 
> 
> 502 Bad gateway

是呀。很奇怪，会是什么问题？研究了半天配置

**Comment by kslr** [comment]
https://guide.v2fly.org/advanced/wss_and_web.html#%E9%85%8D%E7%BD%AE

**Comment by holefrog** [comment]
> 
> 
> https://guide.v2fly.org/advanced/wss_and_web.html#%E9%85%8D%E7%BD%AE

非常感谢，按照这个重新配置了一下。去掉了v2ray服务器中的TLS就可以了。
