### ISSUE TITLE
http的inboud能否加入wpad支持

### ISSUE THREAD

**Issue by Darren** [v2ray/v2ray-core#282]
wpad虽然安全上有些问题，但是自己受控范围内使用还是很方便的
如果v2ray直接支持wpad, 就免去再安装一个另外http服务的麻烦了

**Comment by v2ray** [comment]
你是指 Pac 文件，还是完整的 WPAD 实现？

**Comment by v2ray** [comment]
moved to https://github.com/v2ray/Planning/issues/10.
