### ISSUE TITLE
Package V2ray for Guix

### ISSUE THREAD

**Issue by musicsd** [v2ray/v2ray-core#2820]
Please package this app for Guix. Because Guix System is different from other systems, it is better for developers to package this program for Guix. Thanks

**Comment by kslr** [comment]
Would you like to help add?

**Comment by musicsd** [comment]
> Would you like to help add?

I do not know much about this program, it is better that you and developers package it.

**Comment by musicsd** [comment]
It is good that this program is available in Guix packages, because this program (V2ray) is very good and many users need it.

**Comment by kslr** [comment]
Sorry, We don't have the plan

**Comment by musicsd** [comment]
I will package it in the future...
