### ISSUE TITLE
在qv2ray和v2ray更新之后出现了报错并且v2ray核心启动错误问题

### ISSUE THREAD

**Issue by Un-KnownCode** [v2ray/v2ray-core#2827]
qv2ray和v2ray更新了之后，在qv2ray里面连接节点，报错显示
2021/01/23 13:34:45 [Info] v2ray.com/core/main/jsonem: Reading config: /home/unknowncode/.config/qv2ray/generated/config.gen.json
main: failed to read config files: [/home/unknowncode/.config/qv2ray/generated/config.gen.json] > v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to load geoip: private > v2ray.com/core/infra/conf: country not found in geoip.dat: private

这好像两个都相关，可能是qv2ray的问题？接着我去qv2ray里面问大佬们，给出的解决方法是换一下v2ray的geoip.dat文件，我换了之后出现了新的报错

2021/01/23 15:47:07 [Info] v2ray.com/core/main/jsonem: Reading config: /home/unknowncode/.config/qv2ray/generated/config.gen.json

main: failed to read config files: [/home/unknowncode/.config/qv2ray/generated/config.gen.json] > v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to parse domain rule: geosite:cn > v2ray.com/core/infra/conf: failed to load geosite: cn > unexpected EOF

本来想返回qv2ray那边回复大佬们的，结果那边突然锁项目了，只能可见，不能评论提问题了
所以我过来这边问问大佬们，这是怎么回事，怎么解决

**Comment by Un-KnownCode** [comment]
v2ray版本:4.34.0-1 qv2ray版本:2.6.3-12
系统是archlinux

**Comment by kslr** [comment]
你的数据文件大概坏了

p.s 这里也是不处理 issue
