### ISSUE TITLE
女小白，求神助 ！V2Ray: outbound: failed to find an available destination 还有 v2ray.com/core/common/retry: all retry attempts failed

### ISSUE THREAD

**Issue by sky20-20** [v2ray/v2ray-core#2829]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
      v2rayN- V3.28-2020/11/29

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
      用google 查询资料和youtube

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
      V   P      N 上不去，全局模式下可以上QQ，但是打不开google, 也打不开百度。
        自动的情况下，可以上百度。

4) 你期待看到的正确表现是怎样的？
    可以上google.

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

   我的错误日志：v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > 
v2ray.com/core/proxy/vmess/outbound: failed to find an available destination >
 v2ray.com/core/common/retry: [dial tcp 66 XX XX: operation was canceled] >
 v2ray.com/core/common/retry: all retry attempts failed

(6) 看了一个帖子上面写问起原因，让其运行命令 tracert <你的服务器IP>（举例：tracert 8.8.8.8），运行完成后 把输出的内容以文字的形式贴出来。前5行输出内容请略去，从第6行往下全贴出来。
我就运行一下，将第5行贴出。

 5     9 ms    11 ms     9 ms  111.24.10.109
  6    47 ms    40 ms    33 ms  111.24.4.169
  7    41 ms    40 ms    41 ms  221.176.22.106
  8    49 ms    43 ms    35 ms  221.183.25.117
  9    51 ms    51 ms    53 ms  221.183.55.53
 10   210 ms   208 ms   216 ms  223.120.12.41
 11   225 ms   212 ms   228 ms  223.120.6.70
 12   687 ms   662 ms   639 ms  38.88.224.161
 13   413 ms     *      348 ms  be3359.ccr42.lax01.atlas.cogentco.com [154.54.3.69]
 14   233 ms   254 ms   255 ms  be3177.ccr42.lax01.atlas.cogentco.com [154.54.40.145]
 15   228 ms   222 ms   217 ms  multacom-corp.demarc.cogentco.com [38.99.219.58]
 16   242 ms     *      203 ms  asr1.be2-704.multacom.com [72.44.66.202]
 17     *        *        *     请求超时。
 18     *        *        *     请求超时。
 19     *        *        *     请求超时。
 20     *        *        *     请求超时。
 21     *        *        *     请求超时。
 22     *        *        *     请求超时。
 23     *        *        *     请求超时。
 24     *        *        *     请求超时。
 25     *        *        *     请求超时。
 26     *        *        *     请求超时。
 27     *        *        *     请求超时。
 28     *        *        *     请求超时。
 29     *        *        *     请求超时。
 30     *        *        *     请求超时。

我，一个女小白，通过youtube的视频搭建一个梯子就是想用google 查询资料而已，上个月搭建好了，可以上google，不知道为啥，这次打开V2ray，使用不了了，我不知道有什么问题？是封了嘛？ 上个月刚买的线路，还没开始使用呢，求大神帮忙指导，该如何操作可以继续使用？

**Comment by kslr** [comment]
please move to https://github.com/v2fly/v2ray-core/discussions, and add logs
