### ISSUE TITLE
common/serial/typed_message.proto 无法编译

### ISSUE THREAD

**Issue by nickfox-taterli** [v2ray/v2ray-core#2836]
Using the latest version protoc does not compile.

> common/serial/typed_message.proto: File not found.
v2ray.com/core/common/protocol/user.proto:9:1: Import "common/serial/typed_message.proto" was not found or had errors.
v2ray.com/core/common/protocol/user.proto:18:3: "v2ray.core.common.serial.TypedMessage" seems to be defined in "v2ray.com/core/common/serial/typed_message.proto", which is not imported by "v2ray.com/core/common/protocol/user.proto".  To use it here, please add the necessary import.

I would like to know what is the reason for this?

**Comment by kslr** [comment]
https://www.v2fly.org/en_US/developer/intro/compile.html#pre-work
