### ISSUE TITLE
source配置解析代码错误

### ISSUE THREAD

**Issue by fax001** [v2ray/v2ray-core#285]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please answer the following questions before submitting your issue. Thank you.

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
1) What version of V2Ray are you using?
2.5.1

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
2) What your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

3) 你看到的不正常的现象是什么？
3) What did you see?
source配置加载不正常

4) 你期待看到的正确表现是怎样的？
4) What do you expected to see instead?

5) 请附上你的配置文件。
5) Please attach your configuration file.

goroutine 1 [running]:
panic(0x7c1f20, 0xc4200120e0)
	/home/travis/.gimme/versions/go1.7.3.linux.amd64/src/runtime/panic.go:500 +0x1a1
v2ray.com/core/tools/conf.parseFieldRule(0xc42000fa20, 0x149, 0x160, 0x5, 0xc4214fa601, 0x0)
	/home/travis/gopath/src/v2ray.com/core/tools/conf/router.go:155 +0x330
v2ray.com/core/tools/conf.ParseRule(0xc42000fa20, 0x149, 0x160, 0xc421488200)
	/home/travis/gopath/src/v2ray.com/core/tools/conf/router.go:181 +0x615
v2ray.com/core/tools/conf.(*RouterConfig).Build(0xc420024040, 0xc4214fe570, 0x289, 0xc4214f75d7)
	/home/travis/gopath/src/v2ray.com/core/tools/conf/router.go:42 +0x138
v2ray.com/core/tools/conf.(*Config).Build(0xc420048150, 0x7bbe00, 0xc420048150, 0x0)
	/home/travis/gopath/src/v2ray.com/core/tools/conf/v2ray.go:263 +0x8fe
v2ray.com/core/tools/conf.init.2.func1(0x9fc740, 0xc420024038, 0x1, 0xc420048110, 0x83a701)
	/home/travis/gopath/src/v2ray.com/core/tools/conf/v2ray.go:322 +0x1ca
v2ray.com/core.LoadConfig(0x7ffd00000001, 0x9fc740, 0xc420024038, 0x0, 0x0, 0x29)
	/home/travis/gopath/src/v2ray.com/core/config_loader.go:26 +0x6e
main.startV2Ray(0x0)
	/home/travis/gopath/src/v2ray.com/core/main/main.go:62 +0x248
main.main()
	/home/travis/gopath/src/v2ray.com/core/main/main.go:97 +0x45

![sp20161109_122733](https://cloud.githubusercontent.com/assets/1317574/20127277/e6eebf00-a677-11e6-8962-1eff0c7e4a04.png)

**Comment by v2ray** [comment]
已修复，见 https://github.com/v2ray/v2ray-core/releases/tag/v2.5.2
