### ISSUE TITLE
Add Multiplex Websocket Support

### ISSUE THREAD

**Issue by layonhands** [v2ray/v2ray-core#2852]
The actual Vmess Websocket is already being accurately detected and blocked, since March 2021.

Is there any plan to support Multiplex WebSocket in Vmess in near future?
Right now a lot on Vmess websocket is being detected, but Vmess Websocket seens very good, and not touched.

Adding this could be good idea for a while.

Cheers

**Comment by onoketa** [comment]
That means very long WebSocket connections, maybe easier to identify?
