### ISSUE TITLE
一帮反社会的智障份子

### ISSUE THREAD

**Issue by Mistofs** [v2ray/v2ray-core#2853]
反正这个project已经死了吧

**Comment by HybridGaw** [comment]
项目死了？转xray了？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "v2ray/v2ray-core"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月22日(星期一) 凌晨5:17
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[v2ray/v2ray-core] 一帮反社会的智障份子 (#2853)





 
反正这个project已经死了吧
