### ISSUE TITLE
systemctl 启动v2ray 失败，命令行启动正常。。。

### ISSUE THREAD

**Issue by JohyC** [v2ray/v2ray-core#2862]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

V2Ray 4.36.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16 linux/arm)

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

Linux 服务端啊启动失败

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

命令行启动v2ray正常，--test测试正常。但使用systemctl 无法启动；

4) 你期待看到的正确表现是怎样的？

期待 systemctl 在后台启动v2ray

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
{
    "log": {
        "access": "/var/log/v2ray/v2ray-access.log",
        "error": "/var/log/v2ray/v2ray-error.log",
        "loglevel": "warning"
    },
    "inbound": {
        "port": 65535,
        "protocol": "vmess",
        "listen": "0.0.0.0",
        "settings": {
            "ip": null,
            "udp": true,
            "clients": [
                {
                    "alterId": 64,
                    "security": "auto",
                    "id": "447ef0f9-8db3-47e0-b4c4-1369e8f39652"
                }
            ],
            "auth": null
        },
        "streamSettings": {
            "network": "ws",
            "kcpSettings": null,
            "wsSettings": {
                "connectionReuse": true,
                "path": "/"
            },
            "tcpSettings": null,
            "tlsSettings": {},
            "security": "none"
        }
    },
    "outbound": {
        "protocol": "freedom",
        "settings": {}
    },
    "routing": {
        "strategy": "rules",
        "settings": {
            "rules": [
                {
                    "type": "field",
                    "ip": [
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "203.0.113.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10"
                    ],
                    "outboundTag": "blocked"
                }
            ]
        }
    }
}
```

客户端配置:

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    ● v2ray.service - V2Ray Service
     Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/v2ray.service.d
             └─10-donot_touch_single_conf.conf
     Active: failed (Result: exit-code) since Thu 2021-04-08 17:31:18 CST; 4s ago
       Docs: https://www.v2fly.org/
    Process: 4685 ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json (code=exited, status=23)
   Main PID: 4685 (code=exited, status=23)

Apr 08 17:31:18 Armbian systemd[1]: Started V2Ray Service.
Apr 08 17:31:18 Armbian v2ray[4685]: V2Ray 4.36.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16 linux/ar>
Apr 08 17:31:18 Armbian v2ray[4685]: A unified platform for anti-censorship.
Apr 08 17:31:18 Armbian v2ray[4685]: 2021/04/08 17:31:18 [Info] github.com/v2fly/v2ray-core/v4/main/jsonem: Reading con>
Apr 08 17:31:18 Armbian v2ray[4685]: main: failed to create server > github.com/v2fly/v2ray-core/v4/app/log: failed to >
Apr 08 17:31:18 Armbian systemd[1]: v2ray.service: Main process exited, code=exited, status=23/n/a
Apr 08 17:31:18 Armbian systemd[1]: v2ray.service: Failed with result 'exit-code'.
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

Apr 08 17:18:19 Armbian systemd[1]: Started V2Ray Service.
Apr 08 17:18:19 Armbian v2ray[4439]: V2Ray 4.36.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16 linux/ar>
Apr 08 17:18:19 Armbian v2ray[4439]: A unified platform for anti-censorship.
Apr 08 17:18:19 Armbian v2ray[4439]: 2021/04/08 17:18:19 [Info] github.com/v2fly/v2ray-core/v4/main/jsonem: Reading con>
Apr 08 17:18:19 Armbian v2ray[4439]: main: failed to create server > github.com/v2fly/v2ray-core/v4/app/log: failed to >
Apr 08 17:18:19 Armbian systemd[1]: v2ray.service: Main process exited, code=exited, status=23/n/a
Apr 08 17:18:19 Armbian systemd[1]: v2ray.service: Failed with result 'exit-code'.

**Comment by Cwek** [comment]
> main: failed to create server > github.com/v2fly/v2ray-core/v4/app/log: failed to >

右边还有什么内容？

**Comment by JohyC** [comment]
> > main: failed to create server > github.com/v2fly/v2ray-core/v4/app/log: failed to >
> 
> 右边还有什么内容？

抱歉了 ！此 Issues 可以close了。我重做了系统后解决了此问题，虽然还是不知问题出在哪里。
目前v2ray已经正常使用，并无异状。

**Comment by szdosar** [comment]
可能是权限问题，
要把/etc/systemd/system/v2ray.service
[Service]
User=nobody
里的nobody改成root
systemctl restart v2ray
