### ISSUE TITLE
v2ray突然不能使用

### ISSUE THREAD

**Issue by oha002** [v2ray/v2ray-core#2864]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

答：v2rayN4.22.1懒人包

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

答：正常使用，上脸书看推特都是使用V2

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

答：我知道怎么使用V2，但有一天突然不能连接
4) 你期待看到的正确表现是怎样的？

答：能连接也就是能翻墙

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
配置成功
Vmess-Australia (au-1-fast***com:301)
启动服务(2021/4/21 11:39:11)......
V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 windows/amd64)
A unified platform for anti-censorship.
main: failed to load config: C:\Users\AppData\Local\Temp\Rar$EXa11392.15763\v2rayN\config.json > v2ray.com/core/main/confloader/external: config file not readable > open C:\Users\CZT\AppData\Local\Temp\Rar.15763\v2rayN\config.json: The system cannot find the path specified.

网速显示为启用

其余的太专业我不知道如何操作。如果方便请截图说明步骤。谢谢

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
```

客户端配置:

```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by oha002** [comment]
why  be  closed?

**Comment by oha002** [comment]
why be closed?

Kslr ***@***.***> 于2021年4月21日周三 下午1:31写道：

**Comment by Cwek** [comment]
这是**v2rayN**或者对应懒人包制作方的问题？

看上去是对应配置文件没生产好，导致v2ray加载不了？

**Comment by oha002** [comment]
但是，我原来能用V2翻墙的啊，怎么突然不能翻墙了？你说的错误日志服务器配置我也不知道如何检查

Cwek ***@***.***> 于2021年4月21日周三 下午5:44写道：

**Comment by Cwek** [comment]
```
C:\Users\AppData\Local\Temp\Rar$EXa11392.15763\v2rayN\config.json
````
怪不得会被秒关，看到这个，大概猜到你这个懒人包是一个rar包，然后你直接在rar打开程序吧？

至少先把这个rar解压缩出来，可能里面有个config.json的文件，请按照你原来的配置，参考v2fly上的配置文档来写改好，然后再启动程序。

**Comment by oha002** [comment]
怪不得会被秒关，看到这个，大概猜到你这个懒人包是一个rar包，然后你直接在rar打开程序吧？至少先把这个rar解压缩出来
---------我已经按右键选择解压缩文件


可能里面有个config.json的文件，请按照你原来的配置，参考v2fly上的配置文档来写改好，然后再启动程序。
-----------这怎么改？我不是计算机专业出身，对我来说太难了。谢谢
{
  "policy": null,
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "proxy",
      "port": 10808,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "address": null,
        "clients": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "au-1-fast.teacher2050.com",
            "port": 301,
            "users": [
              {
                "id": "5FED9484-FD25-7725-5673-512B20B7F8BD",
                "alterId": 0,
                "email": ***@***.***",
                "security": "auto"
              }
            ]
          }
        ],
        "servers": null,
        "response": null
      },
      "streamSettings": {
        "network": "tcp",
        "security": null,
        "tlsSettings": null,
        "tcpSettings": null,
        "kcpSettings": null,
        "wsSettings": null,
        "httpSettings": null,
        "quicSettings": null
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": null
      },
      "streamSettings": null,
      "mux": null
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "vnext": null,
        "servers": null,
        "response": {
          "type": "http"
        }
      },
      "streamSettings": null,
      "mux": null
    }
  ],
  "stats": null,
  "api": null,
  "dns": null,
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "port": null,
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "ip": null,
        "domain": null
      }
    ]
  }
}

Cwek ***@***.***> 于2021年4月22日周四 上午11:09写道：
