### ISSUE TITLE
Openwrt 配置透明代理无法正确处理UDP数据

### ISSUE THREAD

**Issue by liang7878** [v2ray/v2ray-core#2875]
Openwrt配置透明代理无法正确处理UDP数据，client配置文件如下
···
{
	"log": {
		"access": "/var/log/v2ray-access.log",
		"loglevel": "debug",
		"error": "/var/log/v2ray-error.log"
	},
	"stats": {
		
	},
	"dns": {
		"hosts": {
			"example.com": "127.0.0.1"
		},
		"servers": [
			"8.8.8.8",
			"1.1.1.1",
			"114.114.114.114",
			{
				"address": "223.5.5.5",
				"port": 53,
				"domains": [
					"geosite:cn",
					"ntp.org",
					"<VPS_host>"
				]
			}
		]
	},
	"routing": {
		"domainStrategy": "IPOnDemand",
		"rules": [
			{
				"type": "field",
				"port": "53",
				"network": "udp",
				"inboundTag": [
					"transparent"
				],
				"outboundTag": "dns-out"
			},
			{
				"type": "field",
				"port": "123",
				"network": "udp",
				"inboundTag": [
					"transparent"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"ip": [
					"223.5.5.5",
					"114.114.114.114"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"ip": [
					"8.8.8.8",
					"1.1.1.1"
				],
				"outboundTag": "v2ray"
			},
			{
				"type": "field",
				"domain": [
					"geosite:category-ads-all"
				],
				"outboundTag": "block"
			},
			{
				"type": "field",
				"protocol": [
					"bittorrent"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"ip": [
					"geoip:private",
					"geoip:cn"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"domain": [
					"geosite:cn"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"network": "tcp,udp",
				"protocol": [
					"http",
					"tls"
				],
				"outboundTag": "v2ray"
			}
		]
	},
	"inbounds": [
		{
			"listen": "0.0.0.0",
			"port": 1081,
			"protocol": "dokodemo-door",
			"settings": {
				"followRedirect": true,
				"network": "tcp,udp"
			},
			"streamSettings": {
				"sockopt": {
					"tproxy": "tproxy"
				}
			},
			"tag": "transparent",
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			},
			"allocate": {
				"strategy": "always"
			}
		},
		{
			"port": 1080,
			"protocol": "socks",
			"settings": {
				"auth": "noauth",
				"udp": false
			},
			"streamSettings": {
				"sockopt": {
					
				}
			},
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			}
		}
	],
	"outbounds": [
		{
			"protocol": "freedom",
			"settings": {
				"domainStrategy": "UseIP"
			},
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			},
			"tag": "direct"
		},
		{
			"protocol": "blackhole",
			"settings": {
				"response": {
					"type": "http"
				}
			},
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			},
			"tag": "block"
		},
		{
			"protocol": "vmess",
			"settings": {
				"vnext": [
					{
						...
					}
				]
			},
			"streamSettings": {
				"network": "tcp",
				"security": "tls",
				"tlsSettings": {
					"allowInsecure": false,
					"allowInsecureCiphers": false,
					"disableSystemRoot": false,
					"certificates": [
						
					]
				},
				"tcpSettings": {
					"header": {
						"type": "none"
					}
				},
				"sockopt": {
					"mark": 255
				}
			},
			"tag": "v2ray",
			"mux": {
				"enabled": true,
				"concurrency": 8
			}
		},
		{
			"protocol": "dns",
			"settings": {
				
			},
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			},
			"tag": "dns-out"
		}
	]
}

···

error log 如下，看起来DNS已经成功解析更新失败
```
2021/05/18 02:24:34 [Debug] app/dns: UDP:8.8.8.8:53 querying DNS for: fonts.gstatic.com.
2021/05/18 02:24:34 [Debug] transport/internet/udp: dispatch request to: udp:8.8.8.8:53
2021/05/18 02:24:34 [Debug] transport/internet/udp: UDP original destination: udp:8.8.8.8:53
2021/05/18 02:24:34 [Debug] [4277390126] proxy/dokodemo: processing connection from: 192.168.1.2:31608
2021/05/18 02:24:34 [Info] [4277390126] proxy/dokodemo: received request for 192.168.1.2:31608
2021/05/18 02:24:34 [Info] [4277390126] app/dispatcher: taking detour [dns-out] for [udp:8.8.8.8:53]
2021/05/18 02:24:34 [Info] [4277390126] proxy/dns: handling DNS traffic to udp:8.8.8.8:53
2021/05/18 02:24:34 [Debug] app/dns: domain www.gstatic.com will use DNS in order: [UDP:8.8.8.8:53 UDP:1.1.1.1:53 UDP:114.114.114.114:53 UDP:223.5.5.5:53]
2021/05/18 02:24:34 [Debug] app/dns: UDP:8.8.8.8:53 querying DNS for: www.gstatic.com.
2021/05/18 02:24:34 [Debug] transport/internet/udp: dispatch request to: udp:8.8.8.8:53
2021/05/18 02:24:34 [Info] app/dns: UDP:8.8.8.8:53 got answer: www.google.com. TypeA -> [172.217.26.132] 34.740769ms
2021/05/18 02:24:34 [Debug] app/dns: UDP:8.8.8.8:53 updating IP records for domain:www.google.com.
2021/05/18 02:24:34 [Info] app/dns: UDP:8.8.8.8:53 got answer: fonts.gstatic.com. TypeA -> [172.217.26.131] 33.608982ms
2021/05/18 02:24:34 [Debug] app/dns: UDP:8.8.8.8:53 updating IP records for domain:fonts.gstatic.com.
2021/05/18 02:24:34 [Info] app/dns: UDP:8.8.8.8:53 got answer: www.gstatic.com. TypeA -> [172.217.31.227] 34.610353ms
2021/05/18 02:24:34 [Debug] app/dns: UDP:8.8.8.8:53 updating IP records for domain:www.gstatic.com.
2021/05/18 02:24:41 [Info] transport/internet/udp: failed to handle UDP input > EOF
2021/05/18 02:24:49 [Info] common/mux: failed to read metadata > io: read/write on closed pipe
2021/05/18 02:24:50 [Info] failed to handler mux client connection > proxy/vmess/outbound: connection ends > context canceled
```

已验证过不存在时间不同步的问题，请教各位大佬有什么idea？

**Comment by liang7878** [comment]
拉了一下server端的log
```
2021/05/20 15:49:21 [Info] [553632714] v2ray.com/core/common/mux: received request for udp:8.8.8.8:53
2021/05/20 15:49:21 [Info] [553632714] v2ray.com/core/app/dispatcher: default route for udp:8.8.8.8:53
2021/05/20 15:49:21 [Info] [553632714] v2ray.com/core/proxy/freedom: opening connection to udp:8.8.8.8:53
2021/05/20 15:49:30 [Info] [553632714] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
2021/05/20 15:49:30 [Info] [553632714] v2ray.com/core/common/mux: session 1 ends. > io: read/write on closed pipe
2021/05/20 15:49:38 [Info] [553632714] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > context canceled
```

**Comment by peterwillcn** [comment]
any news
