### ISSUE TITLE
v2ray服务端产生错误退出

### ISSUE THREAD

**Issue by ToutyRater** [v2ray/v2ray-core#289]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please answer the following questions before submitting your issue. Thank you.

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
1) What version of V2Ray are you using?
服务器 v2.5.2；客户端 actinium 0.6.1，这个版本的v2ray-core应该是2.2.1
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
2) What your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
在手机上通过actinium使用chrome浏览器上网
3) 你看到的不正常的现象是什么？
3) What did you see?
突然间上不了网，检查发现服务器的v2ray遭退出。退出时日志：
> Nov 13 08:25:37 localhost v2ray[457]: panic: runtime error: slice bounds out of range
Nov 13 08:25:37 localhost v2ray[457]: goroutine 685868 [running]:
Nov 13 08:25:37 localhost v2ray[457]: panic(0x7c1f60, 0xc42000e090)
Nov 13 08:25:37 localhost v2ray[457]: /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/runtime/panic.go:500 +0x1a1
Nov 13 08:25:37 localhost v2ray[457]: v2ray.com/core/proxy/shadowsocks.ReadTCPSession(0xc4218fd8a0, 0x9fcfc0, 0xc427868ea0, 0x0, 0x0, 0x0, 0x0, 0x0)
Nov 13 08:25:37 localhost v2ray[457]: /home/travis/gopath/src/v2ray.com/core/proxy/shadowsocks/protocol.go:89 +0x1298
Nov 13 08:25:37 localhost v2ray[457]: v2ray.com/core/proxy/shadowsocks.(*Server).handleConnection(0xc4200115e0, 0xa06fe0, 0xc42785bf00)
Nov 13 08:25:37 localhost v2ray[457]: /home/travis/gopath/src/v2ray.com/core/proxy/shadowsocks/server.go:157 +0x1e7
Nov 13 08:25:37 localhost v2ray[457]: v2ray.com/core/proxy/shadowsocks.(*Server).(v2ray.com/core/proxy/shadowsocks.handleConnection)-fm(0xa06fe0, 0xc42785bf00)
Nov 13 08:25:37 localhost v2ray[457]: /home/travis/gopath/src/v2ray.com/core/proxy/shadowsocks/server.go:85 +0x3e
Nov 13 08:25:37 localhost v2ray[457]: created by v2ray.com/core/transport/internet.(*TCPHub).start
Nov 13 08:25:37 localhost v2ray[457]: /home/travis/gopath/src/v2ray.com/core/transport/internet/tcp_hub.go:89 +0x1b3
Nov 13 08:25:37 localhost systemd[1]: v2ray.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 13 08:25:37 localhost systemd[1]: Unit v2ray.service entered failed state.

看日志似乎是与shadowsocks有关，开的shadowsocks主要是给别人用，不确定当时是否在使用shadowsocks。

4) 你期待看到的正确表现是怎样的？
4) What do you expected to see instead?
解决该退出问题
5) 请附上你的配置文件。
5) Please attach your configuration file.
以下服务器配置：
``` javascipt
{
  "log": {
    "access": "",
    "loglevel": "info"
  },
  "inbound": {
    "protocol": "vmess",
    "port": xxxx,
    "settings": {
      "clients": [
        {
          "id": "----",
          "level": 1,
          "alterId": 31
        }
      ]
    },
    "streamSettings": {
      "network": "kcp"
    }
  },
  "inboundDetour": [
    {
      "protocol": "vmess",
      "port": xxxx,
      "settings": {
        "clients": [
          {
            "id": "xxxx",
            "level": 1,
            "alterId": 31
          }
        ]
      }
    },
    {
      "protocol": "vmess",
      "port": xxxx,
      "settings": {
        "clients": [
          {
            "id": "----",
            "level": 1,
            "alterId": 31
          }
        ]
      },
      "streamSettings": {
        "network": "kcp"
      }
    },
    {
      "protocol": "shadowsocks",
      "port": xxxx,
      "settings": {
        "method": "aes-256-cfb",
        "password": "****"
      }
    }
  ],
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "blocked"
    },
    {
      "tag": "jp",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "****",
            "port": xxxx,
            "users": [
              {
                "id": "----",
                "alterId": 31
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "kcp"
      }
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "domain": [
            "pos.baidu.com",
            "static.blog.csdn.net",
            "wn.x.jd.com",
            "static.360buyimg.com",
            "match.p4p.1688.com",
            "nsclick.baidu.com",
            "baidustatic.com",
            "libs.baidu.com",
            "eclick.baidu.com",
            "cnzz.com",
            "libs.baidu.com",
            "msg.71.am",
            "zhihu-web-analytics.zhihu.com",
            "google-analytics.com",
            "simba.taobao.com",
            "googleadservices.com",
            "analytics.meituan.com",
            "googleads.g.doubleclick.net",
            "strip.taobaocdn.com",
            "googlesyndication.com",
            "medialytics.com",
            "googlesyndication.com",
            "lianmeng.360.cn",
            "tanx.com"
          ],
          "outboundTag": "blocked"
        },
        {
          "type": "chinasites",
          "outboundTag": "jp"
        },
        {
          "type": "chinaip",
          "outboundTag": "jp"
        }
      ]
    }
  },
  "transport": {
    "tcpSettings": {
      "connectionReuse": true
    },
    "kcpSettings": {
      "mtu": 1350,
      "tti": 31,
      "uplinkCapacity": 8,
      "downlinkCapacity": 100,
      "congestion": true,
      "header": {
        "type": "srtp"
      }
    }
  }
}
```

**Comment by v2ray** [comment]
将在 2.6 中修复。

**Comment by astrataro** [comment]
顺道建议将 systemd 里 service 设置的 Restart=on-abnormal 修改为 on-failure
绝大多数 v2ray 用户在服务器部署完成后一旦进入 failed state 时可能并不在意具体原因，而更需要在 unclean exit 之后也能自动重启

**Comment by v2ray** [comment]
已修改，谢谢指出。
