### ISSUE TITLE
想在v2ray服务端outbounds流量出口处加上http代理，一直没有走通，问题如下

### ISSUE THREAD

**Issue by angrykub** [v2ray/v2ray-core#2909]
v2ray版本：
4.40.1

v2ray服务端配置：
`{
  "log": {
        "access": "/var/log/v2ray/access.log",
        "error": "/var/log/v2ray/error.log",
        "loglevel": "debug"
    },
  "inbounds": [
    {
      "port":my_port,
      "listen": "127.0.0.1", 
      "tag": "vmess-in", 
      "protocol": "vmess", 
      "settings": {
        "clients": [
          {
          "id":"my-id",
          "alterId":64
          }
        ]
      }, 
      "streamSettings": {
        "network": "ws", 
        "wsSettings": {
          "path":"/my_path/"
        }
      }
    }
  ], 
  "outbounds": [
    {
      "tag": "http_proxy_with_usrpwd",
      "protocol": "http",
      "settings": {
        "servers": [
          {
            "address": "218.87.165.14",
            "port": 8888,
            "users": [
              {
                "user": "zhima",
                "pass": "zhima"
              }
            ]
          }
        ]
      }
    },
    {
      "protocol": "freedom",
      "settings": { },
      "tag": "direct"
    }
  ], 
  "dns": {
    "servers": [
      "https+local://1.1.1.1/dns-query",
          "1.1.1.1",
          "1.0.0.1",
          "8.8.8.8",
          "8.8.4.4",
          "localhost"
    ]
  },
  "routing": {
    "domainStrategy": "rules",
    "rules": [
      {
        "type": "field",
        "protocol":["http", "tcp"],
        "inboundTag": ["vmess-in"],
        "outboundTag": "direct"
      }
    ]
  }
}`

服务端error.log日志如下：
2021/07/25 19:23:36 [Warning] V2Ray 4.40.1 started
2021/07/25 19:23:55 [Warning] proxy/vmess/encoding: Critical Warning: potentially invalid user: a non VMessAEAD connection is received. From 2022 Jan 1st, this kind of connection will be rejected by default. You should update or replace your client software now. This message will not be shown for further violation on this inbound.
2021/07/25 19:23:55 [Info] [520459010] proxy/vmess/inbound: received request for tcp:v1.mux.cool:0
2021/07/25 19:23:55 [Info] [520459010] common/mux: received request for tcp:ip.gs:80
2021/07/25 19:23:55 [Info] [520459010] app/dispatcher: default route for tcp:ip.gs:80
2021/07/25 19:23:55 [Info] [520459010] transport/internet/tcp: dialing TCP to tcp:218.87.165.14:8888
2021/07/25 19:23:55 [Info] [520459010] transport/internet/tcp: dialing TCP to tcp:218.87.165.14:8888
2021/07/25 19:23:56 [Info] [520459010] transport/internet/tcp: dialing TCP to tcp:218.87.165.14:8888
2021/07/25 19:23:56 [Info] [520459010] transport/internet/tcp: dialing TCP to tcp:218.87.165.14:8888
2021/07/25 19:23:56 [Info] [520459010] transport/internet/tcp: dialing TCP to tcp:218.87.165.14:8888
2021/07/25 19:23:57 [Info] [520459010] app/proxyman/outbound: failed to process outbound traffic > proxy/http: failed to find an available destination > common/retry: [proxy/http: Proxy responded with non 200 code: 403 Forbidden] > common/retry: all retry attempts failed
2021/07/25 19:23:57 [Info] [520459010] common/mux: session 1 ends. > io: read/write on closed pipe
2021/07/25 19:24:12 [Info] [520459010] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > context canceled

**Comment by undefine-man** [comment]
vmess是基于TCP的协议，和http是同级相互独立的协议，所以应该不行吧

**Comment by angrykub** [comment]
忘记关掉了，在outbounds出口加http代理是可以的，不成功是我使用的http代理问题
