### ISSUE TITLE
v2ray 异常退出

### ISSUE THREAD

**Issue by ToutyRater** [v2ray/v2ray-core#291]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please answer the following questions before submitting your issue. Thank you.

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
1) What version of V2Ray are you using?
 v2.6.1
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
2) What your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
使用chrome通过v2ray浏览网页
3) 你看到的不正常的现象是什么？
3) What did you see?
v2ray 异常退出。日志：
>Nov 14 12:10:59 debian-512mb-sgp1-01 v2ray[2821]: 2016/11/14 12:10:59 [Warning]Internet|Listener: Failed to accept new TCP connection: accept tcp [::]:53: accept4: too many open files
Nov 14 12:10:59 debian-512mb-sgp1-01 v2ray[2821]: 2016/11/14 12:10:59 [Warning]Internet|Listener: Failed to accept new TCP connection: accept tcp [::]:53: accept4: too many open files
Nov 14 12:11:16 debian-512mb-sgp1-01 v2ray[2821]: v2ray.com/core/transport/internet/authenticators/http.(*HttpConn).Close(0xc4213e5f00, 0xc4219b2540, 0xc421e05f90)
Nov 14 12:11:16 debian-512mb-sgp1-01 v2ray[2821]: <autogenerated>:3 +0x3b
Nov 14 12:11:16 debian-512mb-sgp1-01 v2ray[2821]: v2ray.com/core/transport/internet/tcp.(*TCPListener).KeepAccepting(0xc4219da240)
Nov 14 12:11:16 debian-512mb-sgp1-01 v2ray[2821]: /home/travis/gopath/src/v2ray.com/core/transport/internet/tcp/hub.go:120 +0x1b8
Nov 14 12:11:16 debian-512mb-sgp1-01 v2ray[2821]: created by v2ray.com/core/transport/internet/tcp.ListenTCP
Nov 14 12:11:16 debian-512mb-sgp1-01 v2ray[2821]: /home/travis/gopath/src/v2ray.com/core/transport/internet/tcp/hub.go:77 +0x25f
Nov 14 12:11:16 debian-512mb-sgp1-01 systemd[1]: v2ray.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 14 12:11:16 debian-512mb-sgp1-01 systemd[1]: Unit v2ray.service entered failed state.

另外，从当日 11：52：20 到12：10：59这18分钟内全是 `[Warning]Internet|Listener: Failed to accept new TCP connection: accept tcp [::]:53: accept4: too many open files` 这样的日志，约7.5万行。
 请问一下日志 `too many open files` 是什么意思？什么情况下会出现这种警告？
4) 你期待看到的正确表现是怎样的？
4) What do you expected to see instead?
修复异常退出问题
5) 请附上你的配置文件。
5) Please attach your configuration file.
```javascipt
{
  "log": {
    "access": "",
    "loglevel": "info"
  },
  "inbound": {
    "protocol": "vmess",
    "port": xxxx,
    "settings": {
      "clients": [
        {
          "id": "----",
          "level": 1,
          "alterId": 31
        }
      ]
    },
    "streamSettings": {
      "network": "kcp"
    }
  },
  "inboundDetour": [
    {
      "protocol": "vmess",
      "port": xxxx,
      "settings": {
        "clients": [
          {
            "id": "xxxx",
            "level": 1,
            "alterId": 31
          }
        ]
      }
    },
    {
      "protocol": "vmess",
      "port": xxxx,
      "settings": {
        "clients": [
          {
            "id": "----",
            "level": 1,
            "alterId": 31
          }
        ]
      },
      "streamSettings": {
        "network": "kcp"
      }
    }
  ],
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "blocked"
    },
    {
      "tag": "jp",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "****",
            "port": xxxx,
            "users": [
              {
                "id": "----",
                "alterId": 31
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "kcp"
      }
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "domain": [
            "pos.baidu.com",
            "static.blog.csdn.net",
            "wn.x.jd.com",
            "static.360buyimg.com",
            "match.p4p.1688.com",
            "nsclick.baidu.com",
            "baidustatic.com",
            "libs.baidu.com",
            "eclick.baidu.com",
            "cnzz.com",
            "libs.baidu.com",
            "msg.71.am",
            "zhihu-web-analytics.zhihu.com",
            "google-analytics.com",
            "simba.taobao.com",
            "googleadservices.com",
            "analytics.meituan.com",
            "googleads.g.doubleclick.net",
            "strip.taobaocdn.com",
            "googlesyndication.com",
            "medialytics.com",
            "googlesyndication.com",
            "lianmeng.360.cn",
            "tanx.com"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  },
  "transport": {
    "tcpSettings": {
      "connectionReuse": true
    },
    "kcpSettings": {
      "mtu": 1350,
      "tti": 31,
      "uplinkCapacity": 8,
      "downlinkCapacity": 100,
      "congestion": true,
      "header": {
        "type": "srtp"
      }
    }
  }
}
```

**Comment by v2ray** [comment]
可以尝试增加打开文件的数量限制，[参考1](https://github.com/shadowsocks/shadowsocks/wiki/%E4%BC%98%E5%8C%96-Shadowsocks)、[2](https://www.91yun.org/archives/545)，ulimit 部分。

大量的错误输出暂时没办法解决，一旦进入这个状态就会大量输出，只能重启 V2Ray 服务器端 。后续版本会减少输出的内容。

**Comment by ToutyRater** [comment]
好的，了解了。多谢解答
