### ISSUE TITLE
lede V2Ray配置文件没有通过测试！！！求大神

### ISSUE THREAD

**Issue by markowen10** [v2ray/v2ray-core#2912]
【2021年08月03日 18:35:08】: ---------------------- LEDE 固件 v2ray -----------------------
【2021年08月03日 18:35:08】: v2ray符合启动条件！~
【2021年08月03日 18:35:08】: 重启dnsmasq服务...
【2021年08月03日 18:35:11】: 尝试先清除已存在的iptables规则，防止重复添加
【2021年08月03日 18:35:12】: 先清空已存在的ipset名单，防止重复添加
【2021年08月03日 18:35:12】: 清除重复的ip rule规则.
【2021年08月03日 18:35:12】: 删除ip route规则.
【2021年08月03日 18:35:12】: 清除firewall中相关的 v2ray 启动命令...
【2021年08月03日 18:35:12】: 创建国内CDN解析优化配置文件
【2021年08月03日 18:35:12】: 创建状态检测解析优化配置文件
【2021年08月03日 18:35:12】: DNS解析方案国外优先，优先解析国外DNS.
【2021年08月03日 18:35:12】: 添加nat-start触发事件...
【2021年08月03日 18:35:12】: 优化网络参数
【2021年08月03日 18:35:12】: 使用 🇯🇵日本--03x0.1 配置文件...
【2021年08月03日 18:35:12】: 解析V2Ray配置文件...
【2021年08月03日 18:35:12】: V2Ray配置文件写入成功到/koolshare/v2ray/v2ray.json
【2021年08月03日 18:35:12】: 没有检测到你的v2ray服务器地址，如果你确定你的配置是正确的
【2021年08月03日 18:35:12】: 请自行将v2ray服务器的ip地址填入【IP/CIDR】黑名单中，以确保正常使用
【2021年08月03日 18:35:12】: 测试V2Ray配置文件.....
【2021年08月03日 18:35:12】: V2Ray配置文件没有通过测试，请检查设置!!!
【2021年08月03日 18:35:12】: 出错原因：main: failed to read config file: /tmp/v2ray_tmp.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to read config file > EOF > exit status 255
【2021年08月03日 18:35:12】: 插件将在5秒后自动关闭！！
【2021年08月03日 18:35:13】: 5
【2021年08月03日 18:35:14】: 4
【2021年08月03日 18:35:15】: 3
【2021年08月03日 18:35:16】: 2
【2021年08月03日 18:35:17】: 1
【2021年08月03日 18:35:18】: 0
【2021年08月03日 18:35:22】: 某些老版本固件已经无法使用新版插件，请升级到最新版固件使用！
【2021年08月03日 18:35:22】: 插件已关闭！！
【2021年08月03日 18:35:22】: ------------------------- v2ray 成功关闭 -------------------------

**Comment by zhubinsheng** [comment]
how to fix this

> 【2021年08月03日 18:35:08】: ---------------------- LEDE 固件 v2ray -----------------------
> 【2021年08月03日 18:35:08】: v2ray符合启动条件！~
> 【2021年08月03日 18:35:08】: 重启dnsmasq服务...
> 【2021年08月03日 18:35:11】: 尝试先清除已存在的iptables规则，防止重复添加
> 【2021年08月03日 18:35:12】: 先清空已存在的ipset名单，防止重复添加
> 【2021年08月03日 18:35:12】: 清除重复的ip rule规则.
> 【2021年08月03日 18:35:12】: 删除ip route规则.
> 【2021年08月03日 18:35:12】: 清除firewall中相关的 v2ray 启动命令...
> 【2021年08月03日 18:35:12】: 创建国内CDN解析优化配置文件
> 【2021年08月03日 18:35:12】: 创建状态检测解析优化配置文件
> 【2021年08月03日 18:35:12】: DNS解析方案国外优先，优先解析国外DNS.
> 【2021年08月03日 18:35:12】: 添加nat-start触发事件...
> 【2021年08月03日 18:35:12】: 优化网络参数
> 【2021年08月03日 18:35:12】: 使用 🇯🇵日本--03x0.1 配置文件...
> 【2021年08月03日 18:35:12】: 解析V2Ray配置文件...
> 【2021年08月03日 18:35:12】: V2Ray配置文件写入成功到/koolshare/v2ray/v2ray.json
> 【2021年08月03日 18:35:12】: 没有检测到你的v2ray服务器地址，如果你确定你的配置是正确的
> 【2021年08月03日 18:35:12】: 请自行将v2ray服务器的ip地址填入【IP/CIDR】黑名单中，以确保正常使用
> 【2021年08月03日 18:35:12】: 测试V2Ray配置文件.....
> 【2021年08月03日 18:35:12】: V2Ray配置文件没有通过测试，请检查设置!!!
> 【2021年08月03日 18:35:12】: 出错原因：main: failed to read config file: /tmp/v2ray_tmp.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to read config file > EOF > exit status 255
> 【2021年08月03日 18:35:12】: 插件将在5秒后自动关闭！！
> 【2021年08月03日 18:35:13】: 5
> 【2021年08月03日 18:35:14】: 4
> 【2021年08月03日 18:35:15】: 3
> 【2021年08月03日 18:35:16】: 2
> 【2021年08月03日 18:35:17】: 1
> 【2021年08月03日 18:35:18】: 0
> 【2021年08月03日 18:35:22】: 某些老版本固件已经无法使用新版插件，请升级到最新版固件使用！
> 【2021年08月03日 18:35:22】: 插件已关闭！！
> 【2021年08月03日 18:35:22】: ------------------------- v2ray 成功关闭 -------------------------
