### ISSUE TITLE
530.8G的虚拟内存

### ISSUE THREAD

**Issue by GeiliCode** [v2ray/v2ray-core#292]
版本: V2Ray v2.5.2 (One for all) 20161109
客户端: macOS 10.12.1 (16B2555)

v2ray刚启动就有530.8G 的 virt, 请问这个情况正常吗, 会对系统性能有影响吗?
```
ps aux|grep v2ray
xxx 22504   0.0  0.2 556607108  32008 s013  S+    4:14下午   0:00.77 v2ray
```

kcptun 也是530.8G 的 virt, 可能都用了相同的库?
```
xxx 98756   0.8  0.6 556604056  93344 s019  S+    2:02下午   2:04.46 client_darwin_amd64 -r
```

**Comment by v2ray** [comment]
Golang 的行为：https://golang.org/doc/faq#Why_does_my_Go_process_use_so_much_virtual_memory
