### ISSUE TITLE
出现大量连接指向同一个目标地址，导致路由器连接数瞬间占满

### ISSUE THREAD

**Issue by ddjj7** [v2ray/v2ray-core#2922]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
**版本：V2Ray 4.41.1 (OpenWrt) R1 (go1.16.7 linux/amd64)**

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
**用于路由器实现局域网整体代理**

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
**路由器服务启动后较短时间内路由器连接数快速增长，直到占满所有连接数，同时耗尽内存导致断流
若使用Qv2ray，v2rayN等Linux/Windows客户端则无此问题**

4) 你期待看到的正确表现是怎样的？
**连接数与网络用量相符**

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

略

客户端配置:

{
	"log": {
		"access": "/var/log/v2ray-access.log",
		"loglevel": "warning",
		"error": "/var/log/v2ray-error.log"
	},
	"dns": {
		"hosts": {
			"example.com": "127.0.0.1"
		},
		"servers": [
			"1.1.1.1",
			"8.8.8.8",
			{
				"address": "114.114.114.114",
				"port": 53,
				"domains": [
					"geosite:cn"
				]
			},
			{
				"address": "223.5.5.5",
				"port": 53,
				"domains": [
					"geosite:cn"
				]
			}
		]
	},
	"routing": {
		"domainStrategy": "IPOnDemand",
		"rules": [
			{
				"type": "field",
				"ip": [
					"geoip:private",
					"geoip:cn"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"domain": [
					"geosite:cn"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"protocol": [
					"bittorrent"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"port": "53",
				"network": "udp",
				"inboundTag": [
					"transparent"
				],
				"outboundTag": "dns_out"
			},
			{
				"type": "field",
				"ip": [
					"114.114.114.114",
					"223.5.5.5"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"ip": [
					"1.1.1.1",
					"8.8.8.8",
					"208.67.222.222"
				],
				"outboundTag": "proxy"
			},
			{
				"type": "field",
				"port": "123",
				"network": "udp",
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"network": "tcp,udp",
				"inboundTag": [
					"transparent"
				],
				"protocol": [
					"http",
					"tls"
				],
				"outboundTag": "proxy"
			}
		]
	},
	"inbounds": [
		{
			"listen": "0.0.0.0",
			"port": 1081,
			"protocol": "dokodemo-door",
			"settings": {
				"followRedirect": true,
				"network": "tcp"
			},
			"streamSettings": {
				"sockopt": {
					"tproxy": "redirect"
				}
			},
			"tag": "transparent",
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			},
			"allocate": {
				"strategy": "always"
			}
		}
	],
	"outbounds": [
		{
			"protocol": "freedom",
			"settings": {		
			},
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			},
			"tag": "direct"
		},
		{
			"protocol": "blackhole",
			"settings": {
				
			},
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			},
			"tag": "block"
		},
		{
			"protocol": "dns",
			"settings": {
				
			},
			"streamSettings": {
				"sockopt": {
					"mark": 255
				}
			},
			"tag": "dns_out"
		},
		{
			"sendThrough": "192.168.1.1",
			"protocol": "vless",
			"settings": {
				"vnext": [
					{
						"address": "my.site",
						"port": myport,
						"users": [
							{
								"id": "myid",
								"encryption": "none"
							}
						]
					}
				]
			},
			"streamSettings": {
				"network": "ws",
				"security": "tls",
				"tlsSettings": {
					"allowInsecure": false,
					"allowInsecureCiphers": false,
					"disableSystemRoot": false,
					"certificates": [
						
					]
				},
				"wsSettings": {
					"path": "/path/"
				},
				"sockopt": {
					"mark": 255
				}
			},
			"tag": "proxy"
		}
	]
}

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

略

客户端错误日志:

**error.log无报错**

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

**大量如以下内容，反复对1-2个ip进行请求**
2021/08/23 22:12:29 我的wan口ip:28260 accepted tcp:47.75.85.225:443 [direct]
2021/08/23 22:12:29 我的wan口ip:23736 accepted tcp:94.74.104.125:443 [direct]
2021/08/23 22:12:29 我的wan口ip:28264 accepted tcp:47.75.85.225:443 [direct]
2021/08/23 22:12:29 我的wan口ip:28266 accepted tcp:47.75.85.225:443 [direct]
2021/08/23 22:12:29 我的wan口ip:23744 accepted tcp:94.74.104.125:443 [direct]
2021/08/23 22:12:29 我的wan口ip:23742 accepted tcp:94.74.104.125:443 [direct]
2021/08/23 22:12:29 我的wan口ip:28272 accepted tcp:47.75.85.225:443 [direct]
2021/08/23 22:12:29 我的wan口ip:28274 accepted tcp:47.75.85.225:443 [direct]
2021/08/23 22:12:29 我的wan口ip:23752 accepted tcp:94.74.104.125:443 [direct]
2021/08/23 22:12:29 我的wan口ip:23750 accepted tcp:94.74.104.125:443 [direct]
2021/08/23 22:12:29 我的wan口ip:28280 accepted tcp:47.75.85.225:443 [direct]
2021/08/23 22:12:29 我的wan口ip:28282 accepted tcp:47.75.85.225:443 [direct]
2021/08/23 22:12:29 我的wan口ip:23760 accepted tcp:94.74.104.125:443 [direct]
2021/08/23 22:12:29 我的wan口ip:23758 accepted tcp:94.74.104.125:443 [direct]
2021/08/23 22:12:29 我的wan口ip:28288 accepted tcp:47.75.85.225:443 [direct]
2021/08/23 22:12:29 我的wan口ip:28290 accepted tcp:47.75.85.225:443 [direct]
2021/08/23 22:12:29 我的wan口ip:23768 accepted tcp:94.74.104.125:443 [direct]
2021/08/23 22:12:29 我的wan口ip:23770 accepted tcp:94.74.104.125:443 [direct]
2021/08/23 22:12:29 我的wan口ip:28300 accepted tcp:47.75.85.225:443 [direct]
2021/08/23 22:12:29 我的wan口ip:28298 accepted tcp:47.75.85.225:443 [direct]
2021/08/23 22:12:29 我的wan口ip:23778 accepted tcp:94.74.104.125:443 [direct]
2021/08/23 22:12:29 我的wan口ip:23776 accepted tcp:94.74.104.125:443 [direct]
2021/08/23 22:12:29 我的wan口ip:28308 accepted tcp:47.75.85.225:443 [direct]
2021/08/23 22:12:29 我的wan口ip:28306 accepted tcp:47.75.85.225:443 [direct]
2021/08/23 22:12:29 我的wan口ip:23786 accepted tcp:94.74.104.125:443 [direct]
2021/08/23 22:12:29 我的wan口ip:23784 accepted tcp:94.74.104.125:443 [direct]
2021/08/23 22:12:29 我的wan口ip:28314 accepted tcp:47.75.85.225:443 [direct]
2021/08/23 22:12:29 我的wan口ip:28316 accepted tcp:47.75.85.225:443 [direct]
2021/08/23 22:12:29 我的wan口ip:23792 accepted tcp:94.74.104.125:443 [direct]

8) 其它相关的配置文件（如 Nginx）和相关日志。
**无**

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。
**无**

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。
**无**

**Comment by ddjj7** [comment]
最近观察了下，发现仅在使用VLESS协议时出现，VMESS无此情况，猜测会不会跟luci-app-v2ray有关？
对某个走不通的端口使用direct方式连接，正常来说这些ip应该是走代理方式的，之后反复进行重试，导致产生大量连接

**Comment by ddjj7** [comment]
放弃，改用hello world无此问题

**Comment by daryl000** [comment]
> 放弃，改用hello world无此问题

我也出现了同样的问题，使用协议VMESS，版本4.43.0(最新版本)，每日或最多每隔两日会固定出现一次类似：
Thu Dec  2 06:52:04 2021 daemon.info v2ray[13961]: 2021/12/01 22:52:04 [wan-ip]:34750 accepted tcp:[wan-ip]:1088 [direct]
的情况。起初此情况会直接导致路由直接内存占满死机，后设置了防火墙所以不会死机，但会持续这样直到手动重启。

求教该问题如何解决，是否为攻击所致。

还有“改用hello world无此问题”，没有看懂。希望可以帮我解答这个长期困扰的问题(十分担心这是网络攻击)

**Comment by ddjj7** [comment]
> > 放弃，改用hello world无此问题
> 
> 我也出现了同样的问题，使用协议VMESS，版本4.43.0(最新版本)，每日或最多每隔两日会固定出现一次类似： Thu Dec 2 06:52:04 2021 daemon.info v2ray[13961]: 2021/12/01 22:52:04 [wan-ip]:34750 accepted tcp:[wan-ip]:1088 [direct] 的情况。起初此情况会直接导致路由直接内存占满死机，后设置了防火墙所以不会死机，但会持续这样直到手动重启。
> 
> 求教该问题如何解决，是否为攻击所致。
> 
> 还有“改用hello world无此问题”，没有看懂。希望可以帮我解答这个长期困扰的问题(十分担心这是网络攻击)

就是我不用luci-app-v2ray了……改用一个名叫“hello world”的客户端（客户端UI？）
我推测是luci-app-v2ray对vless的支持有问题，应该走代理的目标没有走，然后无限重试导致的
你看下你的accesslog是不是和我的类似吧，尝试无限直连一个被墙的目的地，不通的链接又不做释放，重新换个端口再起一个链接

**Comment by daryl000** [comment]
>你看下你的access.log是不是和我的类似吧，尝试无限直连一个被墙的目的地，不通的链接又不做释放，重新换个端口再起一个链接
先回答：NO. 不是在无限访问被墙地址。而是进入了一个明显的消耗死循环，WAN到V2RAY，V2RAY将请求[direct]回WAN-IP。

我一直都没有使用LUCI的V2RAY，直接命令行操作。我想跟luci-app-v2ray没有关系。明显是DDOS的一种(可能是spoofing attack?) 其中有一次我看到了类似这样的记录(log已遗失): tcp: random-IP: port ACCEPT WAN-IP: xxxxx(iptables中设置的其他流量转发端口) 然后就开始了无限循环的[wan-ip]:xxxxx accepted tcp:[wan-ip]:xxxxx [direct] 直到内存耗尽，进程被KILL。

下一步的尝试：
1. 调用geoip来配合iptables，将所有CN的流量都return掉。(减少V2RAY的负载，connection rate limit和其他未知问题)
2. 设置一个BLACKHOLE ROUTE, 将可疑的IP访问直接扔到blackhole里面。

目前还在研究一些安装和设置，如果后面有进展，我再来跟你交流。也希望可以了解到你那里后续的一些情况。
