### ISSUE TITLE
更新GEOSITE时卡死，重新打开就不能上网

### ISSUE THREAD

**Issue by xzh767** [v2ray/v2ray-core#2931]
我使用V2RAY最新版本（在9/9更新）
使用VMESS和VLESS代理结合HEROKU和CF访问外网
错误代码
配置成功
[Vmess] heroku-test-clone(198***42:443)
启动服务(2021/9/10 21:02:43)...
2021/09/10 21:02:44 Using default config:  C:\Program Files\VPN\v2rayN-Core\v2rayN-Core\config.json

V2Ray 4.41.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.6 windows/amd64)
A unified platform for anti-censorship.
2021/09/10 21:02:44 [Info] main/jsonem: Reading config: C:\Program Files\VPN\v2rayN-Core\v2rayN-Core\config.json
main: failed to read config files: [C:\Program Files\VPN\v2rayN-Core\v2rayN-Core\config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to parse domain rule: geosite:google > infra/conf/rule: failed to load geosite: google > infra/conf/geodata/standard: failed to open file: geosite.dat > open C:\Program Files\VPN\v2rayN-Core\v2rayN-Core\geosite.dat: The system cannot find the file specified.
这个问题在更新GEO后出现
正常表现是可以直接访问外网

一个VL一个VM：vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogImhlcm9rdS10ZXN0LWNsb25lIiwNCiAgImFkZCI6ICIxOTguNDEuMjA5LjQyIiwNCiAgInBvcnQiOiAiNDQzIiwNCiAgImlkIjogImFkODA2NDg3LTJkMjYtNDYzNi05OGI2LWFiODVjYzg1MjFmNyIsDQogICJhaWQiOiAiNjQiLA0KICAic2N5IjogImFlcy0xMjgtZ2NtIiwNCiAgIm5ldCI6ICJ3cyIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICJ3aW50ZXItY2FrZS1jNTdhLnhsei53b3JrZXJzLmRldiIsDQogICJwYXRoIjogIi8iLA0KICAidGxzIjogInRscyIsDQogICJzbmkiOiAiIg0KfQ==

vless://ad806487-2d26-4636-98b6-ab85cc8521f7@IP地址:443?encryption=none&security=tls&type=ws&host=域名，不含HTTPS和末尾/、&path=%2f#vless

v2ray客户端：V2RAYN,V4.2,WINDOWS

**Comment by feng17879632526** [comment]
重新更新一下就行了
