### ISSUE TITLE
systemctl status v2ray 运行被禁止

### ISSUE THREAD

**Issue by lotionMake** [v2ray/v2ray-core#2933]
运行之后
![QQ截图20210913185333](https://user-images.githubusercontent.com/89283377/133071576-a59b5622-3923-401a-bdc6-fe72360deb16.png)

使用   /usr/bin/v2ray/v2ray test -config /etc/v2ray/config.json 进行测试
![QQ截图20210913185423](https://user-images.githubusercontent.com/89283377/133071692-182858ee-17ab-4f3e-87ba-5d1e858279cb.png)

运行 journalctl -u v2ray 提示
![QQ截图20210913185523](https://user-images.githubusercontent.com/89283377/133071872-eab65123-0170-4729-beca-4e4b3e2c3c5e.png)

**Comment by Mistofs** [comment]
应该是配置文件不正确
