### ISSUE TITLE
V2RAY可以实现双线路同步吗?

### ISSUE THREAD

**Issue by linsan970809** [v2ray/v2ray-core#2938]
我有电信和移动两条宽带,局域网内有两台主机装了V2RA客户端用来连接香港的一台服务器来玩国外的游戏,为什么两台都要装,因为有一个问题不知道是什么原因,两条线路偶尔会抽风,PING值上500到1000,但是两条线路不会同时抽,所以我只能是电信抽换移动的玩,移动抽换电信的玩,请问V2RAY能不能实现同时走两条线路,也就是说同时发包,服务端判断判断哪条线路的包快就用哪条线路,丢弃另一条线路的包,如图
![Th7sXOD3Cg](https://user-images.githubusercontent.com/61045370/133783451-0b21c0e2-6018-4baa-8fc4-d518d6795c79.jpg)

**Comment by Mistofs** [comment]
可以，你的游戏主机要是能够自动选择用哪一条线路，就可以做到了。
要是V2ray布置在服务器集群上，一台用移动连香港一台用电信连香港，那么就可以用load balancer来解决。
同样，因为你是用局域网的那两台主机来搞事情，所以可以考虑在本地设置load balancer。
