### ISSUE TITLE
怎么共享给局域网内其他机器使用？其他机器可以ping通设置代理的机器

### ISSUE THREAD

**Issue by hlyang1992** [v2ray/v2ray-core#294]
客户端使用的是ubuntu 16.04.

**Comment by eastmalon** [comment]
"address": "127.0.0.1" ==> "address": "0.0.0.0"

**Comment by hlyang1992** [comment]
win10 下面edge浏览器该怎么设置代理？设置为ubuntu地址与端口无效啊

**Comment by hlyang1992** [comment]
谢谢，我看了文档。v2ray真是强大啊
