### ISSUE TITLE
举报! 有人利用openwrt路由器插件安装带木马的v2ray，请大佬曝光他们，还v2ray清凉

### ISSUE THREAD

**Issue by xoomp** [v2ray/v2ray-core#2946]
此链接的项目就是有问题的 https://github.com/kuoruan/openwrt-v2ray 

此openwrt路由器v2ray插件带木马，排查了一圈，证据确凿。可打开access log 逐个替换 v2ray v2ctl 程序观测。
被安装的路由器配置会泄露，如果服务端防火墙设置白名单，路由器会被作为中转代理。
流量庞大，会均衡，肯定是不良机场在利用。
另外openwrt有个lean编译的路由器也带此包或者是一伙的！！！安
装多次路由器，折腾多天，才排查到。
请各位大佬最大化曝光他们。

**Comment by dongqiceo** [comment]
删了吧，开源的，有没有问题看代码嘛
