### ISSUE TITLE
域名匹配的问题

### ISSUE THREAD

**Issue by GeiliCode** [v2ray/v2ray-core#295]
1. 纯字符串: 当此字符串匹配目标域名中任意部分，该规则生效。比如"sina.com"可以匹配"sina.com"、"sina.com.cn"和"www.sina.com"，但不匹配"sina.cn"。

请问是否会匹配 abcsina.com?
如果是的话, 可否有方法实现 [SwitchyOmega - Host wildcard condition](https://github.com/FelisCatus/SwitchyOmega/wiki/Host-wildcard-condition) 中的效果?
因为有些短域名很容易成为其他域名的一部分, 例如 t.cn

2. 正则表达式: 由"regexp:"开始，余下部分是一个正则表达式。当此正则表达式匹配目标域名时，该规则生效。例如"regexp:\\.goo.*\\.com$"匹配"www.google.com"、"fonts.googleapis.com"，但不匹配"google.com"。

正则和1的方法哪个效率高呢?

**Comment by v2ray** [comment]
* sina.com 会匹配 abcsina.com。如果需要只匹配子域名，可以使用 .sina.com。
* SwitchyOmega 中 \*.sina.com 相当于 `regexp:(.*\.)?sina.com$`
 * 注意 json 中需要写成`"regexp:(.*\\.)?sina.com$"` 
* 性能没有差别
