### ISSUE TITLE
关于v2ray混淆host无法转发okhttp请求

### ISSUE THREAD

**Issue by lcybshwm** [v2ray/v2ray-core#2950]
1.我在服务器上使用v2ray搭建了一个节点。然后在v2rayng客户端填了host。
2.然后我在服务器端安装了一个tcpdump的网络请求监控程序，发现get请求和post请求了大部分的网络请求的host可以被程序改写伪装，但是通过okhttp发出的请求，例如User-Agent:okhttp/3.8.1，我认为v2ray没有对其转发。希望作者予以修复。

这个作用其实就是免流防跳点。

**Comment by kslr** [comment]
see docs
