### ISSUE TITLE
v2ray-core日志中会有proxy/vmess/encoding: Critical Warning: potentially invalid user: a non VMessAEAD connection is received. From 2022 Jan 1st, this kind of connection will be rejected by default. You should update or replace your client software now. This message will not be shown for further violation on this inbound.信息。请问这是什么

### ISSUE THREAD

**Issue by GoodManSmallFei** [v2ray/v2ray-core#2951]
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/discussion/issues)进行讨论。

此 Issue 会被立即关闭。

If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2fly/discussion/issues) first.

This issue will be closed immediately.

**Comment by kslr** [comment]
预期行为
