### ISSUE TITLE
服务器windows server 2008 R2 32位，运行v2ray.exe报错：不是有效的win32应用程序

### ISSUE THREAD

**Issue by lonk1999** [v2ray/v2ray-core#2955]
如题。
我在release中下载了v2ray-windows-32.zip，解压后运行报一样的错误。
想知道，是系统缺少什么环境？还是其他说明原因导致。谢谢！

详细说明：
我下载使用的是 V2Ray v4.31.0
v2ray-windows-32.zip

在Dos命令行（管理员）中运行v2ray.exe。

不正常的现象是，弹窗提示“不是有效的win32应用程序”。

你期待看到的是程序能正常被执行。

配置内容没有修改，为压缩包里原始的config.json。

**Comment by mivtec** [comment]
把.net 和VC的运行库都装上
