### ISSUE TITLE
v2ray -config /usr/local/etc/v2ray/config.json -test 测试结果

### ISSUE THREAD

**Issue by crazynet999** [v2ray/v2ray-core#2965]
root@instance-20191219-1620:~# v2ray -config /usr/local/etc/v2ray/config.json -test
V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.3 linux/amd64)
A unified platform for anti-censorship.
2022/01/16 13:07:52 [Info] main/jsonem: Reading config: /usr/local/etc/v2ray/config.json
Configuration OK.

A unified platform for anti-censorship. 这个一直出现，找了好多都无法解决，请问这个是通病吗？

**Comment by crazynet999** [comment]
一直连接不上

**Comment by lekeeith** [comment]
解决了吗？我也遇到这个问题了

**Comment by crazynet999** [comment]
更新一下

**Comment by kdsrsl** [comment]
+1

**Comment by shuidaan** [comment]
V2Ray 4.45.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.18.3 linux/amd64)
A unified platform for anti-censorship.
2022/07/03 06:27:17 [Info] main/jsonem: Reading config: /usr/local/etc/v2ray/config.json
Configuration OK.
