### ISSUE TITLE
客户端报错（... outbound: failed to process outbound traffic > ... encoding: failed to read response header）

### ISSUE THREAD

**Issue by haozhiqianga** [v2ray/v2ray-core#2969]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v4.44.0

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
通过 firefox 代理访问任意国内外网站（如 [www.baidu.com](https://www.baidu.com/)）

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
火狐浏览器显示如下：
```
建立安全连接失败

连接到 www.google.com 时发生错误。PR_END_OF_FILE_ERROR

    由于不能验证所收到的数据是否可信，无法显示您想要查看的页面。
    建议向此网站的管理员反馈这个问题。
```

4) 你期待看到的正确表现是怎样的？
正常连接

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
`服务器和客户端的UTC时间一致`

  服务器端配置:

```javascript
    {
  "inbounds": [
    {
      "listen":"127.0.0.1",
      "port": 16823,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "id", 
            "alterId": 64
          }
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}
```

客户端配置:

```javascript
    {
  "inbounds": [
    {
      "port": 1080,
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
      "settings": {
        "auth": "noauth"
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "server ip",
            "port": 16823,
            "users": [
              {
                "id": "id", 
                "alterId": 64
              }
            ]
          }
        ]
      }
    }
  ]
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
   // 无
```

客户端错误日志:

```javascript
   2022/01/24 13:57:28 [Warning] [1906095046] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > EOF
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    // 无
```

8) 其它相关的配置文件（如 Nginx）和相关日志。
```javascript
    // 无
```

**Comment by haozhiqianga** [comment]
VPS使用的是：hostwinds

**Comment by selviodzn** [comment]
试试把alterid改为0

**Comment by haozhiqianga** [comment]
> 试试把alterid改为0
没有用- 应该是配置外的问题

**Comment by FlyArtist** [comment]
同样的问题，我是通过alterId设置0、升级客户端和内核（把升级的都升级一遍），才解决的

**Comment by miyoosan** [comment]
我的也是hostwinds，也是最近几天出的问题，报错都一样，各种办法都试了，IP端口都通，域名DNS解析也没问题，就是连不上。我都要怀疑是hostwinds的锅了

**Comment by godbandfox** [comment]
错误信息差不多,我还有个websocket1000的报错,我是安卓有网络,win11没有,我感觉是更新客户端的问题,v2rayN换成4.28版本后正常

**Comment by learnman1994** [comment]
> 我的也是hostwinds，也是最近几天出的问题，报错都一样，各种办法都试了，IP端口都通，域名DNS解析也没问题，就是连不上。我都要怀疑是hostwinds的锅了

我的vps是lightsail，不过问题和你一样，端口ip都正常，用的还是we tls模式，但就是最近这两天突然没有任何理由的连不上网。伪装网站可以正常访问，证书也没问题，试过一堆办法，都无解，唉。希望大佬能帮忙解答一下。

**Comment by learnman1994** [comment]
> 同样的问题，我是通过alterId设置0、升级客户端和内核（把升级的都升级一遍），才解决的

谢谢大佬，我把alterId设置成0，就可以了。太奇怪了吧，之前的64用的好好的，结果这两天突然就无法连接，各种谷歌百度都解决不了...原来问题竟是要把64设置成0...

**Comment by shuoyinn** [comment]
set alterId as 0, 看官方文档，貌似是从 v4.28.0 即 2022 年 1 月 1 日开始的版本，就鼓励 alterId 为 0，不再让它 > 0 了，好像是因为要支持启用 VMessAEAD，禁用 MD5 认证信息。不明就里，但是能看出 alterId 设为 0 就行。

**Comment by DaxstUz** [comment]
mac 怎么加载v2ray-core?

**Comment by danperor** [comment]
> > 同样的问题，我是通过alterId设置0、升级客户端和内核（把升级的都升级一遍），才解决的

我也是把这个配置改成0才好的。
谢谢各位大佬
之前v2ray突然不能用了，vps 上的v2ray重装了，重新配置了都不行。
后来忙，就没管了，最近闲了一点才想起来很久不能google了，bing 那拉跨的玩意把so还禁了很不爽。
今天来找方案，仔细看了错误log,来网上一搜索，发现了这篇，改了配置之后，立马可以google了，一下子觉得神清气爽。
希望对其他人有用

**Comment by guov100** [comment]
pc客户端v2rayN将alterId设置0问题解决了，可是ios端Kitsunebi修改为0后，登录iPhone chrome 显示err_ssl_protocol_error错误，大家指导咋解决不，感谢

**Comment by SxLvIo** [comment]
> pc客户端v2rayN将alterId设置0问题解决了，可是ios端Kitsunebi修改为0后，登录iPhone chrome 显示err_ssl_protocol_error错误，大家指导咋解决不，感谢

用小火箭

**Comment by guov100** [comment]
> > pc客户端v2rayN将alterId设置0问题解决了，可是ios端Kitsunebi修改为0后，登录iPhone chrome 显示err_ssl_protocol_error错误，大家指导咋解决不，感谢
> 
> 用小火箭

感谢，小火箭可以
