### ISSUE TITLE
端口被占用时程序持续输出错误信息

### ISSUE THREAD

**Issue by kxyzw** [v2ray/v2ray-core#297]
版本： v2.6.1 windows64
当配置文件中inbound监听某端口，比如1080，而1080端口恰好被其他程序占用时，运行v2ray后会以非常快的速度持续、反复、几乎无间隔的输出端口绑定失败的信息。我在Windows下放任v2ray运行，则v2ray会把大量错误信息输出到设置的日志文件。不过大约10秒后，v2ray程序自动退出了，不知道这是bug还是feature？
我觉得更好的做法应该是，出现端口占用这一类的无法继续运行的错误时，输出一次错误信息后直接终止程序，或者等待用户确认是否重试，即使自动重试也最好限制重试间隔时间。否则可能会出现大量出错信息塞满整个硬盘的情况。

**Comment by pug908** [comment]
废物一个

**Comment by v2ray** [comment]
会在下一版本修复。
