### ISSUE TITLE
Unable to access internet

### ISSUE THREAD

**Issue by bill2343** [v2ray/v2ray-core#2972]
Hi,

I ran the exec to  use V2rayn.  for some reason it did not want to connect to my server so I stopped using it. 
My PC now cannot access the internet at all.  The network connects but when I go to any internet address it says its unreachable
I found it include an automatic startup in my start list, so I disabled it,  No impact.

How do I remove all the components from my PC.

Thanks

**Comment by bill2343** [comment]
Chrome is saying ERR_NETWORK_ACCESS_DENIED

**Comment by Lorg0n** [comment]
Same problem
