### ISSUE TITLE
梅林科学上网解析报错

### ISSUE THREAD

**Issue by smilencexh** [v2ray/v2ray-core#2987]
使用梅林科学上网插件解析v2ray时提示如下错误：
【2022年03月19日 16:33:13】: 解析V2Ray配置文件...
parse error: Invalid numeric literal at line 42, column 13
【2022年03月19日 16:33:13】: V2Ray配置文件写入成功到/koolshare/ss/v2ray.json
【2022年03月19日 16:33:13】: 测试V2Ray配置文件.....
【2022年03月19日 16:33:14】: V2Ray配置文件没有通过测试，请检查设置!!!

使用其他软件没有问题，这是什么原因呢

**Comment by dongqiceo** [comment]
这应该是梅林的问题，版本太老都有可能，梅林生成的json配置文件可能不可用了
