### ISSUE TITLE
transport 项是需要在server端和client段都同时配置吗？

### ISSUE THREAD

**Issue by yueyingjuesha** [v2ray/v2ray-core#300]
比如我在服务器端有kcp底层传输配置：
"transport"：{
  "kcpSettings": {
    "mtu": 1350,
    "tti": 20,
    "uplinkCapacity": 50,
    "downlinkCapacity": 100,
    "congestion": false,
    "readBufferSize": 1,
    "writeBufferSize": 1,
    "header": {
      "type": "none"
    }
}
那么在本地客户端的配置里还需要写transport这一项吗？，还是直接写
"streamSettings": {
    "network": "kcp"
  }就可以了
还有想问下，假设两边都需要同时配置的话  
  "uplinkCapacity": 50,
    "downlinkCapacity": 100,这两个参数必须相等吗？
Thanks!

**Comment by BenhoNNNN** [comment]
客户端配置文件里，对象 outbound 里需配置 streamSettings，
另外 kcpSettings 数组里 uplinkCapacity 与 downlinkCapacity 要设置适合你实际网络状况的值，
未注明的串都会使用默认值。

https://www.v2ray.com/chapter_02/05_transport.html

**Comment by v2ray** [comment]
同上，不必须相等，对于非对称网络如 ADSL，要根据具体带宽设置。
