### ISSUE TITLE
rejected  v2ray.com/core/proxy/socks: failed to read request > EOF

### ISSUE THREAD

**Issue by cnbabycrazy** [v2ray/v2ray-core#3001]
V2Ray 4.31.3 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.3 windows/amd64)
A unified platform for anti-censorship.
2022/04/23 23:20:06 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
v2ctl> Read config:  C:/Users/123/Desktop/1/qv2ray/deployment/config/generated/config.gen.json
2022/04/23 23:20:07 127.0.0.1:54212 accepted tcp:127.0.0.1:0 [QV2RAY_API]
2022/04/23 23:20:24 tcp:127.0.0.1:54213 rejected  v2ray.com/core/proxy/socks: failed to read request > EOF
2022/04/23 23:20:25 tcp:127.0.0.1:54214 rejected  v2ray.com/core/proxy/socks: failed to read request > EOF
2022/04/23 23:20:25 tcp:127.0.0.1:54215 rejected  v2ray.com/core/proxy/socks: failed to read request > EOF
2022/04/23 23:20:26 tcp:127.0.0.1:54216 rejected  v2ray.com/core/proxy/socks: failed to read request > EOF
2022/04/23 23:20:26 tcp:127.0.0.1:54217 rejected  v2ray.com/core/proxy/socks: failed to read request > EOF
2022/04/23 23:20:26 tcp:127.0.0.1:54218 rejected  v2ray.com/core/proxy/socks: failed to read request > EOF
2022/04/23 23:20:27 tcp:127.0.0.1:54219 rejected  v2ray.com/core/proxy/socks: failed to read request > EOF
2022/04/23 23:20:28 tcp:127.0.0.1:54220 rejected  v2ray.com/core/proxy/socks: failed to read request > EOF
2022/04/23 23:20:28 tcp:127.0.0.1:54221 rejected  v2ray.com/core/proxy/socks: failed to read request > EOF

连接HTTP端口10809，是可以正常上网。当想用程序去链接socket5 10808端口时，不管怎么折腾，都一直是这个错误。有没有人跟我碰到一样的问题。系统重装过。使用过v2rayN \ Qv2ray 都是这样。

**Comment by cnbabycrazy** [comment]
用电信宽带就不行，用移动手机流量就可以。我估摸着是不是被屏蔽了。但是同样的节点，http代理却有可以正常上网。只是socket5就不行。

**Comment by HyperFox** [comment]
检查一下你的outbounds->vmess设置里是不是设置了alterId并且它的值>0，如果是那么把它去掉试试（client端和server端的配置都要去掉）

**Comment by yfaimisaka** [comment]
> V2Ray 4.31.3 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.3 windows/amd64) A unified platform for anti-censorship. 2022/04/23 23:20:06 [Info] v2ray.com/core/common/platform/ctlcmd: v2ctl> Read config: C:/Users/123/Desktop/1/qv2ray/deployment/config/generated/config.gen.json 2022/04/23 23:20:07 127.0.0.1:54212 accepted tcp:127.0.0.1:0 [QV2RAY_API] 2022/04/23 23:20:24 tcp:127.0.0.1:54213 rejected v2ray.com/core/proxy/socks: failed to read request > EOF 2022/04/23 23:20:25 tcp:127.0.0.1:54214 rejected v2ray.com/core/proxy/socks: failed to read request > EOF 2022/04/23 23:20:25 tcp:127.0.0.1:54215 rejected v2ray.com/core/proxy/socks: failed to read request > EOF 2022/04/23 23:20:26 tcp:127.0.0.1:54216 rejected v2ray.com/core/proxy/socks: failed to read request > EOF 2022/04/23 23:20:26 tcp:127.0.0.1:54217 rejected v2ray.com/core/proxy/socks: failed to read request > EOF 2022/04/23 23:20:26 tcp:127.0.0.1:54218 rejected v2ray.com/core/proxy/socks: failed to read request > EOF 2022/04/23 23:20:27 tcp:127.0.0.1:54219 rejected v2ray.com/core/proxy/socks: failed to read request > EOF 2022/04/23 23:20:28 tcp:127.0.0.1:54220 rejected v2ray.com/core/proxy/socks: failed to read request > EOF 2022/04/23 23:20:28 tcp:127.0.0.1:54221 rejected v2ray.com/core/proxy/socks: failed to read request > EOF
> 
> 连接HTTP端口10809，是可以正常上网。当想用程序去链接socket5 10808端口时，不管怎么折腾，都一直是这个错误。有没有人跟我碰到一样的问题。系统重装过。使用过v2rayN \ Qv2ray 都是这样。

同。之前我还能用socks5代理，但过了一天就也这样了，不知道原因。用于wsl的git代理

**Comment by libmelo** [comment]
> 检查一下你的outbounds->vmess设置里是不是设置了alterId并且它的值>0，如果是那么把它去掉试试（client端和server端的配置都要去掉）

it works, but why？

**Comment by FengLeee** [comment]
同  估计是服务器端出问题了 重新买个代理吧
