### ISSUE TITLE
IOS使用有伪装域名的vmess节点就上不了网

### ISSUE THREAD

**Issue by simendancer** [v2ray/v2ray-core#3002]
ios15.4使用tcp+http+伪装域名的Vmess节点都上不了网，其他协议的节点都可以正常使用。同一个节点，在pc和安卓上都是可以的，跟节点应该没什么关系。手机重启，重置网络，都没用，不知道是什么原因

**Comment by CliveHugo** [comment]
一样的问题，奇怪的是只有ios打开网页不行，但是telegram什么都能用，pc也没有任何问题，我用的是shadowrocket

**Comment by mivtec** [comment]
websocket + tls  正常
不然你试试?
用的客户端是kitsunbbi

**Comment by 594810899** [comment]
> ios15.4使用tcp+http+伪装域名的Vmess节点都上不了网，其他协议的节点都可以正常使用。同一个节点，在pc和安卓上都是可以的，跟节点应该没什么关系。手机重启，重置网络，都没用，不知道是什么原因

请问一下 这个怎么编译的framework   现在也是需要弄这个，但是不会编译， iOS端没法开发了   请兄弟伙们指导指导啊

**Comment by How-are-u** [comment]
小白问下，使用websocket混淆在服务器上需要配置什么,下面是我的配置文件
"inbound": {
    	"port": 10086,		
    	"protocol": "vmess",	
    	"settings": {
			"clients": [
        		{
	    			"id": "xxx-xxx",	
            		"level": 1,
            		"alterId": 64
        		}
			]
		}
  	},
  	"streamSettings": {
	  	"network": "tcp"
  	},
  	"outbound": {
    	"protocol": "freedom",
    	"settings": {}
  	},
  	"outboundDetour": [
		{
			"protocol": "blackhole",
      		"settings": {},
      		"tag": "blocked"
    	}
  	]

**Comment by 247585870** [comment]
弄好了请问，我也是这样电脑端可以上，iOS手机不行
