### ISSUE TITLE
小白求助，使用期间游戏断流掉线

### ISSUE THREAD

**Issue by kinopio0407** [v2ray/v2ray-core#3008]
我是windows11系统
 v2rayN-v5.23  v2fly-Core.v4.45.0  X-ray Core.v1.5.5

通过vmess链接代理来玩游戏，游戏分为语音、对局、mod三个服务器，其中语音和对局服务器会出现几分钟一次的断线，此时mod服务并不会断（mod是一定要代理才可以连通的，以此证明此时节点是没问题的），断线后查看v2ray客户端信息栏，会有同时出现的4~5条重复报错。系统时间校准过。
2022/05/12 19:31:37 [Warning] [1135993022] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1005 (no status)

本人小白，不知道如何获取服务端配置等信息，希望有大佬可以告知，我随后即可附上相关信息

**Comment by Gmrakari** [comment]
Warning, failed to process outbound traffic 处理outbound的link出现问题，这个问题应该是多种原因导致的，其中也包括网络连接质量，它丢包了，后面连串的报文都会问题的了，不过这个也是有retry重试机制的，见common/retry.go

**Comment by jesusjsc** [comment]
卸载腾讯的一切应用，qq，tim，等等，你会发现不断流了
