### ISSUE TITLE
v2raylinux服务器端经常无故退出

### ISSUE THREAD

**Issue by helloyan** [v2ray/v2ray-core#302]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please answer the following questions before submitting your issue. Thank you.

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
1) What version of V2Ray are you using?
v2ray-v2.2.1-linux-64以后版本

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
2) What your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
opera(chrome核心)代理访问，服务器端后台运行

3) 你看到的不正常的现象是什么？
3) What did you see?
服务器端退出，目前只能退回2.2.1，可稳定运行，测试了多个版本均有此情况

4) 你期待看到的正确表现是怎样的？
4) What do you expected to see instead?
正常运行

5) 请附上你的配置文件。
5) Please attach your configuration file.
{
  "port": 63000,
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "人工隐藏",
          "level": 1,
          "alterId": 64
        }
      ],
      "detour": {
        "to": "detour"
      }
    },
    "streamSettings": {
      "network": "kcp"
  }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "inboundDetour": [
    {
      "protocol": "vmess",
      "port": "50000-50200",
      "tag": "detour",
      "settings": {},
        "streamSettings": {
          "network": "kcp"
        },
      "allocate": {
        "strategy": "random",
        "concurrency": 2,
        "refresh": 5
      }
    }
  ],
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  },
  "transport": {
    "kcpSettings": {
      "uplinkCapacity": 10,
      "downlinkCapacity": 100,
      "congestion":true
    }
  }
}

**Comment by v2ray** [comment]
如果用的是 Systemd 系统，用 `journalctl -u v2ray` 看一下退出的原因。

**Comment by helloyan** [comment]
非systemd系统

**Comment by DarienRaymond** [comment]
应该已经修复
