### ISSUE TITLE
有什么办法能不重启程序，让某个账号失效

### ISSUE THREAD

**Issue by bbhxwl** [v2ray/v2ray-core#3022]
想做个流量控制到期限制的东西，现在好像只能修改配置文件，重启程序，实现账号不可用。

**Comment by Ph0enixxx** [comment]
不同账号开不同端口 用iptables进行管理

**Comment by bbhxwl** [comment]
> 不同账号开不同端口 用iptables进行管理

多谢，是个思路，不过就需要做个管理系统，管理多个设备的这些端口都同步配置是吧？
