### ISSUE TITLE
千万不要安装腾讯的Tim，否则断流断死人！！

### ISSUE THREAD

**Issue by jesusjsc** [v2ray/v2ray-core#3024]
千万不要安装腾讯的Tim，否则断流断死人！！

严重怀疑腾讯的Tim后台的qq保护进程偷偷搞事！

卸载tim后，断流情况就消失了。

目前没有测试qq，预计差不多，也会出现断流。

有测试过其它应用的请留言，谢谢

**Comment by dongqiceo** [comment]
多测几遍，能复现才是真的

**Comment by shuidaan** [comment]
2022/07/03 14:50:49 [Warning] [754974828] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > EOF
2022/07/03 14:50:49 [Warning] [754974828] proxy/http: failed to read response from www.gstatic.com > io: read/write on closed pipe
2022/07/03 14:52:55 [Warning] [3551688414] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > EOF
2022/07/03 14:52:55 [Warning] [3551688414] proxy/http: failed to read response from www.gstatic.com > io: read/write on closed pipe

**Comment by ouguajian** [comment]
我一直都是用Tim

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Mistofs** [comment]
人可以住在中国，但是为什么要和中国人说话。至少你可以安装代理在不使用与共产党有关系的另一台设备上
