### ISSUE TITLE
求api的详细资料

### ISSUE THREAD

**Issue by denwork** [v2ray/v2ray-core#3026]
如何通过api维护内部的所有资源，比如添加socks inbound outbound等的说明，或者具体的例子。最好是go语言的谢谢！
现在我想对现有的v2ray修改socks5的代理出口，不管怎样都不行。尝试了AddOutbound 和AlterOutbound都无法成功。不知道里面的内容该怎么和配置里面的内容对应起来。

**Comment by fish8848-chen** [comment]
请问，你现在实现了吗？同问

**Comment by kidcool-gxh** [comment]
同问，楼主实现了么
