### ISSUE TITLE
v2ran用，有大神帮忙看看怎么回事吗

### ISSUE THREAD

**Issue by chezheng** [v2ray/v2ray-core#3042]
2022/07/15 09:09:39 [Warning] [2994163263] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws://cm.nwncd.com:20706/amdyes):  > read tcp 192.168.118.51:63243->36.139.154.167:20706: i/o timeout transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws://cm.nwncd.com:20706/amdyes):  > read tcp 192.168.118.51:63251->36.139.154.167:20706: i/o timeout transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws://cm.nwncd.com:20706/amdyes):  > read tcp 192.168.118.51:63261->36.139.154.167:20706: i/o timeout transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws://cm.nwncd.com:20706/amdyes):  > read tcp 192.168.118.51:63273->36.139.154.167:20706: i/o timeout transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws://cm.nwncd.com:20706/amdyes):  > read tcp 192.168.118.51:63286->36.139.154.167:20706: i/o timeout] > common/retry: all retry attempts failed
发送请求时出错。

**Comment by chezheng** [comment]
2022/07/15 09:42:36 [Warning] [4101919572] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2022/07/15 09:42:36 [Warning] [1648320942] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2022/07/15 09:42:36 [Warning] [4056582127] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2022/07/15 09:42:36 [Warning] [3765130587] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2022/07/15 09:42:36 [Warning] [1667724103] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)

**Comment by VicaYang** [comment]
> failed to read response header > websocket: close 1000 (normal)
这个有可能是因为客户端版本低的原因。最好能看到access.log的内容。看不到的话先试试更新客户端

**Comment by chezheng** [comment]
已经是5.29的客户端了，access.log哪里可以看到
