### ISSUE TITLE
VPS(vultr)|V2Ray 小白一键配置，连不上外网

### ISSUE THREAD

**Issue by P0sterboi** [v2ray/v2ray-core#3045]
请用足够的信息回答所有问题。所有不遵循此模板的问题将立即关闭。

如果您不确定您的问题是否真的是V2Ray中的一个bug，请[在此处]进行讨论(https://github.com/v2fly/discussion/issues)首先。

1） 您使用的V2Ray版本是什么（如果您在服务器和客户端上部署了不同的版本，请明确指出）？
   服务器：当前 V2Ray 版本: v4.45.2  /  当前 V2Ray 管理脚本版本: v3.57
   客户端：V2Ray v5.29

2） 您使用V2Ray的场景是什么？E、 例如，通过Socks/VMess代理在Chrome上观看YouTube视频。
     通过Vmess代理在Chrome上观看YouTube视频

3） 你看到了什么？（请详细描述，如超时、假TLS证书等）
2022/07/21 12:00:59 [Warning] [3143284735] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [dial tcp 207.xxx.74.xxx:xxx: operation was canceled] > common/retry: all retry attempts failed

4） 你的期望是什么？
     能够正常浏览youtube、google

5） 请附上您的配置文件（**在提交此问题之前屏蔽IP地址**）。
服务器配置：
"inbounds": [
		{
			"port": xxx,
			"protocol": "vmess",
			"settings": {
				"clients": [
					{
						"id": "2039xxxx-e9f4-4c55-9702-7bb11047xxxx",
						"level": 1,
						"alterId": 0
					}
				]
			},
			"streamSettings": {
				"network": "tcp"
			},
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			}
		}
		//include_ss
		//include_socks
		//include_mtproto
		//include_in_config
		//
	],

客户端配置：
"outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "207.xxx.74.xxx",
            "port": xxx,
            "users": [
              {
                "id": "2039xxxx-e9f4-4c55-9702-7bb11047xxxx",
                "alterId": 0,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ]
      },

6） 请附上错误日志，如果文件较大，请特别附上底线。错误日志文件通常位于`/var/log/v2ray/Error。登录Linux。
服务器错误日志：
2022/07/21 11:18:18 [Warning] V2Ray 4.45.2 started
2022/07/21 11:45:27 [Warning] V2Ray 4.45.2 started

客户端错误日志：
2022/07/21 12:00:59 [Warning] [3143284735] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [dial tcp 207.xxx.74.xxx:xxx: operation was canceled] > common/retry: all retry attempts failed

7） 请附上访问日志。访问日志通常位于“/var/log/v2ray/Access”。登录Linux。
2022/07/21 11:45:44 183.11.203.117:1209 accepted tcp:www.bing.com:443 [direct]
2022/07/21 11:49:44 183.11.203.117:2375 rejected  proxy/vmess/encoding: failed to read request header > read tcp 207.148.74.127:37->183.11.203.117:2375: i/o timeout
2022/07/21 11:52:52 116.24.153.76:63135 rejected  proxy/vmess/encoding: failed to read request header > read tcp 207.148.74.127:37->116.24.153.76:63135: i/o timeout
2022/07/21 12:00:39 183.11.203.117:2749 accepted tcp:push.services.mozilla.com:443 [direct]
2022/07/21 12:00:39 183.11.203.117:2771 accepted tcp:www.bing.com:443 [direct]
2022/07/21 12:00:39 183.11.203.117:2776 accepted tcp:settings-win.data.microsoft.com:443 [direct]
2022/07/21 12:00:41 183.11.203.117:2818 accepted tcp:detectportal.firefox.com:80 [direct]
2022/07/21 12:00:41 183.11.203.117:2819 accepted tcp:firefox.settings.services.mozilla.com:443 [direct]
2022/07/21 12:00:42 183.11.203.117:2827 accepted tcp:detectportal.firefox.com:80 [direct]

8） 其他配置（如Nginx）和日志。

9） 如果V2Ray没有运行，请附加来自“-test”的输出。

10） 如果V2Ray服务未运行，请附上日志。

请在提交之前审查您的问题。

**Comment by juceyj** [comment]
same

**Comment by P0sterboi** [comment]
> same

应该是小白式的tcp搭建方法已经默认被墙了，我后面换成了 websocket + tls 就配置成功了，撑到了国庆前，现在ws+tls也不好用了，可能得用NGINX伪装成网站了，我现在还在学怎么伪装流量

**Comment by juceyj** [comment]
> > same
> 
> 应该是小白式的tcp搭建方法已经默认被墙了，我后面换成了 websocket + tls 就配置成功了，撑到了国庆前，现在ws+tls也不好用了，可能得用NGINX伪装成网站了，我现在还在学怎么伪装流量

救命，太难了

**Comment by P0sterboi** [comment]
> > > same
> > 
> > 
> > 应该是小白式的tcp搭建方法已经默认被墙了，我后面换成了 websocket + tls 就配置成功了，撑到了国庆前，现在ws+tls也不好用了，可能得用NGINX伪装成网站了，我现在还在学怎么伪装流量
> 
> 救命，太难了
没办法，我前几天查了一下，从10.3开始443和80端口的tls流量大规模被封锁了，常规的tls搭建已经行不通了（因为443是tls的默认端口），我还在尝试用cdn代理修复，不知道能不能行.

**Comment by P0sterboi** [comment]
> > > same
> > 
> > 
> > 应该是小白式的tcp搭建方法已经默认被墙了，我后面换成了 websocket + tls 就配置成功了，撑到了国庆前，现在ws+tls也不好用了，可能得用NGINX伪装成网站了，我现在还在学怎么伪装流量
> 
> 救命，太难了

维持ws+tls 的配置，用cdn复活了这个节点，443端口被封了也没事，可以复活，已经成功搭好梯子了。
