### ISSUE TITLE
性能测试的瓶颈

### ISSUE THREAD

**Issue by WooDragon** [v2ray/v2ray-core#305]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please answer the following questions before submitting your issue. Thank you.

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
1) What version of V2Ray are you using?
2.7.1

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
2) What your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
内网实验环境，两台万兆服务器通过交换机互联
客户端通过iptables转发至v2ray代理，保护到服务端的数据传输

3) 你看到的不正常的现象是什么？
3) What did you see?
CPU没有用满，但是使用iperf测试时，即便增加线程，性能也不再（线性的）增加。
瓶颈在5.31Gbps左右，iperf线程8个。线程16个也只是到5.37Gbps左右。
CPU仍有20%多的空闲。
![image](https://cloud.githubusercontent.com/assets/2383220/20820627/89a3bf14-b877-11e6-970f-e428211430f3.png)

4) 你期待看到的正确表现是怎样的？
4) What do you expected to see instead?
性能线性增加直到耗尽资源

5) 请附上你的配置文件。
5) Please attach your configuration file.

客户端
```
{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound":{
  "protocol": "dokodemo-door",
    "port": 1080,
    "settings": {
        "network": "tcp",
        "timeout": 0,
        "followRedirect": true,
        "address": ""
        }
  },
 "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "10.0.5.181",
          "port": 10800,
          "users": [
            { "id": "22f8911f-77bb-44d6-bba8-de6045ed65db",
              "alterId": 64
            }
          ]
        }
      ]
    }
  }
}
```

服务端
```
{
    "log": {
        "access": "/var/log/v2ray/access.log",
        "error": "/var/log/v2ray/error.log",
        "loglevel": "warning"
    },
    "inbound": {
        "port": 10800,
        "protocol": "vmess",
        "settings": {
            "clients": [
                {
                  "id": "22f8911f-77bb-44d6-bba8-de6045ed65db",
                  "level": 1,
                  "alterId": 64
                }
            ]
        }
    },
    "outbound": {
        "protocol": "freedom",
        "settings": {}
    }
}
```

iptables规则
```
iptables -t nat -N v2ray
iptables -t nat -A v2ray -p tcp --dport 10800 -j RETURN
iptables -t nat -A v2ray -p tcp -d 10.0.5.181 -j REDIRECT --to-ports 1080
iptables -t nat -A OUTPUT -p tcp -j v2ray

```

**Comment by WooDragon** [comment]
另外，单台服务器承载量不足的情况下（如果目前5G上下是瓶颈的话），vmess能通过 LVS 做负载均衡吗？
（请原谅懒惰的我，还没做实验先了解一下^_^）

**Comment by WooDragon** [comment]
或能否在vmess中提供轻量级或者说极端追求性能的连接能力，场景是不需要应对墙而是国内运营商劫持，只需要进行简单的流量混淆即可。

**Comment by windmgc** [comment]
@WooDragon 有试过关掉connectionReuse之后的性能跟原来有什么区别吗

**Comment by WooDragon** [comment]
@windmgc 
配置文件中这样添加，应该对的吧？
```
"transport": {
  "tcpSettings": {
    "connectionReuse": false
  }
  }
```
测试了下，8和16线程结果分别为5.34和5.41Gbps，略有增加，不过不明显，CPU富裕量差不多。

**Comment by WooDragon** [comment]
增加到24线程也不再有提高了。

**Comment by windmgc** [comment]
恩 证明不是vmess导致的问题，我感觉v2ray的dokodemo-door在tcp的连接方面有点问题，但不能确定

**Comment by wtlusvm** [comment]
向大佬低头，10G网卡，天哪，贫民想都不敢想的事情

**Comment by WooDragon** [comment]
@windmgc 好查吗？我想办法用socks测一下看看……
@wtlusvm 个人用的话我自己自然也是买不起的……拿公司的服务器测测看，好用的话就跑点业务顺便翻个墙……

**Comment by v2ray** [comment]
设计的时候没考虑过这么大的带宽，V2Ray 内部有一些固定大小的缓冲区，可能会成为速度瓶颈。如果有需求我可以重写那部分代码。

负载均衡理论上是可以的，只要 VMess 的 ID 和 AlterId 的值对应即可。

connectionReuse 在这个测试中没什么影响，因为 iPerf 只用了指定数量的连接，并且运行期间不关闭连接。

**Comment by WooDragon** [comment]
@v2ray 
膜拜大神，其实 5Gbps 多的性能已经非常不错了，对我来说也是够用的，只是觉得它可以做到更好。

我目前感觉 v2ray 潜力无限啊，我翻完文档觉得这个思路如果只做翻墙工具根本就是大材小用……

所以想看下核心组件能在性能上达到什么程度，如果有需要的话，我应该最大可以组出单机 40G 的测试环境，不过 CPU 的话可能只能做到裸跑到接近 40G。

**Comment by v2ray** [comment]
请问你的测试环境，单机 CPU 有多少个核？

**Comment by WooDragon** [comment]
@v2ray 
目前使用的是一颗 4 核心 CPU，E3-1230 v3 的服务器

如果有需要的话也可以换成 2 颗 6 核心 E5-2620 v3 的服务器进行测试。

**Comment by v2ray** [comment]
增加下载线程但速度没有提高的原因大概是 TCP 缓冲区满了 V2Ray 没有及时读出内容。下一个版本会提高读取的速度，到时候可以再试一下。

**Comment by v2ray** [comment]
v2.9 中包含了一些改进，但我没办法测试有没有效果。

一些测试的建议：

1. 在 VMess inbound 中设置 level = 1，这样可以在每次读到 TCP socket 的时候少两次 syscall。
2. 不使用 iptables，dokodemo-door 可以设置一个固定的目标地址，如 "address": "127.0.0.1", "port": 5201
  * 注意把 routing 部分删掉，强制转发 127.0.0.1 的流量
3. 使用 VMess 和 freedom 作对比测试。我不认为瓶颈在 VMess 的加密解密上，但不妨一试。

**Comment by windmgc** [comment]
@v2ray 所以如果我有一个并发连接数很高的环境，而且需要频繁开启关闭tcp连接，在v2ray的哪些方面会影响性能？我正好有一个这样的环境，发现关掉connectionReuse会好很多

**Comment by WooDragon** [comment]
@v2ray 不用 iptables 直接用 dokodemo-door, freedom 出去测试看瓶颈应该是消失了，基本把 E3 CPU 跑满，可以怼到 15G 。

![qq 20161205112400](https://cloud.githubusercontent.com/assets/2383220/20872898/575e5d1c-badd-11e6-8273-a7641bb436af.jpg)
![qq 20161205112422](https://cloud.githubusercontent.com/assets/2383220/20872903/66d6f6b4-badd-11e6-8c81-376aa93a8ad4.jpg)

稍后再测试一下 vmess，以及用 E5 CPU对比下。

**Comment by WooDragon** [comment]
@v2ray 通过 vmess 以后，吞吐量骤减，而 CPU 还有富余。

![qq 20161205115117](https://cloud.githubusercontent.com/assets/2383220/20873311/2b21ad72-bae1-11e6-8779-b670290c3d6e.jpg)

![qq 20161205115143](https://cloud.githubusercontent.com/assets/2383220/20873318/36bea2ac-bae1-11e6-84f8-582bec71f5dd.jpg)

![qq 20161205115209](https://cloud.githubusercontent.com/assets/2383220/20873331/53ad2aa0-bae1-11e6-829e-591c50534077.jpg)

**Comment by v2ray** [comment]
基本可以判断现在的瓶颈在加密解密了，AES-CFB 的吞吐量在 200 MB/s 左右，再加上一些其它的损耗，上图的数值看上去可以接受。

**Comment by WooDragon** [comment]
@v2ray 
更强的 CPU 会有所改善吗？

以及 vmess 能提供更丰富的选项么，比如运营商劫持之类的，哪怕 RC4MD5 甚至 BASE64 都能搞定的事情，上 AES 还是太重了。

**Comment by v2ray** [comment]
从 [benchmark](https://www.servethehome.com/intel-xeon-e3-1220-v3-benchmark-review-haswell-xeon/) 上看 E5 比 E3 在 AES 性能上好了不少，6.2 GB/s vs 2.8 GB/s，但我不确定在实际使用中有没有效果。

会考虑增加性能更好的加密方式。

**Comment by v2ray** [comment]
@windmgc 请重新开一个 issue 并附上你的配置文件，如果有测试数据更好。

**Comment by kcschan** [comment]
如果有AES-NI指令，128位的AES在E3-1231v3这样的4核心处理器上应该能有略微比5GB/s高一些的性能。

因为AES-NI的关系，RC4MD5可能反而会比AES慢一半左右。
BASE64会有把报文体积增加三分之一的缺点。

例子：
https://zoompf.com/blog/2014/11/ssl-performance-diary-3-optimizing-data-encryption

Darien Raymond <notifications@github.com>于2016年12月5日周一 下午6:37写道：

**Comment by WooDragon** [comment]
@v2ray 
在双路 E5 上测试，吞吐怼到了 8Gbps 多，非常给力。
另外发现一个不知道是不是算异常的地方，服务端的 CPU 消耗远高于客户端，接收端的 CPU 已经被吃完了，发送端几乎还有一半的 CPU 富裕。
发送端 CPU 和吞吐如下
![9ab 1v5dlva2mqa ww 61k](https://cloud.githubusercontent.com/assets/2383220/20918669/35d18a88-bbd3-11e6-896e-c0d2cb97b75d.png)
![4 ya7bab83bo6 sl9 g9v](https://cloud.githubusercontent.com/assets/2383220/20918718/66da5b78-bbd3-11e6-99d1-18488e17576d.png)
接收端CPU和吞吐如下
![bajn4nc 0yy t cf k o](https://cloud.githubusercontent.com/assets/2383220/20918780/a5306188-bbd3-11e6-87ca-b62c000db3f7.png)
![vpd 45 kveupur0d az dy](https://cloud.githubusercontent.com/assets/2383220/20918782/a6874074-bbd3-11e6-9ec8-868bf1740d9b.png)

@kcschan 感谢解答，长姿势了，我主要是举个栗子，希望有一种以性能为主要考量的选项，来应对不那么高级的审查~

**Comment by v2ray** [comment]
嗯，接收端还有一定的优化空间。

**Comment by wtlusvm** [comment]
@kcschan 感谢~长姿势了，原来AES-256和AES-128差别还是挺大的（有了AES-NI差别更大了）
@WooDragon 我注意到服务端和客户端的Iperf的CPU占用也差了好多，是不是iperf的问题？

**Comment by WooDragon** [comment]
@wtlusvm iperf 的 CPU 感觉是正常的，刚刚试了试 20G 网络，E3 CPU 单跑 iperf，吞吐 18.5Gbps 时，客户和服务端CPU分别为176%和398%上下。
试验时因为接收端有个 v2ray 占了 1800% 多的 CPU 时，iperf 因为需要和 v2ray 互相争抢 CPU 时间，占用率更高应该是可以理解的。

**Comment by wtlusvm** [comment]
@WooDragon 嗯这么看来Iperf占用是正常的，主要问题还是在client上~

**Comment by agzfan** [comment]
AES-128比chacha20 cpu高一倍

就我自己接触过的服务器,和自己用的超微
bios默认cpu硬解aes是关闭
99%的服务器管理员不会主动去开aes
所以买到的99%vps是没有硬件aes

**Comment by ToutyRater** [comment]
@WooDragon 仰望高端玩家。突然很想知道shadowsocks的性能怎么样，楼主有测试过吗

**Comment by v2ray** [comment]
如果性能瓶颈在加密部分的话， Shadowsocks 和 VMess 目前是一样的，用的都是 AES-128-CFB 加密方式。

**Comment by WooDragon** [comment]
@agzfan 看了看现在主流的虚拟化技术都支持 AES-NI 了的，理论上应该会比 CHACHA20 性能好啊……我这的机器默认都是开着的。
@ToutyRater 有空跑一下试试，Shadowsocks 网上有很多人拿来卖的，我猜性能应该不错吧。

**Comment by v2ray** [comment]
2.10 提供了三个新的加密选项，针对你的场景，可以试一下 `"none"` 和 `"aes-128-gcm"`。前者是不加密，和 freedom 相当（速度方面应该会有损失达不到 freedom 那么快），后者比之前版本的加密方式要快，应该可以看到明显的速度提升。

**Comment by v2ray** [comment]
先关了，有问题请新开一个 issue.
