### ISSUE TITLE
文档中 proxySettings 问题

### ISSUE THREAD

**Issue by ToutyRater** [v2ray/v2ray-core#306]
version: v2.8

在[文档](https://www.v2ray.com/chapter_02/01_overview.html )中关于 proxySettings 的说明是这样的：
> * proxySettings: 传出代理配置。
>   - tag: 当指定另一个传出协议的标识时，此传出协议发出的数据，将被转发至所指定的传出协议发出。

这段说明我琢磨了一段时间仍然觉得不通畅。以下是我客户端配置传出部分（路由已配置传出为 NewArukasTCP）：
```javascript
  "outboundDetour": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "45.*.*.*",
            "port": xxxx,
            "users": [
              {
                "alterId": 31,
                "id": "XXXX"
              }
            ]
          }
        ]
      },
      "tag": "USTCP"
    },
    {
      "proxySettings": {
        "tag": "USTCP"
      },
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "153.*.*.*",
            "port": xxxx,
            "users": [
              {
                "alterId": 31,
                "id": "XXXX"
              }
            ]
          }
        ]
      },
      "tag": "NewArukasTCP"
    }
  ]
```
按照说明，我的理解是：
`此传出协议`为 NewArukasTCP ，`指定的传出协议`为 USTCP ，数据将按这样路径发送： **PC --> NewArukasTCP --> USTCP --> web sever** 。
然而，我通过 wireshark 抓包发现 PC 上的数据包都是发往 45.\*.\*.\* 也就是 USTCP：
![wireshark](https://cloud.githubusercontent.com/assets/20978410/20866870/59619f4c-ba2f-11e6-9d1c-84916340ce7b.png)
与此同时，v2ray log 有这样的输出：
>  [Info]VMess|Outbound: Tunneling request to tcp:153.\*.\*.\*:xxxx via tcp:45.\*.\*.\*:xxxx
 [Info]Socks: TCP Connect request to tcp:api.github.com:443
 [Info]DefaultDispatcher: Taking detour [NewArukasTCP] for [tcp:api.github.com:443].
 [Info]Internet: Proxying outbound connection through: USTCP

并且通过 [whatismyip](https://www.whatismyip.com/) 查询得：
![ip](https://cloud.githubusercontent.com/assets/20978410/20866942/146def6a-ba31-11e6-9c3e-acf875e70813.png)
以上几点说明了数据实际上是以 **PC -->USTCP  --> NewArukasTCP --> web sever** 这样的路径发送的，与我看文档理解的  PC --> NewArukasTCP --> USTCP --> web sever 并不一样。
造成这样的问题的原因不知道是我理解不对还是文档确实写错了？

**Comment by v2ray** [comment]
`此传出协议为 NewArukasTCP ，指定的传出协议为 USTCP`，这个理解是对的。

`此传出协议发出的数据，将被转发至所指定的传出协议发出`，这个转发发生在本地，于是由 NewArukasTCP 发出（到 153.x.x.x）的数据，被全部转给了 USTCP，然后 USTCP 把所有数据发给自己的服务器（45.x.x.x）。如果 45.x.x.x 的出口是 freedom 的话，这个 freedom 会拿到发送到 NewArukasTCP 的指示，再将数据发给原本 NewArukasTCP 指定的服务器。

简而言之：PC -> USTCP -> NewArukasTCP -> web server。

**Comment by ToutyRater** [comment]
明白了。原来关键在于`转发发生在本地`，一开始没有这样子想造成了误解。
