### ISSUE TITLE
[求助]配置文件经过test检查没有发现问题，但服务无法正常启动，请求给予一些排查方向的帮助。

### ISSUE THREAD

**Issue by SalvadorLyons** [v2ray/v2ray-core#3061]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
服务器：当前 V2Ray 版本: v5.1.0 ubuntu 20.04

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
以WebSocket + TLS + Web的形式访问网络

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
使用test检查过配置文件路径以及格式，配置文件无问题，但是无法正常启动服务

systemctl status v2ray的结果如下：

Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
Drop-In: /etc/systemd/system/v2ray.service.d
─10-donot_touch_single_conf.conf
Active: failed (Result: exit-code) since Wed 2022-09-07 22:56:41 CST; 1min 59s ago
Docs: https://www.v2fly.org/
Process: 5445 ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json (code=exited, status=2)
Main PID: 5445 (code=exited, status=2)
CPU: 29ms
Sep 07 22:56:41 valuable-pod-1.localdomain systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
Sep 07 22:56:41 valuable-pod-1.localdomain systemd[1]: Stopped V2Ray Service.
Sep 07 22:56:41 valuable-pod-1.localdomain systemd[1]: v2ray.service: Start request repeated too quickly.
Sep 07 22:56:41 valuable-pod-1.localdomain systemd[1]: v2ray.service: Failed with result 'exit-code'.
Sep 07 22:56:41 valuable-pod-1.localdomain systemd[1]: Failed to start V2Ray Service.

4) 你期待看到的正确表现是怎样的？
正常启动服务

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
服务器端配置:
```javascript
    {
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": '$port',
    "listen": "127.0.0.1",
    "protocol": "vmess",
    "settings": {
      "decryption":"none",
      "clients": [
        {
          "id": '"\"$uuid\""',
          "alterId":0
        }
      ]
    },
   "streamSettings":{
      "network": "ws",
      "wsSettings": {
           "path": '"\"$path\""'
      }
   }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {
      "decryption":"none"
    }
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {
        "decryption":"none"
      },
      "tag": "blocked"
    }
  ], 
  "routing": {
    "strategy": "rules",
    "settings": {
      "decryption":"none",
      "rules": [
        {
          "type": "field",
          "ip": [ "geoip:private" ],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}
```

客户端配置:
```javascript
    // 暂时不需要客户端
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
服务器端错误日志:

```javascript
   2022/09/07 22:58:19 [Warning] V2Ray 5.1.0 started
```

客户端错误日志:

```javascript
    // 暂时不涉及到客户端
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

```javascript
    //此文件没有内容 
```

8) 其它相关的配置文件（如 Nginx）和相关日志。
```
server {
	listen 80;
	server_name "$domainName";
	return 301 https://"'$host'""'$request_uri'";

}
server {
	listen 443 ssl http2 default_server;
	listen [::]:443 ssl http2 default_server;
	server_name "$domainName";

	ssl_certificate $ssl_dir/v2ray.crt;
	ssl_certificate_key $ssl_dir/v2ray.key;
	ssl_ciphers EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+ECDSA+AES128:EECDH+aRSA+AES128:RSA+AES128:EECDH+ECDSA+AES256:EECDH+aRSA+AES256:RSA+AES256:EECDH+ECDSA+3DES:EECDH+aRSA+3DES:RSA+3DES:!MD5;
	ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;

	root /usr/share/nginx/html;
	
	location "$path" {
		proxy_redirect off;
		proxy_pass http://127.0.0.1:"$port";
		proxy_http_version 1.1;
		proxy_set_header Upgrade "'"$http_upgrade"'";
		proxy_set_header Connection '"'upgrade'"';
            	proxy_set_header Host "'"$host"'";
            	proxy_set_header X-Real-IP "'"$remote_addr"'";
            	proxy_set_header X-Forwarded-For "'"$proxy_add_x_forwarded_for"'";
	}

}
```

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。
```
v2ray test
V2Ray 5.1.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19 linux/amd64)
A unified platform for anti-censorship. Using config from STDIN
```

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。
```
v2ray.service: Failed with result 'exit-code'.
v2ray.service: Scheduled restart job, restart counter is at 3.
Stopped V2Ray Service.
Started V2Ray Service.
 flag provided but not defined: -config
 Usage of /usr/local/bin/v2ray:
v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
v2ray.service: Failed with result 'exit-code'.
v2ray.service: Scheduled restart job, restart counter is at 4.
Stopped V2Ray Service.
Started V2Ray Service.
 flag provided but not defined: -config
 Usage of /usr/local/bin/v2ray:
v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
v2ray.service: Failed with result 'exit-code'.
v2ray.service: Scheduled restart job, restart counter is at 5.
Stopped V2Ray Service.
v2ray.service: Start request repeated too quickly.
v2ray.service: Failed with result 'exit-code'.
Failed to start V2Ray Service.
Started V2Ray Service.
 flag provided but not defined: -config
 Usage of /usr/local/bin/v2ray:
v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
v2ray.service: Failed with result 'exit-code'.
v2ray.service: Scheduled restart job, restart counter is at 1.
Stopped V2Ray Service.
Started V2Ray Service.
 flag provided but not defined: -config
 Usage of /usr/local/bin/v2ray:
v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
v2ray.service: Failed with result 'exit-code'.
v2ray.service: Scheduled restart job, restart counter is at 2.
Stopped V2Ray Service.
Started V2Ray Service.
 flag provided but not defined: -config
 Usage of /usr/local/bin/v2ray:
v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
v2ray.service: Failed with result 'exit-code'.
v2ray.service: Scheduled restart job, restart counter is at 3.
Stopped V2Ray Service.
Started V2Ray Service.
 flag provided but not defined: -config
 Usage of /usr/local/bin/v2ray:
v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
v2ray.service: Failed with result 'exit-code'.
v2ray.service: Scheduled restart job, restart counter is at 4.
Stopped V2Ray Service.
Started V2Ray Service.
 flag provided but not defined: -config
 Usage of /usr/local/bin/v2ray:
v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
v2ray.service: Failed with result 'exit-code'.
v2ray.service: Scheduled restart job, restart counter is at 5.
Stopped V2Ray Service.
v2ray.service: Start request repeated too quickly.
v2ray.service: Failed with result 'exit-code'.
Failed to start V2Ray Service.
```

**Comment by wenge110110** [comment]
一样的问题 报错
Process: 5445 ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json (code=exited, status=2)
Main PID: 5445 (code=exited, status=2)

**Comment by SalvadorLyons** [comment]
> 一样的问题 报错
> Process: 5445 ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json (code=exited, status=2)
> Main PID: 5445 (code=exited, status=2)

感觉有点像这个问题flag provided but not defined: -config 我打算指定版本试试

**Comment by SalvadorLyons** [comment]
> rm -rf /etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf
> systemctl daemon-reload
> systemctl restart v2ray

在我的服务器环境下，这样没能解决这个问题。你已经可以了吗？你的 v2ray版本是多少呢？

**Comment by wenge110110** [comment]
5.1.0  centos7

**Comment by wenge110110** [comment]
处理方式1：
rm -rf /etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf
systemctl daemon-reload
systemctl restart v2ray
处理方式2：
vi /etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf
把ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json
改为ExecStart=/usr/local/bin/v2ray run -config /usr/local/etc/v2ray/config.json
systemctl daemon-reload
systemctl restart v2ray

**Comment by SalvadorLyons** [comment]
> 处理方式1：
> rm -rf /etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf
> systemctl daemon-reload
> systemctl restart v2ray
> 处理方式2：
> vi /etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf
> 把ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json
> 改为ExecStart=/usr/local/bin/v2ray run -config /usr/local/etc/v2ray/config.json
> systemctl daemon-reload
> systemctl restart v2ray

由于我们的环境不一致，所以我尝试用该方案，并没有解决我的问题，其他小伙伴可以试一试。折腾了好几天了，实在折腾不动，最终我采取的方案为，手动指定安装版本为4.45.2，绕过无法启动的问题。

**Comment by wenge110110** [comment]
你写的问题不就是5.1.0吗

**Comment by SalvadorLyons** [comment]
> 你写的问题不就是5.1.0吗

是啊，但是一直有问题我就放弃用5.1.0了。应该是我配置哪里没处理好。

**Comment by wenge110110** [comment]
留个联系方式私聊 https://t.me/vince12138
