### ISSUE TITLE
当 streamSettings.network 为 kcp 时使用传出代理无法联网

### ISSUE THREAD

**Issue by ToutyRater** [v2ray/v2ray-core#307]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please answer the following questions before submitting your issue. Thank you.

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
1) What version of V2Ray are you using?
v2.8
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
2) What your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
如使用 Chrome 通过 Socks/VMess 浏览网页
3) 你看到的不正常的现象是什么？
3) What did you see?
当配置像下面这样时无法联网（路由已配置传出为 NewArukas，服务器的 inbound 只有 kcp 和 tcp 的区别，其它如 port, id 等均一致）：
```javascript
  "outboundDetour": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "45.*.*.*",
            "port": xxxx,
            "users": [
              {
                "alterId": 31,
                "id": "XXXX"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "xcp" //此处 xcp 表示 tcp 或 kcp 任意一种情况
      },
      "tag": "US"
    },
    {
      "proxySettings": {
        "tag": "US"
      },
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "153.*.*.*",
            "port": xxxx,
            "users": [
              {
                "alterId": 31,
                "id": "XXXX"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "kcp" // 在这里值为 kcp 时会无法联网，tcp 正常
      },
      "tag": "NewArukas"
    }
  ]
```
如打开 Google 时：
![error](https://cloud.githubusercontent.com/assets/20978410/20867216/2563c6ae-ba37-11e6-819a-6277645f8c97.png)

4) 你期待看到的正确表现是怎样的？
4) What do you expected to see instead?
当 streamSettings.network 为 kcp 时能够使用传出代理功能
5) 请附上你的配置文件。
5) Please attach your configuration file.

**Comment by v2ray** [comment]
这是一个问题，设计的时候没考虑到。由于 freedom 不支持 kcp，于是使用 "proxy": {} 的 outbound 也不能使用 kcp。之后会修复这个问题。

**Comment by v2ray** [comment]
下一版本会支持这个设置。需要中转服务器中的 freedom 也使用 network = "kcp" 才可以正常通信。也就是一个连接的两端使用同样的 network。

由于通常 freedom 都会使用 tcp 作为传输方式，所以这个配置意义不大。使用中转服务器的话，还是都用 tcp 好了。
