### ISSUE TITLE
Setting limit for number of connection per UUID?

### ISSUE THREAD

**Issue by theSadra** [v2ray/v2ray-core#3083]
Hello 
Firstly lots of thank for developing such a great and useful software to providing free internet for people around the world.
Nowadays in Iran, we have a fully censored internet that limited by Islamic regime.
I have runed a V2ray server and I need to limit number of connections per UUID for example limiting for 100 connection per uuid
some times my server handles 300 people and overload happens on my server by the way, the quality of service really downs.

is there any way to do this limit?
or I have to edit the source code by my self to providing this feature?
- If yes, how can I do this?

**Comment by mohsentx** [comment]
Hello
I also need this training

**Comment by net-pioneer** [comment]
https://github.com/net-pioneer/v2ray-connection-limiter

**Comment by arsoltani72** [comment]
hi there hope you doing well

**Comment by 5J2J** [comment]
> https://github.com/net-pioneer/v2ray-connection-limiter

How do I set a default port on this limiter? All users are using 443.
I am using: v2ray+ws+tls+nginx
Currently it only works when I use the default port, but I need it to also work when I use v2ray+ws+tls+nginx.
