### ISSUE TITLE
Implementation v2ray-plugin into iOS App

### ISSUE THREAD

**Issue by FetFrumos** [v2ray/v2ray-core#3087]
I need to add v2ray to my ios app. Unfortunately, I didn't find any information at all about such implementation. 
 I found this [library](https://github.com/Tai7sy/v2ray_mobile_lib)  - but it is not supporting now.
 Could someone share information (links, instructions and etc) on how to correctly add support v2ray-plugin to the app for iOS?
Thanks and have a good day!

**Comment by Shengdanhu89** [comment]
This app: shadowrocket may help you

**Comment by FetFrumos** [comment]
@Shengdanhu89  I found this repo - https://github.com/Shadowsocks-Help/ios
but there is only ipa without code. maybe someone can suggest an open source repository?

**Comment by sbh96** [comment]
same issue

**Comment by sbh96** [comment]
@FetFrumos  https://github.com/sail-tunnel/sail
you can use this project but its use leaf as library
leaf is now stable verstion
and i cant use vmess with alterid (v2ray) in leaf 
please check leaf if you find a protocol we can use v2ray as server and leaf as ios client tel me

**Comment by FetFrumos** [comment]
Hello @sbh96 
did you find anything?

**Comment by sbh96** [comment]
> Hello @sbh96 did you find anything?

Hi
[Leaf](https://github.com/eycorsican/leaf) 
But it isnt support vmess with alterid!!!!
Please v2ray team help to leaf to complite vmess suppprt for ios in leaf @vcptr
[Issue](https://github.com/eycorsican/leaf/issues/322)

**Comment by Aronablade** [comment]
for ios this apps are free and support majority of items , fairvpn , napsternet , rockettool

**Comment by FetFrumos** [comment]
Hi @Aronablade,
maybe you can suggest an open source app that supports V2Ray and works on iOS?
thank you

**Comment by Aronablade** [comment]
there is plenty of em but the best of em that i have tried :

shadowrocket  (4$) not free

fairvpn ( best in free without any ads )
95vpn ( free without ads but need high version of ios )
napsternet ( good but have ads )

**Comment by specxdelta** [comment]
Dis anyone found something?

**Comment by mishamoix** [comment]
> Dis anyone found something?
No, just old projects that don't compile now, still looking for a solution

**Comment by mishamoix** [comment]
> Dis anyone found something?

No, just old projects that don't compile now, still looking for a solution

**Comment by SohaibSaleem2000** [comment]
Can anyone find solution? and can suggest me an open source app for v2ray

**Comment by noobkar** [comment]
> @FetFrumos https://github.com/sail-tunnel/sail you can use this project but its use leaf as library leaf is now stable verstion and i cant use vmess with alterid (v2ray) in leaf please check leaf if you find a protocol we can use v2ray as server and leaf as ios client tel me

does any other vmess config work with sail?
