### ISSUE TITLE
请问能否提供一个 protobuf 的 demo

### ISSUE THREAD

**Issue by ToutyRater** [v2ray/v2ray-core#309]
目前 v2ray 的配置文件格式支持 json 及 protobuf。由于配置文件比较大，需要一定的注释，而 json 不支持注释，所以想使用 protobuf 的配置。但是 v2ray 官网没有提供 protobuf 格式配置的相关文档。我也尝试过在 google 搜索如何写 protobuf  的配置，但结果不成功。因此希望可以给出一个 protobuf 格式的 demo 作为参考。

**Comment by v2ray** [comment]
protobuf 是一个二进制格式，而不是像 JSON 一样的文本格式。

我在 JSON 中加一个注释功能好了。

**Comment by kxjhlele** [comment]
考虑一下 把 https://htfy96.github.io/v2ray-config-gen/ 集成到 v2ray 里面，可以通过web服务提供在线修改参数。

**Comment by ToutyRater** [comment]
@v2ray 怪不得查到的资料说 protobuf 比较小，适合用于传输，原来是二进制格式
json 有注释最好不过了，非常感谢

**Comment by ToutyRater** [comment]
@kxjhlele 记得 v2ray 有类似的想法做 GUI，但几个月过去没见动静，估计是比较忙搁置了

**Comment by v2ray** [comment]
注释已加，下一版本发布。
