### ISSUE TITLE
2022/11/11 07:51:23.568 [W] [context.go:165] PostConnection: failed to connect: not support Trojan: %!w(<nil>) 2022/11/11 07:51:23.569 [E] [connection.go:36] failed to connect: failed to connect: not support Trojan: %!w(<nil>) 2022/11/11 07:51:28.673 [E] [connection.go:88] failed to start v2ray-core: not support Trojan: %!w(<nil>) 2022/11/11 07:51:33.634 [E] [connection.go:88] failed to start v2ray-core: not support Trojan: %!w(<nil>) 2022/11/11 07:51:49.574 [E] [connection.go:88] failed to start v2ray-core: not support Trojan: %!w(<nil>) 2022/11/11 07:52:24.926 [E] [connection.go:88] failed to start v2ray-core: not support Trojan: %!w(<nil>) 2022/11/11 07:54:21.928 [E] [connection.go:88] failed to start v2ray-core: not support Trojan: %!w(<nil>) 2022/11/11 07:57:01.046 [E] [connection.go:88] failed to start v2ray-core: not support Trojan: %!w

### ISSUE THREAD

**Issue by yuanjie408** [v2ray/v2ray-core#3090]
2022/11/11 07:51:23.568 [W] [context.go:165] PostConnection: failed to connect: not support Trojan: %!w(<nil>)
2022/11/11 07:51:23.569 [E] [connection.go:36] failed to connect: failed to connect: not support Trojan: %!w(<nil>)
2022/11/11 07:51:28.673 [E] [connection.go:88] failed to start v2ray-core: not support Trojan: %!w(<nil>)
2022/11/11 07:51:33.634 [E] [connection.go:88] failed to start v2ray-core: not support Trojan: %!w(<nil>)
2022/11/11 07:51:49.574 [E] [connection.go:88] failed to start v2ray-core: not support Trojan: %!w(<nil>)
2022/11/11 07:52:24.926 [E] [connection.go:88] failed to start v2ray-core: not support Trojan: %!w(<nil>)
2022/11/11 07:54:21.928 [E] [connection.go:88] failed to start v2ray-core: not support Trojan: %!w(<nil>)
2022/11/11 07:57:01.046 [E] [connection.go:88] failed to start v2ray-core: not support Trojan: %!w

**Comment by zanzhz1101** [comment]
not support Trojan
