### ISSUE TITLE
能ping到不能上网

### ISSUE THREAD

**Issue by sam-mic** [v2ray/v2ray-core#3097]
按照步骤做了，以前有成功过。调整过时间，v2ray active，能ping到，但是链接后不能上网，本地和服务器都没有log产生。试过小火箭和v2rayx。谢谢

**Comment by sam-mic** [comment]
想从香港翻印度，用的aws免费服务器（debian,ubuntu,amazon linux）都试过，因为临时用一下。所以用的是最基础的vmess配置。之前也有提到过可能是tcp6问题，但尝试了一下不行。继续尝试中...

**Comment by Flemington8** [comment]
> 想从香港翻印度，用的aws免费服务器（debian,ubuntu,amazon linux）都试过，因为临时用一下。所以用的是最基础的vmess配置。之前也有提到过可能是tcp6问题，但尝试了一下不行。继续尝试中...

So, have u solve it? I meet the same issue.
