### ISSUE TITLE
v2ray problem on youtube command

### ISSUE THREAD

**Issue by Aronablade** [v2ray/v2ray-core#3107]
hi , when i use a v2ray ( with any panel) on digital ocean server , in youtube it doesn't let me comment or do other things and give me error :
the operation couldnt be completed ( com.google Http status error 403) , some sites like apple in some parts deny to open the web page , in other services like robovps and ... its fine , how to fix this ? i tried to use ssl and use tls on my nods , but it didnt work , randomly its fine on some digital ocean servers , but its super annoying . how to fix this ?

**Comment by amir11235** [comment]
same problem

**Comment by Abd000001** [comment]
> hi , when i use a v2ray ( with any panel) on digital ocean server , in youtube it doesn't let me comment or do other things and give me error : the operation couldnt be completed ( com.google Http status error 403) , some sites like apple in some parts deny to open the web page , in other services like robovps and ... its fine , how to fix this ? i tried to use ssl and use tls on my nods , but it didnt work , randomly its fine on some digital ocean servers , but its super annoying . how to fix this ?

**Comment by mohammad556655** [comment]
i have the same problem as well, tried everything. not solved

**Comment by hamedostadi** [comment]
I have the same problem.
