### ISSUE TITLE
Where is v2ray traffice stats logs saved in hard

### ISSUE THREAD

**Issue by alirezaimi** [v2ray/v2ray-core#3109]
Hi
Where is v2ray traffice stats logs saved in hard ?
I use this article (https://guide.v2fly.org/en_US/advanced/traffic.html#configuration-example) to enable it and see output with v2ctl api , but if i restart the host all stats logs reset .

**Comment by Arzenow** [comment]
سلام چه راه کاری برای فرار از انسداد به طور همیشگی دارید؟

**Comment by Arzenow** [comment]
>راه حل خوبی بود
