### ISSUE TITLE
[非bug]为什么配置文件主要采用protobuf支持

### ISSUE THREAD

**Issue by sinfere** [v2ray/v2ray-core#311]
如题，protobuf适合跨平台之间传递消息，为什么内部的各个config，都采用protobuf类？这样的设计是出于什么考虑？最近在研究代码，对这一点有点不解

**Comment by sinfere** [comment]
看到twitter上的相关推了，真是跳坑-,-

我觉得这种，依赖一个kvstore也未必不好，插件化，但是内部很多配置类在内部传输都用protobuf来封装，感觉不是很舒服

我觉得可以把所有的配置key化，配置中心类管理所有的key，key可以从配置文件读入，也可以从kv读入，甚至其它方式，如db，这样的话感觉更灵活，clean

另外，还有个问题，v2ray为什么需要两端？支持vmess协议可以理解，但是其它的协议，shadowsocks，socks，http，v2ray好像不能作为纯客户端将这些协议作为上游来使用，就是类似cow的那种模式，这是出于什么考虑？

**Comment by v2ray** [comment]
V2Ray core 的设计理念是不依赖于任何外部的存储方式（来读取配置），用户或第三方程序可以自行决定存储方式并通过 protobuf 的方式传给 V2Ray。这也解释了为什么要用 protobuf。

目前 V2Ray 所使用的 JSON 格式的配置文件 ，只是为了兼容性，这部分的逻辑之后将被分割出去做成单独的程序。

可以做为客户端使用的，你可以在 Windows 和 Mac OS 上配置一个 Socks <-> VMess 的 V2Ray 来使用。现在已经有一些[第三方客户端](https://www.v2ray.com/chapter_01/3rd_party.html)可以使用了。

**Comment by sinfere** [comment]
上游使用其他协议呢？比如socks <-> shadowsocks？

另外，未来是否考虑在同一端口支持多种协议？

**Comment by v2ray** [comment]
`socks <-> shadowsocks` 可以的，详见 V2Ray 的[配置文件]。

不考虑支持，没必要。

**Comment by sinfere** [comment]
看错了是socks不支持outbound

了解了，谢谢回复！

**Comment by sinfere** [comment]
研究v2ray代码ing...

还是protobuf的问题，protobuf接收外部配置是很好的设计，但是内部很多地方都用protobuf来encode和decode，是不是很不妥？protobuf我觉得单独写在api里面就好了

这么多个文件夹下面.proto和.pb.go文件，感觉太丑了

**Comment by sinfere** [comment]
Inbound / InboundDetour 与 Outbound / OutboundDetour 我觉得这样的设计比较多余，没必要有Detour，完全可以整合

**Comment by v2ray** [comment]
protobuf 编译出来也是正常的 Go 数据结构，没必要重写一遍，而且重新定义一遍很有可能是一模一样的结构。

inbound 和 outbound 仅仅是 json 配置中， 为了防止误操作导致完全没有 inbound 和 outbound 的情况。在 protobuf 的定义中已经取消了这一设定。

**Comment by sinfere** [comment]
https://github.com/v2ray/v2ray-core/blob/master/transport/internet/headers/http/http.go#L62
```go
for totalBytes < maxHeaderLength {
        ...
		if buffer.Len() >= len(ENDING) {
			totalBytes += buffer.Len() - len(ENDING)
			leftover := buffer.BytesFrom(-len(ENDING))

			buffer.Reset(func(b []byte) (int, error) {
				return copy(b, leftover), nil
			})

		}
```
这里读了很久，有点难以理解，求教，如果头超过了maxHeaderLength，for循环停止，那buffer里面是不是还剩4个多于的字节？

`len(ENDING)`的作用是什么？这几行我没看懂，求解惑

**Comment by v2ray** [comment]
maxHeaderLength 是一个安全性设置，一般情况下不会碰到这么长的 header。在读了 8K 字节的内容还没有发现 ending 时，这时 V2Ray 认为内容不可靠直接返回了。上层的逻辑会进行错误处理。

不过你的分析有道理，我稍微修改了一下（0f0f01ddf69b156a0e7f1ffc62325d1f61c5f17b），现在 reader 在这种情况下直接返回一个 error。

之后这种问题请新开一个 issue。

**Comment by sinfere** [comment]
好的👌
