### ISSUE TITLE
VPN Mode

### ISSUE THREAD

**Issue by RezaShh** [v2ray/v2ray-core#3111]
Hi,
There are some times that we need _VPN mode_ instead of _proxy mode_ please add it to your _v2rayN-Core_.
Thanks.

**Comment by JackyHe398** [comment]
I think we can't connect to server side LAN right? There is no way to do that in the current version.
Now I need to use two layer of encryption to access to the server side LAN. Please tell me if there are a better way to do this TT. We really need VPN mode.

**Comment by JackyHe398** [comment]
But actually I would like to ask, When I am using proxy mode(Globe), vmess server should forward every connection to the internet. But why it cannot act like a VPN and forward the LAN ip to its own LAN?
