### ISSUE TITLE
关于 V2Ray 的 email 问题

### ISSUE THREAD

**Issue by ToutyRater** [v2ray/v2ray-core#312]
V2Ray 在[路由配置](https://www.v2ray.com/chapter_02/03_routing.html#field)中给出了一个 user key：
> * user (V2Ray 2.6+): 一个数组，数组内每一个元素是一个邮箱地址。当某一元素匹配来源用户时，此规则生效。当前 Shadowsocks 和 VMess 支持此规则。

但是我在文档 [Shadowsocks](https://www.v2ray.com/chapter_02/protocols/shadowsocks.html#%E4%BC%A0%E5%85%A5%E5%8D%8F%E8%AE%AE%E9%85%8D%E7%BD%AE%EF%BC%9A) 一节中并没有看到 email 的 key:
> ```javascript
> {
>   "method": "加密方式",
>   "password": "密码",
>   "udp": false,
>   "level": 0,
>   "ota": true
> }
> ```

另外我在 V2Ray 的 shadowsocks [源代码](https://github.com/v2ray/v2ray-core/blob/e46bad3f180f5898556f24497feafbaae07757af/tools/conf/shadowsocks.go)中发现一个 ShadowsocksServerConfig 结构体，其中有一个 Email 成员：
> ```go
> type ShadowsocksServerConfig struct {
>     Cipher   string `json:"method"`
>     Password string `json:"password"`
>     UDP      bool   `json:"udp"`
>     Level    byte   `json:"level"`
>     Email    string `json:"email"`
>     OTA      *bool  `json:"ota"`
> }
> ```

因此推测文档中的 shadowsokcs 小节中的配置少了 email。

以上是猜测。。。

另外还有一个问题，V2Ray 网站无法强制跳转到 https，希望修好这个问题。重现步骤：

1. 清除 V2ray 网站的 cookies 或者使用浏览器的隐私模式
2. 在浏览器的地址栏直接输入 v2ray.com 或 www.v2ray.com 或 http://v2ray.com 或 http://www.v2ray.com， 都会跳转到 http://www.v2ray.com 而不是https://www.v2ray.com
3. 基于 2，在不是 https 的情况下，点击侧边栏的目录任意一小节，打开的仍然不是 http

**Comment by v2ray** [comment]
应该是文档问题，稍后修改。

跳转问题已修复。

**Comment by v2ray** [comment]
文档已修改。
