### ISSUE TITLE
运行v2ray命令报找不到文件

### ISSUE THREAD

**Issue by fw0037** [v2ray/v2ray-core#3121]
使用linux客户端版本：28.2时，解压文件v2ray-linux-64.zip 后，执行命令 v2ray -config config.json时，直接报找不到v2ray文件：

![1675612278234](https://user-images.githubusercontent.com/20429450/216829767-a176815a-478d-4e52-9c14-49d50385a35d.png)

**Comment by morninghut** [comment]
尝试`./v2ray`
