### ISSUE TITLE
Configs not work on windows and get "The ping of current service: -1 ms" message

### ISSUE THREAD

**Issue by farzinfadamin** [v2ray/v2ray-core#3142]
Please answer all the questions with enough information. All issues not following this template will be closed immediately.
If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2fly/discussion/issues) first.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)? V6.6 and I tested other versions but on my PC suddenly I found out server configs don't work and got the ping -1 ms!

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
VMess Proxy

3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)
My VMess server configs work properly on other devices but recently it doesn't work on one of my Windows Pc and I saw weird message of "The ping of current service: -1 ms". Once I check the download test on each server it returns "service unavailable". I don't know what's happened on this device.

4) What's your expectation?
Found out the problem, whether it's windows network or V2Ray problem on this device.

5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

Please review your issue before submitting.

**Comment by pouyan1986** [comment]
سلام آقا از دیروز من هم دچار این مشکل شدم البته ویندوز لپ تاب در حال آپدیت بود من احتمال میدم شاید در اثر آپدیت باشه لطفا اگر پاسخ رو پیدا کردید به من هم اطلاع بدید

**Comment by pouyan1986** [comment]
جواب پیدا شد ساعت ویندوز رو تو حالت اتوماتیک بگذارید باور نکردنیه ظاهرا باعث میشه tls از کار بیفته تغییر ندادن ساعت رسمی یکی از بدبختیاش اینه

**Comment by farzinfadamin** [comment]
The issue has been successfully resolved.

To prevent potential similar problems, verify the "Date/Time" settings on your Windows device and ensure that the "Set Time Automatically" option is enabled. It appears that disabling this feature may cause issues with the proper functioning of TLS.

Thanks to @pouyan1986.

**Comment by mtahagg** [comment]
It didn't work man

**Comment by alizxamax** [comment]
ty so much it worked for me

**Comment by moeinsj** [comment]
> Please answer all the questions with enough information. All issues not following this template will be closed immediately. If you are not sure if your question is truely a bug in V2Ray, please discuss it [here](https://github.com/v2fly/discussion/issues) first.
> 
> 1. What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)? V6.6 and I tested other versions but on my PC suddenly I found out server configs don't work and got the ping -1 ms!
> 2. What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
>    VMess Proxy
> 3. What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)
>    My VMess server configs work properly on other devices but recently it doesn't work on one of my Windows Pc and I saw weird message of "The ping of current service: -1 ms". Once I check the download test on each server it returns "service unavailable". I don't know what's happened on this device.
> 4. What's your expectation?
>    Found out the problem, whether it's windows network or V2Ray problem on this device.
> 5. Please attach your configuration file (**Mask IP addresses before submit this issue**).
> 
> Please review your issue before submitting.

دادا سلاام من ب ی مشکلی خوردم نمیدونم چرااا وی تو ری وصل نمیشه هرچی کانفیگ و پاک کردم دوباره نصب کردم نشد اصلا هیچ عکس العملی نداره ن تنها این بلکه هیچ فیلترشکنی
گفتم شاااید بدونی مشکلش چیه ممنون

**Comment by moeinsj** [comment]
ی

**Comment by Amir-A-M** [comment]
@moeinsj 
من معمولا وقتی vpn کلا وصل نمیشه/ یا local server / xampp و غیره خطا میدن. دستور زیر رو توی ترمینال با دسترسی ادمین میزنم درست میشه
```
// run cmd as Adminstator and run below command
net stop winnat
```
و همینطور برنامه v2rayN رو با run as Adminstator باز کن و گزینه `Enable Tun` رو روشن کن

**Comment by mrtabaa** [comment]
In addition to the great solution of @farzinfadamin, you also need to hit the **Sync Now** button under your Windows's Date/Time settings. Thanks @farzinfadamin!
علاوه بر راهکار خوب @farzinfadamin باید روی دکمه ی **Sync Now** در تنظیمات زمان ویندوز هم کلیک کنید. 
My problem solved.

**Comment by mahan90nn** [comment]
> In addition to the great solution of @farzinfadamin, you also need to hit the **Sync Now** button under your Windows's Date/Time settings. Thanks @farzinfadamin! علاوه بر راهکار خوب @farzinfadamin باید روی دکمه ی **Sync Now** در تنظیمات زمان ویندوز هم کلیک کنید. My problem solved.

کار نمیکنه Not Working:(

**Comment by PAE16** [comment]
У меня выводит ошибку: +0300 2024-10-30 08:02:54 WARN inbound/tun[tun-in]: open tun interface take too much time to finish!
FATAL[0015] start service: initialize inbound/tun[tun-in]: configure tun interface: Cannot create a file when that file already exists.
Что мне делать?
![image](https://github.com/user-attachments/assets/f7095851-e744-40f9-a42f-5f6dcf489f91)
