### ISSUE TITLE
Iran time zone rules doesn't obey daylight time anymore and it causes problem in connection .

### ISSUE THREAD

**Issue by parsa-fathi** [v2ray/v2ray-core#3144]
Hi there, recently Iran's government decided to not using daylight saving time any more but there is problem,since this modification didn't apply globally to time servers, when you want connect in android  without daylight saving time you'll face an error of EOF .

If you use daylight saving time there is no problem , but we don't use daylight saving time anymore .

Please help to solving this issue . Thanks

**Comment by ashkan-moghadasi** [comment]
There isn't GMT+3:30 in some xiaomi phones
And you can't disable daylight time

**Comment by hosni** [comment]
Any update?

**Comment by sajad4656** [comment]
I have same issue for my xiaomi mi9t phone
