### ISSUE TITLE
在shadowsocks协议下下载中断

### ISSUE THREAD

**Issue by waitusz** [v2ray/v2ray-core#315]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
**服务器端v2ray的版本2.9，客户端是SpechtLite0.8**
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
**Crome通过shadowsocks代理在macbed.com下载**
3) 你看到的不正常的现象是什么？
**经过2天的测试，出现下载中断的几率还是蛮高的，对于不支持续传的下载会导致下载的文件不完整**
4) 你期待看到的正确表现是怎样的？
**shadowsocks代理下载中断的问题得到解决，能正确下载这种不支持续传文件的下载**
5) 请附上你的配置文件。

[v2ray_server.txt](https://github.com/v2ray/v2ray-core/files/644183/v2ray_server.txt)

**Comment by wtlusvm** [comment]
V2Ray较消耗系统内存资源，检查下载中断时服务器V2Ray是否被系统kill掉了

**Comment by v2ray** [comment]
Shadowsocks 中把 level 设成 1 试试。https://www.v2ray.com/chapter_02/protocols/shadowsocks.html

**Comment by waitusz** [comment]
@wtlusvm 没有被系统kill，昨晚我下载服务器测试节点的文件是发现是下载速度开始还是正常，比较高，但会越来越慢，直至下载速度降低到0，然后会在下载速度为0的阶段停留几秒，然后恢复连接但是下载速度上不去

**Comment by waitusz** [comment]
@v2ray 回头我加上level 这个参数再试试

**Comment by waitusz** [comment]
@v2ray 刚刚通过下载节点测试文件测试了下，在服务器的设置中添加level=1后，下载没有出现中断，如果没有设置则会出现中断，晚上再继续测试下,服务器版本更新了2.10.1

**Comment by v2ray** [comment]
level=0 时的中断是一个特性，为了防止客户端长期占用一个连接。
