### ISSUE TITLE
v2ray路由规则失效

### ISSUE THREAD

**Issue by renol89303** [v2ray/v2ray-core#3160]
VPS的默认DNS服务器为mosdns，使用adguardhome进行去广告，v2ray的DNS服务设置为adguardhome，adguardhome的上游DNS为mosdns。
流量成功转发通过adguardhome，但是v2ray的路由规则失效，请问下是什么原因呢，图床为我的v2ray配置
https://imgur.com/a/2MX18Br

**Comment by Moryhosseini1** [comment]
{
  "inbounds": [{
    "port": 1080,  // SOCKS 代理端口，在浏览器中需配置代理并指向这个端口
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "udp": true
    }
  }],
  "outbounds": [{
    "protocol": "vmess",
    "settings": {
      "vnext": [{
        "address": "server", // 服务器地址，请修改为你自己的服务器 ip 或域名
        "port": 10086,  // 服务器端口
        "users": [{ "id": "b831381d-6324-4d53-ad4f-8cda48b30811" }]
      }]
    }
  },{
    "protocol": "freedom",
    "tag": "direct",
    "settings": {}
  }],
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [{
      "type": "field",
      "ip": ["geoip:private"],
      "outboundTag": "direct"
    }]
  }
}
