### ISSUE TITLE
请回复我的邮件，这对我很重要‏‏

### ISSUE THREAD

**Issue by FreeLife2025** [v2ray/v2ray-core#3168]
你好
首先，感谢你的精彩项目
你在沟通方面做了很大的改变
特别是伊朗
不幸的是，伊朗的局势每天都变得更加困难
我需要你的帮助来尝试一种新方法
是否可以通过安装了 v2ray 的伊朗服务器和伊朗以外的另一台也安装了 v2ray 的服务器来执行此操作？
我们可以在它们之间放一条隧道吗？
在伊朗服务器中创建用户并将用户连接到伊朗服务器，但通过隧道将外国服务器的流量提供给用户。
我在 v2ray 文档中遇到了这部分，但我无法理解这个问题
这个方法有可能吗？
https://www.v2ray.com/fa/configuration/protocols/dokodemo.html

**Comment by Kikyo-chan** [comment]
你的需求可以理解成天朝搭梯子吗？
比如伊朗国内的用户A需要访问美国Google.com，但是伊朗访问不了，这时你就在美国买了一台服务器（VPS），然后在VPS上部署了 v2ray ，然后伊朗国内的用户A 的电脑也安装了 v2ray （建议用Xray）client，实现翻墙访问Google。
如果是这种，那Project X Community  牛逼闪闪的黑科技正是你需要的，具体参考：
https://github.com/XTLS
https://github.com/XTLS/REALITY

有关安装部署使用请参考：
https://github.com/XTLS/Xray-core

Installation：
![image](https://github.com/v2ray/v2ray-core/assets/18164716/7e28ab01-1214-4b3e-8ae2-bfdce086366e)

Usage：
![image](https://github.com/v2ray/v2ray-core/assets/18164716/7a0427f0-d6da-49fe-891c-df9c29f7a46a)

GUI Clients：
![image](https://github.com/v2ray/v2ray-core/assets/18164716/cdffa93e-c645-42f3-b84b-759ba7cf6112)

**Comment by Kikyo-chan** [comment]
> 

还有别忘记动动鼠标，给项目一个小星星

**Comment by nursery01** [comment]
There are two ways

1.Chain proxy [https://guide.v2fly.org/en_US/advanced/outboundproxy.html](https://guide.v2fly.org/en_US/advanced/outboundproxy.html)

2. Data Forwarding [https://www.v2fly.org/en_US/v5/config/proxy/dokodemo.html](https://www.v2fly.org/en_US/v5/config/proxy/dokodemo.html)

Of course, you can also use nginx forwarding data
