### ISSUE TITLE
Cannot Accessing x-ui panel via internet (v2ray installed on a VM of VMWare/Xubuntu on my Laptop)

### ISSUE THREAD

**Issue by AnonyNovice** [v2ray/v2ray-core#3171]
Hello

## What I did:
  On my laptop, I have `VMWare Workstation Pro v16.2.5`, and on one of the virtual machines, I have` Xubuntu v22.04.1`. I selected **_Bridge  network_** type for the VM network. Additionally, I kept the **_UFW inactive_** in Xubuntu.(_Consequently, the firewall won't hinder my work._)
  I installed a v2ray server on that virtual machine on my laptop based on an excellent guide (a tutorial at [here](https://github.com/iranxray/hope/blob/main/install-xui.md), which I had already setup and successfully used v2ray on Amazon AWS and an Ubuntu virtual machine based on that guide). Then, From within Xubuntu, I can simply reach the X-UI panel. Additionally, I can access it using a Local IP address (192.168.44) from inside the Host OS.

## The Problem:
However, the issue is that I am unable to access the X-UI panel through the Internet! (I am using external IP:Port that applies to the VM network) I kept getting the `404` or `no response` errors! Additionally, neither can the user accounts I setup for accessing the server!

## I tried these:
- I went through the instruction multiple times and repeated everything. (I repeatedly reinstalled everything)
- I tried to discover the solution for two weeks without success!
- Even ChatGPT was a try! It advised me to set up a **port forward** on my router in one of its options. I can't for some reason, **but might that really be the main factor?** since I didn't utilize port forwarding back when I was performing that on a VPS system!
- I even installed `Ubuntu Server v22.04.2` in a virtual machine that I obtained!

**Why is the work flawed?** 

Thank you for your time in advance.

**Comment by nursery01** [comment]
You need to forward the http data of the local ipv4 to your public ipv6

**Comment by AnonyNovice** [comment]
Hello @nursery01 

I appreciate your response. I looked up how to achieve what you suggested, and I came across the following object in the X-UI configuration: [Freedom](https://www.v2ray.com/en/configuration/protocols/freedom.html) I am hope I also came upon the best choice!

However, I do not know how to use it to solve my port forward! Additionally, as is clear from my username! I am a newbie! Could you kindly provide a lesson or some instructions on how to accomplish it?

I am very grateful.

**Comment by nursery01** [comment]
Freedom is free passage, set at the server network export
