### ISSUE TITLE
能不能实现最简单的HTTP加密CDN转发?

### ISSUE THREAD

**Issue by linsan970809** [v2ray/v2ray-core#3172]
我不追求速度,我只是要查谷歌文档而已,
能不能做最简单的HTTP加密直接做内容伪装为HTML网站
然后套一个Cloudflare就行
速度只要能达到100K/S对我来说就够用了,
HTTPS,域名证书申请,NGINX配置伪装这些东西小白真的搞不来

**Comment by xiaokangwang** [comment]
您是不是想要这个？ https://www.v2fly.org/v5/config/stream/meek.html

**Comment by linsan970809** [comment]
> 您是不是想要这个？ https://www.v2fly.org/v5/config/stream/meek.html
其实我也看到了这个协议,但是没有文档,不会配置测试

**Comment by xiaokangwang** [comment]
这里有个说明。 https://cscot.pages.dev/2023/05/31/v2ray-meek/
非常抱歉处于精力限制无法提供针对性的技术支持。

**Comment by linsan970809** [comment]
> 这里有个说明。 https://cscot.pages.dev/2023/05/31/v2ray-meek/ 非常抱歉处于精力限制无法提供针对性的技术支持。
非常感谢,其实很多时候给一个服务端和一个客户端配置,就能看懂了

**Comment by xiaohu-zhang** [comment]
@linsan970809 直接按照v2ray网上的部署文档部署应该就可以了
