### ISSUE TITLE
Centos6.6 Docker 运行错误

### ISSUE THREAD

**Issue by feixuenet** [v2ray/v2ray-core#32]
[root@docker ~]# ./server --config="/root/vpoint_vmess_freedom.json"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x47ac9b]

goroutine 1 [running]:
github.com/v2ray/v2ray-core/config/json.LoadConfig(0x7fff7058a8ae, 0x1f, 0x40cdcd, 0x0, 0x0)
        /root/work/src/github.com/v2ray/v2ray-core/config/json/json.go:63 +0x82b
main.main()
        /root/work/src/github.com/v2ray/v2ray-core/release/server/main.go:47 +0x4ff

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
以上为错误日志。难道是不支持Docker？

**Comment by v2ray** [comment]
请问 /root/vpoint_vmess_freedom.json 文件的内容？

**Comment by v2ray** [comment]
应该已经修复了，如果在 0.8 之后还能重现此问题，请 reopen 此 issue。
