### ISSUE TITLE
v2ray.exe运行后闪退

### ISSUE THREAD

**Issue by 15172107527** [v2ray/v2ray-core#3204]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/discussion/issues)进行讨论。

用v2rayN访问是可以的，把v2rayN软件退出了，v2ray.exe还是闪退

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v5.7.0 windows64

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
配置config.json后运行v2ray.exe闪退

4) 你期待看到的正确表现是怎样的？

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:
{
    "inbounds": [
      {
        "port": 16823, // 服务器监听端口
        "protocol": "vmess",    // 主传入协议
        "settings": {
          "clients": [
            {
              "id": "b831381d-6324-4d53-ad4f-8cda48b30811",  // 用户 ID，客户端与服务器必须相同
              "alterId": 0
            }
          ]
        }
      }
    ],
    "outbounds": [
      {
        "protocol": "freedom",  // 主传出协议
        "settings": {}
      }
    ]
  
客户端配置:
{
  "log": {
    "loglevel": "warning",
    "access": "F:\\v2ray-windows-64\\logsaccess.log",
    "error": "F:\\v2ray-windows-64\\logserror.log"
  },
  "inbounds": [
    {
      "port": 1080, 
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
      "settings": {
        "auth": "noauth" 
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess", 
      "settings": {
        "vnext": [
          {
            "address": "ip",
            "port": 16823,
            "users": [
              {
                "id": "b831381d-6324-4d53-ad4f-8cda48b30811",
                "alterId": 0 
              }
            ]
          }
        ]
      }
    }
  ]
}

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:
服务器日志没配置

客户端错误日志:
客户端配置了日志输出，无日志产生

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
服务器日志没配置

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。

**Comment by 15172107527** [comment]
补充
客户端日志输出地址  F:\\v2ray-windows-64\\logs\\access.log
有双斜杠

**Comment by lv123123long** [comment]
服务端：/usr/local/bin/v2ray test -config /usr/local/etc/v2ray/config.json
输出正常：V2Ray 5.12.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.21.4 linux/amd64)
A unified platform for anti-censorship.
Configuration OK.
配置如下：
{
  "inbounds": [
    {
      "port": 16823, // 服务器监听端口
      "protocol": "vmess",    // 主传入协议
      "settings": {
        "clients": [
          {
            "id": "b831381d-6324-4d53-ad4f-8cda48b30811",  // 用户 ID，客户端与服务器必须相同
            "alterId": 0
          }
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",  // 主传出协议
      "settings": {}
    }
  ]
}


客户端闪退，没有日志
配置如下：
{
  "log": {
    "loglevel": "debug"
  },
  
  "inbounds": [{
    "port": 1080,
    "listen": "127.0.0.1",
    "tag": "socks-inbound",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    },
    "sniffing": {
      "enabled": true,
      "destOverride": ["http", "tls"]
    }
  }],
  // List of outbound proxy configurations.
  "outbounds": [{
    // Protocol name of the outbound proxy.
    "protocol": "vmess",

    // Settings of the protocol. Varies based on protocol.
    "settings": {
      "vnext": [
        {
          "address": "", 
          "port": 16823,  
          "users": [
            {
              "id": "b831381d-6324-4d53-ad4f-8cda48b30811",  
              "alterId": 0,
              "security": "auto",
              "level": 0
            }
          ]
        }
      ]
    }
  },{
    "protocol": "freedom",
    "settings": {}
  }]
}
版本号：v5.12.1

客户端闪退，没有生成日志，不好排查
