### ISSUE TITLE
TCP 连接重用出现问题

### ISSUE THREAD

**Issue by ToutyRater** [v2ray/v2ray-core#321]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please answer the following questions before submitting your issue. Thank you.

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
1) What version of V2Ray are you using?
v2.10.1

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
2) What your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
widnows 10 x64 作为服务器，virtualBox Debian 8.6 x 64 作为客户端，使用 iperf3 通过 V2Ray VMess 协议测速（没有使用 iptables）。

3) 你看到的不正常的现象是什么？
3) What did you see?
当服务器的 tcpSettings.connectionReuse 设置为 false 而客户端设为 true 时，使用命令 `iperf3 -c 127.0.0.1 -p 5201` 通过 VMess 测速，第一次可以正常测速，等一次测速完成时**立即**再执行一遍  `iperf3 -c 127.0.0.1 -p 5201`，这个时候无法正常测速。这个现象可以稳定重现。
![iperf3error](https://cloud.githubusercontent.com/assets/20978410/21093830/ccd42a4a-c04b-11e6-8fb0-31214e47f74d.png)
客户端日志为：
  > Dec 12 04:09:11 debian v2ray[5050]: 2016/12/12 04:09:11 [Warning]VMess|Outbound: Failed to read response from tcp:192.168.43.208:5201: EOF

  服务器日志：
  > 2016/12/12 17:10:10 [Info]Freedom: Failed to transport all TCP request: write tcp 192.168.43.208:11868->192.168.43.208:5201: wsasend: An existing connection was forcibly closed by the remote host.

如果在完成测速之后过一段时间再进行一次测速就不会有这个问题。

而如果服务器 tcpSettings.connectionReuse 设置为 true，无论客户端设置成什么，都没有出现上述情况。
不知道这是正常的现象还是 BUG。

4) 你期待看到的正确表现是怎样的？
4) What do you expected to see instead?

5) 请附上你的配置文件。
5) Please attach your configuration file.
client:
```javascript
{
  "transport": {
    "tcpSettings": {
      "connectionReuse":true
    }
  },
  "log": {
    "loglevel": "warning"
  },
  "inbound": {
    "protocol": "dokodemo-door",
    "port": 5201,
    "settings": {
      "address": "192.168.43.208",
      "network": "tcp,udp",
      "timeout": 0,
      "followRedirect": false,
      "port": 5201
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "192.168.43.208",
          "port": 10800,
          "users": [
            {
              "id": "8691718f-ef3d-49cd-9e1c-243eb3e7f58a",
              "alterId": 64,
              "security": "none"
            }
          ]
        }
      ]
    }
  }
}
```

server:
```javascript
{
  "inbound": {
    "port": 10800,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "alterId": 64,
          "id": "8691718f-ef3d-49cd-9e1c-243eb3e7f58a",
          "level": 1
        }
      ]
    }
  },
  "log": {
    "loglevel": "info"
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "transport": {
    "tcpSettings": {
      "connectionReuse": false
    }
  }
}
```

**Comment by v2ray** [comment]
2.10.2 修复了这个问题。
