### ISSUE TITLE
Shadowsocks支持部分容易被探测服务器正在跑shadowsocks

### ISSUE THREAD

**Issue by Remonli** [v2ray/v2ray-core#323]
2.10.2 版本，被这个issue的代码探测出：

https://github.com/breakwa11/shadowsocks-rss/issues/448

运行结果：
xx.sample.com:20000 is a Shadowsocks-go server, iv size is 8

其他语言的shadowsocks探测结果是unknown server。

**Comment by testcaoy7** [comment]
你有打开一次性认证吗

**Comment by Remonli** [comment]
开了的，这个问题好像是shadowsocks的实现有缺陷，开OTA不能解决。

**Comment by v2ray** [comment]
会在下一版本修复。

**Comment by suikatomoki** [comment]
@v2ray  真的会修复吗？目前 ss 开发人员好像不 care 这个问题啊。
@testcaoy7 开了 OTA 一样能被这个脚本探测出来 服务端 ss-libev 2.6 版 https://gist.github.com/breakwa11/d26cd21949b9ce8f1aba4c2b5652ddb3

**Comment by wtlusvm** [comment]
@suikatomoki 他说的是V2Ray修复这个问题……

**Comment by suikatomoki** [comment]
@wtlusvm 修复了之后还能保证与ss原版的兼容性吗

**Comment by v2ray** [comment]
欢迎测试，在开启 OTA 后无法被探测
