### ISSUE TITLE
定义了2个outbounds及相应的rules希望不同的网站能走不同的代理服务器但却出错

### ISSUE THREAD

**Issue by huang5307** [v2ray/v2ray-core#3233]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 V2Ray 的 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/v2fly/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V2RayN v6.23

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
Chrome 通过 Socks/VMess 代理观上ChatGPT。

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
因为ChatGPT不能走cloudflare，所以我定义了两个服务器，希望普通的流量走proxy，但是chatgpt的流量走newserver，从log看来确实是路由到newserver了，但是ChatGPT还是不能上，而同样定义在newserver的claude.ai却是可以上的（因为它原来cloudflare的服务器也能使用的），所以我怀疑V2RayN即使是路由到了newserver，但是流量还是统统走proxy。

4) 你期待看到的正确表现是怎样的？
我希望ChatGPT的流量能够透过 newserver 的节点出去。

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
    // 在这里附上服务器端配置文件
```

客户端配置:

{
"log": {
"access": "",
"error": "",
"loglevel": "warning"
},
"inbounds": [
{
"tag": "socks",
"port": 10808,
"listen": "127.0.0.1",
"protocol": "socks",
"sniffing": {
"enabled": true,
"destOverride": [
"http",
"tls"
],
"routeOnly": false
},
"settings": {
"auth": "noauth",
"udp": true,
"allowTransparent": false
}
},
{
"tag": "http",
"port": 10809,
"listen": "127.0.0.1",
"protocol": "http",
"sniffing": {
"enabled": true,
"destOverride": [
"http",
"tls"
],
"routeOnly": false
},
"settings": {
"auth": "noauth",
"udp": true,
"allowTransparent": false
}
}
],
"outbounds": [
{
"tag": "proxy",
"protocol": "vless",
"settings": {
"vnext": [
{
"address": "www.visa.com.hk",
"port": 2082,
"users": [
{
"id": "25456ff7-6079-48d9-bfbc-8480561dcd63",
"alterId": 0,
"email": "[t@t.tt](mailto:t@t.tt)",
"security": "auto",
"encryption": "none",
"flow": ""
}
]
}
]
},
"streamSettings": {
"network": "ws",
"wsSettings": {
"path": "/?ed=2048",
"headers": {
"Host": "c047.huang3307.workers.dev"
}
},
"mux": {
"enabled": false,
"concurrency": -1
}
}
},
{
"tag": "direct",
"protocol": "freedom",
"settings": {}
},
{
"tag": "block",
"protocol": "blackhole",
"settings": {
"response": {
"type": "http"
}
}
},
{
"tag": "newserver",
"protocol": "vmess",
"settings": {
"vnext": [
{
"address": "cf9.trojan.tel",
"port": 8880,
"users": [
{
"id": "357d061f-1efa-4648-85ea-647ab42ad240",
"alterId": 0,
"email": "[t@t.tt](mailto:t@t.tt)",
"security": "auto"
}
]
}
]
}
}
],
"routing": {
"domainStrategy": "AsIs",
"rules": [
{
"type": "field",
"inboundTag": ["api"],
"outboundTag": "api",
"enabled": true
},
{
"id": "4675648503892092962",
"type": "field",
"outboundTag": "direct",
"domain": ["domain:example-example.com", "domain:example-example2.com"],
"enabled": true
},
{
"id": "5512271877616629289",
"type": "field",
"outboundTag": "block",
"domain": ["geosite:category-ads-all"],
"enabled": true
},
{
"id": "5298124203295757738",
"type": "field",
"outboundTag": "direct",
"domain": ["geosite:cn"],
"enabled": true
},
{
"id": "5640812491960797671",
"type": "field",
"outboundTag": "direct",
"ip": ["geoip:private", "geoip:cn"],
"enabled": true
},
{
"id": "5714050562420031971",
"type": "field",
"outboundTag": "newserver",
"domain": ["bing.com", "claude.ai", "openai.com", "live.com"],
"enabled": true
},
{
"id": "5714050562420031972",
"type": "field",
"port": "0-65535",
"outboundTag": "proxy",
"enabled": true
}
]
}
}

日志信息

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

服务器端错误日志:

```javascript
    // 在这里附上服务器端日志
```

客户端错误日志:

```javascript
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

2023/11/07 21:59:11 127.0.0.1:61625 accepted //chat.openai.com:443 [http -> newserver]
2023/11/07 21:59:11 127.0.0.1:61628 accepted //chat.openai.com:443 [http -> newserver]
2023/11/07 21:59:18 127.0.0.1:61633 accepted //chat.openai.com:443 [http -> newserver]
2023/11/07 21:59:19 127.0.0.1:61637 accepted //chat.openai.com:443 [http -> newserver]

8) 其它相关的配置文件（如 Nginx）和相关日志。

9) 如果 V2Ray 无法启动，请附上 `--test` 输出。

通常的命令为 `/usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json`。请按实际情况修改。

10) 如果 V2Ray 服务运行不正常，请附上 journal 日志。

通常的命令为 `journalctl -u v2ray`。

请预览一下你填的内容再提交。
{
"log": {
"access": "",
"error": "",
"loglevel": "warning"
},
"inbounds": [
{
"tag": "socks",
"port": 10808,
"listen": "127.0.0.1",
"protocol": "socks",
"sniffing": {
"enabled": true,
"destOverride": [
"http",
"tls"
],
"routeOnly": false
},
"settings": {
"auth": "noauth",
"udp": true,
"allowTransparent": false
}
},
{
"tag": "http",
"port": 10809,
"listen": "127.0.0.1",
"protocol": "http",
"sniffing": {
"enabled": true,
"destOverride": [
"http",
"tls"
],
"routeOnly": false
},
"settings": {
"auth": "noauth",
"udp": true,
"allowTransparent": false
}
}
],
"outbounds": [
{
"tag": "proxy",
"protocol": "vless",
"settings": {
"vnext": [
{
"address": "www.visa.com.hk",
"port": 2082,
"users": [
{
"id": "25456ff7-6079-48d9-bfbc-8480561dcd63",
"alterId": 0,
"email": "[t@t.tt](mailto:t@t.tt)",
"security": "auto",
"encryption": "none",
"flow": ""
}
]
}
]
},
"streamSettings": {
"network": "ws",
"wsSettings": {
"path": "/?ed=2048",
"headers": {
"Host": "c047.huang3307.workers.dev"
}
},
"mux": {
"enabled": false,
"concurrency": -1
}
}
},
{
"tag": "direct",
"protocol": "freedom",
"settings": {}
},
{
"tag": "block",
"protocol": "blackhole",
"settings": {
"response": {
"type": "http"
}
}
},
{
"tag": "newserver",
"protocol": "vmess",
"settings": {
"vnext": [
{
"address": "cf9.trojan.tel",
"port": 8880,
"users": [
{
"id": "357d061f-1efa-4648-85ea-647ab42ad240",
"alterId": 0,
"email": "[t@t.tt](mailto:t@t.tt)",
"security": "auto"
}
]
}
]
}
}
],
"routing": {
"domainStrategy": "AsIs",
"rules": [
{
"type": "field",
"inboundTag": ["api"],
"outboundTag": "api",
"enabled": true
},
{
"id": "4675648503892092962",
"type": "field",
"outboundTag": "direct",
"domain": ["domain:example-example.com", "domain:example-example2.com"],
"enabled": true
},
{
"id": "5512271877616629289",
"type": "field",
"outboundTag": "block",
"domain": ["geosite:category-ads-all"],
"enabled": true
},
{
"id": "5298124203295757738",
"type": "field",
"outboundTag": "direct",
"domain": ["geosite:cn"],
"enabled": true
},
{
"id": "5640812491960797671",
"type": "field",
"outboundTag": "direct",
"ip": ["geoip:private", "geoip:cn"],
"enabled": true
},
{
"id": "5714050562420031971",
"type": "field",
"outboundTag": "newserver",
"domain": ["bing.com", "claude.ai", "openai.com", "live.com"],
"enabled": true
},
{
"id": "5714050562420031972",
"type": "field",
"port": "0-65535",
"outboundTag": "proxy",
"enabled": true
}
]
}
}

复现方法
添加自定义配置服务器，导入以上config.json，打开https://chat.openai.com/

日志信息

**Comment by Aminabedi1390** [comment]
Amin

**Comment by Aminabedi1390** [comment]
127.0.0.1:61625 accepted //chat.openai.com:443 [http -> newserver]
2023/11/07 21:59:11 127.0.0.1:61628 accepted //chat.openai.com:443 [http -> newserver]
2023/11/07 21:59:18 127.0.0.1:61633 accepted //chat.openai.com:443 [http -> newserver]
2023/11/07 21:59:19 127.0.0.1:61637 accepted //chat.openai.com:443 [http -> newserver]

其它相关的配置文件（如 Nginx）和相关日志。

如果 V2Ray 无法启动，请附上 --test 输出。

通常的命令为 /usr/bin/v2ray/v2ray --test --config /etc/v2ray/config.json
