### ISSUE TITLE
TLS的错误现象

### ISSUE THREAD

**Issue by testcaoy7** [v2ray/v2ray-core#324]
版本：2.10.2
错误：当使用TLS时，网页时常卡住，错误信息中出现如下字样：
[Warning]VMess|Outbound: Failed to read response from tcp:www.facebook.com:443: EOF

[Warning]Socks: failed to read request: read tcp 127.0.0.1:1080->127.0.0.1:56923: wsarecv: An existing connection was forcibly closed by the remote host.

其中，第一条错误只是一个样例，有不少类似的指向不同域名的类似错误

开始时，因为用的自签名证书，以为是遭到了干扰，于是便找CloudFlare核签了一份证书，使用CloudFlare的证书时也出现了错误，不知是BUG还是其他原因导致的

**Comment by oing9179** [comment]
同上。而且还会发生另一个现象：
比如下载一个任意大小的文件，下载管理起显示下载速度在 200KiB/s 以下，但通过实际通过网络设备（比如 eth0）传输的数据则有 3MiB/s。感觉像是数据包重传率变高了。

另外，新版还会导致 [Actinium v0.6.1](https://github.com/V2Ray-Android/Actinium/releases/tag/0.6.1) 无法连接到服务器。

暂时回滚至 v2.9.

**Comment by testcaoy7** [comment]
@oing9179 2.10版之前的TLS都是假的，配置了不会生效

**Comment by testcaoy7** [comment]
在三个VPS执行了openssl s_client -host ｛VPS｝ -port 443命令，得到完全不同的结果……

VPS1：使用自签名ECC证书，得到：
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 624 bytes and written 7 bytes
---
New, (NONE), Cipher is (NONE)   <-注意本行
Server public key is 224 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1481616948
    Timeout   : 300 (sec)
    Verify return code: 18 (self signed certificate)
---
可以看到，使用ECC自签名证书后，TLS加密层失败了，另外一台服务器，使用RSA自签名，输出正常（ECDHE-RSA-AES256-GCM-SHA384），还有使用CloudFlare核签证书的第三台服务器，输出也正常（ECDHE-ECDSA-AES256-GCM-SHA384）

不知是什么原因

**Comment by testcaoy7** [comment]
2.10.4速度有了很大提升，用到现在也没爆出任何错误信息

**Comment by oing9179** [comment]
使用新版（[v2.10.5](https://github.com/v2ray/v2ray-core/releases/tag/v2.10.5)）后 问题解决了。
__testcaoy7__ 也表示错误信息不再出现。

@v2ray 由于上述问题已在新版的v2ray中解决，请考虑关闭该Issue.

**Comment by wtlusvm** [comment]
其实一般都是Issue发起者确认issue解决后关闭的，毕竟每次都要作者看一遍也要耗费比较多的精力

**Comment by oing9179** [comment]
@wtlusvm 
喔 原来是这样，Thanks.

**Comment by testcaoy7** [comment]
v2.10.5版本，还是会出现少量错误信息，偶尔还是会有网页打不开的现象

[Warning]VMess|Outbound: Failed to read response from tcp:id.google.com.hk:443: EOF

**Comment by v2ray** [comment]
这个应该和本 issue 无关，开不开 TLS 都会有这个问题。

**Comment by testcaoy7** [comment]
@v2ray 尝试了下，确实没有开TLS也会有错误

**Comment by v2ray** [comment]
如果没什么问题，这个 issue 先关了。有新问题请新开 issue。
