### ISSUE TITLE
ios xcode 

### ISSUE THREAD

**Issue by luosu1025769919** [v2ray/v2ray-core#3249]
有打出ios framework的xcode工程，并在ios能使用的demo吗？我用了framework接入后链接了当是无法正常上网，同一个vmess://协议在shadowrocket上可以正常上网

**Comment by MoneyKey11** [comment]
我有rust写的代码

可以联系我https://t.me/VPNMoney1

**Comment by loveCodingStar** [comment]
联系我

https://t.me/TTMike12
