### ISSUE TITLE
CPU負載異常

### ISSUE THREAD

**Issue by wenjinlibug** [v2ray/v2ray-core#325]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V2ray:   v2.10.2
OS:    Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19)

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
即使不使用代理仍然高負載

3) 你看到的不正常的现象是什么？

root@vultr:~# ps auxw|head -1;ps auxw|sort -rn -k3|head -10
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
**root      2808 99.2  6.3  57364 31964 ?        Ssl  14:44  76:15 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json**
debian-+   439  0.6  4.8 660832 24336 ?        Ssl  08:10   3:15 /usr/bin/transmission-daemon -f --log-error
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
unbound    503  0.0  1.2  34476  6444 ?        Ss   08:10   0:02 /usr/local/sbin/unbound
root        99  0.0  0.0      0     0 ?        S    08:10   0:00 [jbd2/vda1-8]
root         9  0.0  0.0      0     0 ?        S    08:10   0:00 [migration/0]
root         8  0.0  0.0      0     0 ?        S    08:10   0:00 [rcu_bh]
root        80  0.0  0.0      0     0 ?        S<   08:10   0:00 [kworker/0:1H]
root        75  0.0  0.0      0     0 ?        S<   08:10   0:00 [scsi_tmf_1]
root        74  0.0  0.0      0     0 ?        S    08:10   0:00 [scsi_eh_1]

4) 你期待看到的正确表现是怎样的？

5) 请附上你的配置文件。
```javascript
{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 13887,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "xx",
          "level": 1,
          "alterId": 20
        }
      ]
    },
    "detour": {
      "to": "detour"
    }
  },
  "inboundDetour": [
    {
      "port": 13887,
      "protocol": "vmess",
      "tag": "detour",
      "settings": {
        "clients": [
          {
            "id": "xx",
            "level": 1,
            "alterId": 20
          }
        ]
      },
      "allocate": {
        "strategy": "random",
        "concurrency": 5,
        "refresh": 30
      },
      "streamSettings": {
        "network": "kcp"
      }
    }
  ],

  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  },
  "transport": {
    "kcpSettings": {
      "uplinkCapacity": 3,
      "downlinkCapacity": 1,
      "header": {
        "type": "srtp"
      }
    }
  }
}
```

**Comment by v2ray** [comment]
你的 concurrency 设成了 5 但只有一个端口可用，于是就死循环了。解决方法要么把 concurrency 改成 1，要么把端口设为一个范围，如“13887-14887”。

```
"inboundDetour": [
    {
      "port": 13887,
      "protocol": "vmess",
      "tag": "detour",
      "settings": {
        "clients": [
          {
            "id": "xx",
            "level": 1,
            "alterId": 20
          }
        ]
      },
      "allocate": {
        "strategy": "random",
        "concurrency": 5,
        "refresh": 30
      },
      "streamSettings": {
        "network": "kcp"
      }
    }
  ],
```
