### ISSUE TITLE
使用install-release.sh自动更新出现故障

### ISSUE THREAD

**Issue by cnperi** [v2ray/v2ray-core#326]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please answer the following questions before submitting your issue. Thank you.

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
1) What version of V2Ray are you using?
2.10.4

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
2) What your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
通过install-release.sh在树莓派3上更新安装。

3) 你看到的不正常的现象是什么？
3) What did you see?
安装完后，重启v2ray时，raspbain当掉。
4) 你期待看到的正确表现是怎样的？
4) What do you expected to see instead?
install-release.sh工作正常。

5) 请附上你的配置文件。
5) Please attach your configuration file.
bash <(curl -L -s https://raw.githubusercontent.com/v2ray/v2ray-core/master/release/install-release.sh) -p socks5://127.0.0.1:1080

问题初步判断，貌似是v2ray重启时脚本使用了service v2ray stop造成的。
手工安装时使用systemctl stop v2ray 能正常。

**Comment by cnperi** [comment]
刚试验了下，使用systemctl stop v2ray一样halt掉raspbian，和service v2ray stop效果一样。
raspbian是用的最新版RASPBIAN JESSIE LITE（2016-11-25），全新安装，更新到最新版。
因为默认无法下载，所以采用下载zip手工安装，仅装了/usr/bin/v2ray/v2ray，设置/etc/v2ray/config.json，复制了/lib/systemd/system/v2ray.service并执行了systemctl enable v2ray，2.10.4，更新至2.10.5时出现问题（在2.8更新新版本时出现同样问题）。

**Comment by cnperi** [comment]
安装2.10.4之后，使用 systemctl start/stop/restart v2ray 都没有问题。设定了 iptables，运行正常后再用bash <(curl -L -s https://raw.githubusercontent.com/v2ray/v2ray-core/master/release/install-release.sh) -p socks5://127.0.0.1:1080 更新就出现问题了。
请帮助解决。

**Comment by v2ray** [comment]
手边没有 raspberry可以测试，如果能提供halt时的错误信息就更好了。

**Comment by cnperi** [comment]
没从 /var/log/messenges 内找到有用的信息。
刚才反复试了下，systemctl stop v2ray 会造成宕机，而 systemctl restart v2ray 则只会把用户踢出ssh。
另外，v2ray.service 中用的 PID=/var/run/v2ray.pid，而在 raspbian 中，/var/run 只是个 link，链到 /run。而在 /run 下，没有 v2ray.pid。

**Comment by wtlusvm** [comment]
那就麻烦你在 /var/log/syslog找下吧（是的我知道很多（是的我知道找起来费劲（树莓派 model B+并没有异常

**Comment by cnperi** [comment]
丢人啊。找到原因了。
防火墙设置问题。偷懒，没有把本地包排除在v2ray的转发表之外，造成停止v2ray时，所有的转发停止。

**Comment by wtlusvm** [comment]
@cnperi 纯属好奇，内网下RaspberryPi为啥要设防火墙，还是说是类似公司网这样的内网？

**Comment by cnperi** [comment]
@wtlusvm iptables，用来做透明代理。把流量转发到Dokodemo door，实现局域网内机器的自动科学上网。

**Comment by wtlusvm** [comment]
@cnperi 原来如此，有时间去搞个支持openwrt的路由器吧，就不用这么麻烦了
