### ISSUE TITLE
突然不能用了，求神助 VMess|Outbound: Failed to find an available destination:All retry attempts failed.

### ISSUE THREAD

**Issue by walasix** [v2ray/v2ray-core#327]
操作系统：windows XP
V2ray版本：2.10.5 （之前的各版本也都用不了，同样的错误提示）
从昨天开始用不了了，小白求神助，先叩谢了~

**Comment by oing9179** [comment]
运行命令 `tracert <你的服务器IP>`（举例：`tracert 8.8.8.8`），运行完成后 把输出的内容以文字的形式贴出来。前5行输出内容请略去，从第6行往下全贴出来。

**Comment by walasix** [comment]
@oing9179 大神，是在桌面的“开始”——“运行”么？运行一段时间后，窗口自动关闭了，没法全部贴出来啊？另，服务器IP在哪儿查啊？是V2Ray的配置文件里么？本人小白请见谅，以下是部分输出内容：

Tracing route to google-public-dns-a.google.com [8.8.8.8]
over a maximum of 30 hops:

  1     3 ms    <1 ms     1 ms  bogon [10.44.147.254]
  2     1 ms    <1 ms    <1 ms  bogon [10.44.244.129]
  3     2 ms     2 ms     5 ms  bogon [10.44.244.121]
  4     *        *        *     Request timed out.
  5     *        4 ms     6 ms  222.85.86.113
  6     *        *        6 ms  229.124.85.222.broad.zz.ha.dynamic.163data.com.c
n [222.85.124.229]
  7     *        *        *     Request timed out.
  8     *       15 ms    19 ms  202.97.80.37
  9    19 ms    19 ms    19 ms  202.97.53.162
 10     *       18 ms    21 ms  202.97.53.242
 11     *        *       68 ms  202.97.61.54
 12     *        *       62 ms  202.97.122.70
 13     *        *       61 ms  108.170.241.6
 14     *        *        *     Request timed out.
 15     *        *        *     Request timed out.
 16     *       71 ms    72 ms  209.85.245.16
 17     *        *        *     Request timed out.
 18     *        *        *     Request timed out.
 19     *        *        *     Request timed out.
 20     *        *        *     Request timed out.
 21     *        *        *     Request timed out.
 22     *        *        *     Request timed out.
 23

**Comment by oing9179** [comment]
@walasix 
:expressionless: 这样，我再详细写一下步骤。

准备工作：找到你的v2ray客户端的配置文件，在配置文件里找到服务器的ip。注意，是你要连接的服务器的ip而不是 `8.8.8.8`。

1. `开始 -> 运行 -> 输入'cmd'` 然后回车
2. 在出现的窗口里输入 `tracert <你要连接的服务器的IP>` 然后回车，比如 `tracert 8.8.8.8` ，把那个 `8.8.8.8` 替换成你要连接的服务器的IP。
3. 把输出的内容以文本的形式贴出来，记得使用GitHub的插入代码功能，使用方法是：
    > \`\`\`
    > 这里替换成上面输出的内容。
    > \`\`\`
    
    使用后效果大概是这样：
    ```
    1 3 ms <1 ms 1 ms bogon [10.44.147.254]
    2 1 ms <1 ms <1 ms bogon [10.44.244.129]
    3 2 ms 2 ms 5 ms bogon [10.44.244.121]
    4 * * * Request timed out.
    5 * 4 ms 6 ms 222.85.86.113
    6 * * 6 ms 229.124.85.222.broad.zz.ha.dynamic.163data.com.c
    n [222.85.124.229]
    7 * * * Request timed out.
    ```

贴出来之后 再进一步分析问题。

**Comment by walasix** [comment]
@oing9179  大神，配置文件里哪个是我要连接的服务器的ip啊。。[一脸懵逼状]
插入代码功能，是不是直接点击insert code那个按钮呢？[继续一脸懵逼状]

**Comment by walasix** [comment]
```
1 3 ms <1 ms 1 ms bogon [10.44.147.254]
2 1 ms <1 ms <1 ms bogon [10.44.244.129]
3 2 ms 2 ms 5 ms bogon [10.44.244.121]
4 * * * Request timed out.
5 * 4 ms 6 ms 222.85.86.113
6 * * 6 ms 229.124.85.222.broad.zz.ha.dynamic.163data.com.c
n [222.85.124.229]
7 * * * Request timed out.
```

**Comment by v2ray** [comment]
如果你的客户端用的不是默认的配置文件，请附上配置文件的内容。标题中的错误信息通常是因为服务器连上，请检查你的服务器设置。

**Comment by walasix** [comment]
@oing9179  我用的默认配置文件，里面没有你说的那些内容啊，如下：
···
 "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "v2ray.cool",
          "port": 10086,
···

**Comment by walasix** [comment]
@v2ray  谢谢大神，客户端用的是默认配置文件。请问如何检查服务器设置呢？ 
关键是之前这些都用的好好的，突然就不能用了，什么都没改啊

**Comment by v2ray** [comment]
之前官方服务器挂了，现已重启，应该可以用了。

**Comment by walasix** [comment]
@v2ray 还是不能用啊，依然是标题中的那个提示。手机端也不能用。求大神解决方案，谢谢~

**Comment by oing9179** [comment]
@walasix 

请按照 [#6](#issuecomment-266965243) 的描述逐个执行下面两个命令，然后把输出的内容贴出来。

```shell
nslookup v2ray.cool
tracert v2ray.cool
```

**Comment by testcaoy7** [comment]
v2ray.cool 还没有被污染

**Comment by v2ray** [comment]
请再试一下，之前貌似误操作了。

**Comment by 853574130** [comment]
通过最多 30 个跃点跟踪
到 111.216.220.35.bc.googleusercontent.com [35.220.216.111] 的路由:

  1     3 ms     2 ms     3 ms  172.20.10.1
  2     *        *        *     请求超时。
  3     *        *       47 ms  192.168.244.193
  4     *        *        *     请求超时。
  5     *        *        *     请求超时。
  6     *        *        *     请求超时。
  7     *        *        *     请求超时。
  8     *

大佬麻烦帮我看看

**Comment by 853574130** [comment]
> 通过最多 30 个跃点跟踪
> 到 111.216.220.35.bc.googleusercontent.com [35.220.216.111] 的路由:
> 
> 1 3 ms 2 ms 3 ms 172.20.10.1
> 2 * * * 请求超时。
> 3 * * 47 ms 192.168.244.193
> 4 * * * 请求超时。
> 5 * * * 请求超时。
> 6 * * * 请求超时。
> 7 * * * 请求超时。
> 8 *
> 
> 大佬麻烦帮我看看

C:\Users\admin>nslookup 35.220.216.111
服务器:  UnKnown
Address:  fe80::45c:49e2:2811:27e3

名称:    111.216.220.35.bc.googleusercontent.com
Address:  35.220.216.111

**Comment by 853574130** [comment]
> 通过最多 30 个跃点跟踪
> 到 111.216.220.35.bc.googleusercontent.com [35.220.216.111] 的路由:
> 
> 1 3 ms 2 ms 3 ms 172.20.10.1
> 2 * * * 请求超时。
> 3 * * 47 ms 192.168.244.193
> 4 * * * 请求超时。
> 5 * * * 请求超时。
> 6 * * * 请求超时。
> 7 * * * 请求超时。
> 8 *
> 
> 大佬麻烦帮我看看

C:\Users\admin>nslookup 35.220.216.111
服务器:  UnKnown
Address:  fe80::45c:49e2:2811:27e3

名称:    111.216.220.35.bc.googleusercontent.com
Address:  35.220.216.111

**Comment by 853574130** [comment]
> 通过最多 30 个跃点跟踪
> 到 111.216.220.35.bc.googleusercontent.com [35.220.216.111] 的路由:
> 
> 1 3 ms 2 ms 3 ms 172.20.10.1
> 2 * * * 请求超时。
> 3 * * 47 ms 192.168.244.193
> 4 * * * 请求超时。
> 5 * * * 请求超时。
> 6 * * * 请求超时。
> 7 * * * 请求超时。
> 8 *
> 
> 大佬麻烦帮我看看

C:\Users\admin>nslookup 35.220.216.111
服务器:  UnKnown
Address:  fe80::45c:49e2:2811:27e3

名称:    111.216.220.35.bc.googleusercontent.com
Address:  35.220.216.111
