### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by hack3rcon** [v2ray/v2ray-core#3270]
Hello,
I installed V2Ray on Debian. I received the following error message:

`app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > EOF`

I also set the clock, but this problem still exists and unfortunately no one has answered it. I think V2Ray is not suitable for use in a serious environment! Many people have encountered this problem, but no one has answered it.

Any idea?

Thanks.

**Comment by Silentsniper1** [comment]
add me on discord @silentsniper0 ill help you out

**Comment by highlander0test** [comment]
刚用v2ray搭建的，大家可以体验一下
欢迎体验
本网站处于推广阶段，联系群主，注册后提供邮箱，提供免费1个月体验机会
官网：https://www.bzg.life/
官群：https://t.me/BZG_group

**Comment by aiqubits** [comment]
The same problem
Is there a solution ?
