### ISSUE TITLE
What is the role of UUID?

### ISSUE THREAD

**Issue by hack3rcon** [v2ray/v2ray-core#3271]
Hello,
I know UUID is something like password in Shadowsocks. Can two clients with the same UUID connect to the server? If so, how can I prevent two clients with the same UUID from connecting to the server?

Thanks.

**Comment by Silentsniper1** [comment]
> Hello, I know UUID is something like password in Shadowsocks. Can two clients with the same UUID connect to the server? If so, how can I prevent two clients with the same UUID from connecting to the server?
> 
> Thanks.

> _No description provided._

add me on discord @silentsniper0 ill help you out

**Comment by highlander0test** [comment]
刚用v2ray搭建的，大家可以体验一下
欢迎体验
本网站处于推广阶段，联系群主，注册后提供邮箱，提供免费1个月体验机会
官网：https://www.bzg.life/
官群：https://t.me/BZG_group
