### ISSUE TITLE
I built v2ray iOS app nowadays.

### ISSUE THREAD

**Issue by liuyi73191** [v2ray/v2ray-core#3274]
I built v2ray ios and mac app using other sdk. It supports shadowsocks and trojan too.
If you want to develop v2ray app, please contact to me。

Skype: live:.cid.85b9ef80726be21e
QQ：2890152926
Telegram: @GameKing713
Email: [newfuture33@126.com](mailto:newfuture33@126.com)

**Comment by highlander0test** [comment]
刚用v2ray搭建的，大家可以体验一下
欢迎体验
本网站处于推广阶段，联系群主，注册后提供邮箱，提供免费1个月体验机会
官网：https://www.bzg.life/
官群：https://t.me/BZG_group
