### ISSUE TITLE
我有支持vmess aead的iOS的源码

### ISSUE THREAD

**Issue by ghost** [v2ray/v2ray-core#3285]
有需要的联系我
tg：https://t.me/VPNMoney1

**Comment by ghost** [comment]
可以给demo

**Comment by highlander0test** [comment]
刚用v2ray搭建的，大家可以体验一下
欢迎体验
本网站处于推广阶段，联系群主，注册后提供邮箱，提供免费1个月体验机会
官网：https://www.bzg.life/
官群：https://t.me/BZG_group
