### ISSUE TITLE
能否支持 gfwlist ？并且可以把路由设置成默认不走代理？

### ISSUE THREAD

**Issue by dozer47528** [v2ray/v2ray-core#329]
类似 Shadowsocks 客户端的那种做法，默认不走代理，在 gfwlist 中的走代理，也可以手动增加（这个现在有看到）

**Comment by kxjhlele** [comment]
目前除了gfwlist ，其他的需求都支持，看一下帮助的路由部分

**Comment by Lycreal** [comment]
同意，有时不需要全局代理，路由写进配置又太长，维护也麻烦，希望能支持gfwlist

**Comment by vc12345679** [comment]
我猜测，这样可以实现你的要求
1. 把outbound设成freedom直连
2. outboundDetour里配科学上网连接
3. routing里域名策略使用AsIs，配一条rule，使用从gfwlist里提取的域名，指向outboundDetour里的连接

```
{
	"log": {
		"access": "文件地址",
		"error": "文件地址",
		"loglevel": "warning"
	},
	"routing": {
		"strategy": "rules",
		"settings": {
			"domainStrategy": "AsIs",
			"rules": [
				{
					"type": "field",
					"domain": [
						gfwlist提取的域名列表
					],
					"outboundTag": "科学上网连接标签"
				}
			]
		}
	},
	"inbound": {
		本地代理设置
	},
	"outbound": {
		"protocol": "freedom",
		"settings": {}
	},
	"outboundDetour": [
		{
			科学上网连接设置,
			"tag": "科学上网连接标签"
		}
	]
}
```

**Comment by qingyede** [comment]
routing 中的rule里面，删除chinasites，chinaip，然后配合其他switch即可

**Comment by DarienRaymond** [comment]
gfwlist是以LGPL许可发布的，暂时不想和(L)GPL扯上关系，但不排除将来会有某些特殊手段绕过限制。

**Comment by elvisw** [comment]
@DarienRaymond 所以有些代理客户端是用户在使用时才现场下载gfwlist，有的甚至gfwlist的下载地址都需要用户来设置，这就是为了回避gfwlist的LGPL么?

**Comment by DarienRaymond** [comment]
嗯，有可能。

**Comment by kkkgo** [comment]
> gfwlist是以LGPL许可发布的，暂时不想和(L)GPL扯上关系，但不排除将来会用某些特殊手段绕过限制。
能否用外置适配Switchy规则的方法来绕过限制？
https://github.com/v2ray/v2ray-core/issues/1567#issuecomment-466832097

**Comment by Cwek** [comment]
我认为大部分外部的域名清单可以执行编写处理方法来转化为v2的路由清单。

什么，不会写脚本？学什么鬼玩v2（笑）

google的域名、IP信息，都是用用notepad++和excel整理清洗再改写成v2的路由项目的。

**Comment by kkkgo** [comment]
> 我认为大部分外部的域名清单可以自行编写处理方法来转化为v2的路由清单。
> 
> 什么，不会写脚本？学什么鬼玩v2（笑）
> 
> google的域名、IP信息，都是用用notepad++和excel整理清洗再改写成v2的路由项目的。

不为提高程序易用性反而为程序使用门槛高而滋生优越感实在令人费解。
虽然我提的建议官方不一定会采纳，但我相信官方是会朝着提高程序易用性去努力的。
再者，用notepad++和excel整理也不算上是什么比较优雅/令人自豪地使用v2ray的方式，如果你有写的不错的脚本，欢迎为社区贡献。
https://github.com/v2ray/discussion

**Comment by Cwek** [comment]
> > 我认为大部分外部的域名清单可以自行编写处理方法来转化为v2的路由清单。
> > 什么，不会写脚本？学什么鬼玩v2（笑）
> > google的域名、IP信息，都是用用notepad++和excel整理清洗再改写成v2的路由项目的。
> 
> 不为提高程序易用性反而为程序使用门槛高而滋生优越感实在令人费解。
> 虽然我提的建议官方不一定会采纳，但我相信官方是会朝着提高程序易用性去努力的。
> 再者，用notepad++和excel整理也不算上是什么比较优雅/令人自豪地使用v2ray的方式，如果你有写的不错的脚本，欢迎为社区贡献。
> https://github.com/v2ray/discussion

其实你的想法就是从一个成品（gfwlist）转换为另一个成品（v2的路由表项），如果小姐姐愿意专门弄这个专用的转换工具，可以，我也不反对官方的想法，但如果没有的话，只能自己想办法弄，无论是写脚本还是用文本整理。

google的是因为我有这个需求，自己一点点累计资料的，域名从早期搜索到找google自己提供的域名名单，IP也是从HE的BGP摘录。把东西弄得太傻瓜反而引来更多的傻瓜不知道自己在写什么地乱搞一通。

**Comment by elvisw** [comment]
其实V2Ray-Core支持外部geo文件：
这里有人维护了gfwlist的geosite：
https://github.com/ToutyRater/V2Ray-SiteDAT
