### ISSUE TITLE
mac客户端，执行./v2ray-macs --config="point_socks_vmess.json"出现如下错误

### ISSUE THREAD

**Issue by afdnlw** [v2ray/v2ray-core#33]
![screen shot 2015-10-05 at 14 12 44](https://cloud.githubusercontent.com/assets/1336195/10274019/6847a6be-6b6b-11e5-8286-d18c4184772e.png)

客户端是下载的编译好的文件。
请问这个怎么解决。谢谢！

**Comment by v2ray** [comment]
请问你的 out_vmess.json 的内容是什么？

**Comment by afdnlw** [comment]
out_mess.json内容如下：

{
  "vnext": [
    {
      "address": "107.170.234.17”,
      "port": 27183,
      "users": [
        {"id": "40508562-6b1c-11e5-9d70-feff819cdc9f"}
      ],
      "network": "tcp"
    }
  ]
}

 另外，vps端 执行没有报错，

**Comment by v2ray** [comment]
address 后面的引号错了，应该是这个样子：

"address": "107.170.234.17",

**Comment by afdnlw** [comment]
thanks ,
