### ISSUE TITLE
socks: failed to transport all TCP response and writev: broken pipe

### ISSUE THREAD

**Issue by d3athg0d** [v2ray/v2ray-core#3300]
i am getting a lot of this in the logs but not clear what is wrong
2024/06/12 15:34:18 [Debug] transport/internet: dialing to tcp:127.0.0.1:1628
2024/06/12 15:34:18 [Info] [2041544657] proxy/shadowsocks: tunneling request to tcp:r3.o.lencr.org:80 via TCP:127.0.0.1:1628
2024/06/12 15:34:30 [Info] [1734618671] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > writev tcp 127.0.0.1:10091->127.0.0.1:60866: writev: broken pipe
2024/06/12 15:34:30 [Info] [512078344] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > writev tcp 127.0.0.1:10091->127.0.0.1:60881: writev: broken pipe
2024/06/12 15:34:30 [Info] [548881494] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP request > read tcp 127.0.0.1:10091->127.0.0.1:60884: read: connection reset by peer
2024/06/12 15:34:30 [Info] [2291293852] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > writev tcp 127.0.0.1:10091->127.0.0.1:60911: writev: broken pipe
2024/06/12 15:34:30 [Info] [1677176720] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > writev tcp 127.0.0.1:10091->127.0.0.1:60883: writev: connection reset by peer
2024/06/12 15:34:30 [Info] [562782385] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > writev tcp 127.0.0.1:10091->127.0.0.1:60867: writev: broken pipe
2024/06/12 15:34:30 [Info] [3344110513] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > writev tcp 127.0.0.1:10091->127.0.0.1:60851: writev: broken pipe
2024/06/12 15:34:31 [Info] [3628937195] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > writev tcp 127.0.0.1:10091->127.0.0.1:60879: writev: broken pipe
2024/06/12 15:34:31 [Info] [4172243203] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > writev tcp 127.0.0.1:10091->127.0.0.1:60878: writev: broken pipe
2024/06/12 15:34:31 [Info] [2896766123] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > writev tcp 127.0.0.1:10091->127.0.0.1:60912: writev: broken pipe
2024/06/12 15:34:31 [Info] [2300343692] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > writev tcp 127.0.0.1:10091->127.0.0.1:60854: writev: broken pipe
2024/06/12 15:34:31 [Info] [740181955] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > writev tcp 127.0.0.1:10091->127.0.0.1:60885: writev: broken pipe
2024/06/12 15:34:31 [Info] [3636724781] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > writev tcp 127.0.0.1:10091->127.0.0.1:60880: writev: broken pipe
2024/06/12 15:34:31 [Info] [1348059283] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > writev tcp 127.0.0.1:10091->127.0.0.1:60882: writev: broken pipe
2024/06/12 15:34:31 [Info] [1793222317] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > writev tcp 127.0.0.1:10091->127.0.0.1:60914: writev: connection reset by peer
2024/06/12 15:34:31 [Info] [2766699313] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > writev tcp 127.0.0.1:10091->127.0.0.1:60910: writev: broken pipe

config in pictures.

i really appreciate the advices and help.
![CleanShot 2024-06-12 at 15 40 32](https://github.com/v2ray/v2ray-core/assets/78822442/72c27279-163d-4b17-84fd-db0e5fabb8bf)
![CleanShot 2024-06-12 at 15 40 06](https://github.com/v2ray/v2ray-core/assets/78822442/e612b6c3-7ad5-4cc4-ade2-b28cdbb98c8c)

**Comment by highlander0test** [comment]
刚用v2ray搭建的，大家可以体验一下
欢迎体验
本网站处于推广阶段，联系群主，注册后提供邮箱，提供免费1个月体验机会
官网：https://www.bzg.life/
官群：https://t.me/BZG_group
