### ISSUE TITLE
经常网页打不开

### ISSUE THREAD

**Issue by testcaoy7** [v2ray/v2ray-core#331]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
2.10.5

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
使用VMess协议浏览互联网

3) 你看到的不正常的现象是什么？
网页打不开，或者打开了网页上的元素无法正常加载，如果浏览的网页是非HTTPS的，则此现象加剧
使用SS浏览则则没有此现象

4) 你期待看到的正确表现是怎样的？
可以正常浏览互联网

5) 请附上你的配置文件。
```json
{
    "log": {
        "access": "/var/log/v2ray/access.log",
        "error": "/var/log/v2ray/error.log",
        "loglevel": "none"
    },
	"dns": {
		"servers": [
			"8.8.8.8",
			"8.8.4.4"
		]
	},
    "inbound": {
        "port": 443,
	"listen": "0.0.0.0",
        "protocol": "vmess",
        "settings": {
            "clients": [
                {
                    "id": "my id",
                    "level": 1,
                    "alterId": 128
                }
            ]
        },
		"streamSettings": {
			"network": "tcp",
			"security": "tls",
			"tlsSettings": {
				"allowInsecure": true,
				"certificates": [
					{
						"certificateFile": "my cert",
						"keyFile": "my key"
					}
				]
			}
		},
		"allowPassive": false
    },
    "outbound": {
		"sendThrough": "0.0.0.0",
        "protocol": "freedom",
        "settings": {
			"domainStrategy": "UseIP",
			"timeout": 30
		}
    },
    "inboundDetour": [],
    "outboundDetour": [
        {
            "protocol": "blackhole",
            "settings": {
				"response": {
					"type": "http"
				}
			},
            "tag": "blocked"
        }
    ],
    "routing": {
        "strategy": "rules",
        "settings": {
			"domainStrategy": "IPIfNonMatch",
            "rules": [
                {
                    "type": "field",
                    "ip": [
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "203.0.113.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10"
                    ],
                    "outboundTag": "blocked"
                }
            ]
        }
    },
	"transport": {
		"tcpSettings": {
			"connectionReuse": false,
			"header": {
				"type": "none"
			}
		},
		"wsSettings": {
			"connectionReuse": true,
			"path": ""
		}
	}
}
```

**Comment by xiaokangwang** [comment]
建议你附上客户端和服务器段的输出信息。
访问什么网页打不开，如果页面能显示出标题，请使用浏览器的开发者选项给出更详细的信息。

**Comment by testcaoy7** [comment]
@xiaokangwang 举个例子吧，这一现象在浏览非HTTPS网页时表现的比较明显，以Steam（http://store.steampowered.com）为例，浏览时发生游戏介绍页面的图片和视频无法加载

**Comment by testcaoy7** [comment]
PS：如果打开TCP的ConnectionReuse，网络响应会变得十分糟糕，同时爆出很多错误信息：
wsarecv: An existing connection was forcibly closed by the remote host.
wsarecv: An established connection was aborted by the software in your host machine.
wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by cdyfng** [comment]
最近我的使用也没法正常浏览国外网站，一个星期前我用旧版本发现问题。 20161221我更新代码，重新编译，使用原先的配置下还是无法正常浏览。 
你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
2.11.1

你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
设置socks代理，使用chrome等浏览器访问youtube，google等网页

你看到的不正常的现象是什么？
网页打不开，但是国内网站正常使用比如baidu sina
error.log信息如下
2016/12/21 09:33:34 [Warning]VMess|Outbound: Failed to read response from tcp:www.google.com.hk:443: EOF
2016/12/21 09:33:34 [Warning]VMess|Outbound: Failed to read response from tcp:www.google.com.hk:443: EOF
2016/12/21 09:36:22 [Warning]Freedom: Failed to open connection to tcp:api.smoot.apple.com.cn:443: [All retry attempts failed.]
2016/12/21 09:36:44 [Warning]VMess|Outbound: Failed to read response from udp:8.8.8.8:53: EOF
2016/12/21 09:37:40 [Warning]VMess|Outbound: Failed to read response from tcp:live.github.com:443: EOF
2016/12/21 09:38:01 [Warning]VMess|Outbound: Failed to read response from tcp:github.com:443: EOF
2016/12/21 09:38:01 [Warning]VMess|Outbound: Failed to read response from tcp:live.github.com:443: EOF
2016/12/21 09:38:01 [Warning]VMess|Outbound: Failed to read response from tcp:api-glb-ap1.smoot.apple.com:443: EOF
2016/12/21 09:38:58 [Warning]VMess|Outbound: Failed to read response from tcp:assets-cdn.github.com:443: EOF
2016/12/21 09:39:08 [Warning]VMess|Outbound: Failed to read response from tcp:api-glb-ap1.smoot.apple.com:443
access.log 信息如下
2016/12/21 09:37:50 tcp:127.0.0.1:51610 accepted tcp:www.gstatic.com:80 
2016/12/21 09:38:04 tcp:127.0.0.1:51613 accepted tcp:www.youtube.com:443 
2016/12/21 09:38:05 tcp:127.0.0.1:51615 accepted tcp:live.github.com:443 
2016/12/21 09:38:08 tcp:127.0.0.1:51617 accepted tcp:live.github.com:443 
2016/12/21 09:38:19 tcp:127.0.0.1:51619 accepted tcp:github.com:443 
2016/12/21 09:39:20 tcp:127.0.0.1:51651 accepted tcp:collector.githubapp.com:443 
2016/12/21 09:39:20 tcp:127.0.0.1:51652 accepted tcp:live.github.com:443 

你期待看到的正确表现是怎样的？
可以正常浏览互联网

请附上你的配置文件。
[config.txt](https://github.com/v2ray/v2ray-core/files/665281/config.txt)

**Comment by walasix** [comment]
跟楼上同样的问题，版本2.11.1，老版本也是

**Comment by testcaoy7** [comment]
@cdyfng @walasix 你们在SS下就没有这个现象，是吗？

**Comment by agzfan** [comment]
https://github.com/v2ray/v2ray-core/issues/257
1.14版开始,更早的我没试过,这个问题存在了太长时间,从来没有修复过
我发现都是win用户,大胆猜测,win的客户端有问题
我劝你们用ss,真的不是吹b

**Comment by sinfere** [comment]
v2ray.cool 偶尔好像会抽风，可能压力太大，建议自己在服务器端搭一个，再看看情况

**Comment by testcaoy7** [comment]
@sinfere 使用的就是自建的服务器，不止一个，所有自建的服务器（试过美国、日本、韩国、香港、台湾的VPS）都是这样的表现

**Comment by wtlusvm** [comment]
@agzfan 我也不是跟你吹，用了V2Ray这么久，每次出问题都是我的json写的不对导致的，没出现过你这情况，比ss还稳

**Comment by sinfere** [comment]
@testcaoy7 服务端的日志是怎么样的？服务端的配置也发一下

**Comment by testcaoy7** [comment]
@sinfere 我贴的是我服务器的配置文件，所以inbound是vmess，outbound是freedom
刚刚把服务器的loglevel设为debug，结果发现freedom出现不少这样的错误：
`2016/12/24 10:55:18 [Info]Freedom: Failed to transport all TCP response: read tcp 10.140.0.2:24508->184.25.56.34:80: i/o timeout`

以上错误发生在浏览steam过程中，要重现我遇到的现象很容易啊，用TCP传输，逛逛steam或者其他图片很多的网页（比如亚马逊购物）就会体会到了

除此之外，还有以下错误：
`VMess|Inbound: Error when sending data to outbound: io: read/write on closed pipe`
`VMess|Inbound: Error when sending data to outbound: read tcp 10.140.0.2:443->116.237.131.172:59988: read: connection reset by peer`

**Comment by sinfere** [comment]
1. @testcaoy7 看日志的话感觉是服务器访问不到目标网站，但如果用ss等正常的话就暂时没法确定问题了; 等作者看看

2. 尝试把 `"domainStrategy": "UseIP",` 关掉试试

3. 测了v2ray很久了，很稳定

**Comment by testcaoy7** [comment]
@sinfere 感觉像是freedom协议的问题

**Comment by sinfere** [comment]
@testcaoy7 你没给freedom协议配配置streamSettings，那freedom就相当于普通的连接，没什么特别的

**Comment by testcaoy7** [comment]
在做了如下措施后，这一现象已经消失
1、删除服务器和客户端的transport项，不再采用全局，而是采用streamsetting进行分连接配置vmess协议
2、关闭客户端socks5的udp功能
3、为客户端socks5设置超时
4、更新v2ray到最新版本
