### ISSUE TITLE
【建议】为TCP增加倍率发包？

### ISSUE THREAD

**Issue by testcaoy7** [v2ray/v2ray-core#332]
能不能为TCP连接增加双倍发包甚至多倍率发包来提速呢？这样可以显著增加高延迟VPS的响应速度。

**Comment by v2ray** [comment]
V2Ray 不支持也不推荐使用这种方式，请尝试系统自带的 TCP 算法，比如 BBR。

参考：https://github.com/iMeiji/shadowsocks_install/wiki/%E5%BC%80%E5%90%AFTCP-BBR%E6%8B%A5%E5%A1%9E%E6%8E%A7%E5%88%B6%E7%AE%97%E6%B3%95

**Comment by testcaoy7** [comment]
@v2ray 我从4.9 RC7开始用的就是BBR……
