### ISSUE TITLE
各位在用哪个版本的安卓客户端？

### ISSUE THREAD

**Issue by lewisec** [v2ray/v2ray-core#333]
以前是用的V2Ray Go，最近发现翻不出去了，github项目的realease也都删除了，不知道是不是项目停止更新了？换Actinium也翻不出去。不知道各位都在用哪个版本的移动端？

**Comment by v2ray** [comment]
具体错误信息？

**Comment by lewisec** [comment]
服务器上，error.log里面没有任何报错，access.log里面可以看到手机发起的连接。
手机现在用的是Actinium，不管是用我自己vps的配置还是默认的v2ray.cool配置，都不能访问twitter和facebook

**Comment by 6656i** [comment]
国内dns都就会有这问题

**Comment by lewisec** [comment]
经过楼上兄弟提醒，我今天试了下，用v2ray.cool的配置，联通4G手机卡可以翻出去，电信4G不行。
换我自己的配置就是两个卡都不行了。

**Comment by v2ray** [comment]
Will be fixed as https://github.com/v2ray/Planning/issues/8
