### ISSUE TITLE
写了篇 V2Ray 教程，愿意赏脸的请进来看看

### ISSUE THREAD

**Issue by ToutyRater** [v2ray/v2ray-core#334]
地址在这里： https://toutyrater.github.io/v2ray-guide-pages/

很早就开始写了，很多东西都是第一次接触，现学现用，磕磕碰碰的才写了这么点。自个儿看了几遍，不是很满意，后面有时间应该会有一些修正。另外还有一些没写完，一些坑还要补。

进来的是大神的话，欢迎来[这里](https://github.com/ToutyRater/v2ray-guide)指正补充。

**Comment by v2ray** [comment]
非常感谢，已在 Twitter 上的推荐，稍后更新到官网。

**Comment by ToutyRater** [comment]
不用客气的。你能开发 V2Ray 已经是不容易，我写个教程算不上什么

**Comment by theratlesnake** [comment]
看不懂，太复杂了
