### ISSUE TITLE
inbound多端口；ipv6。

### ISSUE THREAD

**Issue by athanoslee** [v2ray/v2ray-core#336]
我有一些文档中没有涉及到的有关服务端的问题：

1. 请问inbound里可以监听多个端口吗？
2. 如果可以，vmess里又设置了多个client，每个client同时可以使用所有监听的端口？
3. v2ray和vmess（的各客户端）对ipv6的支持如何？

**Comment by v2ray** [comment]
1. inboundDetour 中可以设置一个连续的端口范围，或者使用多个 inboundDetour 来监听多个端口；
2. 一个 inbound 只对自己监听的端口有效；
3. 无差别支持 IPv6 并在默认情况下优先使用 IPv6。

**Comment by litao3rd** [comment]
请问一下这里是如何无差别支持 IPv6，我找了你们的文档，也没看到具体配置的地方。我的服务器既有 IPv4，也有 IPv6，客户端网络也支持 IPv6，但是使用的时候，不知道怎么配置优先使用 IPv6，我看链接的 log，使用的链接全是 IPv4。客户端配置的服务器地址，既有域名，（A记录和AAAA记录），也有 IPv4 和 IPv6
