### ISSUE TITLE
Vmess Outbound 连接释放的问题

### ISSUE THREAD

**Issue by sinfere** [v2ray/v2ray-core#339]
https://github.com/v2ray/v2ray-core/blob/master/proxy/vmess/outbound/outbound.go#L82
```go
	var requestFinish, responseFinish sync.Mutex
	requestFinish.Lock()
	responseFinish.Lock()

	session := encoding.NewClientSession(protocol.DefaultIDHash)

	go v.handleRequest(session, conn, request, payload, input, &requestFinish)
	go v.handleResponse(session, conn, request, rec.Destination(), output, &responseFinish)

	requestFinish.Lock()
	responseFinish.Lock()
```

remote <-> proxy <-> client
如果remote和client有一个断开了，整个session都应该结束，上面都应该继续往下执行，现在这样的话，有一方断开了不会让连接释放，会一直hold住，我觉得应该把锁去掉，或者这里是有别的考虑吗？

**Comment by v2ray** [comment]
TCP 可以[单向关闭的](http://superuser.com/questions/298919/what-is-tcp-half-open-connection-and-tcp-half-closed-connection)，在不能排除某些客户端使用这个特性的情况下，V2Ray 只能在 request 和 response 都结束的情况下才主动断开连接。当单边连接断开的时候，V2Ray 依赖客户端（浏览器）或者服务器（网站）来判断是否需要断开连接。

**Comment by sinfere** [comment]
我是在测kcp的时候发现了这个问题；

tcp单向关闭的话，只要某一方再读就会报错，但是proxy其实一直hold住了，不会报错；

tcp断开检测在实际应用中是个很麻烦的问题，sysctl有配置参数，但是实际上不准确

**Comment by sinfere** [comment]
V2Ray实际上没有检测，就是双边断才断

**Comment by sinfere** [comment]
tcp的半开特性应该是transport底层处理的，跟proxy这一层无关，tcp半开，并不会通知上层报错，但是这里上层报错了，就说明底层彻底断开了

**Comment by sinfere** [comment]
总结一下：
1. 测试的时候，kcp明确检测到断开了（超时），但是vmess outbound由于双边hold住，导致连接无法释放

2. tcp半开应该是底层(transport)处理的特性，就像kcp这里，如果重启后仍然能找到序号接着发，连接就能恢复；但是传递到上层了就说明一定断开了

**Comment by sinfere** [comment]
这个问题跟半开无关

**Comment by v2ray** [comment]
TCP 单向关闭会触发 read EOF 或者 writer error 的，你碰到的死锁应该是 KCP 的问题，见 29d62185cffd486b8d9a0f6512303b806450bfe1

**Comment by sinfere** [comment]
这是前面的一条：“tcp单向关闭的话，只要某一方再读就会报错，但是proxy其实一直hold住了，不会报错；”

所以你也同意我说的；

回到最开始的问题，是不是一边断了，两边就要全断？

“TCP 可以单向关闭的，在不能排除某些客户端使用这个特性的情况下，V2Ray 只能在 request 和 response 都结束的情况下才主动断开连接。”

TCP的这个特性，与request和response无关，是TCP底层的行为；request和response这里不应该去管底层，也管不了底层

**Comment by sinfere** [comment]
@29d62185cffd486b8d9a0f6512303b806450bfe1 这个实际上仍然会hold，断开了一边，另外一边没断，request和response的那种写法，只有两边断了才会结束

**Comment by v2ray** [comment]
一边断开，另一边不必要断开。V2Ray 的作用在客户端和服务器之间是传输数据，在一边断开的情况下，由客户端或服务器来决定是否要中断整个连接。在读取 request 或 response 时出错（如数据不完整），V2Ray 并不知道怎样才是正确的响应，比如客户端（或服务器）可能会直接关闭连接（和你建议的一样），也可能在另一边发送一些数据再断开。

你描述的问题应该是某个实现上的 bug，比如该通知的没有通知到，而不是这个设计上的问题。

**Comment by sinfere** [comment]
我觉得这个是设计上的问题，实际上就会导致too many open files，新的连接进不来；
一方断了，代理没有理由不断开另一方，断开是代理应该做的事情，不应该hold，这样会给另一方带来错误的信息；

**Comment by v2ray** [comment]
690d71b16e1ab87a75876e2286f557f2a4452aa1 609dbc1f130c97fa2a8e144151a15667afd963ea 稍微改进了一下，在传输出问题时（如解密验证失败），V2Ray 会快速关闭连接。

**Comment by sinfere** [comment]
👍
