### ISSUE TITLE
linux ubuntu12 一键脚本安装过程中 在unzip 解压/tmp/v2ray/v2ray.zip 这块说找不到这个文件

### ISSUE THREAD

**Issue by cattle-king** [v2ray/v2ray-core#346]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please answer the following questions before submitting your issue. Thank you.

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
1) What version of V2Ray are you using?
一件脚本自动安装的。
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
2) What your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

3) 你看到的不正常的现象是什么？
3) What did you see?
安装过程中unzip加压找不到v2ray.zip文件,但目录中存在该文件。
4) 你期待看到的正确表现是怎样的？
4) What do you expected to see instead?
可以正常安装
5) 请附上你的配置文件。
5) Please attach your configuration file.
![image](https://cloud.githubusercontent.com/assets/24292115/21560464/9106c524-ce9a-11e6-81f4-e55b955eabc2.png)

**Comment by wtlusvm** [comment]
没什么好说的，因为你根本没下完那个zip包，国内用github是这样的，网络问题

**Comment by cattle-king** [comment]
那这种情况只能下载了自己上传手动装了？有没有离线安装包的？

**Comment by wtlusvm** [comment]
[在这里](https://github.com/v2ray/v2ray-core/releases)把最新的zip包下载下来然后解压，看一键安装脚本把文件放在该放的地方咯。

**Comment by v2ray** [comment]
你可以手动下载安装包放在 VPS 上，下载地址如图片上：https://github.com/v2ray/v2ray-core/releases/download/v2.12.1/v2ray-linux-64.zip

然后使用同样的安装脚本进行安装：`./go.sh --version 2.12.1 --local v2ray-linux-64.zip`

**Comment by cattle-king** [comment]
@v2ray 你好，我在安装过程中使用离线包安装，unzip的问题解决了，但是之后的安装步骤仍然出现文件和目录不存在的问题，机器是阿里云的国内机器。
