### ISSUE TITLE
vmess + kcp + http proxy failed read responce

### ISSUE THREAD

**Issue by Ehekatl** [v2ray/v2ray-core#347]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
2.12.1 这个bug有很久了 之前在telegram里也提过
2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
`https_proxy=10.200.1.4:1080 wget https://github.com/openresty/echo-nginx-module/archive/v0.57.tar.gz`
请用这个测试
三次里两次可复现
3) 你看到的不正常的现象是什么？
` [Warning]VMess|Outbound: Failed to read response from tcp:codeload.github.com:443: EOF`
4) 你期待看到的正确表现是怎样的？
一切正常
5) 请附上你的配置文件。
client: https://gist.github.com/Ehekatl/31a52599d3579e4c42de117400f37aa7
server: https://gist.github.com/Ehekatl/dbaaa9249f6ff01f7d37c54b3a48d35d

**Comment by Ehekatl** [comment]
用不用kcp都一样的结果

**Comment by DarienRaymond** [comment]
已在2.47中修复
