### ISSUE TITLE
Chrome's maximum six TCP connection per origin rule，网站需要长时间等待

### ISSUE THREAD

**Issue by sinfere** [v2ray/v2ray-core#348]
最近几天一直被偶尔打开会很慢这个困扰，通常谷歌开几次之后再打开都是要等10秒，我各种怀疑是代理的问题：
1. 慢慢排查，发现是accept连接有非常大的延迟，从刷新页面到日志出现accept，大概10秒
2. 怀疑是底层tcp到golang的问题，tcpdump的时候发现SYNC包同样也出现了10秒的延迟
3. chrome下面，debug，发现慢的情况是因为stalled10秒
![image](https://cloud.githubusercontent.com/assets/1476105/21565105/c1bf87b2-cece-11e6-84ac-32c1a80168a1.png)
4. 发现了各个浏览器对发往同一个host的连接数都有限制：https://bugs.chromium.org/p/chromium/issues/detail?id=12066

看了一些新一点的chromium issue，这个限制已经调整到16了，但是仍然远远不够

这个问题应该怎么破？

**Comment by sinfere** [comment]
但是shadowsocks不会出现这种情况，尴尬...

**Comment by v2ray** [comment]
用了 DNS 吗？在路由中查询 DNS 的话，会有这个问题。

**Comment by sinfere** [comment]
DNS全去掉了，最开始也以为是DNS，后来发现还是有这个问题，stalled太长

**Comment by sinfere** [comment]
升级到新版之后，感觉没这个问题了，感觉是不是连接没有及时释放导致浏览器误判，准备关闭这个issue

都是“感觉”，尴尬

**Comment by testcaoy7** [comment]
@sinfere 客户端的inbound一般是socks，增加timeout项，设置一个较小的数值试试

**Comment by sinfere** [comment]
@testcaoy7 没有收到TCP的SYN包

**Comment by sinfere** [comment]
终于确定了问题所在...

@v2ray 

旧的很多transport写法是，伪代码：
```
func transport {
    defer close

    go request pipe

    response pipe 
}
```

当request goroutine失败，并不会导致response pipe停止，连接仍然一直hold住，导致连接没有释放；这样没有收到SYN包也合理了，因为前一个连接还没释放

这个问题可以稳定重现；已确认

困扰了我两周的问题，每天debug到三四点，终于确定原因了

**Comment by sinfere** [comment]
连接释放太重要了
