### ISSUE TITLE
服务器端以最大流量发送数据的问题？

### ISSUE THREAD

**Issue by cnperi** [v2ray/v2ray-core#349]
一个奇怪的故障。
更新到最新版2.12.1后，不定时出现这种问题，表现如图：
![linode](https://cloud.githubusercontent.com/assets/10166311/21577510/3c0f6f04-cf98-11e6-9092-d65ef0b1e142.png)
传输模式是kcp。服务器突然以最大流量向外传输数据，但是从服务器本身的in/out来看，没有in只有out，像是在反复重传。查看服务器和客户端的log，没有错误。
服务器端v2ray重启后又恢复正常。

**Comment by cnperi** [comment]
最近的一次，放大后如下：
![linode 2](https://cloud.githubusercontent.com/assets/10166311/21577537/11f78606-cf99-11e6-84d0-e246b687de9c.png)
明显可见：in/5xxMB，out/3xGB

**Comment by cnperi** [comment]
今天又出现一次，未干预持续一小时多后恢复正常。

服务器配置如下：
{
	"log" : {
		"access": "/var/log/v2ray/access.log",
		"error": "/var/log/v2ray/error.log",
		"loglevel": "warning"
	},
	"inbound": {
		"port": ****,
		"protocol": "vmess",
		"settings": {
			"clients": [
			{
				"id": "****",
				"level": 1,
				"alterId": 128
			}
			],
			"features": {}
		},
		"streamSettings": {
			"network": "kcp",
			"kcpSettings": {
				"uplinkCapacity": 5,
				"downlinkCapacity": 100,
				"congestion": true
			}
		}
	},
	"inboundDetour": [
	{
		"port": ****,
		"protocol": "vmess",
		"settings": {
			"clients": [
			{
				"id": "****",
				"level": 1,
				"alterId": 128
			}
			],
			"features": {}
		},
		"streamSettings": {
			"network": "kcp",
			"kcpSettings": {
				"uplinkCapacity": 2,
				"downlinkCapacity": 100,
				"congestion": true
			}
		}
	}
	],
	"outbound": {
		"protocol": "freedom",
		"settings": {}
	},
	"outboundDetour": [
	{
		"protocol": "blackhole",
		"settings": {},
		"tag": "blocked"
	}
	],
	"routing": {
		"strategy": "rules",
		"settings": {
			"rules": [
			{
				"type": "field",
				"ip": [
					"0.0.0.0/8",
					"10.0.0.0/8",
					"100.64.0.0/10",
					"127.0.0.0/8",
					"169.254.0.0/16",
					"172.16.0.0/12",
					"192.0.0.0/24",
					"192.0.2.0/24",
					"192.168.0.0/16",
					"198.18.0.0/15",
					"198.51.100.0/24",
					"203.0.113.0/24",
					"::1/128",
					"fc00::/7",
					"fe80::/10"
				],
				"outboundTag": "blocked"
			}
			]
		}
	}
}

**Comment by wtlusvm** [comment]
要不你顺手把log也放上来吧，最好是debug级别的

**Comment by cnperi** [comment]
升级到2.14以上版本后，没再发生这种情况了。具体原因不知。
