### ISSUE TITLE
一件安装脚本go.sh安装过程出现No such file or directory

### ISSUE THREAD

**Issue by cattle-king** [v2ray/v2ray-core#353]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please answer the following questions before submitting your issue. Thank you.

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
2.13.1
1) What version of V2Ray are you using?

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
2) What your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
测试v2ray
3) 你看到的不正常的现象是什么？
3) What did you see?
go.sh 安装离线包出现很多 No such file or directory

4) 你期待看到的正确表现是怎样的？
4) What do you expected to see instead?
正常安装
5) 请附上你的配置文件。
5) Please attach your configuration file.
我的安装命令是：./go.sh --version 2.13.1 --local /root/v2ray-linux-64.zip
机器是国内的阿里云机器

下面是安装的过程日志：
./go.sh --version 2.13.1 --local /root/v2ray-linux-64.zip
Installing V2Ray 2.13.1 on x86_64
Extracting V2Ray package to /tmp/v2ray.
Updating software repo via apt-get.
Installing unzip via apt-get.
Selecting previously unselected package unzip.
(Reading database ... 79605 files and directories currently installed.)
Unpacking unzip (from .../unzip_6.0-4ubuntu2.5_amd64.deb) ...
Processing triggers for man-db ...
Setting up unzip (6.0-4ubuntu2.5) ...
Archive:  /tmp/v2ray/v2ray.zip
  inflating: /tmp/v2ray/v2ray-v2.13.1-linux-64/systemd/v2ray.service  
  inflating: /tmp/v2ray/v2ray-v2.13.1-linux-64/systemv/v2ray  
  inflating: /tmp/v2ray/v2ray-v2.13.1-linux-64/v2ray  
  inflating: /tmp/v2ray/v2ray-v2.13.1-linux-64/vpoint_socks_vmess.json  
  inflating: /tmp/v2ray/v2ray-v2.13.1-linux-64/vpoint_vmess_freedom.json  
cp: cannot stat `/tmp/v2ray/v2ray-2.13.1-linux-64/v2ray': No such file or directory
chmod: cannot access `/usr/bin/v2ray/v2ray': No such file or directory
cp: cannot stat `/tmp/v2ray/v2ray-2.13.1-linux-64/vpoint_vmess_freedom.json': No such file or directory
sed: can't read /etc/v2ray/config.json: No such file or directory
sed: can't read /etc/v2ray/config.json: No such file or directory
PORT:25099
UUID:7c388f65-b374-40cd-a407-a3ca1f5a0046
Installing daemon via apt-get.
Selecting previously unselected package daemon.
(Reading database ... 79623 files and directories currently installed.)
Unpacking daemon (from .../daemon_0.6.4-1_amd64.deb) ...
Processing triggers for man-db ...
Setting up daemon (0.6.4-1) ...
cp: cannot stat `/tmp/v2ray/v2ray-2.13.1-linux-64/systemv/v2ray': No such file or directory
chmod: cannot access `/etc/init.d/v2ray': No such file or directory
update-rc.d: /etc/init.d/v2ray: file does not exist
V2Ray 2.13.1 is installed.

**Comment by cattle-king** [comment]
@v2ray  https://github.com/v2ray/v2ray-core/issues/346 当时有在这个帖子开帖询问，得到您的回复后我用离线方式安装出现了如上错误，请问这种问题如何解决，是脚本不兼容吗？

**Comment by cattle-king** [comment]
发现问题了，那天你回复我的命令里在版本号这里你少些了一个v，正确的命令应该是./go.sh --version v2.13.1 --local /root/v2ray-linux-64.zip

**Comment by wtlusvm** [comment]
那就麻烦你关掉这个issue吧……
