### ISSUE TITLE
websocket 使用 80 端口可能出现连接失败

### ISSUE THREAD

**Issue by zckevin** [v2ray/v2ray-core#356]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please answer the following questions before submitting your issue. Thank you.

1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
1) What version of V2Ray are you using?
2.14

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
2) What your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
使用 websocket 连接中转服务器，中转服务器连接墙外服务器。中转服务器使用 80 端口。

3) 你看到的不正常的现象是什么？
3) What did you see?
连接长时间无相应，经过 wireshark 抓包，发现 HTTP upgrade 失败。

4) 你期待看到的正确表现是怎样的？
4) What do you expected to see instead?
HTTP upgrade，切换 websocket 协议。

5) 请附上你的配置文件。
5) Please attach your configuration file.
{
  "log": {
    "loglevel": "debug",
    "access": "/home/user/v2ray/logs/access.log",
    "error": "/home/user/v2ray/logs/error.log"
  },
  "inbound": {
    "port": 1085,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "xxxxx.com",
          "port": 80,
          "users": [
            {
              "id": "xxxxxx",
              "alterId": 64
            }
          ]
        }
      ]
    },
    "streamSettings": {
        "network": "ws"
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": "1-52",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "54-79",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "81-442",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "444-65535",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        }
      ]
    }
  },
  "transport": {
    "kcpSettings": {
      "uplinkCapacity": 1,
      "downlinkCapacity": 10
    },
    "wsSettings": {
      "connectionReuse": true,
      "path": ""
    }
  }
}

**Comment by v2ray** [comment]
有没有具体的 upgrade 失败的原因？

**Comment by zckevin** [comment]
不好意思忘了附上原因，抱歉。

原因是使用的 gorilla/websocket 在发送 HTTP Upgrade 请求时，HTTP header 如下：

> GET / HTTP/1.1
> Host: server.golang.org:80
> User-Agent: Go-http-client/1.1
> Connection: Upgrade
> Sec-WebSocket-Key: KwWrZH/AjSGnQ==
> Sec-WebSocket-Version: 13
> Upgrade: websocket

我遇到的情况是，Header 中的 Host 字段 server.golang.org:80 在多主机环境下可能导致匹配失败、HTTP 请求僵死，而去掉端口使用 server.golang.org 则正常。感觉这个可能是特殊情况。

Google 了一下，Host 字段只有在非 80 端口时是必须的。

> See section 14.23 of the HTTP spec which specifies that the port # should be included if its not the default port of 80.
[Is Port Number Required in HTTP “Host” Header Parameter?](http://stackoverflow.com/questions/3364144/is-port-number-required-in-http-host-header-parameter)

**Comment by zckevin** [comment]
多谢，辛苦了！
