### ISSUE TITLE
关于TLS流量特征的疑问

### ISSUE THREAD

**Issue by kxyzw** [v2ray/v2ray-core#357]
想请教一下，如果用传输选择TLS会不会导致流量容易被识别？用TLS的话流量特征会和一般HTTPS代理的特征相似吗？会和基于SSL的VPN的特征相似吗？
谢谢~

**Comment by v2ray** [comment]
V2Ray 的 TLS 是标准 TLS，会被识别为和正常 HTTPS 流量一样的流量类型，不具有其它额外的特征。不了解基于 SSL 的 VPN，从 TLS (SSL) 的角度来说应该是一样的，但不排除 VPN 有其它可被识别的特征。

**Comment by kxyzw** [comment]
@v2ray  嗯，根正常访问https网页的流量特征一样的话应该不容易被发现。如果v2ray运行在443端口，能在收到网页请求的时候（也就是浏览器打开 https://v2ray-tls-server/ ）返回一个404或者302，甚至是一个自定义的网页，那就更加像正常的网页服务器了。

**Comment by v2ray** [comment]
目前的解决方案是通过 WebSocket （见[传输配置](https://www.v2ray.com/chapter_02/05_transport.html)中的 wsSettings）+ TLS 来伪装成正常的 HTTPS 流量。这个 HTTPS 流量可以被常见的 Web server （如 Nginx）代理并分流，于是服务器端可以做成一个正常的网页服务器。

**Comment by testcaoy7** [comment]
@v2ray WS+TLS可以用CloudFlare加速么？

**Comment by v2ray** [comment]
可以通过 CF 中转，有没有“加速”效果就是另一说了。

**Comment by kxyzw** [comment]
@v2ray 网站上好像没见到关于WebSocket配置的详细介绍……？是不是network设成ws，然后客户端和服务器端wsSettings保持一致就可以运行了？然后如果要用Nginx分流的话，比如v2ray监听8888，nginx就把请求路径和path一致的请求转到8888端口就可以了？

**Comment by v2ray** [comment]
1. 介绍：https://www.v2ray.com/chapter_02/05_transport.html
2. 是的
3. 是的
4. 被暴露 WebSocket 的 path。具体的传输内容不会有安全问题。

**Comment by kxyzw** [comment]
明白了，谢谢。

**Comment by daiaji** [comment]
@testcaoy7 @ghost 似乎免费配额的CloudFlare不能转WebSocket
我用Apache搭了这么个玩意……
但是不行RewriteEngine On
```
RewriteCond %{HTTP:Upgrade} =websocket [NC]
RewriteRule /(.*)           ws://localhost:6800/$1 [P,L]
RewriteCond %{HTTP:Upgrade} !=websocket [NC]

ProxyPass /jsonrpc http://localhost:6800/jsonrpc
ProxyPassReverse /jsonrpc http://localhost:6800/jsonrpc
```
关掉CloudFlare就OK

**Comment by testcaoy7** [comment]
@daiaji 能中转WS，我就是在用CF优化Virmach的VPS，把延迟从230+降到160+

**Comment by daiaji** [comment]
@testcaoy7 你用的并不是WSS？

**Comment by sisx** [comment]
WebSocket 的 path，直接访问时提示：bad request.
我理解是这是正常的，
但是被Chrome提示"与此网站之间建立的连接不安全"，会不会影响到安全性？
