### ISSUE TITLE
是否有考虑增加PPTP的inbound协议？

### ISSUE THREAD

**Issue by ukid** [v2ray/v2ray-core#359]
我现在科学上网姿势为shadowsocks client->墙内vps->vmess->墙外vps->自由世界。由于墙内PPTP不做拦截，配置起来也方便，是否考虑增加PPTP的inbound协议？

**Comment by testcaoy7** [comment]
支持，如果能把v2ray变成vpn的话打游戏就方便了

**Comment by sinfere** [comment]
那为什么不直接在墙内vps上部署pptp服务器，然后试试iptable转发？

**Comment by testcaoy7** [comment]
@sinfere 如果v2ray本身支持vpn接入的话就不需要国内vps了

**Comment by ukid** [comment]
@sinfere 当然可以这么做，程序员都有洁癖嘛，如果插件能解决岂不是更好。
@testcaoy7 墙外直接使用标准VPN协议会被封。

**Comment by testcaoy7** [comment]
@ukid 不是的，如果v2ray支持pptp inbound的话，那么就是pptp连本地127.0.0.1，v2ray将pptp转换成vmess连服务器

**Comment by sinfere** [comment]
洁癖应该是更加clean才对，集成这么多维护成本很大，现有的组件都不太完美

**Comment by sinfere** [comment]
我感觉 @testcaoy7 非常自信，inbound支持的话放本地和放国内vps没区别

**Comment by xiaokangwang** [comment]
需要注意的是V2Ray目前并不支持数据包合并到数据流的过程。

然后现在有准备支持tuntap，但是进度暂时有生之年。

肯定要先支持tuntap才能支持pptp，然后你们有没有想认领开发的？

**Comment by ukid** [comment]
@xiaokangwang 非常感谢~ 
本人不太擅长网络编程驱动开发啥的，欢迎有志之士助攻！

**Comment by v2ray** [comment]
如果要加 VPN 协议的话也应该是 AnyConnect (OpenConnect)，PPTP 已被证实不安全了。不过 VPN 的实现非常复杂，并且 Golang 的支持有点欠缺（DTLS），暂时不列入计划中。

**Comment by kxyzw** [comment]
电脑上使用的话，配合Proxifier已经可以几乎完美的实现类似VPN的全局代理效果，感觉没必要专门做VPN。

**Comment by Meeepooo** [comment]
尝试国内搭l2tp然后iptables给v2ray，，弄了半天没弄好，，有大佬可以提供点iptables的配置吗，感觉这方面资料好少

**Comment by alechy** [comment]
感觉,应该用 badvpn 转tun 啥啥啥的来搞搞..以前看到过一个帖子 ss 转 vpn全局...

**Comment by gam2046** [comment]
vpn (pptp/l2tp) over v2ray 比较大的现实意义是，国内直连境外VPN是比较困难的，而通过v2ray的伪装后，具有较好穿墙能力。
而用户侧，一方面可以直接满足某些场景下需要的全局代理能力，另一方面也更便于做策略路由（如使用Routeos）
