### ISSUE TITLE
KCP数据包头部伪装导致EOF

### ISSUE THREAD

**Issue by zhouzhiwen2000** [v2ray/v2ray-core#367]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
2.15.1
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
chrome访问网站 通过VMESS,开启动态端口，kcp通道和kcp头部伪装
3)  你看到的不正常的现象是什么？
    What did you see?
客户端报错：
2017/01/22 20:59:08 [Debug]KCP|Connection: #53919 entering state 1 at 30005
2017/01/22 20:59:08 [Debug]KCP|Connection: #53918 sending terminating cmd.
2017/01/22 20:59:09 [Debug]KCP|Connection: #53918 sending terminating cmd.
2017/01/22 20:59:10 [Debug]KCP|Connection: #53918 sending terminating cmd.
2017/01/22 20:59:10 [Debug]KCP|Connection: #53918 entering state 5 at 38013
2017/01/22 20:59:10 [Info]KCP|Connection: Terminating connection to 23.105.***.***:35***
2017/01/22 20:59:10 [Info]VMess|Client: Failed to read response header: EOF
2017/01/22 20:59:10 [Info]VMess|Outbound: Connection ending with EOF
4)  你期待看到的正确表现是怎样的？
    What's your expectation?

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Server Configuration File（服务器端配置文件）:
    ```javascript
    // 在这里附上服务器端配置文件
    // Please attach your server configuration file here.
    ```
    {
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 35***,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "6429d93b-102b-********************",
          "level": 1,
          "alterId": 64
        },
        {
          "id": "5c0ff724-fc05-*******************",
          "level": 1,
          "alterId": 64
        }
      ],
"detour": {
        "to": "detour"
      }
    },
  "streamSettings": {
    "network": "kcp"
  }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
"inboundDetour": [
    {
      "protocol": "vmess",
      "port": "30001-30100",
      "tag": "detour",
      "settings": {},
      "allocate": {
        "strategy": "random",
        "concurrency": 2,
        "refresh": 10
      },
    "streamSettings": {
      "network": "kcp"
    }
    }
  ],
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  },
  "transport": {
    "kcpSettings": {
      "uplinkCapacity": 2,
      "downlinkCapacity": 100,
    "header": {
      "type": "wechat-video"
    }
    }
  }
}

    Client Configuration File（客户端配置文件）:
    ```javascript
    // 在这里附上客户端配置文件
    // Please attach your client configuration file here.
    ```
{
  "inbound": {
    "port": 1082,
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
	  "udp": false
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "23.105.******",
          "port": 352**,
          "users": [
        {
          "id": "***************",
          "level": 1,
          "alterId": 64
        }
      ]

        }
      ]
    },
	    "streamSettings": {
      "network": "kcp"
    }
  },
  "kcpSettings": {
    "mtu": 1350,
    "tti": 20,
    "uplinkCapacity": 2,
    "downlinkCapacity": 100,
    "header": {
      "type": "wechat-video"
    }
  }
  }
    
6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.

    Server Log File（服务器端日志）:
    ```服务端无错误日志，只有：
2017/01/22 04:14:00 [Warning]V2Ray started.
2017/01/22 04:16:28 [Warning]V2Ray started.
2017/01/22 04:17:56 [Warning]V2Ray started.
2017/01/22 04:19:52 [Warning]V2Ray started.
2017/01/22 04:21:07 [Warning]V2Ray started.
2017/01/22 04:43:41 [Warning]V2Ray started.
2017/01/22 04:45:48 [Warning]V2Ray started.
2017/01/22 07:26:47 [Warning]V2Ray started.
2017/01/22 07:30:59 [Warning]V2Ray started.
2017/01/22 07:32:00 [Warning]V2Ray started.
2017/01/22 07:54:31 [Warning]V2Ray started.
2017/01/22 07:56:02 [Warning]V2Ray started.
2017/01/22 07:57:13 [Warning]V2Ray started.
2017/01/22 07:58:39 [Warning]V2Ray started.
2017/01/22 07:59:18 [Warning]V2Ray started.
（多因为调试重启了好几次）
    
    Client Log File（客户端日志）:
 2017/01/22 20:59:08 [Debug]KCP|Connection: #53919 entering state 1 at 30005
2017/01/22 20:59:08 [Debug]KCP|Connection: #53918 sending terminating cmd.
2017/01/22 20:59:09 [Debug]KCP|Connection: #53918 sending terminating cmd.
2017/01/22 20:59:10 [Debug]KCP|Connection: #53918 sending terminating cmd.
2017/01/22 20:59:10 [Debug]KCP|Connection: #53918 entering state 5 at 38013
2017/01/22 20:59:10 [Info]KCP|Connection: Terminating connection to 23.105.***.***:35***
2017/01/22 20:59:10 [Info]VMess|Client: Failed to read response header: EOF
2017/01/22 20:59:10 [Info]VMess|Outbound: Connection ending with EOF

——————————————————————————————————————————————
服务器和客户端的uuid一样的，kcp头部的type四种都试过，只有none行。

**Comment by DarienRaymond** [comment]
应该已经修复，请使用最新版本。
