### ISSUE TITLE
when client close, still have many CLOSE_WAIT connection in server

### ISSUE THREAD

**Issue by XGHeaven** [v2ray/v2ray-core#370]
1)  你正在使用哪个版本的 V2Ray？
server v2.15.1
client shadowsocks

2)  你的使用场景是什么？

当客户端关闭 shadowsocks 的时候，按理来说就会释放所有的连接。那么服务器在收到客户端断开连接的请求的时候也会释放所有的连接，但是现在来看，当所有的客户端都断开与 v2ray 的连接之后，v2ray 并没有释放所有的连接，相反相关的连接进入了 `CLOSE_WAIT` 的状态。
![image](https://cloud.githubusercontent.com/assets/9291212/22273291/d7b87a90-e2da-11e6-9c18-8db595e6e818.png)
我是监听了 8484 端口，可以看到有大量的 `CLOSE_WAIT`
![image](https://cloud.githubusercontent.com/assets/9291212/22273314/f251c88e-e2da-11e6-9226-c558ed355c64.png)
可以看到在 8484 端口上，有 137 个 `CLOSE_WAIT` 和 250 个 正在使用的连接，但是我就3个设备，怎么会产生这么多的连接？

#339 中有人提到过这个问题。不过感觉这个问题似乎并没有修复的样子。 TCP 是可以单向关闭，但是最起码客户端都关闭了连接，服务器也要关闭吧~~

3)  你看到的不正常的现象是什么？

客户端关闭之后，连接并没有正常的关闭

4)  你期待看到的正确表现是怎样的？

客户端关闭之后，连接正确释放。

**Comment by v2ray** [comment]
Fixed in 2.16.4.
