### ISSUE TITLE
某些网站通过V2ray后无法打开

### ISSUE THREAD

**Issue by Gzxhwq** [v2ray/v2ray-core#372]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

服务器端debian和客户端win10都是v2ray 2.15.1

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

Firefox全局通过v2ray访问www.cnbeta.com

3)  你看到的不正常的现象是什么？
    What did you see?

打不开www.cnbeta.com，删除和加上chinasites和chinaip一样结果，通过同服务器的SS可以打开

4)  你期待看到的正确表现是怎样的？
    What's your expectation?

能打开www.cnbeta.com

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Server Configuration File（服务器端配置文件）:
    ```javascript
    // 在这里附上服务器端配置文件
    // Please attach your server configuration file here.
    ```
    
    Client Configuration File（客户端配置文件）:
    ```javascript
    // 在这里附上客户端配置文件
    // Please attach your client configuration file here.
    ```
    
6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.

    Server Log File（服务器端日志）:
    ```
    // 在这里附上服务器端日志
    // Please attach your server log here.
    ```
    
    Client Log File（客户端日志）:
    ```
    // 在这里附上客户端日志
    // Please attach your client log here.
    ```

**Comment by DarienRaymond** [comment]
目测是你的服务器或是配置问题。
