### ISSUE TITLE
有没有办法把v2ray变成vpn？

### ISSUE THREAD

**Issue by metalwood** [v2ray/v2ray-core#373]
目前稳定好用的vpn软件很少，搭建v2ray很方便，也比较稳定。

但是，有些软件客户端默认无法走v2ray、shadowsocks的socks代理，比如一些软件内置网络下载、GIT等等。这种情况下必须用vpn。

所以我想，有没有这样的软件，可以在使用了v2ray客户端的机器上，把v2ray变成vpn？自己用的电脑是mac、windows，谢谢！

**Comment by lcdtyph** [comment]
v2ray可以开http代理，基本所有软件可以用http代理，git可以在.gitconfig中该设置

**Comment by testcaoy7** [comment]
目前还不行，只是个代理服务器

**Comment by wtlusvm** [comment]
如果需要VPN的话，可以试试[SoftEther VPN](https://www.softether.org/)

**Comment by v2ray** [comment]
目前的解决方案是使用 proxifier 之类的工具让软件走代理，或者在路由器上设置透明代理。

**Comment by md11235** [comment]
试试badvpn。。。 @nifflerfox

**Comment by rufengsuixing** [comment]
sstap
