### ISSUE TITLE
v2ray为什么不能当单独的socks代理用？

### ISSUE THREAD

**Issue by metalwood** [v2ray/v2ray-core#376]
macOS

v2rayx最新版https://github.com/Cenmrev/V2RayX

Chrome中可以正常使用翻墙到google.com等，但是，Android Studio下载安装Android SDK时由于服务器被墙，需要使用自定义的代理，于是我在AndroidStudio的代理设置中使用Socks代理，127.0.0.1:1081，却始终无法下载Android SDK。请问是怎么回事？ShadowSocks也是这样。有没有人知道怎么解决？

**Comment by XGHeaven** [comment]
估计是你配置 socks 几的问题吧，你仔细看看 android sdk 的代理配置

**Comment by v2ray** [comment]
请贴上配置和错误信息。

**Comment by v2ray** [comment]
Closing as inactivity.

**Comment by Insofan** [comment]
我用android studio 也走不了v2ray的sock代理, sock确定可以用, 只能添加ss协议然后android studio用ss协议才能下载

**Comment by kslr** [comment]
取决于你的gradle

**Comment by wmxzrs** [comment]
![image](https://user-images.githubusercontent.com/55049173/119118775-232feb80-ba5d-11eb-9398-ce848044ee28.png)
这样成功了，v2ray

**Comment by wmxzrs** [comment]
但是依然搞不懂自动检测系统代理那个为什么不能代理它
