### ISSUE TITLE
Windows 版本不能多开了？

### ISSUE THREAD

**Issue by Remonli** [v2ray/v2ray-core#378]
2.16 之前一直是用vbs多开，代码如下：
```
ws.Run "D:\Programs\V2ray\v2ray.exe -config s1-kcp.json",0,False
wscript.sleep 1000
ws.Run "D:\Programs\V2ray\v2ray.exe -config s2-kcp.json",0,False
wscript.sleep 1000
ws.Run "D:\Programs\V2ray\v2ray.exe -config s3-kcp.json",0,False
wscript.sleep 1000
```

今天升级2.16.1完全断掉不能用，2.16.2 却不能多开了？只有s1-kcp.json 这个配置生效了。

**Comment by Remonli** [comment]
换回2.15.1 多开正常

**Comment by v2ray** [comment]
请附上你的配置文件

**Comment by Remonli** [comment]
抱歉，配置如下,几个不同的配置主要是inbound的端口和outbound的端口不同，outbound指向
kcptun的监听端口。所以是不是inbound detour的dokodemo-door 的53端口被占用，新版旧版在
这部分的处理方式不一样？

`{
  "log": {
     "loglevel": "warning"
  },
  "inbound": {
    "port": 5500,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    }
  },
   "inboundDetour": [
      {
      "protocol": "dokodemo-door",
      "port": 53,
      "listen": "127.0.0.1",
      "settings": {
        "address": "8.8.8.8",
        "port": 53,
        "network": "udp",
        "timeout": 0,
        "followRedirect": false
         }
      }
    ],
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "localhost",
          "port": 22000,
          "users": [
            {
              "id": "cb531081-6f29-88aa-a1d6-61afe40de480",
              "alterId": 20
            }
          ]
        }
      ]
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": "1-52",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "54-79",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "81-442",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "444-65535",
          "outboundTag": "direct"
        },
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        }
      ]
    }
  }
}`

**Comment by v2ray** [comment]
是的，在启动的时候会检测端口情况，如果被占用会报错并退出。
