### ISSUE TITLE
内存溢出

### ISSUE THREAD

**Issue by mickeyandkaka** [v2ray/v2ray-core#38]
我在搬瓦工ubuntu上搭了一个server
512mb内存已经吃了70%多了

mickey   28474  0.5 73.9 479760 387452 ?       Sl   10月06  30:36 ./server --config=/home/mickey/work/src/github.com/v2ray/v2ray-core/release/config/vpoint_vmess_freedom.json

ubuntu14.04 server 64位

**Comment by v2ray** [comment]
已修复（7fe9683f288834f589188f88afa6942bba5a1247），谢谢测试

**Comment by mickeyandkaka** [comment]
hi  我想再说一下，更新代码后重启似乎还是有内存溢出的现象。
