### ISSUE TITLE
无法正确使用v2ray

### ISSUE THREAD

**Issue by wan-qy** [v2ray/v2ray-core#382]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

v2.16.7

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

随意打开网页

3)  你看到的不正常的现象是什么？
    What did you see?

无法打开网页
![default](https://cloud.githubusercontent.com/assets/10987206/22503211/aa74ab54-e8ab-11e6-8dfb-a31499d7da3f.png)
![default](https://cloud.githubusercontent.com/assets/10987206/22503240/c7e5ddca-e8ab-11e6-98f4-8ef1163be5d0.png)

4)  你期待看到的正确表现是怎样的？
    What's your expectation?

网页正常打开

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Server Configuration File（服务器端配置文件）:

```javascript
{
"log": {
  "access": "/var/log/v2ray/access.log",
  "error": "/var/log/v2ray/error.log",
  "loglevel": "warning"
},

"inbound": {
  "port": 25565,
  "protocol": "vmess",
  "settings": {
    "clients": [
      {
        "id": "32cbb004-993d-4155-9b78-394323e9c4ae", 
        "level": 1,
        "alterId": 32
      }
    ]
  },
  "streamSettings":{
      "network":"kcp",
      "kcpSettings": {
        "mtu": 1350,
        "tti": 20,
        "uplinkCapacity": 5,
        "downlinkCapacity": 100,
        "congestion": true,
        "readBufferSize": 3,
        "writeBufferSize": 3,
        "header": {
          "type": "none"
        }
      }
    }
},

"outbound": {
  "protocol": "freedom",
  "settings": {}
},

"outboundDetour": [
  {
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  }
],

"routing": {
  "strategy": "rules",
  "settings": {
    "rules": [
      {
        "type": "field",
        "ip": [
          "0.0.0.0/8",
          "10.0.0.0/8",
          "100.64.0.0/10",
          "127.0.0.0/8",
          "169.254.0.0/16",
          "172.16.0.0/12",
          "192.0.0.0/24",
          "192.0.2.0/24",
          "192.168.0.0/16",
          "198.18.0.0/15",
          "198.51.100.0/24",
          "::1/128",
          "fc00::/7",
          "fe80::/10"
        ],
        "outboundTag": "blocked"
      }
    ]
  }
},

"transport": {
  "tcpSettings": {
    "connectionReuse": true
  }
}
}
```
    
    Client Configuration File（客户端配置文件）:
```javascript
{
  "log": {
    "loglevel": "warning"
  },
  "inbound": {
    "port": 1080,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "",      //ip
          "port": 25565,
          "users": [
            {
              "id": "32cbb004-993d-4155-9b78-394323e9c4ae",
              "alterId": 32,
              "security": "aes-128-gcm"
            }
          ]
        }
      ]
    },
    "streamSettings":{
      "network":"kcp",
      "kcpSettings": {
        "mtu": 1350,
        "tti": 20,
        "uplinkCapacity": 5,
        "downlinkCapacity": 100,
        "congestion": true,
        "readBufferSize": 3,
        "writeBufferSize": 3,
        "header": {
          "type": "none"
        }
      }
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": "1-52",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "54-79",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "81-442",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "444-65535",
          "outboundTag": "direct"
        },
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        }
      ]
    }
  },
  "transport": {
  }
}
```
    
6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.

    Server Log File（服务器端日志）:
    ```
    // 在这里附上服务器端日志
    // Please attach your server log here.
日志中没有错误
2017/02/01 10:19:34 [Warning]V2Ray started.
    ```
    
    Client Log File（客户端日志）:
    ```
    // 在这里附上客户端日志
    // Please attach your client log here.
没有错误
    ```

通过pstree查看发现服务端v2ray正在运行。
服务器为ubuntu 16.10 x64，vultr 日本机房。
客户端windows 10 14393 x64, 浙江电信，线路丢包率在30%左右，ssh很不稳定。
猜测为配置文件问题。

**Comment by v2ray** [comment]
建议的调试方式：
1. 看一下服务器端  access.log 有没有内容。如果有显示 rejected 说明服务器和客户端时间不同步。
2. 把服务器端  loglevel 设为 info 看一下 kcp 有没有收到任何连接。如果没有收到连接，有可能是防火墙问题。
3. 把 streamSettings.network 设为 tcp 看一下是不是 udp 的问题。

**Comment by lcdtyph** [comment]
server的```uplinkCapacity```对应的是client的```downlinkCapacity```
把server中kcp的这两个值对调试试看。

**Comment by wan-qy** [comment]
@v2ray 原因已经找到。（之前几天比较忙）
以 Windows 10 14393，Firefox 51 为例：
将客户端log等级调为 info 后，

1.在 设置->网络和 Internet->代理中将代理设为127.0.0.1:1080，Firefox “使用系统代理设置”，打开任何网页浏览器状态如之前（“安全连接失败”），客户端显示 [Info]Socks|Server: Failed to read request: Socks|Server: Unknown Socks version: 71；
2.关闭系统设置中的代理，Firefox “手动配置代理”，设置 HTTP 代理为127.0.0.1:1080并勾选“为所有协议使用相同代理”，打开任何网页浏览器状态如之前（“安全连接失败”），客户端显示 [Info]Socks|Server: Failed to read request: Socks|Server: Unknown Socks version: 67；
3.取消勾选“为所有协议使用相同代理”，仅设置HTTP代理为127.0.0.1:1080，打开无需翻墙的网站（以github为例）正常打开，v2ray显示[Info]Socks|Server: Failed to read request: Socks|Server: Unknown Socks version: 67 以及 Info]Socks|Server: Failed to read request: Socks|Server: Unknown Socks version: 80；打开需要翻墙的网站（以twitter为例）浏览器显示“连接超时”，v2ray显示[Info]Socks|Server: Failed to read request: Socks|Server: Unknown Socks version: 67；
4.清除HTTP代理，将“socks主机”配置为127.0.0.1:1080，socks v5，一切正常。

解决：不直接在系统设置中设置代理，配置浏览器的socks代理。

**Comment by madobet** [comment]
> @v2ray 原因已经找到。（之前几天比较忙）
> 以 Windows 10 14393，Firefox 51 为例：
> 将客户端log等级调为 info 后，
> 
>     1. 在 设置->网络和 Internet->代理中将代理设为127.0.0.1:1080，Firefox “使用系统代理设置”，打开任何网页浏览器状态如之前（“安全连接失败”），客户端显示 [Info]Socks|Server: Failed to read request: Socks|Server: Unknown Socks version: 71；
> 
>     2. 关闭系统设置中的代理，Firefox “手动配置代理”，设置 HTTP 代理为127.0.0.1:1080并勾选“为所有协议使用相同代理”，打开任何网页浏览器状态如之前（“安全连接失败”），客户端显示 [Info]Socks|Server: Failed to read request: Socks|Server: Unknown Socks version: 67；
> 
>     3. 取消勾选“为所有协议使用相同代理”，仅设置HTTP代理为127.0.0.1:1080，打开无需翻墙的网站（以github为例）正常打开，v2ray显示[Info]Socks|Server: Failed to read request: Socks|Server: Unknown Socks version: 67 以及 Info]Socks|Server: Failed to read request: Socks|Server: Unknown Socks version: 80；打开需要翻墙的网站（以twitter为例）浏览器显示“连接超时”，v2ray显示[Info]Socks|Server: Failed to read request: Socks|Server: Unknown Socks version: 67；
> 
>     4. 清除HTTP代理，将“socks主机”配置为127.0.0.1:1080，socks v5，一切正常。
> 
> 
> 解决：不直接在系统设置中设置代理，配置浏览器的socks代理。

现在 Firefox 安装 SwichyOmega 也可以解决这个问题，并且可以和环境变量 http_proxy https_proxy 共存

**Comment by maoyj** [comment]
V2rayN的情况下，右键开启http代理时，http代理的端口是socks+1。比如V2ray的配置文件socks代理是1080，那么默认http代理就是1081。有些软件只能用http代理不能用socks代理，这时就要用到1081这个。否则指向1080端口的话，v2ray就会不停的报错“v2ray.com/core/proxy/socks: unknown Socks version xx”

**Comment by RaySun0501** [comment]
> V2rayN的情况下，右键开启http代理时，http代理的端口是socks+1。比如V2ray的配置文件socks代理是1080，那么默认http代理就是1081。有些软件只能用http代理不能用socks代理，这时就要用到1081这个。否则指向1080端口的话，v2ray就会不停的报错“v2ray.com/core/proxy/socks: unknown Socks version xx”

老哥，这可太稳了！！成功了
还有1事请教，那既然这样的话，为什么在config.json中看不到http的端口设置呢？

**Comment by cllh1999** [comment]
> V2rayN的情况下，右键开启http代理时，http代理的端口是socks+1。比如V2ray的配置文件socks代理是1080，那么默认http代理就是1081。有些软件只能用http代理不能用socks代理，这时就要用到1081这个。否则指向1080端口的话，v2ray就会不停的报错“v2ray.com/core/proxy/socks: unknown Socks version xx”

感谢啊，模拟器配置代理弄了半天，看了你的马上成了

**Comment by ChenJBBB** [comment]
> > V2rayN的情况下，右键开启http代理时，http代理的端口是socks+1。比如V2ray的配置文件socks代理是1080，那么默认http代理就是1081。有些软件只能用http代理不能用socks代理，这时就要用到1081这个。否则指向1080端口的话，v2ray就会不停的报错“v2ray.com/core/proxy/socks: unknown Socks version xx”
> 
> 老哥，这可太稳了！！成功了
> 还有1事请教，那既然这样的话，为什么在config.json中看不到http的端口设置呢？

太稳了 直接+1 啥都通了

**Comment by qlaall** [comment]
> V2rayN的情况下，右键开启http代理时，http代理的端口是socks+1。比如V2ray的配置文件socks代理是1080，那么默认http代理就是1081。有些软件只能用http代理不能用socks代理，这时就要用到1081这个。否则指向1080端口的话，v2ray就会不停的报错“v2ray.com/core/proxy/socks: unknown Socks version xx”
wc  真的是这个原因  我switch连接直接+1

**Comment by man0315** [comment]
> V2rayN的情况下，右键开启http代理时，http代理的端口是socks+1。比如V2ray的配置文件socks代理是1080，那么默认http代理就是1081。有些软件只能用http代理不能用socks代理，这时就要用到1081这个。否则指向1080端口的话，v2ray就会不停的报错“v2ray.com/core/proxy/socks: unknown Socks version xx”

switch终于+1了   can't thank you enough!!!

**Comment by stedylan** [comment]
谢谢大佬，倒腾了一晚上，终于成功了

**Comment by liyue201** [comment]
> > V2rayN的情况下，右键开启http代理时，http代理的端口是socks+1。比如V2ray的配置文件socks代理是1080，那么默认http代理就是1081。有些软件只能用http代理不能用socks代理，这时就要用到1081这个。否则指向1080端口的话，v2ray就会不停的报错“v2ray.com/core/proxy/socks: unknown Socks version xx”
> > wc  真的是这个原因  我switch连接直接+1

我丢~~成功了

**Comment by zhouxiaofu** [comment]
神奇的 +1, 666
