### ISSUE TITLE
v2ray 连接不上

### ISSUE THREAD

**Issue by dcliubing** [v2ray/v2ray-core#383]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
2.15.1，服务器端2.16.6
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
用 火狐通过 socks/VMESS 代理翻墙
3)  你看到的不正常的现象是什么？
    What did you see?
无法打开墙外网页
4)  你期待看到的正确表现是怎样的？
    What's your expectation?
正常打开墙外网站
5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Server Configuration File（服务器端配置文件）:
    ```javascript
    // 在这里附上服务器端配置文件
    // Please attach your server configuration file here.
    ```
    {
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "info"
  },
  "inbound": {
    "port": 27836,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "fd51b221-c25d-47d7-a2fc-93c550b7ee6e",
          "level": 1,
          "alterId": 64
        }
      ]
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  },
  "transport": {
    "kcpSettings": {
      "uplinkCapacity": 2,
      "downlinkCapacity": 10
    }
  }
}

    Client Configuration File（客户端配置文件）:
    ```javascript
    // 在这里附上客户端配置文件
    // Please attach your client configuration file here.
   {
  "log": {
    "loglevel": "info"

  },
  "inbound": {
    "port": 2080,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "xxxxxxxxxxxx",
          "port": 27836,
          "users": [
            {
              "id": "fd51b221-c25d-47d7-a2fc-93c550b7ee6e",
              "alterId": 64
            }
          ]
        }
      ]
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": "1-52",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "54-79",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "81-442",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "444-65535",
          "outboundTag": "direct"
        },
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        }
      ]
    }
  },
  "transport": {
    "kcpSettings": {
      "uplinkCapacity": 1,
      "downlinkCapacity": 10
    }
  }
}

    
6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.

    Server Log File（服务器端日志）:
    ```
    // 在这里附上服务器端日志
    // Please attach your server log here.
    ```
    2017/01/28 09:34:34 [Warning]V2Ray started.
2017/01/28 09:38:00 [Warning]V2Ray started.
2017/02/02 20:38:13 [Error]Error starting Point server: [Interent|TCPHub: Failed to listen on address:  0.0.0.0 : 27836] > listen tcp 0.0.0.0:27836: bind: address already in use
    Client Log File（客户端日志）:
    ```
    // 在这里附上客户端日志
    // Please attach your client log here.
    ```

**Comment by wtlusvm** [comment]
```
2017/02/02 20:38:13 [Error]Error starting Point server: [Interent|TCPHub: Failed to listen on address: 0.0.0.0 : 27836] > listen tcp 0.0.0.0:27836: bind: address already in use
```

服务端27836端口被别的程序用了

**Comment by dcliubing** [comment]
重新装了VPS系统换了端口还是不行
2017/02/02 22:12:22 [Warning]V2Ray started.
2017/02/02 22:15:52 [Error]Error starting Point server: Interent|TCPHub: Failed to listen on address: 0.0.0.0:27073 > listen tcp 0.0.0.0:27073: bind: address already in use

**Comment by dcliubing** [comment]
服务端和客户端都改成2.16.7了
