### ISSUE TITLE
如何设置Outbound的LocalAddr？

### ISSUE THREAD

**Issue by htfy96** [v2ray/v2ray-core#384]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
2.17.1

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
在多人合租的一台多IP机器上跑一个/多个v2ray实例，使得每个用户走不同的ip地址的freedom outbound。

3)  你看到的不正常的现象是什么？
目前似乎无法配置。

4)  你期待看到的正确表现是怎样的？
能够像SS一样配置Outbound的`LocalAddr`

**Comment by v2ray** [comment]
[outbound 配置](https://www.v2ray.com/chapter_02/01_overview.html#主传出连接配置（outbound）)中有 sendThrough 选项。
