### ISSUE TITLE
如何设置让VPS代理DNS查询请求？

### ISSUE THREAD

**Issue by Lantrancy** [v2ray/v2ray-core#387]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
2.17
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
Chrome（win7） - v2ray(kcp动态端口) - GFW - VPS - internet

我想把客户机（win7）的DNS设置为v2ray，把dns请求转发到vps，让vps从墙外查询然后再把无毒dns返回给客户机，请问如何设置？

我的客户端配置：
{
	"log": {
		"loglevel": "info"
	},
	"inbound": {
		"port": xxxx,
		"listen": "127.0.0.1",
		"protocol": "socks",
		"settings": {
			"auth": "noauth",
			"udp": false,
			"ip": "127.0.0.1"
		}
	},
	"outbound": {
		"protocol": "vmess",
		"settings": {
			"vnext": [{
					"address": "xxxx",
					"port": xxxx,
					"users": [{
							"id": "xxxx",
							"alterId": 64,
							"level": 1,
							"security": "auto"
						}
					]
				}
			]
		},
		"streamSettings": {
			"network": "kcp"
		}
	},
	"outboundDetour": [{
			"protocol": "freedom",
			"settings": {},
			"tag": "direct"
		}
	],
	"dns": {
		"servers": [
			"8.8.8.8",
			"8.8.4.4",
			"localhost"
		]
	},
	"routing": {
		"strategy": "rules",
		"settings": {
			"domainStrategy": "IPIfNonMatch",
			"rules": [{
					"type": "field",
					"port": "1-52",
					"outboundTag": "direct"
				}, {
					"type": "field",
					"port": "54-79",
					"outboundTag": "direct"
				}, {
					"type": "field",
					"port": "81-442",
					"outboundTag": "direct"
				}, {
					"type": "field",
					"port": "444-65535",
					"outboundTag": "direct"
				}, {
					"type": "chinasites",
					"outboundTag": "direct"
				}, {
					"type": "field",
					"ip": [
						"0.0.0.0/8",
						"10.0.0.0/8",
						"100.64.0.0/10",
						"127.0.0.0/8",
						"169.254.0.0/16",
						"172.16.0.0/12",
						"192.0.0.0/24",
						"192.0.2.0/24",
						"192.168.0.0/16",
						"198.18.0.0/15",
						"198.51.100.0/24",
						"203.0.113.0/24",
						"::1/128",
						"fc00::/7",
						"fe80::/10"
					],
					"outboundTag": "direct"
				}, {
					"type": "chinaip",
					"outboundTag": "direct"
				}
			]
		}
	},
	"transport": {
		"kcpSettings": {
			"uplinkCapacity": 5,
			"downlinkCapacity": 20
		}
	}
}

**Comment by wtlusvm** [comment]
```
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
```

有这个字段就表明设置好了

**Comment by v2ray** [comment]
设置一个 dokodemo-door，把某个端口（比如53）的请求转发到比如 8.8.8.8:53 即可。
