### ISSUE TITLE
[需要建议]多节点互联*拓扑见图*

### ISSUE THREAD

**Issue by BenhoNNNN** [v2ray/v2ray-core#392]
![sample](https://cloud.githubusercontent.com/assets/12547424/22889455/33813ab0-f244-11e6-9c26-0613efd1abaf.png)

四台服务器，ABC都有公网IP，D出口有N个公网IP。

A(Windows)：部署CCProxy，提供基于 账户/密码 验证的 http 代理接入服务
（账户有效期、线程数、登录数、流量配额等）。不暴露B面向客户端；
B(Linux)：一侧承转A的流量，一侧穿墙；
C(Linux)：一侧穿墙，一侧承转D的流量；
D(Linux)：访问互联网。（不暴露B与C的穿墙关系）

问题：
1. 为了转发效率、性能开销等考虑，A与B（C与D）内网互联，采用何种形式 http/Socks更优？（或者其他更好的解决方案？）
2. 主要用于Web浏览（视频、音乐等），B与C穿墙互联采用VMess协议，配置方面有没有要注意的事项和建议？（比如加密方式的选择等）
3. D出口上的N个IP有没有可能全部利用起来？（比如随机IP出口或者指定IP能够绑定到A上指定的接入端口）
4. 大量用户在线时，ABCD四台服务器各最依赖的处理能力的建议？（比如侧重CPU计算、IO吞吐、内存容量等？）

**Comment by BenhoNNNN** [comment]
@v2ray :+1:

**Comment by v2ray** [comment]
1. A/B 之间取决于 A 能转发出什么协议。看上去 A 上没有运行 V2Ray，并且只需要转发 HTTP 流量，那么就继续用 HTTP 好了。C/D 之间可以使用 VMess/None。
2. 没。传输方式取决于你的 ISP 的限制，比如用不用 HTTP 混淆，用不用 WebSocket。加密方式取决于带宽，100MB/s 以下的带宽没有差别。
3. 默认情况是随机 IP 出口。如果需要指定 IP，需要建立多个 outbound，每个 outbound 指定不同的 sendThrough，然后用路由功能按需分配。
4. VMess 的缺点是会占用大量内存，内存的计算在官网上有提到。网络 IO 基本上是等价的，就是从 A 进来多少就从 D 出去多少（假设没有分流）。CPU 可以忽略不记。

**Comment by BenhoNNNN** [comment]
@v2ray 谢谢解答，明白了。
