### ISSUE TITLE
V2Ray插件系统? 运行时动态加载dll/so插件喵?

### ISSUE THREAD

**Issue by mindcat** [v2ray/v2ray-core#393]
具体可以是支持更多协议的插件喵

例如ICMP穿墙插件喵

例如DNS穿墙插件喵

**Comment by Robert-Tian** [comment]
这里还是正常人多一些，请尽量说得让别人能看懂。

**Comment by v2ray** [comment]
Golang 在 1.8 中支持了[插件模式](https://tip.golang.org/pkg/plugin/)，目前仅在 Linux 上可用。估计要等到 1.9 或之后的版本才可以全面使用。这此之前，技术上做不到动态加载第三方插件。

**Comment by mindcat** [comment]
@v2ray 这只能说明go与go之间的FFI模式喵...

https://golang.org/cmd/cgo/

https://github.com/sbinet/go-ffi

目前只能找到这些FFI的说喵
go的FFI状况看起来很糟糕喵...

**Comment by mindcat** [comment]
没动力继续提Issue了喵
