### ISSUE TITLE
sock5 inbound does not allow access from any IP for "listen" : "0.0.0.0"

### ISSUE THREAD

**Issue by astrataro** [v2ray/v2ray-core#395]
1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
v1.18 on MacOS.

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
Use v2ray as socks5 server.

3) What did you see?
If I set to `"listen" : "0.0.0.0"` in inbound setting, local machine and other device in LAN cannot access v2ray. V2ray access/error log does not log for anything. Changing it to `"listen" : "127.0.0.1"` allows access from localhost.

4) What's your expectation?
I suppose` "listen" : "127.0.0.1"` should allow access from localhost only, while `"listen" : "0.0.0.0"` refers to any IP.

5) Please attach your configuration file.
    
    Client Configuration File:
    ```javascript
    {
      "dns" : {
        "servers" : [
          ANYDNSSERVER
        ]
      },
      "inbound" : {
        "listen" : "0.0.0.0",
        "port" : ANYPORT,
        "protocol" : "socks",
        "settings" : {
          "auth" : "noauth"
        }
      },
      "log" : {
        "access": "",
        "error": "",
        "loglevel" : "none"
      },
      "outbound" : {
       ++++++++ ANYTHING ++++++++
      },
      "outboundDetour": [
        {
          "protocol": "freedom",
          "settings": {},
          "tag": "direct"
        }
      ],
      "routing": {
        "strategy": "rules",
        "settings": {
          "rules": [
            {
              "type": "field",
              "ip": [
                "0.0.0.0/8",
                "10.0.0.0/8",
                "100.64.0.0/10",
                "127.0.0.0/8",
                "169.254.0.0/16",
                "172.16.0.0/12",
                "192.0.0.0/24",
                "192.0.2.0/24",
                "192.168.0.0/16",
                "198.18.0.0/15",
                "198.51.100.0/24",
                "203.0.113.0/24",
                "::1/128",
                "fc00::/7",
                "fe80::/10"
              ],
              "outboundTag": "direct"
            },
            {
              "type": "chinaip",
              "outboundTag": "direct"
            },
            {
              "type": "chinasites",
              "outboundTag": "direct"
            }
          ]
        }
      }
    }
    ```
    
6) Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.
Nothing looged if set to `"listen" : "0.0.0.0"`.

**Comment by v2ray** [comment]
1. Your loglevel is set to 'none'. That's why there is no log. If you set it to 'info', you should see something like "listening on 0.0.0.0:port".
2. MacOS has some security settings for listening on 0.0.0.0. Usually there will be a dialog popup for security warnings. Please allow it.

**Comment by astrataro** [comment]
My mistake. I use "none" and set empty log file path for daily use. But when testing I've set it to "debug" with proper path, and yes I can find "listening on 0.0.0.0:port". That is all I can get. I used browser or system proxy to attempt to access 127.0.0.1:port, but there's no access or error logged in log file.

**Comment by v2ray** [comment]
Can you check if your macOS allows v2ray to accept incoming connection? http://www.macworld.co.uk/how-to/mac-software/how-open-specific-ports-in-os-x-1010-firewall-3616405/

**Comment by astrataro** [comment]
Ah I've found the cause. Both v2ray and FireWall(allowing v2ray's incoming connection) worked as intended, but another program was occupying the socks5 port.
