### ISSUE TITLE
mkcp的连接建立、异常关闭检测接口是什么？

### ISSUE THREAD

**Issue by metalwood** [v2ray/v2ray-core#399]
我看mkcp介绍文档说增加了“连接”状态控制（虽然UDP没有连接，但是连接方便管理），意思就是知道连接是否建立、关闭、异常关闭的检测，但是代码里没找到相关接口，当Dial一个不存在的IP和端口时，一样可以Dial成功并且写入，直到buffer填满才会报错。请问:

1、我应该怎样知道连接是否建立了呢？
2、“当远程主机断线时，连接会在最多 30 秒内释放”，这个30秒能否作为参数进行调整？

谢谢！

**Comment by v2ray** [comment]
1. 不能知道。mkcp 的设计是没有握手的状态，于是连接的发起方只能等待另一端发回数据才知道有没有收到。于是就有了30秒的超时设置。
2. 暂时不能更改 30 秒的超时设置。

**Comment by metalwood** [comment]
谢谢，希望增加。
