### ISSUE TITLE
[Feature request] VMess: ICMP/DNS 伪装

### ISSUE THREAD

**Issue by oing9179** [v2ray/v2ray-core#400]
DNS 和 ICMP 都是基于UDP的通信协议，也就意味着有可能为 VMess 协议提供伪装。

DNS 伪装缺点：

1. 因为 DNS 协议的原因导致 payload 太小。
2. 可能需要再花钱买个域名

ICMP Ping 伪装缺点：

1. 虽然 ICMP Ping 包可以是任意大小的，但有些防火墙会限制过大的ping包，因此 应该在配置文件中允许配置 `最大 payload 大小`。

__References:__

1. [ICMP Tunnel - wikipedia.org][1]

[1]: https://en.wikipedia.org/wiki/ICMP_tunnel

**Comment by v2ray** [comment]
[ICMP](https://zh.wikipedia.org/wiki/%E4%BA%92%E8%81%94%E7%BD%91%E6%8E%A7%E5%88%B6%E6%B6%88%E6%81%AF%E5%8D%8F%E8%AE%AE) 是独立的协议，既不是 TCP 也不是 UDP。ICMP 的确可以用来传输了一些自定义数据。但是 V2Ray 目前的设计仅限于 TCP 和 UDP，其它类型的 IP 协议暂不考虑。

DNS 协议的格式是定死的，无法加入自定义数据。也就是说，加入自定义数据之后，对 DNS 数据包的解析会失败，于是就成了很强的特征。

于是这两种协议暂时不列入考虑的范围。

**Comment by lins05** [comment]
> 加入自定义数据之后，对 DNS 数据包的解析会失败，于是就成了很强的特征。

可以看看这个实现, 封装后的包确实是合法的 DNS 响应 https://github.com/yarrick/iodine

**Comment by v2ray** [comment]
他的实现利用了DNS查询中的一些自定义字段，比如TXT，来传输数据。传输量有限，见最下面的测试数据，不具有常规使用的价值。
