### ISSUE TITLE
Shadowsocks AEAD Ciphers

### ISSUE THREAD

**Issue by htfy96** [v2ray/v2ray-core#401]
最近Shadowsocks提供了[AEAD Ciphers](https://shadowsocks.org/en/spec/AEAD-Ciphers.html)，并将原来的aes-256-cfb等协议列为deprecated。想了解V2ray是否会支持shadowsocks这些协议？

**Comment by v2ray** [comment]
见 https://github.com/v2ray/Planning/issues/11 。等 ss-libev 先出稳定版再说。
