### ISSUE TITLE
dokodemo-door 作 VPN 反向代理可行吗？

### ISSUE THREAD

**Issue by BenhoNNNN** [v2ray/v2ray-core#402]
A B C 三台服务器

A为墙内作V2Ray客户端，使用协议dokodemo-door监听UDP 500/4500/1701；
B为墙外作V2Ray服务器；
C为墙外VPN服务器，已知业务端口UDP 500/4500/1701。

不知道可行不可行？

**Comment by v2ray** [comment]
可以的

**Comment by BenhoNNNN** [comment]
@v2ray 谢谢。
