### ISSUE TITLE
可否添加启动参数隐藏控制台窗口？

### ISSUE THREAD

**Issue by bitching** [v2ray/v2ray-core#403]
使用Greenchrome可以让v2ray随chrome启动，关闭时可结束v2ray进程，很是方便。
( https://www.shuax.com/archives/ChromeUpdater.html )

然而直接打开会有黑窗口，很不好看。
若打开chrome时通过启动v2ray-taskbar之类打开v2ray，关闭chrome的时候无法结束v2ray主进程，且因关闭方式是结束进程，通知区域会有残留。
所以，可否添加启动参数隐藏控制台窗口，不加参数启动还是输出log给需要的人？

若无法做到加启动参数隐藏控制台窗口，可否加一个启动参数（假设为-exit）：
若v2ray在运行中，新进程以-exit参数启动，通知原进程后退出。原进程收到此信号后亦终止。
这样也可以解决问题。

**Comment by bitching** [comment]
若无法做到加启动参数隐藏控制台窗口，可否加一个启动参数（假设为-exit）：
若v2ray在运行中，新进程以-exit参数启动，通知原进程后退出。原进程收到此信号后亦终止。
这样也可以解决问题。

**Comment by BenhoNNNN** [comment]
控制面板〉系统和安全〉计划任务〉创建基本任务〉名称v2ray〉计算机启动时〉启动程序〉添加程序x:\v2ray\v2ray.exe

勾选〉当完成时，打开“属性”对话框〉不管用户是否登录都要运行〉确定，输入管理员帐号。

另外结束进程需要在“计划任务”里右键任务名称“结束”。

**Comment by v2ray** [comment]
会在下一版本中发行一个新的程序，wv2ray.exe，在启动时不会出现命令行窗口。
