### ISSUE TITLE
升级2.20后不能游戏啦，我只能2.17.1游戏

### ISSUE THREAD

**Issue by vrcms** [v2ray/v2ray-core#404]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

我本来使用2.17.1的，后来看到官网升级到2.2，就升级了，没想到会有问题

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

我通过v2ray 玩游戏，玩h1z1，这种类型游戏需要udp转发才有加速效果的。

3)  你看到的不正常的现象是什么？
    What did you see?

4)  你期待看到的正确表现是怎样的？
    What's your expectation?
但是我升级到2.20发现，无法进入游戏，我不清楚哪个环节出问题
但我可以确定是2.20有问题
排除法：服务端 2.20 ，客户端是2.17.1 或者2.20都无法游戏
              服务端2.17.1  也只能2.17.1的客户端能进入游戏

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
   
    ```
    
6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.

    Server Log File（服务器端日志）:
    ```
    // 在这里附上服务器端日志
2017/02/25 20:22:26 [Warning]VMess|Inbound: Failed to get detour handler: detourProxymand|DefaultInboundHandlerManager: Handler not found: detour
2017/02/25 20:22:27 [Warning]VMess|Inbound: Failed to get detour handler: detourProxymand|DefaultInboundHandlerManager: Handler not found: detour
2017/02/25 20:22:33 [Warning]VMess|Inbound: Failed to get detour handler: detourProxymand|DefaultInboundHandlerManager: Handler not found: detour
2017/02/25 20:22:37 [Warning]VMess|Inbound: Failed to get detour handler: detourProxymand|DefaultInboundHandlerManager: Handler not found: detour

都是这个错误
    

补充：可以看网页，看视频，，就是不能游戏，，，

**Comment by Voleking** [comment]
同样的Warning

**Comment by oing9179** [comment]
@vrcms 
麻烦按照把客户端配置文件贴出来。

**Comment by DarienRaymond** [comment]
2.26  修复了UDP传输的问题，应该正常了

**Comment by ArcherLew** [comment]
@vrcms 你好，请问你是如何使用v2ray代理h1z1的呢？
我试图用sockscap+v2ray代理wow，发现登陆阶段代理是有用的(v2ray log 在刷wow相关信息），进入游戏以后就不走代理了（完全没有v2ray log了）

**Comment by vrcms** [comment]
@ArcherLew 不用v2ray了， 用sstap，就可以了。
