### ISSUE TITLE
建议客户端和服务器启动后开始一次握手，服务器在access。log打印链接成功信息，

### ISSUE THREAD

**Issue by mikechen163** [v2ray/v2ray-core#405]
2.20版本。 配置OK后，服务器没有任何提示

客户端似乎也没有发出任何握手信息，还以为失败了，调试了很久。一直到直接用浏览器访问网站才知道成功了。

建议客户端启动后，和服务器发握手信号。服务器收到后打印成功信息。参考kcptun的做法。

**Comment by v2ray** [comment]
握手是具体协议的行为，V2Ray 实际上不在乎每个协议具体是怎么运作的。目前所支持的协议中，没有一个是主动握手的。主动握手的特征较强，设计不好的话很容易被识别。如果你有需求的话，可以自己写一个测试的脚本，每次配置完运行一下测试便可以知道有没有连通。

**Comment by mikechen163** [comment]
OK。那么能否在官方文档中说明一下，需要通过访问网站或者其他方式来确认配置是否成功，系统缺省不会有任何握手检测信息。
