### ISSUE TITLE
在路由器上启用dokodemo-door协议，配合iptables自动转发流量，发现出现太多的 too many files opened 错误

### ISSUE THREAD

**Issue by mikechen163** [v2ray/v2ray-core#406]
问题通过修改配置文件已经解决，请审核。
------------------------
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

  2.20

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
   
  在路由器上，配置 协议为 dokodemo-door, 链接 twiter 等站点困难。 error log出现 too many open files 错误。   

3)  你看到的不正常的现象是什么？
    What did you see?

  error log出现 too many open files 错误。   
  大量访问 5228端口的tcp链接不能建立成功，导致tcp链接资源耗尽。

  用 netstat -an| grep 1080 ，可以看到大量1080 tcp 连接请求被占用

4)  你期待看到的正确表现是怎样的？
    What's your expectation?
 
   网站可正常访问。
   
5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).

    "inbound": {
    "port": 1080,
    "listen": "0.0.0.0",
    "protocol": "dokodemo-door",
    "settings": {
      "address": "",
      "network": "tcp",
      "timeout": 0,
      "followRedirect": true
    }
  },

。。。。。

{
          "type": "field",
          "port": "444-65535",
          "outboundTag": "direct"
        },

分析error.log 可以看到出现大量的请求访问 google 服务器的5228端口的请求，被直接路由，导致chrome浏览器不断再次发送请求。

修改为下面的配置后，允许访问5228端口流量转发，问题解决！！！！

{
          "type": "field",
          "port": "444-5227",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "5229-65535",
          "outboundTag": "direct"
        },

    
6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.

非常多重复的下面的打印
[Debug]Dokodemo: processing connection from: 192.168.1.3:35663
2017/02/26 13:51:07 [Info]DefaultDispatcher: Taking detour [direct] for [tcp:173.194.203.188:5228].
2017/02/26 13:51:07 [Info]Freedom: Opening connection to tcp:173.194.203.188:5228
2017/02/26 13:51:07 [Info]Internet|TCP: Dailing TCP to tcp:173.194.203.188:5228
    ```
    
    Client Log File（客户端日志）:
    ```
    // 在这里附上客户端日志
    // Please attach your client log here.
    ```

**Comment by v2ray** [comment]
如果你使用的是自己的 VPS，可以默认转发所有的端口。官方服务器这样的配置只是为了不消耗太多的流量。

**Comment by mikechen163** [comment]
ok
