### ISSUE TITLE
华硕AC66U B1运行v2ray崩溃

### ISSUE THREAD

**Issue by zhaibin18** [v2ray/v2ray-core#414]
1)  你正在使用哪个版本的 V2Ray？
V2Ray v2.20.1 (One for all) 20170227
2)  你的使用场景是什么？
使用华硕AC66U B1路由器，运行v2ray，路由器内存256M，运行v2ray之前内存空余192M，路由器信息如下：
admin@RT-AC66U_B1-6CD0:/tmp/home/root# cat /proc/cpuinfo
Processor       : ARMv7 Processor rev 0 (v7l)
processor       : 0
BogoMIPS        : 1998.84

processor       : 1
BogoMIPS        : 1998.84

Features        : swp half thumb fastmult edsp
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc09
CPU revision    : 0

Hardware        : Northstar Prototype
Revision        : 0000
Serial          : 0000000000000000
admin@RT-AC66U_B1-6CD0:/tmp/home/root# uname -a
Linux RT-AC66U_B1-6CD0 2.6.36.4brcmarm #2 SMP PREEMPT Fri Feb 3 00:27:49 EST 2017 armv7l ASUSWRT-Merlin
admin@RT-AC66U_B1-6CD0:/tmp/home/root#
运行v2ray后top内存占用：

> Mem: 64892K used, 190808K free, 576K shrd, 668K buff, 5392K cached
CPU:  0.0% usr  4.5% sys  0.0% nic 95.4% idle  0.0% io  0.0% irq  0.0% sirq
Load average: 0.00 0.01 0.05 1/70 2435
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
 2435  1902 admin    R     1404  0.5   0  4.5 top
 2171     1 admin    S     777m311.1   0  0.0 /jffs/bin/v2ray -config /jffs/etc/v.conf
  442     1 admin    S     6548  2.5   0  0.0 httpd -i br0

3)  你看到的不正常的现象是什么？
v2ray进程崩溃
4)  你期待看到的正确表现是怎样的？
v2ray能正常运行
5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。

{
  "log" : {
    "access": "/dev/null",
    "error": "/dev/null",
    "loglevel": "error"
  },
  "inbound": {
    "port": 1080,
    "protocol": "http",
    "settings": {
      "auth": "noauth"
    }
  },
  "outbound":{
    "protocol": "shadowsocks",
    "settings": {
      "servers": [
        {
          "address": "a.b.c.d",
          "method": "chacha20",
          "ota": false,
          "password": "passwd",
          "port": 443
        }
      ]
    }
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    },
    {
      "protocol": "freedom",
      "tag": "direct",
      "settings": {}
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "chinaip",
          "outboundTag": "direct"
        },
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "domain": [
            "qq.com",
            "baidu.com"
          ],
          "outboundTag": "direct"
        }
      ]
    }
  }
}
    
6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
admin@RT-AC66U_B1-6CD0:/tmp/home/root# /jffs/bin/v2ray -config /jffs/etc/v.conf
V2Ray v2.20.1 (One for all) 20170227
An unified platform for anti-censorship.
2017/03/12 05:10:39 [Debug]Proxyman|DefaultInboundHandler: creating tcp worker on 0.0.0.0:1080
2017/03/12 05:10:39 [Info]TCP|Listener: Listening on 0.0.0.0:1080
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x3c7b6b, 0x16)
        /usr/local/go/src/runtime/panic.go:596 +0x70
runtime.sysMap(0x13e00000, 0x100000, 0x2af1bd01, 0x5b2870)
        /usr/local/go/src/runtime/mem_linux.go:227 +0xb0
runtime.(*mheap).sysAlloc(0x5a5060, 0x100000, 0xeb00005d)
        /usr/local/go/src/runtime/malloc.go:428 +0x2bc
runtime.(*mheap).grow(0x5a5060, 0x8, 0x0)
        /usr/local/go/src/runtime/mheap.go:774 +0x48
runtime.(*mheap).allocSpanLocked(0x5a5060, 0x1, 0x10d75f40)
        /usr/local/go/src/runtime/mheap.go:678 +0x468
runtime.(*mheap).alloc_m(0x5a5060, 0x1, 0x2b, 0x0, 0x2b)
        /usr/local/go/src/runtime/mheap.go:562 +0xdc
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:627 +0x3c
runtime.systemstack(0x10d75f38)
        /usr/local/go/src/runtime/asm_arm.s:278 +0xa8
runtime.(*mheap).alloc(0x5a5060, 0x1, 0x2b, 0x100, 0x1)
        /usr/local/go/src/runtime/mheap.go:628 +0x60
runtime.(*mcentral).grow(0x5a6488, 0x0)
        /usr/local/go/src/runtime/mcentral.go:212 +0x84
runtime.(*mcentral).cacheSpan(0x5a6488, 0x66094)
        /usr/local/go/src/runtime/mcentral.go:93 +0x104
runtime.(*mcache).refill(0x400ea258, 0x2b, 0x124d2000)
        /usr/local/go/src/runtime/mcache.go:122 +0x7c
runtime.(*mcache).nextFree.func1()
        /usr/local/go/src/runtime/malloc.go:526 +0x24
runtime.systemstack(0x10818000)
        /usr/local/go/src/runtime/asm_arm.s:264 +0x80
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1132

goroutine 9749 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_arm.s:209 +0x4 fp=0x12be9e90 sp=0x12be9e8c
runtime.(*mcache).nextFree(0x400ea258, 0x40340c2b, 0x1dfb8, 0x1e88c, 0x13dbc7b0)
        /usr/local/go/src/runtime/malloc.go:527 +0x9c fp=0x12be9ebc sp=0x12be9e90
runtime.mallocgc(0x1000, 0x35bc68, 0x561101, 0x2267e4)
        /usr/local/go/src/runtime/malloc.go:679 +0x8c0 fp=0x12be9f18 sp=0x12be9ebc
runtime.makeslice(0x35bc68, 0x1000, 0x1000, 0x40340ce0, 0x13dcd6a0, 0x1000)
        /usr/local/go/src/runtime/slice.go:54 +0x68 fp=0x12be9f3c sp=0x12be9f18
v2ray.com/core/proxy/http.(*Server).handlePlainHTTP.func2(0x13725100, 0x13725100)
        src/v2ray.com/core/proxy/http/server.go:236 +0x3e0 fp=0x12be9fcc sp=0x12be9f3c
v2ray.com/core/common/signal.executeAndFulfill(0x13dcd6c0, 0x13de0ec0)
        src/v2ray.com/core/common/signal/exec.go:8 +0x1c fp=0x12be9fe4 sp=0x12be9fcc
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:1017 +0x4 fp=0x12be9fe4 sp=0x12be9fe4
created by v2ray.com/core/common/signal.ExecuteAsync
        src/v2ray.com/core/common/signal/exec.go:18 +0x54

goroutine 1 [chan receive, 3 minutes]:
main.main()
        src/v2ray.com/core/main/main.go:102 +0x1b0

goroutine 18 [syscall, 3 minutes]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x154
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x14
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x30

goroutine 19 [IO wait]:
net.runtime_pollWait(0x40485e10, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:164 +0x44
net.(*pollDesc).wait(0x110077fc, 0x72, 0x0, 0x13d9d350)
        /usr/local/go/src/net/fd_poll_runtime.go:75 +0x28
net.(*pollDesc).waitRead(0x110077fc, 0xffffffff, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:80 +0x24
net.(*netFD).accept(0x110077c0, 0x0, 0x561038, 0x13d9d350)
        /usr/local/go/src/net/fd_unix.go:430 +0x15c
net.(*TCPListener).accept(0x10edb4f0, 0x6b924, 0x278030, 0x1100e150)
        /usr/local/go/src/net/tcpsock_posix.go:136 +0x20
net.(*TCPListener).Accept(0x10edb4f0, 0x13dd34c0, 0x0, 0x1, 0x0)
        /usr/local/go/src/net/tcpsock.go:228 +0x3c
v2ray.com/core/transport/internet/tcp.(*TCPListener).KeepAccepting(0x1100e150)
        src/v2ray.com/core/transport/internet/tcp/hub.go:74 +0x30
created by v2ray.com/core/transport/internet/tcp.ListenTCP
        src/v2ray.com/core/transport/internet/tcp/hub.go:68 +0x2fc

goroutine 20 [select]:
v2ray.com/core/app/proxyman/inbound.(*tcpWorker).handleConnections(0x10817ac0, 0x11007780)
        src/v2ray.com/core/app/proxyman/inbound/worker.go:89 +0xf8
created by v2ray.com/core/app/proxyman/inbound.(*tcpWorker).Start
        src/v2ray.com/core/app/proxyman/inbound/worker.go:82 +0x138

goroutine 21 [runnable]:
v2ray.com/core/app/log/internal.(*FileLogWriter).run(0x10dfdce0, 0x564558, 0x10dfdcc0)
        src/v2ray.com/core/app/log/internal/log_writer.go:61 +0x16c
created by v2ray.com/core/app/log/internal.NewFileLogWriter
        src/v2ray.com/core/app/log/internal/log_writer.go:88 +0x1cc

goroutine 22 [select, 3 minutes]:
v2ray.com/core/app/log/internal.(*FileLogWriter).run(0x10dfdd20, 0x564558, 0x10dfdd00)
        src/v2ray.com/core/app/log/internal/log_writer.go:61 +0x16c
created by v2ray.com/core/app/log/internal.NewFileLogWriter
        src/v2ray.com/core/app/log/internal/log_writer.go:88 +0x1cc

goroutine 23 [select, 3 minutes, locked to thread]:
runtime.gopark(0x3d9cec, 0x0, 0x3bf5f8, 0x6, 0x18, 0x2)
        /usr/local/go/src/runtime/proc.go:271 +0xfc
runtime.selectgoImpl(0x108207a0, 0x0, 0xc)
        /usr/local/go/src/runtime/select.go:423 +0x116c
runtime.selectgo(0x108207a0)
        /usr/local/go/src/runtime/select.go:238 +0x10
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal_unix.go:434 +0x2bc
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:1017 +0x4

goroutine 8572 [select]:
v2ray.com/core/common/signal.ErrorOrFinish2(0x564558, 0x12aa1160, 0x1344f480, 0x1344f4c0, 0x8b, 0x12aa1180)
        src/v2ray.com/core/common/signal/exec.go:32 +0x1a8
v2ray.com/core/proxy/freedom.(*Handler).Process(0x10ec4660, 0x5645d0, 0x12aa0160, 0x40340ca0, 0x131fc628, 0x5611d0, 0x10ec4640, 0x0, 0x0)
        src/v2ray.com/core/proxy/freedom/freedom.go:136 +0x51c
v2ray.com/core/app/proxyman/outbound.(*Handler).Dispatch(0x10ec4640, 0x5645d0, 0x12aa0160, 0x40340ca0, 0x131fc628)
        src/v2ray.com/core/app/proxyman/outbound/handler.go:67 +0x58
created by v2ray.com/core/app/dispatcher/impl.(*DefaultDispatcher).Dispatch
        src/v2ray.com/core/app/dispatcher/impl/default.go:72 +0x344

goroutine 9748 [runnable]:
v2ray.com/core/common/signal.executeAndFulfill(0x13dd55f0, 0x13de0e80)
        src/v2ray.com/core/common/signal/exec.go:7
created by v2ray.com/core/common/signal.ExecuteAsync
        src/v2ray.com/core/common/signal/exec.go:18 +0x54

goroutine 8574 [select]:
v2ray.com/core/transport/ray.(*Stream).Read(0x12aa01c0, 0x12aa1380, 0x0, 0x0)
        src/v2ray.com/core/transport/ray/direct.go:72 +0x254
v2ray.com/core/common/buf.Pipe(0x12aa0140, 0x40340ce0, 0x12aa01c0, 0x561308, 0x131fc640, 0x36b740, 0x39d400)
        src/v2ray.com/core/common/buf/io.go:40 +0x24
v2ray.com/core/common/buf.PipeUntilEOF(0x12aa0140, 0x40340ce0, 0x12aa01c0, 0x561308, 0x131fc640, 0x12f1fc, 0xc0001)
        src/v2ray.com/core/common/buf/io.go:62 +0x3c
v2ray.com/core/proxy/http.(*Server).handleConnect.func2(0x0, 0x0)
        src/v2ray.com/core/proxy/http/server.go:148 +0xcc
v2ray.com/core/common/signal.executeAndFulfill(0x12aa0200, 0x1344ebc0)
        src/v2ray.com/core/common/signal/exec.go:8 +0x1c
created by v2ray.com/core/common/signal.ExecuteAsync
        src/v2ray.com/core/common/signal/exec.go:18 +0x54

goroutine 1680 [select, 3 minutes]:
v2ray.com/core/common/signal.(*ActivityTimer).run(0x12960aa0)
        src/v2ray.com/core/common/signal/timer.go:24 +0x120
created by v2ray.com/core/common/signal.CancelAfterInactivity
        src/v2ray.com/core/common/signal/timer.go:47 +0xcc

goroutine 9730 [select]:
v2ray.com/core/transport/ray.(*Stream).Read(0x13ddf0a0, 0x13ddf160, 0x0, 0x0)
        src/v2ray.com/core/transport/ray/direct.go:72 +0x254
v2ray.com/core/common/buf.Pipe(0x13ddf380, 0x40340ce0, 0x13ddf0a0, 0x561308, 0x13c59d28, 0x36b740, 0x39d400)
        src/v2ray.com/core/common/buf/io.go:40 +0x24
v2ray.com/core/common/buf.PipeUntilEOF(0x13ddf380, 0x40340ce0, 0x13ddf0a0, 0x561308, 0x13c59d28, 0x0, 0x0)
        src/v2ray.com/core/common/buf/io.go:62 +0x3c
v2ray.com/core/proxy/shadowsocks.(*Client).Process.func2(0x13778f40, 0x0)
        src/v2ray.com/core/proxy/shadowsocks/client.go:108 +0x84
v2ray.com/core/common/signal.executeAndFulfill(0x13ddf400, 0x13dd3200)
        src/v2ray.com/core/common/signal/exec.go:8 +0x1c
created by v2ray.com/core/common/signal.ExecuteAsync
        src/v2ray.com/core/common/signal/exec.go:18 +0x54

goroutine 1669 [select, 3 minutes]:
v2ray.com/core/common/signal.ErrorOrFinish2(0x564558, 0x12513b00, 0x12966800, 0x12966840, 0x8b, 0x12513b20)
        src/v2ray.com/core/common/signal/exec.go:32 +0x1a8
v2ray.com/core/proxy/freedom.(*Handler).Process(0x10ec4660, 0x5645d0, 0x129552e0, 0x40340ca0, 0x129501f8, 0x5611d0, 0x10ec4640, 0x0, 0x0)
        src/v2ray.com/core/proxy/freedom/freedom.go:136 +0x51c
v2ray.com/core/app/proxyman/outbound.(*Handler).Dispatch(0x10ec4640, 0x5645d0, 0x129552e0, 0x40340ca0, 0x129501f8)
        src/v2ray.com/core/app/proxyman/outbound/handler.go:67 +0x58
created by v2ray.com/core/app/dispatcher/impl.(*DefaultDispatcher).Dispatch
        src/v2ray.com/core/app/dispatcher/impl/default.go:72 +0x344

goroutine 883 [select, 3 minutes]:
v2ray.com/core/common/signal.(*ActivityTimer).run(0x123fc0e0)
        src/v2ray.com/core/common/signal/timer.go:24 +0x120
created by v2ray.com/core/common/signal.CancelAfterInactivity
        src/v2ray.com/core/common/signal/timer.go:47 +0xcc

goroutine 884 [select, 3 minutes]:
v2ray.com/core/transport/ray.(*Stream).Read(0x123e5f20, 0x12432f40, 0x0, 0x0)
        src/v2ray.com/core/transport/ray/direct.go:72 +0x254
v2ray.com/core/common/buf.Pipe(0x123fc0e0, 0x40340ce0, 0x123e5f20, 0x561308, 0x121e9c30, 0x36b740, 0x39d400)
        src/v2ray.com/core/common/buf/io.go:40 +0x24
v2ray.com/core/common/buf.PipeUntilEOF(0x123fc0e0, 0x40340ce0, 0x123e5f20, 0x561308, 0x121e9c30, 0x0, 0x0)
        src/v2ray.com/core/common/buf/io.go:62 +0x3c
v2ray.com/core/proxy/shadowsocks.(*Client).Process.func2(0x0, 0x0)
        src/v2ray.com/core/proxy/shadowsocks/client.go:108 +0x84
v2ray.com/core/common/signal.executeAndFulfill(0x123fc160, 0x123e1540)
        src/v2ray.com/core/common/signal/exec.go:8 +0x1c
created by v2ray.com/core/common/signal.ExecuteAsync
        src/v2ray.com/core/common/signal/exec.go:18 +0x54

goroutine 864 [select, 3 minutes]:
v2ray.com/core/common/signal.ErrorOrFinish1(0x564558, 0x123fc0c0, 0x123e1540, 0x12386cdc, 0x1)
        src/v2ray.com/core/common/signal/exec.go:23 +0xd8
v2ray.com/core/common/signal.ErrorOrFinish2(0x564558, 0x123fc0c0, 0x123e1540, 0x123e1580, 0x121e9c30, 0x0)
        src/v2ray.com/core/common/signal/exec.go:44 +0x188
v2ray.com/core/proxy/shadowsocks.(*Client).Process(0x1080c918, 0x5645d0, 0x123e5ec0, 0x40340ca0, 0x121e9bf0, 0x5611d0, 0x10ec45c0, 0x0, 0x0)
        src/v2ray.com/core/proxy/shadowsocks/client.go:129 +0xe48
v2ray.com/core/app/proxyman/outbound.(*Handler).Dispatch(0x10ec45c0, 0x5645d0, 0x123e5ec0, 0x40340ca0, 0x121e9bf0)
        src/v2ray.com/core/app/proxyman/outbound/handler.go:67 +0x58
created by v2ray.com/core/app/dispatcher/impl.(*DefaultDispatcher).Dispatch
        src/v2ray.com/core/app/dispatcher/impl/default.go:72 +0x344

goroutine 1491 [IO wait, 3 minutes]:
net.runtime_pollWait(0x40485528, 0x72, 0x1095a000)
        /usr/local/go/src/runtime/netpoll.go:164 +0x44
net.(*pollDesc).wait(0x1278f6bc, 0x72, 0x561d40, 0x5600e8)
        /usr/local/go/src/net/fd_poll_runtime.go:75 +0x28
net.(*pollDesc).waitRead(0x1278f6bc, 0x1095a000, 0x2000)
        /usr/local/go/src/net/fd_poll_runtime.go:80 +0x24
net.(*netFD).Read(0x1278f680, 0x1095a000, 0x2000, 0x2000, 0x0, 0x561d40, 0x5600e8)
        /usr/local/go/src/net/fd_unix.go:250 +0x148
net.(*conn).Read(0x126d9220, 0x1095a000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:181 +0x58
v2ray.com/core/transport/internet/internal.(*Connection).Read(0x1278f700, 0x1095a000, 0x2000, 0x2000, 0x10822f00, 0x400ea202, 0x0)
        src/v2ray.com/core/transport/internet/internal/connection.go:70 +0x50
bufio.(*Reader).Read(0x12709410, 0x1095a000, 0x2000, 0x2000, 0x2000, 0x130cd8, 0x10)
        /usr/local/go/src/bufio/bufio.go:199 +0x128
v2ray.com/core/common/buf.ReadFrom.func1(0x1095a000, 0x2000, 0x2000, 0x36ac00, 0x127c5530, 0x127c5530)
        src/v2ray.com/core/common/buf/io.go:25 +0x3c
v2ray.com/core/common/buf.(*Buffer).AppendSupplier(0x127c35e0, 0x127c5530, 0x127c5530, 0x0)
        src/v2ray.com/core/common/buf/buffer.go:56 +0x58
v2ray.com/core/common/buf.(*BytesToBufferReader).Read(0x127ada50, 0x127c35c0, 0x0, 0x0)
        src/v2ray.com/core/common/buf/reader.go:33 +0x108
v2ray.com/core/common/buf.Pipe(0x127ea640, 0x561350, 0x127ada50, 0x4048a7c8, 0x127ea6c0, 0x36b788, 0x39d400)
        src/v2ray.com/core/common/buf/io.go:40 +0x24
v2ray.com/core/common/buf.PipeUntilEOF(0x127ea640, 0x561350, 0x127ada50, 0x4048a7c8, 0x127ea6c0, 0x1260dc40, 0x0)
        src/v2ray.com/core/common/buf/io.go:62 +0x3c
v2ray.com/core/proxy/http.(*Server).handleConnect.func1(0x0, 0x0)
        src/v2ray.com/core/proxy/http/server.go:140 +0x12c
v2ray.com/core/common/signal.executeAndFulfill(0x127ea700, 0x1278fb00)
        src/v2ray.com/core/common/signal/exec.go:8 +0x1c
created by v2ray.com/core/common/signal.ExecuteAsync
        src/v2ray.com/core/common/signal/exec.go:18 +0x54

goroutine 1642 [select, 3 minutes]:
v2ray.com/core/common/signal.ErrorOrFinish2(0x564558, 0x12960a80, 0x12962800, 0x12962840, 0x129503e0, 0x0)
        src/v2ray.com/core/common/signal/exec.go:32 +0x1a8
v2ray.com/core/proxy/shadowsocks.(*Client).Process(0x1080c918, 0x5645d0, 0x128f5a40, 0x40340ca0, 0x1267df60, 0x5611d0, 0x10ec45c0, 0x0, 0x0)
        src/v2ray.com/core/proxy/shadowsocks/client.go:129 +0xe48
v2ray.com/core/app/proxyman/outbound.(*Handler).Dispatch(0x10ec45c0, 0x5645d0, 0x128f5a40, 0x40340ca0, 0x1267df60)
        src/v2ray.com/core/app/proxyman/outbound/handler.go:67 +0x58
created by v2ray.com/core/app/dispatcher/impl.(*DefaultDispatcher).Dispatch
        src/v2ray.com/core/app/dispatcher/impl/default.go:72 +0x344

goroutine 1692 [select, 3 minutes]:
v2ray.com/core/common/signal.(*ActivityTimer).run(0x12513b20)
        src/v2ray.com/core/common/signal/timer.go:24 +0x120
created by v2ray.com/core/common/signal.CancelAfterInactivity
        src/v2ray.com/core/common/signal/timer.go:47 +0xcc

goroutine 2179 [select]:
v2ray.com/core/common/signal.(*ActivityTimer).run(0x123e22e0)
        src/v2ray.com/core/common/signal/timer.go:24 +0x120
created by v2ray.com/core/common/signal.CancelAfterInactivity
        src/v2ray.com/core/common/signal/timer.go:47 +0xcc

goroutine 8496 [select]:
v2ray.com/core/transport/ray.(*Stream).Read(0x135aec20, 0x1320ae40, 0x0, 0x0)
        src/v2ray.com/core/transport/ray/direct.go:72 +0x254
v2ray.com/core/common/buf.Pipe(0x135b0e00, 0x40340ce0, 0x135aec20, 0x561308, 0x131fc128, 0x36b740, 0x39d400)
        src/v2ray.com/core/common/buf/io.go:40 +0x24
v2ray.com/core/common/buf.PipeUntilEOF(0x135b0e00, 0x40340ce0, 0x135aec20, 0x561308, 0x131fc128, 0x400, 0x1235ad20)
        src/v2ray.com/core/common/buf/io.go:62 +0x3c
v2ray.com/core/proxy/freedom.(*Handler).Process.func2(0x133ea780, 0x0)
        src/v2ray.com/core/proxy/freedom/freedom.go:120 +0xd8
v2ray.com/core/common/signal.executeAndFulfill(0x135b0e20, 0x133eaa40)
        src/v2ray.com/core/common/signal/exec.go:8 +0x1c
created by v2ray.com/core/common/signal.ExecuteAsync
        src/v2ray.com/core/common/signal/exec.go:18 +0x54

goroutine 3680 [select]:
v2ray.com/core/transport/ray.(*Stream).Read(0x12ca9080, 0x12d58300, 0x0, 0x0)
        src/v2ray.com/core/transport/ray/direct.go:72 +0x254
v2ray.com/core/common/buf.Pipe(0x12ca8fe0, 0x40340ce0, 0x12ca9080, 0x561308, 0x12aa7d10, 0x36b740, 0x39d400)
        src/v2ray.com/core/common/buf/io.go:40 +0x24
v2ray.com/core/common/buf.PipeUntilEOF(0x12ca8fe0, 0x40340ce0, 0x12ca9080, 0x561308, 0x12aa7d10, 0x561368, 0x1258af60)
        src/v2ray.com/core/common/buf/io.go:62 +0x3c
v2ray.com/core/proxy/http.(*Server).handleConnect.func2(0x0, 0x0)
        src/v2ray.com/core/proxy/http/server.go:148 +0xcc
v2ray.com/core/common/signal.executeAndFulfill(0x12ca90c0, 0x12a735c0)
        src/v2ray.com/core/common/signal/exec.go:8 +0x1c
created by v2ray.com/core/common/signal.ExecuteAsync
        src/v2ray.com/core/common/signal/exec.go:18 +0x54

goroutine 2178 [select, 3 minutes]:
v2ray.com/core/common/signal.ErrorOrFinish2(0x564558, 0x123e22a0, 0x10f43700, 0x10f43740, 0x1bb, 0x564a58)
        src/v2ray.com/core/common/signal/exec.go:32 +0x1a8
v2ray.com/core/proxy/http.(*Server).handleConnect(0x1080c8c0, 0x564558, 0x123e22a0, 0x10d81b80, 0x560ac8, 0x10e79470, 0x4033c488, 0x10f43100, 0x2, 0x1bb, ...)
        src/v2ray.com/core/proxy/http/server.go:154 +0x304
v2ray.com/core/proxy/http.(*Server).Process(0x1080c8c0, 0x5645d0, 0x123e2140, 0x2, 0x5665a8, 0x10f43100, 0x5611a0, 0x1080c8c8, 0x0, 0x0)
        src/v2ray.com/core/proxy/http/server.go:103 +0xa78
v2ray.com/core/app/proxyman/inbound.(*tcpWorker).callback(0x10817ac0, 0x5665a8, 0x10f43100)
        src/v2ray.com/core/app/proxyman/inbound/worker.go:56 +0x14c
created by v2ray.com/core/app/proxyman/inbound.(*tcpWorker).handleConnections
        src/v2ray.com/core/app/proxyman/inbound/worker.go:104 +0xe8

goroutine 1481 [select, 3 minutes]:
v2ray.com/core/transport/ray.(*Stream).Read(0x127ea6c0, 0x127c35c0, 0x0, 0x0)
        src/v2ray.com/core/transport/ray/direct.go:72 +0x254
v2ray.com/core/common/buf.Pipe(0x127c34c0, 0x40340ce0, 0x127ea6c0, 0x561308, 0x1267d138, 0x36b740, 0x39d400)
        src/v2ray.com/core/common/buf/io.go:40 +0x24
v2ray.com/core/common/buf.PipeUntilEOF(0x127c34c0, 0x40340ce0, 0x127ea6c0, 0x561308, 0x1267d138, 0x0, 0x0)
        src/v2ray.com/core/common/buf/io.go:62 +0x3c
v2ray.com/core/proxy/shadowsocks.(*Client).Process.func2(0x12758640, 0x0)
        src/v2ray.com/core/proxy/shadowsocks/client.go:108 +0x84
v2ray.com/core/common/signal.executeAndFulfill(0x127c3540, 0x127a6b40)
        src/v2ray.com/core/common/signal/exec.go:8 +0x1c
created by v2ray.com/core/common/signal.ExecuteAsync
        src/v2ray.com/core/common/signal/exec.go:18 +0x54

goroutine 157 [select, 3 minutes]:
v2ray.com/core/common/signal.ErrorOrFinish2(0x564558, 0x10dfd700, 0x10f365c0, 0x10f36600, 0x8b, 0x10dfd720)
        src/v2ray.com/core/common/signal/exec.go:32 +0x1a8
v2ray.com/core/proxy/freedom.(*Handler).Process(0x10ec4660, 0x5645d0, 0x10e754a0, 0x40340ca0, 0x1080d850, 0x5611d0, 0x10ec4640, 0x0, 0x0)
        src/v2ray.com/core/proxy/freedom/freedom.go:136 +0x51c
v2ray.com/core/app/proxyman/outbound.(*Handler).Dispatch(0x10ec4640, 0x5645d0, 0x10e754a0, 0x40340ca0, 0x1080d850)
        src/v2ray.com/core/app/proxyman/outbound/handler.go:67 +0x58
created by v2ray.com/core/app/dispatcher/impl.(*DefaultDispatcher).Dispatch
        src/v2ray.com/core/app/dispatcher/impl/default.go:72 +0x344

**Comment by xiaokangwang** [comment]
fatal error: runtime: out of memory 
这个是内存不足的问题

**Comment by xiaokangwang** [comment]
硬件配置不足以运行V2Ray或者同时运行的程序过多

**Comment by zhaibin18** [comment]
正常运行v2ray需要多少内存？理论上近200M的内存因该能跑的起来。

**Comment by wtlusvm** [comment]
我注意到你的inbound是http proxy server，outbound是shadowsocks，为什么不试试编译个梅林上的shadowsocks呢

**Comment by zhaibin18** [comment]
主要想用来分流，国内不走shadowsocks，国外走shadowsocks。

**Comment by wwqgtxx** [comment]
试试创建一下虚拟内存，小宝的梅林固件中就有这样的建议，虽然不会真正的用上，但是可以防止golang程序崩溃

**Comment by zhaibin18** [comment]
不好意思如何调？小白一个……

**Comment by DarienRaymond** [comment]
建议开启 mux 以减少内存用量。另外 chinaip 会占用较多内存，近期会修复这个问题。正常使用的话，V2Ray客户端应该不会占用超过100M内存。

**Comment by loveyanbei** [comment]
dd if=/dev/zero of=swap bs=1048576 count=96
mkswap swap
swapon swap
