### ISSUE TITLE
Android Studio Socks 代理用户名密码验证失败

### ISSUE THREAD

**Issue by XGHeaven** [v2ray/v2ray-core#417]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
Server: v2.20.1
Client: Android Studio Socks 代理

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
代理下载Android SDK

3)  你看到的不正常的现象是什么？
提示用户名密码验证失败，但是我能保证用户名密码输入一定是正确的，而且telegram的代理是可以正常使用的。同样的用户名和密码，Android Studio就是失败的。

4)  你期待看到的正确表现是怎样的？
正常代理使用

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
```
    {
      "port": 8485,
      "protocol": "socks",
      "settings": {
        "auth": "password",
	"accounts": [{
	  "user": "xxxx",
	  "pass": "xxxxxx"
	}],
	"udp": true
      }
    }
```
    
6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
```
2017/03/19 06:15:13 tcp:39.174.32.99:50313 rejected  Socks|Server: Invalid username or password.
```

**Comment by DarienRaymond** [comment]
原因是 Android Studio 在验证的时候只发了用户名，没有发密码（长度0），不知道为什么。看上去像是 Android Studio 的问题。搜了一圈没什么发现相关的讨论。解决方案就是开一个不设密码的帐号，或者不验证。
