### ISSUE TITLE
v2ray每天内存规律变化，每隔一个月IO升高内存耗尽。

### ISSUE THREAD

**Issue by ie600** [v2ray/v2ray-core#418]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
     V2Ray v2.19

2)  你的使用场景是什么？ 
      SS/VMess/代理浏览网页

3)  你看到的不正常的现象是什么？
     v2ray每天内存规律变化，每隔一个月IO升高内存耗尽。日志显示v2ray: fatal error: runtime: out of memory,图表里DISK IO很高，同时内存耗尽。
![](https://raw.githubusercontent.com/ie600/temp/master/1.png)
![](https://raw.githubusercontent.com/ie600/temp/master/2.png)

4)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    {
  "inbound": {
    "protocol": "shadowsocks",   
    "port": xxxx,  
    "settings": {
      "method": "chacha20",
      "password": "xxxxx",
      "udp": true
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "xxxx",
          "port": xxxx,
          "users": [
            {
              "id": "xxxx"
            }
          ]
        }
      ]
    }
  },
  "inboundDetour": [
    {
      "port": 1080,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true
      }
    },
    {
      "port": 5353,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "8.8.8.8",
        "port": 53,
        "network": "tcp,udp",
        "followRedirect": false
      }
    },
    {
      "port": 8088,
      "protocol": "dokodemo-door",
      "settings": {
        "network": "tcp",
        "followRedirect": true,
        "timeout": 30
      }
    }
  ],
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
}

**Comment by youxixin888** [comment]
IO高应该是使用了物理内存用光了在使用swap.具体可用内存为什么越来越少期待高人回答.

**Comment by VictoriaRaymond** [comment]
这个内存占用是什么类型的？Resident 还是 Virtual

**Comment by ie600** [comment]
这个是物理内存监控，全都被V2RAY常驻程序占用了。我现在设置了每天晚上24点定时重启，内存就自动释放出来了。希望您能帮忙分析下具体原因以及解决方案，谢谢。

**Comment by ldaochen** [comment]
请问下这是什么监控软件啊？？

**Comment by DarienRaymond** [comment]
会在下一版本修复
