### ISSUE TITLE
建议：主站国际化

### ISSUE THREAD

**Issue by yandereacg** [v2ray/v2ray-core#419]
有一些国外的朋友（不懂中文）对v2ray比较感兴趣，但是v2ray.com的英文介绍不太全面。。需要解释很长时间这是如何工作的。。希望能完善英文版的页面：）

**Comment by VictoriaRaymond** [comment]
目前没有精力增加英文（或其它语言）的内容，欢迎PR。在翻译完成之前，最好的方式是 Google Translator。
