### ISSUE TITLE
We need a logo

### ISSUE THREAD

**Issue by v2ray** [v2ray/v2ray-core#42]
Anything that is close to freedom, proxy, ray, anti-censorship are welcome.

**Comment by Lencerf** [comment]
How about this icon in fontawesome?
http://fortawesome.github.io/Font-Awesome/icon/rocket/

**Comment by thrieu** [comment]
Go 会一些，但还是只熟悉 http 编程，想贡献点力量，怎么办呢给个方向

**Comment by lorentzen** [comment]
Transparent v2ray logo, and other versions of a slightly enhanced and redesigned logo. I want to share my creation with you all. I hope you like: https://www.doprax.com/community/v2ray-logo-files-in-svg-and-png/
