### ISSUE TITLE
是否可以代理application

### ISSUE THREAD

**Issue by ayooay** [v2ray/v2ray-core#421]
请问是否可以实现代理application，用于游戏加速器开发。类似Proxifier这种呢。

**Comment by xiaokangwang** [comment]
在Linux平台上可以通过iptable+cgroup实现，参见 https://kkdev.org/post/classify-network-traffic-partial-global-proxy/ 其中 redsocket 可以使用 v2ray 的 透明代理功能实现。

**Comment by DarienRaymond** [comment]
暂时没有计划做这个功能。
