### ISSUE TITLE
HTTP 代理 go get提示 Content-Length: in 200 response； exit status 128

### ISSUE THREAD

**Issue by kxjhlele** [v2ray/v2ray-core#423]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
v2.20.2
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
http 代理 go get 程序
3)  你看到的不正常的现象是什么？
    What did you see?
下载失败 提示 Content-Length: in 200 response
4)  你期待看到的正确表现是怎样的？
    What's your expectation?
正常更新
5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Server Configuration File（服务器端配置文件）:
    ```javascript
    // 在这里附上服务器端配置文件
    // Please attach your server configuration file here.
    ```
    
    Client Configuration File（客户端配置文件）:
    ```javascript
    // 在这里附上客户端配置文件
    // Please attach your client configuration file here.
    ```
    "inbound": {
    "port": 8118,
    "protocol": "http",
    "settings": {
    }
  }
6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.

    Server Log File（服务器端日志）:
    ```
    // 在这里附上服务器端日志
    // Please attach your server log here.
    ```
    
    Client Log File（客户端日志）:
    ```
    // 在这里附上客户端日志
    // Please attach your client log here.
    ```

**Comment by xiaokangwang** [comment]
建议使用go get -v 并将全部输出反馈

**Comment by kxjhlele** [comment]
刚更新到 v2.22了，还是有这个问题
http代理
root@debian:/mnt/share# go get -u -v v2ray.com/core
Fetching https://v2ray.com/core?go-get=1
Parsing meta tags from https://v2ray.com/core?go-get=1 (status code 200)
get "v2ray.com/core": found meta tag main.metaImport{Prefix:"v2ray.com/core", VCS:"git", RepoRoot:"https://github.com/v2ray/v2ray-core"} at https://v2ray.com/core?go-get=1
v2ray.com/core (download)
# cd .; git clone https://github.com/v2ray/v2ray-core /root/go/src/v2ray.com/core
正克隆到 '/root/go/src/v2ray.com/core'...
fatal: unable to access 'https://github.com/v2ray/v2ray-core/': Content-Length: in 200 response
package v2ray.com/core: exit status 128

socket代理正常

**Comment by DarienRaymond** [comment]
看上去像是 cURL 的更新导致的。根本问题是 V2Ray 的 HTTP 实现不符合标准，但是 cURL 的某个版本拒绝了不标准的 HTTP 头。在某个版本之后又开始开放了这个限制。详见：https://github.com/curl/curl/issues/1317

暂时的解决方案是使用新版本的 cURL，或者等 V2Ray 更新。

**Comment by kxjhlele** [comment]
目前 curl 7.52.1， v2ray 2.22.2 已经正常了，
