### ISSUE TITLE
actinium 拦截广告的问题。

### ISSUE THREAD

**Issue by cnperi** [v2ray/v2ray-core#425]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    手机端actinium0.7.2、服务器v2ray 2.20.2

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
手机chrome上网，已配置了通过域名拦截广告。
3)  你看到的不正常的现象是什么？
    What did you see?
无法拦截广告。
4)  你期待看到的正确表现是怎样的？
    What's your expectation?
正常拦截广告。

记得谁说过，好像android的VPN模式不支持域名方式拦截广告。如果是，请告知，我就不忙活了。

**Comment by DarienRaymond** [comment]
嗯，不支持。在这个 https://github.com/v2ray/Planning/issues/8 完成之前，VPN 模式下不支持域名模式的路由。

**Comment by cnperi** [comment]
OK，谢谢了。记得在哪个地方看到来着，就是找不到。
