### ISSUE TITLE
望推荐款大运存宽带路由器(可刷DDWRT/OpenWRT性能够跑V2Ray)

### ISSUE THREAD

**Issue by BenhoNNNN** [v2ray/v2ray-core#427]
望有经验的朋友不吝告知，谢谢。

**Comment by lixingcong** [comment]
ARM架构妥妥的

看你预算呗，一般得上几百。不过几百块钱还不如买x86软路由

**Comment by wtlusvm** [comment]
![](https://steamcn.com/static/image/smiley/steamcn_5/kbc119.gif)我直接LAN里接一个树莓派做中转。就是Clients->Router---(Shadowsocks)--->RaspberryPi---(VMess)--->Server

**Comment by BenhoNNNN** [comment]
@lixingcong 能告知个品牌信号吗，比如netgear……

**Comment by rampageX** [comment]
BUFFALO WZR-1750DHP 某宝二手 3xx：

> CPU: Broadcom BCM4708A0 (800 MHz, 2 cores)
> FLA1: 128 MiB (Zentel A5U1GA31ATS-BC)
> RAM1: 512 MiB (PieceMakers PMF512816ABR-KADN)

可刷 DD-WRT。

**Comment by DarienRaymond** [comment]
Close due to inactivity
