### ISSUE TITLE
Memory usage - can it be improved?

### ISSUE THREAD

**Issue by nielspeen** [v2ray/v2ray-core#428]
Using v2ray 2.20.2 as a Shadowsocks server.

Memory usage is 1.7G RES (not VIRT!) when opening 500 Shadowsocks ports. (My target is 10000+ ports.)

These 500 ports are just listening, and not actively used. Can the memory usage be improved? (For comparison: listening on 12000 ports with xinetd uses only 98M RES memory.)

**Comment by DarienRaymond** [comment]
Can you share your config file?

**Comment by nielspeen** [comment]
Please find my config file below. (I've trimmed the repetitive parts.)

```
{
  "port": 8888,
  "log": {
    "access":   "/var/log/v2ray/access.log",
    "error":    "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 7777,
    "protocol": "vmess",
    "settings": {
      "clients": [
         // start repeat 500 times with different id and e-mail for vmess access
         {
          "id": "cf648e4e-3367-4ebf-884c-xxxx",
          "email": "mango@fruit.com",
          "level": 0,
          "alterId": 64
        },
        // end repeat
      ],
      "features": {
        "detour": {
          "to": "detour"
        }
      }
    },
    "streamsettings": {
      "network": "tcp"
    }
  },
  "inbounddetour": [
    // start repeat 500 times with different port, email and password for shadowsocks access
    {
      "protocol": "shadowsocks",
      "port": 9999,
      "settings": {
        "email": "apple@fruit.com",
        "method": "chacha20",
        "password": "fhefherufheruifheriuf",
        "udp": false,
        "level": 0
      }
    },
    // end repeat 
    {
      "protocol": "vmess",
      "port": "10240-20479",
      "tag": "detour",
      "settings": {
        "default": {
          "level": 0
        }
      },
      "allocate": {
        "strategy": "random",
        "concurrency": 5,
        "refresh": 5
      }
    }
  ],
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  }
}
```

**Comment by DarienRaymond** [comment]
The majority of memory usage comes from VMess I believe. 500 clients with 64 alter ids each may cause over 500 MB memory + Golang internal overhead. You can reduce the alter id value to 32 or lower to see if the memory usage drops. 

What is your use case for this VMess <-> Shadowsock tunnel with 12000 accounts?

**Comment by nielspeen** [comment]
Thanks. Lowering the alterid saved about 30% in memory. Still very high though. The CPU usage too. (Starts at 100% and slowly drops to 8% or so after 10 minutes.) Will try removing vmess and shadowsocks completely - one at a time - to see which one causes this.

The use case is probably a VPN server. At this stage I'm asked only to see how well shadowsocks scales to larger number of users.

**Comment by DarienRaymond** [comment]
There is no plan to solve this memory usage issue at the moment.
