### ISSUE TITLE
关于 vmess 传入配置中 clients id 和 alterid、level 的疑惑

### ISSUE THREAD

**Issue by cnperi** [v2ray/v2ray-core#429]
我多次阅读了 v2ray 的用户手册，但对 vmess 传入配置中 clients id 和 alterid、level 的使用仍有些疑惑。
1、clients id 是否强制一用户一个？
2、alter id 是否只是为了增强 clients id 的抗探测性？alter id 是否是随机的？alter id 能否用来区分使用同一 clients id 的不同用户？（我原认为 alter id 是为了区分同一用户的不同并发线程而设置的。这种看法是否正确？）
3、level 值为0和非零时，可信任性的区别是什么？严格安全限制的意味着什么？
4、“email 用户邮箱地址，用于区分不同用户的流量”，是否意味着可以多用户使用同一个 clients id，只是通过不同的 email 地址来区分？关键是 email 地址在传出配置中没有设置的地方啊。

**Comment by DarienRaymond** [comment]
1. 不强制
2. 是的。不是，alter id 是根据 client id 由一个确定的规则生成出来的。不能。
3. 目前的设定是超时时限。level = 1 时，连接有更长的超时时限。
4. 不能。email 地址和 client id 要对应。

**Comment by cnperi** [comment]
谢谢 @DarienRaymond 的耐心回答。
对于4，可否这样理解：配置 email 项，仅仅是为了增加 clients id 的可读性？
多用户使用同一个 clients id，有没有数量上的限制？存不存在问题呢？

**Comment by DarienRaymond** [comment]
是的

没有限制，但是会降低安全性。只要知道 client id （和通信的具体时间）就可以解密传输的数据，不同的用户理论上可以拦截对方的流量然后解密。

**Comment by cnperi** [comment]
明白了。谢谢 @DarienRaymond 。

**Comment by hzxswyg** [comment]
个人有一个疑问，能否在日志文件中记录用户email用于表示连接增加日志文件的可读性？

**Comment by dbsxdbsx** [comment]
@DarienRaymond， 您好打扰下。

我有个可能比较傻的问题：
就是我一般翻墙是通过购买某服务商的订阅url，根据返回的服务器地址来+v2rayn这类软件使用代理的。使用时
我也是把环境变量http_proxy(s)设置为127.0.0.1:<port>， 但现在我希望在虚拟机中安装linux，
其在刚安装时只有终端（没有ui）情况下，我希望将某个代理服务器设置为全局代理（这样下载会快很多）—因为日后要直接给host主机装，所以不考虑虚拟机采用host主机代理的方案。

网上看的教程也是在终端中设置 export http_proxy，具体格式为：http://USERNAME:PASSWORD@proxyhost:PROXYPORT/

这里的PROXYHOST:PROXYPORT应该就是填的我选择的某个代理服务器的IP和端口号吧，但是前面的USERNAME:PASSWORD
该怎么填的。 我查了半天资料也只是知道每个代理服务器有个uid，是密码有关的。其他就不知道了。

**Comment by yinyuanzhang** [comment]
> @DarienRaymond， 您好打扰下。
> 
> 我有个可能比较傻的问题： 就是我一般翻墙是通过购买某服务商的订阅url，根据返回的服务器地址来+v2rayn这类软件使用代理的。使用时 我也是把环境变量http_proxy(s)设置为127.0.0.1:， 但现在我希望在虚拟机中安装linux， 其在刚安装时只有终端（没有ui）情况下，我希望将某个代理服务器设置为全局代理（这样下载会快很多）—因为日后要直接给host主机装，所以不考虑虚拟机采用host主机代理的方案。
> 
> 网上看的教程也是在终端中设置 export http_proxy，具体格式为：http://USERNAME:PASSWORD@proxyhost:PROXYPORT/
> 
> 这里的PROXYHOST:PROXYPORT应该就是填的我选择的某个代理服务器的IP和端口号吧，但是前面的USERNAME:PASSWORD 该怎么填的。 我查了半天资料也只是知道每个代理服务器有个uid，是密码有关的。其他就不知道了。

您好，我也遇到了类似问题，请问您解决了么

**Comment by dbsxdbsx** [comment]
> > @DarienRaymond， 您好打扰下。
> > 我有个可能比较傻的问题： 就是我一般翻墙是通过购买某服务商的订阅url，根据返回的服务器地址来+v2rayn这类软件使用代理的。使用时 我也是把环境变量http_proxy(s)设置为127.0.0.1:， 但现在我希望在虚拟机中安装linux， 其在刚安装时只有终端（没有ui）情况下，我希望将某个代理服务器设置为全局代理（这样下载会快很多）—因为日后要直接给host主机装，所以不考虑虚拟机采用host主机代理的方案。
> > 网上看的教程也是在终端中设置 export http_proxy，具体格式为：http://USERNAME:PASSWORD@proxyhost:PROXYPORT/
> > 这里的PROXYHOST:PROXYPORT应该就是填的我选择的某个代理服务器的IP和端口号吧，但是前面的USERNAME:PASSWORD 该怎么填的。 我查了半天资料也只是知道每个代理服务器有个uid，是密码有关的。其他就不知道了。
> 
> 您好，我也遇到了类似问题，请问您解决了么

没解决，我弃坑，不搞linux和虚拟机了。
