### ISSUE TITLE
多个shadowsocks 客户端 程序崩溃

### ISSUE THREAD

**Issue by luolufang** [v2ray/v2ray-core#430]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    2.22

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
shadowsocks多个服务器负载均衡--->socks-->v2ray--->shadowsocks-inbound--> client

3)  你看到的不正常的现象是什么？
    有1个shadowsocks客户端连上后，发送数据后，程序崩溃

4)  你期待看到的正确表现是怎样的？
    多个shadowsocks 客户端正常使用

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
```javascript
{
  "log": { 
    "loglevel": "warning"  
  },
  "inbound": {
    "port": 37192, 
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "3b129dec-72a3-4d28-aeee-028a0fe86e22",  
          "level": 1 
        }
      ]
    }
  },
  "inboundDetour": [
    {
      "protocol": "shadowsocks",   
      "port": 8388, 
      "settings": {
        "method": "aes-256-cfb", 
        "password": "jbjbjb",     
        "udp": false             
    }
    }
    ],
      "outbound": {
     "address": "127.0.0.1",
    "port": 1083, 
    "protocol": "socks", 
    "settings": {
      "auth": "noauth",  
      "udp": false      
    }
  },

  "outboundDetour": [
    {
    "protocol": "freedom", 
    "settings": {},
    "tag": "direct"
  }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": "1-52",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "54-79",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "81-442",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "444-65535",
          "outboundTag": "direct"
        },
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        }
      ]
    }
  },
 "transport": {
"tcpSettings": {
    "connectionReuse": true
  },
    "kcpSettings": {
        "uplinkCapacity": 60,
    "downlinkCapacity": 60,
    "congestion": true,
    "readBufferSize": 2, 
    "writeBufferSize": 2,
    "header": {
      "type": "utp"
    }
  
    }
  }
}
```
    
6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
 An unified platform for anti-censorship.
2017/04/11 11:15:48 [Debug]App|Proxyman|Inbound|AlwaysOnInboundHandler: creating
 tcp worker on 0.0.0.0:37192
2017/04/11 11:15:48 [Debug]App|Proxyman|Inbound|AlwaysOnInboundHandler: creating
 tcp worker on 0.0.0.0:8388
2017/04/11 11:15:48 [Warning]V2Ray started
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x24 pc=0x637ca6]

goroutine 20 [running]:
v2ray.com/core/proxy/socks.(*Client).Process.func1(0x74ca00, 0x0)
        src/v2ray.com/core/proxy/socks/client.go:47 +0x66
v2ray.com/core/common/retry.(*retryer).On(0x131e8528, 0x131faf80, 0x942920, 0x13
1e8528)
        src/v2ray.com/core/common/retry/retry.go:29 +0x70
v2ray.com/core/proxy/socks.(*Client).Process(0x11994a68, 0x945fc0, 0x1325c300, 0
x32150088, 0x12f7c060, 0x942560, 0x12f8ab00, 0x0, 0x0)
        src/v2ray.com/core/proxy/socks/client.go:55 +0x200
v2ray.com/core/app/proxyman/outbound.(*Handler).Dispatch(0x12f8ab00, 0x945fc0, 0
x1325c300, 0x32150088, 0x12f7c060)
        src/v2ray.com/core/app/proxyman/outbound/handler.go:79 +0x1d2
created by v2ray.com/core/app/dispatcher/impl.(*DefaultDispatcher).Dispatch
        src/v2ray.com/core/app/dispatcher/impl/default.go:72 +0x360

**Comment by DarienRaymond** [comment]
你的 socks 配置写错了，socks outbound 配置大约是这样的：

```javascript
{
  "servers": [{
    "address": "127.0.0.1",
    "port": 1234,
    "users": [
      {
        "user": "test user",
        "pass": "test pass"
      }
    ]
  }]
}
```

详见： https://www.v2ray.com/chapter_02/protocols/socks.html

**Comment by luolufang** [comment]
万分感谢。

以下为正确配置

{
  "log": { 
    "loglevel": "warning"  
  },
  "inbound": {
    "port": 37192, 
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "3b129dec-72a3-4d28-aeee-028a0fe86e22",  
          "level": 1 
        }
      ]
    }
  },
  "inboundDetour": [
        {
      "protocol": "shadowsocks",   
      "port": 8389, 
      "settings": {
        "method": "aes-256-cfb", 
        "password": "jbjbjb",     
        "udp": false             
    }
    },
        {
      "protocol": "shadowsocks",   
      "port": 8390, 
      "settings": {
        "method": "aes-256-cfb", 
        "password": "jbjbjb",     
        "udp": false             
    }
    }
    ],
      "outbound":{
          "protocol": "socks",
          "settings": {
              "servers": [{
                  "address": "127.0.0.1",
                  "port": 1083
              }]
          }
      },
  "outboundDetour": [
{

    "protocol": "freedom", 
    "settings": {},
    "tag": "direct"
  }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": "1-52",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "54-79",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "81-442",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "444-65535",
          "outboundTag": "direct"
        },
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        }
      ]
    }
  },
 "transport": {
"tcpSettings": {
    "connectionReuse": true
  },
    "kcpSettings": {
        "uplinkCapacity": 60,
    "downlinkCapacity": 60,
    "congestion": true,
    "readBufferSize": 2, 
    "writeBufferSize": 2,
    "header": {
      "type": "utp"
    }
  
    }
  }
}
