### ISSUE TITLE
v2ray 在路由器上崩溃

### ISSUE THREAD

**Issue by luolufang** [v2ray/v2ray-core#433]
这两天在路由器上折腾v2ray 

调试完毕后发现

017/04/17 08:17:18 [Debug]App|Proxyman|Inbound: creating tcp worker on 127.0.0.1:1083
2017/04/17 08:17:18 [Debug]App|Proxyman|Inbound: creating tcp worker on 0.0.0.0:14443
2017/04/17 08:17:18 [Debug]App|Proxyman|Inbound: creating tcp worker on 0.0.0.0:14444
2017/04/17 08:17:19 [Warning]Core: V2Ray started
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x3c8493, 0x16)
[8C/usr/local/go/src/runtime/panic.go:596 +0x70

问下下个版本有没有可能限制下v2ray 申请的虚拟内存，或者手动指定。

在256M的路由器上，一上来就申请了777M的虚拟内存。

**Comment by luolufang** [comment]
目前用守护脚本
while true
do
if [ `ps | grep "v2ray" | wc -l`  = 3 ];then
nohup /koolshare/v2ray -config=/koolshare/v2ray-client.json &
fi
sleep 3
done
~

3秒扫一次 崩溃了立刻启动

**Comment by DarienRaymond** [comment]
虚拟内存是没办法指定的，Golang 会自动申请一个很大的虚拟内存。如果是这个引起的 panic，就只能去 golang 那边提 issue 了。如果是实际使用的内存超过了限制，暂时没有解决方案。下一版本会有一些改动降低内存的用量。

**Comment by wd** [comment]
我目前也遇到类似问题了，路由器上面跑，会遇到 fatal error: runtime: cannot allocate memory 的错误。
目前在尝试把 alterId 调小到 10 好像有一点用。

  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
 1598     1 admin    S     780m312.0   0  0.1 /jffs/v2ray/v2ray
