### ISSUE TITLE
这两天打不开国外网站了

### ISSUE THREAD

**Issue by walasix** [v2ray/v2ray-core#437]
这两天通过V2ray打不开Google等国外网站，但是国内的网站却可以。
客户端版本2.24.1，客户端也没有错误提示。小白求解~

**Comment by DarienRaymond** [comment]
如果你用的是官方服务器，这几天官方服务器被攻击下线了。

如果你用的是自己的服务器，请附上配置文件和日志。

**Comment by walasix** [comment]
@DarienRaymond 哦，谢谢大神回复。官方的什么时候会恢复呢？ 另外求教怎么搭建自己的服务器？

**Comment by DarienRaymond** [comment]
目前风声较紧，过段时间会择机重开。
