### ISSUE TITLE
关于Mux

### ISSUE THREAD

**Issue by testcaoy7** [v2ray/v2ray-core#439]
1、在配置了TLS的情况下，Mux是否得到来自TLS加密？

2、在同时配置了WebSocket和Mux的情况下，传输会是怎样的？

**Comment by DarienRaymond** [comment]
协议结构从上到下是这样的：

1. 内容(如 Mux) 
2. 认证(如 VMess)
3. 传输(如 TLS/WebSocket) 

下层的协议是看不到上层的内容的，比如 VMess 不知道它传输的内容是不是 Mux，TLS 不知道它传输的内容是 VMess 还是 Shadowsocks。

然后回答你的问题：

1. 是的
2. WebSocket 里面包了 Mux

**Comment by testcaoy7** [comment]
明白了，谢谢！
