### ISSUE TITLE
关于v2ray的协议

### ISSUE THREAD

**Issue by sohaking** [v2ray/v2ray-core#44]
时间随机数，它没法确保两台机子时间完全同步，如果加上网络延迟刚好差1s，那么这1s内就有1/30的数据包会丢失，而且我看了下这个协议的逻辑是十分占用CPU的。不过动态加密比ss好

**Comment by v2ray** [comment]
服务器端会保留当前时间前后两分钟的数据，只要两台机器的时间差距不超过两分钟，就不会有问题。而这两分钟数据的计算，和网络流量的加密解密比起来，根本不算什么。
