### ISSUE TITLE
V2Ray是否支持端口逆映射

### ISSUE THREAD

**Issue by KilyMoco** [v2ray/v2ray-core#440]
我在一个有公网IP的服务器上运行了V2Ray-Server且在一台没有公网IP的电脑上运行了V2Ray-Client，其中V2Ray-Server与V2Ray-Client之间通讯使用了vmess协议。如果有一个外部的连接主动连接到服务器的固定端口上，那么V2Ray-Server是否可以将这个外部连接转发给V2Ray-Client？

**Comment by kxjhlele** [comment]
你直接说反向代理不就好了，
目前不支持，

**Comment by DarienRaymond** [comment]
不支持，目前也没有计划做这个。如有需求请去 https://github.com/v2ray/planning 发 issue。
