### ISSUE TITLE
启用 mux 该如何具体修改配置文件？

### ISSUE THREAD

**Issue by wan-qy** [v2ray/v2ray-core#441]
v2ray.com 给出
```json
{
  "enabled": false,
  "concurrency": 8
}
```
但是我似乎不能理解具体应该如何修改配置文件，Google 无果，望指点。

**Comment by DarienRaymond** [comment]
[示例配置](https://github.com/v2ray/v2ray-core/blob/master/tools/release/config/vpoint_socks_vmess.json)，搜 mux

**Comment by wan-qy** [comment]
Thanks!
