### ISSUE TITLE
有意开发完善windows平台gui

### ISSUE THREAD

**Issue by qingyede** [v2ray/v2ray-core#442]
下面的描述都是针对客户端

最近一段时间我仔细使用了v2ray，发现是一个不错的东东
然后使用了下windows平台的gui，都太简单和难用了

v2ray 的config很强大，但是普通用户可能根本不会用到，然后自己动手做了一个gui。
基本的功能是类似sswindows版，可以在gui上配置服务器信息，可以选择默认使用那个服务器等。
现在的问题是，我能发布这个gui到github上吗？还是只能自用？
另外个人精力有限，没有读core源码，请问下，每次改动config.json，是不是只能重启v2ray？

**Comment by wtlusvm** [comment]
[发布gui到gayhub上可以参考这里](https://www.v2ray.com/chapter_04/org.html)

> 每次改动config.json，是不是只能重启v2ray？
是的

**Comment by DarienRaymond** [comment]
是的，只能重启 V2Ray

**Comment by qingyede** [comment]
明白了，我先去开发基本的gui功能，关闭
