### ISSUE TITLE
自动安装脚本 go.sh 的一些建议

### ISSUE THREAD

**Issue by jinyu121** [v2ray/v2ray-core#443]
首先十分感谢这个脚本。

然后是一些建议：

1. 如果指定了`--local`，那么不要再输入版本号了。压缩包内只有一个版本，正则一下求出版本号吧。
1. 如果不是`--local`，那么自动从github上下载，能否同时下载附带的哈希，自动进行校验？
1. 目前的脚本没有判断“是否真的安装成功”。

THX

**Comment by xiaokangwang** [comment]
关于这个问题有2个需要讨论的内容：
实现的过程中是否会增加需要的依赖项，增加什么依赖项。
校验时的信任链问题。

实现1,2个提议可能会增加需要的依赖项，比如grep sed awk gpg2 openssl中的一个或者多个, 是否有增加这些依赖项的必要。
实现第二个提议的话，应该考虑验证的公钥的存放位置

**Comment by jinyu121** [comment]
1. 现有脚本中已经有用到grep并且工作正常，所以不需要增加其他依赖。
2. 从某个版本开始提供了`metadata.txt`文件。信任链……觉得不需要吧。如果需要的话，可以在release说明里面加上`metadata.txt`的校验码，或者压缩包以“现有文件名-校验码前6位”来命名。不过后一种方案好像增加了脚本难度。

**Comment by DarienRaymond** [comment]
1. 简单的防呆措施还是需要的，你至少要知道你在装的是哪个版本；
2. 欢迎PR
3. 脚本已升级，现在有错误会强制退出。
