### ISSUE TITLE
V2Ray 2.24 间歇性连接无响应或安全连接失败

### ISSUE THREAD

**Issue by lzqyydy** [v2ray/v2ray-core#444]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
2.24

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
自有VPS构建v2ray
Socks/VMess mKCP代理连接网络

3)  你看到的不正常的现象是什么？
1.在不定时间（<10%）出现网络无法连接，表现为连接无响应超时
2.在某些情况下出现握手证书错误（安全连接失败或YouTube返回twitter或facebook证书），是否为dns配置问题？
3.上述问题在一段时间后或不定次重启服务器端v2ray后消失
4.问题发生时与服务器链接畅通

4)  你期待看到的正确表现是怎样的？

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
server：https://pastebin.com/EAch43LH
client（使用mac GUI客户端生成）：https://pastebin.com/TrARaKjW
6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
无记录
warning等级下access与error中均无任何log

**Comment by DarienRaymond** [comment]
和这个( https://github.com/v2ray/v2ray-core/issues/436 )是同一个问题吗

**Comment by lzqyydy** [comment]
我这边从用户层面不能判断出是不是一样的问题
不同点在于
+ 我这边并不是卡顿然后得到结果，是完全的连接失败，之后服务器也没有日志
+ 没有使用mux以及动态端口，仅有vmess（kcp）代理

补充目前出现过的症状
+ 代理完全无响应，无法连接任何站点
+ 代理无法连接youtube和google（安全连接失败），但同时可以访问v2ray.com以及在whatismyip获得正确结果
+ 代理出现证书错误，YouTube证书无效，获取的证书作用于twitter.com（以及一次完全的链接变化）

**Comment by DarienRaymond** [comment]
连接失败有可能是 UDP(mKCP) 被 QoS，由于 UDP 没有状态，客户端在一段时间得不到响应之后会超时退出，而服务器端没有日志。调试方法是开启 mux 看一下这种情况是否减少。mux 会有效减少连接数量。

证书错误似乎不像是 V2Ray 的问题，你的客户端或服务器有可能被劫持。

**Comment by lzqyydy** [comment]
尝试启用mux试试看
