### ISSUE TITLE
路由优先级讨论

### ISSUE THREAD

**Issue by kuyapp** [v2ray/v2ray-core#446]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    v2.26

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    使用不同的inboud走不同的线路(outbound)，同时使用了chinip规则

3)  你看到的不正常的现象是什么？
    使用inboundDetour时，chinaip规则不生效

4)  你期待看到的正确表现是怎样的？
    使用inboundDetour时，chinaip规则生效

通过调试发现原因如下：
当dest是域名时，路由会先把所有rule测试一遍，没有符合的才会resolve成ip，也就是说，这种情况下，ip规则优先级比其它都低。
一般情况没什么问题，但想使用不用的inbound走不同的线路(也就是不同的outbound)时，所以路由中有一个rule是
```javascript
"type": "field",
"inboundTag": [
    "tag-a"
  ],
  "outboundTag": "out-a"
```
这时使用tag-a inbound时，chinaip这种规则就永远不会符合了，因为这条rule会优先符合。

**Comment by x2nbit** [comment]
相同的问题，在routing部分，rules下的规则并没有严格按照先后顺序进行匹配，而是会优先匹配nbound类型的规则。当希望根据不同的inbound走不同的outbound线路时，就没有办法进行ip、域名规则的匹配。
希望的结果是：A入口——ip规则、域名规则等——A出口，B入口——ip规则、域名规则等——B出口，

**Comment by DarienRaymond** [comment]
在下一版本(2.48)会提供新的路由策略 IPOnDemand，会把 IP 和域名放在同一优先级处理。
