### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by angerbaby23456** [v2ray/v2ray-core#447]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。

Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
![image](https://cloud.githubusercontent.com/assets/28673998/26026532/89219fc4-382f-11e7-93d8-4356b8072e2e.png)

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.我用的是chrome看youtube

3)  你看到的不正常的现象是什么？
    What did you see?
手机上能用，电脑上不能用

4)  你期待看到的正确表现是怎样的？
    What's your expectation?

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your{"log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 443,
    "protocol": "vmess",
    "settings": {
        "clients": [
            {
                "id": "31f68388-7066-40bb-aafd-132c7b94cfad",
                "level": 0,
                "alterId": 100
            }
        ],
        "detour": {
            "to": "detour"
        }
    },
    "streamSettings": {
      "network": "tcp",
      "tcpSettings": {
        "connectionReuse": true,
        "header": {
          "type": "http",
          "request": {
            "version": "1.1",
            "method": "GET",
            "path": ["/"],
            "headers": {
              "Host": ["www.baidu.com", "www.sogou.com/"],
              "User-Agent": [
                "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36",
                        "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
              ],
              "Accept-Encoding": ["gzip, deflate"],
              "Connection": ["keep-alive"],
              "Pragma": "no-cache"
            }
          },
          "response": {
            "version": "1.1",
            "status": "200",
            "reason": "OK",
            "headers": {
              "Content-Type": ["application/octet-stream", "application/x-msdownload", "text/html", "application/x-shockwave-flash"],
              "Transfer-Encoding": ["chunked"],
              "Connection": ["keep-alive"],
              "Pragma": "no-cache"
            }
          }
        }
      }
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },

      
  "inboundDetour": [
    {
      "protocol": "vmess",
      "port": "443-1086",
      "tag": "detour",
      "settings": {},
        "allocate": {
            "strategy": "random",
            "concurrency": 10,
            "refresh": 5
        },
    "streamSettings": {
      "network": "tcp",
      "tcpSettings": {
        "connectionReuse": true,
        "header": {
          "type": "http",
          "request": {
            "version": "1.1",
            "method": "GET",
            "path": ["/"],
            "headers": {
              "Host": ["www.baidu.com", "www.sogou.com/"],
              "User-Agent": [
                "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36",
                        "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
              ],
              "Accept-Encoding": ["gzip, deflate"],
              "Connection": ["keep-alive"],
              "Pragma": "no-cache"
            }
          },
          "response": {
            "version": "1.1",
            "status": "200",
            "reason": "OK",
            "headers": {
              "Content-Type": ["application/octet-stream", "application/x-msdownload", "text/html", "application/x-shockwave-flash"],
              "Transfer-Encoding": ["chunked"],
              "Connection": ["keep-alive"],
              "Pragma": "no-cache"
            }
          }
        }
      }
    }
            }
  ],
    

  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}
 configuration file (**Mask IP addresses before submit this issue**).

    Server Configuration File（服务器端配置文件）:
```javascript
    // 在这里附上服务器端配置文件
    // Please attach your server configuration file here.
```

    Client Configuration File（客户端配置文件）:
```javascript
    // 在这里附上客户端配置文件
    // Please attach your client configuration file here.
```

6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.

    Server Log File（服务器端日志）:
```
    // 在这里附上服务器端日志
    // Please attach your server log here.
``` [Warning]Transport|Internet|TCP: failed to accepted raw connections > Retry: [accept tcp [::]:1026: use of closed network connection] > Retry: all retry attempts failed
2017/05/13 23:00:18 [Warning]Transport|Internet|TCP: failed to accepted raw connections > Retry: [accept tcp [::]:571: use of closed network connection] > Retry: all retry attempts failed
2017/05/13 23:00:18 [Warning]Transport|Internet|TCP: failed to accepted raw connections > Retry: [accept tcp [::]:823: use of closed network connection] > Retry: all retry attempts failed
2017/05/13 23:00:18 [Warning]Transport|Internet|TCP: failed to accepted raw connections > Retry: [accept tcp [::]:692: use of closed network connection] > Retry: all retry attempts failed
2017/05/13 23:00:18 [Warning]Transport|Internet|TCP: failed to accepted raw connections > Retry: [accept tcp [::]:499: use of closed network connection] > Retry: all retry attempts failed
2017/05/13 23:00:18 [Warning]Transport|Internet|TCP: failed to accepted raw connections > Retry: [accept tcp [::]:945: use of closed network connection] > Retry: all retry attempts failed
2017/05/13 23:00:18 [Warning]Transport|Internet|TCP: failed to accepted raw connections > Retry: [accept tcp [::]:840: use of closed network connection] > Retry: all retry attempts failed
2017/05/13 23:00:18 [Warning]Transport|Internet|TCP: failed to accepted raw connections > Retry: [accept tcp [::]:693: use of closed network connection] > Retry: all retry attempts failed


    Client Log File（客户端日志）:
```
![image](https://cloud.githubusercontent.com/assets/28673998/26026580/93dfc264-3830-11e7-8f40-5be17a827c37.png)

    // 在这里附上客户端日志
    // Please attach your client log here.
```
![image](https://cloud.githubusercontent.com/assets/28673998/26026587/9e924326-3830-11e7-95c0-ab1d4d8ac579.png)

**Comment by angerbaby23456** [comment]
客户端配置文件
{
  "log": {
    "loglevel": "info"
  },
  "inbound": {
    "port": 1080,
    "listen": "127.0.0.1",
    "protocol": "http",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "127.0.0.1"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
        "vnext": [
            {
                "address": "108.61.186.242",
                "port": 443,
                "users": [
                    {
                        "id": "31f68388-7066-40bb-aafd-132c7b94cfad",
                        "alterId": 100
                    }
                ]
            }
        ]
    },
    "streamSettings": {
      "network": "tcp",
      "tcpSettings": {
        "connectionReuse": true,
        "header": {
          "type": "http",
          "request": {
            "version": "1.1",
            "method": "GET",
            "path": ["/"],
            "headers": {
              "Host": ["www.baidu.com", "www.sogou.com/"],
              "User-Agent": [
                "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36",
                        "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
              ],
              "Accept-Encoding": ["gzip, deflate"],
              "Connection": ["keep-alive"],
              "Pragma": "no-cache"
            }
          },
          "response": {
            "version": "1.1",
            "status": "200",
            "reason": "OK",
            "headers": {
              "Content-Type": ["application/octet-stream", "application/x-msdownload", "text/html", "application/x-shockwave-flash"],
              "Transfer-Encoding": ["chunked"],
              "Connection": ["keep-alive"],
              "Pragma": "no-cache"
            }
          }
        }
      }
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        }
      ]
    }
  }
}

**Comment by angerbaby23456** [comment]
大神，电脑还是用不了

**Comment by cnperi** [comment]
这种情况，最大的可能性，就是客户端电脑的时间没有同步。
