### ISSUE TITLE
请问Windows版能否用于Windows 8/10 的Metro UI App?

### ISSUE THREAD

**Issue by 171621** [v2ray/v2ray-core#449]
Windows 8/10 的Metro UI App因为用的是UWP因此与localhost隔离了。必须要类似VPN的协议才能代理，请问这个Windows版的工具能否用于Windows 8/10 的Metro UI App?

**Comment by DarienRaymond** [comment]
V2Ray Core 不行，Windows UI 版本你在另一个 [repo](https://github.com/v2ray/v2rayN/issues/1) 也问了，这个就关了。

**Comment by 171621** [comment]
好的  多谢了!
