### ISSUE TITLE
HTTP Outbound Support

### ISSUE THREAD

**Issue by undirectlookable** [v2ray/v2ray-core#450]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

> v2.28

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

> 内部网络，必须使用 HTTP 代理访问外网

3)  你看到的不正常的现象是什么？
    What did you see?

> v2ray 不支持 http 协议的 outbound

4)  你期待看到的正确表现是怎样的？
    What's your expectation?

> 支持 http 协议传出，可参考 [gost](https://github.com/ginuerzh/gost)

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Client Configuration File（客户端配置文件）:
```javascript
  "outboundDetour": {
    "protocol": "http",
    "settings": {
      "servers": [{
          "address": "127.0.0.1",
          "port": 1234,
          "users": [
            {
              "user": "test user",
              "pass": "test pass"
            }
          ]
      }]
    }
  }
```

6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.

    Client Log File（客户端日志）:
```text
V2Ray v2.28 (One for all) 20170519
An unified platform for anti-censorship.
Main: failed to read config file: devnet.json > Ext|Tools|Conf|IO: failed to parse json config > Tools|Conf: failed to parse outbound config > Tools|Conf: unknown config id: http
```

**Comment by DarienRaymond** [comment]
不支持，暂时没有计划，如果你有需要的话，请在 https://github.com/v2ray/planning 发一个 issue。

**Comment by flyxl** [comment]
我提交了一个pr用来支持http outbound，不过在我的实现里面，要求http proxy server支持HTTP协议的CONNECT方法，需要使用http outbound功能的可以等pr合并或者fork我的分支自己编译
pr：[https://github.com/v2ray/v2ray-core/pull/1813](https://github.com/v2ray/v2ray-core/pull/1813)
分支地址：[https://github.com/flyxl/v2ray-core](https://github.com/flyxl/v2ray-core)
