### ISSUE TITLE
对于windows客户端的v2ray版本，建议加入两个一键开启和关闭后台启动脚本

### ISSUE THREAD

**Issue by robotneo** [v2ray/v2ray-core#452]
# start_v2ray.bat

@echo off
rem 2017/4/23 编写
rem 启动v2ray程序脚本
rem %~d0：获取当前盘符
rem %~dp0：获取当前盘符和路径
rem %~sdp0：当前盘符和路径文件名格式
rem %~f0：当前批处理的全路径
rem %cd%：当期CMD默认目录

title v2ray启动程序
color 0a
start "v2ray" "%~dp0\wv2ray.exe"
rem 查找进程
rem tasklist|findstr "wv2ray.exe"
tasklist /fi "imagename eq wv2ray.exe"
echo.
echo.
echo 已启动v2ray程序
echo.
pause

# stop_v2ray.bat

@echo off
rem 2017/4/23 编写
rem 关闭wv2ray的批处理命令。
rem stop

title v2ray退出程序
color 0a
rem 查找完整进程名
echo.
tasklist|findstr "wv2ray.exe"
echo.
taskkill /f /im wv2ray.exe
rem if "%errorlevel%"==0
echo.
IF ERRORLEVEL 1 goto 1
IF ERRORLEVEL 0 goto 0
Rem 上面的两行不可交换位置，否则失败了也显示成功。
:0
echo 命令执行成功,已关闭v2ray程序！
Rem 程序执行完毕跳至标题exit处退出
goto exit
:1
echo 命令执行失败,该进程不存在或当前不在运行状态！
Rem 程序执行完毕跳至标题exit处退出
goto exit
:exit
echo.
pause

**Comment by robotneo** [comment]
对于windows客户端的v2ray版本，建议加入两个一键开启和关闭后台启动脚本

**Comment by DarienRaymond** [comment]
这些功能应该是客户端来做的，不属于core的职责。

**Comment by huitc** [comment]
你能更新一下吗？@robotneo @DarienRaymond
