### ISSUE TITLE
v2ray服务启动问题

### ISSUE THREAD

**Issue by dcliubing** [v2ray/v2ray-core#457]
运行在小米mini路由器上面，潘多拉固件，

通过./go.sh --version v2.28 --local /path/to/v2ray.zip以上命令本地安装的，可以运行，但是服务无法启动，每次都需要在bash里手动运行./v2ray

请问如何启动，添加到init.d里也不行。

**Comment by wtlusvm** [comment]
[启动项](http://192.168.1.1/cgi-bin/luci/admin/system/startup)里，下面有个本地启动脚本，加进去就行
