### ISSUE TITLE
请教一个V2Ray中protobuf的问题

### ISSUE THREAD

**Issue by ToutyRater** [v2ray/v2ray-core#459]
最近有做一个v2ray的套壳客户端的想法，打算用protobuf，于是找相关资料学习了一下，目前基本会用。但是在看 v2ra y中的 proto 文件时遇到一些不解的地方。
这里 https://github.com/v2ray/v2ray-core/blob/master/config.proto#L20 的 Config message 就是配置文件了，inbound、outbound 和 transport 最不理解，应该是对应了 JSON 配置中的 inbound(inboudDetour)、outbound(outboundDetour) 和 transport，因此我猜测 app 字段应该包含了 JSON 配置中的 log、dns 和 routing。我的困惑是 app 的类型为 TypedMessage(https://github.com/v2ray/v2ray-core/blob/master/common/serial/typed_message.proto#L10 )，而 TypedMessage 这个消息的字段只有 string 类型的 type 和 bytes 类型的 value，而不是我认为的 log、dns 和 routing 这三个。不止是 app，还有 InboundHandlerConfig(https://github.com/v2ray/v2ray-core/blob/master/app/proxyman/config.proto#L64) 当中的 receiver_settings 和 proxy_settings，按照我的理解 receiver_settings 的类型应该是 ReceiverConfig合理。然后我搜索一下，许多字段都是了 TypedMessage 类型，比如 https://github.com/v2ray/v2ray-core/blob/master/transport/internet/config.proto#L35, https://github.com/v2ray/v2ray-core/blob/master/transport/internet/kcp/config.proto#L53, https://github.com/v2ray/v2ray-core/blob/master/common/protocol/user.proto#L17 等等。能不能指出我上面的理解有什么问题，还有解说一下 TypedMessage  这个消息在 v2ray 的配置中的具体作用

**Comment by DarienRaymond** [comment]
V2Ray 的配置中使用这个 TypedMessage 来提供扩展性，所有的具体配置都可以序列化成 TypedMessage，然后传给 V2Ray。之前再增加新的配置项，主 protobuf 不用修改就直接可用。

TypedMessage 的序列化方法在[这里](https://github.com/v2ray/v2ray-core/blob/master/common/serial/typed_message.go#L10)，用的是 protobuf 的 API，在其它语言中实现一遍并不复杂。

然后参数的传递详见测试代码，比如c[这个](https://github.com/v2ray/v2ray-core/blob/master/common/serial/typed_message.go#L10)。

**Comment by DarienRaymond** [comment]
第二个链接已修复

**Comment by ToutyRater** [comment]
看了一下，还要提高自己的知识水平

**Comment by Mondaydream** [comment]
原来是这样

**Comment by Mondaydream** [comment]
> V2Ray 的配置中使用这个 TypedMessage 来提供扩展性，所有的具体配置都可以序列化成 TypedMessage，然后传给 V2Ray。之前再增加新的配置项，主 protobuf 不用修改就直接可用。
> 
> TypedMessage 的序列化方法在[这里](https://github.com/v2ray/v2ray-core/blob/master/common/serial/typed_message.go#L10)，用的是 protobuf 的 API，在其它语言中实现一遍并不复杂。
> 
> 然后参数的传递详见测试代码，比如[这个](https://github.com/v2ray/v2ray-core/blob/master/testing/scenarios/vmess_test.go#L41)。

可以咨询一下 这样做的好处 是什么吗?
