### ISSUE TITLE
v2ray的客户端配置文件里只设置了localhost，如何只使用本机的DNS，而非使用服务器DNS

### ISSUE THREAD

**Issue by zdm2008** [v2ray/v2ray-core#466]
我server端的配置文件里没有配置DNS，但是在客户端里配置了DNS代码如下：
  "dns": {
    "servers": [
      "localhost"
    ]
  }

现在我的问题是只想让客户使用本机的DNS，例如被google污染，那就不能上google（该应用不是用来翻墙的）

**Comment by BenhoNNNN** [comment]
如果客户端配置文件里DNS功能只设置了localhost的话，那就是用你本机设置的DNS服务器来解析。效果等于没开DNS功能，如果你在墙内的话，一定被污染。

**Comment by wtlusvm** [comment]
是的，这样配置写上去，客户端使用的就是本机IP地址。

**Comment by zdm2008** [comment]
可实际效果并不是你（wtlusvm）说的这样，按这个配置应该是上不了谷歌的，因为本地有DNS污染，可是我的这个配置却能上谷歌。

**Comment by q158073378252010** [comment]
@Towdium 一个这玩意还要来秀一下？
