### ISSUE TITLE
win10客户端，电脑睡眠后更换了本地网络重新打开，v2ray需要重启才能够正常工作。

### ISSUE THREAD

**Issue by Bob-cheng** [v2ray/v2ray-core#469]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
---2.33.1 （服务端版本相同）

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
---之前电脑使用正常，电脑睡眠后，更换有线网络为另外的wifi网络，客户端工作异常，重启客户端后正常。电脑为win10最新版。
---使用Chrome代理到V2ray本地端口上外网（Google、gmail等不能访问）
---使用dropbox代理到本地端口进行文件同步

3)  你看到的不正常的现象是什么？
    What did you see?
---无法加载Google等网页
---dropbox无法同步

4)  你期待看到的正确表现是怎样的？
    What's your expectation?
---网页正确加载
---dropbox正确同步

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).
---客户端和服务端都是下载时的默认配置，除了ip和uuid没有其他修改。

6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.
---服务端没有错误报告，只有启动v2ray的几条数据，表现正常。客户端配置没有要求记录log。 重新启动客户端之后问题解决。问题应该在客户端出现。

**Comment by xiaokangwang** [comment]
这个问题可以被稳定的重现么？

**Comment by Bob-cheng** [comment]
可以，经常发生在睡眠后改变网络再启动之后，尤其是睡眠前用的有线睡眠后用的无线连接的情况。

**Comment by leewi9** [comment]
这个应该是相应的平台的实现工具的问题，而不是v2ray-core的问题

**Comment by liberal-boy** [comment]
经多次测试，v3.6已经没有这个问题，如果确认修复，请关闭issue
