### ISSUE TITLE
不支持TPROXY的路由器是否有可能实现透明代理

### ISSUE THREAD

**Issue by ymoti** [v2ray/v2ray-core#476]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V2.33 - 解压的文件目录显示为v2.33.1

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
在路由器使用socks/VMess，以便局域网所有客户端都可以直接科学上网。

3)  你看到的不正常的现象是什么？
在windows本地运行V2ray可以科学上网，但是在路由器上不行。

个人分析: 

- 在windows本地可以说明服务器端配置没有问题。
- 在配置好dokodemo后，配置iptables时有一条命令返回 ”iptables: No chain/target/match by that name.“
- 经测试发现是因为 “iptables -t mangle -A V2RAY -p udp --dport 53 -j TPROXY --on-port 1053 --tproxy-mark 0x01/0x01”导致。
- 做了大量测试后，发现貌似是因为Merlin的路由器虽然有TPROXY support，但是固件内并没有带这个功能所以命令没有成功执行，并最终导致udp透明代理失败而无法科学上网。(可能有误！)
- 路由器固件为Xwrt-Vortex的R7000, 380.66_2

4)  你期待看到的正确表现是怎样的？
是否有其他可以实现透明代理并得到正确的DNS解析地址? 在Windows客户端上使用SwitchyOmega通过路由器可以科学上网，说明TCP部分的代理已经没有问题。

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
客户端配置文件）:

```
{
  "port": 5000,
  "log": {
    "access": ""
  },
  "inbound": {
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "ip": "127.0.0.1"
    }
  },

  "inboundDetour": [
    {
      "protocol": "dokodemo-door",
      "port": 1053,
      "listen": "127.0.0.1",
      "settings": {
        "address": "8.8.8.8",
        "port": 53,
        "network": "udp",
        "timeout": 0
      }
    }
  ],

  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "1.1.1.1",
          "port": 11111,
          "users": [
            {
              "id": "1111-11111-1111",
              "alterId": 11
           }
          ]
        }
      ]
    },
    "tag": "v2ray"

  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],

  "routing": {
    "strategy": "rules",
    "settings": {

      "rules": [

        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        }
      ]
    }
  }
}
```

6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

下面是TPROXY的错误分析:
```
admin@R7000-307A:/tmp/home/root# iptables -t mangle -N V2RAY
admin@R7000-307A:/tmp/home/root# iptables -t mangle -A V2RAY -p udp --dport 53 -j TPROXY --on-port 1053 --tproxy-mark 0x01/0x01
iptables: No chain/target/match by that name.
admin@R7000-307A:/tmp/home/root# iptables -t mangle -nvL
Chain PREROUTING (policy ACCEPT 184 packets, 19624 bytes)
 pkts bytes target     prot opt in     out     source               destination                                                                              

Chain INPUT (policy ACCEPT 148 packets, 16898 bytes)
 pkts bytes target     prot opt in     out     source               destination                                                                              

Chain FORWARD (policy ACCEPT 36 packets, 2726 bytes)
 pkts bytes target     prot opt in     out     source               destination                                                                              

Chain OUTPUT (policy ACCEPT 138 packets, 40204 bytes)
 pkts bytes target     prot opt in     out     source               destination                                                                              

Chain POSTROUTING (policy ACCEPT 174 packets, 42930 bytes)
 pkts bytes target     prot opt in     out     source               destination                                                                              

Chain V2RAY (0 references)
 pkts bytes target     prot opt in     out     source               destination
```

**Comment by supppig** [comment]
关注这个问题。另外，我也遇到大概类似的问题，inboundDetour--dokodemo-door里面映射了一个8.8.8.8的dns，直接用dig abc.com @127.0.0.1 -p端口 可以成功返回数据，但是用tproxy把53端口的数据转发，本地client都不能显示收到数据。我再慢慢排查下这个问题。
最希望的解决方式是，当dokodemo-door指定了远程IP，"followRedirect": false的时候可以直接用REDIRECT ---to-port转发。

如果能专门开发一种协议，直接远端解析DNS，那是最好不过了。我怕有大量连接的时候，mux设置过小会造成dns解析堵塞。。。

**Comment by kdrx** [comment]
try iptables -t mangle -A V2RAY -p udp --dport 53 -j TPROXY --on-port 1053 --tproxy-mark 0x02/0x02

**Comment by ymoti** [comment]
The 0x02/0x02 does not work. 

I didn't try myself but I read several articles that the Merlin firmware does not build the TPROXY feature, it needs a custom build which basically not possible to me for now.

**Comment by kdrx** [comment]
OK, if Merlin haven't a buildin tproxy mod, you can just only cross compile that module and copy the tproxy.ko file to you router jffs directory, then dynamic loading it with insmod command.

**Comment by luolufang** [comment]
目前为止在梅林路由器上不好弄，基本都没tproxy模块。

2017年7月10日 14:23，"kdrx" <notifications@github.com>写道：

**Comment by yangchuansheng** [comment]
可以另辟蹊径，有一个工具叫badvpn，可以将socks代理伪装成vpn，然后通过路由表的形式来实现智能分流，具体参考我的博客：http://www.yangcs.net/posts/11b0e2ac/#more
但目前还没在梅林固件上编译过badvpn，感兴趣的可以尝试一下

**Comment by paway** [comment]
Guys, the following might be a solution.
- local subnet 192.168.0.0/24
- on router dokodemo-door listening on port 12345
- iptables mark udp packages which need redirect to and fetch response. --- our special dokodemo-door save the day
this is how [BadVPN'way](https://github.com/ambrop72/badvpn/wiki/Tun2socks#udp-forwarding) doing udp forwarding. another `badvpn-udpgw` has to run server. And you have to compile Badvpn for a linux router. So it's not a easy thing.

**Comment by ymoti** [comment]
谢谢大家的回复和支持。最后我还是放弃了一定要实现UDP转发。曾经想过把VPS倒腾下，用来编译TPROXY.KO，但是实在是没有精力了...

最后用的就是常用的方法，虽然不算是完全透明代理，但是基本上也比较省心了吧。把方法写出来希望能够利益后来者吧。

我的路由器是网件的R6900，刷过梅林，最后决定用Advanced Tomato了。(后来发现这固件自带webservice，才发现实在是省了大事了)。

方法就是在路由器端运行v2ray, inbound用的是sock5，outbound用的vess。 VPS那边inbound用的是vmess。这些都是普通的设置，没有什么特别的。

上面UDP转发不支持最后用的是通过PAC文件搞定的。我原本需要透明代理的原因是因为手机没法像chrome那边可以用SwitchyOmega。但是后来发现IOS支持PAC文件，然后可以在PAC文件里把网络重定向到路由器上跑的v2ray的端口，问题就解决了。

补充几点:
1. PAC的介绍可以看[这里](http://tyr.gift/pac-proxy.html)，跳过其他部分直接看PAC就可以了。
2. IE据说是支持PAC的，之前看网上说不支持。 我还在测试中。
3. PAC需要放到网络中，不能是本地链接。所以上面说的Tomato自带webservice派上大用场了。直接启动，然后把PAC文件放上去，然后在IOS里指定路径就可以了。
4. Tomato自带webservice默认路径为 /www，这个目录是不可写的。可以把/www下所有文件拷贝到/jffs/www, 然后把PAC文件也上传到那个目录去就可以了。在手机里指定http://<你的路由器IP>:<web服务端口>/<pac文件名>。比如http://192.168.1.1: 81/proxy.pac.

**Comment by ymoti** [comment]
这个方案自己评估了下优缺点:
电脑: 目前只有chrome可以科学上网。如果有其他用到网络的软件，又不支持sock5的话，就没有办法了。
手机: 除了需要在每台设备都做下设置以外，没有其他问题。

基本上我需要翻墙的只有手机和在电脑上上网查些资料，所以这样对了来说就够了。各位网友请各取所需，希望我的方法能给大家带来一些启发。

**Comment by ymoti** [comment]
@paway I didn't try Badvpn, however I suspect it will also need the TPROXY support which is not available in the firmware of my router.

Neither Merlin nor Tomato come with TPROXY feature.

**Comment by wtlusvm** [comment]
@ymoti 
你如果不怕麻烦的话可以再稍微捯饬捯饬：

1. 首先参照[这里](https://cokebar.info/archives/962)设置一个 Shadowsocks 透明代理，其中二、2.3节DNS配置个人推荐使用方案2（方便后续配置）

2. 然后需要修改一些东西。首先是 Shadowsocks 的配置文件，server_port字段改成路由器地址（如192.168.1.1），其次在路由器端的V2Ray，只需要将 inbound 改成 Shadowsocks ，监听路由器地址（如192.168.1.1）即可。

3.因为梅林固件无 TPROXY ，所以很尴尬地……没法转发 udp 流量，不过这么一捯饬，自动翻墙倒是实现了。

**Comment by ymoti** [comment]
最后通过使用TCP查询DNS加上Dokodemo-door，貌似搞定了这个问题 - 貌似DNS拿到正确地址了(不确定)，但是还是没有办法连接。

这个issue closed掉。再另外开新的issue.

**Comment by ymoti** [comment]
下面是dig时v2ray的日志，感觉是可以了，但是不太确定拿到的DNS是不是正确的。

2017/08/28 12:40:48 [Info]Transport|Internet|TCP: listening TCP on 0.0.0.0:5000
2017/08/28 12:40:48 [Info]Transport|Internet|TCP: listening TCP on 0.0.0.0:5353
2017/08/28 12:40:48 [Warning]Core: V2Ray started
2017/08/28 12:41:03 [Debug]Proxy|Dokodemo: processing connection from: 127.0.0.1:25411
2017/08/28 12:41:03 [Info]App|Dispatcher|Default: default route for tcp:8.8.8.8:53
2017/08/28 12:41:03 [Info]Transport|Internet|TCP: dailing TCP to tcp: x.x.x.x:xx
2017/08/28 12:41:03 [Debug]Proxy|Dokodemo: processing connection from: 127.0.0.1:25967
2017/08/28 12:41:03 [Info]App|Dispatcher|Default: default route for tcp:8.8.8.8:53
2017/08/28 12:41:03 [Info]Transport|Internet|TCP: dailing TCP to tcp: x.x.x.x:xx
2017/08/28 12:41:03 [Info]Proxy|VMess|Outbound: tunneling request to tcp:8.8.8.8:53 via tcp:23.105.216.24:22868
2017/08/28 12:41:03 [Info]Proxy|VMess|Outbound: tunneling request to tcp:8.8.8.8:53 via tcp:23.105.216.24:22868

**Comment by ymoti** [comment]
为避免误导后来者，说明一下这个方案最终并没有成功，DNS查询不能通过TCP转发 - 直接用TCP查询应该是可以，但是通过TCP转发查询应该是不行的。

**Comment by ymoti** [comment]
最后在自更下。 最后还是自学编译了固件把TPROXY加进固件了... 另外就上面大家给的几个解决办法说下:
1. 只编译模块, 然后insmod应该是不行的 - 我曾经找到tproxy.ko，但是insmod失败。推测是因为内核没有enable tproxy （源码支持，但是编译时没有放入）。所以编译固件是必须的。
2. 把ss-tunnel拿过来用应该也是不行(不是100%确定)。 曾经试过这个方案，但是服务器端没有收到数据，推测ss-tunnel本身也是依赖TPROXY。

另外对于使用Broadcom的路由器又想用第三方固件的，分享下个人的经验:
1. Koolshare出的梅林改版固件已经集成SS，TPROXY应该已经可以用了 (未确认，已经没有刷回去了)。但是最近估计不是很稳定。
2. AdvancedTomato界面不错也稳定，但是TPROXY需要自己编译...
3. 有人在AdvancedTomato上做了些改动，并且最新版固件提供了TPROXY。我现在其实没有用自己编译的固件，是用他的。看AdvancedTomato项目上，其实很多commit也是来源于他的项目的。
https://bitbucket.org/AndreDVJ/advancedtomato-arm

希望这个能帮助到需要帮助的人。

**Comment by wtlusvm** [comment]
> 把ss-tunnel拿过来用应该也是不行(不是100%确定)。 曾经试过这个方案，但是服务器端没有收到数据，推测ss-tunnel本身也是依赖TPROXY。

这个可以100%确定，ss-tunnel 确实是依赖 TPROXY 的。
