### ISSUE TITLE
Enable IP level encryption

### ISSUE THREAD

**Issue by v2ray** [v2ray/v2ray-core#48]
To enable V2Ray for iOS and Android, we need IP level encryption, as Socks protocol is not supported natively in these platforms.

**Comment by cirias** [comment]
iOS可以参考[surge](http://surge.run/manual/)

**Comment by v2ray** [comment]
I don't think this is reasonable. On mobile platforms, V2Ray will still support TCP and UDP only. Packets with other types will pass through as is.
