### ISSUE TITLE
V2Ray 客户端防火墙

### ISSUE THREAD

**Issue by tleydxdy** [v2ray/v2ray-core#481]
V2Ray客户端应该怎么配置防火墙？

**Comment by 1oo1** [comment]
v2ray 没有防火墙这个概念，我猜测你想问的是路由[配置+黑洞协议](https://www.v2ray.com/chapter_02/protocols/blackhole.html)吧

**Comment by tleydxdy** [comment]
不是，我的意思是防火墙要开哪些端口才能跟服务器通信。

**Comment by luolufang** [comment]
根据你配置文件开
使用端口 25000：

默认开启：TCP 25000
 
使用mkcp  协议  额外开启 UDP 25000




luolufang@gmail.com
 
发件人： tleydxdy
发送时间： 2017-07-19 09:58
收件人： v2ray/v2ray-core
抄送： Subscribed
主题： Re: [v2ray/v2ray-core] V2Ray 客户端防火墙 (#481)
不是，我的意思是防火墙要开哪些端口才能跟服务器通信。

**Comment by tleydxdy** [comment]
OK，动态端口就范围内全开是吧，主要是文档里没看到
