### ISSUE TITLE
[Feature Request] Use https://dns.google.com/ as internal DNS resolver

### ISSUE THREAD

**Issue by amtlib-dot-dll** [v2ray/v2ray-core#482]
Current Version: v2.33 from Docker Hub

Since ordinary DNS queries usually results in `permission denied` inside Docker, and might be hijacked by the authority bureaucracies, use results from `https://dns.google.com/resolve?name=example.org&type=AAAA&ramdom_padding=some_meaningless_characters` and `https://dns.google.com/resolve?name=example.org&type=A&ramdom_padding=more_meaningless_characters` would be helpful. Full documentation for this can be found at [here](https://developers.google.com/speed/public-dns/docs/dns-over-https). Now that the internal DNS resolver is embedded inside V2Ray, it is a perfect black box with any modifications applicable.

Thank you very much.

**Comment by DarienRaymond** [comment]
This is tricky like a chicken-egg problem. If not configured properly, it will end up with dead loop on querying DNS for google.com.

However, PR is welcome for HTTP based DNS query. For now, there is no plan to implement it.

**Comment by DarienRaymond** [comment]
If you wish, you may open an issue in https://github.com/v2ray/Planning for long term track of feature requests.
