### ISSUE TITLE
出口可否支持http代理？

### ISSUE THREAD

**Issue by windprog** [v2ray/v2ray-core#484]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
v2.5

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
公司网络无直连，需要通过http代理上网

3)  你看到的不正常的现象是什么？
    What did you see?
无法连接代理服务器

尝试过用[gost](https://github.com/ginuerzh/gost)把http代理转成socks5代理再使用: “socks5传出代理”使用
提示: "unknown Socks version: 71"

4)  你期待看到的正确表现是怎样的？
    What's your expectation?
支持http出口协议，实现二层代理

**Comment by DarienRaymond** [comment]
不支持，暂时没有计划，如果你有需要的话，请在 https://github.com/v2ray/planning 发一个 issue。
