### ISSUE TITLE
Shadowsocks obfs plugin 如何配置？

### ISSUE THREAD

**Issue by gagqgs** [v2ray/v2ray-core#485]
RT，如何配置支持 Shadowsocks obfs plugin？有没有示例配置

另，v2ray 的配置太麻烦了，有一个特别棒的项目 [V2ray-config-gen](https://github.com/htfy96/v2ray-config-gen) 可以直接网页配置，但选项支持不全，官方可参考

**Comment by DarienRaymond** [comment]
1. 使用 [standalone 模式](https://github.com/shadowsocks/simple-obfs#standalone-mode)开启 obfs
1. 在 V2Ray 配置中添加一个 [socks outbound](https://www.v2ray.com/chapter_02/protocols/socks.html)，把这个 outbound 指向 obfs
1. 假设配置中已有一个指向V2Ray服务器的VMess outbound，在这个outbound中添加proxySettings，把tag设为上述socks outbound的tag

**Comment by meng-1024** [comment]
请问，能否详细地描述一下v2ray通过standalone模式使用obfs的配置和操作呢？官方页面中只有 “插件：
通过 Standalone 模式支持 obfs”这么一句描述....
