### ISSUE TITLE
CPU使用率高

### ISSUE THREAD

**Issue by bonly** [v2ray/v2ray-core#487]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
github->master

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
客户端连接上后，后继不作任何操作，服务端空转也会也CPU占用率到99%-100%，一直降不下来

3)  你看到的不正常的现象是什么？
    What did you see?
客户端连接上后，后继不作任何操作，服务端空转也会也CPU占用率到99%-100%，一直降不下来，nice到低级别一样占用高

4)  你期待看到的正确表现是怎样的？
    What's your expectation?
空转时CPU占用率低点，因为此问题已导致vps被服务商停掉

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Server Configuration File（服务器端配置文件）:
```javascript
    // 在这里附上服务器端配置文件
    // Please attach your server configuration file here.
```

    Client Configuration File（客户端配置文件）:
```javascript
    // 在这里附上客户端配置文件
    // Please attach your client configuration file here.
```

6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.

    Server Log File（服务器端日志）:
```
    // 在这里附上服务器端日志
    // Please attach your server log here.
```

    Client Log File（客户端日志）:
```
    // 在这里附上客户端日志
    // Please attach your client log here.
```

**Comment by DarienRaymond** [comment]
没有配置文件的话没办法分析哪里出了问题

**Comment by bonly** [comment]
服务端配置如下:
{
    "log": {
        "access": "/var/log/v2ray/access.log",
        "error": "/var/log/v2ray/error.log",
        "loglevel": "none"
    },
    "inbound": {
        "port": 8088,
        "protocol": "vmess",
        "settings": {
            "clients": [
                {
                    "id": "****-*****-*****-****",
                    "level": 1,
                    "alterId": 11
                }
            ]
        },
        "streamSettings": {
            "network": "kcp"
        },
        "detour": {
            "to": "vmess-detour-890025"
        }
    },
    "outbound": {
        "protocol": "freedom",
        "settings": {}
    },
    "inboundDetour": [
        {
            "protocol": "vmess",
            "port": "10000-11000",
            "tag": "vmess-detour-890025",
            "settings": {},
            "allocate": {
                "strategy": "random",
                "concurrency": 500,
                "refresh": 5
            },
            "streamSettings": {
                "network": "kcp"
            }
        },
        {
            "protocol": "shadowsocks",
            "port": 8387,
            "settings": {
                "method": "aes-256-cfb",
                "password": "****",
                "udp": true,
                "level": 1
            }
        },
	{
	    "protocol": "shadowsocks",	
	    "port":8388,
	    "settings":{
		 "level": 1,
		 "method":"aes-256-cfb",
		 "password": "*****",
		 "udp":true
	    }
	},
	{
	    "protocol":"shadowsocks",
	    "port": 8389,
	    "settings":{	
		"method":"aes-256-cfb",
		"udp":true,
		"password": "****",
		"level":1
	    }	
	}	

    ],
    "outboundDetour": [
        {
            "protocol": "blackhole",
            "settings": {},
            "tag": "blocked"
        }
    ],
    "routing": {
        "strategy": "rules",
        "settings": {
            "rules": [
                {
                    "type": "field",
                    "ip": [
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "203.0.113.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10"
                    ],
                    "outboundTag": "blocked"
                }
            ]
        }
    }
}

**Comment by DarienRaymond** [comment]
你的 concurrency 用了 500, 表示有 500 个端口同时开启，在低端的机器上是会造成 CPU 过高的问题。这个数值一般 10 以下就够用了。
