### ISSUE TITLE
关于https、sniproxy、负载均衡

### ISSUE THREAD

**Issue by wangyi2005** [v2ray/v2ray-core#489]
v2ray 版本2.33，https代理+sniproxy

**1、多个sniproxy随机负载平衡。**
"protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "sniproxy-1", 
          "port": 443, 
          "users": [
            {
              "id": "###############",
              "alterId": 64,
              "security": "none"
            }
          ]
        },
	{
          "address": "sniproxy-2", 
          "port": 443, 
          "users": [
            {
              "id": "################",
              "alterId": 64,
              "security": "none"
            }
          ]
        }

**2、https代理**
"streamSettings": {
      "network": "tcp",
	  "security": "tls",
	  "tlsSettings": {
	    "serverName": "#############.openshiftapps.com",
        "allowInsecure": true
	  },

**3、http伪装**
"tcpSettings": {
	    "header": {
          "type": "http",

**Comment by ldaochen** [comment]
请问下https代理是怎么配置的？？ 文档里只有http代理的配置，可以给个http和https同时监听的配置吗？？

**Comment by wangyi2005** [comment]
不好意思，这里https代理指的是通过http伪装+tls，能利用paas平台作为v2ray服务端。

**Comment by 523860169** [comment]
我其实想利用v2ray实现，443端口走sniproxy的ip(219.76.4.xx这种)，80端口走其他代理的方式，但好像v2ray不支持sniproxy ip

**Comment by wangyi2005** [comment]
可以的，
https://github.com/wangyi2005/v2ray/issues

**Comment by 523860169** [comment]
是这个吗？https://github.com/wangyi2005/v2ray/issues/4
可以改一下设置成code吗，没有缩进看着很乱

**Comment by 523860169** [comment]
这个是不是还是要用到Openshift，不能只用sniproxy 的ip吗

**Comment by wangyi2005** [comment]
如果vps的话，要有一个域名和证书。

**Comment by 523860169** [comment]
我现在是路由器上用iptables规则，设置443端口nat为sniproxy的ip，80端口指向ss的透明代理。所以想用v2ray实现类似效果。但是好像不行啊
```
ipset flush proxylist
ipset create proxylist hash:ip
iptables -t nat -I PREROUTING -p tcp -m set --match-set proxylist dst -m multiport --dport 1:442,444:65532 -j REDIRECT --to-port 1080
iptables -t nat -I PREROUTING -p udp -m set --match-set proxylist dst -m multiport --dport 1:442,444:65532 -j REDIRECT --to-port 1080
iptables -t nat -I OUTPUT -p tcp -m set --match-set proxylist dst -m multiport --dport 1:442,444:65532 -j REDIRECT --to-port 1080
iptables -t nat -I OUTPUT -p udp -m set --match-set proxylist dst -m multiport --dport 1:442,444:65532 -j REDIRECT --to-port 1080
iptables -t nat -I PREROUTING -p tcp -m set --match-set proxylist dst --dport 443 -j DNAT --to ***.***.***.***
iptables -t nat -I PREROUTING -p udp -m set --match-set proxylist dst --dport 443 -j DNAT --to ***.***.***.***
iptables -t nat -I OUTPUT -p tcp -m set --match-set proxylist dst --dport 443 -j DNAT --to ***.***.***.***
iptables -t nat -I OUTPUT -p udp -m set --match-set proxylist dst --dport 443 -j DNAT --to ***.***.***.***
```

**Comment by wangyi2005** [comment]
v2ray freedom
{
  "domainStrategy": "AsIs",
  "timeout": 0,
  "redirect": "sniproxy-ip:443"
}
是可以的，但是并发连接太多，非常不稳定。

**Comment by 523860169** [comment]
弄好了，谢谢
还有我想主用ss，辅用sni，但是找到的教程都是主用vmess，辅用ss，不知道ss是不是不能设置在outbound，只能设置在outboundDetour，我这样设置，结果ss不行
```
  "outbound": {
    "protocol": "shadowsocks",
    "settings": {
      "servers": [
        {
          "email": "love@v2ray.com",
          "address": "********",
          "port": 14295,
          "method": "aes-256-cfb",
          "password": "de7558",
          "ota": false
        }
      ]
    },
    "mux": {
      "enabled": true,
      "concurrency": 8
    }
  },
```

**Comment by wangyi2005** [comment]
应该是可以的。

**Comment by 523860169** [comment]
不行
