### ISSUE TITLE
如何同时配置socks,http和https代理

### ISSUE THREAD

**Issue by ldaochen** [v2ray/v2ray-core#490]
用的版本是2.33.1  系统是Mac OSX
客户端配置了socks和http代理，还想同时加上https代理。请教下https怎么配置？

客户端配置
{
  "log": {
    "loglevel": "warning"
  },
  "inbound": {
    "port": 15000,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    }
  },

   "inboundDetour": [{
        "protocol": "http",
        "port": 15001,
        "settings": {}
    }],
  
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "xx.xx.xx.xxx",
          "port": 10000,
          "users": [
            {
              "id": "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx",
              "alterId": 64,
              "security": "auto"
            }
          ]
        }
      ]
    },
    "mux": {
      "enabled": true
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": "1-52",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "54-79",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "81-442",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "444-65535",
          "outboundTag": "direct"
        },
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        }
      ]
    }
  }
}

服务端配置如下:

{
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 10000,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
          "level": 0,
          "alterId": 64
        }
      ]
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {   
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],  
          "outboundTag": "blocked"
        }   
      ]   
    }   
  }
}

**Comment by oing9179** [comment]
我假定你想在服务器端只运行一个 v2ray 实例的情况下，同时接受多种入站协议，这样的话需要修改服务器端的 v2ray 配置文件。
请参考 [配置文件格式 - v2ray.com](https://www.v2ray.com/chapter_02/01_overview.html)，善用 `inboundDetour`。

**Comment by nicholascw** [comment]
1. RTFM.

**Comment by nicholascw** [comment]
V2Ray目前应该是不支持HTTPS代理的，以及个人认为在本地多跑一个HTTPS纯属浪费计算资源和通信效率。如果仍要在本地单独开一个HTTPS请用其他工具前置。

**Comment by DarienRaymond** [comment]
@nicholascw 支持的，HTTP + TLS 即可

**Comment by caster8013** [comment]
> @nicholascw 支持的，HTTP + TLS 即可

你好！可以更详细一点吗？
