### ISSUE TITLE
Can not connect via WebSocket

### ISSUE THREAD

**Issue by S-Tsunemori** [v2ray/v2ray-core#491]
I have setup V2Ray using VMess & TLS, mKCP, today I'm trying to get WebSocket to work without success.

Here's part of my v2ray (server) config:
```json
      "port": 9997,
      "listen": "127.0.0.1",
      "protocol": "vmess",
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/websocket/"
        }
      }
```
and part of my v2ray (client) config:
```json
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "<my-site>.com",
          "port": 443,
          "users": [
            {
              "id": "***",
              "alterId": 64,
              "security": "aes-128-gcm"
            }
          ]
        }
      ]
    },
    "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/websocket/"
        }
    }
```
and part of my nginx config (I have a working HTTPS site running)
```nginx
        location /websocket/ {
                proxy_pass http://127.0.0.1:9997;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }
```

I can acces my HTTPS site normally so nginx is running fine, I can access v2ray via other ports running on the same server (in the same config file) without problem, but I failed to get WebSocket to work.

When I try to use VMess-WebSocket, I see no log on the server side (why?) but I do see logs on cilent side:
```log
2017/07/23 11:32:13 [Warning]Core: V2Ray started
2017/07/23 11:32:44 [Info]Proxy|Shadowsocks: tunnelling request to tcp:www.google.com:443
2017/07/23 11:32:44 [Info]Transport|Internet|WebSocket: creating connection to tcp:<my-site>.com:443
2017/07/23 11:32:45 [Info]Transport|Internet|WebSocket: creating connection to tcp:<my-site>.com:443
2017/07/23 11:32:45 [Info]Transport|Internet|WebSocket: creating connection to tcp:<my-site>.com:443
2017/07/23 11:32:46 [Info]Transport|Internet|WebSocket: creating connection to tcp:<my-site>.com:443
2017/07/23 11:32:47 [Info]Transport|Internet|WebSocket: creating connection to tcp:<my-site>.com:443
2017/07/23 11:32:48 [Warning]App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: failed to ind an available destination > Retry:[Transport|Internet|WebSocket: failed to dial WebSocket] > Retry: all retry attempts failed
```

When I access ```https://<my-site>.com/websocket/``` in my Web Browser, I see a line says "Bad Request" in the browser, and now I can see something in v2ray server access log (level: debug):
```log
[Info]Transport|Internet|WebSocket: failed to convert to WebSocket connection > websocket: not a websocket handshake: 'websocket' token not found in 'Upgrade' header
```

I'm running out of ideas, what am I doing wrong?
(v2ray v2.33.1 nginx  1.10.3)

**Comment by DarienRaymond** [comment]
Does Nginx log anything in both cases?

**Comment by oing9179** [comment]
@S-Tsunemori Reply [#1](https://github.com/v2ray/v2ray-core/issues/491#issue-244884727)

Since you are asking v2ray to connect your server via port `443`, that means you have to tell v2ray that you would like to use TLS Connection.
Edit your original client side `config.json` from:

```json
"streamSettings": {
    "network": "ws",
    "wsSettings": {
        "path": "/websocket/"
    }
}
```

to:

```javascript
"streamSettings": {
    "network": "ws",
    "wsSettings": {
        "path": "/websocket/"
    },
    "security": "tls", // Required, tell v2ray to use TLS Connection.
    "tlsSettings": {
        "serverName": "<my-site>.com", // Required, Nginx needs this to redirect your connection to a proper `port number`.
        "allowInsecure": false // Optional, `true` if you don't care about MITM Attack.
    }
}
```

Reply this thread if any further quesitons.

**Comment by S-Tsunemori** [comment]
@oing9179 

Works like a charm, thank you.

**Comment by oing9179** [comment]
@S-Tsunemori Reply [#4](https://github.com/v2ray/v2ray-core/issues/491#issuecomment-317948662)

You're welcome bro.

**Comment by oing9179** [comment]
@S-Tsunemori Reply [#4](https://github.com/v2ray/v2ray-core/issues/491#issuecomment-317948662)

Also, I would like to recommend you to change the title of this thread to something like "WebSocket over TLS behind Nginx", and this would help others who suffering the same problem can find this thread easily.

**Comment by shijiezhou1** [comment]
> ```nginx
>   location /websocket/ {
>                 proxy_pass http://127.0.0.1:9997;
>                 proxy_http_version 1.1;
>                 proxy_set_header Upgrade $http_upgrade;
>                 proxy_set_header Connection "upgrade";
>         }
> ```

For this part I think only need if you open the port 9997
