### ISSUE TITLE
chinaip 和 chinasites 集合是怎么生成的?

### ISSUE THREAD

**Issue by ldaochen** [v2ray/v2ray-core#493]
我在配置文件中设置了chinaip 和 chinasites都是direct
但是访问新浪微博我发现走了代理服务器。 是因为weibo.com没有加入到chinasites或chinaip中吗？
还是chinaip和chinasites数据太旧了。
客户端是最新的2.33.1 mac版
客户端配置：
{
  "log": {
    "loglevel": "warning"
  },  
  "inbound": {
    "port": 15000,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    }   
  },  

   "inboundDetour": [{
        "protocol": "http",
        "port": 15001,
        "settings": {}
    }], 
 "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {   
          "address": "",
          "port": 10000,
          "users": [
            {   
              "id": "",
              "alterId": 64, 
              "security": "aes-128-gcm"
            }
          ]
        }
      ]
    },
    "mux": {
      "enabled": true
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
 ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
"routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
       "outboundTag": "direct"
        }
      ]
    }
  }
}

**Comment by ldaochen** [comment]
我知道了chinaip 怎么生成的，geoip_gen.go从http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest获取ip信息， 但是chinasites是怎么生成的？？

**Comment by serika00** [comment]
chinasites还是在ext包中生成的：https://github.com/v2ray/ext/blob/master/tools/conf/router_chinasites.go

如果使用V2Ray的路由规则的话，访问的时候一定都先走本地代理，然后再决定是发到远程代理还是通过本地网络做请求，所以在浏览器里看到全部都会走127.0.0.1:15000

**Comment by ldaochen** [comment]
好奇我的conf目录怎么没有router_chinasites.go文件??
如图：
<img width="289" alt="qq20170724-053239 2x" src="https://user-images.githubusercontent.com/4057415/28503068-d2c12304-7031-11e7-9dd2-27371b2cd336.png">

在go build之前，我已经go get github.com/v2ray/ext包了。 


还有一个问题，chinaip集合是什么时候才会被生成？？每次build时候吗？ 还是手动的编译geoip_gen.go运行才能生成？

**Comment by serika00** [comment]
如果我没看漏代码的话，这个chinaip列表应该是手动生成的，cd到目录后`go run geoip_gen.go`，或者清真一点`go generate tools/geoip/geoip.go`

**Comment by DarienRaymond** [comment]
chinaip 是手动更新的，大约每3个月更新一次。

**Comment by ldaochen** [comment]
router_chinasites.go 这个会自动导入到项目中吗？ 我go get了ext，但是tools/conf中没有

**Comment by DarienRaymond** [comment]
会的，没有的话说明你 go get 用错了

**Comment by ldaochen** [comment]
我重新go get试试看

**Comment by mikemikemikecai** [comment]
如果要更新chinaip chinasite必需要执行go工程吗？在已经编译的linux客户端内怎么重新chinasite呢？

**Comment by fbigun** [comment]
现在换成了  https://dev.maxmind.com/geoip/geoip2/geolite2/  这个了吧
