### ISSUE TITLE
程序BUG: "JSON is not loadable." JSON配置的解析函数没有注册。 

### ISSUE THREAD

**Issue by ldaochen** [v2ray/v2ray-core#494]
go get  github.com/v2ray/v2ray-core下载代码安装包
进入main目录，go build 命令生成main执行文件，编写config.json配置文件，
然后执行main, 出错如下：
ldc ~/Desktop/webapp/src/v2ray-core-2.33.1/main$./main 
V2Ray 2.34 (One for all) Custom
An unified platform for anti-censorship.
Main: failed to read config file: /Users/ldc/Desktop/webapp/src/v2ray-core-2.33.1/main/config.json > Core: JSON is not loadable.
经过分析，是tools/conf目录下conf.go中init函数没有执行(原因是main目录下 config_json.go 没有执行)。
func init() {
	core.RegisterConfigLoader(core.ConfigFormat_JSON, func(input io.Reader) (*core.Config, error) {
		return jsonconf.LoadJSONConfig(input)
	})
}

将config_json.go文件中import _ "v2ray.com/core/tools/conf" 复制到main.go中就能正确运行了。

**Comment by serika00** [comment]
```
go build -tags json .
```
调试的时候可以这样加个参数直接build。

这个项目的Release版本似乎是用ext包里的vbuild来完成，不是这样直接go build的。

**Comment by DarienRaymond** [comment]
楼上描述得非常准确。
