### ISSUE TITLE
真奇怪！换了台电脑就不能用了。。

### ISSUE THREAD

**Issue by walasix** [v2ray/v2ray-core#496]
在老电脑上使用没问题，换了台电脑之后（使用相同的网络环境，相同的v2ray版本，相同的浏览器，相同的浏览器代理插件），就打不开任何网页了。小白表示很懵B。求大神神助！~

**Comment by qingfengshi** [comment]
是不是装了迅雷之类的会改变系统网络设置的软件，我之前遇到过类似的问题，卸载了迅雷就可以了。

2017-07-26 16:26 GMT+08:00 walasix <notifications@github.com>:

**Comment by cnperi** [comment]
时间

**Comment by walasix** [comment]
@qingfengshi 谢谢~没有装迅雷啊，不过有爱奇艺，是因为它？我卸载掉试试

**Comment by walasix** [comment]
@cnperi 谢谢~之前电脑的时间确实有问题，不过我校准以后还是不行啊？请问该怎么操作？

**Comment by cnperi** [comment]
@walasix 如果时间校正没问题的话，那应该就是配置上出了问题了。建议在 command 界面下，测试一下配置。/.../v2ray --test --config=/.../config.json
看输出再确认问题所在点。

**Comment by walasix** [comment]
@cnperi 谢谢大神~不过我是从老电脑上把V2RAY文件夹原封不动拷贝过来的。。另外，没明白怎么测试啊？/.../v2ray --test --config=/.../config.json 按照这个输入还是需要把省略号更改成什么呢？

**Comment by cnperi** [comment]
@walasix 原封不动？文件夹位置都没有换吗？那看看是不是配置里面关于 log 的配置。
所谓测试，就是进入命令行模式，进入 v2ray 的文件夹， 然后输入命令 v2ray --test --config=“配置文件所在位置”

**Comment by oing9179** [comment]
@pool360 Reply [#1](https://github.com/v2ray/v2ray-core/issues/500#issue-246085607)

1. 请把客户端和服务器端配置文件贴出来
2. 把客户端和服务器端的日志贴出来

**Comment by walasix** [comment]
@cnperi 是的，文件夹位置没换。而且即便我在新电脑上重新下载V2RAY，重新解压使用，还是不行。
关于测试，我输入命令 v2ray --test --config=“D:\Freedom\v2ray-windows-64-2.33\v2ray-v2.33-windows-64\config.json”，提示“不是内部或外部命令，也不是可运行的程序或批处理文件”。是什么问题呢？

**Comment by walasix** [comment]
@oing9179 好的，不好意思，我正在研究怎么找到日志和配置文件。。

**Comment by walasix** [comment]
还是没搞明白怎么找到日志和配置文件，哪位大佬可以告诉我在哪儿。。
另外，发现虽然翻不出去，但是国内网站却能打开，而且IP地址显示也是本身IP。像是绕开了V2RAY一样

**Comment by DarienRaymond** [comment]
猜测你用的官方服务器，而官方服务器近期不稳定。请自己架设服务器或使用第三方服务。
