### ISSUE TITLE
WPS下V2Ray与SSR不能共用？

### ISSUE THREAD

**Issue by flyingwhalefall** [v2ray/v2ray-core#499]
在搬瓦工上装了centos 7系统，并成功安装v2ray，而且也顺利翻墙了。
接下来我在搬瓦工上继续安装了shadowsocksR，也成功翻墙了。
这时突然发现v2ray无法正常工作了，而我在X SHELL连接vps后发现v2ray 及SSR均是running状态，并无问题。
而且SSR的端口和 v2ray端口设置也不一样，
请问是什么原因导致的呢
谢谢

[root /]# service v2ray status
● v2ray.service - V2Ray Service
   Loaded: loaded (/usr/lib/systemd/system/v2ray.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2017-07-26 14:22:51 EDT; 43min ago
 Main PID: 32077 (v2ray)
   CGroup: /system.slice/v2ray.service
           └─32077 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json

Jul 26 14:22:51 host.localdomain systemd[1]: Started V2Ray Service.
Jul 26 14:22:51 host.localdomain systemd[1]: Starting V2Ray Service...
Jul 26 14:22:51 host.localdomain v2ray[32077]: V2Ray v2.33 (One for all) 20170609
Jul 26 14:22:51 host.localdomain v2ray[32077]: An unified platform for anti-censorship.
Jul 26 14:22:51 host.localdomain v2ray[32077]: 2017/07/26 14:22:51 [Debug]App|Proxyman|Inbound: creating tcp worker on 0.0.0.0:19913
Jul 26 14:22:51 host.localdomain v2ray[32077]: 2017/07/26 14:22:51 [Info]Transport|Internet|TCP: listening TCP on 0.0.0.0:19913

/etc/init.d/functions: line 63: /dev/stderr: Device or resource busyRedirecting to /bin/systemctl status  v2ray.service

[root /]# service shadowsocks status
ShadowsocksR (pid 31987) is running...

/etc/init.d/functions: line 63: /dev/stderr: Device or resource busy

**Comment by Fengzhiying2017** [comment]
除了对外监听的端口不一样，监听的本地端口1080也改成不一样试试

**Comment by 1984women** [comment]
我两个软件没有同时开，估计跟对外监听端口关系不大。
后来用了最土的办法，把vps 重启了下，恢复正常了，汗
不过现在V2RAY上搭建了SS，正为shadowrocket无法使用烦扰。。

**Comment by Fengzhiying2017** [comment]
我在同一台vps上装了ss libev、ssr和v2ray，都能用shadowsocket连接，你检查一下配置

**Comment by 1984women** [comment]
太感谢您的回复了，您简直是开记者招待会了，哈哈
感谢大神帮忙
现在问题解决。
进入研究mac os上v2ray的客户端研究
另外还要寻找vps上有无一键安装openvpn脚本，为了v2ray升级CENTOS 7，不能一键安装搬瓦工openvpn了。。。
