### ISSUE TITLE
Port negotiation between V2Ray client and server

### ISSUE THREAD

**Issue by v2ray** [v2ray/v2ray-core#50]

**Comment by hashhsah** [comment]
What is meant by "port negotiation"?

**Comment by v2ray** [comment]
Say V2Ray server is working on port 8888. V2Ray client should be able to send a request when it starts, to request another port for communication. V2Ray server then allocate another port (say 9999) for this client to send network traffic. If port 9999 is attacked or blocked, client and server can agree on another port for communication. This process is called 'port negotiation'. 

The original port 8888 is not necessary to be a TCP port. There are other ways for the negotiation. For example, client and server can communicate via emails.

**Comment by hashhsah** [comment]
This feature has become essential to successful circumvention.

One possible protocol inspired by frequency-hopping in radio comms:
- Client and server agree on 10 ports (channels). 
- Packets are sent through a port pseudo-randomly chosen according the current time and an agreed session seed. 
- After every 100kB ~ 1MB data is sent, traffic switches to a new port (hopping).
- Port hopping is always requested by the client by TCP SYN on the next port. Server can verify if the requested port is valid.
- To minimize latency, client can request hopping a little earlier than scheduled, i.e. while traffic is still flowing on the old channel.

This traffic pattern would appear identical to several clients behind a broad-band router (NAT gateway) trying to access the same server with short request/replies.

**Comment by v2ray** [comment]
This feature has been implemented in 1.5. [Doc](https://github.com/v2ray/v2ray.github.io/wiki/%E5%8A%A8%E6%80%81%E7%AB%AF%E5%8F%A3). For any problems when using this feature, please open a separate issue.
