### ISSUE TITLE
v2ray配合proxy SwichyOmega无法翻墙了，怎么解决？

### ISSUE THREAD

**Issue by pool360** [v2ray/v2ray-core#500]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

3)  你看到的不正常的现象是什么？
    What did you see?

4)  你期待看到的正确表现是怎样的？
    What's your expectation?

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).

```
通常我都会把v2ray文件解压至硬盘当中配合SwichyOmega插件，这次却出现无法访问现象，两者都是最新版本的

**Comment by walasix** [comment]
@pool360 你确定是SwichyOmega插件的问题吗？我用的是同样的插件，老电脑没问题，但不知为何另外一台新电脑连不上网

**Comment by pool360** [comment]
不知道怎么解决了

**Comment by oing9179** [comment]
@pool360 Reply [#1](https://github.com/v2ray/v2ray-core/issues/500#issue-246085607)

1. 请把客户端和服务器端配置文件贴出来
2. 把客户端和服务器端的日志贴出来

**Comment by boeing888** [comment]
我也遇到了类似的问题，用一段时间后就会断网，重启v2ray客户端后恢复正常。感觉这个问题出的挺频繁的，不知道是哪里出了问题。

**Comment by q158073378252010** [comment]
运行客户端的是windows系统？
如果是那没必要在chrome 中使用 “SwichyOmega” 来接管代理！
奥秘就是将配置改成下面这样
```
"inbound": {
    "port": 1080,
    "listen": "127.0.0.1",
    "protocol": "http",
    "settings": {
        "timeout": 0
    }

```

**Comment by nicholascw** [comment]
No detailed information provided.
