### ISSUE TITLE
能否为inbounddetour[]增加enable字段？

### ISSUE THREAD

**Issue by hzxswyg** [v2ray/v2ray-core#501]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
2.27

建议为inbounddetour数组下的每一个连接提供一个enable字段，如果指明"enable": false，则表明连接不启用。增加该字段后能更方便的进行多连接多用户的配置。

一点小建议。

**Comment by wtlusvm** [comment]
不启用直接注释掉不就好了
