### ISSUE TITLE
【enhancement 】客户端inbound实现CONNECT方式代理

### ISSUE THREAD

**Issue by kalagxw** [v2ray/v2ray-core#504]
RT

**Comment by netroby** [comment]
http proxy default support CONNECT proxy, you can set inboud to http

**Comment by oing9179** [comment]
@kalagxw Reply [#1](https://github.com/v2ray/v2ray-core/issues/504#issue-246519881)

请参考官方文档 [HTTP - v2ray.com](https://www.v2ray.com/chapter_02/protocols/http.html)。
