### ISSUE TITLE
移动端功能正常，PC端无法正常工作

### ISSUE THREAD

**Issue by fkdhhm** [v2ray/v2ray-core#505]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.
-----------------------------------------------------------
VPS系统:centos7 X64

[root@vultr v2ray]# cat /proc/version
Linux version 4.12.4-1.el7.elrepo.x86_64 (mockbuild@Build64R7) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Thu Jul 27 20:03:28 EDT 2017
[root@vultr v2ray]# uname -r
4.12.4-1.el7.elrepo.x86_64

服务端防火墙已关闭

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
  ·   V2Ray v2.33 (One for all) 20170609       服务端
  ·   v2ray-v2.33.1-windows-64                     客户端
  ·   v2rayN-1.11                                            第三方图形化界面
  ·   proxifier                                                 

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    访问一切被墙的软件网站及服务

3)  你看到的不正常的现象是什么？
    服务端设置完成后用同一份配置文件 可以在android（Actinium）及ios(shadowrocket)上运作
    而电脑v2rayN配置完通过proxifier无法正常工作
4)  你期待看到的正确表现是怎样的？
    能够正常访问被墙的网站及服务

---------------------------------附加proxifier日志------------------------------------------------------

[07.29 21:20:35] wv2ray.exe *64 - XXXXXXXXXXXXX 打开通过代理 127.0.0.1:1080 SOCKS5
[07.29 21:20:35] chrome.exe - www.google.com:443 打开通过代理 127.0.0.1:1080 SOCKS5
[07.29 21:20:35] chrome.exe - www.google.com:443 打开通过代理 127.0.0.1:1080 SOCKS5
[07.29 21:20:35] chrome.exe - www.google.com:443 打开通过代理 127.0.0.1:1080 SOCKS5
[07.29 21:20:38] chrome.exe - www.google.com:80 打开通过代理 127.0.0.1:1080 SOCKS5
[07.29 21:20:38] chrome.exe - www.google.com:80 打开通过代理 127.0.0.1:1080 SOCKS5
-----------------------------------------------------------------------------------------------------------
5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
   

 -------------------------------- （服务器端配置文件）--------------------------------------------

{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 20163,
    "listen": null,
    "protocol": "vmess",
    "settings": {
      "auth": null,
      "udp": false,
      "ip": null,
      "clients": [
        {
          "id": "721b6e30-2432-489a-8169-807ce3556071",
          "alterId": 66,
          "security": null
        }
      ]
    },
    "streamSettings": {
      "network": "tcp",
      "security": "",
      "tcpSettings": null,
      "kcpSettings": null,
      "wsSettings": null
    }
  },
  "outbound": {
    "tag": null,
    "protocol": "freedom",
    "settings": null,
    "streamSettings": null,
    "mux": null
  },
  "inboundDetour": null,
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": null,
      "tag": "blocked"
    }
  ],
  "dns": null,
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": null,
      "rules": [
        {
          "type": "field",
          "port": null,
          "outboundTag": "blocked",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "domain": null
        }
      ]
    }
  }
}

---------------------------------------------------------------------------------------------------------------

------------------------------（客户端配置文件）-----------------------------------------------------------
{
  "log": {
    "access": "Vaccess.log",
    "error": "Verror.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 1080,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "127.0.0.1",
      "clients": null
    },
    "streamSettings": null
  },
  "outbound": {
    "tag": "agentout",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "XXXXXXXXXXXXXXX",
          "port": 20163,
          "users": [
            {
              "id": "721b6e30-2432-489a-8169-807ce3556071",
              "alterId": 66,
              "security": "aes-128-gcm"
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "tcp",
      "security": "",
      "tcpSettings": null,
      "kcpSettings": null,
      "wsSettings": null
    },
    "mux": {
      "enabled": true
    }
  },
  "inboundDetour": null,
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {
        "response": null
      },
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "blockout"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": null,
          "outboundTag": "direct",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "domain": null
        }
      ]
    }
  }
}

-------------------------------------------------------------------------------------------------------------------
6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

      

    Server Log File（服务器端日志）:
```
    // 在这里附上服务器端日志
 2017/07/28 17:42:52 [Warning]Core: V2Ray started
2017/07/29 02:54:29 [Warning]Core: V2Ray started
2017/07/29 03:04:01 [Warning]Core: V2Ray started
2017/07/29 03:05:25 [Warning]Core: V2Ray started

    Client Log File（客户端日志）:


2017/07/29 23:24:08 [Info]Transport|Internet|TCP: listening TCP on 127.0.0.1:1080
2017/07/29 23:24:08 [Info]Transport|Internet|UDP: listening UDP on 127.0.0.1:1080
2017/07/29 23:24:08 [Warning]Core: V2Ray started
2017/07/29 23:24:17 [Info]Transport|Internet|TCP: listening TCP on 127.0.0.1:1080
2017/07/29 23:24:17 [Info]Transport|Internet|UDP: listening UDP on 127.0.0.1:1080
2017/07/29 23:24:17 [Warning]Core: V2Ray started
2017/07/29 23:24:23 [Info]Proxy|Socks: TCP Connect request to tcp:93.46.8.89:80
2017/07/29 23:24:23 [Info]App|Dispatcher|Default: default route for tcp:93.46.8.89:80
2017/07/29 23:24:23 [Info]App|Proxyman|Mux: dispatching request to tcp:93.46.8.89:80
2017/07/29 23:24:23 [Info]Transport|Internet|TCP: dailing TCP to tcp:XXXXXXXXXXXXXXXX
2017/07/29 23:24:23 [Info]Proxy|Socks: TCP Connect request to tcp:XXXXXXXXXXXXXXXX
2017/07/29 23:24:23 [Info]App|Dispatcher|Default: default route for tcp:XXXXXXXXXXXXX
2017/07/29 23:24:23 [Info]App|Proxyman|Mux: dispatching request to tcp:XXXXXXXXXXX
2017/07/29 23:24:23 [Info]Proxy|VMess|Outbound: tunneling request to tcp:v1.mux.cool:9527 via tcp:104.207.158.201:20163
2017/07/29 23:24:27 [Info]Proxy|Socks: TCP Connect request to tcp:93.46.8.89:80
2017/07/29 23:24:27 [Info]App|Dispatcher|Default: default route for tcp:93.46.8.89:80
2017/07/29 23:24:27 [Info]App|Proxyman|Mux: dispatching request to tcp:93.46.8.89:80

**Comment by oing9179** [comment]
@fkdhhm Reply [#1](#issue-246521268)

仔细看 Proxifier 日志的第一行:

```
[07.29 21:20:35] wv2ray.exe *64 - XXXXXXXXXXXXX 打开通过代理 127.0.0.1:1080 SOCKS5
[07.29 21:20:35] chrome.exe - www.google.com:443 打开通过代理 127.0.0.1:1080 SOCKS5
[07.29 21:20:35] chrome.exe - www.google.com:443 打开通过代理 127.0.0.1:1080 SOCKS5
[07.29 21:20:35] chrome.exe - www.google.com:443 打开通过代理 127.0.0.1:1080 SOCKS5
[07.29 21:20:38] chrome.exe - www.google.com:80 打开通过代理 127.0.0.1:1080 SOCKS5
[07.29 21:20:38] chrome.exe - www.google.com:80 打开通过代理 127.0.0.1:1080 SOCKS5
```

我总觉得 Proxifier 把 `wv2ray.exe` 的连接也代理了，你可能得配置 Proxifier 把 `wv2ray.exe` 排除掉。

**Comment by fkdhhm** [comment]
@oing9179 我把wv2ray.exe添加直连后
还是不可以

**Comment by oing9179** [comment]
@fkdhhm Reply [#3](https://github.com/v2ray/v2ray-core/issues/505#issuecomment-318880534)

你先试试不用 Proxifier 能否打开网页之类的。
如果能连上，那就把 `wv2ray.exe` 直连之后的 v2ray的日志 和 Proxifier的日志 都贴出来。

**Comment by fkdhhm** [comment]
@oing9179 
使用switchyomega 自己设置127.0.0.1：1080  可翻 
打开proxifier后 switchyomega 设置为直连 可翻

-------------------------------------------------------------switchyomega直连状态下 proxifier日志----------------------------------------------------------------------
[2017.07.30 15:14:16] [2017.07.30 15:14:24] chrome.exe (4600) - ssl.gstatic.com:443 [2017.07.30 15:14:24] chrome.exe (4600) - www.google.com:443 [2017.07.30 15:14:24] chrome.exe (4600) - www.google.com:443 [2017.07.30 15:14:24] chrome.exe (4600) - ssl.gstatic.com:443 [2017.07.30 15:14:24] chrome.exe (4600) - ssl.gstatic.com:443 [2017.07.30 15:14:24] chrome.exe (4600) - www.gstatic.com:443 [2017.07.30 15:14:24] chrome.exe (4600) - www.gstatic.com:443 [2017.07.30 15:14:24] chrome.exe (4600) - ssl.gstatic.com:443 GetSockName : 127.0.0.1:51414
[2017.07.30 15:14:24] chrome.exe (4600) - www.gstatic.com:443 GetSockName : 127.0.0.1:51417
------------------------------------------------------------------------------------------------------------------------------------------------


-------------------------------------------------------------switchyomega直连状态下 v2rayN verror日志-------------------------------------------------------------------
2017/07/30 15:17:15 [Warning]Core: V2Ray started
2017/07/30 15:17:24 [Info]Proxy|Socks: TCP Connect request to tcp:www.google.com:443
2017/07/30 15:17:24 [Info]App|Router: looking up IP for tcp:www.google.com:443
2017/07/30 15:17:24 [Debug]App|DNS|Server: add pending request id 54012
2017/07/30 15:17:24 [Debug]Transport|Internet|UDP: dispatch request to: udp:8.8.8.8:53
2017/07/30 15:17:24 [Info]Transport|Internet|UDP: establishing new connection for udp:8.8.8.8:53
2017/07/30 15:17:24 [Info]App|Dispatcher|Default: default route for udp:8.8.8.8:53
2017/07/30 15:17:24 [Info]App|Proxyman|Mux: dispatching request to udp:8.8.8.8:53
2017/07/30 15:17:24 [Info]Transport|Internet|TCP: dailing TCP to tcp:104.207.158.201:20163
2017/07/30 15:17:24 [Info]Proxy|Socks: TCP Connect request to tcp:apis.google.com:443
2017/07/30 15:17:24 [Info]App|Router: looking up IP for tcp:apis.google.com:443
2017/07/30 15:17:24 [Debug]App|DNS|Server: add pending request id 59284
2017/07/30 15:17:24 [Debug]Transport|Internet|UDP: dispatch request to: udp:8.8.8.8:53
2017/07/30 15:17:24 [Info]Proxy|Socks: TCP Connect request to tcp:ssl.gstatic.com:443
2017/07/30 15:17:24 [Info]App|Router: looking up IP for tcp:ssl.gstatic.com:443
2017/07/30 15:17:24 [Debug]App|DNS|Server: add pending request id 41421
2017/07/30 15:17:24 [Debug]Transport|Internet|UDP: dispatch request to: udp:8.8.8.8:53
2017/07/30 15:17:24 [Info]Proxy|Socks: TCP Connect request to tcp:www.gstatic.com:443
2017/07/30 15:17:24 [Info]App|Router: looking up IP for tcp:www.gstatic.com:443
2017/07/30 15:17:24 [Debug]App|DNS|Server: add pending request id 207
2017/07/30 15:17:24 [Debug]Transport|Internet|UDP: dispatch request to: udp:8.8.8.8:53
2017/07/30 15:17:24 [Info]Proxy|Socks: TCP Connect request to tcp:www.google.com:443
2017/07/30 15:17:24 [Info]App|Router: looking up IP for tcp:www.google.com:443
2017/07/30 15:17:24 [Debug]App|DNS|Server: add pending request id 38900
2017/07/30 15:17:24 [Debug]Transport|Internet|UDP: dispatch request to: udp:8.8.8.8:53
2017/07/30 15:17:24 [Info]Proxy|Socks: TCP Connect request to tcp:www.google.com:443
2017/07/30 15:17:24 [Info]App|Router: looking up IP for tcp:www.google.com:443
2017/07/30 15:17:24 [Debug]App|DNS|Server: add pending request id 20662
2017/07/30 15:17:24 [Debug]Transport|Internet|UDP: dispatch request to: udp:8.8.8.8:53
2017/07/30 15:17:24 [Info]Proxy|VMess|Outbound: tunneling request to tcp:v1.mux.cool:9527 via tcp:104.207.158.201:20163
2017/07/30 15:17:25 [Debug]App|DNS|Server: handling response for id 54012 content: ;; opcode: QUERY, status: NOERROR, id: 54012
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.google.com.	IN	 A

;; ANSWER SECTION:
www.google.com.	221	IN	A	216.58.192.4

2017/07/30 15:17:25 [Debug]App|DNS|Server: handling response for id 38900 content: ;; opcode: QUERY, status: NOERROR, id: 38900
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.google.com.	IN	 A

;; ANSWER SECTION:
www.google.com.	221	IN	A	216.58.192.4

2017/07/30 15:17:25 [Debug]App|DNS|Server: handling response for id 20662 content: ;; opcode: QUERY, status: NOERROR, id: 20662
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.google.com.	IN	 A

;; ANSWER SECTION:
www.google.com.	221	IN	A	216.58.192.4

2017/07/30 15:17:25 [Debug]App|DNS|Server: returning 1 IPs for domain www.google.com.
2017/07/30 15:17:25 [Debug]App|DNS|Server: returning 1 IPs for domain www.google.com.
2017/07/30 15:17:25 [Debug]App|DNS|Server: returning 1 IPs for domain www.google.com.
2017/07/30 15:17:25 [Info]App|Dispatcher|Default: default route for tcp:www.google.com:443
2017/07/30 15:17:25 [Info]App|Dispatcher|Default: default route for tcp:www.google.com:443
2017/07/30 15:17:25 [Info]App|Dispatcher|Default: default route for tcp:www.google.com:443
2017/07/30 15:17:25 [Info]App|Proxyman|Mux: dispatching request to tcp:www.google.com:443
2017/07/30 15:17:25 [Info]App|Proxyman|Mux: dispatching request to tcp:www.google.com:443
2017/07/30 15:17:25 [Info]App|Proxyman|Mux: dispatching request to tcp:www.google.com:443
2017/07/30 15:17:25 [Debug]App|DNS|Server: handling response for id 59284 content: ;; opcode: QUERY, status: NOERROR, id: 59284
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;apis.google.com.	IN	 A

;; ANSWER SECTION:
apis.google.com.	86345	IN	CNAME	plus.l.google.com.
plus.l.google.com.	245	IN	A	216.58.194.206

2017/07/30 15:17:25 [Debug]App|DNS|Server: returning 1 IPs for domain apis.google.com.
2017/07/30 15:17:25 [Info]App|Dispatcher|Default: default route for tcp:apis.google.com:443
2017/07/30 15:17:25 [Info]App|Proxyman|Mux: dispatching request to tcp:apis.google.com:443
2017/07/30 15:17:25 [Debug]App|DNS|Server: handling response for id 207 content: ;; opcode: QUERY, status: NOERROR, id: 207
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.gstatic.com.	IN	 A

;; ANSWER SECTION:
www.gstatic.com.	130	IN	A	216.58.192.3

2017/07/30 15:17:25 [Debug]App|DNS|Server: returning 1 IPs for domain www.gstatic.com.
2017/07/30 15:17:25 [Info]App|Dispatcher|Default: default route for tcp:www.gstatic.com:443
2017/07/30 15:17:25 [Info]App|Proxyman|Mux: dispatching request to tcp:www.gstatic.com:443
2017/07/30 15:17:25 [Debug]App|DNS|Server: handling response for id 41421 content: ;; opcode: QUERY, status: NOERROR, id: 41421
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;ssl.gstatic.com.	IN	 A

;; ANSWER SECTION:
ssl.gstatic.com.	299	IN	A	216.58.194.195

2017/07/30 15:17:25 [Debug]App|DNS|Server: returning 1 IPs for domain ssl.gstatic.com.
2017/07/30 15:17:25 [Info]App|Dispatcher|Default: default route for tcp:ssl.gstatic.com:443
2017/07/30 15:17:25 [Info]App|Proxyman|Mux: dispatching request to tcp:ssl.gstatic.com:443
----------------------------------------------------------------------------------------------------------------------------------------------




--------------------------------------------------------------switchyomega系统代理状态下  proxifier日志---------------------------------------------------------------------

[2017.07.30 15:15:13] chrome.exe (4600) - ssl.gstatic.com:443 [2017.07.30 15:15:13] chrome.exe (4600) - www.gstatic.com:443 [2017.07.30 15:15:13] chrome.exe (4600) - resolve apis.google.com : proxy
[2017.07.30 15:15:13] chrome.exe (4600) - resolve ssl.gstatic.com : proxy
[2017.07.30 15:15:13] chrome.exe (4600) - resolve www.gstatic.com : proxy
[2017.07.30 15:15:13] chrome.exe (4600) - resolve apis.google.com : proxy
[2017.07.30 15:15:13] chrome.exe (4600) - resolve ssl.gstatic.com : proxy
[2017.07.30 15:15:13] chrome.exe (4600) - resolve www.gstatic.com : proxy
[2017.07.30 15:15:13] chrome.exe (4600) - apis.google.com:443 [2017.07.30 15:15:13] chrome.exe (4600) - apis.google.com:443 [2017.07.30 15:15:13] chrome.exe (4600) - ssl.gstatic.com:443 [2017.07.30 15:15:13] chrome.exe (4600) - ssl.gstatic.com:443 [2017.07.30 15:15:13] chrome.exe (4600) - www.gstatic.com:443 [2017.07.30 15:15:13] chrome.exe (4600) - apis.google.com:443 GetSockName : 127.0.0.1:51420
[2017.07.30 15:15:13] chrome.exe (4600) - www.gstatic.com:443 [2017.07.30 15:15:13] chrome.exe (4600) - ssl.gstatic.com:443 GetSockName : 127.0.0.1:51424
[2017.07.30 15:15:13] chrome.exe (4600) - www.gstatic.com:443 GetSockName : 127.0.0.1:51427
[2017.07.30 15:15:16] chrome.exe (4600) - resolve wpad : proxy
[2017.07.30 15:15:16] chrome.exe (4600) - resolve wpad : proxy
[2017.07.30 15:15:16] chrome.exe (4600) - resolve wpad : proxy
[2017.07.30 15:15:16] chrome.exe (4600) - resolve wpad : proxy
[2017.07.30 15:15:16] chrome.exe (4600) - wpad:80 [2017.07.30 15:15:16] chrome.exe (4600) - wpad:80 [2017.07.30 15:15:16] chrome.exe (4600) - wpad:80 GetSockName : 127.0.0.1:51429
--------------------------------------------------------------------------------------------------------------------------------------------------------------


-------------------------------------------------------------switchyomega系统代理状态下  v2rayN verror日志----------------------------------------------------------------------

2017/07/30 15:20:19 [Info]Proxy|Socks: TCP Connect request to tcp:wpad:80
2017/07/30 15:20:19 [Info]App|Router: looking up IP for tcp:wpad:80
2017/07/30 15:20:19 [Debug]App|DNS|Server: add pending request id 36441
2017/07/30 15:20:19 [Debug]Transport|Internet|UDP: dispatch request to: udp:8.8.8.8:53
2017/07/30 15:20:19 [Info]Transport|Internet|UDP: establishing new connection for udp:8.8.8.8:53
2017/07/30 15:20:19 [Info]App|Dispatcher|Default: default route for udp:8.8.8.8:53
2017/07/30 15:20:19 [Info]App|Proxyman|Mux: dispatching request to udp:8.8.8.8:53
2017/07/30 15:20:19 [Info]Transport|Internet|TCP: dailing TCP to tcp:104.207.158.201:20163
2017/07/30 15:20:19 [Info]Proxy|VMess|Outbound: tunneling request to tcp:v1.mux.cool:9527 via tcp:104.207.158.201:20163
2017/07/30 15:20:20 [Debug]App|DNS|Server: handling response for id 36441 content: ;; opcode: QUERY, status: NXDOMAIN, id: 36441
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;wpad.	IN	 A

;; AUTHORITY SECTION:
.	71992	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2017072901 1800 900 604800 86400

2017/07/30 15:20:20 [Debug]App|DNS|Server: returning 0 IPs for domain wpad.
2017/07/30 15:20:20 [Info]App|Dispatcher|Default: default route for tcp:wpad:80
2017/07/30 15:20:20 [Info]App|Proxyman|Mux: dispatching request to tcp:wpad:80

-----------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by oing9179** [comment]
既然 "使用proxifier 同时将switchyomega 设置为直连模式下可翻"：

1. 已经可以访问网页了，好像已经解决了你的问题吧?
2. 如果没有解决的话，可否再详细的描述一下问题，并贴出 你是如何配置 `wv2ray.exe` 直连的

**Comment by fkdhhm** [comment]
@oing9179 
加了个switchyomega就可以用了，虽然不太明白原理
很感谢你对我的帮助！
再次感谢！

**Comment by piceone** [comment]
pc系统时间一定要正确，否则也会导致pc端无法正常工作。

**Comment by Litangren** [comment]
> pc系统时间一定要正确，否则也会导致pc端无法正常工作。

就是这个系统时间差错，解决了困扰我很久的问题！

**Comment by qiuqiran** [comment]
> pc系统时间一定要正确，否则也会导致pc端无法正常工作。

这个才是真理，哈哈哈

**Comment by ouzc12358** [comment]
> pc系统时间一定要正确，否则也会导致pc端无法正常工作。
虽然一直在强调，但还是短路了，找了半天不知道啥情况
