### ISSUE TITLE
invalid character '}' looking for beginning of object key string

### ISSUE THREAD

**Issue by nanqinlang** [v2ray/v2ray-core#506]
1) v2ray版本 v2.33.1

2) debian8 希望以 tls模式+全部vmess协议 运行服务端 不需要国内直连等等所以没写routing和Detour

3) 报错信息 `Main: failed to read config file: /home/v2ray/v2ray-v2.33.1-linux-64/config-server.json > Ext|Tools|Conf|Serial: failed to read config file > invalid character '}' looking for beginning of object key string`

4) 当然是希望服务端能运行  
我已经对着看了好多遍了 我的括号真的没错啊 它就是报错我的括号无效 json并不要求一定要竖着写的吧

5) Server Configuration File（服务器端配置文件）:
```javascript
   {

"log":{
"loglevel":"warning",
"access":"/home/v2ray/log/access.log",
"error":"/home/v2ray/log/error.log"
},

"inbound":{
"port":443,
"protocol":"vmess",
"settings":{"clients":[{"id":"23ad6b10-8d1a-40f7-8ad0-e3e35cd38297", "alterId":64, "level":1}]},
"streamSettings":{"network":"tcp", "security":"tls", "tlsSettings":{"certificates":[{"certificateFile":"/home/v2ray/v2ray-v2.33.1-linux-64/Let's_Encrypt.cer", "keyFile":"/home/v2ray/v2ray-v2.33.1-linux-64/Let's_Encrypt.key"}]}},
},

"outbound":{
"protocol":"vmess",
"settings":{}
}

}
```

**Comment by cnperi** [comment]
查查逗号。倒数第五个“}”后面不应该跟“,”吧？

**Comment by oing9179** [comment]
@nanqinlang Reply [#1](https://github.com/v2ray/v2ray-core/issues/506#issue-246526017)

![JSON format error](https://user-images.githubusercontent.com/3756288/28749972-2876ce82-750c-11e7-9db0-ecc76b41331d.jpg)
楼上说得对，第 `13` 行结尾多了个 `,`。

**Comment by nanqinlang** [comment]
@cnperi @oing9179  
谢谢两位 的确是这个逗号
