### ISSUE TITLE
请问关于电脑应用走v2ray代理的问题（谷歌同步软件googledrivesync）

### ISSUE THREAD

**Issue by Fengzhiying2017** [v2ray/v2ray-core#508]
这个软件可以同步电脑上的文件，尤其是对照片上传后的自动归类十分好用，但发现用v2ray配置好代理后（客户端用的v2rayN，同时在2个端口开启了socks和http代理，经测试都能正常工作），浏览器上网什么的都正常没有出现错误，速度也很快，但貌似这个软件完全不走v2ray通道，查看本地v2ray的日志里没有任何关于googledrivesync的连接请求，而ss开启后却可以自动连接，请教，如何设置才能使本地连接都由v2ray接管，然后根据访问请求进行连接？

软件下载：https://www.google.com/drive/download/

**Comment by oing9179** [comment]
@Fengzhiying2017 Reply [#1](https://github.com/v2ray/v2ray-core/issues/508#issue-246566824)

你说的是像这样的吗?
[是否能支持如Shadowsockets自动代理模式? #163](https://github.com/v2ray/v2ray-core/issues/163)

**Comment by Fengzhiying2017** [comment]
@oing9179 
是这个意思，这个功能主要应该是靠客户端来设置的，可是不知道怎么做？

**Comment by oing9179** [comment]
@Fengzhiying2017 Reply [#3](https://github.com/v2ray/v2ray-core/issues/508#issuecomment-318892558)

v2rayN 客户端目前不支持你需要的功能，可以考虑试试 Proxifier 之类的软件。

**Comment by Fengzhiying2017** [comment]
@oing9179 
好的，谢谢，希望v2ray系列要加快开发，下一步除完善功能提升性能外，客户端的易用性是要重点提高的一个方面，实现开启客户端即能自动代理系统各个应用，基本不需要人工参与就很赞了！

**Comment by ymoti** [comment]
在想那个软件是否支持代理，是的话，直接在设置中指向v2ray的端口是否可行?

**Comment by Fengzhiying2017** [comment]
后来使用了sockscap64，强制将应用走代理临时解决了问题

**Comment by Towdium** [comment]
windows http的话是不是可以考虑在网络设置里边设置全局代理用一下

**Comment by SingZhi** [comment]
那个说：“v2rayN 客户端目前不支持你需要的功能，可以考虑试试 Proxifier 之类的软件。”，其实用v2ray N 开系统代理+全局模式，就可以代理其它软件了！

**Comment by michaeledi** [comment]
@SingZhi @Towdium 仅仅在v2rayN客户端设置全局http代理貌似是没有用的。。。

**Comment by betterRunner** [comment]
> windows http的话是不是可以考虑在网络设置里边设置全局代理用一下

我这边试了一下，可以～

**Comment by hasen6** [comment]
@michaeledi 是，但是不光是v2rayN，苹果的v2rayX全局也没用。看来v2ray只能上网，别的软件都不行。需要的话还是用SSR。

**Comment by SingZhi** [comment]
不是的吧！我pac模式，一些软件就可以走科学网络啊！




------------------ 原始邮件 ------------------
发件人: "hasen6"<notifications@github.com>; 
发送时间: 2019年9月21日(星期六) 晚上7:36
收件人: "v2ray/v2ray-core"<v2ray-core@noreply.github.com>; 
抄送: "SinZhi"<2357004878@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [v2ray/v2ray-core] 请问关于电脑应用走v2ray代理的问题（谷歌同步软件googledrivesync） (#508)




@michaeledi 是，但是不光是v2rayN，苹果的v2rayX全局也没用。看来v2ray只能上网，别的软件都不行。需要的话还是用SSR。

**Comment by hasen6** [comment]
@SingZhi 你在回谁？不知道你说的什么意思。我是说全局模式有问题，可以用浏览器但是打开别的软件像安卓虚拟器上不了YouTube什么的，twitch直播不了什么的。

**Comment by Yihao-G** [comment]
也可以考虑使用https://github.com/mellow-io/mellow

**Comment by likaboy** [comment]
关于开了v2 无法走全局代理的问题 ，你在需要的代理软件里设置 将此软件代理到本地的v2 转发端口 默认1080 试试。

**Comment by wangshanghai240** [comment]
@SingZhi，我用word里面的维基百科，但是无法打开，开了pac

**Comment by luoji111** [comment]
@wangshanghai240 

你所说的Word应该是Microsoft Office全套办公组件中的其中一种

请注意，Microsoft Word是一个UWP(Universal Windows Platform,中文名为Windows通用应用)应用，运行机制是独立运行的沙箱机制，V2ray暂时无法接管其数据

同时，所有在Microsoft store上下载的应用基本为UWP应用

解决方案

通过SID添加UWP排除网络隔离来解决走系统代理问题

由此想到可以在V2ray新增UWP应用排除网络隔离开关

步骤

首先遍历注册表，按如下路径找到所有UWP应用的UWP SID

`HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppContainer\Mappings`

得到SID Array后，用管理员权限打开命令提示符，输入如下命令并执行

```
CheckNetIsolation loopbackexempt -a -p=UWPSID
```

添加排除网络隔离

**Comment by wmxzrs** [comment]
可以使用fiddler 4试试

**Comment by zhanghay** [comment]
> 那个说：“v2rayN 客户端目前不支持你需要的功能，可以考虑试试 Proxifier 之类的软件。”，其实用v2ray N 开系统代理+全局模式，就可以代理其它软件了！

arduino ide此方法可以

**Comment by cccssppp** [comment]
我使用curl 命令和nginx代理都不能访问google，应该只有部分软件可以
