### ISSUE TITLE
syntax error: unexpected range

### ISSUE THREAD

**Issue by SharerMax** [v2ray/v2ray-core#51]
Building V2Ray (v0.10) for linux amd64
# github.com/v2ray/v2ray-core/common/alloc
../src/github.com/v2ray/v2ray-core/common/alloc/buffer.go:112: syntax error: unexpected range, expecting {
../src/github.com/v2ray/v2ray-core/common/alloc/buffer.go:125: syntax error: unexpected }

**Comment by SharerMax** [comment]
install way：
> bash <(curl -s https://raw.githubusercontent.com/v2ray/v2ray-core/master/release/install.sh)

**Comment by v2ray** [comment]
请使用 Go 1.5 编译本程序，你碰到的问题是因为你的机器上事先安装了 Go 并且版本是 1.2 或 1.3。请从 https://golang.org/dl/ 下载并安装最新的 Go 编译器，或使用[预编译的 V2Ray 程序](https://github.com/v2ray/v2ray-core/releases)
