### ISSUE TITLE
建议为VMess添加对mipsel友好的新加密方式

### ISSUE THREAD

**Issue by fanck0605** [v2ray/v2ray-core#510]
V2Ray版本：2.33

本人一般在 mt7621 （mipsel构架）的路由器上运行 V2Ray 用 VMess 代理连接国外服务器，并使用 Edge 通过 Http 代理连接路由器观看 YouTube 4K视频。

但由于 mt7621 的处理能力不强运，用现有的加密方式（运算量对与路由器soc太大）很难获得一个令人满意的代理速度，希望能加入像rc4-md5，aes-128-ctr这种运算量较小的加密方式

**Comment by DarienRaymond** [comment]
chacha20也不行？

**Comment by aresbigboy** [comment]
其实我也挺想v2ray能支持 rc4-md5的。因为我在国内使用v2ray中转海外VPS的时候，国内客户端链接中转服务器，如果支持最简单的ss(rc4-md5) 接入，那么移动设备性能影响最小，速度也最快。比现在支持的chacha20还要快。
