### ISSUE TITLE
搬瓦工 无法安装服务端 显示 -bash: curl: command not found

### ISSUE THREAD

**Issue by l597286** [v2ray/v2ray-core#511]
搬瓦工 openvz 

系统 Debian 7.0 x86_64

 已root

一键安装服务端出现一下信息：
root@localhost:~# bash <(curl -L -s https://install.direct/go.sh)
bash: /dev/fd/63: No such file or directory
root@localhost:~# -bash: curl: command not found

大大们知道这是怎么回事吗？求助

**Comment by fanck0605** [comment]
没有装curl
用”apt-get install -y curl“安装

**Comment by l597286** [comment]
@fanck0605 
貌似没有安装成功啊
root@localhost:~# apt-get install -y curl
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package curl is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'curl' has no installation candidate

**Comment by fanck0605** [comment]
@l597286 
”apt-get -y update“更新一下软件源

**Comment by l597286** [comment]
@fanck0605 
非常感谢大神
先 apt-get -y update   再apt-get install -y curl 然后安装服务端，安装成功！
