### ISSUE TITLE
[enhancement] please support shadowsocks AEAD ciphers

### ISSUE THREAD

**Issue by gregist** [v2ray/v2ray-core#513]
AEAD ciphers are being officially recommended as they are more secure and power-efficient.

["Users should use AEAD ciphers whenever possible."](https://shadowsocks.org/en/spec/AEAD-Ciphers.html) 

Also, chacha20 has been de facto [deprecated](https://shadowsocks.org/en/spec/Stream-Ciphers.html).

**Comment by ernestyao** [comment]
附议

**Comment by DarienRaymond** [comment]
Duplicated with https://github.com/v2ray/Planning/issues/11
