### ISSUE TITLE
Ubuntu 64 手动安装 v2ray Server 2.33 linux-64 错误

### ISSUE THREAD

**Issue by walt138** [v2ray/v2ray-core#515]
Ubuntu 64 手动安装 v2ray Server 2.33 linux-64 错误

Job for v2ray.service failed because the control process exited with error code.
See "systemctl status v2ray.service" and "journalctl -xe" for details.
v2ray.service - LSB: socksv5 based proxy written by go.
Loaded: loaded (/etc/init.d/v2ray; bad; vendor preset: enabled)
Active: failed (Result: exit-code) since Mon
Docs: man:systemd-sysv-generator(8)
Process: 1172 ExecStart=/etc/init.d/v2ray start (code=exited, status=203/EXEC)

systemd[1]: Starting LSB: socksv5 based proxy written by go....
systemd[1]: v2ray.service: Control process exited, code=exited status=203
systemd[1]: Failed to start LSB: socksv5 based proxy written by go..
systemd[1]: v2ray.service: Unit entered failed state.
systemd[1]: v2ray.service: Failed with result 'exit-code'.

**Comment by DarienRaymond** [comment]
错误信息中说了用 journalctl -xe 命令来看细节
