### ISSUE TITLE
关于v2ray单端口多用户

### ISSUE THREAD

**Issue by zhxch3** [v2ray/v2ray-core#517]
![photo_2017-07-31_11-41-33](https://user-images.githubusercontent.com/13222476/28762114-74905b28-75e6-11e7-8ae0-3e17b1aa435e.jpg)

![photo_2017-07-31_11-41-59](https://user-images.githubusercontent.com/13222476/28762110-6ef02270-75e6-11e7-9506-b35337dfb11f.jpg)

配置教程中按照原配置写无法启动，修改添加了]之后启动成功但是无法连接

**Comment by XYenon** [comment]
"clients": [
        {
          "id": "***",
          "level": *,
          "alterId": *,
          "email": "***"
        },
        {
          "id": "***",
          "level": *,
          "alterId": *,
          "email": "***"
        }
      ],
↑ ↑ ↑ 正确写法 ↑ ↑ ↑

**Comment by zhxch3** [comment]
多谢

**Comment by qingfengshi** [comment]
请问一下这里的email是什么？是新版本中添加的用户认证吗？我的配置里一直没有添加email这一项，使用貌似没有问题

**Comment by XYenon** [comment]
V2Ray用户手册 <https://www.v2ray.com/chapter_02/protocols/vmess.html>里的解释是

   - email: 用户邮箱地址，用于区分不同用户的流量。


2017-07-31 18:01 GMT+08:00 qingfengshi <notifications@github.com>:

**Comment by XYenon** [comment]
[V2Ray用户手册](https://www.v2ray.com/chapter_02/protocols/vmess.html)里的解释是

> email: 用户邮箱地址，用于区分不同用户的流量。

**Comment by gbmeco** [comment]
但客户端(IOS 的ShadowRocket 或Kitsunebi)好像并不需要使用email 来认证啊。是不是说这个email 其实也没有用？随便填两个不同的就好了？

**Comment by zhouqiangithub** [comment]
email可以不填
