### ISSUE TITLE
Mux collapse & Speed problem in China Mobile landline connection 

### ISSUE THREAD

**Issue by weeeo** [v2ray/v2ray-core#518]
Hi, I have been testing V2ray lately. I would like to report two problem I found so far.

I am using v2ray-v2.33.1-windows-64 but once I enable Mux and start the program, it collapse immediately.
 
My config as follow:

_> {
>   "log": {
>     "loglevel": "warning"
>   },
>   "inbound": {
>     "port": 1080,
>     "listen": "127.0.0.1",
>     "protocol": "socks",
>     "settings": {
>       "auth": "noauth",
>       "udp": false,
>       "ip": "127.0.0.1"
>     }
>   },
>   "outbound": {
>     "protocol": "vmess",
>     "settings": {
>       "vnext": [
>         {
>           "address": "",
>           "port": ,
>           "users": [
>             {
>               "id": "",
>               "alterId": 64
>             }
>           ]
>         }
>       ]
>     }
>   },
> "mux": {"enabled": true}
>   "outboundDetour": [
>     {
>       "protocol": "freedom",
>       "settings": {},
>       "tag": "direct"
>     }
>   ],
>   "dns": {
>     "servers": [
>       "8.8.8.8",
>       "8.8.4.4",
>       "localhost"
>     ]
>   },
>   "routing": {
>     "strategy": "rules",
>     "settings": {
>       "domainStrategy": "IPIfNonMatch",
>       "rules": [
>         {
>           "type": "field",
>           "port": "1-52",
>           "outboundTag": "direct"
>         },
>         {
>           "type": "field",
>           "port": "54-79",
>           "outboundTag": "direct"
>         },
>         {
>           "type": "field",
>           "port": "81-442",
>           "outboundTag": "direct"
>         },
>         {
>           "type": "field",
>           "port": "444-65535",
>           "outboundTag": "direct"
>         },
>         {
>           "type": "chinasites",
>           "outboundTag": "direct"
>         },
>         {
>           "type": "field",
>           "ip": [
>             "0.0.0.0/8",
>             "10.0.0.0/8",
>             "100.64.0.0/10",
>             "127.0.0.0/8",
>             "169.254.0.0/16",
>             "172.16.0.0/12",
>             "192.0.0.0/24",
>             "192.0.2.0/24",
>             "192.168.0.0/16",
>             "198.18.0.0/15",
>             "198.51.100.0/24",
>             "203.0.113.0/24",
>             "::1/128",
>             "fc00::/7",
>             "fe80::/10"
>           ],
>           "outboundTag": "direct"
>         },
>         {
>           "type": "chinaip",
>           "outboundTag": "direct"
>         }
>       ]
>     }
>   },
>   "transport": {
>     "kcpSettings": {
>       "uplinkCapacity": 1,
>       "downlinkCapacity": 10
>     }
>   }
> }_

the second problem is the speed different between vmess and ss in China Mobile landline connection.
I have enable vmess and ss in the same sever. Different comparisons was made:

group a) 
In CM landline connection, the Max speed of vmess is, like, 30k/s, usually it is lower 10k/s; the Max speed of ss can reach the Max speed the ISP offer.
group b)
In CM cellphone 4G connection, speed of vmess equal to ss.
group c)
In China Unicom 4G connection,  speed of vmess equal to ss.

Shadowrocket is the app to do the test.

One more thing. I don't know if it the problem of CMNET, I am not able to use kcp. I fail to connect v2ry and ss by kcp in CMNET.

**Comment by DarienRaymond** [comment]
Please check the output of V2Ray if the program doesn't start.

The speed difference on different ISPs is purely performance issue of the ISP, not V2Ray.
