### ISSUE TITLE
沃通根证书有问题，底层tls加密应该还不是完美地安全

### ISSUE THREAD

**Issue by lbp0200** [v2ray/v2ray-core#520]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
   V2Ray v2.33.1 (One for all) 20170609

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

3)  你看到的不正常的现象是什么？
    无

4)  你期待看到的正确表现是怎样的？
    What's your expectation?

我记得GoAgent就是自造根证书，对https进行解包，实现的代理https，同理，沃通根证书应该也可以解包tls。另外，搭建钓鱼v2ray服务器，应该就可以解密aes，这样就可以实现对特定目标的监测，他在网上说了什么、看了什么。普通人应该无所谓。

当然现在shadowsocks应该早就沦陷了，还有那么多人用，出问题也是shadowsocks用户先出问题，现在提醒也晚了，说不定还反被shadowsocks用户和商人进行人肉。

我觉得目前最完美的加密方案是ssh，公钥私钥这种，配合http混淆和防主动监测。

我希望我是杞人忧天。

**Comment by wtlusvm** [comment]
>我觉得目前最完美的加密方案是ssh，公钥私钥这种，配合http混淆和防主动监测。

你的意思是TLS不是非对称加密？

**Comment by lbp0200** [comment]
@wtlusvm TLS是非对称加密，我再多了解一下这块的知识。

**Comment by wtlusvm** [comment]
不过我想大概明白你的意思了。其实这也是为什么提倡手动 revoke 沃通、StartCom、CNNIC ROOT 的原因。至于钓鱼服务器解密内容，V2Ray因此提供了链式代理，但是对于不愿意自主搭建服务器的人来说，方案也无效。

**Comment by lbp0200** [comment]
@wtlusvm 除非他们用SS作为socks5代理作为通道，使用Tor之类的，否则神仙难救。
自己不注意安全，QQ、360也能看到他们在干什么。

感谢您的回复
