### ISSUE TITLE
如何让v2ray转发来自局域网内的连接

### ISSUE THREAD

**Issue by fkdhhm** [v2ray/v2ray-core#528]
android--->v2ray--->tcpspeed--->服务端 （无法联通）

而v2ray--->tcpspeed--->服务端 （可正常联通）

**Comment by yingziwu** [comment]
本地监听0.0.0.0，还有要设置好防火墙。2017年8月4日 下午6:31，fkdhhm <notifications@github.com>写道：android--->v2ray--->tcpspeed--->服务端 （无法联通）
而v2ray--->tcpspeed--->服务端 （可正常联通）

**Comment by DarienRaymond** [comment]
不理解你的问题，请详细描述并说明无法联通的现象，比如错误信息等。

**Comment by fkdhhm** [comment]
@DarienRaymond 开启来自局域网内连接 是ss及ssr上的一种功能名称

具体作用是打开此功能后 手机的V2ray能连接电脑端的tcpspeed 

手机客户端没有错误日志

_Sent from my Samsung SM-G9280 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by DarienRaymond** [comment]
让 v2ray 监听 0.0.0.0 即可，并且正确配置防火墙
