### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by anywilliam** [v2ray/v2ray-core#531]
请问这是什么问题，第一次运行

[root@track ~]# service v2ray status
/etc/init.d/v2ray: line 29: /lib/init/vars.sh: No such file or directory
[root@track ~]# service v2ray start
/etc/init.d/v2ray: line 29: /lib/init/vars.sh: No such file or directory

**Comment by DarienRaymond** [comment]
你用的是什么系统？centos 6?

**Comment by anywilliam** [comment]
centos 6

**Comment by DarienRaymond** [comment]
V2Ray的启动脚本不支持centos6，你需要自己写一个，主程序是支持的。
