### ISSUE TITLE
Support transparent proxy

### ISSUE THREAD

**Issue by v2ray** [v2ray/v2ray-core#54]
When a network packet is redirected through iptables, the original destination address is stored in socket option: SO_ORIGINAL_DST

A new inbound connection handler is needed for such scenario.

**Comment by v2ray** [comment]
Found something in this thread: https://groups.google.com/forum/#!msg/Golang-Nuts/--8LqUiUfJ0/KWGkdDQY8PYJ

It seems not easy to get the file descriptor from a net.Conn in golang.

**Comment by cirias** [comment]
话说你是打算自己实现像iptables TPROXY一样的功能么？ iptables那个只能放在PREROUTING里，对本地产生的包没用，好不方便啊。

**Comment by acevery** [comment]
Is that means v2ray could not handle the iptables nat redirect packages right now?

**Comment by v2ray** [comment]
@cirias 是的
@acevery No. This feature has not yet been implemented.

**Comment by acevery** [comment]
@v2ray I see, thanks for your brilliant work, and looking forward for TPROXY support :)

**Comment by acevery** [comment]
@v2ray, How can I use freedom protocol as inbound?

**Comment by v2ray** [comment]
Dokodemo door now support TCP traffic redirected by iptables.

UDP support will be tracked by Trello: https://trello.com/b/mxvCFrh6
