### ISSUE TITLE
能否在access.log中增加uuid或者其他标识增强可读性？

### ISSUE THREAD

**Issue by himan85** [v2ray/v2ray-core#541]
在搭配websocket的时候，源地址都是“127.0.0.1：端口”这么显示出来，如果是单端口多uuid的情况下无法搞清楚用户的访问情况，管理起来很不方便，所以能否就这一点改进一下？

**Comment by DarienRaymond** [comment]
会考虑增加用户email

**Comment by himan85** [comment]
谢谢！
