### ISSUE TITLE
WebSocket without TLS not working

### ISSUE THREAD

**Issue by henrypijames** [v2ray/v2ray-core#542]
1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
2.34 on Ubuntu server, different clients including 2.34 on Windows x64

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
Visiting any website in any browser.

3) What did you see?
WebSocket with TLS: everything works. WebSocket without TLS: nothing works.

Connection timeout in browser. Client (debug mode) reports lots of connection attempts but no error. Server (debug mode) reports:
```
[Info]Transport|Internet|WebSocket: failed to convert to WebSocket connection > write tcp [server]:[port]->[client]:[port]: write: connection reset by peer
```

When visiting the WebSocket port directly with a browser (proxy off), server reports:
```
 [Info]Transport|Internet|WebSocket: failed to convert to WebSocket connection > websocket: not a websocket handshake: 'upgrade' token not found in 'Connection' header
```

This shows that the HTTP connection does come through and is not blocked (at least not always).

4) What's your expectation?
WebSocket working both with and without TLS.

5) Please attach your configuration file.

Server Configuration File:
```javascript
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "debug"
  },
  "inbound": {
    "port": 12345,
    "listen": null,
    "protocol": "vmess",
    "settings": {
      "auth": null,
      "udp": false,
      "ip": null,
      "clients": [
        {
          "id": "uuid",
          "alterId": 32,
          "security": null
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "tcpSettings": null,
      "kcpSettings": null,
      "wsSettings": {
        "connectionReuse": true,
        "path": ""
      }
    }
  },
  "outbound": {
    "tag": null,
    "protocol": "freedom",
    "settings": null,
    "streamSettings": null,
    "mux": null
  },
  "inboundDetour": null,
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": null,
      "tag": "blocked"
    }
  ],
  "dns": null,
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": null,
      "rules": [
        {
          "type": "field",
          "port": null,
          "outboundTag": "blocked",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "domain": null
        }
      ]
    }
  }
}
```

Client Configuration File:
```javascript
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "debug"
  },
  "inbound": {
    "port": 12345,
    "listen": "0.0.0.0",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1",
      "clients": null
    },
    "streamSettings": null
  },
  "outbound": {
    "tag": "agentout",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "domain.tld",
          "port": 12345,
          "users": [
            {
              "id": "uuid",
              "alterId": 32,
              "security": "aes-128-gcm"
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "tcpSettings": null,
      "kcpSettings": null,
      "wsSettings": {
        "connectionReuse": true,
        "path": ""
      }
    },
    "mux": {
      "enabled": true
    }
  },
  "inboundDetour": null,
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {
        "response": null
      },
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "blockout"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": null,
          "outboundTag": "direct",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "domain": null
        }
      ]
    }
  }
}
```

**Comment by henrypijames** [comment]
Further testing reveals that the configs are fine - it works when I run both client and server locally on Windows. So there is either a problem with the Linux build of v2ray (unlikely since it does work with TLS), or it's a network problem (possibly GFW interfering with non-TLS WebSocket connections).

**Comment by henrypijames** [comment]
Incompatibility between Windows and Linux binaries of v2ray ruled out - I ran the Linux binary on the Windows machine (Windows Subsystem for Linux) and got the exact same problem. There's still a possibility of incompatibility on the underlying system level, but this looks increasingly unlikely, and it appears more and more to be the GFW f*cking with non-TLS WebSocket.

**Comment by henrypijames** [comment]
OK, I was too quick to blame the GFW - it's not that, something *is* wrong with WebSocket in v2ray, after all:

I've now tried to proxy from one VPS to another VPS, both outside China (so no GFW between them), both running Ubuntu x64. It didn't work. `curl --socks5 localhost:port google.com` waits forever and times out.

To sum up: WebSocket works great with TLS. It only works without TLS if client and server are on the same computer. It doesn't work without TLS if client and server are on different computers.

**Comment by henrypijames** [comment]
Could this be some kind of unflushed network buffer? Possibly related to gorilla/websocket#267 which v2ray uses?

**Comment by wtlusvm** [comment]
Are you forget to include websocket related config in http section of Nginx or Apache configure file?

**Comment by henrypijames** [comment]
I don't have Ngnix, Apache or any other HTTP server. v2ray is running standalone, and it works fine with TLS.

**Comment by henrypijames** [comment]
FYI, WebSocket without TLS *still* doesn't work in 2.41. Can someone please take a look into this?

**Comment by DarienRaymond** [comment]
I don't think this is a problem in V2Ray. Please check your firewall settings.

**Comment by xaatora** [comment]
i have done the configurations that are required on vmess but still not connecting to the internet when testing the connection in android v2ray it will show: failed to detect internet connection::io read/write on closed pipe cloud it be the problem with utc time cose when i use the coding it changes the utc time this the code i use to config websocket + tls option 4 bash <(curl -s -L https://git.io/v2ray.sh)
