### ISSUE TITLE
疑问 - 为什么DNS的地址还是被污染? 请赐教

### ISSUE THREAD

**Issue by ymoti** [v2ray/v2ray-core#543]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v2.27

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
在Tomato固件的路由器上使用V2ray，期望能够避免DNS污染。
由于Tomato不支持TPROXY，所以使用DNS2SOCKS希望能够把DNS请求通过socks->V2ray->8.8.8.8得到正确的IP地址。

3)  你看到的不正常的现象是什么？
DNS仍然被污染

4)  你期待看到的正确表现是怎样的？
Dig时能得到正确的IP地址。

5) 配置文件如下。在电脑上用Chrome+SwitchyOmega能够正常科学上网。Dokodemot-door部分在这个场景中并没有使用。

{
  "log": {
    "access": "/tmp/var/log/v2ray-access.log",
    "error": "/tmp/var/log/v2ray-error.log",
    "loglevel": "warning"
  },
  
  "inbound": {
    "port": 5000,
    "protocol": "socks",
    
	"settings": 
	{
      	"auth": "noauth",
      	"ip": "127.0.0.1",
	"udp": false 
    	}
  },

  "inboundDetour": [
    {
      "protocol": "dokodemo-door",
      "listen": "0.0.0.0",
      "port": 5353,
      "settings": {
        "address": "8.8.8.8",
        "port": 53,
        "network": "tcp",
        "timeout": 5,
	"followRedirect": false 
      }
    }
  ],

  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "1.1.1.1",
          "port": 1111,
          "users": [
            {
              "id": "1111",
              "alterId": 1111
	   }
          ]
        }
      ]
    },
    "tag": "v2ray"
  
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],

  "routing": {
    "strategy": "rules",
    "settings": {
        "rules": [
	{
		"type": "field",
		"ip": [
			"0.0.0.0/8",
			"10.0.0.0/8",
			"100.64.0.0/10",
			"127.0.0.0/8",
			"169.254.0.0/16",
			"172.16.0.0/12",
			"192.0.0.0/24",
			"192.0.2.0/24",
			"192.168.0.0/16",
			"198.18.0.0/15",
			"198.51.100.0/24",
			"203.0.113.0/24",
			"::1/128",
			"fc00::/7",
			"fe80::/10"
			],
		"outboundTag": "blocked"
        }
        
        ]
    }
  }
}

**Comment by ymoti** [comment]
---------------dns2socks运行命令 ------------------------------------
root@R6900:/jffs/pdnsd# /jffs/dns2socks/dns2socks /l:/tmp/var/log/dns2socks.log 127.0.0.1:5000 8.8.8.8:53 127.0.0.1:1053

---------------dns2socks运行情况------------------------------------
DNS2SOCKS V1.8 (free software, use parameter /? to display help)

SOCKS server 127.0.0.1 port 5000
DNS server   8.8.8.8 port 53
listening on 127.0.0.1 port 1053
cache enabled
authentication disabled

---------------查询DNS时dns2socks运行反馈------------------------------------
2017-08-22 02:32:48     1 www.google.com
2017-08-22 02:36:04     2 www.google.com
2017-08-22 02:36:44     3 www.twitter.com


---------------查询DNS时v2ray的日志------------------------------------
2017/08/21 18:32:48 tcp:127.0.0.1:18138 accepted tcp:8.8.8.8:53 
2017/08/21 18:36:04 tcp:127.0.0.1:18140 accepted tcp:8.8.8.8:53 
2017/08/21 18:36:44 tcp:127.0.0.1:18142 accepted tcp:8.8.8.8:53

**Comment by ymoti** [comment]
我的理解是DNS查询确实通过socks5到了8.8.8.8，但不知为何查询到的IP仍然被污染。

**Comment by testcaoy7** [comment]
试试向64.6.64.6查询，看看是否被污染？
