### ISSUE TITLE
Google等网站打不开，百度等国内网站却可以

### ISSUE THREAD

**Issue by walasix** [v2ray/v2ray-core#544]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    2.34

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    使用chrome& SwitchyOmega打开google

3)  你看到的不正常的现象是什么？
    无法打开google

4)  你期待看到的正确表现是怎样的？
    可以像之前一样打开google

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Server Configuration File（服务器端配置文件）:
```javascript
    // 在这里附上服务器端配置文件
    // Please attach your server configuration file here.
```

    Client Configuration File（客户端配置文件）:
```javascript
    // 在这里附上客户端配置文件
    // Please attach your client configuration file here.
```

6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.

    Server Log File（服务器端日志）:
```
    // 在这里附上服务器端日志
    // Please attach your server log here.
```

    Client Log File（客户端日志）:
```
    // 在这里附上客户端日志
    // Please attach your client log here.
```
原issue #496 ，还是没搞明白怎么找到日志和配置文件，哪位大佬可以告诉我在哪儿。。
另外，发现虽然翻不出去，但是国内网站却能打开，而且百度查IP地址显示也是本身IP。像是绕开了V2RAY一样

**Comment by ymoti** [comment]
日志输出在配置文件里 loglevel改成"debug"，日志文件的路径可以自己设置。

  "log": {
    "access": "/tmp/var/log/v2ray-access.log",
    "error": "/tmp/var/log/v2ray-error.log",
    "loglevel": "debug"
  },

**Comment by DarienRaymond** [comment]
你用的是官方服务器？如果是的话请自己架设一台服务器再试一下。

**Comment by Towdium** [comment]
如果你用的是 windows，配置文件通常在v2ray文件夹中的config.json  
如果你用的是 linux，配置文件通常在/etc/v2ray/config.json  
看了你之前的 issue，请具体描述你的安装与启动方式，以及相关的服务器情况
这样提 issue 别人很难给你帮助。还有同样的问题请不要开多个 issue
