### ISSUE TITLE
V2ray的中转路由功能始终都是走的默认路由

### ISSUE THREAD

**Issue by larry16898** [v2ray/v2ray-core#545]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

客户端和服务端用的版本都是V2.34

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

客户端通过proxifier软件实现自动的全局SOCKS代理，指向一台V2ray的中转机器，这台中转机器上设置了inbound socks，outbound走的vmess到远端的v2ray服务器，另外设置了几个outboundDetour，
想通过在这台中转上设置路由规则，来实现不同的域名走不通的路由。

3)  你看到的不正常的现象是什么？
    What did you see?
发现不管路由规则怎么设置，始终流量都是走的默认路由，也就是outbound出去的。

4)  你期待看到的正确表现是怎样的？
    What's your expectation?

根据路由规则，比如访问的域名，来走不同的路由。

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Server Configuration File（服务器端配置文件）:
{
  "log": {
    "access": "C:\\v2ray\\v2rayaccess.log",
    "error": "C:\\v2ray\\v2rayerror.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 1088,
    "listen": "0.0.0.0",
    "protocol": "vmess",
    "settings": {
	   "clients": [
        {
          "id": "293c95b0-a4a2-47d5-b6eb-da8e6894e7b8",
          "alterId": 100,
          "level": 1 
        }
      ],
      "auth": "noauth",
      "udp": false,
      "ip": "0.0.0.0"
    }
  },
  "outbound": {
    "protocol": "freedom",  
    "settings": {}
  },
  "inboundDetour": [
    {
      "protocol": "shadowsocks",
      "port": 1089, 
      "settings": {
        "method": "chacha20",
        "password": "v2ray",     
        "udp": false
      }
    }
  ],
  "outboundDetour": [
    {
      "protocol": "blackhole",  
      "settings": {},
      "tag": "blocked"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": "1-52",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "54-79",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "81-442",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "444-65535",
          "outboundTag": "direct"
        },
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        }
      ]
    }
  }
}

    Client Configuration File（客户端配置文件）:

{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error":"/var/log/v2ray/error.log",
    "loglevel": "debug"
  },
  "inbound": {
    "port": 1080,
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "0.0.0.0"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "X.X.X.X", //服务器VPS IP地址
          "port": 1088, //通讯端口，客户端和服务端一致，自定
          "users": [
            {
              "id": "293c95b0-a4a2-47d5-b6eb-da8e6894e7b8", //UUID 在这个网站随机生成一个，https://www.uuidgenerator.net， 要保证client和server配置一个UUID
              "alterId": 100 // 这个自定，数字范围0-100，但要保证客户端和服务端一致
            }
          ]
        }
      ]
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "tag": "adblock",
      "settings": {
        "response": {
          "type": "http"  // 自动回复 HTTP 403
        }
      }
    },
    {
      "protocol": "vmess",
      "tag": "secondServer", //使用tag
      "settings": {
        "vnext": [
          {
            "address": "X.X.X.X",
            "port": 1088,
            "users": [
              {
                "id": "293c95b0-a4a2-47d5-b6eb-da8e6894e7b8",
                "alterId": 100
              }
            ]
          }
        ]
      }
    },
    {
      "protocol": "vmess",
      "tag": "thirdServer", //使用tag
      "settings": {
        "vnext": [
          {
            "address": "X.X.X.X",
            "port": 1088,
            "users": [
              {
                "id": "293c95b0-a4a2-47d5-b6eb-da8e6894e7b8",
                "alterId": 100
              }
            ]
          }
        ]
      }
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
	{
	  "type":"field",
	  "domain": [
	    "baidu.com",
	    "qq.com"
	  ],
	  "ip": [
	    "X.X.X.X"
	  ],
	  "outboundTag": "adblock"
	}
      ]
    }
  }
}

6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.

    Server Log File（服务器端日志）:
服务器端无错误日志

    Client Log File（客户端日志）:
2017/08/24 20:02:57 [Info]Transport|Internet|TCP: dailing TCP to tcp:X.X.X.X:1088
2017/08/24 20:02:57 [Info]Proxy|Socks: TCP Connect request to tcp:X.X.X.X:443
2017/08/24 20:02:57 [Info]App|Dispatcher|Default: default route for tcp:103.235.46.39:443
2017/08/24 20:02:57 [Info]Transport|Internet|TCP: dailing TCP to tcp:X.X.X.XX.:1088
2017/08/24 20:02:57 [Info]Proxy|VMess|Outbound: tunneling request to tcp:103.235.46.39:443 via tcp:X.X.X.XX.X:1088
2017/08/24 20:02:57 [Info]Proxy|VMess|Outbound: tunneling request to tcp:103.235.46.39:443 via tcp:X.X.X.XX.XX:1088
2017/08/24 20:02:58 [Info]Proxy|Socks: TCP Connect request to tcp:103.235.46.39:443
2017/08/24 20:02:58 [Info]App|Dispatcher|Default: default route for tcp:103.235.46.39:443
2017/08/24 20:02:58 [Info]Transport|Internet|TCP: dailing TCP to tcp:X.X.X.XX.XXXX:1088
2017/08/24 20:02:58 [Info]Proxy|VMess|Outbound: tunneling request to tcp:103.235.46.39:443 via tcp:1X.X.X.XX.XXX:1088

**Comment by larry16898** [comment]
发现问题原因了。通过观察客户端的日志，发现可能是V2Ray的socks入站接收过来的请求是IP地址，而不是域名，所以就无法做针对域名的路由规则判断。
但是还不知道怎么解决？ 麻烦大神帮忙看看呢？谢谢

**Comment by larry16898** [comment]
问题已经解决了。确实是DNS解析的问题。

**Comment by aaronwme** [comment]
> 问题已经解决了。确实是DNS解析的问题。

我也面临这个问题，请说一下具体的解决步骤！谢谢
