### ISSUE TITLE
go.sh 判斷錯誤 for BANANA PI M64 

### ISSUE THREAD

**Issue by JimmyChangJY** [v2ray/v2ray-core#546]
我用 BANANA PI M64 利用 go.sh 來安裝 V2Ray
發現 uname -r 出現不是 arm64 
而是 aarch64 
所以 go.sh 判斷錯誤，讓我下載的並不是正確的 ARM64 
我後來自己手動修改了
可以在 go.sh 加上 aarch64

後來我自己手動安裝就成功了
跑 service v2ray status 
顯示運作一切正常
感謝作者還有想到ARM64這種小眾使用者
用小系統跑這個V2RAY 放在牆外省電又好用

**Comment by DarienRaymond** [comment]
感谢对 V2Ray 的支持，现在 go.sh 已经可以正确判断 aarch64。
