### ISSUE TITLE
go.sh安装脚本，目前安装的还是v.2.34版本，不能自动检测更新啊！

### ISSUE THREAD

**Issue by ixiaofeng** [v2ray/v2ray-core#548]
go.sh安装脚本，目前安装的还是v.2.34版本，不能自动检测更新啊！

**Comment by aceforeverd** [comment]
v.2.34 is the latest stable version.
compile from source if you like to try testing version.

**Comment by DarienRaymond** [comment]
目前最新的稳定版本依然是 2.34，如果你要安装测试版，可以指定参数 `--version 2.36.3`
