### ISSUE TITLE
关于BBR能否加速使用kcp协议的V2Ray的问题。

### ISSUE THREAD

**Issue by fanck0605** [v2ray/v2ray-core#549]
首先kcp是一个基于UDP传输的协议，而BBR是一个对TCP协议的加速软件。

用BBR加速UDP流量显然不现实，而我的设想是在服务器上开启BBR是否会先对请求的TCP流量进行优化，再通过kcp来转换成UDP流量加速传输，已达到双重加速的作用！

由于买的是OpenVZ的VPS无法使用内核来实现BBR，目前采用了[扩软博客的方法](https://blog.kuoruan.com/116.html)已实现BBR，启用了kcp并开启[拥塞控制](https://www.v2ray.com/chapter_02/transport/mkcp.html)。
（ps：mkcp的拥塞控制作用挺大的，对于经常下大文件的用户建议开启）

才学疏浅不知道这种方式实际是否有实际作用（流量有没有经过BBR），也不知道能否真正起到加速的作用，请高手指点！

**Comment by wwqgtxx** [comment]
BBR是TCP的拥塞控制协议，而UDP本身并没有拥塞控制协议，这个是客户端程序自己实现的（在这里即mKCP协议自己实现的），所以你开BBR也没啥用

**Comment by ihcbbs** [comment]
没有作用。

**Comment by DarienRaymond** [comment]
同上。
