### ISSUE TITLE
V2Ray not properly closing the connection for HTTP/1.0

### ISSUE THREAD

**Issue by KireinaHoro** [v2ray/v2ray-core#551]
**What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?**

Client version 2.34
Server version [inapplicable]

**What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.**

Using dokodemo-door together with iptables 's owner match module for transparent proxying.
Packets from `freedom` protocol seem to be affected.

The project is available at https://github.com/KireinaHoro/v2ray-redir

**What did you see?**

Connections to home routers' control panel webpages which use `micro_httpd` and HTTP/1.0
(which lacks the `Content-Length` header and uses the old "read-till-eof" pattern) won't be
properly closed. Using `curl -v`, one can see that the connection is kept open after the content transfer
has finished (i.e. getting `</html>`).

**What's your expectation?**

Connections get properly closed and curl returns with

    * Closing connection 0

**Please attach your configuration file (**Mask IP addresses before submit this issue**).**

**Server Configuration File**
```javascript
    // Please attach your server configuration file here.
[inapplicable]
```

**Client Configuration File**
```javascript
    // Please attach your client configuration file here.
{
  "port": 1081,
  "log": {
    "access": ""
  },
  "inbound": {
    "protocol": "dokodemo-door",
    "settings": {
        "network": "tcp,udp",
        "timeout": 30,
        "followRedirect": true
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "[redacted]", 
          "port": [redacted],
          "users": [
            {
              "id": "[redacted]", 
              "alterId": [redacted]
            }
          ]
        }
      ]
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "port": "54-79",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "81-442",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "444-65535",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "domain": [
            "gc.kis.scr.kaspersky-labs.com"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        }
      ]
    }
  }
}

```

**Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.**

**Server Log File**
```
    // Please attach your server log here.
[inapplicable]
```

**Client Log File**
```
    // Please attach your client log here.
[none]
```

**Comment by DarienRaymond** [comment]
V2Ray doesn't close inbound/outbound connections unless the other end is closed by peer. In this case, you need to confirm curl or the http server on router closes the http connection. It will be a bug if either of those closes the connection, but V2Ray doesn't act accordingly.

**Comment by KireinaHoro** [comment]
@DarienRaymond The router is closing the connection properly because if I don't configure the redirection to v2ray curl returns elegantly with 

    * Closing connection 0

**Comment by DarienRaymond** [comment]
As mentioned above, V2Ray can't tell whether the payload is HTTP 1.0, 1.1 or others, so it can't treat connection differently. The only way to close a connection more quickly is to adjust the timeout settings. In the next release, default timeout in such case will be reduced to 2 seconds (from 2 minutes). Hopefully the issue will be solved.

The updated timeout only affects the end of connection. It won't interrupt connections when there is still data being transferred.
