### ISSUE TITLE
关于动态端口的需求

### ISSUE THREAD

**Issue by zhfreal** [v2ray/v2ray-core#552]
首先，很抱歉没有按模板填写。

经过反复试验，发现目前的动态端口对于正在传输数据的连接，应该是不切换端口的。

我的应用场景是v2ay代理openvpn。两者都是tcp模式。openvpn一旦连上之后，会持续传输数据，tcp连接一直保持。通过抓包分析，v2ray一直使用同一个端口传输数据，直到openvpn重新连接才可能切换端口。
对于这种连续传输数据的场景，能不能在定时器到时后也切换端口呢？目前运营商对这种长连接qos比较厉害，如果v2ray能在这种场景下也切换端口，那就再好不过了。

**Comment by DarienRaymond** [comment]
这个暂时做不了，要做的话会在mux中加入类似的特性。
