### ISSUE TITLE
vmess协议目前是否支持UDP封装转发？

### ISSUE THREAD

**Issue by auiny** [v2ray/v2ray-core#553]
试过2.34版本的vmess并不支持，作者后续是否能加入这个功能？
如果现在就可以实现，请介绍一下方案。（不依靠shadowsocks链路）

**Comment by DarienRaymond** [comment]
请详细描述UDP封装转发是什么以及你是怎么测试的

**Comment by auiny** [comment]
客户端、服务端均使用2.34版本
使用协议：ws+tls
UDP封装转发描述：UDP over TCP
测试途径：Super Socks5Cap和SSTap转发流量至socks通道的v2ray，并且v2ray配置文件中已开启udp接收。
测试结果：未发现异常日志，但是UDP包无法转发，表现为无法进入游戏，但可以打开网页。用相同软件+ss-libev则完全正常。

**Comment by DarienRaymond** [comment]
发配置文件和错误信息（如果有的话）

**Comment by auiny** [comment]
{"log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 443,
    "protocol": "vmess",
    "settings": {
        "clients": [
            {
                "id": "af01151d-db30-4dbd-ab43-ecc762253c54",
                "level": 1,
                "alterId": 32
            }
        ]
    },

   "streamSettings": {
      "network": "ws",
      "security": "tls",
       "tlsSettings": {
        "certificates": [
          {
            "certificateFile": "/root/domian/fullchain.pem",
            "keyFile": "/root/domian/privkey.pem"
          }
        ]
      },
      "tcpSettings": null,
      "kcpSettings": null,
      "wsSettings": {
        "connectionReuse": true
      }
    }
    
  },


  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  

  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],

  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"

      ]
    }
  }
}

**Comment by auiny** [comment]
不要在意底下的错误，那是我自己写的一段网址屏蔽没删干净。

**Comment by BirkhoffLee** [comment]
+1, this will be very useful when being behind a highly restricted firewall that only allows UDP connections

**Comment by Cwek** [comment]
可以考虑底层传输用kcp，kcp是走UDP的。

**Comment by DarienRaymond** [comment]
你发的是服务器配置。发客户端配置看一下，顺便把客户端loglevel设成debug看一下详细的log。

**Comment by DarienRaymond** [comment]
Possibly https://github.com/v2ray/Planning/issues/45
