### ISSUE TITLE
吐槽一下，这个网址 https://www.v2ray.com/ 的文档写的有够垃圾

### ISSUE THREAD

**Issue by ohsorry** [v2ray/v2ray-core#555]
吐槽一下，这个网址 https://www.v2ray.com/ 的文档写的有够垃圾
就从使用文档就让我对这个项目失去了兴趣
我作为一个好几年的程序员我硬是没看懂怎么用
为什么不准备一个tutorial

程序写出来是让人用的，半天都看不明白怎么用你开源什么
号称模块化竟然连个清晰结构的文档都没有。
起的这个V2Ray名字就不吐槽了。

开源的项目代码一定要足够清晰、简单，不然你的项目不丢人吗
需要介绍下tutorial怎么写吗？
首先你要给出完整的使用流程、如果支持多种工作方式那就多写几个tutorial，让别人可以直接选择，让小白也能够改配置、能够举一反三。
你要乐意可以把reference也写一下
看到这种很烂还很多星的项目，直接差评！

**Comment by Voleking** [comment]
虽然我也觉得文档不是很好，但你连标题都写不好。

少一些问号、感叹号以及语气较强的表达方式，除非你一开始就抱着发泄的目的。开源社区没有谁应该的。

**Comment by DarienRaymond** [comment]
看不懂请回炉重炼。

**Comment by wtlusvm** [comment]
> 我作为一个好几年的程序员我硬是没看懂怎么用

好几年的程序员了，看不懂你自己实现一个工具不是更快吗

**Comment by call4242564** [comment]
开源项目的好处就是当作者不维护 且 项目有bug时 可以自己搞定。
你可以提建议  但是态度至少要有吧。
爱用用 不用*

**Comment by ouguajian** [comment]
原来还有这样的奇葩哦

**Comment by ohsorry** [comment]
敢开源证明有勇气，技术怎么样是另外一回事。这样的项目都坚定拥护可见你们的技术，要么刚毕业要么是外行？多写点程序、多学点技术，回头再来看你今天flow的什么开源项目。flow一个项目证明这里还有你需要学习的，对改bug感兴趣那你还真是个人才。

**Comment by wtlusvm** [comment]
@ohsorry 对啊，你技术牛你就自己写个工具开源出来，让我们夸你厉害不就好了，在这瞎吹还浪费时间

**Comment by ohsorry** [comment]
一般像你这种说话方式的都是那种在学习和工作中爱bb的水货，不用回复了。

**Comment by wtlusvm** [comment]
@ohsorry 哇水货反咬一口，害怕

**Comment by hzxswyg** [comment]
我作为一个不懂代码的小白，我都根据文档自己完成了服务端客户端的配置，还是websocket over tls并实现了nginx反向代理。楼主加油。
