### ISSUE TITLE
需要安装socat吗？

### ISSUE THREAD

**Issue by keaidejia5** [v2ray/v2ray-core#556]
![photo_2017-09-04_18-01-46](https://user-images.githubusercontent.com/29628114/30023269-3f8cff72-91a1-11e7-98c9-e16a23577a40.jpg)

需要安装socat吗？
若需要的话，有教程吗？

**Comment by DarienRaymond** [comment]
你这个是lets encrypt的安装脚本？或者某个第三方集成脚本？V2Ray本身不需要socat

**Comment by keaidejia5** [comment]
弄证书问题，想不到提示这个，算了，不理这个吧。。
