### ISSUE TITLE
ECC证书生成问题？

### ISSUE THREAD

**Issue by keaidejia5** [v2ray/v2ray-core#557]
[https://i.loli.net/2017/09/04/59ad4a0499727.jpg](url)
有人知道这是什么问题吗？

**Comment by keaidejia5** [comment]
![photo_2017-09-04_18-01-46](https://user-images.githubusercontent.com/29628114/30027000-be38f014-91b1-11e7-9165-c23514860a53.jpg)

**Comment by DarienRaymond** [comment]
除非你能说明这个问题和V2Ray有关，这个issue将会被关闭。
