### ISSUE TITLE
Dokodemo-door+ TPROXY 透明代理故障

### ISSUE THREAD

**Issue by p4insh11** [v2ray/v2ray-core#559]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
    **2.3.4**
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
    **Dokodemo-door+ TPROXY 透明代理，客户端是archlinux软路由**
3)  你看到的不正常的现象是什么？
    What did you see?
    **无法打开网页 ，额外启动socket做inbound可以正常上国外网站，国内访问有问题**
4)  你期待看到的正确表现是怎样的？
    What's your expectation?
    **正常使用网页**
5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Server Configuration File（服务器端配置文件）:
```javascript
    // 在这里附上服务器端配置文件
    // Please attach your server configuration file here.
```
   {
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 11122,
    "protocol": "vmess",
    "settings": {
        "udp": true,
        "clients": [
        {
          "id": "UUID1",
          "alterId": 55,
          "level": 1,
          "mail": "xxx@xxx.com"
        },
        {
          "id": "UUID2",
          "alterId": 66,
          "level": 1,
          "mail": "xxx@xxx.com"
        },
        {
          "id": "UUID3",
          "alterId": 98,
          "level": 1,
          "mail": "xxx@xxx.com"
        }
      ]
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",                  
    "settings": {
      "rules": [         
        {
          "type": "field",
          "ip": [ 
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",     
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",  
            "fc00::/7",
            "fe80::/10" 
          ],         
          "outboundTag": "blocked" 
        }
      ]
    }
  } 
}      

    Client Configuration File（客户端配置文件）:
```javascript
    // 在这里附上客户端配置文件
    // Please attach your client configuration file here.
```
  
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "debug"
  },
  "inbound":
    {
      "protocol":"dokodemo-door",
      "port":7227,
      "settings":{
        "address": "",
        "network": "tcp,udp",
        "timeout": 0,
        "followRedirect": true
      }
  },
  "outbound": {
    "tag": "agentout",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "111.111.111.111",
          "port": 11122,
          "users": [
            {
              "id": "UUID1",
              "alterId": 55,
              "security": "aes-128-gcm"
            }
          ]
        }
      ]
    },
    "mux": {
      "enabled": true
    }
  },
  "inboundDetour": null,
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {
        "response": null
      },
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "blockout"
    }
  ],
  "dns": {
    "servers": [
      "localhost"
    ]
  }
}

6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.

    Server Log File（服务器端日志）:
```
    // 在这里附上服务器端日志
    // Please attach your server log here.
```

    Client Log File（客户端日志）:
```
    // 在这里附上客户端日志
    // Please attach your client log here.
```
  2017/09/06 06:59:49 [Info]Transport|Internet|TCP: listening TCP on 0.0.0.0:7227
2017/09/06 06:59:49 [Info]Transport|Internet|UDP: listening UDP on 0.0.0.0:7227
2017/09/06 06:59:49 [Warning]Core: V2Ray started
2017/09/06 06:59:50 [Debug]Proxy|Dokodemo: processing connection from: 172.16.30.110:62595
2017/09/06 06:59:50 [Info]App|Proxyman|Mux: dispatching request to udp:172.16.30.1:53
2017/09/06 06:59:50 [Info]Transport|Internet|TCP: dailing TCP to tcp:111.111.111.111:11122
2017/09/06 06:59:50 [Info]Proxy|VMess|Outbound: tunneling request to tcp:v1.mux.cool:9527 via tcp:111.111.111.111:11122
2017/09/06 06:59:52 [Debug]Proxy|Dokodemo: processing connection from: 172.16.30.200:27847
2017/09/06 06:59:52 [Debug]Proxy|Dokodemo: processing connection from: 172.16.30.200:16720
2017/09/06 06:59:52 [Info]App|Proxyman|Mux: dispatching request to udp:172.16.30.1:53
2017/09/06 06:59:52 [Info]App|Proxyman|Mux: dispatching request to udp:172.16.30.1:53
2017/09/06 06:59:53 [Debug]Proxy|Dokodemo: processing connection from: 172.16.30.110:49874
2017/09/06 06:59:53 [Info]App|Proxyman|Mux: dispatching request to udp:172.16.30.1:53
2017/09/06 06:59:54 [Info]App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport request > io: read/write on closed pipe
2017/09/06 06:59:55 [Debug]Proxy|Dokodemo: processing connection from: 172.16.30.200:13359
2017/09/06 06:59:55 [Info]App|Proxyman|Mux: dispatching request to udp:172.16.30.1:53
2017/09/06 06:59:56 [Info]App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport request > io: read/write on closed pipe
2017/09/06 06:59:57 [Debug]Proxy|Dokodemo: processing connection from: 172.16.30.110:53628
2017/09/06 06:59:57 [Info]App|Proxyman|Mux: dispatching request to udp:172.16.30.1:53
2017/09/06 06:59:57 [Debug]Proxy|Dokodemo: processing connection from: 172.16.30.200:16918
2017/09/06 06:59:57 [Info]App|Proxyman|Mux: dispatching request to udp:172.16.30.1:53
2017/09/06 06:59:58 [Debug]Proxy|Dokodemo: processing connection from: 172.16.30.110:57290
2017/09/06 06:59:58 [Info]App|Proxyman|Mux: dispatching request to udp:172.16.30.1:53
2017/09/06 06:59:59 [Info]App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport request > io: read/write on closed pipe
2017/09/06 07:00:00 [Info]App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport request > io: read/write on closed pipe
2017/09/06 07:00:00 [Info]App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport request > io: read/write on closed pipe
2017/09/06 07:00:01 [Debug]Proxy|Dokodemo: processing connection from: 172.16.30.110:53628
2017/09/06 07:00:01 [Info]App|Proxyman|Mux: dispatching request to udp:172.16.30.1:53
2017/09/06 07:00:02 [Debug]Proxy|Dokodemo: processing connection from: 172.16.30.110:57290
2017/09/06 07:00:02 [Info]App|Proxyman|Mux: dispatching request to udp:172.16.30.1:53
2017/09/06 07:00:02 [Info]App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport request > io: read/write on closed pipe
2017/09/06 07:00:05 [Info]App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > context canceled
2017/09/06 07:00:05 [Info]App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > context canceled
2017/09/06 07:00:05 [Info]App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport request > io: read/write on closed pipe
2017/09/06 07:00:06 [Info]App|Proxyman|Mux: failed to read metadata > io: read/write on closed pipe
2017/09/06 07:00:06 [Info]App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport request > io: read/write on closed pipe
2017/09/06 07:00:07 [Debug]Proxy|Dokodemo: processing connection from: 172.16.30.200:8349
2017/09/06 07:00:07 [Info]App|Proxyman|Mux: dispatching request to udp:172.16.30.1:53
2017/09/06 07:00:07 [Info]Transport|Internet|TCP: dailing TCP to tcp:111.111.111.111:11122
2017/09/06 07:00:07 [Info]Proxy|VMess|Outbound: tunneling request to tcp:v1.mux.cool:9527 via tcp:111.111.111.111:11122
2017/09/06 07:00:10 [Debug]Proxy|Dokodemo: processing connection from: 172.16.30.110:50191
2017/09/06 07:00:10 [Info]App|Proxyman|Mux: dispatching request to udp:172.16.30.1:53
2017/09/06 07:00:12 [Info]App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport request > io: read/write on closed pipe
2017/09/06 07:00:12 [Info]App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport request > io: read/write on closed pipe
2017/09/06 07:00:14 [Debug]Proxy|Dokodemo: processing connection from: 172.16.30.110:50191
2017/09/06 07:00:14 [Info]App|Proxyman|Mux: dispatching request to udp:172.16.30.1:53
2017/09/06 07:00:17 [Debug]Proxy|Dokodemo: processing connection from: 172.16.30.149:59588
2017/09/06 07:00:17 [Info]App|Proxyman|Mux: dispatching request to udp:172.16.30.1:53
2017/09/06 07:00:18 [Info]App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport request > io: read/write on closed pipe
2017/09/06 07:00:19 [Debug]Proxy|Dokodemo: processing connection from: 172.16.30.110:65200
2017/09/06 07:00:19 [Info]App|Proxyman|Mux: dispatching request to udp:172.16.30.1:53
2017/09/06 07:00:21 [Info]App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport request > io: read/write on closed pipe
2017/09/06 07:00:21 [Info]App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport request > io: read/write on closed pipe
2017/09/06 07:00:22 [Debug]Proxy|Dokodemo: processing connection from: 172.16.30.110:55365
2017/09/06 07:00:22 [Info]App|Proxyman|Mux: dispatching request to udp:172.16.30.1:53
2017/09/06 07:00:23 [Debug]Proxy|Dokodemo: processing connection from: 172.16.30.110:65200
2017/09/06 07:00:23 [Info]App|Proxyman|Mux: dispatching request to udp:172.16.30.1:53
2017/09/06 07:00:24 [Info]App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport request > io: read/write on closed pipe
2017/09/06 07:00:24 [Debug]Proxy|Dokodemo: processing connection from: 172.16.30.121:53096
2017/09/06 07:00:24 [Debug]Proxy|Dokodemo: processing connection from: 172.16.30.121:57311
2017/09/06 07:00:24 [Info]App|Proxyman|Mux: dispatching request to udp:172.16.30.1:53
2017/09/06 07:00:24 [Info]App|Proxyman|Mux: dispatching request to udp:172.16.30.1:53
2017/09/06 07:00:26 [Debug]Proxy|Dokodemo: processing connection from: 172.16.30.110:55365
2017/09/06 07:00:26 [Info]App|Proxyman|Mux: dispatching request to udp:172.16.30.1:53
2017/09/06 07:00:27 [Info]App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport request > io: read/write on closed pipe
2017/09/06 07:00:27 [Debug]Proxy|Dokodemo: processing connection from: 172.16.30.110:58309
2017/09/06 07:00:27 [Info]App|Proxyman|Mux: dispatching request to udp:172.16.30.1:53
2017/09/06 07:00:27 [Debug]Proxy|Dokodemo: processing connection from: 172.16.30.149:59588
2017/09/06 07:00:27 [Info]App|Proxyman|Mux: dispatching request to udp:172.16.30.1:53
2017/09/06 07:00:27 [Info]App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport request > io: read/write on closed pipe
2017/09/06 07:00:27 [Info]App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport request > io: read/write on closed pipe
2017/09/06 07:00:29 [Info]App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport request > io: read/write on closed pipe
2017/09/06 07:00:30 [Info]App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport request > io: read/write on closed pipe
2017/09/06 07:00:31 [Debug]Proxy|Dokodemo: processing connection from: 172.16.30.110:58309
2017/09/06 07:00:31 [Info]App|Proxyman|Mux: dispatching request to udp:172.16.30.1:53
2017/09/06 07:00:31 [Info]App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport request > io: read/write on closed pipe
2017/09/06 07:00:31 [Debug]Proxy|Dokodemo: processing connection from: 172.16.30.121:53096
2017/09/06 07:00:31 [Debug]Proxy|Dokodemo: processing connection from: 172.16.30.121:57311
2017/09/06 07:00:31 [Info]App|Proxyman|Mux: dispatching request to udp:172.16.30.1:53
2017/09/06 07:00:31 [Info]App|Proxyman|Mux: dispatching request to udp:172.16.30.1:53

iptables 如下
iptables -t nat -N V2RAY
iptables -t mangle -N V2RAY
iptables -t mangle -N V2RAY_MARK
iptables -t nat -A V2RAY -d 111.111.111.111 -j RETURN
iptables -t nat -A V2RAY -d 0.0.0.0/8 -j RETURN
iptables -t nat -A V2RAY -d 10.0.0.0/8 -j RETURN
iptables -t nat -A V2RAY -d 127.0.0.0/8 -j RETURN
iptables -t nat -A V2RAY -d 169.254.0.0/16 -j RETURN
iptables -t nat -A V2RAY -d 172.16.0.0/12 -j RETURN
iptables -t nat -A V2RAY -d 192.168.0.0/16 -j RETURN
iptables -t nat -A V2RAY -d 224.0.0.0/4 -j RETURN
iptables -t nat -A V2RAY -d 240.0.0.0/4 -j RETURN
iptables -t nat -A V2RAY -p tcp -j REDIRECT --to-ports 7227
ip rule add fwmark 0x01/0x01 table 100 
ip route add local 0.0.0.0/0 dev lo table 100
iptables -t mangle -A V2RAY -p udp --dport 53 -j TPROXY --on-port 7227 --tproxy-mark 0x01/0x01
iptables -t mangle -A V2RAY_MARK -p udp --dport 53 -j MARK --set-mark 1
iptables -t nat -A OUTPUT -p tcp -j V2RAY
iptables -t mangle -A PREROUTING -j V2RAY
iptables -t mangle -A OUTPUT -j V2RAY_MARK

resolv.conf 如下
nameserver  = 8.8.8.8

**Comment by p4insh11** [comment]
明白怎么回事了，官方文档写的真好，自己关闭了

**Comment by lswen** [comment]
怎么回事啊。。。。我udp一直不能代理。。。。

**Comment by xiatiansong** [comment]
@p4insh11   能把成功的配置贴出来参考一下么？我的还没成功
