### ISSUE TITLE
[Doc] 解决网站打开卡，慢的一条可能的解决方案

### ISSUE THREAD

**Issue by netroby** [v2ray/v2ray-core#560]
经过多日连续的观察，发现v2ray代理，在使用过程中，经常遇到无法打开网页，或者很慢的情况。
造成的原因，多半是dns解析的问题。

于是想到用dnscache解决。部署一个dnscache代理于你的v2ray server, 然后设置client的dns servers配置段，加上自己的dnscache, 问题就完美解决了。
```json
"dns": {
                        "server":[
                               "192.*.*.*", //这里是dnscache监听的ip
                                "208.67.222.222",
                                "208.67.220.220"
                        ]
  }

```

附 : https://github.com/netroby/dnscache

**Comment by q158073378252010** [comment]
他们的通病可能是在 chrome 使用了 “**SwitchyOmega**” 扩展来接管 **代理**

**Comment by netroby** [comment]
我也用switchyOmega

**Comment by netroby** [comment]
问题不是这个chrome扩展

**Comment by fanck0605** [comment]
也许可以为v2ray添加dns缓存以加快解析速度

**Comment by wonderffee** [comment]
有点糊涂，部署一个dnscache代理于你的v2ray server，是不是意味着dnscache监听的ip跟v2ray server的ip一模一样，所以标注红色的那一行的ip应该就是v2ray server的ip？

**Comment by otakuchiyan** [comment]
@wonderffee 我个人的理解是 dnscache 启动的 IP, 例如 dnsmasq, DNSCrypt 之类的东西。因为这个 server 字段是从上到下查询的，你也可以去掉红色那一行，直接抄剩下的配置，那是 OpenDNS.
我这样一改，也解决了这个问题。

**Comment by DarienRaymond** [comment]
DNS 的问题会在下一版本修复。
