### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by pkron** [v2ray/v2ray-core#561]
正在使用的版本：v2.36.3 64位（Windows10 X64）
你的使用场景是：通过Firefox浏览网页
看到的不正常是：显示 panic: runtime error: slice bounds out of range，代理服务停止
你期待看到的是：没有错误提示，正常运行。
附上的配置文件：

[config.json.txt](https://github.com/v2ray/v2ray-core/files/1280238/config.json.txt)

出错时软件输出：

panic: runtime error: slice bounds out of range

goroutine 9953 [running]:
v2ray.com/core/common/buf.(*Buffer).Bytes(...)
        src/v2ray.com/core/common/buf/buffer.go:74
v2ray.com/core/proxy/socks.ClientHandshake(0xc044605f80, 0x1ea3d8, 0xc042065118, 0xacc1e0, 0xc042065118, 0x1, 0xc043f3b1dd, 0xc)
        src/v2ray.com/core/proxy/socks/protocol.go:416 +0x1358
v2ray.com/core/proxy/socks.(*Client).Process(0xc04203afe0, 0xad39e0, 0xc043f8b1a0, 0x1ea400, 0xc044454e20, 0xaccca0, 0xc042042e40, 0x0, 0x0)
        src/v2ray.com/core/proxy/socks/client.go:82 +0x49c
v2ray.com/core/app/proxyman/outbound.(*Handler).Dispatch(0xc042042e40, 0xad39e0, 0xc043f8b1a0, 0x1ea400, 0xc044454e20)
        src/v2ray.com/core/app/proxyman/outbound/handler.go:84 +0x1e9
v2ray.com/core/app/dispatcher/impl.(*DefaultDispatcher).routedDispatch(0xc04370cd80, 0xad39e0, 0xc043f8b1a0, 0x1ea400, 0xc044454e20, 0x5000000002, 0xad4160, 0xc044454df0)
        src/v2ray.com/core/app/dispatcher/impl/default.go:135 +0xa8
created by v2ray.com/core/app/dispatcher/impl.(*DefaultDispatcher).Dispatch
        src/v2ray.com/core/app/dispatcher/impl/default.go:76 +0x45d

**Comment by q158073378252010** [comment]
直接 命令行 还是 gui配置？

**Comment by pkron** [comment]
没有GUI配置，我是自己写的CONFIG.JSON文件，用自己的Launcher.exe隐藏窗口~
我发现打开 大纪元 网站特别容易出现这种错误。

**Comment by pkron** [comment]
2017/09/07 10:31:27 [Info]Proxy|HTTP: request to Method [GET] Host [keljkdioisjsoiejlffjlaskjehehwkmvncooeopwoeowqmnmnenqqwpovhl.encoretvb.com] with URL [http://keljkdioisjsoiejlffjlaskjehehwkmvncooeopwoeowqmnmnenqqwpovhl.encoretvb.com/]
2017/09/07 10:31:27 [Info]App|Router: looking up IP for tcp:keljkdioisjsoiejlffjlaskjehehwkmvncooeopwoeowqmnmnenqqwpovhl.encoretvb.com:80
2017/09/07 10:31:27 [Info]App|Dispatcher|Default: default route for tcp:keljkdioisjsoiejlffjlaskjehehwkmvncooeopwoeowqmnmnenqqwpovhl.encoretvb.com:80
2017/09/07 10:31:27 [Info]Transport|Internet|TCP: dailing TCP to tcp:127.0.0.1:2080
panic: runtime error: slice bounds out of range

goroutine 7 [running]:
v2ray.com/core/common/buf.(*Buffer).Bytes(...)
        src/v2ray.com/core/common/buf/buffer.go:74
v2ray.com/core/proxy/socks.ClientHandshake(0xc043760540, 0xd56060, 0xc042004040, 0xacc1e0, 0xc042004040, 0x1, 0xc042018070, 0xc042018000)
        src/v2ray.com/core/proxy/socks/protocol.go:416 +0x1358
v2ray.com/core/proxy/socks.(*Client).Process(0xc04203afe0, 0xad39e0, 0xc04376e180, 0xd560b0, 0xc04375c0e0, 0xaccca0, 0xc042042e00, 0x0, 0x0)
        src/v2ray.com/core/proxy/socks/client.go:82 +0x49c
v2ray.com/core/app/proxyman/outbound.(*Handler).Dispatch(0xc042042e00, 0xad39e0, 0xc04376e180, 0xd560b0, 0xc04375c0e0)
        src/v2ray.com/core/app/proxyman/outbound/handler.go:84 +0x1e9
v2ray.com/core/app/dispatcher/impl.(*DefaultDispatcher).routedDispatch(0xc04370ad60, 0xad39e0, 0xc04376e180, 0xd560b0, 0xc04375c0e0, 0x5000000002, 0xad4160, 0xc04375c0b0)
        src/v2ray.com/core/app/dispatcher/impl/default.go:135 +0xa8
created by v2ray.com/core/app/dispatcher/impl.(*DefaultDispatcher).Dispatch
        src/v2ray.com/core/app/dispatcher/impl/default.go:76 +0x45d

怀疑是域名过长导致

**Comment by q158073378252010** [comment]
这是预编译版本？

**Comment by DarienRaymond** [comment]
你的socks代理配置了密码之类的？

**Comment by pkron** [comment]
socks 代理是 Kcptun ，没有密码~

**Comment by DarienRaymond** [comment]
会在下一版本修复

**Comment by pkron** [comment]
新版 v2.37 Firefox浏览超长域名还是会出错，建议检查输入长度，以防止恶意攻击。
aaaaaaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.tumblr.com


V2Ray v2.37 (One for all) 20170907
An unified platform for anti-censorship.
2017/09/15 09:53:54 [Debug]App|Proxyman|Inbound: creating tcp worker on 0.0.0.0:8080
2017/09/15 09:53:55 [Info]Transport|Internet|TCP: listening TCP on 0.0.0.0:8080
2017/09/15 09:53:55 [Warning]Core: V2Ray started
panic: runtime error: slice bounds out of range

goroutine 10 [running]:
v2ray.com/core/common/buf.(*Buffer).Bytes(...)
        src/v2ray.com/core/common/buf/buffer.go:74
v2ray.com/core/proxy/socks.ClientHandshake(0xc043768360, 0xdb8618, 0xc042004020, 0xacc1e0, 0xc042004020, 0xc043768101, 0xc043773d38, 0x410871)
        src/v2ray.com/core/proxy/socks/protocol.go:416 +0x1358
v2ray.com/core/proxy/socks.(*Client).Process(0xc04203b000, 0xad39e0, 0xc04353b4d0, 0xdb8640, 0xc043720e90, 0xaccca0, 0xc042042f00, 0x0, 0x0)
        src/v2ray.com/core/proxy/socks/client.go:82 +0x49c
v2ray.com/core/app/proxyman/outbound.(*Handler).Dispatch(0xc042042f00, 0xad39e0, 0xc04353b4d0, 0xdb8640, 0xc043720e90)
        src/v2ray.com/core/app/proxyman/outbound/handler.go:83 +0x1e9
v2ray.com/core/app/dispatcher/impl.(*DefaultDispatcher).routedDispatch(0xc04370d080, 0xad39e0, 0xc04353b4d0, 0xdb8640, 0xc043720e90, 0x5000000002, 0xad4160, 0xc043720e60)
        src/v2ray.com/core/app/dispatcher/impl/default.go:135 +0xa8
created by v2ray.com/core/app/dispatcher/impl.(*DefaultDispatcher).Dispatch
        src/v2ray.com/core/app/dispatcher/impl/default.go:76 +0x45d

**Comment by strahe** [comment]
3.1 版本也遇到这个问题了
