### ISSUE TITLE
windows版中的conf.exe有什么用的？

### ISSUE THREAD

**Issue by himan85** [v2ray/v2ray-core#562]
如题，发现2.34开始多了conf.exe文件，readme.md中没有说明用途，打开貌似跟主程序是一样的？想搞清楚是什么用途的？谢谢!

**Comment by DarienRaymond** [comment]
是一个配置文件转换工具，目前此工具的功能在v2ray.exe中包含，将来会被拆分出去。

**Comment by q158073378252010** [comment]
@DarienRaymond  可我检查 hash
发现与vray一致是什么鬼？

**Comment by DarienRaymond** [comment]
因为有bug呗😂

**Comment by DarienRaymond** [comment]
conf(.exe)的作用会在之后的版本中说明。

**Comment by vtroop** [comment]
大雾，，powershell测试了一下这个软件 `conf.exe -h`
输出为`Usage of conf.exe:`

作者你偷懒
