### ISSUE TITLE
websocket列入传输设置是否不妥

### ISSUE THREAD

**Issue by flyingwhitewhale** [v2ray/v2ray-core#563]
计算机小白查了下OSI七层模型
WEBSOCKET和HTTPS都是在应用层
而TCP和UDP/mKCP才是在传输层
在设置里将websocket和TCP,MKCP并列为传输设置是否不妥呢
还是有我等无知之处，请指点

**Comment by DarienRaymond** [comment]
V2Ray对传输层的定义是“把数据准确传到服务器”，至于中间有没有协商或其它加密机制，不属于定义范畴，这点和OSI中的定义不同。

**Comment by flyingwhitewhale** [comment]
谢谢大佬
