### ISSUE TITLE
关于 release 中的 metadata.txt 文件，以及下载后批量校验的相关建议。

### ISSUE THREAD

**Issue by neatgz** [v2ray/v2ray-core#564]
1、目前  metadata.txt 里的格式是类似这样：
File: v2ray-windows-32.zip
Size: 7601919
SHA1: ddac3e3ac0755399d2c6d08abe8d2a01d5105e66
不知道是不是我孤陋寡闻，不晓得目前的  metadata.txt 文件是如何生成的？
假定  metadata.txt 文件和一系列 v2ray-xxx-xx.zip 都下载下来后，有何种办法可以批量校验完整性吗？

2、建议的方法和 metadata.txt 文件格式：

a. Linux下使用 md5sum 命令生成 metadata.txt 文件：
假定一系列的 v2ray-xxx-xx.zip 文件都位于 /root/v2ray-core-237 下
find /root/v2ray-core-237 -type f | xargs  md5sum > metadata.txt.md5
使用此命令生成的 metadata.txt.md5 文件里包含文件的路径信息，故推荐下列方案：
cd /root/v2ray-core-237
find -type f | xargs  md5sum > metadata.txt.md5        // 生成md5
find -type f | xargs  sha1sum > metadata.txt.sha1       // 生成sha1

Linux下使用 diff 命令批量校验文件完整性：
find -type f | xargs  md5sum > metadata_generated_myself.txt.md5        // 根据已下载的一系列的 v2ray-xxx-xx.zip 包，自己批量生成md5
wget https://xxxxxxxxxxxxxxxxxxxxxxx/metadata.txt.md5                   // 获取作者提供的 metadata.txt.md5
diff metadata.txt.md5 metadata_generated_myself.txt.md5                 // 比较二者异同

b. Win 和 Mac 下，批量生成 metadata.txt 文件和 批量校验完整性的小工具比较多。不再赘述，截图一个。
![default](https://user-images.githubusercontent.com/22790906/30232560-3e1a8d8c-9523-11e7-918f-d8e487b8c894.PNG)

使用上述说明的方法生成的 metadata.txt.md5 文件，全平台通用，无论是生成，还是下载后批量校验都是无缝无痛的。
请作者酌情考虑。
另：如果目前的 metadata.txt 文件，有办法下载后批量校验，那么就是我孤陋寡闻了，请告知如何做。
谢谢。
另外使用简单方便的 .sfv 文件也是不错的选择。

**Comment by DarienRaymond** [comment]
最初没有考虑过批量验证的做法，因为安装包里包含配置文件，完全有可能仅由于配置文件改变，重新打包之后md5的值改变。安全的验证方法是把压缩包解开之后，验证二进制文件的gpg签名。
