### ISSUE TITLE
建议给v2ray加个压缩功能，比如支持lz4等

### ISSUE THREAD

**Issue by zdm2008** [v2ray/v2ray-core#566]
建议给v2ray加个压缩功能，比如支持lz4等，希望这个需求能实现，谢谢。

**Comment by luolufang** [comment]
那嵌入式设备怕是要性能爆炸

2017年9月10日 下午3:25，"zdm2008" <notifications@github.com>写道：

**Comment by cryptogun** [comment]
底层的东西只管传输吧。大流量的东西大部分是视频或者图片，不能再压缩了。压缩也只是白白浪费时间和CPU。网页大部分也是gzip后传输，即使明知道HTTPS+压缩不安全。当然应该做个测试再比较决定要不要支持压缩。还要考虑到低端路由器的消耗。

**Comment by DarienRaymond** [comment]
基本不会考虑压缩，至少不会提供通用压缩算法，一般来说现有流量已经是压缩过的，比如网页用的gzip，再次压缩性价比不高。
