### ISSUE TITLE
VMess User level Issue

### ISSUE THREAD

**Issue by jinyu121** [v2ray/v2ray-core#569]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

Latest

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

Chrome->Socks->VMess->       VMess(dynamic port)->Freedom

3)  你看到的不正常的现象是什么？
    What did you see?

I switched my user level to 0 (which means "strict" level), and so many things happened.

1. The speed is slower. When the user level is 1, it's ~3MB/s. But when the user level is 0, ~1MB/s. It's based on several tests.
2. The connection speed is slower. I tested this in Chrome with Switch sharp. When the user level is 1, I can open gist.github.com in seconds. But when the level is 0, I can see "waiting for response....." for a loooooooooooong time(~30s) and "establishing security connection" for a loooong time (~10s). 
3. When the level is 1, I can open my computer at morning, leave it alone, and when back to my computer at night, it works fine, not only speed/connection but also the log. But when switch user level to 0, when I come back to my computer at night, VR seems not working. I can not connect with other websites through VR, and server log booms, filled with `[Warning]Transport|Internet|TCP: failed to accepted raw connections > Retry: [accept tcp [::]:63363: use of closed network connection] > Retry: all retry attempts failed` and the like. I tried to restart the VR process/service both on server and client, not working. So I have to reboot my client computer, OK.

In a word, if your VMess working incorrect, try  to set user level to 1.

I wonder what exactly "user level =0" did?(Oh I remember that you posted it about a year ago... but I forgot that post)

4)  你期待看到的正确表现是怎样的？
    What's your expectation?

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).

    seam as demo `socks_vmess.config`

    Server Configuration File（服务器端配置文件）:

    seam as demo `vmess_freedom.config`

6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.

    Server Log File（服务器端日志）:
```
    [Warning]Transport|Internet|TCP: failed to accepted raw connections > Retry: [accept tcp [::]:63363: use of closed network connection] > Retry: all retry attempts failed
```

**Comment by hzxswyg** [comment]
According to the official documentation: when the user level is 0, this user is not trusted, v2ray will apply more strict security restrictions to this user[1].
Moreover, referring to this [issue#429](https://github.com/v2ray/v2ray-core/issues/429), user level actually means Timeout setting, when the user lever greater than 0, this user has a longer timeout.
[1] https://www.v2ray.com/chapter_02/protocols/vmess.html

**Comment by DarienRaymond** [comment]
I have no idea how this happens. As mentioned above, user level only affects timeout. In another word, if the connection doesn't timeout, the speed should be the same.

**Comment by DarienRaymond** [comment]
Closing due to lack of information.
