### ISSUE TITLE
通过 Firefox 浏览 “微信公众平台” 经常被卡住

### ISSUE THREAD

**Issue by pkron** [v2ray/v2ray-core#573]
正在使用的版本：v2.38 (20170921) 64位（Windows10 X64）

你的使用场景是：通过Firefox浏览“微信公众平台”(后台)

看到的不正常是：部分网页被卡住（Firefox显示“等待 mp.weixin.qq.com...”），需要重启v2ray后可继续访问

你期待看到的是：不会被卡住，不需要重启v2ray

附上的配置文件： https://github.com/v2ray/v2ray-core/files/1280238/config.json.txt

出错时软件输出：（可能相关的日志，有时又没有日志输出）

2017/09/22 11:02:40 [Info]App|Proxyman|Inbound: connection ends > Proxy|HTTP: connection ends > context canceled
2017/09/22 11:02:40 [Info]App|Proxyman|Outbound: failed to process outbound traffic > Proxy|Socks: connection ends > context canceled
2017/09/22 11:04:20 [Info]App|Proxyman|Outbound: failed to process outbound traffic > Proxy|Freedom: connection ends > context canceled

2017/09/22 11:04:32 [Info]App|Proxyman|Inbound: connection ends > Proxy|HTTP: failed to read http request > EOF
2017/09/22 11:04:32 [Info]App|Proxyman|Inbound: connection ends > Proxy|HTTP: failed to read http request > EOF

**Comment by wwqgtxx** [comment]
一个亲测有效的办法，在v2ray前面再套一个socks5代理可以有效缓解这个问题，我是用
https://github.com/nadoo/glider
的，直接设置启动参数为
> glider -listen mixed://:1081 -forward socks5://127.0.0.1:1080 -verbose
然后把浏览器代理改到1081端口基本上就不会出现`failed to read http request > EOF`这种蛋疼的错误了

**Comment by pkron** [comment]
更新新版本到v2.40 (20171006) 64位（Windows10 X64）后暂时没发现卡住问题
