### ISSUE TITLE
[建议]配置文件太长，不方便阅读和修改

### ISSUE THREAD

**Issue by lewisxy** [v2ray/v2ray-core#577]
服务端在设计一些复杂规则或多个协议/端口同时运行的时候配置文件会变得很长，比较乱（很多tag）

不知能不能稍微改进一下配置文件的结构，比如拆分配置文件，把这些：
```
{
  "log": {},
  "dns": {},
  "routing": {},
  "inbound": {},
  "outbound": {},
  "inboundDetour": [],
  "outboundDetour": [],
  "transport": {}
}
```
中的每一个模块拆成单独的文件，如`inbound.conf`，`outbound.conf`，`routing.conf`等等，然后在主配置文件中用类似`include`的方法把不同部分（模块）添加进来，这样降低了维护成本。

**Comment by DarienRaymond** [comment]
V2Ray核心使用的是基于[protobuf的配置](https://github.com/v2ray/v2ray-core/blob/master/config.proto)，如果你想引入一套新的配置机制的话，可以自己开发一个转换工具，把你提到的文件格式，转换成对应的protobuf即可。V2Ray官方暂时没有计划开发额外的配置文件格式。
