### ISSUE TITLE
在V2Ray中支持利用UDP特性传输UDP数据包的功能

### ISSUE THREAD

**Issue by xiaokangwang** [v2ray/v2ray-core#578]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
origin/master
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
使用V2Ray代理游戏流量
3)  你看到的不正常的现象是什么？
    What did you see?
使用时游戏的延迟显著高于V2客户端和V2服务器的延迟加V2服务器和游戏服务器之前的延迟。
4)  你期待看到的正确表现是怎样的？
    What's your expectation?
游戏延迟略大于V2客户端V2服务器延迟和V2服务器和游戏服务器之前的延迟

问题分析：

VMess将全部流量通过流式传输协议传输。对于UDP数据，VMess将UDP数据视为SCTP类SEQ_PACKET，保留了数据包的边界的同时额外的不必要的加入了乱序&丢失的控制，将低了数据传输的带宽和速度。

建议的解决方案：

使用基于UDP协议来实现UDP数据的传输。打开新的UDP连接（首包）会先在VMess协议中握手，在握手完成后，转为在UDP端口上接受和转发数据。如果发送数据时发现超过mtu，就会拆分为多个UDP数据包传输可选的加入前向错误修复。发送数据时总是可能被设置为发送多次以对抗UDP丢包。

**Comment by daiaji** [comment]
我觉得kcp的作者应该写过相对应的东西了吧

**Comment by DarienRaymond** [comment]
c版的kcp有类似的选项（效果不明），但是go版的kcp加入fec之后使得这个选项变得无效了。

**Comment by daiaji** [comment]
@DarienRaymond @xtaci不是先用golang弄出的kcptun xkcptun这项目好像还不能兼容kcptun
https://github.com/xtaci/kcptun/issues/376 这issues很有意思 具体还是问问xtaci有没有作这个吧……

**Comment by DarienRaymond** [comment]
KCP最早是这个项目出来的：https://github.com/skywind3000/kcp

**Comment by daiaji** [comment]
@DarienRaymond 看来是我本末倒置了
https://github.com/xtaci/kcptun/issues/376 这边要是实现了的话 应该是类似的效果？

**Comment by DarienRaymond** [comment]
fec是其中一个问题，对于v2ray（kcp也类似）来说，v2ray的传输层是不知道具体传输的是什么内容，需要上层协议来决定。而vmess是流式协议，没办法做到udp分段传输。

简单来说，如果要支持这一功能，需要在v2ray的三层协议模型中每一层都加入这个特性，这是一个大工程。

**Comment by daiaji** [comment]
@DarienRaymond 
@xtaci 
> I don't know which option you mean in KCP, have no impression on that.

所以说具体是哪个选项啊😭

**Comment by DarienRaymond** [comment]
暂时没有计划添加对UDP/UDP的支持

**Comment by wangyu-** [comment]
>转为在UDP端口上接受和转发数据。如果发送数据时发现超过mtu，就会拆分为多个UDP数据包传输可选的加入前向错误修复。

这不就是UDPspeeder的`--mode 0`模式么😀

你可以V2ray和UDPspeeder一起用。

**Comment by y8d4w1** [comment]
> 
> 
> > 转为在UDP端口上接受和转发数据。如果发送数据时发现超过mtu，就会拆分为多个UDP数据包传输可选的加入前向错误修复。
> 
> 这不就是UDPspeeder的`--mode 0`模式么😀
> 
> 你可以V2ray和UDPspeeder一起用。
目前经过测试，V2RAY主流的WS+TLS+Nginx，配合UDPspeeder还是有问题，不知道有没有这方面的指导
