### ISSUE TITLE
 json: cannot un marshal string into Go struct field VMessAccount.alterId of type uint16

### ISSUE THREAD

**Issue by kmahyyg** [v2ray/v2ray-core#579]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

Both are built in 20170928

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

Just start running the client.

3)  你看到的不正常的现象是什么？
    What did you see?

It noticed me that the uuid in the client config didn't match your data type compiled in your software.

4)  你期待看到的正确表现是怎样的？
    What's your expectation?

Works fine.

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Server Configuration File（服务器端配置文件）:
```javascript
    // 在这里附上服务器端配置文件
    // Please attach your server configuration file here.
```

Works fine according to the log in nohup.out

    Client Configuration File（客户端配置文件）:
```javascript
    // 在这里附上客户端配置文件
    // Please attach your client configuration file here.
```
https://pastebin.com/K8N5srva

6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.

    Server Log File（服务器端日志）:
```
    // 在这里附上服务器端日志
    // Please attach your server log here.
```

No related file to offer.

    Client Log File（客户端日志）:
```
    // 在这里附上客户端日志
    // Please attach your client log here.
```
V2Ray v2.39 (One for all) 20170928
An unified platform for anti-censorship.
Main: failed to read config file: ./v2rayclient.json > Ext|Tools|Conf|Serial: fa
iled to parse json config > Ext|Tools|Conf: invalid VMess user > json: cannot un
marshal string into Go struct field VMessAccount.alterId of type uint16

# Update 1

I change the alterID from "32"  to 32.

Then :  

V2Ray v2.39 (One for all) 20170928
An unified platform for anti-censorship.
Main: failed to read config file: v2rayclient.json > Ext|Tools|Conf|Serial: fail
ed to read config file > invalid character '\r' in string literal

**Comment by DarienRaymond** [comment]
错误信息里有说，检查一下哪里有'\r'字符。

**Comment by kmahyyg** [comment]
I checked the whole file and use Pycharm and Sublime Text 3 searching \r , both returns no matches.
However , after I use the 'reformat code' in Pycharm to this json , it works fine.(But I still have to replace "32" to 32 . Orz.)

**Comment by phantomyq** [comment]
sub2conf.py 里面找到"alterId": use_conf["aid"] 改成"alterId": int(use_conf["aid"])
