### ISSUE TITLE
想请问V2ray服务端可以安装在Windows上面吗

### ISSUE THREAD

**Issue by KenYan519** [v2ray/v2ray-core#581]
你好，不好意思 , 想请问V2ray服务端可以安装在Windows上面吗
因为我在网上找不到有相关资讯 , 都只有安裝在Linux上面

**Comment by DarienRaymond** [comment]
V2Ray不区分客户端和服务器端，你只需要不同的配置文件就可以运行成客户端或者服务器端。但在Windows上只能作为应用程序运行，不能安装成服务。如果你需要安装成服务，可以自己写一个壳。

**Comment by KenYan519** [comment]
好的，非常感谢你的回覆
