### ISSUE TITLE
到底要怎样才能安在centos6里面了！

### ISSUE THREAD

**Issue by a7082633** [v2ray/v2ray-core#582]
执行完脚本，根本启动不了，有没有一个centos6的一些帮助文档啊，服务器东西太多，不敢随便换操作系系统。

**Comment by q158073378252010** [comment]
@a7082633 
直接下载 二进制文件。unzip 解压。挂在 supervisor 下 用保青春！！
如果需要我可以帮你！！！

**Comment by nicholascw** [comment]
RTFM.
