### ISSUE TITLE
内置dns可以强制使用tcp吗

### ISSUE THREAD

**Issue by hweidz** [v2ray/v2ray-core#585]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
2.39

    "dns": {
        "servers": [
            "8.8.8.8"
        ]
    }

试了一下 这样的写法只支持使用udp协议

**Comment by DarienRaymond** [comment]
暂时不支持。
