### ISSUE TITLE
V2Ray的Websocket模式可以部署到Heroku吗？

### ISSUE THREAD

**Issue by zzuzjl** [v2ray/v2ray-core#586]
看到有人将V2Ray使用Websocket方式部署到Openshift3，还有人开发了shadowsocks-over-websocket在Heroku上部署，V2Ray的Websocket模式可以部署到Heroku吗？

**Comment by DarienRaymond** [comment]
技术上没有问题，只要Heroku支持golang。但是Heroku的policy可能不允许部署类似的程序，在使用前最好仔细阅读一下用户条款。

**Comment by daiaji** [comment]
Heroku的网也蛮差的吧 而且不能换cloudflare解析
那就更卡了
