### ISSUE TITLE
Shadowsocks协议TCP Fast Open是默认开启的吗？顺便问一下动态端口要在防火墙上也打开哪些端口吗？

### ISSUE THREAD

**Issue by daiaji** [v2ray/v2ray-core#588]
文档里好像没这选项
-------------------------------
我这边网络真的丧病
可能需要多个备选传入方案……
我是看中了WebSocket
可以用用cloudflare加速
这边平时还好 有时候就kcp也救不了的卡……（自家的移动倒还好 对外网链接相当友善cloudflare延迟也就50MS 电信200MS但是不是很丢包还行 还凑活 直接服务器就完蛋
好像也就cloudflare还能将就用一下（说到底是穷 买不起三网直连VPS
但是kcp还是快一点 TCP只是万不得已将就用……
Shadowsocks是用来兼容我的路由器透明代理软件的
由于路由配置低 KCP都塞不下  v2ray更塞不下（Go写的程序好像都这么大…… c就好点
能写三个inbound吗？

**Comment by DarienRaymond** [comment]
Golang不支持显示开启TFO，但是Linux 3.16开始默认开启了TFO，应该不用额外的配置。

InboundDetour中可以写任意多个inbound。

**Comment by daiaji** [comment]
@DarienRaymond 具体写法呢
InboundDetour倒是有看过说是一个数组
但是三个以上的传入协议实例没见过
我对json也一点都不懂
