### ISSUE TITLE
客户端使用websocket方式 path参数不生效

### ISSUE THREAD

**Issue by hweidz** [v2ray/v2ray-core#589]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
2.39

    "streamSettings": {
      "network": "ws",
       "connectionReuse": false,
       "path": "aaaa"
}

这是客户端的配置
两边都不带path参数 使用默认的 / 是没有问题
不管服务端 客户端配置path后 nginx access日志还是显示在请求 / 没有效果

"GET / HTTP/1.1" 404 162 "-" "Go-http-client/1.1"

**Comment by DarienRaymond** [comment]
会在下一版本修复，暂时的解决方案是使用 "**Path**" 而不是 "path"。

**Comment by hweidz** [comment]
不好意思 reopen一下  是敏感大小写的问题吗 设置成 Path 也是无效

**Comment by gnaish** [comment]
测了下在2.40.2这个版本下还是有这个问题...

**Comment by DarienRaymond** [comment]
哦，你的写法可能有问题，具体是这样的：

```javascript
"streamSettings": {
  "network": "ws",
  "wsSettings": {
    "path": "aaaa"
  }
}
```
