### ISSUE TITLE
Support TUNTAP as inbound

### ISSUE THREAD

**Issue by cirias** [v2ray/v2ray-core#59]
如果能把所有所有流量都用v2ray走就更好了。类Unix系统都支持TUNTAP。TUN是个虚拟的Interface，可以让程序获取IP包。
你们看有没有必要做这个支持？
我自己写过一个用TUN的简单VPN。需要的话可以来写。

**Comment by v2ray** [comment]
有计划做 transparent proxy ( https://github.com/v2ray/v2ray-core/issues/54 ，主要计划是 TCP 和 UDP)，以及 IP 层的代理( https://github.com/v2ray/v2ray-core/issues/48 ) 。猜想你指的应该是 IP 层的代理。

这两个特性的实现暂时考虑使用 pcap 来做，Google 有一个开源库可以用（ https://github.com/google/gopacket ）。我还没有仔细看过。

**Comment by cirias** [comment]
查了点资料，看起来pcap只能capture，但不能intercept
http://stackoverflow.com/questions/10306386/packet-data-intercept-and-modification
这个https://godoc.org/github.com/google/gopacket/pcap里面也没有拦截包的方法。

如果不拦下来只是捕获，然后就另外发送的话，这些包会分别在两条线路上各发一次。这会是个问题。

**Comment by v2ray** [comment]
大致看了一下 TUN/TAP 的原理，看上去使用起来不复杂，关键是要重组 TCP 流，否则 VMess 无法正常工作。如果要做 IP 层的代理，可能代码量会很大。如果你有兴趣的话，不妨做一个 inbound 试试。

我这几天在清理 JSON 相关的代码，周末应该能有一个干净的版本。

**Comment by cirias** [comment]
好的 春节的时候应该会有时间 我尝试一下

**Comment by v2ray** [comment]
moved to https://github.com/v2ray/Planning/issues/1

**Comment by sinfere** [comment]
tun2socks / NEKit 可能会有帮助，底层是lwip
