### ISSUE TITLE
WebSocket可以自定义header吗？

### ISSUE THREAD

**Issue by daiaji** [v2ray/v2ray-core#591]
文档里只有
```
{
  "connectionReuse": true,
  "path": ""
}
```
没有其他设置

**Comment by DarienRaymond** [comment]
目前不支持，WebSocket的协商是自动的。你需要添加什么具体的header吗？

**Comment by daiaji** [comment]
@DarienRaymond 很奇怪明明websocket也是tcp为什么不和“tcp”共用一部分设置 tcp ws mkcp
两个tcp协议怪怪的
具体就是已经在tcp里实现那部分头部伪装
host ua啥的

**Comment by DarienRaymond** [comment]
WebSocket实现的是WebSocket标准，兼容所有其它的WebSocket程序，比如Nginx。如果支持像TCP那样的自定义，就不能被Nginx转发了。当然小改一下应该是可以的，比如UA。修改重要的header肯定是不会支持的。

**Comment by daiaji** [comment]
@DarienRaymond host能改吗？
重要的只有connection和Upgrade吧
实际上只有Upgrade

**Comment by DarienRaymond** [comment]
会在下一版本支持自定义header。
