### ISSUE TITLE
支持从 dnsmasq-china-list 中更新 chinasite

### ISSUE THREAD

**Issue by danielfree** [v2ray/v2ray-core#595]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V2RayX on mac, V2Ray on linux server

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
v2ray 客户端使用 rules 模式，所有流量走 v2ray 通过内置 rules 判断是否走代理。

3)  你看到的不正常的现象是什么？
chinasite 列表不够新。

4)  你期待看到的正确表现是怎样的？
https://github.com/felixonmars/dnsmasq-china-list 维护的国内网站加速列表一直有更新，如果 chinasite 可以定期或者自动从中更新的话就更方便了。

**Comment by daiaji** [comment]
https://github.com/ashi009/bestroutetb
这个方案的路由表好像更短

**Comment by DarienRaymond** [comment]
暂时不考虑内嵌第三方的配置文件。将来会考虑提供工具来修改默认的数据文件。
