### ISSUE TITLE
Type naming convention

### ISSUE THREAD

**Issue by yegle** [v2ray/v2ray-core#6]
Current codebase uses V prefix for almost anything, which doesn't use Golang's naming convention. The whole code should be put in `v2ray` package thus the types would be referred as `v2ray.ID` in other packages.

**Comment by v2ray** [comment]
Fair enough. Will fix it.

**Comment by v2ray** [comment]
Fixed in Commit 51670b223dd0647850578e7d7b75cca6c56dee97
