### ISSUE TITLE
unexpected response header,The connection is probably hijacked.

### ISSUE THREAD

**Issue by foolishcui** [v2ray/v2ray-core#60]
I downloaded the 'v2ray-windows-64.zip' and replaced the ID in 'config.json', and I also set SwitchyOmega in the right way.
In the meantime, the ID had been added in the Server B, while when I opened the v2ray.exe,it told me 'unexpected response header,The connection is probably hijacked.'.
Could you tell me what's going on?
Thanks~

**Comment by v2ray** [comment]
It is probably your server and client use different V2Ray version. You may check V2Ray version by running 'v2ray --version' and you will see something like:

V2Ray v1.1.4 (Post Apocalypse) 20151212

**Comment by v2ray** [comment]
Assuming this issue is resolved.
