### ISSUE TITLE
mux说是可以放到outboundDetour里 不过outboundDetour是数组吧 配置按示例里弄就会报错啊

### ISSUE THREAD

**Issue by daiaji** [v2ray/v2ray-core#601]
```
"outboundDetour": [
    {
      "mux": {
        "enabled": true
     }
    }
  ]
```
v2ray执行的时候就会报错

例子好像都是塞到outbound里
不会有这问题
还是说塞到outbound里
outboundDetour也会开启mux？

**Comment by nicholascw** [comment]
https://www.v2ray.com/chapter_02/01_overview.html

**Comment by daiaji** [comment]
@nicholascw 这样吗？
这是整个outboundDetour都mux还是outboundDetour和outbound都mux
