### ISSUE TITLE
第一次接触V2RAY，想知道WINDOWS平台的V2RAY客户端是不是绿色免安装便携版，能够在USB上运行

### ISSUE THREAD

**Issue by programsuperman** [v2ray/v2ray-core#602]
第一次接触V2RAY，想知道WINDOWS平台的V2RAY客户端是不是绿色免安装便携版，能够在USB上运行。

**Comment by qingfengshi** [comment]
是的，可以

**Comment by programsuperman** [comment]
@qingfengshi 对了，V2RAY客户端运行的时候会默认设置系统代理以让其他网络应用的流量走系统代理吗？

**Comment by daiaji** [comment]
@programsuperman 没有那种客户端

**Comment by qingfengshi** [comment]
shadowsocks是可以使用pac实现这样的功能，V2ray暂时还没有这样的功能，但是可以使用http代理，多数软件都有这种代理选项
@programsuperman <https://github.com/programsuperman>
