### ISSUE TITLE
win10 x64速度缓慢&关于配置文件的一点问题

### ISSUE THREAD

**Issue by chewnglow** [v2ray/v2ray-core#607]
我的使用环境：
我的服务器为个人服务器，只有我一个人的几台设备使用。设备分别为双系统PC（win10 x64+Ubuntu 16.10，核心均为2.4版本）和一台安卓手机（系统7.1.1，使用actinium，核心版本2.34）。
我的客户端使用socks+vmess，不同平台客户端配置文件完全相同（除了手机上和PC上的加密方式不同），服务器端使用vmess协议，单用户单端口设置，配置为最基础配置，路由配置为绕过大陆ip，没有配置诸如kcp、动态端口等功能。另外我确保每次操作前时间正确。
问题一：
我的PC运行Ubuntu系统时可以很好地与手机同时使用，打开网页速度很快也没有问题，但是win10系统下打开墙外页面很慢，打开Google时被检测到了异常流量。墙内网没有问题。
问题二：
我尝试在服务器上打开过kcp、动态端口和多用户功能、修改过alterId，但都无法正常使用。表现为：服务器和客户端对应修改配置文件后，无法打开网页，而手机使用的是最初的配置文件（用户ID和alterId未修改）却可以正常联网。因此考虑修改了错误的配置文件导致修改内容没有生效。我修改的配置文件为/etc/v2ray/config.json，修改之后查看时内容成功修改，但是却没有应用到服务器中。我认真使用文本编辑器比照格式要求检查了代码应该没有问题。

（如添加多用户时的例子如下，其余部分和v2ray说明手册常用配置相同，故略去：）
服务器端：
"clients": [
        {
          "id": "(id1)",
          "level": 1,
          "alterId": 64,		//以前是32，服务器端修改为64后，用户端填64无法联网，填32可正常联网
          "email": "(email1)"
        },
        {
          "id": "(id2)",
          "level": 1,
          "alterId": 64,
          "email": "(email2)"
        },
        {
          "id": "(id3)",
          "level": 1,
          "alterId": 64,
          "email": "(email3)"
        }
      ]
用户端配置代码如下：
  "settings": {
      "clients": [
        {
          "id": "(id2)",
          "level": 1,
          "alterId": 64
        }
      ]
    }

另外我检查了服务器端和客户端的log，均没有提示错误，连接正常，但是服务器端却没有给出accept。

**Comment by chewnglow** [comment]
我明天一早会给出相关的log详细记录

**Comment by nicholascw** [comment]
配置文件改完要重启v2ray的啊。。

**Comment by chewnglow** [comment]
感谢回答，windows端检查完毕，现在没有问题了，应该是间歇性的。
配置文件改完我执行的是v2ray的重启指令但是还是不行。不知是否要重启VPS？

**Comment by agzfan** [comment]
socks的问题,有人说是dns引起的
客户端直接把socks改成http就行了,但是实际使用中http在tumblr上面依然有打不开视频的问题,大多出现在奇怪的域名上,类似xxxxxx.tumblr.com

**Comment by chewnglow** [comment]
前几天有一点忙，最近重新登录之后发现如下的问题：
我登录linux后忘了修改时间导致服务器用户识别错误（在日志文件中记录到），修改时间后仍无法连接到google，服务器log没有任何记录（之前代理不正常的时候也与遇到过这个问题），请问服务器没有log记录的时候代表什么问题？谢谢！（我一会试试用scp将本地的更新配置文件上传至服务器，直接使用ssh在服务器修改配置文件后客户端对应修改仍无法正常使用新功能，只能使用原来的客户端配置文件）

**Comment by chewnglow** [comment]
感谢各位回答，现在的问题和这个问题主题有差别，这个就close了吧
