### ISSUE TITLE
[Enhancement][!!!Urgent!!!] Shadowsocks AEAD support

### ISSUE THREAD

**Issue by lewisxy** [v2ray/v2ray-core#608]
My one of my server's IP was banned by gfw recently, and it is highly suspected they detected Shadowsocks data using AES-256-CFB (there is a paper published recently about this ). 

[Paper link](http://ieeexplore.ieee.org/document/8048116/?reload=true#full-text-section)

AEAD cipher offers authentication and is harder to detect, please consider adding support for AEAD cipher (AES-GCM, chacha20-ietf-poly1305).

Thanks

**Comment by aflyhorse** [comment]
I'm also changing my SS configurations to provide legacy access, and found that none of the AEAD Ciphers are currently supported.

The ciphers SS provided are listed here: https://shadowsocks.org/en/spec/AEAD-Ciphers

**Comment by 10330384** [comment]
Both use VMESS and SS by V2ray at server, the port of VMESS and ss are  both banned. if only use VMESS, it won't be banned.

**Comment by lewisxy** [comment]
@10330384 Sometimes SS is necessary since it's better supported on various devices than VMESS.

**Comment by 10330384** [comment]
> Sometimes SS is necessary since it's better supported on various devices than 
 VMESS.

I agree with that. So I hope V2ray support AEAD.

**Comment by wangqr** [comment]
As a temporary workaround, you can run a shadowsocks client and set the outbound of v2ray to the client's socks5 port.

**Comment by IbarakiKasen** [comment]
As a workaround, you can run a shadowsocks client and set the outbound of v2ray to the client's socks5 port.

**Comment by aflyhorse** [comment]
@10330384 On my case, only the SS port is banned. Vmess port (via mkcp, none header) remains OK.
@IbarakiKasen I've already disabled the SS module in the v2ray and started an ss-libev at the same port with gcm cipher.

**Comment by DarienRaymond** [comment]
The development for SS AEAD is in progress. However, I wouldn't put much hope on it in terms of blocking. If legacy SS ciphers are blocked, AEAD won't do any better.
