### ISSUE TITLE
请添加哈希校验|Please add hash for weekly release

### ISSUE THREAD

**Issue by ZZ4forall** [v2ray/v2ray-core#61]
您好，非常感谢您的付出。请问您是否可以在Release中添加SHA1的哈希校验呢？谢谢您。

**Comment by v2ray** [comment]
Fix in 639bcad78dab31e0ffbe5e2851f9e4edf20499a7

A metadata.txt file will be released together with other binary packages. The content of metadata looks like:

File: v2ray-windows-32.zip
Size: 1720564
SHA1: 49c5a4e5ac4697fb37f322b658a72c433999cfa0

File: v2ray-windows-64.zip
Size: 1876611
SHA1: ff6d654dd8e8f75efdd81d9a58781f15ed3aa9c1

File: v2ray-macos.zip
Size: 2519178
SHA1: 6c11f62651003422ca9972a4c0fe9ecdc726b5a7

File: v2ray-linux-32.zip
Size: 1743429
SHA1: b4834f8d292fffa46c8bc8778c43bfc3d7909878

File: v2ray-linux-64.zip
Size: 1894852
SHA1: f1a8d7ded0a80313e9494b099e29061c9320f6cf

File: v2ray-linux-arm.zip
Size: 1694348
SHA1: a56805c8df25ac8224e08522245c4f8df83157a9

File: v2ray-linux-arm64.zip
Size: 1735239
SHA1: 48c28fd6b08849163383b26af7978bc728032577
