### ISSUE TITLE
C#的protobuf问题

### ISSUE THREAD

**Issue by ToutyRater** [v2ray/v2ray-core#610]
看了一下protobuf，遇到一个问题，就是多.proto文件时用protoc没法生成相应语言的代码，google了一波，各种乱七八糟的说法都有。重点是，我看了v2ray的代码，发现是在 https://github.com/v2ray/v2ray-core/blob/master/tools/genproto/main.go 生成的，于是拉下来把java改成了csharp，编译运行确实可以了，但是生成的文件跟想象中不太一样：
```
$GOSRC
  |--github.com
      |--v2ray
          |--sdk-csharp
              |--proto
                  |--Account.cs
                  |--Address.cs
                  |--Command.cs
                  |--Config.cs
                  |--Destination.cs
                  |--Geoip.cs
                  |--Headers.cs
                  |--Network.cs
                  |--Port.cs
                  |--ServerSpec.cs
                  |--TypedMessage.cs
                  |--User.cs
```
而且目录结构跟sdk-java也不一样，我对golang和protobuf都不算熟，能说一下这是怎么回事吗？

**Comment by DarienRaymond** [comment]
我对C#版本也不太理解，之前生成过一次，本来的期待是和Java的目录结构一样，但生成出来和你看到的是一样的。当然由于没有C#的需求（也对C#没有特别的了解）就没有在意这件事。C#大概是需要对每个目录单独生成一遍，并指定到分别不同的目标路径。

如果你觉得是.proto文件的写法有问题，欢迎PR。

**Comment by ToutyRater** [comment]
好吧，目前看来还不知道为什么会这样，我得抽空研究一下。

另外有个问题，我发现v2ray的测试代码的配置所有inbound和outbound都没有指定是什么协议， .proto文件也没找到跟protocol有关的message。后来我猜测protocol由ProxySettings的type决定，是这样么？

**Comment by DarienRaymond** [comment]
是的，是由message的type决定的

**Comment by ToutyRater** [comment]
好的。先关闭了，protobuf的问题等弄清楚了再另外说

**Comment by RebornL** [comment]
楼主 我想请问一下sdk-java这个要怎么使用？没搜索到相关文档，不知道怎么下手
