### ISSUE TITLE
Shadowsocks UDP协议是否可以被VMESS协议转发

### ISSUE THREAD

**Issue by digitaltwt** [v2ray/v2ray-core#611]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

    2.40

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

    通过shadowsocks的UDP玩外服游戏

3)  你看到的不正常的现象是什么？
    What did you see?

Shadowsocks作为inbound，VMESS作为outbound,UDP协议没有走outbound VMESS协议

4)  你期待看到的正确表现是怎样的？
    What's your expectation?

Shadowsocks作为inbound，VMESS作为outbound,UDP协议应该走outbound VMESS协议

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).
{
  "log": {
    "access": "/mnt/v2ray/access.log",
    "error": "/mnt/v2ray/error.log",
    "loglevel": "info"
  },
  "inbound": {
    "port": 80,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "*******-efa5-42ca-b7e9-6a35282d737f",
          "level": 1
        }
      ]
}
  },

  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "inboundDetour": [
    {
      "protocol": "vmess",
      "port": "30001-30100",
      "settings": {
        "clients": [
          {
            "id": "d17a1af7-efa5-42ca-b7e9-6a35282d737f",
            "level": 1
          }
        ]
      }
    }
  ],
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}

    Client Configuration File（客户端配置文件）:
```javascript
    // 在这里附上客户端配置文件
    // Please attach your client configuration file here.
```
{
  "log": {
    "access": "/mnt/v2ray/access.log",
    "error": "/mnt/v2ray/error.log",
    "loglevel": "info"
  },
  "inbound": {
    "port": 20355,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "e68e21fc-9867-47e9-8b3f-35832634b6c4",
          "level": 1,
          "alterId": 64
        }
      ]
    }
  },
  "inboundDetour": [
    {
      "protocol": "shadowsocks",
      "port": ****,
      "settings": {
        "method": "chacha20",
        "password": "123456",
        "udp": true,
        "level": 1
      }
    },
   
  ],
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "***********",
          "port": 80,
          "users": [
            {
              "id": "*******-efa5-42ca-b7e9-6a35282d737f",
              "security": "aes-128-gcm"
            }
          ]
        }
      ]
    },

    "mux":{"enabled":false}
  },
 
    }
  }
}

6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.

    Server Log File（服务器端日志）:
```
    // 在这里附上服务器端日志
    // Please attach your server log here.

```

服务器日志表现为没有接受到UDP协议

    Client Log File（客户端日志）:
```
    // 在这里附上客户端日志
    // Please attach your client log here.
```
在客户端里shadowsocks的UDP协议直接走了，TCP协议走了VMESS协议
2017/10/15 02:57:18 [Info]Proxy|Shadowsocks: tunnelling request to udp:13.93.165.153:3544
2017/10/15 02:57:18 [Info]Transport|Internet|UDP: establishing new connection for udp:13.93.165.153:3544
2017/10/15 02:57:18 [Info]App|Dispatcher|Default: default route for udp:13.93.165.153:3544
2017/10/15 02:57:18 [Info]Transport|Internet|TCP: dailing TCP to tcp:52.175.23.210:80
2017/10/15 02:57:19 [Info]Proxy|VMess|Outbound: tunneling request to udp:13.93.165.153:3544 via tcp:VMESS server:80
2017/10/15 02:57:19 [Info]Proxy|Shadowsocks: tunnelling request to udp:13.93.165.153:3544
2017/10/15 02:57:19 [Info]Proxy|Shadowsocks: tunnelling request to udp:13.93.165.153:3544

**Comment by DarienRaymond** [comment]
```
2017/10/15 02:57:19 [Info]Proxy|VMess|Outbound: tunneling request to udp:13.93.165.153:3544 via tcp:VMESS server:80
```

VMess 是UDP over TCP的，你在日志中不会看到VMess dial UDP，但是应该能在服务器端看到VMess收到了目标为13.93.165.153:3544的请求。

**Comment by digitaltwt** [comment]
感谢开发者的回复，我有个问题，当我用Mkcp协议传输时，UDP性能反而会变差，浏览网页之类的TCP响应很快，这是什么原因呢？

**Comment by DarienRaymond** [comment]
这个问题分析不了，如果你有详细的log之类的数据，请单独开一个issue讨论。
