### ISSUE TITLE
有办法让utorrent获得远程端口吗?

### ISSUE THREAD

**Issue by agzfan** [v2ray/v2ray-core#616]
本机ip 192.168.1.100 utorrent端口是30000
v2ray端口80
utorrent设置使用代理127.0.0.1:1080

debian设置
nano /etc/sysctl.conf
net.ipv4.ip_forward=1

路由器已经端口映射30000

utorrent显示没有打开端口

**Comment by tefiszx** [comment]
@agzfan utorrent是在哪里看端口有没有打开的？

**Comment by agzfan** [comment]
utorrent界面中下,打勾的是外网,!号表示内网端口没开

**Comment by tefiszx** [comment]
![default](https://user-images.githubusercontent.com/20527882/31807046-5ae826f4-b59e-11e7-9a3c-53c71e33c229.jpg)
@agzfan [是你种子的问题。我试过开代理连接tracker，有传入的连接。路由器正确设置了upnp端口映射。用utorrent，开启代理后，内网端口打开变绿色。看我的截图。换个种子试试把，此Issue和主题无关。

**Comment by agzfan** [comment]
这样设置没有100%流量都跑127.0.0.1(v2ray)上面,你用系统的资源监视器看看
使用代理进行xxxx,2个选项打勾高级里设置net.bind_ip 127.0.01,绑定v2ray的ip
这时100%流量都跑127.0.0.1上面,这个时候端口就显示没有打开.....

**Comment by DarienRaymond** [comment]
不太了解utorrent以及它的用法，猜测你需要的功能是在远程主机上开一个端口，比如30000，然后把这个端口监听到的连接发回给本机的utorrent。这个功能需要socks 5的bind特性支持，在V2Ray中没有实现（并且目前没有计划去实现），应该是无法完成的。

**Comment by DarienRaymond** [comment]
Close due to inactivity.
