### ISSUE TITLE
客户端填多个outbound 实际上也只是在按路由表跑流量吧

### ISSUE THREAD

**Issue by daiaji** [v2ray/v2ray-core#617]
我的outbound 貌似IP被ban了
然后并没有使用outboundDetour里的代理
有类似的负载均衡计划吗？
还是希望尽快能c化……
好放到路由器上
我怀疑是我用ss协议搞得被ban了

**Comment by DarienRaymond** [comment]
没有负载均衡的计划，没有c的计划。

**Comment by fax001** [comment]
负债均衡的确很需要了 最近gfw封锁加剧 竟然会有ip被禁用的情况

**Comment by daiaji** [comment]
@DarienRaymond 这会开得简直是要死了
负载均衡是没太所谓
但是outbound不能连了的话 至少跳到其他的outbound啊
不然一个配置写两三个outbound 结果还是用死掉的outbound
这多outbound有啥用啊……
到头来还是要多写几份配置

**Comment by fax001** [comment]
的确没有负载均衡没关系 但是主备切换这个还是挺有用的

**Comment by daiaji** [comment]
@DarienRaymond 探测代理能不能用 这功能是可以有 特别是现在还没好用的第三方客户端的情况下
