### ISSUE TITLE
按教程配置文件后仍无法通过v2ray上网

### ISSUE THREAD

**Issue by Helldive** [v2ray/v2ray-core#618]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
 v2.41

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
 用chrome并设置了socks代理打开youtube网站
3)  你看到的不正常的现象是什么？
    What did you see?
网页无法读取

4)  你期待看到的正确表现是怎样的？
    What's your expectation?
流畅快速打开网页
5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).
 
    Server Configuration File（服务器端配置文件）:
```javascript
    // 在这里附上服务器端配置文件
    // Please attach your server configuration file here.
```
  "log": {
    "loglevel": "warning"
  },
  "inbound": {
    "port": 1080,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "45.**.**.**",
          "port": 38933,
          "users": [
            {
              "id": "2aabbbb7-6b6f-4d69-bb32-d091c6fc6a6c",
              "alterId": 64,
              "security": "auto"
            }
          ]
        }
      ]
    },
    "mux": {
      "enabled": true
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "tlsSettings": {
        "serverName": "45.**.**.**",
        "allowInsecure": true
      },
      "wsSettings": {
        "path": "/45.**.**.**/"
      }
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": "1-52",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "54-79",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "81-442",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "444-65535",
          "outboundTag": "direct"
        },
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        }
      ]
    }
  }
}

    Client Configuration File（客户端配置文件）:
```javascript
    // 在这里附上客户端配置文件
    // Please attach your client configuration file here.
```{
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 38933,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "2aabbbb7-6b6f-4d69-bb32-d091c6fc6a6c",
          "level": 1,
          "alterId": 64
        }
      ]
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {    
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    } 
  ],         
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",


6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.

    Server Log File（服务器端日志）:
```
    // 在这里附上服务器端日志
    // Please attach your server log here.
```

    Client Log File（客户端日志）:
```
    // 在这里附上客户端日志
    // Please attach your client log here.
```

**Comment by tefiszx** [comment]
client端的配置文件漏了streamSettings，服务端的streamSettings设置为了ws伪装。

**Comment by Helldive** [comment]
@tefiszx 我看的是官网的那个白话文教程  其实它上面也没有这些配置 我是因为下载完v2ray之后 打开原配置文件里面就有着一堆东西 我看不太懂也就没管 只改了id ip 端口等参数 如果要改正的话 就把其他的删除 只保存inbound outbound就行了吗？

**Comment by tefiszx** [comment]
@Helldive 试试用v2ray的配置生成器。话说v2ray现在真的开始火了。
https://htfy96.github.io/v2ray-config-gen/

**Comment by Helldive** [comment]
@tefiszx  谢谢老哥分享  我那个配置也弄好了  多谢老哥提点 确实客户端配置的时候那一堆我看不懂的 教程上没有的东西坏了事 现在已解决了 感觉好多教程里面只给了服务端的模版 没有给客户端的完整模版 给新手小白还是很多压力

**Comment by ehu1084** [comment]
通过题主的问题我发现了自己问题的原因，我们正好相反，客户端设置了ws伪装而服务端没有。。。现在ok了。。。感谢题主 感谢 @tefiszx
