### ISSUE TITLE
SS协议，是否会被识别出来

### ISSUE THREAD

**Issue by HavenLiu** [v2ray/v2ray-core#620]
现在基本已经确认了墙能准确识别ss的数据流，V2Ray也支持ss协议，如果V2Ray使用ss协议，会不会也能被准确识别出来？

**Comment by daiaji** [comment]
我看了一下 好像是可以被识别 不过换成v2ray后不被封的话那基本可以确诊了
ss协议的话当然会被爆菊啦 想啥呢……
不过既然能机器学习ss 那么识别V2Ray也OK吧
只是说用cf中转ws协议 不怂就是了
除非哪天断掉ws协议或者断掉cf

**Comment by DarienRaymond** [comment]
你可以选择不用ss协议

**Comment by LiTianjue** [comment]
我想问一下,现在都用什么协议,我ss已经不能用了

**Comment by daiaji** [comment]
@LiTianjue ws+tls稳得一逼
开会都没断过
因为我用cloudflare中转过
