### ISSUE TITLE
YAML config file support

### ISSUE THREAD

**Issue by tioover** [v2ray/v2ray-core#621]
Because V2Ray config very complex and error-prone, use YAML config file will be improve this.

**Comment by DarienRaymond** [comment]
In short, V2Ray core uses protobuf-based configuration. You can write your own YAML to protobuf translator if you'd like to design a YAML config format. 

See also: 
https://github.com/v2ray/Planning/issues/20
https://github.com/v2ray/Planning/issues/17

**Comment by jekoie** [comment]
把yaml文件转换成pb文件简单啊

**Comment by jekoie** [comment]
用yaml接口就几行代码的事, 还是自己写得个人用吧, 可以的话就pull request.
