### ISSUE TITLE
服务器端日志文件显示接受但是却不能连接墙外网

### ISSUE THREAD

**Issue by chewnglow** [v2ray/v2ray-core#625]
我参考**https://www.v2ray.com/chapter_05/00_config/10_multi_mode.html**（官网KCP+TCP+动态端口参考脚本）完成了配置并检查，客户端和服务器的UUID和alterId均匹配，客户端也设置了kcp。联网发现国内路由正常访问，国外路由不能访问，检查服务器端access.log显示该IP为accept。服务器端系统为ubuntu 16.04，客户端系统为ubuntu 16.10，均使用2.4版v2ray。多谢解答！

**Comment by chewnglow** [comment]
客户端配置
inbound": {
    "port": 1080,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "hexieip",
          "port": hexieport3,
          "users": [
            {
              "id": "hexieid",
              "alterId": 64,
              "security": "aes-128-gcm"
            }
          ]
        }
      ]
    },
    "mux": {
      "enabled": true
    },
    "streamSettings": {
      "network": "kcp" 
    }
  },
服务器端配置：

  "inbound": {
    "port": hexieport1,       
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "hexieid",  
          "level": 1,            
          "alterId": 64            
        }
      ]
    },
    "streamSettings": {
      "network": "kcp"  
    }
  },

  "inboundDetour": [               
    {
      "port": hexieport2,       
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "hexieid",  
            "level": 1,
            "alterId": 64
          }
        ]
      }
    },
    {
      "port": hexieport3,       
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "hexieid",  
            "level": 1,
            "alterId": 64
          }
        ],
        "detour": {
          "to": "detour-kcp"
        }
      },
      "streamSettings": {
        "network": "kcp"
      }
    },
    {
      "port": hexieport4,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "hexieid", 
            "level": 1,
            "alterId": 64
          }
        ],
        "detour": {
          "to": "detour-tcp"
        }
      }
    },
    {
      "protocol": "vmess",
      "port": "10000-10100",   
      "tag": "detour-kcp",
      "settings": {},
      "allocate": {
        "strategy": "random", 
        "concurrency": 2,   
        "refresh": 5
      },
      "streamSettings": {
        "network": "kcp"
      }
    },
    {
      "protocol": "vmess",
      "port": "12000-12100",  
      "tag": "detour-tcp",
      "settings": {},
      "allocate": {
        "strategy": "random",
        "concurrency": 2,
        "refresh": 5
      }
    }
  ],
其中文件编辑均在编辑器里完成，确保无误，并且检查status后也正常无误。
另外有的时候会出现连接不上但是服务器日志没有记录的情况，请问这样是属于什么情况？感谢～

**Comment by LinusKou** [comment]
最新版2.41有同样的问题。双端**access.log**均显示**accepted**，但浏览器就是提示**连接断开**。

实测关闭**kcp**即可，估计应该是**kcp**的问题。

**Comment by zhangyz1997** [comment]
确实近期mKCP非常不稳定，也是连接不上服务端日志无记录，我一开始还以为是被运营商QoS了，还换了几次混淆都没啥用

**Comment by chewnglow** [comment]
感谢回答，考虑使用bbr代替之。另外目前服务端的alterId和客户端不匹配仍可联网，然而把客户端的修改到和服务器相同反而不能联网。日志文件同样没有任何记录。目前虽可正常使用但担心以后添加协议会出现问题。请问这种情况如何解决？多谢！

**Comment by DarienRaymond** [comment]
当服务器端alterId >= 客户端alterId时可以正常连接，你不能连接的原因应该是其它的，比如时间不匹配。
