### ISSUE TITLE
socks代理给局域网共享的问题

### ISSUE THREAD

**Issue by tefiszx** [v2ray/v2ray-core#626]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

> v2ray.exe  --version
V2Ray v2.40 (One for all) 20171006
An unified platform for anti-censorship.`
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

> 
1、win10启动移动热点，开启虚拟wifi，手机连接虚拟wifi获得ip地址192.168.137.X
2、运行wvv2ray.exe -config config.json，监听0.0.0.0:8010端口，让局域网内的机器共享socks代理。
3、运行shadowsocks客户端，监听0.0.0.0:1080端口，让局域网内的机器共享socks代理。
4、运行netstat命令查看当年监听的端口，输出显示1080端口和8010端口均正常监听
`C:\Users\abc>netstat -aon|findstr LISTEN|findstr 8010
  TCP    0.0.0.0:8010           0.0.0.0:0              LISTENING       228
  TCP    [::]:8010              [::]:0                 LISTENING       228

C:\Users\abc>netstat -aon|findstr LISTEN|findstr 1080
  TCP    0.0.0.0:1080           0.0.0.0:0              LISTENING       10324`

3)  你看到的不正常的现象是什么？
    What did you see?

> **在shadowsocks和v2ray均正常运行的情况下，手机设置手动代理为1080端口，上网正常，通过shadowsocks的代理全局翻墙。手机设置手动代理为8010端口，显示连接潮湿，墙内外网站均不能访问。尝试修改配置把v2ray的监听端口换成1080，故障依旧。初步可以排除防火墙和代理类型设置的问题**

4)  你期待看到的正确表现是怎样的？
    What's your expectation?

> 手机设置手动代理为1080端口（shadowsocks监听）和8010端口（v2ray监听），均应上网正常

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Server Configuration File（服务器端配置文件）:
```javascript
    // 在这里附上服务器端配置文件
    // Please attach your server configuration file here.
```
服务端没问题，本机使用v2ray的客户端正常。就是代理不能在局域网内共享
    Client Configuration File（客户端配置文件）:
```javascript
    // 在这里附上客户端配置文件
    // Please attach your client configuration file here.
```
客户端配置如下
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": ""
  },
  "inbound": {
    "port": 8010,
    "listen": "0.0.0.0",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "127.0.0.1",
      "clients": null
    },
    "streamSettings": null
  },
  "outbound": {
    "tag": "agentout",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "VPSIP_Address",
          "port": 10086,
          "users": [
            {
              "id": "MY_UUID",
              "alterId": 64,
              "security": "aes-128-gcm"
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "tcp",
      "security": "",
      "tcpSettings": {
        "connectionReuse": true,
        "header": {
          "type": "http",
          "request": {
            "version": "1.1",
            "method": "GET",
            "path": [
              "/"
            ],
            "headers": {
              "Host": [
                "www.amazoen.com",
                "www.cloudflare.com",
                "www.bing.com"
              ],
              "User-Agent": [
                "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36",
                "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
              ],
              "Accept-Encoding": [
                "gzip, deflate"
              ],
              "Connection": [
                "keep-alive"
              ],
              "Pragma": "no-cache"
            }
          },
          "response": {
            "version": "1.1",
            "status": "200",
            "reason": "OK",
            "headers": {
              "Content-Type": [
                "application/octet-stream",
                "video/mpeg"
              ],
              "Transfer-Encoding": [
                "chunked"
              ],
              "Connection": [
                "keep-alive"
              ],
              "Pragma": "no-cache"
            }
          }
        }
      },
      "kcpSettings": null,
      "wsSettings": null
    },
    "mux": {
      "enabled": true
    }
  },
  "inboundDetour": null,
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {
        "response": null
      },
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "blockout"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": null,
          "outboundTag": "direct",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "domain": null
        },
        {
          "type": "chinasites",
          "port": null,
          "outboundTag": "direct",
          "ip": null,
          "domain": null
        },
        {
          "type": "chinaip",
          "port": null,
          "outboundTag": "direct",
          "ip": null,
          "domain": null
        }
      ]
    }
  }
}
6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.

    Server Log File（服务器端日志）:
```
    // 在这里附上服务器端日志
    // Please attach your server log here.
```

    Client Log File（客户端日志）:
```
    // 在这里附上客户端日志
    // Please attach your client log here.
```

**Comment by DarienRaymond** [comment]
把 loglevel 设为 debug 看一下 v2ray 的输出。

**Comment by tefiszx** [comment]
@DarienRaymond 感谢作者回复。
这是我的输出
`D:\Shadowsocks\v2ray-windows-64\v2rayN>v2ray.exe -config config.json
V2Ray v2.49 (One for all) 20171116
An unified platform for anti-censorship.
2017/11/22 13:36:27 [Debug]App|Proxyman|Inbound: creating tcp worker on 0.0.0.0:8010
2017/11/22 13:36:27 [Info]Transport|Internet|TCP: listening TCP on 0.0.0.0:8010
2017/11/22 13:36:27 [Info]Transport|Internet|UDP: listening UDP on 0.0.0.0:8010
2017/11/22 13:36:27 [Warning]Core: V2Ray started
2017/11/22 13:36:29 [Info]Proxy|Socks: TCP Connect request to tcp:mtalk.google.com:443
2017/11/22 13:36:29 [Info]App|Router: looking for IP for domain: mtalk.google.com
2017/11/22 13:36:29 [Debug]App|DNS|Server: add pending request id 16414
2017/11/22 13:36:29 [Debug]Transport|Internet|UDP: dispatch request to: udp:8.8.8.8:53
2017/11/22 13:36:29 [Info]Transport|Internet|UDP: establishing new connection for udp:8.8.8.8:53
2017/11/22 13:36:29 [Info]App|Dispatcher|Default: default route for udp:8.8.8.8:53
2017/11/22 13:36:29 [Info]App|Proxyman|Mux: dispatching request to udp:8.8.8.8:53
2017/11/22 13:36:29 [Info]Transport|Internet|TCP: dailing TCP to tcp:35.194.253.123:16891
2017/11/22 13:36:29 [Info]Proxy|VMess|Outbound: tunneling request to tcp:v1.mux.cool:9527 via tcp:35.194.253.123:16891
2017/11/22 13:36:29 [Debug]App|DNS|Server: handling response for id 16414 content: ;; opcode: QUERY, status: NOERROR, id: 16414
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;mtalk.google.com.      IN       A

;; ANSWER SECTION:
mtalk.google.com.       21599   IN      CNAME   mobile-gtalk.l.google.com.
mobile-gtalk.l.google.com.      299     IN      A       64.233.188.188

Adding ans: 64.233.188.188
2017/11/22 13:36:29 [Debug]App|DNS|Server: returning 1 IPs for domain mtalk.google.com.
2017/11/22 13:36:29 [Info]App|Dispatcher|Default: default route for tcp:mtalk.google.com:443
2017/11/22 13:36:29 [Info]App|Proxyman|Mux: dispatching request to tcp:mtalk.google.com:443
2017/11/22 13:36:35 [Info]Proxy|Socks: TCP Connect request to tcp:flora.web.telegram.org:443
2017/11/22 13:36:35 [Info]App|Router: looking for IP for domain: flora.web.telegram.org
2017/11/22 13:36:35 [Debug]App|DNS|Server: add pending request id 16356
2017/11/22 13:36:35 [Debug]Transport|Internet|UDP: dispatch request to: udp:8.8.8.8:53
2017/11/22 13:36:36 [Debug]App|DNS|Server: handling response for id 16356 content: ;; opcode: QUERY, status: NOERROR, id: 16356
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;flora.web.telegram.org.        IN       A

;; ANSWER SECTION:
flora.web.telegram.org. 476     IN      A       149.154.171.22

Adding ans: 149.154.171.22
2017/11/22 13:36:36 [Debug]App|DNS|Server: returning 1 IPs for domain flora.web.telegram.org.
2017/11/22 13:36:36 [Info]App|Dispatcher|Default: default route for tcp:flora.web.telegram.org:443
2017/11/22 13:36:36 [Info]App|Proxyman|Mux: dispatching request to tcp:flora.web.telegram.org:443
2017/11/22 13:36:41 [Info]Transport|Internet|UDP: failed to handl UDP input > EOF
2017/11/22 13:36:55 [Info]Proxy|Socks: TCP Connect request to tcp:mail.google.com:443
2017/11/22 13:36:55 [Info]App|Router: looking for IP for domain: mail.google.com
2017/11/22 13:36:55 [Debug]App|DNS|Server: add pending request id 65307
2017/11/22 13:36:55 [Debug]Transport|Internet|UDP: dispatch request to: udp:8.8.8.8:53
2017/11/22 13:36:55 [Info]Transport|Internet|UDP: establishing new connection for udp:8.8.8.8:53
2017/11/22 13:36:55 [Info]App|Dispatcher|Default: default route for udp:8.8.8.8:53
2017/11/22 13:36:55 [Info]App|Proxyman|Mux: dispatching request to udp:8.8.8.8:53
2017/11/22 13:36:55 [Debug]App|DNS|Server: handling response for id 65307 content: ;; opcode: QUERY, status: NOERROR, id: 65307
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;mail.google.com.       IN       A

;; ANSWER SECTION:
mail.google.com.        21599   IN      CNAME   googlemail.l.google.com.
googlemail.l.google.com.        299     IN      A       74.125.204.17
googlemail.l.google.com.        299     IN      A       74.125.204.18
googlemail.l.google.com.        299     IN      A       74.125.204.83
googlemail.l.google.com.        299     IN      A       74.125.204.19

Adding ans: 74.125.204.17
Adding ans: 74.125.204.18
Adding ans: 74.125.204.83
Adding ans: 74.125.204.19
2017/11/22 13:36:55 [Debug]App|DNS|Server: returning 4 IPs for domain mail.google.com.
2017/11/22 13:36:55 [Info]App|Dispatcher|Default: default route for tcp:mail.google.com:443
2017/11/22 13:36:55 [Info]App|Proxyman|Mux: dispatching request to tcp:mail.google.com:443
2017/11/22 13:37:03 [Info]Transport|Internet|UDP: failed to handl UDP input > EOF`

**Comment by DarienRaymond** [comment]
看日志已经可以正常连通了，是不是VPS配置有什么问题。看一下VPS的log

**Comment by tefiszx** [comment]
@DarienRaymond PC上可以正常代理，所以至少PC-VPS之间的配置是正确的。就是不知道手机走PC的代理为什么不行。

这是我vps上的/var/log/v2ray/下的log
` cat /var/log/v2ray/error.log
2017/10/10 02:05:18 [Warning]Core: V2Ray started
2017/10/13 02:57:16 [Info]Transport|Internet|TCP: listening TCP on 0.0.0.0:1234
2017/10/13 02:57:16 [Warning]Core: V2Ray started
2017/10/13 02:59:12 [Info]Transport|Internet|TCP: listening TCP on 0.0.0.0:1234
2017/10/13 02:59:12 [Warning]Core: V2Ray started
2017/10/13 03:05:25 [Warning]Core: V2Ray started
2017/10/13 04:49:46 [Warning]Core: V2Ray started
2017/10/13 04:53:40 [Warning]Core: V2Ray started
2017/10/13 04:54:27 [Warning]Core: V2Ray started
`

**Comment by tefiszx** [comment]
@DarienRaymond  感谢作者不厌其烦的关注解答。我刚刚排查到问题了。
1、确定防火墙允许PC与手机的通信，相应的端口已打开并处于被监听状态
2、v2ray客户端如果要让手机WIFI共享代理，在inbound的代理类型中必须使用http类型的代理。socks类型的，手机端无法直接使用。
总结一下：我原来的配置是这样的。将配置改为**加粗**的部分就正常了。
 "inbound": {
    "port": 8010,
    "listen": "0.0.0.0",
    "protocol": "socks", **这里改为http**
    "settings": {
	 "timeout": 0  **下面4行全部删除**
	 "auth": "noauth",
         "udp": true,
         "ip": "127.0.0.1",
         "clients": null
	},

**Comment by DarienRaymond** [comment]
你的 socks inbound 中，settings.ip 需要改成PC内网IP（不能是 127.0.0.1 ），这样才能正常转发UDP数据。

**Comment by tefiszx** [comment]
@DarienRaymond 在我的安卓7.0的手机上实验了一下。结果如下：
前提是防火墙不对v2ray的代理形成阻拦。
1、inbound 类型"protocol": 设置为socks，settings 的ip 设置为局域网内ip：192.168.137.1（手机ip是192.168.137.8）。手机不能上网，网页错误显示ERR_EMPTY_RESPONSE
2、inbound 类型"protocol": 设置为http，ettings 的ip 设置为局域网内ip：192.168.137.1 和 localhost默认的127.0.0.1，手机均能正常走代理上网。
结论是socks inbound中settings的ip网段使用默认的和局域网内的没影响，还是手机操作系统的代理只能使用http类型的问题。如果在PC中运行privoxy将scoks5代理转为http应该也是可以的。（这个办法我没实验过，但是shadowsocks的win版客户端和v2rayN的win版是自带privoxy的）

**Comment by BoyuanJiang** [comment]
PC端可以使用socks协议，只需android中下载drony，使用SOCKS4a协议代理即可。

**Comment by Justsoos** [comment]
ss 和 ssr 的win版本是支持单端口绑定http和socks5双协议，特殊设计过的。
v2ray默认只支持socks5单端口，单协议，这给了很多人错觉。

**Comment by weituotian** [comment]
@tefiszx v2rayN 不能选择http怎么办?
![image](https://user-images.githubusercontent.com/7270968/54429445-8c1fc880-475b-11e9-9557-58b38db025f3.png)

**Comment by Justsoos** [comment]
v2rayN 自带一个proxifier开http代理，默认socks端口号+1

**Comment by myWillison** [comment]
> v2rayN 自带一个proxifier开http代理，默认socks端口号+1

感谢兄弟，问题解决了
