### ISSUE TITLE
v2ray连接远程桌面(win rdp)延迟大

### ISSUE THREAD

**Issue by agzfan** [v2ray/v2ray-core#629]
一台德国独立win服务器,我本地ping服务器400只能通过代理降低延迟,代理服务器使用一台香港服务器
本地ping香港服务器30,香港ping 德国服务器 200

1.本地--->hk(v2ray vmess tcp模式 只开了http伪装)--->德国服务器
2.本地--->hk(ssr auth_chain_a)--->德国服务器
1的v2ray比2的ssr操作延迟界面刷新等慢了很多,感觉太明显了,慢一倍

几个月前我就发现shadowsocks-libev有这个问题了,还在那边问过,遗憾我技术不够找不到原因,不了了之了
当时测试了v2ray(ss)和ssr都没延迟大问题,只有shadowsocks-libev才存在
最近开始用v2ray(vmess),发现延迟和当时shadowsocks-libev一样,几乎比ssr延迟大一倍

有条件的技术大牛不妨测试下,找到哪里出的问题
我个人理解,如果拿来做游戏代理服务器,一样会遇到这个问题

**Comment by agzfan** [comment]
不知道是否和这个有关....
https://fast.com
测试网速,ssr非常平滑,v2ray感觉就很卡,用的时间非常久,但是2个得到的速度结果是一样的

还有测试上传网盘,比如1fichier.com
ssr上传速度非常平滑
v2ray初期上传速度流量异常,把浏览器关了,发现还有网络流量持续很久,数据提前缓存在了v2ray客户端里了?

**Comment by DarienRaymond** [comment]
最新的版本中做了一些优化，有可能对延迟有帮助。如果还有问题请reopen，最好能附上debug log。
