### ISSUE TITLE
使用v2ray来替代shadowsocks服务器有什么好处？

### ISSUE THREAD

**Issue by Tourin** [v2ray/v2ray-core#630]
由于shadowsocks服务器最近IP经常被封，想替换成v2ray，
但是v2ray目前客户端没有shadowsocks客户端易用，所以想试试用v2ray做为shadowsocks服务器，
这样子和直接用shadowsocks服务器有什么区别，是否会更安全？

**Comment by kehao95** [comment]
围观，小白同问。

**Comment by tefiszx** [comment]
v2ray如果有个向ss一样易用的客户端当然很好。不过只要有一个合适的配置文件v2ray就可以抛开客户端了。而且楼主要用v2ray做ss的服，也要先搞定服务端的配置文件。否则什么都是白搭。很多小白都是倒在了配置文件上。

**Comment by franklee628** [comment]
事实上，当我的ss灰机第一次被击落后，我选择用v2ray来做服务器，当时还留恋ss的客户端，所以为v2ray添加了ss支持，然后大于12个小时后，不仅灰机被击落，机场也TM被炸了。

**Comment by DarienRaymond** [comment]
没有差别，V2Ray的ss是按ss标准来实现的，和其它的ss实现（如ss-libev）没有本质的差别。

**Comment by sssxyd** [comment]
昨天自己搭的灰机被击落，买的ss账号也连不上，终于下定决心换到v2ray。换了之后快很多，web和Android都快，很爽。

**Comment by Cwek** [comment]
其实没啥区别，我也是机了v2的ss入口集成，不过一来ss接入在国内的，不用爬绳子，vmess主力爬绳子。
v2是一个平台，mux多路复用，内部路由，一堆通用化的常规协议（ws，tls等），组合性更好。

**Comment by Justsoos** [comment]
> 但是v2ray目前客户端没有shadowsocks客户端易用

这样用来委婉的提意见，真是很有水平。起码是办公室副主任的人才，哈

**Comment by JeevanMa** [comment]
我也想问，我自己搭好了v2ray服务器，但是支持WMess的ios客户端很难找，所以我就用v2ray的shadowsocks服务，手机是成功连上了，但不确定这样跟直接用ss的服务有什么区别？ 是否更安全？

**Comment by Justsoos** [comment]
楼上其实已经说了，除非你的vps ip足够强大在白名单，比如 … 不建议近期使用ss协议，v2ray其他协议组合隐蔽性更好

**Comment by MartinOrange** [comment]
> 我也想问，我自己搭好了v2ray服务器，但是支持WMess的ios客户端很难找，所以我就用v2ray的shadowsocks服务，手机是成功连上了，但不确定这样跟直接用ss的服务有什么区别？ 是否更安全？

shadowrocket 支持vmess协议的

**Comment by Justsoos** [comment]
补充一下使用体验：在某些内核版本，或某些协议配置下，或某些特殊环境下，v2ray 可能实际会跑出真实流量几倍带宽（尤其是和kcp有关时），而ss/ssr基本上不会出现这个问题。

**Comment by yunkai-c** [comment]
> 补充一下使用体验：在某些内核版本，或某些协议配置下，或某些特殊环境下，v2ray 可能实际会跑出“有效流量”几倍的真实流量（尤其是和kcp有关时），而ss/ssr基本上不会出现这个问题。

我的NAS出现了，客户端几乎占满全部带宽，但不是有效速率

**Comment by MAOA-L** [comment]
ios的shadowrocket可以连接vmess协议
