### ISSUE TITLE
根据官网v2ray.com编译v2ray源文件时出错

### ISSUE THREAD

**Issue by pkron** [v2ray/v2ray-core#633]
正在使用的版本： v2.41

出错时软件输出：

root@locationfree:~# go get -u v2ray.com/core/...
package v2ray.com/core
        imports math/bits: unrecognized import path "math/bits" (import path does not begin with hostname)
root@locationfree:~# go get -u v2ray.com/ext/...
package math/bits: unrecognized import path "math/bits" (import path does not begin with hostname)
root@locationfree:~#

**Comment by DarienRaymond** [comment]
你需要Go 1.9
