### ISSUE TITLE
路由设置里的chinaip和chinasites是否有在更新？

### ISSUE THREAD

**Issue by zywsss** [v2ray/v2ray-core#640]
路由设置里的chinaip和chinasites这两个结果集有在更新的吗？
能否增加选项设置，可以单独配置这两个的在线地址或者本地文件路径？

**Comment by public15** [comment]
https://github.com/v2ray/ext/blob/master/tools/conf/router_chinasites.go

**Comment by public15** [comment]
好像chinaip是三个月左右手动更新一次

**Comment by DarienRaymond** [comment]
同上，chinaip是自动获取的，chinasites有需要的话可以发PR
