### ISSUE TITLE
优先使用 tls 配置中的 serverName 建立 tls 连接

### ISSUE THREAD

**Issue by CzBiX** [v2ray/v2ray-core#643]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
v2.41 

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
vmess+ws+tls

3)  你看到的不正常的现象是什么？
    What did you see?
tls 连接时，使用的是 vmess settings 里写的 address

4)  你期待看到的正确表现是怎样的？
    What's your expectation?
tls 连接时，**优先**使用 tlsSettings 中的 serverName

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Client Configuration File（客户端配置文件）:
```javascript
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "hello.com",
          "port": 443,
        }
      ]
    },
    "mux": {
      "enabled": true
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "tlsSettings": {
        "serverName": "example.com",
        "allowInsecure": false
      },
      "wsSettings": {
        "path": "/"
      }
  }
```

**Comment by happyeddie** [comment]
+1 之前花了好多时间在这个问题上，感觉应该是bug
