### ISSUE TITLE
git or ssh over v2ray not working!

### ISSUE THREAD

**Issue by ryancheung** [v2ray/v2ray-core#644]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

V2Ray v2.33 (One for all) 20170609

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

git or ssh over v2ray socks5 with proxychain4

3)  你看到的不正常的现象是什么？
    What did you see?

不通

4)  你期待看到的正确表现是怎样的？
    What's your expectation?

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Server Configuration File（服务器端配置文件）:
```javascript
"inbound": {
    "port": 443,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "8574c583-xxxxx70f20969f43b",
          "level": 1,
          "alterId": 64
        }
      ]
    }
  },
"streamSettings": {
    "network": "tcp",
    "tcpSettings": {
      "connectionReuse": true, //TCP 连接重用
      "header": { // header 这一项是关于数据包伪装的设置，可自定义合理的内容，但要确保服务器与客户端一致
        "type": "http",
        "request": {
          "version": "1.1",
          "method": "GET",
          "path": ["/"],
          "headers": {
            "Host": ["www.cloudflare.com", "www.amazon.com", "www.aliyun.com"], // 伪装的域名，如果注册有域名解析到了你的 VPS，使用自己的域名会使伪装更真实
            "User-Agent": [
                "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36",
                "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
            ],
            "Accept-Encoding": ["gzip, deflate"],
            "Connection": ["keep-alive"],
            "Pragma": "no-cache"
          }
        },
        "response": {
          "version": "1.1",
          "status": "200",
          "reason": "OK",
          "headers": {
            "Content-Type": ["application/octet-stream", "application/x-msdownload", "text/html", "application/x-shockwave-flash"],
            "Transfer-Encoding": ["chunked"],
            "Connection": ["keep-alive"],
            "Pragma": "no-cache"
          }
        }
      }
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ]
```

    Client Configuration File（客户端配置文件）:
```javascript
    // 在这里附上客户端配置文件
    // Please attach your client configuration file here.
```

6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.

    Server Log File（服务器端日志）:
```
    no log show git/ssh connection arrived.
```

    Client Log File（客户端日志）:
```
    // 在这里附上客户端日志
    // Please attach your client log here.
```

**Comment by ryancheung** [comment]
经测试 shadowsocks 支持 git/ssh，v2ray不支持。

**Comment by serika00** [comment]
git可以直接设置http代理指向v2ray的http inbound，ssh可以设置proxycommand nc -x指向一个socks inboud

**Comment by ryancheung** [comment]
macOS Serria 上试过了，都不行

**Comment by DarienRaymond** [comment]
请使用最新版，如果还不行的话，请发log和客户端配置。
