### ISSUE TITLE
Wifi电脑/手机 V2RAY连不上，手机V2RAY只有4G 可以连上....

### ISSUE THREAD

**Issue by ERIC027** [v2ray/v2ray-core#646]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
**2.36.2**
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
上GOOGLE,FACEBOOK, 等

3)  你看到的不正常的现象是什么？
    What did you see?

用V2RAY 这个上网。用了几个月感觉很不错，电脑上外网很稳定( 但上内/外网均需启动V2RAY)。

问题：

1. 电脑连接（一直用长城宽带）

- 前天用电脑也试了ssh，能连上，但很不稳定，弃之。（开了SSH后约1个小时,退出SSH）这之后电脑上网（长城宽带WIFI），再用V2RAY 就不行了，国内网，外网（谷歌，facebook等）都上不去。
- 退出V2RAY ，直连网络（无代理）时，国内内网才可以登上。

2. 手机连接 （手机是华为P9）

- 手机之前用宽带WIFI ,使用V2RAY 不是稳定，几分钟就掉线，得重新安装ACTINIUM 才行，然后运行几分钟，闪退，反复.....,  后来安装时选了”后台运行”，稳定了些，但运行1个多小时仍会掉线，只得重新安装。  
- 然后前天试了手机使用SSH,一直没成功。 之后重新用打开ACTINIUM,发现长城宽带的WIFI 连不上外网了，然后关掉WIFI, 只用4G，却能连上外网，WHATSAPP, Google, facebook 都能上。

- 然而 我的朋友用跟我相同的配置V2RAY, 在国内另外一个城市，却可以正常使用。

4)  你期待看到的正确表现是怎样的？
    What's your expectation?
能正常访问外网。

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).

 {
  "log": {
    "access": "",
    "error": "",
    "loglevel": ""
  },
  "inbound": {
    "port": 1080,
    "listen": "---------",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "----------",
      "clients": null
    },
    "streamSettings": null
  },
  "outbound": {
    "tag": "agentout",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "----------",
          "port": 3128,
          "users": [
            {
              "id": "016f8fce-a052-11e7-a133-42010a8c0003",
              "alterId": 64,
              "security": "chacha20-poly1305"
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "tcp",
      "security": "",
      "tcpSettings": {
        "connectionReuse": true,
        "header": {
          "type": "http",
          "request": {
            "version": "1.1",
            "method": "GET",
            "path": [
              "/"
            ],
            "headers": {
              "Host": [
                "www.cloudflare.com"
              ],
              "User-Agent": [
                "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36",
                "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
              ],
              "Accept-Encoding": [
                "gzip, deflate"
              ],
              "Connection": [
                "keep-alive"
              ],
              "Pragma": "no-cache"
            }
          },
          "response": {
            "version": "1.1",
            "status": "200",
            "reason": "OK",
            "headers": {
              "Content-Type": [
                "application/octet-stream",
                "application/x-msdownload",
                "text/html",
                "application/x-shockwave-flash"
              ],
              "Transfer-Encoding": [
                "chunked"
              ],
              "Connection": [
                "keep-alive"
              ],
              "Pragma": "no-cache"
            }
          }
        }
      },
      "kcpSettings": null,
      "wsSettings": null
    },
    "mux": {
      "enabled": true
    }
  },
  "inboundDetour": null,
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {
        "response": null
      },
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "blockout"
    }
  ],
  "dns": {
    "servers": [
      "*.*.*.*",
      "*.*.*.*",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": null,
          "outboundTag": "direct",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "domain": null
        },
        {
          "type": "chinasites",
          "port": null,
          "outboundTag": "direct",
          "ip": null,
          "domain": null
        },
        {
          "type": "chinaip",
          "port": null,
          "outboundTag": "direct",
          "ip": null,
          "domain": null
        }
      ]
    }
  }
}

**Comment by Explorare** [comment]
![image](https://user-images.githubusercontent.com/5090766/32006559-a777fd8e-b9d9-11e7-90c2-3605167b82f7.png)
目标是 Vultr LA 机房，目前移动、联通和流畅访问，电信 30% 丢包 BBR 基本废了，建议换个针对高丢包环境的策略。

**Comment by ERIC027** [comment]
SSH 及不稳定，时不时被第三方中止。  换成联通或移动会有用吗

**Comment by Explorare** [comment]
建议你测试一下，如果你是电信宽带，用联通卡走流量试试同一条线路。我这里是电信、联通双线接入的，电信线路基本没法用，联通的没问题。

**Comment by ERIC027** [comment]
现在是长城宽带。我发现启动SSH后，连手机的正常WIFI都接不上了。 之前一直用V2RAY 也是长城宽带，用得挺好。 自从3天前启动SSH后，啥都不行了。V2RAY 彻底死了。SSH启动的几秒钟内可连上谷歌等，然后闪退。 运行的黑框框里，有出现
.........
concurrent connections: 39
local error: Error: This socket has been ended by the other party
显然是被盯上了。。。

**Comment by DarienRaymond** [comment]
看上去像是 ISP 的阻断行为，和 V2Ray 本身无关。可以尝试 TLS + WebSocket 的方式来避开。

**Comment by vioao** [comment]
请问最后怎么解决的？我用的websocket+tls还是不行。只有移动数据网络可以。长城宽带得WIFI就不行

**Comment by 7kms** [comment]
> 请问最后怎么解决的？我用的websocket+tls还是不行。只有移动数据网络可以。长城宽带得WIFI就不行

我也不行啊，我是移动宽带wifi就不行，把电脑连到4g手机的wifi热点就可以。

不理解啊，求大神带一下呀

**Comment by Qking521** [comment]
我是联通，一模一样的现象。 只有移动网络可以，wifi和电脑端一样连不上。
请问楼主最有有没有解决方案

**Comment by kenis1108** [comment]
我是移动网络放手机热点可以，联通宽带不行，咋么办呢

**Comment by hjhdsg** [comment]
宽带是联通的，手机热点是移动的，移动的可以，联通的不行，但是台式机用联通的直接代理是可以的，就openwrt里不行
