### ISSUE TITLE
websocket能代理openvpn吗？

### ISSUE THREAD

**Issue by funbsd** [v2ray/v2ray-core#647]
我配置了一个最简单的websocket。
发现只能代理http和https，不能代理openvpn连接外网。
websocket不支持http/https之外的协议连接外网吗？

**Comment by funbsd** [comment]
另外，TLS可以代理OpenVPN连接外网吗？

**Comment by DarienRaymond** [comment]
请贴配置及log。另外传出代理只有socks，不支持 HTTP

**Comment by zhfreal** [comment]
ws作为v2ray服务器和客户端的传输协议，客户端inbound可任意http或者socks，代理openvpn没有问题。
注意v2ray一般是tcp，所以openvpn也要改成tcp协议。

**Comment by funbsd** [comment]
第一个测试没问题了，可能我之前哪块配置有问题。websocket，tls都可以代理openvpn。
第二个外发代理问题，我用的ccproxy socks做测试，v2ray客户端无法穿过ccproxy与服务器相连。
不知道是不是ccproxy的问题。

v2ray服务器配置：
{
  "log": {
    //"access": "/var/log/v2ray/access.log",
    //"error": "/var/log/v2ray/error.log",
    "loglevel": "info"
  },
  "inbound": {
    "port": 1080,
    "listen":"0.0.0.0",
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "6e8b22a3-ebf0-454d-bd90-d3f115702ce1",
          "alterId": 64
        }
      ]
    },
    "streamSettings":{
      "network":"ws",
      "wsSettings": {
        "path": "/ws"
      }
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  }
}

客户端配置：
{
  "log": {
    //"access": "/var/log/v2ray/access.log",
    //"error": "/var/log/v2ray/error.log",
    "loglevel": "debug"
  },
  "inbound": {
    "port": 1080,
    "listen": "0.0.0.0",
    "protocol": "http",
    "settings": {
      "auth": "noauth",
      "udp": false
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "172.31.2.1",
          "port": 1080,
          "users": [
            {
              "id": "6e8b22a3-ebf0-454d-bd90-d3f115702ce1",
              "alterId": 64
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "wsSettings": {
        "path": "/ws"
      }
    },
    "proxySettings": {
      "tag": "outboundProxy"
    }
  },
  "outboundDetour": [
    {
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 8081
          }
        ]
      },
      "tag": "outboundProxy"
    }
  ]
}

客户端日志：
2017/10/27 23:28:33 [Debug]App|Proxyman|Outbound: proxying to outboundProxy
2017/10/27 23:28:33 [Info]Proxy|VMess|Outbound: tunneling request to tcp:push-s.maxthon.com:80 via tcp:172.31.2.1:1080
2017/10/27 23:28:33 [Info]Transport|Internet|TCP: dailing TCP to tcp:127.0.0.1:8081
2017/10/27 23:28:34 [Info]App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > Proxy|VMess|Encoding: unexpected response header. Expecting 30 but actually 90
2017/10/27 23:28:36 [Info]App|Proxyman|Inbound: connection ends > Proxy|HTTP: connection ends > context canceled

**Comment by funbsd** [comment]
还有个问题，哪些代理服务器支持SOCKS进站，HTTP出站？我想转换一下。因为公司只能用HTTP代理上网。

**Comment by funbsd** [comment]
换了个外发代理dante，也是这个问题。
我用curl测试：
$ curl -iIkLv --socks5-hostname localhost:1080 http://www.domain.com
* STATE: INIT => CONNECT handle 0x600057830; line 1410 (connection #-5000)
* Rebuilt URL to: http://www.domain.com/
* Added connection 0. The cache now contains 1 members
* STATE: CONNECT => WAITRESOLVE handle 0x600057830; line 1446 (connection #0)
*   Trying ::1...
* TCP_NODELAY set
* STATE: WAITRESOLVE => WAITCONNECT handle 0x600057830; line 1527 (connection #0)
* SOCKS5 communication to www.domain.com:80
* Unable to receive initial SOCKS5 response.
* Closing connection 0
* The cache now contains 0 members
* Expire cleared
curl: (7) Unable to receive initial SOCKS5 response.

v2ray客户端日志：
2017/10/28 11:22:27 [Info]Proxy|HTTP: request to Method [GET] Host [crl.globalsign.net] with URL [http://crl.globalsign.net/root-r2.crl]
2017/10/28 11:22:27 [Debug]App|Proxyman|Outbound: proxying to outboundProxy
2017/10/28 11:22:27 [Info]Proxy|VMess|Outbound: tunneling request to tcp:crl.globalsign.net:80 via tcp:vpn.domain.com:80
2017/10/28 11:22:27 [Info]Transport|Internet|TCP: dailing TCP to tcp:192.168.127.49:1080
2017/10/28 11:22:27 [Warning]Proxy|HTTP: failed to read response from crl.globalsign.net > unexpected EOF
2017/10/28 11:22:27 [Info]App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > Proxy|VMess|Encoding: unexpected response header. Expecting 143 but actually 63
2017/10/28 11:22:27 [Info]App|Proxyman|Inbound: connection ends > Proxy|HTTP: failed to read http request > EOF
2017/10/28 11:22:29 [Warning]App|Proxyman|Inbound: connection ends > Proxy|HTTP: failed to read http request > malformed HTTP request "\x05\x02\x00\x01"

**Comment by funbsd** [comment]
还有个问题，为啥curl用不了v2ray的socks代理？IE可以。
$ curl -iIkLv --socks5-hostname localhost:1080 http://www.domain.com
* STATE: INIT => CONNECT handle 0x600057830; line 1410 (connection #-5000)
* Rebuilt URL to: http://www.domain.com/
* Added connection 0. The cache now contains 1 members
* STATE: CONNECT => WAITRESOLVE handle 0x600057830; line 1446 (connection #0)
*   Trying ::1...
* TCP_NODELAY set
* STATE: WAITRESOLVE => WAITCONNECT handle 0x600057830; line 1527 (connection #0)
* SOCKS5 communication to www.domain.com:80
* Unable to receive initial SOCKS5 response.
* Closing connection 0
* The cache now contains 0 members
* Expire cleared
curl: (7) Unable to receive initial SOCKS5 response.

v2ray客户端日志：
2017/10/28 11:22:27 [Info]Proxy|HTTP: request to Method [GET] Host [crl.globalsign.net] with URL [http://crl.globalsign.net/root-r2.crl]
2017/10/28 11:22:27 [Debug]App|Proxyman|Outbound: proxying to outboundProxy
2017/10/28 11:22:27 [Info]Proxy|VMess|Outbound: tunneling request to tcp:crl.globalsign.net:80 via tcp:vpn.domain.com:80
2017/10/28 11:22:27 [Info]Transport|Internet|TCP: dailing TCP to tcp:192.168.127.49:1080
2017/10/28 11:22:27 [Warning]Proxy|HTTP: failed to read response from crl.globalsign.net > unexpected EOF
2017/10/28 11:22:27 [Info]App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > Proxy|VMess|Encoding: unexpected response header. Expecting 143 but actually 63
2017/10/28 11:22:27 [Info]App|Proxyman|Inbound: connection ends > Proxy|HTTP: failed to read http request > EOF
2017/10/28 11:22:29 [Warning]App|Proxyman|Inbound: connection ends > Proxy|HTTP: failed to read http request > malformed HTTP request "\x05\x02\x00\x01"

**Comment by funbsd** [comment]
我大概搞明白了。代理协议、底层协议都得一致。我再想想怎么把这些代理串起来。

**Comment by funbsd** [comment]
好吧，其实还是没想明白。proxySettings的协议必须跟outbound一致吗？

**Comment by funbsd** [comment]
原来用openvpn通过公司http proxy可以连接我的服务器，后来不行了。
所以想在openvpn外面再包装一层，迷惑http proxy，达到穿墙的目的。

**Comment by nicholascw** [comment]
可以用Dokodemo把远端的OpenVPN映射到本地，参考我[转发SSH隧道的记录](https://www.nicho1as.wang/articles/ssh-tunnel-v2ray.html)
