### ISSUE TITLE
Http Inbound 是否考虑增加用户密码验证

### ISSUE THREAD

**Issue by happyeddie** [v2ray/v2ray-core#649]
目前没有验证机制，真心不敢放出来在公网使用，自己有个别软件需要用到http代理，望考虑，多谢

**Comment by DarienRaymond** [comment]
将会在下一版本中加入 Basic Authentication 支持。

**Comment by happyeddie** [comment]
666
昨天提 issues，今天就有了

**Comment by BenhoNNNN** [comment]
给你打82分！剩下的18分以666的形式返还。
