### ISSUE TITLE
路由器上如何设置，手机、pc直接wifi自动获取ip地址就可以FQ吗?不用再手机上和pc端在设置代理(路由器ip:端口)

### ISSUE THREAD

**Issue by wpyok500** [v2ray/v2ray-core#650]
路由器上如何设置，手机、pc直接wifi自动获取ip地址就可以FQ吗?不用再手机上和pc端在设置代理(路由器ip:端口)

**Comment by daiaji** [comment]
透明代理的规则要自己去用iptables写

**Comment by DarienRaymond** [comment]
同上，参考：https://www.v2ray.com/chapter_02/protocols/dokodemo.html
