### ISSUE TITLE
能在config.json里设置pidfile吗

### ISSUE THREAD

**Issue by hweidz** [v2ray/v2ray-core#655]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
2.44
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
看网页
3)  你看到的不正常的现象是什么？
    What did you see?
config.json找不到pidfile相关设置
4)  你期待看到的正确表现是怎样的？
    What's your expectation?
可以手工设定pidfile path

现在用supervisor去管理v2ray进程 想加入monit监控下cpu usage 如果高了就重启下
monit的process支持pidfile 前者subprocess没有打出pidfile的地方 倒是可以 supervisorctl pid 手工来 或者用monit的regex匹配进程 不过如果能直接在配置文件里输出pidfile最好

**Comment by DarienRaymond** [comment]
请问你是怎么启动V2Ray的，启动的同时保存一下pid就可以了吧，不用V2Ray进程来管这个事。如果你是用默认的安装文件，那么systemd会生成一个pid file: https://github.com/v2ray/v2ray-core/blob/master/tools/release/config/systemd/v2ray.service#L8

**Comment by hweidz** [comment]
用的是supervisor的subprocess 配置文件
command=/v2ray -config config.json

**Comment by DarienRaymond** [comment]
对 supervisor 不熟，大概是这样？https://stackoverflow.com/questions/13662849/anyway-to-get-the-id-of-processes-created-by-supervisord

**Comment by hweidz** [comment]
这个方法我知道 就是上面说的 “supervisorctl pid 手工来”
supervisor原理是启动一个supervisord守护进程 然后把所有管理的进程fork出来 比如这里是v2ray
问题是supervisor没提供方法指定子进程的pid到文件 只能用supervisorctl pid $(name)打到stdout

为什么要pidfile 这里我是想用monit来监控这个pidfile cpu或者mem溢出的时候自己重启
实在麻烦也没关系 monit也支持regex 进程名来做监控 麻烦你还特地搜了下stackoverflow 谢谢
