### ISSUE TITLE
Support basic authentication in http proxy

### ISSUE THREAD

**Issue by v2ray** [v2ray/v2ray-core#66]
It would be great that the http proxy can be configured with username/password authentication, so that users may set up public proxies but with limited access.

Side note: username/password authentication is already supported in SOCKS5 proxy.

**Comment by wofeiwo** [comment]
弱问一下这个enhancement的进展？
目前不太敢直接开httpproxy，毕竟流量有限，也怕别人滥用。但是也导致ps4等这种只支持httpproxy的玩意儿使用起来比较麻烦。

**Comment by DarienRaymond** [comment]
一般http代理是开在本地的，或者路由器上，你是多人共享的局域网？

**Comment by wofeiwo** [comment]
本地开的话，除非是路由（有时候用的凑合的老路由，MIPS还不是64，不一定能直接使用V2ray），否则为了使用ps4还得开个电脑做代理。
我是想直接开在oversea server上直接连。有些时候并不care流量加密（当然如果能支持https connect更好）。只是ps4之类的服务需要翻墙能够加速。

**Comment by DarienRaymond** [comment]
这种情况下用nginx之类的工具做个代理就行了，不一定要使用V2Ray

**Comment by DarienRaymond** [comment]
Will be fixed in next release.
