### ISSUE TITLE
第一次用v2ray速度超级慢,有什么办法优化?装锐速或者bbr什么的有用吗?

### ISSUE THREAD

**Issue by genics** [v2ray/v2ray-core#660]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    2.44

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    chrome 通过socks
3)  你看到的不正常的现象是什么？
    youtube速度只有最高300kbps,在打开mu的情况下~

4)  你期待看到的正确表现是怎样的？
    用的vultr能否上8000kbps
5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Server Configuration File（服务器端配置文件）:
```javascript
    // 在这里附上服务器端配置文件
    // Please attach your server configuration file here.
```
{
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 11982,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "2e26ef0d-44e2-45c5-9dc8-1b298c006083",
          "level": 1,
          "alterId": 64
        }
      ]
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }

    Client Configuration File（客户端配置文件）:
```javascript
    // 在这里附上客户端配置文件
    // Please attach your client configuration file here.
```
{
  "inbound": {
    "port": 1080, // 监听端口
    "protocol": "socks", // 入口协议为 SOCKS 5
    "settings": {
      "auth": "noauth"  //socks的认证设置，noauth 代表不认证，由于 socks 通常在客户端使用，所以这里不认证
    }
  },
  "outbound": {
    "protocol": "vmess", // 出口协议
    "settings": {
      "vnext": [
        {
          "address": "0.0.0.0", // 服务器地址，请修改为你自己的服务器 ip 或域名
          "port": 11982,  // 服务器端口
          "users": [
            {
              "id": "2e26ef0d-44e2-45c5-9dc8-1b298c006083",  // 用户 ID，必须与服务器端配置相同
              "alterId": 64 // 此处的值也应当与服务器相同
            }
          ]
        }
      ]
    },
	"mux": {"enabled": true}
  }
}

6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.

    Server Log File（服务器端日志）:
```
    // 在这里附上服务器端日志
    // Please attach your server log here.
```

    Client Log File（客户端日志）:
```V2Ray v2.44 (One for all) 20171026
An unified platform for anti-censorship.
2017/10/28 15:53:12 [Debug]App|Proxyman|Inbound: creating tcp worker on 0.0.0.0:1080
2017/10/28 15:53:12 [Warning]Core: V2Ray started
2017/10/28 15:59:10 [Warning]failed to handler mux client connection > Proxy|VMess|Outbound: connection ends > context canceled
    // 在这里附上客户端日志
    // Please attach your client log here.
```

**Comment by testcaoy7** [comment]
v2ray没问题，是你的线路不好。改良方案：
1、花高价买香港直连VPS
2、安装BBR

**Comment by 523860169** [comment]
mkcp可能会好点

**Comment by genics** [comment]
安装bbr后改善很大,能用了~谢谢  mckp我也试试

**Comment by poea13** [comment]
确实上了BBR后改善了很多啊，谢谢大佬的指点

**Comment by ramboygy** [comment]
感谢大佬，安装BBR后，速度快了10倍。再次感谢
