### ISSUE TITLE
v2ray能否穿透第三方http代理？

### ISSUE THREAD

**Issue by funbsd** [v2ray/v2ray-core#663]
使用场景是这样的：
公司只能用http代理上网，开始用openvpn设置代理就可以连通外网。但是现在openvpn连不通了。

如果使用v2ray客户端和服务器，中间没有其他代理，openvpn也是可以连通的。
但是如果像我们公司这样，中间有http代理，能否穿透过这个http代理？

研究v2ray好几天了，越搞越迷糊。求大神指点。

**Comment by ToutyRater** [comment]
根据你的描述，我觉得v2ray的传出代理可以实现你的要求，但问题在于v2ray的outbound没有http协议，所以你得另外找一个socks转http软件。

**Comment by funbsd** [comment]
理论上，如果v2ray客户端能将原始数据封装，然后通过http代理发给v2ray服务器端，那就是可以实现的。
好吧，这个应该就是VPN原理了。不知道v2ray能不能实现。

**Comment by funbsd** [comment]
@ToutyRater 传出代理好像只是转发原始数据，到不了v2ray服务器端。而且传出代理只是本地转发，而不是告诉下一跳代理转发。

**Comment by funbsd** [comment]
proxysettings确实封装了数据。但是好像跟其他代理软件配合不起来。不知道这种情况v2ray客户端和服务器端应该设置什么协议。搞了半天，还是不行。也没个例子。折腾死我了

**Comment by lewisxy** [comment]
二楼正解。
可以参照[这里](https://www.v2ray.com/chapter_03/outboundproxy.html)进行配置，把outbound的shadowsocks换成socks发送到本地A端口。找一个socks转换http的程序，监听本地A端口，协议SOCKS5，转发到HTTP代理（某远程B端口）。相当于通过HTTP代理发送由V2ray加密的数据给远程V2Ray服务器，但具体HTTP代理能不能转发TCP数据就不清楚了，毕竟HTTP在7层。

**Comment by DarienRaymond** [comment]
@funbsd 你需要一个高阶配置 [proxySettings](https://www.v2ray.com/chapter_02/01_overview.html#主传出连接配置（outbound）)。

简单来说你需要两个 outbound，一个socks 一个 vmess，socks 指向你的 socks -> http 转换程序，vmess 指向服务器的 vmess inbound，然后把 vmess outbound proxy 到 socks。具体的配置需要你自己参透。

**Comment by funbsd** [comment]
@DarienRaymond 我是这么做的，但是不好使。服务器vmess inbound能识别http 转换程序转发的http数据吗？

**Comment by funbsd** [comment]
v2ray客户端错误日志：
2017/10/29 10:12:15 [Info]Proxy|HTTP: request to Method [CONNECT] Host [www.baidu.com:443] with URL [//www.baidu.com:443]
2017/10/29 10:12:15 [Debug]App|Proxyman|Outbound: proxying to proxy
2017/10/29 10:12:15 [Info]Proxy|VMess|Outbound: tunneling request to tcp:www.baidu.com:443 via tcp:172.31.2.1:1080
2017/10/29 10:12:15 [Info]Transport|Internet|TCP: dailing TCP to tcp:127.0.0.1:8081
2017/10/29 10:12:15 [Info]App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > Proxy|VMess|Encoding: unexpected response header. Expecting 65 but actually 205
2017/10/29 10:12:15 [Warning]Proxy|HTTP: failed to read response from e.firefoxchina.cn > unexpected EOF
2017/10/29 10:12:16 [Info]App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > Proxy|VMess|Encoding: unexpected response header. Expecting 9 but actually 41
2017/10/29 10:12:18 [Info]App|Proxyman|Inbound: connection ends > Proxy|HTTP: connection ends > context canceled

v2ray客户端配置：

{
  "log": {
    //"access": "/var/log/v2ray/access.log",
    //"error": "/var/log/v2ray/error.log",
    "loglevel": "debug"
  },
  "inbound": {
    "port": 8888,
    "listen": "0.0.0.0",
    "protocol": "http",
    "settings": {
      "auth": "noauth",
      "udp": false
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "172.31.2.1",
          "port": 1080,
          "users": [
            {
              "id": "6e8b22a3-ebf0-454d-bd90-d3f115702ce1",
              "alterId": 64
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "wsSettings": {
        "path": "/ws"
      }
    },
    "proxySettings": {
      "tag": "proxy"
    }
  },
  "outboundDetour": [
    {
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 8081
          }
        ]
      },
      "tag": "proxy"
    }
  ]
}

v2ray服务器配置：
{
  "log": {
    //"access": "/var/log/v2ray/access.log",
    //"error": "/var/log/v2ray/error.log",
    "loglevel": "info"
  },
  "inbound": {
    "port": 1080,
    "listen":"0.0.0.0",
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "6e8b22a3-ebf0-454d-bd90-d3f115702ce1",
          "alterId": 64
        }
      ]
    },
    "streamSettings":{
      "network":"ws",
      "wsSettings": {
        "path": "/ws"
      }
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  }
}

**Comment by funbsd** [comment]
又仔细想了一下，测试底层是tcp的时候是可以的。
websocket不行，因为http中转代理是tcp，不支持websocket。
tls的时候也不行，因为http中转代理不发起tls握手。

**Comment by funbsd** [comment]
研发完感觉不能穿透公司的http代理。
因为是普通tcp，即没有tls，也不是http，估计会被拒掉。

明天去公司试试，碰碰运气。
顺便试试tls和websocket。没准公司用的是高大上的代理，什么都支持。

**Comment by ToutyRater** [comment]
@funbsd 还得多学习一个啊。如果只是转发了原始数据，到不了v2ray服务端，那说明你配置不对。而且传出代理与inbound无关，主要是outbound和其中的proxySettings，参考[这里](https://www.v2ray.com/chapter_02/01_overview.html#%E4%B8%BB%E4%BC%A0%E5%87%BA%E8%BF%9E%E6%8E%A5%E9%85%8D%E7%BD%AE%EF%BC%88outbound%EF%BC%89)，[这里](https://github.com/v2ray/v2ray-core/issues/306)，[这里](https://www.v2ray.com/chapter_03/outboundproxy.html)，还有[这里](https://toutyrater.github.io/advanced/outboundproxy.html)。给了这么链接还搞不定，那应该是有其它方面的短板限制了你的理解和实操能力

**Comment by funbsd** [comment]
@ToutyRater 我前面已经分析了，已经搞定tcp穿透中间代理了。但是搞不定websocket和tls穿透中间代理，你有办法？给我这么多参考都没啥用。

如果不支持websocket和tls穿透中间代理，那希望v2ray能有2个inbound，一个http inbound接收数据，然后转给另一个vmess inbound解析数据。
或者v2ray自己能实现http outbound，来达到上面的目的。
这样才能更好的隐藏自己，否则纯tcp，稍微有点安全意识的公司，都过不了中间代理。

**Comment by funbsd** [comment]
刚又测试了组合websocket+tls，客户端和服务器端直连可以，但是经过中间代理就不行了。
理论上应该ok的。组合之后应该是https，一般代理都支持的。
各位大神，有啥提示吗？

经过中间代理后，服务器报错：
 tls: oversized record received with length 39041

客户端报错：
2017/10/29 14:29:32 [Debug]App|Proxyman|Outbound: proxying to proxy
2017/10/29 14:29:32 [Info]Proxy|VMess|Outbound: tunneling request to tcp:newtab.firefoxchina.cn:80 via tcp:172.31.2.1:44
3
2017/10/29 14:29:32 [Info]Transport|Internet|TCP: dailing TCP to tcp:127.0.0.1:1080
2017/10/29 14:29:32 [Info]App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection e
nds > Proxy|VMess|Encoding: unexpected response header. Expecting 163 but actually 66
2017/10/29 14:29:32 [Warning]Proxy|HTTP: failed to read response from newtab.firefoxchina.cn > unexpected EOF
2017/10/29 14:29:39 [Warning]App|Proxyman|Inbound: connection ends > Proxy|HTTP: failed to read http request > malformed
 HTTP request "d\x00\x00\x00|6\x00\x00\x1a\x00\x00\x00e\x00\x10\x00\x00\x0000FF193528FCPYCQ\x00\x00\x00\x00"

**Comment by funbsd** [comment]
好吧，又忽略了这个问题，跟v2ray服务器连接的是中间代理，而不是v2ray客户端，不能完成握手。
websocket+tls再通过中间代理的方法不通。
但是为什么可以代理https网站呢？
websocket+tls和纯https有啥区别？

**Comment by funbsd** [comment]
单tls经过中间代理后，也是这个报错，看来只要解决tls握手问题，这个问题就解决了。

**Comment by funbsd** [comment]
有啥软件可以做ssl/tls套，伪装https，支持代理转发？其实我要找到就是这么个东西。
openvpn已经被识别了，不能用了。v2ray tls代理转发报错。
还有啥软件可以实现这个功能？

**Comment by funbsd** [comment]
抓包发现中间代理根本就没发送client hello，直接就是数据。
浏览器经过中间代理就会发送client hello。
怎么才能让中间代理对待v2ray像对待浏览器那样发送client hello？

**Comment by funbsd** [comment]
把websocket当作普通的tcp，也能过中间代理连接服务器。不过没啥意义，这样还不如直接用tcp。

**Comment by undirectlookable** [comment]
曾经提过，但是作者不计划支持，见 #450

**Comment by daiaji** [comment]
outbound的http这个可以有啊

**Comment by marskid** [comment]
stunnel可以发起connect请求到代理
client = yes
accept = 127.0.0.1:8080
connect = proxy:port
protocol = connect
protocolHost = HOST:PORT

**Comment by marskid** [comment]
然后改hosts文件，将域名指向127.0.0.1，端口号也要一致，应该能过支持connect方法的代理。

**Comment by marskid** [comment]
忘记讲了，stunnel的connect端必须是https协议，accept端会转成http协议，v2ray对应配置要改的

**Comment by pennz** [comment]
@funbsd 我记得我按照websocket+tls经过中间代理的方法可以成功。有时间给你抓包看看。

**Comment by Equim-chan** [comment]
你可以尝试使用一下我写的 h2s，它可以将一个或多个 HTTP/HTTPS 代理转为一个 SOCKS5 代理。

我写 h2s 主要就是为了解决 v2ray 不支持 http 传出的问题，另外就是目前 SOCKS 转 HTTP 的很多，但反过来的似乎没有。

https://github.com/Equim-chan/h2s

**Comment by HarukaFuture** [comment]
你好
#1813
你的夙愿已成。

**Comment by QGB** [comment]
```
2022/07/13 10:50:12 [Info] [2530046704] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: failed to open connection to tcp:jcxxxxxxx.tt:443 > v2ray.com/core/common/retry: [dial tcp 2*****9:443: connect: connection refused] > v2ray.com/core/common/retry: all retry attempts failed
2022/07/13 10:50:12 [Info] [2530046704] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe

```
