### ISSUE TITLE
为何手机V2RAY启动后1~2小时就掉线，并且必须卸载重新安装后，再次启动才可以连上，每天都是这样。

### ISSUE THREAD

**Issue by ERIC027** [v2ray/v2ray-core#670]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
ACTIMIUM 0.10.2

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
Whatsapp,google,facebook,...

3)  你看到的不正常的现象是什么？
    What did you see?
每次启动后最多2小时，VPN 就失效了，重启没用，只有卸载后重启才能连上。

4)  你期待看到的正确表现是怎样的？
    What's your expectation?
启动后别掉线，或者掉线后，再次重启就能连上。 不必卸载，再重新安装。

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).
按下载版本，未做修改。

   
```

**Comment by DarienRaymond** [comment]
请至Actinium的repo提交相关问题：https://github.com/V2Ray-Android/Actinium
