### ISSUE TITLE
国内VPS中转不能正常使用

### ISSUE THREAD

**Issue by liuminglm** [v2ray/v2ray-core#673]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

#  v2.45

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

#  电脑通过VMess使用google等网站

3)  你看到的不正常的现象是什么？
    What did you see?
#  按照https://www.v2ray.com/chapter_05/00_config/07_vps_relay.html进行配置，只修改了必要的id，address等，提示：Main: failed to read config file: /jffs/V2Ray2/config.json > Ext|Tools|Conf|Serial: failed to read config file > invalid character ':' after array element

4)  你期待看到的正确表现是怎样的？
    What's your expectation?
#  可以正常国内中转

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Server Configuration File（服务器端配置文件）:
```javascript
    // 在这里附上服务器端配置文件
    // Please attach your server configuration file here.
```
{
  "log" : {                                 // [日志](../chapter_02/01_overview.md)
    "access": "/var/log/v2ray/access.log",  // 访问日志文件
    "error": "/var/log/v2ray/error.log",    // 错误日志文件
    "loglevel": "warning"                   // 错误日志等级
  },
  "inbound": {              // 主传入协议
    "port": 12345,          // 主端口
    "protocol": "vmess",    // 在这里使用 [VMess 协议](../chapter_02/protocols/vmess.md)
    "settings": {
      "clients": [
        {
          "id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", // UUID
          "level": 1,       // 用户等级
          "alterId": 64     // 额外ID
        }
        // 在这里添加更多用户，注意UUID不能重复
        ,{
          "id": "yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy", // UUID
          "level": 0,       // 用户等级
          "alterId": 32     // 额外ID
        }
      ]
    }
  },
  // ========== BEGIN STEP 1 ==========
  // 国内服务器当作国外服务器的“客户端”
  // 国际流量发往国外服务器上
  "outbound": {
    "protocol": "vmess",        // 出口协议
    "settings": {
      "vnext": [
        {
          "address": "1.2.3.4", // 国外服务器地址
          "port": 23456,        // 国外服务器端口
          "users": [
            {"id": "zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz"} // 用户 ID，须与国外服务器端配置相同
          ]
        }
      ]
    }
  },
  // ========== END STEP 1 ==========
  "outboundDetour": [       // 额外传出协议
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
    // ========== BEGIN STEP 2 ==========
    // 增加freedom传出绕路，国内流量直接放行
    ,{
      "protocol": "freedom",
      "tag": "direct",
      "settings": {}
    }
    // ========== END STEP 2 ==========
  ],
  "routing": {                  // 路由设置
    "strategy": "rules",
    "settings": {
      "rules": [
          // ========== BEGIN STEP 3 ==========
          // 配置国内网站和IP直连规则
          {
            "type": "chinaip", // 对于所有国内的 IP，都采用直连模式
            "outboundTag": "direct"
          },
          {
            "type": "field",  // 对于一些常见的网站，也使用直连模式
            "domain": [
              "qq.com",
              "baidu.com"
            ],
            "outboundTag": "direct"
          },
          // ========== END STEP 3 ==========
          "type": "field",      // 不允许客户端访问服务端的局域网地址，以提升安全性
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}
    Client Configuration File（客户端配置文件）:
```javascript
    // 在这里附上客户端配置文件
    // Please attach your client configuration file here.
```

6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.

    Server Log File（服务器端日志）:
```
    // 在这里附上服务器端日志
    // Please attach your server log here.
```
#  V2Ray v2.45 (One for all) 20171029
#  An unified platform for anti-censorship.
#  Main: failed to read config file: /jffs/V2Ray2/config.json > Ext|Tools|Conf|Serial: failed to read config #  #  file > invalid character ':' after array element

    Client Log File（客户端日志）:
```
    // 在这里附上客户端日志
    // Please attach your client log here.
```

**Comment by DarienRaymond** [comment]
[样例](https://www.v2ray.com/chapter_05/00_config/07_vps_relay.html)已更新，之前的 JSON 格式有问题，导致无法正常加载，现在可以了。
