### ISSUE TITLE
v2ray-linux-arm在android真机上通过“ProxyDroid+本地PAC”代理问题

### ISSUE THREAD

**Issue by wansen** [v2ray/v2ray-core#674]
目前远程VPS和windows、android本地都是使用的V2.45版，因v2ray客户端目前在android上都是以VPN模式运行，我本人比较喜欢的是NAT模式运行，经过摸索，发现通过已编译的v2ray-linux-arm直接在手机上开一个http代理1080端口（可能是v2ray的sock端口太先进，很多软件不能与sock代理端口交换数据，请恕我表达不专业），将PAC文件内代理修改为PROXY 127.0.0.10:1080后，再通过ProxyDroid加载本地的PAC文件，没想到竟然可以联网。

在此，要感谢v2ray、ProxyDroid、PAC白名单的开发者。

目前存在如下问题：
因为我使用的是由breakwa11编写的白名单(https://github.com/breakwa11/gfw_whitelist)，现在发现白名单以外的网址都 可以正常访问，而白名单以内的网址（就是国内的）均无法访问，如访问www.myip.cn，手机上提示错误为：[Warning]App|Proxyman|Inbound: connection ends > Proxy|HTTP: malformed proxy host: www.myip.cnhttp: > strconv.Atoi: parsing "": invalid syntax

因为我不是专业人员，所以来反馈一下问题，请帮我看看是什么原因造成的，谢谢！

**Comment by DarienRaymond** [comment]
看上去host的值有点问题，请确认输出信息中，host的值为`www.myip.cnhttp:`，正常的情况应该是`www.myip.cn`。

当然在这种情况下，V2Ray报错值得商榷。

**Comment by wansen** [comment]
谢谢回复，我来追查一下hosts的问题

**Comment by wansen** [comment]
首先我的v2ray配置为

{
  "log": {
    "access": "/dev/fscklogs/access.log",
    "error": "/dev/fscklogs/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 1080,
    "domainOverride": ["http", "tls"],
    "listen": "127.0.0.10",
    "protocol": "http",
    "settings": {
      "timeout": 30
      }
  },
  "outbound": {
    "protocol": "vmess",
    "tag": "http",
    "settings": {
      "vnext": [
        {
          "address": "xx.xx.xx.xx", 
          "port": 8888,
          "users": [
            {
              "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
              "alterId": 64,
              "security": "chacha20-poly1305"
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "tcp",
      "tcpSettings": {
        "header": {
          "type": "http",
          "request": {
            "version": "1.1",
            "method": "GET",
            "path": ["/"],
            "headers": {
	      "Host": ["baidu.com"],
              "User-Agent": [
                "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36",
                        "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
              ],
              "Accept-Encoding": ["gzip, deflate"],
              "Connection": ["keep-alive"],
              "Pragma": "no-cache"
            }
          }
        }
      }
    }
  },
  "outboundDetour": [
    {
    "protocol": "vmess",
    "tag": "tls",
    "settings": {
      "vnext": [
        {
          "address": "xx.xx.xx.xx",
          "port": 443,
          "users": [
            {
              "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
              "alterId": 64,
              "security": "chacha20-poly1305"
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "tlsSettings": {
         "serverName": "www.apple.com",
         "allowInsecure": false
         },
      "wsSettings": {
         "connectionReuse": true,
         "path": "/",
         "headers": {
            "Host": "baidu.com"
          }
        }
      }
    },
    {
      "protocol": "blackhole",
      "settings": {
         "response": {
            "type": "http"
         }
      },
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "AsIs", 
      "rules": [
        {
          "type": "field",
          "domain": [
              "msg.71.com",
              "newloc.map.n.shifen.com"
            ],
          "outboundTag": "blocked"
        },
        {
          "type": "field",
          "ip": [
                "12.34.56.78",
                "23.34.45.56"
              ],
          "outboundTag": "blocked"
        },
        {
          "type": "field",
          "domain": [
              "dropbox.com"
            ],
          "outboundTag": "tls"
        }
      ]
    }
  }
}

手机端通过dnsmasq监听53端口，给出的log为：
Nov  3 19:16:36 dnsmasq[14621]: query[A] www.speedtest.cn from 192.168.1.173
Nov  3 19:16:36 dnsmasq[14621]: forwarded www.speedtest.cn to 114.114.114.114
Nov  3 19:16:36 dnsmasq[14621]: query[A] www.myip.cn from 192.168.1.173
Nov  3 19:16:36 dnsmasq[14621]: forwarded www.myip.cn to 114.114.114.114
Nov  3 19:16:36 dnsmasq[14621]: Maximum number of concurrent DNS queries reached (max: 150)
（已删除重复部分）
其中，国内的直接走114.114.114.114。

谢谢！

**Comment by wansen** [comment]
我不太懂原理，可不可加上以下命令：
iptables -t nat -I OUTPUT -d 114.114.114.114 -p udp --dport 53 -j ACCEPT
iptables -t nat -I OUTPUT -d 114.114.114.114 -p udp --dport 53 -j RETURN

**Comment by wansen** [comment]
不使用dnsmasq, 其它配置不变的情况下测试了ProxyDroid代理dns 或不代理的情况，得到一样的结果，即白名单下国内网站不能访问。

**Comment by DarienRaymond** [comment]
顺便提一句，你用的是HTTP inbound而不是socks。

我修了那个报错的问题，但如果域名的确被改成了`www.myip.cnhttp:`，那一定是访问不到的。看上去不像是v2ray做了这样的修改，应该是你的某个其它的工具改的。

**Comment by wansen** [comment]
是我测试的不充分，现在的情况是，在v2ray 内设置了允许访问的网址，如dropbox.com，可以正常访问，反之，都出现上述错误；不论出口协议是使用tcp 或ws, 我上午再测试一下：其它不变的情况下，kill v2ray 后国内网址的连网情况；其它情况不变的情况下，让shadowsocks 打开一个本地代理端口（ss不代理任何流量或程序），让pac 指定此端口后看看能否正常访问内外网，到时再来报告情况

**Comment by wansen** [comment]
又经过测试，发现应该是ProxyDroid对breakwa11编写的黑、白名单支持不好造成的正在向Max Lv反馈ProxyDroid的问题。
非常感谢你的回复，如果还有什么其它的问题，我再来向你反馈。
