### ISSUE TITLE
V2Ray多用户配置的正确姿势究竟是怎样？

### ISSUE THREAD

**Issue by jinaviva** [v2ray/v2ray-core#679]
SS目前被针对太狠，换v2ray一试，非常好用，除了json配置方式上有时候粗心会出坑，总得来说一切都很顺利就配置好使用了。包括3种不同类型的传输配置，可以说是目前科学上网工具界的先行者，唯一就是客户端生态环境稍微弱，还有就是始终不明白vmess协议的多用户究竟该如何配置，alterid究竟是个啥意思？同一个uuid，不同的email区分用户？有没有多用户管理接口？也没找到相应的文档说明。需要多用户功能，主要是想稍微配置多几个账户和朋友一起使用。

**Comment by BenhoNNNN** [comment]
https://www.v2ray.com/chapter_02/protocols/vmess.html

https://toutyrater.github.io/basic/vmess.html

**Comment by qingfengshi** [comment]
如果是多用户的话，多个uuid要怎么书写呢？使用{}，用，隔开？

**Comment by BenhoNNNN** [comment]
没明白你的字面意思  画个拓扑草图看看

**Comment by qingfengshi** [comment]
按照文档，uuid用来区分不同的用户，那么如果是多用户，每个用户需要一个id，此时配置文件中就会出现多个uuid。在这样的情况下，多个uuid要怎么书写呢？是{uuid1,
uuid2, uuid3,......}的形式吗？

**Comment by DarienRaymond** [comment]
```javascript
clients: [
  {id: "xxxx", alterId: 64},
  {id: "yyyy", alterId: 64}
]
```

**Comment by qingfengshi** [comment]
OK，多谢老大

**Comment by gentlebrother** [comment]
"clients": [
  {"id": "xxxx", "alterId": 64},
  {"id": "yyyy", "alterId": 64}
]

新添加的id，无效，提示500 Internal Privoxy Error  不知道，新加id还要在哪里设置

**Comment by hyperbeta** [comment]
alterid究竟是个啥意思？

alterId 参数，这个参数主要是为了加强防探测能力。理论上 alterId 越大越好，但越大就约占内存(只针对服务器，客户端不占内存)，所以折中之下设一个中间值才是最好的。那么设多大才是最好的？其实这个是分场景的，我没有严格测试过这个，不过根据经验，alterId 的值设为 30 到 100 之间应该是比较合适的。alterId 的大小要保证客户端的小于等于服务器的。

**Comment by jiulingxing** [comment]
config.json这个配置文件没有用，修改了里面的内容没有反应，然后我把这个文件删除都还可以正常使用

**Comment by changjiangblog** [comment]
多用户共用一个端口还是每个用户对应一个单独的端口比较好呢

**Comment by 0polar** [comment]
@changjiangblog
很显然是多用户共用一个端口
因为真实的web服务器都只开一个端口

**Comment by rainbowshine521** [comment]
如果多用户共用一个端口，可不可以分开用户统计流量出来？

**Comment by kslr** [comment]
@rainbowshine521 https://v2ray.com/chapter_02/stats.html

**Comment by GavinMT233** [comment]
> config.json这个配置文件没有用，修改了里面的内容没有反应，然后我把这个文件删除都还可以正常使用

我也有这样的情况，你是怎么解决的？

**Comment by ck2020** [comment]
create new UUID 
# cat /proc/sys/kernel/random/uuid

example config : multi port , multi  user 


`{
  "inbounds": [{
    "port": 1234,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "UUID",
          "level": 1,
          "alterId": 64
        },
        {
          "id": "UUID",
          "level": 1,
          "alterId": 64
        }
      ]
    }
  },
 {
    "port": 1235,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "UUID",
          "level": 1,
          "alterId": 64
        },
        {
          "id": "UUID",
          "level": 1,
          "alterId": 64
        }
      ]
    }
  }],
  "outbounds": [{
    "protocol": "freedom",
    "settings": {}
  },{
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  }],
  "routing": {
    "rules": [
      {
        "type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "blocked"
      }
    ]
  }
}`

**Comment by lijiaqi213** [comment]
添加多账户的目的是什么？

新手求问 为什么不能多个人用一个uuid。。。

**Comment by jellycsc** [comment]
> 添加多账户的目的是什么？
> 
> 新手求问 为什么不能多个人用一个uuid。。。

开机场呗，监测限制流量，卖钱

**Comment by AllenKOO** [comment]
> > config.json这个配置文件没有用，修改了里面的内容没有反应，然后我把这个文件删除都还可以正常使用
> 
> 我也有这样的情况，你是怎么解决的？

Reload配置文件

**Comment by aojie654** [comment]
> > config.json这个配置文件没有用，修改了里面的内容没有反应，然后我把这个文件删除都还可以正常使用
> 
> 我也有这样的情况，你是怎么解决的？

保存完配置记得要restart v2ray

**Comment by tzwjkl** [comment]
如果仅仅是和朋友共用一个v2ray，不求各类统计，需不需要使用不同的uuid？两台主机同时使用同一个uuid连接服务端会不会出现错误？

**Comment by aojie654** [comment]
> 如果仅仅是和朋友共用一个v2ray，不求各类统计，需不需要使用不同的uuid？两台主机同时使用同一个uuid连接服务端会不会出现错误？

完全可以,
我理解中的uuid只是用来区分用户的, 如果不需要做区分多个终端可以用同一个

**Comment by CQNM** [comment]
考古，目前使用在一个端口下加用户ID是可以使用的，但是加了端口后，在新加的端口下放用户ID，无法使用，服务器防火墙已经放通，格式也没问题，怀疑是新端口不能用就端口的配置域名。（模式是 VMESS+TLS）

**Comment by jinbaolu** [comment]
我就很奇怪，mac下可以使用，分享到iPad和iPhone就不行了
