### ISSUE TITLE
v2ray 的 Domain list 功能

### ISSUE THREAD

**Issue by wmjlxl** [v2ray/v2ray-core#689]
请问 v2ray 的 Domain 规则可以加入类似：

p,k,s,r分别表示 prefix (前缀)，keyword(关键词),suffix(后缀),regex(正则表达式)

这样就可以更方便的编写属于自己的规则了，谢谢。

**Comment by DarienRaymond** [comment]
https://www.v2ray.com/chapter_02/03_routing.html
