### ISSUE TITLE
v2.46 Linux X64  "geoip:cn" 问题。 

### ISSUE THREAD

**Issue by liumailong** [v2ray/v2ray-core#693]
v2.46 在Linux X64 中启动报错。
`root@MikroTik:~# ./v2ray-v2.46-linux-64/v2ray
V2Ray v2.46 (One for all) 20171102
An unified platform for anti-censorship.
Main: failed to read config file: /root/v2ray-v2.46-linux-64/config.json > Ext|Tools|Conf|Serial: failed to parse json config > Ext|Tools|Conf: invalid field rule > Ext|Tools|Conf: failed to load GeoIP: cn > proto: router.GeoIPList: illegal tag 0 (wire type 0)`

多次测试后发现是默认路由设置中的“IP'”项目里的 "geoip:cn" 的问题，把这个语句删除就行了

**Comment by xwy2010** [comment]
GeoIP.dat 文件没有吧

**Comment by DarienRaymond** [comment]
`./v2ray-v2.46-linux-64/` 文件夹下面有 geoip.dat 吗，文件有多大？

**Comment by liumailong** [comment]
有
```
geoip.dat
文件大小: 5.03 MB (5,275,648 字节)
MD5: 6BFFBF77AF097F13DDF76B0BD87543B1
```
因为这个文件大小和Win版的不同，最开始也觉是它的问题。
尝试过替换Win版的geoip.dat，但结果一样。

**Comment by DarienRaymond** [comment]
hmmmmm，暂时想不到是什么原因。

**Comment by DarienRaymond** [comment]
正常的 geoip.dat 应该是 4.3MB (4,272,640 字节)，你的文件似乎大了很多的样子。

**Comment by liumailong** [comment]
抱歉，发现是文件管理TotalCMD 的 BUG，从压缩包中向SMB服务器 写入 geoip.dat 就会出错。
第一次见到这样的BUG。浪费了你的时间，抱歉。
