### ISSUE TITLE
关于 http 伪装的一个问题，请教一下！

### ISSUE THREAD

**Issue by jzp820927** [v2ray/v2ray-core#695]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
通过源码编译的最新版

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
使用 Chrome 通过 VMess 浏览网页

3)  你看到的不正常的现象是什么？
    What did you see?
在 outbound 配置的 vmess 协议上，同时配置 HTTP 伪装和 传出代理 则无法正常使用，单独配置 HTTP 伪装，或者 传出代理，则没有问题。难道是 “HTTP 伪装” 和 "传出代理" 这2个配置有冲突？不能同时配置？

4)  你期待看到的正确表现是怎样的？
    What's your expectation?
在 outbound 配置的 vmess 协议上，同时配置 HTTP 伪装和 传出代理 能正常工作。

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Server Configuration File（服务器端配置文件）:
```javascript
    // 在这里附上服务器端配置文件
    // Please attach your server configuration file here.
```
服务端的配置：
　"inbound": {
　　"port": 80,
　　"protocol": "vmess",
　　"settings": {
　　　"clients": [
　　　　{
　　　　　"id": "uuid (隐藏)",
　　　　　"alterId": 64,
　　　　　"level": 1
　　　　}
　　　]
　　},
　　"streamSettings": {
　　　"network": "tcp",
　　　"tcpSettings": {
　　　　"header": {
　　　　　"type": "http",
　　　　　"response": {
　　　　　　"version": "1.1",
　　　　　　"status": "200",
　　　　　　"reason": "OK",
　　　　　　"headers": {
　　　　　　　"Content-Type": ["application/octet-stream", "video/mpeg"],
　　　　　　　"Transfer-Encoding": ["chunked"],
　　　　　　　"Connection": ["keep-alive"],
　　　　　　　"Pragma": "no-cache"
　　　　　　}
　　　　　}
　　　　}
　　　}
　　}
　}

    Client Configuration File（客户端配置文件）:
```javascript
    // 在这里附上客户端配置文件
    // Please attach your client configuration file here.
```
客户端的配置：
　{
　　"protocol": "vmess",
　　"tag": "http",
　　"settings": {
　　　"vnext": [{
　　　　　"address": "server ip 或者 域名 (隐藏)",
　　　　　"port": 80,
　　　　　"users": [{
　　　　　　"id": "uuid (隐藏)",
　　　　　　"alterId": 64
　　　　　}]
　　　　}]
　　},
　　"streamSettings": {
　　　"network": "tcp",
　　　"tcpSettings": {
　　　　"header": {
　　　　　"type": "http",
　　　　　"request": {
　　　　　　"version": "1.1",
　　　　　　"method": "GET",
　　　　　　"path": ["/"],
　　　　　　"headers": {
　　　　　　　"Host": ["www.baidu.com", "www.bing.com"],
　　　　　　　"User-Agent": [
　　　　　　　　"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36",
　　　　　　　　"Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
　　　　　　　],
　　　　　　　"Accept-Encoding": ["gzip, deflate"],
　　　　　　　"Connection": ["keep-alive"],
　　　　　　　"Pragma": "no-cache"
　　　　　　}
　　　　　}
　　　　}
　　　}
　　},
　　"proxySettings": {
　　　"tag": "ss 的 tag"
　　}
　}
其他配置没改，是默认的，SS 在 v2ray 中的配置也测试过能正常工作。

6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.

    Server Log File（服务器端日志）:
```
    // 在这里附上服务器端日志
    // Please attach your server log here.
```
服务器一直报下面的错
2017/11/08 16:16:31 传出代理 SS 的 IP:55982 rejected  Proxy|VMess|Encoding: failed to read request header > read tcp 服务器的 IP:80->传出代理 SS 的 IP:55982: i/o timeout

    Client Log File（客户端日志）:
```
    // 在这里附上客户端日志
    // Please attach your client log here.
```
客户端没有报错信息

**Comment by DarienRaymond** [comment]
对。proxySettings比streamSettings优先级高，一旦proxy掉了，整个streamSettings不起作用。

**Comment by jzp820927** [comment]
一旦proxy掉了？...是指的 传出代理 SS 的稳定性嘛？这个应该没有问题的，我把 http 伪装的配置去掉，单独配置 传出代理 SS 是没有任何问题的。并且单独配置 http 伪装，把 传出代理 SS 的配置去掉，也没有任何问题，也就是说，http 伪装 和 传出代理 SS 单独配置的时候，都没有任何问题。就是这2个配置同时存在的时候，就出问题了。挺奇怪的。

**Comment by DarienRaymond** [comment]
-_- 我修改了原文，本意是说一旦配置了proxySettings，则streamSettings不起作用。

**Comment by jzp820927** [comment]
也就是说，这2个配置无法同时工作？从你上面的说明，好像是 proxySettings 优先级最高，如果配置了，数据就被直接转发出去了，不会再接受客户端配置文件中的其他任何处理操作了？不清楚 v2ray 的内部处理逻辑是怎么工作的，但是感觉上，这2个配置应该是独立，无冲突的，先封装数据包为 http 协议格式，然后再通过代理 转发到目标服务器。像这种问题能不能解决呢？

**Comment by DarienRaymond** [comment]
嗯，就是这样设计的。你可以理解成 streamSettings 是机器到机器的，一旦流量转发到了另一个VPS（比如从另一个outbound出去），那么之前的 streamSettings 就无效了。
