### ISSUE TITLE
关于设置代理后，局域网网站无法访问，baidu.com可以访问，google.com也可以访问过

### ISSUE THREAD

**Issue by mrwenhui** [v2ray/v2ray-core#696]
相关k客户端配置配置如下  ubuntu16.04 桌面版
    "outboundDetour":[
        {
            "tag":"direct",
            "protocol":"freedom",
            "settings":{
                "domainStrategy":"AsIs"
            }
        },
        {
            "tag":"blockout",
            "protocol":"blackhole",
            "settings":{
                "response":{
                    "type":"http"
                }
            }
        }
    ],
    "inbound":{
        "streamSettings":null,
        "settings":{
            "ip":"0.0.0.0",
            "udp":true,
            "clients":null,
            "auth":"noauth"
        },
        "protocol":"http",
        "port":1080,
        "listen":"0.0.0.0"
    },
    "inboundDetour":null,
    "routing":{
        "settings":{
            "rules":[
                {
                    "type":"field",
                    "ip":[
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "192.168.50.0/8",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "203.0.113.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10"
                    ],
                    "domain":[
                        "github.com"
                    ],
                    "port":null,
                    "outboundTag":"direct"
                },
                {
                    "type":"chinasites",
                    "outboundTag":"direct"
                },
                {
                    "type":"chinaip",
                    "outboundTag":"direct"
                }
            ],
            "domainStrategy":"IPIfNonMatch"
        },
        "strategy":"rules"
    },
    "dns":{
        "servers":[
            "8.8.8.8",
            "8.8.4.4",
            "localhost"
        ]
    }

如何让局域网网站也可以正常访问？

**Comment by Cwek** [comment]
> "rules":[
> {
> "type":"field",
> "ip":[
> "0.0.0.0/8",
> "10.0.0.0/8",
> "100.64.0.0/10",
> "127.0.0.0/8",
> "169.254.0.0/16",
> "172.16.0.0/12",
> "192.0.0.0/24",
> "192.0.2.0/24",
> "192.168.0.0/16",
> "192.168.50.0/8",
> "198.18.0.0/15",
> "198.51.100.0/24",
> "203.0.113.0/24",
> "::1/128",
> "fc00::/7",
> "fe80::/10"
> ],
> "domain":[
> "github.com"
> ],
> "port":null,
> "outboundTag":"direct"
> },

我看这里ip和domain是冲突的，将两个分开。

**Comment by DarienRaymond** [comment]
如上。
