### ISSUE TITLE
v2ray.location.asset能不能在配置文件里指定？

### ISSUE THREAD

**Issue by Darren** [v2ray/v2ray-core#702]
现在master的改动，把geoip.dat  geosite.dat放在单独的文件里了？
如果geoip.dat  geosite.dat文件和可执行文件没有放在一起就需要指定v2ray.location.asset
但是bash又不支持带dot的变量名，而且systemd的Environment也不支持。
需要用env来启动， 比如 #455。

所以能不能不用环境变量而使用配置文件？

**Comment by DarienRaymond** [comment]
下一版本将允许 v2ray_location_asset 的形式。
