### ISSUE TITLE
所有网站都走代理了(服务器有流量统计)，客户端配置有问题吗

### ISSUE THREAD

**Issue by wjx0912** [v2ray/v2ray-core#706]
> 
{
	"inbound": {
		"listen": "0.0.0.0",
		"port": 1080,
		"protocol": "http",
		"settings": {
			"timeout": 0
		}
	},

	"inboundDetour": [
	{
		"listen": "0.0.0.0",
		"port": 1079,
		"protocol": "socks",
		"settings": {
			"auth": "noauth"
		}
	}
	],

	"outbound": {
		"protocol": "freedom",
		"settings": {}
	},

	"outboundDetour": [
	{
		"protocol": "vmess",
		"tag": "proxy_please",
		"settings": {
			"vnext": [
			{
				"address": "45.63.95.173",
				"port": 55667,
				"users": [
				{
					"id": "19c357bf-015b-4f23-b625-6fa64397e6e0",
					"alterId": 64
				}
				]
			}
			]
		},
		"streamSettings":{
			"network":"kcp",
			"kcpSettings": {
				"mtu": 1350,
				"tti": 20,
				"uplinkCapacity": 1000,
				"downlinkCapacity": 1000,
				"congestion": false,
				"readBufferSize": 1,
				"writeBufferSize": 1,
				"header": {
					"type": "none"
				}
			}
		}
	}
	],

	"routing": {
		"strategy": "rules",
		"settings": {
			"rules": [
			{
				"type": "field",
				"domain": [
				".google",
				"4tern.com",
				"ime.baidu.jp"
				],
				"outboundTag": "proxy_please"
			},
			{
				"type": "field",
				"ip": [
					"91.108.4.0/22",
					"109.239.140.0/24"
				],
				"outboundTag": "proxy_please"
			}
			]
		}
	}
}

**Comment by wansen** [comment]
按你的配置应该是默认走freedom，没问题的，是否配置贴的不全？或者不该走代理的域名配置到routing里（可以关键字匹配）？还有你用的什么客户端？

**Comment by wansen** [comment]
还有你的配置泄露了你的信息，注意隐私

**Comment by wjx0912** [comment]
找到问题了。是rules里面，有些网址可能有*之类的规则匹配问题。

这是从shadowsocks里面pac找过来的，总共有7000行左右。我再逐行检查下。

万分感谢~~~

**Comment by wjx0912** [comment]
再请教下，有没有一个官方的rules文件？

**Comment by DarienRaymond** [comment]
V2Ray暂时不考虑内嵌支持gfwlist，因为它是GPL的。
