### ISSUE TITLE
linksys wrt 1900acs 路由器，CPU mvebu	TARGET  generic  ,请问v2ray能否支持,需要自己编译吗？

### ISSUE THREAD

**Issue by dcliubing** [v2ray/v2ray-core#709]
```
linksys wrt 1900acs 路由器，CPU mvebu	TARGET  generic  ,下载哪种v2ray,谢谢 。
还是需要编译呢，麻烦详细讲一下。

**Comment by DarienRaymond** [comment]
从 [spec](https://www.linksys.com/gb/p/P-WRT1900ACS/) 看是 ARM 的，可以试一下 ARM 或者 ARM64 的安装包。

**Comment by dcliubing** [comment]
谢谢

**Comment by q158073378252010** [comment]
成功运行？能说说如何做到的?

**Comment by dcliubing** [comment]
安装本地的 vx.xx 版本：./go.sh --version vx.xx --local /path/to/v2ray.zip

/usr/bin/v2ray/v2ray --config /etc/v2ray/config.json @q158073378252010
