### ISSUE TITLE
反对增加额外的程序解析json

### ISSUE THREAD

**Issue by Remonli** [v2ray/v2ray-core#711]
完全是脱裤子放屁的事情. 

如无必要,勿增实体.

看不出任何好处,反而之前所有部署好的服务器全部都要修改脚本.

golang最大优点就是不用各种依赖,下载二进制直接执行.

读取配置文件一个可执行程序最基本的功能,为什么要拆出来?

**Comment by DarienRaymond** [comment]
我每周提交至少100行代码改动，凭什么你就能一劳永逸。

**Comment by Remonli** [comment]
1. 你如果说我是作者我最大爱用用不用滚,自然没问题.
2. 如果要讲道理的话,仅就这个改动而言,你能说说有什么优点吗?缺点我已经说了,一堆用户脚本需要修改,
   优点>缺点自然没问题, 若反之,为什么干这种多余的事情?

**Comment by ToutyRater** [comment]
1.  这样的改动其中一个原因是为了更好地维护代码
2. V（v2ray） 是一个模块化的代理软件包，它的目标是提供常用的代理软件模块，简化网络代理软件的开发。自身定位本就如此
3. v2ray-core 使用的配置格式是 protobuf，将json解析器独立很正常
4. `golang最大优点就是不用各种依赖,下载二进制直接执行`，直接执行就好了，还要什么脚本嘛
5. 用脚本也是可以的，就多copy一个v2ctl，这比苦逼的debug轻松多了
6. v2ray 是一个开源项目，你也可以自行开一个不拆分解析器的分支嘛，比如叫v2ray-rss，免去了那么多用户脚本需要修改

**Comment by Sherman-Liu** [comment]
又没人用刀架着你脖子，不爱用就滚呗，语气像个大爷一样，人家开发者欠你的?

**Comment by ctmakro** [comment]
我今天升级V2Ray，也是被这个设计囧到了。
大多数用户直接写protobuf是有困难的，都得走json。对这些用户来说，v2ctl和v2ray基本上没有分开用的情景，现在搞成两个独立的binary，确实让大家云里雾里的。

一个可能的解释：作者想搞v2ray farm，一次管理十万个帐号，用json太慢。
