### ISSUE TITLE
ID和时间都对，但是log提示invalid user

### ISSUE THREAD

**Issue by ndmouse** [v2ray/v2ray-core#717]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    v2ray 2.50,服务器和客户端都是。
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    客户端firefox,服务器端阿里云香港区ubuntu16.04 64位。

3)  你看到的不正常的现象是什么？
  打不开google
4)  你期待看到的正确表现是怎样的？
    正常连接

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
   
    Server Configuration File（服务器端配置文件）:
{
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "debug"
  },
  "inbound": {
    "port": 443,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "533e80fd-fc90-4dd9-86fd-3b60bb9943b8",
          "level": 1,
          "alterId": 64
        }
      ]
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}
   

    Client Configuration File（客户端配置文件）:
{
  "log": {
    "access": "D:\\v2ray-v2.50-windows-64\\access.log",
    "error": "D:\\v2ray-v2.50-windows-64\\error.log",
    "loglevel": "debug"
  },
  "inbound": {
    "port": 1080,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "XX.XX.XX.xx",
          "port": 443,
          "users": [
            {
              "id": "533e80fd-fc90-4dd9-86fd-3b60bb9943b8",
              "alterId": 64,
              "security": "auto"
            }
          ]
        }
      ]
    },
    "mux": {
      "enabled": true
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "tlsSettings": {
        "serverName": "v2ray.cool",
        "allowInsecure": true
      },
      "wsSettings": {
        "path": "/v2ray.cool/"
      }
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": "1-52",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "54-79",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "81-442",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "444-65535",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "domain": ["geosite:cn"],
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10",
            "geoip:cn"
          ],
          "outboundTag": "direct"
        }
      ]
    }
  }
}

6)  请附上出错时软件输出的日志。
    Server Log File（服务器端日志）:
服务端DEBUG级LOG
2017/11/19 19:29:22 [Info]Proxy|VMess|Inbound: invalid request from 183.185.191.25:56190: Proxy|VMess|Encoding: invalid user
2017/11/19 19:29:22 [Info]App|Proxyman|Inbound: connection ends > Proxy|VMess|Encoding: invalid user
```

    Client Log File（客户端日志）:
先放个客户端debug级log
2017/11/19 19:29:21 [Debug]App|DNS|Server: add pending request id 19745
2017/11/19 19:29:21 [Debug]Transport|Internet|UDP: dispatch request to: udp:8.8.8.8:53
2017/11/19 19:29:21 [Info]Transport|Internet|UDP: establishing new connection for udp:8.8.8.8:53
2017/11/19 19:29:21 [Info]App|Dispatcher|Default: default route for udp:8.8.8.8:53
2017/11/19 19:29:21 [Info]App|Proxyman|Mux: dispatching request to udp:8.8.8.8:53
2017/11/19 19:29:21 [Info]Transport|Internet|WebSocket: creating connection to tcp:XX.XX.XX.xx:443
2017/11/19 19:29:21 [Info]Transport|Internet|WebSocket: creating connection to tcp:XX.XX.XX.xx:443
2017/11/19 19:29:21 [Info]Transport|Internet|WebSocket: creating connection to tcp:XX.XX.XX.xx:443
2017/11/19 19:29:22 [Info]Transport|Internet|WebSocket: creating connection to tcp:XX.XX.XX.xx:443
2017/11/19 19:29:22 [Debug]Transport|Internet|UDP: dispatch request to: udp:8.8.8.8:53
2017/11/19 19:29:22 [Info]Transport|Internet|WebSocket: creating connection to tcp:XX.XX.XX.xx:443
2017/11/19 19:29:23 [Debug]Transport|Internet|UDP: dispatch request to: udp:8.8.8.8:53
2017/11/19 19:29:23 [Info]Transport|Internet|UDP: failed to handl UDP input > EOF
2017/11/19 19:29:23 [Warning]failed to handler mux client connection > Proxy|VMess|Outbound: failed to find an available destination > Retry: [Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://XX.XX.XX.xx/nonexistingpath1024/):  > EOF] > Retry: all retry attempts failed

**Comment by DarienRaymond** [comment]
把客户端streamSettings整体删除即可
