### ISSUE TITLE
V2ray on wrt1900 acs v2

### ISSUE THREAD

**Issue by kskim74** [v2ray/v2ray-core#718]
hi,
Which file do i have to use for router wrt1900 acs v2?
And also how can i install it on a router?

**Comment by DarienRaymond** [comment]
Should be ARM.

You may run V2Ray on a router if you have SSH access to it, just like you run it on a Linux console. However, I don't know whether there is an integration with existing router system (xx-WRT).

**Comment by kskim74** [comment]
Thanks for your reply.
Then which router system is recommended?
Sorry to ask many beginner questions, i’m a beginner with no idea about programming.
Only follow tutorials found on google.  That’s how i’m using shadowsocks at the moment.

**Comment by DarienRaymond** [comment]
I have no idea about the router system. You may search on Google to see if someone has experience on that.
