### ISSUE TITLE
Error an existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by ntgeralt** [v2ray/v2ray-core#72]
在vps 64x ubuntu 14.04  的ssh输入
bash <(curl -L -s https://raw.githubusercontent.com/v2ray/v2ray-core/master/release/install-release.sh)

然后service v2ray start

客户端v2ray-v1.5-windows-32用你默认的公共服务器能连上google，关闭v2ray.exe，修改config， uuid、ip和端口为我vps v2ray/config信息，重新打开v2ray.exe，无法上google，出现Error an existing connection was forcibly closed by the remote host。vps防火墙已打开端口，vps上面建立的ss服务端正常工作。在这里求助下是什么问题。

**Comment by Sherman-Liu** [comment]
是的，我也遇到了一模一样的情况，完全摸不到头绪，服务器端的错误日记里只写了是Invalid authentication。

**Comment by yxxyun** [comment]
删掉  "alterId": 1024 试试

**Comment by v2ray** [comment]
请确定配置文件中 VMess 的 id 和 alterId 这两个值，在客户端和服务器端是一样的。详见：https://github.com/v2ray/v2ray.github.io/wiki/%E5%8D%8F%E8%AE%AE%E5%88%97%E8%A1%A8#vmess-inbound--outbound

**Comment by yxxyun** [comment]
默认的server的配置中没有设置alterId，而客户端默认配置里有。

**Comment by v2ray** [comment]
现在(v1.6)配置文件已更新，alterId 和 id 都一致了。

**Comment by v2ray** [comment]
Assume fixed.
