### ISSUE TITLE
任意门问题

### ISSUE THREAD

**Issue by dcliubing** [v2ray/v2ray-core#721]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
v2.50
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
 Socks/VMess 代理观看 YouTube 视频
3)  你看到的不正常的现象是什么？
    What did you see?
任意门协议不能FQ  ，SOCKS协议可以，没有自己写iptables,路由器上端口转发到  任意门端口，以前成功过，
4)  你期待看到的正确表现是怎样的？
    What's your expectation?

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Server Configuration File（服务器端配置文件）:
```javascript
    // 在这里附上服务器端配置文件
          {
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "info"
  },
  "inbound": {
    "port": 1xxx6,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "7axxxxxxxxxx29",
          "level": 1,
          "alterId": 64
        }
      ]
    },
    "mux": {
      "enabled": false
    }
  },



  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  },
  "transport": {
    "kcpSettings": {
      "uplinkCapacity": 2,
      "downlinkCapacity": 10
    }
  }
}
    // Please attach your server configuration file here.
```

    Client Configuration File（客户端配置文件）:
```javascript
    // 在这里附上客户端配置文件
    // Please attach your client configuration file here.
```

6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.

    Server Log File（服务器端日志）:
```
    // 在这里附上服务器端日志
    // Please attach your server log here.
```
               
    Client Log File（客户端日志）:
```
    // 在这里附上客户端日志
              {
  "log" : {
    
    "loglevel": "warning"
  },
  "inbound": {
    "port": 20080,
    "listen": "0.0.0.0",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "0.0.0.0"
    }
  },
"inboundDetour": [

        {
                "protocol": "dokodemo-door",
                "port": 20082,
                "settings": {
                        "network": "tcp,udp",
                        "timeout": 0,
                        "followRedirect": true
                }
        }
        ],
       {
 "protocol": "dokodemo-door",
 "port": 5321,
"listen": "0.0.0.0",
 "settings": {
   "address": "8.8.4.4",
   "port": 53,
   "network": "udp",
  "timeout": 0
  }
},

  "outbound": {
    "protocol": "vmess",
    "settings": {
   "vnext": [
        {
          "address": "xxxxxxxxxxxxx",
          "port": xxx,
          "users": [
            {
              "id": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
              "alterId": 64,
              "security": "auto"
            }
          ]
        }
      ]

  },
"mux": {
      "enabled": false
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}
    // Please attach your client log here.
```

**Comment by dcliubing** [comment]
2017/11/22 06:43:54 [Info]App|Dispatcher|Default: default route for tcp:173.252.100.32:443
2017/11/22 06:43:54 [Info]Transport|Internet|TCP: dailing TCP to tcp:xxxxxxxx:10086
2017/11/22 06:43:54 [Info]App|Dispatcher|Default: default route for tcp:173.252.100.32:443
2017/11/22 06:43:54 [Info]Transport|Internet|TCP: dailing TCP to tcp:xxxxxxxx:10086
2017/11/22 06:43:55 [Info]Proxy|VMess|Outbound: tunneling request to tcp:173.252.100.32:443 via tcp:xxxxxxxx:10086
2017/11/22 06:43:55 [Info]App|Dispatcher|Default: default route for tcp:173.252.100.32:443
2017/11/22 06:43:55 [Info]Transport|Internet|TCP: dailing TCP to tcp:xxxxxxxx:10086
2017/11/22 06:43:55 [Info]Proxy|VMess|Outbound: tunneling request to tcp:173.252.100.32:443 via tcp:xxxxxxxx:10086
2017/11/22 06:43:55 [Info]Proxy|VMess|Outbound: tunneling request to tcp:173.252.100.32:443 via tcp:xxxxxxxx:10086
2017/11/22 06:43:55 [Info]App|Dispatcher|Default: default route for tcp:173.252.100.32:443
2017/11/22 06:43:55 [Info]Transport|Internet|TCP: dailing TCP to tcp:xxxxxxxx:10086
2017/11/22 06:43:55 [Info]Proxy|VMess|Outbound: tunneling request to tcp:173.252.100.32:443 via tcp:xxxxxxxx:10086
2017/11/22 06:43:57 [Info]App|Dispatcher|Default: default route for tcp:74.125.204.101:443
2017/11/22 06:43:57 [Info]Transport|Internet|TCP: dailing TCP to tcp:xxxxxxxx:10086
2017/11/22 06:43:57 [Info]Proxy|VMess|Outbound: tunneling request to tcp:74.125.204.101:443 via tcp:xxxxxxxx:10086
2017/11/22 06:43:58 [Info]App|Dispatcher|Default: taking detour [blocked] for [tcp:192.168.1.28:22]
2017/11/22 06:43:58 [Info]Proxy|Freedom: opening connection to tcp:192.168.1.28:22
2017/11/22 06:43:58 [Info]Transport|Internet|TCP: dailing TCP to tcp:192.168.1.28:22
2017/11/22 06:44:11 [Info]App|Dispatcher|Default: default route for tcp:183.36.108.223:443
2017/11/22 06:44:11 [Info]Transport|Internet|TCP: dailing TCP to tcp:xxxxxxxx:10086
2017/11/22 06:44:12 [Info]Proxy|VMess|Outbound: tunneling request to tcp:183.36.108.223:443 via tcp:xxxxxxxx:10086
2017/11/22 06:44:14 [Info]App|Dispatcher|Default: default route for udp:8.8.4.4:53
2017/11/22 06:44:14 [Info]Transport|Internet|TCP: dailing TCP to tcp:xxxxxxxx:10086

**Comment by dcliubing** [comment]
是因为dns污染吗

**Comment by DarienRaymond** [comment]
不建议这么做，但是你可以在dokodemo-door 上面开启[domain override](https://www.v2ray.com/chapter_02/01_overview.html#主传入连接配置（inbound）).
