### ISSUE TITLE
geosite:cn配置导致无法使用google play市场

### ISSUE THREAD

**Issue by kz-wind** [v2ray/v2ray-core#722]
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/zh_cn/chapter_01/issue.html)，然后回答下面的问题，谢谢。
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
    What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
服务器v2ray2.50   客户端为android 7.0  v2rayNG 0.2.3  v2ray2.47

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
    What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
在google play上下载应用，google play为手机内置（国行）。国内版市场会连接services.googleapis.cn这个域名，香港vps使用8.8.8.8会解析到203开头的国内IP，已经在服务器内写上hosts强制正确解析。最近在服务器上在加入         
 "domain": [
            "geosite:cn"
           ],
会导致无法正常使用google play，且这一现象只在香港vps上出现。去除domain选项后，恢复正常

3)  你看到的不正常的现象是什么？
    What did you see?
市场报错DF-DEREH-01  
4)  你期待看到的正确表现是怎样的？
    What's your expectation?

5)  请附上你的配置文件（提交 Issue 前请隐藏服务器端IP地址）。
    Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Server Configuration File（服务器端配置文件）:
```javascript
    // 在这里附上服务器端配置文件
    // Please attach your server configuration file here.
```
 "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
//          "domain": [
//            "geosite:cn"
//           ],
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10",
            "geoip:cn"
          ],
          "outboundTag": "blocked"
        }
      ]

    Client Configuration File（客户端配置文件）:
```javascript
    // 在这里附上客户端配置文件
    // Please attach your client configuration file here.
```

6)  请附上出错时软件输出的日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
    Please attach the log file, especially the bottom lines if the file is large. Log file is usually `/var/log/v2ray/error.log` on Linux.

    Server Log File（服务器端日志）:
```
    // 在这里附上服务器端日志
    // Please attach your server log here.
```

    Client Log File（客户端日志）:
```
    // 在这里附上客户端日志
    // Please attach your client log here.
```

**Comment by DarienRaymond** [comment]
看上去原因是 Google 把 services.googleapis.cn 这个域名解析到了国外的 IP 地址，而 geosite:cn 里把所有的 .cn 域名都当成了国内域名。你在 geosite:cn 的规则之前，加一个 services.googleapis.cn 的规则解析到直连(VPS)或者代理（本机）即可。

**Comment by kz-wind** [comment]
"routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "domain": [
            "googleapis.cn"
           ],
        "outboundTag": "direct"
        },
        {
          "type": "field",
          "domain": [
            "geosite:cn"
           ],
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10",
            "geoip:cn"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  },
改成这样后确实可以了，然而我有一个疑问，第一次改成这样后，保存重启了服务端，开启手机客户端连接，打开谷歌市场还是无法访问；之后我把geosite:cn注释掉，重启服务端，手机可以访问谷歌市场；然后现在再去掉注释，重启服务端，继续可以访问谷歌市场。所以我想问一下，当中是否有缓存等之类的问题，导致第一次修改不成功？

**Comment by kz-wind** [comment]
今天早上问题又复现了，服务器的配置没有更改，客户端是我的手机，使用的是v2rayNG手动输入的配置，发现使用香港的服务器登录谷歌还是会出现报错现象

**Comment by kz-wind** [comment]
{
"type": "field",
"domain": [
"googleapis.cn"
],
"outboundTag": "direct"
},
{
"type": "field",
"domain": [
"geosite:cn"
],
在服务器端只要加了geosite:cn后发现，无论手机端如何修改，google play市场就是会报错

**Comment by DarienRaymond** [comment]
有可能是 play store 还用了其它的 .cn 域名？

**Comment by 2dust** [comment]
请升级v2rayNG版本到0.3.0试一试

**Comment by kz-wind** [comment]
升级到0.30后，再将这段
{
"type": "field",
"domain": [
"googleapis.cn"
],
"outboundTag": "direct"
},
加入后，确实好像就正常了，怀疑之前可能内核没升级的原因

**Comment by kz-wind** [comment]
今天又测试了一下，发现还需要将google.cn加入域名代理才可以访问

**Comment by DarienRaymond** [comment]
Consider fixed.

**Comment by chancat87** [comment]
在代理google之前加一个规则。。
geosite:google-cn 直连
