### ISSUE TITLE
高并发性能问题

### ISSUE THREAD

**Issue by Blankwonder** [v2ray/v2ray-core#726]
之前在本地测试 v2ray 时注意到有可观察到的性能问题，于是进行了可量化的性能测试。

测试环境：
硬件：Mac Pro (Late 2013) 3.5 GHz 6-Core Intel Xeon E5
版本号：v2ray-v2.47
测试网络环境：1000M LAN

测试方法：在同一设备上同时运行 v2ray 的 server 和 client，使用 apachbench(ab) 访问 LAN 中另一服务器上的 nginx 欢迎页。由于 ab 不支持 SOCKS5 代理，使用 proxychains4 进行强制代理。

测试命令 proxychains4 ./ab -n 10000 -c 100 http://192.168.20.6/

测试结果：

不使用代理直接测试：4.563 seconds
使用 v2ray：200.528 seconds
使用 ss-libev：39.897 seconds
使用 Surge：19.953 seconds （由于 Surge 仅进行了一次转发，v2ray 和 ss-libev 多了一次额外的转发和加密，所以该数据仅供参考不可用于直接对比）

   Server Configuration File（服务器端配置文件）:
```javascript
{
  "log": {
    "loglevel": "warning"
  },
  "inbound": {
    "port": 10086,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "CAA0F9FB-87AC-454D-B66E-D6ACD439835A",
          "alterId": 64
        }
      ]
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "dns": {
    "servers": [
      "223.5.5.5"
    ]
  }
}
```

    Client Configuration File（客户端配置文件）:

```javascript
{
  "log": {
    "loglevel": "warning"
  },
  "inbound": {
    "port": 1080,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "127.0.0.1",
          "port": 10086,
          "users": [
            {
              "id": "CAA0F9FB-87AC-454D-B66E-D6ACD439835A",
              "alterId": 64,
              "security": "aes-128-gcm"
            }
          ]
        }
      ]
    }
  },
  "dns": {
    "servers": [
      "223.5.5.5"
    ]
  }
}

```

**Comment by DarienRaymond** [comment]
简单的解释是 200 秒 = 100 次连接 * 2 秒超时。100 次连接 = 10000 次请求 / 100 并发

具体的原因是：
1. socks 没有收到 proxychains（或 ab）的关闭连接信号（至少是 close write 信号）；
1. socks 已经读完来自上游 nginx 的数据，并且 nginx 关闭了连接（从 V2Ray 的角度来说只知道是 close write 信号，不能明确知道是不是整个连接关闭）；
1. 此时 socks 会等待 2 秒钟，如果没有更多的来自 proxychains 的数据，则主动关闭连接；

这么做的原因是：
1. 不能排除特殊情况下，某些应用程序在 downlink 关闭的时候继续使用 uplink 发送数据；
1. V2Ray 不会主动发送 close write 信号，因为有一些实现不正确的程序会把 close write 当成 close 来处理；
1. 只有在得到明确信号的情况下（比如 http 代理的 connection close），V2Ray 才会在单边关闭的时候，关闭整个连接。你用 http 代理 + ab 试一下即可得到有效的数据。

**Comment by Blankwonder** [comment]
如果是 half-close 的情况，那么 v2ray-server 在该 socket 收到来自 nginx 的 close 之后，应该向 v2ray-client 的 socket 进行单向 close (POSIX shutdown)，然后 v2ray-client 向 ab 发单向 close。这样 ab 会立刻进行 close，连接得到正常关闭。

**Comment by Blankwonder** [comment]
这样简单进行 2 秒超时的逻辑会使得一些以 TCP close 为结束信号的协议表现不正常，如 HTTP 1.0。

**Comment by DarienRaymond** [comment]
上面解释了，实践中发现有一些奇怪的程序（或者防火墙）不能正确响应 close write，所以 V2Ray 的所有 inbound/outbound 都没有使用这一机制。

**Comment by DarienRaymond** [comment]
> 这样简单进行 2 秒超时的逻辑会使得一些以 TCP close 为结束信号的协议表现不正常，如 HTTP 1.0。

这是代理的问题，socks 不知道其传输的数据是什么类型的，于是就不能根据具体的协议来做不同处理。http 代理不会有这个问题。

**Comment by hshh** [comment]
试试加上 -k 开启 keep alive

**Comment by leewi9** [comment]
我也感觉这里的处理略显简单了，应该有更加perfect的处理方式

**Comment by DarienRaymond** [comment]
会在之后的版本中加入超时的配置项。
