### ISSUE TITLE
Failed to upload file using WebSocket behind Nginx

### ISSUE THREAD

**Issue by S-Tsunemori** [v2ray/v2ray-core#730]
I'm using vmess websocket on port 443 (behind nginx, over tls):

V2Ray (client) config:
```json
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "[* my websocket path *]"
        },
        "security": "tls",
        "tlsSettings": {
          "serverName": "[* my domain name *]",
          "allowInsecure": false
        }
      }
```
nginx config:
```nginx
        location /[* my websocket path *]/ {
                proxy_pass http://127.0.0.1:[* V2ray Listen Port *];
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_read_timeout 86400;
                client_max_body_size 200M;
        }
```

The proxy works (I can visit any sites, watch YouTube videos...) but when trying to upload a file (like attach file to GitHub) it uploads real quick (process bar full fills) then stuck at the end of uploading process, never finishes, fails eventually.

However if I try a smaller file (~10KB) it would upload successfully. The file doesn't need to be too large for it to fail, ~1MB will do. Using other "network" config (like "kcp") on the same server doesn't have this problem.

**Comment by S-Tsunemori** [comment]
Turns out the problem is caused by nginx.

I had
```nginx
client_max_body_size 0;
```
set in ```sever {}``` and ```location {}``` block, which turns out doesn't work (I've no idea why, I'm using ```nginx/v1.10.3 (Ubuntu)```)

Moving it into ```http {}``` block fixed the issue for me.

Still, it would be nice if v2ray can workaround this limitation, at least should update document on websocket.

**Comment by DarienRaymond** [comment]
This is pretty much nginx usage. [The instruction](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size) says `client_max_body_size` can be set on location. The default value is 1M, and there is no way for V2Ray to get over it. If you think this is a bug in Nginx. Please contact its support.
