### ISSUE TITLE
V2ray使用Shadowsocks协议，会同SS一样容易被墙识别么？

### ISSUE THREAD

**Issue by d4rkblue** [v2ray/v2ray-core#734]
你好，请问一下如果V2ray开启Shadowsocks协议，客户端使用SS的，代理过程容易被墙识别么？如果支持SSR会不会好一些？谢谢答复。

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/chapter_01/issue.html)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题，缺少信息将减慢Issue回复速度。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
假设使用最新版 V2Ray
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
通过代理浏览网页或观看youtube
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

4)  你期待看到的正确表现是怎样的？

5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
```javascript
    // 在这里附上服务器端配置文件
```

    客户端配置:
```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
```
    // 在这里附上服务器端日志
```

    客户端错误日志:
```
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
```
    // 在这里附上服务器端日志
```

请预览一下你填的内容再提交。

如果你已经填完上面的问卷，请把下面的英文部份删除，再提交 Issue。

**Comment by daiaji** [comment]
特征和SS一样 当然会被识别啦

**Comment by DarienRaymond** [comment]
从协议层面来说，V2Ray的ss和原版ss没有差别。
