### ISSUE TITLE
unable to read deadline

### ISSUE THREAD

**Issue by offferu** [v2ray/v2ray-core#744]
Please skip to the English section below if you don't write Chinese.

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/chapter_01/issue.html)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题，缺少信息将减慢Issue回复速度。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v2.51
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
vmess + mKCP + 动态端口
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
服务端 error.log 出现大量如下错误
Inbound: connection ends > Proxy|VMess|Inbound: unable to set read deadline > Transport|Internet|mKCP: Connection closed.
4)  你期待看到的正确表现是怎样的？

5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
```javascript
    // 在这里附上服务器端配置文件
```

    客户端配置:
```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
```
    // 在这里附上服务器端日志
```

    客户端错误日志:
```
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
```
    // 在这里附上服务器端日志
```

**Comment by DarienRaymond** [comment]
这个错误是因为mKCP的特性导致的，不影响使用，之后的版本中会修正对错误信息的输出。

**Comment by offferu** [comment]
非常感谢！

**Comment by chalau** [comment]
同样unable to set read deadline：但服务器会立即断开，请指点迷津，谢谢
