### ISSUE TITLE
能否给官方文档透明代理部分补充完整配置？

### ISSUE THREAD

**Issue by xiatiansong** [v2ray/v2ray-core#745]
尝试在用一台centos做透明代理网关，其他电脑设置透明代理机器为网关，但按照官方配置一直不成功。
    能否在官方文档透明代理部分，给一个最简单的完整的客户端和服务端配置，并配合iptables，基本按照最简单配置能跑起来，提问问这块的问题也会少一些。

**Comment by DarienRaymond** [comment]
透明代理或多或少是 Linux（或其它工具比如 iptables）的功能，请参考相关的文档进行配置。

如果你认为 V2Ray 在处理透明代理的过程中有 bug，请按照 issue 模板发详细的信息。
