### ISSUE TITLE
能否详细介绍一下使用apache转发v2ray的websocket (apache+websocket+tls)

### ISSUE THREAD

**Issue by mzxwt** [v2ray/v2ray-core#747]
大神们好！小弟自己租了一台vps用于学习国外先进技术，同时用apache自建了webdav用于zotero同步学习资料。近来发现学校开始封锁udp，可能是用迅雷太多闹的，mkcp残废，想用apache+websocket+tls，无奈不是计算机专业，有心无力，真心希望诸神不吝赐教，写个教程，惠泽吾等小白！

**Comment by Dakai** [comment]
https://toutyrater.github.io/advanced/wss_and_web.html
https://www.ivyseeds.cf/websocket/
按照这两篇文章可以安装好，昨晚亲测

**Comment by mzxwt** [comment]
不好意思问一下 你有apache的配置文件吗 能分享一下吗 谢谢

**Comment by Dakai** [comment]
抱歉，都是按照教程在nginx上配置的，apache怎么配置不懂。

**Comment by DarienRaymond** [comment]
http://lmgtfy.com/?q=apache+websocket+proxy

**Comment by CharnleyJ** [comment]
我也需要一个apache的，找到的都是nginx的，虽然nginx用的挺好的

**Comment by Dakai** [comment]
@mzxwt @PangciPG 我写了个教程，亲测可用：https://dakai.github.io/2017/12/22/v2ray-websocket-tls-apache.html

**Comment by lostanother** [comment]
@Dakai 你好，我跟着你的教程顺利完成了v2ray的转发，不过原来网站却无法用https连接访问了。
我原来的配置是

    <VirtualHost *:443>
                ServerAdmin  webmaster@localhost
                DocumentRoot /var/www/hexo
                ErrorLog ${APACHE_LOG_DIR}/error.log
                CustomLog ${APACHE_LOG_DIR}/access.log combined
                SSLEngine on
                SSLCertificateFile      /etc/v2ray/v2ray.crt;
                SSLCertificateKeyFile  /etc/v2ray/v2ray.key;
    </VirtualHost>

请问有什么办法可以同时用https访问网站并转发v2ray流量到3579端口吗？谢谢

**Comment by Dakai** [comment]
@lostanother 你好，教程可能有些误导，你是否把主域名用来转发v2ray流量了？我是用的一个子域名来转发的，主域名不受影响，具体来说：
etc/apache/sites-available或/etc/httpd/sites-available目录下有两个conf文件，
一个是主域名yourdomain.com.conf，另一个是用来转发V2ray流量的subdomain.yourdomain.com.conf，V2ray配置在后者子域名文件里面，配置如下供参考：


        <VirtualHost *:443>

        ServerName subdomain.yourdomain.com
        ServerAlias subdomain.yourdomain.com
        ##SSL Engine Switch:
        #Enable/Disable SSL for this virtual host.
        SSLEngine On

        RewriteEngine On
        RewriteCond %{HTTP:Upgrade} =websocket [NC]
        RewriteRule /(.*)           ws://localhost:3579/$1 [P,L]
        RewriteCond %{HTTP:Upgrade} !=websocket [NC]
        RewriteRule /(.*)           http://localhost:3579/$1 [P,L]

        ##Proxy to port 3579
        SSLProxyEngine On
        Proxypass /ray http://127.0.0.1:3579
        ProxyPassReverse /ray http://127.0.0.1:3579
        SSLCertificateFile /etc/v2ray/v2ray.crt
        SSLCertificateKeyFile /etc/v2ray/v2ray.key

        </VirtualHost>



设置好后要在DNS管理里把子域名加进去。

**Comment by Hardrain980** [comment]
@lostanother @Dakai 
```
<LocationMatch "/{ws_path}}/">
	ProxyPass ws://127.0.0.1:{port}/{ws_path}/ upgrade=WebSocket
	ProxyAddHeaders Off
	ProxyPreserveHost On
	RequestHeader set Host %{HTTP_HOST}s
	RequestHeader set X-Forwarded-For %{REMOTE_ADDR}s
</LocationMatch>
```
加到`<VirtualHost></VirtualHost>`之间

**Comment by Hardrain980** [comment]
忘了说
需要
- mod_ssl
- mod_proxy
- mod_proxy_wstunnel

**Comment by TingoLee** [comment]
@Hardrain980 添加之后apache2在这行报错ProxyPass ws://127.0.0.1:{port}/{ws_path}/ upgrade=WebSocket

**Comment by PyzmxU** [comment]
> 
> 
> @mzxwt @PangciPG 我写了个教程，亲测可用：https://dakai.github.io/2017/12/22/v2ray-websocket-tls-apache.html

官方教程不行，你的可行NB

**Comment by 1512917705** [comment]
@Dakai
Apache配置中的
RewriteCond %{HTTP:Upgrade} !=websocket [NC]
RewriteRule /(.*) http://localhost:3579/$1 [P,L]
中第二行，这块是非websocket请求，应该换成本地域名，而不是继续转3579端口吧？

**Comment by Dakai** [comment]
> @Dakai
> Apache 配置中的
> RewriteCond %{HTTP:Upgrade} !=websocket [NC]
> RewriteRule /(.*) http://localhost:3579/$1 [P,L]
> 中第二行，这块是非 websocket 请求，应该换成本地域名，而不是继续转 3579 端口吧？

好像是的，你可以试试去掉第二段看看是否还能用？
我已经用回nginx了，没法试验了
