### ISSUE TITLE
动态端口切换是否考虑非周期性

### ISSUE THREAD

**Issue by pminmax945** [v2ray/v2ray-core#75]
最近一篇文章提到gfw可能使用机器学习识别出了包含在
加密隧道中的tls握手（推测识别出了包长度的模式）
http://blog.zorinaq.com/?e=81
那么非周期性的切换是否更难于识别呢？

**Comment by kxjhlele** [comment]
现在就是随机切换的吧 要是能和ftp的被动模式就好了，

**Comment by v2ray** [comment]
@pminmax945 那篇文章并没有提到周期性的问题吧，machine learning 能不能检测到周期性还有待考证。做出非周期性并不复杂，但很难做到完全找不出规律。

@kxjhlele 什么被动模式？

**Comment by kxjhlele** [comment]
http://my.oschina.net/binny/blog/17469 中的被动模式，我刚才又看了一下，现在好像就是这种模式吧，

**Comment by pminmax945** [comment]
@v2ray 是这样的，仅供参考

**Comment by v2ray** [comment]
@kxjhlele 是的

**Comment by wenjinlibug** [comment]
突然有个想法，是否可以用公钥来作为端口的算法？根据公钥不同端口变化的规律和时间也不同。只有同时拥有公钥的服务器和客户端才可以通过算法算出什么时候换什么端口，这样就可以省掉通知客户端换端口的通讯，同时又能做到近似随机周期。
