### ISSUE TITLE
v3.0 ss client unknown cipher method: aes-128-gcm

### ISSUE THREAD

**Issue by hweidz** [v2ray/v2ray-core#753]
Please skip to the English section below if you don't write Chinese.

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/chapter_01/issue.html)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题，缺少信息将减慢Issue回复速度。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v3.0 windows x64

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
当ss client连到 ss-libev 3.1.1

3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
unknown cipher method: aes-128-gcm

**Comment by DarienRaymond** [comment]
请确认你的v2ctl也升到了最新版

**Comment by hweidz** [comment]
看了下 v2ctl不会打出版本 直接下载release页面的v2ray-v3.0-windows-64解压得到的

**Comment by DarienRaymond** [comment]
配置文件发一下

**Comment by hweidz** [comment]
{
    "inbound": {
        "domainOverride": [
            "http",
            "tls"
        ],
        "listen": "127.0.0.1",
        "port": 1111,
        "protocol": "socks",
        "settings": {
            "auth": "noauth",
            "ip": "127.0.0.1",
            "udp": false
        },
        "tag": "1111"
    },
    "inboundDetour": [
        {
            "domainOverride": [
                "http",
                "tls"
            ],
            "listen": "127.0.0.1",
            "port": 2222,
            "protocol": "socks",
            "settings": {
                "auth": "noauth",
                "ip": "127.0.0.1",
                "udp": true
            },
            "tag": "2222"
        },
        {
            "domainOverride": [
                "http",
                "tls"
            ],
            "listen": "127.0.0.1",
            "port": 3333,
            "protocol": "socks",
            "settings": {
                "auth": "noauth",
                "ip": "127.0.0.1",
                "udp": true
            },
            "tag": "3333"
        }
    ],
    "log": {
        "access": "",
        "error": "",
        "loglevel": "none"
    },
    "outbound": {
        "mux": {
            "concurrency": 4,
            "enabled": true
        },
        "protocol": "vmess",
        "settings": {
            "vnext": [
                {
                    "address": "localhost",
                    "port": 0,
                    "users": [
                        {
                            "alterId": 0,
                            "id": "0",
                            "security": "none"
                        }
                    ]
                }
            ]
        },
        "streamSettings": {
            "network": "ws",
            "security": "tls",
            "tlsSettings": {
                "allowInsecure": false,
                "serverName": "localhost
            },
            "wsSettings": {
                "Path": "\/none",
                "connectionReuse": true
            }
        },
        "tag": "wwww"
    },
    "outboundDetour": [
        {
            "mux": {
                "concurrency": 4,
                "enabled": true
            },
            "protocol": "vmess",
            "settings": {
                "vnext": [
                    {
                        "address": "localhost",
                        "port": 0,
                        "users": [
                            {
                                "alterId": 0,
                                "id": "0",
                                "security": "none"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "kcpSettings": {
                    "congestion": true,
                    "downlinkCapacity": 0,
                    "header": {
                        "type": "none"
                    },
                    "mtu": 0,
                    "readBufferSize": 0,
                    "tti": 0,
                    "uplinkCapacity": 0,
                    "writeBufferSize": 0
                },
                "network": "none"
            },
            "tag": "uuuu"
        },
        {
            "protocol": "shadowsocks",
            "settings": {
                "servers": [
                    {
                        "address": "localhost",
                        "method": "aes-128-gcm",
                        "ota": false,
                        "password": "never knows best",
                        "port": 0
                    }
                ]
            },
            "tag": "ssss"
        },
        {
            "protocol": "freedom",
            "settings": {
                "domainStrategy": "AsIs",
                "timeout": 0
            },
            "tag": "direct"
        }
    ],
    "routing": {
        "settings": {
            "domainStrategy": "IPIfNonMatch",
            "rules": [
                {
                    "domain": [
                        "geosite:cn"
                    ],
                    "ip": [
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "203.0.113.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10",
                        "geoip:cn"
                    ],
                    "outboundTag": "direct",
                    "type": "field"
                },
                {
                    "inboundTag": [
                        "1111"
                    ],
                    "outboundTag": "wwww",
                    "type": "field"
                },
                {
                    "inboundTag": [
                        "2222"
                    ],
                    "outboundTag": "uuuu",
                    "type": "field"
                },
                {
                    "inboundTag": [
                        "3333"
                    ],
                    "outboundTag": "ssss",
                    "type": "field"
                }
            ]
        },
        "strategy": "rules"
    }
}

**Comment by DarienRaymond** [comment]
等会发一个测试版
