### ISSUE TITLE
关于开设TCP动态端口的问题

### ISSUE THREAD

**Issue by bobwang3** [v2ray/v2ray-core#754]
Please skip to the English section below if you don't write Chinese.

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/chapter_01/issue.html)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题，缺少信息将减慢Issue回复速度。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
都是V2.51最新版，前天刚升了级。V2.5的时候也有我下面描述的问题。

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
Chrome 浏览谷歌优土鳖等。v2ray设置的TCP443端口+TLS，动态端口每次在29800~30000范围里随机刷2个，每60分钟刷新一次，也是TCP+TLS。均能正常访问，只是有一些奇怪的日志问题。

3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
v2ray服务器端的error.log会每小时出现2条（完全符合我随机端口的设定）这样的警告记录——
……
2017/12/01 01:27:30 [Warning]Transport|Internet|TCP: failed to accepted raw connections > Retry: [accept tcp [::]:29982: use of closed network connection] > Retry: all retry attempts failed
2017/12/01 01:27:30 [Warning]Transport|Internet|TCP: failed to accepted raw connections > Retry: [accept tcp [::]:29881: use of closed network connection] > Retry: all retry attempts failed
2017/12/01 02:27:30 [Warning]Transport|Internet|TCP: failed to accepted raw connections > Retry: [accept tcp [::]:29979: use of closed network connection] > Retry: all retry attempts failed
2017/12/01 02:27:30 [Warning]Transport|Internet|TCP: failed to accepted raw connections > Retry: [accept tcp [::]:29973: use of closed network connection] > Retry: all retry attempts failed

4)  你期待看到的正确表现是怎样的？
在shell界面执行下方命令看见这样的结果——
root@localhost:~# lsof -i6 |grep v2ray
v2ray   6330 root    6u  IPv6  61399      0t0  TCP *:https (LISTEN)
v2ray   6330 root    9u  IPv6  83111      0t0  TCP *:29973 (LISTEN)
v2ray   6330 root   11u  IPv6  84795      0t0  TCP *:29955 (LISTEN)
v2ray   6330 root   12u  IPv6  84796      0t0  TCP *:29884 (LISTEN)
v2ray   6330 root   13u  IPv6  83112      0t0  TCP *:29979 (LISTEN)
奇特的地方在于，我只开了2个随机端口，但是显示双倍的个数。
经过仔细对比，我发现error.log里出现的2个警告报错端口号，会和上面命令后看见其中2个号重合。
--------
我再按时间顺序简单描述一下这个情况的产生——
（为方便描述，假设仍然是"concurrency": 2,  "refresh": 60 ，并且假设打开的随机端口是按顺序产生的）
①systemctl restart v2ray后用lsof -i6 |grep v2ray查看端口，发现开出了2个端口，假设为1001和1002；
②服务器端error.log出现[Warning]Core: V2Ray started的警告日志；
③1小时后观察error.log无反应，但是lsof -i6 |grep v2ray观察打开的端口，会变成4个！假设为1001、1002、1003和1004，本机telnet过去发现这4个端口均有响应；
④再次1小时后（也就是重启v2ray的2小时后）观察error.log，新出现2条上方提到提到的警告，端口为1001和1002；此时lsof观察打开的端口仍然是4个，为1003、1004、1005和1006；
⑤如果再等1小时，警告日志中报错的端口会是1003和1004，实际打开的端口会是1005、1006、1007和1008。

5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
```javascript
    // 在这里附上服务器端配置文件
```

    客户端配置:
```javascript
    // 在这里附上客户端配置
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
```
    // 在这里附上服务器端日志
```

    客户端错误日志:
```
    // 在这里附上客户端日志
```
客户端里会常有这样的日志
[Warning]failed to handler mux client connection > Proxy|VMess|Outbound: connection ends > context canceled
但看上去应该和本问题无关

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
```
    // 在这里附上服务器端日志
```

请预览一下你填的内容再提交。

如果你已经填完上面的问卷，请把下面的英文部份删除，再提交 Issue。
Please remove the Chinese section above.

English:
Please read the [instruction](https://www.v2ray.com/en/get_started/issue.html) and answer the following questions before submitting your issue. Thank you.
Please answer all the questions with enough information. Lack of information will delay response.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)

4) What's your expectation?

5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Server configuration:
```javascript
    // Please attach your server configuration here.
```

    Client configuration:
```javascript
    // Please attach your client configuration here.
```

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.

    Server error log:
```
    // Please attach your server error log here.
```
    Client error log:
```
    // Please attach your client error log here.
```

7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.
```
    // Please attach your server access log here.
```

Please review your issue before submitting.

**Comment by DarienRaymond** [comment]
这个错误信息是正常，每次动态端口切换的时候都会有这个信息。
