### ISSUE TITLE
路由走向错误

### ISSUE THREAD

**Issue by sunshineplan** [v2ray/v2ray-core#755]
版本3.0，其中一段路由配置
{
          "type": "field",
          "domain": [
            "geosite:cn"
          ],
          "ip": [
            "geoip:cn"
          ],
          "outboundTag": "direct"
},
{
          "type": "field",
          "inboundTag": "one",
          "outboundTag": "vmess"
        },
        {
          "type": "field",
          "inboundTag": "two",
          "outboundTag": "vmess"
        }

第一种情况：当配置为"domainStrategy": "IPIfNonMatch"
2017/12/01 22:17:00 [Info]Proxy|Socks: TCP Connect request to tcp:www.baidu.com:443
2017/12/01 22:17:00 [Info]App|Dispatcher|Default: taking detour [vmess] for [tcp:www.baidu.com:443]

第二种情况：当配置为"domainStrategy": "IPOnDemand"
2017/12/01 22:19:13 [Info]Proxy|Socks: TCP Connect request to tcp:www.baidu.com:443
2017/12/01 22:19:13 [Info]App|Router: looking for IP for domain: www.baidu.com
2017/12/01 22:19:13 [Info]App|Dispatcher|Default: taking detour [direct] for [tcp:www.baidu.com:443]

第三种情况：当配置为"domainStrategy": "IPOnDemand"
2017/12/01 22:22:19 [Debug]Proxy|Dokodemo: processing connection from: 10.31.2.2:53755
2017/12/01 22:22:19 [Info]App|Dispatcher|Default: taking detour [vmess] for [tcp:115.239.210.31:80]

这三种情况，除了第二种走对了以外，第一和第三种都走错。

**Comment by DarienRaymond** [comment]
请按模板发 issue 并仔细看文档：https://www.v2ray.com/chapter_02/03_routing.html

**Comment by sunshineplan** [comment]
下次注意
原来是因为当多个属性同时指定时，这些属性需要同时满足，才可以使当前规则生效
所以要把geosite和geoip拆开才对
