### ISSUE TITLE
能否支持数据库模式

### ISSUE THREAD

**Issue by holotr** [v2ray/v2ray-core#76]
将uuid和等级写入数据库方便多用户管理

**Comment by v2ray** [comment]
有计划做一套 API，可由其它程序控制 V2Ray。基本的想法是开放一个 HTTP 端口，接受 REST API。功能包括收集运行数据（如流量），开启关闭端口，增加删除用户等。

至于操作数据库，还要再等一等。

**Comment by CzBiX** [comment]
楼主提出的明显是 XY problem。
所有的管理操作都应该通过 V2Ray 提供的 API 来访问。

**Comment by zerogu** [comment]
强烈举双手支持REST API借口。。。我等WEB开发者的福音哈！

**Comment by wck963** [comment]
Windows pipe/unix socket could be better

**Comment by afyji** [comment]
这套API 现在做好了么

**Comment by wodedajiba** [comment]
做好了吗
