### ISSUE TITLE
High cpu usage (100%) on server

### ISSUE THREAD

**Issue by S-Tsunemori** [v2ray/v2ray-core#763]
The server has been running well for quiet a long time, until recently I found that my server is using up 100% cpu, and it was the v2ray process. In error log, I see TONS (100+) of lines like these:

```log
[Warning]App|Proxyman|Inbound: failed to create TCP worker > App|Proxyman|Inbound: failed to listen TCP on [*]017 > Transport|Internet: failed to listen on address: [IP]:[*]017 > listen udp [IP]:[*]017: bind: address already in use
[Warning]App|Proxyman|Inbound: failed to create TCP worker > App|Proxyman|Inbound: failed to listen TCP on [*]011 > Transport|Internet: failed to listen on address: [IP]:[*]011 > listen udp [IP]:[*]011: bind: address already in use
[Warning]App|Proxyman|Inbound: failed to create TCP worker > App|Proxyman|Inbound: failed to listen TCP on [*]013 > Transport|Internet: failed to listen on address: [IP]:[*]013 > listen udp [IP]:[*]013: bind: address already in use
[Warning]App|Proxyman|Inbound: failed to create TCP worker > App|Proxyman|Inbound: failed to listen TCP on [*]024 > Transport|Internet: failed to listen on address: [IP]:[*]024 > listen udp [IP]:[*]024: bind: address already in use
[Warning]App|Proxyman|Inbound: failed to create TCP worker > App|Proxyman|Inbound: failed to listen TCP on [*]003 > Transport|Internet: failed to listen on address: [IP]:[*]003 > listen udp [IP]:[*]003: bind: address already in use
```
as well as these:
```log
[Warning]App|Proxyman|Inbound: connection ends > Proxy|VMess|Inbound: unable to set read deadline > Transport|Internet|mKCP: Connection closed.
```
and that's all, I see nothing else in the error log (besides ```[Warning]Core: V2Ray started```)

I'm not sure if that's the cause of the high cpu usage. I forgot to check memory usage before restart service but there was no swap I/O so I guess I didn't use up my memory. Was using v2.5.1 on server (linux-amd64) at the time, just updated to v3.0 and restarted service, will see if it happens again.

here's part of my server config (inbound detour section):
```json
    {
      "tag": "inbound_mkcp_main",
      "port": [*]000,
      "listen": "[IP]",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "[UUID]",
            "level": 1,
            "alterId": 32
          }
        ],
        "detour": {
          "to": "inbound_mkcp_detour"
        }
      },
      "streamSettings": {
        "network": "kcp",
        "kcpSettings": {
          [KCPSETTINGS]
        }
      }
    },
    {
      "tag": "inbound_mkcp_detour",
      "port": "[*]001-[*]030",
      "listen": "[IP]",
      "protocol": "vmess",
      "settings": {
        "default": {
          "level": 1,
          "alterId": 32
        }
      },
      "allocate": {
        "strategy": "random",
        "concurrency": 2,
        "refresh": 3
      }
    }
```

**Comment by DarienRaymond** [comment]
It seems that the ports for inbound_mkcp_detour are occupied by other processes.

**Please use issue template to submit new issues.**

**Comment by S-Tsunemori** [comment]
@DarienRaymond 
Sure, I'll use template next time, I've updated this one to fit the format as well.

On server I have only sshd listens on tcp 22, nginx listens on tcp 80 & 443, no other programs listening. The config I posted is the only inbound uses that range of ports, the main inbound listens on 127.0.0.1 using websocket which was reverse proxied by nginx.

I've also updated my server error log on top to include the time stamps, as you can see, even there's a lot of those messages in the recent few days, it's not happening constantly (once every 10~40 mintues) I don't know if it could be the cause of high CPU usage but there's really nothing else in the error log. I've searched in the full error log, and found almost every port from [*]001~[*]030 has failed listening, except for [*]007. Port [*]000 didn't show up in the error log also.

I have also see that message (already in use) before I v2.51 was released (from the time stamp) but that was like only once or twice in a few days and didn't cause any extreme CPU usage or connection fail.

Also, why does the error log say ``` failed to listen TCP on``` ? I'm using mkcp, shouldn't that mean it only listens on udp ports? (I only allowed udp connections on those ports in ufw and the proxy worked fine)

**Comment by DarienRaymond** [comment]
You can disable 'inbound_mkcp_detour' see whether V2Ray still runs at 100% CPU or not. When an inbound uses dynamic ports and port allocation fails like this, it takes 100% CPU to find another available ports.
