### ISSUE TITLE
2.47之后的版本默认配置都没用

### ISSUE THREAD

**Issue by jang-u** [v2ray/v2ray-core#764]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
2.51、3.0、3.01
没有服务器

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
来这

3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
不能来这
能去国内

4)  你期待看到的正确表现是怎样的？
能来这
能去国内

5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
没有服务器

    客户端配置:
默认配置

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
没有服务器

    客户端错误日志:
windows版找不到log

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
没有服务器

8) 其它相关的配置文件（如 Nginx）和相关日志。
2.47和以前的版本默认就能来这：下载解压运行，浏览器设置好代理socks 1080就能来这

**Comment by jang-u** [comment]
2.47之后的版本试过默认配置增加
"domainOverride": "http"
没用
"domainOverride": "tls"
也没用

格式写对的，没写对主程序窗口会报错

**Comment by DarienRaymond** [comment]
官服已挂，请自行搭建服务器或购买第三方服务。
