### ISSUE TITLE
游戏延迟变大

### ISSUE THREAD

**Issue by yuzhg** [v2ray/v2ray-core#765]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V3.0

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
Proxifier + VMess  + window 客户端 玩游戏

3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
大约从某一个版本开始，延迟从平均120 增加到平均140。同样的VPS用ssr的延迟还是和以前相当，所以应该可以排除是服务器本身的问题。
具体记不清是哪个版本了，好想是有一个优化连接的fix以后。

4)  你期待看到的正确表现是怎样的？
延迟当然是越低越好@@

5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

关键部分：
```json
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "***",
          "port":***
          "users": [
            {
              "id": "***",
              "alterId": 10,
              "security": "none"
            }
          ]
        }
      ]
    },
    "mux": {
      "enabled": true
    },
    "streamSettings": {
    }
  },

```
因为主要是游戏的通讯，所以把security关掉了，换来更好的延迟。

另外求问，为了游戏的目的的话，最优化的配置应该用什么@@

**Comment by Cwek** [comment]
kcp？

**Comment by yuzhg** [comment]
我尝试过kcp。
在我的vps链接比较稳定的前提下，kcp貌似并没有太大的提升，相反还会稍微慢一点点。

**Comment by Cwek** [comment]
kcp，可以将tti调密一些（20）试试。

**Comment by yuzhg** [comment]
感谢建议。

我尝试了下，我把TTI改成了10，依然追不上直接用tcp的延迟，大概还是会高一个20左右。

**Comment by agzfan** [comment]
我测试win远程桌面,ssr在操作延迟上也比v2ray低

**Comment by rmlea** [comment]
proxifier 好像不能转发 udp

**Comment by BenhoNNNN** [comment]
我尝试很多版本，目前还是保留 2.46 用来玩游戏，延时比较稳定。

**Comment by WANG-lp** [comment]
@yuzhg security可以使用aes-gcm类加密的，none会使用自定义的包校验，不一定比硬件加速过的aes-gcm快
