### ISSUE TITLE
client和server疯狂报错，暂时不明影响

### ISSUE THREAD

**Issue by kz-wind** [v2ray/v2ray-core#767]
Please skip to the English section below if you don't write Chinese.

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://www.v2ray.com/chapter_01/issue.html)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
服务器3.01版本，客户端3.0版本

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
使用proxifier上网，或者网页直接代理，使用手机代理

3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
暂未发现不正常现象

4)  你期待看到的正确表现是怎样的？
报错停止，找到报错原因
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
```javascript
    // 在这里附上服务器端配置文件
```
{
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 28000,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "*",
          "level": 1,
          "alterId": 64
        }
      ]
    }
  },
  "inboundDetour": [               //举例如果只想使用KCP一种inboundDetour的整个段就可以全部删除^_^
    {
      "port": 29000,       //kcp (udp) 监听端口
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "*",  //替换你的UUID不能重复
            "level": 1,
            "alterId": 64
          }
        ]
      },
          "streamSettings": {
        "network": "kcp"
                }
        },
    {
      "port": 28001,       //tcp (tcp) 动态端口主监听端口
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "*",  //替换你的UUID不能重复
            "level": 1,
            "alterId": 64
          }
        ],
        "detour": {
          "to": "detour-tcp"
        }
      }
    },
    {
      "port": 29001,       //kcp (udp) 动态端口主监听端口
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "*",  //替换你的UUID不能重复
            "level": 1,
            "alterId": 64
          }
        ],
        "detour": {
          "to": "detour-kcp"
        }
      },
          "streamSettings": {
        "network": "kcp"
                }
    },
    {
      "protocol": "vmess",
      "port": "50001-50100",   //kcp (udp)动态端口监听范围
      "tag": "detour-kcp",
      "settings": {},
      "allocate": {
        "strategy": "random", //随机
        "concurrency": 2,     //开放2个端口
        "refresh": 5          //5分钟刷新一次
      },
      "streamSettings": {
        "network": "kcp"
      }
    },
    {
      "protocol": "vmess",
      "port": "51001-51100",   //tcp (tcp)动态端口监听范围
      "tag": "detour-tcp",
      "settings": {},
      "allocate": {
        "strategy": "random",
        "concurrency": 2,
        "refresh": 5
      }
    }
  ],
  
  
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },

  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "domain": [
            "geosite:cn"
           ],
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10",
            "geoip:cn"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  },
  "transport": {
    "kcpSettings": {
      "mtu": 1350,
      "tti": 20,
      "uplinkCapacity": 20,
      "downlinkCapacity": 20,
      "congestion": true,
      "readBufferSize": 1,
      "writeBufferSize": 1,
      "header": {
        "type": "none"
      }
    }
}
    客户端配置:
```javascript
    // 在这里附上客户端配置
```
{
  "log": {
    "access": "Vaccess.log",
    "error": "Verror.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 4434,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "127.0.0.1",
      "clients": null
    },
    "streamSettings": null
  },
  "outbound": {
    "tag": "agentout",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "*",
          "port": 28001,
          "users": [
            {
              "id": "*",
              "alterId": 64,
              "security": "aes-128-gcm"
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "tcp",
      "security": "",
      "tcpSettings": null,
      "kcpSettings": null,
      "wsSettings": null
    },
    "mux": {
      "enabled": true
    }
  },
  "inboundDetour": [
  {
	"protocol": "http",
	"port": 44340,
	"settings": {}
	}
 ],
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {
        "response": null
      },
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "blockout"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": null,
          "outboundTag": "direct",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10",
			"geoip:cn"
          ],
           "domain": ["geosite:cn"]
        }
      ]
    }
  }
}

{
  "log": {
    "access": "Vaccess.log",
    "error": "Verror.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 4436,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "127.0.0.1",
      "clients": null
    },
    "streamSettings": null
  },
  "outbound": {
    "tag": "agentout",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "*",
          "port": 29001,
          "users": [
            {
              "id": "*",
              "alterId": 64,
              "security": "aes-128-gcm"
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "kcp",
      "security": "",
      "tcpSettings": null,
      "kcpSettings": null,
      "wsSettings": null
    },
    "mux": {
      "enabled": true
    }
  },
  "inboundDetour": null,
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {
        "response": null
      },
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "blockout"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": null,
          "outboundTag": "direct",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10",
			"geoip:cn"
          ],
           "domain": ["geosite:cn"]
        }
      ]
    }
  }
}
6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
```
    // 在这里附上服务器端日志
```
2017/12/07 13:10:48 [Warning]Transport|Internet|TCP: failed to accepted raw connections > Retry: [accept tcp [::]:51036: use of closed network connection] > Retry: all retry attempts failed
2017/12/07 13:15:48 [Warning]Transport|Internet|TCP: failed to accepted raw connections > Retry: [accept tcp [::]:51010: use of closed network connection] > Retry: all retry attempts failed
2017/12/07 13:15:48 [Warning]Transport|Internet|TCP: failed to accepted raw connections > Retry: [accept tcp [::]:51054: use of closed network connection] > Retry: all retry attempts failed
2017/12/07 13:20:48 [Warning]Transport|Internet|TCP: failed to accepted raw connections > Retry: [accept tcp [::]:51002: use of closed network connection] > Retry: all retry attempts failed
2017/12/07 13:20:48 [Warning]Transport|Internet|TCP: failed to accepted raw connections > Retry: [accept tcp [::]:51035: use of closed network connection] > Retry: all retry attempts failed
    客户端错误日志:
```
    // 在这里附上客户端日志
```
2017/12/07 12:30:57 [Warning]failed to handler mux client connection > Proxy|VMess|Outbound: connection ends > context canceled
2017/12/07 12:33:01 [Warning]failed to handler mux client connection > Proxy|VMess|Outbound: connection ends > context canceled
2017/12/07 12:33:24 [Warning]failed to handler mux client connection > Proxy|VMess|Outbound: connection ends > context canceled
2017/12/07 12:40:43 [Warning]failed to handler mux client connection > Proxy|VMess|Outbound: connection ends > context canceled
2017/12/07 12:40:43 [Warning]failed to handler mux client connection > Proxy|VMess|Outbound: connection ends > context canceled
2017/12/07 12:43:16 [Warning]failed to handler mux client connection > Proxy|VMess|Outbound: connection ends > context canceled
2017/12/07 12:50:05 [Warning]failed to handler mux client connection > Proxy|VMess|Outbound: connection ends > context canceled
2017/12/07 12:50:12 [Warning]failed to handler mux client connection > Proxy|VMess|Outbound: connection ends > context canceled
2017/12/07 12:50:58 [Warning]failed to handler mux client connection > Proxy|VMess|Outbound: connection ends > context canceled
2017/12/07 12:53:52 [Warning]failed to handler mux client connection > Proxy|VMess|Outbound: connection ends > context canceled
2017/12/07 12:56:00 [Warning]failed to handler mux client connection > Proxy|VMess|Outbound: connection ends > context canceled
2017/12/07 12:56:43 [Warning]failed to handler mux client connection > Proxy|VMess|Outbound: connection ends > context canceled
2017/12/07 13:00:08 [Warning]failed to handler mux client connection > Proxy|VMess|Outbound: connection ends > context canceled
2017/12/07 13:00:57 [Warning]failed to handler mux client connection > Proxy|VMess|Outbound: connection ends > context canceled

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
```
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

请预览一下你填的内容再提交。

这是其中一台服务器的配置和报错日志，由于同时使用2台服务器，并且同时开启tcp，kcp动态端口，且2台服务器配置相同，这里只贴上一台的报错日志，日志报错从客户端上我查看的最早报错的大概日期是11月18日，之前的我也不清楚怎么没了，配置大概是11月9日-11日之间配置的，麻烦查看下问题所在，现在目前应该是不影响正常使用

**Comment by DarienRaymond** [comment]
两个错误信息都没有问题，服务器端是因为开了动态端口，会有周期性（在动态端口刷新时）的信息。客户端的错误信息，如果不影响正确使用，可以无视。

**Comment by kz-wind** [comment]
好的，明白了，谢谢
