### ISSUE TITLE
内存消耗太大了。。。

### ISSUE THREAD

**Issue by zysuper** [v2ray/v2ray-core#77]
和ss比，内存消耗不是一个数量级的呀。

**Comment by thrieu** [comment]
Go 语言是如此，等V大有空优化吧。

**Comment by v2ray** [comment]
请给出具体数据和你的配置，以及你所期待的内存用量。

**Comment by tlhc** [comment]
好耐心的开发者

**Comment by holotr** [comment]
开了5个服务端把512内存的vps榨干了= =

**Comment by v2ray** [comment]
@holotr  请给出你的配置

**Comment by holotr** [comment]
`{
  "port": 9999,
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "protocol": "vmess",
    "settings": {
      "clients": [  
        {
          "id": "e81d8e80-29bc-4c57-bf65-93547fded511",
          "level": 1,
          "alterId": 100
        },
        {
          "id": "258889d8-e0bc-45ca-9b73-dff62429ef94",
          "level": 1,
          "alterId": 100
        },
        {
          "id": "a537392e-d17f-4ad9-910d-22bb4ea5194c",
          "level": 1,
          "alterId": 100
        },
        {
          "id": "4d37e444-c58a-4e51-be85-85c71ebac766",
          "level": 1,
          "alterId": 100
        },
        {
          "id": "048a97e0-5ebb-4e93-8f09-223f685d0887",
          "level": 1,
          "alterId": 100
        }
      ],
      "features": {           
        "detour": {             
          "to": "detourHandler"
        }
      }
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "inboundDetour": [
    {
      "protocol": "vmess",
      "port": "20000-29999",  
      "tag": "detourHandler", 
      "settings": {
        "clients": [ 
          {
            "id": "e81d8e80-29bc-4c57-bf65-93547fded511",
            "level": 1,
            "alterId": 100
          },
          {
            "id": "258889d8-e0bc-45ca-9b73-dff62429ef94",
            "level": 1,
            "alterId": 100
          },
          {
            "id": "a537392e-d17f-4ad9-910d-22bb4ea5194c",
            "level": 1,
            "alterId": 100
          },
          {
            "id": "4d37e444-c58a-4e51-be85-85c71ebac766",
            "level": 1,
            "alterId": 100
          },
          {
            "id": "048a97e0-5ebb-4e93-8f09-223f685d0887",
            "level": 1,
            "alterId": 100
        }
        ]
      },
      "allocate": {           
        "strategy": "random", 
        "concurrency": 2,    
        "refresh": 5         
      }
    }
  ],
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {          
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}`

**Comment by holotr** [comment]
{
  "port": 9999,
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "protocol": "vmess",
    "settings": {
      "clients": [  
        {
          "id": "e81d8e80-29bc-4c57-bf65-93547fded511",
          "level": 1,
          "alterId": 100
        },
        {
          "id": "258889d8-e0bc-45ca-9b73-dff62429ef94",
          "level": 1,
          "alterId": 100
        },
        {
          "id": "a537392e-d17f-4ad9-910d-22bb4ea5194c",
          "level": 1,
          "alterId": 100
        },
        {
          "id": "4d37e444-c58a-4e51-be85-85c71ebac766",
          "level": 1,
          "alterId": 100
        },
        {
          "id": "048a97e0-5ebb-4e93-8f09-223f685d0887",
          "level": 1,
          "alterId": 100
        }
      ],
      "features": {           
        "detour": {             
          "to": "detourHandler"
        }
      }
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "inboundDetour": [
    {
      "protocol": "vmess",
      "port": "20000-29999",  
      "tag": "detourHandler", 
      "settings": {
        "clients": [ 
          {
            "id": "e81d8e80-29bc-4c57-bf65-93547fded511",
            "level": 1,
            "alterId": 100
          },
          {
            "id": "258889d8-e0bc-45ca-9b73-dff62429ef94",
            "level": 1,
            "alterId": 100
          },
          {
            "id": "a537392e-d17f-4ad9-910d-22bb4ea5194c",
            "level": 1,
            "alterId": 100
          },
          {
            "id": "4d37e444-c58a-4e51-be85-85c71ebac766",
            "level": 1,
            "alterId": 100
          },
          {
            "id": "048a97e0-5ebb-4e93-8f09-223f685d0887",
            "level": 1,
            "alterId": 100
        }
        ]
      },
      "allocate": {           
        "strategy": "random", 
        "concurrency": 2,    
        "refresh": 5         
      }
    }
  ],
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {          
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}

**Comment by v2ray** [comment]
@holotr 动态端口情况下的 inboundDetour 里多个 id 设置暂时不会起作用，只保留一个即可，这样可以有效减少内存使用。另外动态端口所使用的 id 不必和主端口一致。

比如这个样子：

```javascript
"inboundDetour": [
    {
      "protocol": "vmess",
      "port": "20000-29999",  
      "tag": "detourHandler", 
      "settings": {
        "clients": [ 
          {
            "id": "11609f59-65ce-4701-bb65-37e5aa55e2bb",
            "level": 1,
            "alterId": 100
          }
        ]
      },
      "allocate": {           
        "strategy": "random", 
        "concurrency": 2,    
        "refresh": 5         
      }
    }
  ],
```

**Comment by holotr** [comment]
谢谢作者大大
