### ISSUE TITLE
3.1版中关于本地策略的几点疑问

### ISSUE THREAD

**Issue by offferu** [v2ray/v2ray-core#770]
1）是level还是levels? //以前网上的配置多为"level": 1, 这次看官网为"levels"
2) 自用VPS是不是level为1？
3）该如何表达？"levels": {"1"} 是这样吗？

**Comment by oing9179** [comment]
@offferu Reply [#1](#issue-280370115)

1. 是level还是levels? //以前网上的配置多为"level": 1, 这次看官网为"levels"
  `level` 是给 VMess 里单个用户用的, `levels` 是用来设置 VMess 用户所使用的 `level`
2. 自用VPS是不是level为1？
  对
3. 该如何表达？"levels": {"1"} 是这样吗？
  喵喵喵?

**Comment by DarienRaymond** [comment]
请仔细看文档。
