### ISSUE TITLE
升级3.1以后无法获取IP，无法正常使用

### ISSUE THREAD

**Issue by afboyxiyang** [v2ray/v2ray-core#771]
今天升级V2Ray3.1，直接用UP命令升级的，服务器是Debian 9 x86_64 
升级前用的是2.5系列，能正常使用，与SSR可以并存！
说升级不会更改配置，结果升级后根本无法正常使用
后来又删除重新安装，也是不行……

------------运行信息-----------
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2017-12-08 10:14:36 EST; 1min 46s ago
 Main PID: 29284 (v2ray)
    Tasks: 6 (limit: 4915)
   CGroup: /system.slice/v2ray.service
           └─29284 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json

Dec 08 10:14:36 debian systemd[1]: Stopped V2Ray Service.
Dec 08 10:14:36 debian systemd[1]: Started V2Ray Service.
Dec 08 10:14:36 debian v2ray[29284]: V2Ray v3.1 (die Commanderin) 20171207
Dec 08 10:14:36 debian v2ray[29284]: An unified platform for anti-censorship.
Dec 08 10:14:36 debian v2ray[29284]: 2017/12/08 10:14:36 [Debug]App|Proxyman|Inbound: creating tcp worker on 0.0.0.0:1234
--------------------------------------

-----------日志-------------------------

2017/12/08 06:09:53 ******:61472 rejected  Proxy|VMess|Encoding: failed to read request header > read tcp ********:1234->********:61472: i/o timeout
2017/12/08 06:09:54 ******:61480 rejected  Proxy|VMess|Encoding: failed to read request header > read tcp *********:1234->*******:61480: i/o timeout

…………………………

------------------------------

**Comment by DarienRaymond** [comment]
请完整填写issue模板
