### ISSUE TITLE
[document request]请更新本地策略(v3.1)相关文档以便用户更好的配置

### ISSUE THREAD

**Issue by kmahyyg** [v2ray/v2ray-core#774]
RT.

TG群里问的太多了，看不明白，还麻烦开发者更新文档

**Comment by supppig** [comment]
支持。我也想知道那4个参数的默认值~~

**Comment by okaygh** [comment]
手册看不太明白,这个本地策略是在服务端还是客户端设置的?还是两边都要设置?服务端和客户端的参数需要一致吗?
