### ISSUE TITLE
v2ray默认不会代理全部流量？

### ISSUE THREAD

**Issue by JuanMao1997** [v2ray/v2ray-core#777]
我在Windows上使用v2.14,默认配置。

用百度查IP显示我真实的IP地址，

用Google查IP则显示日本代理服务器的IP 45.63.123.104

请问可以设置全部流量都走代理么？

现在看来访问未被墙的网站不会使用代理！！！

**Comment by DarienRaymond** [comment]
需要配置：https://www.v2ray.com/chapter_02/03_routing.html
