### ISSUE TITLE
dokodemo使用求解

### ISSUE THREAD

**Issue by fax001** [v2ray/v2ray-core#781]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
3.1
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
使用dokodemo访问gmail
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
通过配置iptables已经实现安装v2ray的机器访问gmail 
4)  你期待看到的正确表现是怎样的？
希望实现其他未安装v2ray的机器可以通过安装了v2ray的机器访问gmail
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
```javascript
    // 在这里附上服务器端配置文件
```

    客户端配置:
```javascript
    {
	"log": {
		"access": "/var/log/v2ray/access.log",
		"error": "/var/log/v2ray/error.log",
		"loglevel": "debug"
	},
	"inbound": {
		"protocol": "dokodemo-door",
		"port": 11111,
		"address": "",
		"settings": {
			"network": "tcp",
			"timeout": 0,
			"followRedirect": true,
			"allowPassive": false
		}
	},
	"outbound": {
		"protocol": "vmess",
		"settings": {
			"vnext": [{
					"address": "",
					"port": 35001,
					"users": [{
							"id": "",
							"alterId": 32
						}
					]
				}
			]
		}
	}
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
```
    // 在这里附上服务器端日志
```

    客户端错误日志:
```
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
```
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

请预览一下你填的内容再提交。

如果你已经填完上面的问卷，请把下面的英文部份删除，再提交 Issue。

**Comment by 1oo1** [comment]
> Dokodemo door（任意门）是一个传入数据协议，它可以监听一个本地端口，并把所有进入此端口的数据发送至指定服务器的一个端口，从而达到端口映射的效果。

Dokodemo door 的文档说明是端口映射用，所以建议 inbound 改成 HTTP 或 SOCKS，address 是 0.0.0.0，注重安全的话可以减少密码验证，其他客户端用这个 inbound 代理即可。

或者，做个软路由，其他设备需要改默认的路由地址，这个稍微复杂，可以Google查下。

**Comment by DarienRaymond** [comment]
至少要说明一下你的iptables配置，以及其它的机器中看到的是什么样的现象吧。你的配置看上去没有问题。

**Comment by fax001** [comment]
@DarienRaymond 
在安装了v2ray的客户端的机器上的iptables
iptables -t nat -N V2RAY
iptables -t mangle -N V2RAY
iptables -t nat -A V2RAY -p tcp -j REDIRECT --to-ports 20158
iptables -t nat -d 74.125.204.108/32 -A OUTPUT -p tcp -j V2RAY
iptables -t nat -d 74.125.204.109/32 -A OUTPUT -p tcp -j V2RAY
iptables -t nat -d 216.58.197.100/32 -A OUTPUT -p tcp -j V2RAY
iptables -t mangle -A PREROUTING -j V2RAY
在安装了v2ray的客户端的机器上访问gmail是正常的
主要是在其他机器上需要如何设置不得要领 
想先了解下可行性
简单描述下几台机器的网络情况
在VPC的同一网段中
可以指定对应IP的路由跳转到安装了v2ray的机器上（不知是否有帮助）
十分感谢

**Comment by DarienRaymond** [comment]
理论上是可以的，iptables的配置可以参考[相关说明](https://www.v2ray.com/chapter_02/protocols/dokodemo.html#%E9%80%8F%E6%98%8E%E4%BB%A3%E7%90%86%E9%85%8D%E7%BD%AE%E6%A0%B7%E4%BE%8B)。至于具体怎么调试，大概需要参考一些Linux的技术文档，我也帮不上太多的忙。

**Comment by ToutyRater** [comment]
@fax001 你可以参考我写的文章： https://toutyrater.github.io/app/transparent_proxy.html ，我用了一段时间，感觉很不错
