### ISSUE TITLE
HTTP与WebSocket伪装在手机上现在好像失效了

### ISSUE THREAD

**Issue by wansen** [v2ray/v2ray-core#788]
今天无意中上了一下10010，去查询了一下手机上网记录，如下：

序号 | 起始时间 | 业务类型 | 流量类型 | 访问网址 | 网址名称
-- | -- | -- | -- | -- | --
1 | 2017-12-20 08:20:17 | 聊天工具 | MobileQQ | imgcache.qq.com |  
2 | 2017-12-20 08:20:06 | 其他手机应用 | SSL安全类业务流量 | serveraddr.com |  
3 | 2017-12-20 08:11:52 | 其他手机应用 | 未识别TCP业务流量 | xxx.xxx.xxx.xxxx |  
4 | 2017-12-20 08:07:34 | 其他手机应用 | 未识别TCP业务流量 | xxx.xxx.xxx.xxxx |  
5 | 2017-12-20 07:57:33 | 其他手机应用 | 未识别TCP业务流量 | xxx.xxx.xxx.xxxx |  
6 | 2017-12-20 07:51:52 | 其他手机应用 | 未识别TCP业务流量 | xxx.xxx.xxx.xxxx |  
7 | 2017-12-20 07:47:33 | 其他手机应用 | 未识别TCP业务流量 | xxx.xxx.xxx.xxxx |  
8 | 2017-12-20 07:41:52 | 其他手机应用 | 未识别TCP业务流量 | xxx.xxx.xxx.xxxx |  
9 | 2017-12-20 07:37:33 | 其他手机应用 | 未识别TCP业务流量 | xxx.xxx.xxx.xxxx |  
10 | 2017-12-20 07:33:10 | 聊天工具 | MobileQQ | imgcache.qq.com |  
11 | 2017-12-20 07:31:52 | 其他手机应用 | 未识别TCP业务流量 | xxx.xxx.xxx.xxxx |  
12 | 2017-12-20 07:27:33 | 其他手机应用 | 未识别TCP业务流量 | xxx.xxx.xxx.xxxx |  
13 | 2017-12-20 07:27:22 | 其他手机应用 | SSL安全类业务流量 | serveraddr.com |  
14 | 2017-12-20 07:21:52 | 其他手机应用 | 未识别TCP业务流量 | xxx.xxx.xxx.xxxx |  
15 | 2017-12-20 07:17:33 | 其他手机应用 | 未识别TCP业务流量 | xxx.xxx.xxx.xxxx |  
…………

使用版本一直跟着v2ray更新走，同样的配置，只是最近在客户端配置内加入：
    "mux": {
      "enabled": true,
      "concurrency": 32
    }
上个月28号前正常（不确定是什么时候加入的MUX，只是最近)：
2 | 2017-11-30 00:09:47 | 其他手机应用 | 未识别TCP业务流量 | xxx.xxx.xxx.xxxx
3 | 2017-11-29 13:01:45 | 其他手机应用 | 未识别TCP业务流量 | xxx.xxx.xxx.xxxx
4 | 2017-11-28 21:32:38 | 其他手机应用 | 未识别TCP业务流量 | xxx.xxx.xxx.xxxx
5 | 2017-11-28 21:15:10 | 其他手机应用 | 未识别TCP业务流量 | 140.207.127.57
6 | 2017-11-28 21:09:41 | 其他手机应用 | 未识别TCP业务流量 | xxx.xxx.xxx.xxxx
7 | 2017-11-28 20:52:11 | 其他手机应用 | 未识别TCP业务流量 | xxx.xxx.xxx.xxxx
8 | 2017-11-28 20:40:18 | 其他手机应用 | 未识别TCP业务流量 | xxx.xxx.xxx.xxxx
9 | 2017-11-28 20:16:14 | 其他手机应用 | 未识别TCP业务流量 | xxx.xxx.xxx.xxxx
10 | 2017-11-28 20:13:20 | 其他手机应用 | 未识别TCP业务流量 | xxx.xxx.xxx.xxxx
11 | 2017-11-28 12:00:02 | 网页 | Web上网流量（Get） | wwww.office365.com
12 | 2017-11-28 11:59:36 | 其他手机应用 | 其他业务流量 | apps.itunes.apple.com
13 | 2017-11-28 11:59:34 | 其他手机应用 | SSL安全类业务流量 | static.oschina.net
14 | 2017-11-28 11:59:31 | 网页 | Web上网流量（Get） | office.live.com
15 | 2017-11-28 11:59:25 | 其他手机应用 | SSL安全类业务流量 | cdn.sspai.com
16 | 2017-11-28 11:59:18 | 网页 | Web上网流量（Get） | www.icloud.com
17 | 2017-11-28 11:58:56 | 网页 | Web上网流量（Get） | www.windows.com

因此不知道是联通升级了检测系统，还是软件有问题，来报个反馈，请开发者在有空时看看。谢谢

**Comment by DarienRaymond** [comment]
请按issue模板填写
