### ISSUE TITLE
Verify error:Invalid response from [domain]

### ISSUE THREAD

**Issue by huajialue04** [v2ray/v2ray-core#789]
执行以下命令生成证书：
sudo ~/.acme.sh/acme.sh --issue -d mydomain.me --standalone -k ec-256
[Fri Dec 22 13:13:39 CST 2017] Standalone mode.
[Fri Dec 22 13:13:39 CST 2017] Single domain='mydomain.me'
[Fri Dec 22 13:13:39 CST 2017] Getting domain auth token for each domain
[Fri Dec 22 13:13:39 CST 2017] Getting webroot for domain='mydomain.me'
[Fri Dec 22 13:13:39 CST 2017] Getting new-authz for domain='mydomain.me'
[Fri Dec 22 13:13:40 CST 2017] The new-authz request is ok.
[Fri Dec 22 13:13:41 CST 2017] Verifying:mydomain.me
[Fri Dec 22 13:13:41 CST 2017] Standalone mode server
[Fri Dec 22 13:13:45 CST 2017] **mydomain.me:Verify error:Invalid response from http://mydomain.me/.well-known/acme-challenge/Gas_eFo1VsnpKZVJQOmQskvuNla23cN2xRYTXTLyyh8:** 
[Fri Dec 22 13:13:45 CST 2017] Please add '--debug' or '--log' to check more details.
[Fri Dec 22 13:13:45 CST 2017] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
域名已经解析成功了。出现粗体字所示错误，是什么问题呢，该怎么办呢？

**Comment by 699ebe23** [comment]
你应该在这个地方提issue
https://github.com/Neilpang/acme.sh/issues

**Comment by huajialue04** [comment]
哦，好的。我这个是在安装V2ray的TLS的时候出现的

**Comment by DarienRaymond** [comment]
目测和v2ray没有关系

**Comment by ToutyRater** [comment]
@huajialue04 看教程请认真点好不好，已经很清楚地说了 `假设注册的域名为 mydomain.me，请将之替换成自己的域名`
