### ISSUE TITLE
xxxxxxx.tumblr.com域名打开困难

### ISSUE THREAD

**Issue by agzfan** [v2ray/v2ray-core#790]
v2ray tcp kcp ws都试过,使用的是http,mux关闭,dns 8.8.8.8 8.8.4.4

打开https://www.tumblr.com/dashboard个人主页订阅了的客户视频图片都是正常
但是点击视频切换到该用户,用户域名通常是xxxxxxx.tumblr.com(杂七杂八的)
刷不出页面,要过好几分钟才能刷出来,而且视频也是要很久才能播放
这个是老问题了,之前某个帖子里也有人提过,不知有没人遇到过?

类似问题
https://github.com/v2ray/v2ray-core/issues/748
https://github.com/v2ray/v2ray-core/issues/561
https://github.com/v2ray/v2ray-core/issues/571

**Comment by DarienRaymond** [comment]
请按issue模板提交issue，否则无法分析具体原因。
