### ISSUE TITLE
运行V2RAY时无法打开绝地求生

### ISSUE THREAD

**Issue by timsensor** [v2ray/v2ray-core#791]
被BattleEye检测到运行V2ray.exe和WV2ray.exe时，就会强制退出游戏
能避免被检测到吗？
00:55:32: Starting BattlEye Service...
00:55:39: Launching game...
00:56:36: Note: File blocks can be ignored if they don't cause problems with the game.
00:56:36: [INFO] Blocked loading of file: "F:\*******\v2rayN\v2ray.exe".
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V2ray 2.50 + V2rayN

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
《绝地求生》

**Comment by xiaokangwang** [comment]
我看了一下BattlEye的说明，从理论上，PUBG是不应该加载V2Ray的，而且这个文件和游戏之间也没有什么关联。

**Comment by xiaokangwang** [comment]
这个是在你运行V2Ray的时候出现的么？如果不运行的时候是什么情况呢？

**Comment by timsensor** [comment]
不运行V2RAY，可以直接进游戏，而不会自动退出。

**Comment by DarienRaymond** [comment]
v2ray.exe 本身没有任何依赖的，你可以改个文件名试试。当然这样 v2rayN 大概就不能用了。

**Comment by xiaokangwang** [comment]
@v2ray 可能是游戏会检查所有运行进程。因此可能我们联系这个厂家将我们排除一下我们的程序。如果改个名字就能用外挂肯定已经这么做了。

**Comment by wilsonkor** [comment]
同样吃鸡，没有遇到楼主的情况哦。。

**Comment by xiaokangwang** [comment]
这个问题应该联系相关反外挂程序的厂家，因为这个问题不在我们的控制的范围之内。  https://www.battleye.com/support/

如果这个问题和具体的配置和设置有关建议按照issue模版重新提交issue。

**Comment by DarienRaymond** [comment]
@xiaokangwang 我只是想排除是不是由v2ray.exe直接引起的，因为看描述还涉及到v2rayN。

@timsensor 我对BattlEye不了解，建议你去他们的客服抱怨一下，需要互怼的话可以（私下）联系v2ray团队。

**Comment by BenhoNNNN** [comment]
同样在用 V2Ray 吃鸡：

1. V2Ray Client 开启 Socks5 传入+ UDP 转发；

2. 前端使用 Proxifier 劫持 PUBG 流量：
```
tslgame.exe; 
tslgame_be.exe; 
beservice_x64.exe; 
brocrashreporter.exe
```
另外默认 localhost via direct 规则不能删，不然游戏 VoIP 功能失效。

3. 提示：前台运行经常会被检测报错，做成后台开机服务，一切正常。

**Comment by chenyue404** [comment]
吃鸡从来不关v2ray，没问题的。

**Comment by bluexzh** [comment]
> 吃鸡从来不关v2ray，没问题的。

你好，请问怎么用v2ray，加速吃鸡
