### ISSUE TITLE
求助，这种情况如何解决！！！

### ISSUE THREAD

**Issue by zhengxuefu** [v2ray/v2ray-core#793]
系统：Red Hat Enterprise Linux Server release 6.8 (Santiago)
Linux  2.6.32-642.3.1.el6.s390x
采用的是go。sh脚本安装，出现如下问题
提示信息如下
Installing daemon
Updating software repo
install_v2ray.sh: line 119: apt-get: command not found
Installing daemon
install_v2ray.sh: line 124: apt-get: command not found
Install daemon fail, please install it manually.
[root@hehe src]# service v2ray start
v2ray: unrecognized service

**Comment by DarienRaymond** [comment]
请确认你的系统支持 apt 或者 yum，如果不支持的话，你需要手动安装 unzip、curl 和 systemd 组件。
