### ISSUE TITLE
当作为中转服务器时 无法命中路由配置的GeoIP规则

### ISSUE THREAD

**Issue by Lily-Ayta** [v2ray/v2ray-core#794]
使用3.4版本时（客户端和中转服务器均同一版本），中转服务器无法根据请求的主机名或IP正确分流至多个ss服务器。

大致的目标是这样的：客户端向中转服务器发送请求，中转根据客户端请求的主机名解析结果（或IP，如果请求不为tls/http）的GeoIP做分流，分流至其他几个区域Shadowsocks服务器。

现在的情况是：对于tls/http的纯ip请求能够正确转发，但如果带主机名请求则无法正确命中IP规则，全部fallback至默认outbound路由。（debug信息如下图，左为中转服务器的输出，右为客户端同时执行测试的结果，中转服务器系统时区为UTC）
![default](https://user-images.githubusercontent.com/29628836/34340275-26d5722a-e9bc-11e7-9afb-063bc684542c.png)
Additional: 设定 `domainStrategy` 为 `IPIfNonMatch` 或 `IPOnDemand` ，情况依旧

在执行后2个测试命令的同时，JP端ss没有收到任何来自中转服务器的请求；但第一个请求已被成功转发（该服务器系统时区为UTC+8，使用shadowsocks-libev）：
![default](https://user-images.githubusercontent.com/29628836/34340363-b65ccf3c-e9bd-11e7-8799-4334d23c1723.png)

客户端&中转服务器配置： https://gist.github.com/Lily-Ayta/c76645aeb6315646c88183666a696a72

**Comment by DarienRaymond** [comment]
服务器的路由中没有配置domainStrategy，默认情况是不进行DNS解析。详见: https://www.v2ray.com/chapter_02/03_routing.html

另外请按issue模板提交issue。
