### ISSUE TITLE
v2ray 报错无法运行。

### ISSUE THREAD

**Issue by newcoderlife** [v2ray/v2ray-core#796]
Please skip to the English section below if you don't write Chinese.

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V2Ray v3.4 (die Commanderin) 20171222
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
无，v2ray无法启动。
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
运行v2ray --version时，提示：
  V2Ray v3.4 (die Commanderin) 20171222
  An unified platform for anti-censorship.
在运行v2ray时报错，提示这句话“An unified platform for anti-censorship.”。
4)  你期待看到的正确表现是怎样的？
能无错运行。
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    客户端配置:
```javascript
    {
    "inbound": {
        "port": 20131,
        "listen": "127.0.0.1",
        "protocol": "socks",
        "settings": {
            "udp": true
        }
    },
    "outbound": {
        "protocol": "vmess",
        "settings": {
            "vnext": [
                {
                    "address": "2400:a480:f:310:c1::5d",
                    "port": 20172,
                    "users": [
                        {
                            "id": "b831381d-6324-4d53-ad4f-8cda48b30811"
                        }
                    ]
                }
            ]
        }
    },
    "outboundDetour": [
        {
            "protocol": "freedom",
            "tag": "direct",
            "settings": {}
        }
    ],
    "routing": {
        "strategy": "rules",
        "settings": {
            "domainStrategy": "IPOnDemand",
            "rules": [
                {
                    "type": "field",
                    "ip": [
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "203.0.113.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10"
                    ],
                    "outboundTag": "direct"
                }
            ]
        }
    }
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    客户端错误日志:
无

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
无

8) 其它相关的配置文件（如 Nginx）和相关日志。
v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2017-12-28 14:48:49 CST; 1s ago
  Process: 3904 ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json (code=exited, status=255)
 Main PID: 3904 (code=exited, status=255)

12月 28 14:48:49 newcoderlife-PC systemd[1]: v2ray.service: Failed with result 'exit-code'.
12月 28 14:48:49 newcoderlife-PC systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
12月 28 14:48:49 newcoderlife-PC systemd[1]: Stopped V2Ray Service.
12月 28 14:48:49 newcoderlife-PC systemd[1]: v2ray.service: Start request repeated too quickly.
12月 28 14:48:49 newcoderlife-PC systemd[1]: Failed to start V2Ray Service.
12月 28 14:48:49 newcoderlife-PC systemd[1]: v2ray.service: Unit entered failed state.
12月 28 14:48:49 newcoderlife-PC systemd[1]: v2ray.service: Failed with result 'exit-code'.
请预览一下你填的内容再提交。

如果你已经填完上面的问卷，请把下面的英文部份删除，再提交 Issue。

**Comment by enmoment** [comment]
遇见相同的问题。
