### ISSUE TITLE
QNAP docker file v2ray/official 不能升级新的版本

### ISSUE THREAD

**Issue by fengrunkai** [v2ray/v2ray-core#798]
能用到v2ray让我很开心，因为有了v2ray就有那么多“科学上网”的功能，我非常敬佩背后的工作人员。

说回正题，我的QNAP docker container能安装docker/official是没有问题，但是如果：
现在我用的v3.4。

要升级新的版本时，根本没有升级的键，于是我尝试多开一个container，从docker hub下载，但是生产出来的container里面的版本跟之前一样。现在我需要把所有安装v2ray/official的container铲除，让后从新安装。

不知道是否version是latest问题，所以系统用了local的latest image，而不是从docker hub里下载。不知道是否docker file里有version number来识别?

Eric

**Comment by fengrunkai** [comment]
我知道怎样解决这个问题。

首先我们先通过ssh进入QNAP (admin mode), 然后在系统root之下执行

docker pull v2ray/official

然后在QNAP container里进行安装（无论在local 或者 docker hub）都可以安装新的版本。

**Comment by DarienRaymond** [comment]
具体的 docket 及相关系统的使用问题请咨询对应的客服，其实我对 docker 也不熟。如果理解正确的话，docker 每次安装最新的 image 即可，不必升级现有的 image。
