### ISSUE TITLE
怎样把docker的config.json备份到别的电脑？

### ISSUE THREAD

**Issue by fengrunkai** [v2ray/v2ray-core#799]
因为要把v2ray升级，我们怎样才能把之前的设定config.json文件备份到被的电脑，然后升级后把config.json设置文件拷贝回来？我现在用的方法是用屏幕cut-and-paste方法。

不知道docker系统是能加入rcp，ssh，ftpd这一类的软件？那么我可以通过它们来实现remote copy function。

现在我使用的v3.4.

谢谢。

Eric

**Comment by DarienRaymond** [comment]
https://stackoverflow.com/questions/22049212/copying-files-from-docker-container-to-host

**Comment by fengrunkai** [comment]
谢谢您的链接，我知道怎样把container的东西拷出来。

非常感谢。
