### ISSUE TITLE
客户端socks协议启用password认证还是不能用

### ISSUE THREAD

**Issue by yuan78** [v2ray/v2ray-core#80]
客户端socks协议启用password认证还是不能用，报错如下：

V2Ray 1.7 (New Order) Custom
An unified platform for anti-censorship.
2016/02/05 19:28:54 [Warning]Point server started on port 1086
2016/02/05 19:29:01 [Warning]Socks: client doesn't support allowed any auth meth
ods.
2016/02/05 19:29:01 [Warning]Socks: client doesn't support allowed any auth meth
ods.
2016/02/05 19:29:01 [Warning]Socks: client doesn't support allowed any auth meth

我的客户端配置是这样的（截取关键部分）：

"inbound": {
    "protocol": "socks",
    "settings": {
      "auth": "password",
	   "accounts": [  
    {"user": "username", "pass": "password"}
  ],

到底哪里有问题，难道是VPS服务端也要做相应配置吗，如何配置呢？

**Comment by v2ray** [comment]
这种情况下，你的浏览器也需要配置 socks 协议的用户名和密码。部分浏览器（或插件）不支持这种方式，比如 SwitchyOmega。

**Comment by yuan78** [comment]
OK,明白了，现在看来这个只是本地的认证，我还以为是跟server之间又多了一道认证。
这种认证我觉得好像没有太大作用，谢谢！

**Comment by v2ray** [comment]
这是 socks 协议的一部分，从工具的角度来说，既然协议中提到了那就要支持。

对于 V2Ray 的客户端和服务器端通讯，只需要设置 id 和 alterId 两个值即可。详见[VMess 协议配置](https://github.com/v2ray/v2ray.github.io/wiki/%E5%8D%8F%E8%AE%AE%E5%88%97%E8%A1%A8#vmess-inbound--outbound)
