### ISSUE TITLE
v2ray 代理服务器拒绝访问

### ISSUE THREAD

**Issue by exosima** [v2ray/v2ray-core#802]
Please skip to the English section below if you don't write Chinese.

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
3.5
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
通过chrome上谷歌
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
代理服务器拒绝访问
4)  你期待看到的正确表现是怎样的？
正常浏览网页
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
```javascript
{
  "inbound": {
    "port": 16823, // 服务器监听端口
    "protocol": "vmess",    // 主传入协议
    "settings": {
      "clients": [
        {
          "id": "b831381d-6324-4d53-ad4f-8cda48b30811",  // 用户 ID，客户端与服务器必须相同
          "alterId": 64
        }
      ]
    }
  },
  "outbound": {
    "protocol": "freedom",  // 主传出协议
    "settings": {}
  }
}


    // 在这里附上服务器端配置文件
```

    客户端配置:
```javascript
    // 在这里附上客户端配置
```
{
  "inbound": {
    "port": 1080, // 监听端口
    "protocol": "socks", // 入口协议为 SOCKS 5
    "settings": {
      "auth": "noauth"  //socks的认证设置，noauth 代表不认证，由于 socks 通常在客户端使用，所以这里不认证
    }
  },
  "outbound": {
    "protocol": "vmess", // 出口协议
    "settings": {
      "vnext": [
        {
          "address": "xxx", // 服务器地址，请修改为你自己的服务器 ip 或域名
          "port": 16823,  // 服务器端口
          "users": [
            {
              "id": "b831381d-6324-4d53-ad4f-8cda48b30811",  // 用户 ID，必须与服务器端配置相同
              "alterId": 64 // 此处的值也应当与服务器相同
            }
          ]
        }
      ]
    }
  }
}
6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
```
    // 在这里附上服务器端日志
```没有

    客户端错误日志:
```没有
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
```
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

请预览一下你填的内容再提交。

**Comment by Gannti** [comment]
请在配置文件中添加 log 字段，并将 loglevel 改为 debug 以提供更详细的信息。

**Comment by exosima** [comment]
只有debug的
![default](https://user-images.githubusercontent.com/33896761/34466666-abeb31ac-ef16-11e7-99fa-bb10ba4d1dbe.PNG)
rcontent.com/33896761/34466666-abeb31ac-ef16-11e7-99fa-bb10ba4d1dbe.PNG)

**Comment by Gannti** [comment]
你的服务端配置文件设置的监听端口是 `16823`，而从 log 上来看客户端在向服务端的 `1236` 端口进行通信，请仔细检查客户端和服务端的端口设置是否一致。

**Comment by exosima** [comment]
-这是之前的我以为端口不对 就改了还是这样 k就不截图了

**Comment by exosima** [comment]
我就想请大佬帮我看下配置文件有没有 问题  没有的话我换个vps试试

**Comment by q158073378252010** [comment]
@exosima 服务器可能正在遭受DDOS 攻击。请联系vps服务商。

**Comment by exosima** [comment]
那我的配置文件有没有问题呢?

**Comment by exosima** [comment]
我vps上有个爬虫但是是单线程的应该没影响

**Comment by exosima** [comment]
真是vps问题无法ping通了 千万别买国内服务商太坑了

**Comment by Chandler-Lu** [comment]
你买的哪家vps。。。

**Comment by exosima** [comment]
dgc的 看它界面还以为是外国人看的想不到是国人
ip被gfw干扰都给我换
呵呵和中国奶粉一样知道自己信誉差就换个洋名字继续坑国人
用户买一定不贪便宜

**Comment by exosima** [comment]
不要脸

**Comment by exosima** [comment]
dgc的 看它界面还以为是外国人看的想不到是国人
ip被gfw干扰都给我换
呵呵和中国奶粉一样知道自己信誉差就换个洋名字继续坑国人
以后买一定不贪便宜
我买搬瓦工的了
不过这个软件我实在配置不起来 可能我智商低的缘故 而且我怀疑是gfw的人搞出来的(v2ray官网居然大陆可以直连)目前只是我怀疑不代表别人态度虽然是开源的但我真不懂go对我来说是黑盒 没黑这个软件的意思 openssl还被fbi留过心脏出血后门的
我就参照知乎的那篇文章用pysocks做了个梯子当然跟这个没法比
只可惜我不会安卓只能电脑用
就不开源了毕竟肉身在墙内我不靠编程吃饭

**Comment by exosima** [comment]
我说dgc不要脸大家不要误会

**Comment by exosima** [comment]
手机也是国产的卡成翔了 输入法还有问题
过完年就换三星
