### ISSUE TITLE
请教v2ray内如何设置某连接只能访问特定ip或者端口，其他的都blocked掉

### ISSUE THREAD

**Issue by laikitleung** [v2ray/v2ray-core#803]
默认是全部通过？

**Comment by xiaokangwang** [comment]
可以使用Rule来实现这个功能 https://www.v2ray.com/chapter_02/03_routing.html。
如果 outbound 是 blackhole 的话就是默认 block 掉。

您必须按照issue模版填写才能对具体的情况进行讨论。

**Comment by laikitleung** [comment]
routing里有先后次序吗？比如我在routing里先direct放行几个ip，后面如何blocked掉其他所有ip?支持通配符吗？

**Comment by xiaokangwang** [comment]
实际上是有顺序的，但是不建议根据这个进行配置，建议配置允许的走vmess/freedom Detour，剩下的都走默认的blackhole就可以

**Comment by laikitleung** [comment]
怎么设置默认走blackhole?

**Comment by xiaokangwang** [comment]
默认走outbound，如果outbound是blackhole就会默认走blackhole

**Comment by laikitleung** [comment]
还是不太理解，是outbound里加blocked的tag吗？然后routing放行部分ip? 比如下面这个应该怎么改
 "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
          ..............放行ip
          ],
          "outboundTag": "direct"
        }
      ]
    }

**Comment by xiaokangwang** [comment]
建议尝试一下这样
"outbound": {
"protocol": "blackhole",
"settings": {}
},
"outboundDetour": [
{
"protocol": "freedom",
"settings": {},
"tag": "direct"
}
],
"routing": {
"strategy": "rules",
"settings": {
"rules": [
{
"type": "field",
"ip": [
..............放行ip
],
"outboundTag": "direct"
}
]
}

**Comment by laikitleung** [comment]
我测试下，非常感谢

**Comment by laikitleung** [comment]
再请教，如果在这个基础上，另一个连接全部放行应该怎么改，比如socks限制访问指定ip，shadowsocks又全部放行

**Comment by fbion** [comment]
mark
