### ISSUE TITLE
ws doesn't work with proxySettings

### ISSUE THREAD

**Issue by GarrisonBaird** [v2ray/v2ray-core#807]
1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
`3.5 on both sides`
2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
`ss over ws over a parent proxy`
3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)
`Data will be sent to the server via the tag in proxySettings, and won't go through ws (according to client logs), getting some random characters when using curl to make a simple http request`
**It works if the proxySettings section is removed**

5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Server configuration:
```javascript
		{
			"tag": "*",
			"port": 80,
			"protocol": "shadowsocks",
			"settings": {
				"email": "*",
				"method": "*",
				"password": "*",
				"udp": false,
				"ota": false
			},
			"streamSettings": {
				"network": "ws",
				"security": "none",
				"wsSettings": {
					"path": "/*",
					"headers": {
						"Host": "*"
					}
				}
			}
		}
```

Client configuration:

```javascript
		{
			"tag": "*",
			"protocol": "shadowsocks",
			"settings": {
				"servers": [
					{
						"email": "*",
						"address": "*",
						"port": 80,
						"method": "*",
						"password": "*"
					}
				]
			},
			"streamSettings": {
				"network": "ws",
				"security": "none",
				"wsSettings": {
					"path": "/*",
					"headers": {
						"Host": "*"
					}
				}
			},
			"proxySettings": {
				"tag": "direct"
			}
		},
		{
			"tag": "direct",
			"protocol": "freedom"
		}
```

_And thanks for your hard working :heart:_

**Comment by nicholascw** [comment]
Hi. Sorry for our [documentation page](https://www.v2ray.com/en/configuration/overview.html) was not available in English by mistake, but according to this page, `streamSettings`would be omitted  if `proxySettings` appears.

**Comment by GarrisonBaird** [comment]
Thanks for your responding.
I do read Chinese though. Cause I only read the part of [传出代理](https://v2ray.com/chapter_03/outboundproxy.html), and didn't notice that little phrase in [文件格式](https://v2ray.com/chapter_02/01_overview.html), so I had no idea about it...
I suggest adding that notice to [传出代理](https://v2ray.com/chapter_03/outboundproxy.html), it should be more clear.

**Comment by GarrisonBaird** [comment]
BTW, I can help with translations :-)

**Comment by GarrisonBaird** [comment]
Found same issue here #783, maybe we should keep this issue open?
