### ISSUE TITLE
启用mKCP传输触发客户端防火墙端口扫描警报

### ISSUE THREAD

**Issue by laikitleung** [v2ray/v2ray-core#810]
小白请教使用简单配置使用时只要流量一大，就会触发端口扫描警报，而用kcptun却不会，何解？
 "streamSettings": {
      "network": "kcp",
	  "kcpSettings": {
        "uplinkCapacity": 10,
        "downlinkCapacity": 30,
        "header": {
          "type": "none"
        }
      } 
    }

**Comment by nicholascw** [comment]
Closed due to uncleared description.
