### ISSUE TITLE
 手机不安客户端，用自带VPN连接中转v2ray 服务器是否可行？

### ISSUE THREAD

**Issue by wulongji2016** [v2ray/v2ray-core#816]
目前很多应用商店无法下载客户端。特别是苹果手机。
因此个别情况下，采用手机无需安装客户端的方式也是有必要的。

苹果的浏览器和很多软件不支持socks代理。但是本身支持VPN。
线路图：1手机VPN------2中转服务器接受VPN -3转给中转服务器的V2ay --------4国外V2ray .
请问：
问题一：中转服务器在2和3处是否有配合工作的可能性？ 
问题二：中转服务器2处的VPN 需要端口转发给V2ray 即可么？ 或者有具体配置，请各位赐教！

**Comment by wulongji2016** [comment]
大家的苹果手机 怎么用的？

**Comment by nicholascw** [comment]
可以,在中转服务器上配置dokodemo-door并用IPTABLES把流量转入.详见手册.

**Comment by BenhoNNNN** [comment]
Mume(免费APP美区)

iOS 本地VPN隧道代理流量 >>socks5>>中转服务器>>VMESS>>墙外服务器>>FREE

缺点：iOS下类似的Mume、Wingy、Surge不支持Socks5 用户验证，中转服务器暴露在公网容易被扫描到socks端口。

**Comment by SquareFong** [comment]
> 大家的苹果手机 怎么用的？

下一个Shadowrocket的ipa安装包，用电脑版的PP助手装到手机里面去

**Comment by 5dao** [comment]
tun2socks,这个,就是你想要的

**Comment by troilus** [comment]
请问这个需求目前实现了吗？


> 目前很多应用商店无法下载客户端。特别是苹果手机。
> 
> 因此个别情况下，采用手机无需安装客户端的方式也是有必要的。
> 
> 
> 
> 苹果的浏览器和很多软件不支持socks代理。但是本身支持VPN。
> 
> 线路图：1手机VPN------2中转服务器接受VPN -3转给中转服务器的V2ay --------4国外V2ray .
> 
> 请问：
> 
> 问题一：中转服务器在2和3处是否有配合工作的可能性？ 
> 
> 问题二：中转服务器2处的VPN 需要端口转发给V2ray 即可么？ 或者有具体配置，请各位赐教！
> 
> 
> 
>
