### ISSUE TITLE
V2Ray的Websocket套上CDN无法访问

### ISSUE THREAD

**Issue by tkkeni** [v2ray/v2ray-core#817]
你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
3.6

    你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

V2Ray的Websocket模式使用CDN加速

    你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

已配置好nginx及v2ray，未配置TLS，域名为xxx.tk及有CDN加速的cdn.xxx.tk都能正常访问到网站，v2ray可以使用服务器地址填xxx.tk可以正常科学上网，但cdn.xxx.tk却无法连接

    你期待看到的正确表现是怎样的？

和使用访问xxx.tk一样，能够正常科学上网

    请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
v2ray:
{
  "inbound": {
    "port": 10000,
    "listen":"127.0.0.1",
    "protocol": "vmess",
    "settings": {
	  "udp": true,
      "clients": [
        {
          "id": "686ff8a8-2624-42f3-8cf0-0cb1d56b7e4d",
          "alterId": 64
        }
      ]
    },
    "streamSettings":{
      "network":"ws",
	  "security": "auto",
      "wsSettings": {
	  "connectionReuse": true,
      "path": "/ws"
      }
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  }
}

    客户端配置:

  "inbound": {
    "port": 1080,
    "listen": "0.0.0.0",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "127.0.0.1",
      "clients": null
    },
    "streamSettings": null
  },
  "outbound": {
    "tag": "agentout",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "cdn.xxx.tk",
          "port": 80,
          "users": [
            {
              "id": "686ff8a8-2624-42f3-8cf0-0cb1d56b7e4d",
              "alterId": 64,
              "security": "none"
            }
          ]
        }
      ]
    },

    请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:

error文件中只有v2ray start

    客户端错误日志:

[Warning]: App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: failed to find an available destination > Retry: [Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (ws://cdn.xxx.tk/ws): 400 Bad Request > websocket: bad handshake] > Retry: all retry attempts failed

    请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

日志为空

    其它相关的配置文件（如 Nginx）和相关日志。

nginx:
    location /ws {
        access_log   off;
	proxy_intercept_errors on;
        proxy_redirect off;
        proxy_pass http://127.0.0.1:10000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
    }

**Comment by ygp987** [comment]
客户端也得加上 websocket 的配置
![image](https://user-images.githubusercontent.com/6169889/35042219-b2d05aac-fbc2-11e7-8920-5a63acfe42ac.png)

**Comment by tkkeni** [comment]
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": ""
  },
  "inbound": {
    "port": 1080,
    "listen": "0.0.0.0",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "127.0.0.1",
      "clients": null
    },
    "streamSettings": null
  },
  "outbound": {
    "tag": "agentout",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "cdn.xxx.tk",
          "port": 80,
          "users": [
            {
              "id": "686ff8a8-2624-42f3-8cf0-0cb1d56b7e4d",
              "alterId": 64,
              "security": "none"
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "security": "",
      "tcpSettings": null,
      "kcpSettings": null,
      "wsSettings": {
        "connectionReuse": true,
        "path": "/ws",
        "headers": null
      }
    },
    "mux": {
      "enabled": false
    }
  },
  "inboundDetour": null,
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {
        "response": null
      },
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "blockout"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": null,
          "outboundTag": "direct",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "domain": null
        }
      ]
    }
  }
}
完整客户端配置如上，无法访问

**Comment by DarienRaymond** [comment]
请确认你的 CDN 支持 WebSocket，并不是所有的 CDN 都支持这一特性。

**Comment by tkkeni** [comment]
已解决，的确是CDN的问题，我忘记打开websocket了。

**Comment by Chankin026** [comment]
套cf的cdn dns中云朵要打开(橙色) +Crypto中ssl打开+ Network中websocks也要打开 就好了
