### ISSUE TITLE
V2RAY 利用dokodemo-door 实现透明代理无法使用Google Play

### ISSUE THREAD

**Issue by 5high** [v2ray/v2ray-core#819]
Please skip to the English section below if you don't write Chinese.

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

V2Ray v3.6 (die Commanderin) 20180112
An unified platform for anti-censorship

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

利用dokodemo-door 实现透明代理
```bash
iptables -t nat -N V2RAY
iptables -t nat -A V2RAY -d serverip -j RETURN
iptables -t nat -A V2RAY -d 172.28.0.0/16 -j RETURN
iptables -t nat -A V2RAY -d 172.29.0.0/16 -j RETURN
iptables -t nat -A V2RAY -d 172.30.0.0/16 -j RETURN
iptables -t nat -A V2RAY -d 192.168.0.0/24 -j RETURN
iptables -t nat -A V2RAY -d 192.168.1.0/24 -j RETURN
iptables -t nat -A V2RAY -d 192.168.89.0/24 -j RETURN
iptables -t nat -A V2RAY -d 192.168.88.0/24 -j RETURN
iptables -t nat -A V2RAY -d 192.168.86.0/24 -j RETURN
iptables -t nat -A V2RAY -p tcp -j REDIRECT --to-ports 12345
iptables -t nat -A PREROUTING -p tcp -j V2RAY
#iptables -t nat -A OUTPUT -p tcp -j V2RAY
ip rule add fwmark 0x01/0x01 table 100
ip route add local 0.0.0.0/0 dev lo table 100
iptables -t mangle -N V2RAY
iptables -t mangle -A V2RAY -p udp -j TPROXY --on-port 12345 --tproxy-mark 0x01/0x01
iptables -t mangle -A PREROUTING -j V2RAY
iptables -t mangle -I V2RAY -d serverip -j RETURN
iptables -t mangle -I V2RAY -d 114.114.114.114 -j RETURN
iptables -t mangle -I V2RAY -d 192.168.0.0/16 -j RETURN
iptables -t mangle -I V2RAY -d 172.28.0.0/16 -j RETURN
iptables -t mangle -I V2RAY -d 172.29.0.0/16 -j RETURN
iptables -t mangle -I V2RAY -d 172.30.0.0/16 -j RETURN
```
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

安卓下Google Play无法打开，电脑端可以开http://play.google.com

4)  你期待看到的正确表现是怎样的？

希望能正常使用Google Play APP 在安卓设备上。

5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
```json
{
  "log" : {
    "loglevel": "debug"
  },
  "inbound": {
    "port": 8866,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "UUID1",
          "level": 1,
          "alterId": 64
        },
	{
          "id": "UUID2",
          "level": 1,
          "alterId": 64
        }
      ],
      "detour": {
        "to": "dynamic_port"
      }
    }
  },
  "outbound": {
    "protocol": "freedom",  
    "settings": {}
  },
  "inboundDetour": [
    {
      "protocol": "vmess",
      "port": "20000-30000",
      "tag": "dynamic_port",
      "settings": {},
      "allocate": {
        "strategy": "random",
        "concurrency": 6,
        "refresh": 5
      }
    }
  ],
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}

```
    客户端配置:
```json
{
  "log": {
    "loglevel": "debug"
  },
  "inbound": {
    "port": 1080,
    "protocol": "socks",
    "settings": {
      "auth": "noauth"
    }
  },

  "inboundDetour": [
     {
         "domainOverride":["tls","http"],
         "port":12345,
         "protocol":"dokodemo-door",
         "settings":{
             "network": "tcp,udp",
             "followRedirect": true
         }
     }
  ],

  "outbound": {
    "tag":"proxy",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "SERVERIP",
          "port": 8866,
          "users": [
            {
              "id": "UUID",
              "alterId": 64
            }
          ]
        }
      ]
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
	{
          "type": "field",
          "domain": [
          	"www.google.com.hk"
          ],
          "outboundTag": "proxy"
        },
        {
          "type": "field",
	  "domian": [
		"womai.com",
		"jd.com",
		"taobao.com",
		"alipay.com",
		"googleapis.cn",
		"ggpht.cn"
		],
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        }
      ]
    }
  }
}
```
6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:

无法取得错误位置

    客户端错误日志:

无法取得错误位置

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
```
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

请预览一下你填的内容再提交。

如果你已经填完上面的问卷，请把下面的英文部份删除，再提交 Issue。

**Comment by nicholascw** [comment]
尝试补全dns部分的配置?

**Comment by 5high** [comment]
能给个补全的例子吗？

2018年1月19日 12:30，"Nicholas Wang" <notifications@github.com>写道：

**Comment by DarienRaymond** [comment]
路由的direct部分写法是不合理的，请仔细阅读[路由的介绍](https://www.v2ray.com/chapter_02/03_routing.html)。

**Comment by 5high** [comment]
//下面是客户端错误日志，192.168.88.167是要访问Google Play的设备。
//经过多次实验发现，如果重启一下服务器端的V2RAY，客户端Google Play APP可以打开一两个页面，之后就会不工作，再重启服务器V2ray还可以再开2个页面。

2018/01/19 22:12:34 [Info]: App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > context canceled
2018/01/19 22:12:34 [Debug]: Proxy|Dokodemo: processing connection from: 192.168.88.167:38930
2018/01/19 22:12:34 [Info]: App|Dispatcher: default route for tcp:149.154.175.50:443
2018/01/19 22:12:34 [Info]: Transport|Internet|TCP: dialing TCP to tcp:172.28.58.10:8866
2018/01/19 22:12:35 [Info]: App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > context canceled
2018/01/19 22:12:35 [Info]: App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > context canceled
2018/01/19 22:12:36 [Info]: Proxy|VMess|Outbound: tunneling request to tcp:149.154.175.50:443 via tcp:172.28.58.10:8866
2018/01/19 22:12:51 [Debug]: Proxy|Dokodemo: processing connection from: 192.168.88.167:38932
2018/01/19 22:12:52 [Info]: App|Dispatcher: default route for tcp:149.154.175.50:443
2018/01/19 22:12:52 [Info]: Transport|Internet|TCP: dialing TCP to tcp:172.28.58.10:25296
2018/01/19 22:12:52 [Info]: Proxy|VMess|Outbound: tunneling request to tcp:149.154.175.50:443 via tcp:172.28.58.10:25296
2018/01/19 22:13:05 [Info]: App|Proxyman|Outbound: failed to process outbound traffic > Proxy|Freedom: connection ends > context canceled
2018/01/19 22:13:05 [Info]: App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > context canceled
2018/01/19 22:13:07 [Info]: App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > context canceled
2018/01/19 22:13:07 [Info]: App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > context canceled
2018/01/19 22:13:07 [Info]: App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > context canceled
2018/01/19 22:13:07 [Info]: App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport response > io: read/write on closed pipe
2018/01/19 22:13:07 [Info]: App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > context canceled
2018/01/19 22:13:07 [Info]: App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > context canceled
2018/01/19 22:13:09 [Info]: App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Proxy|Dokodemo: failed to transport response > write tcp 192.168.88.162:12345->192.168.88.167:38932: write: broken pipe
2018/01/19 22:13:09 [Info]: App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: connection ends > context canceled
2018/01/19 22:13:13 [Debug]: Proxy|Dokodemo: processing connection from: 192.168.88.167:38936
2018/01/19 22:13:13 [Info]: App|Dispatcher: default route for tcp:149.154.175.50:443
2018/01/19 22:13:13 [Info]: Transport|Internet|TCP: dialing TCP to tcp:172.28.58.10:8866
2018/01/19 22:13:13 [Info]: Proxy|VMess|Outbound: tunneling request to tcp:149.154.175.50:443 via tcp:172.28.58.10:8866

**Comment by p4insh11** [comment]
我遇到的问题与你类似，比如安卓在4G下用NG没问题，但是局域网开了透明代理以后，PC可以，安卓不行，打开play.google.com和软件都不行，目测遇到了QUIC的问题，chrome关闭了quic

**Comment by 5high** [comment]
可是安卓手机上没法关闭quic吧？

2018年2月26日 08:55，"p4insh11" <notifications@github.com>写道：

**Comment by p4insh11** [comment]
尝试了一下，确实是quic的原因，我配置和你基本类似，全透明转发到vps上，安卓的网页chrome关闭quic以后正常，但是app里面还是不行，我比较好奇的是为什么4G模式用NG下可以正常，但是透明代理会失败，UDP肯定是能正常工作的

**Comment by 5high** [comment]
NG会不会有相关QUIC转换的功能？

2018年2月26日 09:12，"p4insh11" <notifications@github.com>写道：

**Comment by 5high** [comment]
这个问题已经解决，解决办法如下:
客户端的inbound 里去注释部分：
"inboundDetour": [
     {
         "domainOverride":["tls","http"],
         "port":12345,
         "protocol":"dokodemo-door",
         "settings":{
             "network": "tcp,udp", // 此行去掉即可全局开启QUIC
             "followRedirect": true
         }
     }
  ],

我猜测可能"network": "tcp,udp"这里的udp不包含QUIC，大家可以参考我的办法来实现QUIC透明代理。

**Comment by p4insh11** [comment]
有意思，难道可以默认转发全局协议，quic只是在测试没写出来？
我回去也试试，另外我的设备是在升级以后才出现这个问题，之前同配置一直正常，难道这个位置出了bug，之前的版本忘记版本号了，不然就回退了

**Comment by 5high** [comment]
我不动代码，我猜才也许是想做
DomainOverride加入QUIC支持，然后把QUIC独立出来了，希望可以从QUIC里嗅探域名，但是功能又没有做完所以造成了这个问题，不管怎样吧，你试试看我这个方法是否有效，如果有效在这个ISSUE上回复一下，然后我就关闭这个ISSUE了。

在 2018年2月27日 下午3:53，p4insh11 <notifications@github.com>写道：

**Comment by p4insh11** [comment]
感谢分享，删掉以后测试正常，quic工作正常

**Comment by caonimac** [comment]
感谢5high 同学。
以前用redsocks转发到inbound的socks端口，一切正常 。
昨天改用dokodemo-door代替redsocks，youtube就无法用了，netstat -nap | grep v2ray发现到一些Google 443的端口没有转发，直连了。
按照5high同学的把 dokodemohdoor里的"network": "tcp,udp"删除或注释掉就ok了。

**Comment by caonimac** [comment]
dokodemo-door比redsocks和redsocks2都好！强烈推荐。

**Comment by p4insh11** [comment]
@5high 该close了

**Comment by wangmice** [comment]
遇到同样的问题，应该写入文档里，不然根据教程配置还是会遇到
