### ISSUE TITLE
多用户代理问题

### ISSUE THREAD

**Issue by wanzhiyu** [v2ray/v2ray-core#829]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v2ray-core-3.6
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
多用户代理

3) 遇到的问题
（1）在vmess协议文档中我看到这么一句话：“email: 用户邮箱地址，用于区分不同用户的流量。”
     请问email一定要严格按照邮箱的格式（比如abc@outlook.com）填写吗？我已经尝试过随便用一个字符串（比如abc）实验，发现也可以成功实现代理，请问有什么实质区别吗？
（2）现在多用户流量统计功能已经开发完成了吗，谢谢 :-)

**Comment by DarienRaymond** [comment]
1) 没有，只是建议使用邮件地址。这个配置项不会对数据传输有影响。

2) 正在。

**Comment by beyondkmp** [comment]
流量统计的还在开发吗？ @DarienRaymond
