### ISSUE TITLE
Support VMess over Websocket

### ISSUE THREAD

**Issue by xiaokangwang** [v2ray/v2ray-core#83]
如果支持通过Websocket协议连接就可以在云服务上部署，减少使用成本。

目前v2ray必须运行在自己完全控制的VPS上，也就是必须有独立的TCP端口。

如heroku等云服务上无法部署v2ray。

目前很多云服务是免费的，可以显著降低使用门槛，避免了支付环节的困扰。

**Comment by v2ray** [comment]
计划中，但需要注意的是，Heroku [明确规定](https://www.heroku.com/policy/aup)了不能运行代理软件：

> Prohibited Actions
> 20. Use the Service to operate an "open proxy" or any other form of Internet proxy service that is capable of forwarding requests to any End User or third party-supplied Internet host;

**Comment by xiaokangwang** [comment]
谢谢～
Heroku只是对服务的类型举例， [DotCloud](https://www.dotcloud.com/)，[cloudControl](https://www.cloudcontrol.com/)都提供相同的服务但没有类似的限制。

**Comment by v2ray** [comment]
Added.

**Comment by tkisme** [comment]
BTW how to configure.Any example?
