### ISSUE TITLE
Shadowsocks 客户端连接 V2ray 服务端时，ip地址被作为域名解析

### ISSUE THREAD

**Issue by zw373** [v2ray/v2ray-core#832]
概述：使用 shadowsocks 客户端，通过shadowsocks协议链接v2ray服务端时，ip地址被作为域名进行处理。具体表现为，ip 地址匹配路由规则中的domain规则而忽略所有ip规则，从log中查到路由策略为 IPIfNonMatch 时，v2ray会将ip地址作为域名尝试解析。v2ray 的客户端经测试无此bug.

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

    服务端：v2.39, v3.6 均有此bug
    客户端：shadowsocks 客户端 MacOS ShadowsocksX 2.6.3, ShadowsocksX-NG 1.7.0(1) 均有此bug

2)  你的使用场景是什么？

    使用 ip 地址而非域名的 http 协议 GET 请求。如 http://58.205.196.6/

3)  你看到的不正常的现象是什么？

    ip 地址被作为域名处理，匹配域名的规则，忽略ip的规则，并尝试进行域名解析。如果解析失败，使用默认 Outbound

4)  你期待看到的正确表现是怎样的？
    ip 地址被视为 ip 地址，匹配 ip 的规则

5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:

传入配置：
```javascript
    'inboundDetour': [{'port': 3680,
       'protocol': 'shadowsocks',
       'settings': {'email': '****',
          'level': 1,
          'method': 'aes-128-cfb',
          'password': '****',
          'udp': True}, ...]
```

路由配置：

```javascript
      'routing': {'settings': {'domainStrategy': 'IPIfNonMatch'}, rules:[...]}
```

客户端配置:  shadowsocks 客户端，ip, port, 加密 根据上述配置，其余均为默认设定。

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端日志:
```
2018/01/29 23:39:04 [Info]: Proxy|Shadowsocks: tunnelling request to tcp:58.205.196.6:80
2018/01/29 23:39:04 [Info]: App|Router: looking for IP for domain: 58.205.196.6
```

7) 8） 不适用
请预览一下你填的内容再提交。

**Comment by DarienRaymond** [comment]
本质上这是 Shadowsocks 客户端的问题，Shadowsocks 协议规定了目标地址的类型，当客户端把一个 IP 地址标记为域名传进来时，服务器端就按指定的类型进行传输的。

当然服务器端可以不信任客户端所指定的类型，对目标地址重新解析。

**Comment by Cwek** [comment]
应该是ss客户端的bug？把ip数据和域名标识发过来，然后v2把ip当成域名处理？
