### ISSUE TITLE
DomainOverride加入QUIC支持

### ISSUE THREAD

**Issue by liberal-boy** [v2ray/v2ray-core#834]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
3.6

虽然目前QUIC还未被大规模部署，Google旗下大部分网站已经启用QUIC，导致现有的DomainOverride无法满足部分domain规则分流的需求，建议DomainOverride加入QUIC支持。

**Comment by caonimac** [comment]
youteube根本打不开，当开启udp转发。啊啊啊

**Comment by DarienRaymond** [comment]
Kamino closed and cloned this issue to v2ray/Planning
