### ISSUE TITLE
能资瓷 shadowsocks 服务端是坠吼滴！

### ISSUE THREAD

**Issue by renzhn** [v2ray/v2ray-core#84]
怎么能不资瓷 shadowsocks 服务端呢？现有的 ss 服务那么多，就算是自己的服务器，全部装一套服务端也很费劲

**Comment by laosb** [comment]
Shadowsocks 没有足够的安全性。V2Ray 在设计上就是为了避免踩 Shadowsocks 的坑。

话说回来，Shadowsocks 支持作者已经在做了。

装服务端费解的正解是 Dockerized Deployment，不知道作者有没有考虑。

**Comment by renzhn** [comment]
@laosb ss安全性问题见仁见智，我自己使用没遇到干扰。况且全国出口流量如此之大，简单的流量混淆足够了吧。
个人不喜欢在VPS上装docker，感觉太重量级了。服务端轻量为好，ss都可以在路由器上面运行。

**Comment by renzhn** [comment]
shadowsocks有go语言版本的：shadowsocks-go
看起来作者喜欢所有东西自己实现一套，其实我觉得用别人写的也没什么不好

**Comment by laosb** [comment]
gfw 都动用机器学习了，这个问题就不好讲了。

Docker 不算太重量级吧？能够很大程度上减轻升级扩容的负担，这个应该是很重要的。

> On Feb 16 2016, at 1:55 pm, Ren Zhen &lt;notifications@github.com&gt; wrote:  

>

> [@laosb](https://github.com/laosb)
ss安全性问题见仁见智，我自己使用没遇到干扰。况且全国出口流量如此之大，简单的流量混淆足够了吧。  
个人不喜欢在VPS上装docker，感觉太重量级了。服务端轻量为好，ss都可以在路由器上面运行。

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/v2ray
/v2ray-core/issues/84#issuecomment-184533042).![](https://github.com/notificat
ions/beacon/ACbWbfMKt5tPCOFq2Ed8nA43Ief5Z5KGks5pkrFkgaJpZM4Ha3Sr.gif)

**Comment by renzhn** [comment]
@laosb 在ss没有被彻底屏蔽（个人感觉不大可能）以及目前ss是主流的现状改变之前，我觉得支持ss服务端还是很有必要的

**Comment by v2ray** [comment]
https://www.v2ray.com/zh_cn/chapter_02/02_protocols.html#shadowsocks

请仔细阅读文档

**Comment by renzhn** [comment]
@v2ray 理解出了点偏差，我的意思是作为客户端可以连接现有的ss服务端

**Comment by v2ray** [comment]
ss 的客户端已经很丰富了，Windows、iOS、Android 都有客户端，Mac OS X 可以用 python 版的，V2Ray 无意在这方面与 ss 竞争。
