### ISSUE TITLE
路由配置未生效，无法直连国内地址

### ISSUE THREAD

**Issue by realmhorde** [v2ray/v2ray-core#841]
Please skip to the English section below if you don't write Chinese.

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v3.6版

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
win10+chrome，指定浏览器代理地址（而非使用switch插件规则）时

3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
"routing"即路由配置没有生效

4)  你期待看到的正确表现是怎样的？
访问国内地址和私有地址时使用直连

5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
```javascript
    // 在这里附上服务器端配置文件
```

    客户端配置:
```javascript
{
  "log": {
    "loglevel": "debug"
  },
  "inbound": {
    "domainOverride":["http", "tls"],
    "port": 1080,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "my_vps",
          "port": myport,
          "users": [
            {
              "id": myid,
              "alterId": 64
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "tcp",
      "security": "tls"
    }
  },
    "mux": {
      "enabled": true
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "domain": [
            "geosite:cn"
          ],
          "ip": [
            "geoip:cn",
            "geoip:private"
          ],
          "outboundTag": "direct"
        }
      ]
    }
  }
}
```

注：当发现未生效后我尝试配置过chinasites和chinaip，但依旧未能正常工作，访问日志相同
 "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
           "type":"chinaip",
           "outboundTag":"direct"
        }
      ]
    }
  }

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
```
    // 在这里附上服务器端日志
```

    客户端错误日志:
2Ray v3.6 (die Commanderin) 20180112
An unified platform for anti-censorship.
2018/02/04 10:09:15 [Debug]: App|Proxyman|Inbound: creating stream worker on 127.0.0.1:1080
2018/02/04 10:09:15 [Info]: Transport|Internet|TCP: listening TCP on 127.0.0.1:1080
2018/02/04 10:09:15 [Warning]: Core: V2Ray started
2018/02/04 10:09:20 [Info]: Proxy|Socks: TCP Connect request to tcp:ss1.baidu.com:443
2018/02/04 10:09:20 [Info]: Proxy|Socks: TCP Connect request to tcp:ss1.baidu.com:443
2018/02/04 10:09:20 [Info]: Proxy|Socks: TCP Connect request to tcp:ss1.baidu.com:443
2018/02/04 10:09:20 [Info]: App|Dispatcher: default route for tcp:ss1.baidu.com:443
2018/02/04 10:09:20 [Info]: Transport|Internet|TCP: dialing TCP to tcp:my_vps
2018/02/04 10:09:20 [Info]: Proxy|Socks: TCP Connect request to tcp:ss1.baidu.com:443
2018/02/04 10:09:20 [Info]: App|Dispatcher: default route for tcp:ss1.baidu.com:443
2018/02/04 10:09:20 [Info]: Transport|Internet|TCP: dialing TCP to tcp:my_vps
2018/02/04 10:09:20 [Info]: Proxy|Socks: TCP Connect request to tcp:ss1.bdstatic.com:443
2018/02/04 10:09:20 [Info]: App|Dispatcher: default route for tcp:ss1.bdstatic.com:443
2018/02/04 10:09:20 [Info]: Transport|Internet|TCP: dialing TCP to tcp:my_vps
2018/02/04 10:09:20 [Info]: Proxy|Socks: TCP Connect request to tcp:www.baidu.com:443
2018/02/04 10:09:20 [Info]: App|Dispatcher: default route for tcp:www.baidu.com:443
2018/02/04 10:09:20 [Info]: Transport|Internet|TCP: dialing TCP to tcp:my_vps
2018/02/04 10:09:20 [Info]: Proxy|Socks: TCP Connect request to tcp:www.baidu.com:443
2018/02/04 10:09:20 [Info]: Proxy|Socks: TCP Connect request to tcp:www.baidu.com:443
2018/02/04 10:09:20 [Info]: Proxy|Socks: TCP Connect request to tcp:www.baidu.com:443
2018/02/04 10:09:20 tcp:127.0.0.1:10594 accepted tcp:ss1.baidu.com:443
2018/02/04 10:09:20 tcp:127.0.0.1:10595 accepted tcp:ss1.baidu.com:443
2018/02/04 10:09:20 tcp:127.0.0.1:10596 accepted tcp:ss1.baidu.com:443
2018/02/04 10:09:20 tcp:127.0.0.1:10597 accepted tcp:ss1.baidu.com:443
2018/02/04 10:09:20 tcp:127.0.0.1:10598 accepted tcp:ss1.bdstatic.com:443
2018/02/04 10:09:20 tcp:127.0.0.1:10609 accepted tcp:www.baidu.com:443
2018/02/04 10:09:20 tcp:127.0.0.1:10610 accepted tcp:www.baidu.com:443
2018/02/04 10:09:20 tcp:127.0.0.1:10611 accepted tcp:www.baidu.com:443
2018/02/04 10:09:20 tcp:127.0.0.1:10612 accepted tcp:www.baidu.com:443
2018/02/04 10:09:20 tcp:127.0.0.1:10613 accepted tcp:www.baidu.com:443
2018/02/04 10:09:20 tcp:127.0.0.1:10583 accepted tcp:www.baidu.com:443
2018/02/04 10:09:20 tcp:127.0.0.1:10584 accepted tcp:sp0.baidu.com:443
2018/02/04 10:09:20 tcp:127.0.0.1:10585 accepted tcp:sp0.baidu.com:443
2018/02/04 10:09:20 tcp:127.0.0.1:10586 accepted tcp:sp0.baidu.com:443
2018/02/04 10:09:20 tcp:127.0.0.1:10587 accepted tcp:sp0.baidu.com:443
2018/02/04 10:09:20 tcp:127.0.0.1:10588 accepted tcp:sp0.baidu.com:443
2018/02/04 10:09:20 [Info]: Proxy|VMess|Outbound: tunneling request to tcp:ss1.baidu.com:443 via tcp:my_vps
2018/02/04 10:09:20 [Info]: Proxy|VMess|Outbound: tunneling request to tcp:ss1.baidu.com:443 via tcp:my_vps
2018/02/04 10:09:20 [Info]: Proxy|VMess|Outbound: tunneling request to tcp:ss1.bdstatic.com:443 via tcp:my_vps
2018/02/04 10:09:20 [Info]: Proxy|VMess|Outbound: tunneling request to tcp:www.baidu.com:443 via tcp:my_vps
2018/02/04 10:09:20 [Info]: Proxy|VMess|Outbound: tunneling request to tcp:www.baidu.com:443 via tcp:my_vps
2018/02/04 10:09:20 [Info]: Proxy|VMess|Outbound: tunneling request to tcp:ss1.baidu.com:443 via tcp:my_vps
2018/02/04 10:09:20 [Info]: Proxy|VMess|Outbound: tunneling request to tcp:www.baidu.com:443 via tcp:my_vps
2018/02/04 10:09:20 [Info]: Proxy|VMess|Outbound: tunneling request to tcp:sp0.baidu.com:443 via tcp:my_vps
2018/02/04 10:09:20 [Info]: Proxy|VMess|Outbound: tunneling request to tcp:ss1.bdstatic.com:443 via tcp:my_vps
2018/02/04 10:09:20 [Info]: Proxy|VMess|Outbound: tunneling request to tcp:ss1.bdstatic.com:443 via tcp:my_vps
2018/02/04 10:09:20 [Info]: Proxy|VMess|Outbound: tunneling request to tcp:www.baidu.com:443 via tcp:my_vps
2018/02/04 10:09:20 [Info]: Proxy|VMess|Outbound: tunneling request to tcp:sp0.baidu.com:443 via tcp:my_vps
2018/02/04 10:09:20 [Info]: Proxy|VMess|Outbound: tunneling request to tcp:www.baidu.com:443 via tcp:my_vps
2018/02/04 10:09:20 [Info]: Proxy|VMess|Outbound: tunneling request to tcp:www.baidu.com:443 via tcp:my_vps
2018/02/04 10:09:20 [Info]: Proxy|VMess|Outbound: tunneling request to tcp:sp1.baidu.com:443 via tcp:my_vps
2018/02/04 10:09:20 [Info]: Proxy|VMess|Outbound: tunneling request to tcp:ss2.baidu.com:443 via tcp:my_vps
2018/02/04 10:09:20 [Info]: Proxy|VMess|Outbound: tunneling request to tcp:ss1.baidu.com:443 via tcp:my_vps
2018/02/04 10:09:20 [Info]: Proxy|VMess|Outbound: tunneling request to tcp:sp0.baidu.com:443 via tcp:my_vps
2018/02/04 10:09:22 [Info]: Proxy|Socks: TCP Connect request to tcp:www.baidu.com:443
2018/02/04 10:09:22 tcp:127.0.0.1:10645 accepted tcp:www.baidu.com:443
2018/02/04 10:09:22 [Info]: App|Dispatcher: default route for tcp:www.baidu.com:443
2018/02/04 10:09:22 [Info]: Transport|Internet|TCP: dialing TCP to tcp:my_vps
2018/02/04 10:09:22 [Info]: Proxy|VMess|Outbound: tunneling request to tcp:www.baidu.com:443 via tcp:my_vps

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
```
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

请预览一下你填的内容再提交。

如果你已经填完上面的问卷，请把下面的英文部份删除，再提交 Issue。

**Comment by liberal-boy** [comment]
同一个field中规则间是与关系，也就是连接必须同时满足domain和ip条件才会走direct，通常不建议这么写，应该采用或关系。

**Comment by DarienRaymond** [comment]
同上。

**Comment by realmhorde** [comment]
分开写成这样之后依旧走了代理而非直连

 "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "domain": [
            "geosite:cn"
          ],
          "outboundTag":"direct"
        },
        {
           "type":"field",
          "ip": [
            "geoip:cn",
            "geoip:private"
          ],
           "outboundTag":"direct"
        }
      ]
    }
  }

而且之前也有说过，即便是用chinasites和chinaip的老方法，依旧是走代理出去的。。

**Comment by realmhorde** [comment]
已自行解决。。用vscode打开配置文件后发现多了个},

**Comment by MakerFace** [comment]
> 同一个field中规则间是与关系，也就是连接必须同时满足domain和ip条件才会走direct，通常不建议这么写，应该采用或关系。

太感谢了哥，调了一晚上才知道原来是与的关系，我说怎么一直走代理
