### ISSUE TITLE
如何编辑 geoip.dat

### ISSUE THREAD

**Issue by hxcloud** [v2ray/v2ray-core#847]
所处网络环境特殊，需要编辑国内域名白名单。（根本不会GO语言...

如果有人能为我编译一个没有任何白名单的geoip.dat，将会感激不尽。

**Comment by Cwek** [comment]
能不能允许设置配置一个纯文本的路径，每行按照route对域名的解释规则编写域名判断式。v2定时或固定读取这个文件来生成判断语句块？

**Comment by hxcloud** [comment]
我知道需要编辑 geoip.dat，用 VS Code 打开能看到部分内容 但是有大量的乱码。所以不太清楚应该如何编辑。群里有人说用 golang去编译，但是对于一门完全陌生的语言我真的不会用。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: eycorsican<mailto:notifications@github.com>
发送时间: 2018年2月6日 3:47
收件人: v2ray/v2ray-core<mailto:v2ray-core@noreply.github.com>
抄送: 惶心<mailto:imhx233@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [v2ray/v2ray-core] 如何编辑 geoip.dat (#847)


如果是域名的话，应该要编辑 geosite.dat。

我插个关于 geosite.dat 的事情，现在代码的实现是启动时解释成 domain 规则，然后全部加载到内存里面，这个方式对一些内存比较吃紧的环境，比如 iOS，不是很友好。有一个做法是设计一种数据结构以及算法，然后在运行时动态去 geosite.dat 文件当中做搜索，比如像这种：http://maxmind.github.io/MaxMind-DB/，这样可以减少不少内存使用。

对于 geoip.dat，现在 Kitsunebi 实现 GEOIP 规则的做法就是类似这样。

如果这样实现了，然后在v2ctl里加个格式转换功能，就可以满足上面提到的需求了。

―

**Comment by DarienRaymond** [comment]
@eycorsican 有需求的话可以去 [v2ray/planning](https://github.com/v2ray/planning) 里提一个 issue。不过对于 domain 规则并不容易实现基于文件的搜索。

geosite 的源码在这里：https://github.com/v2ray/ext/blob/master/tools/geosites/cn.go

**Comment by Flysky12138** [comment]
> @eycorsican 有需求的话可以去 [v2ray/planning](https://github.com/v2ray/planning) 里提一个 issue。不过对于 domain 规则并不容易实现基于文件的搜索。
> 
> geosite 的源码在这里：https://github.com/v2ray/ext/blob/master/tools/geosites/cn.go

地址不存在了

**Comment by kslr** [comment]
@Flysky12138 https://github.com/v2ray/geoip
