### ISSUE TITLE
自动安装的 如何让v2ray在服务端后台运行

### ISSUE THREAD

**Issue by jameseroyi** [v2ray/v2ray-core#85]
如题  我是用脚本自动安装的 想将脚下 如恶化让v2ray在服务端自动运行

**Comment by v2ray** [comment]
什么系统？

Debian 8 / Ubuntu 15.04 / CentOS 7 用 systemctl start v2ray 就可以运行，重启之后也会自动运行
Debian 7 / Ubuntu 14.04 用 service v2ray start，重启之后也会自动运行

**Comment by jameseroyi** [comment]
好的  知道啦  感谢付出
2016年2月16日 21:18，"Darien Raymond" <notifications@github.com>写道：

**Comment by VioletSakura777** [comment]
windows server的呢，，用什么命令
