### ISSUE TITLE
客户端IP段 如何正则表示

### ISSUE THREAD

**Issue by wumingshi0531** [v2ray/v2ray-core#853]
Please skip to the English section below if you don't write Chinese.

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v2ray-v3.6-windows-64

请教一个问题， IP配置区，这下面一段如何用正则表示 任意数字.任意数字.任意数字.任意数字

我是想利用代码的运行顺序来像SwitchyOmega插件一样实现需要代理的设置域名，不需要的直接直连
我现在已经配置成功域名区了   IP区不行   该 怎么 用正则或者其他表示所有 IP段

"type": "field",
          "port": null,
          "outboundTag": "direct",
          "ip": [
            "regexp:(\d*)\.(\d*)\.(\d*)\.(\d*)$"
          ],
          "domain": null

客户端提示内容

   U2Ray v3.6<die Commanderin)20180112

An unified platform for anti-censorship-

failed to parse json config:ExtiTools iConf iSerial:failed to read config file>

invalid character 'd'in string escape code2018/02/08 09:01:51 Warning]:Core:

|U2Ray started

**Comment by wumingshi0531** [comment]
regexp:(\d*)\.(\d*)\.(\d*)\.(\d*)$

 代码里斜杠给屏蔽了

**Comment by wumingshi0531** [comment]
0.0.0.0/0  用这个表示也不行。

**Comment by wumingshi0531** [comment]
chinaip,chinasites  pc有用，到路由只偶尔一次有用，重启路由后 怎么弄都没用。

**Comment by liberal-boy** [comment]
v2ray的ip规则不支持正则表达式，只支持IP、CIDR、GeoIP。

**Comment by wumingshi0531** [comment]
"0.0.0.0/0",
            "0.0.0.0/8",
            "183.0.0.0/8",
            "10.0.0.0/8",
            "100.0.0.0/8",
            "10.0.0.0/0",
            "100.0.0.0/0"


好吧 我现在用这种代替了。  有空再试试chinaip,chinasites
