### ISSUE TITLE
树莓派做客户端，iptable 送流量到dokodemo-door ,客户端报UDP端口被占用。

### ISSUE THREAD

**Issue by 5high** [v2ray/v2ray-core#854]
Please skip to the English section below if you don't write Chinese.

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
3.6

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
树莓派做WS+TLS+Caddy+Dokodemo-Door 路由上网,基本功能正常，不确定UDP是否成功转发。

3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
日志报错UDP端口被占用，但其实并没有发现有其他程序监听12345端口。
Feb  8 09:41:49 raspberrypi v2ray[387]: 2018/02/08 09:41:49 [Warning]: App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Transport|Internet|UDP: failed to bind source address > address already in use

4)  你期待看到的正确表现是怎样的？
希望修复这个问题，让UDP顺利转发。

5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
{
   "inbound": {
    "port": 10000,
    "listen":"127.0.0.1",
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "",
          "alterId": 64
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "wsSettings": {
      "path": "/ray"
      }
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
   "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}

    客户端配置:
{
  "inbound": {
    "port": 1080,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true
    }
  },
  "inboundDetour": [
     {
         "domainOverride":["tls","http"],
         "port":12345,
         "protocol":"dokodemo-door",
         "settings":{
             "network": "tcp,udp",
             "followRedirect": true
         }
     }
  ],

  "outbound": {
    "mux": {"enabled": true},
    "tag":"proxy",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "domain.net",
          "port": 443,
          "users": [
            {
              "id": "",
              "alterId": 64
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "tlsSettings": {
        "serverName": "domain.net"
      },
      "wsSettings": {
        "path": "/ray"
      }
    }
  },
"outboundDetour": [
  {
   "tag": "direct", 
   "protocol": "freedom", 
   "settings": {
    "response": null
   }
  }, 
  {
   "tag": "blockout", 
   "protocol": "blackhole", 
   "settings": {
    "response": {
     "type": "http"
    }
   }
  }
 ],  
 "dns": {
  "servers": [
   "8.8.8.8", 
   "8.8.4.4", 
   "localhost"
  ]
 },
  "routing": {
  "settings": {
   "rules": [
    {
          "type": "field",
          "domain": [
          	"www.google.com.hk",
		"googleapis.cn",
		"google.cn",
		"ggpht.cn",
		"chrome.google.com",
		"googleusercontent.com",
		"android.clients.google.com",
		"gvt1.com",
		"xn--ngstr-lra8j.com"
          ],
          "outboundTag": "proxy"
    },
    {
     "ip": [
      "0.0.0.0/8", 
      "10.0.0.0/8", 
      "100.64.0.0/10", 
      "127.0.0.0/8", 
      "169.254.0.0/16", 
      "172.16.0.0/12", 
      "192.0.0.0/24", 
      "192.0.2.0/24", 
      "192.168.0.0/16", 
      "198.18.0.0/15", 
      "198.51.100.0/24", 
      "203.0.113.0/24", 
      "::1/128", 
      "fc00::/7", 
      "fe80::/10"
     ], 
     "domain": null, 
     "type": "field", 
     "port": null, 
     "outboundTag": "direct"
    }, 
    {
     "type": "chinaip", 
     "outboundTag": "direct"
    }, 
    {
     "type": "chinasites", 
     "outboundTag": "direct"
    }
   ], 
   "domainStrategy": "IPIfNonMatch"
  }, 
  "strategy": "rules"
 } 

}
6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

树莓派客户端错误日志:
Feb  8 09:41:49 raspberrypi v2ray[387]: 2018/02/08 09:41:49 [Warning]: App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Transport|Internet|UDP: failed to bind source address > address already in use
Feb  8 09:41:49 raspberrypi v2ray[387]: 2018/02/08 09:41:49 [Warning]: App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Transport|Internet|UDP: failed to bind source address > address already in use
Feb  8 09:41:55 raspberrypi v2ray[387]: 2018/02/08 09:41:55 [Warning]: App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Transport|Internet|UDP: failed to bind source address > address already in use
Feb  8 09:41:55 raspberrypi v2ray[387]: 2018/02/08 09:41:55 [Warning]: App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Transport|Internet|UDP: failed to bind source address > address already in use
Feb  8 09:42:06 raspberrypi v2ray[387]: 2018/02/08 09:42:06 [Warning]: App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Transport|Internet|UDP: failed to bind source address > address already in use
Feb  8 09:42:06 raspberrypi v2ray[387]: 2018/02/08 09:42:06 [Warning]: App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Transport|Internet|UDP: failed to bind source address > address already in use
Feb  8 09:42:12 raspberrypi v2ray[387]: 2018/02/08 09:42:12 [Warning]: App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Transport|Internet|UDP: failed to bind source address > address already in use
Feb  8 09:42:12 raspberrypi v2ray[387]: 2018/02/08 09:42:12 [Warning]: App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Transport|Internet|UDP: failed to bind source address > address already in use
Feb  8 09:42:17 raspberrypi v2ray[387]: 2018/02/08 09:42:17 [Warning]: App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Transport|Internet|UDP: failed to bind source address > address already in use
Feb  8 09:42:17 raspberrypi v2ray[387]: 2018/02/08 09:42:17 [Warning]: App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Transport|Internet|UDP: failed to bind source address > address already in use

服务器端日志
Feb  8 09:39:15 instance-1 rc.local[657]: 2018/02/08 09:39:15 114.249.36.38:43874 accepted tcp:v1.mux.cool:9527
Feb  8 09:39:57 instance-1 rc.local[657]: 2018/02/08 09:39:57 114.249.36.38:43932 accepted tcp:v1.mux.cool:9527
Feb  8 09:39:58 instance-1 rc.local[657]: 2018/02/08 09:39:58 219.234.220.80:43940 accepted tcp:v1.mux.cool:9527
Feb  8 09:40:14 instance-1 rc.local[657]: 2018/02/08 09:40:14 219.234.220.80:43978 accepted tcp:v1.mux.cool:9527
Feb  8 09:41:16 instance-1 rc.local[657]: 2018/02/08 09:41:16 114.249.36.38:44058 accepted tcp:v1.mux.cool:9527
Feb  8 09:41:34 instance-1 rc.local[657]: 2018/02/08 09:41:34 219.234.220.80:44064 accepted tcp:v1.mux.cool:9527
Feb  8 09:41:34 instance-1 rc.local[657]: 2018/02/08 09:41:34 219.234.220.80:44076 accepted tcp:v1.mux.cool:9527
Feb  8 09:41:35 instance-1 rc.local[657]: 2018/02/08 09:41:35 219.234.220.80:44096 accepted tcp:v1.mux.cool:9527
Feb  8 09:41:36 instance-1 rc.local[657]: 2018/02/08 09:41:36 219.234.220.80:44116 accepted tcp:v1.mux.cool:9527
Feb  8 09:41:40 instance-1 rc.local[657]: 2018/02/08 09:41:40 219.234.220.80:44144 accepted tcp:v1.mux.cool:9527
Feb  8 09:41:42 instance-1 rc.local[657]: 2018/02/08 09:41:42 219.234.220.80:44180 accepted tcp:v1.mux.cool:9527
Feb  8 09:41:46 instance-1 rc.local[657]: 2018/02/08 09:41:46 219.234.220.80:44210 accepted tcp:v1.mux.cool:9527
Feb  8 09:41:48 instance-1 rc.local[657]: 2018/02/08 09:41:48 219.234.220.80:44290 accepted tcp:v1.mux.cool:9527
Feb  8 09:42:06 instance-1 rc.local[657]: 2018/02/08 09:42:06 219.234.220.80:44538 accepted tcp:v1.mux.cool:9527
Feb  8 09:42:12 instance-1 rc.local[657]: 2018/02/08 09:42:12 114.249.36.38:44566 accepted tcp:v1.mux.cool:9527
Feb  8 09:42:26 instance-1 rc.local[657]: 2018/02/08 09:42:26 219.234.220.80:44708 accepted tcp:v1.mux.cool:9527
Feb  8 09:43:16 instance-1 rc.local[657]: 2018/02/08 09:43:16 114.249.36.38:44806 accepted tcp:v1.mux.cool:9527
Feb  8 09:44:07 instance-1 rc.local[657]: 2018/02/08 09:44:07 219.234.220.80:44908 accepted tcp:v1.mux.cool:9527
Feb  8 09:44:11 instance-1 rc.local[657]: 2018/02/08 09:44:11 114.249.36.38:44918 accepted tcp:v1.mux.cool:9527
Feb  8 09:44:29 instance-1 rc.local[657]: 2018/02/08 09:44:29 219.234.220.80:44968 accepted tcp:v1.mux.cool:9527
Feb  8 09:44:29 instance-1 rc.local[657]: 2018/02/08 09:44:29 219.234.220.80:44972 accepted tcp:v1.mux.cool:9527
Feb  8 09:44:35 instance-1 rc.local[657]: 2018/02/08 09:44:35 219.234.220.80:45016 accepted tcp:v1.mux.cool:9527
Feb  8 09:44:56 instance-1 rc.local[657]: 2018/02/08 09:44:56 114.249.36.38:45048 accepted tcp:v1.mux.cool:9527
Feb  8 09:45:17 instance-1 rc.local[657]: 2018/02/08 09:45:17 114.249.36.38:45088 accepted tcp:v1.mux.cool:9527
Feb  8 09:45:23 instance-1 rc.local[657]: 2018/02/08 09:45:23 219.234.220.80:45114 accepted tcp:v1.mux.cool:9527
Feb  8 09:46:11 instance-1 rc.local[657]: 2018/02/08 09:46:11 114.249.36.38:45198 accepted tcp:v1.mux.cool:9527
Feb  8 09:46:12 instance-1 rc.local[657]: 2018/02/08 09:46:12 219.234.220.80:45208 accepted tcp:v1.mux.cool:9527
Feb  8 09:46:30 instance-1 rc.local[657]: 2018/02/08 09:46:30 219.234.220.80:45236 accepted tcp:v1.mux.cool:9527
Feb  8 09:47:20 instance-1 rc.local[657]: 2018/02/08 09:47:20 114.249.36.38:45324 accepted tcp:v1.mux.cool:9527
Feb  8 09:48:11 instance-1 rc.local[657]: 2018/02/08 09:48:11 114.249.36.38:45378 accepted tcp:v1.mux.cool:9527
Feb  8 09:49:46 instance-1 rc.local[657]: 2018/02/08 09:49:46 114.249.36.38:45446 accepted tcp:v1.mux.cool:9527
Feb  8 09:51:46 instance-1 rc.local[657]: 2018/02/08 09:51:46 114.249.36.38:45490 accepted tcp:v1.mux.cool:9527
Feb  8 09:52:11 instance-1 rc.local[657]: 2018/02/08 09:52:11 114.249.36.38:45514 accepted tcp:v1.mux.cool:9527

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

8) 其它相关的配置文件（如 Nginx）和相关日志。
报端口占用的时候检查过树莓派其他端口占用情况，并未有其他程序占用12345端口。

root@raspberrypi:/var/log# netstat -anp|grep 12345
tcp6       0      0 :::12345                :::*                    LISTEN      387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.105:57444    ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.105:57466    ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.105:57384    ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60171     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60153     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60206     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60161     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.105:57420    ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60268     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60157     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60256     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.105:57392    ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.105:57381    ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60269     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.105:57404    ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.105:57367    ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.105:57462    ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60216     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:59919     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60220     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60155     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60016     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60205     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60209     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60124     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60240     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60005     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60221     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60128     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:59951     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60266     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60244     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.105:57374    ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.105:57388    ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60258     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:59900     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60139     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.105:57380    ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60004     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:59902     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.105:57428    ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.105:57377    ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:59886     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60154     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.105:57376    ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.105:57382    ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60204     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:59897     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60044     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.105:57421    FIN_WAIT2   -                   
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60134     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60129     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60126     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.105:57405    ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60219     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60156     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.105:57390    ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.105:57431    ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.105:57403    ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.105:57427    ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60218     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60267     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60006     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60257     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60202     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60265     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60132     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60217     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60203     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60184     TIME_WAIT   -                   
tcp6       0      0 172.29.121.177:12345    172.29.121.105:57406    ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:59906     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60228     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60215     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:59895     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60210     TIME_WAIT   -                   
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60002     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:59874     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60190     CLOSE_WAIT  387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.105:57465    ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60255     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60262     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60243     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60270     ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.105:57437    ESTABLISHED 387/v2ray           
tcp6       0      0 172.29.121.177:12345    172.29.121.96:60200     ESTABLISHED 387/v2ray           
udp6       0      0 :::12345                :::*                                387/v2ray**

**Comment by asd2003asd** [comment]
可以贴一下你的 iptables配置吗？你的这个配置实现透明代理功能了没有？

**Comment by xiaokangwang** [comment]
我比较怀疑UDP的原目标数据是否被正确读取，是否可以贴一下完整的debug log？

建议给出 iptables -vL -t $TABLE

另外 https://github.com/v2ray/v2ray-core/blob/52ad41cda393792632ff9d3f13184ace51f7ca3a/transport/internet/udp/hub_linux.go， https://github.com/v2ray/v2ray-core/blob/90925bdf7a49bfcddf3fd6e8ef75276cc23d3cac/transport/internet/udp/hub.go 这里没有相关的调试输出，建议 @VictoriaRaymond 加上，帮助对于这个问题的调试

**Comment by 5high** [comment]
root@raspberrypi:~# iptables -vL -t nat
Chain PREROUTING (policy ACCEPT 785 packets, 133K bytes)
 pkts bytes target     prot opt in     out     source               destination         
  491 28863 V2RAY      tcp  --  any    any     anywhere             anywhere            

Chain INPUT (policy ACCEPT 876 packets, 98329 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 2692 packets, 208K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 2692 packets, 208K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain V2RAY (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     all  --  any    any     anywhere             16.127.196.35.bc.googleusercontent.com 
    0     0 RETURN     all  --  any    any     anywhere             172.28.0.0/16       
    7  2223 RETURN     all  --  any    any     anywhere             172.29.0.0/16       
    0     0 RETURN     all  --  any    any     anywhere             172.30.0.0/16       
    0     0 RETURN     all  --  any    any     anywhere             192.168.0.0/24      
    0     0 RETURN     all  --  any    any     anywhere             192.168.1.0/24      
    0     0 RETURN     all  --  any    any     anywhere             192.168.89.0/24     
    0     0 RETURN     all  --  any    any     anywhere             192.168.88.0/24     
    0     0 RETURN     all  --  any    any     anywhere             192.168.86.0/24     
  484 26640 REDIRECT   tcp  --  any    any     anywhere             anywhere             redir ports 12345


root@raspberrypi:~# iptables -vL -t mangle
Chain PREROUTING (policy ACCEPT 69588 packets, 38M bytes)
 pkts bytes target     prot opt in     out     source               destination         
71633   39M V2RAY      all  --  any    any     anywhere             anywhere            

Chain INPUT (policy ACCEPT 71062 packets, 39M bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 9 packets, 360 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 77480 packets, 38M bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 77530 packets, 38M bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain V2RAY (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     all  --  any    any     anywhere             172.30.0.0/16       
41889   35M RETURN     all  --  any    any     anywhere             172.29.0.0/16       
    0     0 RETURN     all  --  any    any     anywhere             172.28.0.0/16       
    0     0 RETURN     all  --  any    any     anywhere             192.168.0.0/16      
    0     0 RETURN     all  --  any    any     anywhere             16.127.196.35.bc.googleusercontent.com 
 2045 1117K TPROXY     udp  --  any    any     anywhere             anywhere             TPROXY redirect 0.0.0.0:12345 mark 0x1/0x1

**Comment by xiaokangwang** [comment]
请尝试向
`"inboundDetour": [
{
"domainOverride":["tls","http"],
"port":12345,
"protocol":"dokodemo-door",
"settings":{
"network": "tcp,udp",
"followRedirect": true
}`
加上 "listen": "0.0.0.0"
强制其监听IPv4

**Comment by 5high** [comment]
root@raspberrypi:/etc/v2ray# /usr/bin/v2ray/v2ray --config /etc/v2ray/config.json
V2Ray v3.6 (die Commanderin) 20180112
An unified platform for anti-censorship.
2018/02/09 10:35:39 [Warning]: Core: V2Ray started
2018/02/09 10:35:55 [Warning]: App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Transport|Internet|UDP: failed to bind source address > address already in use
2018/02/09 10:36:06 [Warning]: App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Transport|Internet|UDP: failed to bind source address > address already in use
2018/02/09 10:37:37 [Warning]: App|Proxyman|Inbound: connection ends > Proxy|Dokodemo: connection ends > Transport|Internet|UDP: failed to bind source address > address already in use

强制IPV4之后还是有这样的日志出来，ebug 日志内容太多了不便于分析。

**Comment by xiaokangwang** [comment]
请尝试使用本版本的V2Ray并将输出调整至debug。 应该会出现和 Original Destination 相关的输出 https://github.com/v2ray/v2ray-core/releases/tag/v3.8.1

**Comment by 5high** [comment]
使用3.8.1版本后经过十几分钟观察,迅雷大流量下载,日志里未输出udp端口被占用的消息.

**Comment by 5high** [comment]
晚上又看了一下，还是有报udp端口被占用，新版程序指明是到网关的udp数据包，比较奇怪
