### ISSUE TITLE
v2ray使用ws+tls无法隐藏源ip的地址

### ISSUE THREAD

**Issue by kirbyzhu** [v2ray/v2ray-core#855]
配置正常，能够科学上网，但是使用whatismyipaddress查看ip地址出问题，虽然显示了vps的ip，但是能够识别实际来源。

![image](https://user-images.githubusercontent.com/10296293/35964017-756e5e44-0cf1-11e8-95f8-6487413eb1b0.png)

**Comment by liberal-boy** [comment]
你的位置应该是由浏览器上传给whatismyipaddress，不是根据ip定位的。

**Comment by kirbyzhu** [comment]
@liberal-boy 同样设置，换ssr就不存在这个问题，所以我感觉和浏览器没关系。

**Comment by ztc1997** [comment]
@kirbyzhu 你ssr和v是同一个ip？

**Comment by liberal-boy** [comment]
@kirbyzhu ssr和v是同一个服务器？位置来源只有两种可能，ip或者浏览器，如果位置与服务器ip不符，只能来自浏览器。

**Comment by kirbyzhu** [comment]
同一个浏览器。ssr和v虽然不是同一个服务器，但是是同一个vps。同样的方法使用了https://tunnelbroker.net/的ipv6地址。在ssr的同一个服务器上用相同的配置做了一个v，也是显示正常。

很奇怪的是删除了出问题的vps上的ipv6配置，重新在https://tunnelbroker.net/新建了一个ipv6，再次配置后又正常显示了。

真是一个很奇怪的错误。可能是在https://tunnelbroker.net/上会根据来源ipv4地址来指定生成ipv6的地址。

**Comment by lxy0797** [comment]
我也有这样的问题.TLS+WS全局代理后依然显示本地IP而不是代理.
IP查询用的是[ipip.net](url)
浏览器使用的是Chrome
可以访问外网
网络环境是南方联通
