### ISSUE TITLE
geosite:cn建议用ipip的库

### ISSUE THREAD

**Issue by liaobin** [v2ray/v2ray-core#860]
如题，更加准确，地址 https://github.com/17mon/china_ip_list

**Comment by DarienRaymond** [comment]
请证明之

**Comment by liaobin** [comment]
比如b站，使用geoip会出现加载不出视频，配合pac使用则不会

**Comment by DarienRaymond** [comment]
不一定是ip库的问题，也有可能是解析到的 ip 确实不是国内的。
