### ISSUE TITLE
更新3.8后 启动服务端无响应

### ISSUE THREAD

**Issue by enmoment** [v2ray/v2ray-core#862]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v2ray-v3.8-linux-64
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
通过vmess 访问google
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
在vps上运行./v2ray --config config.json后系统显示：
V2Ray v3.8 (die Commanderin) 20180211
An unified platform for anti-censorship.
然后就无其他响应，log中也没有日志
4)  你期待看到的正确表现是怎样的？
服务器能正常启动
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:

{
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "waring"
  },
  "inbound": {
    "port": 1663,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "9d9d9699-7513-4f6a-b5a3-b310e2baebfc",
          "level": 1,
          "alterId":32
        }
      ]
    }
},
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。
无任何日志输出

    客户端错误日志:
无任何日志输出

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
无任何日志输出
8) 其它相关的配置文件（如 Nginx）和相关日志。
无任何日志输出

**Comment by sweard** [comment]
我遇到了同样的问题

**Comment by liberal-boy** [comment]
在warning级别下正常情况不会输出信息，如果你想获得更多输出信息请降低logging level。
