### ISSUE TITLE
多用户情况下如何限制单个用户占用过多系统资源

### ISSUE THREAD

**Issue by songshan99** [v2ray/v2ray-core#864]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）

v3.6

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

一台V2Ray服务器节点，服务器端配置多个用户 (>5个)
每个用户只使用自己的ID和V2Ray节点连接

3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

（并非严格量化测试的结果）如果有用户使用多线程下载，V2Ray服务器端内存和网络带宽均被此用户占用较多，影响其他用户使用。

4)  你期待看到的正确表现是怎样的？

能否有配置选项限制单个用户的最大带宽/连接数/内存占用等等，以平衡多个用户情况下的服务器资源分配。

5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
```javascript
   {
  "inbound": {
    "port": 16823, // 服务器监听端口
    "protocol": "vmess",    // 主传入协议
    "settings": {
      "clients": [
        {
          "id": "第一个ID",  // 用户 ID1
          "alterId": 64
        }
        {
          "id": "第二个ID",  // 用户 ID2
          "alterId": 64
        }
        ......
       {
          "id": "第N个ID",  // 用户 IDn
          "alterId": 64
        }
      ]
    }
  },
  "outbound": {
    "protocol": "freedom",  // 主传出协议
    "settings": {}
  }
}
```

    客户端配置:
无

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
无

    客户端错误日志:
无

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
无

8) 其它相关的配置文件（如 Nginx）和相关日志。
无

**Comment by DarienRaymond** [comment]
你可以把环境变量 V2RAY_RAY_BUFFER_SIZE 设为 1，可以有效减少内存的使用。暂时还没有其它的方式，比如限制连接数之类。

**Comment by 1061302569** [comment]
那岂不是可以一群人连接一个节点了
