### ISSUE TITLE
extreamly high cpu consumption on arm device

### ISSUE THREAD

**Issue by NWindy5** [v2ray/v2ray-core#866]
Please read the [instruction](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md) and answer the following questions before submitting your issue. Thank you.
Please answer all the questions with enough information. All issues not following this template will be closed immediately.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
V3.7
2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
Browse websites
3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)
Extreamly high cpu useage.
pidstat:
<img width="809" alt="2018-02-16 12 17 36" src="https://user-images.githubusercontent.com/33677024/36292805-6ff13a30-130f-11e8-9824-a014286ce3d2.png">
<img width="574" alt="2018-02-16 12 18 08" src="https://user-images.githubusercontent.com/33677024/36292809-73b3f90a-130f-11e8-9125-e380159f54e9.png">

4) What's your expectation?
avrage load should be about 1 (Thats the avrage load when I download files using ssrr-redir)
5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Server configuration:
there is nothing to do with the server

    Client configuration:
```javascript
    {
    "policy": {
        "levels": {
            "0": {
                "uplinkOnly": 0
            }
        }
    },
    "dns": {
        "servers": [
            "localhost"
        ]
    },
    "outboundDetour": [
        {
            "protocol": "freedom",
            "tag": "direct",
            "settings": {}
        }
    ],
    "inbound": {
        "port": 19873,
        "protocol": "dokodemo-door",
        "settings": {
            "network": "tcp,udp",
            "followRedirect": true
        }
    },
    "inboundDetour": [
        {
            "listen": "127.0.0.1",
            "allocate": {
                "strategy": "always",
                "refresh": 5,
                "concurrency": 3
            },
            "port": 8001,
            "protocol": "http",
            "tag": "httpDetour",
            "domainOverride": [
                "http",
                "tls"
            ],
            "streamSettings": {},
            "settings": {
                "timeout": 0
            }
        }
    ],
    "log": {
        "error": "/var/log/v2ray/error.log",
        "loglevel": "warning",
        "access": ""
    },
    "routing": {
        "strategy": "rules",
        "settings": {
            "domainStrategy": "IPIfNonMatch",
            "rules": [
                {
                    "port": "1-52",
                    "type": "field",
                    "outboundTag": "direct"
                },
                {
                    "port": "54-79",
                    "type": "field",
                    "outboundTag": "direct"
                },
                {
                    "port": "81-442",
                    "type": "field",
                    "outboundTag": "direct"
                },
                {
                    "port": "444-65535",
                    "type": "field",
                    "outboundTag": "direct"
                },
                {
                    "type": "field",
                    "ip": [
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "203.0.113.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10",
                        "geoip:cn"
                    ],
                    "outboundTag": "direct"
                },
                {
                    "type": "field",
                    "outboundTag": "direct",
                    "domain": [
                        "geosite:cn"
                    ]
                }
            ]
        }
    },
    "outbound": {
        "sendThrough": "0.0.0.0",
        "mux": {
            "enabled": true,
            "concurrency": 8
        },
        "protocol": "vmess",
        "settings": {
            "vnext": [
                {
                    "address": "$HOSTNAME",
                    "port": 443,
                    "users": [
                        {
                            "id": "$UUID",
                            "alterId": 32,
                            "security": "aes-128-gcm",
                            "level": 1
                        }
                    ]
                }
            ]
        },
        "streamSettings": {
            "network": "ws",
            "tcpSettings": {
                "connectionReuse": false,
                "header": {
                    "type": "none"
                }
            },
            "kcpSettings": {
                "header": {
                    "type": "none"
                },
                "mtu": 1350,
                "congestion": false,
                "tti": 20,
                "uplinkCapacity": 5,
                "writeBufferSize": 1,
                "readBufferSize": 1,
                "downlinkCapacity": 20
            },
            "security": "tls",
            "tlsSettings": {
                "serverName": "$HOSTNAME",
                "allowInsecure": false
            },
            "wsSettings": {
                "path": "/",
                "connectionReuse": true
            }
        }
    }
}
```

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.

    Server error log:
there is nothing to do with the server
    Client error log:
```
   There are a lot of "max files opened " error but noting else
```

7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.
there is noting to do with the access log

Please review your issue before submitting.

8) Other configurations (such as Nginx) and logs.

**Comment by losfair** [comment]
Have you tested with the same configuration on an x86 device ?

**Comment by NWindy5** [comment]
Yes, it worked just fine.Actually I copied it from v2rayx config file

**Comment by losfair** [comment]
AFAIK there is no hardware AES acceleration on 32-bit ARM and Go does not support the AES acceleration feature on ARM64 yet ( [Go issue 18498](https://github.com/golang/go/issues/18498) ).

According to the [documentation](https://www.v2ray.com/chapter_02/protocols/vmess.html), chacha20-poly1305 is preferred on ARM platforms.

**Comment by NWindy5** [comment]
I tried none but it didn't work either.

**Comment by DarienRaymond** [comment]
What is the CPU field in 'pidstat' screenshot? 60%?

Please fix 'too many open files' error first (by allowing more open files). It may cause high CPU usage temporarily, until the error is gone.

**Comment by NWindy5** [comment]
I have set the limit to 4096 files which is the "hard limit" of my device but the error still occurred.
The last column of pidstat is average cpu useage since system has been booted.

**Comment by losfair** [comment]
Could you please do some [profiling](https://blog.golang.org/profiling-go-programs) to find out what functions are consuming cpu cycles on your device?

**Comment by latel** [comment]
same here 

![image](https://user-images.githubusercontent.com/5621862/111402709-a99b1a80-8706-11eb-81c2-e7fc0461da7f.png)
