### ISSUE TITLE
服务器端无法正常启动服务

### ISSUE THREAD

**Issue by kirbyzhu** [v2ray/v2ray-core#867]
中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
     3.9
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
     使用chrome通过socks代理观看youtube视频
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
      希望能够正常使用kcp增加速度和稳定性，并使用utp混淆
4)  你期待看到的正确表现是怎样的？
     服务器段正常启用
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
```
{
"log": {
        "access": "/var/log/v2ray/access.log", 
        "error": "/var/log/v2ray/error.log",  
        "loglevel": "warning"
},

"inbound": {
        "port": 6881,   
        "protocol": "vmess",
        "settings": {
            "clients": [
                {
                    "id": "*****-****-********",  
                    "level": 1,            
                    "alterId": 64         
                },
			"detour": {
                    "to": "detour-kcp"
                }
            ]
        }
},

"inboundDetour": [    
{
            "protocol": "vmess",
            "port": "6882-6999",    
            "tag": "detour-kcp",
            "settings": {},
            "allocate": {
                "strategy": "random", 
                "concurrency": 2,     
                "refresh": 5         
            },
            "streamSettings": {
                "network": "kcp"
            }
  }
],

"outbound": {
        "protocol": "freedom",
        "settings": {}
},

"outboundDetour": [
        {
            "protocol": "blackhole",
            "settings": {},
            "tag": "blocked"
        }
],

"routing": {
        "strategy": "rules",
        "settings": {
            "rules": [
                {
                    "type": "field",
                    "ip": [
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10"
                    ],
                    "outboundTag": "blocked"
                }
            ]
        }
},

"transport": {
        "tcpSettings": {
            "connectionReuse": true
        },
        "kcpSettings": {
            "mtu": 1350,
            "tti": 20,
            "uplinkCapacity": 12,
            "downlinkCapacity": 100,
            "congestion": false,
            "readBufferSize": 2,
            "writeBufferSize": 2,
            "header": {
                "type": "utp"
            }
        }
    }
} 
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

  无法启动服务，所以日志信息无参考价值

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

  无法启动服务，所以日志信息无参考价值 

8) 其它相关的配置文件（如 Nginx）和相关日志。

[root@ v2ray]# systemctl status v2ray
* v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Fri 2018-02-16 23:25:40 CST; 6s ago
  Process: 1218 ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json (code=exited, status=255)
 Main PID: 1218 (code=exited, status=255)

Feb 16 23:25:40  systemd[1]: Unit v2ray.service entered failed state.
Feb 16 23:25:40  systemd[1]: v2ray.service failed.
Feb 16 23:25:40  systemd[1]: v2ray.service holdoff time over, scheduling restart.
Feb 16 23:25:40  systemd[1]: start request repeated too quickly for v2ray.service
Feb 16 23:25:40  systemd[1]: Failed to start V2Ray Service.
Feb 16 23:25:40  systemd[1]: Unit v2ray.service entered failed state.
Feb 16 23:25:40  systemd[1]: v2ray.service failed.

**Comment by DarienRaymond** [comment]
运行一下 `journalctl -u v2ray` 看一下具体的错误信息。

**Comment by kirbyzhu** [comment]
Feb 16 23:21:42  v2ray[1123]: V2Ray v3.9 (die Commanderin) 20180215
Feb 16 23:21:42  v2ray[1123]: An unified platform for anti-censorship.
Feb 16 23:21:42  v2ray[1123]: failed to parse json config: Ext|Tools|Conf|Serial: failed to read config file > invalid character ':' after array element
Feb 16 23:21:42  v2ray[1123]: Main: failed to read config file: /etc/v2ray/config.json > Main: failed to execute v2ctl to convert config file. > exit status 255
Feb 16 23:21:42  systemd[1]: v2ray.service: main process exited, code=exited, status=255/n/a
Feb 16 23:21:42  systemd[1]: Unit v2ray.service entered failed state.
Feb 16 23:21:42  systemd[1]: v2ray.service failed.
Feb 16 23:21:43  systemd[1]: v2ray.service holdoff time over, scheduling restart.
Feb 16 23:21:43  systemd[1]: start request repeated too quickly for v2ray.service
Feb 16 23:21:43  systemd[1]: Failed to start V2Ray Service.
Feb 16 23:21:43  systemd[1]: Unit v2ray.service entered failed state.
Feb 16 23:21:43  systemd[1]: v2ray.service failed.
Feb 16 23:25:39  systemd[1]: Started V2Ray Service.
Feb 16 23:25:39  systemd[1]: Starting V2Ray Service...
Feb 16 23:25:39  v2ray[1177]: V2Ray v3.9 (die Commanderin) 20180215
Feb 16 23:25:39  v2ray[1177]: An unified platform for anti-censorship.
Feb 16 23:25:39  v2ray[1177]: failed to parse json config: Ext|Tools|Conf|Serial: failed to read config file > invalid character ':' after array element
Feb 16 23:25:39  v2ray[1177]: Main: failed to read config file: /etc/v2ray/config.json > Main: failed to execute v2ctl to convert config file. > exit status 255
Feb 16 23:25:39  systemd[1]: v2ray.service: main process exited, code=exited, status=255/n/a
Feb 16 23:25:39  systemd[1]: Unit v2ray.service entered failed state.
Feb 16 23:25:39  systemd[1]: v2ray.service failed.
Feb 16 23:25:39  systemd[1]: v2ray.service holdoff time over, scheduling restart.
Feb 16 23:25:39  systemd[1]: Started V2Ray Service.
Feb 16 23:25:39  systemd[1]: Starting V2Ray Service...
Feb 16 23:25:39  v2ray[1187]: V2Ray v3.9 (die Commanderin) 20180215
Feb 16 23:25:39  v2ray[1187]: An unified platform for anti-censorship.
Feb 16 23:25:39  v2ray[1187]: failed to parse json config: Ext|Tools|Conf|Serial: failed to read config file > invalid character ':' after array element
Feb 16 23:25:39  v2ray[1187]: Main: failed to read config file: /etc/v2ray/config.json > Main: failed to execute v2ctl to convert config file. > exit status 255
Feb 16 23:25:39  systemd[1]: v2ray.service: main process exited, code=exited, status=255/n/a
Feb 16 23:25:39  systemd[1]: Unit v2ray.service entered failed state.
Feb 16 23:25:39  systemd[1]: v2ray.service failed.
Feb 16 23:25:40  systemd[1]: v2ray.service holdoff time over, scheduling restart.
Feb 16 23:25:40  systemd[1]: Started V2Ray Service.
Feb 16 23:25:40  systemd[1]: Starting V2Ray Service...
Feb 16 23:25:40  v2ray[1197]: V2Ray v3.9 (die Commanderin) 20180215
Feb 16 23:25:40  v2ray[1197]: An unified platform for anti-censorship.
Feb 16 23:25:40  v2ray[1197]: failed to parse json config: Ext|Tools|Conf|Serial: failed to read config file > invalid character ':' after array element
Feb 16 23:25:40  v2ray[1197]: Main: failed to read config file: /etc/v2ray/config.json > Main: failed to execute v2ctl to convert config file. > exit status 255
Feb 16 23:25:40  systemd[1]: v2ray.service: main process exited, code=exited, status=255/n/a
Feb 16 23:25:40  systemd[1]: Unit v2ray.service entered failed state.
Feb 16 23:25:40  systemd[1]: v2ray.service failed.
Feb 16 23:25:40  systemd[1]: v2ray.service holdoff time over, scheduling restart.
Feb 16 23:25:40  systemd[1]: Started V2Ray Service.
Feb 16 23:25:40  systemd[1]: Starting V2Ray Service...
Feb 16 23:25:40  v2ray[1208]: V2Ray v3.9 (die Commanderin) 20180215
Feb 16 23:25:40  v2ray[1208]: An unified platform for anti-censorship.
Feb 16 23:25:40  v2ray[1208]: failed to parse json config: Ext|Tools|Conf|Serial: failed to read config file > invalid character ':' after array element
Feb 16 23:25:40  v2ray[1208]: Main: failed to read config file: /etc/v2ray/config.json > Main: failed to execute v2ctl to convert config file. > exit status 255
Feb 16 23:25:40  systemd[1]: v2ray.service: main process exited, code=exited, status=255/n/a
Feb 16 23:25:40  systemd[1]: Unit v2ray.service entered failed state.
Feb 16 23:25:40  systemd[1]: v2ray.service failed.
Feb 16 23:25:40  systemd[1]: v2ray.service holdoff time over, scheduling restart.
Feb 16 23:25:40  systemd[1]: Started V2Ray Service.
Feb 16 23:25:40  systemd[1]: Starting V2Ray Service...
Feb 16 23:25:40  v2ray[1218]: V2Ray v3.9 (die Commanderin) 20180215
Feb 16 23:25:40  v2ray[1218]: An unified platform for anti-censorship.
Feb 16 23:25:40  v2ray[1218]: failed to parse json config: Ext|Tools|Conf|Serial: failed to read config file > invalid character ':' after array element
Feb 16 23:25:40  v2ray[1218]: Main: failed to read config file: /etc/v2ray/config.json > Main: failed to execute v2ctl to convert config file. > exit status 255
Feb 16 23:25:40  systemd[1]: v2ray.service: main process exited, code=exited, status=255/n/a
Feb 16 23:25:40  systemd[1]: Unit v2ray.service entered failed state.
Feb 16 23:25:40  systemd[1]: v2ray.service failed.
Feb 16 23:25:40  systemd[1]: v2ray.service holdoff time over, scheduling restart.
Feb 16 23:25:40  systemd[1]: start request repeated too quickly for v2ray.service
Feb 16 23:25:40  systemd[1]: Failed to start V2Ray Service.
Feb 16 23:25:40  systemd[1]: Unit v2ray.service entered failed state.
Feb 16 23:25:40  systemd[1]: v2ray.service failed.

**Comment by kirbyzhu** [comment]
好像是配置文件里面哪里多了个冒号 我找找看先

**Comment by kirbyzhu** [comment]
有什么工具可以检查这样的错误么 我是通过一个正常使用的json文件删除掉我不需要的内容 按说没增加新的符号啊

**Comment by kirbyzhu** [comment]
问题解决了，json文件写错了

https://www.bejson.com/ 在线定位到错误 然后逐个修改 

v2ray -config=config.json -test 测试通过

谢谢 @DarienRaymond 提供线索！
