### ISSUE TITLE
V3.8开始出现大量断流

### ISSUE THREAD

**Issue by kylidboy** [v2ray/v2ray-core#868]
服务器端版本升级到从3.8开始，会出现大量类似链接被截断的现象，导致下载失败。

配置的mKCP
链接没有问题，
但是流量似乎有错，大量的enterstate 5，
下载会断，代理转发会断，
现在降级回3.6了

**Comment by jasonliul** [comment]
个例, 3.8一切正常.
不过3.8.1/3.9, V2RayN居然不支持. 没有出错信息, 但是无法打开网页. 回退3.8一切OK.

**Comment by 2dust** [comment]
@jasonliul
更新服务端,和V2RayN无关

**Comment by jasonliul** [comment]
@2dust
有劳大大回复...
不过客户端的问题... 唔...这个, 不清楚问题所在.

呜呼, 你等大大, 各打五十大板~~
LOL

**Comment by iambonboncat** [comment]
3.9确实 v2rayN用不了|！

**Comment by 2dust** [comment]
v2ray保证兼容是服务端>=客户端
所以请升级服务端到最新即可

**Comment by DKestBK** [comment]
@jasonliul @iambonboncat 
发现3.8之后如果不更新服务端，客户端要关掉mux才能用

**Comment by jasonliul** [comment]
3.10 已经OK.
大大们辛苦喇~~
