### ISSUE TITLE
Different behavior between v3.7+ and v3.6- when two inbounds share one tag

### ISSUE THREAD

**Issue by y0umu** [v2ray/v2ray-core#871]
English:
Please read the [instruction](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md) and answer the following questions before submitting your issue. Thank you.
Please answer all the questions with enough information. All issues not following this template will be closed immediately.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?
v3.9 both on remote host and local. (arm-v3.6, arm-v3.7, arm-v3.9, linux64-v3.6, linux64-v3.9 are tested against this problem)

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.
Running on my raspberry pi 2 to tunnel requests from other clients in the same LAN, either through socks or http proxy. These clients just want to google something up, they don't watch Youtube, etc.

3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)

Although discoverd on my raspberry pi, this issue can be reproduced on my Fedora 27 as well. 

If two in-bounding configs share the same tag ("wantWsOut" in the json below), one of the configs will not function. Say, one configures the port 8080 to listen to http requests, the other configures port 7900 as the socks5 proxy port.

I ran
`./v2ray --config config/server/rpi/debug2_pi_config_one_in_all.json`
V2Ray v3.9 (die Commanderin) 20180215
An unified platform for anti-censorship.
2018/02/17 23:28:46 [Debug]: App|Log: Logger started
2018/02/17 23:28:46 [Warning]: Core: V2Ray started

then
`sudo netstat -nltup | grep v2ray`
only to see port 8080 is missing from the list:
tcp6       0      0 :::7900                 :::*                    LISTEN      8704/./v2ray        
udp6       0      0 :::7900                 :::*                                8704/./v2ray

This is the most confusing: since older versions of V2Ray (v3.6 and backwards) works fine under such circumstance. With the same json config:
`./v2ray --config config/server/rpi/debug2_pi_config_one_in_all.json`
V2Ray v3.6 (die Commanderin) 20180112
An unified platform for anti-censorship.
2018/02/17 23:26:04 [Debug]: App|Proxyman|Inbound: creating stream worker on 0.0.0.0:8080
2018/02/17 23:26:04 [Debug]: App|Proxyman|Inbound: creating stream worker on 0.0.0.0:7900
2018/02/17 23:26:04 [Info]: Transport|Internet|TCP: listening TCP on 0.0.0.0:8080
2018/02/17 23:26:04 [Info]: Transport|Internet|TCP: listening TCP on 0.0.0.0:7900
2018/02/17 23:26:04 [Info]: Transport|Internet|UDP: listening UDP on 0.0.0.0:7900

`sudo netstat -nltup | grep v2ray`
tcp6       0      0 :::8080                 :::*                    LISTEN      9049/./v2ray        
tcp6       0      0 :::7900                 :::*                    LISTEN      9049/./v2ray        
udp6       0      0 :::7900                 :::*                                9049/./v2ray

I read the docs, both English and Chinese version , carefully again. I noticed the line saying

> tag: This inbound interface's tag, which should be unique among all inbound/outbound interfaces.

**Therefore what I am faced with is in effect what v2ray is designed to be? And on the other hand what v3.6 does is actually a bug?**

4) What's your expectation?
v2ray will listen on both port http 8080 and socks 7900 even the two configs share the same tag, just as what v3.6 does.

5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Server configuration:
```javascript
// not necessary since the problem lies purely on the client side
```

It is worth mentioning that the original json is bloated and is trimmed to what you see here.
    Client configuration:
```javascript
{
  "log": {
    "loglevel": "debug"
//    "access" : "/var/log/v2ray/access.log",
//    "error" : "/var/log/v2ray/error.log"
  },
  "inbound": {
    "listen": "0.0.0.0",
    "port": 8080,
    "protocol": "http",
    "tag": "wantWsOut",
    "settings": {
      "timeout": 0,
      "allowTransparent": true
   }
  },
  "inboundDetour": [
    {
      "listen": "0.0.0.0",
      "port": 7900,
      "protocol": "socks",
      "tag": "wantWsOut",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": "0.0.0.0"
      }
    }    
  ],
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "some:ipv4:of:my:remote:host",
          "port": 7800,
          "users": [
            {
              "id": "some-uuid",
              "alterId": 64,
              "security": "aes-128-gcm"
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "kcp",
      "kcpSettings": {
        "mtu": 1350,
        "tti": 20,
        "uplinkCapacity": 5,
        "downlinkCapacity": 20,
        "congestion": false,
        "readBufferSize": 1,
        "writeBufferSize": 1,
        "header": {
          "type": "wechat-video"
        }
      }
    }
  },
    "mux": {
      "enabled": true
    },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "vmess",
      "tag": "wsOut",
      "settings": {
        "vnext": [
          {
            "address": "some.ipv4ofmy.remote.host",
            "port": 443,
            "users": [
              {
                "id": "some-uuid",
                "alterId": 64,
                "security": "aes-128-gcm"
              }
            ]
          }
        ]
      },
      "streamSettings": {
      "network": "ws",
      "wsSettings": {
            "path": "/mypath",
            "headers": {
                "Host": "www.cctv.com",
                "User-Agent": "Chromium SDK 59.0"
            }
        },
        "security": "tls",
        "tlsSettings": {
            "serverName": "example.com",
            "allowInsecure": false
        }
      }
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": "1-52",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "54-79",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "81-442",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "444-2199",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "2201-5227",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "port": "5229-65535",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "domain": ["geosite:cn"],
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10",
            "geoip:cn"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "inboundTag": ["wantWsOut"],
          "outboundTag": "wsOut"
        }
      ]
    }
  },
  "transport" : {}
}
```

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.

    Server error log:
```
    // Not necessary
```
    Client error log:
```
2018/02/17 23:36:27 [Debug]: App|Log: Logger started
2018/02/17 23:36:27 [Warning]: Core: V2Ray started
```

7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.
```
    // No such log, and it is not necessary
```

Please review your issue before submitting.

8) Other configurations (such as Nginx) and logs.
Not necessary.

**Comment by y0umu** [comment]
To make the original post shorter I am writing in this comment: if I remove either of these tags, both ports will be listened on.

Also I've tested it with the following json (two socks inbounds) and I can see this is not likely an issue in http proxy module.
```javascript
//...
"inbound": {
    "listen": "0.0.0.0",
      "port": 3293,
      "protocol": "socks",
      "tag": "wantWsOut",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": "0.0.0.0"
   }
  },
  "inboundDetour": [
    {
      "listen": "0.0.0.0",
      "port": 3240,
      "protocol": "socks",
      "tag": "wantWsOut",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": "0.0.0.0"
      }
    }    
  ],
//...
```

**Comment by DarienRaymond** [comment]
This is not a documented behavior. It is not guaranteed that multiple inbounds sharing the same tag will work well. Please don't use duplicated tags among inbound ands outbounds.

**Comment by y0umu** [comment]
Thank you @DarienRaymond for the explanation.
