### ISSUE TITLE
Feature request: option to set asset location

### ISSUE THREAD

**Issue by wongsyrone** [v2ray/v2ray-core#875]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
3.10 linux 64
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
x86软路由
3) 详情
Openwrt/LEDE 软路由配置的时候需要把二进制（v2ray/v2ctl）和数据文件(geo*.dat)分开放置，这样能方便管理，希望增加类似于 -config 的配置选项用来指定asset路径。
预期效果：`/usr/sbin/v2ray -config /etc/config.json -asslocation /etc/v2ray`

**Comment by DarienRaymond** [comment]
https://www.v2ray.com/chapter_02/env.html

**Comment by wongsyrone** [comment]
之前以为procd只能指定一个env，后来看了源码已经会了。其实选项自己实现也不难
