### ISSUE TITLE
Perfer IPv6 address when freedom is dialing

### ISSUE THREAD

**Issue by xiaokangwang** [v2ray/v2ray-core#88]
希望能够在freedom进行Dial的时候优先连接IPv6地址。

目前，freedom在Dial时会在得到的域名的地址中随机选择一个进行连接。 

现代浏览器的行为是优先选择IPv6地址进行连接。 这样不但可以促进IPv6的应用，也防止可能的非正常登出。

**Comment by v2ray** [comment]
Fixed in 00fd6861a69694e2f97b5c9d57c3ee8fb3eedbe1
