### ISSUE TITLE
mips softfloat 版本请求

### ISSUE THREAD

**Issue by bitching** [v2ray/v2ray-core#886]
很多常见路由器的CPU都是 MIPS xxx **Kc** 系列，Mips 的文档有提到 Kc 系列的 CPU 都没有 FPU。
而且 OpenWRT/LEDE 的官方固件均未开启 Kernel -> MIPS FPU Emulator ，跟那边提过 issue ，让自己编译固件。。。
2018/2/16新发布的 Golang 1.10 支持软件模拟浮点计算， Release Note 提到唯一需要做的就是设置环境变量 GOMIPS=softfloat 。
以后发布时可否增加一个 softfloat 的版本，让广大 Kc 系列也可以科学上网？

-

令外，能否就裁剪 v2ray-core 写个稍微详细点的教程？
按照 https://steemit.com/cn/@v2ray/meemg-v2ray 提到的方法，稍微减掉一行编译就通不过，就算只删掉 core/app/dns，core/main/json，core/transport/internet/headers/utp 这三项也会提示：
work/src/v2ray.com/ext/tools/conf/vmess.go:86:23: unknown field 'SecureEncryptionOnly' in struct literal of type inbound.Config
Unable to build V2Ray control: exit status 2
不知道问题在哪里。。

**Comment by DarienRaymond** [comment]
会在下一版本增加softfloat的release

第二个问题，你需要`go get -u v2ray.com/core`更新一下代码，这个错误和你删掉的内容无关。

**Comment by crysislinux** [comment]
尝试了一下，v2ray_softfloat 能在mips上使用，但是它会调用v2ctl，然后就又出错了
failed to execute v2ctl to convert config file. > signal: illegal instruction

**Comment by crysislinux** [comment]
在 https://steemit.com/cn/@v2ray/meemg-v2ray 找到了一个办法，
先在别的机器上
v2ctl config < config.json > config.pb
然后在路由器
v2ray -config=config.pb -format=pb

**Comment by Cwek** [comment]
是不是v2ray.service没修改配置文件？一键脚本的配置文件是json，所以还需要v2ctl，只用pb的话可以不用。

**Comment by DarienRaymond** [comment]
下一版本会添加softfloat编译的v2ctl

**Comment by vvxiang** [comment]
我按照 https://steemit.com/cn/@v2ray/meemg-v2ray  已经完成了mips文件的编译，完全照着教材删除的功能，没有出错。我完全不懂得GO语言，是在TG上面找到了一位高人一步步教我完成的，可惜他太忙。我编译完成后，没有教我下一步如何在路由器上面安装启动。我现在编译完成后的v2ray文件只有4M多了，请问我要怎么让这一个单独文件运行起来？

**Comment by brick2008** [comment]
softfloat版本还没有吗

**Comment by ntgeralt** [comment]
实测v2ray有无softfloat的两个版本，在7621路由上体验95%一致，剩下的可能核电抽风，原版v2ray稳点
