### ISSUE TITLE
Please help to review whether server config is viable or not?

### ISSUE THREAD

**Issue by Balnea** [v2ray/v2ray-core#887]
Hi, and thank you for your hard work on the project. 
I recently want to combine two plans into one server config, but I can't find any documents about it.
So I am seeking help here.

1) What version of V2Ray are you using?
V3.10

2) What's your scenario of using V2Ray?
Enjoy youtube with Chrome

3) What did you see? 
Not yet tested, however

4) What's your expectation?
Plan A: For port 443 with websocket+tls+Caddy and hosting a website
Plan B: For portB-portC with mkcp and dynamic port
Both Plan A & B in one server config, while clients config in two different versions respectively

5) Please attach your configuration file.

    Server configuration:
```javascript
 {
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": PortA,
	"listen": "127.0.0.1",
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "UUID1",
          "level": 1,
          "security": "auto",
          "alterId": 32
        }
      ]
    },
    "streamSettings":{
      "network": "ws",
	  "wsSettings": {
	  "path": "/ray"
	  }
    }
  },
  "inboundDetour": [
	{
	"port": PortB,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "UUID2",
          "level": 1,
          "security": "auto",
          "alterId": 32
        }
      ],
	  "detour": {
        "to": "detour-dynamic-kcp"
		}
	},
	"streamSettings":{
      "network":"kcp"
	  },
	"kcpSettings": {
    "mtu": 1350,
    "tti": 10,
    "uplinkCapacity": 100,
    "downlinkCapacity": 100,
    "congestion": true,
    "readBufferSize": 8,
    "writeBufferSize": 8,
    "header": {
      "type": "none"
    }
	}
   	},
	{
	"protocol": "vmess",
    "port": "PortB-PortC",
    "tag": "detour-dynamic-kcp",
    "settings": {},
    "allocate": {
      "strategy": "random",
      "concurrency": 2,
      "refresh": 5
    },
    "streamSettings": {
      "network": "kcp"
    }  
	}
  ],
    "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}
```
    Client configuration:
```javascript
Omitted, but I am sure with seperate server configs, they will work just fine.
```

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.

    Server error log:
```
N/A
```
    Client error log:
```
N/A
```

7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.
```
N/A
```

8) Other configurations (such as Nginx) and logs.
Caddyfile:
mydomain.com
gzip
log /var/log/caddy/access.log
tls my@mail.com
root /var/www/
proxy /ray 127.0.0.1:PortA {
    websocket
    header_upstream -Origin
}

**Comment by DarienRaymond** [comment]
Issue is not supposed for checking configurations in general. Unless you have a specific problem which blocks you from using V2Ray, we are unable to help.
