### ISSUE TITLE
请问alterId起作用吗？服务端和客户端不一致也可以连接吗？

### ISSUE THREAD

**Issue by ch3nBo** [v2ray/v2ray-core#889]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v3.10
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
看youtube
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
**alterId客户端随便设置一个数值都可以正常连接上服务端。**
4)  你期待看到的正确表现是怎样的？
看说明文档alterId服务端和客户端一定要一致，所以较为困惑。
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

**Comment by yamada95** [comment]
从规范上来说，必须要一致：https://www.v2ray.com/chapter_02/protocols/vmess.html

现在不一致也能连，只是因为现在版本实现允许，但不一定在未来版本可以。

**Comment by ch3nBo** [comment]
@yamada95 您好，谢谢您的回复，请问您现在使用的时候也是这样的吗？如果大家暂时都是这样，那我就不困惑了。
