### ISSUE TITLE
https正常反问，开启wss之后无法连接

### ISSUE THREAD

**Issue by scalaview** [v2ray/v2ray-core#891]
Please skip to the English section below if you don't write Chinese.

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V2Ray v3.10(die Commanderin)20180222

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
使用chrome上网
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
按照教程配置好nginx ＋ websocket可以正常使用，在这基础之上配置了服务器的ssl证书，服务器的https能够正常访问，因为在v2ray开启了tls模式，就出现无法脸上wss的情况
4)  你期待看到的正确表现是怎样的？
从我查看log的情况来看，只从开启了tls，v2ray就没接收过请求，感觉是nginx挡住了，但是https正常访问，导致我不知道哪里出现问题，希望可以帮忙解决
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
```javascript
{
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "debug"
  },
  "inbound": {
    "port": 9999,
    "protocol": "vmess",
    "listen": "127.0.0.1",
    "allocate": {
       "strategy": "always"
    },
    "settings": {
      "clients": [
        {
          "id": "",
          "level": 1,
          "alterId": 64,
          "security": "chacha20-poly1305"
        }
      ]
    },
    "streamSettings": {
        "network":"ws",
  "wsSettings": {
     "connectionReuse": false,
     "path": "/"
  },
  "security": "tls",
  "tlsSettings": {
    "certificates": [{
    "certificateFile": "/etc/nginx/ssl/fullchain.cer",
    "keyFile": "/etc/nginx/ssl/my.key"
     }]
  }
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  }
}
```

    客户端配置:
```javascript
{
  "log": {
    "loglevel": "debug"
  },
  "inbound": {
    "port": 1086,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "127.0.0.1"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "host",
          "port": 443,
          "users": [
            {
              "id": "my-id",
              "level": 1,
              "alterId": 64,
              "security": "chacha20-poly1305"
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network":"ws",
      "allowInsecure": true,
      "wsSettings": {
         "connectionReuse": false,
         "path": "/ws"
      },
      "security": "tls",
      "tlsSettings": {
        "serverName": "host"
      }
    }
  },
  "policy": {
    "levels": {
      "0": {"uplinkOnly": 0}
    }
  }
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
```
    无报错
```

    客户端错误日志:
```
 [Warning] [316557554] App|Proxyman|Outbound: failed to process outbound traffic > Proxy|VMess|Outbound: failed to find an available destination > Retry: [Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://host/ws):  > malformed HTTP response "\x15\x03\x01\x00\x02\x02"] > Retry: all retry attempts failed
2018/02/28 22:08:39 [Info] [316557554] App|Proxyman|Inbound: connection ends > Proxy|Socks: connection ends > Proxy|Socks: failed to transport all TCP response > io: read/write on closed pipe
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
```
无异常
2018/02/28 13:24:40 127.0.0.1:25040 accepted tcp:easylist-downloads.adblockplus.org:443
2018/02/28 13:24:53 127.0.0.1:25048 accepted tcp:beacons.gcp.gvt2.com:443
2018/02/28 13:25:07 127.0.0.1:25052 accepted tcp:flora.web.telegram.org:443
2018/02/28 13:26:07 127.0.0.1:25068 accepted tcp:flora.web.telegram.org:443
```

8) 其它相关的配置文件（如 Nginx）和相关日志。
```
server {
        listen 443 ssl;
        server_name  host;

        ssl on;
        ssl_certificate      /etc/nginx/ssl/fullchain.cer;
        ssl_certificate_key  /etc/nginx/ssl/my.key;
        ssl_protocols  SSLv2 SSLv3 TLSv1;
        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        location /ws {
                proxy_pass http://127.0.0.1:9999;
                proxy_redirect off;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }
        root /var/www/host;
}

server {
  listen 80;
  listen [::]:80;
  server_name host;

  root /var/www/host;
  location ~ /.well-known/acme-challenge {
     allow all;
  }
  location / {
     return 301 https://host$request_uri;
  }
}
```
请预览一下你填的内容再提交。

如果你已经填完上面的问卷，请把下面的英文部份删除，再提交 Issue。
Please remove the Chinese section above.

English:
Please read the [instruction](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md) and answer the following questions before submitting your issue. Thank you.
Please answer all the questions with enough information. All issues not following this template will be closed immediately.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)

4) What's your expectation?

5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Server configuration:
```javascript
    // Please attach your server configuration here.
```

    Client configuration:
```javascript
    // Please attach your client configuration here.
```

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.

    Server error log:
```
    // Please attach your server error log here.
```
    Client error log:
```
    // Please attach your client error log here.
```

7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.
```
    // Please attach your server access log here.
```

Please review your issue before submitting.

8) Other configurations (such as Nginx) and logs.

**Comment by DarienRaymond** [comment]
你在nginx开了TLS之后，要把v2ray服务器的TLS关了

**Comment by scalaview** [comment]
服务器应该关掉tls，因为nginx已经做了，犯了个错误
