### ISSUE TITLE
其他地区正常，开启 TLS 后北京联通无法连接

### ISSUE THREAD

**Issue by junbaor** [v2ray/v2ray-core#893]
由于其他地区朋友们都可以连接，我就不贴客户端和服务端的配置了

客户端和服务端版本都是 `v 3.10` ，操作系统版本 Win 10, 使用 Caddy 实现的 TLS 。

北京联通（家和公司）开启 tls 后无法连接, 关闭 tls 使用普通方式可以正常使用。

可以 ping 通域名，下面是证书信息，希望能指出问题或者提供排查思路，感谢。

[![TIM截图20180228225847.png](https://i.loli.net/2018/02/28/5a96c3bb6682a.png)](https://i.loli.net/2018/02/28/5a96c3bb6682a.png)

**Comment by nicholascw** [comment]
Lack of info
