### ISSUE TITLE
路由器透明代理，开启UDP转发后，youtube视频一直转圈圈

### ISSUE THREAD

**Issue by hutozh** [v2ray/v2ray-core#895]
Please skip to the English section below if you don't write Chinese.

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
服务器3.10，客户端3.6
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
路由器透明代理
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
路由器开启udp转发后，chrome看youtube视频，可以打开网页，但视频一直转圈圈。（手机youtube客户端同样），chrome禁用quic后视频就可以正常播放了，但youtube手机客户端无法禁用quic。
路由器关闭udp转发后，chrome开quic也可以正常播放，但chromecast无法使用。。。
4)  你期待看到的正确表现是怎样的？
路由器开启udp转发，chrome开启quic的情况下可以正常播放。
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
```javascript
{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "error"
  },
  "inbound": {
    "port": 1234,
    "listen": "127.0.0.1",
    "protocol": "vmess",
    "settings": {
      "auth": null,
      "udp": true,
      "ip": null,
      "clients": [
        {
          "id": "XXXX",
          "alterId": 100,
          "security": "none"
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "security": "",
      "tcpSettings": null,
      "kcpSettings": null,
      "wsSettings": {
        "connectionReuse": true
      }
    }
  },
  "outbound": {
    "tag": null,
    "protocol": "freedom",
    "settings": null,
    "streamSettings": null,
    "mux": null
  },
  "inboundDetour": null,
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": null,
      "tag": "blocked"
    }
  ],
  "dns": null,
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": null,
      "rules": [
        {
          "type": "field",
          "port": null,
          "outboundTag": "blocked",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "domain": null
        }
      ]
    }
  }
}
```

    客户端配置:
```javascript
{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "domainOverride": ["tls","http"],
    "port": 12345,
    "protocol": "dokodemo-door",
    "settings": {
	  "network": "tcp,udp",
      "followRedirect": true,
      "udp": true
    }
  },
  "outbound": {
    "tag": "agentout",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "XXX.XXX.XXX",
          "port": 443,
          "users": [
            {
              "id": "XXXXXXXXX",
              "alterId": 100,
              "security": "chacha20-poly1305"
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "tcpSettings": null,
      "kcpSettings": null,
      "wsSettings": {
        "connectionReuse": true,
        "path": "/",
        "headers": {
          "Host": "XXXXX"
        }
      }
    },
    "mux": {
      "enabled": true
    }
  }
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
```
没有错误日志
```

    客户端错误日志:
```
    没有日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
```
    只有很多行accepted tcp:v1.mux.cool:9527 
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

**Comment by p4insh11** [comment]
"inbound": {
    "domainOverride": ["tls","http"],
    "port": 12345,
    "protocol": "dokodemo-door",
    "settings": {
	  "network": "tcp,udp",   ///////////注释掉可破，原因不明
      "followRedirect": true,
      "udp": true
    }

**Comment by hutozh** [comment]
@p4insh11 可以了，非常感谢。

**Comment by caonimac** [comment]
"network": "tcp,udp", ///////////注释掉，经测试就是关闭了udp转发。其实问题没有解决。

**Comment by caonimac** [comment]
"network": "tcp,udp", 改为"network": "tcp,udp,quic", 也能运行的，并且好像youtube能用，先看看再来反馈

**Comment by hutozh** [comment]
但是注释掉之后，youtube，chromecast都可以正常使用了。不删就不行。

**Comment by hutozh** [comment]
@DarienRaymond 能否给解释一下？

**Comment by hutozh** [comment]
不是说chromecast必须udp转发吗

**Comment by p4insh11** [comment]
所以这个问题非常奇怪，理论上和实际上配置都支持UDP转发，但是QUIC场景（手机app版U2B）会失败，这点我也很难理解，群里看到有说过QUIC是带序号
只能再次 @DarienRaymond 解释一下

**Comment by vikibg** [comment]
遇到类似问题，k3openwrt lede上运行客户端，现象Googleplay 无法正常显，YouTube正常，atv firetv 访问YouTube也正常。

**Comment by caonimac** [comment]
其实15天以前，同样配置看youtube是很流畅的，并且打开https://www.google.com，点击地址拦的小锁，查看证书，可以明确看到quic协议。

现在必须把quic关闭，才能youtube。

**Comment by hutozh** [comment]
突然想到quic不正常是不是因为nginx不支持quic？

**Comment by caonimac** [comment]
刚刚用redsocks2替代dokodemo-door，可以quic了。

不知道怎么回事，还是希望用回dokodemo-door。

**Comment by caonimac** [comment]
![screenshot_2018-03-28-18-04-40](https://user-images.githubusercontent.com/35394132/38023150-14a2337c-32b4-11e8-889a-78645c978e9e.png)
Redsocks2替代dokodemo-door，确认可以quic，鉴定完毕。有图为证。

**Comment by p4insh11** [comment]
@hutozh 好思路，有可能，caddy 据说是支持的，我在2号服务器试试，你也可以实验下

**Comment by caonimac** [comment]
Redsocks+cloudflare+nginx+ws+tls
确认可以quic

**Comment by p4insh11** [comment]
晚上我重新开一个issue出来，昨晚测试了一会，能确认UDP转发正常但是quic无法使用，iptable有TPROXY的UDP数据

**Comment by ShuoHuang** [comment]
> "inbound": {
> "domainOverride": ["tls","http"],
> "port": 12345,
> "protocol": "dokodemo-door",
> "settings": {
> "network": "tcp,udp", ///////////注释掉可破，原因不明
> "followRedirect": true,
> "udp": true
> }

你好，能帮我看下[https://github.com/v2ray/v2ray-core/issues/1341](1341)的第一个问题吗，与这个问题类似，我试过你的解决方案，没有成功
