### ISSUE TITLE
能否指定服务端的输出ip

### ISSUE THREAD

**Issue by kirbyzhu** [v2ray/v2ray-core#898]
问题描述：openvz，原ip正常，发ticket申请了一个新的cn2的ip，可能客服操作失误，两个ip都给我了，分别是venet0:0（CN2）和venet0:1（原ip）。前两天CN2的好像被同网段牵连，无法连接。但是原ip幸免，ssh原来的ip可以正常访问和操作。由于原ip不是系统默认的主ip，使用caddy和酸酸乳等在原ip监听都不能正常使用，可能是出口的数据使用CN2ip被墙。又无法修改默认的ip，也不敢再发ticket提醒客服注意。

现在使用 v2ray+cloudflare使用tls和cdn能够把cn2的ip用起来，用域名使用v2ray服务。但是由于通过了cdn中转，速度受限。

问题，能不能有办法在v2ray上设置都使用原ip监听和转发数据，相当于我仅仅使用venet0:1来完成v2ray的服务。

**Comment by DarienRaymond** [comment]
https://www.v2ray.com/chapter_02/01_overview.html

搜索`listen`和`sendThrough`关键字。
