### ISSUE TITLE
TLS 与Mux 之间的区别

### ISSUE THREAD

**Issue by N214** [v2ray/v2ray-core#899]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
3.0

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
访问互联网

3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）

本人有一个知识上的小问题，经过nginx web tls后发现网速明显下降，据说是TLS过程中握手导致的。
可如果在客户端上加mux协议，网速几乎与之前（裸vmess）相差无几，这是为什么？
还有的就是服务端的access log上之前都是走433端口的变成mux.cool:9527，这里有点不太明白

谢谢大家

**Comment by DarienRaymond** [comment]
TLS降速是正常的，因为多加了几层，包括你用的nginx转发，都会对速度有影响。Mux的提速是因为Mux把多个TCP流合成了一个，比如TLS握手包只有几十字节，同时浏览三个网页的话，需要三条连接分别传输这几十字节，而开启了Mux之后，这三条连接被合并成了一条，并且（几十字节*3）的数据也合并在了一个数据包里传输，所以体验到的速度变快了。

**Comment by N214** [comment]
好的好的，拿笔记本记一下😂。
谢谢微姐，搭建时学到了很多知识这才是最重要的。

**Comment by Cwek** [comment]
我觉得用点脑子和多RTFM就大概能理解吧。
协议栈的传输效率就是套的越多，有效负载数据越少，传输速度（也就是相同的包交换频率下）越慢。

**Comment by agzfan** [comment]
开Mux更快绝对是心理作用
我长期拿来下载(bt gd),观察了很久Mux打开会导致经常速度波动大,很慢,关了后下载会稳定很多

**Comment by Cwek** [comment]
@agzfan 的确不一定会快（也就是多条“逻辑上的”TCP线路挤在一条“实际的”TCP线路，怎么会快？协议叠得越多，传输速度越慢。），只是有助于聚合并发连接，避免频繁新建TCP连接，和适当地隐藏网页请求特征。

**Comment by DarienRaymond** [comment]
https://toutyrater.github.io/advanced/mux.html

**Comment by xiaorong61** [comment]
> 开Mux更快绝对是心理作用 我长期拿来下载(bt gd),观察了很久Mux打开会导致经常速度波动大,很慢,关了后下载会稳定很多

带宽和加载速度是两码事，如果是加载大量小的 http 请求，连接复用会降低很多延迟。
