### ISSUE TITLE
v2ray是否支持绑定特定IP和非连续端口动态切换

### ISSUE THREAD

**Issue by zxcso** [v2ray/v2ray-core#90]
看了配置教程，但是没有看到怎样才能让v2ray绑定特定的IP，请问怎么弄。另外动态端口是否可以支持非连续的，因为我使用了CN2线路的加速，分配的端口并非连续的，并且动态分配端口是采用服务端推送配置，如过有中专，端口可能不同（即服务端监听端口与客户端监听端口不同），是否可以支持服务端客户端分别配置。

**Comment by v2ray** [comment]
1. 如果你是指监听本机的特定 IP，那暂时还不支持，V2Ray 会监听本机所有的 IP；
2. 暂不支持非连续的端口；
3. 你需要使用 V2Ray 进行中转，如果中转的程序不理解 V2Ray 的指令，客户端再怎么配置也是没有意义的。

实际上我太理解你的使用方法，能否详细地描述一下。

**Comment by zxcso** [comment]
基本架构
![gfw](https://cloud.githubusercontent.com/assets/7419060/13377848/1cbb4fe0-de28-11e5-972c-819d15f7b38c.png)
中国电信有两套网络，老网络ChinaNet和下一代网络CN2
由于ChinaNet主要是面向国内的普通大众，没有QoS，国际链路没有优化，使用的人非常多，直接翻墙速度比较慢。
比如：
![srebn92z0g n9r 1 7 e 8_q](https://cloud.githubusercontent.com/assets/7419060/13377880/2a80d568-de29-11e5-932a-693aca2944fe.png)
而CN2却不一样，面向企业，有QoS，国际链路有优化。
于是：
![q 3 pk hnqbj085 2o n3_q](https://cloud.githubusercontent.com/assets/7419060/13377900/5f3c9dfe-de2a-11e5-91e1-e43bcc75222a.png)
瞬间提速10-15倍
但是问题来了，线路转发服务商只开放30000-40000这些端口，而且是随机分配。
所以就需要非连续动态端口。
假定服务器主端口20，转发30001，动态端口21-25，转发端口30002，30059，30065，30022
客户端无法配置动态端口，于是，服务器叫客户端去监听22，但实际上转发服务器的22是不开放的，于是就无法传输数据，那好呗，重新设置服务端，让服务器也监听这些端口，但是，重新配置过转发服务器的端口又变了，所以还是无法传输数据。
所以就有了上面的问题。

**Comment by v2ray** [comment]
如果我没有理解错的话，你在厦门的服务器中没有运行 V2Ray，而是直接做了某种类似 iptables 的转发。在这种情况下，动态端口是无论如何都不能正常工作的。因为厦门的服务器不能理解 V2Ray 的动态端口指令，它无法把数据转发到正确的端口。

在这种情况下，你可以在 EC2 的 V2Ray 中开启 N 个端口（非动态），类似这样：

```javascript
"inboundDetour": [
  {
    "protocol": "vmess",
    "port": 30001,
    "settings": {
      "clients": [{ "id": "3b129dec-72a3-4d28-aeee-028a0fe86e22"}]
    }
  },
  {
    "protocol": "vmess",
    "port": 30002,
    "settings": {
      "clients": [{ "id": "3b129dec-72a3-4d28-aeee-028a0fe86e22"}]
    }
  },
  // 以此类推
]
```

客户端使用[多服务器模式](https://www.v2ray.com/zh_cn/chapter_05/00_config/01_multi_server.html)连接。这样可以做到多个端口负载均衡的效果，也可以解决你的转发服务器端口映射的问题。

**Comment by zxcso** [comment]
嗯，现在就在这样使用，另外问一下，在动态端口开启之后，主端口是只用于发送命令还是也会传输数据？

**Comment by v2ray** [comment]
会传输数据，但客户端会在有动态端口的时候优先选择动态端口，直到动态端口过期之后，才回到主端口。

**Comment by zxcso** [comment]
谢谢，还有一个问题。。。就是在多服务器模式下是否可以开启动态端口？我想一下是可以，因为动态端口是由服务端指定的。。。

**Comment by v2ray** [comment]
动态端口是单个服务器的特性，如果你有多台服务器，每台服务器可以使用不同的配置而互相不会冲突。

**Comment by maxchendt** [comment]
https://www.v2ray.com/en/chapter_00/versions.html 中 2016.06.05 v1.15  开始 "Allow listening on a specific IP address". 具体配置方法参见  https://www.v2ray.com/chapter_02/01_overview.html ,  例如

    "listen": "127.0.0.1",
