### ISSUE TITLE
是否有进驻Homebrew仓库或者自建tap的计划

### ISSUE THREAD

**Issue by mzxwt** [v2ray/v2ray-core#901]
首先感谢大神的作品！
最近使用doublemine的tap安装和更新v2ray感觉很方便，不足之处就是更新相对慢一些，同时担心这个tap能坚持更新多久。看到大概半年前在v2ex上有讨论关于v2ray-core进驻Homebrew仓库的帖子，不知道大神有没有计划，方便吾等小白更新v2ray-core。另外，Linux的一键安装脚本能否一并移至GitHub。期待回复，非常感谢！

**Comment by Voleking** [comment]
像我一样自建一个，自己把控更新速度。

**Comment by DarienRaymond** [comment]
暂时没有这类的计划，各种仓库太多管不过来。我给doublemine发了一个[issue](https://github.com/Doublemine/homebrew-v2ray/issues/1)，提议做自动化的更新。

[安装脚本](https://github.com/v2ray/v2ray-core/blob/master/release/install-release.sh)已经在repo里了，网站上看到的内容是一样的。

**Comment by Doublemine** [comment]
@mzxwt 正常情况下，自动更新的延时不会超过24小时。

**Comment by mzxwt** [comment]
@Doublemine 感谢回复，希望可以坚持做下去！非常感谢各位的付出！衷心感谢！

**Comment by DarienRaymond** [comment]
感谢 @Doublemine ，[repo](https://github.com/v2ray/homebrew-v2ray)已经转移到v2ray org。
