### ISSUE TITLE
"geosite:cn""geoip:cn"有问题?

### ISSUE THREAD

**Issue by agzfan** [v2ray/v2ray-core#904]
同一台hk服务器tls tcp

2个配置客户端,相同的dns

客户端1: v2ray tls tcp+chrome ("geosite:cn""geoip:cn"开)
客户端2:v2ray tls tcp+firefox ("geosite:cn""geoip:cn"等路由全关)

客户端1打开下面2个网站被秒断
veracrypt.codeplex.com
netflix.com
------------------------
无法访问此网站
连接已重置。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
运行 Windows 网络诊断
ERR_CONNECTION_RESET
------------------------

客户端2能正确打开这2个网站
大家试试看,是否我一个人的问题.....

**Comment by Cwek** [comment]
贴配置文件先，是不是中继设置错误？

还有不会控制环境变量，不应该统一使用相同浏览器配置来测试？
Chrome，socks代理使用Switchy插件的话，域名请求是通过发送域名给V2处理，不需要请求DNS。
Firefox，socks代理使用FoxyProxy的话，在开远程DNS解析的话，理论上是先用V2请求远程DNS获得IP后，再发送IP请求V2处理。反之，和Chrome的情况一致。

"geosite:cn"、"geoip:cn"要配合适当的DNS和路由配置才能有效的。

**Comment by agzfan** [comment]
我用的是http没用socks

**Comment by Cwek** [comment]
猜测：
1.请求目标主机是域名，配置了cnsite匹配的，就用域名继续分类请求，否则使用DNS配置获得IP，再按照IP请求。
2.请求目标主机是IP，按照geoip分类请求。
0.1.如果v2的DNS配置，可能回到域名请求取得错误的IP（包括污染地址，或者分配到不适合地区的地址）

**Comment by DarienRaymond** [comment]
请使用issue模板并附上详细的配置和日志。

**Comment by DarienRaymond** [comment]
猜测原因是DNS污染。
