### ISSUE TITLE
服务端的v2ray启动不了怎么办

### ISSUE THREAD

**Issue by xianfishAh** [v2ray/v2ray-core#908]
输入service v2ray status后显示：

● v2ray.service - V2Ray Service
   Loaded: loaded (/lib/systemd/system/v2ray.service; enabled)
   Active: failed (Result: start-limit) since Sat 2018-03-03 14:57:01 CST; 20min ago
  Process: 8132 ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json (code=exited, status=255)
 Main PID: 8132 (code=exited, status=255)

Mar 03 14:57:01 xianfish systemd[1]: Unit v2ray.service entered failed state.
Mar 03 14:57:01 xianfish systemd[1]: v2ray.service holdoff time over, sched...t.
Mar 03 14:57:01 xianfish systemd[1]: Stopping V2Ray Service...
Mar 03 14:57:01 xianfish systemd[1]: Starting V2Ray Service...
Mar 03 14:57:01 xianfish systemd[1]: v2ray.service start request repeated t...t.
Mar 03 14:57:01 xianfish systemd[1]: Failed to start V2Ray Service.
Mar 03 14:57:01 xianfish systemd[1]: Unit v2ray.service entered failed state.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by DarienRaymond** [comment]
用 `journalctl -u v2ray` 看一下具体的错误。

**Comment by xianfishAh** [comment]
再次重装重启一系列后，正常启动用上了，原因不明
