### ISSUE TITLE
3.11版路由器无法启动,InboundHandlerManager not set

### ISSUE THREAD

**Issue by hutozh** [v2ray/v2ray-core#909]
Please skip to the English section below if you don't write Chinese.

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
3.11
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
路由器透明代理 
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
路由器由3.6更新到3.11版，无法启动，提示InboundHandlerManager not set
4)  你期待看到的正确表现是怎样的？
路由器能够启动
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
```javascript
{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "error"
  },
  "inbound": {
    "port": 1234,
    "listen": "127.0.0.1",
    "protocol": "vmess",
    "settings": {
      "auth": null,
      "udp": true,
      "ip": null,
      "clients": [
        {
          "id": "XXXX",
          "alterId": 100,
          "security": "none"
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "security": "",
      "tcpSettings": null,
      "kcpSettings": null,
      "wsSettings": {
        "connectionReuse": true
      }
    }
  },
  "outbound": {
    "tag": null,
    "protocol": "freedom",
    "settings": null,
    "streamSettings": null,
    "mux": null
  },
  "inboundDetour": null,
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": null,
      "tag": "blocked"
    }
  ],
  "dns": null,
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": null,
      "rules": [
        {
          "type": "field",
          "port": null,
          "outboundTag": "blocked",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "domain": null
        }
      ]
    }
  }
}
```

    客户端配置:
```javascript
{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "domainOverride": ["tls","http"],
    "port": 12345,
    "protocol": "dokodemo-door",
    "settings": {
      "followRedirect": true,
    }
  },
  "outbound": {
    "tag": "agentout",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "XXX.XXX.XXX",
          "port": 443,
          "users": [
            {
              "id": "XXXXXXXXX",
              "alterId": 100,
              "security": "chacha20-poly1305"
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "tcpSettings": null,
      "kcpSettings": null,
      "wsSettings": {
        "connectionReuse": true,
        "path": "/",
        "headers": {
          "Host": "XXXXX"
        }
      }
    },
    "mux": {
      "enabled": true
    }
  }
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
```
    // 在这里附上服务器端日志
```

    客户端错误日志:
```
V2Ray v3.11 (die Commanderin) 20180301
An unified platform for anti-censorship.
Main: failed to create server > Core: InboundHandlerManager not set.

```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
```
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

请预览一下你填的内容再提交。

**Comment by DarienRaymond** [comment]
请使用最新版的v2ctl

**Comment by hutozh** [comment]
@DarienRaymond 路由器中没使用v2ctl，按https://steemit.com/cn/@v2ray/meemg-v2ray配置文件转为pb

**Comment by hutozh** [comment]
@DarienRaymond 另外想请教，以上配置，可以删除的模块都是有哪些，谢谢。

**Comment by DarienRaymond** [comment]
除了你用到的socks, vmess, ws, router,和必须有的dispatcher, inbound/outboundhandlermanager, 其它都可以删

**Comment by hutozh** [comment]
@DarienRaymond 现在的版本，必须使用v2ctl了吗？

**Comment by hutozh** [comment]
@DarienRaymond ws+tls，保留以下模块可以吗？还有用不到的模块吗？
	// Required features. Can't remove unless there is replacements.
	_ "v2ray.com/core/app/dispatcher"
	_ "v2ray.com/core/app/proxyman/inbound"
	_ "v2ray.com/core/app/proxyman/outbound"

	// Default commander and all its services.
	_ "v2ray.com/core/app/commander"
	_ "v2ray.com/core/app/log/command"
	_ "v2ray.com/core/app/proxyman/command"

	// Other optional features.
	_ "v2ray.com/core/app/log"

	// Inbound and outbound proxies.
	_ "v2ray.com/core/proxy/dokodemo"
	_ "v2ray.com/core/proxy/vmess/outbound"

	// Transports
	_ "v2ray.com/core/transport/internet/tls"
	_ "v2ray.com/core/transport/internet/websocket"

	// Transport headers

	// JSON config format
	_ "v2ray.com/core/main/json"

**Comment by DarienRaymond** [comment]
如果你手动使用v2ctl转换的话，上面的/main/json可以删掉，启动v2ray的时候传入pb格式的配置即可。

另外commander那三行也不是必要的。

**Comment by hutozh** [comment]
@DarienRaymond 请问那三行commander分别负责什么？另外我使用pb格式，没使用v2ctl，就出现Main: failed to create server > Core: InboundHandlerManager not set.错误提示。

**Comment by DarienRaymond** [comment]
远程控制，对于你的场景来说基本用不到。

用最新版的v2ctl重新转换一下配置文件。

**Comment by hutozh** [comment]
@DarienRaymond log模块不可以删除吗？删除后提示：Main: failed to create server > Serial: Unknown type: v2ray.core.app.log.Config

**Comment by DarienRaymond** [comment]
嗯，暂时不行
