### ISSUE TITLE
华硕AC68U安装V2RAY不成功且无任何日志

### ISSUE THREAD

**Issue by jokerqing** [v2ray/v2ray-core#911]
中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v2ray-linux-arm v3.11
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
华硕AC68U，koolshare梅林固件上手动下载v2ray-linux-arm安装
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
用命令/jffs/v2ray/v2ray --config=/jffs/v2ray/config.json启动无报错，但无法正常翻墙，curl -x socks5://127.0.0.1:1080 google.com命令返回Connection timed out。日志改为debug也无任何信息，只有启动的两条。
4)  你期待看到的正确表现是怎样的？
正常运行v2ray
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
```javascript
{
   "log":{
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "debug"
   },
   "inbound":{
      "port":1080,
      "listen":"0.0.0.0",
      "protocol":"socks",
      "settings":{
         "auth":"noauth",
         "udp":false,
         "ip":"127.0.0.1"
      }
   },
   "inboundDetour":[
      {
         "protocol":"dokodemo-door",
         "port":1060,
         "settings":{
            "address":"",
            "network":"tcp,udp",
            "timeout":30,
            "followRedirect":true
         }
      }
   ],
   "outbound":{
      "protocol":"vmess",
      "streamSettings":{
         "network":"tcp",
		 "security":"tls"
      },
      "settings":{
         "vnext":[
            {
               "address":"",
               "port":10086,
               "users":[
                  {
                     "id":"",
                     "alterId":32,
                     "security":"aes-128-gcm"
                  }
               ]
            }
         ]
      },
      "mux":{
         "enabled":true
      }
   },
   "outboundDetour":[
      {
         "protocol":"freedom",
         "settings":{
         },
         "tag":"direct"
      }
   ],
   "dns":{
      "servers":[
         "8.8.8.8",
         "8.8.4.4",
         "localhost"
      ]
   },
   "routing":{
      "strategy":"rules",
      "settings":{
         "domainStrategy":"IPIfNonMatch",
         "rules":[
            {
               "type":"field",
               "port":"1-52",
               "outboundTag":"direct"
            },
            {
               "type":"field",
               "port":"54-79",
               "outboundTag":"direct"
            },
            {
               "type":"field",
               "port":"81-442",
               "outboundTag":"direct"
            },
			{
               "type":"field",
               "port":"444-65535",
               "outboundTag":"direct"
            },
            {
               "type":"chinasites",
               "outboundTag":"direct"
            },
            {
               "type":"field",
               "ip":[
                  "0.0.0.0/8",
                  "10.0.0.0/8",
                  "100.64.0.0/10",
                  "127.0.0.0/8",
                  "169.254.0.0/16",
                  "172.16.0.0/12",
                  "192.0.0.0/24",
                  "192.0.2.0/24",
                  "192.168.0.0/16",
                  "198.18.0.0/15",
                  "198.51.100.0/24",
                  "203.0.113.0/24",
                  "::1/128",
                  "fc00::/7",
                  "fe80::/10"
               ],
               "outboundTag":"direct"
            },
            {
               "type":"chinaip",
               "outboundTag":"direct"
            }
         ]
      }
   }
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

2018/03/03 15:05:28 [Debug] App|Log: Logger started
2018/03/03 15:05:28 [Warning] Core: V2Ray v3.11 started

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。

访问日志为空。无任何信息

8) 其它相关的配置文件（如 Nginx）和相关日志。

奇怪的一点是。错误日志的时间与本地时间不同。但梅林管理页面是正确的。也就是说。telnet和梅林管理界面时间不一致。不知这个问题是否与空白页面有关，以及如何解决

**Comment by DarienRaymond** [comment]
你可以试一下用freedom出口，curl baidu.com 有什么现象，以确定具体原因。

**Comment by jokerqing** [comment]
@DarienRaymond 感谢您的回复。昨天已经尝试过curl -x socks5://127.0.0.1:1080 baidu.com。返回正常。但是我发现输入任何一个端口。如socks5://127.0.0.1:10124。socks5://127.0.0.1:1083。全都可以正常返回百度。但是都不可以访问google

**Comment by gbmeco** [comment]
期待成功。希望可以共享一下经验。相信很多人现在都和我一样在找路由器使用v2ray 的教程。 

谢谢！

**Comment by DarienRaymond** [comment]
几个调试建议：
1. 如果你用了自签TLS证书，你需要在客户端指定`"allowInsecure": true`。
2. 把客户端的log.level设为"debug"看一下具体的错误信息。
3. `curl --socks5-hostname 127.0.0.1:1080 -v https://www.google.com"`

**Comment by eMeab** [comment]
好好看下官网啊
"inboundDetour": [
        {
         "domainOverride": ["tls","http"],
         "port": ,
         "protocol": "dokodemo-door",
         "settings": {
             "network": "tcp,udp",
             "followRedirect": true
            }
        }
    ],
这样就可以路由器透明代理了 要配置好iptables

**Comment by yevision94** [comment]
按照这个来https://gist.github.com/wd/e0bc83b33ce63506a9bdbc3b81658c52
昨晚刚折腾成功，走一遍后发现还是蛮简单的，建议先拉下去看步骤

**Comment by gimmeangel** [comment]
请问这个问题解决了吗？是如何解决的？ 我也遇到了这个问题，而且在软件中心V2ray的运行状态上显示红色字体的“规则未运行”，各位上面的帖子都看了，也试了试，依然没有能解决这个问题。现在就是透明代理不行，如果在PC上用V2ray客户端功能完全正常。

如果各位大神有解决这个问题，请告之，感谢。

**Comment by zhric** [comment]
请问这个问题解决了吗？ 我也出现了相同问题，路由器是66U-B1，v2ray 是自己在路由器上编译的，版本是 4.33.0
启动日志：
`2020/12/09 10:01:51 [Debug] v2ray.com/core/app/log: Logger started
2020/12/09 10:01:51 [Debug] v2ray.com/core/app/proxyman/inbound: creating stream worker on 127.0.0.1:8000
2020/12/09 10:01:51 [Debug] v2ray.com/core/app/proxyman/inbound: creating stream worker on 0.0.0.0:8100
2020/12/09 10:01:51 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:8000
2020/12/09 10:01:51 [Info] v2ray.com/core/transport/internet/udp: listening UDP on 127.0.0.1:8000
2020/12/09 10:01:51 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 0.0.0.0:8100
2020/12/09 10:01:51 [Info] v2ray.com/core/transport/internet/udp: listening UDP on 0.0.0.0:8100
2020/12/09 10:01:51 [Warning] v2ray.com/core: V2Ray 4.33.0 started`

同样也是控制台日志少8个小时。 access.log 是空的
