### ISSUE TITLE
删改了all.go，可是编译的Mipsle版本为什么还是那么大

### ISSUE THREAD

**Issue by 523860169** [v2ray/v2ray-core#913]
按照这个[教程](https://steemit.com/cn/@v2ray/meemg-v2ray)，自我感觉已经删掉很多了，可是编译出来的v2ray还是有5.96M，完全不像教程里说的只有4M多，请问是否有什么其他特别的技巧
编译命令
`bin\vbuild -os=linux -arch=mipsle`

all.go
```
package all
import (
	_ "v2ray.com/core/app/dispatcher"
	_ "v2ray.com/core/app/proxyman/inbound"
	_ "v2ray.com/core/app/proxyman/outbound"
	_ "v2ray.com/core/app/log"
	_ "v2ray.com/core/proxy/dokodemo"
	_ "v2ray.com/core/proxy/vmess/outbound"
	_ "v2ray.com/core/transport/internet/tls"
	_ "v2ray.com/core/transport/internet/websocket"
)

```

config.json
```
{
  "log": {
    "loglevel": "warning"
  },
  "inbound": {
    "port": 1080,
    "listen": "0.0.0.0",
    "protocol": "dokodemo-door",
    "settings": {
      "followRedirect": true
    },
    "domainOverride": ["http", "tls"]
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "I'm IP",
          "port": 443,
          "users": [
            {
              "id": "I'm UUID",
              "alterId": 32,
              "security": "none"
            }
          ]
        },{
          "address": "I'm IP",
          "port": 443,
          "users": [
            {
              "id": "I'm UUID",
              "alterId": 32,
              "security": "none"
            }
          ]
        },{
          "address": "I'm IP",
          "port": 443,
          "users": [
            {
              "id": "I'm UUID",
              "alterId": 32,
              "security": "none"
            }
          ]
        }
      ]
    },
    "mux": {
      "enabled": true
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "tlsSettings": {
        "serverName": "I'm SN"
      },
      "wsSettings": {
        "headers": {
          "Host": "I'm HOST"
        }
      }
    }
  }
}

```

**Comment by 523860169** [comment]
又删了几行，现在5.96M
all.go
```
package all
import (
	_ "v2ray.com/core/app/dispatcher"
	_ "v2ray.com/core/app/proxyman/inbound"
	_ "v2ray.com/core/app/proxyman/outbound"
	_ "v2ray.com/core/app/log"
	_ "v2ray.com/core/proxy/dokodemo"
	_ "v2ray.com/core/proxy/vmess/outbound"
	_ "v2ray.com/core/transport/internet/tls"
	_ "v2ray.com/core/transport/internet/websocket"
)

```

**Comment by DarienRaymond** [comment]
每个平台的文件大小略有差异，比如macOS就比其它平台都大一点。你的配置中，如果把websocket删掉应该可以达到4M左右，但websocket一个组件就是这么大，没办法。

**Comment by 523860169** [comment]
也只能把程序放在/tmp里了，希望以后有可能libev吧，谢谢

**Comment by hutozh** [comment]
Arm 的5.3m，同样模块

**Comment by tEstCJN** [comment]
@523860169 
看的同一个教程。
    我的all.go文件配置:
```javascript
package all

import (
	_ "v2ray.com/core/app/dispatcher"
	_ "v2ray.com/core/app/proxyman/inbound"
	_ "v2ray.com/core/app/proxyman/outbound"
	_ "v2ray.com/core/app/log"
	_ "v2ray.com/core/proxy/dokodemo"
	_ "v2ray.com/core/proxy/freedom"
	_ "v2ray.com/core/proxy/vmess/outbound"
	_ "v2ray.com/core/transport/internet/kcp"
	_ "v2ray.com/core/transport/internet/headers/utp"
	_ "v2ray.com/core/main/json"
)
```
编译完成后，linux安装upx并运行"upx -9 v2ray"压缩一下，文件大小为1,584KB(我的情况)
K2路由器空间不多，所以用了v2ray+gfwlist方式，geoip和geosite两大文件也可以不要

另外，看见狐吧基佬[滑稽]

**Comment by hutozh** [comment]
好像使用pb格式配置文件，也可以不用geoip和geosite，我看pb配置文件里包含网址列表了。但是我没验证过。

**Comment by 523860169** [comment]
我没用路由功能，所以也没传geo那两个文件，不然光是程序就6M，再加上那两个文件，就十几M了

**Comment by wclmgcd** [comment]
可以发一下编译好的mipsle给我吗?电脑上tls+websocket,感觉还是不如路由器方便.但我自己按https://steemit.com/cn/@v2ray/meemg-v2ray这个编译,GOPATH/bin/vbuild -os=linux -arch=mipsle这一步,出现 GOPATH/bin/vbuild: No such file or directory.

**Comment by wclmgcd** [comment]
发邮件wuceyi@gmail.com,感谢

**Comment by 523860169** [comment]
cd /d "D:\Program Files\go"
bin\vbuild -os=linux -arch=mipsle

**Comment by wclmgcd** [comment]
感谢,已成功.另外
顺便介绍一下如何在路由器中绕过 v2ctl 程序的限制。
    准备好你的配置文件 config.json
    在 PC 上把它转换成 Protobuf 格式：v2ctl config < config.json > config.pb
    在路由器运行 V2Ray：v2ray -config=config.pb

这里,在 PC 上把它转换成 Protobuf 格式,这个使用什么命令?或者软件?

还有https://gobomb.github.io/post/cross-complie-v2ray/这里提到用upx 来压缩v2ray是否可行?压缩后还能在openwrt运行?

**Comment by 523860169** [comment]
解压win端的v2ray到D:\工具\翻墙\v2ray
cd /d "D:\工具\翻墙\v2ray"
v2ctl config < WiFi.json > v2ray.pb

**Comment by 523860169** [comment]
下载https://github.com/upx/upx/releases/download/v3.94/upx394w.zip，解压里面的upx.exe到D:\Program Files\go\bin里，然后执行编译后多执行一条命令，目前是把5.96M压缩到1.84M，路由器测试运行正常
cd /d "D:\Program Files\go"
bin\vbuild -os=linux -arch=mipsle
upx v2ray-custom-linux-mipsle\v2ray

**Comment by wclmgcd** [comment]
我把压缩后的v2ray和config.pb,放入路由/usr/bin,执行v2ray -config=config.pb -format=pb提示
Illegal instruction,极路由1s,cc15.05版本

**Comment by wclmgcd** [comment]
找到原因,LEDE内核需要支持MIPS FPU Emulator 才能正常运行golang编译的二进制执行文件, 否则运行时会显示 Illegal instruction.

**Comment by 523860169** [comment]
softfloat版本好像就是给没有启用FPU的固件用的，不过听说softfloat会损失性能

**Comment by wclmgcd** [comment]
还是不行,一样 Illegal instruction

**Comment by 523860169** [comment]
那要不你重新开一个issue问一下fpu这个问题吧

**Comment by wclmgcd** [comment]
用编译好的可以用,自己编译的不行,编译好的里面softfloat版本的和v2ray版的大小有区别,而自己编译的softfloat版本和v2ray版的大小是一样的,不知道是哪里出现问题

**Comment by wclmgcd** [comment]
我的极路由1s已经自己编译固件,透明代理.现在的问题是v2ray 运行config.json时,cpu占用过大,只能采用v2ray -config=config.pb -format=pb,但这个只能在putty中输入,并且不能关闭putty.有什么办法能把这个命令加入到路由器的开机启动吗?

**Comment by 523860169** [comment]
@DarienRaymond 新版是不是改了什么，按主楼自定义后，启动不了，改好了好几个地方还是一直不行

**Comment by DarienRaymond** [comment]
@523860169 新开一个 issue 发具体信息

**Comment by tEstCJN** [comment]
@523860169 
多次修改后，发现精简了这行就不行，上次修改3.15版本时还没有这行。
_ "v2ray.com/core/main/confloader/external"

我的配置是v2ray+kcp
`
all.go

package all
import (
	_ "v2ray.com/core/app/dispatcher"
	_ "v2ray.com/core/app/proxyman/inbound"
	_ "v2ray.com/core/app/proxyman/outbound"
	_ "v2ray.com/core/app/log"
	_ "v2ray.com/core/proxy/dokodemo"
	_ "v2ray.com/core/proxy/freedom"
	_ "v2ray.com/core/proxy/vmess/outbound"
	_ "v2ray.com/core/transport/internet/kcp"
	_ "v2ray.com/core/transport/internet/headers/srtp"
	_ "v2ray.com/core/transport/internet/headers/utp"
	_ "v2ray.com/core/transport/internet/headers/wechat"
	_ "v2ray.com/core/main/confloader/external"
)

`

**Comment by 523860169** [comment]
@DarienRaymond 好了，不知是路由器还是浏览器缓存导致，路由器上启动v2ray后，浏览器浏览被屏蔽网页却还是不能访问，刚刚启动了几分钟后再浏览，就发现正常了

**Comment by rc452860** [comment]
@523860169 能压缩到2M内？

**Comment by 523860169** [comment]
@rc452860 以前可以，现在不行了

**Comment by rc452860** [comment]
@523860169 好的，感谢。
