### ISSUE TITLE
路由中针对端口设置是否启用粘滞模式，以及超时时间

### ISSUE THREAD

**Issue by cjjdaq** [v2ray/v2ray-core#914]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v3.11
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
遨游互联网
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
负载均衡无法会话保持,虽然可以通过添加另外的outbound（单一服务器）进行域名归类，但终归没有针对目标端口进行会话保持+超时时间主要方便，而且能更有效的利用多组服务器。
4)  你期待看到的正确表现是怎样的？
能够在路由中针对端口设置是否启用粘滞模式，以及超时时间。以及达到来自相同源 IP 的流量，如果已经匹配过此规则并且在粘滞超时时间内，将会使用相同的服务器出口
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
```javascript
    // 在这里附上服务器端配置文件
```

    客户端配置:
```javascript
{
    "log": {
        "access": "/tmp/log/Vaccess.log",
        "error": "/tmp/log/Verror.log",
        "loglevel": "warning"
    },
    "inbound": {
		"protocol": "dokodemo-door",
        "port": 1080,
        "address": "",
        "settings": {
			"followRedirect": true
        }
    },
 "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "111.111.111.111",
          "port": 443,
          "users": [
            {
              "id": "92329e79-ee98-4b9a-9963-6f9365550dae",
              "alterId": 64
            }
          ]
        }，
{
          "address": "222.222.222.222",
          "port": 443,
          "users": [
            {
              "id": "92329e79-ee98-4b9a-9963-6f9365550dae",
              "alterId": 64
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
	   "tlsSettings": {
        "serverName": "fan.abc.com"
      },
      "wsSettings":{
          "path":"/abasd"
      }
    }
  },
    "mux": {"enabled": true},
    "inbounddetour": [
    {
     "port": 1081,
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true
    }
    }
  ]
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
```
    // 在这里附上服务器端日志
```

    客户端错误日志:
```
    // 在这里附上客户端日志
```

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
```
    // 在这里附上服务器端日志
```

8) 其它相关的配置文件（如 Nginx）和相关日志。

**Comment by DarienRaymond** [comment]
能提供一个你期望中的路由配置并加以说明吗？

**Comment by cjjdaq** [comment]
{
  "type": "field",
  "ip": [
    "0.0.0.0/8",
    "10.0.0.0/8",
    "fc00::/7",
    "fe80::/10",
    "geoip:cn"
  ],
  "port": "0-100",
  "network": "tcp",
  "source": [
    "10.0.0.1",
  ],
"sticky":"true",//粘滞模式,已经匹配过此规则并且在粘滞超时时间内，将会使用相同的服务器出口
"timeout":"600", //粘滞超时,单位为秒。留空则使用默认值 600 秒
  "inboundTag": [
    "tag-vmess"
  ],
  "outboundTag": "direct"
}

**Comment by cjjdaq** [comment]
是被挂起了么

**Comment by VictoriaRaymond** [comment]
目前没有计划实现此功能。
