### ISSUE TITLE
请求添加骗过isp qos的混淆功能

### ISSUE THREAD

**Issue by agzfan** [v2ray/v2ray-core#918]
一些vps qos太厉害了,比如hk那边的
ssr的tls可以骗过qos但是封的厉害

最近ss出了一个tls插件也可以骗过qos
https://github.com/cbeuw/GoQuiet/wiki/GoQuiet

希望v2ray也能提供类似功能
v2ray tls+http混淆我测试不能骗过qos

**Comment by DarienRaymond** [comment]
如果你有具体的需求，比如运营商的QoS是如何运作的，以及如何绕过，否则项目组无法提供帮助。

如果你觉得V2Ray做不到GoQuiet的功能，是你的配置不对。请按issue模板提交。
