### ISSUE TITLE
x509: failed to load system roots and no roots provided

### ISSUE THREAD

**Issue by ticonci** [v2ray/v2ray-core#919]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
v3.11.3, v2ray_softfloat, mpls
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
路由器
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
x509: failed to load system roots and no roots provided
4)  你期待看到的正确表现是怎样的？
没见过这个报错，和go有关系吗？

x509: failed to load system roots and no roots provided
这个报错和go有关系吗？

**Comment by 523860169** [comment]
安装ca-certificates

**Comment by ticonci** [comment]
@523860169  谢谢搞定了
