### ISSUE TITLE
Does 'alterId''s value affects VPS performance?

### ISSUE THREAD

**Issue by Sherman-Liu** [v2ray/v2ray-core#92]
Does the 'alterId''s value affect VPS performance?

The value in my server and client's config.json shows "alterId": 1024 (and it's working fine),but I just noticed that the default config.json in /etc/v2ray/ from right after running the install script shows "alterId": 64,should I change the value in my file to 64?

Does this affect anything?

**Comment by v2ray** [comment]
alterId affects the amount of memory used by V2Ray process. The previous setting of 1024 causes over 50 MB usage. Combined with the dynamic port feature, total memory usage could be several hundreds of MB. I reduced the default value of "alterId" simply because many people complained about memory usage.

The communication speed of V2Ray is not affected by "alterId", unless V2Ray uses too much memory and triggers swapping.

More details here: https://www.v2ray.com/zh_cn/chapter_03/01_effective.html#alterid

**Comment by Sherman-Liu** [comment]
Thanks for the clarification.

**Comment by v2ray** [comment]
Depend on your network usage. I recommend the value to be the number of average network connections per second to your VPS. Say 30 to 40 for a regular usage. 100 is definitely safe for a single user VPS.

**Comment by Sherman-Liu** [comment]
Though this issue was closed, I have to say that from what I've tested today, the 'alterid' value affects bandwidth a lot, especially on my low-end VPS server(1 CPU, 768M Memory, 25G SSD).

Before changing the value (alterid:1024), the test showed(sorry I forgot to do a screenshot) [PING:140 Download Speed:1.46Mbps Upload Speed:0.9Mbps], which was pretty sad.

After changing the value (alterid:200), the test showed 
![vultr-jp](https://cloud.githubusercontent.com/assets/11748513/13255370/d6a887e8-da80-11e5-9fbb-1f8263a1d559.png)
 [PING:99 Download Speed:5.3Mbps Upload Speed:2.35Mbps],I‘m quite satisfied with this result now.

**Comment by v2ray** [comment]
Can you choose a location with the same ping for test?

**Comment by Sherman-Liu** [comment]
Actually both tests was on the same location, same server, just different alterid value. I don't have a clue why the ping value mismatch so much.

I'll try testing again tomorrow morning, and see if I can recreate the result.

**Comment by Sherman-Liu** [comment]
I've done the testing this morning, in this method: test the speed---stop the v2ray service---change the alterid value in the config.json file on both server and client---start the v2ray service---test the speed  on the same location again after clean the browser's cache.

But, the result was really confusing...

TEST 1 [alterid 200]

![alterid 200 speed test 1](https://cloud.githubusercontent.com/assets/11748513/13273110/0a03ebea-dadc-11e5-8af4-3426b005c7f0.jpg)

TEST 2 [alterid 1024]

![alterid 1024 speed test 1](https://cloud.githubusercontent.com/assets/11748513/13273128/26300cf4-dadc-11e5-96f1-0eb2cda8efdd.jpg)

TEST 3 [alterid 200]

![alterid 200 speed test 2](https://cloud.githubusercontent.com/assets/11748513/13273141/3b05e18a-dadc-11e5-9423-35c0909600d3.jpg)

TEST 4 [alterid 1024]

![alterid 1024 speed test 2](https://cloud.githubusercontent.com/assets/11748513/13273148/4d9c5c48-dadc-11e5-9752-cbcfc7c15e70.jpg)

All these tests were done in about 10 minutes, the speed was really unstable, maybe it's my VPS host's problem, or maybe it's not.

I turned on dynamic ports function on my server, could this be the problem?

Definitely need more tests.

**Comment by v2ray** [comment]
I believe the results are reasonable. The difference in the speed is probably caused by some flakes in the network. You may try alterId=10 to confirm. I believe the value alterId has no impact on connection speed.

**Comment by Sherman-Liu** [comment]
Yes, I've tested it once more this morning, I can confirm that the value of alterid does almost nothing to the bandwidth, maybe there is something wrong with the VPS host.

Thanks for the help.

**Comment by Saya47** [comment]
I don't understand what alterId does, I've read the docs on VMESS, but the explanation is not clear for me.
Does alterId mean for example 2 devices can connect with same ID?

**Comment by kianenigma** [comment]
As far as I know alterId helps add further obfuscation and make your server less prone to being probed/blocked by a firewall.
