### ISSUE TITLE
能否增加一个DNS劫持功能，并结合chinasites实现无需sniffer的透明自动翻墙

### ISSUE THREAD

**Issue by ownhere** [v2ray/v2ray-core#922]
Please skip to the English section below if you don't write Chinese.

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V2Ray-3.11 x86_64/mips/arm
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
手机移动翻墙，路由器全局透明翻墙
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
新功能建议
4)  你期待看到的正确表现是怎样的？
低资源消耗下实现全局透明翻墙
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
不适用    

现在dokodemo模式下的透明翻墙+domainOverride，使用强行拆包的方式寻找域名并解析来解决DNS污染和分配墙内外流量问题，此方式若用于低cpu能力的路由器时会有较高的负载。
能否增加一个DNS劫持模块，把路由器收到或将要发出的DNS请求转发到V2Ray内部（这一步骤可能和V2Ray无关），同时结合chinasites字典表，对于国内域名使用alidns等国内公开dns查询，对于国外域名使用谷歌或opendns查询，这样就无需考虑墙内的DNS污染问题而去做强行拆包动作，V2Ray只工作在layer3以下，提高效率。

**Comment by DarienRaymond** [comment]
开一个DNS解析并不会比SNI劫持更省内存。如果你需要稳定的DNS，可以选择一个第三方的解析工具，然后用V2Ray来转发流量。
