### ISSUE TITLE
Default alterId in config.json doesn't work.

### ISSUE THREAD

**Issue by sjx95** [v2ray/v2ray-core#932]
Version: v2ray-linux-amd64 v3.12, both Server and Client.

I configure server with the instruction on v2ray.com, like this:
```
 "clients": [
    {
      "id": "27848739-7e62-4138-9fd3-098a63964b6b",
      "email": "love@v2ray.com"
    }
  ],
  "default": {
    "level": 1,
    "alterId": 64
  },
```

But after I set alterId=64 on client, a "invalid id" message logged at `/var/log/v2ray/access.log`.
If I add `"alterId": 64` in clients section, or set `alterId=0` on client, it works well.

So is there any bug when decoding config file on server?

**Comment by DarienRaymond** [comment]
VMess Inbound settings: 
```
 "clients": [
    {
      "id": "27848739-7e62-4138-9fd3-098a63964b6b",
      "alterId": 100,
      "email": "blah"
    }
  ]
```

The `default` settings doesn't apply on manually specified clients.

The `security` settings will be fixed in the next release.

**Comment by sjx95** [comment]
Okay, thank you for your works.
