### ISSUE TITLE
rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by ilikecola** [v2ray/v2ray-core#935]
Please skip to the English section below if you don't write Chinese.

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
V2Ray v3.12
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
Using Api
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
2018/03/09 04:43:30 failed to call grpc command: rpc error: code = Unavailable desc = transport is closing
4)  你期待看到的正确表现是怎样的？
Api success
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
```javascript
"api":{
      "tag": "api",
      "services": [
        "HandlerService",
        "LoggerService"
      ]
   },
...
{
         "listen": "127.0.0.1",
         "port": 10085,
         "protocol": "dokodemo-door",
         "settings": {
             "address": "127.0.0.1"
          },
          "tag": "api"
        }
...
{
               "inboundTag": [
                   "api"
                ],
                "outboundTag": "api",
                "type": "field"
            }
```

其它相关的配置文件（如 Nginx）和相关日志。
DEMO.go

```go
const (
        API_ADDRESS = "127.0.0.1"
        API_PORT    = 10085
        INBOUND_TAG = "vmess_inbound"
        LEVEL   = 1
        EMAIL   = "123@gmail.com"
        UUID    = "2601070b-ab53-4352-a290-1d44414581ee"
        ALTERID = 32
)
func addUser(c command.HandlerServiceClient) {
        resp, err := c.AlterInbound(context.Background(), &command.AlterInboundRequest{
                Tag: INBOUND_TAG,
                Operation: serial.ToTypedMessage(&command.AddUserOperation{
                        User: &protocol.User{
                                Level: LEVEL,
                                Email: EMAIL,
                                Account: serial.ToTypedMessage(&vmess.Account{
                                        Id:               UUID,
                                        AlterId:          ALTERID,
                                        SecuritySettings: &protocol.SecurityConfig{Type: protocol.SecurityType_AUTO},
                                }),
                        },
                }),
        })
        if err != nil {
                log.Printf("failed to call grpc command: %v", err)
        } else {
                log.Printf("ok: %v", resp)
        }
}
func removeUser(c command.HandlerServiceClient) {
        resp, err := c.AlterInbound(context.Background(), &command.AlterInboundRequest{
                Tag: INBOUND_TAG,
                Operation: serial.ToTypedMessage(&command.RemoveUserOperation{
                        Email: EMAIL,
                }),
        })
        if err != nil {
                log.Printf("failed to call grpc command: %v", err)
        } else {
                log.Printf("ok: %v", resp)
        }
}
func main() {
        cmdConn, err := grpc.Dial(fmt.Sprintf("%s:%d", API_ADDRESS, API_PORT), grpc.WithInsecure())
        if err != nil {
                panic(err)
        }
        hsClient := command.NewHandlerServiceClient(cmdConn)
        addUser(hsClient)
        // removeUser(hsClient)
}
```

**Comment by DarienRaymond** [comment]
1. 这个错误可以稳定重现吗？还是偶尔出现？
2. V2Ray在demo执行期间一直在运行吗？
3. V2Ray中有没有什么超时设置？

**Comment by DarienRaymond** [comment]
4. 另外试一下 [WithBlock 选项](https://godoc.org/google.golang.org/grpc#WithBlock)

**Comment by ilikecola** [comment]
@DarienRaymond 
1.Always
2.Yes
3.No Policy settings
4.Trying on it

Thanks!

**Comment by DarienRaymond** [comment]
Assuming fixed.

**Comment by maxrisk** [comment]
我查用户使用流量时就出现这个问题，请问是怎么解决的？

**Comment by GavinTao1219** [comment]
同求，运行
`/usr/bin/v2ray/v2ctl api --server=127.0.0.1:10085 StatsService.GetStats 'name: "user>>>123@gmail.com>>>traffic>>>downlink" reset: false'`
就出现了这个问题

我的配置文件如下：
`{
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "api": {
    "service": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag":"api"
  },
  "inbound": {
    "port": 40050,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
	  "email":"123@gmail.com",
          "id": "678c949e-c811-4968-bb33-b8022a1ee6e3",
          "level": 1,
          "alterId": 64
        }
      ],
      "detour": {
        "to": "dynamicPort"
      }
    },
    "tag":"proxy"
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "inboundDetour":[
    {
      "protocol": "vmess",
      "port": "10000-20000", // 端口范围
      "tag": "dynamicPort",
      "settings": {
        "default": {
          "level": 1,
          "alterId": 32
        }
      },
      "allocate": {            // 分配模式
        "strategy": "random",  // 随机开启
        "concurrency": 2,      // 同时开放两个端口
        "refresh": 3           // 每三分钟刷新一次
      }
    },
    {
      "listen": "127.0.0.1",
      "port": 10085,
      "protocol": "dokodemo-door",
      "settings": {
          "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        },
        {
          "inboundTag": [
              "api"
          ],
          "outboundTag": "api",
          "type": "field"
        }
      ]
    }
  }
}`

**Comment by GavinTao1219** [comment]
同求，运行
```
/usr/bin/v2ray/v2ctl api --server=127.0.0.1:10085 StatsService.GetStats 'name: "user>>>123@gmail.com>>>traffic>>>downlink" reset: false'
```
就会出现此issue所描述的问题

我的配置文件如下：
```
{
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "api": {
    "service": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag":"api"
  },
  "inbound": {
    "port": 40050,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
	  "email":"123@gmail.com",
          "id": "678c949e-c811-4968-bb33-b8022a1ee6e3",
          "level": 1,
          "alterId": 64
        }
      ],
      "detour": {
        "to": "dynamicPort"
      }
    },
    "tag":"proxy"
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "inboundDetour":[
    {
      "protocol": "vmess",
      "port": "10000-20000", // 端口范围
      "tag": "dynamicPort",
      "settings": {
        "default": {
          "level": 1,
          "alterId": 32
        }
      },
      "allocate": {            // 分配模式
        "strategy": "random",  // 随机开启
        "concurrency": 2,      // 同时开放两个端口
        "refresh": 3           // 每三分钟刷新一次
      }
    },
    {
      "listen": "127.0.0.1",
      "port": 10085,
      "protocol": "dokodemo-door",
      "settings": {
          "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        },
        {
          "inboundTag": [
              "api"
          ],
          "outboundTag": "api",
          "type": "field"
        }
      ]
    }
  }
}
```

**Comment by cpzz50** [comment]
> 同求，运行
> 
> ```
> /usr/bin/v2ray/v2ctl api --server=127.0.0.1:10085 StatsService.GetStats 'name: "user>>>123@gmail.com>>>traffic>>>downlink" reset: false'
> ```
> 就会出现此issue所描述的问题
> 
> 我的配置文件如下：
> 
> ```
> {
>   "log" : {
>     "access": "/var/log/v2ray/access.log",
>     "error": "/var/log/v2ray/error.log",
>     "loglevel": "warning"
>   },
>   "api": {
>     "service": [
>       "HandlerService",
>       "LoggerService",
>       "StatsService"
>     ],
>     "tag":"api"
>   },
>   "inbound": {
>     "port": 40050,
>     "protocol": "vmess",
>     "settings": {
>       "clients": [
>         {
> 	  "email":"123@gmail.com",
>           "id": "678c949e-c811-4968-bb33-b8022a1ee6e3",
>           "level": 1,
>           "alterId": 64
>         }
>       ],
>       "detour": {
>         "to": "dynamicPort"
>       }
>     },
>     "tag":"proxy"
>   },
>   "outbound": {
>     "protocol": "freedom",
>     "settings": {}
>   },
>   "inboundDetour":[
>     {
>       "protocol": "vmess",
>       "port": "10000-20000", // 端口范围
>       "tag": "dynamicPort",
>       "settings": {
>         "default": {
>           "level": 1,
>           "alterId": 32
>         }
>       },
>       "allocate": {            // 分配模式
>         "strategy": "random",  // 随机开启
>         "concurrency": 2,      // 同时开放两个端口
>         "refresh": 3           // 每三分钟刷新一次
>       }
>     },
>     {
>       "listen": "127.0.0.1",
>       "port": 10085,
>       "protocol": "dokodemo-door",
>       "settings": {
>           "address": "127.0.0.1"
>       },
>       "tag": "api"
>     }
>   ],
>   "outboundDetour": [
>     {
>       "protocol": "blackhole",
>       "settings": {},
>       "tag": "blocked"
>     }
>   ],
>   "routing": {
>     "strategy": "rules",
>     "settings": {
>       "rules": [
>         {
>           "type": "field",
>           "ip": [
>             "0.0.0.0/8",
>             "10.0.0.0/8",
>             "100.64.0.0/10",
>             "127.0.0.0/8",
>             "169.254.0.0/16",
>             "172.16.0.0/12",
>             "192.0.0.0/24",
>             "192.0.2.0/24",
>             "192.168.0.0/16",
>             "198.18.0.0/15",
>             "198.51.100.0/24",
>             "203.0.113.0/24",
>             "::1/128",
>             "fc00::/7",
>             "fe80::/10"
>           ],
>           "outboundTag": "blocked"
>         },
>         {
>           "inboundTag": [
>               "api"
>           ],
>           "outboundTag": "api",
>           "type": "field"
>         }
>       ]
>     }
>   }
> }
> ```

同求
