### ISSUE TITLE
我们探讨一下阿里云是怎么发整改通知的

### ISSUE THREAD

**Issue by loveyanbei** [v2ray/v2ray-core#936]
RT，运行了v2r和ss，刚收到整改邮件
探讨一下云服务商是怎么发现你的。
进程检测？
流量特征？遇到入站出站流量差不多的就开始发邮件？

**Comment by kirbyzhu** [comment]
你的所有对他们来说是透明的

**Comment by marskid** [comment]
朋友的国内阿里云，给我一个ubuntu docker ，在docker 里跑v2ray 将vmess转成http公开明文代理，没有密码验证，一天后发邮件要求整改。

不管是进程检测还是协议检测，阿里云都可以做到。

**Comment by whlsxl** [comment]
阿里云跑了好多spy 在你虚拟机上的

**Comment by Balnea** [comment]
你用阿里云装v2ray，分明是帮助他们在机器学习协议特征吧？

**Comment by loveyanbei** [comment]
@whlsxl 我之前就杀掉了所有的agent，以前也没问题。
最近估计是风声紧了把
不过那个主机已经快到期了，已经换搬瓦工cn2

**Comment by loveyanbei** [comment]
@whlsxl spy很正常，要不然你怎么获取vm详细信息，告警什么的，尤其是很细的东西。
当然国内有政策，那个spy会干什么就难说了。

**Comment by ownhere** [comment]
v2ray和ss的监听端口是很明显特征的那种吗？

**Comment by DarienRaymond** [comment]
本repo不讨论玄学
