### ISSUE TITLE
v2ray重载配置档问题

### ISSUE THREAD

**Issue by guigeng** [v2ray/v2ray-core#950]
是否可以加入reload命令，在v2ray运行过程中重新载入配置文件。
比如修改了配置文件后，需要restart v2ray。
那么加入重载命令后执行v2ctl -reload，配置文件就可以实时生效。

不知道是否可以实现。

**Comment by DarienRaymond** [comment]
duplicated to https://github.com/v2ray/Planning/issues/29

暂时没有计划实现这一功能
