### ISSUE TITLE
在padavan路由器MT7621（mipsle） ws+tls模式无法正常工作，ASUS AC68U 梅林系统（arm）工作正常。

### ISSUE THREAD

**Issue by senseye2006** [v2ray/v2ray-core#952]
1、你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
3.13

2、你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。

使用newifi-d1路由器，padavan 3.4.3.9-099_e58fdd7，MT7621（mipsle）
和ASUS AC68U 路由器 梅林 380.69_2 arm
访问google.com

3、你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
MT7621 ws+tls模式无法正常工作。

4、你看到的正确表现是怎样的？
同样的配置，PC端访问正常，ASUS AC68U正常访问，MT7621 mKCP模式正常访问。

5、请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": ""
  },
  "inbound": {
    "port": 1080,
    "listen": "0.0.0.0",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "127.0.0.1",
      "clients": null
    },
    "streamSettings": null
  },
  "outbound": {
    "tag": "agentout",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "服务器",
          "port": 443,
          "users": [
            {
              "id": "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx",
              "alterId": 64,
              "security": "aes-128-gcm"
            }
          ]
        }
      ],
      "servers": null
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "tcpSettings": null,
      "kcpSettings": null,
      "wsSettings": {
        "connectionReuse": true,
        "path": "/位置",
        "headers": null
      }
    },
    "mux": {
      "enabled": true
    }
  },
  "inboundDetour": null,
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {
        "response": null
      },
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "blockout"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": null,
          "outboundTag": "direct",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "domain": null
        },
        {
          "type": "field",
          "port": null,
          "outboundTag": "direct",
          "ip": null,
          "domain": [
            "geosite:cn"
          ]
        },
        {
          "type": "field",
          "port": null,
          "outboundTag": "direct",
          "ip": [
            "geoip:cn"
          ],
          "domain": null
        }
      ]
    }
  }
}

输出显示错误为：
2018/03/12 13:36:12 tcp:192.168.3.133:19811 accepted tcp:www.google.com:443 
2018/03/12 13:36:12 tcp:192.168.3.133:19812 accepted tcp:www.google.com:443 
2018/03/12 13:36:13 tcp:192.168.3.133:19813 accepted tcp:www.google.com:443 
2018/03/12 13:36:15 [Warning] failed to handler mux client connection > Proxy|VMess|Outbound: failed to find an available destination > Retry: [Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://服务器域名/位置):  > x509: failed to load system roots and no roots provided] > Retry: all retry attempts failed

**Comment by acdxxx177** [comment]
能给个梅林的配置吗,我的配置一直不成功,iptables转发到dokodemo-door一直出错,谢谢

**Comment by senseye2006** [comment]
还没配置iptables转发到dokodemo-door

**Comment by senseye2006** [comment]
解决了，是/etc/ssl下缺少证书。
