### ISSUE TITLE
v2ray运行一段时间，会异常退出

### ISSUE THREAD

**Issue by xiaomotou** [v2ray/v2ray-core#96]
服务器ubuntu 14.04 ,版本v1.8
v2ray 部分文件配置如下：
> ...
> "inboundDetour": [
>     {
>       "protocol": "shadowsocks",
>       "port": 8080,
>       "settings": {
>         "method": "aes-256-cfb",
>         "password": "",
>         "udp": true
>       }
>     },
> ...

中转服务器用阿里百川，只开放了8080端口。使用haproxy进行了中转，配置文件如下
> global
>         ulimit-n  51200
> 
> defaults
>         log global
>         mode    tcp
>         option  dontlognull
>         contimeout 1000
>         clitimeout 150000
>         srvtimeout 150000
> 
> frontend ss-in
>         bind *:8124
>         default_backend ss-out
> 
> backend ss-out
>         server server1 vps_ip:8080 maxconn 20480

日志中出现大量：（53456端口不一定）
[Error]Shadowsocks: Failed to read IV: read tcp vps_ip:8080->中转服务器ip:53456: read: connection reset by peer

**Comment by v2ray** [comment]
如果 Connection Reset 不是你的 HAProxy 所为的话，那就是 GFW 干的了。

异常退出多数是因为内存不足，你的 VPS 总内存有多少？

**Comment by xiaomotou** [comment]
总共741M，平时大概有400多M剩余
