### ISSUE TITLE
利用socket5协议代理SSH，登出后连接需要很久才能断开

### ISSUE THREAD

**Issue by FanhuaCloud** [v2ray/v2ray-core#963]
"inbound": {
        "protocol": "socks",
        "port": 1300,
        "listen": "127.0.0.1",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "ip": "127.0.0.1"
        }
      },
      "outbound": {
        "protocol": "vmess",
        "settings": {
          "vnext": [
            {
              "address": "*",
              "port": 443,
              "users": [
                {
                  "id": "*",
                  "alterId": 64,
                  "security": "auto",
                  "level": 1
                }
              ]
            }
          ]
        }

**Comment by Ariselia** [comment]
能否复现这个问题并提供详细日志？

**Comment by DarienRaymond** [comment]
在配置文件中加入：

```javascript
"policy": {
    "levels": {
        "1": {
            "uplinkOnly": 0,
            "downlinkOnly": 0
        }
    }
}
```

详见：https://www.v2ray.com/chapter_02/policy.html

**Comment by FanhuaCloud** [comment]
好的，感谢
