### ISSUE TITLE
暂停 youtube 的视频播放客户端，中断IDM的下载，v2ray自己还在狂跑流量？？

### ISSUE THREAD

**Issue by Justsoos** [v2ray/v2ray-core#964]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
core: v2ray-v3.10-windows-64
v2rayN v1.22

2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
win 10 + mpv + http proxy + v2rayN + v2ray core

3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
打开 mpv（内置youtube-dl）看油管，选择视频中段某点开始看，网卡满速跑 load 近半分钟。关闭 mpv 后，内存进程杀掉mpv，网卡还在跑流量，可能要跑30秒到1分钟，查看发现是 v2ray.exe 

4)  你期待看到的正确表现是怎样的？
这个是不是传说中 v2ray 的网络设计不同之处？ 用 ssr 从没这个问题 -- mpv 点到比如一个视频 20 分钟，也就缓冲几秒钟就打开，关闭 mpv 后不会跑流量

**Comment by Ariselia** [comment]
能否复现这个问题并且提供 v2ray 在 loglevel  为 debug 级别的日志？

**Comment by Justsoos** [comment]
重现很容易，用 IDM 通过 v2ray 代理，下载 virtualbox 最新版，就重现了：
```
hidden-time-stamp 3:20 [Info] [530367739] Proxy|Socks: TCP Connect request to tcp:23.203.229.40:443
hidden-time-stamp 3:20 [Info] [530367739] App|Dispatcher: default route for tcp:23.203.229.40:443
hidden-time-stamp 3:20 [Info] [530367739] App|Proxyman|Mux: dispatching request to tcp:23.203.229.40:443
hidden-time-stamp 4:56 [Debug] Transport|Internet|mKCP: #58225 entering state 1 at 600001
hidden-time-stamp 4:56 [Info] Transport|Internet|mKCP: #58225 closing connection to 137.175.66.78:5346
hidden-time-stamp 4:56 [Info] failed to handler mux client connection > Proxy|VMess|Outbound: connection ends > context canceled
hidden-time-stamp 4:56 [Info] App|Proxyman|Mux: failed to read metadata > context canceled
```
我掐表，3:29 时暂停的 IDM，但 v2ray 持续跑满负载流量，到 4:21 流速才归零。

**Comment by Justsoos** [comment]
补充一下，IDM 下载完毕后，v2ray 流量同步降到 0，但如果是中间暂停，就会出现这个现象。

传说，v2ray 会在服务端内存按 uri 下载整个文件到内存，再推送到客户端，是这个原因的副产品吗？？
很显然，ss和ssr是面向包转发的，不会有这个问题。 v2ray 采用了面向 uri 文件的储存、转发？

**Comment by Justsoos** [comment]
对了，一楼提到的问题，也是 mpv 看youtube 时候，**中间暂停**，就会出现高达几分钟的v2ray带宽跑满。我估计同样是因为mpv 看的 油管视频，也是以文件 uri 方式被 v2ray 储存、转发的吧？

**Comment by Justsoos** [comment]
https://github.com/v2ray/v2ray-core/commit/81a147e5407fb7af6efcd75be78c404e2bed5965
这个版本，稍有改善。
暂停后继续跑流量的时间，从 ver3.15 的一分钟左右，缩短到 30 秒

**Comment by DarienRaymond** [comment]
在你的配置文件里加入： 

```javascript
"policy": {
    "levels": {
        "0": {
            "uplinkOnly": 0,
            "downlinkOnly": 0
        }
    }
}
```

其中那个`"0"`按你的实际user level调整。

**Comment by Justsoos** [comment]
设置 “policy” 字段后，这次缩短到15秒了。。。哈哈。
不过没应用6小时前两个PR，还是 https://github.com/v2ray/v2ray-core/commit/81a147e5407fb7af6efcd75be78c404e2bed5965 我再更新编译试试。

**Comment by Justsoos** [comment]
第一，建议，将 git commit 版本hash放到 exe 信息里，便于识别 exe ，提交问题。
比如：
```
V2Ray 3.16 (die Commanderin) (50af0bd) Custom
A unified platform for anti-censorship.
```
第二，另外，刚测了 https://github.com/v2ray/ext/commit/50af0bd26f2effcaa1244426b993e9fba49d72e6 ，这个版本是 30 秒

**Comment by Justsoos** [comment]
https://github.com/v2ray/v2ray-core/commit/435be616619fa8c138c993bddb78ce3dcf8775c5
这个版本 OK 了，流量秒停！

不过还要发个新版本，并通知各个客户端制作人，新加了
```
  "policy": {
    "levels": {
      "0": {"uplinkOnly": 0}
    }
  }
```
目前，此字段还会被 v2rayN 自动删除

**Comment by Justsoos** [comment]
刚又测了下，就算被v2rayN 删掉了这个字段，还是秒停的。

**Comment by Justsoos** [comment]
哈哈，收到 v3.16 https://github.com/v2ray/v2ray-core/releases/tag/v3.16

> 启动服务(2018/4/6 13:59:16)......
> V2Ray v3.16 (die Commanderin) **20180405**
> A unified platform for anti-censorship.

聊胜于无，可惜，只能用天来标记官方版本exe，而不是commit hash

**Comment by Justsoos** [comment]
@2dust @Jrohy  core 又出了一个新字段 policy，貌似有没有对断流都不影响。
但 v2rayN 系列会主动删除这个字段，需要改版咯~ 我来招徕下生意。哈哈

**Comment by bash99** [comment]
@Justsoos 这个配置是加到服务器端还是客户端？

**Comment by SmileDream** [comment]
kcp配置关闭YouTube流量还在跑不停

**Comment by William96911** [comment]
现在这个问题还没解决，用的是FDM，终止下载后还在跑流量
