### ISSUE TITLE
WS+TLS+Webserver模式，网站可以用http访问，但是不能用https访问，显示404

### ISSUE THREAD

**Issue by flukaxkx** [v2ray/v2ray-core#971]
**1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）**
3.11

**2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。**
ws+tls+webserver (Apache2)，科学上网上网，使用google查资料。

**3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）**
代理正常工作，webserver使用http访问可以显示默认页面，用https访问则显示404，找不到页面。

**4)  你期待看到的正确表现是怎样的？**

**1.想请教https这样是否是正常的，如果不正常怎么修改。
2.想请教我的tls是否已经启动了，怎么证明或者验证一下。
多谢多谢**

**5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。**
        **服务器端配置:**
```javascript
   {
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 12345,
    "listen":"127.0.0.1",
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "ididididididid",
          "level": 1,
          "alterId": 64
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "wsSettings": {
        "path":"/ray"
      }
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}
```

 **客户端配置:**
```javascript
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": ""
  },
  "inbound": {
    "port": 1080,
    "listen": "0.0.0.0",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "127.0.0.1",
      "clients": null
    },
    "streamSettings": null
  },
  "outbound": {
    "tag": "agentout",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "myserver.mydomain",
          "port": 443,
          "users": [
            {
              "id": "IDIDIDID",
              "alterId": 64,
              "security": "aes-128-cfb"
            }
          ]
        }
      ],
      "servers": null
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "tcpSettings": null,
      "kcpSettings": null,
      "tlsSettings":{
        "serverName":"myserver.mydomain",
        "allowInsecure":true
      },
      "wsSettings": {
        "connectionReuse": true,
        "path": "/ray",
        "headers": null
      }
    },
    "mux": {
      "enabled": true
    }
  },
  "inboundDetour": null,
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {
        "response": null
      },
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "blockout"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": null,
          "outboundTag": "direct",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "domain": null
        }
      ]
    }
  }
}
```
**Apache2 server.conf**
```
<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        ServerName myserver.mydomain
        DocumentRoot /var/www/html

</VirtualHost>


<IfModule mod_ssl.c>
    <VirtualHost _default_:443>

        ServerName myserver.mydomain
        ServerAlias myserver.mydomain
        ServerAdmin webmaster@localhost

        DocumentRoot /var/www/html

        LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        Alias /log/ "/var/log/"
        <Directory "/var/log/">
            Options Indexes MultiViews FollowSymLinks
            AllowOverride None
            Order deny,allow
            Deny from all
            Allow from all
            Require all granted
        </Directory>

        ##SSL Engine Switch:
        #Enable/Disable SSL for this virtual host.
        SSLEngine On

        RewriteEngine On
        RewriteCond %{HTTP:Upgrade} =websocket [NC]
        RewriteRule /(.*)           ws://localhost:12345/$1 [P,L]
        RewriteCond %{HTTP:Upgrade} !=websocket [NC]
        RewriteRule /(.*)           http://localhost:12345/$1 [P,L]


        ##Proxy to port 3579
        #Replace xxx.xxx.xxx.xxx with your servers IP adress or hostname
        #Replace yourCertname with your servers SSL certificate name
        SSLProxyEngine On
        Proxypass /ray http://127.0.0.1:12345
        ProxyPassReverse /ray http://127.0.0.1:12345

        SSLCertificateFile /***/***/***.crt
        SSLCertificateKeyFile /***/***/***.key

    </VirtualHost>
</IfModule>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```
**Apache2 ports.conf**
```
Listen 80

<IfModule ssl_module>
        Listen 443
</IfModule>

<IfModule mod_gnutls.c>
        Listen 443
</IfModule>
```

**6)  请附上出错时软件输出的错误日志。**
v2ray代理好用，没有错误日志

**7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。**

**8) 其它相关的配置文件（Apache）和相关日志。**
Apache2也没有错误日志，但有访问日志
**Apache2 access.log**
```
*.*.*.* - - [20/Mar/2018:08:40:44 -0400] "GET / HTTP/1.1" 404 1861 "-" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"
*.*.*.* - - [20/Mar/2018:08:44:39 -0400] "GET / HTTP/1.1" 404 351 "-" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"
```
**浏览器错误提示**
chrome 显示证书错误，
IE不显示，但会触发杀毒软件显示证书不受信任，
下面是chrome的显示
```
您的连接不是私密连接
攻击者可能会试图从 888.888.888 窃取您的信息（例如：密码、通讯内容或信用卡信息）。了解详情
NET::ERR_CERT_AUTHORITY_INVALID
 
自动向 Google 发送一些系统信息和网页内容，以帮助检测危险应用和网站。隐私权政策

此服务器无法证明它是888.888.888；您计算机的操作系统不信任其安全证书。出现此问题的原因可能是配置有误或您的连接被拦截了。

继续前往888.888.888（不安全）
```
继续访问后显示
```
找不到 888.888.888 的网页
找不到与以下网址对应的网页：https://888.888.888/
HTTP ERROR 404
```
请预览一下你填的内容再提交。

如果你已经填完上面的问卷，请把下面的英文部份删除，再提交 Issue。

**Comment by windy1lee** [comment]
DNS，比如你用的cloudflare。在cloudflare可以开始强制https这个功能！可以试一下

**Comment by flukaxkx** [comment]
好的，
我查了一下，刚刚明白了一点概念，我仔细学习一下。
我不是学IT的，搞这些东西都要现学习。:(

**Comment by Hardrain980** [comment]
1.Apache可以用mod_proxy_wstunnel实现，不必自行用rewrite规则实现
2.我觉得是这两行导致了问题
```
RewriteCond %{HTTP:Upgrade} !=websocket [NC]
RewriteRule /(.*)           http://localhost:12345/$1 [P,L]
```
这两行把`Upgrade` header不存在或值不是`websocket`的请求也redirect到v2ray的监听端口去了

**Comment by flukaxkx** [comment]
多谢，多谢。
把这两行 注释 掉以后，https就可以正常访问了，代理也可以正常工作。

昨天试图改成下面这两种样子，都没有成功
```
RewriteRule /(.*)           https://localhost:443/$1 [P,L]
```
```
RewriteRule /(.*)           http://localhost/$1 [P,L]
```
今天看了你的回复才明白过来。:)

mod_proxy_wstunnel正在学习中。

**Comment by Hardrain980** [comment]
突然想到这个配置还有问题

按照这个配置文件，redirect到v2ray后端的逻辑是

发现`upgrade: websocket`这个header => 重定向到http(ws)://127.0.0.1:{v2ray_port}。

而为了做到隐蔽，应该是:

请求的路径是serverpath(GET /{v2ray_path}/ HTTP/1.1)才重定向到http(ws)://127.0.0.1:{v2ray_port}并添加`Connection: upgrade`和`Upgrade: websocket`两个header。

**Comment by flukaxkx** [comment]
不好意思，这两天没上，才看到。
您的意思是还是以请求路径估为rewrite的条件比较合适。

**Comment by flukaxkx** [comment]
我改成 这样了：
后面的注释是我这么写的意图，不知道这么写对不对。
我只会在浏览器和代理客户端上测试，是可以的。
求教你那个命两行测试用的是什么命令。

唉，非专业的翻墙真费劲！！！！！！！！！！！
很多语法什么的都要自己查，有时候还看不懂。 :(

```
RewriteEngine On
RewriteCond %{HTTP:Upgrade} =websocket [NC]       //当请求ws协议时
RewriteCond %{REQUEST_URI}  ^/ray$ [NC]                //并且当请求目录为/ray，后面没有别的字符时
RewriteRule /(.*)           ws://localhost:10086/$1 [P,L]   //重定向到v2ray

RewriteCond %{HTTP:Upgrade} =websocket [NC]       //当请求ws协议时
RewriteCond %{REQUEST_URI}  !^/ray$ [NC]                //并且当请求目录不是/ray，后面可以有别的字符时
RewriteRule /(.*)           http://www.xxx.com [R,L]        //重定向到网站首页

RewriteCond %{HTTP:Upgrade} !=websocket [NC]       //当请求不是ws协议时
RewriteRule /(.*)           http://www.xxx.com [R,L]          //重定向到网站首页
```

**Comment by Hardrain980** [comment]
其实不用这么麻烦吧
直接把这个加进443端口的VirtualHost就可以了
```
<LocationMatch "{v2ray_path}}">
	ProxyPass ws://127.0.0.1:{v2ray_port}/{v2ray_path} upgrade=WebSocket
	ProxyAddHeaders Off
	ProxyPreserveHost On
	RequestHeader set Host %{HTTP_HOST}s
	RequestHeader set X-Forwarded-For %{REMOTE_ADDR}s
</LocationMatch>
```
`{v2ray_port}`和`{v2ray_path}`根据实际情况修改

**Comment by flukaxkx** [comment]
主要是 mod_proxy_wstunnel 这部分不大明白。
rewrite 在这不是有现成的实例可以改嘛。
嘿嘿

**Comment by Hardrain980** [comment]
数日未得空回覆，今尝试了复现：
1.使用mod_proxy_wstunnel(以路径为判据)
```
GET / HTTP/1.1
Host: {servername}
//返回网页
=========================================
GET / HTTP/1.1
Host: {servername}
Upgrade: Websocket
//返回网页
=========================================
GET / HTTP/1.1
Host: {servername}
Connection: Upgrade
Upgrade: Websocket
//返回网页
=========================================
GET / HTTP/1.1
Host: {servername}
Connection: Upgrade
Upgrade: Websocket
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: 9sgA8WeNZxxIQ8lZ/UWkuA==
//返回网页
=========================================
GET /{v2ray_path}/ HTTP/1.1
Host: {servername}
//500错误
=========================================
GET /{v2ray_path}/ HTTP/1.1
Host: {servername}
Upgrade: Websocket
//400错误
=========================================
GET /{v2ray_path}/ HTTP/1.1
Host: {servername}
Connection: Upgrade
Upgrade: Websocket
//400错误
=========================================
GET /{v2ray_path}/ HTTP/1.1
Host: {servername}
Connection: Upgrade
Upgrade: Websocket
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: 9sgA8WeNZxxIQ8lZ/UWkuA==
//101 Switching Protocol(连接成功)

可见，如果没找到{v2ray_path}，无论header怎样都返回网页，特征不明显(v2ray_path设置的长且随机生成的话很难找)
```
2.通过mod_rewrite，发现`Upgrade: Websocket`就跳转:
```
GET / HTTP/1.1
Host: {servername}
//返回网页
=========================================
GET / HTTP/1.1
Host: {servername}
Upgrade: Websocket
//返回404(没有HTML的错误页面)
=========================================
GET /{任意路径} HTTP/1.1
Host: {servername}
Upgrade: Websocket
//返回404(没有HTML的错误页面)
```

这里面第三次尝试显示了一个明显的特征，就是只要有拿个header，请求任意(非{v2ray_path}的)路径都返回无HTML错误页面的404(正常服务器的4xx/5xx错误时多半会返回一个HTML页面，令访问者知道发生了什么错误)

**Comment by flukaxkx** [comment]
请问一下，你看见上面结果用的是什么软件或者命令啊？

**Comment by Hardrain980** [comment]
`openssl s_client`

**Comment by flukaxkx** [comment]
多谢多谢

**Comment by OneWizard** [comment]
问一下最终解决的apache完整配置文件。。。

**Comment by OneWizard** [comment]
多谢，mod_proxy_wstunnel测试成功，照理说ProxyPass ws://127.0.0.1:{v2ray_port}/{v2ray_path} upgrade=WebSocket应该是没问题的（官方文档上有），就是一直报错（然后最后还是rewrite对付了）

**Comment by flukaxkx** [comment]
我把下面这段删掉了，不知道有什么用，删了也不影响使用，
```
        Alias /log/ "/var/log/"
        <Directory "/var/log/">
            Options Indexes MultiViews FollowSymLinks
            AllowOverride None
            Order deny,allow
            Deny from all
            Allow from all
            Require all granted
        </Directory>
```

**Comment by Hardrain980** [comment]
@flukaxkx `upgrade`那行不应该换行，是接在`ProxyPass`后面的，与`ws://127.0.0.1:port/path`之间空一格

**Comment by Hardrain980** [comment]
@flukaxkx 删除那个 `Alias /log/ "/var/log/"`或导致不能正常记录日志

**Comment by DarienRaymond** [comment]
Assume fixed. Please open a new issue if you have other questions.

**Comment by doudouhn6** [comment]
@Hardrain980 @flukaxkx 参照mod_proxy_wstunnel模式可以顺利科学上网，但是为什么访问伪装网站就出现403错误？有没有什么配置既可以科学上网又可以正常访问伪装网站？
附：
403错误信息
Forbidden

You don't have permission to access this resource.

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.


mod_proxy_wstunnel模式的domain.conf配置
<VirtualHost *:80>
    ServerName www.your_domain
    ServerAlias your_domain
    DirectoryIndex index.html index.htm index.php
    DocumentRoot /data/www/html
    Redirect permanent / https://www.tiffme.us/
</VirtualHost>

<IfModule mod_ssl.c>
    <VirtualHost _default_:443>
        ServerName www.your_domain
        ServerAlias your_domain
        DirectoryIndex index.html index.htm index.php
        DocumentRoot /data/www/html

        CustomLog "logs/wp_access_log" combined
        ErrorLog "logs/wp_error_log"
        LogLevel info ssl:warn

        Alias /log/ "/var/log/"
        <Directory "/var/log/">
            Options Indexes MultiViews FollowSymLinks
            AllowOverride None
            Require all granted
        </Directory>

        SSLProtocol all -TLSv1 -TLSv1.1 -SSLv2 -SSLv3
        SSLCipherSuite    ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:!aNULL:!eNULL:!EXPORT:!DES:!3DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA
        SSLHonorCipherOrder on
        Header always set Strict-Transport-Security "max-age=15768000"

        SSLEngine on
        SSLCertificateFile /etc/letsencrypt/live/your_domain/your_domain.cer
        SSLCertificateKeyFile /etc/letsencrypt/live/your_domain/your_domain.key
        
        #RewriteEngine On
        #SSLProxyEngine On
        
        <LocationMatch "/ray">
            ProxyPass ws://127.0.0.1:10574/ray upgrade=WebSocket
            ProxyAddHeaders Off
            ProxyPreserveHost On
            RequestHeader set Host %{HTTP_HOST}s
            RequestHeader set X-Forwarded-For %{REMOTE_ADDR}s
        </LocationMatch>
    </VirtualHost>
</IfModule>

**Comment by flukaxkx** [comment]
您这个设置貌似只有http模式的部分，没有https的部分，只监听80端口，但
‘’’
Redirect permanent / https://www.your_domain/
‘’’
强制用https访问，而您又没对443端口进行设置。

你试试注释掉这行，或者如上面的设置文件一样增加
‘’’
<IfModule mod_ssl.c>
    <VirtualHost _default_:443>
……
    </VirtualHost>
</IfModule>
‘’’
试试

**Comment by doudouhn6** [comment]
@flukaxkx 谢谢您的回复！我尝试用修正后的配置还是出现了访问伪装网站显示403错误，请看修正后的配置：
cat > /etc/httpd/conf.d/wp.conf << EOF
<VirtualHost *:80>
    DocumentRoot /data/www/html
    ServerName www.your_domain
    ServerAlias your_domain
    DirectoryIndex index.html index.php


    Redirect permanent / https://www.your_domain/
    #RedirectMatch permanent ^/(.*)$ http://www.your_domain/$1
    #RewriteRule ^/(.*) https://%{SERVER_NAME}/\$1 [R,L]
    #ProxyRequests Off
    #ProxyPassMatch ^/(.*\.php)\$ fcgi://127.0.0.1:9000/data/www/html/\$1
        <Directory "/data/www/html">
            Options None
            AllowOverride None
            Require all granted
        </Directory>
</VirtualHost>


<VirtualHost *:443>
    DocumentRoot /data/www/html
    ServerName www.your_domain
    ServerAlias your_domain
    DirectoryIndex index.html index.php


    <If "%{HTTP_HOST} == 'your_domain'">
        Redirect permanent / https://www.your_domain/
        #RedirectMatch permanent ^/(.*)$ https://www.your_domain/$1
    </If>


    #ProxyRequests Off
    #ProxyPassMatch ^/(.*\.php)\$ fcgi://127.0.0.1:9000/data/www/html/\$1
    #ProxyPassMatch ^/(wp-status|ping)\$ fcgi://127.0.0.1:9000/\$1
        <Directory "/data/www/html">
            Options None
            AllowOverride None
            Require all granted
        </Directory>


    CustomLog "logs/wp_access_log" combined
    ErrorLog "logs/wp_error_log"


    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/www.your_domain/cert.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/www.your_domain/privkey.pem
    SSLCertificateChainFile /etc/letsencrypt/live/www.your_domain/chain.pem
    SSLCACertificateFile /etc/letsencrypt/live/www.your_domain/fullchain.pem


    SSLHonorCipherOrder on
</VirtualHost>
EOF

**Comment by doudouhn6** [comment]
@flukaxkx 
![Screenshot_20210317-040733](https://user-images.githubusercontent.com/10879231/111373418-d1728a00-86d6-11eb-9a34-5abb94677e1b.png)
![Screenshot_20210317-040807](https://user-images.githubusercontent.com/10879231/111373459-d9322e80-86d6-11eb-9e01-a789ed734012.png)
![Screenshot_20210317-040823](https://user-images.githubusercontent.com/10879231/111373485-dfc0a600-86d6-11eb-910b-968fe102b8d6.png)
截图信息

**Comment by flukaxkx** [comment]
我试了你的配置，没有问题。

我觉得问题可能出在 “/data/www/html” 这三个文件夹的权限。
你检查一下这三个文件夹的权限，只读是不行的，
把 data www 和 html 权限都设置成 755 试一下。

**Comment by doudouhn6** [comment]
@flukaxkx 
已经更改成755权限了，还是403错误，会不会是第三方最新版httpd引发的错误？
cat > /etc/yum.repos.d/codeit.el7.repo << EOF
[CodeIT]
name=CodeIT
baseurl=https://repo.codeit.guru/packages/centos/\$releasever/\$basearch/
#baseurl=https://repo.codeit.guru/packages/centos/7/x86_64/
enabled=1
gpgcheck=1
gpgkey=https://repo.codeit.guru/RPM-GPG-KEY-codeit
EOF

**Comment by doudouhn6** [comment]
附：755权限截图
![chmod data](https://user-images.githubusercontent.com/10879231/111483174-8789b280-876f-11eb-8356-630f018bcfd0.JPG)
![403 Forbidden](https://user-images.githubusercontent.com/10879231/111483208-8f495700-876f-11eb-8b7b-b894e3877e8c.JPG)

**Comment by doudouhn6** [comment]
@flukaxkx 这是我写的一个v2 httpd centos7脚本，您帮看看可能是哪里出现了引发403的错误
https://github.com/doudouhn6/doudouhn6.github.com/blob/master/v2%20httpd%20centos7.txt

**Comment by flukaxkx** [comment]
@doudouhn6 
我在centOS 7 上试了一下，你的设置，还是没发现问题，正常运行。
我的也是安装的 CodeIT 上的 httpd，CentOS自带的版本太低了。

而且，根据 [https://askubuntu.com/questions/1279755/apache-you-dont-have-permission-to-access-this-resource](https://askubuntu.com/questions/1279755/apache-you-dont-have-permission-to-access-this-resource)上面的描述，你目录的所有者也没有问题，CentOS httpd 的用户名就是 Apache。

我做了个试验，在 index.html 里面引用另一个没有访问权限的网页，结果如图所示，所以我认为还是文件权限的问题，但是我搞不清楚问题在哪里。
![err403](https://user-images.githubusercontent.com/36734466/111501002-8bbdcc00-877f-11eb-8d76-d65b9320cabf.jpg)

脚本那个，我不是学计算机的，真的是看不懂脚本，实在是帮不上忙，抱歉。
