### ISSUE TITLE
建议，内置dns缓存

### ISSUE THREAD

**Issue by rufengsuixing** [v2ray/v2ray-core#973]
我在服务器上抓了udp 53 的包，打开网页dns会多次查询同一域名，建议内置一个简单的缓存，缓存时间几秒就行，服务器就不会重复查询dns
17:24:29.759582 IP my ip.21507 > 67.207.67.2.domain: 12223+ AAAA? cm.bilibili.com. (                                               33)
17:24:29.759824 IP my ip.30881 > 67.207.67.2.domain: 44067+ A? cm.bilibili.com. (33)
17:24:29.910731 IP my ip.23614 > 67.207.67.2.domain: 11693+ AAAA? cm.bilibili.com. (                                               33)
17:24:29.910997 IP my ip.34764 > 67.207.67.2.domain: 13376+ A? cm.bilibili.com. (33)
17:24:30.018867 IP my ip.58836 > 67.207.67.2.domain: 10784+ AAAA? cm.bilibili.com. (                                               33)
17:24:30.019144 IP my ip.10196 > 67.207.67.2.domain: 43192+ A? cm.bilibili.com. (33)
17:24:30.019852 IP my ip.52190 > 67.207.67.2.domain: 51430+ AAAA? cm.bilibili.com. (                                               33)
17:24:30.020044 IP my ip.16624 > 67.207.67.2.domain: 49732+ A? cm.bilibili.com. (33)
17:24:30.959652 IP my ip.27757 > 67.207.67.2.domain: 14363+ AAAA? cm.bilibili.com. (                                               33)
17:24:30.959901 IP my ip.29158 > 67.207.67.2.domain: 21611+ A? cm.bilibili.com. (33)
17:24:30.960617 IP my ip.14503 > 67.207.67.2.domain: 1302+ AAAA? cm.bilibili.com. (3                                               3)
17:24:30.960772 IP my ip.11252 > 67.207.67.2.domain: 14191+ A? cm.bilibili.com. (33)
17:24:31.510026 IP my ip.21195 > 67.207.67.2.domain: 43998+ AAAA? cm.bilibili.com. (                                               33)
17:24:31.510231 IP my ip.25818 > 67.207.67.2.domain: 56024+ A? cm.bilibili.com. (33)
17:24:31.510785 IP my ip.49300 > 67.207.67.2.domain: 28509+ AAAA? cm.bilibili.com. (                                               33)
17:24:31.510915 IP my ip.12698 > 67.207.67.2.domain: 31723+ A? cm.bilibili.com. (33)
17:24:35.170212 IP my ip.56623 > 67.207.67.2.domain: 9134+ AAAA? cm.bilibili.com. (3

**Comment by wuxiangzhou2010** [comment]
浏览器的DNS  缓存是不是被关闭了呢，

**Comment by yujinqiu** [comment]
@rufengsuixing  麻烦提供对应的配置,  我看代码中是有对应的 cache 逻辑的. 

```
	ips := s.GetCached(domain)
	if ips != nil {
		return ips, nil
	}

	for _, server := range s.servers {
```

**Comment by wuxiangzhou2010** [comment]
If the browser is set to resolve DNS through socksv5, then the domain will be resolved through the server, will the DNS A/AAA record still be cached for 10 seconds?

**Comment by DarienRaymond** [comment]
这个现象应该是你的客户端主动发出的DNS请求，即V2Ray只是转发了一下而已。V2Ray并不支持对其转发的内容（和收到的相应回复）进行缓存。
