### ISSUE TITLE
使用Android客户端的问题

### ISSUE THREAD

**Issue by qingfengshi** [v2ray/v2ray-core#976]
尝试使用v2ray的Android客户端v2rayNG和bifrostV，在使用过程中发现两个软件都存在相同问题：电脑上使用正常的config.json文件，导入Android客户端后不能连接。不知是不是不能直接导入json文件？
由于两个软件求助反应太慢，导致我在这里发帖求助，见谅。

**Comment by DarienRaymond** [comment]
这个是客户端的问题。一般来说客户端需要额外（或不同）的配置项，比如日志的路径，从而不兼容core的配置文件。这个core也没办法解决。
