### ISSUE TITLE
请教关于树莓派2 2B做客户端网关的速度问题

### ISSUE THREAD

**Issue by ntgeralt** [v2ray/v2ray-core#977]
1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
both v3.14
2)  你的使用场景是什么？
按照官网教程用树莓派2 2B做客户端网关，主路由K2P的网关地址为树莓派ip
3)  你看到的不正常的现象是什么？
树莓派2成功透明代理。
但速度低于用电脑v2rayN.exe客户端。
多次试验youtube 4k播放时
树莓派 固定14000kbps以内
v2rayn.exe 30000kbps+

4)  你期待看到的正确表现是怎样的？
更高的速度。播放4k时 树莓派ssh输入top 看到v2ray 占用固定140%左右。
但他是四核.不清楚是不是技能限制。

5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    {
  "log": {
    "access": "",
    "error": "",
    "loglevel": ""
  },
  "inbound": {
    "port": 1080,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "127.0.0.1",
      "clients": null
    },
    "streamSettings": null
  },
  "outbound": {
    "tag": "agentout",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "3322.net",
          "port": 443,
          "users": [
            {
              "id": "72720b06-dc5bf2439f6a",
              "alterId": 64,
              "security": "auto"
            }
          ]
        }
      ],
      "servers": null
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "tcpSettings": null,
      "kcpSettings": null,
      "wsSettings": {
        "connectionReuse": true,
        "path": "/",
        "headers": {
          "Host": "www.com"
        }
      }
    },
    "mux": {
      "enabled": true,
	  "concurrency": 8
    }
  },
  "inboundDetour": [
    {
      "domainOverride": ["tls","http"],
      "port": 12345,
      "protocol": "dokodemo-door",
      "settings": {
      "network": "tcp,udp",
	  "listen": "0.0.0.0",
      "followRedirect": true
      }
    }
  ],
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "dns": {
    "servers": [
      "119.29.29.29",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        }
      ]
    }
  }
}

日志
2018/03/19 15:45:39 [Warning] Core: V2Ray v3.14 started

**Comment by wuxiangzhou2010** [comment]
树莓派的性能没有那么强，可以考虑 下x86的软路由，或者参考这个[链接](https://toutyrater.github.io/app/transparent_proxy.html#%E8%BD%AF%E7%A1%AC%E4%BB%B6%E5%87%86%E5%A4%87)

**Comment by InoriHeart** [comment]
Pi 3 的性能
之前跑在上面，iOS不能更新 APP，下载一直断线。
换笔记本才正常用的

或许可以考虑一下 Pi 3 +？

**Comment by ntgeralt** [comment]
同上，做网关的时候 ，王者荣耀和吃鸡手游有不正常延迟，换4g后正常。估计是路由白名单和udp不对，不过也不知道错在哪，有望专家能提供一个标准json模板

**Comment by 805447391** [comment]
同树莓派，我的是pi3 model B，使用mkcp模式，sock5模式下，网速能到10Mbps，但是使用dokodemo-door模式建立透明代理，速度只有可怜的1M。树莓派的性能没那么差，我用的openwrt开启了多核优化，C库为glibc。但是这个现象始终令我费解，求解决方案。
初步怀疑问题所在：
1.iptables转发问题（性能，规则，...）
2.dokodemo-door问题

**Comment by billryan** [comment]
同  14000 Kb 以内，用 http/socks 也是一样的，应该不是 iptables/dokodemo 的问题

**Comment by billryan** [comment]
TLS+Websocket+Vmess 在 14000 Kb 以内，换原生的 Vmess TCP 模式可以到 23000 Kb 左右

**Comment by DarienRaymond** [comment]
用了 TLS 之后 VMess 的加密方式可以使用 none，应该对速度有帮助。

另外多核心在这个场景中没什么帮助，因为数据是顺序加密/解密的，不存在并行的空间。

**Comment by ticonci** [comment]
我是model 3B+， tls+none加密，最多跑16000左右
