### ISSUE TITLE
请教ubnt erx究竟用哪个版本?

### ISSUE THREAD

**Issue by xd0112** [v2ray/v2ray-core#978]
根据https://arkis.me/post/0018-erxproxy/
安装了v3.10的 v2ray 然后该贴提示

"有两种方式安装v2ray,一种可以参考本文的第一步直接安装，不过它的脚本判断为mips，并非mipsel，我怕这么安装出问题，所以我选用了本地安装的方式。"

按照贴中地址下载了v3.10安装包v2ray-v3.10-linux-mips,可以正常当透明代理使用.

但是我和github上对应的mips v3.10版本MD5值,两者对比并不相同.
github上的版本安装v3.14与v.310后无法正常启动,一直提示
Shutting down V2Ray service.
Restarting V2Ray service.
V2Ray v3.14 is installed.
root@ubnt:/tmp# /etc/init.d/v2ray status
[FAIL] v2ray is not running ... failed!

通过在线的安装脚本安装也一直这样提示,同样的配置文件,只有帖子中提供的版本可以正常启动.
本人客户端配置如下:

{
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 1080,
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": false,
      "ip": "0.0.0.0"
    }
  },
  "inboundDetour": [
    {
      "domainOverride": ["tls","http"],
      "port": 12345,
      "protocol": "dokodemo-door",
      "settings": {
          "network": "tcp,udp",
          "followRedirect": true
      }
  }
  ],

  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext":[
        {
          "address":"XXX.XXX.XXX.XXX",
          "port": XXXX,
          "users":[
            {
              "id":"XXXXXXXXXX",
              "level":1,
              "alterId":64
            }
          ]
        }
      ]
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "adblock"
    },
    {
        "protocol": "vmess",
        "settings":  {
            "vnext":[
              {
                "address":"XXX.XXX.XXX.XXX",
                "port": XXX,
                "users":[
                  {
                    "id":"XXXXXXXX",
                    "level":1,
                    "alterId":64
                  }
                ]
              }
            ]
          },
        "tag": "blacksite"
      }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "chinasites",
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        },
        {
            "domain": [
              "pan.baidu.com",
              "csdn.net",
              "github.com"
            ],
            "type": "field",
            "outboundTag": "blacksite"       
          },
        {
          "domain": [
            "tanx.com",
            "googeadsserving.cn",
            "baidu.com"
          ],
          "type": "field",
          "outboundTag": "adblock"       
        },
        {
          "domain": [
            "amazon.com",
            "microsoft.com",
            "jd.com",
            "youku.com",
            "baidu.com"
          ],
          "type": "field",
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        }
      ]
    }
  }
}

**Comment by DarienRaymond** [comment]
你可以手动运行一下v2ray看看是什么错误。如果CPU不支持硬件FPU的话，有可能需要使用安装包里的 *_softfloat* 版本。

**Comment by xd0112** [comment]
_softfloat版本是哪个?

我都放弃在erx上部署v2ray了,只能用别人提供的安装包,不能在这下载最新的,感觉心里不踏实.

这2天部署在树莓派上了,轻松简单,完全没有ubnt上这么多事...

**Comment by UVJkiNTQ** [comment]
er-x 是mipsel的……安装脚本会认成mips，但erx那个性能还是算了吧

**Comment by Hardrain980** [comment]
ER-X和ER-X-SFP的CPU都是MT7621
交叉编译时可能需要Mediatek官方提供的编译器

此外，Go的程序还是不太建议在路由器上跑(x86软路由例外)

**Comment by DarienRaymond** [comment]
请提供一下erx上的 `uname -m` 的输出，以方便修复安装脚本的问题。

**Comment by xd0112** [comment]
@DarienRaymond uname -m 也提示的是mips, 所以这应该是ubnt erx的问题,实际是mipsel,感觉没有必要改动现有脚本了,后面的人有需要的话自己编译吧.

**Comment by p4insh11** [comment]
ERX就是MIPSEL， ERL才是MIPS，不过这个解密能力够，但是跑应用不行

**Comment by gareylui** [comment]
erx 2.08 hotfix，修改了安装脚本，强制返回mipsel，安装成功，注意1.x版本的erx的debian os不支持xz，导致连unzip都装不了一直apt-get报错，升级2.x即可解决问题
