### ISSUE TITLE
Problem With Shadowsocks OTA Function

### ISSUE THREAD

**Issue by Sherman-Liu** [v2ray/v2ray-core#98]
Hi there. 

I'm trying the newest 1.9 version of V2Ray now, everything seems working nicely, the V2ray client on my computer working smoothly. But there's something that bothers me, the malfunction of the Shadowsocks OTA Function.

When I turned on the OTA function, switched on Shadowsocks, for the first 10 seconds it's working fine, but then I can't open any pages or stream any videos online, when I turned the Shadowsocks on & off again, it's working for another 10 seconds, then it stopped working just as before,I have checked the error.log and access.log, they look like this:

error.log:

2016/02/28 15:01:01 [Warning]Shadowsocks: Invalid request from udp:***.**.**.**:59278: Invalid authentication.
2016/02/28 15:01:01 [Error]Shadowsocks: Invalid OTA: [72 11 46 19 184 229 164 60 131 225]
2016/02/28 15:01:01 [Warning]Shadowsocks: Invalid request from udp:***.**.**.**:59279: Invalid authentication.
2016/02/28 15:01:01 [Error]Shadowsocks: Invalid OTA: [94 243 201 255 114 162 170 168 191 240]
2016/02/28 15:01:01 [Warning]Shadowsocks: Invalid request from udp:***.**.**.**:59280: Invalid authentication.
2016/02/28 15:01:01 [Error]Shadowsocks: Invalid OTA: [58 238 22 246 233 128 164 139 136 21]
2016/02/28 15:01:01 [Warning]Shadowsocks: Invalid request from udp:***.**.**.**:59281: Invalid authentication.
2016/02/28 15:01:01 [Error]Shadowsocks: Invalid OTA: [254 138 45 119 165 194 203 15 44 165]

access.log:

2016/02/28 15:10:20 ***.**.**.**:12570 accepted tcp:203.208.48.154:443 
2016/02/28 15:10:20 ***.**.**.**:12571 accepted tcp:173.194.73.118:443 
2016/02/28 15:10:20 ***.**.**.**:12572 accepted tcp:203.208.48.154:443 
2016/02/28 15:10:21 udp:***.**.**.**:61979 rejected  Invalid authentication.
2016/02/28 15:10:21 udp:***.**.**.**:61979 rejected  Invalid authentication.
2016/02/28 15:10:21 udp:***.**.**.**:61951 rejected  Invalid authentication.

Both log files repeating in this pattern.

I've checked the clock on my server and my phone, they are perfectly in sync.

It seems a little fishy here, I turned on dynamic ports function on my server, should Shadowsocks change ports too? Shouldn't it have a static port? Or something other went wrong?

Please help, thanks a lot!

**Comment by v2ray** [comment]
First of all, dynamic port is a VMess only feature. It doesn't apply to Shadowsocks. 

2 questions regarding your issue:
1) What client do you use? ss-android?
2) From your log, TCP always works while UDP doesn't work at all, after OTA is enabled. Can you confirm that?

**Comment by Sherman-Liu** [comment]
1. Shadowsocks-Android by Max Lv, official build, 2.9.10

2. Yes, I can confirm that.

**Comment by Sherman-Liu** [comment]
Hold on a second, let me try one more time. Without computer client on.

**Comment by Sherman-Liu** [comment]
Thank god I've tested it one more time. No, there's no tcp packet working, both tcp and udp protocols were all down.

**Comment by Sherman-Liu** [comment]
The TCP connection in log before was from my computer's V2Ray client, it was a false result.

**Comment by Sherman-Liu** [comment]
I found an interesting thing, if I turn off UDP forwarding, and keep OTA turned on, it works perfectly, but if I turn on both UDP forwarding and OTA, everything stopped working, why?

**Comment by v2ray** [comment]
Fixed and released in v1.9.1

**Comment by Sherman-Liu** [comment]
![c18](https://cloud.githubusercontent.com/assets/11748513/13384723/5551bece-ded3-11e5-8fa0-89e019d4d917.jpg)

Well, there's only one thing left for me to say, you sir, ROCK!!
