### ISSUE TITLE
Unstable Problem : 'too many open files'/'All retry attempts failed'

### ISSUE THREAD

**Issue by Sherman-Liu** [v2ray/v2ray-core#99]
The day before yesterday, I upgraded the V2Ray to version 1.9, it was working fine at that time.

But on today's morning, the V2Ray became really slow and unstable, the web page I opened through V2Ray became corrupted, client showed something repeatedly like this:

2016/03/01 10:56:19 [Error]VMessOut: Failed to read VMess response (1008 bytes): EOF

And I checked error.log under /var/log/v2ray/ on my server, it showed something like this (repeating for several hundreds times, I replaced some lines for ...) :

2016/02/29 08:58:48 [Error]Freedom: Failed to open connection to tcp:***.**.**.**:443: All retry attempts failed.
...
2016/02/29 09:20:18 [Warning]Listener: Failed to accept new TCP connection: accept tcp [::]:4288: accept4: too many open files
...
2016/02/29 09:37:58 [Error]Freedom: Failed to open connection to tcp:***.**.**.**:80: All retry attempts failed.
...
2016/02/29 16:42:50 [Error]Shadowsocks: Failed to read IV: read tcp ***.**.**.**:4288->***.**.**.**:31974: i/o timeout
...
2016/03/01 02:43:16 [Warning]VMessIn: Invalid request from ***.**.**.**:47927: Invalid user.
...

Before I know V2Ray, I was using Shadowsocks, that time I knew that there were some issue like 'too many open files' gonna stuck system's I/O, but I don't understand, does V2Ray shares the same issue too?

Could I use the old way to fix it? Like this?: (https://github.com/shadowsocks/shadowsocks/wiki/Optimizing-Shadowsocks)

Would this method adapt V2Ray? Or would it do harm to V2Ray's performance?

**Comment by v2ray** [comment]
1) There are "Level" settings in both [VMess](https://www.v2ray.com/zh_cn/chapter_02/protocols/vmess.html) and [Shadowsocks](https://www.v2ray.com/zh_cn/chapter_02/protocols/shadowsocks.html) protocol. You can try setting it to 0 to close TCP connections more aggressively to avoid this problem.

2) For invalid requests like below, are these request coming from your IP? If the IPs are unknown, your VPS may be attacked. You can blocked those IPs through your firewall.
>2016/02/29 16:42:50 [Error]Shadowsocks: Failed to read IV: read tcp **...:4288->...:31974: i/o timeout
>2016/03/01 02:43:16 [Warning]VMessIn: Invalid request from **...*:47927: Invalid user.

3) Yes, the optimization for Shadowsocks also applied to V2Ray.

**Comment by Sherman-Liu** [comment]
Thanks for the help, I'll try the old way first.

BTW, could you tell me more about how 'level''s value work? It's not very clear in the manual.

**Comment by v2ray** [comment]
In general, level = 0 means the account is used by someone you don't trust, who may send malicious connection/data to your VPN; while level > 0 means the account is by someone who can be trusted.

In detail, for level = 0, when V2Ray (both VMess and Shadowsocks) reads payload in a TCP connection. It waits for 2 minutes until anything is read. If there is nothing incoming in 2 minutes, the TCP connection will be closed by the server. Otherwise, V2Ray keeps reading incoming data until client closes the connections.

For level = 1, there is no "2 minutes" timeout settings, V2Ray will wait forever and keep the connection open.

The timeout value is implementation detail, and may be changed in the future. Don't rely on the specific value.

**Comment by Sherman-Liu** [comment]
Thanks for the detail, they really clarified it  for me.

So, now in my understanding:

When level=0, the TCP connection works like normal TCP protocol, just with time-out value sets to 120 seconds.

But when level=1, the TCP connection has no "time-out", it always works in a "keep-alive" way, until client send a "close connection" packet.

Are these understandings correct?

If they were correct, would this means that when level=1, if there're something wrong with the client(which could not send out close connection packet), the server might eat up all the useable TCP connections and stuck up the network traffic, which when level=0 wouldn't act like this?

Would this suggest that level=0 is much stable than level=1? What about bandwidth performance?

There're so many new knowledge I have to learn, I'm truly sorry if I bothered you.

Please help. Thanks!

**Comment by v2ray** [comment]
Well, operation system may have a timeout setting to kill a TCP connection after a while. Some article say it is 432000 seconds (120 hours) but I am not sure about this.

Yes, level=0 is more stable for short connections. For long running connection, like websocket, the "2-minute" setting may be troublesome. There is no perfect settings in this sense. I prefer to solve your concern in a smarter way.

**Comment by Sherman-Liu** [comment]
It would be so nice if level=0 could use a custom time-out value……I think something like 300~600 seconds would be both stable & safe enough……

But anyway, thanks for the help!

Good day!

**Comment by v2ray** [comment]
Accknowledged
