### ISSUE TITLE
客户端和服务端, 无法启动

### ISSUE THREAD

**Issue by letterk** [v2ray/v2ray-core#996]
Please skip to the English section below if you don't write Chinese.

中文：
提交 Issue 之前请先阅读 [Issue 指引](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md)，然后回答下面的问题，谢谢。
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。

1)  你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
3.14
2)  你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
Chrome 通过 Socks/VMess 代理观看 YouTube 视频
3)  你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
客户端, 服务端都无法启动, 提示config, json不正确

● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2018-03-28 03:22:14 UTC; 54min ago
  Process: 3044 ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json (code=exited, status=255)
 Main PID: 3044 (code=exited, status=255)
      CPU: 13ms

Mar 28 03:22:13 vultr.guest systemd[1]: v2ray.service: Main process exited, code=exited, status=255/n/a
Mar 28 03:22:13 vultr.guest systemd[1]: v2ray.service: Unit entered failed state.
Mar 28 03:22:13 vultr.guest systemd[1]: v2ray.service: Failed with result 'exit-code'.
Mar 28 03:22:14 vultr.guest systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
Mar 28 03:22:14 vultr.guest systemd[1]: Stopped V2Ray Service.
Mar 28 03:22:14 vultr.guest systemd[1]: v2ray.service: Start request repeated too quickly.
Mar 28 03:22:14 vultr.guest systemd[1]: Failed to start V2Ray Service.
Mar 28 03:22:14 vultr.guest systemd[1]: v2ray.service: Unit entered failed state.
Mar 28 03:22:14 vultr.guest systemd[1]: v2ray.service: Failed with result 'exit-code'.

4)  你期待看到的正确表现是怎样的？
正常启动
5)  请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。
    
    服务器端配置:
```javascript
    // 在这里附上服务器端配置文件
{
    "log": {
        "access": "/var/log/v2ray/access.log",
        "error": "/var/log/v2ray/error.log",
        "loglevel": "warning"
    },
    "inbound": {
        "port": 22512,
        "protocol": "vmess",
        "settings": {
            "clients": [
                {
                    "id": "c7043546-465e-4ae5-be97-a448cb25aa68",
                    "level": 1,
                    "alterId": 64
                }
            ],
            "disableInsecureEncryption": "none"
        }
    },
    "outbound": {
        "protocol": "freedom",
        "settings": {}
    },
    "outboundDetour": [
        {
            "protocol": "blackhole",
            "settings": {},
            "tag": "blocked"
        }
    ],
    "routing": {
        "strategy": "rules",
        "settings": {
            "rules": [
                {
                    "type": "field",
                    "ip": [
                        "0.0.0.0/8",
                        "10.0.0.0/8",
                        "100.64.0.0/10",
                        "127.0.0.0/8",
                        "169.254.0.0/16",
                        "172.16.0.0/12",
                        "192.0.0.0/24",
                        "192.0.2.0/24",
                        "192.168.0.0/16",
                        "198.18.0.0/15",
                        "198.51.100.0/24",
                        "203.0.113.0/24",
                        "::1/128",
                        "fc00::/7",
                        "fe80::/10"
                    ],
                    "outboundTag": "blocked"
                }
            ]
        }
    }
}
```

    客户端配置:
```javascript
    // 在这里附上客户端配置
{
    "log": {
        "loglevel": "warning"
    },
    "inbound": {
        "port": 19252,
        "listen": "127.0.0.1",
        "protocol": "socks",
        "settings": {
            "auth": "noauth",
            "udp": false,
            "ip": "127.0.0.1"
        }
    },
    "outbound": {
        "protocol": "vmess",
        "settings": {
            "address": "***",
            "port": "22512",
            "users": [
                {
                    "id": "c7043546-465e-4ae5-be97-a448cb25aa68",
                    "alterId": 64,
                    "security": "auto",
                    "level": 1
                }
            ]
        },
        "tag": "direct"
    },
    "policy": {
        "levels": {
            "0": {
                "uplinkOnly": 0
            }
        }
    }
}
```

6)  请附上出错时软件输出的错误日志。在 Linux 中，日志通常在 `/var/log/v2ray/error.log` 文件中。

    服务器端错误日志:
无法启动无日志
    客户端错误日志:
无法启动无日志

7) 请附上访问日志。在 Linux 中，日志通常在 `/var/log/v2ray/access.log` 文件中。
无法启动无日志

8) 其它相关的配置文件（如 Nginx）和相关日志。

journalctl -u v2ray
failed to parse json config: Ext|Tools|Conf|Serial: failed to read config file > invalid character ':' after array element

**Comment by SnorlaxYum** [comment]
"disableInsecureEncryption"应该形如"disableInsecureEncryption": true这种格式，值是true或false
把"port": "22512"改成"port": 22512
要注意数字、Boolean和字符串的区别，加了引号完全不是一个东西
